Cache pathfinding results to speed up calculations
ihhub/fheroes2 pull request #1541
Opened 2020-09-05 08:53 UTC by idshibanov

Using Djikstra-style implementation. Path/distance calculation is constant after cache initialization.

2020-09-06 02:08 UTC, ihhub commented
Hi @idshibanov , is it ready for review?

2020-09-07 15:31 UTC, ihhub requested changes
Hi @idshibanov , looks great! Could you please take a look into my comments and discuss if you have any questions?

2020-09-07 15:31 UTC, ihhub commented on src/fheroes2/heroes/route.cpp
> +    swap( world.getPath( hero->GetIndex(), dst, hero->GetLevelSkill( Skill::Secondary::PATHFINDING ), false ) );
Please cache `hero->GetLevelSkill( Skill::Secondary::PATHFINDING )` into a separate variable.

2020-09-07 15:31 UTC, ihhub commented on src/fheroes2/heroes/route.cpp
> +    swap( world.getPath( hero->GetIndex(), dst, hero->GetLevelSkill( Skill::Secondary::PATHFINDING ), false ) );
Also please cache `hero->GetIndex()` as well.

2020-09-07 15:31 UTC, ihhub commented on src/fheroes2/heroes/route.cpp
> +    swap( world.getPath( hero->GetIndex(), dst, hero->GetLevelSkill( Skill::Secondary::PATHFINDING ), false ) );
Why do we need to swap? We can directly assign it as it'd be the same.

2020-09-07 15:31 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.h
> +        u16 test_value = 0;
If this member is used only for debug purposes we should put `ifdef` guard around it.

2020-09-07 15:31 UTC, ihhub commented on src/fheroes2/world/world.h
> +    bool isTileUnderProtection( int to, int dst );
Could we make this method `const`?

2020-09-07 15:31 UTC, ihhub commented on src/fheroes2/world/world_pathfinding.cpp
> +        path.push_front( { node._from, Direction::Get( node._from, currentNode ), cost - node._cost } );
Please use `emplace_front` instead to avoid object copy.

2020-09-07 15:31 UTC, ihhub commented on src/fheroes2/world/world_pathfinding.cpp
> +bool Pathfinder::reEvaluateIfNeeded( int from, uint8_t skill, int destination )
We do not check the return value of this function anywhere.

2020-09-07 15:31 UTC, ihhub commented on src/fheroes2/world/world_pathfinding.cpp
> +        // bool protectedTile = !( _cache[currentNodeIdx]._from != -1 && !Maps::GetTilesUnderProtection( _cache[currentNodeIdx]._from ).empty() );
Do we need this commented code?

2020-09-07 15:31 UTC, ihhub commented on src/fheroes2/world/world_pathfinding.cpp
> +    while ( lastProcessedNode != nodesToExplore.size() ) {
We can combine these and line 197 into normal `for ( size_t lastProcessedNode = 0; lastProcessedNode < nodesToExplore.size(); ++lastProcessedNode)` loop.

2020-09-07 15:31 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.cpp
>              }
Is this code used only in debug mode? If yes please guard it by `ifdef`.

2020-09-07 15:31 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.h
> +        u16 test_value = 0;
Let's name it to something more meaningful like `moveCost`.

2020-09-07 15:31 UTC, ihhub commented on src/fheroes2/world/world_pathfinding.cpp
> +                    uint32_t moveCost = _cache[currentNodeIdx]._cost + getMovementPenalty( currentNodeIdx, newIndex, *it, skill );
Please make this variable `const`.

2020-09-07 15:31 UTC, ihhub commented on src/fheroes2/world/world_pathfinding.cpp
> +                        newTile.test_value = moveCost;
If we use test_value only in debug mode please put `ifdef` guard to avoid extra calculations in release mode :)

2020-09-07 15:31 UTC, ihhub commented on src/fheroes2/heroes/route.cpp
> +    swap( world.getPath( hero->GetIndex(), dst, hero->GetLevelSkill( Skill::Secondary::PATHFINDING ), false ) );
g++ is unhappy about swap as well:
```
../fheroes2/heroes/route.cpp:127:11: error: non-const lvalue reference to type 'list<...>' cannot bind to a temporary of type 'list<...>'
    swap( world.getPath( hero->GetIndex(), dst, hero->GetLevelSkill( Skill::Secondary::PATHFINDING ), false ) );
```

2020-09-07 17:49 UTC, idshibanov commented on src/fheroes2/world/world_pathfinding.cpp
> +                        newTile.test_value = moveCost;
I will remove this test value once I chase down the last bug.

2020-09-08 03:34 UTC, idshibanov commented
> 
> Hi @idshibanov , is it ready for review?

It is ready now. Removed the old and debugging code as well.

2020-09-08 14:54 UTC, ihhub requested changes
Hi @idshibanov , I left just one comment. Could you please take a look into it?

2020-09-08 14:54 UTC, ihhub commented on src/fheroes2/world/world_pathfinding.cpp
> +void Pathfinder::evaluateMap( int start, uint8_t skill, int destination )
`destination` input parameter is not used anywhere. Do we need it?

2020-09-08 15:21 UTC, idshibanov commented on src/fheroes2/world/world_pathfinding.cpp
> +void Pathfinder::evaluateMap( int start, uint8_t skill, int destination )
No, we don't anymore. I will remove.

2020-09-08 16:04 UTC, ihhub commented
Hi @idshibanov , I tested the changes. I can see a noticeable delay when I switch to a hero which can walk for a long distance. I'm just curious: can we make a usage of distance in this case? For example, once we switch to a hero we calculate every possible path based on a current area to show, then we add more and more points when we try to calculate longer distance... I'm just curious. From what I see in the code most likely it's not possible.

2020-09-08 16:19 UTC, idshibanov commented
> 
> 
> Hi @idshibanov , I tested the changes. I can see a noticeable delay when I switch to a hero which can walk for a long distance. I'm just curious: can we make a usage of distance in this case? For example, once we switch to a hero we calculate every possible path based on a current area to show, then we add more and more points when we try to calculate longer distance... I'm just curious. From what I see in the code most likely it's not possible.

Before the change amount of move points directly affected the distance and slowness of the algorithm. Right now, it calculates everything which was reasonably fast in my tests.

I can limit amount of max iterations. I think once road check will be replaced with the boolean speed of calculation will improve dramatically.

2020-09-09 09:33 UTC, merged

2020-09-09 09:33 UTC, ihhub commented
Hi @idshibanov , thanks a lot for your valuable contribution to the project!