Update dialog_thievesguild.cpp
ihhub/fheroes2 pull request #1612
Opened 2020-09-09 13:32 UTC by Aditya-Srivastav

Fixed text in bar and Columns in Adventure Map 
#1590 #1593

2020-09-13 05:01 UTC, ihhub requested changes
Hi @Aditya-Srivastav, could you please take a look into given comment?

2020-09-13 08:12 UTC, Aditya-Srivastav commented on src/fheroes2/dialog/dialog_thievesguild.cpp
> +    text.Set( _( "Shrine ~ Player RanKings" ), Font::BIG );
As I am unfamiliar with the game.
I was able to run the game but could not reach the window in the issue.
Therefore I could not test the #1593.
I will fix #1590 for now.

2020-09-13 08:16 UTC, ihhub commented on src/fheroes2/dialog/dialog_thievesguild.cpp
> +    text.Set( _( "Shrine ~ Player RanKings" ), Font::BIG );
You can create separate pull request for #1593. It's good if we have one pull request per issue so it's easy to track changes :)

2020-10-18 04:35 UTC, ihhub commented
Hi @4D17Y4 could you please tell us whether you're going to complete this pull request?

2020-10-21 15:01 UTC, ihhub commented
Closing this pull request as it needs a rework and the author is not going to work on it :(

2020-10-21 15:01 UTC, closed without merging