Redo 7z search
ihhub/fheroes2 pull request #1615
Opened 2020-09-09 21:45 UTC by ticolensic

2020-09-09 21:48 UTC, ticolensic commented
I came across a strange bug, which happened the first time I ran it in cmd. After I reopened cmd and ran it, it disappeared. It tried to run "(x86)\7-Zip\7z.exe" which is obviously the lack of quotes. But it downloaded a couple of files already. Moreover, it doesn't return back to the folder it was run from.

So I propose these changes:

 1. add the quotes
 2. fail fast
 3. return to previous folder

2020-09-10 01:23 UTC, ihhub requested changes
Hi @ticolensic , thanks for changes! Could you please take a look into given comments? We also can't do fast fail if 7-zip is not install in the system as people could use other archivers.

2020-09-10 01:23 UTC, ihhub commented on script/windows/install_packages.bat
> +    echo "Failed to unzip archives because 7-zip is not installed in system. Please unpack all archives in packages internal folders and manually run setup_packages.bat file after"
This message is invalid as we don't download anything before.

2020-09-10 01:23 UTC, ihhub commented on script/windows/install_packages.bat
> +echo %sevenZipPath%
Do we need to output this for end user?

2020-09-10 01:23 UTC, ihhub commented on script/windows/install_packages.bat
> +for /f "delims=" %%i in ('"where 7z.exe > nul"') do set sevenZipPath=%%i
Please put 7-zip checks after package downloading. Right now we're forcing user to have 7-zip on his machine which is incorrect.

2020-10-04 03:18 UTC, ihhub commented
Closing this pull request as the author hasn't replied for many weeks.

2020-10-04 03:18 UTC, closed without merging