PlayStation Vita port
ihhub/fheroes2 pull request #1616
Opened 2020-09-09 22:06 UTC by Northfear

Not sure if anything can be used from this port, but any advices that could help me to maintain it are welcome (I'm not really a C++ dev).
Stuff that I would add to the main tree:
1. Changes in src/Makefile. "export CC" is required for libsmacker. Applying SDL_FLAGS after platform includes is pretty handy too (in case any of the platform might need to override it).
2. Surface creation code with RGBA masks.

2020-09-10 01:46 UTC, ihhub requested changes
Hi @Northfear , I left few comments. I hope there are helpful for your project ;)

2020-09-10 01:46 UTC, ihhub commented on src/engine/screen.h
> +#ifdef VITA
This is an incorrect place. Base class must be independent from SDL.

2020-09-10 01:46 UTC, ihhub commented on src/engine/screen.cpp
> +                resolutionSet.insert( std::make_pair( 960, 544 ) );
For your case please define a variable to store these value. No hardcoded values please :)

2020-09-10 01:46 UTC, ihhub commented on src/engine/screen.cpp
> +                resolutionSet.insert( std::make_pair( 640, 480 ) );
Please use DEFAULT_WIDTH and DEFAULT_HEIGHT.

2020-09-10 01:46 UTC, ihhub commented on src/engine/screen.cpp
> +            if ( width_ != 960 || height_ != 544 ) {
Please use not hardcoded values but define variables for them.

2020-09-10 01:46 UTC, ihhub commented on src/engine/screen.cpp
> +#ifdef VITA
I think the best way would be to derive a child class from this one and override needed functions so the code will look much cleaner.

2020-09-10 01:46 UTC, ihhub commented on src/engine/localevent.h
> +    bool vita_input_active = false;
Please use camelCase variable naming.

2020-09-10 01:46 UTC, ihhub commented on src/engine/localevent.h
> +    Sint16 xaxisl_value = 0;
Please use STL standard: `int16_t`

2020-09-10 01:46 UTC, ihhub commented on src/engine/localevent.cpp
> +    SDL_Rect vitaDestRect = fheroes2::Display::instance().engine()->vitaDestRect;
This is definitely not a correct way to retrieve members from a class.

2020-09-10 01:46 UTC, ihhub commented on src/engine/localevent.cpp
> +    int32_t w = 960;
Please don't use hardcoded values.

2020-09-10 01:46 UTC, ihhub commented on src/engine/localevent.cpp
> +    if ( xaxis_float > fheroes2::Display::instance().width() )
Please cache `fheroes2::Display::instance()`

2020-09-10 01:46 UTC, ihhub commented on src/engine/localevent.cpp
> +    xaxis_float += ( ( pow( abs( xaxisl_value ), 1.03f ) * ( xaxisl_value / abs( xaxisl_value ) ) * deltaTime ) / movementSpeed ) * settingsSpeedMod;
These are magic values. We need a proper variable or explanation.

2020-09-10 01:46 UTC, ihhub commented on src/engine/screen.cpp
> +                        if ( ( 960.0 / 544.0 ) >= ( (float)width_ / height_ ) ) {
Please use only C++ casting.

2020-09-10 01:46 UTC, ihhub commented on src/engine/tools.cpp
> +    return c;
Combine these 2 lines.

2020-09-10 01:46 UTC, ihhub commented on src/engine/tools.cpp
> +            pos--;
Please use pre-increment form.

2020-09-10 01:46 UTC, ihhub commented on src/fheroes2/game/fheroes2.cpp
> +int _newlib_heap_size_user = 192 * 1024 * 1024;
This variable is not used anywhere.

2020-09-10 01:46 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +        vita_keep_aspect_ratio = config.IntParams( "vita_keep_aspect_ratio" );
This parameter we will re-implement again in the future.

2020-09-11 15:20 UTC, ihhub commented on README.md
> +
Here should be a description what is this project about. Something like "This is a PlayStation Vita port of fheroes2[link to this ihhub main page] project." So people won't be confused about the project as well as we'll have a correct differentiation.

2020-10-21 15:05 UTC, ihhub commented
Hi @Northfear you have some merge conflicts with your code. I think we're changing the code too fast :)

2020-10-21 19:41 UTC, Northfear commented
@ihhub Nah, everything is pretty chill nowadays, just some minor stuff that I haven't pushed yet. Refactorings just after 0.8 were painful on the other hand. Something was breaking every few days.

2020-10-25 10:57 UTC, ihhub commented on src/Makefile
> -CFLAGS := $(SDL_FLAGS) $(CFLAGS)
Do we need this change?

2020-10-25 11:08 UTC, ihhub commented on src/engine/screen.cpp
> +#include <SDL.h>
Why do we need this change?

2020-10-25 11:09 UTC, ihhub commented on src/engine/system.cpp
> +#ifdef VITA
Put it before std::string and just directly return the string without assignment.

2020-10-25 11:11 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +    std::string vita_filename = "ux0:data/fheroes2/" + filename;
This variable could be const.

2020-10-25 11:12 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +        if ( vita_pointer_speed < 0 )
else if is faster.

2020-10-25 11:14 UTC, ihhub commented on src/engine/tools.cpp
> +        char c = GetCurrentVitaChar();
This variable could be const.

2020-10-25 11:15 UTC, ihhub commented on src/engine/tools.cpp
> +        char c = GetCurrentVitaChar();
The same for other cases.

2020-10-25 11:19 UTC, ihhub commented on src/engine/screen.h
> +        virtual void SetVitaKeepAspectRatio( bool keepAspect ) {};
This is an error. These functions must return something.

2020-10-25 11:32 UTC, ihhub commented on .gitignore
> +.vscode
Please revert it. Vscode is added at line 48.

2020-10-25 11:35 UTC, ihhub commented on src/engine/localevent.cpp
> +            w *= ( static_cast<float>( fheroes2::Display::VITA_FULLSCREEN_WIDTH ) / vitaDestRect.width );
This is a compilation warning.

2020-10-25 13:30 UTC, ihhub commented on src/engine/dir.cpp
> +            std::string filename( dir.d_name );
This variable could be `const`.

2020-10-25 13:31 UTC, ihhub commented on src/engine/localevent.cpp
> +        return;
This check should be at the very beginning of the function.

2020-10-25 13:32 UTC, ihhub commented on src/engine/localevent.cpp
> +        yAxisFloat = display.height();
```
    if ( xAxisFloat < 0 )
        xAxisFloat = 0;
    else if ( xAxisFloat > display.width() )
        xAxisFloat = display.width();

    if ( yAxisFloat < 0 )
        yAxisFloat = 0;
    else if ( yAxisFloat > display.height() )
        yAxisFloat = display.height();
```
is faster.

2020-10-25 13:35 UTC, ihhub commented on src/engine/screen.cpp
> +        bool vitaKeepAspectRatio;
No need an explicit naming of vita as the class name contains the same name.

2020-10-25 13:36 UTC, ihhub commented on src/engine/screen.h
> +        virtual void SetVitaKeepAspectRatio( bool keepAspect ) {};
Also no need ; at the end.

2020-10-25 13:37 UTC, ihhub commented on src/engine/tools.cpp
> +KeySym vitaKeys[TOTAL_CHARACTERS_VITA] = {
This array should be `const`

2020-10-25 13:39 UTC, ihhub commented on src/engine/tools.cpp
> +    KeySym keySym = KeySymFromChar( current_char );
Why don't we have a map instead of vector so the complexity of searching the character will be O(log(TOTAL_CHARACTERS_VITA)) and also we should store not the index but the real value.

2020-10-25 13:39 UTC, ihhub commented on src/engine/tools.cpp
> +    return CharFromKeySym( vitaKeys[currentCharIndex], currentUpper ? MOD_CAPS : MOD_NONE );;
Double ; at the end.

2020-10-25 13:40 UTC, ihhub commented on src/engine/tools.cpp
> +    KeySym keySym = KeySymFromChar( current_char );
Ah, I get it. It's because of the increasing index.

2020-10-25 13:42 UTC, ihhub commented on src/fheroes2/game/fheroes2.cpp
> +int _newlib_heap_size_user = 192 * 1024 * 1024;
This variable needs an explanation comment in terms on Vita SDK.

2020-10-30 18:46 UTC, Northfear commented on src/Makefile
> -CFLAGS := $(SDL_FLAGS) $(CFLAGS)
That was the cleanest way to deal wit hit.
`$(shell sdl2-config --libs)` is not an option for a lot of platforms, and littering whole Makefile with lots of ifdefs is messy, so moving final CFLAGS assignment after platform-specific Makefiles seemed like the cleanest solution.

2020-10-30 19:08 UTC, Northfear commented on src/engine/screen.cpp
> +#include <SDL.h>
It's required for linear filtering during fullscreen scaling (if the game is not at native resolution).
`SDL_SetHint( SDL_HINT_RENDER_SCALE_QUALITY, "linear" );`

2020-10-30 19:30 UTC, Northfear commented on src/engine/localevent.cpp
> +        return;
Cursor speed on the 1st frame after idling will be totally broken in that case (deltaTime will be massive, since lastTime wasn't updated last frame).
```
    uint32_t currentTime = SDL_GetTicks();
    float deltaTime = currentTime - lastTime;
    lastTime = currentTime;
```

2020-10-30 20:27 UTC, Northfear commented on src/engine/localevent.cpp
> +            w *= ( static_cast<float>( fheroes2::Display::VITA_FULLSCREEN_WIDTH ) / vitaDestRect.width );
Should I do static casts on all Wconversion warnings? There's quite a lot of them

2020-11-04 16:41 UTC, ihhub commented on src/engine/screen.cpp
> +            memcpy_neon( palettedTexturePointer, display.image(), width * height * sizeof( uint8_t ) );
Why do we need to copy the buffer if we can do the same way like it's done for SDL1 8-bit images?

2020-11-04 16:47 UTC, Northfear commented on src/engine/screen.cpp
> +            memcpy_neon( palettedTexturePointer, display.image(), width * height * sizeof( uint8_t ) );
@ihhub you mean like using _renderSurface directly instead of palettedTexturePointer?
I've tried that, but performance was pretty bad this way. I suspect that there were some ram->vram transfers on each _renderSurface change, so memcpy each frame ended up being the fastest so far (~36fps on world map right now)

2020-11-05 03:21 UTC, ihhub commented on src/engine/screen.cpp
> +            memcpy_neon( palettedTexturePointer, display.image(), width * height * sizeof( uint8_t ) );
I mean that we replaced a pointer to `_image` member inside Display class by a pointer to an array from SDL for SDL 1 implementation.

Is 36 FPS for full resolution? What was the previous value?

2020-11-05 16:35 UTC, Northfear commented on src/engine/screen.cpp
> +            memcpy_neon( palettedTexturePointer, display.image(), width * height * sizeof( uint8_t ) );
With `linkRenderSurface`, right? Yeah, I've tried that. <10fps. I think palettedTexturePointer points to video mem or something like that, so direct manipulations aren't really fast.
The previous value was 18fps (15 before your optimizations), but I think it can actually handle even more than 30fps, since scrolling map AND moving cursor produces 60fps (and scrolling feels way smoother. I should probably double check the code).

2020-11-05 17:30 UTC, Northfear commented on src/engine/screen.cpp
> +            memcpy_neon( palettedTexturePointer, display.image(), width * height * sizeof( uint8_t ) );
Yup. Can definitely handle more. It's probably a good idea to introduce some kind of more global redraw requirement var, since map scrolling doesn't affect colorCycling.isRedrawRequired() and there's no redraws until it's fired for me (scroll feels a bit choppy at ~50fps on PC for me)

2021-01-03 14:36 UTC, ihhub commented
Hi @Northfear , could you please rebase your branch from master amd fix merging conflicts? We will see what we can do next to standartise the code for Vita.

2021-01-13 13:43 UTC, ihhub commented
Hi @Northfear , could you please update this pull request? We will have much smaller changes here :)

2021-01-14 13:26 UTC, ihhub commented on src/Makefile.vita
> +ifdef WITH_SDL2
Please update this as we dropped such flag

2021-01-17 14:23 UTC, ihhub commented on src/fheroes2/agg/bin_info.cpp
> +        const std::vector<float> & angles = projectileAngles;
I think this change is not needed.

2021-01-17 14:24 UTC, ihhub commented on src/fheroes2/agg/bin_info.h
> +        std::vector<float> projectileAngles;
I think this change is not needed.

2021-01-17 14:24 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +    const std::string vita_filename = "ux0:data/fheroes2/" + filename;
Please use camelCase variable naming.

2021-01-17 14:25 UTC, ihhub commented on src/fheroes2/system/settings.h
> +    int vita_keep_aspect_ratio;
Initialization of this variable is missing in constructor.

2021-01-17 14:26 UTC, ihhub commented on src/engine/screen.cpp
> +            palettedTexturePointer = (uint8_t *)vita2d_texture_get_datap( texBuffer );
Please always use C++ casting over C-style.

2021-01-17 14:26 UTC, ihhub commented on src/engine/screen.cpp
> +            SDL_memset( palettedTexturePointer, '\0', width_ * height_ * sizeof( uint8_t ) );
Replace `'\0'` by 0.

2021-01-17 14:27 UTC, ihhub commented on src/engine/screen.cpp
> +            SDL_memset( palettedTexturePointer, '\0', width_ * height_ * sizeof( uint8_t ) );
Is there a reason why `SDL_memset` is used over `memset`?

2021-01-17 17:00 UTC, Northfear commented on src/fheroes2/agg/bin_info.cpp
> +        const std::vector<float> & angles = projectileAngles;
It's shouldn't be needed. But in practice everything just crashes at `AnimationReference` constructor on init. Probably due to some problem in toolchain.. which is kinda weird, considering that double is not a thing with NEON and armv7 anyway.

2021-01-19 00:54 UTC, ihhub commented on src/fheroes2/agg/bin_info.cpp
> +        const std::vector<float> & angles = projectileAngles;
What's the description of crash?

2021-01-27 11:53 UTC, ihhub commented on src/engine/tools.cpp
> +    KeySym keySym = KeySymFromChar( current_char );
Please make this variable const.

2021-01-27 11:54 UTC, ihhub commented on src/fheroes2/agg/bin_info.cpp
> +        const std::vector<float> & angles = projectileAngles;
Orange Pi crashes as well. Is it the only place for it for the crash fix?

2021-01-27 12:55 UTC, Northfear commented on src/fheroes2/agg/bin_info.cpp
> +        const std::vector<float> & angles = projectileAngles;
@ihhub yeah, that's the only one for me (crashes on init)

2021-01-31 04:43 UTC, ihhub commented on src/fheroes2/agg/bin_info.cpp
> +        const std::vector<float> & angles = projectileAngles;
Please update it as the fix is in master branch.

2021-01-31 04:44 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +    if ( config.Exists( "vita_keep_aspect_ratio" ) ) {
Please take a look into `GLOBAL_KEEP_ASPECT_RATIO` option. I think this is exactly what you need.

2021-01-31 04:45 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +#ifdef VITA
Most likely will go while using `GLOBAL_KEEP_ASPECT_RATIO`.

2021-01-31 04:46 UTC, ihhub commented on src/engine/screen.h
> +        virtual void SetVitaKeepAspectRatio( bool ) {}
Please name it more generic like `keepAspectRatio`.

2021-01-31 04:46 UTC, ihhub commented on src/engine/screen.h
> +        virtual void SetVitaKeepAspectRatio( bool ) {}
Since we made similar changes to SDL2 could you please check if it's even needed for SDL 2?

2021-02-02 16:13 UTC, ihhub requested changes

2021-02-02 16:13 UTC, ihhub commented on src/engine/screen.cpp
> +            _surface = SDL_CreateRGBSurface( 0, width_, height_, 32, 0x000000ff, 0x0000ff00, 0x00ff0000, 0xff000000 );
The surface is not used anywhere. Do we need to even use it?

2021-02-02 16:13 UTC, ihhub commented on src/engine/screen.cpp
> +            memcpy( vita2d_texture_get_palette( texBuffer ), _palette32Bit.data(), sizeof( uint32_t ) * 256 );
We do the same copy in `_createPalette` method.

2021-02-02 16:13 UTC, ihhub commented on src/engine/screen.cpp
> +            memcpy( vita2d_texture_get_palette( texBuffer ), _palette32Bit.data(), sizeof( uint32_t ) * 256 );
Should we then move `_createPalette` call after initialization of textBuffer?

2021-02-02 16:13 UTC, ihhub commented on src/engine/screen.cpp
> +        uint8_t * palettedTexturePointer = nullptr;
Please name class members starting with '_' character.

2021-02-02 16:13 UTC, ihhub commented on src/engine/screen.cpp
> +            fheroes2::Rect rect;
Shouldn't we just store `fheroes2::Rect` object within the class then **SDL_Rect**?

2021-02-02 16:13 UTC, ihhub commented on src/engine/screen.cpp
> +        enum
Constructor is missing. It should be declared.

2021-02-02 16:13 UTC, ihhub commented on src/engine/screen.cpp
> +        std::vector<uint32_t> _palette32Bit;
Please make the base class members to be protected then you could use them without duplicate creation.

2021-02-02 16:13 UTC, ihhub commented on src/engine/localevent.h
> +    void DPadTextInputActive( bool active )
Please rename it into `setDPadTextInputStatus( const bool active )`.

2021-02-02 16:13 UTC, ihhub commented on src/engine/localevent.cpp
> +            res.push_back( c );
Please use `emplace_back` instead.

2021-02-02 16:13 UTC, ihhub commented on src/engine/localevent.cpp
> +#if defined( FHEROES2_VITA )
Please put all new code under unnamed namespace at the top of this file.

2021-02-02 16:13 UTC, ihhub commented on src/engine/screen.cpp
> +            return resolution;
`return fheroes2::Size( VITA_FULLSCREEN_WIDTH, VITA_FULLSCREEN_HEIGHT );` will be faster.

2021-02-02 16:13 UTC, ihhub commented on src/engine/screen.cpp
> +                filteredResolutions.push_back( std::make_pair( VITA_FULLSCREEN_WIDTH, VITA_FULLSCREEN_HEIGHT ) );
Please use `emplace_back` without **std::make_pair**. It is a faster approach.

2021-02-02 16:33 UTC, Northfear commented on src/engine/screen.cpp
> +            _surface = SDL_CreateRGBSurface( 0, width_, height_, 32, 0x000000ff, 0x0000ff00, 0x00ff0000, 0xff000000 );
Surface is kinda useless, but It's still used during palette generation
`_palette32Bit[i] = SDL_MapRGBA( _surface->format, *( value ), *( value + 1 ), *( value + 2 ), 255 );`

2021-02-02 17:01 UTC, Northfear commented on src/engine/localevent.cpp
> +            res.push_back( c );
res is std::string, so there's no emplace_back

2021-02-11 09:35 UTC, ihhub requested changes
Hi @Northfear , I left multiple comments here. Could you please take a look? Essentially all Vita related code must be within `engine` directory.

2021-02-11 09:35 UTC, ihhub commented on src/engine/dir.cpp
> +    int uid = sceIoDopen( path.c_str() );
Please make `const`.

2021-02-11 09:35 UTC, ihhub commented on src/engine/dir.cpp
> +        if ( filter.size() ) {
Please use `!filter.empty()` instead.

2021-02-11 09:35 UTC, ihhub commented on src/engine/dir.cpp
> +        push_back( fullname );
Please make `fullname` non-const and replace this line by `emplace_back( std::move( fullname ) );` . In this case we won't copy the variable.

2021-02-11 09:35 UTC, ihhub commented on src/engine/dir.cpp
> +                if ( std::string::npos == StringLower( filename ).find( StringLower( filter ) ) )
Please combine these 2 lines.

2021-02-11 09:35 UTC, ihhub commented on src/engine/localevent.cpp
> +    if ( res.size() ) {
Please use `!res.empty()` instead.

2021-02-11 09:35 UTC, ihhub commented on src/engine/localevent.cpp
> +        currentUpper = ( res.size() == 0 );
`currentUpper = res.empty();`

2021-02-11 09:35 UTC, ihhub commented on src/engine/screen.cpp
> +            _surface = SDL_CreateRGBSurface( 0, width_, height_, 32, 0x000000ff, 0x0000ff00, 0x00ff0000, 0xff000000 );
Then we have to remove it and `_palette32Bit` related code within this class.

2021-02-11 09:35 UTC, ihhub commented on src/engine/screen.cpp
> -        std::vector<uint32_t> _palette32Bit;
Please revert this change.

2021-02-11 09:35 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +    le.SetDPadTextInputStatus( true );
Let's create a methods called `openVirtualKeyboard` and `closeVirtualKeyboard` and put this logic inside them. I think the code will be much cleaner.

2021-02-11 09:35 UTC, ihhub commented on src/fheroes2/game/fheroes2.cpp
> +#endif
This is not a place to hardware specific stuff. Let's put it somewhere within `engine` directory, like in `engine.h` and `engine.cpp` file. We could call the function `void initHardware()` which will do this code.

2021-02-11 09:35 UTC, ihhub commented on src/fheroes2/game/fheroes2.cpp
> +#endif
Let's create `void closeHardware()` function in `engine.h` for this purpose. Also please add a comment stating that this is a function for actions specific to some platforms.

2021-02-11 09:35 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +        _controllerPointerSpeed = config.IntParams( "controller pointer speed" );
Could you please create a separate pull request for this change?

2021-02-11 09:35 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +#endif
Could you please create a function in `dir.h` under fheroes2 namespace called `void addOSSpecificDirectories( ListDirs &dirs )` where we put this logic inside?

2021-02-11 09:35 UTC, ihhub commented on src/engine/system.h
> +#elif defined( FHEROES2_VITA )
This code will require a change with #2760 pull request.

2021-02-11 09:35 UTC, ihhub commented on src/engine/screen.cpp
> +            if ( _window != nullptr ) {
We could call the method of the base class to cleanup all the members from it and here only leave the code related to members of this class.

2021-02-11 09:35 UTC, ihhub commented on src/engine/screen.cpp
> +            // linkRenderSurface( _palettedTexturePointer );
Please remove this commented line if we don't use it.

2021-02-11 09:35 UTC, ihhub commented on src/engine/screen.cpp
> +                        float scale = static_cast<float>( VITA_FULLSCREEN_HEIGHT ) / height_;
Please make this variable `const`.

2021-02-11 09:35 UTC, ihhub commented on src/engine/screen.cpp
> +                        float scale = static_cast<float>( VITA_FULLSCREEN_WIDTH ) / width_;
Please make this variable `const`.

2021-02-11 09:35 UTC, ihhub commented on src/engine/endian_h2.h
> +#elif defined( FHEROES2_VITA )
Please make a separate pull request for this file as we changed the same for Switch.

2021-02-16 16:55 UTC, Northfear commented on src/engine/screen.cpp
> +            if ( _window != nullptr ) {
@ihhub `fheroes2::BaseRenderEngine` is the base class of `VitaRenderEngine`, so there's nothing to cleanup in it really. Or an I missing something?

2021-03-02 13:25 UTC, ihhub requested changes
Hi @Northfear , I made multiple suggestions and corrections. Could you please take a look? Also please remove empty images as well.

2021-03-02 13:25 UTC, ihhub commented on Makefile.dolce
> +PROJECT_TITLE := Free Heroes 2
Please name it as `Free Heroes of Might & Magic II`.

2021-03-02 13:25 UTC, ihhub commented on Makefile.dolce
> +		--add platforms/vita/sce_sys/livearea/contents/template.xml sce_sys/livearea/contents/template.xml \
Please use `files/images/platform/pvs` directory instead.

2021-03-02 13:25 UTC, ihhub commented on Makefile.dolce
> +		--add files/fonts/smallfonts.ttf files/fonts/smallfonts.ttf \
Please remove these files. We don't use them for now.

2021-03-02 13:25 UTC, ihhub commented on Makefile.vita
> +PROJECT_TITLE := Free Heroes 2
Please name it as `Free Heroes of Might & Magic II`.

2021-03-02 13:25 UTC, ihhub commented on Makefile.vita
> +		--add platforms/vita/sce_sys/livearea/contents/template.xml=sce_sys/livearea/contents/template.xml \
Please use `files/images/platform/pvs` directory instead.

2021-03-02 13:25 UTC, ihhub commented on Makefile.vita
> +		--add files/fonts/smallfonts.ttf=files/fonts/smallfonts.ttf \
Please remove inclusion of these files. We don't use them.

2021-03-02 13:25 UTC, ihhub commented on README.md
> +# PlayStation Vita port of [fheroes2](https://github.com/ihhub/fheroes2) project
Please create a new file called `README_PSV.md` under `doc` directory and move all information there. Since PSV is a very specific platform we just add a link to a new files in the main readme.

2021-03-02 13:25 UTC, ihhub commented on platforms/vita/sce_sys/livearea/contents/template.xml
> +<?xml version="1.0" encoding="utf-8"?>
Please move this file to `files/images/platform/psv` directory.

2021-03-02 13:25 UTC, ihhub commented on src/engine/dir.cpp
> +        dirs.push_back( "ux0:data/fheroes2" );
Please use `emplace_back` instead.

2021-03-02 13:25 UTC, ihhub commented on src/Makefile.dolce
> +CFLAGS := $(CFLAGS) -DFHEROES2_VITA -I$(DOLCESDK)/arm-dolce-eabi/include -Ofast -mcpu=cortex-a9 -mfpu=neon -ftree-vectorize -fgraphite-identity -floop-nest-optimize -fno-lto
Please use `-03` flag as we have floating point calculations.

2021-03-02 13:25 UTC, ihhub commented on src/Makefile.vita
> +CFLAGS := $(CFLAGS) -DFHEROES2_VITA -DUSE_VITASDK -I$(VITASDK)/arm-vita-eabi/include -Ofast -mcpu=cortex-a9 -mfpu=neon -ftree-vectorize -fgraphite-identity -floop-nest-optimize -fno-lto
Please use `-03` flag as we have floating point calculations.

2021-03-02 13:25 UTC, ihhub commented on src/Makefile.vita
> +AR := arm-vita-eabi-gcc-ar
The only difference between these 2 makefiles is a path. Why don't we make another variable and use it in a single makefile?

2021-03-02 13:25 UTC, ihhub commented on src/Makefile.vita
> +AR := arm-vita-eabi-gcc-ar
We actually already know this based on `DOLCESDK` and `VITASDK` so why don't we check this variable and set another one for the path?

2021-03-02 13:25 UTC, ihhub commented on README.md
> +# PlayStation Vita port of [fheroes2](https://github.com/ihhub/fheroes2) project
Moreover, the best way to avoid long descriptions is to just create a helper script. I can help with this if needed.

2021-03-22 15:10 UTC, ihhub requested changes
Hi @Northfear , I left few comments here. Would you mind take a look?

2021-03-22 15:10 UTC, ihhub commented on src/engine/localevent.h
> +    const uint64_t TOUCH_RMB_DELAY = 750;
This is not obvious what RMB stands for. Could you please explain?

2021-03-22 15:10 UTC, ihhub commented on src/engine/localevent.cpp
> +void LocalEvent::TouchpadRMBEmulation()
Does this method work only on Vita? If yes we should guard it with if-def.

2021-03-26 19:19 UTC, Northfear commented on src/engine/localevent.h
> +    const uint64_t TOUCH_RMB_DELAY = 750;
Right mouse button. I've tried H3 on Android recently and liked how rmb emulation worked there, so I was playing around with the same idea

2021-03-26 19:30 UTC, Northfear commented on src/engine/localevent.cpp
> +void LocalEvent::TouchpadRMBEmulation()
Should work on any touchpad. Still needs some more testing tho.

2021-03-29 14:06 UTC, ihhub commented
Hi @Northfear , could you please take a look why the compilation is failing as previously it was passing?

2021-03-29 14:21 UTC, Northfear commented
That's because of these two lines in Makefile.vita
```
CFLAGS_TP := $(CFLAGS)
CXXFLAGS_TP := $(CXXFLAGS)
```
In general Makefile CFLAGS are assigned to CFLAGS_TP before all of the warning flags.
Is there even a need for Third party CFLAGS?

2021-03-29 14:33 UTC, ihhub commented
> That's because of these two lines in Makefile.vita
> 
> ```
> CFLAGS_TP := $(CFLAGS)
> CXXFLAGS_TP := $(CXXFLAGS)
> ```
> 
> In general Makefile CFLAGS are assigned to CFLAGS_TP before all of the warning flags.
> Is there even a need for Third party CFLAGS?

Anyway, I fixed it :)

2021-03-29 14:41 UTC, ihhub commented
@Northfear , it fails right now by another compilation error: https://travis-ci.org/github/ihhub/fheroes2/jobs/764866478
Logically it shouldn't.

2021-03-29 14:48 UTC, Northfear commented
@ihhub yeah, I know about this one. I've no idea why it's considering something like `0xA4` as 2 bytes, but I'm pretty sure it has something to do with CFLAGS.
I'll check it out in a bit..

2021-03-29 14:57 UTC, ihhub requested changes
Hi @Northfear , I also left few comments here. Once you fix the compilation and address these comments we're good to go :)

2021-03-29 14:57 UTC, ihhub commented on doc/README_PSV.md
> +Music files in OGG format (from GoG release of the game) should be placed into the "ux0:data/fheroes2/music/" folder. To enable OGG music set "music = external" option in "ux0:data/fheroes2/fheroes2.
Does Vita support configuration file saving? If yes we should remove the second sentence as such option is enabled in the game.

2021-03-29 14:57 UTC, ihhub commented on doc/README_PSV.md
> +[rePatch reDux0](https://github.com/dots-tb/rePatch-reDux0) OR [FdFix](https://github.com/TheOfficialFloW/FdFix) plugin is required for proper suspend/resume support (only use one at a time).
It is not clear what these tools for. Suspend/resume of the system?

2021-03-29 14:57 UTC, ihhub commented on src/engine/localevent.h
> +    const float TOUCH_RMB_DEADZONE = 0.01F;
Could we please revert these changes for RMB? I think it's not that essential to have them for now and we could find more elegant way to do it? Since the rest of the code is already reviewed reverting this one might help to finish this pull request faster.

2021-03-29 14:57 UTC, ihhub commented on src/engine/localevent.h
> +    const float TOUCH_RMB_DEADZONE = 0.01F;
We had some emulation touch code before as it was very similar to this.

2021-03-29 14:57 UTC, ihhub commented on src/Makefile.vita
> +AR := arm-vita-eabi-gcc-ar
Please add this header to the file as per our new standards:
```
###########################################################################
#   Free Heroes of Might and Magic II: https://github.com/ihhub/fheroes2  #
#   Copyright (C) 2021                                                    #
#                                                                         #
#   This program is free software; you can redistribute it and/or modify  #
#   it under the terms of the GNU General Public License as published by  #
#   the Free Software Foundation; either version 2 of the License, or     #
#   (at your option) any later version.                                   #
#                                                                         #
#   This program is distributed in the hope that it will be useful,       #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#   GNU General Public License for more details.                          #
#                                                                         #
#   You should have received a copy of the GNU General Public License     #
#   along with this program; if not, write to the                         #
#   Free Software Foundation, Inc.,                                       #
#   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             #
###########################################################################
```

2021-03-29 14:57 UTC, ihhub commented on Makefile.vita
> +TARGET	:= fheroes2
Please add this header to the file as per our new standards:
```
###########################################################################
#   Free Heroes of Might and Magic II: https://github.com/ihhub/fheroes2  #
#   Copyright (C) 2021                                                    #
#                                                                         #
#   This program is free software; you can redistribute it and/or modify  #
#   it under the terms of the GNU General Public License as published by  #
#   the Free Software Foundation; either version 2 of the License, or     #
#   (at your option) any later version.                                   #
#                                                                         #
#   This program is distributed in the hope that it will be useful,       #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#   GNU General Public License for more details.                          #
#                                                                         #
#   You should have received a copy of the GNU General Public License     #
#   along with this program; if not, write to the                         #
#   Free Software Foundation, Inc.,                                       #
#   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             #
###########################################################################
```

2021-03-29 18:08 UTC, Northfear commented on doc/README_PSV.md
> +[rePatch reDux0](https://github.com/dots-tb/rePatch-reDux0) OR [FdFix](https://github.com/TheOfficialFloW/FdFix) plugin is required for proper suspend/resume support (only use one at a time).
File descriptors are invalidated in homebrew on suspend/resume of PSV (which results in pretty nasty bugs or crashed). Previously I was tracking power events and reopening files on resume, but plugins are are just a better way to deal with it.

2021-03-30 00:36 UTC, merged

2021-03-30 00:36 UTC, ihhub commented
@Northfear , wonderful work! Thanks a lot for your efforts!