Implement base for battle AI
ihhub/fheroes2 pull request #1656
Opened 2020-09-13 06:04 UTC by idshibanov

Skeleton unit logic only, still missing castle defend and combat spell heuristics.
New pathfinding algorithm for battle arena and special debug mode for it if DBG_DEVEL flag is enabled.

2020-09-13 06:34 UTC, ihhub reviewed
Hi @idshibanov , I left just few comments. Please take a look.

2020-09-13 06:34 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +        return myArmy * 10 < enemy;
It's good to know what **10** stands for.

2020-09-13 06:34 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +        return currentUnit.isFlying();
What if we have a walking unit but faster than current one?

2020-09-13 06:34 UTC, ihhub commented on src/fheroes2/battle/battle_pathfinding.cpp
> +            if ( y > 0 && ( x > 0 || ( y % 2 ) == 0 ) ) {
We could cache `y % 2` like `const int mod = y % 2;`

2020-09-13 06:34 UTC, ihhub commented on src/fheroes2/battle/battle_pathfinding.cpp
> +            _cache[i]._from = -1;
Let's cache `_cache[i]` by reference variable.

2020-09-13 06:34 UTC, ihhub commented on src/fheroes2/battle/battle_troop.cpp
> +    return unitsLeft * ( Monster::GetDamageMin() + Monster::GetDamageMax() ) / 2;
This is incorrect. We don't use Bless and Curse modificators here.

2020-09-13 06:45 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +        return currentUnit.isFlying();
"Faster" is ambiguous here. This call determines how far unit can move in context of threat range. Initiative/turn order aspect of the speed wouldn't matter.

2020-09-13 06:49 UTC, idshibanov commented on src/fheroes2/battle/battle_troop.cpp
> +    return unitsLeft * ( Monster::GetDamageMin() + Monster::GetDamageMax() ) / 2;
Good catch.

2020-09-16 13:39 UTC, ihhub requested changes
Hi @idshibanov , I left few comments. Could you please take a look into them?

2020-09-16 13:39 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +                    const Unit * enemy = Board::GetCell( cell )->GetUnit();
Are we sure that `enemy` is always not NULL?

2020-09-16 13:39 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +                        canOutrunEnemy = false;
This variable is for every unit while the rest of variables are not. We need a little explanation about this case please.

2020-09-16 13:39 UTC, ihhub commented on src/fheroes2/battle/battle_pathfinding.cpp
> +            break;
We can `return -1` from here. No need to check further.

2020-09-16 13:39 UTC, ihhub commented on src/fheroes2/battle/battle_pathfinding.cpp
> +            if ( unitHead ) {
We check `!unitHead` at line 124 so there is no need to make such check here.

2020-09-18 07:10 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +                    const Unit * enemy = Board::GetCell( cell )->GetUnit();
`GetAdjacentEnemies` must return valid tiles. I will log an error if it fails now.

2020-09-18 07:16 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +                        canOutrunEnemy = false;
Added a comment there, hopefully it's enough. To stay true this condition has to pass for every adjacent enemy unit

2020-09-19 01:49 UTC, ihhub reviewed
Hi @idshibanov , good work! I left just few comments here. Please take a look.

2020-09-19 01:49 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +        return hero && ( hero->GetLevel() > 2 || !hero->GetBagArtifacts().empty() );
Shall we change the conditions to check primary skills instead? For example, some Campaign hero's are definitely worth to be saved as they have much higher stats.

2020-09-19 01:49 UTC, ihhub commented on src/fheroes2/battle/battle_arena.cpp
> +bool Battle::Arena::TileIsAccessible( int32_t indexTo )
Battle grid contains hexes, not tiles. Maybe it's worth to rename to don't make a confusion for other developers.

2020-09-19 01:49 UTC, ihhub commented on src/fheroes2/battle/battle_troop.cpp
> +uint32_t Battle::Unit::CalculateRetaliationDamage( uint32_t damageTaken ) const
Please check `u32 Battle::Unit::GetDamage( const Unit & enemy ) const` method and maybe remove duplicated code.

2020-09-19 01:49 UTC, ihhub commented on src/fheroes2/battle/battle_troop.cpp
> +uint32_t Battle::Unit::CalculateRetaliationDamage( uint32_t damageTaken ) const
At least
```
    uint32_t damagePerUnit = 0;
    if ( Modes( SP_CURSE ) )
        damagePerUnit = Monster::GetDamageMin();
    else if ( Modes( SP_BLESS ) )
        damagePerUnit = Monster::GetDamageMax();
    else
        damagePerUnit = ( Monster::GetDamageMin() + Monster::GetDamageMax() ) / 2;
```
we can definitely wrap into a separate code.

2020-09-19 08:42 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +        return hero && ( hero->GetLevel() > 2 || !hero->GetBagArtifacts().empty() );
We could change it, but I think it's not worth the effort at the moment. Ideally the threshold/condition will be calculated during the AI turn, before the battle.

2020-09-19 08:50 UTC, idshibanov commented on src/fheroes2/battle/battle_troop.cpp
> +uint32_t Battle::Unit::CalculateRetaliationDamage( uint32_t damageTaken ) const
Code looks similar but it achieves different things. Retaliation calculates raw damage (from `Monster` class) numbers without automatically applying unit count (in `ArmyTroop` class) and damage modifiers.

I think a lot of that code (`GetDamage`) has to be refactored anyway, I just didn't want to turn it into another chunk of changes.

2020-09-20 23:29 UTC, merged

2020-09-20 23:29 UTC, ihhub commented
Hi @idshibanov thanks a lot for these changes!