Amount of creatures moved down by 1 pixel in DrawMonsterInfo
ihhub/fheroes2 pull request #1812
Opened 2020-09-26 10:32 UTC by shprotru

Fix #1740

2020-09-26 11:45 UTC, ihhub commented
Hi @shprotru , this is not a full fix for the issue. The biggest problem here is a horizontal position of numbers. Moreover, we have 2 types of window: good and evil interfaces and they have different area for such number.

This is a proper fix for only `good` interface:
```
pos.x = offset.x + 80 + 125 / 2 - text.w() / 2;
pos.y = offset.y + 222 + 23 / 2 - text.h() / 2 + 1;
```

but still we must avoid all these hardcoded values.

2020-09-26 21:51 UTC, idshibanov commented
> but still we must avoid all these hardcoded values.

What's the approach for this you think? Most hardcoded offsets in UI I saw are related to original assets (shadows, GUI sprites) which won't change.

2020-09-27 10:31 UTC, ihhub requested changes
Hi @shprotru , could you please take a look into 2 given comments?

2020-09-27 10:31 UTC, ihhub commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +    pos.x = offset.x + ( Settings::Get().ExtGameEvilInterface() ? offsetXEvilAmountBox : offsetXGoodAmountBox ) + widthAmountBox / 2 - text.w() / 2;
Please cache `Settings::Get().ExtGameEvilInterface()` variable: `const bool isEvilInterface = Settings::Get().ExtGameEvilInterface()`.

2020-09-27 10:31 UTC, ihhub commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +    const int offsetXGoodAmountBox = 80;
Put all these variables in unnamed namespace at the beginning of the file.

2020-09-27 10:44 UTC, shprotru commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +    const int offsetXGoodAmountBox = 80;
done

2020-09-27 10:49 UTC, shprotru commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +    pos.x = offset.x + ( Settings::Get().ExtGameEvilInterface() ? offsetXEvilAmountBox : offsetXGoodAmountBox ) + widthAmountBox / 2 - text.w() / 2;
done

2020-09-27 15:39 UTC, ihhub commented
> > but still we must avoid all these hardcoded values.
> 
> What's the approach for this you think? Most hardcoded offsets in UI I saw are related to original assets (shadows, GUI sprites) which won't change.

At least we need to minimize these hardcoded values replacing them where needed by formulas. This will make our code more flexible for the future changes.

2020-09-27 15:40 UTC, merged

2020-09-27 15:40 UTC, ihhub commented
@shprotru good job! Thank you very much for fixing this issue!