Add captain portraits in Kingdom Overview
ihhub/fheroes2 pull request #1880
Opened 2020-10-03 17:37 UTC by taeber

### After
![After](https://user-images.githubusercontent.com/1855194/94998021-0782de00-057d-11eb-9cef-1df739e02cd4.png)
_Captain portraits appear after change_

### Before
![Before](https://user-images.githubusercontent.com/1855194/94998023-08b40b00-057d-11eb-954c-5be1c6526fea.png)
_No captain portraits even when Captain present before_

### Unchanged
![](https://user-images.githubusercontent.com/1855194/94998022-081b7480-057d-11eb-8bac-06d9b9922313.png)
_Hero portrait takes precedent_

![No portrait without captain](https://user-images.githubusercontent.com/1855194/94998023-08b40b00-057d-11eb-954c-5be1c6526fea.png)
_No portrait when there is no captain and no hero_

Fixes #1848

2020-10-04 06:59 UTC, ihhub requested changes
Hi @taeber , great work! Could you please take a look into given comments?

2020-10-04 06:59 UTC, ihhub commented on src/fheroes2/castle/captain.cpp
> +        fheroes2::Blit( port, dstsf, px, py );
Could you please merge `GetPortrait( type )` with this line so we don't create an extra object:
```
fheroes2::Blit( GetPortrait( type ), dstsf, px, py );
```

2020-10-04 06:59 UTC, ihhub commented on src/fheroes2/castle/captain.cpp
> +        fheroes2::Blit( port, dstsf, px + barw + 1, py );
Could you please merge `GetPortrait( type )` with this line so we don't create an extra object:
```
fheroes2::Blit( GetPortrait( type ), dstsf, px + barw + 1, py );
```

2020-10-04 06:59 UTC, ihhub commented on src/fheroes2/castle/captain.cpp
> +        const int iconsw = Interface::IconsBar::GetItemWidth();
Please use camelStyle of variable naming: `iconWidth` and `iconHeight`.

2020-10-04 06:59 UTC, ihhub commented on src/fheroes2/castle/captain.cpp
> +        blueBG.fill( fheroes2::GetColorId( 15, 30, 120 ) );
Original HoMM 2 palette doesn't have such color. Could you please find out (by using a color picket tool for example) the needed color for this case?

2020-10-04 06:59 UTC, ihhub commented on src/fheroes2/castle/captain.cpp
> +        const int iconsw = Interface::IconsBar::GetItemWidth();
and for `barWidth` as well please.

2020-10-06 16:46 UTC, taeber commented
Yes, I will look into making those changes when I get time. I want to mention that this was adapted from `Heroes::PortraitRedraw()`, so I think any changes I make here should be made there as well. What do you think?

2020-10-06 17:14 UTC, taeber commented on src/fheroes2/castle/captain.cpp
> +        fheroes2::Blit( port, dstsf, px, py );
I adapted this code from `Heroes::RedrawPortrait`, where the "extra object" was created.

I can make the change you want, but, just so you know, compilers are smart enough to optimize this type of code so the change you're asking for won't impact the generated assembly.

In fact, I checked out both versions (with and without the "extra object") of this code with [Compiler Explorer](https://godbolt.org/) and the assembly that gets generated by both GCC and clang is **exactly** the same.

Another option is to use `std::move( port )` to hint to the compiler that a copy isn't necessary (and therefore not "extra"), but again, it's not necessary in this case.

2020-10-07 13:58 UTC, ihhub commented on src/fheroes2/castle/captain.cpp
> +        fheroes2::Blit( port, dstsf, px, py );
Sadly, we support a broad range of compilers and we cannot guarantee that every compiler will optimize in the same way. It's better to be more explicit in this case.

We still have a lot of old and non-optimized code so I'm not surprised if even the untouched part of the code is bad :)

2020-10-07 17:14 UTC, idshibanov commented
> 
> Yes, I will look into making those changes when I get time. I want to mention that this was adapted from `Heroes::PortraitRedraw()`, so I think any changes I make here should be made there as well. What do you think?

If you're willing to refactor `Heroes::PortraitRedraw()` as well - go ahead; it is always welcome. We're slowly rewriting the project, but there's still a lot of places that require special attention. GUI is one of them.

Could do it in a separate PR so current changes won't be stuck in approval hell.

2020-10-21 15:02 UTC, ihhub commented
Hi @taeber do you have some time to update your pull request?

2020-10-22 13:54 UTC, taeber commented
Sorry @ihhub. I actually just started a new job and have found no time to work on this.

2020-10-23 00:09 UTC, ihhub commented
Congratulations, @taeber ! No worries, I'll complete this 🙂

2020-11-23 14:13 UTC, merged

2020-11-23 14:14 UTC, ihhub commented
@taeber thank you very much for your valuable contribution to the project!