fixed issue #1887
ihhub/fheroes2 pull request #1897
Opened 2020-10-04 12:18 UTC by Lumary2

Happy Hacktoberfest :)

2020-10-04 14:55 UTC, ihhub requested changes
Hi @Lumary2, could you please make the requested change or discuss it?

2020-10-04 14:55 UTC, ihhub commented on README.md
> +- open `script/macos` or `script/linux` directory depending on your OS and run **install_sdl_1.sh** or **install_sdl_2.sh** file.  For Arch based distros you need to install SDL with the command `sud
Hi @Lumary2 , could you please revert changes in this file as we follow the rule of having only related changes in pull request?

2020-10-04 15:57 UTC, Lumary2 commented on README.md
> +- open `script/macos` or `script/linux` directory depending on your OS and run **install_sdl_1.sh** or **install_sdl_2.sh** file.  For Arch based distros you need to install SDL with the command `sud
Hi @ihhub You can close this pr and I did a new one without the readme change.

2020-10-05 15:28 UTC, ihhub commented
Closing this pull request by author's request.

2020-10-05 15:29 UTC, closed without merging