RPM Linux Distros
ihhub/fheroes2 pull request #1929
Opened 2020-10-07 22:48 UTC by kaeptnkrunch

added the commands for RPM based Linux distributions like Fedora/Red Hat and the File SDL_mixer.ymp for openSUSE.

2020-10-21 15:03 UTC, ihhub reviewed
Hi @kaeptnkrunch could you please check given comments?

2020-10-24 06:35 UTC, ihhub requested changes
Hi @kaeptnkrunch could you please take a look into given comments?

2020-10-28 10:26 UTC, kaeptnkrunch commented on script/linux/SDL_mixer.ymp
> +        <description>Non free or non open source parts of openSUSE Leap 15.2.</description>
Hey, yes its a File for One-Click-Install of the SDL. Its common in openSUSE and beginner Friendly

2020-10-28 11:50 UTC, merged

2020-10-28 11:50 UTC, ihhub commented
@kaeptnkrunch thank you very much for you contribution to the project!

2020-10-28 11:58 UTC, kaeptnkrunch commented
I´m sry for my late reply