feat: when retreating, give the hero its default army instead of 1 T1 unit
ihhub/fheroes2 pull request #1935
Opened 2020-10-09 10:48 UTC by eos428

Also let me know if my coding style is not up to your taste and/or standards.

2020-10-09 10:53 UTC, ihhub commented
Hi @eos428 , thanks for your work! Please refer to **Clang-format** CI job (which failed) to comply with our code styling🙂

2020-10-09 10:58 UTC, eos428 commented
Hmm... I'm not too used with code styling checks. Is it because I didn't space out the two circular brackets?

2020-10-09 15:49 UTC, ihhub requested changes
Hi @eos428 , code you please revert code refactoring changes so we could review only the portion related to the fix? We know that our code is not ideal but this refactor doesn't make the code significantly better or faster.

2020-10-09 15:49 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> -    if ( !isFreeman() ) {
Could you please revert code refactoring and only leave the changes related to the fix? It's really difficult to understand exact change with this refactoring.

2020-10-09 15:49 UTC, ihhub commented
> Hmm... I'm not too used with code styling checks. Is it because I didn't space out the two circular brackets?

You correctly fixed coding styling issues :)

2020-10-09 16:05 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +            bool isSurrender = reason & Battle::RESULT_SURRENDER;
Please make this variable `const` as we don't change it. Also we're introducing a compilation warning here. The proper code should be:
```
const bool isSurrender = ( reason & Battle::RESULT_SURRENDER ) != 0;
```
We're currently fixing a lot of compilation warnings so this is one of them :)

2020-10-10 02:31 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +            const bool isSurrender = reason & Battle::RESULT_SURRENDER;
The only case where we don't reset army is for surrender case so the whole if-else code in this case must be rewritten as:
```
if ( ( reason & Battle::RESULT_RETREAT ) == 0 ) {
    army.Reset( true );
}
```

2020-10-10 02:42 UTC, eos428 commented on src/fheroes2/heroes/heroes.cpp
> +            const bool isSurrender = reason & Battle::RESULT_SURRENDER;
Shouldn't this if clause be for Battle::RESULT_SURRENDER then?

2020-10-10 09:35 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +            army.Reset( false );
Could you please verify when a hero surrenders his army still present when a player re-hires him?

2020-10-10 09:43 UTC, eos428 commented on src/fheroes2/heroes/heroes.cpp
> +            army.Reset( false );
I tested it and there's only 1 T1 unit on the hero after surrendering.

2020-10-10 09:50 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +            army.Reset( false );
In the original game a surrendered hero has his army as he pays money to keep it.

2020-10-10 10:18 UTC, eos428 commented on src/fheroes2/heroes/heroes.cpp
> +            army.Reset( false );
Should be okay now since the army no longer resets on surrendering

2020-10-10 11:21 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +            army.Reset( false );
The correct implementation should be:
```
if ( ( reason & Battle::RESULT_SURRENDER ) == 0 ) { // reset the army if hero didn't surrender
    army.Reset( true );
}
```

I don't think that in the original game we ever had an army with 1 creature.

Is it correct, @LeHerosInconnu?

2020-10-10 11:57 UTC, LeHerosInconnu commented on src/fheroes2/heroes/heroes.cpp
> +            army.Reset( false );
In Heroes 2, retreating heroes lose any troops still in their army and are subsequently available in the tavern with a standard army, never with a single creature.

This one-creature army appeared in a patch for Heroes 3 following complaints from multiplayer players* that it was unfair and unbalanced to be able to recruit heroes with a small army.
This patch was frustrating for the solo player who wants to have fun playing the game.

*Definition of multiplayer players:
Those who are few but who cry out loud.
They take out all the fun of a game under the pretext of balancing (which in any case is never attainable) by all imposing a bunch of rules that ruin all the concepts of a game.

For me, Heroes of Might and Magic 2 (and 3) is a strategy game that should be designed for single player play.
The multiplayer is just marketing, a line to add to the game sheet to have 2 to 3% more sales.
The time dedicated to implement multiplayer, could have been used to implement other features and/or more content for the game.
What a waste.

2020-10-10 12:11 UTC, idshibanov commented on src/fheroes2/heroes/heroes.cpp
> +            army.Reset( false );
> For me, Heroes of Might and Magic 2 (and 3) is a strategy game that should be designed for single player play.
> The multiplayer is just marketing, a line to add to the game sheet to have 2 to 3% more sales.

It is not 1996 anymore. Modern engine has to meet modern needs.

2020-10-10 12:51 UTC, LeHerosInconnu commented on src/fheroes2/heroes/heroes.cpp
> +            army.Reset( false );
@idshibanov.

> > For me, Heroes of Might and Magic 2 (and 3) is a strategy game that should be designed for single player play.
> > The multiplayer is just marketing, a line to add to the game sheet to have 2 to 3% more sales.
> 
> It is not 1996 anymore. Modern engine has to meet modern needs.

Yes, I know. :)
It was fun to write it down and so true back then. :D

But still, have you estimated the proportion of solo and multiplayer players?
And if multiplayer players plan to play the game over time? (And not just one or two games and that's enough.)

For a turn-based game, even with the possibility of simultaneous actions, the waiting time is still significant.
And it is more bearable in "hot seat" mode.
And what do you think of the PBEM (play by email) mode?

2020-10-11 08:23 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +            army.Reset( false );
Let's fix how it suppose to be in the original game. If hero retreats it will have a basic army.

@eos428 please proceed with proposed solution of mine.

2020-10-11 09:03 UTC, eos428 commented on src/fheroes2/heroes/heroes.cpp
> +            army.Reset( false );
My last commit should be according to your solution already :)

2020-10-11 13:35 UTC, merged

2020-10-11 13:35 UTC, ihhub commented
@eos428 thank you very much for your contribution to the project!

2020-10-11 15:05 UTC, eos428 commented
No problem, The pleasure's all mine :)