Game windows, changes to title, yellow color and colon
ihhub/fheroes2 pull request #1990
Opened 2020-10-14 08:54 UTC by shprotru

Fix for #1919

2020-10-21 14:58 UTC, ihhub requested changes
Hi @shprotru could you please take a look into comments?

2020-10-21 14:58 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    std::string title, msg;
Please do not declare multiple variables at one use. Always declare one variable per line.

2020-10-21 14:58 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    const bool isTitlePresent = title.length() > 0;
Please use `!title.empty()` instead.

2020-10-21 14:58 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +        TextBox box( title, Font::YELLOW_BIG, 270 );
Please make this variable `const`.

2020-10-21 14:58 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +        TextBox box( msg, Font::BIG, 270 );
Please make this variable `const`.

2020-10-21 14:58 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +        TextBox box( title, Font::YELLOW_BIG, 270 );
What the value 270 stand for? Is it a width of the window?

2020-10-21 14:58 UTC, ihhub commented on src/fheroes2/dialog/dialog_recrut.cpp
> +    TextBox recruitMonsterText( str, Font::YELLOW_BIG, BOXAREA_WIDTH );
Let's please put all changes which are not present in the original game into separate pull request as we did not discussed them properly.

2020-10-21 16:42 UTC, shprotru commented on src/fheroes2/battle/battle_dialogs.cpp
> +        TextBox box( title, Font::YELLOW_BIG, 270 );
can't .Blit then, reason:
```
no instance of overloaded function "TextBox::Blit" matches the argument list and object (the object has type qualifiers that prevent a match) -- argument types are: (int, int) -- object type is: const TextBox
```

2020-10-21 17:41 UTC, shprotru commented on src/fheroes2/battle/battle_dialogs.cpp
> +        TextBox box( title, Font::YELLOW_BIG, 270 );
This is a text width, was taken here: https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/battle/battle_dialogs.cpp#L392

2020-10-21 18:00 UTC, shprotru commented on src/fheroes2/battle/battle_dialogs.cpp
> +    std::string title, msg;
done

2020-10-21 18:00 UTC, shprotru commented on src/fheroes2/battle/battle_dialogs.cpp
> +    const bool isTitlePresent = title.length() > 0;
done

2020-10-21 18:01 UTC, shprotru commented on src/fheroes2/battle/battle_dialogs.cpp
> +        TextBox box( msg, Font::BIG, 270 );
can't call `.Blit` then, reason:
```
no instance of overloaded function "TextBox::Blit" matches the argument list and object (the object has type qualifiers that prevent a match) -- argument types are: (int, int) -- object type is: const TextBox
```

2020-10-22 08:58 UTC, shprotru commented on src/fheroes2/dialog/dialog_recrut.cpp
> +    TextBox recruitMonsterText( str, Font::YELLOW_BIG, BOXAREA_WIDTH );
reverted back

2020-10-22 13:28 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +        TextBox box( title, Font::YELLOW_BIG, 270 );
Please declare a separate variable for this. Old code contains a lot of hardcoded values and we should avoid them as much as possible.

2020-10-22 14:07 UTC, shprotru commented on src/fheroes2/battle/battle_dialogs.cpp
> +        TextBox box( title, Font::YELLOW_BIG, 270 );
check, please

2020-10-22 14:15 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    }
Let's do like this:
```
    int32_t messageYOffset = 0;
    if ( !title.empty() ) {
        TextBox box( title, Font::YELLOW_BIG, bsTextWidth );
        box.Blit( pos_rt.x + bsTextXOffset, pos_rt.y + bsTextYOffset );
        messageYOffset = bsTextIndent;
    }

    if ( !msg.empty() ) {
        TextBox box( msg, Font::BIG, bsTextWidth );
        box.Blit( pos_rt.x + bsTextXOffset, pos_rt.y + bsTextYOffset + messageYOffset );
    }
```
Is it easier to read?

2020-10-22 14:29 UTC, shprotru commented on src/fheroes2/battle/battle_dialogs.cpp
> +    }
done

2020-10-26 14:18 UTC, ihhub commented
Hi @shprotru , I'm still keeping looking at this PR so don't think that we forget about this :) I just don't want to make a radical changes from the original (for now).

@Branikolog could you please take a look into the original issue and give your opinion?

2020-11-23 15:53 UTC, ihhub commented
Hi @shprotru could you please do this:
- leave only the changes related to `Income` and `Buy Monsters` dialogs
- remove the rest of the code.

We need this as the original issue combines changes to new windows which are not present in the original game and changes in old dialogs which have the same style as in the original game.

We're okay to modify new windows as by styling is better but for old windows is debatable. After merging the changes only for old windows we can update the issue and you can create a new pull request once we agree on changes.

2020-11-24 19:23 UTC, shprotru commented
@Branikolog this was as a suggestion(currently declined changes), need your approvement or decline.
![Снимок экрана от 2020-11-24 22-13-28](https://user-images.githubusercontent.com/53114202/100141156-026a4d00-2ea3-11eb-9bf3-1e76245b2f8b.png)
![Снимок экрана от 2020-11-24 22-19-19](https://user-images.githubusercontent.com/53114202/100141225-2168df00-2ea3-11eb-8476-35a3c6345967.png)
![Снимок экрана от 2020-11-24 22-15-03](https://user-images.githubusercontent.com/53114202/100141158-039b7a00-2ea3-11eb-9b2f-f8930800bf5d.png)

2020-11-24 21:13 UTC, Branikolog commented
Hi, @shprotru !
I agree with @ihhub, these improvements are debatable. 
But you know, actually, I like them. Looking at your screenshots, I can tell they're looking not bad! We were going to leave improvements the original UI to the latest release... And implementing them right now is probably a bit too early... 
Anyway. My +1 for this changes.

2020-11-25 00:35 UTC, LeHerosInconnu commented
@Branikolog and @shprotru.

> Hi, @shprotru !
> But you know, actually, I like them. Looking at your screenshots, I can tell they're looking not bad!
> Anyway. My +1 for this changes.

I like this positivism. :)

Thank you @shprotru, for showing him the way. :D

2020-11-26 17:45 UTC, shprotru commented
Hi, @LeHerosInconnu! I am done with `A glorious victory!`, but how to deal with `The enemy has surrendered!` and `The enemy has fled!` titles?

2020-11-26 19:36 UTC, LeHerosInconnu commented
Hello @shprotru,

> Hi, @LeHerosInconnu! I am done with `A glorious victory!`, but how to deal with `The enemy has surrendered!` and `The enemy has fled!` titles?

Good question. :)

On the one hand, the title is a sentence with a verb and it can be a bit weird to capitalize every word in the sentence.

`The Enemy Has Surrendered!` and `The Enemy Has Fled!`

On the other hand, if all the words are not capitalized the rule is not respected and that is just as weird.

Maybe we should change the text to make it less weird:

"The Enemy Surrendered!"

and:

"The Enemy Fled!"

Instead of:

"The enemy has surrendered!"

and:

"The enemy has fled!"

What do you folks think?

2020-11-27 11:37 UTC, Branikolog commented
Actually, I like all this sentences look in original game without "capitalization".

2020-11-27 18:23 UTC, shprotru commented
Declined capitalization of `A glorious victory!` message

2020-11-28 16:16 UTC, ihhub commented
Let's move all changes from the original game into separate pull request. We're mixing right now the original design and our new windows. We should separate it in order to track changes and implement them once everyone (majority) accepts them.

I think this is a proper way to move with this issue after all.

2020-11-28 16:18 UTC, ihhub commented
I'm okay with changing the color of titles in battle dialogs for now but let's don't change messages in this pull request.

2020-11-28 16:22 UTC, ihhub requested changes
Hi @shprotru , I left few comments. Could you please take a look?

2020-11-28 16:22 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    const std::string msgAGloriousVictory = "A glorious victory!";
Please use `const char *` instead.

2020-11-28 16:22 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    const std::string msgAGloriousVictory = "A glorious victory!";
Actually please revert to the original value when we use the same sentence in both places. Let's make less changes in the original code so it's easier to track.

2020-11-28 16:22 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    if ( msg.length() > 0 ) {
Please use this `if ( !msg.empty() ) {`.

2020-11-28 16:26 UTC, shprotru commented on src/fheroes2/battle/battle_dialogs.cpp
> +    const std::string msgAGloriousVictory = "A glorious victory!";
done

2020-11-28 16:26 UTC, shprotru commented on src/fheroes2/battle/battle_dialogs.cpp
> +    if ( msg.length() > 0 ) {
done

2020-11-30 11:36 UTC, merged

2020-11-30 11:37 UTC, ihhub commented
@shprotru thank a lot for fixing this issue!