Give every magic guild at least one of the guaranteed spells
ihhub/fheroes2 pull request #2042
Opened 2020-10-19 13:16 UTC by eos428

Solves #1532.

2020-10-19 13:25 UTC, idshibanov commented
Great job! Can you also take a look at discussion in #1531 ? Game also should guarantee that one of the damage spells is there. (Arrow/Cold ray/Lightning/Cold ring/Fireball, equal random chance). Maybe you can adjust your code to do both.

2020-10-19 13:41 UTC, eos428 commented
Sure, why not :) I'll take the chance to kill two issues in one PR :D

2020-10-19 14:51 UTC, eos428 commented
Now this PR also solves #1531. Based on the discussions and screenshots in that issue, it seems possible for a mage guild to have no adventure spell for any level. I also refactored the way to append spells into the mage guild so let me know if I overstepped my boundaries.

2020-10-19 18:30 UTC, idshibanov requested changes
Please replace 5 variables and switch cases with a spell count vector. Something like that:
```
std::vector<int> spellLevelCount = {3, 3, 2, 2, 1};

--spellLevelCount[guaranteedDamageSpellLevel - 1];

for ( size_t idx = 0; idx < 5; ++idx )
    for ( int i = 0; i < spellLevelCount[idx]; ++i )
        general.Append( GetUniqueSpellCompatibility( general, race, spellLevelCount[idx] + 1 ) );
```

2020-10-20 10:28 UTC, idshibanov approved these changes

2020-10-21 14:35 UTC, ihhub reviewed
Hi @eos428 , everything looks good except one place. Could you please take a look into it? If you disagree please explain why and maybe we just need to have a comment explaining such.

2020-10-21 14:35 UTC, ihhub commented on src/fheroes2/castle/mageguild.cpp
> +    while ( spells.isPresentSpell( spell ) || !spell.isRaceCompatible( race ) )
The only concern is this loop which could be an infinite loop. To avoid this we need to copy the logic from `Spell::Rand` method and add needed checks in the loop where we populate a temporary container. In such case we could avoid an unknown amount of iterations (or even infinite) and fix the case when we don't have a spell (maybe in the future for example).

2020-10-21 16:00 UTC, eos428 commented on src/fheroes2/castle/mageguild.cpp
> +    while ( spells.isPresentSpell( spell ) || !spell.isRaceCompatible( race ) )
Hmm... I think we don't have to redo the part where we have to populate a temporary container, since it's already done in `Spell::Rand`. In my latest commit, I'll just make sure to stop the while loop if we get `Spell::NONE`. Let me know your thoughts about it.

2020-10-21 16:52 UTC, ihhub commented on src/fheroes2/castle/mageguild.cpp
> +    while ( spells.isPresentSpell( spell ) || !spell.isRaceCompatible( race ) ) {
Here we still have an unknown number of iterations to get a proper spell. The chance to get a proper spell could varies from 1 to 100 or even 1000. We must copy the logic from Spell::Rand and do everything in one iteration instead of relying on randomization.

2020-10-22 03:34 UTC, eos428 commented on src/fheroes2/castle/mageguild.cpp
> +    while ( spells.isPresentSpell( spell ) || !spell.isRaceCompatible( race ) ) {
Latest commit now uses the for loop logic as in Spell::Rand. Still, I think we could optimize this further by having const vectors of all spells in a particular level, and then build up another vector that filters the spell list of that level based on the multiple conditions?

2020-10-22 12:59 UTC, merged

2020-10-22 12:59 UTC, ihhub commented
@eos428 thanks a lot for fixing these issues!