Use hero spell power when applying Earthquake
ihhub/fheroes2 pull request #2061
Opened 2020-10-21 20:24 UTC by tau3

Hello!

Please, review my PR for #117 

I couldn't find out what do magic numbers 8, 29, 73, 96 mean. If everything else is ok, i think it's worth making constants for them to increase readability.

2020-10-22 13:44 UTC, ihhub requested changes
Hi @tau3 thanks a lot for your efforts! Could you please take a look into given comments?

2020-10-22 13:44 UTC, ihhub commented on src/fheroes2/battle/battle_action.cpp
> +    for ( auto i : { 8, 29, 73, 96 } ) {
Hi @tau3 magic numbers you mentioned (8, 29, 73, 96) are cell positions in the battle grid. Please go ahead and add them as a part of private enumeration of the `Battle::Arena` class.

2020-10-22 13:44 UTC, ihhub commented on src/fheroes2/battle/battle_action.cpp
> +    for ( auto i : { 8, 29, 73, 96 } ) {
Please avoid using `auto` for trivial types or classes. We allow to use them only in lambda functions and in specific loops. We're doing this for better readability and understating the code.

2020-10-22 13:44 UTC, ihhub commented on src/fheroes2/battle/battle_action.cpp
> +    auto range = damage_range( commander );
Please make these 2 variables `const` as we don't modify them.

2020-10-22 13:44 UTC, ihhub commented on src/fheroes2/battle/battle_action.cpp
> +std::pair<int, int> damage_range( const HeroBase * );
Please add missing input variable name.

2020-10-22 13:44 UTC, ihhub commented on .gitignore
> +fheroes2
It's okay adding VS Code extension into ignore list but please revert changes for these 3 includes.

2020-10-22 13:44 UTC, ihhub commented on src/fheroes2/battle/battle_action.cpp
> +    auto result = std::make_pair( 0, 1 );
Please avoid using `auto` word here.

2020-10-22 13:44 UTC, ihhub commented on src/fheroes2/battle/battle_action.cpp
> +        result = std::make_pair( 0, 1 );
We could directly return without the need of having a temporary variable.

2020-10-22 13:44 UTC, ihhub commented on src/fheroes2/battle/battle_action.cpp
> +    return result;
No need to have a temporary variable. Just directly `return std::make_pair( 0, 1 );`

2020-10-22 13:44 UTC, ihhub commented on src/fheroes2/battle/battle_action.cpp
> +    auto spell_points = commander->GetSpellPoints();
Please make this variable `const` as well.

2020-10-22 13:45 UTC, ihhub commented
Hi @LeHerosInconnu, do you know that this is the case in the original game as well?

2020-10-22 13:59 UTC, LeHerosInconnu commented
@ihhub.

> Hi @LeHerosInconnu, do you know that this is the case in the original game as well?

I cannot answer with great precision how the spell works.
But, the higher the Spell Power level of the hero who casts the spell, the more damage the spell does to walls, turrets and drawbridge and more elements of the castle enclosure are also affected.
The spell's sound is also louder depending on the hero's Spell Power level.

2020-10-22 14:51 UTC, tau3 commented on src/fheroes2/battle/battle_action.cpp
> +    for ( auto i : { 8, 29, 73, 96 } ) {
Hi!) Not sure i understood the idea about private enum, but i made a static const array with a self-desribing name (because it's not used anywhere else). Is it ok?

2020-10-22 14:56 UTC, tau3 commented
@ihhub thank you for putting effort in verbose review, it helps a lot! 

There is one thing that shoud have been clarified earlier: i made an assumption that `u32 HeroBase::GetSpellPoints( void ) const` returns percents, and not a absolute value. Is it correct?

2020-10-22 15:33 UTC, idshibanov commented
> There is one thing that shoud have been clarified earlier: i made an assumption that `u32 HeroBase::GetSpellPoints( void ) const` returns percents, and not a absolute value. Is it correct?

Original issue wasn't well defined. Spellpoints is a wrong thing to get, it's a hero's "mana" and it's value can be from 0 to anything (300+), depending on Knowledge stat.

You have to use `int Heroes::GetPower( void ) const` to get spell power and then we have to define the damage ranges. There's no similar logic in original game (it's all random) but this is a nice enhancement that I agree should be added. Again, there's no "max" value to a spell power, but I think we should set a limit ourselves.

We don't want to make spell completely worthless on low power (it is a very situation spell anyway). My suggestion is:
1-2 power range is 0...1
3-5 power range is 0...2
6-9 power range is 0...3
10+ power range is 1..3

2020-10-22 19:03 UTC, LeHerosInconnu commented
I was convinced that it wasn't as random as all that.
I remember a combat in which a Sorceress AI hero with a high level of Spell Power destroyed multiple walls with a single spell, so it was a coincidence.
Well.

Why not really take the hero's Spell Power level into account then and make the spell always be useful (always having knowledge of the damage).

So, it seems that each wall has 3 points of resistance.

What do you think about this:
Each part of the castle enclosure has a certain number of points of resistance.
- Wall: 3 points of resistance each, so 12 points of resistance.
- Drawbridge: 3 points of resistance.
- Turret with archers: 3 points of resistance each, so 6 points of resistance.
- Drawbridge turret: 2 points of resistance each, so 4 points of resistance.
- Ballista: 5 points of resistance.

That is a total of 30 points of resistance.

For the fortifications of the Knight's Castle, 3 points of resistance are added for each wall and for the drawbridge, so 15 additional points of resistance.

The Earthquake spell does 1 point of damage per level of Spell Power distributed randomly over the different parts of the castle enclosure.

For example, a hero with 10 in Spell Power does 10 damage distributed randomly on different parts of the castle enclosure.

A hero with 30 (and 30+) in Spell Power destroys all parts of the castle enclosure with a single Earthquake spell (even if the catapult does no damage).

And a hero with 45 (and 45+) in Power spell destroys all parts of the castle enclosure of the Knight's Castle with the fortifications with a single Earthquake spell (even if the catapult does no damage).

Having a hero with 30 in Spell Power is not easy to obtain but at the same time it is not impossible to achieve.

2020-10-22 21:15 UTC, idshibanov commented
> So, it seems that each wall has 3 points of resistance.
> 
> What do you think about this:
> Each part of the castle enclosure has a certain number of points of resistance.

Regular walls and towers have 2 hit points in the game, draw bridge is 1 (guaranteed to break on a hit). Only fortified wall in Knight's castle are 3 hits each.

Let's be careful here and not get carried away by new ideas. If you change the castle values then you can break catapult mechanics (which are much more critical to game integrity than some rare spell). Also 30 to 45 spell power are ridiculous values for this game. This is not Heroes 3, let's not balance for some crazy custom maps either.

In the context of this pull request damage range is applied only to walls. So walls have 2 or 3 hp, and should receive 0 to 3 damage accordingly.

2020-10-23 11:31 UTC, LeHerosInconnu commented
@idshibanov.

> > So, it seems that each wall has 3 points of resistance.
> > What do you think about this:
> > Each part of the castle enclosure has a certain number of points of resistance.
> 
> Regular walls and towers have 2 hit points in the game, draw bridge is 1 (guaranteed to break on a hit). Only fortified walls in Knight's castle are 3 hits each. That brings the total either to 15 or 19.

Thank you for the precision on the number of resistance points.
In your calculation, the ballista is considered with 2 resistance points as a turret, right?

> Let's be careful here and not get carried away by new ideas. If you change the castle values then you can break catapult mechanics (which are much more critical to game integrity than some rare spell). Also 30 to 45 spell power are ridiculous values for this game. This is not Heroes 3, let's not balance for some crazy custom maps either.
> 
> In the context of this pull request damage range is applied only to walls. So walls have 2 or 3 hp, and should receive 0 to 3 damage accordingly.

The level of 30 Spell Power is intentional to ensure that the Earthquake spell is not too powerful. :)
So an average hero with 10 in Spell Power needs to cast the spell three times to destroy all parts of the castle enclosure.

Of course, the secondary skill Ballistics should also be adjusted accordingly (or/and the resistance of the parts of the castle enclosure adjusted).

But this is more of an idea for Beyond 1.0, for now let's make the spell work as in the original game.

2020-10-23 16:04 UTC, ihhub requested changes
Hi @tau3 , could you please take a look into given comments? Please don't hesitate to discuss if you think that they're incorrect.

2020-10-23 16:04 UTC, ihhub commented on src/fheroes2/battle/battle_action.cpp
> +    static const int[] cells_affected_by_earthquake = { 8, 29, 73, 96 };
What I meant is to define an enumeration in a private section of this class:
```
enum
{
    FIRST_WALL_HEX_POSITION = 8,
    SECOND_WALL_HEX_POSITION = 29,
    THIRD_WALL_HEX_POSITION = 73,
    FORTH_WALL_HEX_POSITION = 96
};
```
then here in this method just declare a temporary non-static container
```
const std::vector<int> wallHexPositions = { FIRST_WALL_HEX_POSITION, SECOND_WALL_HEX_POSITION, THIRD_WALL_HEX_POSITION, FORTH_WALL_HEX_POSITION };
```

2020-10-23 20:47 UTC, tau3 commented
Hey @ihhub!

Here are the changes. I agree, all those bullets comments are good: obviously, every project should be written in a single style, following selected best practices.

2020-10-24 01:49 UTC, merged

2020-10-24 01:49 UTC, ihhub commented
Hi @tau3 , a bunch of thanks for your contribution to the project!