A creature blinded by Unicorn, with triggered moral is still able to attack
ihhub/fheroes2 pull request #2105
Opened 2020-10-26 20:33 UTC by shprotru

Fix for #2016

2020-10-27 00:25 UTC, idshibanov commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( finish == 0 )
When does this happen?

2020-10-27 08:40 UTC, shprotru commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( finish == 0 )
Hi @idshibanov this done for avoid infinite loop if unit deal 0 damage, currently this is does not appear, because we not tested good our engine. Test case for that: attacker hero with 0 attack skill and 1 peasan, defending hero with 100 defence skill and 1 titan. Peasan attack titan, how much damage they will deal? If 0 infinite loop should be happen.
Mainly this is done for future upgrades: adding into the game of new spells, like weakness, which could reduce attacker damage, etc.

2020-10-31 10:33 UTC, ihhub requested changes

2020-10-31 11:54 UTC, ihhub commented on src/fheroes2/battle/battle_arena.cpp
> +    const bool notBlindOrParalyzed = !current_troop->Modes( SP_BLIND | IS_PARALYZE_MAGIC );
Please do non-inverse logic as we have 2 opposite logic places so no reason to apply logical NOT here.

2020-10-31 11:57 UTC, ihhub commented on src/fheroes2/battle/battle_arena.cpp
> +    const bool notBlindOrParalyzed = !current_troop->Modes( SP_BLIND | IS_PARALYZE_MAGIC );
Actually, I'm wrong but to have better code readability please make `const bool isNonMovable =current_troop->Modes( SP_BLIND | IS_PARALYZE_MAGIC );` variable.

2020-10-31 11:59 UTC, shprotru commented on src/fheroes2/battle/battle_arena.cpp
> +    const bool notBlindOrParalyzed = !current_troop->Modes( SP_BLIND | IS_PARALYZE_MAGIC );
done

2020-10-31 17:15 UTC, idshibanov commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( finish == 0 )
Take out this statement altogether, we can **break** things. Especially with assert.

Finish is animation counter for the next loop. If it's 0 then the loop simply won't run, there's no "infinite loop". We have more logic (for mirror image) that won't execute if you return.

2020-11-01 05:50 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( finish == 0 )
Hi @shprotru , let's revert this code then :)

2020-11-01 09:23 UTC, shprotru commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( finish == 0 )
removed

2020-11-01 10:33 UTC, merged

2020-11-01 10:34 UTC, ihhub commented
@shprotru thank you very much for fixing this bug!