Strategic AI: cooperating heroes and improved estimates
ihhub/fheroes2 pull request #2108
Opened 2020-10-27 06:04 UTC by idshibanov

Now we can evaluate and compare army reinforcements, castle buildings, heroes, skills, spells and artifacts to make more accurate strategic decisions in the future.

Taught AI heroes to exchange armies and artifacts.
Added a few additional validation checks to avoid heroes getting stuck on each other.
Made few improvements based on newly implemented tools (castle/hero priority for example).

2020-10-28 13:34 UTC, ihhub requested changes
Hi @idshibanov , I left multiple comments in this pull request. Could you please take a look into them? My worry that we need to separate Black Dragons upgrade from others.

Also I'm thinking that we might need to use `std::bitset` to hold many other items...

2020-10-28 13:34 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                if ( hero.getStatsValue() >= otherHero->getStatsValue() + 1 )
Why did we put +1?

2020-10-28 13:34 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +            strength += troop->GetStrength();
Please change it into:
```
for ( const Troop * troop : *this ) {
    if ( troop && troop->isValid() )
        strength += troop->GetStrength();
}
```

so it'll be easier to separate on loop from another :)

2020-10-28 13:34 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +            ++value;
Please add {} to the first loop to make the code little more easier to read.

2020-10-28 13:34 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +            ++value;
Shall we have a special case only for `DWELLING_UPGRADE7` with Warlock castle?

2020-10-28 13:34 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +    for ( u32 dw = DWELLING_MONSTER6; dw >= DWELLING_MONSTER1; dw >>= 1 )
Please use `uint32_t` instead of `u32`.

2020-10-28 13:34 UTC, ihhub commented on src/fheroes2/heroes/skill.cpp
> +    for ( const Skill::Secondary skill : *this ) {
Please use const reference here.

2020-10-28 13:34 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +            result += art.getArtifactValue();
Please add {} to the first loop to make the code little more easier to read.

2020-10-28 13:34 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +        }
Please add {} to the first loop to make the code little more easier to read.

2020-10-28 13:34 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +        }
Please add {} to the first loop to make the code little more easier to read.

2020-10-28 14:50 UTC, idshibanov commented
> 
> 
> Hi @idshibanov , I left multiple comments in this pull request. Could you please take a look into them? My worry that we need to separate Black Dragons upgrade from others.
> 
> Also I'm thinking that we might need to use `std::bitset` to hold many other items...

I agree that castle code should be changed to use bitset for buildings. We already ran out of bits without even adding new buildings. We can do this change after the release as castle code should be refactored too.

I'll move black dragons to a separate IF.

2020-10-28 14:56 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                if ( hero.getStatsValue() >= otherHero->getStatsValue() + 1 )
Should have 2 level difference before offering troops to other hero.

2020-10-28 15:09 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                if ( hero.getStatsValue() >= otherHero->getStatsValue() + 1 )
Shouldn't this be `if ( hero.getStatsValue() > otherHero->getStatsValue() + 1 )` (without =)?

2020-10-28 15:20 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                if ( hero.getStatsValue() >= otherHero->getStatsValue() + 1 )
Updated to +2 without =

2020-10-28 15:28 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +    for ( uint32_t level = 0; level < 6; ++level ) {
Here we miss DWELLING_UPGRADE7.

2020-10-28 15:45 UTC, idshibanov commented on src/fheroes2/castle/castle.cpp
> +    for ( uint32_t level = 0; level < 6; ++level ) {
It is a special case at this time, I don't think it's important to show here. If 6th dwelling is upgraded in Warlock castle we can safely assume it's up to Black dragons.

2020-10-28 17:14 UTC, idshibanov commented on src/fheroes2/castle/castle.cpp
> +    for ( uint32_t level = 0; level < 6; ++level ) {
Cleaned it up a little bit

2020-10-29 05:46 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +        return hero && ( color == hero->GetColor() || !Players::isFriends( color, hero->GetColor() ) );
How is it possible to walk through of existing hero?

2020-10-29 10:19 UTC, merged

2020-10-29 10:20 UTC, ihhub commented
@idshibanov excellent work!