One rumor per week
ihhub/fheroes2 pull request #2110
Opened 2020-10-27 14:17 UTC by tau3

Hi!

This is a fix for #1975.
The same rumor will be returned during in-game week. There is also check that each week there will be a different rumor (per castle)

2020-10-28 13:15 UTC, ihhub requested changes
Hi @tau3 , could you please take a look into given comments? If you have a better idea about the design of the solution please speak out :)

2020-10-28 13:15 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +{}
Hi @tau3 , could you please do not use delegated constructor as it's very hard to understand the code. To avoid this just make `Castle::Castle( s32 cx, s32 cy, int rc )` constructor to have default arguments.

2020-10-28 13:15 UTC, ihhub commented on src/fheroes2/castle/castle.h
> +    };
Please explicitly put `private` section of the class and place it after public section.

2020-10-28 13:15 UTC, ihhub commented on src/fheroes2/castle/castle_tavern.cpp
> +    int currentWeek = world.GetWeek();
Please make this variable `const` as we don't modify it.

2020-10-28 13:15 UTC, ihhub commented on src/fheroes2/castle/castle.h
> +    RumorOfWeek rumorOfWeek;
Please put this member to the same place as other members. Also please start the name of the member from underscore character **_**

2020-10-28 13:15 UTC, ihhub commented on src/fheroes2/castle/castle.h
> +        const std::string * rumor;
Please name members of the class from underscore character **_**.

2020-10-28 13:15 UTC, ihhub commented on src/fheroes2/castle/castle_tavern.cpp
> +        }
Why do we need remember a pointer of a possibly removable string instead of an index of `vec_rumors`? Just pass a reference to `vec_rumors` into the constructor of this class so then we don't need to refer to **world** variable.

2020-10-28 13:15 UTC, ihhub commented on src/fheroes2/castle/castle_tavern.cpp
> +        }
Also after making these changes we can remove `world.GetRumors();` method.

2020-10-28 13:15 UTC, ihhub commented on src/fheroes2/castle/castle_tavern.cpp
> +    world.GetWeek();
Why do we need this line of code?

2020-10-28 13:31 UTC, tau3 commented on src/fheroes2/castle/castle_tavern.cpp
> +    world.GetWeek();
it was an accident :)

2020-10-28 13:34 UTC, tau3 commented on src/fheroes2/castle/castle.h
> +        const std::string * rumor;
Sure, np. Is it current naming convention of the project? I think i haven't seen many members with underscores in other classes

2020-10-28 13:34 UTC, ihhub commented on src/fheroes2/castle/castle.h
> +        const std::string * rumor;
Yes, it is. Sadly, we have a lot of old code which was written without a proper code styling :(

2020-10-29 17:01 UTC, ihhub requested changes
Hi @tau3 could you please take a look into given comments?

I thought that `vec_rumors` is a vector but it's a list which is weird. We might need to change it's type but for now let's address the rest of comments.

2020-10-29 22:03 UTC, tau3 commented
Hey @ihhub! Thanks for reviews and patience :)

Did all the changes you reqested, but after a dev test i found out that castles are initialized _before_ world, hence the list of rumors is empty during castles creation, what leads to a failure in `RumorOfWeek` class on assert. That is why i decided to move rumor picking logic into `World` class. Despite a pointer member, current solution is better IMO because it has lesser changeset and doesn't introduce a new entity.

What do you think?

2020-10-31 03:12 UTC, ihhub commented
> Hey @ihhub! Thanks for reviews and patience :)
> 
> Did all the changes you reqested, but after a dev test i found out that castles are initialized _before_ world, hence the list of rumors is empty during castles creation, what leads to a failure in `RumorOfWeek` class on assert. That is why i decided to move rumor picking logic into `World` class. Despite a pointer member, current solution is better IMO because it has lesser changeset and doesn't introduce a new entity.
> 
> What do you think?

Yes, it looks much cleaner.

2020-10-31 03:18 UTC, ihhub requested changes
Hi @tau3 , could you please take a look at given comments?

2020-10-31 03:18 UTC, ihhub commented on src/fheroes2/world/world.h
> +    const std::string * _rumor;
Please initialize this member with `nullptr` in the constructor of the class.

2020-10-31 03:18 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +}
A small modification is needed just to prevent some **bad** coding in the future (not your changes):
```
    if ( vec_rumors.empty() ) {
        _rumor = nullptr;
        assert( 0 );
        return;
    }
    else if ( vec_rumors.size() == 1 ) {
        _rumor = &vec_rumors.front();
        assert( 0 );
        return;
    }

    const std::string * current = _rumor;
    while ( current == _rumor ) {
        _rumor = Rand::Get( vec_rumors );
    }
```

In this case we can handle all corner cases.

2020-11-01 11:17 UTC, merged

2020-11-01 11:17 UTC, ihhub commented
@tau3 thank you very much for your contribution to the project!