Differentiate save files based on game type
ihhub/fheroes2 pull request #2122
Opened 2020-10-28 16:21 UTC by eos428

Solves #323 

So far the actual saving and loading seems alright for standard and campaign maps. However, I haven't saved the extra things needed for campaign maps.

@ihhub @idshibanov Any pointers on what to save? I think it should the player's hero data so maybe one of the `heroes` stream operators?

2020-10-28 17:55 UTC, idshibanov commented
> 
> @ihhub @idshibanov Any pointers on what to save? I think it should the player's hero data so maybe one of the `heroes` stream operators?

Things to keep track:
1. Maps finished to this point
2. Maps chosen (when there's a branch in campaign, especially switch between Good and Evil campaigns at 5th scenario)
3. Campaign awards earned (artifacts, creatures, "dwarven alliance" in Good campaign)
4. Current scenario bonus chosen (one of the three)
5. Optionally (not in original, but nice to have) we can save certain heroes (experience and skills only).

You don't have to add all of them right now, but make sure it will be easy to do in the future.

2020-10-29 17:04 UTC, ihhub commented
Hi @eos428 , it's a very good but critical change which also breaks the backward compatibility. We will definitely come back to this pull request after 0.8.3 which is just in few days.

2020-10-30 03:19 UTC, eos428 commented
No problem with that, take your time 👍 

There's also campaign data which I do partially for this PR so I'd imagine there'll be a lot to review here haha

2020-10-31 17:58 UTC, eos428 commented
Some update on the latest state of this PR:

- Added some initial code on campaign data (I expect a lot of refactoring once it's reviewed hehe)
- Did campaign scenario bonus. Probably no more than this for now, to prevent the PR over-scoping and becoming too big. Still have to test the troop bonus, but I tested the other two and it looks fine.

Things left to do for this PR:
- Implement IO on campaign data
- Code cleanup, of course
- Likely many variable and/or class renaming

2020-11-06 14:03 UTC, ihhub requested changes
Hi @eos428 , great stuff! We need to polish the code right now so move forward. Could you please take a look into given comments?

2020-11-06 14:03 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +        return ".savm";
If we already have a differentiation in file extension then there is no need to have separate directories for them. Also to keep backward compatibility I recommend to keep `.sav` for normal maps,

@idshibanov what's you opinion about this?

2020-11-06 14:03 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +        return ".savm";
Ideal situation if we have the same format for all saves and store some specific information in them related to the type of the save.

2020-11-06 14:03 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +        conf.game_difficulty << conf.game_type << conf.preferably_count_players << conf.debug << conf.opt_game << conf.opt_world << conf.opt_battle << conf.opt_addons
Aha! We already save a game type. Why don't we use it when we read saves? :)

2020-11-06 16:30 UTC, eos428 commented on src/fheroes2/system/settings.cpp
> +        conf.game_difficulty << conf.game_type << conf.preferably_count_players << conf.debug << conf.opt_game << conf.opt_world << conf.opt_battle << conf.opt_addons
I think this is not applicable when reading the file info, so I'm placing the game type in HeaderSAV now. However, bad news is that the newest solution I used also breaks backward compatibility.

2020-11-10 07:47 UTC, idshibanov commented on src/fheroes2/system/settings.cpp
> +        return ".savm";
I agree, we should keep using .sav, it is better to differentiate by file content. Splitting by directory is only for convenience if you have a lot of saves/autosave each campaign scenario.

2020-11-10 13:58 UTC, eos428 commented on src/fheroes2/system/settings.cpp
> +        return ".savm";
As of the latest commit, I'm reverting this back to just returning `.sav`. I still keep the directory splits though to prevent the autosaves overwriting each other and for convenience purposes.

2020-11-12 02:24 UTC, ihhub requested changes
Hi @eos428 I left few more comments. Please take a look.

2020-11-12 02:24 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +        uint32_t _amount;
Class is not allowed to have any public members. Please make it a structure or make these members private.

2020-11-12 02:24 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +        inline ScenarioBonusData getCurrentScenarioBonus() const
Please remove `inline` word. All methods within header file are interpret by a compiler as inline. Also there is no guarantee that a compiler will inline this function even if you mark it inline.

2020-11-12 02:24 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +        inline std::vector<std::string> getFinishedMaps() const
Should we pass this member by const reference instead of making a copy of it?

2020-11-12 02:24 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +            return earned_campaign_awards;
Should we pass this member by const reference instead of making a copy of it?

2020-11-12 02:24 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +        ScenarioBonusData current_scenario_bonus;
Please add `_` at the beginning of the file and use camelCase variable naming.

2020-11-12 02:24 UTC, ihhub commented on src/fheroes2/game/difficulty.cpp
> +    static cost_t startingResourcesSet[] = {{10000, 30, 99, 30, 99, 99, 99},
Why did we change it?

2020-11-12 02:24 UTC, ihhub commented on src/fheroes2/game/game_io.cpp
> +        HeaderSAV( const Maps::FileInfo & fi, bool loyalty, const int gt )
Please use more descriptive name rather than `gt` as another developer won't understand what it means.

2020-11-12 02:24 UTC, ihhub commented on src/fheroes2/game/game_loadgame.cpp
> +    const size_t arraySize = buttons.size();
Let's name it as `buttonCount`. Array is too common word and could mean anything.

2020-11-12 02:24 UTC, ihhub commented on src/fheroes2/game/game_newgame.cpp
> +    const size_t bonusChoiceCount = bonus_choices.size();
Please cast it to uint32_t as we use it below:
```
const uint32_t bonusChoiceCount = static_cast<uint32_t>( bonus_choices.size() ); // safe to do this
```

2020-11-12 02:51 UTC, eos428 commented on src/fheroes2/game/difficulty.cpp
> +    static cost_t startingResourcesSet[] = {{10000, 30, 99, 30, 99, 99, 99},
Oh shit, I forgot this was my way of testing mage guild until lv5 haha

2020-11-12 03:33 UTC, eos428 commented
Fixes done. A bit unsure if I misunderstood some of the reviews so let me know if I do!

2020-11-19 15:44 UTC, ihhub requested changes
Hi @eos428 , I left multiple comments. Could you please take a look and see if they make sense?

2020-11-19 15:44 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +        Data();
Please a constructor as a first method of the class.

2020-11-19 15:44 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +    class Data
It's not obvious what kind of Data this class for. We could rename this class or add a comment with an explanation.

2020-11-19 15:44 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +        , _earnedCampaignAwards( std::vector<std::string>() )
Please do like this:
```
: _finishedMaps()
, _earnedCampaignAwards()
```

2020-11-19 15:44 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +    ScenarioBonusData::ScenarioBonusData( uint32_t t, uint32_t st, uint32_t amt )
Please use the same variable names as in method declaration:
```
uint32_t type, uint32_t sub_type, uint32_t amount
```

2020-11-19 15:44 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +        uint32_t _sub_type;
Please use camelCase variable naming. It should be `_subType`.

2020-11-19 15:44 UTC, ihhub commented on src/fheroes2/game/game_newgame.cpp
> +        // TODO: shortened artifact names, so that we get "Thunder Mace" instead of "Thunder Mace of Dominion"
Do we need this commented code?

2020-11-19 15:44 UTC, ihhub commented on src/fheroes2/game/game_newgame.cpp
> +            Players & sortedPlayers = conf.GetPlayers();
Please use const reference here.

2020-11-19 15:44 UTC, ihhub commented on src/fheroes2/game/game_newgame.cpp
> +                Player & player = ( **it );
Please use const reference here.

2020-11-19 15:44 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.h
> +    Heroes * GetBestHero( void ) const;
Please remove then `const` modifier from the method.

2020-11-19 15:44 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +        dir = "save/standard";
I think `save` path is fine.

2020-11-19 15:44 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +        conf.game_difficulty << conf.game_type << conf.preferably_count_players << conf.debug << conf.opt_game << conf.opt_world << conf.opt_battle << conf.opt_addons
We could worry about this later. First we need to get a workable version and then we can figure out backward compatibility.

2020-11-19 15:44 UTC, ihhub commented on src/fheroes2/system/settings.h
> +    void SetCurrentCampaignScenarioBonus( const Campaign::ScenarioBonusData );
Please add a name of input argument and pass it by const reference.

2020-11-19 15:44 UTC, ihhub commented on src/fheroes2/system/settings.h
> +    void SetCurrentCampaignMapName( const std::string fileName );
Please pass the argument by const reference.

2020-11-19 15:44 UTC, ihhub commented on src/fheroes2/system/settings.h
> +    Campaign::Data campaign_data;
Please use camelCase naming `campaignData`.

2020-11-19 15:44 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +std::string Settings::GetSaveFileExtension( const int /*gameType*/ )
In this case let's just remove input argument for now.

2020-11-19 15:53 UTC, eos428 commented on src/fheroes2/game/game_newgame.cpp
> +        // TODO: shortened artifact names, so that we get "Thunder Mace" instead of "Thunder Mace of Dominion"
I'd say yes if we look into using shortened artifact names. Currently if we use "Thunder Mace of Dominion" the text will overflow. The idea is to iterate through the current scenario bonuses to display them, which is a no-go at the moment because of this issue.

2020-11-19 15:55 UTC, eos428 commented on src/fheroes2/system/settings.cpp
> +        dir = "save/standard";
My concern is that the autosaves for a game type could overwrite an autosave for another game type. If we are fine with that then I'd revert this change.

2020-11-19 16:01 UTC, ihhub commented on src/fheroes2/game/game_newgame.cpp
> +        // TODO: shortened artifact names, so that we get "Thunder Mace" instead of "Thunder Mace of Dominion"
Please try to use 4 arguments method of `void Blit( s32, s32, int maxw, fheroes2::Image & sf = fheroes2::Display::instance() ) const;` where for third argument you could specify the width of your text which will be truncated.

2020-11-19 16:01 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +        dir = "save/standard";
I mean only for the standard game while campaign and multiplayer will have separate directories.

2020-11-23 16:28 UTC, ihhub requested changes
Hi @eos428 , I left multiple comments. Could you please take a look?

2020-11-23 16:28 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +        const bool useAmount = _type != ScenarioBonusData::ARTIFACT;
I think this condition is not exactly valid for all cases. There is a possibility to give multiple artifacts. Should we do like this instead?
```
const bool useAmount = _amount > 1;
```

2020-11-23 16:28 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +        return useAmount ? _amount + " " + objectName : objectName;
Please use an implicit conversion to std::string:
```
return useAmount ? std::to_string( _amount ) + " " + objectName : objectName;
```

2020-11-23 16:28 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +        const bool useAmount = _type != ScenarioBonusData::ARTIFACT;
Also please put this variable just before return.

2020-11-23 16:28 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +        std::vector<std::string> _finishedMaps;
How about storing IDs of maps instead? For example, ***0, 1, 3, 4***? The name of the map is longer and is not unique.

2020-11-23 16:28 UTC, ihhub commented on src/fheroes2/dialog/dialog_file.cpp
>                      break;
Please remove this break as it's not reachable.

2020-11-23 16:28 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +        std::vector<std::string> _finishedMaps;
This could be useful when we display completed maps during campaign map selection.

2020-11-23 16:28 UTC, ihhub commented on src/fheroes2/game/game_loadgame.cpp
> +    // cursor
Please remove this comment.

2020-11-23 16:28 UTC, ihhub commented on src/fheroes2/game/game_loadgame.cpp
> +    const size_t buttonCount = buttons.size();
Please use an explicit conversion:
```
const size_t buttonCount = static_cast<uint32_t>( buttons.size() ); // it's safe to do this.
```

2020-11-23 16:28 UTC, ihhub commented on src/fheroes2/game/game_loadgame.cpp
> +        if ( le.MouseClickLeft( buttons[0].area() ) || HotKeyPressEvent( EVENT_BUTTON_STANDARD ) ) {
Here we're missing Multiplayer game type.

2020-11-23 16:28 UTC, ihhub commented on src/fheroes2/game/game_loadgame.cpp
> +        if ( le.MouseClickLeft( buttons[1].area() ) || HotKeyPressEvent( EVENT_BUTTON_CAMPAIN ) ) {
Please use `else if` to reduce the amount of checks.

2020-11-23 16:28 UTC, ihhub commented on src/fheroes2/game/game_newgame.cpp
> +    std::vector<Campaign::ScenarioBonusData> bonus_choices;
Let's please create a separate function in this file under unnamed namespace:
```
std::vector<Campaign::ScenarioBonusData> getCampaignBonusData( const bool isGoodCampaign, const int scenarioId )
{
    assert( scenarioId >= 0 );
    std::vector<Campaign::ScenarioBonusData> bonus;

    if ( isGoodCampaign ) {
        if ( scenarioId == 0 ) {
            bonus_choices.emplace_back( Campaign::ScenarioBonusData( Campaign::ScenarioBonusData::RESOURCES, Resource::GOLD, 2000 ) );
            bonus_choices.emplace_back( Campaign::ScenarioBonusData( Campaign::ScenarioBonusData::ARTIFACT, Artifact::THUNDER_MACE, 1 ) );
            bonus_choices.emplace_back( Campaign::ScenarioBonusData( Campaign::ScenarioBonusData::ARTIFACT, Artifact::MINOR_SCROLL, 1 ) );
        }
    }
    else {
        if ( scenarioId == 0 ) {
            // add code here as well
        }
    }
    return bonus;
}
```
at least we will have a base code for bonuses for all campaign scenarios.

2020-11-23 16:28 UTC, ihhub commented on src/fheroes2/game/game_newgame.cpp
> +                }
Please add an extra code:
```
default:
    assert( 0 );
```
in case of incorrect value.

2020-11-23 16:28 UTC, ihhub commented on src/fheroes2/game/game_newgame.cpp
> +                    kingdom.GetBestHero()->GetArmy().JoinTroop( Troop( Monster( scenario_bonus._subType ), scenario_bonus._amount ) );
I think this might not be the case. What if we have a supported hero has better army? Shall we add an extra field for this?

2020-11-24 12:01 UTC, eos428 commented on src/fheroes2/game/game_newgame.cpp
> +                    kingdom.GetBestHero()->GetArmy().JoinTroop( Troop( Monster( scenario_bonus._subType ), scenario_bonus._amount ) );
CMIIW but GetBestHero() gets the hero with the strongest army. If we want to return let's say, the hero with highest level, we probably should get it done in another PR

2020-11-28 16:37 UTC, ihhub requested changes
Hi @eos428 I left few comments and also some of previous comments haven't been addresses.

On top of this we have to modify `CURRENT_FORMAT_VERSION` and `LAST_FORMAT_VERSION` values. Please check `if ( binver > CURRENT_FORMAT_VERSION || binver < LAST_FORMAT_VERSION ) {` line in game_io.cpp file for more details.

2020-11-28 16:37 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +        friend StreamBase & operator>>( StreamBase &, ScenarioBonusData & );
Please do not skip input argument names. The old code has such style and it's a bad one as a reader won't understand what these will mean.

2020-11-28 16:37 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +        }
Do we need to make this method non-const?

2020-11-28 16:37 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +        }
Do we need to make this method non-const?

2020-11-28 16:37 UTC, ihhub commented on src/fheroes2/game/game_newgame.cpp
> +}
Please add an empty line at the end of the file.

2020-11-29 01:12 UTC, eos428 commented on src/fheroes2/campaign/campaign_data.h
> +        }
Thought it was impossible before scurrying stack overflow. Turns out I need to put const both at start and end of the function haha

2020-11-30 13:35 UTC, ihhub requested changes
Hi @eos428 I left multiple comments mostly regarding the architecture of your changes. Could you please take a look?

2020-11-30 13:35 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +#include <cassert>
Let's please use `assert.h` to comply with most of the code.

2020-11-30 13:35 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +        std::vector<int> _finishedMaps;
If yes we need some enumeration to hold campaign names.

2020-11-30 13:35 UTC, ihhub commented on src/fheroes2/dialog/dialog_file.cpp
> +                        result = Game::LOADGAME;
This is a bit confusing: does `Game::LOADGAME` belong to multiplayer mode?

2020-11-30 13:35 UTC, ihhub commented on src/fheroes2/game/game_newgame.cpp
> +    Campaign::ScenarioBonusData scenario_bonus;
Please name the variable in camelCase: `scenarioBonus`.

2020-11-30 13:35 UTC, ihhub commented on src/fheroes2/game/game_newgame.cpp
> +    std::vector<Campaign::ScenarioBonusData> bonus_choices = getCampaignBonusData( goodCampaign, 0 );
Please name the variable in camelCase: `bonusChoices`. Also since we don't modify the variable please make it const reference.

2020-11-30 13:35 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +        dir = "save/multiplayer";
We should explicitly define `TYPE_HOTSEAT` mode. Hot Seat and Network modes are both multiplayer modes but they're different.

2020-11-30 13:35 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +std::string Settings::GetSaveDir( const int gameType )
Since we're storing information about save type in save file should be store all saves under the same directory?

2020-12-01 01:06 UTC, eos428 commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +    std::sort( list2.begin(), list2.end(), Maps::FileInfo::TimeSorting );
It was for solving #1211

2020-12-01 01:14 UTC, eos428 commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +        savname.erase( savname.find_last_of( '.' ) );
Hmm you are right, back then this change was to accomodate the different save file formats (savc etc). This wasn't the best solution in the first place too on hindsight.

2020-12-01 01:17 UTC, eos428 commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +        savname.erase( savname.find_last_of( '.' ) );
But I think this wouldn't load a zip file since the files are loaded from `GetSortedMapsFileInfoList()` in `dialog_selectfile.cpp`, which looks for files with the correct extension.

2020-12-01 01:20 UTC, eos428 commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +                result = System::ConcatePath( Settings::GetSaveDir(), filename + Settings::GetSaveFileExtension() );
I agree, maybe in `maps_fileinfo`?

2020-12-01 01:24 UTC, eos428 commented on src/fheroes2/dialog/dialog_file.cpp
> +                        result = Game::LOADGAME;
I think this one is for unhandled game types at the moment. So instead of immediately jumping to the list of save files to load we get the load panel before that.

2020-12-01 01:33 UTC, eos428 commented on src/fheroes2/system/settings.cpp
> +std::string Settings::GetSaveDir( const int gameType )
If all saves are in the same directory, then the autosaves would write each other. So I wouldn't like to store all save files in the same directory.

2020-12-01 02:10 UTC, eos428 commented on src/fheroes2/campaign/campaign_data.h
> +        std::vector<int> _finishedMaps;
Yeah we should store the campaignID as well. It's added as of the latest commit

2020-12-02 14:25 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +std::string Settings::GetSaveDir( const int gameType )
Let's then do like in the original game: each save type has it's own file extension.

2020-12-02 16:16 UTC, eos428 commented on src/fheroes2/system/settings.cpp
> +std::string Settings::GetSaveDir( const int gameType )
Done, I'll keep the different save directory function around (but commented) just in case we want to revisit it again

2020-12-03 13:35 UTC, ihhub requested changes
Hi @eos428 I left multiple comments. Could you please take a look?

2020-12-03 13:35 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +    std::sort( list2.begin(), list2.end(), Maps::FileInfo::TimeSorting );
Can we please simplify this pull request and move the logic for #1211 into a separate one? In this way we can surely faster proceed with things :)

2020-12-03 13:35 UTC, ihhub commented on src/fheroes2/game/game_newgame.cpp
> +std::vector<Campaign::ScenarioBonusData> getCampaignBonusData( const bool isGoodCampaign, const int scenarioId )
Since we're handling campaign ID we can replace `isGoodCampaign` by it so later we can expand this function.

2020-12-03 13:35 UTC, ihhub commented on src/fheroes2/game/game_newgame.cpp
> +            Players & sortedPlayers = conf.GetPlayers();
This is still a valid comment.

2020-12-03 13:35 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +}
Please change it into:
```
std::string Settings::GetSaveDir()
{
    const char * dir = "save";
    return GetWriteableDir( dir );
}
```

2020-12-03 13:35 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +    return extension;
Please change it into:
```
if ( gameType & Game::TYPE_STANDARD )
    return ".sav";
else if ( gameType & Game::TYPE_CAMPAIGN )
    return ".savc";
else if ( gameType & Game::TYPE_HOTSEAT )
    return ".savh";

return ".savm";
```

2020-12-03 13:35 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +    if ( conf.game_type & Game::TYPE_CAMPAIGN )
Here is a potential bug which might need to address later: what if we load a save without this info? We can leave it as it is but please add a comment above: `// TODO: add verification logic`

2020-12-03 13:35 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +        // game config
Since we're changing this code please remove these useless comments. They don't add any extra information for a reader.

2020-12-03 13:35 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +                result = System::ConcatePath( Settings::GetSaveDir(), filename + Settings::GetSaveFileExtension() );
Let's put it into Game namespace in `game_io.h` and `game_io.cpp` files.

2020-12-03 13:35 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +        , _currentScenarioBonus()
_currentScenarioID and _campaignID are basic type variables. Please explicitly initialize them with values.

2020-12-03 13:35 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +    list1.ReadDir( Settings::GetSaveDir(), fileExtension, false );
We can combine these 2 lines:
```
const std::string fileExtension = Settings::GetSaveFileExtension();
list1.ReadDir( Settings::GetSaveDir(), fileExtension, false );
```
as we don't use `fileExtension` anywhere else in this function.

2020-12-03 13:35 UTC, ihhub commented on src/fheroes2/game/game_io.cpp
> +    const bool autosave = ( System::GetBasename( fn ) == "AUTOSAVE" + conf.GetSaveFileExtension() );
Once we move `GetSaveFileExtension` into Game namespace we can revert these changes (command order).

2020-12-03 13:35 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.h
> +    Heroes * GetBestHero( void ) const;
This is still a valid comment.

2020-12-03 13:42 UTC, eos428 commented on src/fheroes2/system/settings.cpp
> +    if ( conf.game_type & Game::TYPE_CAMPAIGN )
A similar check is present in operator>>, should that be enough or there may be something else?

2020-12-03 15:31 UTC, ihhub requested changes
Hi @eos428 I left multiple comments. Could you please take a look?

2020-12-03 15:31 UTC, ihhub commented on src/fheroes2/game/game_newgame.cpp
> +
Just a tiny correction: could you please remove this empty line and 354 line to group the code? It's more of cosmetic changes :)

2020-12-03 15:31 UTC, ihhub commented on src/fheroes2/maps/maps_fileinfo.cpp
> +bool Maps::FileInfo::TimeSorting( const FileInfo & fi1, const FileInfo & fi2 )
Please revert this function.

2020-12-03 15:31 UTC, ihhub commented on src/fheroes2/game/game_loadgame.cpp
> +
Please remove empty lines before `else if`. It might lead to a confusion for readers.

2020-12-03 15:31 UTC, ihhub commented on src/fheroes2/game/game_loadgame.cpp
> +            Dialog::Message( _( "Cancel" ), _( "Cancel back to the main menu." ), Font::BIG );
Please add `{`, `}` for all cases since you have cases with bodies.

2020-12-23 16:12 UTC, ihhub commented
Hi @eos428 ,
I think we need to make some change in order to support old saves and prevent incorrect old save loading.

In `bool Game::Load( const std::string & fn )` function we have the code:
```
HeaderSAV header;

// read raw info
fs >> strver >> binver >> header;
```
where we load a header. The issue here that modified HeaderSAV will read extra information from save file which is not present in the old saves.
To avoid this issue we need to modify the code to do this first:
```
fs >> strver >> binver;
```

after this we have to rename `HeaderSAV` into `HeaderSAVBase` and inherit from it another structure with our new parameter and call it (obviously) `HeaderSAV`. Then at the time of save loading we could decide which structure we need to use (we can utilize `std::unique_ptr<HeaderSAVBase>` for this) and load needed info. Please let me know if you have better ideas or questions.

2020-12-24 15:22 UTC, ihhub requested changes
Hi @eos428 , I left just few comments. Could you please take a look into them?

2020-12-24 15:22 UTC, ihhub commented on src/fheroes2/game/game_loadgame.cpp
> +    const size_t buttonCount = static_cast<uint32_t>( buttons.size() ); // it's safe to do this.
There is no need to do static_cast here. We can use `size_t` directly.

2020-12-24 15:22 UTC, ihhub commented on src/fheroes2/game/game_loadgame.cpp
> +    for ( uint32_t i = 0; i < buttonCount - 1; ++i ) {
Please replace `uint32_t` with `size_t`.

2020-12-24 15:22 UTC, ihhub commented on src/fheroes2/game/game_loadgame.cpp
> +        for ( uint32_t i = 0; i < buttonCount; ++i ) {
Please replace `uint32_t` with `size_t`.

2020-12-24 15:40 UTC, eos428 commented on src/fheroes2/game/game_io.cpp
> +        Maps::FileInfo info;
Do you mean by placing the variables before the HeaderSAVBase constructors?

2020-12-25 06:43 UTC, ihhub commented on src/fheroes2/game/game_io.cpp
> +        Maps::FileInfo info;
Yes. At the place where they were before changes.

2020-12-25 07:35 UTC, eos428 commented on src/fheroes2/game/game_io.cpp
> +        Maps::FileInfo info;
Ah I see. The latest commit should have addressed that, plus changing status from u16 to uint16_t

2020-12-27 05:43 UTC, ihhub requested changes
Hi @eos428 , things we need to change:
- pass game type to `Game::LoadSAV2FileInfo` function and check it with read game type. If it's different then return **false**
- revert changes in **dialog_selectfile.cpp** related to cursor. It breaks save file interaction
- fix loading hot head and multiplayer file types. I think we mixed them together

The rest of changes I corrected. Please take a look :)

2020-12-27 05:43 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectfile.cpp
> -    cursor.Hide();
Please revert back all changes related to `cursor.Hide()` and `cursor.Show()` as it breaks the behaviour of typing a name for new save.

2020-12-27 05:47 UTC, ihhub commented on src/fheroes2/game/game_loadgame.cpp
> +            if ( ListFiles::IsEmpty( GetSaveDir(), GetSaveFileExtension( Game::TYPE_MULTI ), false ) ) {
Here we are setting game type as multi but expecting to read hot seat.

2020-12-27 05:56 UTC, ihhub commented
Also @eos428 could you please squash all commits into one as GitHub behaves strangely with so many commits in a branch?

2020-12-27 07:32 UTC, eos428 commented
Hi @ihhub I have made the changes as you requested.

However, in loading multiplayer saves separately (hotseat and network) I had to make more changes to the code. Mostly copy-pasted stuff though, but I hope you don't mind with that.

Also, I have to revert cursor Show/Hide changes in `Game::LoadGame()` due to reverting the changes in `dialog_selectfile.cpp`.

2020-12-27 11:44 UTC, merged

2020-12-27 11:45 UTC, ihhub commented
@eos428 great thanks for your work! Well done!