2070 scenario selection
ihhub/fheroes2 pull request #2123
Opened 2020-10-28 22:03 UTC by emotionalamoeba

Map Id was being found from the config only the first time, when it was zero. 
To solve this I used the same search inside a function which is called when opening the select scenario dialog.

2020-10-29 17:20 UTC, ihhub commented on src/fheroes2/game/game_scenarioinfo.cpp
> +    if ( PrepareMapsFileInfoList( lists, ( conf.GameType( Game::TYPE_MULTI ) ) ) ) {
Could you please explain why we use TYPE_MULTI here? How about a single player game?

2020-10-29 17:43 UTC, emotionalamoeba commented on src/fheroes2/game/game_scenarioinfo.cpp
> +    if ( PrepareMapsFileInfoList( lists, ( conf.GameType( Game::TYPE_MULTI ) ) ) ) {
Sure,

TYPE_MULTI is a bitmask of TYPE_HOTSEAT and TYPE_NETWORK
conf.GameType checks the game_type value in the Settings for a collision with this mask, and return true if the current game type is multiplayer.

This boolean is passed into PrepareMapsFileInfoList, which will strip out multiplayer maps if the game type is not multiplayer.

2020-10-29 18:20 UTC, emotionalamoeba commented on src/fheroes2/game/game_scenarioinfo.cpp
> +    if ( PrepareMapsFileInfoList( lists, ( conf.GameType( Game::TYPE_MULTI ) ) ) ) {
Would you mind if I change conf.GameType( int f ) to conf.IsGameType( int f ) ?

I think that would make this more readable

2020-10-30 15:36 UTC, ihhub commented on src/fheroes2/game/game_scenarioinfo.cpp
> +    if ( PrepareMapsFileInfoList( lists, ( conf.GameType( Game::TYPE_MULTI ) ) ) ) {
@emotionalamoeba please go ahead and change it.

2020-10-31 10:27 UTC, ihhub commented
Hi @emotionalamoeba ,

please try multiplayer mode:
![image](https://user-images.githubusercontent.com/19829520/97776848-b2031680-1ba6-11eb-9bd4-ed040d5fcec7.png)

while selection shows this:
![image](https://user-images.githubusercontent.com/19829520/97776855-b9c2bb00-1ba6-11eb-8629-eb75245b07d8.png)

2020-10-31 12:19 UTC, emotionalamoeba commented
Looks like list filtering logic in maps_fileinfo still needs some work, so I'm learning more about that now :)

2020-11-01 11:56 UTC, ihhub commented
Hi @emotionalamoeba after your changes I see only one map in multiplayer mode :(

2020-11-01 12:25 UTC, emotionalamoeba commented
Hi @ihhub. Could you provide me a few maps I can use to test this? I only have a couple currently.

2020-11-02 14:33 UTC, ihhub commented
> Hi @ihhub. Could you provide me a few maps I can use to test this? I only have a couple currently.

Hi @emotionalamoeba sadly sharing maps (especially original) is against our project policy to avoid licence issues. I'll try to debug your changes and see what's happening.

2020-11-02 14:47 UTC, ihhub requested changes
Hi @emotionalamoeba I left multiple comments. Could you please take a look into them and discuss if you have a better idea?

2020-11-02 14:47 UTC, ihhub commented on src/fheroes2/maps/maps_fileinfo.cpp
> +    size_t humanOnlyColors = Color::Count( HumanOnlyColors() );
This variable is not used anywhere.

2020-11-02 14:47 UTC, ihhub commented on src/fheroes2/maps/maps_fileinfo.cpp
>  bool Maps::FileInfo::isMultiPlayerMap( void ) const
This method wasn't used anywhere and it simply doesn't work leading to filter all maps. A map could contain human and AIs. We can't use this method.

2020-11-02 14:47 UTC, ihhub commented on src/fheroes2/maps/maps_fileinfo.cpp
> +bool Maps::FileInfo::isSinglePlayerMap( void ) const
Please remove this method. There is no use of it.

2020-11-02 14:47 UTC, ihhub commented on src/fheroes2/maps/maps_fileinfo.cpp
> +    MapsFileInfoList::iterator it
Every map is a single-player map. We don't even need to sort maps for this case.

2020-11-02 14:47 UTC, ihhub commented on src/fheroes2/game/game_scenarioinfo.cpp
> +size_t GetSelectedMapId( MapsFileInfoList & lists )
This function should receive one extra argument: a number of human players. For each map please check the number of players which can be player by humans and filter accordingly.

2020-11-02 14:47 UTC, ihhub commented on src/fheroes2/maps/maps_fileinfo.cpp
> +        lists.resize( std::distance( lists.begin(), it ) );
Please revert back these changes.

2020-11-02 14:47 UTC, ihhub commented on src/fheroes2/maps/maps_fileinfo.cpp
> +        lists.resize( std::distance( lists.begin(), it ) );
Additionally, we could sort maps as it was proposed in game_scenarioinfo.cpp or we could do there. In this case please remove this old code related to `multi`, the input argument and `isMultiPlayerMap` method as all of them have no effect.

2020-11-02 15:01 UTC, emotionalamoeba commented on src/fheroes2/game/game_scenarioinfo.cpp
> +size_t GetSelectedMapId( MapsFileInfoList & lists )
This function currently only matches name to id and isn't used to filter the maps. Are you saying to add the number of players in case there are identically named maps, or to make this function also filter the map list for display?

2020-11-02 15:02 UTC, ihhub commented on src/fheroes2/game/game_scenarioinfo.cpp
> +size_t GetSelectedMapId( MapsFileInfoList & lists )
To filter map list.

2020-11-02 15:03 UTC, emotionalamoeba commented on src/fheroes2/game/game_scenarioinfo.cpp
> +size_t GetSelectedMapId( MapsFileInfoList & lists )
PrepareMapsFileInfoList could use humanPlayerCount to filter maps?

2020-11-02 15:05 UTC, ihhub commented on src/fheroes2/game/game_scenarioinfo.cpp
> +size_t GetSelectedMapId( MapsFileInfoList & lists )
Yes. As I described earlier we could use the filtering there so passing a number of human players instead of just bool makes more sense.

2020-11-02 17:54 UTC, emotionalamoeba commented on src/fheroes2/game/game_scenarioinfo.cpp
> +size_t GetSelectedMapId( MapsFileInfoList & lists )
I've reverted various changes I made due to a misunderstanding of multiplayer vs single player. I've now bought the full game, loaded the maps and can see that using the logic which was inside PrepareMapsFileInfoList the map list varies between single and multi player. It was already using the humanPlayerCount stored in the config inside the prepare maps as 'PreferablyCountPlayers', so there is no need to pass the same thing in as an argument. Someone who understands this stuff a lot better than me has already created that logic and I'm not equipped to improve it without knowing more about the intention/which maps are appearing erroneously.

2020-11-05 03:26 UTC, ihhub commented on src/fheroes2/game/game_scenarioinfo.cpp
> +size_t GetSelectedMapId( MapsFileInfoList & lists )
Thanks! I'll take a look. no worries.

2020-11-08 16:59 UTC, ihhub approved these changes

2020-11-09 11:02 UTC, merged

2020-11-09 11:03 UTC, ihhub commented
@emotionalamoeba thanks a lot for fixing this issue!