Play sound on shipwreck pickup
ihhub/fheroes2 pull request #2127
Opened 2020-10-29 11:02 UTC by tau3

Hi!

This one fixes #1971. There are also changes for inspections in corresponding funciton.

2020-10-29 17:11 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +            MP2::StringObject( object ),
To solve the issue with type casting please change `u32 obj` input argument to `int obj`.

2020-10-29 17:11 UTC, ihhub requested changes
Hi @tau3 I left only one comment. Could you please take a look?

2020-10-29 20:02 UTC, tau3 commented
Hi @ihhub! Yeah, that is obviously better. Done.

2020-10-31 03:09 UTC, merged

2020-10-31 03:09 UTC, ihhub commented
@tau3 a bunch of thanks for fixing this issue!