Remove SDL dependensy for IO classes (serialize.cpp)
ihhub/fheroes2 pull request #2133
Opened 2020-10-30 10:15 UTC by undef21

IO is independent from SDL now

2020-11-18 16:24 UTC, ihhub commented on src/engine/endian_h2.h
> +#ifndef ENDIAN_H2_H
Please add file header as shown [here](https://github.com/ihhub/fheroes2/wiki/Copyright-standard).

2020-11-18 16:25 UTC, ihhub commented on src/engine/endian_h2.h
> +#error "add your platform here"
Please rename this into `Unsupported platform`.

2020-11-18 16:26 UTC, ihhub commented on src/engine/serialize.cpp
> +        long pos = std::ftell( fp );
Please make this variable `const`.

2020-11-18 16:26 UTC, ihhub commented on src/engine/serialize.cpp
> +        long len = std::ftell( fp );
Please make this variable `const`.

2020-11-18 16:27 UTC, ihhub commented on src/engine/serialize.h
> +    std::FILE * fp;
Why don't we use `std::fstream` instead? Our project supports even C++11.

2020-11-20 17:51 UTC, undef21 commented on src/engine/endian_h2.h
> +#ifndef ENDIAN_H2_H
Done.

2020-11-20 17:51 UTC, undef21 commented on src/engine/endian_h2.h
> +#endif
Done

2020-11-20 17:51 UTC, undef21 commented on src/engine/endian_h2.h
> +#error "add your platform here"
Done.

2020-11-20 17:53 UTC, undef21 commented on src/engine/serialize.cpp
> +        long pos = std::ftell( fp );
Done.

2020-11-20 17:53 UTC, undef21 commented on src/engine/serialize.cpp
> +        long len = std::ftell( fp );
Done

2020-11-20 18:02 UTC, undef21 commented on src/engine/serialize.h
> +    std::FILE * fp;
SDL_RWops is lightweight wrapper for C file functions. Without global rewriting stream classes this approach the least invasive.

2020-11-28 14:44 UTC, ihhub requested changes
Hi @undef21 , I left multiple comments. Could you please take a look?

2020-11-28 14:44 UTC, ihhub commented on src/engine/serialize.cpp
> +    return fp;
Here we're introducing compilation warning. Please do this `return fp != NULL;`

2020-11-28 14:44 UTC, ihhub commented on src/engine/serialize.cpp
> +    fp = NULL;
Please correct into:
```
if ( fp ) {
    std::fclose( fp );
    fp = NULL;
}
```
We don't need to set a variable to NULL if its' already NULL.

2020-11-28 14:44 UTC, ihhub commented on src/engine/serialize.cpp
> +    if ( fp ) {
Please do this:
```
if ( !fp )
    return 0;

the rest of the code.
```

2020-11-28 14:44 UTC, ihhub commented on src/engine/serialize.cpp
> +    if ( fp ) {
Please do this:
```
if ( !fp )
    return 0;

the rest of the code.
```

2020-11-28 14:44 UTC, ihhub commented on src/engine/serialize.h
> +        return val;
Please change into:
```
        if ( !fp )
            return 0;
        T val;
        std::fread( &val, sizeof( T ), 1, fp );
        return val;
```
so then for non-opened stream we don't waste resources.

2020-11-28 14:44 UTC, ihhub commented on src/engine/serialize.h
> +    void putUint( T val )
Please add `const` qualifier for the input argument.

2020-11-28 14:44 UTC, ihhub commented on src/engine/serialize.h
>      StreamFile( const StreamFile & ) {}
Since we're changing this class please move this code under an explicit `private` section after `public`.

2020-11-28 14:44 UTC, ihhub commented on src/engine/serialize.cpp
> +uint16_t StreamFile::getBE16()
Since you changed types in source file please change them in header as well.

2020-11-28 15:18 UTC, undef21 commented on src/engine/serialize.cpp
> +    fp = NULL;
fclose() don't set fp to NULL

2020-12-10 17:22 UTC, ihhub requested changes
Hi @undef21 I left very minor comments. Please take a look.

2020-12-10 17:22 UTC, ihhub commented on src/engine/serialize.cpp
> +    long len = std::ftell( fp );
Please make these 2 variables `const`.

2020-12-10 17:22 UTC, ihhub commented on src/engine/serialize.h
> +    std::FILE * fp;
Please name it as `_file`.

2020-12-14 21:31 UTC, undef21 commented on src/engine/serialize.cpp
> +    long len = std::ftell( fp );
Done.

2020-12-14 21:32 UTC, undef21 commented on src/engine/serialize.h
> +    std::FILE * fp;
Done.

2020-12-22 15:51 UTC, merged

2020-12-22 15:52 UTC, ihhub commented
Well done @undef21 ! We're getting closer to a better version of the project!

2021-02-22 20:18 UTC, winterheart commented
I don't get point of change. Why to unbind SDL dependency from low IO operations, if SDL provides good cross-platform abstraction layer over system capabilities? Now endian_h2.h is bunch of ifdefs which narrows crossplatforming support only with these OSes, that defined there, instead SDL approach where you don't need to bother with LE/BE problems and can virtually do IO on every system that supports SDL.