Fix portraits/hero information display in battle only mode
ihhub/fheroes2 pull request #2150
Opened 2020-11-01 15:47 UTC by idshibanov

I used battle only mode very frequently for testing.

Morale and luck indicators have image restorer that was overwriting whole display. This caused cases when UI seemed unresponsive (i.e. you change a hero and it still shows the default one).

2020-11-02 14:59 UTC, ihhub requested changes
Hi @idshibanov in this case could you please update `HeroesIndicator::SetPos()` method and remove `bool skip_back` input parameter as there are no other cases which call it?

2020-11-03 12:34 UTC, ihhub commented
Hi @idshibanov with these changes we have such issue (check second hero moral icon):
![image](https://user-images.githubusercontent.com/19829520/97985892-dca5d700-1e13-11eb-8392-cfdba66fd905.png)

2020-11-03 21:20 UTC, idshibanov commented
> 
> 
> Hi @idshibanov with these changes we have such issue (check second hero moral icon):

Yes, I noticed it too that's why I did not remove `skip_back` parameter initially. We might need it or have to refactor `HeroesIndicator` to fix this as SpriteBack remembers the wrong background as you switch heroes.

2020-11-04 03:05 UTC, idshibanov commented
Updated to avoid resetting `SpriteBack` (and calling `SetPos`) on hero change. Had to refactor base class a bit for it to work. Also avoid deleting indicator on every change.

2020-11-04 10:25 UTC, ihhub commented on src/fheroes2/heroes/heroes_indicator.cpp
> +    hero = &h;
Hmm... passing a reference and taking a pointer from it is not a very good way to do. We should pass a pointer then.

2020-11-06 14:23 UTC, ihhub requested changes
Hi @idshibanov please change input references into pointers so the caller of class will know that this class works with pointers.

2020-11-07 08:38 UTC, idshibanov commented
Added additional checks for NULL pointers in classes (since now it's possible to instantiate one without a hero).

2020-11-08 06:47 UTC, merged

2020-11-08 06:47 UTC, ihhub commented
@idshibanov thank you very much for fixing this issue!