Strategic AI: general improvements
ihhub/fheroes2 pull request #2155
Opened 2020-11-01 19:57 UTC by idshibanov

- Optimize threat distance calculations. AI turns are twice as fast on average.
- Track map region stats for better decision-making.
- Improved castle build order (priority on gold income buildings).
- Recruit heroes in castles other than the first one in the list.
- Skip teleports if every exit was already explored.
- Protect high value (based on buildings built) castles first.
- Another round of adjustments to hero object values
- Move battle-related debugging logs from AI to BATTLE mode.
- Minor refactor of World post load logic.

2020-11-02 14:00 UTC, ihhub requested changes
Hi @idshibanov I left few comments. Could you please take a look?

2020-11-02 16:25 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +        size_t heroLimit = world.w() / Maps::SMALL + 1;
For now, yes. In the future AI will buy additional heroes where situation is right (to hunt down enemy hero for example).

2020-11-02 16:25 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +        size_t heroLimit = world.w() / Maps::SMALL + 1;
Also more heroes = slower turns. I don't think it will be able to use 8 effectively at this stage.

2020-11-02 16:50 UTC, ihhub reviewed
Hi @idshibanov , I left few more comments. Could you please take a look?

2020-11-02 16:50 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            const int objectCount = _regions[tile.GetRegion()].validObjects.size();
Please cache `tile.GetRegion()` call.

2020-11-02 16:50 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                else if ( hero.isVisited( tile ) )
No need else here.

2020-11-02 16:50 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            const int objectCount = _regions[tile.GetRegion()].validObjects.size();
Actually please cache `_regions[tile.GetRegion()]`

2020-11-02 16:50 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +            }
Please modify it into `assert( regionID < _regions.size() );` as release build will think that this is an empty if-body.

2020-11-02 16:50 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +            }
Also if we really want to check everything we need to make sure that `regionID` is not negative.

2020-11-02 16:50 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +            if ( enemy->second ) {
To minimize code changes we can do like this:
```
if ( enemy->second == 0 )
    continue;
```
so we'll have much less number of code line changes (I hope).

2020-11-02 16:50 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +                        lowestHeroCount = heroCount;
We could add a check to stop the loop:
```
if ( lowestHeroCount == 0 ) // can't be lower than 0
    break;
```

2020-11-03 03:04 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +            if ( enemy->second )
It's an opposite logic to what we had previously. Is it correct?

2020-11-03 03:37 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +            if ( enemy->second )
Yes, this is part of speeding up the calculations. I flipped the start and destination points to avoid re-caching inside pathfinder.

2020-11-03 03:45 UTC, merged

2020-11-03 03:46 UTC, ihhub commented
Excellent work, @idshibanov ! Well done!