Enemy castle view based on Thieves Guild count
ihhub/fheroes2 pull request #2187
Opened 2020-11-08 05:46 UTC by eos428

Solves #366.

Probably doing more than required for specifically this issue, but I think the changes to displaying army count overall are needed so that I don't make almost identical functions for doing it based on thieves guild count

2020-11-11 15:36 UTC, ihhub requested changes
Hi @eos428 I left multiple comments. Could you please take a look?

2020-11-11 15:36 UTC, ihhub commented on src/fheroes2/army/army.h
> +    static void DrawMonsterLines( const Troops & troops, uint32_t posX, uint32_t posY, uint32_t lineWidth, uint32_t drawType, uint32_t drawMethod = DRAW_SCOUTE,
Please put the new argument as a last one. It's easier to read changes.

2020-11-11 15:36 UTC, ihhub commented on src/fheroes2/army/army.h
> +    static void DrawMonsterLines( const Troops & troops, uint32_t posX, uint32_t posY, uint32_t lineWidth, uint32_t drawType, uint32_t drawMethod = DRAW_SCOUTE,
We have only 2 possible choices then why can't we just use a boolean input variable instead? Something like `isScouteView` will work.

2020-11-11 15:36 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +bool Castle::PredicateIsBuildThievesGuild( const Castle * castle )
Honestly, having so many functions which essentially call the same thing is not good.  Please remove this function and inside your std::count_if call just do like this:
```
return static_cast<uint32_t>( std::count_if( castles.begin(), castles.end(), []( const Castle * castle ) { return castle && castle->isBuild( BUILD_THIEVESGUILD ); } ) );
```
also just do the same for `PredicateIsBuildMarketplace` (remove this function). We use it only in one place after all.

2020-11-11 15:36 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +bool Castle::PredicateIsBuildBuilding( const Castle * castle, const uint32_t building )
After all changes we won't need this function as well.

2020-11-11 15:36 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +    const int thievesGuildCount = world.GetKingdom( conf.GetPlayers().current_color ).GetCountThievesGuild();
Instead of `conf.GetPlayers().current_color` please use `castle.GetColor()`.

2020-11-11 15:36 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +    else if ( castle.isFriends( conf.CurrentColor() ) ) {
Please cache `castle.GetColor()` value before line 646 and use it everywhere.

2020-11-12 02:20 UTC, eos428 commented on src/fheroes2/game/game.cpp
> +    return guildCount == 1 ? "???" : Army::SizeString( count );
I think this is correct.

If guildCount == 0, we wouldn't reach this function in the first place (the only thing displayed would be "Unknown")
If guildCount == 1 output "???"
If guildCount > 1 output Few, Several, Lots, etc

2020-11-12 02:58 UTC, eos428 commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +    const int thievesGuildCount = world.GetKingdom( conf.GetPlayers().current_color ).GetCountThievesGuild();
I believe these two are different things, no?

2020-11-12 09:31 UTC, eos428 commented on src/fheroes2/castle/castle.cpp
> +bool Castle::PredicateIsBuildThievesGuild( const Castle * castle )
Just chiming in my personal opinion - I like the more general IsBuildBuilding predicate, but not the  'middle-man' functions like IsBuildMarketplace and such. It's probably not expressed well in the previous commit with both around though.

2020-11-19 15:50 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +bool Castle::PredicateIsBuildThievesGuild( const Castle * castle )
In this case let's just use `PredicateIsBuildBuilding` and input argument. Populating functions just for single use is not a good idea so either we stay with a generic function like this or to add the code directly like I proposed initially.

2020-11-19 15:51 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +bool Castle::PredicateIsBuildThievesGuild( const Castle * castle )
You're right about having `PredicateIsBuildBuilding` function. The code looks ugly is we have all these lambda functions everywhere.

2020-11-19 16:03 UTC, ihhub reviewed
Hi @eos428 I left just few comments. Please take a look. I also tested the changes, they look good so we're almost ready to merging your changes :)

2020-11-28 14:28 UTC, merged

2020-11-28 14:28 UTC, ihhub commented
Great job, @eos428 ! Thanks a lot for fixing this issue!