Correctly reduce hero army after whirlpool (#1054)
ihhub/fheroes2 pull request #2208
Opened 2020-11-10 14:28 UTC by Killbrum

Fix for #1054.

But instead of dividing troops by 2 (as it was described in #1054) each time, I've decided to stay with fandom.com explanation (https://mightandmagic.fandom.com/wiki/Whirlpool). In this implementation, there is a 1/3 chance that the weakest troop will be divided by 2. In case if troops count is already one -> troop will be removed.

2020-11-10 16:58 UTC, idshibanov commented
Can confirm the logic, it's a 33% chance to lose some creatures in original game. Sometimes articles online can be misleading.

2020-11-12 17:30 UTC, LeHerosInconnu commented
I confirm that in the original game, the Whirlpool divides (33% chance) the weakest troop of creatures by half until there is only one creature left in the hero's army (this last creature is never removed).

2020-11-14 06:27 UTC, ihhub requested changes
Hi @Killbrum I left few comments. Could you please take a look?

2020-11-14 06:27 UTC, ihhub commented on src/fheroes2/ai/ai_hero_action.cpp
> +            if ( troop->GetCount() == 1 ) {
As it was explained please add an extra check for different troop count. If we have only one active slot we can't discharge it.

2020-11-14 14:36 UTC, LeHerosInconnu commented on src/fheroes2/ai/ai_hero_action.cpp
> +            if ( troop->GetCount() == 1 ) {
Hello @ihhub,

> Hi @LeHerosInconnu, could you please tell us the behavior of whirlpool when an army has just 1 creature?

A hero must always have at least one creature in his army.
So, if there is only one creature in the hero's army, the hero will always conserve this creature when he will use the whirlpool.

2020-11-18 03:14 UTC, ihhub requested changes
Hi @Killbrum , it is almost done. Please check few given comments.

2020-11-18 03:14 UTC, ihhub commented on src/fheroes2/ai/ai_hero_action.cpp
> +        if ( hero.GetArmy().GetMonstersCount() <= 1 ) {
Please use `GetCount()` method instead as it return the number of slots in army.

2020-11-18 03:14 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +u32 Troops::GetMonstersCount() const
Please remove this method in favor of existing `GetCount()`.

2020-11-18 07:28 UTC, Killbrum commented on src/fheroes2/ai/ai_hero_action.cpp
> +        if ( hero.GetArmy().GetMonstersCount() <= 1 ) {
They are slightly different. GetCount() returns, as you said, the number of active slots while I need to get the total amount of army. 

Otherwise, I will need to do this

```
Troop * troop = hero.GetArmy().GetWeakestTroop();
assert( troop );
if ( !troop )
  return;

if ( hero.GetArmy().GetCount() == 1 && troop->GetCount() == 1 ) {
  return;
}
```

Like the main idea that even if you have one active slot, you still able to reduce that slot down to 1. If the above code works for you - okay, no issues, will do.

Mainly I would like to avoid hard constructions inside the main action block.

2020-11-18 15:15 UTC, ihhub commented on src/fheroes2/ai/ai_hero_action.cpp
> +        if ( hero.GetArmy().GetMonstersCount() <= 1 ) {
My concern is that having `GetCountMonsters` and `GetMonstersCount` is really confusing. These names are identical :)

I don't recollect any other situation where we need to total creature count in the army so your last proposed solution would work perfectly without creating an extra function. To make it clear please add following comment before the second if-check:
```
// If an army has only one slot with 1 creature then we don't need to do anything.
```
This makes the code easier to understand.

2020-11-18 20:02 UTC, Killbrum commented on src/fheroes2/ai/ai_hero_action.cpp
> +        if ( hero.GetArmy().GetMonstersCount() <= 1 ) {
okay, I see, thank you so much! :)

Will fix tomorrow, sorry I have a hard week

2020-11-21 02:54 UTC, merged

2020-11-21 02:54 UTC, ihhub commented
@Killbrum good job! Thanks a lot for fixing this issue!