Update VisualStudio 2015 project settings and configuration
ihhub/fheroes2 pull request #2219
Opened 2020-11-14 17:51 UTC by Killbrum

This PR is the first step to update VisualStudio project files and settings. The main purpose of this PR is to synchronize settings between platforms and configurations, explicitly adds WIN and _DEBUG/NDEBUG definitions. Also, changes touch Release configuration to produce way more optimized builds.

As a next step, I'm going to reorganize the VisualStudio folder with their properties and add a project file for the latest VS

2020-11-14 19:45 UTC, Killbrum commented
My apologies, will back tomorrow and check why it fails, sorry.

2020-11-16 04:09 UTC, ihhub commented
Hi @Killbrum is this PR ready for review?

2020-11-16 06:09 UTC, Killbrum commented
@ihhub yep, it's ready :) check it please

2020-11-18 16:06 UTC, ihhub requested changes
Hi @Killbrum the main concern of these changes is that we just explicitly set options of VS which are set by default. Could you please correct me if I'm wrong?

2020-11-18 16:06 UTC, ihhub commented on fheroes2.vcxproj
> +      <MultiProcessorCompilation>true</MultiProcessorCompilation>
Hi @Killbrum please put put common properties into `VisualStudio/common.props` file which has `ClCompile` section as well. It will make the code to be shorter and easier to maintain.

2020-11-18 16:06 UTC, ihhub commented on fheroes2.vcxproj
> +      <ExceptionHandling>Sync</ExceptionHandling>
Aren't these options (except multiprocessor) defined by default in Visual Studio if you don't explicitly set them?

2020-11-19 14:43 UTC, Killbrum reviewed
Hmm strange because I didn't modify the file manually. Okay, will fix

2020-11-19 14:56 UTC, ihhub commented
> Hmm strange because I didn't modify the file manually. Okay, will fix

It happens :) We are not blaming anyone ;)

2020-11-19 15:02 UTC, Killbrum commented
> Hi @Killbrum the main concern of these changes is that we just explicitly set options of VS which are set by default. Could you please correct me if I'm wrong?

Mainly I would like to do the next things:
- explicitly set options where possible (it might not be really obvious what exactly VS applies during the build). Also, VS usually changes build options from "in use" to "deprecated" and "removed". Of course, it doesn't happen each year, but it happens.
- use props only for includes and macro. I would like to keep compiler/linker settings per project, not per props file. Usually, props files visually hide settings, and it's not crystally clear what happens while you will not look at props.

2020-11-19 15:07 UTC, Killbrum commented on fheroes2.vcxproj
> +      <MultiProcessorCompilation>true</MultiProcessorCompilation>
I would rather like to remove ClCompile section from common.props and move it as per project settings. Mainly there should be different projects for different executables. Like map editor, maybe some utilities, and all of them might use different compilation settings. But at the same time, includes and macros will be the same.

2020-11-19 15:11 UTC, Killbrum commented on fheroes2.vcxproj
> +      <ExceptionHandling>Sync</ExceptionHandling>
To be honest, it's sort of result of testing different options. From the beginning, I've tried to enable RTCc for debug builds and enable Warning Level 4 (threat as error) but actually wasn't able to. I still want to enable those options, but it will be done in a separate PR.

If you want, I can remove those "unused" settings.

2020-11-24 08:53 UTC, Killbrum commented
@ihhub please give me a few more days. It's not hard to process everything, and literally, I try to check this repo every day. But to be honest, I have a hard week(s) at work now because we need to finish our releases in time and ship it to our customers before the new year. Actually, we're working even on weekends to finish it faster... that's why haven't any time to look into this issue

2020-11-24 08:56 UTC, ihhub commented
Hi @Killbrum , no rush. Take your time. We don't have a strict timeline for every pull request :)

2020-11-28 08:30 UTC, Killbrum commented
I'm so sorry for such a long delay. Changes are small, but I physically hadn't enough time. So, mainly I've removed all settings that were set implicitly. Please tell me whether do I need to make other changes? Thank you!

2020-11-28 12:22 UTC, ihhub commented on fheroes2.vcxproj
> +      <MultiProcessorCompilation>true</MultiProcessorCompilation>
Hmmm... I don't think we will have something different in settings for Editor or tool as they will share the same code (ignore current Editor implementation, we're going to remove it). In this case, there're no obvious reasons to make separation of compilation settings leading to code duplication.

2020-11-28 17:33 UTC, Killbrum commented on fheroes2.vcxproj
> +      <MultiProcessorCompilation>true</MultiProcessorCompilation>
I see your point. Right, the main idea of .props files is to share the same settings between projects, and since we've only one project (right now), there is nothing to share, and we can keep everything in one props file. But at the same time, those settings might be very generic (or we can end up with creating separate props for each case), and it will not guarantee that all project files will not contain their own settings.

So I would like to propose keeping macro, path, and generic definitions in props files, but project settings keep in project files. Like we already have to possible targets (game exe and map editor), and who knows what will be in a year or two :)

But anyway. Please tell me your final opinion, and let's move forward. It is not so critical to spend too much time on this.

2020-11-29 17:18 UTC, ihhub commented on fheroes2.vcxproj
> +      <MultiProcessorCompilation>true</MultiProcessorCompilation>
Hmm... Let me think a bit.

2020-11-29 20:15 UTC, Killbrum commented on fheroes2.vcxproj
> +      <MultiProcessorCompilation>true</MultiProcessorCompilation>
Ah, it doesn't worth :) I'll update review tomorrow

2020-12-10 12:28 UTC, ihhub commented
Hi @Killbrum , I receive this warning:
```
cl : Command line warning D9030: '/Gm' is incompatible with multiprocessing; ignoring /MP switch
```
on Visual Studio 2015 for Debug build.

2020-12-10 12:37 UTC, ihhub commented on fheroes2.vcxproj
> +      <PreprocessorDefinitions>_WIN64;%(PreprocessorDefinitions)</PreprocessorDefinitions>
We don't use this macro anywhere. Please remove it.

2021-02-12 04:43 UTC, ihhub commented
The compilation with these changes increased in 3 times :(

2021-03-29 13:03 UTC, merged

2021-03-29 13:03 UTC, ihhub commented
@Killbrum , thank you very much for your conitrbution to the project!

2021-04-05 20:52 UTC, Killbrum commented
> The compilation with these changes increased in 3 times while game's speed remains the same :(

Yep, it happens because "Whole Program Optimization" (/GL) enables optimization between modules (.obj / .lib / etc.), and since fheroes contains different third-parties that are physically linked to the project - compilation and linking time significantly increases. Usually, all mid/large-sized third parties are separated from the main binary (DLL, for example). In the current case, they are linked to the project. Thus/GL tries to optimize the game engine and all other third parties, which takes time.

2021-04-05 20:53 UTC, Killbrum commented
My apologies for being absent. I had too many problems due to COVID, work, certification and etc. Will try to get back to my fixes and bring something useful.

2021-04-05 23:55 UTC, ihhub commented
@Killbrum , no worries 🙂