Reset buttons when cursor move out (#387)
ihhub/fheroes2 pull request #2230
Opened 2020-11-16 12:48 UTC by vasilenkoalexey

Suggestion to fix #387

2020-11-16 16:12 UTC, ihhub commented
Hi @vasilenkoalexey I will check your PRs soon. Don't worry if they aren't reviewed yet.

2020-11-16 21:21 UTC, vasilenkoalexey commented
>Don't worry if they aren't reviewed yet.
Of course, we do it all at our leisure!

2020-11-18 16:21 UTC, ihhub requested changes
Hi @vasilenkoalexey good job! Could you please take a look at given comments? Also one more question: what will happen when we pressed the button, moved away from button area and then return back?

2020-11-18 16:21 UTC, ihhub commented on src/fheroes2/gui/interface_buttons.h
> +        void ResetButtons( void );
Please remove `void` input parameter. It's a legacy code style.

2020-11-18 16:21 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +        }
Please modify the existing code instead otherwise we're adding more CPU cycles having the same code:
```
// cursor over buttons area
else if ( ( !isHiddenInterface || conf.ShowButtons() ) && le.MouseCursor( buttonsArea.GetRect() ) ) {
    if ( Cursor::POINTER != cursor.Themes() )
        cursor.SetThemes( Cursor::POINTER );
    res = buttonsArea.QueueEventProcessing();
}
```

will be
```
// cursor over buttons area
else if ( ( !isHiddenInterface || conf.ShowButtons() ) && le.MouseCursor( buttonsArea.GetRect() ) ) {
    if ( Cursor::POINTER != cursor.Themes() )
        cursor.SetThemes( Cursor::POINTER );
    res = buttonsArea.QueueEventProcessing();
    isCursorOverButtons = true;
}
```

Then just before `// Stop moving hero first` we could declare a variable
```
const bool prevIsCursorOverButtons = isCursorOverButtons;
isCursorOverButtons = false;
```

and then here we will have the code:
```
if ( prevIsCursorOverButtons && !isCursorOverButtons)
{
    buttonsArea.ResetButtons();
}
```

2020-11-18 16:21 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +    bool isCursorOverButtons = le.MouseCursor( buttonsArea.GetRect() );
Please assign this variable to false. There is no way to have a case when we start a game with pressed buttons.

2020-11-19 11:23 UTC, vasilenkoalexey commented
> what will happen when we pressed the button, moved away from button area and then return back?

Buttons stay released, because `ResetPressLeft()` was called in `ResetButtons()`.

2020-11-19 14:57 UTC, ihhub commented
Nice! Now the code is much cleaner. Thank you!

2020-11-19 15:03 UTC, merged

2020-11-19 15:03 UTC, ihhub commented
@vasilenkoalexey thank you so much for your valuable contribution to the project!