fix mouse coordinates sdl2 bug (#1091) prototype
ihhub/fheroes2 pull request #2238
Opened 2020-11-17 16:39 UTC by undef21

This pr was tested for SDL2 Linux build (with fake fullscreen).

2020-11-18 15:56 UTC, ihhub requested changes
Hi @undef21 I left multiple comment in this pull request. Could you please take a look into them?

2020-11-18 15:56 UTC, ihhub commented on src/engine/screen.cpp
> +                    SDL_SetRenderDrawColor( _renderer, 0, 0, 0, 0 );
Do we need to do this for every call? I think we need to do this once we go to fullscreen mode.

2020-11-18 15:56 UTC, ihhub commented on src/engine/screen.cpp
> +                    SDL_RenderClear( _renderer );
Do we need this call as well here?

2020-11-18 15:56 UTC, ihhub commented on src/engine/screen.cpp
> +        return fheroes2::Size( DM.w, DM.h );
We should cache this variable at the time of switching into fullscreen mode. `SDL_GetCurrentDisplayMode` call is not an instant while we're calling this method thousands of times per second.

2020-11-18 15:56 UTC, ihhub commented on src/engine/screen.h
> +#include "SDL.h"
We must never do this. The idea behind screen is to hide the implementation only in source file. Please revert this change.

2020-11-18 15:56 UTC, ihhub commented on src/engine/screen.h
> +            return _engine->isFullScreen();
Could you please explain why do we need this change? `engine().isFullScreen()` will do the same.

2020-11-18 15:56 UTC, ihhub commented on src/engine/localevent.cpp
> +        const fheroes2::Display & d = fheroes2::Display::instance();
Please name it as `display`. It's a common name in the while code.

2020-11-18 15:56 UTC, ihhub commented on src/engine/localevent.cpp
> +            const float aspect = std::min( float( outSize.width ) / d.width(), float( outSize.height ) / d.height() );
Please use C++ style casting only.

2020-11-18 15:56 UTC, ihhub commented on src/engine/localevent.cpp
> +            mouse_cu.x = ( mouse_cu.x - ( float( outSize.width ) - aspect * d.width() ) / 2. ) / aspect;
Here we're introducing compilation warning by converting from double to short. Please fix it.

2020-11-18 15:56 UTC, ihhub commented on src/engine/localevent.cpp
> +            mouse_cu.y = mouse_cu.y / float( outSize.height ) * d.height();
Could you please explain why do we have different formulas for X and Y coordinates?

2020-11-18 15:56 UTC, ihhub commented on src/engine/localevent.cpp
> +#if SDL_VERSION_ATLEAST( 2, 0, 0 ) && !defined( __WIN32__ )
This is an incorrect way to do. Android might have no problems in fullscreen mode for example. Please add defines related to target OS only.

2020-11-18 15:56 UTC, ihhub commented on src/engine/localevent.cpp
> +            const float aspect = std::min( float( outSize.width ) / d.width(), float( outSize.height ) / d.height() );
Also here we calculate aspect ratio every time. Why don't we cache this aspect ratio instead of output size?

2020-11-20 16:27 UTC, undef21 commented on src/engine/screen.cpp
> +                    SDL_SetRenderDrawColor( _renderer, 0, 0, 0, 0 );
Deleted.

2020-11-20 16:29 UTC, undef21 commented on src/engine/screen.cpp
> +                    SDL_RenderClear( _renderer );
Probably, yes. Without this call we have different graphical artifacts after switching between windowed and full screen modes.

2020-11-20 16:30 UTC, undef21 commented on src/engine/screen.cpp
> +        return fheroes2::Size( DM.w, DM.h );
Done

2020-11-20 16:30 UTC, undef21 commented on src/engine/screen.h
> +#include "SDL.h"
Deleted

2020-11-20 16:31 UTC, undef21 commented on src/engine/screen.h
> +            return _engine->isFullScreen();
Yes. engine().isFullScreen() is used now. Deleted.

2020-11-20 16:32 UTC, undef21 commented on src/engine/localevent.cpp
> +        const fheroes2::Display & d = fheroes2::Display::instance();
Deleted. In other place 'display' is used.

2020-11-20 16:32 UTC, undef21 commented on src/engine/localevent.cpp
> +            const float aspect = std::min( float( outSize.width ) / d.width(), float( outSize.height ) / d.height() );
Done

2020-11-20 16:33 UTC, undef21 commented on src/engine/localevent.cpp
> +            mouse_cu.x = ( mouse_cu.x - ( float( outSize.width ) - aspect * d.width() ) / 2. ) / aspect;
Done.

2020-11-20 16:44 UTC, undef21 commented on src/engine/localevent.cpp
> +            mouse_cu.y = mouse_cu.y / float( outSize.height ) * d.height();
If we want save OG aspect ratio, we have black rectangles left and right. For X we subtract left black area width, then scale X. Y-dimension completely fits into the screen, so Y is scaled only.

2020-11-20 16:44 UTC, undef21 commented on src/engine/localevent.cpp
> +#if SDL_VERSION_ATLEAST( 2, 0, 0 ) && !defined( __WIN32__ )
Deleted.

2020-11-20 16:44 UTC, undef21 commented on src/engine/localevent.cpp
> +            const float aspect = std::min( float( outSize.width ) / d.width(), float( outSize.height ) / d.height() );
Done.

2020-11-20 16:45 UTC, undef21 commented on src/engine/screen.h
> +#include "SDL.h"
Deleted.

2020-11-20 16:45 UTC, undef21 commented on src/engine/screen.cpp
> +                    SDL_SetRenderDrawColor( _renderer, 0, 0, 0, 0 );
Deleted.

2020-11-20 16:48 UTC, undef21 commented on src/engine/screen.cpp
> +                    SDL_RenderClear( _renderer );
Probably, yes. Without SDL_RenderClear here, I have different graphical artifacts when switch windowed and full screen modes.
![artefact1](https://user-images.githubusercontent.com/71143197/99826338-4854a780-2b69-11eb-8344-7e5227f375cb.png)
![artefact2](https://user-images.githubusercontent.com/71143197/99826380-54d90000-2b69-11eb-928a-fec5bb3ac032.png)

2020-11-20 16:48 UTC, undef21 commented on src/engine/screen.cpp
> +        return fheroes2::Size( DM.w, DM.h );
Done

2020-11-20 16:49 UTC, undef21 commented on src/engine/screen.h
> +            return _engine->isFullScreen();
engine().isFullScreen() is used now. Deleted.

2020-11-20 16:49 UTC, undef21 commented on src/engine/localevent.cpp
> +            const float aspect = std::min( float( outSize.width ) / d.width(), float( outSize.height ) / d.height() );
Done

2020-11-20 16:50 UTC, undef21 commented on src/engine/localevent.cpp
> +            mouse_cu.x = ( mouse_cu.x - ( float( outSize.width ) - aspect * d.width() ) / 2. ) / aspect;
Done

2020-11-27 03:12 UTC, ihhub requested changes
hi @undef21 , I left few comments. Please take a look.

2020-11-27 14:24 UTC, undef21 commented on src/engine/screen.cpp
> +            const float precission = .001;
precission deleted.

2020-11-27 14:25 UTC, undef21 commented on src/engine/screen.cpp
> +                _transformVals = {( dm.w - scale * width ) / 2, 0., scale};
Done.

2020-11-27 14:25 UTC, undef21 commented on src/engine/screen.cpp
> +            const float deviceAspect = static_cast<float>( dm.w ) / dm.h;
Done.

2020-11-27 14:26 UTC, undef21 commented on src/engine/screen.cpp
> +            if ( isFullScreen() && _transformVals._isScalingNeeded ) {
bool variables in _transformVals are deleted at now.

2020-11-27 14:26 UTC, undef21 commented on src/engine/screen.cpp
> +                const float outputAspect = static_cast<float>( dm.h ) / height;
Done.

2020-11-27 14:26 UTC, undef21 commented on src/engine/screen.cpp
> +        void _calculateTransformVals()
Done.

2020-11-27 14:27 UTC, undef21 commented on src/engine/screen.cpp
> +            float _aspect;
Done.

2020-11-27 14:33 UTC, undef21 commented on src/engine/screen.cpp
> +        struct
What is C++ declaration of a structure?

`struct _transformValsType
{
    double a;
    double b;
} _transformVals;` ?

2020-11-28 15:33 UTC, ihhub commented on src/engine/screen.cpp
> +        struct
Please declare like this:
```
struct TransformParam
{
    double offsetX;
    double offsetY;
    double scale;
};
```

and then in the class use `TransformParam _transformVals`.

2020-11-29 04:12 UTC, ihhub requested changes
Hi @undef21 I left multiple comments regarding code improments. Please take a look.

2020-11-29 04:12 UTC, ihhub commented on src/engine/screen.cpp
> +            const double aspectsDiff = static_cast<double>( dm.w ) / dm.h - static_cast<double>( width ) / height;
This is still slightly incorrect as we can't compare float / double values in auch a manner.

To avoid this issue please use this way: we can interpret your equation in 3 parts:
(a / b) - (c / d) > 0
(a / b) - (c / d) < 0
(a / b) - (c / d) = 0

In this case let's do some math changes:
(a / b) > (c / d)
(a / b) < (c / d)
(a / b) = (c / d)

Going further:
(a * d) > (c * b)
(a * d) < (c * b)
(a * d) = (c * b)

As you can see all values can be used as integers so we don't need any precision.

2020-11-30 18:44 UTC, undef21 commented on src/engine/screen.cpp
> +                    SDL_RenderClear( _renderer );
This line and SDL_RenderSetLogicalSize line are wrapped with #ifndef __WIN32__ now.

2020-11-30 18:52 UTC, undef21 commented on src/engine/screen.cpp
> +            SDL_SetHint( SDL_HINT_RENDER_SCALE_QUALITY, "linear" );
Put this functions before texture creation because if put them after texture creation, then scale filtering stops working.

2020-12-01 05:43 UTC, ihhub commented
Hi @undef21 the changes are approved. We'll need some time to verify them before merging into master.

2020-12-02 02:21 UTC, ihhub requested changes
Hi @undef21 all works perfectly! Just please make some more changes to make the code be even better ;)

2020-12-02 02:21 UTC, ihhub commented on src/engine/localevent.cpp
>  const Point & LocalEvent::GetMouseCursor( void )
Since this method is one line of code please put it in header to make the inline method.

2020-12-02 02:21 UTC, ihhub commented on src/engine/screen.cpp
> +#ifndef __WIN32__
Please remove this macro and the macro below. Some Windows resolutions need it after all.

2020-12-02 02:21 UTC, ihhub commented on src/engine/screen.cpp
> +                    SDL_RenderClear( _renderer );
This call needs a check for return value like it's done for the rest of functions.

2020-12-02 02:21 UTC, ihhub commented on src/engine/screen.cpp
> +            SDL_RenderSetLogicalSize( _renderer, width_, height_ );
This call needs to check the return value.

2020-12-02 02:21 UTC, ihhub commented on src/engine/screen.cpp
> +            SDL_SetHint( SDL_HINT_RENDER_SCALE_QUALITY, "linear" );
From the documentation this function might fail if there's another hint set so maybe for now we don't check its return value.

2020-12-02 14:26 UTC, undef21 commented on src/engine/localevent.cpp
>  const Point & LocalEvent::GetMouseCursor( void )
Done.

2020-12-02 14:27 UTC, undef21 commented on src/engine/screen.cpp
> +#ifndef __WIN32__
Done.

2020-12-02 14:27 UTC, undef21 commented on src/engine/screen.cpp
> +                    SDL_RenderClear( _renderer );
Done.

2020-12-02 14:27 UTC, undef21 commented on src/engine/screen.cpp
> +            SDL_RenderSetLogicalSize( _renderer, width_, height_ );
Done.

2020-12-02 14:30 UTC, undef21 commented on src/engine/screen.cpp
> +            SDL_SetHint( SDL_HINT_RENDER_SCALE_QUALITY, "linear" );
This function shouldn't stop application, probably. But we will know if something will be wrong).

2020-12-02 15:23 UTC, merged

2020-12-02 15:23 UTC, ihhub commented
Great work @undef21 !