Shadow near hero
ihhub/fheroes2 pull request #2250
Opened 2020-11-19 18:21 UTC by vasilenkoalexey

Suggestion to fix #772. Sure, code need some refractor.

2020-11-20 00:25 UTC, ihhub commented
Hi @vasilenkoalexey this is not a correct way to fix the issue. We're modifying the core code just to fix this single case. We must fix the root of problem which is drawing some objects near hero twice.

2020-11-20 20:40 UTC, vasilenkoalexey commented
> We're modifying the core code just to fix this single case.

It seems to me, `transform` parameter its just feature like `flip` parameter. I also found only single case when `flip` used (in `Castle::WellRedrawInfoArea`) but nonetheless, this parameter already in core code. 

>We must fix the root of problem which is drawing some objects near hero twice.

But we should draw some objects at dependency tiles on top of hero, this is necessary to ensure the correct display of pseudo perspective.

In any case, if you have an idea how to do it in a different way, let's discuss and try to implement.

2020-11-21 10:48 UTC, vasilenkoalexey commented
Another important moment.
In the proposed solution, the rendering process looks like this:
1. Objects with shadow are drawn.
2. Drawn a hero with shadow.
3. Re-drawn objects near the hero but without shadow.
Thus, the shadow transformation is not applied to the drawn hero.

In any other cases, even without re-rendering of objects near the hero:
1. Drawn a hero with a shadow
2. Drawn objects with a shadow near the hero
Then, when drawing objects, the shadow transformation is applied to the already drawn hero, including the already drawn hero's shadow (which means that part of the hero's image and his shadow will become darker). Thus, we have the same problem, but it is not so obvious.
It seems to me that the most correct and flexible solution is to allow control over the process of drawing the shadow by disabling transformation.

2020-11-22 02:09 UTC, ihhub commented
Reasons why the proposed solution is debatable:
- we introduce an extra check in a core function for every pixel during image rendering. In this case even to draw a map of the default size we are going to do extra thousands or even millions operations. This change absolutely will slowdown performance of rendering. We can't do that
- we still draw the same object twice (with or without shadow), wasting resources.

The root of the problem lies in `void Heroes::Redraw` method and more specifically after the comment `// redraw dependences tiles`. If you comment the code below you could see that the hero is drawn above every object and that's why this hacky code tries to fix it. The correct solution would be to draw a hero when we are drawing objects. However, the way how it's done right now in `void Interface::GameArea::Redraw` method might be incorrect. The idea behind of all of this is to draw every object once but in right order without hacks and workarounds.

2020-11-26 11:48 UTC, ihhub commented
Hi @vasilenkoalexey , I think I have a better idea:
- first step is to identify hero's positions in `void Interface::GameArea::Redraw` method before any drawings (bottom or top)
- during drawing bottom and top objects check whether they are related to hero's position. If yes, don't draw.
- after bottom and top drawings draw all heroes like it's done right now
- also we might need to modify `void Heroes::Redraw` method as well

In this case we don't draw any objects twice. What do you think?

2020-11-26 20:46 UTC, vasilenkoalexey commented
I have implemented a small part of the idea. Now we not drawing bottom, bottom left and bottom right tiles near hero. As i see we dont need to touch top tiles (although I may be wrong but i cant find such case).
So, we will need to completely draw these tiles when we draw the heroes. But there are some concerns - if there are several heroes nearby, perhaps we will draw over the already drawn hero. Perhaps the list of heroes must first be sorted by XY coordinates.

2020-11-27 18:26 UTC, vasilenkoalexey commented
Now three bottom tiles are drawn after the hero. Everything looks correct, there are no dark shadows, but I'm not completely sure. For example, if two heroes side by side we get the following situation. It seems that we must look for other heroes near current hero.

![shadow](https://user-images.githubusercontent.com/24250224/100476486-bf081c80-30f6-11eb-8f09-72e984a263e0.png)

2020-11-28 15:34 UTC, ihhub commented
> Now three bottom tiles are drawn after the hero. Everything looks correct, there are no dark shadows, but I'm not completely sure. For example, if two heroes side by side we get the following situation. It seems that we must look for other heroes near current hero.
> 
> ![shadow](https://user-images.githubusercontent.com/24250224/100476486-bf081c80-30f6-11eb-8f09-72e984a263e0.png)

What's the problem with this situation? A shadow of one hero onto another? I think we have a plenty of places where we have the same situation. Correct me, @idshibanov .

2020-11-28 15:59 UTC, ihhub requested changes
Hi @vasilenkoalexey , I left few comments. Please take a look. My main left concern is performance after your changes. I'm still thinking how to improve it.

2020-11-28 15:59 UTC, ihhub commented on src/fheroes2/heroes/heroes_move.cpp
> +    /*
Shall we remove then this code if there's no need it in?

2020-11-28 15:59 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +                        const Maps::Tiles & tileTop = world.GetTiles( Maps::GetDirectionIndex( tile.GetIndex(), Direction::TOP ) );
Please cache `tile.GetIndex()` into a separate variable.

2020-11-28 15:59 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +                        if ( tileTop.GetHeroes() ) {
We can combine it into `redrawNear = tileTop.GetHeroes() != NULL;` so it's just easier to read.

2020-11-28 18:06 UTC, vasilenkoalexey commented
> What's the problem with this situation? A shadow of one hero onto another? I think we have a plenty of places where we have the same situation.

No. There is dark shadow right under palm, because we draw this tile twice when we draw each hero. But I already fixed it in last commit.
Before
![shadow](https://user-images.githubusercontent.com/24250224/100522778-7ca91300-31bc-11eb-94ad-cdde4f7674e0.png)
After
![shadow1](https://user-images.githubusercontent.com/24250224/100522780-7fa40380-31bc-11eb-8727-ddb36e3d3e6d.png)

> The current implementation even before your changes has the same effect. We can fix it separately.
Agreed. For example first we can draw all heroe's shadow and then all heroes itself.

2020-11-28 18:10 UTC, vasilenkoalexey commented on src/fheroes2/heroes/heroes_move.cpp
> +    /*
> Shall we remove then this code if there's no need it in?

As it seems to me, yes. But I have a fear that now we are drawing some objects in the wrong order. Perhaps there are any test maps for testing object rendering cases?

2020-11-28 18:12 UTC, vasilenkoalexey commented on src/fheroes2/gui/interface_gamearea.cpp
> +                        if ( tileTop.GetHeroes() ) {
Shure, i will

2020-11-28 18:23 UTC, vasilenkoalexey commented
> My main left concern is performance after your changes. I'm still thinking how to improve it.

I can improve the logic of using methods `Maps::isValidDirection Maps::GetDirectionIndex`, now it looks a little ugly. On the other hand, I can collect statistics of time execution for the `Interface::GameArea::Redraw` method by Visual Studio profiler

2020-12-02 04:16 UTC, ihhub requested changes
Hi @vasilenkoalexey , I left multiple comments. Could you please take a look into them?

2020-12-02 19:09 UTC, vasilenkoalexey commented on src/fheroes2/heroes/heroes_move.cpp
> +            if ( tileRight.GetHeroes() == NULL ) {
> Is it intentional?

![shadow3](https://user-images.githubusercontent.com/24250224/100919161-7c758400-34ea-11eb-8d30-08c4c1c824a2.png)
Yes. We need it to fix case when two heroes are horizontally across one tile.Then the shadow in the middle at the bottom is drawn twice. But to fix it we should only one additional validation, from left to right or from right to left, otherwise the tile will not be drawn. So, I have implemented left to right validation.

2020-12-02 19:37 UTC, vasilenkoalexey commented
Hi @ihhub, I have committed some changes according to your comments.

2020-12-07 13:16 UTC, ihhub requested changes
Hi @vasilenkoalexey all looks good except one issue: a hero goes under the road:
![image](https://user-images.githubusercontent.com/19829520/101355385-73f9c080-38d1-11eb-88ed-507530e59c0f.png)
We forgot that we draw roads too :)

2020-12-08 21:23 UTC, vasilenkoalexey commented
> We forgot that we draw roads too :)

Hi, @ihhub! I think not only road. Some objects on bottom tile should be rendered before and some after (for eaxmple, crown of a tree or roof of buildings) hero. This is most likely why the original code contains a function `SkipRedrawTileBottom4Hero`. So i need a little more time to decide how to implement it in our solution.

2020-12-11 20:42 UTC, vasilenkoalexey commented
So, I implemented rendering of the ground surface on the bottom tile before the hero, and rendering of objects after. This solved the problem with the road, and with artifacts too.

2020-12-12 10:27 UTC, ihhub commented
@vasilenkoalexey looks like it works flawlessly! I will test a little more and merge it if everything is fine :)

2020-12-12 10:31 UTC, ihhub commented
Oh, no. We have to deal with boats :(
![image](https://user-images.githubusercontent.com/19829520/101981462-fefb0200-3ca7-11eb-8f2f-a2234c010472.png)

Also there's a part of building is missing:
![image](https://user-images.githubusercontent.com/19829520/101981477-205bee00-3ca8-11eb-8b41-afc4e512c9e8.png)

2020-12-12 18:56 UTC, vasilenkoalexey commented
I hope all cases covered now. Another important note - looks like we should pass `isPuzzleDraw`, `drawMonstersAndBoats`, `drawBottom`, `drawTop` to `Heroes::Redraw`. I can implement it in this PR. Or can create another.

2020-12-12 20:55 UTC, vasilenkoalexey commented
Possible this PR will also fix #2179

2020-12-13 15:55 UTC, ihhub commented
Hi @vasilenkoalexey this case is not hasn't been fixed:
![image](https://user-images.githubusercontent.com/19829520/101981477-205bee00-3ca8-11eb-8b41-afc4e512c9e8.png)

2020-12-17 20:14 UTC, vasilenkoalexey commented
Now I think that the code should be completely rewritten. The task turned out to be more difficult and I need more time to find the right solution...

2021-01-03 09:07 UTC, ihhub commented
Hi @vasilenkoalexey , could you please fix merging conflicts for this pull request? Also after some time of thinking about this problem I think the best way would be to draw a hero by parts like other objects: top and bottom (and middle?). Right now we are trying to do some voodoo magic here and there by separating hero's drawings from others. Maybe we should approach the problem with this idea? What do you think?

2021-01-04 15:21 UTC, vasilenkoalexey commented
> Maybe we should approach the problem with this idea? What do you think?

Hi, @ihhub. I think it's better to close this pr and create a new one. I cannot say now which solution needs to be implemented, since the basic problem is to find the correct order for rendering objects near the hero. So, I will create a new pr when I come up with a solution.

2021-01-17 15:43 UTC, vasilenkoalexey commented
Closed because needed another solution

2021-01-17 15:43 UTC, closed without merging