Adventure map, Freeman's Foundry window, wrong title and wrong text
ihhub/fheroes2 pull request #2253
Opened 2020-11-21 20:24 UTC by shprotru

Fix for #2245

2020-11-22 02:33 UTC, ihhub requested changes
Hi @shprotru , I left few comments in this pull request. Please take a look.

2020-11-22 02:33 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +        std::vector<bool> hasSuitableMonster;
Please declare this variable after with known size of next variable.

2020-11-22 02:33 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +            if ( heroArmy.HasMonster( *iter ) )
We could combine all these 3 lines into one without if-check.

2020-11-22 02:33 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +            if ( heroArmy.HasMonster( *iter ) )
We could combine all these 3 lines into one without if-check.

2020-11-22 02:33 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +                mons.push_back( freemansfoundryMonsToUpgrade[iter] );
Please use emplace_back instead.

2020-11-22 06:29 UTC, shprotru commented on src/fheroes2/heroes/heroes_action.cpp
> +    const std::size_t monstersLimit = 3;
done

2020-11-22 06:29 UTC, shprotru commented on src/fheroes2/heroes/heroes_action.cpp
> +        for ( std::size_t iter = 0; iter < hasSuitableMonster.size(); ++iter ) {
done

2020-11-22 06:29 UTC, shprotru commented on src/fheroes2/heroes/heroes_action.cpp
> +        std::vector<bool> hasSuitableMonster;
done

2020-11-22 06:29 UTC, shprotru commented on src/fheroes2/heroes/heroes_action.cpp
> +            if ( heroArmy.HasMonster( *iter ) )
done

2020-11-22 06:29 UTC, shprotru commented on src/fheroes2/heroes/heroes_action.cpp
> +            if ( heroArmy.HasMonster( *iter ) )
done

2020-11-22 06:29 UTC, shprotru commented on src/fheroes2/heroes/heroes_action.cpp
> +                mons.push_back( freemansfoundryMonsToUpgrade[iter] );
done

2020-11-22 06:31 UTC, shprotru commented
![Снимок экрана от 2020-11-22 09-30-20](https://user-images.githubusercontent.com/53114202/99896860-87881300-2ca5-11eb-91b8-106d9f7ddb00.png)
![Снимок экрана от 2020-11-22 09-30-48](https://user-images.githubusercontent.com/53114202/99896861-88b94000-2ca5-11eb-85f9-5a9c34182834.png)
![Снимок экрана от 2020-11-22 09-31-11](https://user-images.githubusercontent.com/53114202/99896862-88b94000-2ca5-11eb-92da-8d23603babf1.png)

2020-11-26 10:02 UTC, ihhub requested changes
Hi @shprotru excellent work! Just few more things to polish and we are good to go!

2020-11-26 10:02 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +    const std::vector<Monster> freemansfoundryMonsToUpgrade( {Monster( Monster::SWORDSMAN ), Monster( Monster::PIKEMAN ), Monster( Monster::IRON_GOLEM )} );
Here we have an issue: we create 2 arrays but utilize only one. Why don't we like this:
```
const std::vector<Monster> monsToUpgrade;
```

and then in case scenario assign `{Monster( Monster::OGRE ), Monster( Monster::ORC ), Monster( Monster::DWARF )}` or emplace back all values.

2020-11-26 10:02 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
>      std::vector<Monster> mons;
Since we already hold Monster instance in the vector below we should just keep pointers here to avoid memory copy.

2020-11-26 10:02 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +            if ( !heroArmy.HasMonster( monsToUpgrade->at( i ) ) )
Once we use just one vector we could use `[]` operator.

2020-11-26 10:23 UTC, shprotru commented on src/fheroes2/heroes/heroes_action.cpp
> +        for ( std::size_t i = 0; i < monsToUpgrade->size(); ++i ) {
how about `auto` here? Let compiler decide what type is better for him.

2020-11-26 17:46 UTC, shprotru commented on src/fheroes2/heroes/heroes_action.cpp
> +bool ActionToUpgradeArmy( Army & army, const Monster & mons, std::string & str1, std::string & str2, const bool & combineWithAnd )
done

2020-11-26 17:50 UTC, shprotru commented on src/fheroes2/heroes/heroes_action.cpp
> +    if ( monsToUpgrade != nullptr && !monsToUpgrade->empty() ) {
done

2020-11-26 17:53 UTC, shprotru commented on src/fheroes2/heroes/heroes_action.cpp
> +    const std::vector<Monster> freemansfoundryMonsToUpgrade( {Monster( Monster::SWORDSMAN ), Monster( Monster::PIKEMAN ), Monster( Monster::IRON_GOLEM )} );
done

2020-11-26 17:54 UTC, shprotru commented on src/fheroes2/heroes/heroes_action.cpp
>      std::vector<Monster> mons;
check, please, am I done this right way?

2020-11-26 17:54 UTC, shprotru commented on src/fheroes2/heroes/heroes_action.cpp
> +            if ( !heroArmy.HasMonster( monsToUpgrade->at( i ) ) )
done

2020-11-27 04:17 UTC, merged

2020-11-27 04:18 UTC, ihhub commented
@shprotru thank you very much for your great work!