fix portrait layout for surrending dialog
ihhub/fheroes2 pull request #2266
Opened 2020-11-28 11:34 UTC by undef21

resolve issue #2259

2020-11-28 15:30 UTC, ihhub requested changes
Hi @undef21 are buttons on the same position as in the original game?

2020-11-28 15:30 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    fheroes2::Button btnDecline( pos_rt.x + 295, pos_rt.y + 152, icn, 2, 3 );
The distance from left edge of the window to left button is 75 pixels while for the right - 65.

2020-11-28 16:20 UTC, undef21 commented on src/fheroes2/battle/battle_dialogs.cpp
> +    fheroes2::Button btnDecline( pos_rt.x + 295, pos_rt.y + 152, icn, 2, 3 );
Yes.
I was saw first screenshot from issue #2259.

![compare](https://user-images.githubusercontent.com/71143197/100520294-1c12d980-31ae-11eb-9003-cac4780c58dd.png)

Base OG screenshot from issue. The part over red line is from fheroes2.

2020-12-02 14:04 UTC, merged

2020-12-02 14:04 UTC, ihhub commented
@undef21 a huge thanks for fixing these issues! Good work!