"Town portal" spell window should have evil UI elements
ihhub/fheroes2 pull request #2272
Opened 2020-11-28 15:59 UTC by shprotru

Fix #2240

2020-11-28 16:04 UTC, ihhub requested changes
Hi @shprotru I left few comment. Please take a look.

2020-11-28 16:04 UTC, ihhub commented on src/fheroes2/agg/icn.h
Please remove this empty line.

2020-11-28 16:04 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> +    const fheroes2::Sprite & upperPart = fheroes2::AGG::GetICN( conf.ExtGameEvilInterface() ? ICN::LISTBOX_EVIL : ICN::LISTBOX, 0 );
Please cache `const int listId = conf.ExtGameEvilInterface() ? ICN::LISTBOX_EVIL : ICN::LISTBOX;`.

2020-11-28 16:04 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> +    const fheroes2::Sprite & upperPart = fheroes2::AGG::GetICN( conf.ExtGameEvilInterface() ? ICN::LISTBOX_EVIL : ICN::LISTBOX, 0 );
Also please cache `conf.ExtGameEvilInterface()` as well.

2020-11-28 16:04 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> +    const int btnICNID = conf.ExtGameEvilInterface() ? ICN::SYSTEME : ICN::SYSTEM;
Please name it as `buttonIcnId` for just easier reading.

2020-11-28 16:09 UTC, shprotru commented on src/fheroes2/agg/icn.h
done

2020-11-28 16:09 UTC, shprotru commented on src/fheroes2/heroes/heroes_spell.cpp
> +    const fheroes2::Sprite & upperPart = fheroes2::AGG::GetICN( conf.ExtGameEvilInterface() ? ICN::LISTBOX_EVIL : ICN::LISTBOX, 0 );
done

2020-11-28 16:10 UTC, shprotru commented on src/fheroes2/heroes/heroes_spell.cpp
> +    const int btnICNID = conf.ExtGameEvilInterface() ? ICN::SYSTEME : ICN::SYSTEM;
done

2020-11-28 16:39 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> +    int32_t totalHeight = rtAreaItems.height + 6;
Could you please explain why do we need this change?

2020-11-28 17:04 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> +    int32_t totalHeight = rtAreaItems.height + 6;
Ah, you just moved it below.

2020-11-28 17:12 UTC, shprotru commented on src/fheroes2/heroes/heroes_spell.cpp
> +    int32_t totalHeight = rtAreaItems.height + 6;
yeah, `totalHeight` moved closer to place where it's used

2020-11-29 02:53 UTC, merged

2020-11-29 02:53 UTC, ihhub commented
@shprotru thank you very much for fixing this issue!