No sound of vanishing AI hero, after losing a battle
ihhub/fheroes2 pull request #2275
Opened 2020-11-28 20:30 UTC by shprotru

Fix #2271

2020-11-29 10:12 UTC, ihhub requested changes
Hi @shprotru could you please take a look into few given comments?

2020-11-29 10:12 UTC, ihhub commented on src/fheroes2/heroes/heroes_move.cpp
> +    return true;
I think we can do this in one line:
```
return Interface::Basic::Get().GetGameArea().GetVisibleTileROI() & GetCenter();
```

2020-11-29 10:12 UTC, ihhub commented on src/fheroes2/heroes/heroes.h
> +    bool IsInROI() const;
This is a helper function which must be `private`. Also please name it from a non-capital letter.

2020-11-29 10:13 UTC, ihhub commented on src/fheroes2/heroes/heroes.h
> +    bool IsInROI() const;
Also name it as `isInVisibleMapArea`. ROI is not very descriptive for readers.

2020-11-29 11:29 UTC, shprotru commented on src/fheroes2/heroes/heroes_move.cpp
> +    return true;
done

2020-11-29 11:29 UTC, shprotru commented on src/fheroes2/heroes/heroes.h
> +    bool IsInROI() const;
done

2020-11-30 12:17 UTC, ihhub commented
Hi @shprotru with all these changes what's the benefit of doing it? From performance point of view we have a slower code.

2020-12-02 03:29 UTC, ihhub commented
Hi @shprotru please update the logic of the newly created method to fix #2307.

2020-12-10 17:15 UTC, merged

2020-12-10 17:16 UTC, ihhub commented
@shprotru thank you very much for this enhancement!