Fix freeze while buying hero
ihhub/fheroes2 pull request #2278
Opened 2020-11-28 21:38 UTC by vasilenkoalexey

Fix freeze while buying hero in castle. I'm not sure that issue exists.

2020-12-22 15:28 UTC, ihhub requested changes
Hi @vasilenkoalexey I left multiple comments here. Could you please take a look?

Also did you test building construction in Barbarian castle? This castle has many road dependencies so previous code was a bit hacky to make everything work.

2020-12-22 15:28 UTC, ihhub commented on src/fheroes2/castle/castle.h
> +            , build( BUILD_NOTHING ){};
Being little pedantic: please remove `;` here as this is an implementation of a method.

2020-12-22 15:28 UTC, ihhub commented on src/fheroes2/castle/castle.h
> +        uint32_t build;
Please add an underscore character for your members of the class like `_alpha` and `_build`. Most of the code does not follow this standard yet as it was written before us but we are slowly adapting to it.

2020-12-22 15:28 UTC, ihhub commented on src/fheroes2/castle/castle.h
> +        void StartFadeBuilding( uint32_t build );
Please make this input argument as `const` as we do not modify it.

2020-12-22 15:28 UTC, ihhub commented on src/fheroes2/castle/castle_building.cpp
> +    return ( alpha == 255 );
I think the correct one would be `return alpha >= 255;` as according to your loop above the value might be more if someone else changes the increment.

2020-12-22 15:28 UTC, ihhub commented on src/fheroes2/castle/castle_building.cpp
> +        alpha = 256;
This is an example why we need to modify the logic of **IsFadeDone** method as it will return `false` after calling this method.

2020-12-22 15:28 UTC, ihhub commented on src/fheroes2/castle/castle.h
> +        uint32_t GetBuild() const;
Please make these methods inline: just move the implementation here. No need to add `inline` word as it's redundant. The same applies to `IsFadeDone` method.

2020-12-22 15:28 UTC, ihhub commented on src/fheroes2/castle/castle_dialog.cpp
> +                            uint32_t build = fadeBuilding.GetBuild();
Please make this variable `const`.

2020-12-22 15:28 UTC, ihhub commented on src/fheroes2/castle/castle_dialog.cpp
> +        else if ( alphaHero == 240 ) {
Is there a situation when `alphaHero > 240`? Do we need to handle such case?

2020-12-22 15:28 UTC, ihhub commented on src/fheroes2/castle/castle_dialog.cpp
> +    int alphaHero = 241;
It is unknown why we assign the value 241 to this variable. Shall we assign 255 instead?

2020-12-22 21:37 UTC, vasilenkoalexey commented on src/fheroes2/castle/castle_dialog.cpp
> +                            uint32_t build = fadeBuilding.GetBuild();
I am reusing this variable below in code `build = OpenTown();`. But if really necessary I can create another const variable.

2020-12-25 18:57 UTC, vasilenkoalexey commented on src/fheroes2/castle/castle.h
> +        uint32_t GetBuild() const;
Done

2020-12-25 18:59 UTC, vasilenkoalexey commented on src/fheroes2/castle/castle.h
> +        void StartFadeBuilding( uint32_t build );
Done

2020-12-25 18:59 UTC, vasilenkoalexey commented on src/fheroes2/castle/castle.h
> +        uint32_t build;
Done

2020-12-25 18:59 UTC, vasilenkoalexey commented on src/fheroes2/castle/castle.h
> +            , build( BUILD_NOTHING ){};
Done

2020-12-25 19:00 UTC, vasilenkoalexey commented on src/fheroes2/castle/castle_dialog.cpp
> +    int alphaHero = 241;
I slightly changed the logic of drawing the hero, it became simpler and clearer now

2020-12-25 19:06 UTC, vasilenkoalexey commented
> Also did you test building construction in Barbarian castle? This castle has many road dependencies so previous code was a bit hacky to make everything work.

I have done some buildings and did not find any problems, i didn't modify `RedrawRoadConnection` but just started using alpha in the dialog loop.

2021-01-10 16:22 UTC, ihhub requested changes
Hi @vasilenkoalexey , there is an issue while building building connected with roads. For example, I built Coliseum and road crossing appeared at the very end of animation:
![image](https://user-images.githubusercontent.com/19829520/104128495-d21f3500-53a2-11eb-97d1-65faae99ddcd.png)

2021-01-10 16:22 UTC, ihhub commented on src/fheroes2/castle/castle_building.cpp
> +    this->_build = build;
Please remove `this->` usage. It's redundant.

2021-01-10 16:22 UTC, ihhub commented on src/fheroes2/castle/castle_dialog.cpp
> +        if ( alphaHero != 255 ) {
To be safe let's change this condition into `if ( alphaHero >= 255 ) {` to prevent any future change effect.

2021-01-10 19:59 UTC, vasilenkoalexey commented
> Hi @vasilenkoalexey , there is an issue while building building connected with roads. For example, I built Coliseum and road crossing appeared at the very end of animation:
I fixed it :)

2021-01-10 20:00 UTC, vasilenkoalexey commented on src/fheroes2/castle/castle_dialog.cpp
> +        if ( alphaHero != 255 ) {
done

2021-01-10 20:00 UTC, vasilenkoalexey commented on src/fheroes2/castle/castle_building.cpp
> +    this->_build = build;
done

2021-01-12 15:20 UTC, ihhub commented
Hi @vasilenkoalexey ,
I just open a castle window and see this:
![image](https://user-images.githubusercontent.com/19829520/104333567-5c46d500-552c-11eb-84f4-44ee8ecd41f5.png)

2021-01-13 16:30 UTC, vasilenkoalexey commented
> Hi @vasilenkoalexey ,
> I just open a castle window and see this:

Because
`if ( alphaHero != 255 ) {` replaced by  ` if ( alphaHero >= 255 ) {`

A little explanation of the implementation
In the process of fade, we increase the alpha by a certain delta. Its mean alpha value at some point may turn out to be more than 255.
That is, alpha can have three states
alphaHero<255 fade in progress
alphaHero>255 alpha has reached the limit and fade process must be stopped (set alphaHero to 255)
alphaHero==255 fade process stopped

So, If you agreed with this implementation, I will return `!=` or we can discuss another implementation

2021-01-14 14:42 UTC, ihhub commented
> > Hi @vasilenkoalexey ,
> > I just open a castle window and see this:
> 
> Because
> `if ( alphaHero != 255 ) {` replaced by ` if ( alphaHero >= 255 ) {`
> 
> A little explanation of the implementation
> In the process of fade, we increase the alpha by a certain delta. Its mean alpha value at some point may turn out to be more than 255.
> That is, alpha can have three states
> alphaHero<255 fade in progress
> alphaHero>255 alpha has reached the limit and fade process must be stopped (set alphaHero to 255)
> alphaHero==255 fade process stopped
> 
> So, If you agreed with this implementation, I will return `!=` or we can discuss another implementation

Are you referring to castle_dialog.cpp file, line 650 `if ( alphaHero >= 255 ) {`?

2021-01-14 14:51 UTC, vasilenkoalexey commented
> Are you referring to castle_dialog.cpp file, line 650 `if ( alphaHero >= 255 ) {`?

Exactly

2021-01-14 14:52 UTC, ihhub commented
> > Are you referring to castle_dialog.cpp file, line 650 `if ( alphaHero >= 255 ) {`?
> 
> Exactly

Please change it then.

2021-01-15 23:40 UTC, vasilenkoalexey commented
I think comparing alpha with 255 looks ugly, so i created enum. And some code improvement since we are using modern C++.

2021-01-16 13:13 UTC, ihhub reviewed
Hi @vasilenkoalexey , I left just one comment. Could you please take a look?

2021-01-16 13:13 UTC, ihhub commented on src/engine/image.h
> +        transaprent = 0
`transparent` is misspelled but the biggest issue is creation of this enumeration. We have a lot of places with 255 and 0 usages while in this pull request we changed only few. In my opinion it's an overkill to use enumeration for minimum and maximum values of `uint8_t` type. Could we please go without the enumeration?

2021-01-16 14:05 UTC, vasilenkoalexey commented on src/engine/image.h
> +        transaprent = 0
Done

2021-01-17 00:44 UTC, ihhub commented
Hi @vasilenkoalexey , I tested the changes. Only one thing is broken: at the time of hero purchase monster sprites in his army are not fading as he. Before the change it was the case.

2021-01-17 13:04 UTC, vasilenkoalexey commented
> Hi @vasilenkoalexey , I tested the changes. Only one thing is broken: at the time of hero purchase monster sprites in his army are not fading as he. Before the change it was the case.

Fixed :)

2021-01-17 13:28 UTC, merged

2021-01-17 13:28 UTC, ihhub commented
@vasilenkoalexey thank you so much for adding this change to the project!