some improvements for Makefile
ihhub/fheroes2 pull request #2295
Opened 2020-11-29 22:52 UTC by undef21

- add -Werror for SDL2 build;

- enable echoing for fheroes2 build. It's usefull for build linter and visual control.

2020-11-30 08:56 UTC, ihhub requested changes
Hi @undef21 I describe steps which we need to do. Please take a look.

2020-11-30 08:56 UTC, ihhub commented on src/Makefile
> +CFLAGS := $(CFLAGS) -Werror
Please declare an extra environment variable called `FHEROES2_STRICT_COMPILATION`. Once it's set we add this compilation warning.
Please don't forget to update makefile in the root to include a description of the new variable.

Then later please change these files:
```
.github/workflows/osx_pull_request.yml
.github/workflows/osx_release.yml
```
To add this new variable like it's done for `WITH_SDL2: "ON"`.

On top of this please modify **.travis.yml** file to add changes in 2 builds like `- export WITH_SDL2="ON"`.

2020-11-30 08:56 UTC, ihhub commented on src/dist/Makefile
> +	$(CXX) -c -MD $(addprefix -I, $(SRCDIRLIST)) $< $(CFLAGS)
Please revert this change for now as it's not related to the issue. We can do this separately.

2020-11-30 13:54 UTC, undef21 commented on src/Makefile
> +CFLAGS := $(CFLAGS) -Werror
Done.

2020-11-30 13:54 UTC, undef21 commented on src/dist/Makefile
> +	$(CXX) -c -MD $(addprefix -I, $(SRCDIRLIST)) $< $(CFLAGS)
Done.

2020-12-01 00:08 UTC, merged

2020-12-01 00:09 UTC, ihhub commented
@undef21 thank you so much for this improvement!