Implement Stack split hotkeys (CTRL and shift)
ihhub/fheroes2 pull request #2316
Opened 2020-12-03 13:00 UTC by eos428

Solves #2280. Also created key hold logic I guess.

Implemented logics:
- While a stack is selected, hold shift + left click on an empty troop to split.
- While a stack is NOT selected, hold ctrl + left click on that stack to create another stack containing just one unit of the clicked stack. See H3HD ctrl split for reference.

2020-12-07 13:03 UTC, ihhub requested changes
Hi @eos428 I left multiple comments here. Could you please take a look?

2020-12-07 13:03 UTC, ihhub commented on src/fheroes2/army/army_bar.cpp
> +    const_cast<Army *>( army1 )->SplitTroopIntoFirstFreeSlot( troop, 1 );
We don't need to use const_cast as GetArmy has 2 variants. Please make army1 (actually armyFrom) as a non-const variable.

2020-12-07 13:29 UTC, eos428 commented on src/engine/localevent.cpp
> +        if ( event.type == SDL_KEYDOWN ) {
From SDL itself I don't think there's any. But IIRC we do use `GetClean()` when switching windows?

2020-12-07 13:35 UTC, eos428 commented on src/fheroes2/army/army_bar.cpp
> +    const_cast<Army *>( army1 )->SplitTroopIntoFirstFreeSlot( troop, 1 );
I think there's only one GetArmy() function in `ArmyTroop` class. As of my latest commit I'm editing that GetArmy function so that it doesn't a const instead, which might be debatable

2020-12-07 13:44 UTC, eos428 commented on src/fheroes2/army/army_bar.cpp
> +    const_cast<Army *>( army1 )->SplitTroopIntoFirstFreeSlot( troop, 1 );
Nevermind I shouldn't have changed that GetArmy() function as it breaks consistency and causes errors elsewhere

2020-12-09 14:15 UTC, ihhub requested changes
Hi @eos428 , I left few comments. Could you please take a look?

2020-12-09 14:39 UTC, eos428 commented on src/fheroes2/army/army_bar.cpp
> +    const Troop troop( troopFrom );
You're right, we don't have to cast to `Troop` here. My bad. Should have looked in more detail before copying existing functions' logics... Which is unfortunately the story of this PR.

2020-12-10 01:06 UTC, LeHerosInconnu commented
Hello @eos428,
 
> Implemented logics:
> 
> * While a stack is selected, hold shift + left click on an empty troop to split.

In the original game, when a troop is selected, it is also possible to hold shift + left click on another troop of the same type of creatures to transfer creatures from the first troop to the second troop.
It would also be nice to add this possibility to get the full functionality of the original game.

In original game:

![Move troop shift](https://user-images.githubusercontent.com/43583994/101707715-0d6cd200-3a8c-11eb-8a53-946d3c7717b0.gif)

2020-12-10 02:44 UTC, eos428 commented
Hi @LeHerosInconnu.

Thanks for the info. As of the latest commit I have implemented that logic as well.

@ihhub Since I edited `RedistributeArmy()`, there seems to be a lot of things worth refactoring in that function. Is it okay if this PR just handles the additional split function and the refactoring is done in another PR? I don't want to risk the PR getting too big like before :P

2020-12-10 03:25 UTC, LeHerosInconnu commented
Hello @eos428,

> Hi @LeHerosInconnu.
> 
> Thanks for the info. As of the latest commit I have implemented that logic as well.

Very nice, thanks. :)

> Also to note: The fast split function becomes a tad wonky when splitting to the same troop type. It only takes into account the selected stack's units, which may not be what we're looking for.

Yes, this function needs to be improved. :)
Look at this issue: https://github.com/ihhub/fheroes2/issues/1289.

2020-12-10 16:13 UTC, ihhub commented
> Hi @LeHerosInconnu.
> 
> Thanks for the info. As of the latest commit I have implemented that logic as well.
> 
> @ihhub Since I edited `RedistributeArmy()`, there seems to be a lot of things worth refactoring in that function. Is it okay if this PR just handles the additional split function and the refactoring is done in another PR? I don't want to risk the PR getting too big like before :P
> 
> Also to note: The fast split function becomes a tad wonky when splitting to the same troop type. It only takes into account the selected stack's units, which may not be what we're looking for.

If refactor is just for code readability we can do it in a separate. If it requires for this PR's changes then we can do it here.

2020-12-10 16:41 UTC, eos428 commented
I see, I'll refactor that function in another PR then. Also, since the other issues linked aren't exactly related to hotkeys, I'll do them in a separate PR as well.

As for this PR, there's nothing more for me to add, so fire away the reviews :)

2020-12-11 00:38 UTC, ihhub reviewed
Hi @eos428 , everything looks good. I'll test it today and merge if no issues.

2020-12-11 00:38 UTC, ihhub commented on src/fheroes2/army/army_bar.cpp
> +
It's a very minor: please remove this empty to group code blocks together.

2020-12-11 15:31 UTC, merged