fix elements' layout at monster info dialog
ihhub/fheroes2 pull request #2328
Opened 2020-12-04 18:23 UTC by undef21

related issues #1200, #1773, #1927

2020-12-07 13:20 UTC, ihhub commented
Hi @undef21 , this is what we have during battle:
![image](https://user-images.githubusercontent.com/19829520/101355744-fc786100-38d1-11eb-9026-98bc4b337b4e.png)

as you could see the number of rounds for spells is truncated by the button.

2020-12-07 21:20 UTC, undef21 commented
Hi @ihhub. All buttons positioned as in OG. Are numbers feature fheroes2? May be it's better to move spells icons upper 4px?
![Снимок экрана_2020-12-08_00-17-40](https://user-images.githubusercontent.com/71143197/101406881-1d00e500-38eb-11eb-9cc8-5751bb470a68.png)

2020-12-08 00:57 UTC, ihhub commented
> Hi @ihhub. All buttons positioned as in OG. Do numbers are feature of fheroes2? May be it's better to move spells icons upper 4px?
> ![Снимок экрана_2020-12-08_00-17-40](https://user-images.githubusercontent.com/71143197/101406881-1d00e500-38eb-11eb-9cc8-5751bb470a68.png)

Hi @undef21 please check on shooters :)

2020-12-08 13:53 UTC, undef21 commented
Hello @ihhub. What about this? Text was shifted up 1px as OG. Spells icons too. Button was shifted 2px down.
![Снимок экрана_2020-12-08_16-33-01](https://user-images.githubusercontent.com/71143197/101492156-a826bd00-3975-11eb-9cca-e31389699d96.png)

2020-12-08 14:03 UTC, ihhub commented
Hi @undef21 , we need more opinions to make the right decision. For me icons are too close to the text and to the button. Maybe we need to shift whole text a little bit up and the icons by 1 pixel up.

@idshibanov , @Branikolog and @LeHerosInconnu, could you please give you opinion?

2020-12-08 14:31 UTC, undef21 commented
It's from master branch
![Снимок экрана_2020-12-08_16-14-33](https://user-images.githubusercontent.com/71143197/101495139-3c465380-3979-11eb-8d55-e5922996e4f3.png)

It's from PR in non-batle mode
![Снимок экрана_2020-12-08_17-21-33](https://user-images.githubusercontent.com/71143197/101496714-23d73880-397b-11eb-9d58-aefb47eddea2.png)

2020-12-08 14:35 UTC, ihhub commented
@undef21 , ah, now I got it! Seems like a totally valid solution.

2020-12-08 18:05 UTC, LeHerosInconnu commented
Hello @ihhub,

> Hi @undef21 , we need more opinions to make the right decision. For me icons are too close to the text and to the button. Maybe we need to shift whole text a little bit up and the icons by 1 pixel up.
> 
> @idshibanov , @Branikolog and @LeHerosInconnu, could you please give you opinion?

I don't want to appear negative, but everything seems really too compressed and it's not the most beautiful visual aspect.
The window is too small. :)

Have you considered the possibility to display the number next to the sprite, near the lower right corner of the spell, and not under the sprite.

During a combat, it is really rare for a troop to have more than 4 to 5 active spells at the same time.

By spacing the spells a bit with the number next to and not under them, it should be possible to keep readability without having "compressed data" in the window.

Screens are for explanation only.
The horizontal position of the number of turns should be adjusted for each spell.

In fheroes2:
Archers with five active spells:

![Spells display 002](https://user-images.githubusercontent.com/43583994/101521847-a3b6d000-3986-11eb-906a-74f1e18a9fd2.png)

![Spells display 019 02](https://user-images.githubusercontent.com/43583994/101521854-a6b1c080-3986-11eb-830f-925a9ca096a8.png)

It's possible to have more active spells, and you still need to plan to be able to display many more spells, even if it overflows the window, as fheroes2 already does, it's okay.
This possibility is unlikely in practice during a combat. :)

In fheroes2:

![Spells display 014](https://user-images.githubusercontent.com/43583994/101521881-b3361900-3986-11eb-8289-294e9bd3d95f.png)

![Spells display 015](https://user-images.githubusercontent.com/43583994/101521887-b6310980-3986-11eb-8fd6-cd357a6f3caa.png)

2020-12-09 11:37 UTC, Branikolog commented
My 5 cents...
It would be nice, if the text inside this window will be at the same place, as the text in non-battle mode.
Considering the spacing between icons and "exit" button: as this feature is used by player not too often (As for me, I hardly use left click over my creatures. Like once a year. :) ) I won't complain, f some elements would be too close to "Exit" button. So, if the space between spell durability and the button will be 1px - it will be ok for me. (Different placing of "exit" button in various windows is more noticeable (in my point of view) than text, being shifted a bit up or down. So, i think, the button should be the same place, as other windows in game
The proposal of @LeHerosInconnu looks not bad, but I personally prefer, when number is shown under he icon of spells.
Anyway, as we introduce here new features, comparing to OG, I don't feel the need to follow OG arrangements in this window. So I think, we are free to move everything a bit, so that spaces would be around the same level.

2020-12-09 15:57 UTC, ihhub commented
Hi @undef21 are you able to move the number to the right side? If you need my help just ask :)

2020-12-09 23:37 UTC, LeHerosInconnu commented
@Branikolog.

> It would be nice, if the text inside this window will be at the same place, as the text in non-battle mode.
> So, i think, the button should be the same place, as other windows in game

Yes, it is important that text and buttons are in the same place in the different windows.
It is the small details that will make the game "perfect". :)

> Considering the spacing between icons and "exit" button: as this feature is used by player not too often (As for me, I hardly use left click over my creatures. Like once a year. :) ) I won't complain, f some elements would be too close to "Exit" button.

That's fine that it doesn't bother you too much, but you also have to think about all types of users, and the window should be pleasant to look at, even if it's not used often.

> The proposal of @LeHerosInconnu looks not bad, but I personally prefer, when number is shown under he icon of spells.

I would also prefer the numbers to be under the spells, but the window is too small to make it look nice, so an alternative is needed. :)

Hello @ihhub and @undef21,

> Hi @undef21 are you able to move the number to the right side? If you need my help just ask :)

I haven't tested with all the spell sprites, but as you can see in the screenshots, the Berserker and Hypnotize spell sprites are smaller in their vertical dimension (you can see that the numbers of turns are not aligned vertically).
It would be preferable to align all the spell sprites vertically according to the bottom of the sprite and not the top of the sprite as is currently the case.
This way the number of spell turns at the right would be close to the base of the sprite and not close to the "vertical space" under the sprite.

2020-12-10 08:00 UTC, Branikolog commented
> but the window is too small to make it look nice, so an alternative is needed. :)

We definitely need to find some compromise here. Until we create a solution to expand windows of the UI. ;)

2020-12-10 09:48 UTC, undef21 commented
Hello.

> Hi @undef21 are you able to move the number to the right side? If you need my help just ask :)

Yes. What is better, positioning text to right bottom corner of sprite or use unique offset for each sprite because some sprites have large transparent area at corners? Or may be draw digits over sprites with align to bottom of sprite?

> Yes, it is important that text and buttons are in the same place in the different windows.
> It is the small details that will make the game "perfect". :)

Agree. Buttons positions and text vertical alignment is same OG at this PR. But free space for additionals is too small. And there is small graphic issue at right bottom corner of exit button, if we change vertical position of this one as we can see at the first screenshot. 

It's possible solution for case of mad spell casting :
![Снимок экрана_2020-12-10_12-26-54](https://user-images.githubusercontent.com/71143197/101754736-1fc72a00-3ae5-11eb-80e0-cbb37b99624c.png)

2020-12-10 10:01 UTC, Branikolog commented
> It's possible solution for case of mad spell casting

👍

2020-12-10 23:30 UTC, LeHerosInconnu commented
Hello @undef21,

> What is better, positioning text to right bottom corner of sprite or use unique offset for each sprite because some sprites have large transparent area at corners? Or may be draw digits over sprites with align to bottom of sprite?

This is what I would do:

Why not have both. :)
The position of the number of turns displayed next to the sprite's bottom right corner when there is enough space, and adjusted for spells with a large space at the bottom; it would be a shame to hide the sprite's graphic when it's not needed.
And the position of the number of turns displayed over the sprite only in the case of mad spell casting.

Here are the distances and spaces used in the example below:
- a distance of 7 pixels between the right side of the number of turns and the right side of the sprite of the corresponding spell for sprites that have a large space at the bottom,
- a space of 5 pixels between the right side of the number of turns and the left side of the next sprite,
- a distance of 12 pixels between the right side of the number of turns and the right side of the sprite of the corresponding spell for sprites that have no space at the bottom,
- a space of 5 pixels between the top of the "EXIT" button and the bottom of the sprite as well as the bottom of the number of turns shadow (a space of 6 pixels with the bottom of the number of turns without taking the number of turns shadow into account), and all the sprites aligned vertically according to the bottom of the sprite,
- the ensemble of sprites and numbers of turns centered horizontally in the remaining space inside the frame (the orange rectangles for an equivalent space on each side inside the frame).

![Display spells H2 01 mod pixels](https://user-images.githubusercontent.com/43583994/101841880-238b9880-3b47-11eb-85b0-86846e043279.png)

![Display spells H2 01 mod](https://user-images.githubusercontent.com/43583994/101841884-25edf280-3b47-11eb-8b3d-6dd801df6bca.png)

2020-12-14 21:38 UTC, undef21 commented
Hello.
@LeHerosInconnu, thank a lot for detailed proposal.
If i understand right, your proposal is 12px text block with left border same as sprite. Text is aligned to right border of this block.
Block is shifted left 5px for "Bless", "Haste", "Shield", "Stoneskin" and "Dragonslayer". Something similar this:

![1](https://user-images.githubusercontent.com/71143197/102134860-25679b80-3e68-11eb-8692-8248e12296df.png)

For example case when text block is not shifted 5px:
![2](https://user-images.githubusercontent.com/71143197/102135164-a161e380-3e68-11eb-994e-513bf3ae4925.png)

2020-12-15 05:44 UTC, LeHerosInconnu commented
Hello @undef21,

> Hello.
> @LeHerosInconnu, thank a lot for detailed proposal.
> If i understand right, your proposal is 12px text block with left border same as sprite. Text is aligned to right border of this block.
> Block is shifted left 5px for "Bless", "Haste", "Shield", "Stoneskin" and "Dragonslayer". Something similar this:
> 
> ![1](https://user-images.githubusercontent.com/71143197/102134860-25679b80-3e68-11eb-8692-8248e12296df.png)

Great, that seems fine to me for two-digit numbers. :)
But this feels a bit strange for single-digit numbers.

Would it be possible to shift all the numbers five pixels to the left for single-digit numbers (for 1 to 9 turns, and this for all spells with and without large space at the bottom of the sprite) without affecting the spacing between the spell sprites?

- so, a space of 10 pixels between the right side of the number of turns and the left side of the next sprite only for single-digit numbers (for 1 to 9 turns).
(The space remains 5 pixels between the right side of the number of turns and the left side of the next sprite for two-digit numbers.)

![One digit only pixels fh2 02](https://user-images.githubusercontent.com/43583994/102174591-21ef0700-3e9e-11eb-9870-9d98299bee6e.png)

![One digit only fh2 01](https://user-images.githubusercontent.com/43583994/102174585-1ef41680-3e9e-11eb-81a5-a4260f100818.png)

![One digit and two digits fh2 01](https://user-images.githubusercontent.com/43583994/102175718-4e0b8780-3ea0-11eb-9c87-c6c97a730c2b.png)

Also don't forget to center horizontally the block of sprites and numbers in the right frame of the window. :)

2020-12-16 09:35 UTC, undef21 commented
Hello, @LeHerosInconnu.
The next iteration here)
![Снимок экрана от 2020-12-16 12-25-27](https://user-images.githubusercontent.com/71143197/102330685-eb4ae680-3f9a-11eb-8e86-ae4560e4c603.png)
![Снимок экрана от 2020-12-16 12-29-35](https://user-images.githubusercontent.com/71143197/102330713-f43bb800-3f9a-11eb-8f4b-9ce066a92270.png)

2020-12-16 10:16 UTC, LeHerosInconnu commented
Hi @undef21,

> Hello, @LeHerosInconnu.
> The next iteration here)

That looks very good to me.
Very good work, thank you very much. :)

![](https://github.githubassets.com/images/icons/emoji/unicode/1f44d.png)

2020-12-17 14:20 UTC, ihhub requested changes
Hi @undef21 I left multiple comments. Could you please take a look?

2020-12-17 14:20 UTC, ihhub commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +    std::vector<std::tuple<uint32_t, uint32_t, int, int> > spellsInfo; // sprite, duration, text right border, space
Please use a normal structure to hold the data. Reading tuple is very troublesome.

2020-12-17 14:20 UTC, ihhub commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +    if ( spellsInfo.size() )
Please use `!spellsInfo.empty()` instead.

2020-12-17 14:20 UTC, ihhub commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +    for ( u32 ii = 0; ii < ARRAY_COUNT( modes ); ++ii ) {
Since we fully modify this method then please use `uint32_t` and `i` instead of `ii`.

2020-12-17 14:20 UTC, ihhub commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +        int space = textRightOffset == 2 ? 10 : 5;
Please make this variable `const`.

2020-12-17 14:20 UTC, ihhub commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +                   return std::get<1>( first ) > 0 && std::get<1>( first ) < std::get<1>( second );
Once we use a structure this code will be easier to read.

2020-12-17 14:20 UTC, ihhub commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +            ow = dst.x + maxSpritesWidth / 2;
Please put `{}` to be consistent with the first part of if-body.

2020-12-17 14:20 UTC, ihhub commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +    std::sort( spellsInfo.begin(), spellsInfo.end(),
I think logically we need to do this:
- populate `spellsInfo`
- sort `spellsInfo`
- iteratively remove extra items if `spellsInfo` width is more than N
- draw the rest of items from `spellsInfo`

2020-12-22 00:08 UTC, undef21 commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +    std::vector<std::tuple<uint32_t, uint32_t, int, int> > spellsInfo; // sprite, duration, text right border, space
Done.

2020-12-22 00:08 UTC, undef21 commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +    if ( spellsInfo.size() )
Done.

2020-12-22 00:08 UTC, undef21 commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +    for ( u32 ii = 0; ii < ARRAY_COUNT( modes ); ++ii ) {
Done.

2020-12-22 00:09 UTC, undef21 commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +        int space = textRightOffset == 2 ? 10 : 5;
Done.

2020-12-22 00:09 UTC, undef21 commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +                   return std::get<1>( first ) > 0 && std::get<1>( first ) < std::get<1>( second );
Done.

2020-12-22 00:09 UTC, undef21 commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +            ow = dst.x + maxSpritesWidth / 2;
Done.

2020-12-22 00:13 UTC, undef21 commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +    std::sort( spellsInfo.begin(), spellsInfo.end(),
Do you mean to remove extra sprites?
For case of extreme overcasting:
![Снимок экрана от 2020-12-22 02-56-50](https://user-images.githubusercontent.com/71143197/102833930-9298a500-4403-11eb-8ca7-b347738babdb.png)

2020-12-22 14:08 UTC, merged

2020-12-22 14:08 UTC, ihhub commented
@undef21 , thanks a lot for fixing these bugs!