[Bugfix][2327] Chain lightning priority
ihhub/fheroes2 pull request #2343
Opened 2020-12-09 18:12 UTC by tau3

Hi!

This is a possible fix for #2327

2020-12-10 09:52 UTC, ihhub requested changes
Hi @tau3 I left multiple comments. Could you please take a look into them?

2020-12-10 09:52 UTC, ihhub commented on src/fheroes2/battle/battle_board.h
> +    typedef s32 Index;
Please don't typedef POD. It's very confusing to understand that's it is POD after all.

2020-12-10 09:52 UTC, ihhub commented on src/fheroes2/battle/battle_arena.h
> +        bool IsImmuneToChainLightning( Index troop, const HeroBase * hero ) const;
Please do not drop input argument names. The old code contains such but this is a bad styling making the code unreadable to other developers.

2020-12-10 09:52 UTC, ihhub commented on src/fheroes2/battle/battle_arena.h
> +        bool IsImmuneToChainLightning( Index troop, const HeroBase * hero ) const;
Also here every input argument could be `const`.

2020-12-10 09:52 UTC, ihhub commented on src/fheroes2/battle/battle_action.cpp
> +            TargetsInfo targetsForSpell = TargetsForChainLightning( hero, dst );
This variable should be `const`.

2020-12-10 09:52 UTC, ihhub commented on src/fheroes2/battle/battle.h
> +        void addAll( const Battle::TargetsInfo & rhs )
Also this method should accept input argument by r-value `&&` and we will just move elements instead of copying them. Use `emplace_back` for this purpose.

2020-12-10 09:52 UTC, ihhub commented on src/fheroes2/battle/battle_action.cpp
> +            targets.push_back( res );
We can use this:
```
targets.emplace_back();
TargetInfo & res = targets,back();

res.defender = target;
// store temp priority for calculate damage
res.damage = std::distance( targetIndexes.begin(), it );
```
In this case we don't make a copy and also we can remove `TargetInfo res;`.

2020-12-10 12:04 UTC, tau3 commented on src/fheroes2/battle/battle_action.cpp
> +            TargetsInfo targetsForSpell = TargetsForChainLightning( hero, dst );
not sure i understand: how do we use it as a `const` with `void append( TargetsInfo && rhs )`?

2020-12-11 02:30 UTC, idshibanov commented on src/fheroes2/battle/battle_action.cpp
> +        Indexes nearestTroops = board.GetNearestTroopIndexes( currentTargetIndex, &ignoredTroops );
`board.GetNearestTroopIndexes` is buggy and a part of the problem here. It can add two-hex unit twice if you cast the lightning at the "tail" hex. In addition it always calculates distance to "head" index when "tail" could be closer.

2020-12-11 02:32 UTC, idshibanov commented on src/fheroes2/battle/battle_action.cpp
> +        std::remove_if( nearestTroops.begin(), nearestTroops.end(), predicate );
Add Immune/magic resist troops to `ignoredTroops` list instead of checking/removing it every cycle.

2020-12-11 02:34 UTC, idshibanov commented on src/fheroes2/battle/battle_action.cpp
> +    return target->GetMagicResist( Spell::CHAINLIGHTNING, power ) == 100;
This comparison is incorrect in my opinion, if resist is in 1-99 range you should run a Rand() call to check if unit resists it this time (Dwarves for example).

2020-12-22 15:16 UTC, ihhub requested changes
Hi @tau3 I left multiple comments in this pull request. Could you please take a look into them?

2020-12-22 15:16 UTC, ihhub commented on src/fheroes2/battle/battle.h
> +        void append( TargetsInfo && rhs )
Let's please call it `targetsInfo` to have more sense in the name.

2020-12-22 15:16 UTC, ihhub commented on src/fheroes2/battle/battle.h
> +                push_back( info );
We're just copying the data so there is no reason to pass the argument by r-value. Also we could simply use `insert` method which does exactly what this loop is doing.

2020-12-28 03:24 UTC, ihhub commented
Hi @tau3 could you please fix merge conflict and code styling issues?

2020-12-29 15:02 UTC, ihhub requested changes
Hi @tau3 ,

I left multiple comments regarding the implementation. Could you please take a look into them?

2020-12-29 15:02 UTC, ihhub commented on src/fheroes2/battle/battle_board.cpp
> +        distances.resize( std::count_if( distances.begin(), distances.end(), predicate ) );
We don't need to sort the container as `std::count_if` runs through every element of the container. However, since we need to find the smaller element we can do like this to speed things up:
```
std::sort( distances.begin(), distances.end(), IndexDistance::Shortest );
const uint32_t smallestDistance = distances.front().second;

for ( size_t i = 1; i < distances.size(); ++i ) {
    if ( distances[i] != smallestDistance ) {
        distances.resize( i );
        break;
    }
}
```

2020-12-29 15:02 UTC, ihhub commented on src/fheroes2/battle/battle_board.cpp
> +    for ( IndexDistance distance : distances ) {
Please use const reference as here we're making a copy of std::pair.

2020-12-29 17:33 UTC, tau3 commented on src/fheroes2/battle/battle_action.cpp
> +        res.damage = std::distance( targetIndexes.begin(), it );
i think we shouldn't expect that `FindChainLightningTargetIndexes` return invalid indexes, so check for null can be replaced with `assert`

2020-12-29 17:45 UTC, tau3 commented on src/fheroes2/battle/battle_board.cpp
> +    for ( Cell cell : *this ) {
yep, good catch.

2020-12-29 17:50 UTC, tau3 commented on src/fheroes2/battle/battle_board.h
> +#include "pairs.h"
yes, we use `IndexDistance`

2020-12-29 18:02 UTC, tau3 commented
@ihhub fixed. Unfortunately, i can't see why clang-format fails in reports :\

2021-01-21 15:57 UTC, merged

2021-01-21 15:57 UTC, ihhub commented
@tau3 thank you very much for helping to fix these issues!