Hero screen, Morale info window, missing text when the army consists only of undead troops
ihhub/fheroes2 pull request #2375
Opened 2020-12-13 08:20 UTC by shprotru

Fix for #2358

2020-12-13 11:13 UTC, shprotru commented
Hi @LeHerosInconnu! I have some doubts on #2359 understanding, check, please this screenshot:
![Снимок экрана от 2020-12-13 14-10-06](https://user-images.githubusercontent.com/53114202/102010139-31ab0600-3d4d-11eb-9551-a5de88b532f1.png)
Here is hero, who robbed `Graveyard`, with army consists from undead units only.

2020-12-13 11:26 UTC, Branikolog commented
Hi, @shprotru.
I'll take a risk answering your question. :)
I'd like to see the sentence about undead army in the bottom of this window separated by a small space from previous morale modifiers.

2020-12-13 11:32 UTC, shprotru commented
@Branikolog new line returned back(I intended to do as in the original).
![Снимок экрана от 2020-12-13 14-31-00](https://user-images.githubusercontent.com/53114202/102010582-fa8a2400-3d4f-11eb-86bf-a45d242194d3.png)
![Снимок экрана от 2020-12-13 14-31-12](https://user-images.githubusercontent.com/53114202/102010583-fbbb5100-3d4f-11eb-8ae4-5169feac2e83.png)

2020-12-13 12:05 UTC, Branikolog commented
In my personal point of view, after phrase "Current Morale Modifiers" we should see all effects applied. And after that, with a small space between, we should type about the fact, that army is undead and modifiers are not applied. (as it is not morale modifier, so it is rather confusing to see it among other modifiers)
How do you think?

2020-12-13 14:05 UTC, shprotru commented
@LeHerosInconnu, please, notice, combination for description "Current Morale Modifiers: None" was removed.

2020-12-13 16:33 UTC, shprotru commented
![2020-12-13_16-56-24](https://user-images.githubusercontent.com/53114202/102017797-160a2480-3d7a-11eb-8fa4-b57e1551ef49.png)
![2020-12-13_16-56-33](https://user-images.githubusercontent.com/53114202/102017798-173b5180-3d7a-11eb-9b0b-562f0366b38f.png)

2020-12-13 23:16 UTC, LeHerosInconnu commented
Hello @shprotru and @Branikolog,

Here's how I see it. :)

- Army without undead, without morale modifiers:
"None" must be displayed to indicate to the player that there are no active moral modifiers (it is indicated this way in the original game).

"Neutral Morale

Neutral morale means your armies will never be blessed with extra attacks or freeze in combat.

Current Morale Modifiers:

None"

- Army with living creatures and undead:

"Bad Morale

Bad morale may cause your armies to freeze in combat.

Current Morale Modifiers:

Some undead in groups -1"

When the army is composed solely of undead troops, I think it's best to first let the player know that moral modifiers are not taken into account, and only then to indicate the active morale modifiers in case living creatures would be added to the army.
(That means, the following morale modifiers are not taken into account; and then list them.)

- Army full undead, without morale modifiers:
"None" must be displayed to indicate to the player that there are no active moral modifiers.

"Neutral Morale

Neutral morale means your armies will never be blessed with extra attacks or freeze in combat.

Entire army is undead, so morale does not apply.

Current Morale Modifiers:

None"

- Army full undead, with morale modifiers:
For a full undead army, the title must always be "Neutral Morale" even if there are moral modifiers (and the neutral morale sprite displayed).

"Neutral Morale

Neutral morale means your armies will never be blessed with extra attacks or freeze in combat.

Entire army is undead, so morale does not apply.

Current Morale Modifiers:

Graveyard robber -1"

**

Perhaps the word "groups" should also be replaced by "army":

"Some undead in army -1"

Instead of:

"Some undead in groups -1"

**

In another issue, I will also make a proposal to adjust the messages for more or less positive Morale (Awful, Treason, etc.), and also for Luck. :)

- Army with living creatures and undead, and -2 to morale modifiers:

"Awful Morale

Awful morale may cause your armies to freeze in combat more often.

Current Morale Modifiers:

Some undead in army -1
Troops of 3 alignments -1"

- Army with living creatures and undead, and at least -3 to morale modifiers:

"Treason Morale

Treason morale may cause your armies to freeze in combat very often.

Current Morale Modifiers:

Some undead in army -1
Troops of 3 alignments -1
Graveyard robber -1"

2020-12-14 07:13 UTC, Branikolog commented
Hi, @LeHerosInconnu.

> When the army is composed solely of undead troops, I think it's best to first let the player know that moral modifiers are not taken into account, and only then to indicate the active morale modifiers in case living creatures would be added to the army.

I would prefer see morale modifiers first, as experienced player would always know the origin of his army, and modifiers, as more needed information, should be higher in the window. And notification for morale not being applied, is useful for newcomers. 

> In another issue, I will also make a proposal to adjust the messages for more or less positive Morale (Awful, Treason, etc.), and also for Luck.

Totally agreed, as we have description of morale in battle by words, and it is not obvious, what this description means exactly.

2020-12-14 08:35 UTC, LeHerosInconnu commented
Hello @Branikolog,

> Hi, @LeHerosInconnu.
> 
> > When the army is composed solely of undead troops, I think it's best to first let the player know that moral modifiers are not taken into account, and only then to indicate the active morale modifiers in case living creatures would be added to the army.
> 
> I would prefer see morale modifiers first, as experienced player would always know the origin of his army, and modifiers, as more needed information, should be higher in the window. And notification for morale not being applied, is useful for newcomers.

From the point of view of reading comprehension, it is preferable to first indicate that the morale modifiers that follow are not taken into account.

Also, putting this sentence at the end can be interpreted as being part of the morale modifiers, which is not the case (you even wrote it). :D
Therefore, it is better to put it before the "Current Morale Modifiers:" line of text. :)

2020-12-14 10:38 UTC, Branikolog commented
> putting this sentence at the end can be interpreted as being part of the morale modifiers

That's why we make a space between modifiers and this sentence. Also, text arrangement of this window would always be the same, no matter undead army or not: there always will be description of current morale, then go modifiers, and only after optional goes this sentence. In your suggestion this sentence will appear between morale description and modifiers, which cause this window look different for this two cases.
Anyway, it's just my point of view. 
Our team can suggest their own decision. ;)

2020-12-14 13:27 UTC, LeHerosInconnu commented
Hello @Branikolog,
 
> In your suggestion this sentence will appear between morale description and modifiers, which cause this window look different for this two cases.

This is even better. :)
"The window has changed? Yes, the army is only made up of undead, so morale modifiers are not applied."
This is a good visual mnemonic. :D

> Anyway, it's just my point of view.
> Our team can suggest their own decision. ;)

Yes. :)

2020-12-19 04:28 UTC, ihhub requested changes
Hi @shprotru I left just 2 comment. Could you please take a look?

2020-12-19 04:28 UTC, ihhub commented on src/fheroes2/army/army.cpp
>              return 0;
Please add `{}` to this else block.

2020-12-19 08:29 UTC, shprotru commented on src/fheroes2/army/army.cpp
>              return 0;
done

2020-12-22 15:10 UTC, merged

2020-12-22 15:10 UTC, ihhub commented
@shprotru a bunch of thanks for fixing these issues! Great job!