Kingdom Overview screen, Towns/Castles Overview screen, wrong numbers displayed for heroes' primary skills
ihhub/fheroes2 pull request #2376
Opened 2020-12-13 12:32 UTC by shprotru

Fix for #2356

2020-12-13 15:53 UTC, ihhub requested changes
Hi @shprotru I left few comments. Please take a look into them.

2020-12-13 15:53 UTC, ihhub commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +            char skillValues[64];
This is incorrect way of populating a string. Please do not use `sprintf` for such purposes but a normal string concatenation.

2020-12-13 15:53 UTC, ihhub commented on src/fheroes2/heroes/skill.cpp
> -    return msg << skill.attack << skill.defense << skill.knowledge << skill.power;
Do we need this change and the change below? Aren't they below to file saving and loading?

2020-12-13 15:53 UTC, ihhub commented on src/fheroes2/heroes/skill.cpp
> -    return os.str();
return `GetAttack() + sep + GetDefense() + sep + GetPower() + sep + GetKnowledge();` will work as expected.

2020-12-13 16:30 UTC, shprotru commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +            char skillValues[64];
done

2020-12-13 16:30 UTC, shprotru commented on src/fheroes2/heroes/skill.cpp
> -    return msg << skill.attack << skill.defense << skill.knowledge << skill.power;
done

2020-12-13 16:30 UTC, shprotru commented on src/fheroes2/heroes/skill.cpp
> -    return os.str();
done

2020-12-13 17:03 UTC, ihhub commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +    const std::string sep = "-";
Just declare it locally before `text.Set`. This variable should use stack memory so making it static makes no sense.

2020-12-13 17:10 UTC, shprotru commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +    const std::string sep = "-";
done

2020-12-15 11:11 UTC, merged

2020-12-15 11:11 UTC, ihhub commented
@shprotru thank you very much for fixing this issue!