Adjust troop separation dialog position
ihhub/fheroes2 pull request #2387
Opened 2020-12-15 05:53 UTC by eos428

Solves #278

Tested on 640 x 480, 800 x 600 and 1280 x 720 and all of them seems to be consistent with each other. But note that the dialog position is also moved for other situations which are
- Splitting inside a single hero's screen
- Splitting inside a hero meeting

Example images:

These are the results for the new dialog position in a castle.

![Screenshot 2020-12-15 124729](https://user-images.githubusercontent.com/38433056/102176302-b9bb1800-3ed3-11eb-8dcb-d7847f35f00f.jpg)
![Screenshot 2020-12-15 092427](https://user-images.githubusercontent.com/38433056/102176313-bde73580-3ed3-11eb-9387-f3cfa222194e.jpg)

Inside a hero screen

![Screenshot 2020-12-15 125139](https://user-images.githubusercontent.com/38433056/102176629-64333b00-3ed4-11eb-902e-148fb712a0dc.jpg)

Inside a hero meeting screen

![Screenshot 2020-12-15 125122](https://user-images.githubusercontent.com/38433056/102176635-68f7ef00-3ed4-11eb-8599-25377b670bc9.jpg)

@Branikolog Can you check whether this one is positioned good enough for all cases? Thanks in advance!

2020-12-15 08:05 UTC, Branikolog commented
Hi, @eos428!
Your solution is much better, than the current one! Good work.

2020-12-15 17:38 UTC, ihhub requested changes
Hi @eos428 I left one comment. Could you please take a look?

2020-12-15 17:38 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +    const int boxYPosition = defaultYPosition + ( ( display.height() - display.DEFAULT_HEIGHT ) * 0.5f ) - boxHeight;
Please just divide by 2. In this case we don't introduce implicit type conversion.

2020-12-16 01:21 UTC, eos428 commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +    const int boxYPosition = defaultYPosition + ( ( display.height() - display.DEFAULT_HEIGHT ) * 0.5f ) - boxHeight;
Done :)

2020-12-16 03:50 UTC, merged

2020-12-16 03:51 UTC, ihhub commented
@eos428 thank you so much for your valuable contribution to the project!