remove click area around "exit" button
ihhub/fheroes2 pull request #2404
Opened 2020-12-15 14:17 UTC by undef21

issue #2394

2020-12-16 04:12 UTC, ihhub requested changes
Hi @undef21 , could we please change the logic of calculating area for Income based on my suggestions?

2020-12-16 04:12 UTC, ihhub commented on src/fheroes2/castle/castle_dialog.cpp
> +    const Rect & resActiveArea = Rect( rectResource, rectResource.w, 165 );
We should always hardcoded values. Why don't we create this area based on `buttonExit` position?

2020-12-16 04:12 UTC, ihhub commented on src/fheroes2/castle/castle_dialog.cpp
> +    const Rect & resActiveArea = Rect( rectResource, rectResource.w, 165 );
Please also use `fheroes2::Rect` and a normal constructor in this situation.

2020-12-16 11:12 UTC, undef21 commented on src/fheroes2/castle/castle_dialog.cpp
> +    const Rect & resActiveArea = Rect( rectResource, rectResource.w, 165 );
Done.

2020-12-16 11:12 UTC, undef21 commented on src/fheroes2/castle/castle_dialog.cpp
> +    const Rect & resActiveArea = Rect( rectResource, rectResource.w, 165 );
Done.

2020-12-16 16:57 UTC, ihhub commented on src/fheroes2/castle/castle_dialog.cpp
> +        if ( le.MouseClickLeft( Rect( resActiveArea ) ) ) {
Please remove an explicit class conversion. We're going to remove Rect class in the future.

2020-12-16 17:19 UTC, undef21 commented on src/fheroes2/castle/castle_dialog.cpp
> +        if ( le.MouseClickLeft( Rect( resActiveArea ) ) ) {
Done.

2020-12-21 13:55 UTC, merged

2020-12-21 13:56 UTC, ihhub commented
Hi @undef21 thanks a lot for fixing this issue!