Interface itemsbar adjustment + fix some split logics
ihhub/fheroes2 pull request #2459
Opened 2020-12-23 06:45 UTC by eos428

Also fixes #2391, but mostly this should be about refactoring `interface_itemsbar.h` and ensuring things are still working as before with improvements.

2020-12-27 15:48 UTC, ihhub requested changes
Hi @eos428 I left multiple comments. Could you please take a look into them and also review whether we need to return something from the most of action methods after all?

2020-12-27 15:48 UTC, ihhub commented on src/fheroes2/army/army_bar.cpp
> +        RedistributeArmy( selectedTroop, troop, [&]() { can_see_troop_info = false; } );
This line and line 522 are only places passing a pointer to lambda function. This lambda function just sets a variable to some state. Would it be more easier if we just pass a pointer to a boolean variable?

2020-12-27 15:48 UTC, ihhub commented on src/fheroes2/army/army_bar.h
> +    bool can_see_troop_info;
Please use camelCase variable naming: `_isTroopInfoVisible`.

2020-12-27 15:48 UTC, ihhub commented on src/fheroes2/army/army_bar.h
> +    bool can_see_troop_info;
This new member is not initialized in the constructor.

2020-12-27 15:48 UTC, ihhub commented on src/fheroes2/gui/interface_itemsbar.h
> +        virtual bool ActionBarRightMouseHold( Item &, Item & )
I'm change curious do we even check the return values of all these methods? If not we don't need to even return anything after all.

2020-12-27 15:48 UTC, ihhub commented on src/fheroes2/gui/skill_bar.h
> +    virtual bool ActionBarRightMouseHold( int & ) override;
Since we change the code above to add input argument names please do the same here and for the 58-59 lines as well.

2020-12-27 15:48 UTC, ihhub commented on src/fheroes2/resource/artifact.h
> +    virtual bool ActionBarRightMouseHold( Artifact & ) override;
Since we change the code above to add input argument names please do the same here.

2020-12-27 15:48 UTC, ihhub commented on src/fheroes2/gui/interface_itemsbar.h
> +        virtual bool ActionBarRightMouseHold( Item &, Item & )
Actually some of return values are handled in `ActionCursorItemIter` method...

2020-12-28 14:03 UTC, ihhub commented
Hi @eos428 please fix compilation error in `OSX / sdl2` CI job.

2020-12-28 14:24 UTC, eos428 commented on src/fheroes2/gui/interface_itemsbar.h
> +        virtual bool ActionBarRightMouseHold( Item &, Item & )
I don't know the exact details, but I think the most important ones to keep track are ActionBarCursor and LeftSingleClick. I think ActionBarCursor returning true would stop the rest of event processing, which is not what we'd want.

2020-12-28 15:17 UTC, merged

2020-12-28 15:18 UTC, ihhub commented
@eos428 thanks a lot for your priceless contribution to the project!