Game controller support
ihhub/fheroes2 pull request #2469
Opened 2020-12-24 11:06 UTC by Northfear

Tested on Linux with Xbox One and Xbox Series X controller. Was working on Vita too.
No point of supporting SDL1 IMO, since joystick support in SDL1 is a bit of a mess (no build in bindings for different controllers and OS).
Support is enabled with WITH_CONTROLLER=true option. The only thing that stops from dropping option altogether and supporting controller by default is hardware cursor with SDL2.

2020-12-24 14:18 UTC, ihhub requested changes
Hi @Northfear, I think we need to change the concept a bit in order to avoid this macro usage. Could you please check whether we could compile the same code on SDL 1? If yes then we're safe to do so and we can internally enable\disable Controller support. If not we can do 2 ways:
- separate implementations of SDL 1 and SDL 2 for LocalEvent class. It sounds crazy but the code will be much more cleaner and easier to modify
- add a new class just to handle controllers and add an instance of this class into LocalEvent only for SDL2. In this case we can have working code but without macros.
What do you think?

2020-12-24 14:18 UTC, ihhub commented on src/engine/localevent.cpp
> +    uint32_t currentTime = SDL_GetTicks();
Please make this variable `const` as we don't modify it.

2020-12-24 14:18 UTC, ihhub commented on src/engine/localevent.cpp
> +    uint32_t deltaTime = currentTime - lastControllerTime;
Please also make this variable `const` as well.

2020-12-24 14:18 UTC, ihhub commented on src/engine/localevent.h
> +    bool dpadScrollActive = false;
Please add `_` character at the beginning of each new member of the class. This is a part of our coding standard to differentiate class members and the rest of variables.

2020-12-24 14:18 UTC, ihhub commented on src/engine/localevent.h
> +    void ProcessControllerAxisMotion( void );
Since we're going to remove the macro please move these method above to the rest of methods under private section.

2020-12-24 14:18 UTC, ihhub commented on src/engine/localevent.h
> +    void ProcessControllerAxisMotion( void );
Please remove `void` from input argument list. It's redundant.

2020-12-24 14:18 UTC, ihhub commented on src/engine/localevent.h
> +    const float CONTROLLER_AXIS_SPEEDUP = 1.03f;
These variables are a bit magical. We need some explanation perhaps for them. For example, I don't know why we set 1.03f instead of 1.

2020-12-24 14:18 UTC, ihhub commented on src/engine/localevent.h
> +    float yAxisFloat = 0;
Why don't we use `double` instead?

2020-12-24 14:18 UTC, ihhub commented on src/engine/localevent.h
> +    float yAxisFloat = 0;
The naming of these 2 members is confusing: what's the difference between `xAxisFloat` and `xAxisLValue` or  `xAxisFloat` and `xAxisLValue`? Could we please set more understandable names?

2020-12-24 14:18 UTC, ihhub commented on src/engine/engine.cpp
> +#endif
This is the only place where we need to check for configuration file setting. The rest will be handled later.

2020-12-24 14:18 UTC, ihhub commented on src/Makefile
> +endif
Also if we want to set these changes only for SDL_2 then please do this:
```
ifdef WITH_SDL2
CFLAGS := $(CFLAGS) -DFHEROES2_CONTROLLER_SUPPORT
endif
```

2020-12-24 14:18 UTC, ihhub commented on src/Makefile
> +endif
However, we might just want to check the support of SDL2 instead in the code.

2020-12-24 14:18 UTC, ihhub commented on src/engine/localevent.cpp
> +        int16_t ySign = ( yAxisLValue > 0 ) - ( yAxisLValue < 0 );
Could you please make these 2 variables `const` too?

2020-12-24 14:18 UTC, ihhub commented on src/fheroes2/system/settings.h
> +    int controller_pointer_speed;
Please name this member as `_controllerPointerSpeed`.

2020-12-24 14:41 UTC, Northfear commented on Makefile
> +# WITH_CONTROLLER: build with game controller support (SDL2 only)
There's even no need for config option. It should "just work" when plugged in and shouldn't get in a way when not.

The real problem with macro is Cursor and RenderCursor class. Emulated controller pointer movement is obviously not a hardware cursor and it will be invisible with SDL 2.0 RenderCursor when hardware mouse is not present (or just won't move otherwise).

So the only way to avoid macros is to use software cursor by default one.

2020-12-25 01:12 UTC, ihhub commented
Hi @Northfear please rebase the code from master. I added needed changes to dynamically enable or disable cursor software emulation.

2020-12-25 23:05 UTC, Northfear commented
PR updated. It's automatically switching between HW and SW cursor when controller is plugged/unplugged now.
WITH_CONTROLLER macros removed and replaced with `#if SDL_VERSION_ATLEAST( 2, 0, 0 )` when needed. Compiles with both SDL1 and SDL2.

2020-12-27 04:00 UTC, ihhub requested changes
Hi @Northfear I left multiple comments. Could you please take a look?

2020-12-27 10:29 UTC, Northfear commented
@ihhub fixed

2020-12-27 15:16 UTC, ihhub requested changes
Hi @Northfear, I left multiple comments. Could you please take a look and discuss?

2020-12-27 17:12 UTC, Northfear commented on src/engine/screen.cpp
> +        if ( _cursor->isVisible() && _cursor->isSoftwareEmulation() && !_cursor->_image.empty() ) {
Software cursor sprite was still shown at offsetX and offsetY positions after unplugging the controller. I've added this to make sure that no leftovers of software cursor will be shown if HW one is active.

2020-12-27 17:23 UTC, Northfear commented on src/engine/screen.h
>          void setPosition( int32_t offsetX, int32_t offsetY )
The duality of that offset argument confused me for sure

2020-12-27 17:35 UTC, Northfear commented on src/engine/screen.h
> +        int32_t _offsetY;
Yeah, we need them when switching to hardware cursor (without a proper offset HW cursor was a blank pointer up until the next SetThemes call).
I just wasn't sure how should we access the other gui Cursor class from this one, so storing current cursor offset values in case we'll need to re-init HW cursor seemed like the easiest solution.
Other Cursor class seems like a better place to store these values, so I'm honestly not quite sure what is the best way to deal with this.

2020-12-28 15:35 UTC, ihhub commented on src/engine/screen.h
> +        int32_t _offsetY;
Let me come back to you tomorrow. I think I have an idea but I need to verify it.

2020-12-30 06:17 UTC, ihhub commented on src/engine/screen.h
> +        int32_t _offsetY;
Hi @Northfear, why don't we try this way:
- we don't store the offset in fheroes2::Cursor class
- before enabling or disabling software emulation by calling `isSoftwareEmulation` we hide the Cursor via `show` call
- after `isSoftwareEmulation` call we will execute `Cursor::SetThemes( Cursor::Themes(), true )` setting the offset internally to fheroes2::Cursor. In this case we shouldn't see flickering or moving cursor effects.

What do you think?

2020-12-30 15:54 UTC, ihhub commented
Hi @Northfear please resolve merge conflicts with master branch.

2021-01-03 08:46 UTC, ihhub requested changes
Hi @Northfear, we've almost finished this pull request. I left comments for just 2 places. Could you please take a look into them as I can't modify them directly?

2021-01-03 08:46 UTC, ihhub commented on src/engine/localevent.cpp
> +    const uint32_t currentTime = SDL_GetTicks();
To do this we have to rebase your source code from master branch. Could you please do this?

2021-01-03 08:46 UTC, ihhub commented on src/fheroes2/gui/cursor.cpp
> +    if ( fheroes2::cursor().isSoftwareEmulation() ) {
If we don't need this please move Cursor logic under if-body but do small modification `Cursor::Get().Move( x, y );`. In this case we won't create a temporary variable just for one call.

2021-01-03 11:01 UTC, Northfear commented
@ihhub fixed both

2021-01-03 14:33 UTC, merged

2021-01-03 14:33 UTC, ihhub commented
@Northfear , huge thanks for these important changes!

2021-01-11 19:53 UTC, dimag0g commented
On Nintendo Switch I have a problem with these lines:

        if ( _controllerPointerPosX < 0 )
            _controllerPointerPosX = 0;
        else if ( _controllerPointerPosX > display.width() )
            _controllerPointerPosX = display.width();

        if ( _controllerPointerPosY < 0 )
            _controllerPointerPosY = 0;
        else if ( _controllerPointerPosY > display.height() )
            _controllerPointerPosY = display.height();

When the cursor reaches the bottom/right edges of the screen using the controller, scrolling doesn't work. Shouldn't the cursor rather stop at `display.width()-1` and `display.height()-1`?

2021-01-12 10:52 UTC, Northfear commented
@dimag0g it should totally stop at display.width()-1. Thanks for the hint, I'll fix it later today.
As for touch events they should generally work fine for the most part, but it turns into a bit of a mess in my case because of 2 touchpads on Vita (accidental touches on the second one are really annoying) and wrong cursor positions with resolutions other than native ones (like centered or scaled 640*480)

2021-01-13 08:29 UTC, dimag0g commented
@dimag0g On Switch you can set any resolution you like (up to 1920x1080) and it gets scaled to the physical resolution (1280x720) by the library. I set it to 848x480 so that objects remain comfortably large. Touch event coordinates are floats in 0..1 range, so they don't depend on the resolution I set.