Refactor for AllCastles
ihhub/fheroes2 pull request #2476
Opened 2020-12-24 17:21 UTC by vincent-grosbois

- don't inherit from std::vector
- add an extra container to store position of castle sprites, so
that Get() method is in O(1)

This should fix #2385

2020-12-27 14:48 UTC, ihhub requested changes
Hi @vincent-grosbois , good job! I left multiple comments here. Could you please take a look into them?

2020-12-27 14:48 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +    */
This comment is a bit confusing. Could you please explain what this drawing is about?

2020-12-27 14:48 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +    */
I got it. It's a location of the castle tiles.

2020-12-27 14:48 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +}
Please move the implementation of these methods to header file making them inline (without the word inline).

2020-12-27 14:48 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +    for ( auto & castle : castles )
Please make this variable `const` as we don't modify it.

2020-12-27 14:48 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +    for ( u32 i = 0; i < size; ++i ) {
Please use `uint32_t` instead of `u32`.

2020-12-27 14:48 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +        auto castle = new Castle();
Please change it into `Castle * castle = new Castle();`. This is a pretty small type to be replaced by `auto`.

2020-12-27 14:48 UTC, ihhub commented on src/fheroes2/castle/castle.h
> +    std::vector<int8_t> castleTiles;
As per our standards please add `_` symbol to the beginning of class members: `_castles` and `_castleTiles`. The old code is filled with different approach which makes a bit harder to understand whether it is a class member or local/input variable.

2020-12-27 14:48 UTC, ihhub commented on src/fheroes2/castle/castle.h
> +    Castle * Get( const Point & ) const;
Please add the name of the input argument. It's the old code again was written in such manner.

2020-12-27 14:48 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +    int8_t idx = castleTiles[position.y * world.w() + position.x];
Please make this variable `const`.

2020-12-27 14:48 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +    return ( idx == -1 ) ? NULL : castles[idx];
To be safe let's change the condition to `( idx < 0 )`.

2020-12-27 14:48 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +        castleTiles.resize( world.w() * world.h(), -1 );
Here we could have a problem. What if we load a new map? Do we clear the vector? If not that this leads to left-overs from the previous loaded map.

2020-12-27 14:48 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +    castleTiles[p.y * w + p.x] = idx;
Let's write this code like this:
```
const int8_t idx = static_cast<int8_t>( castles.size() - 1 );
const int32_t width = world.w();

int32 position = castle->GetCenter().x +castle->GetCenter()..y * width;
castleTiles[position] = idx; // (0, 0)

--position;
castleTiles[position] = idx; // (-1, 0)

position -= width;
castleTiles[position] = idx; // (-1, -1)

and etc.
```

In this case we don't do extra calculations.

2020-12-27 14:48 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +    */
Let's change this comment into:
```
// Castle element positions are:
//   -
//  ---
// -+++-
// ++X++
// where - is ???, + is ??? and X is ???
```

2020-12-27 17:29 UTC, vincent-grosbois commented on src/fheroes2/castle/castle.cpp
> +        castleTiles.resize( world.w() * world.h(), -1 );
I'll change it to a check on castles.empty()
But anyway, if we load a new map already call clear on this object (otherwise it will contain data from the previous map in the castles member)
So effectively, this condition will trigger at each first call to AddCastle after a map reset
Now that I think of it, this will bug if we ever have maps with no castles, but I think it's impossible

2021-04-17 05:53 UTC, ihhub commented
The complexity increased to **O(n)** but without extra array usage.

2021-04-17 06:05 UTC, merged

2021-04-17 06:05 UTC, ihhub commented
@vincent-grosbois , thank you so much for this improvement!