Implement Alt hotkey to unite stacks of same type, Implement CTRL split even with selected troop
ihhub/fheroes2 pull request #2506
Opened 2020-12-28 16:34 UTC by eos428

Solves #2407 and #2408 (includes the middle mouse rendition of the ctrl split too)

2021-01-03 08:54 UTC, ihhub requested changes
Hi @eos428 , everything looks good. Just few more corrections required. Could you please take a look?

2021-01-03 08:54 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +        if ( !( *it )->isValid() || ( *it )->GetID() != targetTroop.GetID() )
To improve code readability could we please create a local variable from **it** like this `Troop * troop = *it;`?

2021-01-03 08:54 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +    const int totalMonsterCount = GetCountMonsters( targetTroop.GetID() );
We should cache `targetTroop.GetID()` expression.

2021-01-13 13:20 UTC, ihhub commented
Hi @eos428 could you please fix merging conflicts?

2021-01-13 13:31 UTC, eos428 commented
@ihhub done :)

2021-01-13 13:41 UTC, merged

2021-01-13 13:41 UTC, ihhub commented
@eos428 thank you so much for implemting this logic!