View world
ihhub/fheroes2 pull request #2538
Opened 2021-01-04 14:43 UTC by vincent-grosbois

Here's a big PR that enables the "View World" window
What is missing:
- incorrect offset for some icons
- resource name is not written in the icons

2021-01-04 15:16 UTC, ihhub requested changes
Hi @vincent-grosbois , good work! I proposed another approach to do the same. Could you please take a look into given comments?

2021-01-04 15:16 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +/***************************************************************************
Please add file footer according to [this page](https://github.com/ihhub/fheroes2/wiki/Copyright-standard).

2021-01-04 15:16 UTC, ihhub commented on src/fheroes2/kingdom/view_world.h
> +/***************************************************************************
Please add file footer according to [this page](https://github.com/ihhub/fheroes2/wiki/Copyright-standard).

2021-01-04 15:16 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +                        fheroes2::Blit( blackFogTile2, zoomLevel2, dstx2, dsty2 );
Please use `fheroes2::Fill` function instead so you won't need any extra images for this.

2021-01-04 15:16 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.h
> +    public:
We strictly do no allow any members to be public.

2021-01-04 15:16 UTC, ihhub commented on src/fheroes2/world/world.h
> +public:
We strictly do no allow any members to be public.

2021-01-04 15:16 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    cursor.Hide();
Please remove this and line 559 as they are redundant for the new redering engine.

2021-01-04 15:16 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +void drawAddon( fheroes2::Image & dst, const Maps::Addons & addon, int dstx, int dsty, int quantity2, uint32_t UIDToIgnore )
This and the function below are alsmot the same to `void Maps::Tiles::RedrawAddon` and `void Maps::Tiles::RedrawObjects` methods. Why don't we modify `Interface::GameArea` ROI like it's done for puzzle for the moment of generating image? Then we can call `void Interface::GameArea::Redraw` method with needed parameters which will generate for us needed image (maybe we have to add some small checks like for monster drawings) but this approach will be much cleaner and smaller. You could take a look into `fheroes2::Image Interface::GameArea::GenerateUltimateArtifactAreaSurface` method as a reference. After getting needed image we just need to draw extra objects like heroes or monsters.
What do you think?

2021-01-13 15:07 UTC, ihhub commented
Hi @vincent-grosbois could you please rebase your branch from master? I'm not able to compile it on my machine once I put your changes on the top of the master branch.

2021-01-13 16:29 UTC, vincent-grosbois commented
> 
> 
> Hi @vincent-grosbois could you please rebase your branch from master? I'm not able to compile it on my machine once I put your changes on the top of the master branch.

it should be good now

2021-01-17 03:38 UTC, ihhub requested changes
Hi @vincent-grosbois , I left multiple comments here as a part of first review. Could you please take a look?

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        cachedImages[3] = world.getViewWorldCache().GetCachedImage();
Storing cached image in world might be not a good idea since we are no releasing resources after exiting World View mode. What if we calculate it every time inside this constructor? How slow it is to do such?

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    _cachedTerrain = fheroes2::Image( world.w() * TILEWIDTH, world.h() * TILEWIDTH );
It's a huge image after all: 2 * 192 * 32 * 192 * 32 = 72 MB. We can't do this as some systems such as PlayStation Vita doesn't have so much RAM available for our application.

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    Interface::GameArea gamearea = Interface::Basic::Get().GetGameArea();
We do we make a copy of game are here? Can't we remember the original roi, do computations and then return roi back?

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    CacheForMapWithResources( bool revealAll )
Please make this constructor `explicit` and input argument `const`.

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    fheroes2::Image cachedImages[4]; // One image per zoom Level
Here's a problem with memory: we store 72 MB image in world map, then we have 1 image as a copy of it, and 3 more images of 18 MB, 4.5 MB and 1.125 MB. Overall it's 167.625 MB which is an overkill for memory consumption.

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        Interface::GameArea gamearea = Interface::Basic::Get().GetGameArea();
Is there a reason why we make a copy of game area?

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +int colorToOffsetICN( int color )
Since this is a static function within the source file please create an unnamed namespace just after header inclusions and put this function here. This is to reduce the scope of function and to improve readability of the code as we can know what extra we have in the file.
Also please make input argument as `const`.

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.h
> +        Rect _roiForZoomLevels[4];
Please prefer **fheroes2::Rect** over **Rect** as the old class is limited to int16_t and causes conversion warnings in the code.

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.h
> +        Point _center;
Please prefer **fheroes2::Point** over **Point** as the old class is limited to int16_t and causes conversion warnings in the code.

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    cursor.Hide();
Please remove `cursor.Hide()` and `cursor.Show()` as it's a legacy code and make no difference for us.

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        cursor.Show();
Please remove this line as it does nothing here.

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +                newRoiCenter.y = initRoiCenter.y - ( newMousePos.y - initMousePos.y ) * TILEWIDTH / TileSizePerZoomLevel[currentROI._zoomLevel];
Please use constructor to assign values in place.

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    Point dst_pt2( display.width() - RADARWIDTH + 16, display.height() - 177 );
Please use `fheroes2::Point` type instead.

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    Point dst_pt( display.width() - RADARWIDTH + 16, display.height() - 69 );
Please use `fheroes2::Point` type instead.

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    const s32 world_w = world.w();
Please use `int32_t` instead of `s32`.

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +static const int TileSizePerZoomLevel[4] = {4, 6, 12, 32};
Please put these variables as well as other static functions declared in this file under unnamed namespace. Variables don't need `static` keyword in this case. It's good to know what helper code exist in this source code.

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +static const int TileSizePerZoomLevel[4] = {4, 6, 12, 32};
We might not need to cache images. Please use `ICN::GROUND12`, `ICN::GROUND6` and `ICN::GROUND4` for terrain generation. It should be much more efficient.

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +static const int TileSizePerZoomLevel[4] = {4, 6, 12, 32};
Also I think these ICNs might hel you with implementation:
- ICN::LETTER12, ICN::LETTER6, ICN::LETTER4
- ICN::MISC12, ICN::MISC6, ICN::MISC4
- ICN::VWFLAG12, ICN::VWFLAG6, ICN::VWFLAG4

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    const int pixelsW = sizeInPixels.w * TILEWIDTH / TileSizePerZoomLevel[(int)zoomLevel];
Please always use C++ casting over C-casting.

2021-01-17 03:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    fheroes2::Sprite s = fheroes2::Crop( image, offsetPixelsX, offsetPixelsY, ROIScreen.w, ROIScreen.h );
Please make this variable `const` and call it with some meaningful name like `cropped`.

2021-01-17 11:26 UTC, vincent-grosbois commented on src/fheroes2/kingdom/view_world.cpp
> +    Interface::GameArea gamearea = Interface::Basic::Get().GetGameArea();
Yes but whats is the reason for doing it that way ? It's logically a different GameArea that I want to draw on, so I don't see the upsides of doing weird temporary change of values. I think that GameArea class is very light too

2021-01-17 11:27 UTC, vincent-grosbois commented on src/fheroes2/kingdom/view_world.cpp
> +        cachedImages[3] = world.getViewWorldCache().GetCachedImage();
I think it's 0.1 sec at map loading for the biggest map

2021-01-17 11:32 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        cachedImages[3] = world.getViewWorldCache().GetCachedImage();
The timing really depends on hardware. What are specs of your machine?

2021-01-17 19:05 UTC, vincent-grosbois commented on src/fheroes2/kingdom/view_world.cpp
> +        cachedImages[3] = world.getViewWorldCache().GetCachedImage();
i7-6700 HQ@2.6Ghz
8GB of ram
so not super recent laptop

2021-01-17 22:41 UTC, vincent-grosbois commented
@ihhub 
I've addressed some comments, but it's not finished yet.
I don't know what you mean about using ICN::GROUND16 etc. Am I supposed to change the whole part about drawing world and just drawing these ICN instead ? How do I know which index to select?

2021-01-18 01:39 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        cachedImages[3] = world.getViewWorldCache().GetCachedImage();
Hmm... then it should be okay to do calculations upon clicking View World button.

2021-01-18 01:45 UTC, ihhub commented
> @ihhub
> I've addressed some comments, but it's not finished yet.
> I don't know what you mean about using ICN::GROUND16 etc. Am I supposed to change the whole part about drawing world and just drawing these ICN instead ? How do I know which index to select?

Hi @vincent-grosbois ,
GROUND are tiles for zoomed images. In other words they're resized versions of original 32x32 tiles. MISC is for objects on map and LETTER is a letter which should be used on these objects. To have a clear picture please do this:
- add `#include "image_tool.h"` into agg.cpp
- inside `bool LoadModifiedICN( int id )` function add this code:
```
            case ICN::GROUND12:
                LoadOriginalICN( id );
                for ( size_t i = 0; i < _icnVsSprite[id].size(); ++i ) {
                    Save( _icnVsSprite[id][i], "your_path" + std::to_string(i) + ".bmp");
                }
```

so that youcan see what these ICNs are.

2021-01-21 20:42 UTC, vincent-grosbois commented
@ihhub I've updated the PR, normally it correctly uses the new resize API

2021-02-01 14:10 UTC, ihhub commented
Hi @vincent-grosbois , few things to notice:
- my FPS goes crazy in this mode. A wooping 400 FPS :) Are we doing everything in a loop?
- there's a black section on the right of the interface. I recommend to put View World there and just draw the rest of background

![image](https://user-images.githubusercontent.com/19829520/106469126-d76f2b80-64d9-11eb-8809-6ade3f3a6b3a.png)

2021-02-01 14:20 UTC, vincent-grosbois commented
> Are we doing everything in a loop?
What do you mean?
>     * there's a black section on the right of the interface. I recommend to put View World there and just draw the rest of background
I'll see what I can do, it's a good idea to show the rest of the map indeed. But I don't know how I can make it so the borders on the right don't look ugly. Also I'll have to check all resolutions

2021-02-01 14:47 UTC, ihhub requested changes
Hi @vincent-grosbois , I left multiple comments here. Could you please take a look?

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        display.render();
We should put this line in the block before as there's no reason to redraw if nothing's changed.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +
Please remove this empty line.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.cpp
> +
These methods are not used anywhere. Should we remove them?

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.h
> -
Please revert this line. Let's keep minimal changes for this pull request.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/gui/interface_radar.cpp
> -
Please revert this line. Let's keep minimal changes for this pull request.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +    const bool drawBottom = ( flag & LEVEL_BOTTOM ) == LEVEL_BOTTOM;
Please move this back to the original place since there're no need move this variable.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +    if ( hero && hero->GetPath().isShow() && ( flag & LEVEL_ROUTES ) ) {
Please declare an extra variable `const bool darwRoutes = ( flag & LEVEL_ROUTES ) != 0;` and use it here.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        const int nCachedLevels = 3;
Please do **not** use Hungarian variable naming, just call it as `cachedLevels`.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        fheroes2::Image temporaryImg = fheroes2::Image( blockSizeX, blockSizeY );
Please use normal constructor `fheroes2::Image temporaryImg( blockSizeX, blockSizeY );` as it's the fastest way.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        assert( ( world.h() * TILEWIDTH ) % blockSizeY == 0 );
Please cache `world.w() * TILEWIDTH` and `world.h() * TILEWIDTH` and use them in the loops below and here.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +                    const int blockSizeResizedX = blockSizeX * TileSizePerZoomLevel[i] / TILEWIDTH;
Please cache `TileSizePerZoomLevel[i] / TILEWIDTH`.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    display.fill( 0 );
Is there a strong need to fill the whole image? I think what we need is to update certain parts of the display.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    fheroes2::Blit( cropped, display, BORDERWIDTH + ( offsetPixelsX < 0 ? -offsetPixelsX : 0 ), BORDERWIDTH + ( offsetPixelsY < 0 ? -offsetPixelsY : 0 ) );
Just use `fheroes2::Blit` call directly without any cropping. This function has an overloaded version to support custom width and height and it does internal 'cropping' inside without an extra image.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    Rect roiTiles = ROI.GetROIinTiles();
Please make this variable `const`.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    Rect roiPixels = ROI.GetROIinPixels();
Please make this variable `const`.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        const int dsty = yy * tileSize - offsetY + BORDERWIDTH;
Please call it as `posY` or `dstY`.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +            const int dstx = xx * tileSize - offsetX + BORDERWIDTH;
Please call it as `posX` or `dstX`.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    for ( int32_t yy = minTileY; yy < maxTileY; yy += 1 ) {
Please use `y` instead of `yy`.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        for ( int32_t xx = minTileX; xx < maxTileX; xx += 1 ) {
Please use `x` instead of `xx`.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    for ( int32_t yy = minTileY; yy < maxTileY; yy += 1 ) {
Also please use normal pre-increment of the variable instead of `+= 1`.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        for ( int32_t xx = minTileX; xx < maxTileX; xx += 1 ) {
Also please use normal pre-increment of the variable instead of `+= 1`.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    const int IcnPerZoomLevelFlags[4] = {ICN::VWFLAG4, ICN::VWFLAG6, ICN::VWFLAG12, ICN::VWFLAG12};
Please name all variable from non-capital letter.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +                                int colorOffset = colorToOffsetICN( tile.QuantityColor() );
Here we shadow the previous variable. Please use the previous variable or rename this one.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    Rect visibleScreenInPixels = interface.GetGameArea().GetROI();
Please make these variables `const`.

2021-02-01 14:47 UTC, ihhub commented on src/fheroes2/world/world.h
> +#include "view_world.h"
Do we need this file inclusion?

2021-02-01 14:48 UTC, ihhub commented
> What do you mean?
I pointed a place to fix this :)

Also I don't see that in the original game there are any changes related to Radar. The only thing changes is visible area. Could you please check it? If it's true then we don't need all changes for radar but a simple set of visible are for it.

2021-02-01 16:04 UTC, vincent-grosbois commented on src/fheroes2/kingdom/view_world.cpp
> +                    const int blockSizeResizedX = blockSizeX * TileSizePerZoomLevel[i] / TILEWIDTH;
I'll do it but I really don't see the point, makes things less readable IMO
In term of code generated I'm sure it's not changing anything

2021-02-01 16:06 UTC, vincent-grosbois commented on src/fheroes2/kingdom/view_world.cpp
> +                    const int blockSizeResizedX = blockSizeX * TileSizePerZoomLevel[i] / TILEWIDTH;
I can't cache it actually, the whole point is that this division does not yield an integer, so we need to do the full computation 
> blockSizeX * TileSizePerZoomLevel[i] / TILEWIDTH
and
> x * TileSizePerZoomLevel[i] / TILEWIDTH
to have exact result

2021-02-01 16:10 UTC, vincent-grosbois commented on src/fheroes2/kingdom/view_world.cpp
> +    display.fill( 0 );
I'm not sure what you mean
There are certains parts of the display that are potentially never drawn over on the next frame, like the  part of the frame where no map is being drawn. That's why I set everything to 0 first

2021-02-01 16:35 UTC, vincent-grosbois commented on src/fheroes2/kingdom/view_world.cpp
> +    fheroes2::Blit( cropped, display, BORDERWIDTH + ( offsetPixelsX < 0 ? -offsetPixelsX : 0 ), BORDERWIDTH + ( offsetPixelsY < 0 ? -offsetPixelsY : 0 ) );
I tried but it seems it doesn't work well.
I think in some situations (if offsetPixelsX  > 0), we fail the Verify() check in Blit() and we do'nt draw anything

2021-02-01 16:37 UTC, vincent-grosbois commented
@ihhub I adressed all comments in this new commit, I think

> Also I don't see that in the original game there are any changes related to Radar. The only thing changes is visible area. Could you please check it? If it's true then we don't need all changes for radar but a simple set of visible are for it.
We need to change the radar because it has to handle changing area size (for the rectangle) and it also has to handle the change of zoom level

2021-02-04 04:01 UTC, ihhub requested changes
Hi @vincent-grosbois , I left multiple comments here. Could you please take a look?

2021-02-04 04:01 UTC, ihhub commented on src/fheroes2/kingdom/view_world.h
> +    OnlyVisible = 0, // Only show what is currently under fog of war
Should the comment state the opposite: `Only show what is current not under fog of war`?

2021-02-04 17:57 UTC, vincent-grosbois commented on src/fheroes2/kingdom/view_world.cpp
> +    fheroes2::Point viewCenterInPixels( worldMapROI.x * TILEWIDTH + visibleScreenInPixels.w / 2, worldMapROI.y * TILEWIDTH + visibleScreenInPixels.h / 2 );
not possible due to the if check afterwards

2021-02-04 18:43 UTC, vincent-grosbois commented on src/fheroes2/kingdom/view_world.cpp
> +    const fheroes2::Sprite cropped = fheroes2::Crop( image, offsetPixelsX, offsetPixelsY, ROIScreen.w + 2 * BORDERWIDTH + RADARWIDTH, ROIScreen.h );
Hello
I've tried to replace this with:
    ```
    fheroes2::Point inPos( offsetPixelsX, offsetPixelsY );
        fheroes2::Point outPos( BORDERWIDTH + ( offsetPixelsX < 0 ? -offsetPixelsX : 0 ), BORDERWIDTH + ( offsetPixelsY < 0 ? -offsetPixelsY : 0 ) );
        fheroes2::Size outSize( ROIScreen.w + 2 * BORDERWIDTH + RADARWIDTH, ROIScreen.h );
        fheroes2::Rect outputROI( outPos , outSize);

        fheroes2::FitToRoi( image, inPos, display, outPos, outSize, outputROI );

        fheroes2::Blit( image, inPos, display, outPos, outSize );

But basically it still fails. Basically when we passe inX < 0 or inY < 0 we abort drawing. It seems like a bug to me
```

2021-02-04 18:50 UTC, vincent-grosbois commented on src/fheroes2/kingdom/view_world.cpp
> +    const fheroes2::Sprite cropped = fheroes2::Crop( image, offsetPixelsX, offsetPixelsY, ROIScreen.w + 2 * BORDERWIDTH + RADARWIDTH, ROIScreen.h );
I think I found a way to do it

2021-02-04 19:59 UTC, vincent-grosbois commented
hi @ihhub I think I adressed all the issues

2021-02-07 15:28 UTC, ihhub requested changes
Hi @vincent-grosbois , good job! We're almost there. Could you please rebase your branch from master and check the comments?

2021-02-07 15:28 UTC, ihhub commented on src/fheroes2/gui/interface_border.h
> +    void GameBorderRedraw( const bool viewWorld );
To be more understandable I'm proposing to name this variable as `viewWorldMode`.

2021-02-07 15:28 UTC, ihhub commented on src/fheroes2/gui/interface_radar.cpp
> +    fheroes2::Image sf( sw, sw );
This image should go away.

2021-02-07 15:28 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +#endif
Shall we use `std::vector<fheroes2::Image> cachedImages` instead? Then here we can do like this:
```
#ifdef VIEWWORLD_DEBUG_ZOOM_LEVEL
            cachedImages.resize( 4 );
#else
            cachedImages.resize( 3 );
#endif
```
and lower in this code use `cachedImages.size()`. What do you think?

2021-02-07 15:28 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +                cachedImages[i] = fheroes2::Image( world.w() * tileSizePerZoomLevel[i], world.h() * tileSizePerZoomLevel[i] );
Please use `resize()` call instead.

2021-02-07 15:28 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        explicit CacheForMapWithResources( const bool revealAll )
If we don't expect default constructor to be called please delete it: `CacheForMapWithResources() = delete;`.

2021-02-07 15:28 UTC, ihhub commented on src/fheroes2/kingdom/view_world.h
> +        bool ChangeZoom( const bool zoomIn, const bool cyle = false );
`cycle` is misspelled.

2021-02-08 15:23 UTC, vincent-grosbois commented
hi @ihhub , here's a new review that includes all changes

2021-02-10 15:28 UTC, ihhub requested changes
Hi @vincent-grosbois , I left multiple comments here. Could you please take a look?

2021-02-10 21:29 UTC, vincent-grosbois commented on src/fheroes2/kingdom/view_world.cpp
> +    newCenter.y = clamp( newCenter.y, 0, world.h() * TILEWIDTH );
you're aware that it's going to produce the same assembly right ?

2021-02-10 21:32 UTC, vincent-grosbois commented on src/fheroes2/kingdom/view_world.cpp
> +    const Rect visibleScreenInPixels = interface.GetGameArea().GetROI();
I dcan't do it for GetVisibleTileROI as it's returning a new object

2021-02-10 21:42 UTC, vincent-grosbois commented
@ihhub  done

2021-02-11 14:32 UTC, ihhub requested changes
Hi @vincent-grosbois , few more things are left to be addressed:
- code duplication removal in Interface::Radar. I described the way how to compensate performance drop
- we should not draw heroes in View World mode, just their icons
- the bottom of interface dawings are incorrect:
our version:
![image](https://user-images.githubusercontent.com/19829520/107649686-ac928d80-6cb8-11eb-8b87-6c32ccffa522.png)
the original game:
![image](https://user-images.githubusercontent.com/19829520/107649746-bc11d680-6cb8-11eb-96cc-614f4d38b333.png)

The reset of missing features like support of spells and letter we can do in a separate pull request.

2021-02-11 14:32 UTC, ihhub commented on src/fheroes2/gui/interface_radar.cpp
> +void Interface::Radar::RedrawObjects( int color, ViewWorldMode flags ) const
Let's combine this and the original `RedrawObjects` methods. The only difference is presence of flags. To compensate an extra computations for normal radar let's do this:
- move `GetChunkSize` function at the top of the file under unnamed namespace and modify it's body to:
```
int GetChunkSize( int size1, int size2 )
{
    if ( size1 > size2 ) {
        const int res = size1 / size2;
        if ( ( size1 % size2 ) * 10 > size2 ) {
            return res + 1;
        }
        return res;
    }

    return 1;
}
```
this will be slightly faster than before.
- in `RedrawObjects` method inside the loop make these changes (notice swapped conditions):
```
#ifdef WITH_DEBUG
            const bool visibleTile = revealAll || IS_DEVEL() || !tile.isFog( color );
#else
            const bool visibleTile = revealAll || !tile.isFog( color );
#endif
```
- change all uint32_t to int32_t (we're introducing implicit type conversion)
- cache `rect.y + offset.y` and `rect.x + offset.x` before the loop

2021-02-11 14:46 UTC, vincent-grosbois commented
Hello @ihhub 
please go ahead and either do the changes you feel are useful or let someone else do them, I don't think I will continue working on this issue.
This is probably the 10th back and forth we have on this PR, where each time a new objection is raised on the same initial codebase I've submitted
I think that for an open source project that concerns a 25 year old game, the focus should probably placed on trying to add missing/new features, rather than endlessly nitpicking which integers should be "cached" or not, which has absolutely 0 impact on the generated assembly and make the code less clear. I really don't think this is bringing anything to the final product, but this is wasting everybody's precious time

2021-02-11 14:52 UTC, ihhub commented
> Hello @ihhub
> please go ahead and either do the changes you feel are useful or let someone else do them, I don't think I will continue working on this issue.
> This is probably the 10th back and forth we have on this PR, where each time a new objection is raised on the same initial codebase I've submitted
> I think that for an open source project that concerns a 25 year old game, the focus should probably placed on trying to add missing/new features, rather than endlessly nitpicking which integers should be "cached" or not, which has absolutely 0 impact on the generated assembly and make the code less clear. I really don't think this is bringing anything to the final product, but this is wasting everybody's precious time

Hi @vincent-grosbois , sure. I will finish this pull request.

2021-02-11 16:59 UTC, merged

2021-02-11 17:02 UTC, ihhub commented
@vincent-grosbois , thank you so much for your huge work on this issue!

My apologies if I was too strict on performance optimizations as they are essential in such applications. Sadly fo us, the old code was written in a ba manner leading to have a mix of optimized and unoptimized solutions :(