Touchpad support
ihhub/fheroes2 pull request #2552
Opened 2021-01-07 17:57 UTC by Northfear

Touchpad support is a bit hard to get right on all devices, but once we have
- screen resolution
-  render area size and placement (it may be a window somewhere or scaled region on the screen)
-  and game resolution itself
 
most of the cases should be covered. `getWindowDestRect` and `getScreenResolution` might need overriding on Switch or some other consoles, since SDL ports may return some garbage values with them (but idea is still the same: getScreenResolution should return full resolution of the screen with touchpad and getWindowDestRect should return rect where everything is rendered (it may be a window on Linux/Windows or some centered/scaled area on console port for example).

Previously I had "trackpad" touch controls too with RMB support with 2 fingers (same as on old fheroes2 Android port), but I've dropped them later, since no one was using them anyway. I can add them too along with some option for switching between control methods, but I don't think that there's any use for it before any working mobile ports.

2021-01-08 00:23 UTC, ihhub commented
Hi @Northfear , could you please fix compilation for SDL2 on Ubuntu? It's failing for Travis-CI jobs.

2021-01-10 03:17 UTC, ihhub requested changes
Hi @Northfear , I left multiple comment here. Could you please take a look?

2021-01-10 03:17 UTC, ihhub commented on src/engine/localevent.cpp
> +    int touchNumber = SDL_GetNumTouchDevices();
Please make this variable `const`.

2021-01-10 03:17 UTC, ihhub commented on src/engine/screen.cpp
> +            return rect;
We should cache this value at the time of setting resolution or changing from/to fullscreen as this operation is not instant.

2021-01-10 03:17 UTC, ihhub commented on src/engine/screen.cpp
> +        virtual std::pair<int, int> getScreenResolution() const override
Please use `fheroes2::Size` type instead of std::pair.

2021-01-10 03:17 UTC, ihhub commented on src/engine/screen.cpp
> +            int32_t displayIndex = SDL_GetWindowDisplayIndex( _window );
Please make this variable `const`.

2021-01-10 03:17 UTC, ihhub commented on src/engine/screen.cpp
> +            return resolution;
We should cache this variable at the time of setting resolution or changing from/to fullscreen mode.

2021-01-10 03:17 UTC, ihhub commented on src/engine/localevent.cpp
> +        const std::pair<int, int> gameSurfaceRes( display.width(), display.height() ); // native game (surface) resolution
Please use `fheroes2::Size` structure instead.

2021-01-12 21:49 UTC, Northfear commented
@ihhub fixed. overriding/macroing `cacheScreenWindowRect()` should make it functional on other platforms too (switch/vita/android, etc)

2021-01-13 12:40 UTC, ihhub requested changes
Hi @Northfear , everything looks good. Please take a look into comments about names of variables and functions. I know that this is silly sometimes but we should make this core code be understandable by everyone as it's an essential part of the project.

2021-01-13 12:40 UTC, ihhub commented on src/engine/screen.cpp
> +        virtual void cacheScreenWindowRect()
This method shouldn't be virtual and should be places under private section. Please also rename it into `void _retrieveWindowInfo() const`.

2021-01-13 12:40 UTC, ihhub commented on src/engine/screen.cpp
> +        fheroes2::Rect _windowRectangle;
Please rename it into `_activeWindowROI`.

2021-01-13 12:40 UTC, ihhub commented on src/engine/screen.cpp
> +        fheroes2::Size _screenResolution;
Please rename it into `_currentScreenResolution`.

2021-01-13 12:40 UTC, ihhub commented on src/engine/screen.h
> +        virtual fheroes2::Rect getWindowDestRect() const
Please rename it into `getActiveWindowROI`.

2021-01-13 12:40 UTC, ihhub commented on src/engine/screen.h
> +        virtual fheroes2::Size getScreenResolution() const
Please rename it into `getCurrentScreenResolution`.

2021-01-13 13:03 UTC, Northfear commented
@ihhub done. `void _retrieveWindowInfo()` shouldn't be const probably, but other than I've fixed everything else.

2021-01-13 13:10 UTC, ihhub requested changes

2021-01-13 13:10 UTC, ihhub commented on src/engine/engine.cpp
> +    LocalEvent::Get().OpenTouchpad();
This is bug: we open a touchpad while quitting.

2021-01-13 13:13 UTC, ihhub commented
Hi @Northfear I fixed a bug when we were initializing touchpad at the time of quitting the application :)

2021-01-13 13:18 UTC, merged

2021-01-13 13:18 UTC, ihhub commented
@Northfear thanks a lot for such nice addition to the proejct!