Refactor campaign scenario window
ihhub/fheroes2 pull request #2553
Opened 2021-01-08 12:02 UTC by eos428

I am not sure how to title this PR properly, but in a gist, this PR:
- Moves most of campaign-related logic to from `game_newgame.cpp` to `game_campaign.cpp`
- Add some functions in CampaignData and Settings to get campaignData variables

The idea to making `SelectCampaignScenario` is to call this function when you win a campaign scenario, in which you'd select the next campaign scenarios, and so on.

Things I need some help on:
- Drawing the campaign scenario icons and making them clickable, the best solution probably requires the scenario data to be done first, though, so that it understands where to branch without making it magic number-y
- Redrawing the description, etc on picking a scenario, but I think this one should be enough with another call to `SelectCampaignScenario`

Things I'm saving for another (or more) PR, because I don't want to risk of making this PR too big:
- Making Game::SelectCampaignScenario() take a bool param `isStarting`
- A campaign scenario data (or whatever it's going to be named) that contains the scenario bonuses, description, branching possibilities... etc

2021-01-09 14:27 UTC, ihhub requested changes
Hi @eos428 , I left multiple comments and questions in this pull request. Could you please take a look at them and express your opinion about some comments?

2021-01-09 14:27 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +void SetScenarioBonus( Campaign::ScenarioBonusData scenarioBonus )
Since `Campaign::ScenarioBonusData` is a structure please pass it by const reference.

2021-01-09 14:27 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +}
Please add an empty line at the end of this file.

2021-01-09 14:27 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +int Settings::GetLastCompletedCampaignScenarioID() const
Settings strictly speaking is a place for storing/updating settings of the file while campaign is not a part of it. I think it would be better to move this code somewhere related to campaign code only.

2021-01-09 14:27 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +int Settings::GetLastCompletedCampaignScenarioID() const
Based on the above statement we could move `campaignData` outside Settings.

2021-01-10 03:34 UTC, eos428 commented on src/fheroes2/system/settings.cpp
> +int Settings::GetLastCompletedCampaignScenarioID() const
I agree with this. Should we make `CampaignStatic` to store campaign-related data separately?

2021-01-10 03:38 UTC, eos428 commented on src/fheroes2/system/settings.cpp
> +int Settings::GetLastCompletedCampaignScenarioID() const
On second thought, CampaignStatic doesn't seem like a suitable name when compared to the purposes of the other static classes. Maybe just straight up create a static `CampaignData::Get()`?

2021-01-12 15:52 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +int Settings::GetLastCompletedCampaignScenarioID() const
Let's add `CampaignData::instance()`.

2021-01-12 16:04 UTC, ihhub requested changes
Hi @eos428 good job! I left few comments here. Could you please take a look?

2021-01-12 16:04 UTC, ihhub commented on src/fheroes2/game/game_io.cpp
> +    if ( fileGameType | Game::TYPE_CAMPAIGN )
Here we need to be careful and use the check for save version as well.

2021-01-12 16:04 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +    fheroes2::Display & display = fheroes2::Display::instance();
Is it correct that the below code was just copy-pasted from the old place?

2021-01-12 16:04 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +#include "audio_music.h"
Could you please verify whether we need all these file headers to be included in this file? For example, I don't see the code related to `audio_music.h` inclusion.

2021-01-13 02:29 UTC, eos428 commented on src/fheroes2/game/game_campaign.cpp
> +#include "audio_music.h"
Yeah, a lot of them are not necessary here. I do wish it could be like C# where unnecessary usings are highlighted differently here :P

2021-01-13 02:30 UTC, eos428 commented on src/fheroes2/game/game_campaign.cpp
> +        return GetCampaignMaps( maps, PRICE_OF_LOYALTY_CAMPAIGN_SCENARIO_FILE_EXTENSION );
For this one, I'll go ahead with getting the file extension from the first element of the arrays if that's okay with you.

2021-01-13 02:34 UTC, eos428 commented on src/fheroes2/game/game_campaign.cpp
> +    fheroes2::Display & display = fheroes2::Display::instance();
I'm not sure why this one isn't marked as outdated. But until this particular commit, it's mostly copy-pasted from the old code. The major difference being that the campaign ID (and now the scenario ID too) will be obtained from CampaignData.

Also as of the latest commit, I am adding a bool param `isStarting` so that the scenario ID will be 0 if `isStarting` is true. However, I think we'd need to immediately set it to the next scenario ID when we come back to this function upon clearing a scenario.

2021-01-13 05:40 UTC, eos428 commented on src/fheroes2/game/game_campaign.cpp
> +    fheroes2::Display & display = fheroes2::Display::instance();
On second thought I think the `isStarting` bool isn't necessary. When a campaign scenario is completed we should call something like `CompleteCampaignScenario` which will either bring the player to the credits section or updating the currentScenarioID before calling `SelectCampaignScenario` again

2021-01-13 15:10 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +        void Reset();
Could you please rename `Reset` into `reset` to have the same method naming style?

2021-01-13 15:10 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +#include "audio_music.h"
It's a matter of IDE usage :)

2021-01-13 15:21 UTC, ihhub requested changes
Hi @eos428 , I left few comments. The biggest concern whether we're breaking existing saves for campaign. It's not a very big deal but we have to handle it either by increasing save type number or by checking a specific version of save files and ignoring the previous data.

2021-01-13 15:21 UTC, ihhub commented on src/fheroes2/game/game_io.cpp
> +    if ( conf.GameType() & Game::TYPE_CAMPAIGN && loadver >= FORMAT_VERSION_090_RELEASE )
We don't need to check save format version. We know that we're using the latest one :) Pleaser remove the second check.

2021-01-13 15:21 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> -    if ( conf.game_type & Game::TYPE_CAMPAIGN )
Is it correct to say that we're breaking previous campaign related saves?

2021-01-13 15:21 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> -    if ( conf.game_type & Game::TYPE_CAMPAIGN )
I think we do. In this case we have to increase the version of save file...

2021-01-14 12:21 UTC, eos428 commented on src/fheroes2/system/settings.cpp
> -    if ( conf.game_type & Game::TYPE_CAMPAIGN )
Done, but I can't help but feel the saves that would be broken are from a very specific timeframe for a version that's not even released ;D I think this would affect only a few testers for our commits from 0.8.4 to 0.9.0 IIRC.

2021-01-17 13:48 UTC, ihhub reviewed
Hi @eos428 could you please check no compatibility option? Does it lead to a crash? If no then please drop backward compability for campaign related saves.

2021-01-17 13:48 UTC, ihhub commented on src/fheroes2/system/settings.h
>  #define FORMAT_VERSION_090_RELEASE 9000
Please rename it into `FORMAT_VERSION_084_RELEASE` and then `FORMAT_VERSION_090_RELEASE_2` into `FORMAT_VERSION_090_RELEASE`.

2021-01-17 13:48 UTC, ihhub commented on src/fheroes2/system/settings.h
>  #define FORMAT_VERSION_090_RELEASE 9000
If we drop compatibility do old save loading crash the game?

2021-01-17 15:10 UTC, eos428 commented on src/fheroes2/system/settings.h
>  #define FORMAT_VERSION_090_RELEASE 9000
Without the backwards compability in `Settings`  >> and << operators the game crashes ;(

2021-01-20 14:10 UTC, ihhub commented on src/fheroes2/system/settings.h
>  #define FORMAT_VERSION_090_RELEASE 9000
Then we have to keep it as it is.

2021-01-20 14:22 UTC, merged

2021-01-20 14:23 UTC, ihhub commented
@eos428 thank you so much for your contribution to the project!