Fix scouting bugs + make crystal ball work
ihhub/fheroes2 pull request #2568
Opened 2021-01-10 14:08 UTC by vincent-grosbois

Here's a refactor of quick dialog info: now we have separated variables for scouting level for a given tile, and option settings etc. Previously all was merged into a "scoute" int which caused lots of complicated code

This fixes the following:
- bug where hero with scouting can see army size number even with "extended scouting" option off
- same bug with guarded mines
- #1460
- #1459

2021-01-13 15:33 UTC, ihhub requested changes
Hi @vincent-grosbois , the code looks okay. I just left multiple comments. Could you please take a look? I'll later test the changes.

2021-01-13 15:33 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +    uint32_t scoutingLevel = hero->GetSecondaryValues( Skill::Secondary::SCOUTING );
Please make this variable `const`.

2021-01-13 15:33 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +    const uint32_t thievesGuildCount = world.GetKingdom( currentColor ).GetCountThievesGuild();
Please cache `world.GetKingdom( currentColor )`.

2021-01-13 15:33 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +    uint32_t nbCrystalBalls = HasArtifact( Artifact::CRYSTAL_BALL );
Could you please rename this variable to `crystalBallCount` as not everyone (expecially not native English speakers) understand what **nb** stands for?

2021-01-13 15:33 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +bool Kingdom::IsTileVisibleFromCrystalBall( int32_t dest ) const
Could you please make input argument `const` as we don't modify it?

2021-01-22 14:44 UTC, ihhub requested changes
Hi @vincent-grosbois , I left just one comment regarding the approach of passing variables. Could you please take a look and give your opinion?

2021-01-22 14:44 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +            name_object = ShowArtifactInfo( tile, extendedScoutingOption, scoutingLevelForTile );
Hi @vincent-grosbois , there's a way to reduce the change we make in this pull request: instead of changing every function for showing the info from
```
if ( show ) {
```
to
```
if ( extendedScoutingOption && scoutingLevel > Skill::Level::NONE ) {
```

why don't we pass scouting level or even bool instead? By right we should calculate all logic in this `Dialog::QuickInfo` function. Current approach is bit problematic to understand. Of course not every function should be untouched by most of the logic for visibility should be in this function.

What do you think?

2021-01-22 16:18 UTC, vincent-grosbois commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +            name_object = ShowArtifactInfo( tile, extendedScoutingOption, scoutingLevelForTile );
Sorry not sure I follow
The point of this change is to change the function signature so we separately send the config options and the scouting levels explicitely, so that we can understand what's going on and prevent bugs. I don't really see what is the issue with the current approach, excep that it's more verbose, but it's the point.
I'm not sure what is the change you are asking for though

2021-01-23 12:51 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +            name_object = ShowArtifactInfo( tile, extendedScoutingOption, scoutingLevelForTile );
After another look I think you're right and we keep as it is.

2021-01-23 12:53 UTC, merged

2021-01-23 12:53 UTC, ihhub commented
Hi @vincent-grosbois , thanks you very much for your enormous contribution for the project!