Fix bugs in Kingdom View
ihhub/fheroes2 pull request #2597
Opened 2021-01-14 22:55 UTC by vincent-grosbois

Fix #2302
Fix #2596

The idea is that:
- for castle window, we don't need to update focus when opening the
window through Kingdown window
- for hero window, we already don't update focus, except when dismissing
heroes where this is forced

In order to have an up-to-date UI when a hero is dismissed from the
Kingdom view (ie, correct heroes icon bar and correct world map focus),
what I'm doing is redrawing the main window, then redrawing the
Kingdom UI on top. This ensures that the UI is always correct for all
resolutions

I'm only updating the list element in the Kingdom UI when a hero is
dismissed

2021-01-17 14:15 UTC, ihhub commented
Hi @vincent-grosbois could you please fix merge conflicts use std::unique_ptr for HeroRow class as it's implemented righ now for CastleRow? In this case the code will be more error-free.

2021-01-18 09:50 UTC, vincent-grosbois commented
@ihhub should be OK now

2021-01-25 13:28 UTC, ihhub requested changes
Hi @vincent-grosbois , could you please check given few comments?

2021-01-25 13:28 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +                if ( windowIsGameWorld ) {
Could you please explain the reason why we don't need to do fade out animation for some cases?

2021-01-25 13:48 UTC, vincent-grosbois commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +    CstlRow( Castle * ptr )
No default constructor is generated in this case, so this can never happen ;)

2021-01-25 13:48 UTC, vincent-grosbois commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +    HeroRow( Heroes * ptr )
same above

2021-01-25 13:51 UTC, vincent-grosbois commented on src/fheroes2/game/game_startgame.cpp
> +                if ( windowIsGameWorld ) {
Here we call this method without even being on the main map window, which this method assumes. I think that if we keep the fadeout it works more or less but we are stuck for 2 secs on the kingdom window while the fadeout animation plays in the background

2021-01-25 14:23 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +                if ( windowIsGameWorld ) {
I think this is because my changes broke fading option... eh...

2021-01-25 15:26 UTC, ihhub commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +    CstlRow( Castle * ptr )
I'm able to add `CstlRow() {}` to these changes which is a default constructor. From the code there's no indication that we assign **castle** member to some value in the default constuctor.

2021-01-25 15:40 UTC, vincent-grosbois commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +    CstlRow( Castle * ptr )
Sorry, there must be a misunderstanding.
Currently there is a constructor that takes a castle pointer and will set the castle pointer variable in the instance. There is no other way to build a CstlRow instance, so it's not possible that this pointer variable end up not initialized. There is also no default constructor generated. So no user of the class can construct an incorrect object using the curent API.

If you add an incorrect default constructor... then yes it's going to be incorrect :D
What is the point of adding a correct default constructor that would not be called?

2021-01-25 15:48 UTC, ihhub commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +    CstlRow( Castle * ptr )
What I meant is if we modify `CstlRow( Castle * ptr )` into `CstlRow( Castle * ptr = nullptr )` then we automatically make it as the default constructor. Even if we don't have calls to create a default constructor it's good to prevent such situation in the future.

2021-01-25 15:51 UTC, ihhub commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +    CstlRow( Castle * ptr )
Moreover, in the constructor you can assert ptr to make sure that it's no nullptr.

2021-01-25 15:59 UTC, vincent-grosbois commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +    CstlRow( Castle * ptr )
I will change it so we can merge it but I really don't see the point:
you are asking me to add a default constructor, that is not currently needed in the codebase, whose only purpose is to create an incorrect instance. Or, a default constructor that is never called but that will crash when called

2021-01-25 16:01 UTC, ihhub commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +    CstlRow( Castle * ptr )
What we can do without these constructors: just assing nullptr to castle member directly :)

2021-01-25 16:06 UTC, vincent-grosbois commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +    CstlRow( Castle * ptr )
But you can still do that with the constructors?

2021-01-25 16:16 UTC, ihhub commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +    CstlRow( Castle * ptr )
No. In C++11 and above you can assign values to members inside class declaration in the same way as you do in constructor. Default constructor or member's default value will do the same thing.

My worry about default constructor that in the future (not now) someone else or even we try to use this class with default constructor leading to uncertain results. Also most of static analyzers complain with 5 method rule where we have to declare a default constructor, copy and move constructor and their assignment variants.

My apologies for being too pedantic in this case but I faced few similar cases so it's better to prevent the problem rather than fix it :)

2021-01-25 16:37 UTC, ihhub reviewed
Hi @vincent-grosbois , just one place regarding the same variable. The rest looks pretty good.

2021-01-25 16:37 UTC, ihhub commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +            const bool mainWindowChanged = refreshHeroList;
There is no use of this variable as it's just a copy of `refreshHeroList` variable.

2021-01-25 16:37 UTC, ihhub commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +            if ( refreshHeroList || mainWindowChanged ) {
`mainWindowChanged` is `refreshHeroList`. Please remove `mainWindowChanged`

2021-01-26 11:05 UTC, merged