Implementing CMake buildsystem for project
ihhub/fheroes2 pull request #2629
Opened 2021-01-19 20:00 UTC by winterheart

This is implementation of cmake build project which, I believe, will help to ease maintain project.

Closes #2480.

2021-01-20 13:16 UTC, ihhub requested changes
Hi @winterheart , I left multiple comments here. On top of this these changes break normal make compilation.

2021-01-20 13:16 UTC, ihhub commented on src/thirdparty/CMakeLists.txt
> +endif(ENABLE_XML)
Please add one empty line at the end of this file.

2021-01-20 13:16 UTC, ihhub commented on .github/workflows/cmake_build.yml
> +
Please remove **one** empty line line at the end of this file.

2021-01-20 13:16 UTC, ihhub commented on .github/workflows/cmake_build.yml
> +          cmake -B build -DUSE_SDL_VERSION=${{ matrix.config.sdl_version }} -DENABLE_IMAGE=ON -DENABLE_MIXER=ON -DENABLE_UNICODE=ON
We're missing **FHEROES2_STRICT_COMPILATION** flag for compilation

2021-01-20 13:16 UTC, ihhub commented on CMakeLists.txt
> +option(ENABLE_TOOLS		"Enable additional tools" OFF)
Please correct identation of this text.

2021-01-20 13:16 UTC, ihhub commented on CMakeLists.txt
> +
Please remove this empty line.

2021-01-20 13:16 UTC, ihhub commented on CMakeLists.txt
> +install(FILES CONTRIBUTING.md README.md changelog.txt DESTINATION ${CMAKE_INSTALL_DOCDIR})
If install is designed for packaging please remove `CONTRIBUTING.md README.md` files but include `doc/README.txt` without **doc** path.

2021-01-20 13:16 UTC, ihhub commented on README.md
> +```
We have scripts to install all these libraries. Please either remove this information or refer to them.

2021-01-20 13:16 UTC, ihhub commented on README.md
> +cmake --build build -j2
This is an incorrect command. What if your machine has 16 cores? `j2` flag means compile in 2 threads. Also on low profile machines such as Raspberry Pi users might face RAM limitation issues while compiling in multiple threads.

2021-01-20 13:16 UTC, ihhub commented on cmake/FindSDL2.cmake
> +# Distributed under the OSI-approved BSD 3-Clause License.  See accompanying
Could you please tell where these cmake files come from?

2021-01-20 13:16 UTC, ihhub commented on cmake/README.md
> +These modules are based on the SDL (1.2) modules, with the same names,
The above list includes only SDL 2 packages while here we're referring to 1.2 version. Is it a mistake?

2021-01-25 16:35 UTC, kant2002 commented
@winterheart can you take a look at https://github.com/ihhub/fheroes2/pull/2669 ? I suspect that you would be affected by my PR in the tools folder. My PR would broke at least this line `add_executable(xmi2mid xmi2mid.cpp)` since I rename file to avoid creation of xmi2mid.obj files from two different xmi2mid.cpp files.

2021-01-25 21:54 UTC, winterheart commented on src/dist/Makefile
> +SOURCEDIR  := $(wildcard $(SOURCEROOT)/*/)
This currently broken, need to rework things...

 As I noted before, that why bare Makefiles is not best solution for crossplatform environment. `ls` on Linux and BSD has different logic, so here I tried to workaround with Makefile built-in function, but this it not work. Need to rethink, how bypass this problem.

2021-01-25 21:56 UTC, winterheart commented on README.md
> +```
Scripts will **remove** packages, which not that user asked for. If intention was install additional dependencies, that should install but not remove packages, or user's system may be broken.

2021-01-31 02:32 UTC, ihhub commented on README.md
> +```
I remember there was a solid reason to do this on Unix systems. I will check it again.

2021-01-31 07:18 UTC, kant2002 commented on src/tools/CMakeLists.txt
> +add_executable(xmi2mid xmi2mid.cpp)
```suggestion
add_executable(xmi2mid xmi2mid_cli.cpp)
```

2021-01-31 12:03 UTC, winterheart commented on README.md
> +```
Removed section.

2021-01-31 12:04 UTC, winterheart commented on cmake/FindSDL2.cmake
> +# Distributed under the OSI-approved BSD 3-Clause License.  See accompanying
Added separate file `cmake/README_fheroes.md` with proper attribution.

2021-01-31 12:06 UTC, winterheart commented on cmake/README.md
> +These modules are based on the SDL (1.2) modules, with the same names,
No there no mistake. SDL2 modules based on 1.2 versions, which already included in CMake. SDL2 modules does not exists in CMake core modules, so there added modules which  mimics SDL1.2 behaviour.

2021-01-31 12:06 UTC, winterheart commented on src/tools/CMakeLists.txt
> +add_executable(xmi2mid xmi2mid.cpp)
fixed, thank you

2021-01-31 12:11 UTC, winterheart commented on src/dist/Makefile
> +SOURCEDIR  := $(wildcard $(SOURCEROOT)/*/)
Reworked this part of code as 

```
SOURCEROOT := ../fheroes2
SOURCEDIR  := $(filter %/, $(wildcard $(SOURCEROOT)/*/)) $(filter %/, $(wildcard $(SOURCEROOT)/*/*/))
POT        := $(TARGET).pot

SEARCH     := $(wildcard $(SOURCEROOT)/*/*.cpp) $(wildcard $(SOURCEROOT)/*/*/*.cpp)
```
which uses internal Makefile functions. Additionally simplified code and made it more robust.

2021-01-31 12:37 UTC, winterheart commented
@ihhub fixed all review requests.

2021-02-04 04:32 UTC, ihhub requested changes
Hi @winterheart , could you please check my questions?

2021-02-04 04:32 UTC, ihhub commented on CMakeLists.txt
> +install(FILES doc/README.txt changelog.txt DESTINATION ${CMAKE_INSTALL_DOCDIR})
Looks like this CMake solution doesn't support Windows, doesn't it? If it is the case we should add a code to even prevent trying to build on Windows.

2021-02-04 04:32 UTC, ihhub commented on .github/workflows/cmake_build.yml
> +          sudo apt-get install ${{ matrix.config.sdl_packages }}
Why do we need to install SDL packages if CMake should do this? Otherwise there's no value to even use CMake as the only thing is left is this case is to compile the application.

2021-02-05 07:06 UTC, kant2002 commented on CMakeLists.txt
> +install(FILES doc/README.txt changelog.txt DESTINATION ${CMAKE_INSTALL_DOCDIR})
I'm interested in Windows support, and can make changes if needed.

2021-02-07 21:45 UTC, winterheart commented on CMakeLists.txt
> +install(FILES doc/README.txt changelog.txt DESTINATION ${CMAKE_INSTALL_DOCDIR})
I've not tested on Windows yet, just because that not clear what is situation about Windows support in project right now. Windows support can be easily achieved, but for now I just propose base framework for future expansion.

2021-02-07 21:50 UTC, winterheart commented on .github/workflows/cmake_build.yml
> +          sudo apt-get install ${{ matrix.config.sdl_packages }}
To be clear, CMake is not package manager that automatically resolves and installs dependencies, it's build system that greatly ease integration with system packages and system discovery capabilities.
This can be achieved by another ways, for example via Conan package manager, which has native support for CMake project system.

2021-02-09 15:32 UTC, ihhub commented on CMakeLists.txt
> +install(FILES doc/README.txt changelog.txt DESTINATION ${CMAKE_INSTALL_DOCDIR})
Most of developers use Windows. Let's stick to the original implementation here to avoid a huge pull request.

2021-02-23 22:01 UTC, winterheart commented on .github/workflows/cmake_build.yml
> +          sudo apt-get install ${{ matrix.config.sdl_packages }}
I've implemented windows compilation with vcpkg integration, that looks promising as substitute for current hand-written dependency management. While it can be used for macOS and Linux with conjunction with cmake, I'd suggest to stick with system-wide dependencies as they more convenient for end-users. For Windows, vcpkg is seems only viable option to give developer flexible and wide-used tool for dependency management.

2021-02-24 07:41 UTC, kant2002 commented on .github/workflows/cmake_build.yml
> +          sudo apt-get install ${{ matrix.config.sdl_packages }}
This is match my expectations on the modern cross platform work in C++. I'm not sure that vcpckg is that convenient, but integration with VS was okish.

2021-03-01 15:15 UTC, winterheart commented
So, what to do next?

2021-03-01 23:58 UTC, ihhub commented
> So, what to do next?

I'll come back to your pull request soon 🙂

2021-03-02 16:03 UTC, ihhub requested changes
Hi @winterheart, I left few comments. Would you mind to take a look?

Also could you please create a separate pull request for endian file as other person wants to do the same fix in #2894 ? Since you're the first one who made this change as it'd be unfair to approve that pull request ignoring your fix.

2021-03-14 11:19 UTC, winterheart commented on .github/workflows/cmake_build.yml
> +          vcpkg --triplet x64-windows install ${{ matrix.config.sdl_packages }}
It takes 10 mins only first time, later builds should be taken from cache. Scripts only handle SDL1/SDL2 libraries with deps, while vcpkg can handle whole dependency list, including gettext and tinyxml (only drawback is they not supporting SDL1, but as I can see, fheroes2 moves towards to SDL2 only dependencies). I tried to integrate cmake with custom scripts location, but layout of installation contradicts with locations that expected by cmake's FindPackage modules which requires to modify either scripts or cmake module.

2021-03-14 11:20 UTC, winterheart commented on README.md
> +# SDL2
vcpkg don't have SDL1 packages that why there only SDL2 instructions.

2021-03-14 11:35 UTC, winterheart commented on README.md
> +git clone https://github.com/microsoft/vcpkg.git
This instruction for first-time installation. If user already cloned fheroes2 repository, then he already has git. Instructions for installing vcpkg taken from vcpkg site.

2021-03-14 11:42 UTC, winterheart commented on CMakeLists.txt
> +project(fheroes2 VERSION 0.8.4 LANGUAGES C CXX)
updated

2021-03-31 02:26 UTC, kant2002 commented
@winterheart Ooh thanks, for splitting up application onto libraries, that make like for development of tools and tests much easier!

2021-04-14 21:10 UTC, qarkai commented on CMakeLists.txt
> +set(USE_SDL_VERSION SDL CACHE STRING "SDL version")
Makefile uses SDL2 by default. I think here should be SDL2 too.

2021-04-15 15:28 UTC, kant2002 commented on README.md
> +For Windows you'll need Visual Studio 2019 with C++ support and [vcpkg package manager](https://vcpkg.readthedocs.io/en/latest/) for dependency management.
@ihhub How this can be moved forward, even if with small issues like that one? For me CMake greatly simplify life, since  project management can be simplified, and this PR already have engine as separate binary component. Current state of Visual Studio support with single vcproj seems not very efficient to me, since I have to build project one by one, all code reuse not on the libraries level, but on files level for `tools` project. I want to have tests inside Visual Studio and this simply would not fly if we do not have SLN file, which explicitly gitignored in this repository (not sure why).

Maybe this PR can land? and if you have quality of life improvements for the newcomers, I can fix that. Given that @winterheart seems to be slightly discouraged to continue with this PR. If that's the case I more then happy fix all issues, just want that all this excellent work to be attributed to him.

2021-04-15 16:04 UTC, ihhub commented
Hi @winterheart  and @kant2002 , what we need to do in this pull request to be in ready state:
- remove Windows from Github Actions. Windows build is too long and for every new pull request it will drag a lot of time.
- CMakeLists.txt: update version to 0.9.2 and make SDL 2 as a default option
- create a separate file called `doc/README_cmake.md` with a description of compilation. The main page should not be too long for users to scroll. We could refer to newly created file in the main README.
- rename `cmake/README_fheroes.md` into `cmake/README_fheroes2.md`

Most of things I can do myself except file renaming.

2021-04-15 16:25 UTC, ihhub commented
I've done all needed changes. I'll merge it once compilation is completed and I'll have morning by my time :)

2021-04-15 16:28 UTC, kant2002 commented
Thanks a lot! if you need some cleanup after that, in docs or other places. Let me know.

2021-04-15 16:29 UTC, ihhub commented
> Thanks a lot! if you need some cleanup after that, in docs or other places. Let me know.

We'll surely need it as well as to add back Windows build. I think we need to figure out the way how to use our scripts which are much faster than vcpkg.

2021-04-15 16:32 UTC, ihhub approved these changes

2021-04-15 16:46 UTC, merged

2021-04-15 16:46 UTC, ihhub commented
@winterheart , thank you so much for helping the project!