Deterministic bonus for hero level-up
ihhub/fheroes2 pull request #2630
Opened 2021-01-19 20:31 UTC by vincent-grosbois

2021-01-25 13:24 UTC, ihhub requested changes
Hi @vincent-grosbois , I left multiple comments here. Could you please take a look?

2021-01-25 13:24 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +const int SEED_VERSION = 9001;
Please add `FORMAT_VERSION_090_PRE_RELEASE` with **9001** value in `settings.h` file and change `FORMAT_VERSION_090_RELEASE` value to **9002** instead of this static variable.

2021-01-25 13:24 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +    if ( Game::GetLoadVersion() >= SEED_VERSION ) {
There's no need to add a check while writing a save file. Please remove this check.

2021-01-25 13:24 UTC, ihhub commented on src/fheroes2/heroes/skill.h
> +    public:
We shouldn't allow an access to members of a class. Please do not do this.

2021-01-25 13:24 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +template <class T>
Please put this function under unnamed namespace at the top of the file jsut after file header inclusions. This is to do not pollute global namespace and to keep all static functions in one place.

2021-01-25 13:24 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +/* We generate seeds based on the hero and global world map seed
Please put this comment inside the method to avoid a situation when someone will move the method but keep the comment :)

2021-01-25 13:24 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> + * skill would always be the same  once the 1st one is selected.
Please remove an extra space before word **once**.

2021-01-25 13:24 UTC, ihhub commented on src/fheroes2/heroes/heroes.h
> +    uint32_t seedSecondaySkillRandomChoose;
Please assign **0** as a default values to all members since we don't declare constructor.

2021-02-09 15:36 UTC, ihhub commented
Hi @idshibanov , could you please give your opinion about the way how we solve this issue? I think the original game solves it in a different way. Do you know about it?

2021-02-10 01:17 UTC, idshibanov commented on src/fheroes2/heroes/heroes.cpp
> +        hash_combine( hash, GetLevelSkill( skillId ) );
In original game each hero (hired and in the pool) gets a random seed (in range of 0-255) on new game launch. When level up event happens random generator is initialized with this seed (+30 every time if multiple level ups). Same seed is used every time. Skill selection is obviously based on hero's faction (we have those values in `game_static.cpp`).

Obviously with this logic values will change if hero's skills change between saves. We just have to decide if we want to reproduce original behavior or use better randomness for fheroes2.

2021-02-10 21:43 UTC, vincent-grosbois commented on src/fheroes2/heroes/heroes.cpp
> +        hash_combine( hash, GetLevelSkill( skillId ) );
Hello
I don't really get what's the difference in practice between both versions.
Anyway I think the point is that with reloading your save, you are garanteed to received the same skills, which is the case with this PR

2021-02-16 17:34 UTC, ihhub approved these changes

2021-02-17 04:07 UTC, merged

2021-02-17 04:08 UTC, ihhub commented
@vincent-grosbois , a bunch of thanks for your contribution to the project!