Hide hero shadow in castle
ihhub/fheroes2 pull request #2637
Opened 2021-01-20 16:40 UTC by vasilenkoalexey

Hide hero shadow when hero in castle (like in OG)

2021-01-23 12:56 UTC, ihhub commented on src/fheroes2/heroes/heroes_move.cpp
> +    const Maps::Tiles & tile = world.GetTiles( center.x, center.y );
Let's call it `heroTile` instead other if-bodies can have the same name.

2021-01-24 06:20 UTC, ihhub requested changes
Hi @vasilenkoalexey , I left 2 comments. Could you please take a look?

2021-01-24 06:20 UTC, ihhub commented on src/fheroes2/heroes/heroes_move.cpp
> +        if ( tile.GetObject( false ) == MP2::OBJ_CASTLE && ( sprite_index > 44 || ( sprite_index % 9 ) < 5 ) ) {
Checking sprite index of a hero might be a bad idea. Please check with dimension door and town portal spells.

2021-01-24 16:47 UTC, vasilenkoalexey commented on src/fheroes2/heroes/heroes_move.cpp
> +        if ( tile.GetObject( false ) == MP2::OBJ_CASTLE && ( sprite_index > 44 || ( sprite_index % 9 ) < 5 ) ) {
This is the definition that the hero is moving and he is somewhere in the middle between the bottom tile and top castle tile. I dont known how town portal spells can help here :(

2021-01-25 13:55 UTC, ihhub commented on src/fheroes2/heroes/heroes_move.cpp
> +        if ( tile.GetObject( false ) == MP2::OBJ_CASTLE && ( sprite_index > 44 || ( sprite_index % 9 ) < 5 ) ) {
For example, I used Town Portal spell to teleport a hero to a castle. As you could see the location of the hero could be any:
![image](https://user-images.githubusercontent.com/19829520/105714979-fe68b300-5f57-11eb-96dc-56bd45a7691e.png)

2021-01-26 22:47 UTC, vasilenkoalexey commented on src/fheroes2/heroes/heroes_move.cpp
> +        if ( tile.GetObject( false ) == MP2::OBJ_CASTLE && ( sprite_index > 44 || ( sprite_index % 9 ) < 5 ) ) {
> As you could see the location of the hero could be any:

Do you mean direction? I dont see any problem here - hero on castle, and there is no hero shadow. `sprite_index > 44` mean hero turns in place without moving (we should not render hero shadow when he just turn in castle). `( sprite_index % 9 ) < 5` mean hero goes out of the castle but has passed less than "half way" to the bottom tile. And we start to draw hero shadow only if he has passed more than "half way". At least I see this kind of logic in  the OG... I don't understand why we can't use sprite index here, and how Town Portal Spell can help implement this. Could you explain in more detail what you mean?

2021-01-27 10:21 UTC, ihhub commented on src/fheroes2/heroes/heroes_move.cpp
> +        if ( tile.GetObject( false ) == MP2::OBJ_CASTLE && ( sprite_index > 44 || ( sprite_index % 9 ) < 5 ) ) {
I meant that while using Town Portal spell we don't the direction of a hero leading to a false condition for your code which later shows a shadow of the hero.

Give me please some time to come up with a solution to cover all cases.

2021-01-27 22:55 UTC, vasilenkoalexey commented on src/fheroes2/heroes/heroes_move.cpp
> +        if ( tile.GetObject( false ) == MP2::OBJ_CASTLE && ( sprite_index > 44 || ( sprite_index % 9 ) < 5 ) ) {
> Give me please some time to come up with a solution to cover all cases.

Shure. But for all hero directions `sprite_index % 9` always is zero (if hero not moving or turning). I decided to check "with  eyes" for all Town Portal directions and did not see the hero shadow
![hero](https://user-images.githubusercontent.com/24250224/106065046-c30ee580-610b-11eb-9e0c-ec875368cec3.jpg)

2021-02-01 13:22 UTC, ihhub commented
Hi @vasilenkoalexey ,

actually in the original game hero has a shadow while in a castle:
![image](https://user-images.githubusercontent.com/19829520/106464364-84927580-64d3-11eb-8268-f36221322356.png)

2021-02-01 15:00 UTC, vasilenkoalexey commented
> actually in the original game hero has a shadow while in a castle:

Hmm... You right, but castle drawn over shadow... So i will cover this case in fututre PR with drawing the hero and the shadow in different loops.

2021-02-01 15:00 UTC, closed without merging