Fade boat shadow
ihhub/fheroes2 pull request #2641
Opened 2021-01-20 20:32 UTC by vasilenkoalexey

Should fix #2441 and #2442
Also we should draw animate for monsters and boats only if `drawMonstersAndBoats == true`, also we should draw animate for monsters and boats before redraw top, because boat have long shadow.

2021-01-22 15:06 UTC, ihhub requested changes
Hi @vasilenkoalexey , I left multiple comments here. Could you please take a look?

2021-01-22 15:06 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +        const Game::ObjectFadeAnimation::Info & fadeInfo = Game::ObjectFadeAnimation::Get();
Please declare this object outside the if-body as it's same as on line 256.

2021-01-22 15:06 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
>          const Point & mp = Maps::GetPoint( fadeInfo.tile );
Declare this variable inside `if ( icn != ICN::MONS32 && fadeInfo.object != MP2::OBJ_BOAT ) {` block.

2021-01-22 15:06 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +            const Point & mp = Maps::GetPoint( fadeInfo.tile );
What if we have a boat animation just between 2 boats: at the top and at the bottom? Would be more accurate to do in this way:
- check if it's a valid animation
- check if it's boat or monster
- set a boolean flag to true if above conditions are true
- if the boolean flag is true check if current position in the loop above is the same
- if the position is the same do the animation

Does it make more sense?

2021-01-22 18:02 UTC, vasilenkoalexey commented on src/fheroes2/gui/interface_gamearea.cpp
> +            const Point & mp = Maps::GetPoint( fadeInfo.tile );
I got idea, but i suggest put this logic to `RedrawBoat` then we can use `withShadow ` flag during fade in\out. It will be more correct. What you think?

2021-01-25 14:09 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +            const Point & mp = Maps::GetPoint( fadeInfo.tile );
Mm... I don't get about `withShadow` flag related to fading animation. Could you please explain the structure of your future implementation?

2021-01-26 22:17 UTC, vasilenkoalexey commented on src/fheroes2/gui/interface_gamearea.cpp
> +            const Point & mp = Maps::GetPoint( fadeInfo.tile );
> Mm... I don't get about `withShadow` flag related to fading animation. Could you please explain the structure of your future implementation?

So... For example we process boat fade out... Called `RedrawMonstersAndBoat` (with alpha and shadow)  inside` GameArea::Redraw`, then called `hero.second->Redraw` where `RedrawBottom4Hero` called in which `RedrawMonstersAndBoat` called again with alpha (because we still process fade out) but WITHOUT shadow (as we want prevent shadow double rendering). In addition, I have a future solution for #2179, where I also plan to redraw the boat inside `hero.second->Redraw`.  In the last commit, I implemented the correct way to do this, and realized more common and correct way for fade processing.

2021-01-30 13:57 UTC, ihhub requested changes
Hi @vasilenkoalexey , please remove tuple usage in the code. It is very confusing to read it for anyone.

2021-01-30 13:57 UTC, ihhub commented on src/fheroes2/game/game.h
> +        using FadeTask = std::tuple<uint8_t, uint32_t, int32_t, uint32_t, uint32_t, uint32_t, bool, bool, uint8_t>;
Please do **not** use tuple. For example, no developer will understand the meaning of these arguments. Use a normal structure.

2021-01-30 13:57 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +            const auto alpha = std::get<5>( fadeTask );
Using a normal structure we don't even need to use extra temporary variables.

2021-01-30 20:20 UTC, vasilenkoalexey commented on src/fheroes2/gui/interface_gamearea.cpp
> +            const auto alpha = std::get<5>( fadeTask );
Done

2021-02-13 14:05 UTC, ihhub requested changes
Hi @vasilenkoalexey , I left multiple comments here. Could you please take a look?

2021-02-13 14:05 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +            if ( fadeTask.animationIndex ) {
Is it correct that here we can use only values above 0? If yes could you please write an explicit expression of it as negative values will make this condition true as well.

2021-02-13 14:42 UTC, vasilenkoalexey commented on src/fheroes2/game/game.h
> +            bool fadeIn;
> Is there a case when the same object has both animation types?
Yes, summon boat have both fade in and fade out animation.

2021-02-13 14:55 UTC, vasilenkoalexey commented on src/fheroes2/heroes/heroes_spell.cpp
> +    for ( auto it = boats.cbegin(); it != boats.cend(); ++it ) {
I just made the style of the code slightly more modern (romove `u32` and `auto` using).

The last commit, in which summon boat does not depend on the skills of the hero, I agreed with Branikolog. If it important i can put this changes to another pr.

2021-02-13 15:33 UTC, vasilenkoalexey commented on src/fheroes2/maps/maps_tiles.cpp
> -    if ( spriteIndicies.second != -1 ) {
Look at `Maps::Tiles::GetMonsterSpriteIndices( const Tiles & tile, uint32_t monsterIndex )`
there only one place where `spriteIndices.second` filled
`spriteIndices.second = monsterIndex * 9 + 1 + monsterAnimationSequence[( Game::MapsAnimationFrame() + mp.x * mp.y ) % ARRAY_COUNT( monsterAnimationSequence )];`
It mean we can use zero value here as "no animation" flag. I think its more comprehensive solution.

2021-02-13 15:43 UTC, vasilenkoalexey commented on src/fheroes2/gui/interface_gamearea.cpp
> +            if ( fadeTask.animationIndex ) {
`fadeTask.animationIndex` unsigned and filled in `Game::ObjectFadeAnimation::StartFadeTask` by `Maps::Tiles::GetMonsterSpriteIndices` in one case (I explained above about this method) or by `ICN::AnimationFrame` in another case (when we draw object but not monster) and this method again unsigned (another reason to make unsigned animation index and using zero value).

2021-02-13 16:10 UTC, vasilenkoalexey commented on src/fheroes2/heroes/heroes_action.cpp
> +    if ( tile.GetObject() != MP2::OBJ_ZERO )
Done

2021-02-13 16:10 UTC, vasilenkoalexey commented on src/fheroes2/game/game_startgame.cpp
> +                        if ( fadeTask.alpha < ( 235 ) ) {
Done

2021-02-13 16:10 UTC, vasilenkoalexey commented on src/fheroes2/game/game.h
> +            uint32_t objectIndex;
Done

2021-02-19 00:10 UTC, ihhub requested changes
Hi @vasilenkoalexey , could you please take a look on few given comments? Soon I will ask QA team to test it deeply again.

2021-02-19 00:10 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> +    for ( auto it = boats.cbegin(); it != boats.cend(); ++it ) {
Could we please revert changes in this file and open another pull request for it? It is a goo practice to separate changes for different issue.

2021-02-21 22:24 UTC, vasilenkoalexey commented on src/fheroes2/game/game.h
> +#include "mp2.h"
Done

2021-02-21 22:24 UTC, vasilenkoalexey commented on src/fheroes2/game/game.h
> +                objectTileset = objectTileset_;
Done

2021-02-21 22:25 UTC, vasilenkoalexey commented
Done

2021-02-24 13:33 UTC, merged

2021-02-24 13:33 UTC, ihhub commented
@vasilenkoalexey , thank you very much for fixing these issues!