[Bugfix][2646] Ability to retreat when player has no towns
ihhub/fheroes2 pull request #2649
Opened 2021-01-22 12:51 UTC by tau3

Hello!

This is a fix for #2646. It needs to be checked before merge. Can I have a save file to reproduce?

2021-01-22 14:43 UTC, Branikolog commented
[BUG.zip](https://github.com/ihhub/fheroes2/files/5856540/BUG.zip)

2021-01-23 12:50 UTC, tau3 commented
@Branikolog thank you! 

I was able to retreat after being attacked by the nearest hostile hero. 👌

2021-01-25 13:52 UTC, ihhub requested changes
Hi @tau3 , could you please check proposed approach?

2021-01-25 13:52 UTC, ihhub commented on src/fheroes2/battle/battle_arena.cpp
> -    return hero && hero->isHeroes() && NULL == hero->inCastle() && world.GetKingdom( hero->GetColor() ).GetCastles().size();
Could we please just remove `&& world.GetKingdom( hero->GetColor() ).GetCastles().size()` for the whole pull request changes?

2021-01-30 13:59 UTC, merged

2021-01-30 14:00 UTC, ihhub commented
@tau3 thank you very much for the fix!