Fix #2654
ihhub/fheroes2 pull request #2658
Opened 2021-01-23 17:39 UTC by vincent-grosbois

2021-01-24 15:25 UTC, ihhub commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +        btnMarket.disable();
It'll be more safe to call `btnMarket.hide();` as well then we won't draw this button.

2021-01-24 15:28 UTC, ihhub requested changes
Hi @vincent-grosbois , I left few comments here. Would you mind to take a look?

2021-01-24 15:28 UTC, ihhub commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +        btnMarket.disable();
It'll be more safe to call btnMarket.hide(); as well then we won't draw this button.

2021-01-24 15:28 UTC, ihhub commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +            btnMarket.draw();
Please move `btnMarket.draw();` outside this if-body.

2021-01-24 15:28 UTC, ihhub commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +        if ( allowPayment || kingdom.GetCountMarketplace() == 0 ) {
If we hide the button before the loop then we don't need `kingdom.GetCountMarketplace() == 0` condition.

2021-01-28 13:29 UTC, Branikolog commented
Hello, @vincent-grosbois 
A "castle" button with marketplace still appears, if we don't have market built in town and some creatures are willing to join us.
![image](https://user-images.githubusercontent.com/55348946/106144945-fbeba080-6185-11eb-992e-84f161661851.png)

2021-01-30 15:04 UTC, merged

2021-01-30 15:04 UTC, ihhub commented
@vincent-grosbois , thank you very much for the fix!