UI fixes in game start dialog
ihhub/fheroes2 pull request #2660
Opened 2021-01-23 19:29 UTC by kant2002

- Fixed position of Scenario parameters dialog
- Fixed position of Scenario Map selection dialog
- Change text in map size hint, to be displayed in more pleasant manner.
See # 1235

2021-01-25 14:07 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> -    Rect rt( ( display.width() - panel.width() ) / 2, ( display.height() - panel.height() ) / 2, panel.width(), panel.height() );
Hi @kant2002 , we might need to revert this and similar change in **game_scenarioinfo.cpp** file as the description of the original issue might be outdated. Please do not do any change as of now.

2021-01-30 15:15 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> -    Rect rt( ( display.width() - panel.width() ) / 2, ( display.height() - panel.height() ) / 2, panel.width(), panel.height() );
Hi @kant2002 , please revert this and the change in `game_scenarioinfo.cpp` as it's confirmed that we don't need to show exactly the same as in the original game.

2021-01-30 15:24 UTC, kant2002 commented
Okay. Will revert

On Sat, Jan 30, 2021 at 21:15 Ihar Hubchyk <notifications@github.com> wrote:

> *@ihhub* commented on this pull request.
> ------------------------------
>
> In src/fheroes2/dialog/dialog_selectscenario.cpp
> <https://github.com/ihhub/fheroes2/pull/2660#discussion_r567257076>:
>
> > @@ -202,7 +202,7 @@ const Maps::FileInfo * Dialog::SelectScenario( const MapsFileInfoList & all, siz
>      }
>
>      const fheroes2::Sprite & panel = fheroes2::AGG::GetICN( ICN::REQSBKG, 0 );
> -    Rect rt( ( display.width() - panel.width() ) / 2, ( display.height() - panel.height() ) / 2, panel.width(), panel.height() );
>
> Hi @kant2002 <https://github.com/kant2002> , please revert this and the
> change in game_scenarioinfo.cpp as it's confirmed that we don't need to
> show exactly the same as in the original game.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ihhub/fheroes2/pull/2660#discussion_r567257076>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABAPKN3LFXOX2B5VG6TDHTLS4QPAXANCNFSM4WP5HMYA>
> .
>

2021-02-09 12:37 UTC, ihhub requested changes

2021-02-09 12:37 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +                             _( "Indicates whether the map\r\nis small (36 x 36), medium\r\n(72 x 72), large (108 x 108),\r\nor extra large (144 x 144)." ), Font::BIG );
Please remove '\r' as it's not parsed by our string parser.

2021-02-09 13:07 UTC, kant2002 commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +                             _( "Indicates whether the map\r\nis small (36 x 36), medium\r\n(72 x 72), large (108 x 108),\r\nor extra large (144 x 144)." ), Font::BIG );
What kind of string parser? I test that before post, so maybe i'm not aware about something? Or this would be Windows only change?

2021-02-09 14:40 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +                             _( "Indicates whether the map\r\nis small (36 x 36), medium\r\n(72 x 72), large (108 x 108),\r\nor extra large (144 x 144)." ), Font::BIG );
Like `TextBox` class but you're right that this shouldn't impact.

2021-02-09 14:42 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +                             _( "Indicates whether the map\r\nis small (36 x 36), medium\r\n(72 x 72), large (108 x 108),\r\nor extra large (144 x 144)." ), Font::BIG );
It does nothing: nothing bad but nothing good at all :) A smaller string without \r is always better as it will eat less memory. I see no place in the game using \r.

2021-02-11 17:15 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +                             _( "Indicates whether the map\r\nis small (36 x 36), medium\r\n(72 x 72), large (108 x 108),\r\nor extra large (144 x 144)." ), Font::BIG );
I removed \r symbol usage as it does nothing. Pardon me please if I was too pushy.

2021-02-11 17:22 UTC, merged

2021-02-11 17:22 UTC, ihhub commented
@kant2002 thank you so much for your contribution to the project!