Campaign continuation initial support
ihhub/fheroes2 pull request #2661
Opened 2021-01-24 08:08 UTC by eos428

It was definitely more than I'd expect... It's definitely not complete so far so I'd like your input on how to proceed, aside from the usual reviews of course.

Implemented logics:
- Renamed previous CampaignData to CampaignSaveData
- CampaignData and CampaignScenarioData
- Refactor DrawCampaignScenarioIcons()
- Use CampaignData and CampaignScenarioData for Roland and Archibald campaigns, which I will do partially for this PR.

Pending logic for this PR:
- Proper implementation of CompleteCampaignScenario()
- Probably further refactor DrawCampaignScenarioIcons(), or maybe just use a layout data or something

Also, if anyone wants to help me test by giving me save files right before a campaign scenario is cleared, that'd be much appreciated!

2021-01-24 18:47 UTC, LeHerosInconnu commented
Hello @eos428,

> Also, if anyone wants to help me test by giving me save files right before a campaign scenario is cleared, that'd be much appreciated!

In the original game, there are cheat codes to win and lose a scenario.
There is nothing similar already implemented in fheroes2?
This would make testing the game much easier.

2021-01-25 11:55 UTC, eos428 commented
In the end what I did was actually playing through them - I decided to just have some fun in a while haha

2021-01-30 16:52 UTC, ihhub requested changes
Hi @eos428 , I left multiple comments. Could you please take a look?

2021-01-30 16:52 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +            const std::vector<int> nextMaps = _scenarios[i].getNextMaps();
Here we copy a container. Please use const reference.

2021-01-30 16:52 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +            for ( size_t j = 0, nextMapCount = nextMaps.size(); j < nextMapCount; ++j ) {
Please change to `for ( size_t j = 0; j < nextMaps.size(); ++j ) {`. Compiler will do the rest.

2021-01-30 16:52 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +            for ( size_t j = 0, nextMapCount = nextMaps.size(); j < nextMapCount; ++j ) {
Also please change to `j` to something more meaningful like `mapId`.

2021-01-30 16:52 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +                    scenarioIDs.emplace_back( nextMaps[i] );
Should we break here? If there a chance when we have multiple maps with the same ID?

2021-01-30 16:52 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +                startingScenarios.emplace_back( _scenarios[i].getScenarioID() );
Is there a possiblity to have multiple start scenarios? If not please break the loop after.

2021-01-30 16:52 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +            if ( std::any_of( nextMaps.begin(), nextMaps.end(), [&]( const int nextMap ) { return nextMap == scenarioID; } ) )
Please pass only `scenarioID` to the capture list. We shouldn't expose what is not needed.

2021-01-30 16:52 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +        for ( int i = 0, count = _scenarios.size(); i < count; ++i ) {
Please change to `for ( int i = 0; i < _scenarios.size(); ++i ) {`

2021-01-30 16:52 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.cpp
> +    bool TryGetMatchingFile( const std::string & fileName, std::string & matchingFilePath )
Please name this function from a non-capital letter.

2021-01-30 16:52 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +            int x = currentX, y = middleY;
Please initialize each variable at a separate line.

2021-01-30 16:52 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +            for ( int j = 0, prevScenarioNextMapsCount = prevScenarioNextMaps.size(); j < prevScenarioNextMapsCount; ++j ) {
Please change to `for ( int j = 0; j < prevScenarioNextMaprevScenarioNextMaps.size()psCount; ++j ) {`

2021-01-30 16:52 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +                if ( std::none_of( nextMaps.begin(), nextMaps.end(), [&]( int scenarioID ) { return scenarioID == prevScenarioNextMaps[j]; } ) )
Please pass only `prevScenarioNextMaps[j]` as a separate variable. We don't need to expose everything to this lambda function.

2021-01-30 16:52 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +                 || std::any_of( completedScenarioNextMaps.begin(), completedScenarioNextMaps.end(), [&]( const int scenarioID ) { return scenarioID == i; } ) )
Please pass only `i` into capture list. We don't need to expose everything to this lambda function.

2021-01-30 16:52 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +            else if ( std::any_of( clearedMaps.begin(), clearedMaps.end(), [&]( const int scenarioID ) { return scenarioID == i; } ) )
Please pass only `i` into capture list. We don't need to expose everything to this lambda function.

2021-01-30 16:52 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +            Campaign::ScenarioData( 3, std::vector<int>{4}, getCampaignBonusData( 0, 3 ), std::string( "CAMPG04.H2C" ), rolandCampaignDescription[0] ) );
Please remove `Campaign::ScenarioData(` portion as `emplace_back` constructs in-place.

2021-01-30 16:52 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +            Campaign::ScenarioData( 2, std::vector<int>{}, getCampaignBonusData( 1, 2 ), std::string( "CAMPE03.H2C" ), archibaldCampaignDescription[0] ) );
Please remove `Campaign::ScenarioData(` portion as `emplace_back` constructs in-place.

2021-01-30 16:52 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +            selectableScenarioButtons.button( i ).press();
Do we need to proceed further is this condition is true?

2021-01-30 17:17 UTC, eos428 commented on src/fheroes2/campaign/campaign_data.cpp
> +                startingScenarios.emplace_back( _scenarios[i].getScenarioID() );
It depends honestly, I just thought of making it more flexible, at the risk of designers getting too expansive with their ideas. So I'd like your opinion on this.

If we want simply 1 starting scenario per campaign, we might as well just starting _scenarios[0]

2021-01-30 17:28 UTC, eos428 commented on src/fheroes2/campaign/campaign_data.cpp
> +                    scenarioIDs.emplace_back( nextMaps[i] );
I think multiple maps shouldn't have the same scenario ID, but nonetheless you are right about breaking it.

2021-01-30 23:31 UTC, dreamer commented on src/fheroes2/campaign/campaign_data.cpp
> +                break;
Suggestion: it seems like `count` is unused and `i` is unnecessary - consider using for-each loop:
```C++
for ( const auto & scenario : _scenarios ) {

    if ( scenario.getScenarioID() >= scenarioID )
        break;
    
    // and keep using scenario instead of _scenarios[i]
```

2021-01-30 23:36 UTC, dreamer commented on src/fheroes2/campaign/campaign_data.h
> +#endif
Keep newline after `#endif`, otherwise various editors will keep adding it automatically and it will affect other people's PRs.

2021-01-30 23:46 UTC, dreamer commented on src/fheroes2/game/game_campaign.cpp
> +    void DrawCampaignScenarioIcon( const int icnId, const int iconIdx, const fheroes2::Point & offset, const int posX, const int posY )
Nice :)

2021-01-30 23:47 UTC, dreamer commented on src/fheroes2/game/game_campaign.cpp
> +        for ( int i = 0, scenarioCount = scenarios.size(); i < scenarioCount; ++i ) {
It seems like for-each loops can be used here as well :)

2021-01-30 23:54 UTC, dreamer commented on src/fheroes2/game/game_campaign.cpp
> +                 || std::any_of( completedScenarioNextMaps.begin(), completedScenarioNextMaps.end(), [&]( const int scenarioID ) { return scenarioID == i; } ) )
This lambda expression is repeated several times below… maybe

```C++
auto isCurrentScenario = []( int scenarioID ) { return scenarioID == i; };

// and then
std::any_of( completedScenarioNextMaps.begin(), completedScenarioNextMaps.end(), isCurrentScenario );
```

2021-01-31 01:27 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +                 || std::any_of( completedScenarioNextMaps.begin(), completedScenarioNextMaps.end(), [&]( const int scenarioID ) { return scenarioID == i; } ) )
For small comparisons like this using an extra lambda function is extenaive. Also instead of std::any_of please use std::find which doea exactly the same.

2021-01-31 01:28 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +            else if ( std::any_of( clearedMaps.begin(), clearedMaps.end(), [&]( const int scenarioID ) { return scenarioID == i; } ) )
Please consider changing to std:: find.

2021-01-31 01:31 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +                break;
A normal loop works totally fine: for ( size_t i = 0; i < scenarios.size(); ++i ) {

In proposed ranged loop we are using a reference which is bigger than int size for 64-bit applications. The normal loop will be optimized by compiler in a better way.

2021-01-31 01:33 UTC, ihhub commented
Hi @eos428 please also fix merging conflict.

2021-01-31 01:56 UTC, eos428 commented on src/fheroes2/game/game_campaign.cpp
> +            selectableScenarioButtons.button( i ).press();
I assume we'd still need to draw the buttons either way, I'm not too familiar with button groups but I think pressing the button for the currently selected scenario is needed

2021-01-31 03:36 UTC, ihhub requested changes
Hi @eos428 , I left few more comments. Would you mind to check them?

2021-01-31 03:36 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +                if ( nextMaps[i] == scenarioID ) {
Here we should use mapID istead of i.

2021-01-31 03:36 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +
Please remove this empty line at the top of the file.

2021-01-31 03:36 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.cpp
> +        const auto iterator = std::find_if( files.begin(), files.end(), [&]( const std::string & filePath ) { return isCampaignMap( filePath, fileName ); } );
Please pass only needed variables to lambda function capture list.

2021-01-31 03:36 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +        // TODO: find icon Idx for done (yellow ring border)
Is this comment still valid?

2021-01-31 03:36 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +        const int middleY = 40, deltaY = 42;
Please initialize each variable at a separate line.

2021-01-31 03:36 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +            const std::vector<int> nextMaps = scenarios[i].getNextMaps();
Here we make a copy of the container. We should use const reference instead.

2021-01-31 03:36 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +    else {
We don't need else condition else since the above if-block has return code.

2021-01-31 03:36 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +        for ( uint32_t i = 0; i < bonuses.size(); ++i ) {
i should be size_t type.

2021-01-31 10:58 UTC, dreamer commented on src/fheroes2/campaign/campaign_data.cpp
> +                break;
Reference being a pointer is the same size as size_t on 64-bit architectures.

2021-01-31 13:27 UTC, eos428 commented on src/fheroes2/game/game_campaign.cpp
> +        // TODO: find icon Idx for done (yellow ring border)
Not anymore, but on another note, we could look into reviewing usage of `isGoodCampaign` boolean in the future because expansion campaigns use different icons.

2021-02-01 10:52 UTC, ihhub requested changes
Hi @eos428 , I left multiple comments here. Could you please take a look?

2021-02-01 10:52 UTC, ihhub commented on fheroes2.vcxproj
> +	<ClCompile Include="src\fheroes2\campaign\campaign_scenariodata.cpp" />
Please fix intendation of this line.

2021-02-01 10:52 UTC, ihhub commented on fheroes2.vcxproj
> +	<ClInclude Include="src\fheroes2\campaign\campaign_scenariodata.h" />
Please fix intendation of this line.

2021-02-01 10:52 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +            if ( isStartingScenario( _scenarios[i].getScenarioID() ) )
Please cache `_scenarios[i].getScenarioID()` call.

2021-02-01 10:52 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +        return scenarioID == _scenarios.back().getScenarioID();
Please add an assertion to check that `_scenarios` is not empty.

2021-02-01 10:52 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +        CampaignData();
Please put the constructor at the top of `public` section.

2021-02-01 10:52 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.cpp
> +#include "assert.h"
Please change it to `<cassert>`.

2021-02-01 10:52 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.cpp
> +        const std::string mapFolder = "maps";
Please use normal constructor call `const std::string mapFolder( "maps" );`

2021-02-01 10:52 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.cpp
> +        const std::string mapFolder = "maps";
Actually just remove this variable and use "maps" in **GetListFiles** call.

2021-02-01 10:52 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.cpp
> +    ScenarioData::ScenarioData( int scenarioID, std::vector<int> nextMaps, std::vector<ScenarioBonusData> bonuses, const std::string & fileName,
We shouldn't pass complex objects by value. Please change to const reference for `std::vector<ScenarioBonusData> bonuses`.

2021-02-01 10:52 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.cpp
> +    ScenarioData::ScenarioData( int scenarioID, std::vector<int> nextMaps, std::vector<ScenarioBonusData> bonuses, const std::string & fileName,
The same applies for `std::vector<int> nextMaps`.

2021-02-01 10:52 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +            bonus.emplace_back( Campaign::ScenarioBonusData::RESOURCES, Resource::GOLD, 2000 );
Shouldn't we change bonuses for subsequent maps?

2021-02-01 10:52 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +        const auto mapInfo = scenario.loadMap();
Please avoid `auto` usage: use original Maps::FileInfo type.

2021-02-01 10:52 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +        Campaign::CampaignData campaignData = Campaign::CampaignData();
Why can't we use `Campaign::CampaignData campaignData;`?

2021-02-01 10:52 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +        Campaign::CampaignData campaignData = Campaign::CampaignData();
Why can't we use `Campaign::CampaignData campaignData;`?

2021-02-01 10:52 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +    const std::vector<int> selectableScenarios
Please use const reference here.

2021-02-01 11:46 UTC, eos428 commented on src/fheroes2/game/game_campaign.cpp
> +            bonus.emplace_back( Campaign::ScenarioBonusData::RESOURCES, Resource::GOLD, 2000 );
Yes, but a good proportion of them (change starting faction) have logics that are not implemented yet so these are meant to be placeholders. See #2668 for more details.

2021-02-01 13:43 UTC, ihhub requested changes
Hi @eos428 , good job! There're few comments left by me. Please check them.

2021-02-01 13:43 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.h
> +        ScenarioData( int scenarioID, const std::vector<int> & nextMaps, const std::vector<Campaign::ScenarioBonusData> & bonuses, const std::string & fileName,
This class doesn't have a default constructor. If it's not expected then please add `ScenarioData() = delete;` or define it's implementation.

2021-02-01 13:43 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.h
> +        const Maps::FileInfo loadMap() const;
Please remove first `const` here as we're returning a value.

2021-02-01 13:43 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.h
> +#include "serialize.h"
Instead of including this header please try this:
- add a forward declaration of `class StreamBase`
- include this header in source file.

2021-02-01 13:43 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.h
> +#include "gamedefs.h"
Do we need this file to be inluded?

2021-02-01 13:43 UTC, ihhub commented on src/fheroes2/game/game.h
> +        SELECTCAMPAIGNSCENARIO,
Even having the rest of enties with no separation please consider name new entries with _ symbol like `SELECT_CAMPAIGN_SCENARIO` and `COMPLETE_CAMPAIGN_SCENARIO` as it really improves readability of the code.

2021-02-01 13:43 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +        const std::vector<Campaign::ScenarioData> scenarios = campaignData.getAllScenarios();
Please use const reference to do not make an extra copy of the container.

2021-02-01 13:43 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +                DrawCampaignScenarioIcon( iconsId, Campaign::SCENARIOICON_UNAVAILABLE, trackOffset, x, y );
Could you please include `{}` for each if-section to make the code little better to read? :)

2021-02-01 13:43 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +        scenarioDatas.emplace_back( 0, std::vector<int>{1}, getCampaignBonusData( 0, 0 ), std::string( "CAMPG01.H2C" ), rolandCampaignDescription[0] );
Here we could do the trick:
```
scenarioDatas.reserve(4);
```
so the below code won't resize the vector :)

2021-02-01 13:43 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +        scenarioDatas.emplace_back( 0, std::vector<int>{1}, getCampaignBonusData( 0, 0 ), std::string( "CAMPG01.H2C" ), rolandCampaignDescription[0] );
It's not critical. I'm leaving the decision for you.

2021-02-01 13:43 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +#include "dialog.h"
Please remove this file inclusion. It was removed recently.

2021-02-01 13:43 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +    const Campaign::CampaignData GetCampaignData( int campaignID )
Please remove `const` from returned value.

2021-02-01 13:43 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +    const Campaign::CampaignData GetArchibaldCampaignData()
Please remove `const` from returned value.

2021-02-01 13:43 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +    const Campaign::CampaignData GetRolandCampaignData()
Please remove `const` from returned value.

2021-02-01 13:43 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +        bonus.emplace_back( Campaign::ScenarioBonusData::ARTIFACT, Artifact::THUNDER_MACE, 1 );
It should be Mage's Ring.

2021-02-01 14:09 UTC, eos428 commented on src/fheroes2/campaign/campaign_scenariodata.h
> +#include "serialize.h"
I think overall only `maps_fileinfo.h` is necessary for inclusion, should I still do the StreamBase declaration?

2021-02-07 15:14 UTC, ihhub requested changes
Hi @eos428 , everything looks good. I left just few comments. Please take a look at them and also please rebase again from master as we made even more code restructure changes.

2021-02-07 15:14 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +        return _scenarios[scenarioID].getNextMaps();
It'd good to check `scenarioID` for validity.

2021-02-07 15:14 UTC, ihhub commented on src/fheroes2/campaign/campaign_savedata.cpp
> +        _finishedMaps.emplace_back( _currentScenarioID );
It'd be wise to check if `_finishedMaps.empty() || _finishedMaps`.back() != _currentScenarioID` to avoid duplicated calls. Also we could add an assertion to check that there're no duplicates.

2021-02-07 15:14 UTC, ihhub commented on src/fheroes2/campaign/campaign_savedata.h
> +#include "serialize.h"
Can we make direct declaration of `StreamBase` and include this header in cpp file?

2021-02-08 07:57 UTC, eos428 commented on src/fheroes2/campaign/campaign_data.cpp
> +                if ( nextMaps[mapID] == scenarioID ) {
this is a 2-dimensional loop, so even if we break after the emplace back, it should still look for the next scenarios that happen to be before the scenarioID passed as param.

I would say the mistake is to emplace_back `nextMaps[mapID]` (which would be the scenarioID passed as param) instead of `_scenarios[i].getScenarioID()`

2021-02-08 11:14 UTC, eos428 commented on src/fheroes2/campaign/campaign_savedata.h
> +#include "serialize.h"
I might have misunderstood the request so feel free to correct me if I'm wrong on this one

2021-02-09 13:02 UTC, ihhub commented
Hi @eos428 , first of all we shouldn't show winning video of a single player game after completing the campaign scenario. Next is that we need to redraw black background for next scenario:
![image](https://user-images.githubusercontent.com/19829520/107367289-17599280-6b1a-11eb-8084-e7796662476a.png)

2021-02-09 13:47 UTC, ihhub approved these changes

2021-02-09 13:56 UTC, merged

2021-02-09 13:57 UTC, ihhub commented
@eos428 , thanks a lot for your enormous contribution to the project!