Fix tools
ihhub/fheroes2 pull request #2669
Opened 2021-01-25 13:28 UTC by kant2002

- Change haders in the tools
- Create fheroe2/agg/decode.cpp which has logic for ICN decoding. It is separate file, to not take all sound related functions in the tools which make it complicated to build.
- Add VC projects for building of each tool

2021-01-25 15:45 UTC, ihhub requested changes
Hi @kant2002, good job. I left multiple comments here. Could you please take a look?

2021-01-25 15:45 UTC, ihhub commented on 82m2wav.vcxproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
Please move all vcproj files into `src/tools` directory as they aren't a part of the main project to do not mess with the main project file.

2021-01-25 15:45 UTC, ihhub commented on 82m2wav.vcxproj
> +<Project DefaultTargets="Build" ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
Could you please change ToolsVersion (manually) to 14.0? In this way we can add compilation on AppVeyor.

2021-01-25 15:45 UTC, ihhub commented on src/fheroes2/agg/decode.cpp
> +        void DecodeICNSprite( Sprite & sprite, const ICNHeader & header, const uint8_t * data, uint32_t sizeData )
Please move this function into `image_tool.cpp` as it's more approprite place for it. Also please rename it `decodeICNSprite` according to our coding standards (old code has different). On top of this we should avoid double definition of the same structure. Please pass `const uint8_t * data, const uint32_t sizeData, const int32_t width, const int32_t height, const int32_t offsetX, const int32_t offsetY` so the full signature of the function will be:
```
Sprite decodeICNSprite( const uint8_t * data, const uint32_t sizeData, const int32_t width, const int32_t height, const int32_t offsetX, const int32_t offsetY );
```

It is totally valid to return the object by value since we declared move constructors. Then later in the agg.cpp we can do like this:
```
const uint8_t * data = body.data() + headerSize + header1.offsetData;
_icnVsSprite[id][i] = decodeICNSprite( data, sizeData, header1.width, header1.height, static_cast<int16_t>( header1.offsetX ), static_cast<int16_t>( header1.offsetY ) );
```

2021-01-25 15:45 UTC, ihhub commented on src/fheroes2/agg/decode.cpp
> +            sprite.resize( header.width, header.height );
Here we can do:
```
Sprite output( width, height );
```

2021-01-25 15:45 UTC, ihhub commented on src/fheroes2/agg/agg.cpp
> +StreamBase & operator>>( StreamBase & st, fheroes2::AGG::ICNHeader & icn );
Please move `ICNHeader` structure to **agg_file**.

2021-01-25 15:58 UTC, kant2002 commented on 82m2wav.vcxproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
That's why I ask for static library. I have to include all files with `engine` folder to not deal with inter-dependencies and anyway include most (if not all) of files. Will move.

2021-01-25 16:26 UTC, kant2002 commented on 82m2wav.vcxproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
@ihhub Actually I cannot do that. If you look closer, you will find that I import properties from common files, which has path relative to project root, and if I move projects to tools folder, I either have to drop inclusion of properties and shared sets of data, or I have to do quite a bit of refactoring on the tooling. Can this suggestion would be done in the followup PR?

2021-01-26 00:23 UTC, ihhub commented on 82m2wav.vcxproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
Oh, that's bad. Let me think a bit about it.

2021-01-27 07:52 UTC, kant2002 commented on 82m2wav.vcxproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
@ihhub I rebase PR based on https://github.com/ihhub/fheroes2/pull/2675 and I move project files to `src\tools` folder, still has to play with shared files, but that's much more manageable.

2021-01-27 10:19 UTC, ihhub commented on 82m2wav.vcxproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
Great job, @kant2002 ! I'll check this pull request once I reach home :)

2021-01-27 12:35 UTC, ihhub reviewed
Hi @kant2002 , everything looks good except one function which should be moved to agg_file to have a better code structure. Could you please take a look?

2021-01-27 12:35 UTC, ihhub commented on src/engine/image_tool.cpp
> +StreamBase & operator>>( StreamBase & st, fheroes2::ICNHeader & icn )
This function as well as it's definition should go to agg_file instead. Could you please move it there?

2021-01-27 12:35 UTC, ihhub commented on src/tools/icn2img.cpp
> +StreamBase & operator>>( StreamBase & st, fheroes2::ICNHeader & icn );
We should remove this operator from here and from agg.cpp file and define it inside agg_file.h instead.

2021-01-30 07:12 UTC, kant2002 commented on src/tools/82m2wav.vcxproj
> +    <ClCompile Include="..\engine\agg_file.cpp" />
I leave this one as is for now, since all engine files still has a lot of dependencies on each other. you cannot remove SDL for this projects. I plan to tackle that in subsequent PR. This is big enough to really validate. 
`serialize -> tools -> localevent -> audio_mixer` so I cannot simplify tools right now.

2021-01-30 07:12 UTC, kant2002 commented on src/tools/82m2wav.vcxproj
> +    <ClCompile Include="..\engine\agg_file.cpp" />
I leave this one as is for now, since all engine files still has a lot of dependencies on each other. you cannot remove SDL for this projects. I plan to tackle that in subsequent PR. This is big enough to really validate. 
`serialize -> tools -> localevent -> audio_mixer` so I cannot simplify tools right now.

2021-01-30 07:13 UTC, kant2002 commented on src/tools/bin2txt.vcxproj
> +    <ClCompile Include="..\engine\agg_file.cpp" />
That's the only one project which I can simplify and remove SDL dependencies.

2021-01-30 07:13 UTC, kant2002 commented on src/tools/extractor.vcxproj
> +    <ClCompile Include="..\engine\agg_file.cpp" />
Included header files.

2021-01-30 16:58 UTC, merged

2021-01-30 16:59 UTC, ihhub commented
@kant2002 thank you so much for adding this ability back!