Spell book
ihhub/fheroes2 pull request #2674
Opened 2021-01-25 22:16 UTC by vincent-grosbois

This contains a small refactor of spellbook (1st commit) and the fix for issue #51

2021-01-30 16:13 UTC, ihhub requested changes
Hi @vincent-grosbois , I left multiple comment here. Could you please take a look?

2021-01-30 16:13 UTC, ihhub commented on src/fheroes2/spell/spell_book.cpp
> +    Spell curspell = Spell::NONE;
Could you please explain why we changed from a parametrized constructor to assignment constructor here?

2021-01-30 16:13 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +            std::function<void( const std::string & )> statusCallback = [this]( const std::string & status ) {
Let's pass only `&bar` of the current class. We don't need the whole class to be exposed. Nothing wrong in the current implementation, just to follow incapsulation principle :)

2021-01-30 16:13 UTC, ihhub commented on src/fheroes2/spell/spell_book.cpp
> +        return std::string( spell1.GetName() ) < std::string( spell2.GetName() );
Please compare it using `strcmp` without **std::string** usage.

2021-01-31 14:31 UTC, vincent-grosbois commented on src/fheroes2/spell/spell_book.cpp
> +    Spell curspell = Spell::NONE;
I don't think it's assignment constructor in that case, it should call the same constructor.
I thought this is more readable

2021-02-07 15:37 UTC, ihhub requested changes
Hi @vincent-grosbois , I left few comments only. Could you please take a look?

2021-02-07 15:37 UTC, ihhub commented on src/fheroes2/resource/artifact.h
> +class StatusBar;
Please forward declaration of this class at the top of the file.

2021-02-07 15:37 UTC, ihhub commented on src/fheroes2/heroes/heroes_base.h
> +    Spell OpenSpellBook( SpellBook::Filter filter, bool canSelect, std::function<void( const std::string & )> * statusCallback = nullptr ) const;
Please remove default parameter and just explicitly set it in one call.

2021-02-07 22:43 UTC, vincent-grosbois commented on src/fheroes2/resource/artifact.cpp
> +            std::function<void( const std::string & )> statusCallback = [statusBar]( const std::string & status ) {
> 
> 
> We can't we pass `[&_statusBar]` without extra variable?

no, this is a C++17 feature apparently
C++11 it's either this or the initial version, ie using this in the closure

2021-02-07 22:51 UTC, vincent-grosbois commented
@ihhub  done!

2021-02-08 15:56 UTC, merged

2021-02-08 15:56 UTC, ihhub commented
@vincent-grosbois , thank you so much for adding this feature!