Battle screen, area-based spells vs Anti-Magic
ihhub/fheroes2 pull request #2680
Opened 2021-01-27 19:50 UTC by shprotru

Fix for #2677

2021-01-28 12:20 UTC, ihhub requested changes

2021-01-28 12:20 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +                    isApplicable = !( highlightedUnit->GetMagicResist( humanturn_spell, spellPower ) < 100 && highlightedUnit->Modes( SP_ANTIMAGIC )
This is not exactly a correct way to fix the problem. We need to move the check for Anti Magic mode in `GetMagicResist` method and remove the check in `Battle::Unit::AllowApplySpell` method since it internally calls `GetMagicResist`. Also here we need to call `isMagicResist` instead to simplify reading.

2021-01-30 16:35 UTC, ihhub requested changes

2021-01-30 16:35 UTC, ihhub commented on src/fheroes2/battle/battle_troop.cpp
> +    if ( Modes( SP_ANTIMAGIC ) )
Please remove
```
    if ( Modes( SP_ANTIMAGIC ) )
        return false;
```
from `bool Battle::Unit::AllowApplySpell`.

2021-01-30 17:10 UTC, shprotru commented on src/fheroes2/battle/battle_interface.cpp
> +                    isApplicable = !( highlightedUnit->GetMagicResist( humanturn_spell, spellPower ) < 100 && highlightedUnit->Modes( SP_ANTIMAGIC )
done

2021-01-30 17:12 UTC, shprotru commented on src/fheroes2/battle/battle_troop.cpp
> +    if ( Modes( SP_ANTIMAGIC ) )
done

2021-01-31 04:31 UTC, merged

2021-01-31 04:31 UTC, ihhub commented
@shprotru , great thanks for fixing this issue!