verbose damage description in log
ihhub/fheroes2 pull request #2730
Opened 2021-02-03 17:34 UTC by tau3

Hi! 

This is a fix for #2006 

But I'm unsure if it works well with current localisation mechanism (that apparently uses a string hash to find a translation?)

2021-02-06 01:45 UTC, ihhub requested changes
Hi @tau3 , I left multiple comments. Could you please take a look?

2021-02-06 01:45 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    std::stringstream msg;
Please, do **not** use sstream. string has all abilities needed.

2021-02-06 01:45 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
In the description of the issue the requirement is to show a common damage for every creature. Here we're showing the damage individually. How will it look with 14 undead/life creatures? Could you please check this in the issue?

2021-02-06 01:45 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( damages.size() != 1 ) {
Please make it more explicit: size() > 1 and assert that this array in not empty at the beginning of the function.

2021-02-06 01:45 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +std::string MakeDamageMessage( const Spell & spell, const std::set<uint32_t> & damages )
Please put this and the function above to anonymous namespace at the top of this file.

2021-02-11 20:04 UTC, tau3 commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
Hi @ihhub!

Thanks for review. I probably unterstood the description differently. Should damages be groupped? Like `the spell does 30 damage to 3 creatures, 40 damage to 2 creatures, etc.`?

2021-02-12 06:36 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
Let's ask our QA team:
@Branikolog and @LeHerosInconnu, what do you think?

2021-02-12 12:01 UTC, Branikolog commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
Well, I suppose @LeHerosInconnu suggested to show the actual individual Damage-x-number of creatures affected. 
As for me, I personally prefer current implementation, as in this way we know the overall damage applied to all creatures (which is useful info, if player struggles between mass cast and single target spell). In future we'd 100% sure add spell damage to the description in spell book. So player would know the individual damage per creature while reading info in spell book. But after a cast he would also get the additional info on the overall damage he managed to deal....
Cannot say, the suggestion is bad. It looks quite good but less informative I expect.
We can also try to show both these implementations... But I'm not sure it will look good... Like: "Spell does 30 to x living creatures (150 total)"

2021-02-12 19:15 UTC, LeHerosInconnu commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
For me, the total damage has no interest and this misleads the player.

The goal is to inform the player about the distribution of damage according to the number of groups present and especially according to the hero's Spell Power.

If, for example, the spell did 75 damage to two opposing troops out of a total of four, say one troop with a total of 60 hp and another troop with a total of 70 hp (so even if the troops had a total hp less than the damage caused by the spell), I prefer to know that the spell did four times 75 damage rather than a total of 300 damage.
It is much more informative to understand what happened.

Also, it is not necessary to specify the damage for each group, this would be more complicated to understand.

It is simply enough to indicate the damage of the spell according to the hero's Spell Power and the number of troops impacted by the spell (even if the damage is higher than the total hp of the troop).

Example:
The Death Wave spell does 10 damage per Spell Power.
The hero has 7 Spell Power.
There are four troops that were affected by the spell (some troops had less than 70 hp, others more than 70 hp).
Display:
"The Death Wave spell does 70 damage to 4 troops of living creatures."

Example:
The Death Ripple spell does 5 damage by Spell Power.
The hero has 13 Spell Power.
There are 8 troops that were affected by the spell (some troops had less than 65 hp, others more than 65 hp, some allied troops were also affected).
Display:
"The Death Ripple spell does 65 damage to 8 troops of living creatures."

Compare this with a mass spell like Armageddon.

Example:
The Armageddon spell does 50 damage by Spell Power.
The hero has 10 Spell Power.
There are 10 troops that were affected by the spell.

What is indicated is the damage caused according to the hero's Spell Power:
"The Armageddon spell does 500 damage."

 And not the damage caused to all the troops:
"The Armageddon spell does 5000 damage."

It has to be consistent in the way the damage is indicated.
And that's the way it works in the original game. :)

2021-02-13 06:12 UTC, Branikolog commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
@LeHerosInconnu, let me disagree a bit.) 
A player will always know, how much damage mass spell will deal, as we're anyway going to show the damage in spell book info. So the same amount of damage will be shown in log, it's obvious
On the other hand, when a player has cast the spell and watched the total amount of damage in log, he can find out, that the spell could be less effective, comparing to single cast spell (ex. lightning) regarding total damage. 
So information about the total damage can be useful and information about damage taken by each troop is obvious and could be checked in spell info window, while choosing the spell.

2021-02-13 17:45 UTC, LeHerosInconnu commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
@Branikolog.

I think that, as you suggested before, the best solution would be to specify the total damage at the same time:

"The Death Ripple spell does 30 damage to 5 troops of living creatures (total: 150)."

Or:

"The Death Ripple spell does 30 damage to 5 troops of living creatures for a total of 150 damage."

2021-02-13 20:01 UTC, Branikolog commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
I think for now we should first make the original mechanics, which were described by @LeHerosInconnu above, then. 
But I wish @tau3 would be able to improve the description in a log to display both total and individual damage for such kind of spells, in future, after we discuss it in separate issue.
@LeHerosInconnu, could you, please, specify if description of a type of creatures affected (for Holy and Death spells) are required in log (I mean living/non-living).  Also, regarding other mass pells. I've noticed, that Armageddons spell example didn't have the quantity of creatures affected, as well as their type. Do we need here some special kind of description, like "The Armageddon spell does 500 damage to X creatures on a battlefield" or "--/-- for each of X creatures affected by the spell" ?

2021-02-13 21:18 UTC, LeHerosInconnu commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
@Branikolog.

> @LeHerosInconnu, could you, please, specify if description of a type of creatures affected (for Holy and Death spells) are required in log (I mean living/non-living).

For a player who already knows the game, precision would not be necessary, but it is also important to think about players who are completely unfamiliar with the game.
Holy and Death spells are mass spells but are special because they do not affect all the creatures present, only one type of creature.
I think it's better to specify it in this case.

> Also, regarding other mass pells. I've noticed, that Armageddons spell example didn't have the quantity of creatures affected, as well as their type. Do we need here some special kind of description, like "The Armageddon spell does 500 damage to X creatures on a battlefield" or "--/-- for each of X creatures affected by the spell" ?

In the case of mass spells that affect all creatures, such as the Armageddon spell, I think it is not necessary to specify the type of creatures or the number of groups impacted.
All creatures are affected and all groups are hit (except when the creatures are immune or protected).
But perhaps it would be nice to add a sentence when, for example, a Dwarf troop (or several troops) resisted a mass spell, or when the troops (allies or enemies) only received half of the damage due to an artifact, etc.

2021-02-14 04:07 UTC, Branikolog commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
@LeHerosInconnu
> I think it's better to specify it in this case.
Could you, please, precise what exactly should be written in a log for each current case(spell)?
> All creatures are affected and all groups are hit (except when the creatures are immune or protected).
I think it would be a nice enhancement. Could you, please, create a discussion and issue later for mass spells' log description, so we can forge nice and user-friendly solution?

2021-02-14 08:48 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
@LeHerosInconnu and @Branikolog , we could and we will create a dicussion about the best possible way of displaying but for now I think what we can do is to display this message:
```
The Death Ripple spell does 30 damage to 5 troops of living creatures for a total of 150 damage.
```
or this one (please note `up to`):
```
The Death Ripple spell does up to 30 damage to 5 troops of living creatures for a total of 150 damage.
```

Please choose any of two solutions and we could proceed with this pull request.

2021-02-14 09:58 UTC, Branikolog commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
Well, if it is possible to show both damage implementations together....

> The Death Ripple spell does 30 damage to 5 troops of living creatures for a total of 150 damage.

I vote for shorter one.

What about other mass attacking spells like Armageddon or Storm?

2021-02-14 10:07 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
Let's do the base first and then we can create another pull request for this. I prefer to have step by step implementation rather than everything in one shot.

2021-02-14 21:11 UTC, LeHerosInconnu commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
I choose the sentence with "up to", adjusted with the word "maximum" instead of "total" (I think it's necessary with "up to"):

"The Death Ripple spell does up to 30 damage to 5 troops of living creatures for a maximum of 150 damage."

The sentence will be written on two lines anyway. :)

2021-02-15 04:33 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
I actually prefer with up to as well. @tau3, could you please make these changes? Please let me know if something is unclear for you.

2021-02-16 10:12 UTC, LeHerosInconnu commented
@Branikolog.

> @LeHerosInconnu
> 
> > I think it's better to specify it in this case.
> 
> Could you, please, precise what exactly should be written in a log for each current case(spell)?
> 
> > All creatures are affected and all groups are hit (except when the creatures are immune or protected).
> 
> I think it would be a nice enhancement. Could you, please, create a discussion and issue later for mass spells' log description, so we can forge nice and user-friendly solution?

Okay, I'll create a discussion later.

2021-02-16 15:55 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
![image](https://user-images.githubusercontent.com/19829520/108087380-59527d80-70b2-11eb-9d91-36d09e1bb71e.png)
I don't think that 2 row string looks nice. Check that status message shows only the last part.

2021-02-16 16:16 UTC, LeHerosInconnu commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
And this way:

"Death Ripple does up to 30 damage to 5 living troops (max: 150)."

2021-02-16 16:19 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
I think we have to keep the word spell for here.

2021-02-16 16:26 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
>      if ( spell.isDamage() ) {
This is the whole implementation based on latest discussion:
```
void Battle::Interface::RedrawActionSpellCastPart2( const Spell & spell, TargetsInfo & targets )
{
    if ( spell.isDamage() ) {
        uint32_t killed = 0;
        uint32_t totalDamage = 0;
        uint32_t maximumDamage = 0;
        uint32_t damagedMonsters = 0;

        for ( TargetsInfo::const_iterator it = targets.begin(); it != targets.end(); ++it ) {
            if ( !it->defender->isModes( CAP_MIRRORIMAGE ) ) {
                killed += ( *it ).killed;

                ++damagedMonsters;
                totalDamage += it->damage;
                if ( maximumDamage < it->damage )
                    maximumDamage = it->damage;
            }
        }

        // targets damage animation
        RedrawActionWincesKills( targets );

        if ( totalDamage > 0 ) {
            assert( damagedMonsters > 0 );
            std::string msg;
            if ( spell.isUndeadOnly() ) {
                if ( damagedMonsters == 1 ) {
                    msg = _( "The %{spell} spell does %{damage} damage to one undead creature." );
                    StringReplace( msg, "%{damage}", totalDamage );
                }
                else {
                    msg = _( "The %{spell} spell does up to %{damage} damage to %{count} undead creatures" );
                    StringReplace( msg, "%{spell}", spell.GetName() );
                    StringReplace( msg, "%{damage}", maximumDamage );
                    StringReplace( msg, "%{count}", damagedMonsters );
                    status.SetMessage( msg, true );

                    msg = _( "for a total of %{totalDamage} damage." );
                    StringReplace( msg, "%{totalDamage}", totalDamage );
                }
            }
            else if ( spell.isALiveOnly() ) {
                if ( damagedMonsters == 1 ) {
                    msg = _( "The %{spell} spell does %{damage} damage to one living creature." );
                    StringReplace( msg, "%{damage}", totalDamage );
                }
                else {
                    msg = _( "The %{spell} spell does up to %{damage} damage to %{count} living creatures" );
                    StringReplace( msg, "%{spell}", spell.GetName() );
                    StringReplace( msg, "%{damage}", maximumDamage );
                    StringReplace( msg, "%{count}", damagedMonsters );
                    status.SetMessage( msg, true );

                    msg = _( "for a total of %{totalDamage} damage." );
                    StringReplace( msg, "%{totalDamage}", totalDamage );
                }
            }
            else {
                msg = _( "The %{spell} does %{damage} damage." );
                StringReplace( msg, "%{damage}", totalDamage );
            }

            StringReplace( msg, "%{spell}", spell.GetName() );

            if ( killed ) {
                status.SetMessage( msg, true );
                msg = _n( "1 creature perishes.", "%{count} creatures perish.", killed );
                StringReplace( msg, "%{count}", killed );
            }

            status.SetMessage( msg, true );
        }
    }

    status.SetMessage( " ", false );
    _movingUnit = NULL;
}
```

2021-02-16 20:47 UTC, Branikolog commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
Word "max" looks confusing... Players... (especially me-like, whos English is quite bad :D ) can decide, that some creature took 150 damage...
"Total" seems more clear for me...

2021-02-17 01:24 UTC, LeHerosInconnu commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
@Branikolog.

> Word "max" looks confusing... Players... (especially me-like, whos English is quite bad :D ) can decide, that some creature took 150 damage...
> "Total" seems more clear for me...

The expression "Max" (for maximum) is already used in fheroes2.

The expression "Total" makes people think that it is the total damage received, whereas this is not the case when, for example, one (or more troops) received less damage (they had less hp) than the damage caused by the spell.

@ihhub.

The expression "living troops" should be used instead of "living creatures".

The expression "troops" represents a group of creatures.
A troop can contain, 1 creature or 10 creatures or 100 creatures.

What is reported here is the number of troops that have been affected.

"The Death Ripple spell does up to 30 damage to 5 living troops."

2021-02-17 07:56 UTC, Branikolog commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
>What is reported here is the number of troops that have been affected.

Correct!

>The expression "Total" makes people think that it is the total damage received, whereas this is not the case when, for example, one (or more troops) received less damage (they had less hp) than the damage caused by the spell.

Here we have an expression, that troops not have RECEIVED damage, but the spell DOES DAMAGE to several groups of creatures... The damage can be much higher, than troop's HP. So total damage is a sum of potential damage dealt for all troops.

2021-02-18 02:08 UTC, LeHerosInconnu commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
@Branikolog.

> > The expression "Total" makes people think that it is the total damage received, whereas this is not the case when, for example, one (or more troops) received less damage (they had less hp) than the damage caused by the spell.
> 
> Here we have an expression, that troops not have RECEIVED damage, but the spell DOES DAMAGE to several groups of creatures... The damage can be much higher, than troop's HP. So total damage is a sum of potential damage dealt for all troops.

I think you almost got it. :D

The complete sentence should have been:

"The Wave of Death spell does up to 30 damage to 5 troops of living creatures up to a potential maximum of 150 damage."

The Wave of Death spell does 30 damage to 5 troops of living creatures.
Potential damage is a maximum of 150 damage (5 x 30).
Let's say 3 troops each had 30 damage, one troop had 25 damage, one troop had 10 damage.
The total damage received by the troops is (3 x 30) + 25 + 10 or 125 damage.

On a potential maximum of 150 damage, the troops received 125 damages.

As you have written, it is the sum of the potential damages (max: 150) that should be referred to in the sentence to be displayed, it is not the "total" (total: 125) of the received damages.
The spell has a power of 150 damage (max: 150); however, the creatures have received only 125 damage (total: 125).

So, from the sentence:
"The Wave of Death spell does up to 30 damage to 5 troops of living creatures up to a potential maximum of 150 damage."

I've shortened the end of the sentence to:
"...up to a maximum of 150 damage."
And then:
"...(maximum: 150 damage)."
And then:
"...(max: 150 damage)."
And then:
"...(max: 150)."

I could have shortened the end of the sentence to:
...up to a potential of 150 damage."
And then:
...(potential: 150 damage)
And then:
...(potential: 150)
But not:
...(pot: 150) :D

So, the expression (max: 150) is more appropriate and understandable (than (potential: 150) or (pot: 150)), and also shorter.
Anyway "total" would be misused here. :)

2021-02-18 08:28 UTC, Branikolog commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
You've missed only one thing: in a log it goes a description of the damage of a spell, but not the damage received by creatures. :) If we're talking about receiving damage by creatures all your statements are true. (It would look like "creatures received 30/30/30/25/10" and here we can type either "potential maximum of 150" or "total damage 125")
But we have a description, that spell DOES damage, no matter, how much damage each troop could obtain. So the total damage from the spell for all creatures should be 150.
So the idea is:
- if we speak about received damage, we can talk about either maximum potential damage(150) or sum of actual damage obtained by all troops(125).
- if we speak about the damage that a spell DOES to troops (which is a current case), we can talk about either sum of each spell damage applied to all troops(150) or the sum of damage obtained by all troops (125) . Even if each of 5 troops had 1 HP the overall damage, spell applied to them would be 150.

2021-02-18 22:14 UTC, LeHerosInconnu commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
@Branikolog.

> You've missed only one thing: in a log it goes a description of the damage of a spell, but not the damage received by creatures. :)

Yes, it's the description of the effects of the spell according to the Spell Power of the hero we're talking about.
The Death Wave spell does 10 damage per Spell Power.
The hero has 3 Spell Power.
There are five troops that were affected by the spell.
So up to 30 damage to five troops, so up to 150 damage.
Okay.

> If we're talking about receiving damage by creatures all your statements are true. (It would look like "creatures received 30/30/30/25/10" and here we can type either "potential maximum of 150" or "total damage 125")

Yes.

> But we have a description, that spell DOES damage, no matter, how much damage each troop could obtain. So the total damage from the spell for all creatures should be 150.

Yes.

> So the idea is:
> 
> * if we speak about received damage, we can talk about either maximum potential damage(150) or sum of actual damage obtained(received) by all troops(125).

Yes.

> * if we speak about the damage that a spell DOES to troops (which is a current case), we can talk about either sum of each spell damage applied to all troops(150) or the sum of damage obtained(received) by all troops (125) .

Yes.

> Even if each of 5 troops had 1 HP the overall damage, spell applied to them would be 150.

Yes.

And this is where the word "total" can be confusing.
Because for the reader the word "total" can correspond to the potential "total" damage of the spell or to the "total" damage received by all affected troops.

Let's write the sentence with the word "total" instead of the word "maximum", specifying completely what happened (without going into too much detail for each of the troops):

"The Wave of Death spell does up to 30 damage to 5 troops of living creatures up to a potential total of 150 damage, the 5 troops of living creatures received a total of 125 damage."

If the word "total" is used in a shortened version of the sentence, what total is it?
Is it the one referring to potential damage (150) or is it the one referring to damage received (125)?

2021-02-19 07:50 UTC, Branikolog commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
> Because for the reader the word "total" can correspond to the potential "total" damage of the spell or to the "total" damage received by all affected troops.

Here what I was talking about in previous sentence:
In the first part of description in a log it is written about "The SPELL, that DOES damage". (Not the damage RECEIVED by creatures) So it's quite simple to understand, that total damage is sum of damage of the spell to all troops, and not the potential or received damage by troops. 
We should better exclude "up to"
So, I suggest as simple and as short sentence as we can:
"The Death Ripple spell does 30 damage to 5 living troops (total: 150)."
Here we're talking about the spell. How much damage it deals to every living troop (no matter how much damage troop can handle, we're talking about the spell itself)
So the total damage is simple sum of spell's damage for all troops.
Also, with this sentence (I believe) we solve a problem with a two line log sentence. (I hope it can fit single line)

2021-02-19 18:08 UTC, LeHerosInconnu commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
@Branikolog.

> > Because for the reader the word "total" can correspond to the potential "total" damage of the spell or to the "total" damage received by all affected troops.
> 
> Here what I was talking about in previous sentence:
> In the first part of description in a log it is written about "The SPELL, that DOES damage". (Not the damage RECEIVED by creatures) So it's quite simple to understand, that total damage is sum of damage of the spell to all troops, and not the potential or received damage by troops.
> We should better exclude "up to"
> So, I suggest as simple and as short sentence as we can:
> "The Death Ripple spell does 30 damage to 5 living troops (total: 150)."
> Here we're talking about the spell. How much damage it deals to every living troop (no matter how much damage troop can handle, we're talking about the spell itself)
> So the total damage is simple sum of spell's damage for all troops.
> Also, with this sentence (I believe) we solve a problem with a two line log sentence. (I hope it can fit single line)

Without "up to", this sentence is acceptable because it is no longer ambiguous:
"The Death Ripple spell does 30 damage to 5 living troops (total: 150)."

Besides, it's almost the same as the one proposed 6 days ago: :)

> @Branikolog.
> 
> I think that, as you suggested before, the best solution would be to specify the total damage at the same time:
> 
> "The Death Ripple spell does 30 damage to 5 troops of living creatures (total: 150)."

So let's go for it:
"The Death Ripple spell does 30 damage to 5 living troops (total: 150)."

2021-02-21 09:32 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
Nope, no go as the sentence is too long:
![image](https://user-images.githubusercontent.com/19829520/108620976-af387400-746a-11eb-952b-668197dcb026.png)

We have to cut at least 5 characters.

2021-02-21 10:13 UTC, Branikolog commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
I propose to show log message in the following manner:
"Wilfrey casts Death Ripple.
The spell does 10 damage to 10 living creatures (total: 100)"
I mean show message in two lines simultaneously.
In the first line we anyway have a message, that Death Ripple spell was cast.
Here we should make the both lines of journal be visible for 3-5 seconds after cast. After time has passed we should show only the second line of spell-cast log:
"The spell does 10 damage to 10 living creatures (total: 100)
Hide logs"
So player after some time will anyway know the damage of spell he applied to battlefield. (All the most useful info is placed in the second line of the spell description)
Opening the full log will allow him to find the information, what type of spell was cast, if he accidentally forgot.

2021-02-22 04:34 UTC, LeHerosInconnu commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
Here is what is currently displayed for each damage spell and my proposal for each case.

I suggest removing the line that starts with "Player's color and spell name" (with a spelling error: "casts" without "s", and without a dot at the end of the line):
"Blue cast spell: Chain Lightning"

And to put the number of troops affected (when necessary) in the same line as the number of creatures affected:
"The Chain Lightning hits 4 troops, 11 creatures perish."

And to add details when a Dwarf troop resists a spell, and when the troops are protected from the spell.
In the examples, with Battle Dwarves resisting the spell, and troops that are protected with the "Broach of Shielding" artifact.
I don't know if it's necessary to add sentences for the immunity of Dragons and when a troop is protected with the "Anti-Magic" spell, etc.

Remove the word "spell" from the sentence:
"The Death Ripple spell does 40 damage to all living creatures."
(Currently, the word "spell" is only used for "Death Ripple", "Death Wave", "Holy Word" and "Holy Shout" spells.)
And replace the word "creatures" with the word "troops":
"The Death Ripple does 10 damage to all living troops." 

So, let's go.

Natasha (and Gem) has 2 Spell Power.

"Turn 1
Natasha casts Chain Lightning on the Unicorns.
The Chain Lightning does 80 damage (total: 150).
The Chain Lightning hits 4 troops, 11 creatures perish."

(Chain Lightning does 40 damage per Spell Power, then half of the damage up to four troops: ((40 x 2 = 80) + (80/2 = 40) + (40/2 = 20) + (20/2 = 10), so 80 + 40 + 20 + 10 = 150).)

![Spell damage sentence fh2 001](https://user-images.githubusercontent.com/43583994/108652457-8218af80-74c4-11eb-9788-ad7ca923e3de.png)

Turn 1
Hero name, spell name, creature name of the target troop (a target must be chosen to be able to cast the spell):
Natasha casts Chain Lightning on the Unicorns.
Spell name, number of the spell's base damage according to the hero's Spell Power, (four troops are hit, total potential base damage of the spell according to the hero's Spell Power):
The Chain Lightning does 80 damage (total: 150).
Number of troops affected by the spell, number of creatures decimated:
The Chain Lightning hits 4 troops, 11 creatures perish.

If no creature perishes:

The Chain Lightning hits 4 troops, 0 creatures perish.

"Turn 2
Natasha casts Lightning Bolt on the Unicorns.
The Lightning Bolt does 50 damage.
The Lightning Bolt causes 1 creature to perish."

(Lightning Bolt does 25 damage per Spell Power.)

![Spell damage sentence fh2 002](https://user-images.githubusercontent.com/43583994/108652536-af655d80-74c4-11eb-98f4-d9dd0b4b5d42.png)

Turn 2
Hero name, spell name, creature name of the target troop (a target must be chosen to be able to cast the spell):
Natasha casts Lightning Bolt on the Unicorns.
Spell name, number of the spell's base damage according to the hero's Spell Power (only one troop is affected, no need to specify the total potential damage): 
The Lightning Bolt does 50 damage.
Only one troop is affected, no need to indicate the number of troops affected; number of creatures decimated:
The Lightning Bolt causes 1 creature to perish.

If no creature perishes:

The Lightning Bolt causes 0 creature to perish.

"Turn 3
Natasha casts Cold Ring.
The Cold Ring does 20 damage (total: 40).
The Cold Ring hits 2 troops, 2 creatures perish."

(Cold Ring does 10 damage per Spell Power.)

![Spell damage sentence fh2 003](https://user-images.githubusercontent.com/43583994/108652551-b7bd9880-74c4-11eb-8d02-c12b42c22710.png)

Turn 3
Hero name, spell name, no creature name (it is not necessary to choose a target to be able to cast the spell, and the spell can affect several troops):
Natasha casts Cold Ring.
Spell name, number of the spell's base damage according to the hero's Spell Power (several troops are affected, total potential base damage of the spell according to the hero's Spell Power):
The Cold Ring does 20 damage (total: 40).
Number of troops affected by the spell, number of creatures decimated:
The Cold Ring hits 2 troops, 2 creatures perish.

"Turn 4
Natasha casts Cold Ray on the Unicorns.
The Cold Ray does 40 damage.
The Cold Ray causes 1 creature to perish."

(Cold Ray does 20 damage per Spell Power.)

![Spell damage sentence fh2 004](https://user-images.githubusercontent.com/43583994/108652557-bee4a680-74c4-11eb-9d8d-138286f718c8.png)

"Turn 5
Natasha casts Fireball.
The Fireball does 20 damage (total: 40).
The Fireball hits 2 troops, 2 creatures perish."

(Fireball does 10 damage per Spell Power.)

![Spell damage sentence fh2 005](https://user-images.githubusercontent.com/43583994/108652572-c73ce180-74c4-11eb-855a-6dd67270e6cb.png)

"Turn 6
Natasha casts Fireblast.
The Fireblast does 20 damage (total: 60).
The Fireblast hits 3 troops, 3 creatures perish."

(Fireblast does 10 damage per Spell Power.)

![Spell damage sentence fh2 006](https://user-images.githubusercontent.com/43583994/108652585-cefc8600-74c4-11eb-9bc6-e1c104342f94.png)

"Turn 7
Natasha casts Meteor Shower.
The Meteor Shower does 50 damage (total: 100).
The Meteor Shower hits 2 troops, 3 creatures perish."

(Meteor Shower does 25 damage per Spell Power.)

![Spell damage sentence fh2 007](https://user-images.githubusercontent.com/43583994/108652603-d6239400-74c4-11eb-9918-8d78a1c78918.png)

"Turn 8
Natasha casts Magic Arrow on the Unicorns.
The Magic Arrow does 20 damage.
The Magic Arrow causes 1 creature to perish."

(Magic Arrow does 10 damage per Spell Power.)

![Spell damage sentence fh2 008](https://user-images.githubusercontent.com/43583994/108652617-dcb20b80-74c4-11eb-9592-a8376fc9d973.png)

"Turn 9
Natasha casts Armageddon.
The Armageddon does 100 damage to all troops.
The enemy Battle Dwarves resist the spell!
The Armageddon hits 5 troops, 24 creatures perish."

The Armageddon spell is a mass spell, it is not necessary to indicate the total potential damage.
(Armageddon does 50 damage per Spell Power.)

![Spell damage sentence fh2 009](https://user-images.githubusercontent.com/43583994/108652625-e3408300-74c4-11eb-8153-b30222d43e0e.png)

If there is one friendly troop that is affected by the spell:

The spell hits 1 friendly troop!

If there are friendly troops that are affected by the spell:

The spell hits 3 friendly troops!

If friendly Battle Dwarves resist the spell:

The friendly Battle Dwarves resist the spell!

If there are several troops of friendly (and/or enemy) Battle Dwarves resisting the spell, a line is written for each troop:

The enemy Battle Dwarves resist the spell!
The enemy Battle Dwarves resist the spell!
The friendly Battle Dwarves resist the spell!
The friendly Battle Dwarves resist the spell!

If friendly and/or enemy troops suffer only partial damage from the spell (Broach of Shielding):
(Broach of Shielding: Provides 50% protection from Armageddon and Elemental Storm, but decreases the spell power by 2.)

Friendly troops take only half damage!
Enemy troops take only half damage!

If there are several troops of friendly (and/or enemy) Battle Dwarves resisting the spell, and friendly troops suffer only partial damage from the spell:

The enemy Battle Dwarves resist the spell!
The enemy Battle Dwarves resist the spell!
The friendly Battle Dwarves resist the spell!
The friendly Battle Dwarves resist the spell!
Friendly troops take only half damage!

If there are several troops of friendly (and/or enemy) Battle Dwarves resisting the spell, and enemy troops suffer only partial damage from the spell:

The enemy Battle Dwarves resist the spell!
The enemy Battle Dwarves resist the spell!
The friendly Battle Dwarves resist the spell!
The friendly Battle Dwarves resist the spell!
Enemy troops take only half damage!

If there are several troops of friendly (and/or enemy) Battle Dwarves resisting the spell, and friendly and enemy troops suffer only partial damage from the spell:

The enemy Battle Dwarves resist the spell!
The enemy Battle Dwarves resist the spell!
The friendly Battle Dwarves r [...]

2021-02-26 14:59 UTC, Branikolog commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
@LeHerosInconnu

> Could you, please, create a discussion...

I mean not here... I didn't want to watch here these tremendous posts.... ^_^

Here's a discussion for all-mass spells, to change the total damage to individual spell damage... All that "resist stuff" should be discussed in separate discussion thread.

On subject:

To summarize the above post(s):
`"[Hero name] casts [spell name]."`
`"The [spell name] does xxx damage to all troops."`
`"xx creatures perish"`
{Discussion regarding "Total" or "Not total" damage I propose to transfer into separate discussion thread.}

In a case he cast death or holy spells we should show the next message in a log:
`"The [spell name] does xxx damage to all living(non-living) troops."`
`"xx living(non living) creatures perish"`

Let's stick as much close to OG, as we can for now.

Does anybody has any objections?

I hope, @LeHerosInconnu will make a discussion thread, where we all together would discuss what improvements we can make for log description regarding spells. I can also propose a few nice. ;)

2021-02-26 18:06 UTC, LeHerosInconnu commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
@Branikolog.

> @LeHerosInconnu
> 
> > Could you, please, create a discussion...
> 
> I mean not here... I didn't want to watch here these tremendous posts.... ^_^
> 
> Here's a discussion for all-mass spells, to change the total damage to individual spell damage... All that "resist stuff" should be discussed in separate discussion thread.
> 
> I hope, @LeHerosInconnu will make a discussion thread, where we all together would discuss what improvements we can make for log description regarding spells. I can also propose a few nice. ;)

I created a discussion here: (https://github.com/ihhub/fheroes2/discussions/2873)

> On subject:
> 
> To summarize the above post(s):
> `"[Hero name] casts [spell name]."`
> `"The [spell name] does xxx damage to all troops."`
> `"xx creatures perish"`
> {Discussion regarding "Total" or "Not total" damage I propose to transfer into separate discussion thread.}
> 
> In a case he cast death or holy spells we should show the next message in a log:
> `"The [spell name] does xxx damage to all living(non-living) troops."`
> `"xx living(non living) creatures perish"`
> 
> Let's stick as much close to OG, as we can for now.
> 
> Does anybody has any objections?

For mass spells:
`"[Hero name] casts [spell name]."`
`"The [spell name] does [Hero Spell Power x spell base damage] damage to all troops."`

For: `"xx creatures perish"`
I think it's not very pleasant to start the sentence with a number, that's why I added the number of troops affected before the number of decimated creatures and repeating the name of the spell.

This: 
`"Gem casts Elemental Storm."`
`"The Elemental Storm does 50 damage to all troops."`
`"The Elemental Storm hits 5 troops, 10 creatures perish."`

Instead:
`"Gem casts Elemental Storm."`
`"The Elemental Storm does 50 damage to all troops."`
`"10 creatures perish."`

For Death and Holy spells:
`"The [spell name] does [Hero Spell Power x spell base damage] damage to all living (undead) troops."`
`"xx living (undead) creatures perish"`

The term "undead" is used in the original game:
![Damage spell undead H2 01](https://user-images.githubusercontent.com/43583994/109335827-df18ba80-7862-11eb-84be-9796ec54aa18.png)

This:
`"Gem casts Holy Shout."`
`"The Holy Shout does 40 damage to all undead troops."`
`"The Holy Shout hits 1 troop, 2 creatures perish."`

Instead:
`"Gem casts Holy Shout."`
`"The Holy Shout does 40 damage to all undead troops."`
`"2 creatures perish."`

2021-02-26 19:03 UTC, Branikolog commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
Hi, @LeHerosInconnu!

>The term "undead" is used in the original game:

Okay. 
Unfortunately, original game crashed a few days before and now I cannot compare fheroes2 with it.) 

>I think it's not very pleasant to start the sentence with a number

I agree with you... 
But indicating the number of troops affected is not so useful info... As we have not so much troops on a battlefield, and we can easily understand and count, who was affected by the spell (except the cases of immune or resistances, but you have a nice suggestion regarding it (nevertheless, which requires some polishes in my opinion :) )).
So I think we should start sentence with some other words to look more pleasant. (if I'm not mistaken, in original game there were such sentences, starting with numbers) 
What if type the total info damage before the number of creatures perished? 
Something like: "The spell does xxx total damage,  xx creatures perished."
So the first part of the sentence contains the reason, why we have some creatures perished. That looks much more informative and good looking.. 
In a case my conclusions are wrong, we can type in log any simple good-looking sentence. Something like: "The spell was the reason, why xx creatures perished"

2021-02-26 21:55 UTC, LeHerosInconnu commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
Hello @Branikolog,

> Hi, @LeHerosInconnu!
> 
> > The term "undead" is used in the original game:
> 
> Okay.
> Unfortunately, original game crashed a few days before and now I cannot compare fheroes2 with it.)
> 
> > I think it's not very pleasant to start the sentence with a number
> 
> I agree with you...
> But indicating the number of troops affected is not so useful info... As we have not so much troops on a battlefield, and we can easily understand and count, who was affected by the spell (except the cases of immune or resistances, but you have a nice suggestion regarding it (nevertheless, which requires some polishes in my opinion :) )).
> So I think we should start sentence with some other words to look more pleasant. (if I'm not mistaken, in original game there were such sentences, starting with numbers)
> What if we place the total info damage before the number of creatures perished?
> Something like: "The spell does xxx total damage, xx creatures perished."
> So the first part of the sentence contains the reason, why we have some creatures perished. That looks much more informative and good looking..
> In a case my conclusions are wrong, we can type in log any simple good-looking sentence. Something like: "The spell was the reason, why xx creatures perished"

For a mass spell, the number of troops affected is more important to know than the total damage inflicted.
This is a direct indication of whether the spell is effective (hits a lot of troops) or less effective (hits fewer troops).

Let's say the power of the spell is 65 damage [Hero Spell Power x spell base damage].

With the sentence:
The spell hits X troops, X creatures perish.

First case:
The spell hits 5 troops, 10 creatures perish.

Second case:
The spell hits 2 troops, 20 creatures perish.

We can see immediately that the spell is more effective in the first case, because it affects more troops, just read the sentence.

With the sentence:
The spell does xxx total damage, xx creatures perished.

First case:
The spell does 325 total damage, 10 creatures perish.

Second case:
The spell does 130 total damage, 20 creatures perish.

Here, how to determine the effectiveness of the spell?
In the second case, more creatures are decimated.
Would the spell be more effective than in the first case?
Even though the total damage is higher in the first case?
With this sentence, it is necessary to calculate (in relation to the power of the spell [Hero Spell Power x spell base damage]) to determine the number of troops affected in order to know the effectiveness of the spell, whereas in the first sentence, you just have to read the sentence, it's simpler and clearer.

And it is also necessary to take into account that when the log list is not deployed, only the last sentence is visible.

![Spell damage sentence fh2 011](https://user-images.githubusercontent.com/43583994/108652662-fa7f7080-74c4-11eb-8199-515ec2a803bf.png)

![Logs list not deployed 01](https://user-images.githubusercontent.com/43583994/109355654-d08ccc00-787f-11eb-9c18-6c097e2c3d00.png)

And there, it's much clearer, the sentence `"The spell hits 5 troops, 10 creatures perish."` gives all the necessary information to know the effectiveness of the spell, while the sentence `"The spell does 325 total damage, 10 creatures perish."` doesn't allow at all to determine the effectiveness of the spell because the number of troops hit is not known.

2021-02-27 09:03 UTC, Branikolog commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
@LeHerosInconnu

Now we are talking about all-mass spells, that deal damage over the whole battlefield.
We even have description in the log above, that "spell hits ALL creatures". (Or ALL living/undead creatures)
So why do we need to describe how much troops were affected, if it's quite obvious? Spell hits every troop you can watch at the battlefield. So you can easily count them. (It's also easy due to limitation of hero army by 5 troops. So it would be 10 max. Okay, we can summon some, but it's rely not a problem to understand, how much troops are there on a battlefield). So do we really need to watch the quantity of creatures affected, if we know, that spell hits all of them?
In my point of view, total damage is more useful info, as we can understand how much damage spell applied to creatures and compare it with some single target spell.
For example: the mass spell deals 65 damage per troop.
The spell potentially hit 4 targets. (The most common case, when we cast this type of spell is the situation, when the spell is harmless to our creatures. So we watch the overall damage for all enemy troops in a log by this way.)
So the spell hits 65x4=140 damage.
At the same time we have a single target spell in our spellbook (ex. Lightning) which deals 140 damage as well...
So here we can compare these two spells and find out, that we deal the same amount of damage for different mana cost. So it would be more efficient to cast single target "Lightning" spell better than another mana-expensive mass spell.
That's the point of of the total damage.

2021-02-27 11:09 UTC, LeHerosInconnu commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
@Branikolog.

> @LeHerosInconnu
> 
> Now we are talking about all-mass spells, that deal damage over the whole battlefield.
> We even have description in the log above, that "spell hits ALL creatures". (Or ALL living/undead creatures)
> So why do we need to describe how much troops were affected, if it's quite obvious? Spell hits every troop you can watch at the battlefield. So you can easily count them. (It's also easy due to limitation of hero army by 5 troops. So it would be 10 max. Okay, we can summon some, but it's rely not a problem to understand, how much troops are there on a battlefield). So do we really need to watch the quantity of creatures affected, if we know, that spell hits all of them?
> In my point of view, total damage is more useful info, as we can understand how much damage spell applied to creatures and compare it with some single target spell.
> For example: the mass spell deals 65 damage per troop.
> The spell potentially hit 4 targets. (The most common case, when we cast this type of spell is the situation, when the spell is harmless to our creatures. So we watch the overall damage for all enemy troops in a log by this way.)
> So the spell hits 65x4=140 damage.
> At the same time we have a single target spell in our spellbook (ex. Lightning) which deals 140 damage as well...
> So here we can compare these two spells and find out, that we deal the same amount of damage for different mana cost. So it would be more efficient to cast single target "Lightning" spell better than another mana-expensive mass spell.
> That's the point of of the total damage.

> So the spell hits 65x4=140 damage.

Something seems to be broken. :D
65 x 4 = 260 damage.

> At the same time we have a single target spell in our spellbook (ex. Lightning) which deals 140 damage as well...

For the same Spell Power, the Lightning Bolt spell does 325 damage, and the Lightning Bolt spell would never do 140 damage, because 140 is not a multiple of 25 (nor of 12.5 with the Lightning Helm artifact, nor of 37.5 with the Lighting Rod artifact). :)

> So here we can compare these two spells and find out, that we deal the same amount of damage for different mana cost. So it would be more efficient to cast single target "Lightning" spell better than another mana-expensive mass spell.

Well, I get the idea anyway. :)

> So it would be more efficient to cast single target "Lightning" spell better than another mana-expensive mass spell.

Not necessarily, it is sometimes smarter to eliminate several small opposing troops at the same time, in order to be able to use another spell, for example the "Blind" spell, the next turn.
It all depends on the situation.

So, you want this:

`"[Hero name] casts [spell name]."`
`"The [spell name] does [Hero Spell Power x spell base damage] damage to (all) (all living) (all undead) troops."`
`"The [spell name] does [total max potential damage = [Hero Spell Power x spell base damage] x number of troops hit] damage, [number of creatures] creatures perish."`

`"Gem casts Death Ripple."`
`"The Death Ripple does 65 damage to all living troops."`
`"The Death Ripple does 260 damage, 10 creatures perish."`

Okay, let's go for it. :)

2021-02-27 11:39 UTC, Branikolog commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
> Something seems to be broken. :D

You know... These numbers are so complicated...

>65 x 4 = 260 damage.

That's one more evidence, that we need to show total damage. ) Not everybody can count so well. ^_^

`"The Death Ripple does 65 damage to all living troops."`
`"The Death Ripple does 260 damage, 10 creatures perish."`
I think we should add `"total"` in the second line, not to confuse player by two same expressions: "does 65 damage" and "does 260 damage.

2021-02-27 12:02 UTC, LeHerosInconnu commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
@Branikolog.

> > Something seems to be broken. :D
> 
> You know... These numbers are so complicated...
> 
> > 65 x 4 = 260 damage.
> 
> That's one more evidence, that we need to show total damage. ) Not everybody can count so well. ^_^

:D

> `"The Death Ripple does 65 damage to all living troops."`
> `"The Death Ripple does 260 damage, 10 creatures perish."`
> I think we should add `"total"` in the second line, not to confuse player by two same expressions: "does 65 damage" and "does 260 damage.

I think the line would become too long with "total" (or "max" :D) added.

The Death Ripple does 1000 total damage, 1000 creatures perish.

2021-03-03 13:15 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    msg << Join( damages );
We should remove `total`:
![image](https://user-images.githubusercontent.com/19829520/109811302-99466280-7c65-11eb-8b4a-85caa4c83331.png)

2021-03-14 10:28 UTC, merged