optimize logging / translation headers
ihhub/fheroes2 pull request #2760
Opened 2021-02-07 10:46 UTC by dimag0g

I extracted the logging/debug functionality and put it in a separate unit (`logging.h`/`logging.cpp`) in the engine. I also renamed `DEBUG` `ERROR` and `VERBOSE` macros to `DEBUG_LOG`, `ERROR_LOG` and `VERBOSE_LOG`, to hopefully make it clearer what those macros actually do (logging), and to avoid the conflict with the `ERROR` macro on Windows. In addition, I have moved the `_(` macro inside `translations.h`, and included that file in `text.h` instead of `gamedefs.h`, and directly in a dozen of units which use translations but don't depend on  `text.h`.

Let's discuss the implementation details of the logging. Is it OK to define functions in the global namespace, or should I use the `Logging` namespace? Is it OK to have an `InitLog` function (it really helps dealing with dependency on `Settings`)? Anything else that needs fixing?

2021-02-07 11:43 UTC, dimag0g commented
Practical question: is there a way to apply the output of `clang-format-git` to the code? It's not in the format `git` understands.

2021-02-07 14:38 UTC, ihhub commented
> 
> 
> Practical question: is there a way to apply the output of `clang-format-git` to the code? It's not in the format `git` understands.

Hi @dimag0g , please refer to [this topic](https://github.com/ihhub/fheroes2/pull/166).

2021-02-07 15:44 UTC, ihhub commented
@dimag0g , I will review this pull request once you solve the compilation issues. Please do not hesitate to ask any help if you need :)

2021-02-07 20:04 UTC, dimag0g commented
@ihhub Hi, I finally it sorted out. Sorry it took so long. Ready for review.

2021-02-09 14:19 UTC, ihhub requested changes
Hi @dimag0g , I left multiple comments. Could you please take a look?

2021-02-09 14:19 UTC, ihhub commented on src/engine/logging.cpp
> +/***************************************************************************
Please correct the header of the file according to [this link](https://github.com/ihhub/fheroes2/wiki/Copyright-standard).

2021-02-09 14:19 UTC, ihhub commented on src/engine/logging.h
> +/***************************************************************************
Please correct the header of the file according to [this link](https://github.com/ihhub/fheroes2/wiki/Copyright-standard).

2021-02-09 14:19 UTC, ihhub commented on src/engine/logging.h
> +void InitLog( int debug_setting = DEFAULT_DEBUG );
Please put all functions under fheroes2 namespace.

2021-02-09 14:19 UTC, ihhub commented on src/engine/logging.h
> +std::string GetLogTime( void );
Please remove void. It's redundant.

2021-02-09 14:19 UTC, ihhub commented on src/engine/logging.h
> +const char * StringDebug( int );
Please add the name of input paramter and `const` modifier.

2021-02-09 14:19 UTC, ihhub commented on src/engine/logging.cpp
> +    return std::string( buf );
Please modify this code into:
```
time_t raw;
std::time( &raw );

struct tm * tmi = std::localtime( &raw );

std::string temp;
temp.resize( 13 );
std::strftime( temp.data(), temp.size() - 1, "%X", tmi );
return temp;
```
This is to avoid memory code and make the code look better.

2021-02-09 14:19 UTC, ihhub commented on fheroes2.vcxproj
> +    <ClCompile Include="src\engine\logging.cpp" />
Please add header file as well.

2021-02-13 10:48 UTC, merged

2021-02-13 10:49 UTC, ihhub commented
@dimag0g , I made needed changes. Thank you very much for your changes!

2021-02-15 17:09 UTC, dimag0g commented
@ihhub Hi, sorry I dropped the ball here. Had a really busy week. Thank you so much for finishing this for me!