Change building status message
ihhub/fheroes2 pull request #2762
Opened 2021-02-07 17:04 UTC by kant2002

When hover over building display information about units which can be bought if this is that kind of building. For other building just display name of the building
Closes #1730

2021-02-07 18:02 UTC, kant2002 commented
Have following error.

```
../fheroes2/castle/castle.cpp:2804:13: error: declaration shadows a field of 'Castle' [-Werror,-Wshadow]
    Monster building( race, buildingId );
            ^
../fheroes2/castle/castle.h:242:9: note: previous declaration is here
    u32 building;
        ^
../fheroes2/castle/castle.cpp:2806:17: error: declaration shadows a field of 'Castle' [-Werror,-Wshadow]
        Monster dwelling( race, building.GetDwelling() );
                ^
../fheroes2/castle/castle.h:248:9: note: previous declaration is here
    u32 dwelling[CASTLEMAXMONSTER];

```
Isn't it a bit much? or can this be enforced on VC++ level too.

2021-02-08 16:00 UTC, ihhub commented
Hi @kant2002 , none of warnings are enforced of developer's machine. We do this only on server's level. Sadly Visual Studio is not that flexible as gcc that's why right now we use -W4 flag and just don't fail the compilation.

2021-02-08 16:03 UTC, kant2002 commented
It was an annoyance to not be able fix that issue on dev machine

2021-02-09 12:34 UTC, ihhub requested changes
Hi @kant2002 , I left multiple comments here. Could you please take a look?

2021-02-09 12:34 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +    Monster buildingInfo( race, buildingId );
Please make this variable `const`.

2021-02-09 12:34 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +    if ( buildingInfo.GetDwelling() ) {
Please cache this variable as we call it twice `const uint32_t dwellingType = buildingInfo.GetDwelling();`.

2021-02-09 12:34 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +std::string Castle::buildingStatusMessage( uint32_t buildingId ) const
`buildingId` is a dwellingId for monsters. Why don't we try to do this `( buildingId & DWELLING_MONSTERS ) != 0` meaning that this is a monster dwelling? So the code would be:
```
if ( ( buildingId & DWELLING_MONSTERS ) == 0 ) {
    return GetStringBuilding( buildingId );
}
...
// the rest of the code.
```

2021-02-09 12:34 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +    Monster buildingInfo( race, buildingId );
This variable might not needed based on the above comment.

2021-02-09 12:34 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +    if ( buildingInfo.GetDwelling() ) {
This variable might not needed based on the above comment.

2021-02-09 12:34 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +        Monster dwellingInfo( race, buildingInfo.GetDwelling() );
Please make this variable `const` and name it as `monster` as it is a monster :)

2021-02-09 12:34 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +        std::string msg_status = _( "Recruit %{name}" );
Please use camelCase variable naming: `std::string msgStatus( _( "Recruit %{name}" )  );`.

2021-02-09 12:34 UTC, ihhub commented on src/fheroes2/castle/castle.h
> +    std::string buildingStatusMessage( uint32_t ) const;
Please add the name of input argument (old code was written in such weird way) and make the input parameter const as we don't modify it.

2021-02-09 14:15 UTC, kant2002 commented
@ihhub I fix all suggestions except `buildingId & DWELLING_MONSTERS ) == 0` change which seems to low-level and less intuitive for the reader. I hope and put trust in the compiler to revert conditions etc. Let me know if you have any concerns about this style

2021-02-09 14:22 UTC, ihhub commented
> @ihhub I fix all suggestions except `buildingId & DWELLING_MONSTERS ) == 0` change which seems to low-level and less intuitive for the reader. I hope and put trust in the compiler to revert conditions etc. Let me know if you have any concerns about this style

Hi @kant2002 , it is not a low level code. This code:
```
    const Monster buildingInfo( race, buildingId );
    const uint32_t dwellingMonsterId = buildingInfo.GetDwelling();
    const bool isDwelling = dwellingMonsterId != 0;
```
essentially creates an instance of a class, we check dwelling id based on this instance and remove the object. My proposed solution does the check without extra memory usage. If you aren't sure about understanding by other developers let's put a comment describing why we do all this.

2021-02-09 14:25 UTC, kant2002 commented
Isn't the Monster class just glorified int?

2021-02-09 14:27 UTC, ihhub commented
> Isn't the Monster class just glorified int?

Yes but we don't need to even create an instance of this class to do the job. Also there's an extra logic when we create it and call the function (invoking call stack usage).

2021-02-09 14:27 UTC, kant2002 commented
Also I do not fully understand what you trying to say about relationship between `buildingId` and `DWELLING_MONSTERS`. I still do not get how can I get `monsterId` from building id.

2021-02-09 14:37 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +std::string Castle::buildingStatusMessage( const uint32_t buildingId ) const
This is what I'm proposing:
```
std::string Castle::buildingStatusMessage( const uint32_t buildingId ) const
{
    // Check if building is a monster dwelling or its upgraded version
    if ( ( buildingId & DWELLING_MONSTERS ) == 0 && ( buildingId & DWELLING_UPGRADES ) == 0 ) {
        return GetStringBuilding( buildingId );
    }

    const Monster monster( race, buildingId );
    std::string msgStatus = _( "Recruit %{name}" );
    StringReplace( msgStatus, "%{name}", monster.GetMultiName() );
    return msgStatus;
}
```

Check that I changed GetName to GetMultiName as logically a dwelling contains more than 1 monster.

2021-02-09 15:00 UTC, kant2002 commented on src/fheroes2/castle/castle.cpp
> +std::string Castle::buildingStatusMessage( const uint32_t buildingId ) const
Ok. now it make sense. Regarding singular vs plural form. Testers are want pixel perfect match sometimes, so I do not move from original issues description. Now it make more sense.

2021-02-09 15:02 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +std::string Castle::buildingStatusMessage( const uint32_t buildingId ) const
I think everyone will agree with plural form. @Branikolog what do you think?

2021-02-09 15:04 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +std::string Castle::buildingStatusMessage( const uint32_t buildingId ) const
@LeHerosInconnu (sorry, missed you to mentioned in previous message), what do you think?

2021-02-09 15:09 UTC, Branikolog commented on src/fheroes2/castle/castle.cpp
> +std::string Castle::buildingStatusMessage( const uint32_t buildingId ) const
Hi, @kant2002 and @ihhub !
Plural form of creatures is already implemented in fheroes2 recruit windows:
![image](https://user-images.githubusercontent.com/55348946/107383066-ac9c5d00-6b01-11eb-9b59-886496776b3c.png)
So in bottom textline should be the same should be.

2021-02-09 19:22 UTC, LeHerosInconnu commented on src/fheroes2/castle/castle.cpp
> +std::string Castle::buildingStatusMessage( const uint32_t buildingId ) const
Taking into account the singular and plural improves the original game, so it's a good thing. :)

2021-02-10 08:18 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +std::string Castle::buildingStatusMessage( const uint32_t buildingId ) const
Great! @kant2002 , could you please incorporate these changes with plural form of monsters?

2021-02-11 04:01 UTC, merged

2021-02-11 04:02 UTC, ihhub commented
@kant2002 thank you so much for fixing this issue!