Remove dependency on game.h and campaign_data.h
ihhub/fheroes2 pull request #2764
Opened 2021-02-07 17:20 UTC by kant2002

2021-02-07 18:45 UTC, kant2002 commented on src/fheroes2/game/game_io.cpp
> +    if ( conf.GameType() & Game::TYPE_CAMPAIGN && Game::GetLoadVersion() == FORMAT_VERSION_084_RELEASE ) {
Please take a note on `Game::GetLoadVersion() == FORMAT_VERSION_084_RELEASE`. My understanding that it should be `Game::GetLoadVersion() >= FORMAT_VERSION_084_RELEASE` to work on future versions too. I do not change that, since this is unrelated to my changes, but would be good to have answer, so I can fix that in followup PR

2021-02-08 02:01 UTC, eos428 commented on src/fheroes2/game/game_io.cpp
> +    if ( conf.GameType() & Game::TYPE_CAMPAIGN && Game::GetLoadVersion() == FORMAT_VERSION_084_RELEASE ) {
This if clause is correct because it was at `FORMAT_VERSION_084_RELEASE` that campaign save data were stored in settings.

2021-02-08 02:10 UTC, kant2002 commented on src/fheroes2/game/game_io.cpp
> +    if ( conf.GameType() & Game::TYPE_CAMPAIGN && Game::GetLoadVersion() == FORMAT_VERSION_084_RELEASE ) {
So right now this is not stored as part of setting. Correct? Just double-checking, since I discover that bug when was only FORMAT_VERSION_084_RELEASE declared IIRC.

2021-02-08 04:21 UTC, eos428 commented on src/fheroes2/game/game_io.cpp
> +    if ( conf.GameType() & Game::TYPE_CAMPAIGN && Game::GetLoadVersion() == FORMAT_VERSION_084_RELEASE ) {
Yes it's no longer stored as part of setting

2021-02-08 04:33 UTC, kant2002 commented on src/fheroes2/game/game_io.cpp
> +    if ( conf.GameType() & Game::TYPE_CAMPAIGN && Game::GetLoadVersion() == FORMAT_VERSION_084_RELEASE ) {
Ok. Make sense now.

2021-02-09 12:41 UTC, ihhub requested changes
Hi @kant2002 , please have a look into few given comments. Also please take a not as we might modify this pull request as very soon we'll merge campaign related pull request.

2021-02-09 12:41 UTC, ihhub commented on src/fheroes2/game/game_io.cpp
> +    if ( conf.GameType() & Game::TYPE_CAMPAIGN && Game::GetLoadVersion() == FORMAT_VERSION_084_RELEASE ) {
Please change it to `if ( ( conf.GameType() & Game::TYPE_CAMPAIGN ) != 0 && Game::GetLoadVersion() == FORMAT_VERSION_084_RELEASE ) {` to be more explicit as it's very easy to mix & and &&.

2021-02-09 12:41 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +    const std::string fname = System::ConcatePath( Settings::GetWriteableDir( "save" ), "fheroes2.bin" );
Please remove `Settings::` as we're making the call from the same class.

2021-02-09 12:41 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +    std::string fname = System::ConcatePath( Settings::GetWriteableDir( "save" ), "fheroes2.bin" );
Please remove `Settings::` as we're making the call from the same class.

2021-02-09 13:42 UTC, kant2002 commented
@ihhub I correct all suggestions. Can you take a look?

2021-02-11 17:59 UTC, ihhub commented
Hi @kant2002 , could you please fix merging conflict?

2021-02-11 19:32 UTC, kant2002 commented
@ihhub take a look

2021-02-12 05:46 UTC, ihhub reviewed
Hi @kant2002 , everything looks great, just please add one comment in the code to be safe and I'll merge this pull request.

2021-02-12 05:46 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +    // 0x80 value should be same as in Game::TYPE_LOADFILE enumeration value
Could you please add a comment at the place of TYPE_LOADFILE declaration to refer to this method in case of its value change? Something like TYPE_LOADFILE = 0x80, // in case of changing this value please update Settings::LoadedGameVersion method.

2021-02-12 07:11 UTC, merged

2021-02-12 07:11 UTC, ihhub commented
@kant2002 , a bunch of thanks making our codebase better!