Add days passed to Campaign SaveData and fix unsaved CampaignID
ihhub/fheroes2 pull request #2793
Opened 2021-02-12 15:15 UTC by eos428

There's no issue written for either of these yet, so this wouldn't close any of our current issues.

2021-02-12 15:50 UTC, idshibanov commented on src/fheroes2/system/settings.h
> +#define FORMAT_VERSION_091_RELEASE 9100
There are two additional savegame changing PRs coming in. I would avoid going straight to 9100 for now. Have to decide the strategy around it.

2021-02-13 00:27 UTC, eos428 commented on src/fheroes2/system/settings.h
> +#define FORMAT_VERSION_091_RELEASE 9100
In that case, why not have all 3 PRs increase the version to the same number? I think it wouldn't make sense if we need to increase version for every one of the PRs, especially if let's say, they'd be merged within hours/days of each other.

2021-02-13 00:48 UTC, idshibanov commented on src/fheroes2/system/settings.h
> +#define FORMAT_VERSION_091_RELEASE 9100
Could work. @ihhub what do you think?

2021-02-13 01:06 UTC, ihhub commented on src/fheroes2/system/settings.h
> +#define FORMAT_VERSION_091_RELEASE 9100
Yes. We can do this. I can fix merge conflicts as well. Which is the third PR besides #2630?

2021-02-16 15:20 UTC, ihhub requested changes
Hi @eos428 , everything looks good except one place. Could you please fix it?

2021-02-16 15:20 UTC, ihhub commented on src/fheroes2/campaign/campaign_savedata.h
> +        int _daysPassed;
The number of days cannot be negative value plus `world.CountDay()` returns `uint32_t`. Could you please fix it?

2021-02-16 17:38 UTC, ihhub requested changes
Hi @eos428 , could you please change int to uint32_t in highlighted places? The rest is perfect.

2021-02-16 17:38 UTC, ihhub commented on src/fheroes2/campaign/campaign_savedata.h
> +        int getDaysPassed() const
Please return here `uint32_t`.

2021-02-16 17:38 UTC, ihhub commented on src/fheroes2/campaign/campaign_savedata.h
> +        void addDaysPassed( const int days );
Please change it to `uint32_t`.

2021-02-17 02:25 UTC, ihhub approved these changes

2021-02-17 04:19 UTC, merged

2021-02-17 04:20 UTC, ihhub commented
@eos428 , thank you veru much for this fix!