Fix scenario difficulty (#2656)
ihhub/fheroes2 pull request #2796
Opened 2021-02-12 19:56 UTC by 0UserName

Fix for #2656. As I understand it, every time `Settings::SetCurrentFileInfo` is called, the `game_difficulty` value is [reset](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/system/settings.cpp#L849) to `Difficulty::NORMAL`, thereby overriding the value set by the user:

```
/* read maps info */
void Settings::SetCurrentFileInfo( const Maps::FileInfo & fi )
{
    current_maps_file = fi;

    players.Init( current_maps_file );

    // game difficulty
    game_difficulty = Difficulty::NORMAL; // <- this
    preferably_count_players = 0;
}
```

If remove the override, the previously selected value is retained between scenario restarts, but is reset when you load the saved game to the value used in it. In principle, if implement new `Game::LoadDifficulty`/`Game::SaveDifficulty` methods by analogy with `Game::LoadPlayers`/`Game::SavePlayers`, then the problem will be solved.

2021-02-13 13:45 UTC, ihhub requested changes
Hi @0UserName, could you please take a look at given comments and also name your branch without special characters as I'm unable to git pull it for verification?

2021-02-13 13:45 UTC, ihhub commented on src/fheroes2/game/game.cpp
> +    conf.SetGameDifficulty( difficulty );
Please combine these two lines to avoid a creation of temporary variable.

2021-02-13 13:45 UTC, ihhub commented on src/fheroes2/game/game.h
> +    void SaveDifficulty( int newDifficulty );
Could you please make the input argument `const` as we do not modify it?

2021-02-13 14:07 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> -    game_difficulty = Difficulty::NORMAL;
If we removed this line Campaign maps will depends on the last selection of difficulty of single-player/multi-player games. Could you please check this? Difficulty affects the amount of resources at the start of a scenario.

2021-02-13 14:23 UTC, 0UserName commented
Hi @ihhub,

> Could you please take a look at given comments and also name your branch without special characters as I'm unable to git pull it for verification?

Yep. I made edits to the code (except last remark), but through `--force`. I hope it's not a problem. Apparently, it is not possible to change the external branch and need to create a new PR (if wrap the branch name in quotation marks ('# 2656'), then everything should work, in any case the console client works).

2021-02-13 14:25 UTC, ihhub commented
> Hi @ihhub,
> 
> > Could you please take a look at given comments and also name your branch without special characters as I'm unable to git pull it for verification?
> 
> Yep. I made edits to the code (except last remark), but through `--force`. I hope it's not a problem. Apparently, it is not possible to change the external branch and need to create a new PR (if wrap the branch name in quotation marks ('# 2656'), then everything should work, in any case the console client works).

Got it! I'll try again my tomorrow morning🙂

2021-02-14 02:37 UTC, 0UserName commented on src/fheroes2/system/settings.cpp
> -    game_difficulty = Difficulty::NORMAL;
Indeed. I did not have the full version of the game and this moment was missed. Additional changes have been made to the mechanism for set/get the difficulty of the game:

- Initial game difficulty is set from the `main` method through the extended version of the initializing method `Settings`.
- Access to `game_difficulty` in the rest of the code is made not through `Settings::GameDifficulty` and `Settings::SetGameDifficulty`, but through the `Game::GetDifficulty` and `Game::SaveDifficulty` methods that take into account the type of the current game. 
- For the following types, the difficulty value is always returned, set to `Difficulty::NORMAL`: `Game::TYPE_MENU`, `Game::TYPE_CAMPAIGN`, `Game::TYPE_BATTLEONLY`.
- All other types imply the possibility of choosing the complexity (I proceeded from the possibility of setting it through the GUI) and they reuse the previously saved value.

It is also required to check the correctness of the game difficulty setting when loading the save. However, the concept of changes can be assessed right now.

2021-02-14 10:19 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> -    game_difficulty = Difficulty::NORMAL;
Hi @0UserName, my apologies but this code architecture is bit incorrect. Now we have 2 places where we work with game difficulty. We should not do this as it confuses any other developers. I think your original implementation was totally fine except removing this line of code. `SetCurrentFileInfo` method is called for campaign scenarios as well but for normal cases we just need to override the value which was in your original implementation. Could you please revert back to it?

2021-02-14 11:43 UTC, 0UserName commented on src/fheroes2/system/settings.cpp
> -    game_difficulty = Difficulty::NORMAL;
> Now we have 2 places where we work with game difficulty. 

Well, in fact, there is one place if you do not take into account the initialization of `Settings`. If return the default value in the constructor, there will be one entry point - through Game.

My point was that the game difficulty setting also depends on the game type, since in the case of `Game::TYPE_CAMPAIGN` and `Game::TYPE_BATTLEONLY` it was reset to `Difficulty::NORMAL`, but in this case it is logical to delegate the logic of its updating to the code that is inherent in this 'domain'. Otherwise, two places appear in the code that affect the value. In addition, do not have to store an additional variable responsible for the game's difficulty state (previously there was a difficulty variable at `Game` level).

2021-02-15 13:52 UTC, ihhub requested changes
Hi @0UserName , I left multiple comments to correct your solution. Could you please take a look and discuss if needed?

2021-02-15 13:52 UTC, ihhub commented on src/fheroes2/game/game.cpp
> +}
We should remove `GameDifficulty` related code from **Settings** at all. Please store just a global variable for `gameDifficulty` inside game.cpp. Also the code here should look like this:
```
return ( Settings::Get().GameType() & Game::TYPE_CAMPAIGN != 0 ) ? Difficulty::NORMAL : gameDifficulty;
```

2021-02-15 13:52 UTC, ihhub commented on src/fheroes2/game/game.cpp
> +    }
Please just directly assign the value to newly created variable `gameDifficulty`.

2021-02-15 13:52 UTC, ihhub commented on src/fheroes2/game/fheroes2.cpp
> +#include "difficulty.h"
Please revert changes in this file.

2021-02-15 13:52 UTC, ihhub commented on src/fheroes2/game/game.h
> +    void SaveDifficulty( const int d );
Please pass meaningful name of the variable like `difficulty`.

2021-02-15 13:52 UTC, ihhub commented on src/fheroes2/game/game.h
> +    int GetDifficulty( void );
Please remove **void**. This is from legacy code which we're trying to remove. Also please name methods from non-capital letter.

2021-02-15 13:52 UTC, ihhub commented on src/fheroes2/game/game.cpp
> +}
Damn, this parameter is loaded inside Settings. Okay, in this case please do like this:
```
return ( Settings::Get().GameType() & Game::TYPE_CAMPAIGN != 0 ) ? Difficulty::NORMAL : Settings::Get().GameDifficulty();
```

2021-02-15 13:52 UTC, ihhub commented on src/fheroes2/game/game.cpp
> +    }
Here just directly call `Settings::Get().SetGameDifficulty()`.

2021-02-15 13:52 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> -    , game_difficulty( Difficulty::NORMAL )
Please revert this change and include back the header.

2021-02-15 13:52 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +/*
Please remove this method. We shouldn't do this.

2021-02-15 13:52 UTC, ihhub commented on src/fheroes2/system/settings.h
> +    /*
Please remove this method. We shouldn't do this.

2021-02-15 15:22 UTC, 0UserName commented on src/fheroes2/game/game.cpp
> +}
As far as I understand, for `TYPE_BATTLEONLY`, difficulty should be similar to that for `TYPE_CAMPAIGN` . Not? In this case, there will be an 'or'? switch is definitely not suitable?

2021-02-15 15:24 UTC, ihhub commented on src/fheroes2/game/game.cpp
> +}
Difficulty is applicable only on maps. Battle only is just a battle emulator.

2021-02-15 15:46 UTC, 0UserName commented on src/fheroes2/game/game.cpp
> +}
I hope this is my last question :). The original implementation resets the complexity when selecting a new map in the Scenario dialog. I suppose we should use the previous value used?

2021-02-15 16:24 UTC, 0UserName commented on src/fheroes2/game/game_scenarioinfo.cpp
> +                levelCursor.setPosition( coordDifficulty[Game::GetDifficulty()].x, coordDifficulty[Game::GetDifficulty()].y ); // From 0 to 4, see: Difficulty enum
@ihhub , what do you think?

2021-02-16 16:23 UTC, ihhub commented on src/fheroes2/game/game.cpp
> +}
Any question should not be last ;) Yes, logically we should.

2021-02-16 16:25 UTC, ihhub commented on src/fheroes2/game/game_scenarioinfo.cpp
> +                levelCursor.setPosition( coordDifficulty[Game::GetDifficulty()].x, coordDifficulty[Game::GetDifficulty()].y ); // From 0 to 4, see: Difficulty enum
It should be fine.

2021-02-16 16:28 UTC, 0UserName commented on src/fheroes2/game/game.cpp
> +}
Then I have nothing to add to the PR. I will now resolve conflicts locally and re-push the PR.

2021-02-16 16:41 UTC, 0UserName commented on src/fheroes2/game/game.cpp
> +}
It turns out that you can resolve conflicts right here. Are there any rules for commits? Do I need to do squash or something?

2021-02-16 18:00 UTC, ihhub commented on src/fheroes2/game/game.cpp
> +}
All commits within a pull request will be squashed upon merging so you do not need to care about the number of commits.

2021-02-16 18:03 UTC, ihhub approved these changes

2021-02-21 13:09 UTC, merged

2021-02-21 13:09 UTC, ihhub commented
@0UserName , thank you so much for your contribution to the project!