Persist AI related hero variables in savegames
ihhub/fheroes2 pull request #2798
Opened 2021-02-13 06:54 UTC by idshibanov

Role and last visited island ID. Also merged AI enum with the hero ones since it's set by the same Modes call.

2021-02-16 17:24 UTC, ihhub requested changes
Hi @idshibanov , I left multiple comments. Could you please take a look?

2021-02-16 17:24 UTC, ihhub commented on src/fheroes2/system/players.cpp
> +        DEBUG_LOG( DBG_GAME, DBG_WARN, "Player object without AI" );
Is it even possible? If not let's add an assertion here.

2021-02-16 17:24 UTC, ihhub commented on src/fheroes2/system/players.h
> +#include "ai.h"
Could we try to do forward declaration instead of header if possible?

2021-02-16 17:24 UTC, ihhub commented on src/fheroes2/system/players.cpp
> +        if ( std::shared_ptr<AI::Base> ai = ( *it )->getAIInstance().lock() ) {
Let's create a method called `GetAIPersonalityString` of `Player` class so we move all needed logic inside there. Then we can remove `getAIInstance` method as well.

2021-02-16 17:25 UTC, idshibanov commented on src/fheroes2/system/players.cpp
> +        DEBUG_LOG( DBG_GAME, DBG_WARN, "Player object without AI" );
Yes, I also thought about assert here. Let me add it.

2021-02-17 02:19 UTC, ihhub approved these changes

2021-02-17 04:09 UTC, merged

2021-02-17 04:09 UTC, ihhub commented
@idshibanov , thanks a lot for making AI be smarter and more smarter!