Add auto battle resolve mode to the game
ihhub/fheroes2 pull request #2801
Opened 2021-02-14 03:58 UTC by idshibanov

Sped up AI battles as well by removing unnecessary delay, now it happens almost instantly.

Added auto-combat and auto spellcasting settings and included them in base interface:
![image](https://user-images.githubusercontent.com/1373638/107868057-d1b90480-6e4e-11eb-8786-aa142b33d5d5.png)

![image](https://user-images.githubusercontent.com/1373638/107868068-e1384d80-6e4e-11eb-9292-1d0f10af22d6.png)

I hope this will be useful for many, especially people debugging the game.

2021-02-14 10:28 UTC, ihhub requested changes
Hi @idshibanov , could you please move new settings to global as this is the best place for them?

2021-02-14 10:28 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +void Settings::setBattleAutoResolve( bool enable )
These settings should be a part of `opt_global` as they are switchable inside UI settings. Also please add them for reading and writing into the condiguration file.

2021-02-14 10:28 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +bool Settings::ExtBattleAutoResolve( void ) const
The name of the methods should be different if we move them into global settings.

2021-02-14 14:58 UTC, idshibanov commented on src/fheroes2/system/settings.cpp
> +void Settings::setBattleAutoResolve( bool enable )
Updated.

2021-02-16 16:50 UTC, ihhub reviewed
Hi @idshibanov , I commented only one place. Could you please take a look?

2021-02-16 16:50 UTC, ihhub commented on src/fheroes2/battle/battle_main.cpp
> +    bool showBattle = !Settings::Get().BattleAutoResolve() && isHumanBattle;
We shouldn't allow instant battle for both armies being human-controlled. For example, in multiplayer.

2021-02-16 16:50 UTC, ihhub commented on src/fheroes2/battle/battle_main.cpp
> +    bool showBattle = !Settings::Get().BattleAutoResolve() && isHumanBattle;
So the logic should be like this:
```
const bool autoresolveBattle = Settings::Get().BattleAutoResolve();
const bool isHumanBattle = army1.isControlHuman() || army2.isControlHuman();
const bool allHumans = army1.isControlHuman() && army2.isControlHuman();
const bool showBattle = allHumans || ( !autoresolveBattle && isHumanBattle );
```

2021-02-16 16:57 UTC, merged

2021-02-16 16:57 UTC, ihhub commented
@idshibanov , great work! Thank you very much for such feature!