Cache released disabled button sprite
ihhub/fheroes2 pull request #2818
Opened 2021-02-17 20:49 UTC by tau3

Hi!

Found a TODO, attempted to fix.

2021-02-18 13:41 UTC, ihhub requested changes
Hi @tau3 , could you please take a look at few given comments?

2021-02-18 20:24 UTC, tau3 commented on src/fheroes2/gui/ui_button.h
> +        std::shared_ptr<Sprite> releasedDisabled;
fixed №1, №3, but the field needs to be protected because it is invalidated in ancestor classes directly e.g. when sprite is changed

2021-02-21 09:44 UTC, ihhub requested changes
Hi @tau3 , I left one comment to modify proposed code design. Please take a look.

2021-02-21 09:44 UTC, ihhub commented on src/fheroes2/gui/ui_button.cpp
> +        _releasedDisabled.reset();
We should not expose this class member to child classes. Please move it to private section. The correct way to invalidate this unique pointer is to remember a pointer to the original image and compare it every time. within `void ButtonBase::draw( Image & area )` method.

2021-03-06 15:02 UTC, merged

2021-03-06 15:02 UTC, ihhub commented
@tau3 , thank you so much for this improvement!