#761
ihhub/fheroes2 pull request #2826
Opened 2021-02-19 17:56 UTC by 0UserName

Magic book behavior in OG:

![og_open_book_no_select](https://user-images.githubusercontent.com/46850587/108541849-02d48180-72f4-11eb-99a2-abde4011258a.PNG)

![og_trade_book_not_allowed](https://user-images.githubusercontent.com/46850587/108541848-01a35480-72f4-11eb-8548-6439ed696728.PNG)

Magic book behavior in FH:

![fh_open_book_no_select](https://user-images.githubusercontent.com/46850587/108541941-213a7d00-72f4-11eb-9bd5-235724695eff.PNG)

![fh_trade_book_not_allowed](https://user-images.githubusercontent.com/46850587/108541946-226baa00-72f4-11eb-8eb7-2981472cc276.PNG)

The change is to move the magic book opening logic from the `ArtifactsBar::ActionBarLeftMouseDoubleClick` method to `ArtifactsBar::ActionBarLeftMouseSingleClick`. This prevents the magic book from being selected and moved in the inventory form.

To prevent opening and moving the magic book in the `MeetingArtifactBar`, the opening logic in the situation when `_statusBar == nullptr` is removed.

2021-02-21 09:37 UTC, ihhub commented
Hi @0UserName , could you please remove special characters from your branch name? I tried to clone it on Windows and Ubuntu and it does not work at all. I cannot merge pull requests without at least testing them.

2021-02-21 13:02 UTC, ihhub commented
> 
> 
> Hi @0UserName , could you please remove special characters from your branch name? I tried to clone it on Windows and Ubuntu and it does not work at all. I cannot merge pull requests without at least testing them.

Actually, ignore it. I found a way :)

2021-02-21 13:16 UTC, ihhub commented
@Branikolog , please test this change and leave your opinion. I think we haven't found a proper solution (behavior) for this issue.

2021-02-21 15:41 UTC, Branikolog commented
Enter spell book on single click is quite ok... The same to original behaviour.
Nevertheless, I found several issues with selection in this build: (I'm not sure, that the changes made are responsible for issues)
- Select any artifact and try to move it over a book. Book opens, but selection of the artifact is still visible.
![image](https://user-images.githubusercontent.com/55348946/108629738-6edcf400-7472-11eb-9a53-da390c88a842.png)
![image](https://user-images.githubusercontent.com/55348946/108629749-7ac8b600-7472-11eb-99a9-819d8d58a47e.png)
I think, when we select artifact and then click on the book, we should cancel the selection. And then we can click on the book once again to open it.
- The same happens to meeting screen.
When we select any artifact in hero's inventory and then click on the book, selection should be canceled. But it triggers popping text window.
![image](https://user-images.githubusercontent.com/55348946/108629894-2245e880-7473-11eb-8609-226c583d51ee.png)
![image](https://user-images.githubusercontent.com/55348946/108629905-2ffb6e00-7473-11eb-9a95-7f3d63b8b94b.png)
- We can select and move the book in one special case:
Select any artifact in meeting hero's inventory and then click on the book of the other hero. The selection of book is succeeded and we're able to move it
![image](https://user-images.githubusercontent.com/55348946/108630058-127ad400-7474-11eb-92c7-f944de51cc0d.png)
![image](https://user-images.githubusercontent.com/55348946/108630066-173f8800-7474-11eb-8a41-392cc2e0e05a.png)
![image](https://user-images.githubusercontent.com/55348946/108630076-1eff2c80-7474-11eb-978e-71a1662e6181.png)
Which is definitely shouldn't be allowed.

2021-02-26 00:19 UTC, 0UserName commented
Hi @Branikolog ,

> The same happens to meeting screen.
> When we select any artifact in hero's inventory and then click on the book, selection should be canceled. But it triggers popping text window.

To be honest, I don't really understand why selecting is a problem.  The selection of an item in the original game is retained even when clicking on the Magic Book (for `MeetingArtifactBar`) and the behavior of the original game should have formed the basis (if I understood the original ticket correctly). Now we have come to the conclusion that in **both** views the message "This item can't be traded." not required at all. Is it correct?

I made edits:

- The first remark has been corrected. Within the inventory, the selection is reset when the Magic Book is clicked, the message is not displayed.

- The second remark has been corrected. When trying to move Magic Book within the same hero, the message is not displayed, but it is displayed when trying to move items between heroes.

- The third point has been corrected. Fixed bug with moving Magic Book. 


But overall I'm not sure about resetting the selection in the `MeetingArtifactBar`.


https://user-images.githubusercontent.com/46850587/109236744-4726bc80-77e1-11eb-8996-1482d4841916.mp4

2021-02-26 11:26 UTC, Branikolog commented
Hi, @0UserName !

> Now we have come to the conclusion that in **both** views the message "This item can't be traded." not required at all. Is it correct?

No...
I'm sorry, for not being able to describe clear enough my message, as I sometimes have some difficulties with English. :)

But You've made everything absolutely correct!
On your video attached everything is perfect. 

Cancelling the selection of artifact, while trying to move it within one hero in hero meeting screen is obvious behaviour: while applying this action we try to move book, but not trade it to another hero. In previous implementation we watch popping message, that item can't be traded, but we simply made an attempt to move it. So, cancelling of the selection is quite common reaction to the case, where we want to make unallowed action.
So I also made a proposal to cancel the selection in single hero info window too, to keep the same interaction pattern within the whole game. Player should recognize the same reaction to his attempts to move a book within all windows in game.
Also, in original game we cannot move artifacts in hero info window, so we anyway need to implement some interaction patterns.

At the same time, when we try to move one artifact over a book of another hero, this considered as trading, and we should watch the popping message, that trading is unavailable. (Which you've already implemented in the video)

2021-02-28 19:22 UTC, 0UserName commented
So the PR is ready for review?

2021-03-02 15:43 UTC, ihhub requested changes
Hi @0UserName , I left multiple comments here. Could you please take a look?

2021-03-02 15:43 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +            bool mbNotSelected = isMagicBookSelected();
Here is a bit incorrect logic:
```
if ( isMagicBookSelected() ) {
    if ( _statusBar != nullptr && mbNotSelected ) {
         std::function<void( const std::string & )> statusCallback = [this]( const std::string & status ) { _statusBar->ShowMessage( status ); };
         _hero->OpenSpellBook( SpellBook::Filter::ALL, false, &statusCallback );
    }
    else {
        _hero->OpenSpellBook( SpellBook::Filter::ALL, false, nullptr );
    }
}
```

2021-03-02 15:43 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +        messageMagicBookAbortTrading();
Please paste the body of this method here as it's used only in one place - here.

2021-03-02 15:43 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +bool ArtifactsBar::isMagicBookSelected( Artifact & artifact )
Please rename this method as `isMagicBook` as this method does not check the selection of the artifact.

2021-03-02 15:43 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +            if ( !isMagicBookSelected( art ) && !isMagicBookSelected() ) {
Please combine these 2 if-conditions.

2021-03-05 21:32 UTC, 0UserName commented on src/fheroes2/resource/artifact.cpp
> +            bool mbNotSelected = isMagicBookSelected();
```
    else {
        _hero->OpenSpellBook( SpellBook::Filter::ALL, false, nullptr );
    }
```

I don't really understand what this part is for?

2021-03-05 21:35 UTC, 0UserName commented on src/fheroes2/resource/artifact.cpp
> +bool ArtifactsBar::isMagicBookSelected( Artifact & artifact )
With the context in mind, the method checks the selection of elements since the call occurs within the function responsible for clicks on elements. In any case, I was guided by this logic.

2021-03-06 14:53 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +bool ArtifactsBar::isMagicBookSelected( Artifact & artifact )
We should name methods or functions by what they do actually :) In this case other develop would call this method thinking thatit returns **true** if a Magic Book is really selected on UI which is not the case here.

2021-03-06 15:40 UTC, ihhub commented
Hi @0UserName , I'll check again and merge it tomorrow morning as now is a bit late for me. My apologies for delays.

2021-03-07 09:54 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +            bool mbNotSelected = isMagicBookSelected();
Yes, it leads to opening the magic book. We also have a status bar in Hero's screen which doesn't exist when a player open the book within World Map that's why we have to have the above check.

2021-03-07 09:58 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +        bool mbNotSelected = isMagicBookSelected();
Could you please make this variable `const` and rename to the opposite name as it should be? Right now the variable stands for the book being not selected while the value assigned to from `isMagicBookSelected` method is the opposite.

2021-03-07 09:58 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +            bool mbNotSelected = isMagicBookSelected();
Also opening the book within Meeting Hero dialog have the same issue: it doesn't have status bar.

2021-03-07 10:00 UTC, ihhub requested changes
Hi @0UserName , I left multiple comments as well answered for your question. Could you please take a look?

My apologies if this review becomes lengthy :(

2021-03-07 10:16 UTC, 0UserName commented on src/fheroes2/resource/artifact.cpp
> +            bool mbNotSelected = isMagicBookSelected();
Do you mean this?

![wm](https://user-images.githubusercontent.com/46850587/110236360-5d055180-7f46-11eb-8029-efafefeaef0e.PNG)

As far as I understand, `Spell SpellBook::Open` is responsible for opening the book in this dialog. And as I understand these code sections are not connected in any way.  If we add the `else` branch, then within the `MeetingArtifactBar` it will be possible to open magic book.

2021-03-07 11:11 UTC, 0UserName commented on src/fheroes2/resource/artifact.h
> +    bool isMagicBookSelected();
Partially done. Adding the attribute to `ArtifactsBar::isMagicBookSelected` entails the need to change the methods called internally.

2021-03-07 11:19 UTC, 0UserName commented on src/fheroes2/resource/artifact.cpp
> +            bool mbNotSelected = isMagicBookSelected();
> Also opening the book within Meeting Hero dialog have the same issue: it doesn't have status bar.

We shouldn't open the magic book in this dialog. From #761 

> While trading between heroes a message "This item can't be traded" should pop up when clicking over a book,

2021-03-08 12:52 UTC, Branikolog commented
@0UserName 
There should appear a window "This item can't be traded" if we make a single click over a book in hero meeting screen. (In a case none of artifacts is selected)

2021-03-08 14:25 UTC, 0UserName commented
> There should appear a window "This item can't be traded" if we make a single click over a book in hero meeting screen. (In a case none of artifacts is selected)

In `MeetingArtifactBar`, the window appears when trying to:

  - Transfer of an item, i.e. when two items are selected
  - Select the magic book when no other element is selected

2021-05-02 06:53 UTC, ihhub approved these changes

2021-05-02 07:06 UTC, merged

2021-05-02 07:06 UTC, ihhub commented
@0UserName , thank you so much for fixing this issue!