[Bugfix][2822] Sound off when minimized
ihhub/fheroes2 pull request #2830
Opened 2021-02-20 16:09 UTC by tau3

Hello!

This a _partial_ fix for #2822 (MacOS/SDL2/**SDL_Mixer**)

What was done:

1. SDL2 window event handling logic was moved into a separate function (`OnSdl2WindowEvent`) beause `LocalEvent::HandleEvents` is too big and complex;
2. Changed detected events types from window hidden/shown to focus lost/acuired;
3. Unfortunately, SDL_Mixer doesn't pause played music _immediately_. I didn't consider halting and restarting music on focus change because it would restart a song each time - probably not good. Instead, here is a workaround - store current volume, set to zero and restore when focus is aquired

2021-02-21 10:15 UTC, ihhub requested changes
Hi @tau3 , could you please take a look at given comment and also make changes for SDL 1 code as well? To remove code duplication we could introduce 2 private methods for pausing sounds and resuming them.

2021-02-21 10:15 UTC, ihhub commented on src/engine/localevent.h
> +    u16 _volume;
Please use `uint16_t` instead of **u16** and fix the build for SDL1.

2021-02-21 10:15 UTC, ihhub commented on src/engine/localevent.cpp
> +    , _volume( 0 )
Could we please be more explicit and define where this volume belongs to: sound or music?

2021-03-04 14:55 UTC, tau3 commented
Hi @ihhub!

Thank you for reviews, as usual.

SDL1 build fails on my Big Sur - i wouldn't be able to check if changes work fine, that's why SDL1-related logic is left untouched.
Btw, I can't see why SDL1 build is broken after my recent commit. Do some access rights required?

2021-03-05 00:13 UTC, ihhub commented
Hi @tau3 , to check what's wrong with the build please click on Details right from it. There you can check logs.
It fails due to unused variable.

2021-03-06 14:42 UTC, ihhub requested changes
Hi @tau3 , I left few comments about code structure. Could you please take a look?

2021-03-06 14:42 UTC, ihhub commented on src/engine/localevent.h
> +    void OnSdl2WindowEvent( const SDL_Event & event );
Please move this method into private section.

2021-03-06 14:42 UTC, ihhub commented on src/engine/localevent.cpp
> +    if ( Mixer::isValid() ) {
Please modify the code to have fast return:
```
if ( !Mixer::isValid() ) {
    return;
}
```
so the rest of code will not be shifted much.

2021-03-06 14:42 UTC, ihhub commented on src/engine/localevent.cpp
> +            loop_delay = 100;
This section of the code is duplicated at lines 1002-1007. Could we please create another private method, let's call it `void StopSounds()` where we put all the logic there?

2021-03-06 14:42 UTC, ihhub commented on src/engine/localevent.cpp
> +            loop_delay = 1;
This section of the code is duplicated at lines 1010-1017. Could we please create another private method, let's call it `void ResumeSounds()` where we put all the logic there?

I'm aware of music volume changes so could you please check if it affects SDL1?

2021-03-10 15:27 UTC, tau3 commented on src/engine/localevent.cpp
> +            loop_delay = 1;
music keeps playing with SDL1 ¯\_(ツ)_/¯

2021-03-10 15:40 UTC, tau3 commented on src/engine/localevent.cpp
> +            loop_delay = 1;
also `SDL_APPACTIVE` is only registered for `cmd + tab` switching. `cmd + h` doesn't work at all, and on mouse window switching or restoring from dock there are only a `SDL_JoyAxisEvent` events, so a workaround will be required in the future

2021-03-10 16:10 UTC, ihhub commented on src/engine/localevent.cpp
> +#endif
What if we execute this code on SDL 1? If there are no changes then we don't need if-def blocks around `_musicVolume` variable.

2021-03-11 12:13 UTC, tau3 commented on src/engine/localevent.cpp
> +#endif
i tried yesterday... this trick doesn't work on SDL1

2021-03-11 13:49 UTC, ihhub commented on src/engine/localevent.cpp
> +#endif
In this case can we just remove if-def if it does nothing?

2021-03-14 13:00 UTC, merged

2021-03-14 13:01 UTC, ihhub commented
@tau3 , thank you very much for this fix!