Fix Split-related issues, and Implement some new ones
ihhub/fheroes2 pull request #2850
Opened 2021-02-23 14:06 UTC by eos428

Solves
- #2823 -> Stacks remain highlighted when splitting, and the highlight will be gone after the splitting or otherwise
- #2824 -> Shift hotkey for splitting when clicking a stack similar to how ctrl and alt hotkeys
- #2679 -> Cancel highlighted troop after ctrl/alt/shift split hotkeys are used
- #2671 -> The `2` option for fast splitting in the split window. For cross-army splitting, this will bring all troops of the splitted stack into the other army

2021-02-23 14:16 UTC, Branikolog commented
Hello, @eos428 
I'm sorry for not updated #2671 issue.
I've recently created a discussion post, where fast split logics was described. https://github.com/ihhub/fheroes2/discussions/2821#discussioncomment-384156
Could you, please, check it?
We've canceled transferring of all troops to meeting army by fast split buttons. ( One stack should be lived in native army spot)

2021-02-23 14:34 UTC, eos428 commented
Hi @Branikolog 

If I understand correctly, all cases of fast split should still leave 1 part of the stack in the original army?

2021-02-23 14:44 UTC, Branikolog commented
@eos428 
Yes. Leaving one stack in basic army and place 1 - 5 stacks (according to pressed 2 - 6 fast buttons) to another army.

2021-02-23 15:01 UTC, eos428 commented
Done :)

2021-02-23 15:19 UTC, Branikolog commented
Nice! 
Thanks a lot, @eos428. :)

2021-02-24 13:53 UTC, ihhub requested changes
Hi @eos428 , I left multiple comments. Could you please take a look?

2021-02-24 13:53 UTC, ihhub commented on src/fheroes2/army/army_bar.cpp
> +                    remainingTroops++;
Please use pre-increment form.

2021-02-24 13:53 UTC, ihhub commented on src/fheroes2/army/army_bar.cpp
> +                int remainingTroops = troopFromCount / slots;
You could do like this to avoid extra check `const uint32_t remainingTroops = ( troopFromCount + slots - 1) / slots;`

Also please check variable types as here we're making an implicit conversion of unsigned to signed.

2021-02-24 13:53 UTC, ihhub commented on src/fheroes2/army/army_bar.cpp
> +                    remainingTroops++;
Based on the above comment we won't need this code.

2021-02-24 13:53 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +        sprites[i] = fheroes2::AGG::GetICN( ICN::REQUESTS, spriteIconIdx++ );
Please put variable increment on a separate line and use pre-increment form.

2021-02-24 13:53 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +    float spriteWidthStart = -0.5f * ( freeSlots - 1 );
Please make this variable `const`.

2021-02-24 13:53 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +    int deltaXStart = ( freeSlots - 2 ) * -5;
Pleae make this variable `const`.

2021-02-24 13:53 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
>      fheroes2::Display & display = fheroes2::Display::instance();
Could we please check add an assert to check that the number of freeSlots is always bigger than 0 otherwise the code below will stuck forever: `freeSlots - 1`?

2021-02-24 13:53 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +        const int spriteWidth = static_cast<int>( sprites[i].width() * ( i + spriteWidthStart ) );
Can we do like this instead
```
const int32_t spriteWidth = sprites[i].width();
const int32_t offset = spriteWidth * ( i -  freeSlots / 2 ) + spriteWidth / 2;
vrts[i] = fheroes2::Rect( center + offset + deltaXStart + i * deltaX, pos.y + 95, spriteWidth, sprites[i].height() );
```
?
Then we won't need float calcualtions. What do you think?

2021-02-24 15:07 UTC, eos428 commented on src/fheroes2/dialog/dialog_selectcount.cpp
>      fheroes2::Display & display = fheroes2::Display::instance();
Thanks, I like this solution. To be fair mine's a bit crude and is more in the line of "gets the job done" :P

2021-02-26 14:34 UTC, ihhub requested changes
Hi @eos428 , I left few more comments. Could you please take a look?

2021-02-26 14:34 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +        vrts[i] = fheroes2::Rect( center + offset + deltaXStart + i * deltaX, pos.y + 95, sprites[i].width(), sprites[i].height() );
Please use `spriteWidth` instead of `sprites[i].width()` as we already cached it.

2021-02-26 14:34 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +    std::vector<fheroes2::Rect> vrts( freeSlots );
Here we allocate a container of size `freeSlots` but we modify only `freeSlots - 1` elements.

2021-02-26 14:34 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +    if ( !sprites.empty() ) {
This condition is always true according to line 348.

2021-02-26 15:25 UTC, Branikolog commented
Hi, @eos428 !
I've checked your recent build.
Here are some issues:
We're trying to split skeletons over skeletons:
![image](https://user-images.githubusercontent.com/55348946/109317855-38cab600-785e-11eb-870e-7e341b5d1964.png)
![image](https://user-images.githubusercontent.com/55348946/109317958-5566ee00-785e-11eb-8043-467abd07162e.png)
When we choose fast split buttons, the target stack is not considered and the native stack is being splitted over only empty slots:
![image](https://user-images.githubusercontent.com/55348946/109318085-792a3400-785e-11eb-80c4-cdcd67f87655.png)
![image](https://user-images.githubusercontent.com/55348946/109318108-80e9d880-785e-11eb-83c5-6e562c924345.png)

Also, are we going to implement some other features, from the discussion thread, where complete logic is described?
I mean pre-selected [2] button on default splitting and "1 troop to move" on default splitting dialog over the same type of stack.

2021-02-27 14:04 UTC, Branikolog commented
Hi, @eos428 !
Pre-selection of [2] button works well now!
But I nevertheless have some comments:
Here we're going to split peasants into two stacks choosing the right free one.
![image](https://user-images.githubusercontent.com/55348946/109389070-ccae8780-791b-11eb-95b9-c4f612a9ce26.png)
When we press ok a new stacks appears in the wrong place:
![image](https://user-images.githubusercontent.com/55348946/109389088-e223b180-791b-11eb-9ae1-084d551bf120.png)
For splitting into two stacks we should place new stack at the stack, we've made right click on.
It should have been worked in this way:
![image](https://user-images.githubusercontent.com/55348946/109389141-37f85980-791c-11eb-9824-56ce4f0a6da5.png)
The same should work for splitting over the same type of stack:
![image](https://user-images.githubusercontent.com/55348946/109389202-90c7f200-791c-11eb-8db0-e4be29af7b86.png)
Here we split bottom peasants over the upper stack and want them be equalized.
We press [2] button and watch the upper stack moved:
![image](https://user-images.githubusercontent.com/55348946/109389220-ab01d000-791c-11eb-8f65-bdcaabf049af.png)
The result I expected is:
![image](https://user-images.githubusercontent.com/55348946/109389232-be14a000-791c-11eb-961f-787784ba4cf1.png)

Also, in a https://github.com/ihhub/fheroes2/discussions/2821#discussioncomment-384156 we've decided to set one creature as the default creature splitting quantity on the same type stack.
Your current implementation offers to equalize both stacks on a default:
(on a screenshot we're splitting 28 peasants over 10)
![image](https://user-images.githubusercontent.com/55348946/109389442-aa1d6e00-791d-11eb-8ce8-82e5c6646b36.png)
When we split one stack over another of the same type we should set the default quantity of 1 creature and set the pre-selected [2] button off:
![image](https://user-images.githubusercontent.com/55348946/109389449-b7d2f380-791d-11eb-8c61-447f7bf0b139.png)

2021-02-28 04:16 UTC, eos428 commented
Hi @Branikolog and @ihhub, I have implemented these logics based on Bran's latest comments:

- During any type of fast split, the original troop's position stays
- During fast split to the same stack, the target troop's position stays
- During fast split to an empty stack, the selected empty stack will contain one of the splitted chunks
- Turn off default fast-split when splitting to the same troop type
- Default split count to 1 when splitting to the same troop type

Let me know if there's anything missing from the required logics :)

2021-03-01 11:53 UTC, Branikolog commented
@eos428 
Great work!
Could you, please, fix one more little thing, and everything will be ok!
Currently, when we split into more than two stacks, 3rd, 4th etc troops are appear in the left free slot:
(Here we press the right free slot, while trying to split Hydras)
![image](https://user-images.githubusercontent.com/55348946/109493340-6487af00-7a9d-11eb-9834-749e4e8b47e1.png)
And the third troop appears in the oppostie side of the garrison:
![image](https://user-images.githubusercontent.com/55348946/109493402-7ec18d00-7a9d-11eb-98bb-2b16e734b0e9.png)
Which looks a bit weird....
Can we make all the splitted troops appear nearby the slot we're clicking?
I expect Hydras appear close to the slot I used to point while splitting:
![image](https://user-images.githubusercontent.com/55348946/109493672-e2e45100-7a9d-11eb-9566-2c2fdb027eb2.png)

2021-03-01 13:38 UTC, eos428 commented
@Branikolog done, the remaining troop chunks should be closer to the selected slot now. Also note that with the current logic, we'd try to create the chunks on the right side of the selected slot before going to the left.

2021-03-01 14:14 UTC, Branikolog commented
@eos428 
Excellent! No matter, what side would be prioritized. Right or left...
Thanks for making so many corrections! No it should work perfect.

2021-03-01 15:33 UTC, Branikolog commented
@eos428 
Hi. 
Something works wrong.
While splitting troops between armies, a certain number of creatures run away...
(here we splitting 38 Rogues over 1 Rogue in castle garrison)
![image](https://user-images.githubusercontent.com/55348946/109519613-72006180-7abc-11eb-8c06-6a492eb61671.png)
![image](https://user-images.githubusercontent.com/55348946/109519657-7c226000-7abc-11eb-8222-d07f349ce036.png)

2021-03-01 15:35 UTC, ihhub requested changes
Hi @eos428 , I left few comments. Could you please take a look?

2021-03-01 15:35 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +    auto TryCreateTroopChunk = [&]( iterator it ) {
Please pass only `remainingSlots` in capture list. It is a good practice not to capture everything.

Also please pass by const reference `Troop` instead of iterator.

2021-03-01 15:35 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +    for ( iterator it = selectedSlotIterator - 1; it != begin(); --it ) {
What if the selected slot is at `begin()`?

2021-03-01 15:35 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +    for ( iterator it = selectedSlotIterator + 1; it != end(); ++it ) {
Is there a case when selected slot is equal to `end()`?

2021-03-01 15:35 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +    const int deltaXStart = ( freeSlots - 2 ) * -5;
Please static_cast `freeSlots` before anything as `freeSlots - 2` might not guarantee to be **int**. In case of freeSlots == 1 it might lead to unexpected results.

2021-03-01 15:35 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +                --remainingCount;
Why do we decrease twice here?

2021-03-02 02:47 UTC, eos428 commented on src/fheroes2/army/army.cpp
> +    for ( iterator it = selectedSlotIterator - 1; it != begin(); --it ) {
this one is likely the issue found in Bran's screenshot. begin() is still eligible

2021-03-02 02:48 UTC, eos428 commented on src/fheroes2/army/army.cpp
> +    for ( iterator it = selectedSlotIterator - 1; it != begin(); --it ) {
But in case the selected slot is begin(), then all the remaining chunks will be added to the right side of the selected slot.

2021-03-02 02:59 UTC, eos428 commented on src/fheroes2/army/army.cpp
> +    for ( iterator it = selectedSlotIterator + 1; it != end(); ++it ) {
Maybe if selectedSlot is not part of the army in question? But either way, with the way the for loop is constructed it souldn't be an issue even if selectedSlot is equal to end()

2021-03-02 03:00 UTC, eos428 commented on src/fheroes2/army/army.cpp
> +    for ( iterator it = selectedSlotIterator - 1; it != begin(); --it ) {
In any case, I will change this to use reverse_iterator with it != rend() instead to fix the issue highlighted by Bran

2021-03-02 03:01 UTC, eos428 commented on src/fheroes2/army/army.cpp
> +                --remainingCount;
Those are 2 different things. 

Remaining slots is the number of free slots to distribute to, 
Remaining count is the modulo of the division, (say 35 % 3 will make this 2)

2021-03-02 03:07 UTC, eos428 commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +    const int deltaXStart = ( freeSlots - 2 ) * -5;
Come to think of it, these variables (aside from `vrts`) are not used at all if freeSlots < 2... We do have stuff we'd draw only if freeSlots > 1 so I think we should place them inside that if clause instead. Includes the static_cast change proposed of course.

What do you think?

2021-03-02 13:55 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +                --remainingCount;
Ah, sorry, I misread.

2021-03-02 15:25 UTC, ihhub approved these changes

2021-03-02 15:35 UTC, merged

2021-03-02 15:35 UTC, ihhub commented
@eos428 , a huge thanks for fiing all this logic!