Fix object's visited info #293 + fix grammar
ihhub/fheroes2 pull request #2867
Opened 2021-02-25 22:34 UTC by Sergeenko

![Untitled](https://user-images.githubusercontent.com/27135466/109228168-bc829500-77c1-11eb-883e-298f4fe611a1.png)

2021-02-26 14:03 UTC, ihhub requested changes
Hi @Sergeenko, everything look good except one place where we would like to reduce code duplication. Could you please take a look?

2021-02-26 14:03 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +    if ( showVisitedOption ) {
Since we modified this function could we please remove the function above and for its calls use this function passing `true` for the thrid input argument? In this case we will reduce code duplication.

2021-02-26 14:09 UTC, Sergeenko commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +    if ( showVisitedOption ) {
Hi @ihhub, makes sense. I will do.

2021-02-26 14:10 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +    if ( showVisitedOption ) {
Great! Thank you!

2021-02-28 02:47 UTC, ihhub approved these changes

2021-02-28 02:48 UTC, merged

2021-02-28 02:48 UTC, ihhub commented
@Sergeenko , thank you so much for your contribution to the project!