Fix boat drawing issue
ihhub/fheroes2 pull request #2883
Opened 2021-02-28 14:55 UTC by vasilenkoalexey

fix #2720
fix #2434
fix #2179

2021-03-09 00:08 UTC, ihhub requested changes
Hi @vasilenkoalexey , I left few comments here. Could you please take a look?

2021-03-09 00:08 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +    MapsIndexes drawList;
Please create 2 separate variables: one for heroes and one for boat so that in the later loop we don't need to check object type.

2021-03-09 00:08 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.cpp
> +    if ( visibleTileROI & mp ) {
Please use early function return logic:
```
if ( !( visibleTileROI & mp ) ) {
    return;
}
```

2021-03-09 00:08 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.h
> +        void RedrawMonster( fheroes2::Image & dst, const Rect & visibleTileROI, const Interface::GameArea & area ) const;
What there a big reason to rename `gameArea` into `area`? We still have other methods using `gameArea`.

2021-03-09 09:39 UTC, vasilenkoalexey commented on src/fheroes2/gui/interface_gamearea.cpp
> +    MapsIndexes drawList;
It is important to draw boats and heroes in the order in which we found them during top-left to bottom-right loop. Otherwise, we may incorrectly draw boat and hero one on top of the other.

2021-03-09 09:47 UTC, vasilenkoalexey commented on src/fheroes2/maps/maps_tiles.cpp
> +    if ( visibleTileROI & mp ) {
Done. Moreover,  I think we can replce it by assertion.

2021-03-09 09:50 UTC, vasilenkoalexey commented on src/fheroes2/maps/maps_tiles.h
> +        void RedrawMonster( fheroes2::Image & dst, const Rect & visibleTileROI, const Interface::GameArea & area ) const;
Renamed completely. Better when an instance of the same class has the same name.

2021-03-09 14:43 UTC, ihhub commented
Hi @vasilenkoalexey , we have ab issue with drawing other objects (check lighthouse):
![image](https://user-images.githubusercontent.com/19829520/110487703-ccd33200-8128-11eb-85f5-353315f338bb.png)

2021-03-10 22:29 UTC, vasilenkoalexey commented
> Hi @vasilenkoalexey , we have ab issue with drawing other objects (check lighthouse):

Should be fixed now

2021-03-14 14:48 UTC, ihhub requested changes
Hi @vasilenkoalexey , I left just one comment in regards to performance. Could you please take a look?

2021-03-14 14:48 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.cpp
> +    RedrawTop( dst, visibleTileROI, area );
We are calling `RedrawTop` twice. We shouldn't do this. We could check the existance of boat at particular tile in `if ( drawTop ) {` loop and do not draw it.

2021-03-17 21:03 UTC, vasilenkoalexey commented on src/fheroes2/maps/maps_tiles.cpp
> +    RedrawTop( dst, visibleTileROI, area );
Yes, you are right. But we have same problem right now for hero. I can fix both in separate pr or put commit to this pr.

2021-03-18 01:22 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.cpp
> +    RedrawTop( dst, visibleTileROI, area );
If the fix is not that big let's put it here please.

2021-03-19 10:20 UTC, vasilenkoalexey commented on src/fheroes2/maps/maps_tiles.cpp
> +    RedrawTop( dst, visibleTileROI, area );
Done

2021-03-22 15:11 UTC, ihhub commented
Hi @Branikolog , could you please test these changes?

2021-03-22 15:15 UTC, Branikolog commented
@ihhub 
Sure! Give me a few hours.

2021-03-22 19:25 UTC, Branikolog commented
Everything looks fine.
My only concern is...
Shouldn't the boat be drawn under the object if they are on the same line?
![image](https://user-images.githubusercontent.com/55348946/112046481-242bc600-8b5d-11eb-82f0-f74d57e5e12f.png)
Here I expect boat be drawn under Witch Hut.
Also, hero is drawn under the boat here...
Or should we consider this as another issue?

2021-03-23 12:42 UTC, vasilenkoalexey commented
I fixed problem when hero is drawn under the boat. But boat and Witch Hut is different issue #2186

2021-03-25 13:55 UTC, merged

2021-03-25 13:55 UTC, ihhub commented
@vasilenkoalexey , a huge thanks for fixing these issues in one shot!