Exit castle during battle
ihhub/fheroes2 pull request #2885
Opened 2021-02-28 17:07 UTC by vasilenkoalexey

fix #649

2021-03-01 15:40 UTC, ihhub commented
Hi @vasilenkoalexey , the fix does nothing :)

2021-03-01 16:03 UTC, vasilenkoalexey commented
> Hi @vasilenkoalexey , the fix does nothing :)

You right, my bad... But it pr allow to exit from castle by [X] button...

2021-03-03 13:03 UTC, ihhub requested changes

2021-03-03 13:03 UTC, ihhub commented on src/fheroes2/castle/castle_dialog.cpp
> +    while ( le.HandleEvents( true, true ) ) {
This change just closes castle's window while the issue state to close the game showing a confirmation dialog for this.

2021-03-03 15:22 UTC, vasilenkoalexey commented
So, I think to completely fix # 649 we need a more complex solution

2021-03-03 15:22 UTC, closed without merging