Make MouseRelease* events one-shot to fix excessive FPS issue
ihhub/fheroes2 pull request #2895
Opened 2021-03-02 14:05 UTC by oleg-derevenetz

Related to #2842

At the moment, MouseRelease* events (used by drag&drop logic in ArmyBar) are not one-shot events, this leads to excessive FPS issues after clicking on creature stack in this bar. In this patch I suggest the somewhat naive approach to this issue. Also I'm not sure that these events should be one-shot by design (and some other part of the code does not count on the fact that they are NOT one-shot events), so may be some different, more complex approach is needed here.

2021-03-02 21:04 UTC, oleg-derevenetz commented
Also, I'm not sure, why CLICK_XXX being reset in functions LocalEvent::MouseClick*(), like [here](https://github.com/ihhub/fheroes2/blob/f4e8e5a84149596d4cd6556238cdf2e6e60d3254/src/engine/localevent.cpp#L1480). What if those functions will be called more than once in event handling chain? Shouldn't we reset CLICK_XXX modes in HandleEvents() only?

2021-03-03 14:21 UTC, oleg-derevenetz commented
Should also fix #2397, #2357 if they haven't already been fixed by #2485.

2021-03-04 13:36 UTC, ihhub commented
@Branikolog , I'll provide you with release for this pull request. Please test it extensively.

2021-03-05 14:57 UTC, ihhub requested changes
Hi @oleg-derevenetz, I left multiple comments, mostly on code optimization. Also there is a bug:
In this window I select Phoenixes
![image](https://user-images.githubusercontent.com/19829520/110132188-df3a2c80-7e05-11eb-8881-08b9b62b6b7c.png)
then right click on empty space to open troop split window:
![image](https://user-images.githubusercontent.com/19829520/110132267-f416c000-7e05-11eb-86dd-e97e4e0b6fb8.png)
after this I press cancel button (see that it's just around secondary skill area);
![image](https://user-images.githubusercontent.com/19829520/110132364-0c86da80-7e06-11eb-8d73-186ce2a1cd31.png)
immediately a new window pops up.

2021-03-05 14:57 UTC, ihhub commented on src/engine/localevent.cpp
> +    if ( MouseReleaseRight() && ( rt & mouse_pr ) && ( rt & mouse_rr ) ) {
Could we please modify this code into `return MouseReleaseRight() && ( rt & mouse_pr ) && ( rt & mouse_rr );`?

2021-03-05 14:57 UTC, ihhub commented on src/engine/localevent.cpp
> +    if ( MouseReleaseRight() ) {
Could we please modify this code into `return MouseReleaseRight();`?

2021-03-05 14:57 UTC, ihhub commented on src/engine/localevent.cpp
> +    if ( MouseReleaseMiddle() && ( rt & mouse_pm ) && ( rt & mouse_rm ) ) {
Could we please modify this code into `return MouseReleaseMiddle() && ( rt & mouse_pm ) && ( rt & mouse_rm );`?

2021-03-05 14:57 UTC, ihhub commented on src/engine/localevent.cpp
> +    if ( MouseReleaseMiddle() ) {
Could we please modify this code into `return MouseReleaseMiddle();`?

2021-03-05 14:57 UTC, ihhub commented on src/engine/localevent.cpp
> +    if ( MouseReleaseLeft() && ( rt & mouse_pl ) && ( rt & mouse_rl ) ) {
Could we please modify this code into `return MouseReleaseLeft() && ( rt & mouse_pl ) && ( rt & mouse_rl );?

2021-03-05 14:57 UTC, ihhub commented on src/engine/localevent.cpp
> +    if ( MouseReleaseLeft() ) {
Could we please modify this code into `return MouseReleaseLeft();`?

2021-03-05 15:26 UTC, oleg-derevenetz commented
Well, now I suspect that all those CLICK_XXX in previous version of this code were being reset to avoid bugs like this. Due to singleton nature of LocalEvent, even if click was already handled in dialog event loop, it may still be handled in parent window event loop after closing the dialog. Looks like I'll have to reset MOUSE_RELEASED in a similar way...

2021-03-05 15:49 UTC, ihhub commented
> Well, now I suspect that all those CLICK_XXX in previous version of this code were being reset to avoid bugs like this. Due to singleton nature of LocalEvent, even if click was already handled in dialog event loop, it may still be handled in parent window event loop after closing the dialog, but before calling HandleEvents(). Looks like I'll have to reset MOUSE_RELEASED in a similar way...

Sorry about that. This implementation was done before us so we have to struggle with this. A proper event handling shouldn't even involve loops...

2021-03-05 16:13 UTC, oleg-derevenetz commented
Event loop isn't a bad idea per se (remember WinAPI), but not in combination with singleton event class... :)

2021-03-05 19:06 UTC, oleg-derevenetz commented
Well, it looks like I have to return to my original approach and just make MouseRelease* events non-recurring, CLICK_XXX flags are here to stay. This should fix the original issue with excessive FPS and shouldn't break anything (however, extensive tests are desirable).

2021-03-05 19:57 UTC, oleg-derevenetz commented
Let's try to solve the issue with "leaking" clicks by adding separate MOUSE_CLICKED flag that will be cleared right after click was checked (just like with CLICK_XXX flags before). Thus, click events will be "separated" from mouse release events. Extensive tests are still desirable.

2021-03-06 14:50 UTC, merged

2021-03-06 14:51 UTC, ihhub commented
@oleg-derevenetz , a bunch of thanks to tackling this problem!

2021-03-06 14:53 UTC, oleg-derevenetz commented
@ihhub Thanks! I will keep an eye on related issues to make sure I didn't break anything.