Do not allow the visiting hero to learn Library spells if the Library hasn't been built yet
ihhub/fheroes2 pull request #2898
Opened 2021-03-05 13:07 UTC by oleg-derevenetz

fix 2743

2021-03-05 15:28 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left just few small corrections. Could you please take a look?

2021-03-05 15:28 UTC, ihhub commented on src/fheroes2/castle/mageguild.cpp
> +    all.Append( library );
This line does nothing as library is empty at this point of execution. Could you please remove this line?

2021-03-05 15:28 UTC, ihhub commented on src/fheroes2/castle/mageguild.cpp
> +            if ( spell != Spell::NONE ) {
A small code correction:
```
if ( spell == Spell::NONE ) {
    continue;
}
```
so the code below will be slightly easier to read.

2021-03-05 15:28 UTC, ihhub commented on src/fheroes2/castle/mageguild.cpp
> +    all.Append( library );
We could just simplify this code into `SpellStorage all( general );`

2021-03-05 15:35 UTC, oleg-derevenetz commented on src/fheroes2/castle/mageguild.cpp
> +            if ( spell != Spell::NONE ) {
I'm not sure is this check even necessary, because SpellStorage::Append() have a built-in protection against Spell::NONE. But this check was there before, so I decided to left it. I'll refactor this.

2021-03-05 15:43 UTC, ihhub commented on src/fheroes2/castle/mageguild.cpp
> +            if ( spell != Spell::NONE ) {
We can remove this check then but with this check the code will be a bit faster (no need to put function calls on stack). We have a plenty of old code which needs some cleanup as well :)

2021-03-05 18:48 UTC, oleg-derevenetz commented
@ihhub I made the requested changes, could you please take a look when will you have time?

2021-03-06 03:33 UTC, merged

2021-03-06 03:33 UTC, ihhub commented
@oleg-derevenetz , a bunch of thanks for fixing this issue!