Implement Campaign Awards
ihhub/fheroes2 pull request #2926
Opened 2021-03-09 13:43 UTC by eos428

Solves #2670

I am marking this as a draft PR since it's obviously not finished, but please review it nonetheless.

Working awards so far:
- Resource bonus
- Creature bane/alliance
- Get artifact
- Get spell (assumed to work since get artifact works)

Remove enemy hero should work, but untested.

Not implemented yet:
- Carry over forces (a freak situation, the only one that requires something saved beforehand)
- Varying award obtain condition. Seems to be applied only to Hero defeated bonuses afaik
- Remove campaign awards. Needed for betrayals and in PoL, replacing the Anduran artifacts with the Battle Robe.

2021-03-14 16:15 UTC, ihhub requested changes
Hi @eos428 , I left multiple comments here. Would you mind to take a look?

2021-03-14 16:15 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +            TYPE_CREATURE_BANE, // eg: dwarf bane
Could we call it `TYPE_CREATURE_CURSE`? I'm afraid that non-native English speakers might not understand this.

2021-03-14 16:15 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +                Monster monster = Monster( campaignAwards[i]._subType );
Please make it `const`.

2021-03-14 16:15 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +            if ( isAlliance || isBane ) {
We could do like this:
```
if ( !isAlliance && !isBane ) {
    continue;
}
...
```

2021-03-14 16:15 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +    // check for creature alliance/bane
This code needs more explanation as it is not easy to read without extra knowledge. Could you please add some comments explaining roughly why we have this code?

2021-03-14 16:15 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +        enum AwardType
Please try to make it `enum class AwardType : int`. In this case a compiler will always demand the presence of all items in the enumeration for switch-case code.

2021-03-14 16:15 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.h
> +        CampaignAwardData( int id, uint32_t type, uint32_t subType, uint32_t amount, int startScenarioID, std::string customName = "" );
Please pass `std::string` by const reference.

2021-03-14 16:15 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.h
> +        void AddObtainableCampaignAward( const CampaignAwardData & obtainableAward );
This method doesn't have implementation.

2021-03-14 16:15 UTC, ihhub commented on src/fheroes2/game/game.h
> +    const std::vector<Campaign::CampaignAwardData> GetObtainedCampaignAwards( const Campaign::CampaignSaveData & saveData );
Please remove first `const` at this line.

2021-03-14 16:15 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +            Text award( obtainedAwards[i].ToString(), Font::BIG );
Please move this object out of a loop and use `Set` method to assing a text.

2021-03-14 16:15 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +                for ( uint32_t j = 0; j < carryOverTroops.size(); ++j )
Could we please use `troopId` instead of `j` to have more readable code?

2021-03-14 16:15 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +    const auto scenarioDatas = GetCampaignData( saveData.getCampaignID() ).getAllScenarios();
This variable is not used anywhere.

2021-03-14 16:15 UTC, ihhub commented on src/fheroes2/campaign/campaign_savedata.cpp
> +        if ( Game::GetLoadVersion() < FORMAT_VERSION_092_RELEASE ) {
Here we need to check version when we added this type of data as well. Was it since the beginning?

2021-03-14 16:15 UTC, ihhub commented on src/fheroes2/campaign/campaign_savedata.cpp
> +            std::vector<std::string> temp_OldObtainedCampaignAwards;
Please use `camelCase` variable naming.

2021-03-15 11:09 UTC, eos428 commented on src/fheroes2/campaign/campaign_savedata.cpp
> +        if ( Game::GetLoadVersion() < FORMAT_VERSION_092_RELEASE ) {
Yes, it was there since the beginning. So probably 0.9.0?

2021-03-15 11:23 UTC, eos428 commented on src/fheroes2/army/army.cpp
> +                Monster monster = Monster( campaignAwards[i]._subType );
If you are referring to the `monster`, we cannot do that with the current implementation since we are looking to cycle through the creature's upgrades, which edits the value of `monster` here.

2021-03-19 07:47 UTC, eos428 commented
Sorry I deleted this branch on accident when I was looking through old branches to delete.

Reopened

2021-03-22 15:01 UTC, ihhub requested changes
Hi @eos428 , I left multiple comments. Would you mind to take a look?

2021-03-23 14:09 UTC, eos428 commented on src/fheroes2/campaign/campaign_data.h
> +        CampaignAwardData( int id, uint32_t type, uint32_t subType, std::string customName );
https://github.com/ihhub/fheroes2/blob/07691844273c849dc480d421718c31f0a011eaf0/src/fheroes2/campaign/campaign_data.cpp

This was the earliest version of campaign save data that got in `master`. I think this is already in 0.9.0 but wasn't prominent because campaign continuation wasn't implemented yet at that point. A save file from a version even earlier than that wouldn't even get to this >> operator but I could be wrong.

2021-03-28 16:03 UTC, ihhub requested changes
Hi @eos428 , I left multiple comments here. Could you please take a look?

2021-03-28 16:03 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +        for ( uint32_t i = 0; i < awards.size(); ++i ) {
Please use `size_t` type here.

2021-03-28 16:03 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +                    for ( uint32_t j = 0; j < heroes.size(); ++j ) {
Please use `size_t` type here.

2021-03-28 16:03 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +    for ( uint32_t i = 0; i < obtainableAwards.size(); ++i ) {
Please use `size_t` type here.

2021-03-28 16:03 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +        experience = GetExperienceFromLevel( 4 );
How about a normal scenario? Does this hero have the same level?

2021-03-28 16:03 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +            for ( uint32_t i = 0; i < resourceBonuses.size(); ++i )
Please use `size_t` type here.

2021-03-28 16:03 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +            for ( uint32_t i = 0; i < campaignAwards.size(); ++i ) {
Please use `size_t` type here.

2021-03-28 16:03 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +        for ( uint32_t i = 0; i < obtainedAwards.size(); ++i ) {
Please use `size_t` type here.

2021-03-29 12:41 UTC, eos428 commented on src/fheroes2/campaign/campaign_data.cpp
> +            objectName = Heroes( _subType, 0 ).GetName() + std::string( " defeated" );
Yes, we shouldn't need the variable assignment here.

2021-03-29 12:44 UTC, eos428 commented on src/fheroes2/heroes/heroes.cpp
> +        experience = GetExperienceFromLevel( 4 );
Afaik Sister Eliza is a unique hero and is thus unselectable in normal scenarios.

2021-03-29 15:08 UTC, ihhub commented
Hi @Branikolog , could you please test these changes?

2021-04-02 15:50 UTC, ihhub requested changes
Hi @eos428 , there are multiple comments left. Could you please take a look?

2021-04-02 15:50 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +    // check for creature alliance/bane campaign awards, campaign only and of course, for human players
Tiny correction: please start this comment with a capital C.

2021-04-02 15:50 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +                resourceBonuses.emplace_back( Funds( campaignAwards[i]._subType, campaignAwards[i]._amount ) );
Please remove `Funds(` as emplace_back construct an object in-place.

2021-04-02 15:50 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +                AddFundsResource( resourceBonuses[i] );
Why can't we directly call `AddFundsResource` in the loop before?

2021-04-02 15:50 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +    CampaignAwardData::CampaignAwardData( int id, uint32_t type, uint32_t subType, uint32_t amount, int startScenarioID, const std::string & customName /*= ""*/ )
Please remove the comment as it's invalid.

2021-04-02 15:50 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +            return Heroes( _subType, 0 ).GetName() + std::string( " defeated" );
This block needs translation support. Please use `_( )` to return a translated text for std::string additions.

2021-04-02 15:50 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +            obtainableAwards.emplace_back( 1, Campaign::CampaignAwardData::TYPE_HIREABLE_HERO, Heroes::ELIZA, 0, 0, "Sorceress Guild" );
Please put `"Sorceress Guild"` into translation call `_(   )`.

2021-04-02 15:50 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +            obtainableAwards.emplace_back( 1, Campaign::CampaignAwardData::TYPE_HIREABLE_HERO, Heroes::BAX, 0, 0, "Necromancer Guild" );
Please put `"Necromancer Guild"` into translation call `_(   )`.

2021-04-02 15:50 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +            obtainableAwards.emplace_back( 4, Campaign::CampaignAwardData::TYPE_CREATURE_ALLIANCE, Monster::GREEN_DRAGON, "Dragon Alliance" );
Please put `"Dragon Alliance"` into translation call `_(   )`.

2021-04-02 15:50 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +    int forceJoinType = JOIN_NONE;
This variable and the lines 1508-1509 should go under the below if-condition.

2021-04-02 15:50 UTC, ihhub commented on src/fheroes2/game/game.h
> +    std::vector<Campaign::CampaignAwardData> GetObtainedCampaignAwards( const Campaign::CampaignSaveData & saveData );
I think this is not a good place for campaign function. Should we put it in `campaign_savedata` files?

2021-04-02 15:50 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +            recruits.SetHero1( world.GetFreemanHeroesSpecial( obtainedAwards[i]._subType ) );
What if we dont have such award? Should we fall to
```
const bool preferNative = recruits.GetID1() == Heroes::UNKNOWN && recruits.GetID2() == Heroes::UNKNOWN;
recruits.SetHero1( world.GetFreemanHeroes( preferNative ? GetRace() : Race::NONE ) );
```
code?

2021-04-03 01:56 UTC, eos428 commented on src/fheroes2/kingdom/kingdom.cpp
> +                AddFundsResource( resourceBonuses[i] );
you are right... dunno what I was thinking here heh

2021-04-03 02:10 UTC, eos428 commented on src/fheroes2/kingdom/kingdom.cpp
> +            recruits.SetHero1( world.GetFreemanHeroesSpecial( obtainedAwards[i]._subType ) );
I think at the moment it might fall to the `GetRecruits()` if case where it will update an unknown hero to a new one but you're right. This might be a problem if we don't have such an award in the campaign.

2021-04-03 02:15 UTC, eos428 commented on src/fheroes2/game/game.h
> +    std::vector<Campaign::CampaignAwardData> GetObtainedCampaignAwards( const Campaign::CampaignSaveData & saveData );
And in that regard, should we also move `getCampaignAwardData` to `campaign_savedata` too? For at least two reasons:
- Those are local functions
- Referring to a function in `game.h` would cause cyclic dependncy, but CMIIW on this one

2021-04-03 15:12 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +                AddFundsResource( resourceBonuses[i] );
It's okay. We aren't (yet) building rockets so :)

2021-04-03 16:01 UTC, ihhub requested changes
Hi @eos428 , I left few more comments. Could you please take a look?

2021-04-03 16:01 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +        const int yOffset = obtainedAwards.size() > 3 ? 16 : 22;
As discussed in Discord we could have even 7 awards. In this case should we show first 3 and then forth line would be `and more` (translated of course)?

2021-04-04 02:31 UTC, eos428 commented on src/fheroes2/game/game_campaign.cpp
> +        const int yOffset = obtainedAwards.size() > 3 ? 16 : 22;
That could work I suppose. In case we have four awards only we should show the fourth award, but otherwise we'll show `and more` instead.

2021-04-07 16:05 UTC, ihhub requested changes
Hi @eos428 , I left just 2 comments. Could you please also rebase from master branch? We're waiting @Branikolog to finish his testings before merging this pull request.

2021-04-07 16:05 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +                    const KingdomHeroes heroes = kingdom.GetHeroes();
Please use here const reference as `GetHeroes()` returns a reference.

2021-04-07 16:05 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +        if ( isControlHuman() && conf.GameType() & Game::TYPE_CAMPAIGN ) {
Since `conf` is used in one place only please use a direct call: `Settings::Get().GameType()` so we do not need to create an extra variable for this.

2021-04-17 09:53 UTC, ihhub commented
Hi @eos428 , could you please rebase this branch from master?

2021-04-17 14:15 UTC, eos428 commented
@ihhub done :)

2021-04-19 14:00 UTC, ihhub reviewed
Hi @eos428 , I left few more comments. Could you please take a look?

2021-04-25 14:41 UTC, ihhub commented
Hi @eos428 , could you please fix compilation errors?
```
D:\a\fheroes2\fheroes2\src\fheroes2\campaign\campaign_data.cpp(257): error C4715: 'Campaign::CampaignAwardData::ToString': not all control paths return a value [D:\a\fheroes2\fheroes2\fheroes2-vs2019.vcxproj]
```

2021-05-01 10:29 UTC, merged

2021-05-01 10:29 UTC, ihhub commented
@eos428 , thanks a lot for this big feature!