iconv fix for MinGW
ihhub/fheroes2 pull request #2931
Opened 2021-03-09 17:04 UTC by hgdagon

!\[Properties\](https://user-images.githubusercontent.com/15173076/110506798-47159f00-80b4-11eb-91f8-086d3434159f.png)  
!\[Full Info\](https://user-images.githubusercontent.com/15173076/110506801-47ae3580-80b4-11eb-9e52-8bdfb9033e3b.png)

So, the big change is the introduction of a resource file. I don't have any experience with resource files, I just followed the documentation. I was planning to draw a new logo/icon, currently, the (modified) repo banner is used as icon.

Other changes are minor. Please, review as you see fit.

2021-03-13 13:59 UTC, ihhub requested changes
Hi @hgdagon , would you mind to create a new pull request with changes for `files/fheroes2.rc` and `src/fheroes2/system/gamedefs.h` files only excluding even images? These changes are useful for Visual Studio build as well and it's good to separate them from others.

2021-03-13 13:59 UTC, ihhub commented on files/fheroes2.rc
> +            VALUE "Comments",         "https://ihhub.github.io/fheroes2/\0"
Let's change it to `Visit us at https://ihhub.github.io/fheroes2`.

2021-03-13 13:59 UTC, ihhub commented on files/fheroes2.rc
> +            VALUE "CompanyName",      "ihhub\0" //Placeholder. What do we put here? Can be omitted.
Let's put `fheroes2 Resurrection team`.

2021-03-13 13:59 UTC, ihhub commented on files/fheroes2.rc
> +            VALUE "LegalCopyright",   "\251 2021 Andrey Afletdinov <fheroes2@gmail.com>\0" //Placeholder. Not sure what goes here. NWC? 3DO? Ubisoft? Can be omitted.
Please change it into `"\251 2021 fheroes2 Resurrection team <fhomm2@gmail.com>. All rights for the original HoMM II game belong to Ubisoft"`.

2021-03-13 13:59 UTC, ihhub commented on files/fheroes2.rc
> +            VALUE "ProductName",      "Free Heroes2 Engine\0"
Please change it to `Free Heroes of Might and Magic II engine`.

2021-03-13 13:59 UTC, ihhub commented on files/fheroes2.rc
> +#include <windows.h>
Please move this whole file to `src/resources` directory.

2021-03-13 13:59 UTC, ihhub commented on src/fheroes2/system/gamedefs.h
>  #define MAJOR_VERSION 0
Could we please create a new files `src/fheroes2/system/version.h` where we move all these 3 definitions? In this case we do not need the above trick and we will decouple the code.

2021-03-13 14:11 UTC, hgdagon commented on src/fheroes2/system/gamedefs.h
>  #define MAJOR_VERSION 0
OK, move, as in remove them from gamedefs, right?

2021-03-28 15:54 UTC, ihhub requested changes
Hi @hgdagon , I left few comments here for now. Could you please take a look?

2021-03-28 15:54 UTC, ihhub commented on .gitignore
> +VisualStudio/packages/*
This change won't allow us to modify `zlib1.2.11.zip` in the future.

2021-03-28 15:54 UTC, ihhub commented on script/demo/download_demo.sh
> +if ! [ '$(command -v wget)' ]; then
Could you please confirm that this script works on MacOS as well?

2021-04-01 17:48 UTC, hgdagon commented on script/demo/download_demo.sh
> +if ! [ '$(command -v wget)' ]; then
It does now!

2021-04-01 17:49 UTC, hgdagon commented on .gitignore
> +VisualStudio/packages/*
Excluded \`zlib\*.zip\`

2021-04-01 17:50 UTC, hgdagon commented on src/tools/82m2wav.cpp
> -    if ( argc != 3 ) {
Sorry, been a bit too busy recently. Seems like you made all the changes yourself)

2021-04-01 17:51 UTC, hgdagon commented on script/demo/download_demo.bat
> +powershell -command "Expand-Archive -Force 'demo\demo.zip' 'demo'"
I think it's time for me to close this, make separate branches, and separate PRs.

2021-04-01 17:54 UTC, hgdagon commented on script/demo/download_demo.bat
> +@echo off
No, just for consistency - ``download_demo.sh'/`download_demo.bat``. Why, do we need to specify the os?

2021-04-02 05:13 UTC, ihhub commented
Hi @hgdagon ,
let's do these steps:
1. Keep this pull request open but change it to draft
2. Open a new pull request just for package script installation (with changes for appveyor)
3. Open a new pull request for demo script changes (this is the most important). Please try to use `git mv` command for file renaming before modifying them. It will help to prevent growing git size repository
4. Open a new pull request just for tools fixes
5. Open a new pull request for MinGW changes.


What do you think?

2021-04-24 11:22 UTC, ihhub commented on script/windows/install_packages.bat
> -if not exist "..\..\..\packages"           mkdir "..\..\..\packages"
The problem with using this approach is that user with Win 7 or older won't be able to run it if PowerShell of version lower than 3 is installed.

2021-08-01 15:04 UTC, ihhub commented
@hgdagon , I'm closing this pull request as most of the changes we did in a separate pull request. Please feel free to create a new pull request if we miss something.

2021-08-01 15:04 UTC, closed without merging