Allow to place units in moat in front of the bridge
ihhub/fheroes2 pull request #2932
Opened 2021-03-09 21:35 UTC by oleg-derevenetz

fix #2024

2021-03-09 22:20 UTC, oleg-derevenetz commented
This should fix another funny bug as well (I thought I saw it in the Issues, but I couldn't find it): if bridge was locked in opened state by any flying creature, it didn't close when that creature flew away. As a result, an enemy unit that was close enough to the bridge, could have time to rush in the castle over the bridge just before the bridge closed behind the unit :)

2021-03-09 22:26 UTC, Branikolog commented
Flying creatures doesn't seem to affect gates at all:
![image](https://user-images.githubusercontent.com/55348946/110546550-ad93cf00-813f-11eb-962a-7d20eca0d032.png)

2021-03-09 22:51 UTC, oleg-derevenetz commented
> That will be great, if both these bugs will be fixed, you've talked above.

This PR doesn't fix bug with bridge not affected by flying units defending the castle yet. I hope to fix this too in a while :) Just not today...

2021-03-09 23:17 UTC, oleg-derevenetz commented
@Branikolog I just tried to run OG in DosBox and it seems that in OG flying units are just not able to land on the castle gate cell, even if there is an infantry on the bridge and it's lowered. Is this a known bug in OG?

2021-03-10 10:12 UTC, Branikolog commented
@oleg-derevenetz 
Indeed! OG doesn't allow flyers to open gate...
We have a pro specialist here, @LeHerosInconnu, who knows everything about original game. :D 
I bet, @LeHerosInconnu ahs already a long list waiting of such bugs to be fixed. )

2021-03-10 10:17 UTC, oleg-derevenetz commented
@Branikolog I mean, in OG flying units can't land on gates cell even if bridge is lowered (and even it's already destroyed!). Is this considered as a bug in OG (and needs to be fixed somehow) or as a normal behavior?

2021-03-10 10:23 UTC, Branikolog commented
@oleg-derevenetz 
I'm 100% sure we should fix it. Any flying creature should be able to land at gates area.

2021-03-10 13:18 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz and @Branikolog,

> @Branikolog I mean, in OG flying units can't land on gates cell even if bridge is lowered (and even if it's already destroyed!). Is this considered as a bug in OG (and needs to be fixed somehow) or as a normal behavior?

> @oleg-derevenetz
> I'm 100% sure we should fix it. Any flying creature should be able to land at gates area.

Yes, this is a bug in the original game.
https://heroes2.forumactif.com/t879-heroes-2-bugs-problems-with-castle-gate-during-combat
Fheroes2 must fix it. :)

> @oleg-derevenetz
> Indeed! OG doesn't allow flyers to open gate...
> We have a pro specialist here, @LeHerosInconnu, who knows everything about original game. :D
> I bet, @LeHerosInconnu ahs already a long list waiting of such bugs to be fixed. )

Make your choice. :D
https://heroes2.forumactif.com/f37-original-heroes-2-bugs

2021-03-11 13:56 UTC, Branikolog commented
Hi, @oleg-derevenetz !
I've tested your build and have some issues:
![Moat 2](https://user-images.githubusercontent.com/55348946/110796978-a2e55100-8289-11eb-96e9-b5127983e338.png)
Cyclops cannot enter some hexes in a moat, that for sure, are reachable.
This happens only if they're standing in a moat in front of gates.
Another example:
![Moat3](https://user-images.githubusercontent.com/55348946/110797782-8a296b00-828a-11eb-8971-4b52d513a096.png)
Here elves can enter moat everywhere:
![Moat4](https://user-images.githubusercontent.com/55348946/110797918-b0e7a180-828a-11eb-89f2-bc9febb71c85.png)

2021-03-11 14:15 UTC, oleg-derevenetz commented
Hi @Branikolog

On the second screenshot cyclops are not standing in a moat before the gates, but they are still unable to enter the moat near (partially?) ruined walls. Do you have a save file before this battle (preferably hotseat)?

2021-03-11 14:20 UTC, Branikolog commented
@oleg-derevenetz 
On a second and third screenshots Grand Elves' turn. 
Unfortunately I cannot provide savefile, as I'm on my road to home now.
Only in ~ 1.5 hours I can.

2021-03-11 14:27 UTC, oleg-derevenetz commented
@Branikolog Ah, now I understand - any unit is unable to reach those cells in the moat near the wall if it standing near the gates? Thanks, I'll look into it.

2021-03-11 14:33 UTC, Branikolog commented
@oleg-derevenetz 
Correct. 
Anyway, we have lots of moat-related issues... Probably your implementation comes into conflict with all that problems..

2021-03-12 06:19 UTC, ihhub commented
Hi @oleg-derevenetz , offtopic: would you mimd to join our Discord server where we usually have faster discussions about any problems?

2021-03-12 11:25 UTC, oleg-derevenetz commented
Hi @ihhub, to be honest I have no experience using Discord, so may be later :) I'm a bit old-fashioned and normally don't use messengers for communication - they take too much time. Thanks anyway!

2021-03-12 11:52 UTC, Branikolog commented
Hi, @oleg-derevenetz !
Discord - is a simple chat, which you can use through your browser. I've started using it after joining this project.)
P.S. Do you still need a multiplayer savefile, where you can make some tests?

2021-03-12 12:05 UTC, oleg-derevenetz commented
Hi @Branikolog, well, that's a problem with all chats: they steal your attention on a regular basis :) Regarding savefile: thanks, I already was able to reproduce the issue and it seems that I already fixed it for one-hex units, but there are also issues with moat and two-hex units, now I'm trying to investigate them... Also, for some reason, there are two similar, but separate pathfinding engines: one is in battle_board.cpp, and another is in battle_pathfinding.cpp, and this complicates the task somewhat :)

2021-03-12 12:20 UTC, Branikolog commented
@oleg-derevenetz 
There're tons of issues with moat currently. 2hex creatures cannot return back through moat. Defensive army is always stuck in a moat, as the path goes through moat cells..
On engines: feel free to ask @ihhub or @idshibanov. :) (Which would be much easier using discord... ;) )

2021-03-12 14:15 UTC, idshibanov commented
> Also, for some reason, there are two similar, but separate pathfinding engines: one is in battle_board.cpp, and another is in battle_pathfinding.cpp, and this complicates the task somewhat :)

A star implementation in `battle_board.cpp` is the older code that is only used for user's interface and actions. I want to move fully to the second one (in battle_pathfinding.cpp); just didn't have the time to refactor. There's definitely duplication of logic.

2021-03-12 16:46 UTC, idshibanov requested changes
I got movement working in fheroes2 after I checked out your branch:
![image](https://user-images.githubusercontent.com/1373638/110970999-513fd380-8328-11eb-9b41-ac8db351b291.png)

Turns out same moves are bugged in the original game.

1. Bridge blocks further movement even for defender units. I think OG simply applies moat penalty to every case. Personally I don't think we should reproduce this behavior.
![image](https://user-images.githubusercontent.com/1373638/110970898-34a39b80-8328-11eb-8dcf-d7846e9f8c56.png)

2. If you click here Cavalry just skips the turn:
![image](https://user-images.githubusercontent.com/1373638/110968764-e8eff280-8325-11eb-9df4-b9ede8c99fdd.png)

2021-03-12 16:46 UTC, idshibanov commented on src/fheroes2/battle/battle_board.cpp
> +                    if ( isMoatBuilt && Board::isMoatIndex( cellId, unit.GetColor() ) && cellId != targetHeadCellId && cellId != targetTailCellId )
Here we should check tailCellId if it's a moat index or not. This should fix your wide unit issues and force them to move around.

2021-03-12 16:46 UTC, idshibanov commented on src/fheroes2/battle/battle_pathfinding.cpp
> +                            additionalCost += ARENASIZE;
This change will break AI, please revert cost here. Units won't move through moat and attack as they'll think it's unreachable.

2021-03-12 16:46 UTC, idshibanov commented on src/fheroes2/battle/battle_pathfinding.cpp
>                      const Cell * tailCell = ( unitIsWide && pathStart != newTailIndex ) ? Board::GetCell( newTailIndex ) : nullptr;
I found an actual bug on this line here that could prevent AI units from moving back to castle. You can either fix it now or I'll push a separate PR. It should be something like that:
```
const Cell * tailCell = ( unitIsWide && !unit.GetPosition().contains( newTailIndex ) ) ? Board::GetCell( newTailIndex ) : nullptr;
```

2021-03-12 17:08 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_pathfinding.cpp
> +                            additionalCost += ARENASIZE;
Yeah, I wasn't originally going to touch ArenaPathfinder, it's a mechanical change along with updating isMoatIndex() arguments. I'll revert it.

2021-03-12 17:11 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_board.cpp
> +                    if ( isMoatBuilt && Board::isMoatIndex( cellId, unit.GetColor() ) && cellId != targetHeadCellId && cellId != targetTailCellId )
I think I've already tried this, but this led to some issues. I'll try it and then check again.

2021-03-12 17:13 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_pathfinding.cpp
>                      const Cell * tailCell = ( unitIsWide && pathStart != newTailIndex ) ? Board::GetCell( newTailIndex ) : nullptr;
I can add this to my PR, but the problem is I am unable to test AI pathfinding properly. You know where to look, but I'm not. Maybe it would be better to add this change as a separate PR?

2021-03-12 18:00 UTC, oleg-derevenetz commented
Hi @idshibanov 

Thank you very much for your review and suggestions!

> Bridge blocks further movement even for defender units. I think OG simply applies moat penalty to every case. Personally I don't think we should reproduce this behavior.

I think that's not the case in fheroes2 (with this PR):

<img width="639" alt="Unicorn movement" src="https://user-images.githubusercontent.com/32623900/110978463-79edba80-8374-11eb-9588-afd56ef37044.png">

> If you click here Cavalry just skips the turn:

This should work properly as well with this PR:

<img width="640" alt="Unicorn before the turn" src="https://user-images.githubusercontent.com/32623900/110979023-24fe7400-8375-11eb-9a8f-78b043656e5f.png">
<img width="639" alt="Unicorn after the turn" src="https://user-images.githubusercontent.com/32623900/110979087-36478080-8375-11eb-899f-94b12d06c3ea.png">

> Here we should check tailCellId if it's a moat index or not. This should fix your wide unit issues and force them to move around.

Yes, thank you! This prevents two-hex units from moving "with the tail in the moat" and fixes incorrect pathfinding in cases like this:

<img width="639" alt="Unicorn fail" src="https://user-images.githubusercontent.com/32623900/110979444-abb35100-8375-11eb-9d9f-4db3481a2a52.png">

2021-03-12 18:01 UTC, idshibanov commented
Tested the changes locally, everything looks good to me. I'll handle `ArenaPathfinder` updates later as a separate PR.

2021-03-12 18:08 UTC, oleg-derevenetz commented
> Tested the changes locally, everything looks good to me. I'll handle ArenaPathfinder updates later as a separate PR.

@idshibanov  Thank you very much!

Hi @ihhub what do you think? Maybe it will make sense to create a new build for @Branikolog for further testing?

2021-03-12 22:08 UTC, idshibanov approved these changes

2021-03-13 04:28 UTC, ihhub commented
Hi @oleg-derevenetz , sure. I'll poke @Branikolog to test it.

2021-03-13 13:38 UTC, Branikolog commented
Latest build:
Goblins are able to enter castle while standing in a moat in front of gates (when walls are destroyed):
![image](https://user-images.githubusercontent.com/55348946/111031807-65fc9400-841a-11eb-8992-01d062320052.png)
![image](https://user-images.githubusercontent.com/55348946/111031825-7ad92780-841a-11eb-9515-23304a1a0dee.png)
![image](https://user-images.githubusercontent.com/55348946/111031830-8593bc80-841a-11eb-97a7-d1a5e468207b.png)

2021-03-13 13:49 UTC, oleg-derevenetz commented
@Branikolog Hmm, looks like another issue with pathfinding. As I seen in the code, there was special piece of code that should force units to stop in the moat in any case, even if walls are destroyed. I'll take a look into this tonight...

2021-03-13 13:55 UTC, oleg-derevenetz commented
@Branikolog Ah, there is an exception in this rule: if unit starts his movement in a moat, this restriction doesn't work. I need to think about how to fix this better (and to not break anything).

2021-03-13 14:32 UTC, Branikolog commented
@oleg-derevenetz 
I'm not sure it is the issue you're working at, actually...
Nevertheless, any troop can enter the moat in front of gates. I mean the above problem could be related to another issue (#471)
The only difference here, is that troop is moving correctly: it leaves the moat and creates its path over the land... And then steps into a moat but doesn't stop, because of #471 issue. (because currently creature standing in a moat can walk over it in any direction without penalty which is another issue)

2021-03-13 14:37 UTC, oleg-derevenetz commented
@Branikolog This PR should fix #471 as well. Now units shouldn't be able to walk in a moat in any direction more than one cell. However, when they START IN A MOAT, they will be able to walk through the dry land and then cross the moat in different place. This is a different issue, and I'll try to address this later today.

2021-03-13 14:40 UTC, Branikolog commented
@oleg-derevenetz 
Okay. I hope, you'll fix it without any problem. :)

2021-03-13 14:42 UTC, oleg-derevenetz commented
@Branikolog I hope so too... :)

2021-03-13 14:52 UTC, idshibanov commented
> Ah, there is an exception in this rule: if unit starts his movement in a moat, then this restriction doesn't work. I need to think about how to fix this better (and to not break anything).

There seems to be an edge case when unit starts its turn in the moat. They can move through one moat tile to enter the castle if they stand behind a tower for example.

2021-03-13 14:55 UTC, oleg-derevenetz commented
@idshibanov I thought unit should be able to enter a castle only if it stands in a moat in the cell directly adjacent to the breach in the wall?

2021-03-13 15:12 UTC, idshibanov commented
> 
> 
> @idshibanov I thought unit should be able to enter a castle only if it stands in a moat in the cell directly adjacent to the breach in the wall?

Oh wait, nevermind. I double-checked it with original copy now and you're right. It was a diagonal move.

2021-03-13 21:15 UTC, oleg-derevenetz commented
OK, here's what we have today.

> Goblins are able to enter castle while standing in a moat in front of gates (when walls are destroyed):

@Branikolog Should be fixed now, no longer the case:

<img width="640" alt="Minotaurs 1" src="https://user-images.githubusercontent.com/32623900/111044100-957dc180-8457-11eb-9e66-ce3870598d7f.png">
<img width="640" alt="Minotaurs 2" src="https://user-images.githubusercontent.com/32623900/111044117-ab8b8200-8457-11eb-9c4a-af9b64fb3048.png">

> Here we should check tailCellId if it's a moat index or not. This should fix your wide unit issues and force them to move around.

@idshibanov It turns out that this change brought another issue to life:

<img width="639" alt="Unicorns fail 1" src="https://user-images.githubusercontent.com/32623900/111044243-5f8d0d00-8458-11eb-92d2-e8bd876823c4.png">
<img width="639" alt="Unicorns fail 2" src="https://user-images.githubusercontent.com/32623900/111044251-6ae03880-8458-11eb-86ac-dc5265a872ed.png">
<img width="638" alt="Unicorns fail 3" src="https://user-images.githubusercontent.com/32623900/111044257-7469a080-8458-11eb-96cd-47f372f264bc.png">

I fixed this by applying moat penalty to the tail only if head cell wasn't already in the moat at the previous stage, that fixed _almost_ everything (including diagonal moves from the moat to the castle for 2hex creatures)... except this:

<img width="639" alt="Unicorn fail 1" src="https://user-images.githubusercontent.com/32623900/111044402-8a2b9580-8459-11eb-9402-5b76426f854e.png">

Unicorns are unable to reach this cell and stop at cell 84:

<img width="640" alt="Unicorn fail 2" src="https://user-images.githubusercontent.com/32623900/111044426-b3e4bc80-8459-11eb-80e5-dea81f844327.png">

The same is observed for for the top part of the moat. I can roughly imagine the reason of this, but don't know how to fix this properly yet. I think this may be considered a minor issue for now...

2021-03-13 22:10 UTC, oleg-derevenetz commented
@idshibanov There is another pathfinding issue as well:

<img width="639" alt="Centaurs fail" src="https://user-images.githubusercontent.com/32623900/111051036-4fc5f680-8461-11eb-95a8-9c9aeb672d74.png">

while Centaurs are still able to reach this cell while wall is not yet broken:

<img width="641" alt="Centaurs OK" src="https://user-images.githubusercontent.com/32623900/111051057-78e68700-8461-11eb-8c73-89fa8fd416fb.png">

That's because, when the wall is broken, they are trying to reach this cell by diagonal move through the castle and then they fail, because they need to pass the moat once again :)

2021-03-13 22:29 UTC, oleg-derevenetz commented
I would like to propose the following: if @Branikolog would be so kind to thoroughly test a new build with this PR once again :) and there will be no any new pathfinding issues in addition to the two mentioned above, and if @ihhub and @idshibanov would also be so kind to review this PR once again and there will be no new comments and suggestions, let's open the separate issues regarding those two problems above and merge this PR?

2021-03-14 09:01 UTC, Branikolog commented
@oleg-derevenetz 
One issue found:
![image](https://user-images.githubusercontent.com/55348946/111062891-d3610100-84bc-11eb-8c48-ab50477b0ec1.png)
Medusas are able to move 2 cells in a moat.
But at the same time cannot (which is ok) return back.
![image](https://user-images.githubusercontent.com/55348946/111062921-05726300-84bd-11eb-9ef3-5594e6c4978f.png)

2021-03-14 09:07 UTC, oleg-derevenetz commented
Hi @Branikolog

Not quite sure what the problem is. Units in a moat can move to adjacent cells in a moat, but only to adjacent ones. Medusas on this screenshot are able to move to the adjacent moat cells, but they will move to the distant moat cells only through the dry land.

2021-03-14 09:09 UTC, Branikolog commented
@oleg-derevenetz 
What about this case?
![image](https://user-images.githubusercontent.com/55348946/111063053-aeb95900-84bd-11eb-92fa-5622834d1661.png)
![image](https://user-images.githubusercontent.com/55348946/111063127-08218800-84be-11eb-99e8-9fc645c867bc.png)

2021-03-14 09:15 UTC, oleg-derevenetz commented
@Branikolog I'll look into it. It looks like this PR turns into "PR that should fix all pathfinding at once" :) Don't know is this really reasonable though, given that AFAIK there is a new pathfinding engine in development...

2021-03-14 09:20 UTC, ihhub commented
> @Branikolog I'll look into it. It looks like this PR turns into "PR that should fix all pathfinding at once" :) Don't know is this really reasonable though, given that AFAIK there is a new pathfinding engine in development...

Hi @oleg-derevenetz , please do not fix all of this. I'll check myself and verify with @idshibanov and he's going to optimize the pathfinding. Please do not waste your time on this issue for now :)

2021-03-14 09:30 UTC, oleg-derevenetz commented
> Hi @oleg-derevenetz , please do not fix all of this. I'll check myself and verify with @idshibanov and he's going to optimize the pathfinding. Please do not waste your time on this issue for now :)

Hi @ihhub Thank you :) I can also rollback some pathfinding-related changes here if you find them breaking things.

2021-03-14 11:38 UTC, oleg-derevenetz commented
@Branikolog Hmm, tried it out of curiosity:

<img width="639" alt="Centaurs" src="https://user-images.githubusercontent.com/32623900/111066910-8425cb00-84d2-11eb-83de-f38f57e9d2e9.png">

Minotaurs are blocking Centaurs movement to the upper moat cells (only adjacent moat cells are available), but Centaurs are able to make a diagonal move to the dry land to reach lower moat cells. Everything seems fine, but this is with latest changes from last evening.

2021-03-14 12:14 UTC, Branikolog commented
@oleg-derevenetz 
Huh... I've checked the OG...
In the OG medusas are able to move over a moat...
I'm so got used to H3 mechanics, so I was surprised, that H2 has a slight different behaviour with moat logics:
![image](https://user-images.githubusercontent.com/55348946/111067991-db7a6a00-84d7-11eb-85de-f3874132d439.png)
Medusas are able to go over the whole moat up to the lower hex available.... o_O

2021-03-14 12:18 UTC, Branikolog commented
@oleg-derevenetz 
So, I'm rather confused about the implementation you're working about...
Btw, I'm using a build compiled a few hours ago...
![image](https://user-images.githubusercontent.com/55348946/111068114-75421700-84d8-11eb-8d75-ab3b7cdf326a.png)

2021-03-14 12:24 UTC, oleg-derevenetz commented
Hi @Branikolog

> In the OG medusas are able to move over a moat...

As far as I know, in OG unit can move only to adjacent moat cell directly. If it needs to go to distant moat cells, it should go to the dry land first, move over the dry land to the moat and then step to a moat. If it can't move out of moat to the dry land for some reason (due to due to blocking by another unit(s) for example), it shouldn't be able to move to distant moat cells.

> Btw, I'm using a build compiled a few hours ago...

This PR isn't merged yet, may be you are running build from the master branch?

2021-03-14 12:53 UTC, Branikolog commented
@oleg-derevenetz 
Oh right. I'm working on build made 16 hours ago...

> As far as I know, in OG unit can move only to adjacent moat cell directly. If it needs to go to distant moat cells, it should go to the dry land first, move over the dry land to the moat and then step to a moat. If it can't move out of moat to the dry land for some reason (due to blocking by another unit(s) for example), it shouldn't be able to move to distant moat cells.

Check the screenshot, which I made from OG:

>Huh... I've checked the OG...

Medusas are able to move through the whole moat area in front of gates.
Actually, it seems to me, that in the OG moat doesn't stop troops if they are already standing in moat. But! When troops are ready to enter castle through broken wall they come close to that area in front of broken wall and stop without entering castle. Troops can pass through multiple moat cells (If they start their move from a moat) but always stop in a cell in front of broken wall.

Actually, I'm confused about this logic, as got used to H3 behaviour (As you described above)...

P.S. Are you still rejecting using discord? :-P Discussing such things is much more effective and faster there...

2021-03-14 13:02 UTC, oleg-derevenetz commented
@Branikolog

> Medusas are able to move through the whole moat area in front of gates.

I think that's because in OG "main" hex of 2hex creatures is a tail cell, while in fheroes2 it's a head cell. So in OG medusas technically are not in the moat, because their tails are on dry land :) I think it's hard to accurately replicate the behavior because of this.

> Actually, it seems to me, that in the OG moat doesn't stop troops if they are already standing in moat.

As for single-hex units, it actually does:

![Pikemen](https://user-images.githubusercontent.com/32623900/111069524-7b3af680-84de-11eb-8179-4f40aeddfc77.jpg)

Pikemen are not able to move more than one cell in a moat if blocked by other troops.

> P.S. Are you still rejecting using discord? :-P Discussing such things is much more effective and faster there...

May be later :)

2021-03-14 15:21 UTC, idshibanov commented
> I think that's because in OG "main" hex of 2hex creatures is a tail cell, while in fheroes2 it's a head cell. So in OG medusas technically are not in the moat, because their tails are on dry land :) I think it's hard to accurately replicate the behavior because of this.

I was going to say the same thing. OG mechanics aren't the best, let's not replicate this and avoid further changes to pathfinding in this PR. I tested most recent version and it seems fine to me.

2021-03-15 10:03 UTC, ihhub approved these changes

2021-03-15 10:11 UTC, merged

2021-03-15 10:12 UTC, ihhub commented
@oleg-derevenetz , thank you so much for your efforts fixing this issue!