initial debianization
ihhub/fheroes2 pull request #2953
Opened 2021-03-14 08:52 UTC by undef21

Add  packaging ability for debian-like systems.
For building .deb package you need install build-essential package and build dependencies, then run
`dpkg-buildpackage -us -uc -b`

2021-03-22 15:07 UTC, ihhub requested changes
Hi @undef21 , I left few comments here. Could you please take a look?

2021-03-22 15:07 UTC, ihhub commented on debian/changelog
> + -- fheroes2 team <mail@example.org>  Sat, 13 Mar 2021 23:53:31 +0300
Our email is `fhomm2@gmail.com`.

2021-03-22 15:07 UTC, ihhub commented on debian/control
> +Maintainer: fheroes2 team <mail@example.org>
Our email is `fhomm2@gmail.com`.

2021-03-22 15:07 UTC, ihhub commented on debian/copyright
> +           2019-2021 fheroes2 team <fheroes2@example.org>
To do not confuse people it would be better to put these lines in a reverse way.

2021-03-22 15:07 UTC, ihhub commented on debian/install
> +fheroes2 usr/games
Please add missing emty line at the end of the file :)

2021-03-22 15:07 UTC, ihhub commented on debian/rules
> +export FHEROES2_STRICT_COMPILATION = 1
Please remove this flag. We use it only for our servers while end users shouldn't use it as it break compilation in case of any warnings.

2021-03-23 06:35 UTC, undef21 commented on debian/changelog
> +fheroes2 (0.9.1-1) UNRELEASED; urgency=medium
Usually debian directory is placed at source root because build helpers expect this path. Otherwise users should move this dir to source root manually.

2021-03-26 23:57 UTC, hgdagon commented
@undef21 Can you, please move debian/fheroes2.desktop to src/resources (or maybe @ihhub can suggest a better location), so we can use it for other distros as well?

2021-03-27 14:53 UTC, undef21 commented
@hgdagon, ok. I'll move all common packaging stuff to script/package dir when this PR'll be ready.

2021-04-13 16:09 UTC, ihhub requested changes
Hi @undef21 , I left few more comments here. Is this pull request ready for final review?

2021-04-13 16:09 UTC, ihhub commented on script/packaging/debian/docs
> +fheroes2.key
If this is documentation section then we should include `doc/README.txt` file.

2021-04-13 16:09 UTC, ihhub commented on script/packaging/common/fheroes2.sh
> +test -x $FHEROES2_DIR/fheroes2 || (ln -s /usr/lib/games/fheroes2/fheroes2 $FHEROES2_DIR && cp /usr/share/doc/fheroes2/fheroes2.key $FHEROES2_DIR) || exit
We should copy `doc/README.txt` file as well.

2021-04-14 12:42 UTC, undef21 commented on debian/fheroes2.sh
> +FHEROES2_DIR=$HOME/.fheroes2
Currently this dir not only for config. XDG-compiliace is another task which needed rewriting directory searching logic.

2021-04-14 12:50 UTC, undef21 commented on script/packaging/debian/docs
> +fheroes2.key
> Is this pull request ready for final review?

Not yet. Also package needs man page and README.txt. What do you think if we split current README to README and INSTALL files? README will contain platform-independent info about copyrights, directory structure, needed OG files, and INSTALL will be contain info about installing for various platforms?

2021-04-21 10:56 UTC, qarkai commented on script/packaging/debian/install
> +script/packaging/common/fheroes2.sh => /usr/games/fheroes2
Looks like there is extra `/` before `usr`.

2021-04-22 15:28 UTC, undef21 commented on script/packaging/debian/install
> +script/packaging/common/fheroes2.sh => /usr/games/fheroes2
Thanks. Fixed.

2021-06-02 20:38 UTC, qarkai commented on script/packaging/common/fheroes2.sh
> +#!/bin/sh
Can get rid of this wrapper script by compiling with properly defined `CONFIGURE_FHEROES2_DATA` flag.

2021-06-03 08:59 UTC, undef21 commented on script/packaging/common/fheroes2.sh
> +#!/bin/sh
Sure. I will test master branch and rework this pr at this holidays. Thank you for XDG support. It's simplify packaging for unices.

2021-06-07 13:53 UTC, qarkai commented on script/packaging/debian/rules
> +	convert src/resources/fheroes2.png debian/fheroes2.xpm
Is it Debian requirement? According to [Icon Theme Specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) PNG is supported.

2021-06-07 14:34 UTC, ihhub requested changes
Hi @undef21 , I left multiple comments here. Would you mind to take a look? Also is it possible to target this pull request for 0.9.5 release which is going in a month?

2021-06-07 14:34 UTC, ihhub commented on script/packaging/debian/control
> +Build-Depends: debhelper (>= 9), dh-exec, imagemagick, libsdl2-dev,libsdl2-mixer-dev, libsdl2-ttf-dev, libtinyxml-dev, libz-dev
Please remove `libtinyxml-dev` as we killed all XML code recently.

2021-06-07 14:34 UTC, ihhub commented on script/packaging/debian/control
> +Description: free implementation of Heroes of Might and Magic II game engine
Let's call it `Free remake of Heroes of Might and Magic II game engine`. It's even more understandable.

2021-06-07 14:34 UTC, ihhub commented on script/packaging/debian/docs
> +fheroes2.key
I think we have something for Playstation Vita. Could you please take a look?

2021-06-07 14:34 UTC, ihhub commented on script/packaging/debian/docs
> +fheroes2.key
Also we have a proper `README.txt` in `doc` directory.

2021-06-07 14:34 UTC, ihhub commented on script/packaging/debian/rules
> +export WITHOUT_BUNDLED_LIBS = 1
This flag is no longer present. Please remove it.

2021-06-07 14:34 UTC, ihhub commented on script/packaging/debian/changelog
> +fheroes2 (0.9.2-1) UNRELEASED; urgency=medium
Please update game's version.

2021-06-07 15:00 UTC, qarkai commented on script/packaging/debian/control
> +Description: free implementation of Heroes of Might and Magic II game engine
AFAIU this description is from About on main page. I use it in [AUR](https://aur.archlinux.org/packages/fheroes2) too.

2021-06-08 14:18 UTC, ihhub requested changes
Hi @undef21 , I left few more comments here. Could you please take a look?

2021-06-08 14:18 UTC, ihhub commented on script/packaging/debian/copyright
> +Source: https://github.com/ihhub/fheroes2/releases
Should we point to **https://github.com/ihhub/fheroes2** instead?

2021-06-08 14:18 UTC, ihhub commented on script/packaging/debian/rules
> +export RELEASE = 1
This option we should remove from make and cmake. Please remove this line as well. I'll make needed change in a separate pull request.

2021-06-08 14:18 UTC, ihhub commented on script/packaging/debian/README.Debian
> +fheroes2 requires data files from the original Heroes of Might and Magic II. All rights to original game files is owned by Ubisoft.
It would be great to have 80 characters line limits as it's done for README.txt. Some users still use command line / bash to read text files...

2021-06-08 14:18 UTC, ihhub commented on script/packaging/debian/README.Debian
> +--- Install ---
The text in this file shall be following:
```
--- Copyright ---
All rights for the original game and its resources belong to former The 3DO Company.
These rights were transferred to Ubisoft. We do not encourage and do not support
any form of illegal usage of the original game. We strongly advise to purchase
the original game on GOG or Ubisoft Store platforms. Alternatively, you can
download a free demo version of the game with help of our scripts.

--- Installation and Requirements ---
You are required to have at a demo or full version of Heroes of Might and Magic II
game to be able to play it.

If you do not have the original Heroes of Might and Magic II game please run
'demo_unix.sh' to download and install all needed files.

If you have a legally purchased game, you need to copy all directories which
belong to HoMM2 (such as DATA, MAPS and etc) into
$XDG_DATA_HOME/fheroes2 location.

--- License ---
This project is under GNU General Public License v2.0. Please refer to file
LICENSE for more details.

--- Donation ---
Currently we accept donations via Patreon at https://www.patreon.com/fheroes2.
All donations will be used only for the future project development as we do not
consider this project as a source of income by any means.
```

No need to explain about certain folders from the original game. What do you think?

2021-06-08 14:18 UTC, ihhub commented on script/packaging/debian/control
> +Description: Free remake of Heroes of Might and Magic II game engine
I think here we miss a full stop at the end of the sentence.

2021-06-08 14:18 UTC, ihhub commented on script/packaging/debian/control
> + .
Do we need this line with a dot?

2021-06-08 16:06 UTC, undef21 commented on script/packaging/debian/copyright
> +Source: https://github.com/ihhub/fheroes2/releases
According [this doc](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#source-field) and comparing another packages, this field usually contains url of page with source tarballs.

2021-06-08 16:09 UTC, undef21 commented on script/packaging/debian/rules
> +export RELEASE = 1
Done.

2021-06-08 16:23 UTC, undef21 commented on script/packaging/debian/control
> +Description: Free remake of Heroes of Might and Magic II game engine
This field is header of description.
![example1](https://user-images.githubusercontent.com/71143197/121222105-e8b4b400-c88e-11eb-8016-9ad2d3ac839b.png)

2021-06-08 16:25 UTC, undef21 commented on script/packaging/debian/control
> + .
Yes. This dot is translated to empty line.

2021-06-08 19:36 UTC, undef21 commented on script/packaging/debian/README.Debian
> +--- Install ---
Look good.
I deleteв paragraph `If you do not have the original Heroes of Might and Magic II game please run
'demo_unix.sh' to download and install all needed files.` because otherwise we'll have to add script and additional dependencies for package

2021-06-09 13:28 UTC, ihhub commented
Hi @hgdagon and @qarkai , do you have any more comments on this pull rquest?

2021-06-09 13:28 UTC, ihhub approved these changes

2021-06-09 13:45 UTC, qarkai commented on script/packaging/debian/control
> +Build-Depends: debhelper (>= 9), libsdl2-dev,libsdl2-mixer-dev, libsdl2-ttf-dev, libz-dev
What about `gettext` and `libsdl2-image-dev`?

2021-06-09 19:39 UTC, qarkai approved these changes

2021-06-10 04:20 UTC, merged

2021-06-10 04:20 UTC, ihhub commented
@undef21 , thank you very much for such improvement!