Fix interaction with the castle bridge for flying units
ihhub/fheroes2 pull request #2960
Opened 2021-03-15 13:09 UTC by oleg-derevenetz

In the original game, flying unit could not land on the gates cell, even even if they were already open or destroyed:

![OG](https://user-images.githubusercontent.com/32623900/111154773-a2f49200-85a4-11eb-96fe-dfc7484a96a1.jpg)

At the moment, in fheroes2 flying units don't interact with gates and bridge in any way, what leads to situations like this:

<img width="639" alt="Phoenixes fail" src="https://user-images.githubusercontent.com/32623900/111155041-fb2b9400-85a4-11eb-88ca-f7064e11b09c.png">

In this PR I propose some fixes that will cause flying units to interact with the bridge like everyone else: the bridge should be lowered first to allow landing on the gates cell and usually (if it's possible) to allow landing on the moat cell near the gates.

2021-03-15 15:37 UTC, oleg-derevenetz commented
Sorry for multiple force pushing, it seems that "scan-build analyzer" workflow constantly fails on apt-get update step.

2021-03-18 11:10 UTC, ihhub commented
> Sorry for multiple force pushing, it seems that "scan-build analyzer" workflow constantly fails on apt-get update step.

Hi @oleg-derevenetz , it's totally fine to have any reasonable number of pushes or commits. We do not restrict it.

2021-03-18 13:30 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left just few comments here. Could you please take a look? Also I requested @Branikolog to test this version.

2021-03-18 13:30 UTC, ihhub commented on src/fheroes2/battle/battle_board.h
> +        static bool isBridgeIndex( s32, const Unit & );
Could you please add input argument names? The old code is filled with this weird coding style. We shouldn't do this as such approach makes the code less readable.

2021-03-18 13:30 UTC, ihhub commented on src/fheroes2/battle/battle_bridge.cpp
> +        const s32 prevPos = b.GetHeadIndex();
Could you please replace `s32` by **int32_t**? We would like to remove this `using` cases from the code (slowly).

2021-03-18 13:30 UTC, ihhub commented on src/fheroes2/battle/battle_bridge.cpp
> +        if ( dstPos == GATES_CELL ) {
We could do like this: `return dstPos == GATES_CELL;`. So it's just one-two CPU ticks faster but... :)

2021-03-18 13:30 UTC, ihhub commented on src/fheroes2/battle/battle_board.cpp
> +        for ( iterator it = begin(); it != end(); ++it ) {
Please use here normal `size_t` based loop. The compiler will optimize this and `it - begin()` will be just `size_t` value. It also would be a bit more readable. However, I'm leaving it up to you to decide.

2021-03-18 13:33 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_board.h
> +        static bool isBridgeIndex( s32, const Unit & );
Of course. Just did it "in the style of the surrounding code" :) I'll fix this.

2021-03-22 12:13 UTC, Branikolog commented
I made a few tests... Everything seems to work fine.

2021-03-22 14:38 UTC, merged

2021-03-22 14:38 UTC, ihhub commented
@oleg-derevenetz , huge thanks for fixing this issue!