Code cleanup
ihhub/fheroes2 pull request #2986
Opened 2021-03-17 18:41 UTC by tau3

Hello. 

There are some fixes for code smells and alerts:
lgtm - `Battle::Only`
sonarcube - `ListActions`, `MapObjects`, `World`

2021-03-22 15:22 UTC, ihhub requested changes
Hi @tau3 , could you please take a look at few given comments?

2021-03-23 00:47 UTC, tau3 commented on src/fheroes2/battle/battle_only.h
> +        std::unique_ptr<LuckIndicator> luckIndicator2;
sure, i'll do

2021-03-23 00:48 UTC, tau3 commented on src/fheroes2/heroes/heroes_indicator.h
> +#include "image.h"
to use `fheroes2::ImageRestorer`in `heroes_indicator.h` after recent changes

2021-03-29 14:20 UTC, ihhub commented on src/fheroes2/battle/battle_only.h
> +        std::unique_ptr<LuckIndicator> luckIndicator2;
Let's focus only on this part. It's good to do incremental changes rather than everything in one shot.

2021-03-29 14:23 UTC, ihhub requested changes
Hi @tau3 , I left few more comments regarding code optimization. Could you please take a look?

2021-03-29 14:23 UTC, ihhub commented on src/fheroes2/battle/battle_only.cpp
>      }
Please remove the check for nullptr and just call reset() directly. This method will handle such logic inside.

2021-03-29 14:23 UTC, ihhub commented on src/fheroes2/battle/battle_only.cpp
>      }
Please remove the check for nullptr and just call reset() directly. This method will handle such logic inside.

2021-04-04 06:52 UTC, ihhub requested changes
@tau3 , there are few more comments. Could you please take a look?

2021-04-04 06:52 UTC, ihhub commented on src/fheroes2/battle/battle_only.cpp
>      if ( cinfo2 )
We could remove this check.

2021-04-04 06:52 UTC, ihhub commented on src/fheroes2/battle/battle_only.cpp
>      if ( hero2 ) {
We could remove this check as well.

2021-04-04 06:52 UTC, ihhub commented on src/fheroes2/battle/battle_only.cpp
> +    selectArmy1.reset();
This part of the code is identical to `UpdateHero1` (moral and luck indicators are actually reset there as well). Should we create a method called `resetHero1` to put this code there? The same applies for hero 2.

2021-04-08 20:33 UTC, tau3 commented on src/fheroes2/battle/battle_only.cpp
> +    selectArmy1.reset();
I think we shouldn't. It would be better to make a struct that contains hero, army, bars, etc, so `Batlle::Only` would have only two private members - those members can be passed to update/reset functions, which would reduce code duplication. But it's a matter of a separate PR IMO

2021-04-11 13:20 UTC, merged

2021-04-11 13:20 UTC, ihhub commented
@tau3 , thank you very much for this code cleanup!