Reformat installation instruction and add Gentoo
ihhub/fheroes2 pull request #3026
Opened 2021-03-27 13:48 UTC by kant2002

I extract each platform as separate section, so that block would be easier to read.
Also add instructions how to compile application on Gentoo.

2021-03-27 16:51 UTC, Northfear commented
`sdl2-mixer` and `sdl2-ttf` should probably be the default ones for Gentoo tho

2021-03-28 11:34 UTC, kant2002 commented
Probably yes. Due to my first exposure, I first install plain `desktop/systemd` profile, and only then `desktop/plasma/systemd`, so this may explain my need to install additional dependencies.

2021-03-28 15:41 UTC, ihhub requested changes
Hi @kant2002 , I left few comments here. Could you please take a look?

2021-03-28 15:41 UTC, ihhub commented on README.md
> +
Please remove this empty line.

2021-03-28 15:41 UTC, ihhub commented on README.md
> +
Please remove this empty line.

2021-03-28 15:41 UTC, ihhub commented on README.md
> +
Please remove this empty line.

2021-03-28 15:41 UTC, ihhub commented on README.md
> +If you have Gentoo, in addition to basic distribution you need to run following commands
Since the title already states Gentoo I think we should rephrase it to `In addition to basic distribution you need to run following commands:`. What do you think?

2021-03-28 15:41 UTC, ihhub commented on README.md
> +emerge --ask sdl-ttf
Is it possible to combine these 2 commands into one?

2021-03-28 16:23 UTC, kant2002 commented
@ihhub I deliberately do not include instructions how to install dependencies for SDL1. Let me know if you want these option to be highlighted.

2021-03-29 14:04 UTC, ihhub commented
> @ihhub I deliberately do not include instructions how to install dependencies for SDL1. Let me know if you want these option to be highlighted.

I think it's fine not to mention SDL 1 as it's useful only for really old OSes.

2021-03-29 14:04 UTC, merged

2021-03-29 14:04 UTC, ihhub commented
@kant2002 , thank you very much for this documentation cleanup!