Add support for tests
ihhub/fheroes2 pull request #3046
Opened 2021-03-29 06:00 UTC by kant2002

This is minimum amount of changes which require to 
- add ability to have in-memory drawing device
- Be able to load data from AGG files multiple times in the same application. 

I test these changes on simple tests which just draw different luck/morale modifiers depending on the hero stats.
These test definitely do not optimal, and maybe useful, but serves me as PoC for whole work.

2021-03-30 14:44 UTC, ihhub requested changes
Hi @kant2002 , I left multiple comments here. Would you mind to take a look once you have time?

2021-03-30 14:44 UTC, ihhub commented on src/fheroes2/agg/agg.cpp
> +    fheroes2::AGG::clearICNSprites();
Let's call it from fheroes2.cpp. We should avoid dependencies.

2021-03-30 14:44 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +        _icnVsSprite.clear();
We should clean TIL images as well. In this case we can call this function as `clear`. Also please put it under the namespace above.

2021-03-30 14:44 UTC, ihhub commented on src/engine/screen.h
> +#if CAN_OVERRIDE_RENDERING
Could we please avoid using macros her? Could you please explain the intention of this change?

2021-03-31 01:29 UTC, kant2002 commented on src/engine/screen.h
> +#if CAN_OVERRIDE_RENDERING
I have to provide custom display (renderer) and custom cursor for tests. Currently there no way to provide different display and cursor without changing how these objects constructed. There other way where I change existing way how to construct rendering pipeline, but I decide that this is less invasive way. These code needed only for tests, so I decide to not include it in production version

2021-03-31 03:23 UTC, kant2002 commented on src/fheroes2/agg/agg_image.cpp
> +        _icnVsSprite.clear();
This seems to be redundant right now.

2021-03-31 03:25 UTC, kant2002 commented on src/engine/screen.h
> +#if CAN_OVERRIDE_RENDERING
Look at the https://github.com/kant2002/fheroes2/blob/kant/example-tests/tests/fheroes2.tests/test.cpp#L67 how I currently manage to create tests

2021-04-02 05:30 UTC, ihhub commented on src/engine/screen.h
> +#if CAN_OVERRIDE_RENDERING
Let me please come up with a solution to replace a singleton or to support multiple instances of Display. I'm sure we could do this in non-hacky way :)

2021-04-07 07:13 UTC, kant2002 commented
From Discord discussion
- @ihhub : actually we need to replace renderEngine instead of Display as display is just an image

2021-04-07 12:45 UTC, ihhub commented
I'm closing this pull request as we merge similar code for the same problem.

2021-04-07 12:45 UTC, closed without merging