Make recruitment of heroes more random
ihhub/fheroes2 pull request #3054
Opened 2021-03-29 19:34 UTC by oleg-derevenetz

fix #1315

2021-03-29 22:06 UTC, idshibanov commented on src/fheroes2/kingdom/kingdom.cpp
> +        recruits.SetHero1( world.GetFreemanHeroes() );
I think actual condition here should be a bit more complicated. When new game is started 1st recruit is guaranteed to be of the same race. Once bought it is indeed random.

2021-03-29 22:33 UTC, oleg-derevenetz commented
Hi @idshibanov

> When new game is started 1st recruit is guaranteed to be of the same race.

Hmm, I thought that such guarantees exist only for starting (already hired) hero... Well, then yes, logic should be more complicated. I'll rework this.

2021-03-31 00:54 UTC, idshibanov approved these changes

2021-03-31 14:57 UTC, ihhub requested changes
Hi @oleg-derevenetz , only one small optimization is required. Could you please take a look?

2021-03-31 14:57 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +    const bool preferNative = recruits.GetID1() == Heroes::UNKNOWN && recruits.GetID2() == Heroes::UNKNOWN;
Please put this variable under the if-condition below as it effects only that code.

2021-03-31 15:34 UTC, merged

2021-03-31 15:36 UTC, ihhub commented
@oleg-derevenetz , good job! A bunch of thanks for fixing this bug!