Double shadow
ihhub/fheroes2 pull request #3061
Opened 2021-03-30 15:58 UTC by vasilenkoalexey

Remove double shadow.

2021-04-02 16:15 UTC, ihhub requested changes
Hi @vasilenkoalexey , I left multiple comments here. Could you please take a look?

2021-04-02 16:15 UTC, ihhub commented on src/fheroes2/heroes/heroes_move.cpp
> +            if ( Maps::isValidDirection( centerIndex, direction ) ) {
All these 3 conditions could be combined into one if.

2021-04-02 16:15 UTC, ihhub commented on src/fheroes2/heroes/heroes_move.cpp
> +                int32_t directionIndex = Maps::GetDirectionIndex( centerIndex, direction );
Could you please make this variable `const`?

2021-04-02 16:15 UTC, ihhub commented on src/fheroes2/heroes/heroes.h
> +    int32_t DrawObjectsOnDirectionBottomIndex() const;
Instead of having multiple variable and a bunch of methods why don't we declare a structure to hold all this data and return a reference to it during drawing? In this case we will have only one call which will be faster.

2021-04-02 16:15 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +                        const int object0 = tile0.GetObject();
Please name it without extra numbers. Also could you please add a comment above this loop explaining what we are doing here?

2021-04-02 16:15 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +                    }
This code will be optimized while using a structure.

2021-04-02 16:15 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +            if ( hero ) {
To save spacing and increase readability we can do like this:
```
if ( hero == nullptr )
    conitinue;
...
// the rest of the code
``.

2021-04-02 16:15 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +    for ( auto it = drawList.cbegin(); it != drawList.cend(); ++it ) {
Could we please use normal indexing loop here and then later we just use indexing as well? Working with iterators here might be a bit overkill.

2021-04-02 16:15 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +                    for ( auto it0 = it + 1; it0 != drawList.cend(); ++it0 ) {
How big could `drawList` be?

2021-04-04 05:38 UTC, ihhub requested changes
Hi @vasilenkoalexey , I left few comments here. Would you mind to take a look?

2021-04-04 05:38 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.h
> +bool SkipRedrawTileBottom4Hero( const uint8_t tileset, const uint8_t icnIndex, const int passable );
This function is used only on one file - `heroes_move.cpp`. Could you please move it into unnamed namespace of this file?
Right now this function is within global namespace which should be avoidable.

2021-04-04 05:38 UTC, ihhub commented on src/fheroes2/heroes/heroes.h
> +    struct RedrawIndex _redrawIndex;
Please remove keyword `struct`. C++ does not need this.

2021-04-04 05:38 UTC, ihhub commented on src/fheroes2/heroes/heroes.h
> -    void RedrawShadow( fheroes2::Image & dst, int32_t dx, int32_t dy, const Rect & visibleTileROI, const Interface::GameArea & gamearea ) const;
Could we please revert this change as it brings no value to the code? It is always good to keep changes minimal.

2021-04-04 05:38 UTC, ihhub commented on src/fheroes2/heroes/heroes_move.cpp
> +void Heroes::UpdateObjects( const Maps::Tiles & tile )
Do this and `UpdateTop` modify or use any member of **Heroes** class? If not would it be better to make them as methods of newly created `RedrawIndex` structure as we modify only this structure's members?

2021-04-04 05:38 UTC, ihhub commented on src/fheroes2/heroes/heroes_move.cpp
> +    if ( MP2::OBJ_HEROES == object ) {
We could combine these 2 lines into one: `if ( tile.GetObject() == MP2::OBJ_HEROES ) {`

2021-04-04 11:59 UTC, vasilenkoalexey commented on src/fheroes2/maps/maps_tiles.h
> +bool SkipRedrawTileBottom4Hero( const uint8_t tileset, const uint8_t icnIndex, const int passable );
This function also used by `void Maps::Tiles::RedrawBottom4Hero` in `map_tiles.cpp`

2021-04-04 12:35 UTC, vasilenkoalexey commented on src/fheroes2/heroes/heroes_move.cpp
> +void Heroes::UpdateObjects( const Maps::Tiles & tile )
Yes, it is possible, but then we should move `InitDependencesTiles` too. On the other hand now all index values protected from modifying outside of `Heroes `class (because `Heroes::GetRedrawIndex()` return const). So, its mean if we move methods to `RedrawIndex `all members will be unprotected or we should again add `GetXXX `for each member.

2021-04-04 12:52 UTC, vasilenkoalexey commented on src/fheroes2/heroes/heroes_move.cpp
> +    if ( MP2::OBJ_HEROES == object ) {
I think we even dont need it if check only hero

2021-04-12 15:51 UTC, ihhub requested changes
Hi @vasilenkoalexey , here are few comments left. Could you please take a look into them?

2021-04-12 15:51 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +    for ( const int32_t index : drawList ) {
We could optimize this code by checking `drawTop` and `drawBottom` first:
```
if ( drawTop || drawBottom ) {
    for ( const int32_t index : drawList ) {
        const Maps::Tiles & tile = world.GetTiles( index );
        Heroes * hero = tile.GetHeroes();
        if ( hero == nullptr ) {
            continue;
        }

        const Point center = tile.GetCenter();
        // the rest of the code.
}
```

2021-04-12 15:51 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +                    drawList.emplace_back( tile.GetIndex() );
Could you please try to store `const Maps::Tiles &` in an array instead of indexes? I think it would be faster as now we do this:
- get tile index and store it in an array
- get tile index from the array and find tile from world

If we can store `const Maps::Tiles &` then we avoid one step which should be faster. Also we could consider storing pointers instead of references if needed.

What do you think?

2021-04-12 15:51 UTC, ihhub commented on src/fheroes2/heroes/heroes_move.cpp
> +    if ( MP2::OBJ_BOAT == object || MP2::OBJ_HEROES == object ) {
Could we please apply an opposite logic for early function return?
```
if ( MP2::OBJ_BOAT != object && MP2::OBJ_HEROES != object ) {
    return;
}

// the rest of the code.
```
Less complex code easier to read :)

2021-04-12 15:51 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.h
> +bool SkipRedrawTileBottom4Hero( const uint8_t tileset, const uint8_t icnIndex, const int passable );
Then please move it under `namespace Interface`. We should try to avoid global function exposure.

2021-04-12 15:51 UTC, ihhub commented on src/fheroes2/heroes/heroes.h
> +    const RedrawIndex & GetRedrawIndex() const;
Could you please move these methods to the same location as `Redraw` and `RedrawShadow` so it'll be more visibly grouped?

2021-04-12 15:51 UTC, ihhub commented on src/fheroes2/heroes/heroes.h
> +    void InitDependencesTiles();
Shall we call this method as `SetRedrawIndexes`?

2021-04-12 15:51 UTC, ihhub commented on src/fheroes2/heroes/heroes.h
> +    void UpdateTop( const Maps::Tiles & tile );
Shall we call it `UpdateRedrawTop`?

2021-04-12 15:51 UTC, ihhub commented on src/fheroes2/heroes/heroes.h
> +    void UpdateObjects( const Maps::Tiles & tile );
Shall we call it simple as `UpdateRedrawBottom`?

2021-04-12 15:51 UTC, ihhub commented on src/fheroes2/heroes/heroes_move.cpp
> +    _redrawIndex.topOnDirectionBottom = -1;
Could you please add here one empty line to visually separate 2 parts of the code?

2021-04-12 22:42 UTC, vasilenkoalexey commented
Hi @ihhub!

All your comments fixed now.

> Also we could consider storing pointers instead of references if needed.

I think we cant using "raw" pointers at least for `topList` and `objectList` because here we need correct redrawing order according to tile index.

2021-04-13 13:13 UTC, ihhub commented
> Hi @ihhub!
> 
> All your comments fixed now.
> 
> > Also we could consider storing pointers instead of references if needed.
> 
> I think we cant using "raw" pointers at least for `topList` and `objectList` because here we need correct redrawing order according to tile index.

Yes, that's correct. I was referring only to one container.

2021-04-13 15:54 UTC, ihhub commented
Hi @vasilenkoalexey , I tested the latest version and there is a problem with shadow below the hero:
![image](https://user-images.githubusercontent.com/19829520/114582764-7c18a100-9cb3-11eb-88fe-ef4d1a337b1e.png)

2021-04-13 17:56 UTC, vasilenkoalexey commented
> there is a problem with shadow below the hero:

Fixed now. All similar cases can be fixes by just adding indexes to `SkipRedrawTileBottom4Hero` in future PRs.

2021-04-14 04:38 UTC, merged

2021-04-14 04:38 UTC, ihhub commented
@vasilenkoalexey , thank you so much for fixing these important issues!