Randomize attack position choice
ihhub/fheroes2 pull request #3065
Opened 2021-03-31 05:53 UTC by idshibanov

Adding a way to share random device.

2021-04-02 16:24 UTC, ihhub requested changes
Hi @idshibanov , could you please take a look at 2 given comments?

2021-04-02 16:24 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +    Rand::Shuffle( tiles );
Shall we then fix this call for `puzzle.cpp` as well?

2021-04-02 16:24 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> -        const Indexes & around = Board::GetAroundIndexes( defender );
Is it correct that with big change a monster will attack from a random position?

2021-04-02 16:48 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> -        const Indexes & around = Board::GetAroundIndexes( defender );
It will still filter positions later on and select only the best one. Shuffle only matters when monster can attack from all sides (e.g. flyer). Right now they are always going from top-left clockwise which is very predictable.

You can see an example of current behavior in #2750.

2021-04-02 16:50 UTC, idshibanov commented on src/fheroes2/world/world.cpp
> +    Rand::Shuffle( tiles );
Sure! It didn't come up on my code search for some reason.

2021-04-03 12:09 UTC, merged

2021-04-03 12:09 UTC, ihhub commented
@idshibanov , thank you very much for making AI even more smarter!