Make Game::ObjectFadeAnimation synchronous to perform events in the correct order
ihhub/fheroes2 pull request #3081
Opened 2021-04-02 01:45 UTC by oleg-derevenetz

fix #3074
fix #1151

Needs to be thoroughly tested on different types of disappearing objects (neutral armies, resources, artifacts, chests, jails, barriers, flotsams, shipwreck survivors, and so on, as well as boats in case of "Summon Boat" spell).

2021-04-02 16:27 UTC, ihhub commented
Hi @oleg-derevenetz , is it ready for review?

2021-04-02 16:34 UTC, oleg-derevenetz commented
Hi @ihhub Yes, I think so. There were just minor style changes recently. But I don't think that this PR should be merged in 0.9.2, it should be tested first.

2021-04-05 15:36 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left multiple comments in relation to type conversion. Also I quickly tested the version and I found that after a battle we display an incorrect monster frame disappering on the map. On the screenshot I attacked Pikemen:
![image](https://user-images.githubusercontent.com/19829520/113592345-9cb77a00-9667-11eb-8c34-dc8e1c7303ac.png)

2021-04-05 15:36 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +            const uint32_t tileIdx = tile.GetIndex();
`GetIndex` returns **int32_t**. Here we are introducing compilation warning.

2021-04-05 15:36 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +    const uint32_t tileIdx = tile.GetIndex();
`GetIndex` returns **int32_t**. Here we are introducing compilation warning.

2021-04-05 15:36 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +        const uint32_t tileIdx = tile.GetIndex();
`GetIndex` returns **int32_t**. Here we are introducing compilation warning.

2021-04-05 15:36 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +        const uint32_t tileIdx = tile.GetIndex();
`GetIndex` returns **int32_t**. Here we are introducing compilation warning.

2021-04-05 15:36 UTC, ihhub commented on src/fheroes2/game/game.cpp
> +void Game::ObjectFadeAnimation::PerformFadeTask( uint8_t object, uint32_t fromIndex, uint32_t toIndex, bool fadeOut, bool fadeIn )
Tile indexes are `int32_t` type. Could you please change them?

2021-04-05 15:36 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +            const uint32_t tileIdx = tile.GetIndex();
and actually in the rest of places as well.

2021-04-05 17:01 UTC, oleg-derevenetz commented
Hi @ihhub

> Tile indexes are int32_t type. Could you please change them?

That's probably because Tiles::maps_index is uint32_t. So if we change signedness here, we will get a warning in another place.

2021-04-07 15:53 UTC, merged

2021-04-07 15:53 UTC, ihhub commented
@oleg-derevenetz , thank you so much for fixing these issues!