Hero info window, "Blood" morale shouldn't include exclamation mark
ihhub/fheroes2 pull request #3105
Opened 2021-04-04 10:06 UTC by shprotru

Fix for #3098

2021-04-05 16:04 UTC, ihhub commented on src/fheroes2/heroes/heroes_indicator.cpp
> +        StringReplace( str, "%{morale}", moraleStr );
What do you think about this solution:
```
std::string str = _( "%{morale} Morale" );
StringReplace( str, "%{morale}", Morale::String( morale ) );
StringReplace( str, "!", "" );
```
?

2021-04-05 18:38 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_indicator.cpp
> +        StringReplace( str, "%{morale}", moraleStr );
Wouldn't it be better to modify Morale::String() to return different strings depending on who they are intended for? Just replace an exclamation mark isn't enough in Spanish language, for example, because they have inverted variants of question and exclamation marks (for example "Hello!" is "¡Hola!" in Spanish).

2021-04-06 00:05 UTC, ihhub commented on src/fheroes2/heroes/heroes_indicator.cpp
> +        StringReplace( str, "%{morale}", moraleStr );
Honestly, I don't see that this exclamation mark presence is an issue at all. We have other place where we use Morale::String() with exclamation mark. By right String function must return something proper without doing some hacks like here.

2021-04-12 16:23 UTC, ihhub requested changes

2021-04-12 16:23 UTC, ihhub commented on src/fheroes2/heroes/heroes_indicator.cpp
>          std::string str = _( "%{morale} Morale" );
I think the best solution in this case is to add a corner case:
```
if ( morale == Morale::BLOOD ) {
    return _( "Blood Morale" );
}
else {
    std::string str = _( "%{morale} Morale" );
    StringReplace( str, "%{morale}", Morale::String( morale ) );
}
```

2021-04-14 04:46 UTC, merged

2021-04-14 04:46 UTC, ihhub commented
@shprotru , thanks a lot for fixing this issue!