Fix for the #3117
ihhub/fheroes2 pull request #3119
Opened 2021-04-07 09:28 UTC by kant2002

2021-04-07 09:29 UTC, kant2002 commented
I place test separately https://github.com/kant2002/fheroes2/commit/782d6c86304f670fb591c659e53d09527de9c864 until Test project lands in main branch.

2021-04-07 13:59 UTC, ihhub requested changes

2021-04-07 13:59 UTC, ihhub commented on src/fheroes2/heroes/skill.cpp
> +        const uint32_t necroCount = std::max( Skill::GetNecromancyPercent( hero ), count );
Could you please verify this check with Spade of Necromancy artifact as well as built Shrines? I think this will not work. The correct solution should be
```
Skill::GetNecromancyPercent( hero ) - hero.GetSecondaryValues( Skill::Secondary::NECROMANCY ) + count;
```

2021-04-09 14:02 UTC, kant2002 commented on src/fheroes2/heroes/skill.cpp
> +        const uint32_t necroCount = std::max( Skill::GetNecromancyPercent( hero ), count );
Seems to be correct. If hero `PickupArtifact` `Artifact::SPADE_NECROMANCY` then message with proposed fix produced `Basic Necromancy (+1) allows 20 percent of the creatures killed in combat to be brought back from the dead as Skeletons.` which seems to be right.

2021-04-09 14:05 UTC, kant2002 commented on src/fheroes2/heroes/skill.cpp
> +        const uint32_t necroCount = std::max( Skill::GetNecromancyPercent( hero ), count );
Add one more test in kant2002@b5f72fd9

2021-04-10 02:29 UTC, merged

2021-04-10 02:30 UTC, ihhub commented
@kant2002 , thank you so much for fixing this bug!