Don't allow the player to scroll world map while hero is moving
ihhub/fheroes2 pull request #3123
Opened 2021-04-07 14:39 UTC by oleg-derevenetz

fix #1159

Also fixes an issue when cursor isn't turned into Cursor::WAIT when hotkey is used to start the hero's movement.

2021-04-07 16:04 UTC, oleg-derevenetz commented
Hi @ihhub I removed that small delay before starting scrolling using mouse pointer, if you think that it's needed for something, I'll revert it back.

2021-04-11 15:42 UTC, ihhub commented
> 
> 
> Hi @ihhub I removed that small delay before starting scrolling using mouse pointer, if you think that it's needed for something, I'll revert it back.

Hi @oleg-derevenetz , please revert it back. We need it to avoid immediate scrolling when player click near the edge of the screen. Otherwise, it's very difficult to to manage.

2021-04-14 13:29 UTC, ihhub requested changes

2021-04-14 13:42 UTC, Branikolog commented on src/fheroes2/game/game_startgame.cpp
> +                continue;
In the OG animation proceeds, while scrolling.
Stopping it can be noticeable on low scrolling speeds...

2021-04-14 14:32 UTC, oleg-derevenetz commented on src/fheroes2/game/game_startgame.cpp
> +                continue;
Hi @ihhub this continue is already there in the current version. I thought it is here for a reason. Should I remove it?

2021-04-14 14:35 UTC, oleg-derevenetz commented on src/fheroes2/game/game_delays.cpp
> +                           500, // SCROLL_START_DELAY
Delay of 20ms is barely noticeable. May be something between?

2021-04-14 15:48 UTC, oleg-derevenetz commented on src/fheroes2/game/game_startgame.cpp
> +                continue;
Hi @ihhub @Branikolog I just checked - it doesn't stop the animation of objects. They have time to animate in the period of those SCROLL_DELAY ms as it happens in the current version of the corresponding code.

2021-04-14 17:05 UTC, oleg-derevenetz commented
Hi @ihhub

> Please reduce this value to 20. RIght now the overall delay takes 1 second.

Well, in fact it's between 500ms and 1s :) But I agree that it may be too long. On the other hand, 20ms is barely noticeable - like no delay at all. I changed it to 250, please try it again, it it still too long, I can change it to 100.

> By doing this we're stopping animation of objects on map while scrolling.

Although it's not really the case - it doesn't stop the animation of objects (they have time to animate in the period of those SCROLL_DELAY ms as it happens in the current version of the corresponding code with the same `continue` after `render()`) it really seems useless, so I removed it.

2021-04-18 04:35 UTC, ihhub commented
Let's ask an expert in the game:
@LeHerosInconnu, could you please tell what's the delay before starting scrolling in the original game?

2021-04-18 06:57 UTC, oleg-derevenetz commented
Hi @ihhub BTW I never used consoles, how accurate is the mouse emulation on them in relation to this PR? How likely is it to miss the pointer near edges?

2021-04-18 08:46 UTC, ihhub commented
> Hi @ihhub BTW I never used consoles, how accurate is the mouse emulation on them in relation to this PR? How likely is it to miss the pointer near edges?

I don't have any consoles to test but @Northfear can shed a light on this question.

2021-04-18 12:42 UTC, LeHerosInconnu commented
Hello @ihhub,

> Let's ask an expert in the game:
> @LeHerosInconnu, could you please tell what's the delay before starting scrolling in the original game?

In the original game, there is no noticeable delay.

In original game:

https://user-images.githubusercontent.com/43583994/115145806-c2735480-a053-11eb-949e-f7f22e01be4c.mp4

2021-04-18 12:55 UTC, oleg-derevenetz commented
Well, let's make no noticeable delay then :)

2021-04-19 11:53 UTC, merged

2021-04-19 11:54 UTC, ihhub commented
@oleg-derevenetz , thanks a lot for fixing this bug!