implement new necromancy window
ihhub/fheroes2 pull request #3150
Opened 2021-04-11 03:19 UTC by eos428

Solves #1497 and #1498

Some examples of the new necromancy window:

![Screenshot 2021-04-11 101805](https://user-images.githubusercontent.com/38433056/114291158-69357f00-9aaf-11eb-9582-edf2ab61857d.jpg)
![Screenshot 2021-04-11 101752](https://user-images.githubusercontent.com/38433056/114291164-6cc90600-9aaf-11eb-98a2-2a13ff433500.jpg)

2021-04-11 07:59 UTC, oleg-derevenetz commented
Hi @eos428

> Solves #1497 and #1498

There is a [very handy syntax](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to link issues and pull requests, I use it all the time :) Linked issues will be automatically closed as soon as linked pull request is merged.

2021-04-11 08:55 UTC, eos428 commented
Hi @oleg-derevenetz, thanks for the tip! I linked those issues via those keywords now.

2021-04-12 16:10 UTC, ihhub requested changes
Hi @eos428 , I left multiple comments here. Would you mind to take a look?

2021-04-12 16:10 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    cursor.Show();
Do we need this line? What will happen if we remove it?

2021-04-12 16:10 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    LocalEvent & le = LocalEvent::Get();
Please declare variable just where they are going to be used (near the loop).

2021-04-12 16:10 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    const bool isEvilInterface = conf.ExtGameEvilInterface();
This variable should be defined before line 584 and should be used at lines 584-585.

2021-04-12 16:10 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    const bool isEvilInterface = conf.ExtGameEvilInterface();
After this change `conf` will be used only in one place so we could change this line into `const bool isEvilInterface = Settings::Get().ExtGameEvilInterface();`

2021-04-12 16:10 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    const int anime_oy = 36;
Please use camelCase variable naming. Also you could use `fheroes2::Point` to store this data.

2021-04-12 16:10 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    fheroes2::Display & display = fheroes2::Display::instance();
Please move this declaration at line 586.

2021-04-12 16:10 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    cursor.SetThemes( Cursor::POINTER );
If we're going to remove `cursor.Show();` code then we don't need to declare **cursor** variable modifying this code into `Cursor::Get().SetThemes( Cursor::POINTER );`.

2021-04-12 16:10 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    TextBox titleBox( title, Font::YELLOW_BIG, bsTextWidth );
We could directly use the string here: `TextBox titleBox( _( "Necromancy!" ), Font::YELLOW_BIG, bsTextWidth );` without extra variable declaration.

2021-04-12 16:10 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    StringReplace( msg, "%{monster}", mons.GetPluralName( raiseCount ) );
Please move these lines before line 617 so it will be easier to read the code.

2021-04-12 16:10 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +        sequence.push( ICN::UNKNOWN, false );
Please move this code before line 599 to group the code by logic of execution.

2021-04-12 16:10 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    fheroes2::Blit( monsterSprite, display, ( display.width() - monsterSprite.width() ) / 2, yOffset += ( messageBox.h() + monsterSprite.height() ) );
Please do not combine 2 separate operations into one call. It is really hard to understand what `yOffset += ( messageBox.h() + monsterSprite.height() )` value this operation will return.

2021-04-12 16:10 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    messageBox.Blit( xOffset, yOffset += bsTextIndent );
Please do not combine 2 separate operations into one call. It is really hard to understand what `yOffset += bsTextIndent` value this operation will return.

2021-04-13 12:35 UTC, eos428 commented on src/fheroes2/battle/battle_dialogs.cpp
> +    cursor.SetThemes( Cursor::POINTER );
Overall it doesn't seem like we need any cursor-related logics as they are done in `DialogBattleSummary` which precedes this window. So I'll be removing calls to cursor in this function.

2021-04-13 12:38 UTC, eos428 commented on src/fheroes2/battle/battle_dialogs.cpp
> +    TextBox titleBox( title, Font::YELLOW_BIG, bsTextWidth );
At the moment it doesn't seem like we can `Blit` with a const `TextBox` so I'll be keeping this non-const for now.

2021-04-13 16:25 UTC, merged

2021-04-13 16:25 UTC, ihhub commented
@eos428 , huge thanks for adding this feature to the project!