Fog optimization
ihhub/fheroes2 pull request #3176
Opened 2021-04-14 10:45 UTC by vasilenkoalexey

Minor fog drawing optimization

2021-04-22 13:35 UTC, ihhub commented
Hi @vasilenkoalexey , the complexity of this implementation in a normal scenario when hero moves makes the drawings even slower as for each tile we're going to check `isFog` 9 times. Please correct me about this.

2021-04-22 14:46 UTC, vasilenkoalexey commented
> Hi @vasilenkoalexey , the complexity of this implementation in a normal scenario when hero moves makes the drawings even slower as for each tile we're going to check `isFog` 9 times. Please correct me about this.

The main part of the implementation

```
if ( drawFog && tile.isFog( colors ) ) {
  // don't redraw tile if fog all around
  fogList.emplace_back( tile );
  if ( tile.isFogAllAround( colors ) ) {
    continue;
  }
}
```
We call `tile.isFogAllAround()` if and only if` tile.isFog() == true`. It doesn't matter if there is a moving or not moving hero in the tile or not. If `tile.isFog() == true` and `tile.isFogAllAround() == true` we dont redraw whole tile, but yes, we call `isFog()` additional 8 times instead, and i am shure it should be mach faster then full tile redrawing.
On the other hand, if no fog on screen, we call `isFog()` once per tile, but without these additional loops 
```
for ( int32_t y = minY; y < maxY; ++y ) {
  for ( int32_t x = minX; x < maxX; ++x ) {
     const Maps::Tiles & tile = world.GetTiles( x, y );
     if ( tile.isFog( colors ) )
       tile.RedrawFogs( dst, colors, *this );
   }
 }
```
So, even in this case drawing will be faster

2021-05-17 04:05 UTC, ihhub commented
Hi @vasilenkoalexey , could you please resolve conflicts for this pull request?

2021-05-18 13:23 UTC, vasilenkoalexey commented
> Hi @vasilenkoalexey , could you please resolve conflicts for this pull request?

Done

2021-05-18 14:23 UTC, ihhub requested changes
Hi @vasilenkoalexey , I left few comments here. Could you please take a look?

2021-05-18 14:23 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +            const fheroes2::Point mp( x, y );
Please remove this unused variable.

2021-05-18 14:23 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +    const int colors = Players::FriendColors();
Could we please call it as `friendColors` since we do refactoring? In this case it'd be very obvious for reader to know what this variable means.

2021-05-18 14:23 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +            }
This block should be ignored for debug mode when we do not draw fog at all.

2021-05-18 14:23 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +            }
We could consider to use a boolean variable before the loop to check like this:
```
bool drawFog = true;
#ifdef WITH_DEBUG
drawFog = !IS_DEVEL();
#endif
```
and then use the check later in the code include existing `if ( IS_DEVEL() ) {` place.

2021-05-18 14:23 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +            }
Oh, since we already have the variable then let's do like this:
```
#ifdef WITH_DEBUG
const bool drawFog = ( ( flag & LEVEL_FOG ) == LEVEL_FOG ) && !IS_DEVEL();
#else
const bool drawFog = ( flag & LEVEL_FOG ) == LEVEL_FOG;
#endif
```

2021-05-18 20:47 UTC, vasilenkoalexey commented
> Hi @vasilenkoalexey , I left few comments here. Could you please take a look?

Done!

2021-05-19 05:10 UTC, merged

2021-05-19 05:11 UTC, ihhub commented
@vasilenkoalexey , huge thanks for improving this code!