More double shadow
ihhub/fheroes2 pull request #3211
Opened 2021-04-16 21:07 UTC by vasilenkoalexey

Fix another double shadow
![s1](https://user-images.githubusercontent.com/24250224/115083968-dcf0e500-9f10-11eb-8436-109b626ffb27.png)

2021-05-17 03:58 UTC, ihhub requested changes
Hi @vasilenkoalexey , there are few comments. Could you please take a look and also rebase your branch from master as we made some changes which might impact compilation?

2021-05-17 03:58 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.cpp
> +    return Maps::Tiles::isShadowSprite( icn, icnIndex );
I assume that the only place which is fixing the problem is this method where we swap the order of checking the conditions. Is it correct?

2021-05-17 03:58 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.cpp
> +bool Maps::Tiles::isShadowSprite( const int icn, const uint8_t icnIndex )
Since we introduced overloaded method please make changes in `Exclude4LongObject` function as well.

2021-05-17 03:58 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.cpp
> +    return Tiles::isShadowSprite( MP2::GetICNObject( tileset ), icnIndex );
Please remove `Tiles::` as we're calling a method within the same namespace/class.

2021-05-17 12:02 UTC, vasilenkoalexey commented on src/fheroes2/maps/maps_tiles.cpp
> +    return Maps::Tiles::isShadowSprite( icn, icnIndex );
We just replace partial shadow sprites checks by `isShadowSprite` wich cover all shadow sprites and cover all double shadow cases near hero and another object.

2021-05-17 12:34 UTC, vasilenkoalexey commented on src/fheroes2/maps/maps_tiles.cpp
> +    return Tiles::isShadowSprite( MP2::GetICNObject( tileset ), icnIndex );
Done

2021-05-17 12:34 UTC, vasilenkoalexey commented on src/fheroes2/maps/maps_tiles.cpp
> +bool Maps::Tiles::isShadowSprite( const int icn, const uint8_t icnIndex )
Done

2021-05-18 14:07 UTC, merged

2021-05-18 14:07 UTC, ihhub commented
@vasilenkoalexey , thank you so much for fixing this issue!