Use XDG directories
ihhub/fheroes2 pull request #3218
Opened 2021-04-17 15:07 UTC by qarkai

Use `$XDG_CONFIG_HOME/fheroes2`on Linux (`~/.config/fheroes2` by default) for `fheroes2.bin`, `fheroes2.cfg`.
Use `$XDG_DATA_HOME/fheroes2` on Linux (`~/.local/share/fheroes2` by default) for `data`, `files/save`, `maps`.
On other platforms use directory returned by `System::GetHomeDirectory`.
Close #2860.

2021-04-17 15:59 UTC, oleg-derevenetz commented
Hi @qarkai Great, thanks! There is also `demo_linux.sh` script from `script/demo`, maybe adopt it to XDG paths as well?

2021-04-18 04:48 UTC, ihhub requested changes
Hi @qarkai , I left multiple comments in this pull request. Could you please take a look?

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.cpp
> +            res = System::ConcatePath( System::GetEnvironment( "HOME" ), std::string( "." ).append( prog ) );
Please directly return from here without assigning to another variable.

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.cpp
> +            res = System::ConcatePath( System::GetEnvironment( "APPDATA" ), prog );
Please directly return from here without assigning to another variable.

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.cpp
> +    res = GetHomeDirectory( prog );
Please directly return from here without assigning to another variable.

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.cpp
> +    auto config_env = System::GetEnvironment( "XDG_CONFIG_HOME" );
Please use `camelCase` variable naming.

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.cpp
> +        auto home_env = System::GetEnvironment( "HOME" );
Please use `camelCase` variable naming.

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.cpp
> +            res = System::ConcatePath( System::ConcatePath( home_env, ".config" ), prog );
Please directly return from here without assigning to another variable.

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.cpp
> +        res = System::ConcatePath( config_env, prog );
Please directly return from here without assigning to another variable.

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.cpp
> +    std::string res;
I think there is no need to declare this variable. BY the end of the function we could return `std::string();`.

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.cpp
> +    auto data_env = System::GetEnvironment( "XDG_DATA_HOME" );
Please use `camelCase` variable naming.

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.cpp
> +        auto home_env = System::GetEnvironment( "HOME" );
Please use `camelCase` variable naming.

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.cpp
> +        res = System::ConcatePath( data_env, prog );
Please directly return from here without assigning to another variable.

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.cpp
> +            res = System::ConcatePath( System::ConcatePath( home_env, ".local/share" ), prog );
Please directly return from here without assigning to another variable.

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.cpp
> +    res = GetHomeDirectory( prog );
Please directly return from here without assigning to another variable.

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.h
> +    std::string GetDataDirectory( const std::string & );
Please add input parameter names. Old project was using this weird standard. We should always declare names in definition.

2021-04-18 04:48 UTC, ihhub commented on src/fheroes2/game/fheroes2.cpp
> +void InitDataDir( void );
Please remove `void` as an input parameter. It's old style.

2021-04-18 04:48 UTC, ihhub commented on src/fheroes2/game/fheroes2.cpp
> +    const std::string config_dir = System::GetConfigDirectory( "fheroes2" );
Please use `camelCase` variable naming.

2021-04-18 04:48 UTC, ihhub commented on src/fheroes2/game/fheroes2.cpp
> +    const std::string data_dir = System::GetDataDirectory( "fheroes2" );
Please use `camelCase` variable naming.

2021-04-18 04:48 UTC, ihhub commented on src/fheroes2/game/fheroes2.cpp
> +    const std::string data_files_save = System::ConcatePath( data_files, "save" );
Please use `camelCase` variable naming.

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.cpp
> +        auto home_env = System::GetEnvironment( "HOME" );
Please use `const char *` as this is just a base type.

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.cpp
> +    auto config_env = System::GetEnvironment( "XDG_CONFIG_HOME" );
Please use `const char *` as this is just a base type.

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.cpp
> +    auto data_env = System::GetEnvironment( "XDG_DATA_HOME" );
Please use `const char *` as this is just a base type.

2021-04-18 04:48 UTC, ihhub commented on src/engine/system.cpp
> +        auto home_env = System::GetEnvironment( "HOME" );
Please use `const char *` as this is just a base type.

2021-04-18 11:47 UTC, qarkai commented
> Hi @qarkai , I left multiple comments in this pull request. Could you please take a look?

Made changes. Don't know hot to "close" changes request though.

2021-04-18 11:48 UTC, ihhub commented
> > Hi @qarkai , I left multiple comments in this pull request. Could you please take a look?
> 
> Made changes. Don't know hot to "close" changes request though.

There's no need to close them. Resolving them is enough :)

2021-04-22 07:09 UTC, karolchmist commented
I tested this branch when building `fheroes2` for [NixOS](https://nixos.org/), it works great :+1: Hoping to see it in `0.9.3` release.

2021-04-22 14:10 UTC, ihhub commented on src/engine/system.cpp
> +            return System::ConcatePath( System::GetEnvironment( "APPDATA" ), prog );
This change forces Windows to load files from `C:\Users\UserName\AppData\Roadming\fheroes2` path. Is it intentional?

2021-04-22 14:21 UTC, ihhub reviewed
Hi @qarkai , I left two questions. Could you please take a look?

2021-04-22 14:21 UTC, ihhub commented on src/engine/system.cpp
> +        return "ux0:data/fheroes2";
This path is defined in `AddOSSpecificDirectories` as well.

2021-04-22 14:27 UTC, qarkai commented on src/engine/system.cpp
> +            return System::ConcatePath( System::GetEnvironment( "APPDATA" ), prog );
I'm not sure how to respond. Saves, fheroes2.bin and fheroes2.cfg are written to `AppData\Roaming\fheroes2` dir. It was intentional.
Data and maps are loaded from `Settings::GetRootDirs` directories. That shouldn't have changed.

2021-04-22 14:30 UTC, ihhub commented on src/engine/system.cpp
> +            return System::ConcatePath( System::GetEnvironment( "APPDATA" ), prog );
I got a created `maps` directory under `AppData\Roaming\fheroes2` as well. Saves and configuration files are okay to store there.

2021-04-22 14:36 UTC, qarkai commented on src/engine/system.cpp
> +            return System::ConcatePath( System::GetEnvironment( "APPDATA" ), prog );
This is due to `InitDataDir()`. But I didn't change this behavior. It was there in `InitHomeDir()`. Do you want me to remove creation of `maps` directory?

2021-04-22 14:53 UTC, qarkai commented on src/engine/system.cpp
> +        return "ux0:data/fheroes2";
Also `ux0:data/fheroes2` is defined in `Settings::Save()`. If `__LINUX__` is not defined for PS Vita build then that method could be simplified.
As for `Settings::GetRootDirs()` as the only caller of `AddOSSpecificDirectories()` I'd suggest using temporary `unordered_set` to exclude duplicated paths.

2021-04-22 15:43 UTC, ihhub commented on src/engine/system.cpp
> +            return System::ConcatePath( System::GetEnvironment( "APPDATA" ), prog );
Yes, please. We shouldn't create `maps` under this path but where `data` is for Windows.

2021-04-22 15:44 UTC, ihhub commented on src/engine/system.cpp
> +        return "ux0:data/fheroes2";
Hmm... Maybe leave it as it is for now.

2021-05-03 13:52 UTC, ihhub commented
Hi @qarkai , I think @Branikolog has a point regarding Windows systems. Putting files somewhere outside initial directory might be misleading for users.

2021-05-03 14:28 UTC, qarkai commented
Hi @ihhub, I believe that user's files should be kept in user's directories. Consider two people sharing config and saves directory on a computer when one prefers good interface and other prefers evil one.
Configuration file location could be placed in readme/FAQ.
Also let be honest: this project is for geeks and they usually know where their files could be and even expect that.

2021-05-03 14:55 UTC, ihhub commented
@qarkai , actually the biggest majority of our users are on Windows and they aren't expecting files to be stored anywhere else except the folder where the archive is extracted. Also based on the feedback from Linux based forums many users face problems of running the application so I would say geeks is too much.
Every project should be as much as possible user friendly without assumptions of high OS level from users.

2021-05-03 15:00 UTC, ihhub commented
The best way is to ask our team to avoid any one side opitions :)

@oleg-derevenetz , @LeHerosInconnu and @idshibanov  could you please give us your opinion as well?

2021-05-03 15:07 UTC, karolchmist commented
Just my 0.02¢ as a geeky Linux user :) Why not checking all the possible locations: first current dir, then XDG dirs? Plus a config option to specify it if needed. This way everyone should be happy.

2021-05-03 15:39 UTC, ihhub commented
> Just my 0.02¢ as a geeky Linux user :) Why not checking all the possible locations: first current dir, then XDG dirs? Plus a config option to specify it if needed. This way everyone should be happy.
> 
> (On NixOS Linux we can't use the current dir)

I totally agree with you. For example, I have Ubuntu machine and I am totally fine to keep all files within the same directory.

2021-05-03 15:43 UTC, qarkai commented
@karolchmist The problem is with different directories for config and saves. If we search for writeable directory then all files go to which is first in directories list. I believe that config files should be in config dir, since they could be easily regenerated and reconfigured if configure dir is lost but saves should be in data dir.
@ihhub Maybe you should note that in #2860 and close it earlier.

2021-05-03 15:46 UTC, LeHerosInconnu commented
From the point of view of the average user, it's always better to have everything in one folder; and the majority of users are more average users than geeks.

And for some users, it's already complicated to have to search in subfolders. :D

2021-05-03 15:51 UTC, ihhub commented
@qarkai , my apologies for this as I need to maintain a lot of things so I came back to this pull request once I got time.

2021-05-03 17:43 UTC, undef21 commented
My some cents. Why not use both approaches?
Game can use different paths depending command line parameters or executable name. For example, if we start game `fheroes2 <game_dir>`, then game search and save all data in this dir. If game started without parameters then it use OS-specific paths.

2021-05-03 18:03 UTC, qarkai commented
@ihhub sorry, I didn't mean to be offensive, I really appreciate your work on this project.

2021-05-03 22:43 UTC, oleg-derevenetz commented
Hi all,

How about the following logic: if directory with `fheroes2` (or `fheroes2.exe`) binary is writeable by current user, then use it to load and store config files, maps and savefiles. Otherwise, use $HOME/$APPDATA. This should cover cases when user just downloaded ZIP archive with game files, unpacked it into some directory and run the game from it, as well as cases when game was installed by administrator or package manager into some global directory, like `C:\Program Files` on Windows or `/usr/bin` on Linux.

Additionally, it is possible to add command-line switch to manage this behavior explicitly, for example, `fheroes2 --user-data-dir=DIR` and mention this in the documentation.

2021-05-04 10:27 UTC, undef21 commented
> if directory with `fheroes2` (or `fheroes2.exe`) binary is writeable by current user, then use it to load and store config files, maps and savefiles.

In this case admins'll break OS-filesystem rules. Admins want to play too.

2021-05-04 10:33 UTC, oleg-derevenetz commented
> In this case admins'll break OS-filesystem rules. Admins want to play too.

Admins will break those rules only if they run app with elevated privileges (through UAC on Windows or as root on Linux). Normally they shouldn't do that.

2021-05-04 10:46 UTC, undef21 commented
Yes, it's unusual, but possible case. If game try to follow OS-specific rules, then it's better when all accounts follow same rules ( XDG for linux, %APPDATA% for win, something for *BSD).

Also, is there cross-platform way for getting program path? Because if we run fheroes2 from some PATH directory, then game can't detect program dir.

2021-05-04 18:31 UTC, oleg-derevenetz commented
> Yes, it's unusual, but possible case. If game try to follow OS-specific rules, then it's better when all accounts follow same rules ( XDG for linux, %APPDATA% for win, something for *BSD).

Then we should say bye-bye to per-user paths, at least on Windows. No ordinary user will bother to run `fheroes2.exe .`. He will just unpack ZIP archive and double-click on EXE.

2021-05-04 18:41 UTC, qarkai commented
BTW why it's ZIP instead of installer?

2021-05-04 19:01 UTC, oleg-derevenetz commented
Hi @qarkai

> BTW why it's ZIP instead of installer?

First of all, because nobody implemented installer yet :) Also, without support for per-user data paths, there was no reason to use installer so far.

2021-05-04 19:22 UTC, qarkai commented
@oleg-derevenetz I opened #3340 for tracking and discussion.

2021-05-15 14:14 UTC, qarkai commented
> Also, is there cross-platform way for getting program path? Because if we run fheroes2 from some PATH directory, then game can't detect program dir.

There is [`SDL_GetBasePath`](https://wiki.libsdl.org/SDL_GetBasePath) but it requires SDL 2.0.1.
Also there are a [bunch](https://stackoverflow.com/a/1024937/6771534) of platform-specific methods which could be wrapped in something like `System::GetProgramPath`.

2021-06-01 13:36 UTC, ihhub commented
Hi @qarkai , could you kindly please resolve merge conflicts as I can't do it by myself?

2021-06-01 15:20 UTC, ihhub commented
Hi @Northfear , could you please test these changes on PS Vita as well?

2021-06-01 17:00 UTC, oleg-derevenetz approved these changes

2021-06-02 11:58 UTC, Northfear commented
> 
> 
> Hi @Northfear , could you please test these changes on PS Vita as well?

Checked. Everything seems to be working fine

2021-06-02 13:55 UTC, ihhub commented
Hi @qarkai and @oleg-derevenetz , for `fheroes2.bin`, `fheroes2.cfg` and for `files/save` I have no objections to store outside the current directory but `maps` is a part of data files of the original game and they shouldn't be separate for each user. We have only one instance of the game which contains the executable files, resources files in `data`, `music`, `maps` and `Heroes2` (for animation) directories.

Let me please clarify things so everything will be aligned:
- we store data files such as `data`, `music`, `anim` and `maps` within the game's directory
- we cstore configuration files and saves outside the game's directory.

Please correct me if I'm wrong.

2021-06-02 14:00 UTC, oleg-derevenetz commented
Hi @ihhub suppose we have a multi-user system with unrelated users, and one of them bought original HoMM2 game, and the other is not. In this case, files of original game should be stored in user's directory.

2021-06-02 14:02 UTC, ihhub commented
> Hi @ihhub suppose we have a multi-user system with unrelated users, and one of them bought original HoMM2 game, and the other is not. In this case, files of original game should be stored in user's directory.

Is the original game installed per user? I use GOG version and everything installed out of C drive obviously.

2021-06-02 14:04 UTC, qarkai commented
Data files *could* be stored in user's directory. But nothing prevents from storing them in game's directory (or some common system directory on Linux if `CONFIGURE_FHEROES2_DATA` was used).

2021-06-02 14:08 UTC, ihhub commented
> Data files _could_ be stored in user's directory. But nothing prevents from storing them in game's directory (or some common system directory on Linux if `CONFIGURE_FHEROES2_DATA` was used).

If files _could_ be stored then we **should**. As a user I expect that all data files will be in the same directory where my installation is. At least in terms on Window's users. Having data files somewhere else might be odd for many.

2021-06-02 14:12 UTC, ihhub commented
> > Data files _could_ be stored in user's directory. But nothing prevents from storing them in game's directory (or some common system directory on Linux if `CONFIGURE_FHEROES2_DATA` was used).
> 
> If files _could_ be stored then we **should**. As a user I expect that all data files will be in the same directory where my installation is. At least in terms on Window's users. Having data files somewhere else might be odd for many.

Right now everything works as I described before: demo script downloads files to the same directory where fheroes2.exe locates. While configuration files are in user's directory which is fine.

2021-06-02 14:15 UTC, oleg-derevenetz commented
@ihhub

> Is the original game installed per user?

Original game is shipped as a whole with data files because owners have copyright for them. We don't have a rights to distribute data files, so I'd be careful here and let each user install it's own data files individually. Also, at one moment we should be able to provide fheroes2 packages, and individual data files are fit for this ideally (BTW, in Linux and MacOS shared data should reside somewhere in /usr/local/share anyway). But it's up to you. I personally see only gains from per-user data files: no copyright issues, one user may have full PoL, while another may have just a demo.

2021-06-02 14:15 UTC, qarkai commented
As a user I'd like to have opportunity storing **new** maps in my data directory thus avoiding UAC/sudo in order to write them in game's directory in `C:\Program Files` or `/usr/whatever`.
I kind of agree that `data`, `music`, `anim` should be in game's directory.

2021-06-02 14:39 UTC, merged

2021-06-02 14:39 UTC, ihhub commented
Hi @qarkai , thanks a lot for these changes!

I've decided to go with them as I feel that I'm dragging you guys with the implementation :)

2021-06-03 08:15 UTC, karolchmist commented
I built it on NixOS Linux and it works, thank you :+1: