add initial support of russian localization
ihhub/fheroes2 pull request #3258
Opened 2021-04-22 22:42 UTC by undef21

relates #3223

![Снимок экрана_2021-04-23_01-41-16](https://user-images.githubusercontent.com/71143197/115793602-14f69d00-a3d5-11eb-85d3-c8d12cf322ed.png)
![Снимок экрана_2021-04-23_01-34-41](https://user-images.githubusercontent.com/71143197/115793648-2b045d80-a3d5-11eb-9a69-d206aab1d919.png)
![Снимок экрана_2021-04-23_01-35-43](https://user-images.githubusercontent.com/71143197/115793655-2cce2100-a3d5-11eb-970e-3d78f2e7bd8d.png)

2021-04-24 02:18 UTC, ihhub requested changes
Hi @undef21 , here are few comments left. Could you please take a look?

2021-04-24 02:18 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                        icn[136] = icn[192];
If we are going to remove 192 element then we should call std::swap.

2021-04-24 02:18 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                        icn[152] = icn[225];
If we're going to remove 225 element then please call std::swap here to avoid extra memory copy.

2021-04-24 02:18 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                        icn.insert( icn.begin() + 96, 64, icn[0] );
Are we going to use these letters? Does element 0 contain a letter? If not then we should just populate the array with empty sprites.

2021-04-24 02:18 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                        icn.erase( icn.end() - 1 );
Please use pop_back call instead.

2021-04-24 17:09 UTC, undef21 commented on src/fheroes2/agg/agg_image.cpp
> +                        icn.insert( icn.begin() + 96, 64, icn[0] );
Element 0 used as common placeholder in local fonts not only in russian localization. This one have width. It may be usefull, for example, if user load map with foreign ecoding.

2021-04-25 02:05 UTC, ihhub requested changes
Hi @undef21 , I left few more comments regarding code optimization. Could you please check again?

2021-04-25 02:05 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                        std::swap( icn[152], icn[225] );
Should we do swapping and element removal before element insertion? In this case we'll save some CPU resources.

2021-04-25 02:05 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    if ( icn.size() == 162 ) {
I'd highly recommend to check the size of needed elements in the array to make that we're dealing with proper data. For example (numbers are random),
```
if ( imageArray.size() == 162 && imageArray[136].width() == 7 && imageArray[136].height() == 9 && imageArray[161].width() == 8 && imageArray[161].height() == 6 )
```
In this case we'll be more sure that we're dealing with CP1251 letters. Yes, the code looks uglier but prevents us from false positives.

2021-04-25 10:10 UTC, undef21 commented on src/fheroes2/agg/agg_image.cpp
> +                        std::swap( icn[152], icn[225] );
I think no because before insertion we don't have placeholders chars.

2021-04-25 10:11 UTC, undef21 commented on src/fheroes2/agg/agg_image.cpp
> +                    if ( icn.size() == 162 ) {
Done. Now we check position and width of the widthest char in font. Not all locales have so big char.

2021-04-25 11:04 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                        std::swap( icn[152], icn[225] );
We don't need them. We just swap characters first as they exist in the array of images, remove the last one, remove the middle one and then add N characters at the front. In this case insertion will be faster as we don't need to copy 2 extra characters/images.

2021-04-25 12:47 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    std::swap( imageArray[0xB8 - 0x20], imageArray[161 + 0xC0 - 0x80] ); //
Is this comment missed?

2021-04-25 13:42 UTC, undef21 commented on src/fheroes2/agg/agg_image.cpp
> +                        std::swap( icn[152], icn[225] );
Sorry for misunderstanding.
Currently we do next steps:
letters array after load font.icn: 0x20-0x7F, 0xC0-0xDF, 0xA8, 0xE0-0xFF, 0xB8.
after inserting spaces: 0x20-0x7F, 64 spaces, 0xC0-0xDF, 0xA8, 0xE0-0xFF, 0xB8.
after two swapping: 0x20-0x7F, 40 spaces, 0xA8, 15 spaces, 0xB8, 7 spaces, 0xC0-0xDF, space, 0xE0-0xFF, space.
after removing single spaces: 0x20-0x7F, 40 spaces, 0xA8, 15 spaces, 0xB8, 7 spaces, 0xC0-0xFF.

Which characters we should swap before inserting?

2021-04-25 14:42 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                if ( imageArray.size() == 162 && ( imageArray[121].width() == 19 || imageArray[121].width() == 15 ) ) {
Could you please explain why we check width for 2 different values? Is the official localization only one?

2021-04-25 14:43 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    // Engine expects that letter indexes correspondes to charcode - 0x20.
Grammar correction `correspond`, plural form.

2021-04-25 14:58 UTC, undef21 commented on src/fheroes2/agg/agg_image.cpp
> +                if ( imageArray.size() == 162 && ( imageArray[121].width() == 19 || imageArray[121].width() == 15 ) ) {
This is widthes of letter 0xD9 for normal and small fonts. Reworked.

2021-04-25 15:57 UTC, merged

2021-04-25 15:57 UTC, ihhub commented
@undef21 , thank you very much for this feature!

2021-07-06 07:11 UTC, dimag0g commented
@undef21 I see you are using the version from Бука (Buka), which is perhaps the best Russian version of the game from translation quality point of view. Unfortunately, there is a problem with it: while the text with regular font size is encoded in CP1251, small font text is encoded with a different, non-standard encoding, something like `small_char_code = regular_char_code - offset` for most letters. This means that in order to properly support this version without the unicode font, the Russian translation file has to be split in two (for two respective font sizes), and each part must be encoded differently.

For now, I've switched to a game version from XXI Век (XXI Vek), which simply uses CP1251 throughout the whole game, however, this version is quite rare and also worse in many ways (voice quality is poor, font face is difficult to read and not matching the English font face, etc.). See for yourself:

![homm2_ru](https://user-images.githubusercontent.com/10945319/124557103-68f01a00-de39-11eb-8c5b-65eb3ebbbf9b.png)

The translation file is generated using the following rule:

```
ru.mo: ru.po
	msgmerge -U --no-location $< fheroes2.pot
	iconv -f utf-8 -t CP1251 $< > $<.tmp
	sed -i 's/UTF-8/CP1251/' $<.tmp
	msgfmt $<.tmp -o $@
```

As you are familiar with the code, maybe you could take a look to see what it takes to support the Buka version, perhaps with a code change specific to the Russian locale?

2021-07-07 15:53 UTC, undef21 commented
Good catch, @dimag0g. Could you please check [this fix](https://github.com/ihhub/fheroes2/pull/3816)?