Save Completed Campaign Scenario to file
ihhub/fheroes2 pull request #3315
Opened 2021-05-01 02:11 UTC by eos428

While testing campaign awards, @Branikolog remarked that in the OG, when we complete a campaign scenario the OG creates a save file which will immediately lead you to the campaign scenario selection window (or probably the credits, if it's the last one).

I'm pretty sure this will have merge conflicts with the big campaign award PR, so when either of the PRs are merged I will resolve the conflicts asap.

Example: Good_1_Complete

2021-05-01 04:51 UTC, ihhub requested changes
Hi @eos428 , I left few comments here. Could you please take a look?

2021-05-01 04:51 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +#include "system.h"
Do we need this file inclusion?

2021-05-01 04:51 UTC, ihhub commented on src/fheroes2/game/game_io.cpp
> +    std::string base = name.size() ? name : "newgame";
Please use translation code `_( newgame )`.

2021-05-01 04:51 UTC, ihhub commented on src/fheroes2/game/game_io.cpp
> +    base.resize( std::distance( base.begin(), std::find_if( base.begin(), base.end(), ::ispunct ) ) );
Are we going to remove a dot *.* here from the end? If yes please use `rfind` call instead.

2021-05-01 04:51 UTC, ihhub commented on src/fheroes2/game/game_io.cpp
> +    os << System::ConcatePath( Game::GetSaveDir(), base ) << "_Complete" << Game::GetSaveFileExtension();
Please use translation code `_( _Complete )`. Also string concatenation works totally fine with `std::string`. We do not need **ostringstream** here.

2021-05-01 04:51 UTC, ihhub commented on src/fheroes2/game/game_io.cpp
> +    return Game::Save( os.str() );
Since we're at `Game` namespace we could remove `Game::`.

2021-05-01 14:53 UTC, eos428 commented on src/fheroes2/game/game_campaign.cpp
> +#include "system.h"
Probably no as of now, I forgot to remove this one when I moved the code to game_io

2021-05-01 15:05 UTC, eos428 commented on src/fheroes2/game/game_io.cpp
> +    base.resize( std::distance( base.begin(), std::find_if( base.begin(), base.end(), ::ispunct ) ) );
I think in this case we just want to change something like `Good 1` to `Good_1`. In this case, would the `std::replace_if` below be enough?

2021-05-03 15:40 UTC, merged

2021-05-03 15:40 UTC, ihhub commented
@eos428 , thank you very much for this improvement!