Fix catapult miss animation: show this animation near the actual target object
ihhub/fheroes2 pull request #3320
Opened 2021-05-01 22:05 UTC by oleg-derevenetz

fix #3127

2021-05-01 22:16 UTC, oleg-derevenetz commented
Hi @Branikolog could you please take a look at this when you have some free time? I don't like that when animating the miss in OG style (if I understand correctly, in case of a miss, the boulder should fall in the courtyard near the target) sometimes you may get the impression that boulder hits creature standing on the cell on which the boulder falls. Maybe it's better to animate the miss with small explosion over the actual target?

2021-05-02 04:54 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left few style related comments. Could you please take a look?

2021-05-02 04:54 UTC, ihhub commented on src/fheroes2/battle/battle_action.cpp
> +            bool hit = cmd.GetValue() != 0;
We could make these variables `const`.

2021-05-02 04:54 UTC, ihhub commented on src/fheroes2/battle/battle_arena.cpp
> +            bool hit = catapult->GetHitOrMiss();
We could make this variable `const`.

2021-05-02 04:54 UTC, ihhub commented on src/fheroes2/battle/battle_catapult.cpp
> +bool Battle::Catapult::GetHitOrMiss() const
The name of the method is not very clear. What's about call it "IsNextShotHit"? Not an ideal one, of course.

2021-05-02 06:40 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_catapult.cpp
> +bool Battle::Catapult::GetHitOrMiss() const
Yes, it sounds better, thanks :)

2021-05-02 07:08 UTC, merged

2021-05-02 07:08 UTC, ihhub commented
@oleg-derevenetz , thanks a lot for fixing this issue!

2021-05-02 19:11 UTC, Branikolog commented
> Hi @Branikolog could you please take a look at this when you have some free time? I don't like that when animating the miss in OG style (if I understand correctly, in case of a miss, the boulder should fall in the courtyard near the target) sometimes you may get the impression that boulder hits creature standing on the cell on which the boulder falls. Maybe it's better to animate the miss with small explosion over the actual target?

Sounds like a good idea for future improvement. It seems that in heroes 3 developers got rid of current miss animation. I find it weird too. We need to discuss whether make miss animation over the actual target or, probably, in front bottom area of the target castle part.
Until then, I think, we should focus on more important issues. :)