add additional info for oracle dialog
ihhub/fheroes2 pull request #3324
Opened 2021-05-02 10:47 UTC by undef21

fix #1589

2021-05-03 15:10 UTC, ihhub requested changes
Hi @undef21 , I left multiple comments here. Would you mind to take a look?

2021-05-03 15:10 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +Monster Army::GetBestMonster()
This method should be called as `GetStrongestMonster` based on what it does. Also this method must be `const` as it doesn't modify any of its members.

2021-05-03 15:10 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +            monster = **ci;
Could you please add `{}` to make code easier to read?

2021-05-03 15:10 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.h
> +    Monster GetBestMonster();
This method should be `const`.

2021-05-03 15:10 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +        auto cur_mon = ( *ci )->GetArmy().GetBestMonster();
Please try to avoid using `auto` unless it's necessary. Declaring here type `Monster` will make code much easier to read.

2021-05-03 15:10 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +        auto cur_mon = ( *ci )->GetArmy().GetBestMonster();
Please try to avoid using `auto` unless it's necessary. Declaring here type `Monster` will make code much easier to read.

2021-05-03 15:10 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +        auto cur_mon = ( *ci )->GetArmy().GetBestMonster();
Also please use `camelCase` variable naming.

2021-05-03 15:10 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +    for ( KingdomHeroes::const_iterator ci = heroes.cbegin(); ci != heroes.cend(); ci++ ) {
We could avoid iterators by using ranged loops: `for ( const Heroes * hero : heroes )`.

2021-05-03 15:10 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +    for ( KingdomCastles::const_iterator ci = castles.cbegin(); ci != castles.cend(); ci++ ) {
We could avoid iterators by using ranged loops: `for ( const Castle * castle : castles )`.

2021-05-03 15:10 UTC, ihhub commented on src/fheroes2/dialog/dialog_thievesguild.cpp
> +            int32_t px = pos.x - 25 + i * step;
This variable could be `const`.

2021-05-03 15:10 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +        auto cur_mon = ( *ci )->GetArmy().GetBestMonster();
Also please use `camelCase` variable naming.

2021-05-04 11:20 UTC, Branikolog commented
Hi, @undef21!
I've noticed, that "Best Hero Stats" has became too close to "Best Hero".
It should be centered in stats line. 
Could you, please, fix it?

2021-05-04 13:31 UTC, merged

2021-05-04 13:32 UTC, ihhub commented
@undef21 , thank you very much for the fix!