Generate obstacles on battlefield based on the battle tile index
ihhub/fheroes2 pull request #3382
Opened 2021-05-09 17:12 UTC by oleg-derevenetz

fix #1294

2021-05-13 09:32 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left just 2 comments regarding the implementation. Could you please check them?

2021-05-13 09:32 UTC, ihhub commented on src/fheroes2/battle/battle_arena.cpp
> +        std::mt19937 seededGen( static_cast<uint32_t>( index ) );
I think we need to use `GetMapSeed()` from the world cobject plus add to it the index of the tile. What do you think?

2021-05-13 09:41 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_arena.cpp
> +        std::mt19937 seededGen( static_cast<uint32_t>( index ) );
Hi @ihhub

> Wouldn't we have the same obstacles at the same map indexes across all maps?

If they have the same terrain type, yes. Is this an issue?

> I think we need to use GetMapSeed() from the world cobject plus add to it the index of the tile. What do you think?

Yes, it's possible if the above is considered as an issue.

2021-05-13 09:42 UTC, ihhub commented on src/fheroes2/battle/battle_arena.cpp
> +        std::mt19937 seededGen( static_cast<uint32_t>( index ) );
Hi @oleg-derevenetz , yes, it is the issue. Each map should have a unique battle obstacles so players can't exploit it :)

2021-05-15 13:53 UTC, merged

2021-05-15 13:53 UTC, ihhub commented
@oleg-derevenetz , thank you so much for fixing this bug!