fixed issue #3366
ihhub/fheroes2 pull request #3389
Opened 2021-05-10 16:08 UTC by gentooza

fixing issue #3366 
taking an intermediate string variable, for checking monster count.
if == 1 is only one.

cheers!

2021-05-11 00:58 UTC, ihhub requested changes
Hi @gentooza , I left few comments here. Could you please take a look?

2021-05-11 00:58 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +        std::string count = StringLower( Game::CountScoute( troop.GetCount(), isOwned ? static_cast<int>( Skill::Level::EXPERT ) : scoutingLevel ) );
We shouldn't compare a string with 1 as this function might return "one" as well (for example in the future). The right approach would be to check scouting level and the amount of troops. If it's an expert level and the number is 1 then use non-plural name.

2021-05-11 16:02 UTC, gentooza commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +        std::string count = StringLower( Game::CountScoute( troop.GetCount(), isOwned ? static_cast<int>( Skill::Level::EXPERT ) : scoutingLevel ) );
ok, cool
I'll handle it, ok?
cheers

2021-05-12 13:31 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +        std::string count = StringLower( Game::CountScoute( troop.GetCount(), isOwned ? static_cast<int>( Skill::Level::EXPERT ) : scoutingLevel ) );
Hi @gentooza , what I meant is:
```
const int scoutingLevel = isOwned ? static_cast<int>( Skill::Level::EXPERT ) : scoutingLevel;
if ( scoutingLevel == Skill::Level::EXPERT && troop.GetCount() == 1 ) {
    StringReplace( str, "%{monster}", StringLower( troop.GetName() ) );
}
else {
    StringReplace( str, "%{monster}", StringLower( troop.GetMultiName() ) );
}

StringReplace( str, "%{count}", StringLower( Game::CountScoute( troop.GetCount(), scoutingLevel ) ) );
```

2021-05-13 09:33 UTC, ihhub requested changes
Hi @gentooza , would you mind to take a look at slightly enhanced solution being proposed? What do you think?

2021-05-13 09:57 UTC, gentooza commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +        std::string count = StringLower( Game::CountScoute( troop.GetCount(), isOwned ? static_cast<int>( Skill::Level::EXPERT ) : scoutingLevel ) );
Hi! @ihhub 

yeah sure! I have only a question, if we do this:
```
if ( scoutingLevel == Skill::Level::EXPERT && troop.GetCount() == 1 ) {
[...]
```
we are going to ignore the *extendedScoutingOption* flag, isn't it?
same in ShowMonsterInfo function.

cheers

2021-05-13 10:06 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +        std::string count = StringLower( Game::CountScoute( troop.GetCount(), isOwned ? static_cast<int>( Skill::Level::EXPERT ) : scoutingLevel ) );
According to the condition above this code `( isOwned || ( extendedScoutingOption && scoutingLevel > Skill::Level::NONE )` we can reach this code only is `isOwned` is set to **true** making `scoutingLevel` as **Skill::Level::EXPERT** or when `extendedScoutingOption` is set to true. So in this case there is no need to check for `extendedScoutingOption` again. Please correct me if I'm wrong.

2021-05-13 11:22 UTC, gentooza commented
yes, totally agree
is it now ok?

2021-05-15 13:49 UTC, merged

2021-05-15 13:50 UTC, ihhub commented
@gentooza , thank you very much for your contribution to the project!

2021-05-16 19:27 UTC, gentooza commented
you are welcome!
and congrats, it's a very cool project