Combat, AI behavior, AI hero Hector casts the Blind spell which does not give any benefit because the hero has only 1 point of Spell Power
ihhub/fheroes2 pull request #3401
Opened 2021-05-11 21:44 UTC by shprotru

Fix for #3395

2021-05-12 13:39 UTC, ihhub requested changes
Hi @shprotru , I left multiple comments here. Could you please take a look?

2021-05-12 13:39 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +        u32 acount = _commander->HasArtifact( Artifact::WIZARD_HAT );
Please use `uint32_t` type instead.

2021-05-12 13:39 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +    double BattlePlanner::spellEffectValueMultiplier() const
This function should just return `uin32_t` which will explicitly converted into `double` with no issues.

2021-05-12 13:39 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +            return 0.0;
Here we can return `0`.

2021-05-12 13:39 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +        u32 acount = _commander->HasArtifact( Artifact::WIZARD_HAT );
Also please name this variable properly like `artifactCount`.

2021-05-12 13:39 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +        if ( acount )
This check is redundant. Multiplication by 0 will give 0.

2021-05-12 13:39 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +        if ( acount )
In this case we don't need the original `acount` variable.

2021-05-12 19:35 UTC, shprotru commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +    double BattlePlanner::spellEffectValueMultiplier() const
done

2021-05-12 19:35 UTC, shprotru commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +        u32 acount = _commander->HasArtifact( Artifact::WIZARD_HAT );
done

2021-05-12 19:36 UTC, shprotru commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +        u32 acount = _commander->HasArtifact( Artifact::WIZARD_HAT );
done

2021-05-12 19:36 UTC, shprotru commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +            return 0.0;
done

2021-05-13 09:35 UTC, ihhub requested changes

2021-05-13 09:35 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +        int spellPower = _commander->GetPower();
Here we're introducing type conversion warning. Please cast it to `uint32_t` and make the variable the same type.

2021-05-13 12:17 UTC, shprotru commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +        int spellPower = _commander->GetPower();
done

2021-05-13 14:26 UTC, idshibanov requested changes

2021-05-13 14:26 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +        uint32_t spellPower = static_cast<uint32_t>( _commander->GetPower() );
Please rename this variable to `duration` and method to `BattlePlanner::spellDurationMultiplier` so it's more clear it has to be applied to duration effects only.

2021-05-13 14:30 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +        return target.GetStrength() * ratio * spellEffectValueMultiplier();
**This will break** existing logic and end up with strong enemy heroes overvaluing and casting only buff/debuff spells instead of damage ones. We only care if spell duration is short, it doesn't matter if spell will be running 5 turns or 15 because battle is likely to be over by then.

I think value should be something like 0.33 -> 0.66 -> 1.0.

2021-05-13 14:34 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +            return 0;
What we can do here is add an additional check: `if ( spellPower < 2 && target.Modes( TR_MOVED ) )` because there's still a little bit of value for 1-turn effects if unit hasn't moved yet. Or even something like this:
```
if ( duration > 0 && target.Modes( TR_MOVED ) )
    --duration;
```

That means it's better to move this check out of this method into beginning of `BattlePlanner::spellEffectValue` and return 0 there before we do any additional calculations.

2021-05-13 15:06 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +            return 0;
We could fix #3380 with this too.

2021-05-18 14:14 UTC, ihhub commented
Hi @shprotru , could you please take a look at @idshibanov comments?

2021-05-23 16:40 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +            return 0;
@shprotru Small bug - if condition should be `duration < 2 && target.Modes( TR_MOVED )` otherwise AI won't ever cast spells on fastest units that already moved.

2021-05-23 17:49 UTC, idshibanov approved these changes

2021-05-24 15:35 UTC, merged

2021-05-24 15:35 UTC, ihhub commented
@shprotru , thank you veru much for fixing this issue!