Implement Protect Villages Victory Condition
ihhub/fheroes2 pull request #3404
Opened 2021-05-13 01:14 UTC by eos428

More accurately put, this is actually a lose condition but at the moment I'm not sure if we should make an entirely new enum instead of adding towards what we already have. 

Applied in Save the Dwarves.

2021-05-13 02:04 UTC, eos428 commented
For some reason, psv-sdl2 is failing here. Not sure what's going on... seems to be just bad luck?

2021-05-13 08:35 UTC, oleg-derevenetz commented
Hi @eos428 yes, it failing sometimes because installer script can't properly unpack archives - it seems that downloaded archive is broken for some reason, so script cannot install necessary PSV library and giving up.

2021-05-13 09:14 UTC, ihhub commented
> Hi @eos428 yes, it failing sometimes because installer script can't properly unpack archives - it seems that downloaded archive is broken for some reason, so script cannot install necessary PSV library and giving up.

That's why I created an issue to cache PS Vita builds :)

2021-05-13 09:19 UTC, oleg-derevenetz commented
Hi @ihhub

> That's why I created an issue to cache PS Vita builds :)

Cache itself will not help in this case - we need to make a patch to the original installer script to force it to ignore unpacking errors and apply it every time :) And also it will need to unpack those archives in a "safe way" - to temporary directory first to ensure that half-unpacked binaries doesn't overwrite existing valid ones. Lots of changes to 3rd party code.

2021-05-13 09:22 UTC, ihhub commented
> Hi @ihhub
> 
> > That's why I created an issue to cache PS Vita builds :)
> 
> Cache itself will not help in this case - we need to make a patch to the original installer script to force it to ignore unpacking errors and apply it every time :) And also it will need to unpack those archives in a "safe way" - to temporary directory first to ensure that half-unpacked binaries doesn't overwrite existing valid ones. Lots of changes to 3rd party code.

We surely not going to do this :) This is out of this project scope work. Having a temporary failures is better than wasting days of our time.

2021-05-13 09:29 UTC, ihhub requested changes
Hi @eos428 , there are few comments left. Would you mind to take a look?

2021-05-13 09:29 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.h
> +        PROTECT_VILLAGES = 2
We should create a separate `ScenarioLossCondition` enumeration to do not confuse code readers. We could do in the same way:
```
enum class ScenarioLossCondition : int
{
    STANDARD = 0, // standard map's defined loss condition
    LOSE_ANY_VILLAGE = 1
};
```

In this case the solution will be scalable for the future changes.

2021-05-13 09:29 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +    if ( ( conf.GameType() & Game::TYPE_CAMPAIGN ) != 0 ) {
Could we please add a separate method in Settings class called `isCampaignGameType()` as we already have multiple places where we use the same code? I think it would be make the code easier to read. What do you think?

2021-05-13 09:29 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +                bool hasVillage = false;
I am not sure how do we check if AI captured one of villages as the loop below just checks if at least one village is present. Could you please explain it?

2021-05-13 14:30 UTC, eos428 commented on src/fheroes2/world/world.cpp
> +                bool hasVillage = false;
I think these lose conditions should be for the player (human) only, which I will be pushing soon. Also I will be changing the loss condition to LOSE_ALL_VILLAGES which should help clarify things.

Overall this loop just checks whether the player has a village or not. The player will lose if he doesn't have any village.

2021-05-13 14:31 UTC, eos428 commented on src/fheroes2/world/world.cpp
> +    if ( ( conf.GameType() & Game::TYPE_CAMPAIGN ) != 0 ) {
Yes, we should do that.

2021-05-16 13:21 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +                bool hasVillage = false;
But in this case we do not cover the situation within the campaign map where a player looses when even on village is being captured. I have an idea: what if we check certain types of villages under AI control. We know that these villages are Sorceress so we can check if any of these vilages is under AI control. Also we could rename the condition to `LOSE_ANY_SORCERESS_VILLAGE`. What do you think?

2021-05-17 03:47 UTC, ihhub requested changes
Hi @eos428 , I left just few more comments. Would you mind to take a look?

2021-05-17 03:47 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.h
> +        STANDARD = 0,
Could you please add a comment `// standard map's defined loss condition` here?

2021-05-17 03:47 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.h
> +        ScenarioData( int scenarioID, const std::vector<int> & nextMaps, const std::vector<Campaign::ScenarioBonusData> & bonuses, const std::string & fileName,
Hmmm... Could we please remove this constructor? The only gain of doing this is to not add `ScenarioVictoryCondition::STANDARD` at scenario initialization. I don't think it's a big drawback of having just one constructor :)

2021-05-17 03:47 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +                        continue;
Could we please combine these conditions?

2021-05-17 08:08 UTC, merged

2021-05-17 08:08 UTC, ihhub commented
@eos428 , thank you very much for this code improvement!