Mute sound by setting music & effects volume to zero instead of pausing them
ihhub/fheroes2 pull request #3428
Opened 2021-05-16 23:52 UTC by oleg-derevenetz

fix #3113
fix #3240
fix #3415

After some investigation, I found that _sometimes_ `Mixer::isPaused()` here:

https://github.com/ihhub/fheroes2/blob/94ceef01ddb7cace7e11873e412e9ad9990ccf7b/src/engine/localevent.cpp#L1258

doesn't return 0, and therefore channels are not resumed here:

https://github.com/ihhub/fheroes2/blob/94ceef01ddb7cace7e11873e412e9ad9990ccf7b/src/engine/localevent.cpp#L1272

which leads to freeze when game waits for a particular sound to finish. Needs to be tested on Windows and Linux as well.

@ihhub BTW it seems that build with WITHOUT_MIXER is broken long ago. Does it make sense to support WITHOUT_MIXER mode?

2021-05-17 03:38 UTC, ihhub commented
Hi @oleg-derevenetz , in my view we should remove all these compilation switches as a many as possible. I've never tested a build with `WITHOUT_MIXER` flag. Interesting to see what will it give to us...

2021-05-17 03:41 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left few comments in this pull request. Could you please take a look?

2021-05-17 03:41 UTC, ihhub commented on src/engine/audio_mixer.cpp
> +    return Mix_AllocateChannels( -1 );
`Mix_AllocateChannels` returns **int**. Could you please update the return value?

2021-05-17 03:41 UTC, ihhub commented on src/engine/audio_mixer.cpp
> +    return chunks.size();
Since we're doing static_cast and `size()` returns **size_t** would it be more rational to return **size_t** from this method as well?

2021-05-17 03:41 UTC, ihhub commented on src/engine/localevent.cpp
> +    for ( size_t channel = 0; channel < channelsCount; channel++ ) {
Please use prefix form of increment.

2021-05-17 03:41 UTC, ihhub commented on src/engine/localevent.cpp
> +        for ( size_t channel = 0; channel < channelsCount; channel++ ) {
Please use prefix form of increment.

2021-05-17 07:03 UTC, oleg-derevenetz commented
@ihhub

> in my view we should remove all these compilation switches as a many as possible

I plan to move mute/unmute code from localevent to mixer/music to properly handle situations when, for example, player starts hero teleportation and then switches to another window, so I want to remove obviously dead WITHOUT_MIXER code first. I'll do it in this PR then.

2021-05-17 11:02 UTC, oleg-derevenetz commented
Review from @winterheart will be highly appreciated, because I'm not CMake expert, may be some changes could have been done in a more graceful way.

2021-05-17 12:09 UTC, oleg-derevenetz commented
Hi @ihhub It's also interesting how this will work on Windows, because on Windows there is AFAIK "one volume to rule them all". Could you please check this on Windows when you'll have the desire and opportunity?

2021-05-17 15:51 UTC, winterheart commented
Hi. Everything fine with CMake changes, no issues found.

2021-05-17 16:20 UTC, oleg-derevenetz commented
Hi @winterheart 

> Everything fine with CMake changes, no issues found.

Thank you!

2021-05-18 13:58 UTC, ihhub commented
Hi @Northfear , could you please test these changes on PS Vita? Just verify that sounds and music are present even when you switch to the main screen and come back.

2021-05-18 14:15 UTC, oleg-derevenetz commented
Hi @ihhub BTW I'm going to remove optional parameter from Mixer::isPlaying() (to check channel volume first) later in separate PR, because it seems that it is not used anywhere.

2021-05-18 14:25 UTC, ihhub commented
> Hi @ihhub BTW I'm going to remove optional parameter from Mixer::isPlaying() (to check channel volume first) later in separate PR, because it seems that it is not needed anywhere.

Sure!

2021-05-18 16:35 UTC, Northfear commented
> Hi @Northfear , could you please test these changes on PS Vita? Just verify that sounds and music are present even when you switch to the main screen and come back.

Done. Everything seems to be working fine

2021-05-19 01:29 UTC, ihhub commented
Music volume on Windows still effects sound volume as before. "one volume to rule them all" is still present :)

2021-05-19 01:44 UTC, ihhub requested changes
Hi @oleg-derevenetz , I commented just at 2 places. Could you please take a look? The rest of the code looks good.

2021-05-19 01:44 UTC, ihhub commented on src/engine/audio_mixer.cpp
> +    std::vector<int> savedVolumes;
Could we please move these variables under a single structure and then have just one instance of it in anonymous namespace? First of all, we shouldn't pollute this namespace as these variables are used only in this file. Secondly, SonarQube would complain about so many static variables but having only on structure instance will make the code smell number smaller.

2021-05-19 01:44 UTC, ihhub commented on src/engine/audio_music.cpp
> +    int savedVolume = 0;
Could we please move these variables under a single structure and then have just one instance of it in anonymous namespace? First of all, we shouldn't pollute this namespace as these variables are used only in this file. Secondly, SonarQube would complain about so many static variables but having only on structure instance will make the code smell number smaller.

2021-05-19 06:27 UTC, oleg-derevenetz commented on src/engine/audio_music.cpp
> +    int savedVolume = 0;
Hi @ihhub May be I just put them into the anonymous namespace? I agree that there is no point to put them into Music namespace if they are used just in this file, but putting them in single structure might be justified if, for example, they both returned from some function or something like that, but doing this just for pleasing SonarQube... It will complain about this structure anyway, and there will be no gain in any aspect (CPU or RAM consumption) :)

2021-05-19 06:39 UTC, ihhub commented on src/engine/audio_music.cpp
> +    int savedVolume = 0;
Sure. Let's put to anonymous namespace at least.

2021-05-20 03:45 UTC, merged

2021-05-20 03:46 UTC, ihhub commented
@oleg-derevenetz , thanks a lot for fixing these big issues!