Fix next hero choose logic
ihhub/fheroes2 pull request #3431
Opened 2021-05-17 13:44 UTC by tau3

Fixes #3364
A hero with non-zero move points can be chosen as next even if movement is not possible on predetermined path

2021-05-18 13:55 UTC, ihhub requested changes
Hi @tau3 , I left just few comments. Could you please take a look?

2021-05-18 13:55 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +        return move_point > threshold;
This check might be incorrect. Could you please verify what happens when a hero has 1 point of movement which is not enough to even move on a road?

2021-05-18 13:55 UTC, ihhub commented on src/fheroes2/heroes/heroes.h
> +    bool MayStillMove( bool isConsiderMovePoints = true ) const;
A small correction: since we're adopting better coding rules could you please make this input variable `const`?

2021-05-27 21:25 UTC, tau3 commented on src/fheroes2/heroes/heroes.cpp
> +        return move_point > threshold;
yep, there should have been "more-or-equal" comparison. fixed it.

2021-06-07 14:34 UTC, ihhub commented
Hi @Branikolog , could you please test this change?

2021-06-07 20:31 UTC, Branikolog commented
Hi, @tau3 
Next hero button works not correct in a case we have multiple heroes in a situation, where they can make a move in one direction, but cannot in other.
Here we have both heroes with no predetermined path, but "Next hero" button works only in focusing on second hero...
![image](https://user-images.githubusercontent.com/55348946/121083266-e51a2200-c7e7-11eb-8788-816da6d46476.png)

When we make predetermined path for both heroes (first hero without ability to move, and second hero able to move)...
![image](https://user-images.githubusercontent.com/55348946/121083571-45a95f00-c7e8-11eb-9748-97e47b480e7b.png)
![image](https://user-images.githubusercontent.com/55348946/121083614-53f77b00-c7e8-11eb-8ed8-d318a7b6b5b2.png)
..."Next hero" button switches between both of them.

2021-07-13 16:08 UTC, merged

2021-07-13 16:09 UTC, ihhub commented
@tau3 , thank you very much for this fix!