Download standalone unzip executable to extract demo zip if PS doesn't support `Expand-Archive`
ihhub/fheroes2 pull request #3455
Opened 2021-05-19 07:23 UTC by hgdagon

2021-05-19 07:29 UTC, oleg-derevenetz reviewed
Hi @hgdagon I left one comment regarding these changes, what is your opinion about that?

2021-05-19 07:29 UTC, oleg-derevenetz commented on script/demo/demo_windows.bat
> +unzip -o -qq -L demo.zip data/* maps/*
Hi @hgdagon I really don't think that downloading arbitrary EXE files from arbitrary websites (controlled by unknown persons) is a good idea. @ihhub what do you think?

2021-05-19 07:40 UTC, hgdagon commented on script/demo/demo_windows.bat
> +unzip -o -qq -L demo.zip data/* maps/*
@oleg-derevenetz I understand the concern. maybe we can build our EXE and host it on GitHub?

2021-05-19 10:01 UTC, oleg-derevenetz commented on script/demo/demo_windows.bat
> +unzip -o -qq -L demo.zip data/* maps/*
@hgdagon How about this:

https://gist.github.com/oleg-derevenetz/0423eb953289104723c0b0c1fbe5d905

? Does it work on Windows 7? I think there is no reason to take Windows XP into account because it shipped without PowerShell pre-installed...

2021-05-19 10:03 UTC, ihhub commented on script/demo/demo_windows.bat
> +unzip -o -qq -L demo.zip data/* maps/*
@oleg-derevenetz , let me try it on one of Win7 machines.

2021-05-19 10:14 UTC, ihhub commented on script/demo/demo_windows.bat
> +unzip -o -qq -L demo.zip data/* maps/*
It works!

2021-05-19 10:30 UTC, ihhub commented on script/demo/demo_windows.bat
> +unzip -o -qq -L demo.zip data/* maps/*
Plus we still need to download Wing32.dll. This file is needed to run demo version of the original game.

2021-05-19 10:32 UTC, oleg-derevenetz commented on script/demo/demo_windows.bat
> +unzip -o -qq -L demo.zip data/* maps/*
@ihhub isn't the demo version downloaded just for the sake of original assets?

2021-05-19 10:34 UTC, hgdagon commented on script/demo/demo_windows.bat
> +unzip -o -qq -L demo.zip data/* maps/*
I personally do not care whether it's unzip or anything else, as long as the use isn't required to do any additional manual labor. Also, @ihhub no, Wing32.dll shouldn't be needed.

2021-05-19 11:06 UTC, oleg-derevenetz commented on script/demo/demo_windows.bat
> +unzip -o -qq -L demo.zip data/* maps/*
I really don't see why this dll might be needed, even if we want to run original game demo. Isn't this game for DOS? AFAIK DOS doesn't have a concept of DLLs :)

2021-05-19 12:17 UTC, hgdagon commented on script/demo/demo_windows.bat
> +unzip -o -qq -L demo.zip data/* maps/*
@oleg-derevenetz This is the win demo. Since running the demo as it is is a scenario that should be considered, I kept it in case the script is run outside.

2021-05-19 15:20 UTC, oleg-derevenetz commented on script/demo/demo_windows.bat
> +unzip -o -qq -L demo.zip data/* maps/*
@ihhub Then it would be more secure to at least check the sha256 hash of the downloaded file against a hardcoded value to make sure that file wasn't replaced on web hosting by some malicious version. `Get-FileHash` in PowerShell allows to compute hashes.

2021-05-20 05:47 UTC, ihhub requested changes

2021-05-20 05:47 UTC, ihhub commented on script/demo/demo_unix.sh
> +#!/bin/bash
Let's make this changes in a separate pull request please?

2021-05-20 05:47 UTC, ihhub commented on script/demo/demo_windows.bat
> +powershell -Command "(New-Object Net.WebClient).DownloadFile('https://archive.org/download/HeroesofMightandMagicIITheSuccessionWars_1020/h2demo.zip', '%fh2Path%demo.zip')"
Could we please also check SHA256 of this archive and `wing32.zip`? You could take a look at an example [here](https://stackoverflow.com/questions/63396620/how-can-i-compare-a-filess-sha256-hash-in-powershell-to-a-known-value).

2021-05-20 05:47 UTC, ihhub commented on script/demo/demo_windows.bat
> +powershell -Command "(New-Object Net.WebClient).DownloadFile('https://archive.org/download/HeroesofMightandMagicIITheSuccessionWars_1020/h2demo.zip', '%fh2Path%demo.zip')"
If it's not straighforward we can do this in a seprate pull request.

2021-05-20 15:26 UTC, hgdagon commented on script/demo/demo_windows.bat
> +powershell -Command "(New-Object Net.WebClient).DownloadFile('https://archive.org/download/HeroesofMightandMagicIITheSuccessionWars_1020/h2demo.zip', '%fh2Path%demo.zip')"
@ihhub Are you sure `Get-FileHash` works on Win7?

2021-05-22 14:53 UTC, ihhub commented on script/demo/demo_windows.bat
> +powershell -Command "(New-Object Net.WebClient).DownloadFile('https://archive.org/download/HeroesofMightandMagicIITheSuccessionWars_1020/h2demo.zip', '%fh2Path%demo.zip')"
It doesn't :(

2021-05-23 01:13 UTC, ihhub commented
closing this pull request in favor for #3469

2021-05-23 01:13 UTC, closed without merging