Modernize & secure demo version installation scripts
ihhub/fheroes2 pull request #3469
Opened 2021-05-20 16:21 UTC by oleg-derevenetz

2021-05-20 20:36 UTC, oleg-derevenetz commented
`Get-FileHash` is available since PowerShell 4.0, so it should be available on Windows 7 SP1 and later.

2021-05-21 11:57 UTC, ihhub commented
Hi @oleg-derevenetz , Windows script can't be run on Windows 7:
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

d:\fheroes2\fheroes2\script\demo>demo_windows.bat
[1/4] downloading demo version
FATAL ERROR: The term 'Get-FileHash' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or i
f a path was included, verify that the path is correct and try again.
Press any key to exit...
```

My powershell version is **2.0**.

2021-05-21 12:09 UTC, oleg-derevenetz commented
Hi @ihhub Well, it's sad :( I'll make an exception handler for the case if Get-FileHash isn't supported.

2021-05-21 12:12 UTC, oleg-derevenetz commented
@ihhub BTW should this script ever run in unattended mode via AppVeyor? BAT file had corresponding check at the end, but I don't see why it needed.

2021-05-22 03:18 UTC, ihhub requested changes
Hi @oleg-derevenetz , nice work! I left few more comments here. Would you mind to take a look?

2021-05-22 03:18 UTC, ihhub commented on script/windows/install_packages.bat
> +powershell -Command "Expand-Archive -LiteralPath 'zlib\zlib1.2.11.zip' -DestinationPath 'zlib' -Force"
`Expand-Archive` is not supported on PowerShell 2.0. Could we please use the same trick as for demo downloading?

2021-05-22 06:44 UTC, oleg-derevenetz commented on script/windows/install_packages.bat
> +powershell -Command "Expand-Archive -LiteralPath 'zlib\zlib1.2.11.zip' -DestinationPath 'zlib' -Force"
Hi @ihhub

> Could we please use the same trick as for demo downloading?

The problem is that this script is intended to run in AppVeyor as well, and that trick uses the shell (explorer.exe), but I highly doubt that Windows VM does have it running. That's why I asked if demo_windows.bat should ever be used with AppVeyor or not. From the other side, this script is for developers, not end users, may be we can sacrifice a PowerShell 2.0 compatibility in this case?

2021-05-22 06:52 UTC, ihhub commented on script/windows/install_packages.bat
> +powershell -Command "Expand-Archive -LiteralPath 'zlib\zlib1.2.11.zip' -DestinationPath 'zlib' -Force"
demo_windows.bat could be used in the future for unit testing but for now it's not used anywhere. Regarding install_packages.bat script: at least I have to update my powershell😅

2021-05-22 06:58 UTC, oleg-derevenetz commented on script/windows/install_packages.bat
> +powershell -Command "Expand-Archive -LiteralPath 'zlib\zlib1.2.11.zip' -DestinationPath 'zlib' -Force"
Hi @ihhub We can make a separate versions then: for users/developers (with shell) and for AppVeyor (with Expand-Archive). What do you think?

2021-05-22 07:03 UTC, ihhub commented on script/windows/install_packages.bat
> +powershell -Command "Expand-Archive -LiteralPath 'zlib\zlib1.2.11.zip' -DestinationPath 'zlib' -Force"
Hi @oleg-derevenetz , looks like a good idea! Let's do this.

2021-05-22 10:58 UTC, qarkai commented on script/demo/demo_unix.sh
> +if [[ "$(which wget 2> /dev/null)" != "" ]]; then
Please use bash builtin `command -v` instead of `which`.

2021-05-22 11:05 UTC, oleg-derevenetz commented on script/demo/demo_unix.sh
> +if [[ "$(which wget 2> /dev/null)" != "" ]]; then
Hi @qarkai What's the benefit (apart from using built-in command itself)?

2021-05-22 11:46 UTC, qarkai commented on script/demo/demo_unix.sh
> +if [[ "$(which wget 2> /dev/null)" != "" ]]; then
`which` command adds unnecessary dependency on package `which`.

2021-05-22 11:50 UTC, qarkai commented
Does this PR supersedes #3455 and #3456?

2021-05-22 11:50 UTC, oleg-derevenetz commented on script/demo/demo_unix.sh
> +if [[ "$(which wget 2> /dev/null)" != "" ]]; then
@qarkai  That's a good reason. I'll replace `which` by `command` then.

2021-05-22 12:01 UTC, qarkai commented on script/demo/demo_unix.sh
> +if [[ "$(which wget 2> /dev/null)" != "" ]]; then
Also with `command` we can simply check return value, not test output:
`if command -v wget > /dev/null; then echo 'found'; fi`

2021-05-22 12:04 UTC, oleg-derevenetz commented on script/demo/demo_unix.sh
> +if [[ "$(which wget 2> /dev/null)" != "" ]]; then
> Also with command we can simply check return value, not test output:

Yes, I know. But it doesn't seems much shorter than

`if [[ "$(command -v wget)" != "" ]]; then echo 'found'; fi`

:)

2021-05-22 12:11 UTC, oleg-derevenetz commented
@qarkai

> Does this PR supersedes #3455 and #3456?

Yes, it seems so.

2021-05-22 12:17 UTC, qarkai commented on script/demo/demo_unix.sh
> +if [[ "$(which wget 2> /dev/null)" != "" ]]; then
It's not about "shorter". It's about "simpler and faster" since that method doesn't call extra `test` command.

2021-05-22 12:23 UTC, oleg-derevenetz commented on script/demo/demo_unix.sh
> +if [[ "$(which wget 2> /dev/null)" != "" ]]; then
`test` as well as `[[` are built-in constructions of bash anyway. "Premature micro optimizations" of such kind are usually useless.

2021-05-22 14:56 UTC, ihhub commented
Hi @hgdagon, could you please take a look at this pull request? I think it's the same way as you have in your pull requests. My apologies if we do double job :(

2021-05-22 16:01 UTC, hgdagon commented
@ihhub no need to apologize, however it seems like I won't be able to finish my PR. I can't for the life of me figure out how batch scripts work, I had issues with jumps, if statements, comparisons, exiting loops vs exiting the script itself, etc. that no amount of documentation online helped me figure out what's going on. So, if @oleg-derevenetz has a solution, we should definitely go with this one.

That said, from the get-go I was looking into a method to skip the download (since it just takes too long) if the file already exists, so I did actually learn that `Get-Filehash` doesn't work in PS2.0. One solution I found online was `Certutil`, like this

```batchfile
certutil -hashfile demo.zip SHA256 | find /V "hash"
```

I'm also not quite sure about switching to ps scripts entirely, because of the execution policy BS. Here, we're still running from a batch script, which is something I was trying to avoid.

P.S. WOW! 110 lines for downloading a small demo?

2021-05-22 16:39 UTC, oleg-derevenetz commented
Hi @hgdagon

> One solution I found online was Certutil, like this
> `certutil -hashfile demo.zip SHA256 | find /V "hash"`

I can try to adopt `certutil` as a fallback variant if `Get-FileHash` is not available, in separate PR. However, due to localized nature of its output, the above command may not work "as is" depending on user language. Need to think about different locale-independent approach.

> I'm also not quite sure about switching to ps scripts entirely, because of the execution policy BS. Here, we're still running from a batch script, which is something I was trying to avoid.

BAT files are utter crap in a modern Windows environment. They have a poor syntax, very weak functionality (without external utilities or inclusions of PowerShell code), insufficient error handling capabilities. PowerShell, on the other hand, lives up to its name in terms of scripting (however, to my taste, it's not so good as the **shell** itself, in comparison with bash or zsh, but that's another story).

2021-05-23 09:04 UTC, hgdagon commented
> BAT files are utter crap in a modern Windows environment. They have a poor syntax, very weak functionality 

Yes, but they allows us to run ps commands directly. That's my only concern here. However, I do see the limitations, i.e. if I understand correctly, you can't send variables from one ps command to the other. You would need to take care of variables in batch and then pass them on to the next command.

> due to localized nature of its output, the above command may not work "as is" depending on user language

I see, but if we're sure the hash is always on line 2, maybe we could use this?

```powershell
certutil -hashfile demo.zip SHA256 | select -first 1 -skip 1
```

Also, this reminds me exactly why I wanted to use unzip. It allows us to extract only the 2 directories that we need (unless we're extracting the whole thing for a dev, but that, obviously, is also very easy with unzip) and not having to bother with any copy operations, resulting in a much leaner script.

That said, BSD-tar is also another option on Win10 (don't remember since which build, though).

2021-05-23 09:37 UTC, oleg-derevenetz commented
> if I understand correctly, you can't send variables from one ps command to the other. You would need to take care of variables in batch and then pass them on to the next command.

Yes, and there may be complex variables like COM objects and so on. BAT files are completely unaware of such things.

> I see, but if we're sure the hash is always on line 2, maybe we could use this?

I did it in a [slightly different manner](https://github.com/oleg-derevenetz/fheroes2/blob/7d8bb5804d5003e42d651e637fdba417195dd653/script/demo/demo_windows.ps1#L19):

`return (certutil.exe -hashfile $Path sha256 | Select-String -Pattern "^[0-9A-Fa-f]{64}$").Line.ToUpper()`

but I think it's a matter of taste.

2021-05-23 09:42 UTC, ihhub commented
Hi @oleg-derevenetz , what I received while running `demo_windows.bat`:
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

d:\fheroes2\fheroes2\script\demo>demo_windows.bat
[1/4] downloading demo version
FATAL ERROR: You cannot call a method on a null-valued expression.
Press any key to exit...
```

2021-05-23 09:44 UTC, oleg-derevenetz commented
Hi @ihhub Do you have certutil installed? What does the `certutil.exe -hashfile h2demo.zip sha256` print?

2021-05-23 09:48 UTC, ihhub commented
> Hi @ihhub Do you have certutil installed? What does the `certutil.exe -hashfile h2demo.zip sha256` print?

Here is the output:
```
d:\fheroes2\fheroes2\script\demo\demo>certutil.exe -hashfile h2demo.zip sha256
CertUtil: -hashfile command FAILED: 0xd00000bb (-805306181)
CertUtil: WsResetMetadata
```

2021-05-23 09:54 UTC, oleg-derevenetz commented
@ihhub 

> Here is the output:
> 
> ```
> d:\fheroes2\fheroes2\script\demo\demo>certutil.exe -hashfile h2demo.zip sha256
> CertUtil: -hashfile command FAILED: 0xd00000bb (-805306181)
> CertUtil: WsResetMetadata
> ```

OMG. 0xc00000bb is STATUS_NOT_SUPPORTED, interesting, what exactly is "not supported" here. Any suggestions for such cases? Ignore error and print a warning?

2021-05-23 09:57 UTC, ihhub commented
> @ihhub
> 
> > Here is the output:
> > ```
> > d:\fheroes2\fheroes2\script\demo\demo>certutil.exe -hashfile h2demo.zip sha256
> > CertUtil: -hashfile command FAILED: 0xd00000bb (-805306181)
> > CertUtil: WsResetMetadata
> > ```
> 
> OMG. 0xc00000bb is STATUS_NOT_SUPPORTED, interesting, what exactly is "not supported" here. Any suggestions for such cases? Ignore error and print a warning?

I think yes, let's just pring the warning. Even despite of fact that this is not recommended. We should have some solution (which is already better than before) right now which we could improve in the future. We shouldn't waste so much time on this.

2021-05-23 13:06 UTC, merged

2021-05-23 13:07 UTC, ihhub commented
@oleg-derevenetz , excellent job! Thanks a lot for these changes!