Fix #1293
ihhub/fheroes2 pull request #3493
Opened 2021-05-23 18:16 UTC by vasilenkoalexey

Fix #1293

2021-05-25 17:33 UTC, ihhub requested changes
Hi @vasilenkoalexey , I left few comments here. Would you mind to take a look?

2021-05-25 17:33 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +    if ( drawList.size() > 0 ) {
We should compare this number with 1, not 0. Only 2 or more heroes in the container are needed for sorting.

2021-05-25 17:33 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +        for ( auto it = drawList.begin(); it != drawList.end() - 1; ) {
Could we please just use a normal counter-based loop here? Reading iterator-based code is really hard.

2021-05-25 17:33 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +            Heroes * hero1 = ( *it )->GetHeroes();
Please declare here a new variable called `const Maps::Tiles * tile = drawList[i];` as it below.

2021-05-26 05:27 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +            std::swap( *it, *( it + 1 ) );
Do we need to break the loop here? We know that only 1 hero is moving at once.

2021-05-29 09:31 UTC, Branikolog commented
It seems that hero overlaps another one standing nearby While moving northwest..
![image](https://user-images.githubusercontent.com/55348946/120065342-859a7480-c079-11eb-88fd-19431589c9f6.png)

2021-06-06 15:00 UTC, ihhub commented
Hi @vasilenkoalexey , I think we need to priotirized hero animation only for a situation of a hero moving to bottom-left direction. To do this we might need to add a special bollean flag in Hero class to indicate that the hero is moving.

2021-06-13 22:30 UTC, vasilenkoalexey commented
Also should fix #2500

2021-07-17 02:09 UTC, ihhub requested changes
Hi @vasilenkoalexey , I left one comment regarding logic. Could you please take a look?

2021-07-17 02:09 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +                std::iter_swap( it, it + 1 );
Should we check the next hero in the list and his tile ID?
```
const auto currentHeroTile = std::find( drawList.begin(), drawList.end(), tileMovingHero );
assert( currentHeroTile != drawList.end() );
const auto nextHeroTile = currentHeroTile + 1;
if ( nextHeroTile != drawList.end() && ( nextHeroTile->GetIndex() == currentHeroTile->GetIndex() + 1 )
    && ( nextHeroTile.GetObject() == MP2::OBJ_HEROES || nextHeroTile.GetObject() == MP2::OBJ_BOAT ) ) {
    std::iter_swap( currentHeroTile, nextHeroTile );
}
```

The same logic applies for the case below.

2021-07-17 15:26 UTC, vasilenkoalexey commented on src/fheroes2/gui/interface_gamearea.cpp
> +                std::iter_swap( it, it + 1 );
We process tiles from top to bottom and left to RIGHT, its mean we put heroes to list in same order. Here, we get neighbor hero exactly at RIGHT tile(in relation to the current hero), and its mean that current hero tile index is one less than neighbor tile index, and neighbor hero should be always next in heroes list (again in relation to the current hero). So I think additional checks are unnecessary here.

2021-07-17 16:10 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +                std::iter_swap( it, it + 1 );
Additional checks will help to verify the described logic by you. If someone else, even me, will change a piece of the code like sort heroes and etc. then at least we can catch the incorrect behavior. Nothing more than this. We can repalce `nextHeroTile->GetIndex() == currentHeroTile->GetIndex() + 1` by `nextHeroTile->GetIndex() == Maps::GetDirectionIndex( currentHeroTile->GetIndex(), Direction::RIGHT )` to keep even better readability without hardcoding.

2021-07-25 10:12 UTC, Branikolog commented on src/fheroes2/gui/interface_gamearea.cpp
> +                std::iter_swap( it, it + 1 );
While moving northwest hero is still overlapping a standing hero.
![Bug](https://user-images.githubusercontent.com/55348946/126895548-e1ed160c-1478-49d2-a5ec-c46ea0bb17bd.png)

2022-07-22 15:49 UTC, ihhub commented
I am closing this pull request as the upcoming Adventure Map rendering would cover this issue.

2022-07-22 15:49 UTC, closed without merging