Fix #3489
ihhub/fheroes2 pull request #3494
Opened 2021-05-23 19:38 UTC by vasilenkoalexey

Fix #3489

2021-06-07 14:55 UTC, ihhub requested changes
Hi @vasilenkoalexey , I left just one comment with different approach to solve the problem. Could you please check it?

2021-06-07 14:55 UTC, ihhub commented on src/fheroes2/maps/maps.cpp
> +Maps::Indexes Maps::FindBoatTiles( int32_t center )
Let's please not to create a separate function just for one case as we could have more cases in the future. What if we modify the original `ScanAroundObject` function to accept an extra boolean argument `const bool ignoreHeroes` without default value and then modify the existing calls which are only 6 cases. To differentiate 2 functions let's call the one with distance as `ScanAroundObjectWithDistance`.

2021-06-10 09:49 UTC, vasilenkoalexey commented on src/fheroes2/maps/maps.cpp
> +Maps::Indexes Maps::FindBoatTiles( int32_t center )
Done

2021-06-10 16:29 UTC, ihhub commented
Hi @Branikolog , could you please test this issue?

2021-06-11 13:22 UTC, Branikolog commented
Hi, @ihhub !
With this fix we cannot summon boat over other one anymore.
But I've found another issue: we can summon opponent's boat, after he disembarked.
![image](https://user-images.githubusercontent.com/55348946/121692620-ed68aa80-cad0-11eb-9a61-46efa7eb72f0.png)
![image](https://user-images.githubusercontent.com/55348946/121692850-2e60bf00-cad1-11eb-916c-f214c7613914.png)
![image](https://user-images.githubusercontent.com/55348946/121692873-3587cd00-cad1-11eb-9087-f4aee9d8ae93.png)

[Summon Opponents boat.zip](https://github.com/ihhub/fheroes2/files/6638682/Summon.Opponents.boat.zip)
(Disembark by a green hero. End turn. Summon boat by Vatavna.

2021-06-11 22:17 UTC, vasilenkoalexey commented
I think issue should be renamed to "... relation to another hero on boat"

> But I've found another issue: we can summon opponent's boat, after he disembarked.

We shouldn't be able to? Now the boat has no reference to the owner or creator.

2021-06-12 15:12 UTC, Branikolog commented
Any boat, that once was summoned or embarked by a hero is considered as property of a player and cannot be summoned, until other player embarks it and refreshes ownership.

2021-06-13 12:26 UTC, vasilenkoalexey commented
Hmm... Anyway this is a completely different problem.

2021-06-15 12:53 UTC, merged

2021-06-15 12:53 UTC, ihhub commented
@vasilenkoalexey , thank you so much for fixing this issue!