Implement PoL campaign Data
ihhub/fheroes2 pull request #3511
Opened 2021-05-24 13:40 UTC by eos428

Implemented
- Most of the grunt work, which turns out to be more than expected thanks to NWC's inconsistencies in the map files
- Scenario bonus data to increase Primary Stats
- Campaign Tracks (partially, 2-row tracks have to be drawn differently)

Some outstanding issues:
- Video playback for the scenarios
- Need to check whenever we get an artifact as a campaign award. If we have all the materials to form a set, we should make a new artifact campaign award and replace the awards for the set materials
- The scenario selection screens are a hot mess right now
- Actually making these campaigns playable in a conventional manner

I am opening this PR right now so that we can get the grunt work out of the way. The next ones will deal more into the visuals of scenario selection screen.

2021-05-26 05:00 UTC, ihhub requested changes
Hi @eos428 , there are few minor comments. Would you mind please to take a look?

2021-05-26 05:00 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +        _( "Subdue the unruly local lords in order to provide the Empire with facilities to operate in this region." ),
Could you please check whether the original game has 2 spaces between sentences? By default it should have. Of course it's more cosmetic change.

2021-05-26 05:00 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.cpp
> +        std::vector<Campaign::ScenarioBonusData> bonus;
Could you please explain me why we didn't decide to handle with an assertion other cases? I think we didn't do this because at the beginning we had non-full campaign but now we have so should we add such check?
This question is applicable for all campaigns.

2021-05-26 14:13 UTC, eos428 commented on src/fheroes2/campaign/campaign_scenariodata.cpp
> +        std::vector<Campaign::ScenarioBonusData> bonus;
Yeah, I think at this point we can assert now.

2021-05-26 14:14 UTC, eos428 commented on src/fheroes2/campaign/campaign_data.cpp
> +        _( "Subdue the unruly local lords in order to provide the Empire with facilities to operate in this region." ),
Just checked Meridian's LP for expansion campaign and yes, there should be 2 spaces between each sentence.

2021-05-26 14:49 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.cpp
> +        std::vector<Campaign::ScenarioBonusData> bonus;
Let's do then.

2021-05-26 15:08 UTC, ihhub commented on src/fheroes2/campaign/campaign_data.cpp
> +        _( "Subdue the unruly local lords in order to provide the Empire with facilities to operate in this region." ),
Could we please add these then?

2021-05-26 15:15 UTC, eos428 commented on src/fheroes2/campaign/campaign_data.cpp
> +        _( "Subdue the unruly local lords in order to provide the Empire with facilities to operate in this region." ),
Sorry I misread, it was actually a single space between sentences.
![Screenshot 2021-05-26 221455](https://user-images.githubusercontent.com/38433056/119685795-e22a4380-be6f-11eb-83bc-3a83885625a2.jpg)

2021-05-27 04:28 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.cpp
> +        std::vector<Campaign::ScenarioBonusData> bonus;
Actually, I was asking to add a **default** case in switch to cover this :)

2021-05-27 04:55 UTC, eos428 commented on src/fheroes2/campaign/campaign_scenariodata.cpp
> +        std::vector<Campaign::ScenarioBonusData> bonus;
Ah yes I forgot about the assertion in default. Latest commit should have the assertions there now.

2021-05-27 04:56 UTC, eos428 commented on src/fheroes2/game/game_campaign.cpp
> +                assert( bestHero != nullptr );
This one should also be done by now despite github not showing it.

2021-05-27 05:03 UTC, ihhub commented on src/fheroes2/campaign/campaign_scenariodata.cpp
> +        assert( scenarioID >= 0 && scenarioID < 4 );
Please remove this assertion.

2021-05-27 11:46 UTC, merged

2021-05-27 11:46 UTC, ihhub commented
@eos428 , a bunch of thanks for implementing this!