Visit artesian spring once a week
ihhub/fheroes2 pull request #3543
Opened 2021-05-27 22:56 UTC by tau3

Fixes #3470 
Only one hero will be able to visit an Artesian Spring in a week.

Fix notes:
Probably there is a more convenient way to iterate through all colors, but I couldn't find it. Maybe `IsAnyKingdomVisited` should be a member of `World` and `Kingdoms` should be an iterable class? It would simplify code.

2021-06-05 02:18 UTC, ihhub requested changes
Hi @tau3 , there are multiple comments left in this pull request. Could you please take a look?

2021-06-17 12:58 UTC, tau3 commented on src/fheroes2/world/world.cpp
> +bool IsAnyKingdomVisited( const u32 obj, const s32 dstIndex )
So the code style has had some changes? I remember changing to capitals earlier

2021-06-17 12:59 UTC, tau3 commented on src/fheroes2/world/world.cpp
> +    const int maxColor = 1 << KINGDOMMAX;
yeah, this one is better, thank you

2021-06-17 13:47 UTC, ihhub requested changes
Hi @tau3 , just one more comment. Would you mind to have a look?

2021-06-17 13:47 UTC, ihhub commented on .gitignore
> +
Could we please revert this change as it doesn't belong to the issue? It's good to separate changes

2021-06-17 13:48 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +bool IsAnyKingdomVisited( const u32 obj, const s32 dstIndex )
Most of the new code is written for functions starting with non-capital letter :)

2021-06-17 14:10 UTC, merged

2021-06-17 14:10 UTC, ihhub commented
@tau3 , thank you very much for this fix!

2021-06-17 18:21 UTC, tau3 commented on .gitignore
> +
ok, i'll push those changes to `.gitignore` in a separate one