Support PoL heroes & artifacts in "battle only" mode
ihhub/fheroes2 pull request #3549
Opened 2021-05-28 22:28 UTC by oleg-derevenetz

Need a review from someone who is familiar with PoL addon mechanics to make sure that I do the right things here and didn't forget anything. PoL doesn't add new secondary skills, spells or monsters, right?

2021-05-28 22:34 UTC, oleg-derevenetz commented
Not sure is this really a regression though...

2021-05-29 01:10 UTC, ihhub commented
> Currently heroes from PoL cannot be used in "battle only" mode (they turn into Heroes::UNKNOWN) and I suppose that there may be also issues with artifacts from PoL if this addon is not available on player's machine.
> 
> Need a review from someone who is familiar with PoL addon mechanics to make sure that I do the right things here and didn't forget anything. PoL doesn't add new secondary skills, spells or monsters, right?

Hi @oleg-derevenetz , PoL doesn't adds only new artifacts and buildings on the map.

2021-05-29 06:47 UTC, ihhub requested changes

2021-05-29 07:23 UTC, oleg-derevenetz commented on src/fheroes2/world/world.cpp
> +        fi._version = GameVersion::PRICE_OF_LOYALTY;
Hi @ihhub As far as I understand, this is the special case of auto-generated "map" created for "battle only" mode just to have some "world". This function is called only for `TYPE_BATTLEONLY` game type.

2021-05-29 07:46 UTC, oleg-derevenetz commented on src/fheroes2/world/world.cpp
> +        fi._version = GameVersion::PRICE_OF_LOYALTY;
BTW it seems that all this auto-generated 10x10 map consists of "water" tiles, that's why "battle only" battles are always on board of the ship.

2021-05-29 08:55 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +        fi._version = GameVersion::PRICE_OF_LOYALTY;
Ah, I misread it.

2021-05-29 08:57 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +        fi._version = GameVersion::PRICE_OF_LOYALTY;
For water tile: you have to modify `mp2tile.tileIndex = static_cast<uint16_t>( Rand::Get( 16, 19 ) );` line to enable other types of surfaces.

2021-05-29 08:59 UTC, oleg-derevenetz commented on src/fheroes2/world/world.cpp
> +        fi._version = GameVersion::PRICE_OF_LOYALTY;
@ihhub

> For water tile: you have to modify mp2tile.tileIndex = static_cast<uint16_t>( Rand::Get( 16, 19 ) ); line to enable other types of surfaces.

Yes, I figured it out. Boarding battles are OK for me :)

2021-05-29 08:59 UTC, merged

2021-05-29 09:00 UTC, ihhub commented
@oleg-derevenetz , thank you very much for improving the game!