Create Windows executable installers
ihhub/fheroes2 pull request #3582
Opened 2021-05-31 15:12 UTC by qarkai

Use Inno Setup for creating installers with optional download of demo version files.
Fixes #942.

2021-05-31 15:29 UTC, ihhub requested changes
Amazing work @qarkai ! I left few comments. Could you please take a look?

2021-05-31 15:29 UTC, ihhub commented on fheroes2.iss
> +#define AppName "fheroes2"
Could you please move this file to `script/windows` directory?

2021-05-31 15:29 UTC, ihhub commented on appveyor.yml
> -  - path: build\$(platform)\$(configuration)\fheroes2_windows_$(platform)_$(deploy_conf_name).zip
Please let's keep **windows** word as not everyone understands that this executable is only for Windows.

2021-05-31 15:29 UTC, ihhub commented on fheroes2.iss
> +Filename: "{app}\demo_windows.bat"; Description: "Load demo files"; Flags: postinstall runascurrentuser unchecked
This option should be **enabled** by deafult. Is it possible to make?

2021-05-31 15:29 UTC, ihhub commented on fheroes2.iss
> +Filename: "{app}\demo_windows.bat"; Description: "Load demo files"; Flags: postinstall runascurrentuser unchecked
Let's rename the message into `Download demo version files`.

2021-05-31 15:31 UTC, ihhub commented
@oleg-derevenetz , partially related to these changes: I think we need to display a message at the start of demo script to notify users that downloading takes some time. Something like `Downloading takes up to few minutes. Please wait...`. What do you think?

2021-05-31 15:34 UTC, oleg-derevenetz commented
Hi all,

I think we need to add proper support for multi-user environments (#3218) first.

2021-05-31 15:35 UTC, ihhub commented
@oleg-derevenetz , sure! I'll take a look at it again tomorrow.

2021-05-31 15:36 UTC, oleg-derevenetz commented
@ihhub

>  I think we need to display a message at the start of demo script to notify users that downloading takes some time.

Yes, it will be useful. As a separate PR?

2021-05-31 15:42 UTC, ihhub commented
> @ihhub
> 
> > I think we need to display a message at the start of demo script to notify users that downloading takes some time.
> 
> Yes, it will be useful. As a separate PR?

We could do this as a separate PR or as a part of this one. I'm okay with both options.

2021-05-31 20:54 UTC, oleg-derevenetz requested changes
Great work, @qarkai! I left just one comment, please take a look when it's convenient for you.

Also I think it would be nice to sign installer binary (and may be app binary as well, this is debatable), but it can be done later in a separate PR.

2021-05-31 20:54 UTC, oleg-derevenetz commented on script/windows/fheroes2.iss
> +AppName={#AppName}
I think it also worth to add `LicenseFile` parameter somewhere here to let user view and accept app's license since LICENSE file is included in app bundle anyway.

2021-06-01 13:41 UTC, ihhub requested changes
Hi @qarkai , the rest looks very good. I left just one comment to keep the old archive with artifacts as well. Would you mind to take a look?

2021-06-01 13:41 UTC, ihhub commented on appveyor.yml
> -  - cmd: cd C:\projects\fheroes2\build\%platform%\%configuration%
I am thinking that now all users might have permissions to run the game and also our QA team could use multiple version of the game on their machines. Could we please still keep zip archive together with the installer? There's no harm of doing such as we can still upload both.

2021-06-01 13:57 UTC, qarkai commented on appveyor.yml
> -  - cmd: cd C:\projects\fheroes2\build\%platform%\%configuration%
I'm not familiar with AppVeyor. How do I have to change `artifacts` section to keep both `exe` and `zip` files? Does 
```yaml
artifacts:
  - path: build\$(platform)\$(configuration)\fheroes2_windows_$(platform)_$(deploy_conf_name).exe
    name: fheroes2-%platform%-%deploy_conf_name%
  - path: build\$(platform)\$(configuration)\fheroes2_windows_$(platform)_$(deploy_conf_name).zip
    name: fheroes2-%platform%-%deploy_conf_name%
```
enough?

2021-06-01 14:19 UTC, ihhub commented on appveyor.yml
> -  - cmd: cd C:\projects\fheroes2\build\%platform%\%configuration%
Hi @qarkai , according to [this page](https://www.appveyor.com/docs/packaging-artifacts/) we could use something like `- path: 'build\$(platform)\$(configuration)\fheroes2_windows_$(platform)_$(deploy_conf_name).*'

Could you please try this approach?

2021-06-01 14:51 UTC, qarkai commented on appveyor.yml
> -  - cmd: cd C:\projects\fheroes2\build\%platform%\%configuration%
Not sure why [this](https://ci.appveyor.com/project/ihhub/fheroes2/builds/39413321/job/jom0qnjp7lr6r7dt#L958) happened. Everything else is ok.

2021-06-01 15:14 UTC, ihhub commented on appveyor.yml
> -  - cmd: cd C:\projects\fheroes2\build\%platform%\%configuration%
AppVeyor is not always stable. I've restarted the build.

2021-06-01 15:17 UTC, ihhub approved these changes

2021-06-01 19:49 UTC, oleg-derevenetz commented
Hi @qarkai it seems that [Icons] section is missing in `fheroes2.iss`, so installer won't create start menu and/or desktop shortcuts for this game. Is this intentional? If no, it would be nice to add an ability to create start menu group with shortcuts to `fheroes2.exe`, `demo_windows.bat` (with some descriptive names) and uninstaller, and may be (optionally) desktop shortcut to `fheroes2.exe` as well.

2021-06-01 20:00 UTC, qarkai commented
Hi @oleg-derevenetz, sorry I didn't think of shortcuts.
> with some descriptive names

Are `Free Heroes II` and `Get demo version files` ok?

2021-06-01 20:53 UTC, oleg-derevenetz commented
@qarkai

> Are `Free Heroes II` and `Get demo version files` ok?

`Free Heroes II` is OK, and let's name BAT file link as `Download demo version files` for consistency, because it's named this way in `[Run]` section.

2021-06-02 04:18 UTC, ihhub commented
> @qarkai
> 
> > Are `Free Heroes II` and `Get demo version files` ok?
> 
> `Free Heroes II` is OK, and let's name BAT file link as `Download demo version files` for consistency, because it's named this way in `[Run]` section.

Hi @qarkai and @oleg-derevenetz , I think `fheroes2` or `Run fheroes2` will be more user friendly as people might not get what **Free Heroes 2** is.

2021-06-02 04:26 UTC, ihhub commented on script/windows/fheroes2.iss
> +AppName={#AppName}
I would recommend to add these fields to have complete information about the application:
```
AppPublisher="fheroes2 Resurection Team"
AppPublisherURL="https://github.com/ihhub/fheroes2"
AppUpdatesURL="https://github.com/ihhub/fheroes2/releases"
AppSupportURL="https://discord.gg/xF85vbZ"
```

2021-06-02 10:15 UTC, qarkai commented
Looks like `demo_windows.bat` doesn't work with admin rights. I tried to run it using `Run as administrator` directly and via shortcut.
The only way it works for me is running it from cmd/PowerShell admin terminal.
I'll set `Run as administrator` flag to shortcut but that doesn't fix issue.

2021-06-02 10:27 UTC, oleg-derevenetz commented
@qarkai

> Looks like demo_windows.bat doesn't work with admin rights.

Well, in general case it shouldn't. It should download & install demo files into %APPDATA% directory of a particular user, so it should be run under user's credentials, not under elevated credentials.

2021-06-02 10:44 UTC, qarkai commented
```
runascurrentuser
If this flag is specified, the spawned process will inherit Setup/Uninstall's user credentials (typically, full administrative privileges).
```
It's interesting that script works from installer.
Right, we move demo data to %APPDATA% in #3590. I'll fix installer after it merged.

2021-06-02 10:58 UTC, oleg-derevenetz commented
@qarkai

> It's interesting that script works from installer.

May be it's running not by itself, but as an argument to cmd.exe, which in turn running under elevated privileges by installer. Anyway, it is not needed due to #3218 and #3590, because each user should have its own copy of game data files anyway.

2021-06-02 15:36 UTC, qarkai commented
So according to #3590 we'll have two scenarios for downloading demo files:
1) User checks `Download demo...` in installer, demo files should be downloaded to game's directory.
2) User runs `Download demo...` from Start menu, demo files should be downloaded to user's directory.

Did I get it right?

2021-06-02 15:40 UTC, oleg-derevenetz commented
@qarkai Yes, it seems so.

2021-06-03 04:54 UTC, merged

2021-06-03 04:55 UTC, ihhub commented
@qarkai and @oleg-derevenetz , amazing work! Thanks a lot for this!

If you have any corrections please do them within a day as tomorrow we're going to make a release.

2021-06-03 09:50 UTC, oleg-derevenetz commented
Hi @qarkai I just noticed that desktop shortcut is created not for "All Users", but only for administrator's account that runs the installer. I.e. if I run the elevated installer as "Admin", desktop shortcut is created in `C:\Users\Admin\Desktop`.

2021-06-03 10:20 UTC, oleg-derevenetz commented
Hi @qarkai Also it seems that "Game data files" link doesn't currently work as intended, possibly because %APPDATA%\fheroes2 directory doesn't exist yet when this link is created. I propose to change its target to `%WINDIR%\explorer.exe "%APPDATA%\fheroes2"` instead, this seems to work.

2021-06-03 10:25 UTC, oleg-derevenetz commented
Hi @qarkai It would be nice to fix this early enough to include fixes in 0.9.4 (if it's possible of course).

2021-06-03 10:29 UTC, qarkai commented
If there are no `%APPDATA%\fheroes2` dir and I click on shortcut with `%WINDIR%\explorer.exe "%APPDATA%\fheroes2"` target it opens Documents dir.

2021-06-03 10:32 UTC, oleg-derevenetz commented
@qarkai Yes, but if there is `%APPDATA%\fheroes2` dir, it at least opens it :) Current shortcut just does nothing (even if `%APPDATA%\fheroes2` was created later).

2021-06-03 11:30 UTC, qarkai commented
It looks like compiler adds quotes if `Filename` contains spaces and `"%WINDIR%\explorer.exe %APPDATA%\fheroes2"` is still invalid.

2021-06-03 11:36 UTC, oleg-derevenetz commented
Sad :( Is there any way around this?

2021-06-03 11:41 UTC, qarkai commented
My first idea is adding `createonlyiffileexists` flag and creating this shortcut in `demo_windows` script.

2021-06-03 11:48 UTC, oleg-derevenetz commented
Running of `demo_windows.bat` is optional and may be turned off, if there is some script necessary, then it should be a separate script.

2021-06-03 12:03 UTC, oleg-derevenetz commented
@qarkai Why don't use "%WINDIR%\explorer.exe" as `Filename` and "%APPDATA%\fheroes2" as `Parameters`?

2021-06-03 12:26 UTC, qarkai commented
@oleg-derevenetz, fixed in #3599