Campaign, some names of bonuses don't fit the box and should be shortened #3509
ihhub/fheroes2 pull request #3610
Opened 2021-06-04 02:20 UTC by felix642

Fix for issue #3509

2021-06-04 04:13 UTC, ihhub commented
Hi @felix642 , please fix code styling issues highlighted by **Code style check / clang-format (pull_request)** runner.

2021-06-04 15:16 UTC, ihhub requested changes
Hi @felix642 , I left few comments here. Would you mind to take a look?

2021-06-04 15:16 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +const char * Artifact::GetCampaignName( void ) const
Please put this function into anonymous namespace in `campaign_scenariodata.cpp` file as this is campaign specific information only.

2021-06-04 15:16 UTC, ihhub commented on src/fheroes2/spell/spell.cpp
> +const char * Spell::GetCampaignName( void ) const
Please put this function into anonymous namespace in `campaign_scenariodata.cpp` file as this is campaign specific information only.

2021-06-04 15:16 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +const char * Artifact::GetCampaignName( void ) const
Also please name the function from **non** capital letter. Once this function is moved to the described file it should accept `const int32_t artifactId` argument.

2021-06-04 15:16 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> -    {0, 12, TYPE3, _( "Ultimate Book of Knowledge" ), _( "The %{name} increases your knowledge by %{count}." )},
After required changes this file will no longer needed to be updated. Let's keep please changes minimal for now.

2021-06-04 16:32 UTC, felix642 commented on src/fheroes2/resource/artifact.cpp
> +const char * Artifact::GetCampaignName( void ) const
I wasn't  quite sure to understand the coding style. Some functions where named using upper camel case while others were using lower camel case. Is there a specific rule for that ?

2021-06-04 16:48 UTC, felix642 commented on src/fheroes2/resource/artifact.cpp
> -    {0, 12, TYPE3, _( "Ultimate Book of Knowledge" ), _( "The %{name} increases your knowledge by %{count}." )},
Yes, I'm having a little bit of trouble with clang-format. I'll take a look at that later!

2021-06-04 16:49 UTC, felix642 commented on src/fheroes2/resource/artifact.cpp
> -    {0, 12, TYPE3, _( "Ultimate Book of Knowledge" ), _( "The %{name} increases your knowledge by %{count}." )},
Yes, I'm having a bit of trouble with clang-format I'll take a look at that later !

2021-06-05 02:00 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +const char * Artifact::GetCampaignName( void ) const
My apologies for this. We inherited a a lot of old code from previous team and the coding style there wasn't present. Per our standard a function should be named with non-capital letter.

2021-06-05 02:01 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> -    {0, 12, TYPE3, _( "Ultimate Book of Knowledge" ), _( "The %{name} increases your knowledge by %{count}." )},
I'm sorry about this again. At the start of the project we formatted everything but then CI server got an updated version of clang-format (even with the same rules) leading to such situations.

2021-06-05 02:13 UTC, merged

2021-06-05 02:14 UTC, ihhub commented
@felix642 , a bunch of thanks for fixing this issue!