Scenario with random players, in the original game, random opponents are generated so that all castles are present and different when possible
ihhub/fheroes2 pull request #3618
Opened 2021-06-04 22:21 UTC by felix642

fix for issue #3476

2021-06-05 02:16 UTC, ihhub commented
Hi @felix642 , small hint: in the message please type something like `fix #1234`. In this case you're making alink between a pull request and the corresponding issue so at the time of merging the pull request the issue will be closed too :)

2021-06-06 03:57 UTC, ihhub requested changes
Hi @felix642 , I left multiple comments here. Could you please take a look?

2021-06-06 03:57 UTC, ihhub commented on src/fheroes2/system/players.cpp
> +            int raceIndex = Rand::Get( 0, availableRaces.size() - 1 );
This variable could be `const`.

2021-06-06 03:57 UTC, ihhub commented on src/fheroes2/system/players.cpp
> +            int raceIndex = Rand::Get( 0, availableRaces.size() - 1 );
Please fix compilation warning: typecast `availableRaces.size() - 1` to uint32_t. We still haven't enabled this warning properly as we're cleaning the code :(

2021-06-06 03:57 UTC, ihhub commented on src/fheroes2/system/players.cpp
> -    if ( player && player->GetRace() == Race::RAND )
Please add an assertion here just in case: `assert( player && player->GetRace() != Race::RAND );` to make sure that we're processing correct data.

2021-06-06 03:57 UTC, ihhub commented on src/fheroes2/system/players.cpp
> +    availableraces.erase( remove_if( availableraces.begin(), availableraces.end(), [player]( int race ) { return player->GetRace() == race; } ), availableraces.end() );
`race` input argument could be `const`.

2021-06-06 03:57 UTC, ihhub commented on src/fheroes2/system/players.cpp
> +    availableraces.erase( remove_if( availableraces.begin(), availableraces.end(), [player]( int race ) { return player->GetRace() == race; } ), availableraces.end() );
For easier code reading (and faster execution) we could do like this:
```
const int raceToRemove = player->GetRace();
availableraces.erase( remove_if( availableraces.begin(), availableraces.end(), [raceToRemove ]( const int race ) { return raceToRemove == race; } ), availableraces.end() );
```
As we don't make multiple calls to GetRace() method anymore. Of course it's totally optional as we aren't dealing with huge amount of data.

2021-06-06 03:57 UTC, ihhub commented on src/fheroes2/system/players.cpp
> +void PlayerRemoveAlreadySelectedRaces( Player * player, std::vector<int> & availableraces )
Please name variables in camelCase way like `availableRaces`.

2021-06-06 03:57 UTC, ihhub commented on src/fheroes2/system/players.cpp
> +void PlayerRemoveAlreadySelectedRaces( Player * player, std::vector<int> & availableraces )
Just to explain: we still have a lot of old code which was written in C way without proper coding rules so please ignore it.

2021-06-06 03:57 UTC, ihhub commented on src/fheroes2/system/players.cpp
> -    if ( player && player->GetRace() == Race::RAND )
I think we should have a check for nullptr. Could you please verify this on scenarios with only 2-3 players?

2021-06-09 00:17 UTC, felix642 commented on src/fheroes2/system/players.cpp
> +void PlayerRemoveAlreadySelectedRaces( Player * player, std::vector<int> & availableraces )
Yes I saw that ahah! This was just a mistake I didn't notice...

2021-06-09 00:30 UTC, felix642 commented on src/fheroes2/system/players.cpp
> -    if ( player && player->GetRace() == Race::RAND )
I'm not quite sure to understand why you want to add an assert ? We might receive a null pointer or a race that is not random. In that case, we simply don't get a random race for that specific player.

2021-06-09 00:30 UTC, felix642 commented on src/fheroes2/system/players.cpp
> +            int raceIndex = Rand::Get( 0, availableRaces.size() - 1 );
I added a static_cast<T>() can you confirm that this is what you wanted me to do ?

2021-06-09 13:23 UTC, ihhub commented on src/fheroes2/system/players.cpp
> -    if ( player && player->GetRace() == Race::RAND )
I meant that `player` could be nullptr and then here we access a nullptr object which leads to a crash but looking at the code I see that `for_each( begin(), end(), []( Player * player ) { player->SetPlay( true ); } );` doesn't have a check so it's fine to have no assertion here. My apologies.

2021-06-09 13:25 UTC, merged

2021-06-09 13:25 UTC, ihhub commented
@felix642 , thank you so much for the fix!