Adventure map, AI behavior, red AI player's hero Thundax does not capture a defenseless castle (0.9.4 3612)
ihhub/fheroes2 pull request #3626
Opened 2021-06-05 02:46 UTC by felix642

Fix for issue #3625.

I'm not quite sure this is the best way to fix it. I will have to do some extended testing to see how to ai react. If you have any suggestion I would be glad to hear it!

2021-06-06 02:36 UTC, idshibanov requested changes
I think you're treating a side effect rather then fixing the underlying issue. It might fix it for that save, but will be worse in others.

I have yet to debug the save, but I believe core issue here right now is `dangerousTaskPenalty`. Essentially AI doesn't think he can hold the captured object, so ignores it. We need an edge case that will encourage AI to go to castle if current map region is dangerous.

2021-06-06 02:36 UTC, idshibanov commented on src/fheroes2/castle/castle.cpp
> +        value += 10;
This definitely shouldn't be in this method since it's not building related. Also `army` references garrison only, so this will trigger even if there's defending hero in the castle.

2021-06-06 02:36 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +        return value - ( 1.5 * distance * std::log10( distance ) );
This can potentially break a lot of other logic since AI heroes will focus on objects close to them (e.g. picking up resource instead of capturing a mine).

2021-06-06 04:01 UTC, ihhub commented
Hi @felix642 and @idshibanov , I think we need to make changes in `double Normal::getObjectValue` method for **if ( objectID == MP2::OBJ_CASTLE ) {** case and increase object value if the castle is empty.

As mentioned by @idshibanov , we have `int AI::Normal::getPriorityTarget` method where we add a penalty for objects with high threat:
```
const RegionStats & regionStats = _regions[world.GetTiles( node.first ).GetRegion()];
if ( heroStrength < regionStats.highestThreat )
    value -= dangerousTaskPenalty;
```

What I could suggest is that for this situation we have to ignore (?) the threat.

2021-06-06 04:07 UTC, idshibanov commented
> I think we need to make changes in double Normal::getObjectValue method

> What I could suggest is that for this situation we have to ignore (?) the threat.

Agree with both suggestions.

2021-06-12 18:38 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                    value -= dangerousTaskPenalty / 2;
You can use `Castle::GetGarrisonStrength()` instead, it will account for special cases automatically.

Also if `castle` isn't nullptr I don't think you have to check `node.second` value.

2021-06-14 15:28 UTC, ihhub requested changes
Hi @felix642 , I left just one comment here. Could you please take a look?

2021-06-14 15:28 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                    value += 5;
I'd say that this value is too small. Why don't we add some percentage instead? For example, 50%.

2021-06-19 02:11 UTC, felix642 commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                    value += 5;
After testing, I felt like 50% was a bit too much... I did change it to 25% I do not know if you think this is enough ?

2021-06-19 03:19 UTC, idshibanov approved these changes

2021-06-19 06:23 UTC, ihhub reviewed
Hi @felix642 , I left one comment and one question. Could you please take a look?

I fixed merging conflict.

2021-06-19 06:23 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                if ( castle->GetActualArmy().GetStrength() <= 0 )
We could do even better: `if ( castle->GetActualArmy().isValid() )` which returns **true** only for an empty army.

2021-06-19 06:23 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                if ( castle && ( castle->GetGarrisonStrength( &hero ) <= 0 || castle->GetColor() == hero.GetColor() ) )
My apologies, @felix642 . Could you please explain the logic here?

2021-06-20 02:46 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                if ( castle && ( castle->GetGarrisonStrength( &hero ) <= 0 || castle->GetColor() == hero.GetColor() ) )
Ah, I think I got the idea.

2021-06-20 15:19 UTC, felix642 commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                if ( castle && ( castle->GetGarrisonStrength( &hero ) <= 0 || castle->GetColor() == hero.GetColor() ) )
I'm checking if the castle is empty (no troops inside) or if it is the player's castle.

2021-06-20 15:38 UTC, felix642 commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                if ( castle->GetActualArmy().GetStrength() <= 0 )
Are you sure about that? I'm currently looking at the method and it doesn't seems to return true for an empty army. 

`bool Troops::isValid( void ) const
{
    for ( const_iterator it = begin(); it != end(); ++it ) {
        if ( ( *it )->isValid() )
            return true;
    }
    return false;
}`

If we look at the isValid() method, it will always return false if 
`
it.begin() == it.end()
`
So I'm not quite sure why it would return true on an empty army..? There might be something I don't understand or don't see...

2021-06-21 11:27 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                if ( castle->GetActualArmy().GetStrength() <= 0 )
It returns **true** only if a monster returns **true** for `isValid` call.

2021-06-21 14:02 UTC, felix642 commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                if ( castle->GetActualArmy().GetStrength() <= 0 )
Exactly, but you told me that it "returns true only for an empty army" so I'm kind of confused right now...

2021-06-21 14:05 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                if ( castle->GetActualArmy().GetStrength() <= 0 )
My bad. I meant `if ( !castle->GetActualArmy().isValid() )` with NOT logical operation.

2021-06-22 11:22 UTC, merged

2021-06-22 11:23 UTC, ihhub commented
@felix642 , a bunch of thanks for improving AI!