I3622 Fixed the displayed text in the army bar
ihhub/fheroes2 pull request #3627
Opened 2021-06-05 03:33 UTC by felix642

fix #3622

2021-06-05 07:33 UTC, oleg-derevenetz requested changes
Hi @felix642, I left a few comments, could you please take a look?

2021-06-05 07:33 UTC, oleg-derevenetz commented on src/fheroes2/army/army.cpp
> +    for ( const_iterator it = begin(); it != end(); ++it ) {
I'd use `std::accumulate()` instead of all these old-school iterators. Something like:

`return std::accumulate( begin(), end(), 0u, []( uint32_t total, const Troop * item ) { return item->isValid() ? total + item->GetCount() : total; } );`

Or range-based `for` at least.

2021-06-05 07:33 UTC, oleg-derevenetz commented on src/fheroes2/army/army.cpp
> +u32 Army::getTotalCount( void ) const
Please use standard type `uint32_t` as a return type instead of `u32` in a new code.

2021-06-05 07:33 UTC, oleg-derevenetz commented on src/fheroes2/army/army.h
> +    u32 getTotalCount( void ) const;
Please use standard type `uint32_t` as a return type instead of `u32` in a new code.

2021-06-05 07:33 UTC, oleg-derevenetz commented on src/fheroes2/army/army_bar.cpp
> +    bool save_last_troop = selectedTroop.GetArmy()->getTotalCount() <= 1;
This will not work properly. "Save last troop" logic should be applied only if army is led by a hero. With this change, if there is only one unit left in castle garrison, you will get "Cannot move last troop" status message if you are going to move this unit from castle garrison to the guest hero's army, even if you in fact can. Additional checks for a hero presence (like in `Army::SaveLastTroop()`) are needed here.

2021-06-06 04:15 UTC, ihhub requested changes
Hi @felix642 , there are just 2 minor comments left. Would you mind to take a look?

2021-06-06 04:15 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +uint32_t Army::getTotalCount( void ) const
Please remove **void** from method's input parameters. It is redundant.

2021-06-06 04:15 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +    return std::accumulate( begin(), end(), 0u, []( uint32_t count, Troop * troop ) { return troop->isValid() ? count + troop->GetCount() : count; } );
Both input arguments of the lambda function could be `const`.

2021-06-09 00:07 UTC, felix642 commented on src/fheroes2/army/army.cpp
> +uint32_t Army::getTotalCount( void ) const
I also removed it from the .h file.

2021-06-09 13:32 UTC, ihhub commented
Hi @Branikolog , could you please test thes changes?

2021-06-10 11:19 UTC, Branikolog commented
@ihhub , @felix642 
Everything seems to work fine.
I noticed, that in the OG we have "to garrison" in the statement.
![image](https://user-images.githubusercontent.com/55348946/121516408-d81f4d80-c9f6-11eb-8c0f-a696f768863b.png)

2021-06-10 13:35 UTC, felix642 commented
> @ihhub , @felix642
> Everything seems to work fine.
> I noticed, that in the OG we have "to garrison" in the statement.
> ![image](https://user-images.githubusercontent.com/55348946/121516408-d81f4d80-c9f6-11eb-8c0f-a696f768863b.png)

Should I change the text as well?

2021-06-10 14:16 UTC, Branikolog commented
@felix642 
I think, making it the same to original is not a bad idea. ;)

2021-06-10 16:13 UTC, ihhub commented
Hi @felix642 , let's make it

> > @ihhub , @felix642
> > Everything seems to work fine.
> > I noticed, that in the OG we have "to garrison" in the statement.
> 
> Should I change the text as well?

Hi @felix642 , let's do this in a separate pull request.

2021-06-10 16:13 UTC, merged

2021-06-10 16:14 UTC, ihhub commented
@felix642 , thanks a lot for the fix!