Implement Town Screen Hotkeys
ihhub/fheroes2 pull request #3641
Opened 2021-06-06 09:38 UTC by eos428

fix #3640
fix #3438

2021-06-07 13:09 UTC, ihhub commented
Hi @eos428 , could you please fix compilation on Windows (AppVeyor)?

2021-06-28 13:33 UTC, ihhub commented
Hi @Branikolog , could you please test these changes?

2021-06-28 14:57 UTC, ihhub requested changes
Hi @eos428 , I left just one comment for now. Could you please check it?

2021-07-20 14:11 UTC, ihhub requested changes
Hi @eos428 , I left 2 comments. Would you mind to take a look?

2021-07-20 14:11 UTC, ihhub commented on src/fheroes2/castle/castle_dialog.cpp
> +    auto getPressedBuildingHotkey() -> building_t
Why can't we just do `building_t getPressedBuildingHotkey()` ?

2021-07-20 14:11 UTC, ihhub commented on src/fheroes2/castle/castle_dialog.cpp
> +            for ( auto it = cacheBuildings.cbegin(); it != cacheBuildings.cend(); ++it ) {
Hi @eos428 , my apologies for a very late request but could we please separate two changes into 2 pull requests? I feel it'd be easier to review with much smaller changes.

2021-07-20 22:46 UTC, eos428 commented on src/fheroes2/castle/castle_dialog.cpp
> +    auto getPressedBuildingHotkey() -> building_t
Back then there was a nagging from clang_tidy. I'll revert this change soon

2021-07-20 23:02 UTC, eos428 commented on src/fheroes2/castle/castle_dialog.cpp
> +            for ( auto it = cacheBuildings.cbegin(); it != cacheBuildings.cend(); ++it ) {
Hi @ihhub, it's alright. Going forward with this PR I'll remove the refactoring for now. It'll be up again in the PR after this :)

2021-07-21 13:30 UTC, merged

2021-07-21 13:30 UTC, ihhub commented
@eos428 , thank you very much for this improvement!