Adding gettext to the list of installed packages
ihhub/fheroes2 pull request #3645
Opened 2021-06-06 21:28 UTC by pr1vateer

In [compilation instructions for Linux](https://github.com/ihhub/fheroes2#macos-and-linux) it's implied that you just need to run **install_sdl_2.sh** or **install_sdl_1.sh** to install dependencies (no other steps are present).

However both of these files are missing **gettext** package so if you follow the instruction, your compilation will fail.

2021-06-07 12:24 UTC, ihhub requested changes
Hi @pr1vateer , I left 2 comments here. Would you mind to take a look?

2021-06-07 12:24 UTC, ihhub commented on script/linux/install_sdl_1.sh
> +sudo apt-get install -y gettext
Please combine this line with the line 10 to speed up package installation.

2021-06-07 12:24 UTC, ihhub commented on script/linux/install_sdl_2.sh
> +sudo apt-get install -y gettext
Please combine this line with the line 10 to speed up package installation.

2021-06-08 18:38 UTC, pr1vateer commented on script/linux/install_sdl_1.sh
> +sudo apt-get install -y gettext
Sure, moved it in both places

2021-06-08 18:47 UTC, pr1vateer commented
I think it's also good to squash those commits so did that as well.

2021-06-09 13:26 UTC, merged

2021-06-09 13:26 UTC, ihhub commented
@pr1vateer , thank you very much for the contribution to the project!