OBJ enum
ihhub/fheroes2 pull request #3672
Opened 2021-06-11 19:41 UTC by vasilenkoalexey

Proposal to use MP2::OBJ enumeration for object on map instead of different types. But here compatibility with the current Sav formart is lost, since some serializable objects have been changed. I can fix this with a custom serializer. Also, we can create class enum and use for example MP2::OBJ::ZERO instead if MP2::OBJ_ZERO.

2021-06-11 19:53 UTC, undef21 commented on src/fheroes2/agg/m82.cpp
> +u32 M82::GetIndexLOOP00XXFromObject( const MP2::OBJ obj )
Since you change this code, could you please replace type with uint32_t?

2021-06-11 22:21 UTC, vasilenkoalexey commented on src/fheroes2/agg/m82.cpp
> +u32 M82::GetIndexLOOP00XXFromObject( const MP2::OBJ obj )
Sure

2021-06-12 00:50 UTC, felix642 reviewed
Hi @vasilenkoalexey! It is from my understanding that we want to remove references to u32 in the code. I saw a bunch of them in the lines that you changed. Could you please replace them with uint32_t ? 
Thank you!

2021-06-12 00:50 UTC, felix642 commented on src/fheroes2/objects/mounts.cpp
> +MP2::OBJ ObjMnts2::GetActionObject( u32 )
Replace this with uint32_t also.

2021-06-12 00:50 UTC, felix642 commented on src/fheroes2/resource/artifact.cpp
> +u32 GoldInsteadArtifact( const MP2::OBJ obj )
Same as the 2 other comments.

2021-06-12 00:50 UTC, felix642 commented on src/fheroes2/resource/artifact.h
> +u32 GoldInsteadArtifact( const MP2::OBJ obj );
uint32_t again.

2021-06-12 00:50 UTC, felix642 commented on src/fheroes2/world/world.h
> +    u32 CountCapturedObject( const MP2::OBJ obj, int col ) const;
uint_32t.

2021-06-12 00:50 UTC, felix642 commented on src/fheroes2/world/world.h
> +    u32 GetCount( const MP2::OBJ obj, int ) const;
uint_32t.

2021-06-12 00:50 UTC, felix642 commented on src/fheroes2/world/world.cpp
> +u32 World::CountCapturedObject( const MP2::OBJ obj, int col ) const
uint32_t.

2021-06-12 13:50 UTC, ihhub requested changes
Hi @vasilenkoalexey , there are multiple comments. Would you mind to take a look?

2021-06-12 13:50 UTC, ihhub commented on src/fheroes2/maps/mp2.h
> +    enum OBJ : uint8_t
Please name this enumeration as **MapObjectType** as the current **OBJ** is not obvious.

2021-06-12 13:50 UTC, ihhub commented on src/fheroes2/maps/mp2.h
> +    enum OBJ : uint8_t
Could you please explain why this enumeration has **uint8_t** type? I know that the original maps has this type but once we read them from the map format we don't bound to it. Do we use `uint8_t` for saves?

2021-06-12 13:50 UTC, ihhub commented on src/engine/pathfinding.h
> +template <class T>
There is only one place which used `uint16_t`. Also this class shouldn't depend on implementation details of maps. Perhaps @idshibanov  could explain why we used `uint16_t` initially and if there anything which stops us to use `int32_t` or `uint32_t`.

2021-06-12 13:50 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +        switch ( obj ) {
Renaming `object` to `obj` seems an unneccesary change even to have the standard naming. If we want to have a standard one shouldn't it be `objectType` as **object** is misleading?

2021-06-12 15:39 UTC, idshibanov commented on src/engine/pathfinding.h
> +template <class T>
This change is fine, it has to be templated because it's used in battle class. These nodes are not serialized anywhere at the moment so we can easily convert it to uint32_t.

2021-06-12 18:44 UTC, vasilenkoalexey commented on src/fheroes2/heroes/heroes_action.cpp
> +        switch ( obj ) {
I agreed, if we rename enum to `MapObjectType` then `objectType` looks good

2021-06-12 21:11 UTC, vasilenkoalexey commented on src/fheroes2/maps/mp2.h
> +    enum OBJ : uint8_t
> Do we use `uint8_t` for saves?

Yes, I tried to keep compatibility with the current save file. Type of `Tiles::mp2_object` is `uint8_t` but `IndexObject` derived from `std::pair<s32, int>` and ObjectColor derived from `std::pair<int, int>` where `int` is a type of map object. It mean, right now we store to sav file object with different types.
We have to decide - keep the current file format and implement custom serializers or determine the unified type of object, but then we will lose compatibility with the current version of the sav file...

2021-06-12 21:17 UTC, vasilenkoalexey commented on src/fheroes2/maps/mp2.h
> +    enum OBJ : uint8_t
Done

2021-06-12 21:17 UTC, vasilenkoalexey commented on src/fheroes2/heroes/heroes_action.cpp
> +        switch ( obj ) {
Done

2021-06-28 14:18 UTC, ihhub commented
I moved this pull request to 0.9.6 as these changes are not critical and more of code quality improvements. Also they have to wait a bit since we're changing the way how we handle this kind of information.

2021-08-15 03:03 UTC, ihhub commented
Hi @vasilenkoalexey , since we made a **lot** of changes in the past could you please either update this pull request or close and create one based on the latest commit from master branch? If you choose to go with the second approach could you please keep the changes minimal so it'll be easier to review?

2021-08-16 12:39 UTC, closed without merging