CMake: Implementing optional deploy of demo data
ihhub/fheroes2 pull request #3698
Opened 2021-06-15 20:45 UTC by winterheart

Now CMake project supports `-DENABLE_DEMO` option which controls fetching and installing HoMM II demo data.

2021-06-17 20:14 UTC, oleg-derevenetz reviewed
Although demo data deployment works perfectly by itself, there is one issue - fheroes2 binary is unable to find deployed files after `cmake --install` phase. That's because, although the CMake variables `CONFIGURE_FHEROES2_LOCALEDIR` and `CONFIGURE_FHEROES2_DATA` were set in CMakeLists.txt, they were never turned into corresponding preprocessor definitions. Proposed commit fixes this (along with adding proper quoting around their string values - so as not to leave it at the mercy of shell, there are many different shells and quoting rules may change from one shell to another).

P.S. There is one issue in my approach too - it assumes that `CONFIGURE_FHEROES2_*` variables contain relative paths, so `${CMAKE_INSTALL_PREFIX}` is prepended to them. This may break if they will contain absolute paths instead. Need to think how to correctly convert CMake variables to preprocessor definitions considering both possibility of relative path and possibility of absolute path. Any ideas?

2021-06-22 13:35 UTC, ihhub requested changes
Hi @winterheart , I left few comments here. Would you mind to take a look?

2021-06-22 13:35 UTC, ihhub commented on CMakeLists.txt
> +option(ENABLE_DEMO     "Fetch and install HoMM II demo data" OFF)
Let's call it please `GET_HOMM2_DEMO`. People might get confused by this option without reading the description.

2021-06-22 13:35 UTC, ihhub commented on src/Makefile.switch
> +CXXFLAGS := $(CXXFLAGS) $(ARCH) -D__SWITCH__ -DCONFIGURE_FHEROES2_DATA=//switch/fheroes2
@dimag0g , could you please verify this change?

2021-06-22 13:35 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +#define EXPANDDEF( DEF ) STRINGIFY( DEF )
Why do we need 2 macros if we can use one single `EXPANDDEF` calls `STRINGIFY`?

2021-06-22 13:48 UTC, oleg-derevenetz commented on src/fheroes2/system/settings.cpp
> +#define EXPANDDEF( DEF ) STRINGIFY( DEF )
@ihhub AFAIK when you use a macro as an argument for another macro (like here) it's only substituted when it is not used with # or ##, so we need additional macro EXPANDDEF that will expand initial macro first and then call STRINGIFY that will add quotes. May be I'm wrong of course, but you can check it :)

2021-06-23 16:15 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +#define EXPANDDEF( DEF ) STRINGIFY( DEF )
You're totally right. It works only with ##... I need more rest :)

2021-06-28 13:25 UTC, merged

2021-06-28 13:26 UTC, ihhub commented
@winterheart , thank you very much for this improvement!