Rework on monster related code and added monster description
ihhub/fheroes2 pull request #3699
Opened 2021-06-16 15:05 UTC by ihhub

close #3397

2021-06-16 21:50 UTC, oleg-derevenetz requested changes
Hi @ihhub I left a few notes here, would you mind taking a look?

2021-06-16 21:50 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_objects.cpp
> +    return msg << static_cast<const MapObjectSimple &>( obj ) << obj.condition << obj.count;
BTW, where this MapMonster type actually used? I can see that they may be read and written in world/world.cpp in these operators:

```
StreamBase & operator>>( StreamBase & msg, MapObjects & objs )
StreamBase & operator<<( StreamBase & msg, const MapObjects & objs )
```

But I couldn't find at least one place where they were originally created and placed in this MapObjects...

2021-06-16 21:50 UTC, oleg-derevenetz commented on src/fheroes2/monster/monster_info.h
> +        MonsterAbility() = delete;
Since we already have user-defined constructors for this struct, default constructor will not be generated, so there is no need to explicitly delete it.

2021-06-16 21:50 UTC, oleg-derevenetz commented on src/fheroes2/monster/monster_info.h
> +        MonsterWeakness() = delete;
Since we already have user-defined constructors for this struct, default constructor will not be generated, so there is no need to explicitly delete it.

2021-06-16 21:50 UTC, oleg-derevenetz commented on src/fheroes2/monster/monster_info.h
> +        MonsterData() = delete;
Since we already have user-defined constructor for this struct, default constructor will not be generated, so there is no need to explicitly delete it.

2021-06-16 21:50 UTC, oleg-derevenetz commented on src/fheroes2/monster/monster_info.cpp
> +            { M82::UNKNOWN,  M82::UNKNOWN,  M82::UNKNOWN,  M82::UNKNOWN , M82::UNKNOWN  },
Since not all of us use IDEs with all these fancy IntelliSense features, it would be convenient to add a comment describing what all these columns mean :)

2021-06-16 21:50 UTC, oleg-derevenetz commented on src/fheroes2/monster/monster_info.cpp
> +            { 0,  0,  0,  0,  0,   Speed::VERYSLOW,  0 , std::set<fheroes2::MonsterAbility>(), std::set<fheroes2::MonsterWeakness>() },
Same here - it would be convenient to add a comment describing what all these columns mean.

2021-06-16 21:50 UTC, oleg-derevenetz commented on src/fheroes2/monster/monster_info.cpp
> +            { "Unknown Monster",  "Unknown Monsters",  0,  Race::NONE, 0, { 0,    0, 0, 0, 0, 0, 0 } },
Same here - it would be convenient to add a comment describing what all these columns mean.

2021-06-16 21:50 UTC, oleg-derevenetz commented on src/fheroes2/monster/monster_info.cpp
> +            if ( foundAbility == abilities.end() ) {
Shouldn't it be "!=" here instead of "=="?

2021-06-17 04:59 UTC, ihhub commented on src/fheroes2/maps/maps_objects.cpp
> +    return msg << static_cast<const MapObjectSimple &>( obj ) << obj.condition << obj.count;
Hi @oleg-derevenetz , It wasn't used anywhere. The functions were empty.

2021-06-17 05:53 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_objects.cpp
> +    return msg << static_cast<const MapObjectSimple &>( obj ) << obj.condition << obj.count;
Maybe then remove it as part of this PR?

2021-06-17 06:10 UTC, ihhub commented on src/fheroes2/maps/maps_objects.cpp
> +    return msg << static_cast<const MapObjectSimple &>( obj ) << obj.condition << obj.count;
I'll do it.

2021-06-17 09:30 UTC, ihhub commented on src/fheroes2/maps/maps_objects.cpp
> +    return msg << static_cast<const MapObjectSimple &>( obj ) << obj.condition << obj.count;
Actually it's used in `StreamBase & operator<<( StreamBase & msg, const MapObjects & objs )`. Class inheritance makes it hard to track the changes. `Monster` class itself had no logic inside >> and << operators so I removed them.

2021-06-17 09:37 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_objects.cpp
> +    return msg << static_cast<const MapObjectSimple &>( obj ) << obj.condition << obj.count;
Hi @ihhub

> Actually it's used in `StreamBase & operator<<( StreamBase & msg, const MapObjects & objs )`. Class inheritance makes it hard to track the changes. `Monster` class itself had no logic inside >> and << operators so I removed them.

Yes, it can be loaded and saved using these operators, but how it appears in MapObjects to be saved first and then loaded? I can not yet understand where and in what cases it is initially created to be placed into MapObjects.

2021-06-17 09:40 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_objects.cpp
> +    return msg << static_cast<const MapObjectSimple &>( obj ) << obj.condition << obj.count;
@ihhub At first I thought that this class is used to implement groups of neutral monsters on the map, but it seems that it isn't the case, because they are implemented using `Maps::Tiles::QuantityTroop()`.

2021-06-17 09:42 UTC, ihhub commented on src/fheroes2/maps/maps_objects.cpp
> +    return msg << static_cast<const MapObjectSimple &>( obj ) << obj.condition << obj.count;
I know. The code is so confusing. We need to make it better :(

2021-06-17 09:44 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_objects.cpp
> +    return msg << static_cast<const MapObjectSimple &>( obj ) << obj.condition << obj.count;
It seems that this class was used once for something, but I don't see any use of it now.

2021-06-17 11:40 UTC, ihhub commented
Hi @oleg-derevenetz , I addressed all your comments. Could you please take a look again?

2021-06-17 11:41 UTC, ihhub commented on src/fheroes2/maps/maps_objects.cpp
> +    return msg << static_cast<const MapObjectSimple &>( obj ) << obj.condition << obj.count;
We can't just simply remove it as we need it for backwards compatibility.

2021-06-17 11:47 UTC, ihhub commented on src/fheroes2/maps/maps_objects.cpp
> +    return msg << static_cast<const MapObjectSimple &>( obj ) << obj.condition << obj.count;
Let's remove it outside this pull request. I did some changes for versioning but we can finish them separately.

2021-06-17 13:26 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_objects.cpp
> +    return msg << static_cast<const MapObjectSimple &>( obj ) << obj.condition << obj.count;
@ihhub OK :) BTW I don't think that it will break backwards compatibility, because it doesn't look like MapObjects contained objects with type MapMonster in the foreseeable past (because they weren't created anywhere). But I agree that this is not entirely on the subject of this PR :)

2021-06-17 14:25 UTC, oleg-derevenetz approved these changes
Hi @ihhub Found no issues, just one optional suggestion and a question.

2021-06-17 14:25 UTC, oleg-derevenetz commented on src/fheroes2/monster/monster_info.h
> +        EXTRA_DAMAGE_FROM_CERTAIN_SPELL
As far as I understand, they are not used in any spell-related logic yet?

2021-06-17 14:31 UTC, ihhub commented on src/fheroes2/monster/monster.cpp
> +        msg >> dummyMonster;
I'll add it just not to forget.

2021-06-17 14:33 UTC, ihhub commented on src/fheroes2/monster/monster_info.h
> +        EXTRA_DAMAGE_FROM_CERTAIN_SPELL
Not, yet. I haven't changed everything as I wanted to keep minimal changes for now. We have to change a bunch of code in battle-related files. The main purpose of this pull request was to add monster's description field.

2021-06-18 04:52 UTC, merged