code cleanup: Don't use else after return
ihhub/fheroes2 pull request #3700
Opened 2021-06-16 17:51 UTC by qarkai

Fix clang-tidy [readability-else-after-return](https://releases.llvm.org/11.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/readability-else-after-return.html) warnings. Flattens code a little bit.

2021-06-20 05:23 UTC, ihhub commented
Hi @qarkai , this change is more personal readability change rather than code correction. For example:
```
int getMagicNumber( const bool truth )
{
    if ( truth )
    {
        return 42;
    }
    else {
        return 51;
    }
}
```
With proposed changes the code will looks like:
```
int getMagicNumber( const bool truth )
{
    if ( truth )
    {
        return 42;
    }

    return 51;
}
```

Both versions of the code are eligible and none of them is wrong. For some cases the first version is easier to read, for another - the second.

If we want to have such rule how are we going automatically enforce it for the subsequent changes?

2021-06-20 07:39 UTC, qarkai commented
```c++
    if ( truth )
    {
        return 42;
    }

    return 51;
```
We could change it to ` return truth ? 42 : 51;`. I'll rewrite some changes.

> If we want to have such rule how are we going automatically enforce it for the subsequent changes?

I ran tool from IDE but I guess we could check output of something like `clang-tidy --checks=readability-else-after-return -p build **/*.cpp` after running `cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ...`

2021-06-20 10:05 UTC, oleg-derevenetz commented
In general, I don't like to enforce such things, because i's a matter of taste. There may be "guard" `if`s, like this:

```
if (check_1) {
    return false;
}

if (check_2) {
    return false;
}

return something();
```

In this case "no else after return" rule is justifiable. But there may be also "choice" `if`s, like this:

```
if (condition) {
    return something();
} else {
    return something_else();
}
```

and in this case "no else after return" rule is not always good in terms of readability. Yes, sometimes it's handy to replace `if` by `?:`, but sometimes it's not:

```
if (condition) {
    do_something();

    return something();
} else {
    do_something_else();

    return something_else();
}
```

2021-06-20 12:42 UTC, qarkai commented
@ihhub, @oleg-derevenetz, @idshibanov I'll revert anything you don't like.

2021-06-22 13:46 UTC, ihhub requested changes
Hi @qarkai , I left multiple comments here. Could you please check them?

2021-06-22 13:46 UTC, ihhub commented on src/engine/screen.cpp
> +            return fheroes2::Cursor::isVisible() && ( _emulation || ( SDL_ShowCursor( SDL_QUERY ) == SDL_ENABLE ) );
This change compliates the code reading. Could you please revert it?

2021-06-22 13:46 UTC, ihhub commented on src/fheroes2/battle/battle_cell.h
> +        bool isPassable( const Unit & b, int direction ) const;
Could we please rename the first input argument into `monster`? In this case it'll be obvious what **b** is :)

2021-06-22 13:46 UTC, ihhub commented on src/fheroes2/gui/text.cpp
> +    if ( 0x21 <= character && character <= fheroes2::AGG::ASCIILastSupportedCharacter( ft ) )
Could you please swap arguments for comparison `character >= 0x21`. Reading code in such way is a bit unusual.

2021-06-22 13:46 UTC, ihhub commented on src/fheroes2/objects/objtown.cpp
> +        result |= Direction::TOP;
We could use like this: `return ( result |  Direction::TOP );`.

2021-06-22 14:48 UTC, qarkai commented
Unfortunately `clang-tidy` didn't find a bunch of else-after-return code, I'll close this PR then. Sorry for the noise.

2021-06-22 14:48 UTC, closed without merging

2021-06-22 14:52 UTC, ihhub commented
Hi @qarkai , no worries about this!

Is it possible to add clang-tidy into our pipeline? As I wrote previously some checks are really useful like unused headers and it'd be great to catch them.

2021-06-22 15:12 UTC, qarkai commented
@ihhub I believe it's possible. There are [some actions](https://github.com/marketplace?type=actions&query=clang-tidy+) in marketplace which add support for clang-tidy.
Probably the main question is which checks do you want to run. There are a lot of them: https://clang.llvm.org/extra/clang-tidy/checks/list.html.

2021-06-22 15:57 UTC, oleg-derevenetz commented
Hi @ihhub @qarkai Please don't blindly trust to tools such as clang-tidy, especially in terms of "unused" headers. clang-tidy checks only particular build configuration, and it knows nothing about others. For example, on older Xcode versions there was no `abs(int)` in `cmath.h`, which breaks the build:

https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/145739/steps/install-port/logs/stdio

So I added `#include <cstdlib>` to the appropriate files in this commit: https://github.com/ihhub/fheroes2/commit/0998f27b07716055d29ef2a89918cb2879ddcb49, which was subsequently removed in https://github.com/ihhub/fheroes2/commit/9efabb1fe74febdc7ee9297a5a83baea68c70c00 ("Remove unused headers and forward declarations"), and this will break the build again.

2021-06-22 16:04 UTC, qarkai commented
Hi @oleg-derevenetz probably those headers should be added under `#ifdef old xcode`. It allows to:
* ignore them for `clang-tidy`, `iwyu`, etc.
* easily remove them when support for old Xcode is dropped

2021-06-22 16:50 UTC, oleg-derevenetz commented
> Hi @oleg-derevenetz probably those headers should be added under `#ifdef old xcode`. It allows to:

In this case people who will build this on older Xcode should know somehow that they should add this define via command line, or we should add some code that will recognize older Xcode versions (using CMake, for example) and add this define automatically. Lots of trouble.

2021-06-22 19:07 UTC, qarkai commented
At least those includes could be marked with something like `// for old Xcode`.