update gitignore
ihhub/fheroes2 pull request #3703
Opened 2021-06-17 18:26 UTC by tau3

- ignore cmake artifacts
- ignore vim temp files
- ignore lang server config file

2021-06-18 10:53 UTC, qarkai commented on .gitignore
> +*.cmake
This ignores possible changes in `cmake/FindSDL2*.cmake` modules. IMHO build directory on line 60 is enough since it covers all "cmake artifacts".

2021-06-28 13:38 UTC, ihhub requested changes
Hi @tau3 , based on @qarkai comment and swp file extension we might no need these changes in first place. Could you please check?

2021-06-28 13:38 UTC, ihhub commented on .gitignore
> +*.swp
This is definitely an overkill. What if other person will use another editor with its own temp files?

2021-07-01 14:10 UTC, ihhub commented
I'm closing this pull request for now since it doesn't bring any value according the comments.

2021-07-01 14:10 UTC, closed without merging