Maps::FileInfo: don't save the full path to the map file, save only the basename
ihhub/fheroes2 pull request #3724
Opened 2021-06-19 23:01 UTC by oleg-derevenetz

fix #3722

2021-06-22 11:28 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left one comment and one question. Could you please take a look?

2021-06-22 11:28 UTC, ihhub commented on src/fheroes2/game/game_io.cpp
> +    conf.SetMapsFile( Settings::GetLastFile( "maps", System::GetUniversalBasename( conf.MapsFile() ) ) );
If is correct that this call is needed only for saves which were made before these changes?

2021-06-22 11:28 UTC, ihhub commented on src/engine/system.cpp
> +    }
Here we're doing double loop while we could run only once:
```
const char sep = ( SEPARATOR == '/' ) ? '\\' : '/';
std::replace( path.begin(), path.end(), sep, SEPARATOR );
```
because we have to replace only separators which are different from the curent system.

2021-06-22 11:39 UTC, oleg-derevenetz commented on src/fheroes2/game/game_io.cpp
> +    conf.SetMapsFile( Settings::GetLastFile( "maps", System::GetUniversalBasename( conf.MapsFile() ) ) );
Hi @ihhub Yes, I believe so. Do you want to add a `static_assert` here to remove it later?

2021-06-22 11:41 UTC, oleg-derevenetz commented on src/engine/system.cpp
> +    }
If we have just two types of separators, yes, we can replace it with `?:`. It doesn't look like we will run fheroes2 on systems with other types of separators :)

2021-06-22 11:51 UTC, ihhub commented on src/fheroes2/game/game_io.cpp
> +    conf.SetMapsFile( Settings::GetLastFile( "maps", System::GetUniversalBasename( conf.MapsFile() ) ) );
Yes, please. Let's add an assertion so in the future we won't need to waste CPU resources for this and then we can remove `GetUniversalBasename` method.

2021-06-22 13:28 UTC, ihhub commented on src/engine/system.cpp
> +    }
I know no more than 2 separators in the wild :)

2021-06-22 19:53 UTC, oleg-derevenetz commented on src/engine/system.cpp
> +    }
I remember one old system with colon (:) as a directory separator :) But I hope we will not support it :)

2021-06-23 16:04 UTC, ihhub commented on src/fheroes2/game/game_io.cpp
> +    conf.SetMapsFile( Settings::GetLastFile( "maps", System::GetUniversalBasename( conf.MapsFile() ) ) );
Should we add a check here:
```
if ( binver < FORMAT_VERSION_095_RELEASE ) {
    conf.SetMapsFile( Settings::GetLastFile( "maps", System::GetUniversalBasename( conf.MapsFile() ) ) );
}
```
?

So we won't waste resources for the new save files.

2021-06-23 16:15 UTC, oleg-derevenetz commented on src/fheroes2/game/game_io.cpp
> +    conf.SetMapsFile( Settings::GetLastFile( "maps", System::GetUniversalBasename( conf.MapsFile() ) ) );
Well, we should always do the `conf.SetMapsFile( Settings::GetLastFile( "maps", ... ) ) );` part to have a full path to the map in Settings. The only part that is not needed here in case of a new save files is `System::GetUniversalBasename()` call. I don't think that it will waste so many resources, but, if you wish, I can add the check for it.

2021-06-23 16:16 UTC, ihhub commented on src/fheroes2/game/game_io.cpp
> +    conf.SetMapsFile( Settings::GetLastFile( "maps", System::GetUniversalBasename( conf.MapsFile() ) ) );
That's fine. Let's leave it as it is. I'll merge this pull request.

2021-06-23 16:17 UTC, merged

2021-06-23 16:18 UTC, ihhub commented
@oleg-derevenetz , thank you so much for fixing this issue!