Remove static game data from save files
ihhub/fheroes2 pull request #3727
Opened 2021-06-20 09:43 UTC by ihhub

plus few code corrections to remove compilation warnings

2021-06-20 11:18 UTC, oleg-derevenetz requested changes
Hi @ihhub I left one suggestion and one question here, would you mind taking a look?

2021-06-20 11:18 UTC, oleg-derevenetz commented on src/fheroes2/monster/monster.cpp
> +    const payment_t pay = id != upgr.id ? upgr.GetCost() - GetCost() : GetCost();
I think we can just `return id != upgr.id ? upgr.GetCost() - GetCost() : GetCost();` here.

2021-06-20 11:18 UTC, oleg-derevenetz commented on src/fheroes2/system/save_format_version.h
> +#define FORMAT_VERSION_PRE_095_RELEASE 9500
Why do we need a separate `FORMAT_VERSION_PRE_095_RELEASE` version?

2021-06-20 12:17 UTC, ihhub commented on src/fheroes2/system/save_format_version.h
> +#define FORMAT_VERSION_PRE_095_RELEASE 9500
Because this change was done few commits ago. We could ignore and have one but if someone has saves of this release version they're screwed.

2021-06-20 12:17 UTC, ihhub commented on src/fheroes2/monster/monster.cpp
> +    const payment_t pay = id != upgr.id ? upgr.GetCost() - GetCost() : GetCost();
Good point!

2021-06-20 14:07 UTC, oleg-derevenetz commented on src/fheroes2/system/save_format_version.h
> +#define FORMAT_VERSION_PRE_095_RELEASE 9500
Ah, yes, really.

2021-06-21 10:48 UTC, qarkai commented on src/fheroes2/heroes/heroes_spell.cpp
> +    const u32 distance = Spell::CalculateDimensionDoorDistance();
```suggestion
    constexpr u32 distance = Spell::CalculateDimensionDoorDistance();
```

2021-06-21 10:48 UTC, qarkai commented on src/fheroes2/spell/spell.cpp
> +u32 Spell::CalculateDimensionDoorDistance()
```suggestion
constexpr u32 Spell::CalculateDimensionDoorDistance()
```

2021-06-21 10:49 UTC, qarkai commented on src/fheroes2/spell/spell.h
> +    static u32 CalculateDimensionDoorDistance();
```suggestion
    static constexpr u32 CalculateDimensionDoorDistance();
```

2021-06-21 11:15 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> +    const u32 distance = Spell::CalculateDimensionDoorDistance();
Hi @qarkai , compiler will opimize the call without this magical keyword :)

2021-06-21 11:15 UTC, merged