Remove ARRAY_COUNT macro
ihhub/fheroes2 pull request #3735
Opened 2021-06-21 14:18 UTC by qarkai

Use std::array, range-based for and algorithms.
Also remove now unused headers.

2021-06-22 11:59 UTC, shprotru commented
Greetings, @qarkai, please, use `uint32_t` instead of `u32` and `uint8_t` instead of `u8`.

2021-06-22 12:10 UTC, qarkai commented
Hi @shprotru I'll do. Is it worth replacing all aliases from `types.h` in separate PR?

2021-06-22 12:21 UTC, qarkai commented
> use `uint32_t` instead of `u32` and `uint8_t` instead of `u8`.

What about `int32_t` instead of `s32`?

2021-06-22 13:06 UTC, shprotru commented
> > use `uint32_t` instead of `u32` and `uint8_t` instead of `u8`.
> 
> What about `int32_t` instead of `s32`?

That would be fine

2021-06-23 16:25 UTC, ihhub requested changes
Hi @qarkai , there are multiple comments. Could you please take a look and check if they're eligible?

2021-06-23 16:25 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +        for ( auto & troop : troops )
Could we please replace **auto** with **Troop**? **auto** is good for long names or iterators but having here the original class makes the code more readable for other developers.

2021-06-23 16:25 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +        for ( auto & troop : troops )
Could we please replace **auto** with **Troop**? **auto** is good for long names or iterators but having here the original class makes the code more readable for other developers.

2021-06-23 16:25 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +                               [this, &strs]( int sum, uint8_t obj ) { return sum + ObjectVisitedModifiersResult( MDF_MORALE, obj, *this, strs ); } );
Could we please write this via loop? Reading such code might be troublesome.

2021-06-23 16:25 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +                               [this, &strs]( int sum, uint8_t obj ) { return sum + ObjectVisitedModifiersResult( MDF_LUCK, obj, *this, strs ); } );
Could we please write this via loop? Reading such code might be troublesome.

2021-06-23 16:25 UTC, ihhub commented on src/fheroes2/heroes/heroes_base.cpp
> +    return std::accumulate( arts, std::end( arts ), 0, [&base, &strs]( int sum, uint8_t art ) { return sum + ArtifactModifiersResult( MDF_ATTACK, art, base, strs ); } );
Could we please write this via loop? Reading such code might be troublesome.

2021-06-23 16:25 UTC, ihhub commented on src/fheroes2/heroes/heroes_base.cpp
> +    return std::accumulate( arts, std::end( arts ), 0, [&base, &strs]( int sum, uint8_t art ) { return sum + ArtifactModifiersResult( MDF_DEFENSE, art, base, strs ); } );
Could we please write this via loop? Reading such code might be troublesome.

2021-06-23 16:25 UTC, ihhub commented on src/fheroes2/heroes/heroes_base.cpp
> +    return std::accumulate( arts, std::end( arts ), 0, [&base, &strs]( int sum, uint8_t art ) { return sum + ArtifactModifiersResult( MDF_POWER, art, base, strs ); } );
Could we please write this via loop? Reading such code might be troublesome.

2021-06-23 16:25 UTC, ihhub commented on src/fheroes2/heroes/heroes_base.cpp
> +                            [&base, &strs]( int sum, uint8_t art ) { return sum + ArtifactModifiersResult( MDF_KNOWLEDGE, art, base, strs ); } );
Could we please write this via loop? Reading such code might be troublesome.

2021-06-23 16:25 UTC, ihhub commented on src/fheroes2/heroes/heroes_base.cpp
> +    return std::accumulate( arts, std::end( arts ), 0, [&base, &strs]( int sum, uint8_t art ) { return sum + ArtifactModifiersResult( MDF_MORALE, art, base, strs ); } );
Could we please write this via loop? Reading such code might be troublesome.

2021-06-23 16:25 UTC, ihhub commented on src/fheroes2/heroes/heroes_base.cpp
> +    return std::accumulate( arts, std::end( arts ), 0, [&base, &strs]( int sum, uint8_t art ) { return sum + ArtifactModifiersResult( MDF_LUCK, art, base, strs ); } );
Could we please write this via loop? Reading such code might be troublesome.

2021-06-23 17:12 UTC, qarkai commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +    std::array<char, 20> shortTime;
How do I access underlying char pointer for std::strftime?

2021-06-23 17:15 UTC, qarkai commented on src/fheroes2/castle/castle.cpp
> +        for ( auto & troop : troops )
`auto` is good for deducing types.

2021-06-23 17:17 UTC, qarkai commented on src/fheroes2/heroes/heroes.cpp
> +        for ( auto & troop : troops )
No need to repeat the very same explanation. It's annoying.

2021-06-23 17:17 UTC, qarkai commented on src/fheroes2/heroes/heroes.cpp
> +                               [this, &strs]( int sum, uint8_t obj ) { return sum + ObjectVisitedModifiersResult( MDF_LUCK, obj, *this, strs ); } );
Again.

2021-06-23 17:17 UTC, qarkai commented on src/fheroes2/heroes/heroes_base.cpp
> +    return std::accumulate( arts, std::end( arts ), 0, [&base, &strs]( int sum, uint8_t art ) { return sum + ArtifactModifiersResult( MDF_ATTACK, art, base, strs ); } );
And again.

2021-06-24 00:52 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +        for ( auto & troop : troops )
Hi @qarkai , I did this because some developers miss places if not explicitly highlight. My apologies if it felt annoying. I'll try to reduce the amount of comments for the same issue.

2021-06-24 07:32 UTC, oleg-derevenetz commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +    std::strftime( &shortDate[0], shortDate.size() - 1, "%b %d,", std::localtime( &timeval ) );
Well, first of all, `strftime()` may fail (for example, even abbreviated month name in some locale may exceed 20 characters, theoretically), and in this case buffer contents will be undefined (under "undefined" I mean UB in the case if underlying implementation of `std::string` counts on some rules regarding its content - for example, on the fact that it is always will be null-terminated).

Second, after this call string length will be still 20 characters, so even if we are 100% sure that [first of all] will never ever happen, should at least call `resize()` with an argument set to the value returned by `strftime()` (the number of bytes written into the buffer not including the terminating 0).

In general, well, yeah, `std::string` really doesn't fit well for this purpose. Raw character array is more safer here.

2021-06-28 13:28 UTC, merged

2021-06-28 13:28 UTC, ihhub commented
@qarkai , thanks a lot for this change!