I2809 continuous scrollbar v2
ihhub/fheroes2 pull request #3741
Opened 2021-06-22 00:32 UTC by felix642

fix #2809

Hi @ihhub, here's a new version for the continuous scrollbar. I only implemented it in the marketplace since I wanted your opinion before adding it everywhere. 
If you accept this version I'll add it everywhere.

2021-06-22 14:57 UTC, ihhub requested changes
Hi @felix642 , I left my suggestion about this approach. Could you please take a look?

2021-06-22 14:57 UTC, ihhub commented on src/fheroes2/gui/ui_button.cpp
> +    }
Hi @felix642 , I'm thinking that we might need to just create even more generic class which will accept `std::function<bool()>` in it's constructor. In this case we will move the new class into `ui_tool.h/cpp` files and name it something more generic. This is due to a fact that it's not exactly a button and it does nothing with button except checking its status.

One of the names which comes into my mind suitable for the new class is **UITimer** but still it's not the good one.

2021-06-22 14:57 UTC, ihhub commented on src/fheroes2/gui/ui_button.h
> +        explicit ContinuousButton( Button & button, const uint64_t delay, const uint64_t originalDelay );
It's no obvios what `delay` and `originalDelay` stand for.

2021-06-22 14:58 UTC, ihhub commented on src/fheroes2/gui/ui_button.cpp
> +    }
Moving forward with the idea: to pass the function we could use lambda-function wrapper for this. For example:
`[](_button)( return _button.isPressed() )`.

2021-06-23 01:56 UTC, felix642 commented on src/fheroes2/gui/ui_button.cpp
> +    }
Hi @ihhub I really appreciate the feedback that you give me! If we make an abstraction of the horrible names I gave to my variables, I tried a 3rd implementation of the continuous scrollbar and I would like to know if this one works for you. If it does, I'm going to rename the objects / variables and implement it pretty much everywhere in the code.

2021-06-23 04:23 UTC, ihhub commented on src/fheroes2/gui/ui_button.cpp
> +    }
Hi @felix642 , looks good so far. Please make each member of the class at separate line. We need to find better names for the class and methods :( I'll think about them as well. How about `TimedEventValidator`?

Also one issue which is not addressed is that we don't have feedback from the button object to reset the status of UITimer object. We're doing the check in the loop but it doesn't guarantee that we might have release and press again events in between. A good thing is that we have `ActionObject` as a base class which has such connection. So might need to derive our new class from it. To make the code cleaner could we please create a new file called `ui_base.h` and `ui_base.cpp` where we move `ActionObject` class. In this case it could be used not only for buttons.

What do you think?

2021-06-24 14:36 UTC, felix642 commented on src/fheroes2/gui/ui_button.cpp
> +    }
Hi @ihhub,
I think this is a good idea! I have made the required changes and everything seems to be working perfectly. I think there is still some job to do on the variables names but at least we have a good version I think. If it is ok for you I'll start implementing it pretty much everywhere in the code.

2021-06-24 14:55 UTC, ihhub requested changes
Hi @felix642 , I left few comments but the rest looks good. Please proceed with the rest of the implementation.

2021-06-24 14:55 UTC, ihhub commented on src/fheroes2/gui/ui_base.cpp
> +}
Please add an empty line at the end of the file.

2021-06-24 14:55 UTC, ihhub commented on src/fheroes2/gui/ui_base.h
> +}
Please add an empty line at the end of the file.

2021-06-24 14:55 UTC, ihhub commented on src/fheroes2/gui/ui_tool.cpp
> +        if ( _delayBeforeFirstUpdate.isPassed() && _comparator() && _delayBetweenUpdate.isPassed() ) {
Just for code consistency: please put `_comparator()` as the last check.

2021-06-24 14:55 UTC, ihhub commented on src/fheroes2/gui/ui_tool.h
> +        explicit TimedEventValidator( std::function<bool()> comparator, const uint64_t delayBetweenUpdate, const uint64_t delayBeforeFirstUpdate );
A small correction: please swap `delayBetweenUpdate` and `delayBeforeFirstUpdate` so logically it would be easier to understand.

2021-06-28 14:58 UTC, ihhub commented
Hi @felix642 , could you please fix Visual studio builds?

2021-06-28 14:59 UTC, ihhub commented
> Hi @felix642 , could you please fix Visual studio builds?

To do this you have to manually modify `fheroes2-vs2019.vcxproj` and `fheroes2-vs2015.vcxproj` files to include newly added files.

2021-06-30 15:07 UTC, ihhub requested changes
Hi @felix642 , I left few comments regarding code styling. Could you please take a look?

2021-06-30 15:07 UTC, ihhub commented on src/fheroes2/gui/ui_tool.h
> +                                      const uint64_t delayBetweenUpdate = DELAY_BETWEEN_UPDATES );
Please rename these variables into: `verification` (or `validation`), `delayBeforeFirstUpdateMs` and `delayBetweenUpdateMs`. **comparator** doesn't actually compare anything.
Also please assign values directly without `constexpr` usage.

2021-06-30 15:07 UTC, ihhub commented on src/fheroes2/gui/ui_tool.h
> +        bool isActiveForLongEnough();
How about `isDelayPassed`?

2021-06-30 15:07 UTC, ihhub commented on src/fheroes2/gui/ui_tool.h
> +                                      const uint64_t delayBetweenUpdate = DELAY_BETWEEN_UPDATES );
The same variable naming applies to the members of the class.

2021-06-30 15:08 UTC, ihhub commented
Hi @Branikolog , could you please verify these changes?

2021-07-01 12:35 UTC, Branikolog commented
Hello, @ihhub 
I've noticed, that holding of buttons switching heroes don't work at all. While we can scroll castles and towns by holding similar buttons in a corner parts of interface.
![image](https://user-images.githubusercontent.com/55348946/124125149-f3bfc600-da81-11eb-9682-f3bfcf6571bb.png)

2021-07-01 14:08 UTC, ihhub commented
Hi @Branikolog , it wasn't simply implemented.

@felix642 , could you please add the functionality to hero's screen as well?

2021-07-03 02:18 UTC, felix642 commented
> Hi @Branikolog , it wasn't simply implemented.
> 
> @felix642 , could you please add the functionality to hero's screen as well?

I'm having a bit of trouble with this dialog. I will try to implement it in a day or two!

2021-07-03 10:29 UTC, ihhub commented
Hi @felix642 , to fix this please change line 211 in heroes_dialog.cpp file to `LocalEvent & le = LocalEvent::Get();`. However, this change will cause #486 appear again. To avoid such please call `LocalEvent::GetClean()` before any call of **OpenDialog()** method for heroes.

2021-07-03 10:32 UTC, ihhub requested changes
Hi @felix642 , we're almost there! I left few more comments and proposed the way how we could fix hero's dialog. Could you please take a look?

2021-07-03 10:32 UTC, ihhub commented on src/fheroes2/heroes/heroes.h
> +#include "ui_button.h"
Do we need changes in this file? If not please revert them.

2021-07-03 10:32 UTC, ihhub commented on src/fheroes2/heroes/heroes_dialog.cpp
> +static fheroes2::Button buttonPrevHero( 0, 0, ICN::HSBTNS, 4, 5 );
Please revert these changes. I proposed better solution to avoid such tricks.

2021-07-04 02:40 UTC, felix642 commented
> Hi @felix642 , we're almost there! I left few more comments and proposed the way how we could fix hero's dialog. Could you please take a look?

Hi @ihhub, thanks for the help! I made the required changes. The branch should now be ready to merge unless you need me to change something else.

2021-07-04 05:53 UTC, merged

2021-07-04 05:53 UTC, ihhub commented
@felix642 , thank you so much for improving this feature!