Improve the INSTALL.md structure
ihhub/fheroes2 pull request #3749
Opened 2021-06-23 20:22 UTC by oleg-derevenetz

Discussed in #3738. @Branikolog, you can see web version with changes from this PR here:

https://oleg-derevenetz.github.io/fheroes2/

2021-06-24 10:12 UTC, ihhub commented
Hi @oleg-derevenetz , since we're touching md files could you please remove **maintainability**, **reliability** and **code quality: c/c++** banners. After all our goal is to have absolute zero of issues in the code so these values don't give us any proper information. What do you think?

2021-06-24 11:10 UTC, oleg-derevenetz commented
Hi @ihhub

> since we're touching md files could you please remove **maintainability**, **reliability** and **code quality: c/c++** banners. After all our goal is to have absolute zero of issues in the code so these values don't give us any proper information. What do you think?

Well, I have no objections, I'll do this later today. I'm thinking about creating a separate README.md in /doc anyway (for the website), but I'm not sure about the content for it. I'll make a basic skeleton of the new website and README.md in the project root (for GitHub) tonight and you will be able to take a look and suggest a content.

2021-07-04 06:03 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left multiple comments here. Could you please check them as first priority?

2021-07-04 09:20 UTC, oleg-derevenetz commented on _config.yml
> -theme: jekyll-theme-merlot
Hi @ihhub because I (personally) think that without styling at all website looks better than with default Merlot theme :) But it's debatable of course.

2021-07-04 09:41 UTC, oleg-derevenetz commented on docs/INSTALL.md
> +# fheroes2 installation guide
@ihhub because, well, I don't know how to do it exactly :) README_PSV describe this as follows: "Install fheroes2.vpk to your Vita", that's all. Also, as far as I understand, you can't do in on any Vita, you should somehow unlock it first. So I omitted Vita by now.

2021-07-04 09:46 UTC, ihhub commented on docs/INSTALL.md
> +# fheroes2 installation guide
A valid point.

2021-07-04 09:47 UTC, ihhub commented on _config.yml
> -theme: jekyll-theme-merlot
Let's keep it as before for now please. We could make voting for the look of website :)

2021-07-04 10:35 UTC, oleg-derevenetz commented on _config.yml
> -theme: jekyll-theme-merlot
@ihhub Ah, I forgot one more thing: without the Merlot theme, there are automatic links to the main page of the website, while with Merlot there are none. So I added these links manually in a separate commit.

2021-07-04 12:10 UTC, merged

2021-07-04 12:11 UTC, ihhub commented
@oleg-derevenetz , enormous thanks for improving our website!

2021-07-04 12:19 UTC, ihhub commented
Hm... Looks like GitHub neeeds `_config.yml` to be present in the root.

2021-07-04 12:21 UTC, oleg-derevenetz commented
Hi @ihhub

> Hm... Looks like GitHub neeeds `_config.yml` to be present in the root.

Website looks OK to me now.

2021-07-04 12:22 UTC, ihhub commented
Ah, okay. For me it looks good too. Maybe my browser caching :(