Settings cleanup
ihhub/fheroes2 pull request #3759
Opened 2021-06-26 23:10 UTC by oleg-derevenetz

Cleanup settings a bit:

* Remove deprecated "use alternative resources", "use swsurface only" and "videodriver" settings;
* Remove timidity support (was useful with `WITHOUT_MIXER`, which is no longer supported);
* Use single setting "sound" (`Settings::Sound()`) to enable and disable all sound in the app instead of combination of `Settings::Sound()` and `Settings::Music()` (the latter wasn't configured correctly via config file anyway).

2021-06-30 15:28 UTC, ihhub commented
Hi @oleg-derevenetz , why do we have a single option for sounds and music as these two are independent?

2021-06-30 15:32 UTC, oleg-derevenetz commented
Hi @ihhub these options were like "emergency switch" if there are some issues with mixer - if it wasn't able to be initialized. I don't see why we should have two emergency switches in this case :) Especially given that music-related was never properly initialized via the config file.

2021-06-30 15:59 UTC, oleg-derevenetz commented
@ihhub May be just not save and read it to/from config file at all?

2021-07-01 14:29 UTC, ihhub commented
Hi @oleg-derevenetz , now I got what you meant. I thought it's in-game music and sound volumes but it's overall enabling/disable option. Let's remove. I can't even think of any useful case / operating system when we don't need to have sounds.

2021-07-01 14:41 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left few comments related to Network. My main cocern is that we don't need to remove any logic related to it except SDL_NET as we're going to add this support in the future.

2021-07-01 14:41 UTC, ihhub commented on src/fheroes2/game/game_newgame.cpp
> -#ifdef NETWORK_ENABLE
Let's just remove this guard but have this code since we're going to add network support. Right now the button isn't even rendered so it's safe to do such.

2021-07-01 15:07 UTC, oleg-derevenetz commented on src/fheroes2/system/settings.cpp
> +    os << std::endl << "# sound (including music): on/off" << std::endl;
Hi @ihhub I'm thinking about removing this completely and replacing by something like `Mixer::isValid()` instead.

2021-07-04 06:01 UTC, merged

2021-07-04 06:02 UTC, ihhub commented
@oleg-derevenetz , huge thanks for cleaning up old messy code!