Check early if the kingdom is vanquished
ihhub/fheroes2 pull request #3769
Opened 2021-06-27 23:27 UTC by oleg-derevenetz

Currently, if a human player doesn't have any castles and he dismisses his last hero, his kingdom is not considered as vanquished until he ends his turn. This in itself looks weird (although it's just a cosmetic issue), but what's worse - he is able to make savefile (or autosave, if autosave is enabled at the end of the turn), and when you try to load this savefile, the application loops forever in `Interface::Basic::StartGame()`. This PR is intended to fix this.

2021-06-30 11:49 UTC, oleg-derevenetz commented
Hi @ihhub

> ihhub linked an issue that may be closed by this pull request 20 hours ago
> A message, that player was defeated, appears only after AI turn is over #2625

Unfortunately, no - at least not in all cases with current set of changes. You see, currently kingdom officially recognized as dead due to an absence of castles only in the beginning of a new day. So a new day should come, and all remaining AI players should over their turns during previous day to make it happen. Currently the "fast" way will only work if last hero was dismissed by hand. If there is no castles in the kingdom, turn will be automatically over after `ShowWarningLostTownsDialog()` call in the beginning of `HumanTurn()` and we still should wait for the new day.

2021-06-30 12:03 UTC, oleg-derevenetz commented
Hi @ihhub if you don't mind, I'd like to address an issue with message about defeat in a separate PR.

2021-06-30 14:49 UTC, ihhub commented
> Hi @ihhub if you don't mind, I'd like to address an issue with message about defeat in a separate PR.

Hi @oleg-derevenetz , no issues. I thought we're going to fix it here but it's fine to do it in a separate pull request.

2021-06-30 15:14 UTC, oleg-derevenetz commented
Hi @ihhub I'll take a look into this issue tonight and, if I will have a fix, I may add it to this PR.

2021-06-30 15:15 UTC, ihhub commented
Hi @oleg-derevenetz , sure! Please also take a note that we have 3-4 days before the release so we should have time to review and test the code.

2021-06-30 21:32 UTC, oleg-derevenetz commented
Hi @ihhub Yes, you're right, this PR should fix #2625 :)

2021-06-30 22:14 UTC, oleg-derevenetz commented
Hi @ihhub @Branikolog I came to the conclusion that current vanquish logic (due to countdown of days since last town was lost) is wrong (related to #2909), and, moreover, it's wrong in OG as well.

Currently in OG, if I start a single-player game with zero towns, the first day isn't counted in a countdown (it begins only from second day), however, if I start a multiplayer game in OG, and player with zero towns isn't the first player in a row, then countdown for him starts from the first day.

Also, currently in fheroes2 in multiplayer mode, if blue player (first in a row) captures the last town of a, say, red player (third in a row), then when red player gets a turn, then countdown timer for him is already started. I believe it's not fair, because it's the same day, and not a new one, and countdown timer should start only on a new day.

So in this PR I propose the following logic:

* If player starts with zero castles, first day isn't counted - neither in single-player mode, nor in multiplayer;
* If player loses his last town, because some previous player in a row captured his town **_on the same turn_**, then player gets just a warning when he presses "end turn" (if he doesn't captured any town on the same turn), and countdown timer starts from the next turn.

I attached ZIP file with custom map (slightly changed map from #2909 to allow the human player to choose red color and to allow multiplayer mode) and savefile from Slugfest (in hotseat, blue player is ready to capture the red's player castle) to illustrate my proposal.

[proposal.zip](https://github.com/ihhub/fheroes2/files/6744294/proposal.zip)

2021-07-02 20:36 UTC, oleg-derevenetz commented
Just found & fixed one more issue - wrong information is displayed in a loss dialog if map have WINS_SIDE or LOSS_STARTHERO conditions, and human player loses during an AI turn... I think it's better to postpone this PR until 0.9.5 will be released - not so many changes, but they are all subtle.

2021-07-04 16:04 UTC, ihhub commented
Hi @oleg-derevenetz , is this pull request ready for review?

2021-07-04 16:08 UTC, oleg-derevenetz commented
Hi @ihhub in general - yes, but I have some doubts regarding vanquish logic, please see my comment here addressed to you and Branikolog.

2021-07-06 05:12 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left few comments. Also regarding the explanation of countdown for town loss: it makes sense for me. We must have the same conditions for any type of the game.

2021-07-06 05:12 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +        }
Optional: we can remove else body here as the code will never reach this place after hitting break.

2021-07-06 05:12 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +    lost_town_days = Game::GetLostTownDays() + 1;
This is a bit confusing. Why can't we modify return value of `GetLostTownDays`?

2021-07-06 05:13 UTC, ihhub commented
Hi @Branikolog , please test this pull request as your highest priority.

2021-07-06 08:25 UTC, oleg-derevenetz commented on src/fheroes2/game/game_over.cpp
> +                        if ( Dialog::YES == Dialog::Message( "", "Do you wish to continue the game?", Font::BIG, Dialog::YES | Dialog::NO ) ) {
@ihhub Currently it is shown after "you won" message, but before the High Scores screen, so I left it as is.

2021-07-06 08:30 UTC, oleg-derevenetz commented on src/fheroes2/kingdom/kingdom.cpp
> +    lost_town_days = Game::GetLostTownDays() + 1;
@ihhub Well, because technically 7 days is the right value for it, an extra day is for that warning message "blabla, you should get the town during the next week".

2021-07-06 08:46 UTC, oleg-derevenetz commented on src/fheroes2/game/game_startgame.cpp
> +        }
@ihhub Suppose that `LocalCheckGameOver()` returns `fheroes2::GameMode::CANCEL` (as it usually do :) ). In this case we may get unexpected (here) value of `fheroes2::GameMode::CANCEL` in `res` and this may break something - for example, this may break check at line 643.

2021-07-08 12:05 UTC, Branikolog commented on src/fheroes2/kingdom/kingdom.cpp
> +    lost_town_days = Game::GetLostTownDays() + 1;
Correct me, if I'm wrong, but player cannot loose his castle during his turn... Only during enemy's turn. So the next day comes, should be considered as the first of countdown.

2021-07-08 12:09 UTC, Branikolog commented
I've noticed, that the condition of capturing a special town isn't working for AI. 
![image](https://user-images.githubusercontent.com/55348946/124919071-730f4580-dffe-11eb-9319-79e359a18221.png)

2021-07-08 12:17 UTC, oleg-derevenetz commented
@Branikolog

> I've noticed, that the condition of capturing a special town isn't working for AI.

Do you mean that this condition is not provided for AI players in the original game (so AI players are not able to win by capturing a certain town in OG)?

2021-07-08 12:31 UTC, Branikolog commented
> Do you mean that this condition is not provided for AI players in the original game (so AI players are not able to win by capturing a certain town in OG)?

In the OG we have a special box allowing AI to win the scenario by capturing a certain city. But in fheroes2, in a case the condition was set, the game continues.

2021-07-08 12:41 UTC, oleg-derevenetz commented
> In the OG we have a special box allowing AI to win the scenario by capturing a certain city. But in fheroes2, in a case the condition was set, the game continues.

Yeah, it seems that in `World::CheckKingdomLoss()` currently only checked are the `WINS_GOLD` and `WINS_ARTIFACT` conditions achieved by kingdoms, but not the `WINS_TOWN`.

2021-07-10 08:12 UTC, oleg-derevenetz commented
@Branikolog

> In the OG we have a special box allowing AI to win the scenario by capturing a certain city. But in fheroes2, in a case the condition was set, the game continues.

It seems that it's the same behavior as in OG. I managed to create a map (attached to this comment) with such a win condition, red player is able to capture target town at the first turn. If red player is controlled by human, he wins after capturing the target town. However, if red player is controlled by AI, game continues after capturing it.

[CAPTOWN.zip](https://github.com/ihhub/fheroes2/files/6794887/CAPTOWN.zip)

2021-07-10 09:31 UTC, oleg-derevenetz commented on src/fheroes2/kingdom/kingdom.cpp
> +    lost_town_days = Game::GetLostTownDays() + 1;
@Branikolog Suppose we have two human-controlled players (blue and red). The blue player has the first turn, he captures red's town on the first turn. Then the red player has its turn, but the day is still the same(!), so this day shouldn't be counted as a first day of the countdown. Only the next day should.

2021-07-10 09:41 UTC, oleg-derevenetz commented
Two more issues have been found (and hopefully fixed):

* Currently, in a single-player game, an incorrect loss message is shown if the player loses due to the `LOSS_TOWN` condition;
* Currently, in a single-player game, an incorrect loss message is shown if the player loses because the enemy wins due to the `WINS_GOLD` or `WINS_ARTIFACT` conditions.

2021-07-12 15:27 UTC, ihhub commented on src/fheroes2/game/game_over.cpp
> +            */
Shall we remove this commented code?

2021-07-12 15:50 UTC, oleg-derevenetz commented on src/fheroes2/game/game_over.cpp
> +            */
Hi @ihhub I suppose that this code may be handy for multiplayer games in future, but I'm not sure. That's why I commented it out.

2021-07-13 11:59 UTC, Branikolog commented
> > In the OG we have a special box allowing AI to win the scenario by capturing a certain city. But in fheroes2, in a case the condition was set, the game continues.
> 
> It seems that it's the same behavior as in OG. I managed to create a map (attached to this comment) with such a win condition, red player is able to capture target town at the first turn. If red player is controlled by human, he wins after capturing the target town. However, if red player is controlled by AI, game continues after capturing it.
> 
> [CAPTOWN.zip](https://github.com/ihhub/fheroes2/files/6794887/CAPTOWN.zip)

Hi, @oleg-derevenetz 

You've forgot to set a special condition for AI at your map:
![image](https://user-images.githubusercontent.com/55348946/125447515-80fe4b93-0ffe-4c12-aef0-4fcc759c9e46.png)

2021-07-13 12:43 UTC, oleg-derevenetz commented on src/fheroes2/kingdom/kingdom.cpp
> +    lost_town_days = Game::GetLostTownDays() + 1;
Hi @Branikolog

> Why can't we implement a simple check: If there's no towns belonging to current player, then counter to loss should be initiated saying, there're 7 days left.

Hmm, that's how it currently works in this PR. At the end of the day on which castle was lost player gets a warning, and on the next day countdown begins. That's how it should work. 

> 
> >Then the red player has its turn, but the day is still the same(!), so this day shouldn't be counted as a first day of the countdown. Only the next day should.
> 
> Is this a difference in countdown in a case if a player lost his castle before his first turn and the case if player starts without castles at all?

No, why there should be a difference? Currently in OG there is a difference - if player starts a single-player game without a castle, then countdown begins on the second day, but if he starts the game on the same map in multi-player, then countdown begins on the first day. I believe that this behavior is wrong, and 7-day countdown should begin always on the next day, it was already discussed in this PR.

2021-07-13 16:03 UTC, oleg-derevenetz commented
@Branikolog

> You've forgot to set a special condition for AI at your map:

Ah, it seems so. I'll check this later today then.

2021-07-14 13:20 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +        for ( Players::const_iterator it = sortedPlayers.begin(); it != sortedPlayers.end(); ++it ) {
Looks like clang-tidy doesn't really handle pointers. It should be `for (const Player * player : sortedPlayers )` but please don't change it now.

2021-07-15 15:35 UTC, ihhub approved these changes

2021-07-17 15:55 UTC, merged

2021-07-17 15:56 UTC, ihhub commented
@oleg-derevenetz , thanks a lot for these changes! I merged them because it's better to test them during gameplay.