Add morale and luck normalize functions
ihhub/fheroes2 pull request #3773
Opened 2021-06-29 15:13 UTC by qarkai

Deduplicate code.

2021-06-29 21:17 UTC, felix642 requested changes
Hi @qarkai I left 2 small comments on your pull request.

2021-06-29 21:20 UTC, felix642 commented on src/fheroes2/kingdom/luck.cpp
> +int Luck::Normalize( int luck )
The parameter luck could be const.

2021-06-29 21:20 UTC, felix642 commented on src/fheroes2/kingdom/morale.cpp
> +int Morale::Normalize( int morale )
The parameter morale could be const

2021-06-29 21:46 UTC, qarkai commented on src/fheroes2/kingdom/luck.cpp
> +int Luck::Normalize( int luck )
It could be but I don't see reason to make it const.

2021-06-30 00:50 UTC, ihhub commented on src/fheroes2/kingdom/luck.cpp
> +int Luck::Normalize( int luck )
Making const tells compiler to verify that the input argument is not modified within the function. Even from performance or logical view such change has zero impact it makes code cleaner. Also SonarQube has such checks as well but we disabled them for now.

2021-06-30 06:41 UTC, qarkai commented on src/fheroes2/kingdom/luck.cpp
> +int Luck::Normalize( int luck )
It doesn't matter if argument is modified or not since it passed by value. `const` adds noise so code is not cleaner. SonarQube doesn't follow C++ Core Guidelines in not enforcing const for function's arguments. See exception for https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rconst-immutable

2021-06-30 23:06 UTC, oleg-derevenetz commented on src/fheroes2/kingdom/luck.cpp
> +int Luck::Normalize( int luck )
Normally (in my own code) I don't use immutable parameters passed by value. However, I don't see any harm in making these parameters `const`, if this is required by code style in a particular project, because it's in fact may really help to catch a potential bug (the only exception - if this parameter undergoes some kind of "normalization" inside a function - for example, capping). C++ Core Guidelines doesn't recommend enforcing this because this may cause lots of false positives in **_existing valid code_**, but this is not related to a **_new code_**, that should follow practices adopted in a particular project.

2021-07-01 09:50 UTC, qarkai commented on src/fheroes2/kingdom/luck.cpp
> +int Luck::Normalize( int luck )
Ok, there is no conflict with code style. New code matches existing `Luck::String` and `Luck::Description` (and `Morale::*` too).
Does project have code style actually? There is no description/link in [contribution guide](https://github.com/ihhub/fheroes2/blob/master/CONTRIBUTING.md).

2021-07-01 12:14 UTC, ihhub commented on src/fheroes2/kingdom/luck.cpp
> +int Luck::Normalize( int luck )
We have code styling which locates [here](https://github.com/ihhub/fheroes2/wiki/Code-style). We just didn't have time to modify all documentation.

2021-07-01 13:50 UTC, qarkai commented on src/fheroes2/kingdom/luck.cpp
> +int Luck::Normalize( int luck )
Opened #3781.

2021-07-01 14:05 UTC, merged

2021-07-01 14:06 UTC, ihhub commented
@qarkai , thanks a lot for removing code duplication.