Castle Construction Screen, Tavern, one of the heroes available in the tavern changes every time the save file is loaded
ihhub/fheroes2 pull request #3800
Opened 2021-07-04 20:00 UTC by felix642

fix #3374

2021-07-05 01:40 UTC, ihhub requested changes
Hi @felix642 , I left few comments. Could you please take a look?

2021-07-05 01:40 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +        Kingdom * kingdom = &world.GetKingdom( kingdomColor );
Why do we getting an address of a reference and then check if the pointer is not null?

2021-07-05 01:40 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +    const Colors colors( Color::ALL );
Please check Player namespace. There was a function to return colors present in the current game.

2021-07-05 02:27 UTC, felix642 commented on src/fheroes2/castle/castle.cpp
> +        Kingdom * kingdom = &world.GetKingdom( kingdomColor );
That's a good question. I changed it.

2021-07-17 16:12 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +    // actually update available heroes to recruit
Hi @felix642 , could you please explain the logic of the fix and it's hard to understand why we do this?

2021-07-25 14:54 UTC, felix642 commented on src/fheroes2/castle/castle.cpp
> +    // actually update available heroes to recruit
HI @ihhub sorry for the late reply.
The current logic implemented right now is that whenever somebody buys a new hero, we update the heroes for this particular player.
The problem with that is that many players can have the same hero available in their castle. Which means that if someone buys a hero other players might have an "invalid" hero in their castle. The way the game handle this case is that whenever the player open his castle, the current available heroes are check and reset if needed. 
But, this could lead to situations like #3374. Since the current hero is "invalid", we update it whenever the castle is open.
So what I did to fix this issue is that whenever a player buys a hero, we update the heroes for every players (updating meaning that we check the state of the available heroes and if they are invalid we reset them)

2021-08-01 05:36 UTC, merged

2021-08-01 05:36 UTC, ihhub commented
@felix642 , a bunch of thanks for fixing this issue!