Add 500 EP for conquering a town regardless of defending hero existence
ihhub/fheroes2 pull request #3837
Opened 2021-07-12 16:32 UTC by qarkai

Doesn't summarize with bonus for defeating hero.
Fixes #3833.

2021-07-12 18:41 UTC, oleg-derevenetz requested changes
Hi @qarkai I just left a comment regarding village case, please take a look when it is convenient for you.

2021-07-12 18:41 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_arena.cpp
> +        if ( ( castle || army2->GetCommander() ) && !( result_game.army2 & ( RESULT_RETREAT | RESULT_SURRENDER ) ) ) {
I just checked the OG and it seems that hero gains additional 500 XP even if he captured a village (without a defending hero). So this additional check for `castle` is not enough, because in the `Battle::Arena::Arena()` constructor `castle` is reset to `nullptr` if the battle takes place in the village.

2021-07-12 18:46 UTC, qarkai commented on src/fheroes2/battle/battle_arena.cpp
> +        if ( ( castle || army2->GetCommander() ) && !( result_game.army2 & ( RESULT_RETREAT | RESULT_SURRENDER ) ) ) {
Thank you for checking. This won't work then.

2021-07-13 12:40 UTC, ihhub approved these changes

2021-07-13 16:03 UTC, merged

2021-07-13 16:03 UTC, ihhub commented
@qarkai , a bunch of thanks for fixing this logic!