Update ru/fr translations and the Makefile
ihhub/fheroes2 pull request #3838
Opened 2021-07-12 19:31 UTC by dimag0g

I've finished my work on RU/FR translations. It's far from perfect, but at least there are no untranslated strings now. I'll be happy to apply changes affecting many strings, especially concerning rules of thumb listed below. Fixing individual strings should IMO be done by subsequent pull requests which don't modify half of the file and are easily mergeable.

I have tried to follow these rules, at least for new translations:

- specific names (buildings/items/spells/etc.) should be exactly as in official games. I used GoG version for French and Buka version for Russian.
- Longer sentences should not be copied (to avoid copyright issues). I mostly used Deepl with a manual check for gender / plural form issues, especially around variables. Specific names in longer strings should still be consistent with the rest of the game.
- In languages featuring formal tone (e.g. polite "you" vs. familiar "you"), the game should address the player in formal tone, and so should his in-game subjects. Independent characters (seers, witches, etc.) should use informal tone when implied by context (e.g. "you already know everything, now get out of my house" looks awkward with polite "you").
- In order to fit translated text on in-game controls, re-phrasing was preferred to shortening.
- The character set of the translation should not be altered to be more compatible with a given game version (e.g replacing `Ä` with `A` because `Ä` is missing in the in-game font). This should be done via the Makefile.

Speaking of the Makefile, I made some changes there too, hopefully the comments explain them well enough.

2021-07-13 12:24 UTC, ihhub commented
Hi @LeHerosInconnu and @Branikolog , could you please verify French and Russian translations? Please comment directly in this pull request if any mistake is found.

2021-07-14 07:04 UTC, dimag0g commented
@Branikolog At this stage I would be especially interested in recurring issues which affect many translated items, perhaps even across different languages.

2021-07-14 17:35 UTC, LeHerosInconnu commented
Hello @ihhub,

> Hi @LeHerosInconnu and @Branikolog , could you please verify French and Russian translations? Please comment directly in this pull request if any mistake is found.

I am very busy at the moment and will be for some time.
I will try to see with a person, if he could take care of it. :)

2021-07-15 14:57 UTC, ihhub requested changes
Hi @dimag0g , I left few comments regarding the copyright while we are still waiting to review translation. Would you mind to take a look?

2021-07-15 14:57 UTC, ihhub commented on files/lang/ru.po
> +# dimag0g <dmitry.grigoryev@outlook.com>, 2021.
Please put this line before the lines 5-6 lines and change it to non-personalized statement as none of our files has it:
```
fheroes2 team <fhomm2@gmail.com>, 2021
```

2021-07-15 14:57 UTC, ihhub commented on files/lang/ru.po
> +"Last-Translator: dimag0g <dmitry.grigoryev@outlook.com>\n"
Please change it to non-personalized statement as none of our files has it:
```
fheroes2 team <fhomm2@gmail.com>
```

2021-07-15 14:57 UTC, ihhub commented on files/lang/fr.po
> +# dimag0g <dmitry.grigoryev@outlook.com>, 2021.
Please change it to non-personalized statement as none of our files has it:
```
fheroes2 team <fhomm2@gmail.com>, 2021
```

2021-07-15 14:57 UTC, ihhub commented on files/lang/fr.po
> +"Last-Translator: dimag0g <dmitry.grigoryev@outlook.com>\n"
Please change it to non-personalized statement as none of our files has it:
```
fheroes2 team <fhomm2@gmail.com>
```

2021-07-15 15:00 UTC, ihhub commented on files/lang/ru.po
> +# dimag0g <dmitry.grigoryev@outlook.com>, 2021.
Sample of the same copyright statement can be found [here](https://github.com/ihhub/fheroes2/search?q=fhomm2%40gmail.com).

2021-07-15 22:01 UTC, dimag0g commented on files/lang/fr.po
> +"Last-Translator: dimag0g <dmitry.grigoryev@outlook.com>\n"
Hi @ihhub, I have put the fix in a separate commit.

2021-07-16 00:39 UTC, ihhub commented on files/lang/fr.po
> +"Last-Translator: dimag0g <dmitry.grigoryev@outlook.com>\n"
Thank you!

2021-07-16 00:40 UTC, ihhub approved these changes

2021-07-16 09:04 UTC, undef21 reviewed
Hello @dimag0g. Could you please look at comments&

2021-07-17 07:31 UTC, dimag0g commented on files/lang/ru.po
> +msgstr "Фантом уничтожен!"
The spell is called "Фантом" in Buka version. The mirrored troops are called "Фантом", "Фантом воина" or "Призрачный отряд" in different parts of the game.  I personally prefer "Фантомный отряд" everywhere, which doesn't imply singular as "Фантом воина" does, yet shows clear relation to the spell by using the same terminology.

2021-07-17 07:32 UTC, dimag0g commented on files/lang/ru.po
> +msgstr "Магия в авто-битве"
Will use "автобитва" everywhere.

2021-07-17 07:35 UTC, dimag0g commented on files/lang/ru.po
> +msgstr "Остановить Авто-Битву?"
Will use "автобитва", no caps. Note that I still plan to capitalize in-game terms where the English text uses caps, such as "Logistics" -> "Логистика".

2021-07-17 07:35 UTC, dimag0g commented on files/lang/ru.po
> +msgstr "Верните замок Ivory Gates, который пал из-за предательства."
Good catch, thanks!

2021-07-17 07:39 UTC, dimag0g commented on files/lang/ru.po
> +msgstr "Медаль за Отвагу"
This is clearly me using auto-translation carelessly, which copy-pasted the "Medal of Courage" translation in every short string with "Medal". It should be "Символ неудачи" as far as I can tell.

2021-07-17 07:44 UTC, dimag0g commented on files/lang/ru.po
> +msgstr "Тень-курсор"
I really need help here. It's not really "Тень курсора" which is "Cursor shadow", as in the cursor casting a shadow of itself. Instead it's a cursor which looks like a shadow on the selected battlefield case, am I right? I'm open to suggestions, but I would really prefer my "Тень-курсор" -> "Shadow-cursor" to "Тень курсора" -> "Cursor shadow".

2021-07-17 07:52 UTC, dimag0g commented on files/lang/ru.po
> +msgstr "Выкл"
I personally don't feel that such an obvious abbreviation needs a dot, pretty much like I prefer "OK" and "USS" to "O.K." and "U.S.S." in English. I'll use "Выкл." nevertheless, to mimic the "Buka" translation.

2021-07-17 15:53 UTC, merged

2021-07-17 15:54 UTC, ihhub commented
@dimag0g , thanks a lot for these changes!

We'll still polish all translations but for now we have to make them work :)

2021-07-18 12:10 UTC, 1GodRage commented
Most of French original names & texts from French H2 Deluxe version can be found on this fansite:
http://homm2.free.fr/enroth.php?p=artefacts&lang=fr

2021-07-18 16:41 UTC, LeHerosInconnu commented
Hello @1GodRage,

> Most of French original names & texts from French H2 Deluxe version can be found on this fansite:
> http://homm2.free.fr/enroth.php?p=artefacts&lang=fr

Thanks for your help. :)
I sent you a private message on https://heroes2.forumactif.com/ about a problem with your link.

2021-07-18 16:47 UTC, 1GodRage commented
With pleasure. I fixed the link. :) @LeHerosInconnu 

I tried many times to participate to "git" projects over the last few years... And something doesn't work in my brain. xD
So the only "real" help I can provide, is to share my website. xD

2021-07-19 19:51 UTC, dimag0g commented
@1GodRage, Thanks, I'll take a look at your site next time I polish the French translation. Working on German version now.
For now I mostly used the output of `strings HEROES2W.EXE` to find out the proper names of artifacts, spells etc.