Make AI to use Lich's ability properly
ihhub/fheroes2 pull request #3856
Opened 2021-07-14 16:10 UTC by ihhub

relates to #3498

2021-07-14 16:52 UTC, idshibanov requested changes

2021-07-14 16:52 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +                            attackPriority += monster->GetScoreQuality( currentUnit );
I believe GetScoreQuality() doesn't check if monster is friendly or not. Subtract the value in that case.

2021-07-15 10:11 UTC, shprotru commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +                            attackPriority += monster->GetScoreQuality( currentUnit );
@idshibanov additionaly, it should take into account this case: AI army is surround only one squad of enemy titans, what should do lich in that case? shoot or going on foot in hand to hand. Anyway, this case should not cause the program to hang.

2021-07-15 14:44 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +                            attackPriority += monster->GetScoreQuality( currentUnit );
@idshibanov , this method returns negative values:
```
    // Negative value of units that changed the side
    if ( attacker.Modes( SP_BERSERKER ) || attacker.Modes( SP_HYPNOTIZE ) ) {
        attackerThreat *= -1;
    }
    // Otherwise heavy penalty for hiting our own units
    else if ( attacker.GetArmyColor() == defender.GetArmyColor() ) {
        attackerThreat *= -2;
    }
    // Finally ignore disabled units (if belong to the enemy)
    else if ( attacker.Modes( SP_BLIND ) || attacker.Modes( IS_PARALYZE_MAGIC ) ) {
        attackerThreat = 0;
    }
```

2021-07-17 15:19 UTC, idshibanov approved these changes

2021-07-17 15:20 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +                            attackPriority += monster->GetScoreQuality( currentUnit );
Okay, my mistake then :)

2021-07-17 15:55 UTC, merged