Build .mo files in CI pipelines
ihhub/fheroes2 pull request #3864
Opened 2021-07-15 23:19 UTC by oleg-derevenetz

Related to #3844

2021-07-16 00:53 UTC, oleg-derevenetz commented
OK, here is a list of what DOES WORK at the moment:

* `.mo` files are created and added to ZIP archives in all pipelines (including Linux, macOS and Windows).

Here is a list of what DOESN'T WORK yet:

* I was forced to use `.po` files and `Makefile` from #3838 by @dimag0g because many of current `.po` files looks invalid;
* Even so, I was unable to build `.mo` from `es.po` and `pl.po`, so I removed them so far (this may be reverted, but it breaks the build);
* I was forced to introduce a few changes in `Makefile` from #3838 due to portability issues;
* `.mo` files are not yet included in the installer packages created by the Inno Setup.

The names of commits associated with changes from #3838 begin with "!".

2021-07-17 15:52 UTC, ihhub requested changes

2021-07-17 15:52 UTC, ihhub commented on files/lang/Makefile
> +%.mo: %.po
Let's please not to remove existing translation files but instead of *.po we should specify explicitly which languages we want to translate. I know that this is a hacky way to do the things right but for example Polish language is present in GoG version.
Also before doing this let me please merge the pull request for French and Russian languages.

2021-07-17 16:04 UTC, ihhub commented
Hi @oleg-derevenetz , could you please rebase your branch from master?

2021-07-17 19:34 UTC, oleg-derevenetz commented
Hi @ihhub

> Hi @oleg-derevenetz , could you please rebase your branch from master?

Done. Regarding invalid `es.po` and `pl.po`, I just renamed them so far instead of making separate targets in `Makefile`. Once they will be ready, we can always rename them back.

2021-07-18 01:49 UTC, merged

2021-07-18 01:50 UTC, ihhub commented
@oleg-derevenetz , excellent work!

2022-06-03 06:38 UTC, undef21 commented on files/lang/Makefile
> +	LANG=ru_RU.CP1251 LC_ALL=ru_RU.CP1251 LC_CTYPE=ru_RU.CP1251 sed -e 's/UTF-8/CP1251/' $<.tmp > $<.2.tmp
@oleg-derevenetz could you explain what issue this line fixed, please?

2022-06-03 07:24 UTC, oleg-derevenetz commented on files/lang/Makefile
> +	LANG=ru_RU.CP1251 LC_ALL=ru_RU.CP1251 LC_CTYPE=ru_RU.CP1251 sed -e 's/UTF-8/CP1251/' $<.tmp > $<.2.tmp
@undef21 on some systems (at least on macOS, may be on some others) `sed` should know the locale to properly read/write symbols from the file. Without this change it tried to read the file using the default locale, usually XX_xx.utf-8, and naturally failed because of "invalid multibyte sequences".

2022-06-03 07:54 UTC, undef21 commented on files/lang/Makefile
> +	LANG=ru_RU.CP1251 LC_ALL=ru_RU.CP1251 LC_CTYPE=ru_RU.CP1251 sed -e 's/UTF-8/CP1251/' $<.tmp > $<.2.tmp
Ohh, it's sadly. If we change this recipe to
```
ru.mo: ru.po                                                                                                                          
    sed -e 's/UTF-8/CP1251/' $< | iconv -f utf-8 -t CP1251 | msgfmt - -o $@
```
will it work on MacOS?

2022-06-03 08:07 UTC, oleg-derevenetz commented on files/lang/Makefile
> +	LANG=ru_RU.CP1251 LC_ALL=ru_RU.CP1251 LC_CTYPE=ru_RU.CP1251 sed -e 's/UTF-8/CP1251/' $<.tmp > $<.2.tmp
@undef21 by doing so, you will rely on the default locale. If it is UTF-8, then it would probably work. However, if it for some reason will be set to the UTF-16 (which seems to be very unlikely), it would probably fail. You can try it on the CI pipelines, they will run the build on macOS too.