Add translation support without Unicode
ihhub/fheroes2 pull request #3869
Opened 2021-07-18 15:12 UTC by ihhub

works on SDL 1 as well and only for game versions with correct language
alphabet

2021-07-18 17:49 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few comments here, could you please take a look when you have time? Also I have the following questions:

1. Is there any value in the current "Unicode" implementation? As I can see, it doesn't even know how to work correctly with Unicode fonts;
2. As I can see, there was an attempt to bind in-game language to the system language (I mean, before, now it seems that this is regulated via config file only). I believe that by default (on empty `lang`) in-game language should be bound to the language of resources in the `DATA` folder (if possible, of course). Otherwise we may get weird mixes, when, for example, in-game language is Russian, but game resources are in English, so user will need to edit the config file to set `lang` by hand.

2021-07-18 17:49 UTC, oleg-derevenetz commented on src/fheroes2/game/fheroes2.cpp
> +            const std::string mofile = conf.ForceLang().empty() ? System::GetMessageLocale( 1 ).append( ".mo" ) : std::string( conf.ForceLang() ).append( ".mo" );
I believe that `conf.ForceLang()` can't be empty here.

2021-07-18 17:49 UTC, oleg-derevenetz commented on src/fheroes2/game/game_io.cpp
> +        warningMessage += '\'';
I believe better wording may be like this: "This saved game is localized to %s language, but the current language of the game is %s."

2021-07-19 12:25 UTC, ihhub commented
> Hi @ihhub I just left a few comments here, could you please take a look when you have time? Also I have the following questions:
> 
> 1. Is there any value in the current "Unicode" implementation? As I can see, it doesn't even know how to work correctly with Unicode fonts;
> 2. As I can see, there was an attempt to bind in-game language to the system language (I mean, before, now it seems that this is regulated via config file only). I believe that by default (on empty `lang`) in-game language should be bound to the language of resources in the `DATA` folder (if possible, of course). Otherwise we may get weird mixes, when, for example, in-game language is Russian, but game resources are in English, so user will need to edit the config file to set `lang` by hand.

Hi @oleg-derevenetz ,
1. Unicode related code was in the old version of the project before 0.8.1 when we introduced current rendering engine. Before that rendering was based on SDL functions rather than on technology-separate logic leading to possibility to use SDL TTF support to convert fonts into SDL images for the subsequent rendering. However, such approach makes the game to have incorrect fonts. Maybe for some people it's not the issue but for others it's a big deal. So right now unicode related code has no value at all as we use in-game fonts. We can remove it.
2. This is a problem which I haven't figured out yet. Somehow we need to detect which language the original game resources contains. Whether it is French, Russian, Polish, German or English (the rest of languages were not officially supported). One way to do this is to verify almost every letter presented in alphabet to match the language. Let's take Russian language since you mentioned it. Russian language is Cyrillic alphabetic based where some letters are very similar to Latin but other aren't. Then we take Polish alphabet which is very similar to Latin. Without storing assets from the original game (we can't do this) how we detect that image in alphabet at place let's say 50 is H (russian letter) insted of K (latin letter).

Possible solutions for this problem:
- remember CRC32 from AGG files of the original copies of the game. Disadvantage: are we breaking the license by this?
- find alphabets which have letters on certain positions while others don't. By empty I mean an image bigger than 1x1 pixel. Some images are really 1x1 because they aren't used in the language. Disadvantage: 2 alphabets can have similar places which aren't empty.
- find an indicator: file, line and etc. which states the language of assets but I don't know about any of those.

2021-07-19 12:28 UTC, ihhub commented on src/fheroes2/game/game_io.cpp
> +        warningMessage += '\'';
Got it. I'll fix it. Thank you!

2021-07-19 12:28 UTC, ihhub commented on src/fheroes2/game/fheroes2.cpp
> +            const std::string mofile = conf.ForceLang().empty() ? System::GetMessageLocale( 1 ).append( ".mo" ) : std::string( conf.ForceLang() ).append( ".mo" );
Good catch!

2021-07-19 12:48 UTC, oleg-derevenetz commented
Hi @ihhub

> So right now unicode related code has no value at all as we use in-game fonts. We can remove it.

I can do it in a separate PR after merging this one.

> remember CRC32 from AGG files of the original copies of the game. Disadvantage: are we breaking the license by this?

I don't really think that we are breaking the license by providing a hash sum for certain data files. If this were the case, many antivirus software or package managers would "break the license" in this way :)

2021-07-19 20:18 UTC, oleg-derevenetz approved these changes

2021-07-19 22:58 UTC, undef21 commented
> remember CRC32 from AGG files of the original copies of the game. Disadvantage: are we breaking the license by this?

Such project as ScummVM [contains](https://github.com/scummvm/scummvm/blob/master/engines/agos/detection_tables.h) md5 sums of supported game resources for many years.

2021-07-20 02:27 UTC, merged