SpellStorage doesn't inherit from std::vector anymore
ihhub/fheroes2 pull request #3870
Opened 2021-07-19 21:07 UTC by vincent-grosbois

This is cleaner because now it's impossible to directly modify the underlying std::vector
But it required several refactors in different places, so not sure it's worth it overall

2021-07-20 09:55 UTC, qarkai commented on src/fheroes2/spell/spell_storage.h
> +    typedef std::vector<Spell>::const_iterator const_iterator;
```suggestion
    using const_iterator = std::vector<Spell>::const_iterator;
```

2021-07-20 10:02 UTC, qarkai commented on src/fheroes2/spell/spell_storage.h
> +    int Size() const;
Method appears unused.

2021-07-20 10:13 UTC, qarkai commented on src/fheroes2/spell/spell_book.cpp
> +                                              } ) ) );
```suggestion
        storage.spells.erase( std::remove_if( storage.spells.begin(), storage.spells.end(), [filter]( const Spell & s ) {
                                                  return ( ( SpellBook::Filter::ADVN == filter ) && s.isCombat() )
                                                         || ( ( SpellBook::Filter::CMBT == filter ) && !s.isCombat() );
                                              } ), storage.spells.end() );
```

2021-07-20 10:15 UTC, qarkai commented on src/fheroes2/spell/spell_book.cpp
> +            storage.spells.resize( std::distance( storage.spells.begin(), itend ) );
```suggestion
        storage.spells.erase( std::remove( storage.spells.begin(), itend, Spell( Spell::TOWNGATE ) ), storage.spells.end() );
        storage.spells.erase( std::remove( storage.spells.begin(), itend, Spell( Spell::TOWNPORTAL ) ), storage.spells.end() );
```

2021-07-20 10:19 UTC, qarkai commented on src/fheroes2/spell/spell_storage.cpp
> +bool SpellStorage::HasSpell( const Spell & spell ) const
Please follow https://github.com/ihhub/fheroes2/wiki/Code-style#naming

2021-07-20 10:19 UTC, qarkai commented on src/fheroes2/spell/spell_storage.cpp
> +    for ( auto it : spells ) {
Please follow https://github.com/ihhub/fheroes2/wiki/Code-style#auto

2021-07-20 15:04 UTC, ihhub requested changes
Hi @vincent-grosbois , I left several comments here. Would you mind to take a look?

2021-07-20 15:04 UTC, ihhub commented on src/fheroes2/spell/spell_storage.h
> +    std::vector<Spell> spells;
Please name it as `_spells` to indicate that this is a member of the class. Also is there a reason to make this member **protected** over **private**?

2021-07-20 15:04 UTC, ihhub commented on src/fheroes2/spell/spell_storage.cpp
> +    return os.str();
We can do this without `ostringstream`:
```
std::string output;

for ( const Spell & spell : spells ) {
    if ( !output.empty() ) {
        output += ", ";
    }
    output += spell.GetName();
}

return output;
```

This version won't produce `, `at the end of the string.

2021-07-20 16:47 UTC, vincent-grosbois commented on src/fheroes2/battle/battle_main.cpp
> +    for ( auto sp : spells ) {
@ihhub I'm not sure what's the big deal with copying a spell instance, it's just wrapping an int
I'll do it I guess but to me this is really a kind of premature optimization

2021-07-20 20:03 UTC, vincent-grosbois commented on src/fheroes2/spell/spell_storage.h
> +    std::vector<Spell> spells;
it's done so SpellBook class has access to it too

2023-07-21 15:02 UTC, ihhub commented
I am closing this pull request due to the low impact on the code and presence of many merge conflicts.

2023-07-21 15:02 UTC, closed without merging