Add monster names to translations
ihhub/fheroes2 pull request #3913
Opened 2021-07-27 09:02 UTC by dimag0g

The main goal if this PR is to add monster names to translation files. Many translations files already have the appropriate translations, but the `gettext` calls on English strings were missing in the source code, so those translations were disabled.

I made a merge pass on all translation files (including the invalid ones), without any manual fixes afterwards. I see that at least in the Polish translation many monster names were associated correctly with their English counterparts.

There are also two small fixes related to translations but not monster names sepcifically:

- the "guarded by" message was not translated if scouting was not learned
- the message "some undead in groups" [sic] featured an inappropriate plural form

2021-07-27 14:43 UTC, ihhub requested changes
Hi @dimag0g , I left few comments here. Could you please check them?

2021-07-27 19:42 UTC, dimag0g commented on src/fheroes2/monster/monster_info.cpp
> +                { _( "Unknown Monster" ), _( "Unknown Monsters" ), 0, Race::NONE, 0, { 0, 0, 0, 0, 0, 0, 0 } },
Sorry, I don't quite understand the target we need to achieve. If the user changes the language at runtime, all translated strings stored in static variables will have wrong values. This is not limited to monster names AFAIK. E.g. the campaign data will have the same behavior, and I'm sure there's more. Shall all such places be reworked?

Frankly, I would just force the user to restart the game if they changed the language.

2021-07-27 23:56 UTC, dimag0g commented on src/fheroes2/monster/monster_info.cpp
> +                { _( "Unknown Monster" ), _( "Unknown Monsters" ), 0, Race::NONE, 0, { 0, 0, 0, 0, 0, 0, 0 } },
If it's really necessary to support language changes at runtime, there's `gettext_noop` which I could use instead of `_` - it adds strings to the translation catalog without actually translating them.

2021-07-28 08:41 UTC, dimag0g commented
@ihhub I just realized the monster abilities and hero skills are not translated either, let me know if you want me to amend this PR with these changes

2021-07-28 14:33 UTC, ihhub commented
> @ihhub I just realized the monster abilities and hero skills are not translated either, let me know if you want me to amend this PR with these changes

Sure. Let's do this. I also noticed that you touched a lot of language files. My first question is can we remove comments about file and line in source code from `fheroes2.pot` file? We frequently update codebase so these comments make no sense.

Secondly, could you please explain why do we have so many changes in files? I see that some of them like French translation is just code movement from one place to another.

2021-07-28 14:47 UTC, dimag0g commented
@ihhub,

Regarding `fheroes2.pot`, I think we should simply remove this file from source control and use the latest version in `src/dist`  when merging. Perhaps it's a good idea to have a separate `merge` make target.

Regarding the lines which moved around, some of those are existing translations which came from the disabled translation pool at the end of the file back to their rightful place. Other lines moved around for no apparent reason. All I can tell is their position doesn't change after a full rebuild (`make clean; make`).

2021-07-28 15:55 UTC, dimag0g commented
I have added some changes which replace `_n( )` with `_( )`, for the reasons explained here: #3919

2021-07-28 18:14 UTC, dimag0g commented on src/fheroes2/monster/monster.cpp
> +    return fheroes2::getMonsterData( id ).generalStats.pluralName;
reverted.

2021-07-29 13:04 UTC, ihhub commented
Hi @dimag0g , if we can go without **fheroes2.pot** file then let's just remove it. Could you please explain about `merge` target?

2021-07-29 19:57 UTC, dimag0g commented
@ihhub I suggest we make a `merge` target, as in `make merge`. This would trigger a merge of all translation files against `../../src/dist/fheroes2.pot`. The normal `make` in `files/lang` would only make `.mo` files out of `.po` files, without the need to build the `.pot` file.

The alternative is to always merge against `../../src/dist/fheroes2.pot`, but that would mean translators will need a complete toolchain if they want to build `.mo` files to test their work.

2021-07-30 12:08 UTC, dimag0g commented
@ihhub I have added a commit replacing `$(wildcard $(SEARCH))` with `$sort( $(wildcard $(SEARCH)))`, hopefully that will prevent translation strings moving around.

2021-07-31 00:19 UTC, ihhub commented
Hi @dimag0g , could you please fix merge conflicts for this pull request as I approved another one with changes similar to this one?

2021-07-31 01:27 UTC, ihhub approved these changes

2021-07-31 05:53 UTC, dimag0g commented
@ihhub Done. I also took the liberty to remove the `\r` character from `pl.po`, which AFAIK does nothing in addition to `\n`

2021-07-31 08:34 UTC, merged

2021-07-31 08:34 UTC, ihhub commented
@dimag0g , excellent work! Thank you very much!

2021-07-31 09:26 UTC, dimag0g commented
@ihhub I really appreciate the time and effort you dedicate to this project!

2021-07-31 09:27 UTC, ihhub commented
@dimag0g , you're very welcome! I'm finishing UI dialog to change language during runtime, not only on the first game startup :)

2021-07-31 09:38 UTC, dimag0g commented
@ihhub FYI, I have [discovered](https://unix.stackexchange.com/questions/662718/xgettext-incorrectly-sorts-strings) that `xgettext -F`, while sorting translation entries by file location, still sorts entries alphabetically if they are on the same line. You can see the example in `army.cpp`:

    _( "army|Few" ),    _( "army|Several" ), _( "army|Pack" ),   _( "army|Lots" ),  _( "army|Horde" )

resulting in "Few", "Horde", "Lots", "Pack", "Several" order in the translation files.

While this is sub-optimal from the translator's PoV, I think it's acceptable, and since it seems to prevents the reordering after each merge, I think we should still keep it from now on.

2021-07-31 09:40 UTC, ihhub commented
Once we have almost completed translations we won't need to care about sorting strings after all. For now it might be a bit inconvinient but it's just a temporary measure. My idea was to make things stable with changes in the code.