allow player to immediately edit save file name without clicking on the input field
ihhub/fheroes2 pull request #3933
Opened 2021-07-31 02:27 UTC by eos428

fix #3103

2021-07-31 04:49 UTC, ihhub requested changes

2021-07-31 04:49 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +    bool edit_mode = true;
This change allows to edit save files for Save file Loading screen.

2021-07-31 13:50 UTC, ihhub requested changes

2021-07-31 13:50 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +    bool edit_mode = editor;
The original issue requires input field to always have an active state while this change will make it only for the time of opening the dialog and after clicking on an item the focus is gone. Also **_** symbol is not present.

2021-07-31 14:48 UTC, eos428 commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +    bool edit_mode = editor;
Yeah you're right, we probably don't need `editMode` anymore in this case and we might as well change up the `listbox` so that it doesn't need `editMode` anymore.

2021-08-14 14:58 UTC, merged

2021-08-14 14:58 UTC, ihhub commented
@eos428 , huge thanks for adding this feature!