Nintendo Switch build fixes
ihhub/fheroes2 pull request #3953
Opened 2021-08-02 12:28 UTC by dimag0g

- add custom 848x480 resolution, fix touchscreen scaling
- hardcode home directory as `/switch/fheroes2`
- convert the icon file to JPG (PNG is not working)
- custom controls layout, described in the Readme file

2021-08-02 16:00 UTC, ihhub requested changes
Hi @dimag0g , I left multiple comments here. Could you please take a look?

2021-08-02 16:00 UTC, ihhub commented on docs/README_switch.md
> +It's possible to use USB mice / keyboards with this build.
Could we rephrase this sentence into `USB mice and keyboards are supported too.`?

2021-08-02 16:02 UTC, ihhub commented
@dimag0g , can't the icon have transparent background? If not I can provide an image with a proper background in this case.

2021-08-02 19:16 UTC, oleg-derevenetz requested changes
Hi @dimag0g I left a few comments, could you take a look when it is convenient for you?

2021-08-02 19:16 UTC, oleg-derevenetz commented on Makefile.switch
> +PLATFORM = switch
Is this variable used anywhere? The sub-`make` command receives separate `PLATFORM=switch` argument.

2021-08-02 19:16 UTC, oleg-derevenetz commented on Makefile.switch
> +.PHONY: $(TARGET).elf
Why the `$(TARGET).nacp` and `$(TARGET).elf` are declared as phony targets? These are real files and they can be tracked by `make` as usual. Is there some reason I don't know about?

2021-08-02 19:19 UTC, dimag0g commented on src/engine/localevent.cpp
> +#define SDL_CONTROLLER_BUTTON_DPAD_DOWN 12
The purpose of these `#undef/#define` is to redefine existing constants, in order to keep intact the code that uses them. I'm pretty sure redefining them as enumeration will not work.

2021-08-02 19:29 UTC, dimag0g commented on Makefile.switch
> +.PHONY: $(TARGET).elf
`$(TARGET).nacp` depends on `$(PROJECT_VERSION)` and other variables. It will not be rebuild if these variables change, unless declared as `.PHONY`. As an option, it could be declared to depend on the file which defines the current version, e.g. `Makefile.switch`.

`$(TARGET).elf` is a copy of `src/dist/$(TARGET).elf`, which in turn depends on all `.cpp`/`.h` files inside `src`. It will not be rebuilt when the source code changes, unless the sub-make is run unconditionally.

Is there a better way to force `make` targets to always be rebuilt?

2021-08-02 19:37 UTC, oleg-derevenetz commented on Makefile.switch
> +.PHONY: $(TARGET).elf
Yeah, fair point - they depend on non-files and files that are not tracked by this Makefile.

> As an alternative, we could simply list all the commands inside an existing .PHONY target, all

Yes, it will look better this way. BTW, we can list `clean` as phony as well.

2021-08-02 19:39 UTC, oleg-derevenetz commented on Makefile.switch
> +.PHONY: $(TARGET).elf
BTW, could you please implement similar changes in `Makefile.vita` as well? `$(TARGET).elf` depends on external files here and `param.sfo` depends on variables.

2021-08-02 19:58 UTC, dimag0g commented on docs/README_switch.md
> +This is a port of Free Heroes 2 (free implementation of Heroes of Might and Magic 2 engine) to Nintendo Switch.
Should I include `README_switch.md` along with `README.txt`, or should I only include `README_switch` and add missing parts of `README.txt` to it?

2021-08-02 20:38 UTC, dimag0g commented on Makefile.switch
> +.PHONY: $(TARGET).elf
@ihhub I've tried to implement the requested fixes. I left the `#undef/#define` part unchanged, modified the Makefile.switch to run the packaging commands unconditionally, and replaced the icon with a white background version. I never managed a PNG icon to work on a Switch, so keeping the transparent background is not possible AFAIK.

Unfortunately, I will be unavailable for the next few days. If there's a trivial change required which you could do yourself, it might be better to do so instead of waiting for me to respond.

2021-08-02 20:39 UTC, dimag0g commented
@ihhub I've tried to implement the requested fixes. I left the `#undef/#define` part unchanged, modified the Makefile.switch to run the packaging commands unconditionally, and replaced the icon with a white background version. I never managed a PNG icon to work on a Switch, so keeping the transparent background is not possible AFAIK.

Unfortunately, I will be unavailable for the next few days. If there's a trivial change required which you could do yourself, it might be better to do so instead of waiting for me to respond.

2021-08-03 01:46 UTC, ihhub commented on docs/README_switch.md
> +This is a port of Free Heroes 2 (free implementation of Heroes of Might and Magic 2 engine) to Nintendo Switch.
Both files should be present like you did.

2021-08-03 14:31 UTC, oleg-derevenetz commented
Hi @ihhub are you sure you want to delete JPG and not PNG?

2021-08-03 14:39 UTC, ihhub commented
> Hi @ihhub are you sure you want to delete JPG and not PNG?

Yes, I wanted to replace JPEG but I couldn't so I made another commit to add JPEG file. Now it's in master branch.

2021-08-03 14:49 UTC, ihhub approved these changes

2021-08-03 15:09 UTC, ihhub commented
Hi @oleg-derevenetz , do you have any more comments about this pull request?

2021-08-03 15:22 UTC, oleg-derevenetz commented
Hi @ihhub No, I suppose we can merge this. We can make a separate PRs then if needed.

2021-08-03 15:22 UTC, merged

2021-08-03 15:22 UTC, ihhub commented
@dimag0g , a huge thanks for these changes!