Remove zoomIn flag from ViewWorld::ZoomROIs::ChangeZoom
ihhub/fheroes2 pull request #3970
Opened 2021-08-04 17:27 UTC by qarkai

Split `ChangeZoom()` to `zoomIn()` and `zoomOut()`.

2021-08-08 05:15 UTC, ihhub requested changes
Hi @qarkai , I left just 2 comments here. Could you please take a look?

2021-08-08 05:15 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    bool changed = ( newLevel != _zoomLevel );
We could make this variable `const`.

2021-08-08 05:15 UTC, ihhub commented on src/fheroes2/kingdom/view_world.h
> +        bool zoomOut( const bool cycle = false );
Can we please avoid using default values for input arguments?

2021-08-08 07:18 UTC, qarkai commented on src/fheroes2/kingdom/view_world.h
> +        bool zoomOut( const bool cycle = false );
As you wish.

2021-08-14 14:23 UTC, merged

2021-08-14 14:23 UTC, ihhub commented
@qarkai , thank you very much for this code cleanup!