Do not let the player get a random artifact that allows him to win the game
ihhub/fheroes2 pull request #4001
Opened 2021-08-10 23:09 UTC by oleg-derevenetz

fix #3999

2021-08-14 14:42 UTC, ihhub requested changes
Hi @oleg-derevenetz , there are multiple comments. Could you please take a look at them?

2021-08-14 14:42 UTC, ihhub commented on src/fheroes2/resource/artifact.h
> +void ResetArtifactStats();
Could we please avoid using global functions? We can put them in `fheroes2` namespace to reduce their scope.

2021-08-14 14:42 UTC, ihhub commented on src/fheroes2/resource/artifact.h
> +void ExcludeArtifactFromRandom( int art );
I would recommend to make this input argument `const` and name it as `artifactID` :)

2021-08-14 14:42 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +        { 0, 12, TYPE3, _( "Ultimate Book of Knowledge" ), _( "The %{name} increases your knowledge by %{count}." ) },
Could we please remove translation calls here since we do the same in the code below and also it's a global variable which is initialized at the very beginning of the application.

2021-08-14 14:42 UTC, ihhub commented on src/fheroes2/world/world_loadmap.cpp
> +    ResetArtifactStats();
What's about loading a save file? I think we need to reset there as well.

2021-08-14 14:42 UTC, ihhub commented on src/fheroes2/world/world_loadmap.cpp
> +    }
Shouldn't we need to put this check just before `ProcessNewMap` call?

2021-08-14 14:45 UTC, oleg-derevenetz commented on src/fheroes2/world/world_loadmap.cpp
> +    ResetArtifactStats();
@ihhub As far as I know, random artifacts are replaced by actual ones on the start of a new game (when MP2 is processed), so in save files random artifacts are not random anymore :)

2021-08-14 14:46 UTC, ihhub commented on src/fheroes2/world/world_loadmap.cpp
> +    ResetArtifactStats();
That's a good point :)

2021-08-14 14:51 UTC, oleg-derevenetz commented on src/fheroes2/resource/artifact.cpp
> +        { 0, 12, TYPE3, _( "Ultimate Book of Knowledge" ), _( "The %{name} increases your knowledge by %{count}." ) },
I believe that translation calls are needed here to properly generate `.po` file. They don't really work but they are just markers for `gettext` parser.

2021-08-14 14:53 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +        { 0, 12, TYPE3, _( "Ultimate Book of Knowledge" ), _( "The %{name} increases your knowledge by %{count}." ) },
Oh, yes. I totally forgot about this. We can leave as it is or use `gettext_noop` call instead.

2021-08-14 15:15 UTC, oleg-derevenetz commented on src/fheroes2/resource/artifact.cpp
> +        { 0, 12, TYPE3, _( "Ultimate Book of Knowledge" ), _( "The %{name} increases your knowledge by %{count}." ) },
I believe `_()` looks shorter.

2021-08-14 15:23 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +        { 0, 12, TYPE3, _( "Ultimate Book of Knowledge" ), _( "The %{name} increases your knowledge by %{count}." ) },
The difference between `_()` and `gettext_noop` is that the last function does exactly nothing. Anyway, I'm marking this comment as resolved.

2021-08-15 05:36 UTC, merged

2021-08-15 05:36 UTC, ihhub commented
@oleg-derevenetz , good job! Thanks for the fix!