Update fr.po
ihhub/fheroes2 pull request #4003
Opened 2021-08-11 14:56 UTC by 1GodRage

Lots of improvements.

2021-08-11 14:59 UTC, 1GodRage commented
In french, "blabla!" => "blabla !"
and "bla:" => "bla :"
"dommage" => "dégât" (sounds much more french and accurate)
En français, "Endommage" et "Dommage" ne font pas référence au vivant, mais aux objets.


lines 35 to 119: I suggest to keep that same as the original to keep consistant the words put on each estimations (few => quelques, etc).



452	msgstr "%{spell} fait %{value} dégât(s) à un mort-vivant."
Je propose "dégâts" au lieu de "dégât(s)" vu que ce sera très rarement "1" point de dégât.


Incohérence dans les lignes 470 473 476
Je propose de mettre les attaques spéciales au singulier, ainsi, c'est le nom de l'attaque, et n'est plus relié au nombre de créatures attaquantes :
L'attaque de Licorne ...
Le regard de Meduse ...
La malédiction de Momie ...

493 494:
> msgid "Low morale causes the %{monster} to freeze in panic."
> msgstr "Un moral bas fait que les %{monster} gèlent en panique."
Traduction à refaire (freeze in panic = ?).

610 -> 619, and 733 -> 743: Firsts campaign texts
Double spaces in both English and French texts, between "." and next sentence. Is it done on purpose?

845 msgstr "Coeur de la corruption"
"Cœur ..." could be "more french" but may not be in the Heroes2 Font.

931 msgid "The Epic Battle"
932 msgstr "Combat Épique"
Rajouter "Le " ? Le "É" passe bien ?

997 msgid "Fount of Wizardry"
998 msgstr "Source de la Magie"
Source de Sorcellerie ?

1034 "ou vos rivaux seront sûrement arrivés à la source avant vous."
Je trouve la tournure vraiment bizarre. (et c'est pas la première ; c'est des phrases qui en anglais ont "surely")

1050 msgstr "Iles Pirates"
Je propose "Îles ..." mais pas sûr si ça passe. (les autres noms de ce genre pour les campagnes ont les accents (É))

1104 msgstr "Les ogres vous reconnaissent comme le Dwarfbane et vous rallient."
Traduction à refaire (Dwarfbane = ?)
1156 "... Dwarfbane ..."


1230+:
> msgstr "Place du marché"
Marché avec une Majuscule dans le jeu original.
> msgstr "Jardin de Cristaux"
"... cristaux" sans majuscule dans le jeu original.
Normalement en français la majuscule est au premier mot seulement, alors qu'en anglais on met des majuscules à chaque mot.


1244 msgid "Mage Guild, Level 1"
1245 msgstr "Guide des mages niv. 1"
Sur le jeu de base c'est "Guilde des magiciens" ( http://homm2.free.fr/enroth.php?p=sorc )
Version de GoG ?

1397 -> : Upgraded buildings
Certains "renforcés" ne font pas sens... Je propose les noms du jeu original (pas la version traduite par GoG) :
Cimetière renforcée => Grand cimetière
Pyramide renforcée => Grande pyramide
Cromlech renforcé => Grand cromlech
Labyrinthe renforcé => Grand labyrinthe
Manoir renforcé => Grand manoir
Arène renforcée => Arène améliorée
Tour d'ivoire renforcée => Haute tour d'ivoire
Mausolée renforcée => Grand mausolée
Cathédrale renforcée => Basilique
Château céleste renforcée => Grand château céleste 


1579 "Le Donjon augmente les revenus de votre village de %{count} pièces par jour."
1590 "La tempête ajoute +2 à la puissance des sortilèges d'un sorcier qui défend."
Inconsistances : On garde la majuscule à chaque fois, ou on la sors à chaque fois ? ^^


1585 "La bibliothèque augmente le nombre de sorts de la guilde d'un pour chaque ""niveau de la guilde."
Je propose => "La bibliothèque rajoute 1 sort à chaque niveau de la guilde des magiciens."

1596 "Le lieu saint augmente la puissance de nécromancie de tous les nécromanciens ""de 10 pour cents."
C'est bizarre ça... un lieu saint chez les nécromants...

1600 msgstr "Impossible de recruter - guest to guard automove error."
Manque une traduction.


1623 msgid "Army is full"
1624 msgstr "L'armée est complète"
Le message ne devrait pas plutôt dire "Nombre maximal atteint dans le peloton." ?


1627 msgstr "Join Error"
à traduire.


1733 msgstr "Pas assez de ressources pour acheter des monstres."
Vérifier dans le jeu si le mot "créature" ne serait pas plus approprié que "monstre".
(pareil pour les 2 entrées suivantes)


1922 msgstr "Classe"
Classification ? Je propose "Alignement" comme dans le H2 original... Ou à la limite "Faction".

1928 "Victoire\n"
1929 "Conditions"
Victory conditions => Conditions de victoire. (trouver où ça s'affiche en jeu puis aviser)
Même problème pour :
1935 "Défaite\n"
1936 "Conditions"

2005 msgstr "gardée par "
Comment vérifié l'info ingame ? C'est la mine qui est gardée ?
2008 msgstr "gardé par %{count} de %{monster}"
Là c'est un trésor gardé par ??


2055 msgid "Move Points"
2056 msgstr "P. de voyage"
Je propose "Mouvement", le joueur comprendra de lui même que c'est des points. (on dit pas "points d'attaque" par exemple, donc ça devrait passer)


2262 msgstr "Interface"
Je proposerai "Interface : Coloris", ou alors il faudrait renommer les options "Bien" et "Mal" en "Clair" et "Sombre" pour l'interface. Ce serait plus parlant.
2268 msgstr "Interface"
serait "Interface" et les options seraient "Attachée" et "Libre"... Au lieu de "Afficher" et "Cacher" => Il faudrait faire un nouveau dessins pour cette case là.

2277 msgstr "Bascule le mode de combat instantané."
Proposition : "Change les modes de combat instantané."

2339 msgid "1st"
2340 msgstr "1-er"
Le tiret est-il vraiment utile ? Dans Heroes 2 le tiret ça devient un genre de tilde méga-grande... Je propose de sortir les tirets : "1er"

2478 "A multi-player game, with several human players completing against each "
competing is the right word, right? xD

2590 msgstr "Combat unique"
Je proposerai "Mode Bataille", ou au moins "Unique combat", ou "Bataille seule" ou "Combat seulement" ou "Champ de bataille" ou même "Bataille !".

2635 "Play with 5 human players, and optionally, up to 1 additional computer "
For English version: "optionnally, up to 1" => "optionnally 1"

2686 "L'ennemi a capturé %{name} !\n"
2687 "Ils sont triomphants."
La manière de le dire semble incohérente. Il faudrait trouver qq chose de plus élégant.
"Le camp adverse l'emporte." ?

2769 "Ne pas gagner d'ici la fin du mois %{month}, semaine %{week}, jour %{day}."
Soit : "... d'ici la fin du moins %{month}."
Soit : "... avant %{month}, semaine %{week}, jour %{day}."

2825 msgstr "Classe :"
Suggestion : "Alignement :"

2831 msgstr "Les astrologues proclament le mois de %{name}."
2834 msgstr "Les astrologues proclament la Semaine de %{name}."
de, du, de la, des ? + inconsistance de la majuscule : mois / Semaine
...la semaine de Loup => ...la semaine du Loup
From:
5392 msgid "week|PLAGUE"
it is weekly creatures. Can we add "de le ..." inside?

2848 et 2851 "%{count} pour cent !"
Suggestion : "%{count}% !"

2902 msgstr "Continuez le mouvement du Héros le long du chemin actuel."
Continuer ? <= à vérifier ingame

2905 msgstr "Résumé du Royaume"
Suggestion : "Infos Royaume" ou "Récap. Royaume" ou juste "Royaume". Dans le jeu original c'est "Vue générale du Royaume".

2908 msgstr "Voir un résumé de votre Royaume."
Suggestion : "Voir un récapitulatif de votre Royaume."

3032 msgstr "Nécroman"
What is that? ^^ Necromancy?

3286 msgstr "%{objet} voleur"
Where ingame?

3411 msgstr "En cherchant dans les vêtements en lambeaux, vous trouvez %{artifact}."
J'espère que le %{artifact} contient le déterminant aussi... ^^'
=> "... trouvez le/la/l' %{artifact}."
3428 msgstr "En cherchant à l'intérieur, vous trouvez le %{artifact}."
Même soucis... ça peut donner par exemple "le Arc doré" ou "le Patte de lapin".

Gender problem : artifact
3845 "gentillesse en vous donnant le %{art}."
3849 "Un lutin vous offre l'%{art} pour le petit prix de %{gold} pièces d'or."
3855 "Un lutin vous offre la %{art} pour le petit prix de %{gold} pièces d'or et "
"%{count} de %{res}."
3883 "qu'il est prêt à donner le %{art} à la première personne sage qu'il "
3892 "soldat vous dit qu'il est prêt à transmettre le %{art} au premier vrai chef "
3912 msgstr "Victorieux, vous prenez votre prix, le %{art}."
3933 "l'ouvrez et trouvez %{gold}'or et le %{art}."
4364 msgstr "Vous avez trouvé %{artifact}."
4465 "vous tuez le monstre et trouvez le %{art} à l'arrière de la grotte."
=> sug [...]

2021-08-11 18:09 UTC, oleg-derevenetz requested changes
Hi @1GodRage there is a quotation mark missing in the `fr.po` which breaks the build. Please fix this.

2021-08-11 18:09 UTC, oleg-derevenetz commented on files/lang/fr.po
> +"semaine.
This string should end with a quotation mark.

2021-08-11 19:15 UTC, 1GodRage commented on files/lang/fr.po
> +"semaine.
Oops! Thanks for noticing it @oleg-derevenetz 
fixed in the 2nd update.

2021-08-14 15:16 UTC, ihhub requested changes
Hi @1GodRage , I left few comments here. Would you mind to take a look?

2021-08-14 15:16 UTC, ihhub commented on files/lang/fr.po
> +msgstr "%{name} passe le tour"#if 2+ monster: "... passent ..."
Could we please at least add a space before `#` so it's easier to understand that this is a comment?

2021-08-14 15:16 UTC, ihhub commented on files/lang/fr.po
> +msgstr "%{name} passe le tour"#if 2+ monster: "... passent ..."
The same comment applies for lines 424 and 421.

2021-08-14 15:16 UTC, ihhub commented on files/lang/fr.po
> +msgstr "Voir seulement les grandes cartes (108x108)"
Why did we remove a full stop from here and from line 2113?

2021-08-14 15:16 UTC, ihhub commented on files/lang/fr.po
> +""
Please remove this empty text line.

2021-08-14 15:16 UTC, ihhub commented
Hi @dimag0g , could you please also review these changes?

2021-08-14 16:25 UTC, dimag0g commented
Concerning the character set:
- `œ` will have to be replaced by `oe` to be usable, and since there are very few words using it, I suggest we leave `oe` directly in the translation files
- Capitals with diacritics (`Î`, `É`, etc.) are also not available AFAIK. Most of these are already replaced by regular English capitals (e.g. `E`) via the Makefile, I suggest we also add `Î` ->`I` replacement.

2021-08-14 16:31 UTC, dimag0g commented on files/lang/fr.po
> +msgstr "%{name} passe le tour"#if 2+ monster: "... passent ..."
"skip" is plural, as in "they skip", so it should be translated with a plural form as well. Whether singular forms should be implemented in the game is a separate question, and it's impossible to provide a translation for singular forms before such a change is done.

2021-08-14 17:55 UTC, dimag0g commented on files/lang/fr.po
> +msgstr "Formation Déploiement"
I would personally prefer "Dispersée" here, as seen in the GoG version of the game.

2021-08-14 17:55 UTC, dimag0g commented on files/lang/fr.po
> -"Type de jeu de fichier non valide. Assurez-vous que vous avez le dernier "
Makes me wonder if "Invalid file game type" should also be rephrased to "Invalid game file type". @ihhub, what do you think?

2021-08-14 17:55 UTC, dimag0g commented on files/lang/fr.po
> +""
Perhaps the French name, "Le Prix de la Loyauté", should be used.

2021-08-14 17:55 UTC, dimag0g commented on files/lang/fr.po
> +"Joueur %{color}, il ne vous reste que %{day} jours pour capturer un village, "
@ihhub The original string should use `ngettext` plural forms here (day/days).

2021-08-14 17:55 UTC, dimag0g commented on files/lang/fr.po
> +"Cette fenêtre fournit des informations sur le statut de votre héros et "
This is actually 3 views in one: hero status, kingdom info, and date. I think we should use the same union ("and" or "or") for all three options in English, and the translations should follow. @ihhub what do you think?

2021-08-14 17:55 UTC, dimag0g commented on files/lang/fr.po
> +"rallier votre armée pour un prix. Voulez-vous recruter des Meduses ?"
"Meduses" -> "Méduses"

2021-08-14 17:55 UTC, dimag0g commented on files/lang/fr.po
> -"Vous trouverez un démon puissant et grotesque dans la grotte. « Aujourd'hui, "
Could you also make a search pass and replace `«` quotes with `"`? I know `«` looks more French, but they are only used inconsistently in a few places.

2021-08-14 17:55 UTC, dimag0g commented on files/lang/fr.po
> +"céderait pour %{count} pièces d'or.\""
"céderait" -> "céderai"

2021-08-14 17:55 UTC, dimag0g commented on files/lang/fr.po
> +"%{skill} donne aux tirs de catapulte de votre héros plus de chances de "
This is a description for "ballistics" skill, which is translated to "Ballistique" if I remember right. Are you sure you want to drop the article? In fact, we should IMO consider adding appropriate articles in other skill descriptions as well.

2021-08-14 17:55 UTC, dimag0g commented on files/lang/fr.po
> +"des sorts de froid."
Perhaps "La %{name} réduit de moitié tous les dégâts infligés à vos troupes par des sorts de froid." ? Same for fire/lighning spells.

2021-08-14 17:55 UTC, dimag0g commented on files/lang/fr.po
> +"double les dégâts subis par le froid."
"dégâts subis par le froid" -> "dégâts infligés par le froid"

2021-08-14 17:55 UTC, dimag0g commented on files/lang/fr.po
> +"double les dégâts subis par le feu."
"dégâts subis par le feu" -> "dégâts infligés par le feu"

2021-08-14 17:55 UTC, dimag0g commented on files/lang/fr.po
> +#~ msgstr "monde : interdire les Mois de PESTE"
Strings starting with `#~` are old translations for strings which no longer exist in the software. They are kept around in case they become useful again (e.g. if the editor is implemented), but in general they are not useful. Sorry to tell you this after you did the work. We should still accept your improvements of course.

2021-08-14 17:57 UTC, dimag0g commented
@1GodRage I just wanted to add I was impressed by the amount of work you did and the attention to details. Your improvements are a real blessing to the project!

2021-08-15 04:59 UTC, dimag0g commented
@1GodRage, In general, I agree with most of your suggestions in the first comment, with some exceptions listed below. Would you like to add them to this PR or start a new one?

1245 msgstr "Guide des mages niv. 1"
I shortened "magiciens" to "mages" to fit the level info (niv. 1) on the label. Do you suggest we drop it?

1590 "La tempête ajoute +2"
I suggest we keep the capital letter everywhere ("Tempête")

1596 "Le lieu saint"
Should be "Mausolée", it's actually the same name in French for "Mausoleum" and "Shrine". In the future, we might consider add context to this string, e.g. "building|Shrine", to distinguish it form the spell shrines found on the adventure map.

1928 "Victoire\n" "Conditions"
This is a sentence split in two lines, show in the adventure options screen. It should be "Conditions\n" "de Victoire" or something like this.

2831 msgstr "Les astrologues proclament le mois de %{name}."
5392 msgid "week|PLAGUE"
Good idea, we should move the preposition ("de") inside the name string to allow correct fusion with article ("de la" / "du").

3633 msgstr "Signe"
Should be "Panneau"

3286 msgid "%{object} robber"
This should be replaced by "%{object} robbed" in English (as in "Graveyard robbed", "Shipwreck robbed", etc.) and translated to
"%{object} cambriolé". Note "%{object}" must remain untranslated.

2478 "A multi-player game, with several human players completing against each "
"completing" -> "competing" in English.

3032 msgstr "Nécroman"
This is a shortened version of "Nécromancien" which fits on the interface.

5653 msgid "Stone Liths"
Simply called "Porte" in GoG version

5702 msgstr "Mandrake"
"Mandragore" (a sort of violet plant growing on the swamp)

7767 msgid "world: allow set guardian to objects"
This option allows you to cast "set guardian" spell to objects other than mines.
"monde: sort Gardien appliquable aux objets divers"

7796 msgid "castle: allow guardians" - I understand this is a setting which allows visiting heroes to take place of the castle guardian if the owner of the castle decides to recruit a hero of their own. @ihhub, perhaps the English string should be "castle: allow guardian heroes"?

2021-08-15 07:15 UTC, ihhub commented
Hi @dimag0g , we can change it but I can say these are **experimental** options which can be removed in the future.

2021-08-15 15:24 UTC, 1GodRage commented on files/lang/fr.po
> +msgstr "%{name} passe le tour"#if 2+ monster: "... passent ..."
ok: `msgstr "%{name} passent le tour" #if only 1 monster: "... passe ..."`
do I replace the fr.po by a new version with this change (and all others changes)? Or do we "validate" this fr.po and make the changes after that?

2021-08-15 15:26 UTC, ihhub commented on files/lang/fr.po
> +msgstr "%{name} passe le tour"#if 2+ monster: "... passent ..."
Hi @1GodRage, you can directly modify the file in this pull request if you agree with given comments. Don't worry about number of commits 🙂

2021-08-15 15:30 UTC, 1GodRage commented on files/lang/fr.po
> +msgstr "Voir seulement les grandes cartes (108x108)"
I removed the full stop "." to match the 2 others lines:
2096 msgstr "Voir seulement les cartes de petite taille (36x36)"
and
2101 msgstr "Voir seulement les cartes de taille moyenne (72x72)"
I thought that adding a "." was not necessary because this sentence has just 1 verb in dictionary form. But I could be wrong. I also thought the consistency was important, and shorter is better. (a bit afraid that this "." makes the whole "(108x108)." being a new line or so. ^^

2021-08-15 15:33 UTC, 1GodRage commented on files/lang/fr.po
> +""
I never saw the PoL called "Le Prix de la Loyauté" in french. I think most of french players kept it in English because "Heroes of Might and Magic" is also never translated into "Héros de Force et de Magie". @dimag0g 

Should I also remove the English empty text line? @ihhub 
2565 msgstr ""

2021-08-15 15:41 UTC, 1GodRage commented on files/lang/fr.po
> +msgstr "Pt. de magie"
We could also write it like that: `Pt de magie`, or even `Point magie`

2021-08-15 15:51 UTC, 1GodRage commented on files/lang/fr.po
> +"Les nains reconnaissent leurs alliés et se joignent volontiers à vos forces."
`alliés ... rallient` have the same etymology; one is `allied` the other one is `to become allied`. It sounds repetitive, and thus can confuse some players; in first part of the sentence they are friendly but not in your army, second sentence the same word means they are joining your army.
Also, `rallient vos forces` sounds funky. But as the GoG version: `rallient votre armée` sounds good. :)
If the condition is _having Dwarves in the army_, then we could say something like` Les nains reconnaissent les leurs, et souhaitent rallier votre armée.`

2021-08-15 15:57 UTC, 1GodRage commented on files/lang/fr.po
> +"Le Puits augme le taux de croissance de population de deux créatures par "
Mistake! `augmente` is the right word. Nice catch @dimag0g 
(Probably a Ctrl+Z that gone wrong. xD I reviewed the whole file in 2 days, I hope there isn't too many such kind of mistakes. xD)
Also, `le taux de croissance de la population` sounds better than `le taux de croissance de population`. Deal? :)

2021-08-15 16:00 UTC, 1GodRage commented on files/lang/fr.po
> +msgstr "Formation Déploiement"
There were 2 words: `Dispersée, Déploiement`, to make it consistent everywhere, I did pick the shorter word. :)
Déploiement sounds better, I'll make the modifications. :)

2021-08-15 16:15 UTC, 1GodRage commented on files/lang/fr.po
> +"%{skill} donne aux tirs de catapulte de votre héros plus de chances de "
I deleted the article (La/Le) for consistency with others lines, + the idea that maybe the `%{skill}` could change:
```
Les Principes de Ballistique
La Ballistique avancée
L'Expert Ballistique
```
But if the word is only the skill without the Advanced/Expert, then we could put the article before.

2021-08-15 16:22 UTC, 1GodRage commented on files/lang/fr.po
> +"des sorts de froid."
I would tend to prioritise words "infliger/inflige/infligent" for "Me deals damage to enemy" and words "subir/subit/subissent" for "Me or my troops get damaged by", to have a consistency into the vocabulary used in the game.
My opinion come from a basic-action point of view "Attack, Cast spell, Inflict" and obviously the word "subir" is when we get damaged.

But, we could also only stick to "infliger/inflige/infligent" regardless who does damage to whom. ;)

2021-08-15 16:33 UTC, 1GodRage commented on files/lang/fr.po
> +"double les dégâts subis par le froid."
I know the artefact, whatever the word I know what it does. But a new player reading `dégâts infligés par le froid` may think that it doubles the cold damage of its spells... instead of taking double damage.
I agree the sentence is not really beautiful, but I didn't got a better idea at that moment.
A good way is also to say "**dégâts de froid**" instead of "dégâts infligés par le froid". (Diablo 2 popularized this terminology, so we can use it and be sure that everybody will understand, at least, I saw that way of telling "cold damage" in many games since Diablo2 ^^')

My best bet is: `double les dégâts de froid infligés à vos troupes.`
(but we must add "à vos troupes" to make the description fit the effect of this artifact)

2021-08-15 16:34 UTC, 1GodRage commented on files/lang/fr.po
> +"double les dégâts subis par le feu."
what about: "double les dégâts de feu infligés à vos troupes."

2021-08-15 16:36 UTC, 1GodRage commented on files/lang/fr.po
> +#~ msgstr "monde : interdire les Mois de PESTE"
Honestly I thought there were no-more-used sentences pending for deletion/rehabilitation, and it was just few lines in the end of the file, I had fun with them. ;) No worries dimag0g. ;)

2021-08-15 17:28 UTC, 1GodRage commented on files/lang/fr.po
> +msgstr "%{name} passe le tour"#if 2+ monster: "... passent ..."
> Hi @1GodRage, you can directly modify the file in this pull request if you agree with given comments. Don't worry about the number of commits 🙂
OMG Thank you very much!! I totally missed this feature! :D It will be much less stressful to do edit the PR instead of local file. :)

2021-08-15 19:47 UTC, 1GodRage commented
> @1GodRage, In general, I agree with most of your suggestions in the first comment, with some exceptions listed below. Would you like to add them to this PR or start a new one?

Thank you, and sorry that some of my suggestions are written in French, I can translate them in English if needed. :) (But you seems to have a high understanding of French language @dimag0g :D)

I think it's better for me to stick in this PR: I just learnt that I can edit the PR. :D

> 1245 msgstr "Guide des mages niv. 1"
> I shortened "magiciens" to "mages" to fit the level info (niv. 1) on the label. Do you suggest we drop it?

"Guide" -> "Guilde"
In original french H2 also it was longer than the box.
On Archangel Castle (French HoMM community) everybody understood that "GdM" meant "Guilde des Magiciens".
For me, Magicien = any magic user (the name literraly means Magic-user). Mage = maybe dark magic user, maybe something else.
in Heroes2, Mage is the Warlock... Magicien is the Wizard.
So, it's "normal" that this building is related to the Wizards, because they have the Library, a building that boosts the "Guilde des Magiciens".
My suggestion is: `G. des Magiciens niv. 1`
Other suggestion: `Guilde des M. niv. 1`


> 1590 "La tempête ajoute +2"
> I suggest we keep the capital letter everywhere ("Tempête")

So, capital letter for all the "specific names (buildings/items/spells/etc.)"?
It will need a full relecture.


> 1596 "Le lieu saint"
> Should be "Mausolée", it's actually the same name in French for "Mausoleum" and "Shrine". In the future, we might consider add context to this string, e.g. "building|Shrine", to distinguish it form the spell shrines found on the adventure map.

This specific building was a problem in original French H2 too: it was "Mausolée", but the building of the Lich is also "Mausolée".
Shrine "Sanctuaire" is also the adventure-map building for spells.
I would suggest to even find a new name. "Cénotaphe" could fit.

> 1928 "Victoire\n" "Conditions"
> This is a sentence split in two lines, show in the adventure options screen. It should be "Conditions\n" "de Victoire" or something like this.

Ok, done.

> 2831 msgstr "Les astrologues proclament le mois de %{name}."
> 5392 msgid "week|PLAGUE"
> Good idea, we should move the preposition ("de") inside the name string to allow correct fusion with article ("de la" / "du").

Ok, do I do it soon, or need to wait (extra programmation needed)?

> 3633 msgstr "Signe"
> Should be "Panneau"

Ok, done.

> 3286 msgid "%{object} robber"
> This should be replaced by "%{object} robbed" in English (as in "Graveyard robbed", "Shipwreck robbed", etc.) and translated to
> "%{object} cambriolé". Note "%{object}" must remain untranslated.

Ok, done. But I really want to add "déjà": "déjà cambriolé", as for "already visited" is "déjà visité". Without "déjà", it sounds as an adjective, and thus seems to be the part of the name.

> 2478 "A multi-player game, with several human players completing against each "
> "completing" -> "competing" in English.

Ok, done.

> 3032 msgstr "Nécroman"
> This is a shortened version of "Nécromancien" which fits on the interface.

In french there is "Nécromancien" and also "Nécromant" (same meaning). Often shortened as "Nécro" by any player in any game.
Cutting the word in the middle of a syllab sounds not good.
Good Suggestion: Nécromant (if lenght fit)
Bad Suggestion: Nécro.

> 5653 msgid "Stone Liths"
> Simply called "Porte" in GoG version

Original French version also called it "Porte".
-> Ok, done.
But I recall some others HoMM using few others words:
Monolith (Monolithe in french)
Menhir
Dolmen

> 5702 msgstr "Mandrake"
> "Mandragore" (a sort of violet plant growing on the swamp)

Ok, done.

> 7767 msgid "world: allow set guardian to objects"
> This option allows you to cast "set guardian" spell to objects other than mines.
> "monde: sort Gardien appliquable aux objets divers"

Ok, done: `monde : sort Gardien applicable aux objets divers`

> 7796 msgid "castle: allow guardians" - I understand this is a setting which allows visiting heroes to take place of the castle guardian if the owner of the castle decides to recruit a hero of their own. @ihhub, perhaps the English string should be "castle: allow guardian heroes"?

Ok, done: `"château : les Héros peuvent remplacer le Capitaine"`

Maybe I can suggest that "unions :" should be "Alliances :". It's a longer word but... I never saw "union" in the game.. Just in the description of 1 or 2 maps.


There is also the texts for the campaigns... They are long, there is corrections to do (But playing the campaign is needed to be sure that the texts is meaningful), and... I think it could be a good idea to have the campaigns in a separate file, to ease for translations and maybe to future customisation/moddings?

Should I also apply the suggestions that I made in the first (long & half-french) comment?
I would prefer you tell me wich one I should apply. :)

for the makefile:
Î -> I
î -> i
(used for "îles", meaning "islands", and so, can be a needed word in many maps)


> @1GodRage I just wanted to add I was impressed by the amount of work you did and the attention to details. Your improvements are a real blessing to the project!

Thank you very much :)

2021-08-16 06:35 UTC, dimag0g commented on files/lang/fr.po
> +msgstr "Formation Déploiement"
Please do the replacement Déploiement => Dispersée then.

2021-08-16 06:37 UTC, dimag0g commented on files/lang/fr.po
> +""
My bad, I thought I saw "Le Prix de la Loyauté" somewhere and mistakenly decided it was an official name.

2021-08-16 06:39 UTC, dimag0g commented on files/lang/fr.po
> +msgstr "Pt. de magie"
Unless there is a real constraint in dialog size, I would prefer to keep the translation you have suggested initially. Perhaps we can already apply it to the translation file and deal with dialog size (or translation shortening) in a separate PR.

2021-08-16 06:42 UTC, dimag0g commented on files/lang/fr.po
> +"des sorts de froid."
My concern is that the double "par" preposition makes it ambiguous who took the damage: the troops, or the spell.

2021-08-16 06:46 UTC, dimag0g commented on files/lang/fr.po
> +"double les dégâts subis par le froid."
Again, my understanding of the French language makes me interpret "dégâts subis par le froid" as "damage taken by the cold", not "damage inflicted by the cold". But then, I'm not a native speaker. "double les dégâts de froid" sounds good, could we do it the Diablo way then?

2021-08-16 06:47 UTC, dimag0g commented on files/lang/fr.po
> +"double les dégâts subis par le feu."
This also sounds good to me, or we could do it the Diablo way as well.

2021-08-16 07:00 UTC, dimag0g commented
@1GodRage

"Guilde des M. niv. 1" sounds good to me

"Cénotaphe" is nice, but let's stick to the original game and translate both as "Mausolée"

"Nécroman" is already a tad too [large](https://user-images.githubusercontent.com/10945319/129523290-aa37cb35-153c-4de5-9055-f42b39710bdd.png), "Nécromant" certainly wouldn't fit. Let's leave "Nécroman", the GoG guys didn't find a better solution and I don't think we will.

msgstr "Les astrologues proclament le mois %{name}."
and
msgstr "de la PESTE"
should work without any extra programming

"Monolith" is IMO OK if you don't like "Porte".

"unions:" indeed should be "alliances :"

2021-08-16 10:21 UTC, 1GodRage commented on files/lang/fr.po
> +""
I see 3 cases where it would be in translated:automatic translation, Québec player may translate it, games related website not being familiar with HoMM mais translate randomly some titles.

2021-08-16 10:24 UTC, 1GodRage commented on files/lang/fr.po
> +msgstr "Pt. de magie"
So, I let `Pt. de magie` for the moment?

2021-08-16 10:30 UTC, 1GodRage commented on files/lang/fr.po
> +"double les dégâts subis par le froid."
I see, and I understand, both "readings" are possible... and usually it would be taken as you said... But for me, it's the same problem as "damage inflicted by the cold".
Diablo way is the way :D

2021-08-16 10:45 UTC, 1GodRage commented on files/lang/fr.po
> +"des sorts de froid."
Diablo way solved the double "par". :)

2021-08-16 10:53 UTC, 1GodRage commented on files/lang/fr.po
> +"double les dégâts subis par le feu."
Do we really replace "subis/taken" by "infligé/inflicted" everywhere?
subis -> infligés?
Right now the sentence in the PR is: `double les dégâts de feu infligés à vos troupes`
if we keep "taken/subis": `double les dégâts de feu subis par vos troupes`

2021-08-16 13:12 UTC, 1GodRage commented
There is a commonly used way to shorten words, deleting last voyels: "Nécromnt" (do the "t" takes less space than the "a"?..)
But I agree, let's keep "Nécroman", it's even this exact [word in the original H2](https://user-images.githubusercontent.com/63362446/129555319-981ee91d-d6a8-4b44-b0a8-b7614f62e54f.png). 🤣 

> msgstr "Les astrologues proclament le mois %{name}."
> and
> msgstr "de la PESTE"
> should work without any extra programming

Changes done. I am wondering about unicorn/wolfes/any other creature week's.
is there somewhere an "of the unicorn" stored?
Cause right now it would turn into "Les astrologues proclament la semaine Licorne." instead of "... semaine **de la** licorne."
A "fast" way to fix it would be to says that if it's a creature of the game, "... semaine **des** licornes." but the meaning change a little... (This sentence look-likes the unicorns will stay only this week on the adventure map. xD)

> "Monolith" is IMO OK if you don't like "Porte".

We'll keep "Porte" because both original H2 and GoG H2 call them "Porte".
But, "Porte" (= door) is only 1 of the 3 types of "dimensional passage". :p If someday we can have a specific name for each type of "Porte"... I'll remember. ;)

I start to implement the "good" suggestions I made in my first message, and forget any "bad" suggestion I made. 🤣 And thus:
There is some lines in the style of:
"%{spell} fait %{value} dégât(s) à un mort-vivant."
Would it be possible that a spell inflict only 1 point of damage?
If it's impossible, I suggest: "%{spell} inflige %{value} dégâts à un mort-vivant."
_(maybe it will be possible with later versions 1.x?)_

"Archmagi" was "Grand mage" in the French original H2. But "Archi-mage" sounds more used in recent years than in 1996. :D What name to stick with?

2021-08-17 05:24 UTC, dimag0g commented
@1GodRage, "I am wondering about unicorn/wolfes/any other creature week"
Bummer, I forgot about these. I guess there is no fix that would work 100% in French.

2021-08-18 14:56 UTC, ihhub commented on files/lang/fr.po
> -"Type de jeu de fichier non valide. Assurez-vous que vous avez le dernier "
We can rephrase it for sure but let's do it outside this pull request.

2021-08-18 14:57 UTC, ihhub commented on files/lang/fr.po
> +""
I have no idea why English has this empty line. It makes no sense. I've checked other translations, they don't have it so please go ahead and remove.

2021-08-18 14:58 UTC, ihhub commented on files/lang/fr.po
> +"Joueur %{color}, il ne vous reste que %{day} jours pour capturer un village, "
You're right. Let's do it in a separate pull request.

2021-08-18 15:00 UTC, ihhub commented on files/lang/fr.po
> +"Cette fenêtre fournit des informations sur le statut de votre héros et "
This window allows to see hero and date or kingdom and date, not all 3 at the same time so the description some kind of correct.

2021-08-18 15:01 UTC, ihhub commented on files/lang/fr.po
> +msgstr "Pt. de magie"
We can't change right now this dialog so we have to go with the shorter form.

2021-08-18 15:06 UTC, ihhub commented
Hi @1GodRage and @dimag0g , I left few comments here and answers for your questions. Could you please take a look? If we don't have much more changes to do we can proceed with merging them.

2021-08-18 18:56 UTC, 1GodRage commented on files/lang/fr.po
> +"Cette fenêtre fournit des informations sur le statut de votre héros et "
Depending the screen-size, maybe not all 3 at the same time, but, all 3 yes.
On my screen it's all 3 at the same time:
![image](https://user-images.githubusercontent.com/63362446/129955767-8a2de378-c72b-4aff-98f5-59bf612f91f7.png)

2021-08-18 19:21 UTC, 1GodRage commented
> Hi @1GodRage and @dimag0g , I left few comments here and answers for your questions. Could you please take a look? If we don't have much more changes to do we can proceed with merging them.

Viewed and made the changes. :)


The lasts few points to discuss/decide about, in order to finish this translation:

**subis -> infligés**
Do we really replace "subis (taken)" by "infligé (inflicted)" everywhere?
I don't think it's an improvement.

**"Archmagi"** was "Grand mage" in the French original H2. But "Archi-mage" sounds more used in recent years than in 1996. :D What name to stick with? (My opinion is to stick with original H2: "Grand mage")

**Campaigns texts**: full review needed... A job for me or another french player... later. ^^
Replace i -> î in the "makefile" is needed.

**...the week of the...**
"Astrologers proclaim Week of the %{name}."
FR: "proclament la Semaine %{name}." -> need to add: "de le/de la/du" depending on which creature it is.

2021-08-19 15:45 UTC, ihhub commented
Hi @1GodRage , if you're okay that we make other proposed changes in a separate pull request then I can merge changes of this one.

2021-08-19 18:54 UTC, 1GodRage commented
> Hi @1GodRage , if you're okay that we make other proposed changes in a separate pull request then I can merge changes of this one.

Ok :)

2021-08-20 00:42 UTC, merged

2021-08-20 00:42 UTC, ihhub commented
@1GodRage , thank you so much for your contribution to the project!