Finish idle animation during battle action
ihhub/fheroes2 pull request #4008
Opened 2021-08-12 17:22 UTC by vasilenkoalexey

Finish idle animation during battle action.  fix #1229

2021-08-14 14:33 UTC, ihhub requested changes
Hi @vasilenkoalexey , I left multiple comments here. Would you mind to take a look at them? Also please verify my idea that monsters on which a spell is applied are still moving.

2021-08-14 14:33 UTC, ihhub commented on src/fheroes2/battle/battle_army.h
> +        bool animateIdleUnits( const bool restart = true );
Please do not use default values for input arguments. Could we please remove it?

2021-08-14 14:33 UTC, ihhub commented on src/fheroes2/battle/battle_army.h
> +        bool animateIdleUnits( const bool restart = true );
Also could we please name this input argument something like `forceRestartIdleAnimation` to be more specific about the purpose of this variable?

2021-08-14 14:33 UTC, ihhub commented on src/fheroes2/battle/battle_interface.h
> +        bool IdleTroopsAnimation( const bool restart = true );
The same comment here: could we please avoid default parameters for input arguments?

2021-08-14 14:33 UTC, ihhub commented on src/fheroes2/battle/battle_interface.h
> +        bool IdleTroopsAnimation( const bool restart = true );
And also could we please make the variable more specifically as right now it's unknown what we want to restart.

2021-08-14 14:33 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        else if ( redrawNeeded ) {
We don't need to create another variable which is used only in one place. We can directly call the method here. Also it'll be faster since we won't call the method if the above condition is true. This applies for all cases in these changes.

2021-08-14 14:33 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +            Redraw();
Could you please check how it will look during a spell casting? I think the monster might be moving being stoned at the same time which is not allowed to be.

2021-08-14 21:33 UTC, vasilenkoalexey commented on src/fheroes2/battle/battle_interface.cpp
> +        else if ( redrawNeeded ) {
Let me explain...
I tried to cover case when we should draw both idle and battle animation, 
```
 while ( le.HandleEvents() && currentAlpha < 220 ) {
        CheckGlobalEvents( le );

        const bool redrawNeeded = IdleTroopsAnimation( false );

        if ( Game::validateAnimationDelay( Game::BATTLE_SPELL_DELAY ) ) {
            currentAlpha += 20;
            target.SetCustomAlpha( currentAlpha );
            Redraw();
        }
        else if ( redrawNeeded ) {
            Redraw();
        }
    }
```
In this case we call Redraw() once

But for this implementation
```
 while ( le.HandleEvents() && currentAlpha < 220 ) {
        CheckGlobalEvents( le );

        if ( Game::validateAnimationDelay( Game::BATTLE_SPELL_DELAY ) ) {
            currentAlpha += 20;
            target.SetCustomAlpha( currentAlpha );
            Redraw();
        }
        if ( IdleTroopsAnimation( false ) ) {
            Redraw();
        }
    }
```
we call Redraw()  twice, 
So, i dont see another simple implementation without additional var.

But if you think this has little performance impact, I will fix

2021-08-14 23:19 UTC, vasilenkoalexey commented on src/fheroes2/battle/battle_interface.cpp
> +            Redraw();
Here we animate idle
```
bool Battle::Force::animateIdleUnits( const bool forceRestartIdleAnimation )
{
    bool redrawNeeded = false;

    for ( Force::iterator it = begin(); it != end(); ++it ) {
        Unit & unit = **it;

        // check if alive and not paralyzed
        if ( unit.isValid() && !unit.Modes( SP_BLIND | IS_PARALYZE_MAGIC ) ) {
            if ( unit.isIdling() ) {
                if ( unit.isFinishAnimFrame() ) {
                    redrawNeeded = unit.SwitchAnimation( Monster_Info::STATIC ) || redrawNeeded;
                }
                else {
                    unit.IncreaseAnimFrame();
                    redrawNeeded = true;
                }
            }
```
and
```
        SP_PARALYZE = 0x40000000,
        SP_STONE = 0x80000000,

        IS_PARALYZE_MAGIC = 0xC0000000,
```
And `IS_PARALYZE_MAGIC` looks like `SP_PARALYZE | SP_STONE`. So, all should be fine.
We can replace it for example by IS_FROZEN = SP_BLIND | SP_SP_PARALYZE | SP_STONE or leave it as it is :)

2021-08-15 10:57 UTC, vasilenkoalexey commented on src/fheroes2/battle/battle_interface.cpp
> +            Redraw();
But spell applied after redraw. I think then we should switch animation to STATIC for all targets before redrawing.

```
    if ( interface ) {
        interface->RedrawActionSpellCastPart1( spell, dst, current_commander, targets );
        for ( const TargetInfo & target : resistTargets ) {
            interface->RedrawActionResistSpell( *target.defender, playResistSound );
        }
    }

    TargetsApplySpell( current_commander, spell, targets );
```

2021-08-15 11:41 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        else if ( redrawNeeded ) {
I suggested to make
```cpp
else if ( IdleTroopsAnimation( false ) ) {
    Redraw();
}
```

2021-08-15 11:42 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        else if ( redrawNeeded ) {
Besides this please verify that idle animation won't change its speed while we're drawing a spell with **different** speed.

2021-08-15 12:47 UTC, vasilenkoalexey commented on src/fheroes2/battle/battle_interface.cpp
> +        else if ( redrawNeeded ) {
> I suggested to make

Ok, done.

> Besides this please verify that idle animation won't change its speed while we're drawing a spell with **different** speed.

Should be ok, since we do not affect the change of idle frames.

2021-08-15 12:49 UTC, vasilenkoalexey commented on src/fheroes2/battle/battle_interface.cpp
> +            Redraw();
> Could you please check how it will look during a spell casting?

I switch all spell targets to STATIC before redrawing.

2021-08-15 12:58 UTC, vasilenkoalexey commented on src/fheroes2/battle/battle_army.h
> +        bool animateIdleUnits( const bool restart = true );
Done

2021-08-22 13:33 UTC, Branikolog commented
Everything seems to work well.

2021-09-02 12:51 UTC, ihhub commented
Hi @vasilenkoalexey , please try to apply a Resurrect spell on a unit which neighbors a unit with idling animation. The spell is flicking. For example in this scenario I was applying the spell on Titans when Bone Dragons were having idling animation:
![image](https://user-images.githubusercontent.com/19829520/131846473-51f9f547-b2f8-4688-ade5-3fee0ac52f54.png)

2021-11-07 07:39 UTC, ihhub commented
Hi @vasilenkoalexey , shall we rework this pull request as we made significant changes in this part of the code?

2022-09-07 19:07 UTC, closed without merging