Update game_highscores.cpp
ihhub/fheroes2 pull request #4058
Opened 2021-08-21 21:47 UTC by Arthusppp

Monster sprite added to the High Scores. Fixes #954.

Hello! My first real commit. Please be kind to a newbie programmer like me ;) 

What I have fixed: I have added a monster to the High Scores dialog. See my example below:
![7AzZ774HdO](https://user-images.githubusercontent.com/85434237/130335427-a18f7d96-e0b6-4456-8250-30422b25aae2.gif)

My (zipped) test high score file: 
[fheroes2.hgs.zip](https://github.com/ihhub/fheroes2/files/7026235/fheroes2.hgs.zip)

The issues/questions I have:
1. the monsterAnimationSequence variable is the same as in map_tiles.cpp:67. How to share it elegantly?
2. is there any better way to handle the "rating to monster" relationship?
3. I do not know if I handled the Redraw part correctly. I was trying to reuse map_tiles as much as possible, but... pls let me know.

2021-08-22 02:38 UTC, ihhub requested changes
Hi @Arthusppp , I left multiple comments here. Would you mind to take a look?

2021-08-22 02:38 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +                                                                 /*7*/ Monster::GOBLIN,
Do we need these comments with numbers?

2021-08-22 02:38 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +    return monster;
We could directly return from the function as `return Monster( rating2monster[rating] );`. No need to create a temporary variable for this.

2021-08-22 02:38 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +            ++frame;
Let's not use reference to World Map animation. We can have an internal counter within `HGSData` class and increment it within `RedrawList` method.

2021-08-22 02:38 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +    Monster GetMonsterByRating( u32 rating );
Please put this method at the top of private section with separation by an empty line from class members. Also use `uint32_t` instead of **u32**. Since this method does nothing to class it should be **static** with signature:
```
static Monster getMonsterByRating( const uint32_t rating );
```
Notice that the first letter is non-capital.

2021-08-22 02:38 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +    const std::array<uint8_t, 15> monsterAnimationSequence = { 0, 0, 1, 2, 1, 0, 0, 0, 3, 4, 5, 4, 3, 0, 0 };
This is a duplication code from `maps_tiles.cpp`. Please create a separate function in monster_anim.h and monster_anim.cpp classes under fheroes2 namespace to return a const reference to the same container. This container should be located in anonymous (with no name) namespace at the beginning of monster_anim.cpp file. Then here and in maps_tile.cpp use newly created function.

2021-08-22 02:38 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +        /*+hgs.days+ox+oy - to start from "random" animation frame when a monster occurs more than once in the high score list*/
Please use single line comment.

2021-08-22 02:38 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +        uint32_t spriteIndex = monster.GetSpriteIndex() * 9;
These variables can be const.

2021-08-22 02:38 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +              + monsterAnimationSequence[( static_cast<unsigned long long>( hgs.days ) + ox + oy + Game::MapsAnimationFrame() ) % monsterAnimationSequence.size()];
This variable can be const.

2021-08-22 02:38 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +              + monsterAnimationSequence[( static_cast<unsigned long long>( hgs.days ) + ox + oy + Game::MapsAnimationFrame() ) % monsterAnimationSequence.size()];
Why do we convert `hgs.days` into **unsigned long long**?

2021-08-22 02:38 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +#include "bin_info.h"
Do we need this file inclusion?

2021-08-22 09:46 UTC, LeHerosInconnu commented
Hello @Arthusppp and @ihhub,

Would it be possible to adjust the position of the elements in these screens (at least the horizontal and vertical position of the creature sprites in this PR).

In original game:

![High scores 20](https://user-images.githubusercontent.com/43583994/130350267-2eeb90ba-9ddd-4257-baac-2f105b38f529.png)

![High scores 21](https://user-images.githubusercontent.com/43583994/130350273-8b723f9c-934d-488b-87cc-5a303cbe0e0a.png)

2021-08-22 13:28 UTC, qarkai commented on src/fheroes2/game/game_highscores.cpp
> +    return monster;
Or even `return { rating2monster[rating] };`

2021-08-22 13:28 UTC, qarkai commented on src/fheroes2/game/game_highscores.cpp
> +        rating = 228;
Please don't use magic numbers. It's `rating2monster.size() - 1`. Moreover to avoid duplicating it could be written as `rating = std::min(rating, rating2monster.size() - 1);`.

2021-08-23 04:41 UTC, Arthusppp commented on src/fheroes2/game/game_highscores.cpp
> +              + monsterAnimationSequence[( static_cast<unsigned long long>( hgs.days ) + ox + oy + Game::MapsAnimationFrame() ) % monsterAnimationSequence.size()];
If not, then my Visual says:

> Warning	C26451	Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2)

How I should handle it? Should I ignore this warning?
Or maybe sth like:

> + monsterAnimationSequence[( (size_t)ox + oy + hgs.days + Game::MapsAnimationFrame() ) % monsterAnimationSequence.size()];

2021-08-23 23:49 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +              + monsterAnimationSequence[( static_cast<unsigned long long>( hgs.days ) + ox + oy + Game::MapsAnimationFrame() ) % monsterAnimationSequence.size()];
Yes, please ignore it for now. It's not a compilation warning after all.

2021-08-24 19:42 UTC, Arthusppp commented on src/fheroes2/game/game_highscores.cpp
> +                                                                 /*7*/ Monster::GOBLIN,
No we dont. Removed.

2021-08-24 19:43 UTC, Arthusppp commented on src/fheroes2/game/game_highscores.cpp
> +    return monster;
Many thanks for this! Implemented with this:

`return Monster( rating2monster[std::min( rating, rating2monster.size() - 1 )] );`

2021-08-24 19:45 UTC, Arthusppp commented on src/fheroes2/game/game_highscores.cpp
> +            ++frame;
No problem :) I "have copied" the World Map animation algorithm. Please take a look and let me know.

2021-08-24 19:49 UTC, Arthusppp commented on src/fheroes2/game/game_highscores.cpp
> +    Monster GetMonsterByRating( u32 rating );
I have changed to size_t as the std::min claims that uint32_t (and most probably u32 as well) is "_template parameter _Ty is ambiguous_". What I try to achieve here is:

`return Monster( rating2monster[std::min( rating, rating2monster.size() - 1 )] );`

Please let me know whether this is good approach or not.

2021-08-24 19:50 UTC, Arthusppp commented on src/fheroes2/game/game_highscores.cpp
> +    const std::array<uint8_t, 15> monsterAnimationSequence = { 0, 0, 1, 2, 1, 0, 0, 0, 3, 4, 5, 4, 3, 0, 0 };
Done as described above.

2021-08-24 19:50 UTC, Arthusppp commented on src/fheroes2/game/game_highscores.cpp
> +        /*+hgs.days+ox+oy - to start from "random" animation frame when a monster occurs more than once in the high score list*/
Done.

2021-08-24 19:51 UTC, Arthusppp commented on src/fheroes2/game/game_highscores.cpp
> +        uint32_t spriteIndex = monster.GetSpriteIndex() * 9;
Done. I believe I have changed all variables like this to be const.

2021-08-24 19:51 UTC, Arthusppp commented on src/fheroes2/game/game_highscores.cpp
> +              + monsterAnimationSequence[( static_cast<unsigned long long>( hgs.days ) + ox + oy + Game::MapsAnimationFrame() ) % monsterAnimationSequence.size()];
Done.

2021-08-24 19:52 UTC, Arthusppp commented on src/fheroes2/game/game_highscores.cpp
> +              + monsterAnimationSequence[( static_cast<unsigned long long>( hgs.days ) + ox + oy + Game::MapsAnimationFrame() ) % monsterAnimationSequence.size()];
Ok, ignored and removed "static_cast" part.

2021-08-24 19:52 UTC, Arthusppp commented on src/fheroes2/game/game_highscores.cpp
> +#include "bin_info.h"
No, we do not this in the current implementation. Removed.

2021-08-24 19:53 UTC, Arthusppp commented on src/fheroes2/game/game_highscores.cpp
> +        rating = 228;
Many thanks for this. I have implemented the following:

`return Monster( rating2monster[std::min( rating, rating2monster.size() - 1 )] );`

2021-08-25 15:17 UTC, ihhub commented
Hi @Arthusppp  and @LeHerosInconnu , let fix the alignment of elements in a separate pull request to simplify the changes here.

2021-08-25 15:28 UTC, ihhub requested changes
Hi @Arthusppp , here are multiple comments left. Would you mind to take a look?

2021-08-25 15:28 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +        if ( hgs.validateAnimationDelay() ) {
Why can't we use `Game::validateAnimationDelay( Game::MAPS_DELAY )` without introducing duplicated code?

2021-08-25 15:28 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +    u32 hgs_animation_frame = 0;
I think we should remove this code based on suggestion about **validateAnimationDelay** call.

2021-08-25 15:28 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +}
I think we should remove this code based on suggestion about **validateAnimationDelay** call.

2021-08-25 15:28 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.cpp
> +        const std::array<uint8_t, 15> monsterAnimationSequence = fheroes2::MonsterAnimationSequence();
Please use const reference to avoid object copy.

2021-08-25 15:28 UTC, ihhub commented on src/fheroes2/monster/monster_anim.cpp
> +    std::array<uint8_t, 15> MonsterAnimationSequence()
This function must return const reference.

2021-08-25 15:28 UTC, ihhub commented on src/fheroes2/monster/monster_anim.cpp
> +    std::array<uint8_t, 15> MonsterAnimationSequence()
Please rename it into `getMonsterAnimationSequence` to be even more easy to understand :)

2021-08-25 15:28 UTC, ihhub commented on src/fheroes2/monster/monster_anim.cpp
> +    const std::array<uint8_t, 15> monsterAnimationSequence = { 0, 0, 1, 2, 1, 0, 0, 0, 3, 4, 5, 4, 3, 0, 0 };
Please put this variable in unnamed namespace at the top of this file after header inclusions.

2021-08-25 15:28 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +        const Monster monster = HGSData::getMonsterByRatingStandardGame( hgs.rating );
We're constructing `const std::array<Monster::monster_t, 229> rating2monster` multiple times (even on stack memory). Why can't we do this before the loop and then just put the logic from the method here?

2021-08-25 15:28 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +        text.Blit( ox + 79 + 405, oy + 70 );
Please combine all numbers. They're all magic numbers so no point to separate them even knowing the compiler will optimize the code.

2021-09-02 00:31 UTC, merged

2021-09-02 00:31 UTC, ihhub commented
@Arthusppp , thank you so much for this feature!