Fixes #3996
ihhub/fheroes2 pull request #4072
Opened 2021-08-23 12:25 UTC by vincent-grosbois

2021-08-23 14:11 UTC, oleg-derevenetz requested changes
Hi @vincent-grosbois I left a few comments here, would you mind to take a look?

2021-08-23 14:11 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_arena.cpp
> +size_t UpdateRandomSeed( const size_t seed, const Battle::Actions & actions )
I suppose it's better to create an anonymous namespace in the beginning of the source file and move it here (along with `GetCovr()`) may be.

2021-08-23 14:11 UTC, oleg-derevenetz commented on src/engine/rand.h
> +    class BattleRandomGenerator
`Engine` contains some generic classes and functions, not bound to the game logic itself. Since this random generator may be used not only in a battle, may be rename it in a more generic way - `DeterministicRandomGenerator` may be?

2021-08-23 21:51 UTC, vincent-grosbois commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +        assert( _randomGenerator );
This pointer will outlive the arena, but it can only ever be re-entered via this method, so it's going to be re-set to a correct value on the next battle. It's the same thing that is happening for _commander member, where it's also dangling.

I think the correct fix for this would be a refactor of this class (create a new instance for each battle) rather than fixing this specific member

2021-08-24 09:13 UTC, oleg-derevenetz approved these changes

2021-08-25 08:42 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_arena.cpp
>          catapult = army1->GetCommander() ? new Catapult( *army1->GetCommander() ) : nullptr;
@vincent-grosbois BTW catapult probably needs your random generator too.

2021-08-25 09:21 UTC, vincent-grosbois commented
Youre right!

Envoyé de mon iPhone

> Le 25 août 2021 à 10:42, Oleg Derevenetz ***@***.***> a écrit :
> 
> ﻿
> @oleg-derevenetz commented on this pull request.
> 
> In src/fheroes2/battle/battle_arena.cpp:
> 
> > @@ -211,9 +234,9 @@ Battle::Arena::Arena( Army & a1, Army & a2, s32 index, bool local )
>  
>      if ( castle ) {
>          // init
> -        towers[0] = castle->isBuild( BUILD_LEFTTURRET ) ? new Tower( *castle, TWR_LEFT ) : nullptr;
> -        towers[1] = new Tower( *castle, TWR_CENTER );
> -        towers[2] = castle->isBuild( BUILD_RIGHTTURRET ) ? new Tower( *castle, TWR_RIGHT ) : nullptr;
> +        towers[0] = castle->isBuild( BUILD_LEFTTURRET ) ? new Tower( *castle, TWR_LEFT, _randomGenerator ) : nullptr;
> +        towers[1] = new Tower( *castle, TWR_CENTER, _randomGenerator );
> +        towers[2] = castle->isBuild( BUILD_RIGHTTURRET ) ? new Tower( *castle, TWR_RIGHT, _randomGenerator ) : nullptr;
>          const bool fortification = ( Race::KNGT == castle->GetRace() ) && castle->isBuild( BUILD_SPEC );
>          catapult = army1->GetCommander() ? new Catapult( *army1->GetCommander() ) : nullptr;
> @vincent-grosbois BTW catapult probably needs your random generator too.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-08-25 14:10 UTC, oleg-derevenetz commented
@vincent-grosbois How about making this deterministic combat optional (I mean, instant combat should still be replayed as is, but allow each specific battle to take place in its own way)? In other words, an option to not derive initial seed from map cell index and world's map seed?

2021-08-25 14:51 UTC, ihhub reviewed
Hi @vincent-grosbois , good job! I left just few comments here. Would you mind to take a look?

2021-08-25 14:51 UTC, ihhub commented on src/engine/rand.h
> +        DeterministicRandomGenerator & operator=( const DeterministicRandomGenerator & ) = delete;
Could we please add deleted destructor to please clang-tidy?

2021-08-25 14:51 UTC, ihhub commented on src/engine/rand.cpp
> +}
Absolutely optional: we could put the body of these methods inside header making them inline methods.

2021-08-25 14:51 UTC, ihhub commented on src/fheroes2/battle/battle_arena.cpp
> +    army1 = new Force( a1, false, _randomGenerator );
Hi @oleg-derevenetz , should we shut this warning too?

2021-08-25 14:51 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +        assert( _randomGenerator );
Can we please just add a TODO comment for the future refactoring but not to do this in the current pull request?

2021-08-25 14:51 UTC, ihhub commented on src/engine/rand.h
> +        uint32_t Get( uint32_t from, uint32_t to = 0 ) const;
These input arguments could be `const`.

2021-08-25 14:51 UTC, ihhub commented on src/fheroes2/battle/battle_army.h
> +#include "rand.h"
Here we can go with forward declaration while putting the header into the source file.

2021-08-25 14:51 UTC, ihhub commented on src/fheroes2/battle/battle_troop.h
> +#include "rand.h"
Here we can go with forward declaration while putting the header into the source file.

2021-08-25 14:55 UTC, oleg-derevenetz commented on src/engine/rand.h
> +        DeterministicRandomGenerator & operator=( const DeterministicRandomGenerator & ) = delete;
Defaulted destructor you mean? :) I don't think that deleted destructor would be useful here.

2021-08-25 14:56 UTC, ihhub commented on src/engine/rand.h
> +        DeterministicRandomGenerator & operator=( const DeterministicRandomGenerator & ) = delete;
Oh, my bad. I have more sleep. You're absolutely right.

2021-08-25 16:20 UTC, vincent-grosbois commented
> @vincent-grosbois How about making this deterministic combat optional (I mean, instant combat should still be replayed as is, but allow each specific battle to take place in its own way)? In other words, an option to not derive initial seed from map cell index and world map seed?

why not but how do you want to do it? with a config option?

2021-08-30 13:00 UTC, merged

2021-08-30 13:00 UTC, ihhub commented
@vincent-grosbois , thank you so much for this change!