Display message about Ultimate Artifact after the battle
ihhub/fheroes2 pull request #4106
Opened 2021-08-28 18:52 UTC by a1exsh

Fix #1511

The capture of human player's ultimate artifact is harder to handle, because it happens in a different place in the code: https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/battle/battle_main.cpp#L238-L257

This logic is duplicated in the dialog code that this PR changes, but there it is interleaved with display code...

2021-08-30 06:32 UTC, a1exsh commented on src/fheroes2/battle/battle_dialogs.cpp
> +        std::sort( sortedBag2.begin(), sortedBag2.end(),
We need to at least use `std::stable_sort` here, or better don't have the logic in two places.  Will check what can be done about that.

2021-08-30 08:05 UTC, a1exsh commented
Added handling of computer trying to capture an ultimate artifact:
![image](https://user-images.githubusercontent.com/489601/131302356-993510b5-42ea-4139-9d7b-470a21186172.png)

In the end, the logic is still in two places, but the dialog treats the artifact bags as "read-only".  This could be further extracted into a single place, but requires more effort than I can spend right now.

2021-08-31 16:41 UTC, a1exsh commented
> This could be further extracted into a single place, but requires more effort than I can spend right now.

I have an idea.  We could separate the logic into two functions:
1. Calculate anticipated artifact transfer after the battle, without actually modifying anything.
2. If a human player was involved in the battle, the battle summary dialog is shown where the artifact transfer is only displayed, but not yet executed.
3. Ultimately (he-he), the transfer is executed, regardless if a human player is involved, based on the data calculated in the first step.

The requried data structure can be as simple as a list of `(src, dst)` iterator pairs.

What do you think?

2021-08-31 18:42 UTC, a1exsh commented
Implementation looks like this: https://github.com/ihhub/fheroes2/pull/4106/commits/46eb6890333d05c1def9139450170fbdfd35d87a

I'm also noticing an opportunity to make the code in `Battle::Loader()` significantly shorter by using a `do { ... } while ()`.  Should I try to do that in this PR or better a separate one? :)

2021-08-31 18:44 UTC, a1exsh commented on src/fheroes2/battle/battle_main.cpp
> +        // FIXME: abstraction leak
Not sure what to do about this one.  We need to signal "no slot" on the left (winner) side somehow, but that's not possible with generic iterators, I guess.

2021-09-02 10:20 UTC, ihhub requested changes
Hi @a1exsh , I left few comments here but before addressing them could you please explain the logic behind the code as reading iterator based code is a bit troublesome?

2021-09-02 10:20 UTC, ihhub commented on src/fheroes2/battle/battle_main.cpp
> +    void ExecArtifactsPickup( const ArtifactsPickup & actions, BagArtifacts::const_iterator wend );
Let please put these functions in anonymous namespace within this file to reduce its scope.

2021-09-02 10:20 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +                }
Should we do the opposite logic to avoid NOT operation?
```
if ( art.isUltimate() ) {
    // do something
}
else {
    // do anything else
}
```

It's not about optimization but a reader can easily doesn't notice "!" while reading the code.

2021-09-02 10:20 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +        for ( ArtifactsPickup::const_iterator it = artifacts.begin(); it != artifacts.end(); ++it ) {
Let's do range loop here but without  **auto**:
```
for ( const ArtifactsPickup & artifactPickup : artifacts )
```

2021-09-02 10:20 UTC, ihhub commented on src/fheroes2/battle/battle_main.cpp
> +    BagArtifacts & bag_loss = hero_loss.GetBagArtifacts();
Please use camelCase variable naming. For example `winnerBag` and `loserBag`.

2021-09-02 10:20 UTC, ihhub commented on src/fheroes2/battle/battle.h
> +    using ArtifactsPickup = std::list<std::pair<BagArtifacts::iterator, BagArtifacts::iterator>>;
Hmm... I think the solution using iterators is not the best. `Artifact` is a very lightweight class so we can just store instead or even pointers to Artifact class as **BagArtifacts** is just a storage for them. What do you think?

2021-09-02 17:08 UTC, a1exsh commented
@ihhub thanks for having a look!

The goal of is to extract the logic for artifacts pickup after the battle, so that it's not duplicated in the dialog and in the code that runs e.g. when both heroes involved in the battle are played by the AI.  My idea was to separate logic into two steps:
1. Prepare the plan for artifact pickup.
2. Execute the actual transfer, according to the plan.

Both steps are always taken, regardless if human player is involved, which requires less checks in the code.  In case of a human player, the plan is used to show captured/lost artifacts in the battle summary dialog, but actual transfer happens at a later step.

Most of the logic is in the function for preparing the plan, and execution is simply following it.  The plan (`ArtifactsPickup`) consists of pairs of references to places in the corresponding heroes artifact bags.  The task of executing the transfer is just going through the list of pairs, copying artifact values from one place to the other (unless there is no place to copy to, which is the case with ultimate artifacts or artifacts for which there was no free space in the winning hero's bag), finally removing the artifact from the losing hero bag (this is done always).

I've chosen iterators, but we could also use pointers.  Use of pointers has the advantage that we don't need additional parameter for sentinel value, we can just use a null pointer for that.

2021-09-03 06:15 UTC, a1exsh commented
@ihhub here's how it looks with the pointers instead of iterators: https://github.com/ihhub/fheroes2/pull/4106/commits/31ea0b7eedfd7be1538e8c273fe705bfdc2ba75c

2021-09-05 03:23 UTC, ihhub commented
Hi @Branikolog , could you please test these changes?

2021-09-11 11:09 UTC, ihhub requested changes

2021-09-11 11:09 UTC, ihhub commented on src/fheroes2/battle/battle_main.cpp
> +    Battle::ArtifactsPickup PlanArtifactsPickup( BagArtifacts & winnerBag, BagArtifacts & loserBag )
What if we simplify this code without using pointers at all? Artifact is lightweight class so it won't take much more space than a normal pointer.
```cpp
std::vector<Artifact> planArtifactTransfer( const BagArtifacts & winnerBag, const BagArtifacts & loserBag )
{
    std::vector<Artifact> artifacts;

    // Calculate how many places the winner has in his bag.
    size_t availableArtifactSlots = 0;
    for ( const Artifact & artifact : winnerBag ) {
        if ( !artifact.isValid() ) {
            ++availableArtifactSlots;
        }
    }

    for ( const Artifact & artifact : loserBag ) {
        if ( artifact.isValid() && art.GetID() != Artifact::MAGIC_BOOK ) {
            if ( art.isUltimate() ) {
                artifacts.emplace_back( artifact );
            }
            else if ( availableArtifactSlots > 0 ) {
                artifacts.emplace_back( artifact );
                --availableArtifactSlots;
            }
        }
    }

    return artifacts;
}
```
then inside `transferArtifacts` function which is `ExecArtifactsPickup` right now will look like:
```cpp
void transferArtifacts( BagArtifacts & winnerBag, BagArtifacts & loserBag, const std::vector<Artifact> & artifacts )
{
    // Clear loser's artifact bag.
    for ( Artifact & artifact : loserBag ) {
        if ( artifact.isValid() && art.GetID() != Artifact::MAGIC_BOOK ) {
            artifact = Artifact::UNKNOWN;
        }
    }

    size_t artifactPos = 0;

    for ( Artifact & artifact : winnerBag ) {
        if ( artifact.isValid() ) {
            continue;
        }

        for ( ; artifactPos >= artifacts.size(); ++artifactPos ) {
            if ( !artifacts[artifactPos].isUltimate() ) {
                artifact = artifacts[artifactPos];
                ++artifactPos;
                break;
            }
        }

        if ( artifactPos >= artifacts.size() ) {
            break;
        }
    }
}
```

In `Arena::DialogBattleSummary` method we pass `const std::vector<Artifact> & artifacts` which will combine both ultimate and normal artifacts. The condition
```cpp
if ( ( isWinnerHuman && nullptr != pickup.first ) || art.isUltimate() ) { // always show the message for ultimate artifacts
```
will simply be changed into
```cpp
if ( isWinnerHuman || art.isUltimate() ) { // always show the message for ultimate artifacts
```

We loose a bit here in performance (1 extra loop) but it should be fine as this code is executed very rarely. However, we'd gain in code readability. What do you think?

2021-09-11 11:39 UTC, a1exsh commented on src/fheroes2/battle/battle_main.cpp
> +    Battle::ArtifactsPickup PlanArtifactsPickup( BagArtifacts & winnerBag, BagArtifacts & loserBag )
Yeah, we can also get along with copying the artifacts.  The ultimate artifacts should still be moved to the end of the list, though, that makes the display more logical, IMO.

I will apply your suggestion and test how it works, thanks!

2021-09-11 12:29 UTC, a1exsh commented on src/fheroes2/battle/battle_main.cpp
> +    Battle::ArtifactsPickup PlanArtifactsPickup( BagArtifacts & winnerBag, BagArtifacts & loserBag )
OK, seems like it works like expected.

Test map: [ARTICAPT.zip](https://github.com/ihhub/fheroes2/files/7147814/ARTICAPT.zip)
1. Play Blue to defeat Green's hero that has the Ultimate Book of Knowledge.
2. Play Green to see Ultimate Book disappear as Blue (computer) tries to get it.

2021-09-11 14:13 UTC, merged

2021-09-11 14:13 UTC, ihhub commented
@a1exsh , thank you so much for these changes!