Remove flags from most of the captured objects when losing
ihhub/fheroes2 pull request #4140
Opened 2021-09-03 07:17 UTC by a1exsh

Fixes #1640

The original code needs rework, IMO, as it's abstraction leaks all the way down, but for now just fix the reported issue.

2021-09-03 07:21 UTC, a1exsh commented
This map may be useful for testing: [ALLTEST.MP2.zip](https://github.com/ihhub/fheroes2/files/7103974/ALLTEST.MP2.zip)

Grab those Phoenixes and head to the East! ;)

2021-09-03 07:23 UTC, a1exsh commented
Before green has lost:
![image](https://user-images.githubusercontent.com/489601/131966643-bab2764a-d1f2-42ec-a0b6-a1c551725218.png)

After (flags removed from all captured objects):
![image](https://user-images.githubusercontent.com/489601/131966702-2ce9b9ea-b0ff-4dd5-8a52-8fbd3f950b4a.png)

2021-09-03 09:53 UTC, oleg-derevenetz requested changes
Hi @a1exsh I left a few minor comments, please take a look when it's convenient for you.

2021-09-03 09:53 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_tiles.cpp
> +void Maps::Tiles::CorrectFlags32( int col, u32 index, bool up )
Since function signature is modified here, it is useful to add `const` to parameter types.

2021-09-03 09:53 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_tiles.h
> +        void CorrectFlags32( int col, u32 index, bool );
The same is here - it would be useful to add `const`.

2021-09-03 09:53 UTC, oleg-derevenetz commented on src/fheroes2/world/world.cpp
> +            MP2::MapObjectType objectType = static_cast<MP2::MapObjectType>( objcol.first );
I suppose, `objectType` can be declared as `const` here.

2021-09-03 12:55 UTC, qarkai commented on src/fheroes2/maps/maps_tiles.cpp
> +    }
```suggestion
    if ( col == Color::NONE ) {
        removeFlags();
        return;
    }
```
And revert `else` branch whitespace changes. Patch will be smaller.

2021-09-03 16:51 UTC, a1exsh commented on src/fheroes2/world/world.cpp
> +            MP2::MapObjectType objectType = static_cast<MP2::MapObjectType>( objcol.first );
Yes, that makes sense.

2021-09-03 16:55 UTC, a1exsh commented on src/fheroes2/world/world.cpp
> +            MP2::MapObjectType objectType = static_cast<MP2::MapObjectType>( objcol.first );
```suggestion
            const MP2::MapObjectType objectType = static_cast<MP2::MapObjectType>( objcol.first );
```

2021-09-03 16:55 UTC, a1exsh commented on src/fheroes2/maps/maps_tiles.h
> +        void CorrectFlags32( int col, u32 index, bool );
Any chance to skip consts on pass-by-value parameters in declarations?..

I like the symmetry and all, but it becomes really noisy very fast, IMO.

2021-09-03 16:55 UTC, a1exsh commented on src/fheroes2/maps/maps_tiles.cpp
> +void Maps::Tiles::CorrectFlags32( int col, u32 index, bool up )
```suggestion
void Maps::Tiles::CorrectFlags32( const int col, const u32 index, const bool up )
```

2021-09-03 16:55 UTC, a1exsh commented on src/fheroes2/maps/maps_tiles.cpp
> +    }
Maybe...

2021-09-03 17:11 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_tiles.h
> +        void CorrectFlags32( int col, u32 index, bool );
Hi @a1exsh in this project `const` is used in parameter types for the same reason as for local variables - to ensure that they are not accidentally changed somewhere. There may be use cases with non-const parameters - for example, if parameter value should be somehow capped and you don't want to add a separate variable just to cap the parameter passed by value, but in general `const` parameters are welcome in a new code.

2021-09-03 17:26 UTC, a1exsh commented on src/fheroes2/maps/maps_tiles.h
> +        void CorrectFlags32( int col, u32 index, bool );
I totally get that, but what I'm pointing out is that it's possible to use `const` parameters in function definitions, but omit the modifiers in the declaration, like in the line above.

The declaration is for the caller, and the caller doesn't care if implementation modifies passed by value parameters like int, bool, etc.  Of course, in case of pointers, references, composite types or containers, `const` should be used in the declarations as well.

2021-09-03 17:35 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_tiles.h
> +        void CorrectFlags32( int col, u32 index, bool );
Ah, you mean just function declarations... You see, when people (for example, me) write a new function, they write definition first and then just copy definition to the place where declaration resides (usually it's a header file) - or, may be, vice versa. In either case, they should either remove `const` from declaration or add them to the definition, which is extra action. I suppose that just keeping them completely identical is much easier.

2021-09-03 17:39 UTC, a1exsh commented on src/fheroes2/maps/maps_tiles.h
> +        void CorrectFlags32( int col, u32 index, bool );
```suggestion
        void CorrectFlags32( const int col, const u32 index, const bool );
```

2021-09-03 17:40 UTC, a1exsh commented on src/fheroes2/maps/maps_tiles.h
> +        void CorrectFlags32( const int col, const u32 index, const bool );
```suggestion
        void CorrectFlags32( const int col, const u32 index, const bool up );
```

Since we are changing it anyway

2021-09-03 17:46 UTC, oleg-derevenetz approved these changes

2021-09-04 05:46 UTC, ihhub commented
Hi @a1exsh , I think we already have a solution for this. Please take a look at `Maps::Tiles::removeFlags` method inside. What we need is to call this method on all objects own by the player except castles and towns where we should set gray flags.

2021-09-04 06:02 UTC, a1exsh commented
@ihhub hey, but that's exactly what this PR does!

2021-09-04 06:03 UTC, ihhub commented
> 
> 
> @ihhub hey, but that's exactly what this PR does!

Ah, my bad. I missed one line here. My apologies. I'll review it very soon.

2021-09-04 06:28 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +            world.GetTiles( ( *it ).first ).CaptureFlags32( objectType, objcol.second );
We could do this way:
```cpp
const MP2::MapObjectType objectType = static_cast<MP2::MapObjectType>( objcol.first );
const bool isCastle = ( objectType == MP2::OBJ_CASTLE ) || ( objectType == MP2::OBJN_CASTLE );
if ( isCastle ) {
    world.GetTiles( it->first ).CaptureFlags32( objectType, Color::UNUSED );
}
else {
    world.GetTiles( it->first ).removeFlags();
}
```
without any changes outside this method. Of course it's the same way as before but less hacky way without extra conditions in methods. What do you think?

Also please notice that `OBJN_CASTLE` should be checked too.

2021-09-04 06:37 UTC, a1exsh commented on src/fheroes2/world/world.cpp
> +            world.GetTiles( ( *it ).first ).CaptureFlags32( objectType, objcol.second );
I think I've tried that initially, but it didn't work for the Sawmill and Alchemist Lab, because these two objects have special handling in that they set the flag on a _different_ tile.  So I had to move the handling all the way down to the `CorrectFlags32` function, even though that makes the change bigger.

That is `OBJN_CASTLE` and why don't have have a `case` for it in `CaptureFlag32`?

2021-09-04 06:38 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +            world.GetTiles( ( *it ).first ).CaptureFlags32( objectType, objcol.second );
OBJ_CASTLE is the main entrance while OBJN_CASTLE is for the rest of tiles related to castle. I think your solution is correct.

2021-09-04 06:41 UTC, a1exsh commented on src/fheroes2/world/world.cpp
> +            world.GetTiles( ( *it ).first ).CaptureFlags32( objectType, objcol.second );
I also think that assignment of `objcol.second` is essential in this method and should not be removed (as in your proposed change).

2021-09-04 09:17 UTC, merged

2021-09-04 09:17 UTC, ihhub commented
@a1exsh , thanks a lot for this fix!