Add the FAQ to the repository home page.
ihhub/fheroes2 pull request #4223
Opened 2021-09-19 10:43 UTC by Arthusppp

2021-09-19 13:55 UTC, oleg-derevenetz requested changes
LGTM in general, except minor formatting issue. I suppose we should also make the same changes in the docs/README.md as well?

2021-09-19 13:55 UTC, oleg-derevenetz commented on README.md
> +
This extra empty line is not needed.

2021-09-19 18:01 UTC, Arthusppp commented on README.md
> +
Done.

2021-09-20 10:13 UTC, oleg-derevenetz approved these changes

2021-09-20 12:23 UTC, ihhub requested changes
Hi @Arthusppp , I left one identical comment here. Could you please take a look?

2021-09-20 12:23 UTC, ihhub commented on README.md
>  ## Development
I think we should rename it into `Contribution and Development`.

2021-09-20 12:23 UTC, ihhub commented on docs/README.md
>  ## Development
I think we should rename it into `Contribution and Development`.

2021-09-21 00:52 UTC, merged

2021-09-21 00:52 UTC, ihhub commented
@Arthusppp , thank you so much for updating the documentation!