Campaign high scores
ihhub/fheroes2 pull request #4261
Opened 2021-09-26 06:13 UTC by eos428

fix #4166

In summary:
- Rename hgs_t to HighScoreStandardData, also create HighScoreCampaignData
- Rename HGSData to HighScoreDataContainer which now also contains a vector of HighScoreCampaignData
- Remove display logic from HGSData and place it inside anonymous namespace in game_highscores.cpp
- Create highscores.cpp and highscores.h for pure high-score logic, game's highscore logic will be in game_highscores.cpp
- Alot of code cleanup here and there, probably there's still more we can do here

I'll need some help on the correct sprite index for high score campaign's background. I will make a comment on the specific line needing the changes. And then regarding about the change in file formatting which we'd look to make closer to a save file's, I'd put that in another PR after this to avoid overscoping. This PR is already a lot more than what I expected in the first place.

Also, this is totally not a good first issue ;)

2021-09-26 08:10 UTC, eos428 commented on src/fheroes2/game/game_highscores.cpp
> +        fheroes2::Blit( fheroes2::AGG::GetICN( ICN::HSBKG, 4 ), display, ox, oy );
This is the wrong background issue I wrote about in the PR summary. Need help to get the correct sprite index on this one.

2021-09-26 13:44 UTC, vincent-grosbois commented on src/fheroes2/game/highscores.cpp
> +        for ( size_t i = 0; i < monsterDays.size(); ++i ) {
I'm sure you can use somethin like std::lower_bound instead to have the result in O(log(n)) instead of O(n)
it may not matter though

2021-09-26 13:54 UTC, vincent-grosbois commented on src/fheroes2/game/highscores.cpp
> +    const uint8_t HGS_MAX = 10;
would suggest renaming this or putting a comment on what it is

2021-09-27 13:16 UTC, eos428 commented on src/fheroes2/game/highscores.cpp
> +    const uint8_t HGS_MAX = 10;
Yeah, I suppose we could rename these, the IDs probably still need a comment in addition to the renaming though haha

2021-09-29 04:43 UTC, ihhub requested changes
Hi @eos428 , I left several comments here. Could you please take a look at them and see that my suggestions are useful?

2021-09-29 04:43 UTC, ihhub commented on src/fheroes2/game/highscores.cpp
> +    const uint8_t HGS_MAX = 10;
This variable must be `size_t` type to avoid implicit conversion.

2021-09-29 04:43 UTC, ihhub commented on src/fheroes2/game/highscores.cpp
> +    HighScoreDataContainer & HighScoreDataContainer::Get()
Do we need this method? It's used only for singleton classes while in our cases we can just create a normal instance of this class as it's used only in one place after all.

2021-09-29 04:43 UTC, ihhub commented on src/fheroes2/game/highscores.h
> +    struct HighScoreStandardData
The only difference between `HighScoreStandardData` and `HighScoreCampaignData` structures is presence of `_rating` member in the last structure. To reduce code duplication we should at least derive `HighScoreCampaignData` from `HighScoreStandardData` structure.
Moreover, we can calculate rating during runtime (not a big deal to call small function 10 times). In this case we'll need only one structure to hold all needed data. What do you think?

2021-09-29 04:43 UTC, ihhub commented on src/fheroes2/game/highscores.h
> +        uint32_t _localTime;
I recommend to change this type to `uint64_t` to avoid conversion warnings.

2021-09-29 04:43 UTC, ihhub commented on src/fheroes2/game/highscores.h
> +        const std::vector<HighScoreCampaignData> & GetHighScoresCampaign()
These 2 methods could be `const`.

2021-09-29 04:43 UTC, ihhub commented on src/fheroes2/game/highscores.cpp
> +}
Please add an empty line at the end of this file.

2021-09-29 04:43 UTC, ihhub commented on src/fheroes2/game/highscores.cpp
> +                monsterDays.emplace_back( std::make_pair( daySoFar, monstersInRanking[i] ) );
Please try to remove `std::make_pair` here and emplace_back should work properly without it.

2021-09-29 04:43 UTC, ihhub commented on src/fheroes2/game/highscores.cpp
> +        hdata << static_cast<uint16_t>( HGS_ID2 ) << _highScoresStandard << _highScoresCampaign;
Please remove static_cast call here. It'd redundant based on a fact that `HGS_ID2` is uint16_t type.

2021-09-29 04:43 UTC, ihhub commented on src/fheroes2/game/highscores.cpp
> +        return true;
We could combine these lines into
```cpp
return !hdata.fail() && hdata.write( fileName ) );
```

2021-09-29 04:43 UTC, ihhub commented on src/fheroes2/game/highscores.cpp
> +        std::vector<HighScoreStandardData> & highScores = _highScoresStandard;
Why do we need this extra variable if we can use `_highScoresStandard` directly?

2021-09-29 04:43 UTC, ihhub commented on src/fheroes2/game/highscores.cpp
> +        std::vector<HighScoreCampaignData> & highScores = _highScoresCampaign;
Why do we need this extra variable if we can use `_highScoresCampaign` directly?

2021-09-29 04:43 UTC, ihhub commented on src/fheroes2/game/highscores.cpp
> +    void HighScoreDataContainer::RegisterScoreStandard( const std::string & playerName, const std::string & scenarioName, const uint32_t days, const uint32_t rating )
if we're going to use the same structure we might need to create another private function which will be called from this method and the method below to reduce code duplication.

2021-09-29 04:43 UTC, ihhub commented on src/fheroes2/game/highscores.cpp
> +                monsterRatings.emplace_back( std::make_pair( ratingSoFar, monstersInRanking[i] ) );
We can remove std::make_pair call from this line.

2021-09-29 04:43 UTC, ihhub commented on src/fheroes2/game/highscores.cpp
> +        std::pair<size_t, Monster::monster_t> lastData = monsterRatings.back();
We're making a copy of std::pair here. Please use const reference here.

2021-09-29 11:37 UTC, eos428 commented on src/fheroes2/game/highscores.cpp
> +    HighScoreDataContainer & HighScoreDataContainer::Get()
At the moment this is used in both HighScoresStandard() and HighScoresCampaign(). I don't wish to make a new instance every time these two functions are called since we have to initialize the pairs for monster ratings and days,

2021-09-29 11:40 UTC, eos428 commented on src/fheroes2/game/highscores.h
> +    struct HighScoreStandardData
Yes I agree with calculating rating during runtime. In that case, I think we need to store the game difficulty too?

2021-09-29 11:45 UTC, eos428 commented on src/fheroes2/game/highscores.cpp
> +        std::vector<HighScoreCampaignData> & highScores = _highScoresCampaign;
Sorry, personal coding style in c# when I use vscode. The idea is to minimize direct references to class' variables by creating a local variable. But no worries I will change this one and the one above.

2021-09-29 11:51 UTC, eos428 commented on src/fheroes2/game/game_highscores.cpp
> +    static uint32_t monsterAnimationFrameId = 0;
Yeah, I guess we can create local variables in both HighScoresStandard() and HighScoresCampaign()

2021-09-29 11:59 UTC, eos428 commented on src/fheroes2/game/highscores.cpp
> +    void HighScoreDataContainer::RegisterScoreStandard( const std::string & playerName, const std::string & scenarioName, const uint32_t days, const uint32_t rating )
Yes I think we should create a template function for std::vector<T> where T is either high score standard or high score campaign

2021-09-29 12:02 UTC, eos428 commented on src/fheroes2/game/highscores.h
> +    struct HighScoreStandardData
Also while the variables are almost the same, I think we should still make the distinction between the string's variable name. One is campaignName and another is scenarioName.

2021-09-29 12:43 UTC, eos428 commented on src/fheroes2/game/highscores.h
> +        uint32_t _localTime;
I took a look and it seems we don't have a method to serialize or deserialize uint64_t yet. Should we do this the serialization thing in another PR?

2021-09-29 12:47 UTC, eos428 commented on src/fheroes2/game/highscores.cpp
> +    HighScoreDataContainer & HighScoreDataContainer::Get()
On second thought I think I get what you mean, this should be inside the anonymous namespace in `game_highscores.cpp`

2021-09-29 12:53 UTC, eos428 commented on src/fheroes2/game/game_highscores.cpp
> +        fheroes2::Blit( fheroes2::AGG::GetICN( ICN::HSBKG, 4 ), display, ox, oy );
I see... thanks for the info. There's an issue where the button is still `Campaign` when we are viewing campaign high scores.  I thought it was the background but maybe the problem is somewhere else?

2021-09-29 13:20 UTC, undef21 commented on src/fheroes2/game/game_highscores.cpp
> +    fheroes2::Button buttonStandard( top.x + 8, top.y + 315, ICN::HISCORE, 2, 1 );
Sprites of button "Standard"  have indices 2, 3.

2021-09-29 19:43 UTC, undef21 commented on src/fheroes2/game/game_highscores.cpp
> +            le.MousePressLeft( buttonCampaign.area() ) ? buttonCampaign.drawOnPress() : buttonCampaign.drawOnRelease();
I think problem with "Campaign" button here...

2021-09-29 19:43 UTC, undef21 commented on src/fheroes2/game/game_highscores.cpp
> +            le.MousePressLeft( buttonStandard.area() ) ? buttonStandard.drawOnPress() : buttonStandard.drawOnRelease();
...and here. Comment this lines and you can see.

2021-09-30 11:48 UTC, eos428 commented on src/fheroes2/game/game_highscores.cpp
> +            le.MousePressLeft( buttonStandard.area() ) ? buttonStandard.drawOnPress() : buttonStandard.drawOnRelease();
This doesn't seem to solve the issue... It seems the background image in  `fheroes2::Blit( fheroes2::AGG::GetICN( ICN::HSBKG, 0 ), display, top.x, top.y );` in `RedrawHighScoresCampaign()` also includes the `Campaign` button, which is not what we are looking for and I think that's the root cause of the wrong button issue.

Maybe there's another high score background sprite that we don't know yet?

2021-10-01 09:28 UTC, undef21 commented on src/fheroes2/game/game_highscores.cpp
> +            le.MousePressLeft( buttonStandard.area() ) ? buttonStandard.drawOnPress() : buttonStandard.drawOnRelease();
This is not quite an original resource. IСN was converted from original format. It's same as game screenshot.

2021-10-05 06:01 UTC, eos428 commented on src/fheroes2/game/game_highscores.cpp
> +            le.MousePressLeft( buttonStandard.area() ) ? buttonStandard.drawOnPress() : buttonStandard.drawOnRelease();
Sorry for late response.

IMO the best solution would be to draw the background just once. But there's the problem where the background gets dirty due to the monster sprite.

Alternatively we could draw the campaign button again on top of the background, but it seems a bit hacky to say the least.

2021-11-08 14:16 UTC, ihhub commented
Hi @eos428 , **game_highscores.cpp** contains 2 functions:
- **fheroes2::GameMode Game::HighScoresStandard()**
- **fheroes2::GameMode Game::HighScoresCampaign()**

from what I can see these functions are extremely identical except few minor things. We have to reduce code duplication here and we can do this way: add a new function in unnamed namespace within this file which will accept a single parameter indicating whether it is a campaign or a normal scenario (**const bool isCampaign** is sufficient). Then the remaining logic inside function will depend on this variable. Some variables will just have a common name.

What do you think?

2021-11-10 11:48 UTC, eos428 commented
Hi @ihhub, I think that's something we can try. Hopefully the only param we have to pass is just `isCampaign`.

2022-04-23 12:28 UTC, zenseii commented
Hi guys! What is currently remaining for this PR to be merged? It would seem that working on issues such as these https://github.com/ihhub/fheroes2/issues/5269, https://github.com/ihhub/fheroes2/issues/5239, https://github.com/ihhub/fheroes2/issues/5165 would have to wait until this PR has been merged, right?

2022-05-22 10:00 UTC, ihhub approved these changes

2022-05-22 10:01 UTC, ihhub commented
Hi @oleg-derevenetz , I completed this pull request so I marked it approved. Please take a look for some obvious mistakes if any.

2022-05-22 21:44 UTC, oleg-derevenetz requested changes
Hi @ihhub I left only one obvious notice, please take a look when you have time :)

2022-05-22 21:44 UTC, oleg-derevenetz commented on src/fheroes2/game/game_highscores.cpp
> +        std::string msg = std::string( "Developer mode, not save! \n \n Your result: " ) + std::to_string( Campaign::CampaignSaveData::Get().getDaysPassed() );
I suppose we need to use the `Game::GetGameOverScores()` here in case of a regular single player game.

2022-05-23 23:50 UTC, merged

2022-05-23 23:51 UTC, ihhub commented
@eos428 , thank you very much for these changes!