New week is only determined through current day + map seed
ihhub/fheroes2 pull request #4283
Opened 2021-09-28 20:38 UTC by vincent-grosbois

This make new week deterministic once the map is loaded
It may not 100% be what we want as in heroes 2 I think it's also partly
random once the map is loaded

2021-09-29 08:27 UTC, Branikolog commented
> This make new week deterministic once the map is created It may not 100% be what we want as in heroes 2 I think it's also partly random once the map is created

Hi, @vincent-grosbois !
In the OG if we load autosave - the week will always be the same. But if we load and replay the game from a more distant point (like 3+ days) the week changes... 
Not sure about H2, but comparing with H3 autosave can even bring other week in a case AI actions were completely different.

2021-09-29 09:02 UTC, vincent-grosbois commented
> > This make new week deterministic once the map is created It may not 100% be what we want as in heroes 2 I think it's also partly random once the map is created
> 
> Hi, @vincent-grosbois ! In the OG if we load autosave - the week will always be the same. But if we load and replay the game from a more distant point (like 3+ days) the week changes... Not sure about H2, but comparing with H3 autosave can even bring other week in a case AI actions were completely different.

Indeed it's basically what I was  saying
now the question I had is _how_ this change of week exactly appears, or rather, if we can do something similar.
One thing I thought about (maybe) is to also hash based on the list of all heroes' stats

2021-09-30 13:10 UTC, ihhub commented
Hi @vincent-grosbois , I think the original game depends on all neutral monsters on the map instead of heroes. Logically, spawning of neutrals relates on locations where other monsters stay. To prove my theory: run the original game, make a save, check the new week, load the save and hire extra hero or dismiss few, check the new week. I think it should remain the same.

2021-09-30 15:43 UTC, vincent-grosbois commented
> Hi @vincent-grosbois , I think the original game depends on all neutral monsters on the map instead of heroes.

Ok so for the hashing part I can make it dependent also on the list / position / type of neutral monsters
How does it sound ?

2021-09-30 16:01 UTC, a1exsh commented
> > This make new week deterministic once the map is created It may not 100% be what we want as in heroes 2 I think it's also partly random once the map is created
> 
> Hi, @vincent-grosbois ! In the OG if we load autosave - the week will always be the same. But if we load and replay the game from a more distant point (like 3+ days) the week changes... Not sure about H2, but comparing with H3 autosave can even bring other week in a case AI actions were completely different.

Do you mean replay these 3 days identically to the first try? In that case we should expect the same outcome, including the week announcement. Otherwise, it can easily happen that the random number generator is asked different number of times, thus affecting all further outcomes.

2021-09-30 17:53 UTC, Branikolog commented
Hi, @a1exsh!

> Do you mean replay these 3 days identically to the first try? In that case we should expect the same outcome, including the week announcement. Otherwise, it can easily happen that the random number generator is asked different number of times, thus affecting all further outcomes.

Yes. In the OG I made a savepoint on tuesday, then simply skipped 3 days in a row and each reload was completely different week announcement.

2021-10-02 14:46 UTC, ihhub commented
Hi @vincent-grosbois , yes. This is exactly what I'm thinking.

2021-10-02 14:49 UTC, ihhub commented
> 
> 
> Hi, @a1exsh!
> 
> > Do you mean replay these 3 days identically to the first try? In that case we should expect the same outcome, including the week announcement. Otherwise, it can easily happen that the random number generator is asked different number of times, thus affecting all further outcomes.
> 
> Yes. In the OG I made a savepoint on tuesday, then simply skipped 3 days in a row and each reload was completely different week announcement.

It's because AI most likely fought neutrals. Make a map with no neutrals and try this.

2021-10-02 17:13 UTC, vincent-grosbois commented
@ihhub you can review it then :)

2021-10-03 02:26 UTC, ihhub requested changes
Hi @vincent-grosbois , I left few comments in this pull request. Could you please take a look?

2021-10-03 02:26 UTC, ihhub commented on src/fheroes2/world/world.h
> +    size_t _week_seed; // global seed for the map, for this week
Since we assigned the value for the above variable let's do the same for this member.

2021-10-03 15:21 UTC, merged

2021-10-03 15:22 UTC, ihhub commented
@vincent-grosbois , thank you so much for this useful improvement!