Add missing button shadows in dialogs
ihhub/fheroes2 pull request #4350
Opened 2021-10-09 19:44 UTC by a1exsh

Relates to #4349

2021-10-10 08:30 UTC, a1exsh commented
Original:
![image](https://user-images.githubusercontent.com/489601/136688492-26d1aa23-2339-4606-a23f-435feb838fab.png)

Changed:
![image](https://user-images.githubusercontent.com/489601/136688500-c4b37bd2-7fa4-43d7-90e6-22627b7b046a.png)

2021-10-10 09:27 UTC, Branikolog commented
Hi, @a1exsh 
Looks fantastic! :)
But I've noticed, that the original central button has its shadow (which is a part of image) merged with the frame darkening of the frame. Is it possible  to get rid of bright line (between shadow and the frame darkening) here?
![config shadow](https://user-images.githubusercontent.com/55348946/136690108-affbf808-66ba-439d-b931-1e928685adf3.png)

2021-10-10 09:37 UTC, a1exsh commented
@Branikolog good catch.  I think we can fix that by extending the shadow by just one more pixel (currently it is -4,4).

2021-10-10 09:51 UTC, Branikolog commented
@a1exsh 
Also, it feels like shadow to the left contrasts more with the background, comparing to the same place near central button. Is it just due to another background texture?

2021-10-10 14:39 UTC, a1exsh commented
> @a1exsh Also, it feels like shadow to the left contrasts more with the background, comparing to the same place near central button. Is it just due to another background texture?

@Branikolog that is because the `OKAY` button and the shadow beneath it are part of the original resource, but we add shadow manually for our custom button, and it doesn't match 100%.  Now that I think about it, in this case both buttons are of the same size, so what we can try is copying the original button together with the shadow instead.

2021-10-10 19:33 UTC, Branikolog commented
@a1exsh 
It's perfect!

2021-10-12 16:10 UTC, a1exsh commented
Experimental settings dialog:
![image](https://user-images.githubusercontent.com/489601/136989673-75427cff-49ec-4d35-a164-4f5828be0e55.png)

Game config dialog:
![Screenshot from 2021-10-12 18-09-08](https://user-images.githubusercontent.com/489601/136991834-a2569548-00b5-4a97-b16e-414950af6ff5.png)
![image](https://user-images.githubusercontent.com/489601/136991893-34527a4c-379c-4313-a5a9-ed9ca695d0c2.png)

2021-10-15 14:57 UTC, Branikolog commented
Hi, @a1exsh.
One more case found.
![image](https://user-images.githubusercontent.com/55348946/137508389-50a3f2c7-c933-43a6-9438-55bcdef2d349.png)

2021-10-16 10:31 UTC, a1exsh commented
Still quick (as in "hack"), but less dirty corners:
![image](https://user-images.githubusercontent.com/489601/137584004-8adb25ac-61e5-4c71-ad50-9e4a3541050a.png)

2021-10-29 19:15 UTC, a1exsh commented
Not sure if there are button shadows for this dialog in OG, will check later:
![image](https://user-images.githubusercontent.com/489601/139490004-fe6ee84b-cb4c-4ffd-89b9-99a6fd6464ad.png)

2021-10-29 19:57 UTC, a1exsh commented
There are no shadows, but I guess it might have looked a bit better with them:
![heroes2_006](https://user-images.githubusercontent.com/489601/139494498-7c05d776-cf6c-4b95-99fc-4f60bfd00d8b.png)

2021-10-30 11:20 UTC, a1exsh commented
Fixed gift resources buttons position and added shadows.

Before:
![image](https://user-images.githubusercontent.com/489601/139530903-b18a0345-9396-4abe-afca-3793952cc6a2.png)

After:
![Screenshot from 2021-10-30 13-15-23](https://user-images.githubusercontent.com/489601/139530780-c5995725-e348-465e-9b0e-a86c814e445e.png)

It is kinda frustrating that every dialog has its own way of calculating position and border and placing the buttons on the window...  Are there any plans to start working on a proper UI toolkit? :) @ihhub

2021-10-30 13:18 UTC, Branikolog commented
> Not sure if there are button shadows for this dialog in OG, will check later: ![image](https://user-images.githubusercontent.com/489601/139490004-fe6ee84b-cb4c-4ffd-89b9-99a6fd6464ad.png)

We have an opened issue for that. :)
#2261
Just not to forget to close it after fixing. ;)

2021-10-30 16:47 UTC, a1exsh commented
It really becomes an art at some point: every single button is unique %)

![image](https://user-images.githubusercontent.com/489601/139541872-dcace824-c92b-426a-9cad-baa349016f3b.png)

2021-10-30 16:52 UTC, a1exsh commented on src/fheroes2/gui/ui_button.cpp
> +        return *_shadowSprite.get();
Not sure about this one: I've just copied the approach from `_getDisabled()`.

2021-10-31 17:45 UTC, a1exsh commented
While working on this I've noticed another glitch related to the Evil "show hero" / "show market" buttons used in Surrender dialog as well as when an army is willing to join the hero.

To make the pressed state we replace all back pixels (color index 36) with transform 1, but the there are pixels with the same index also in the middle of the pressed Evil buttons, not only around the border.  This results in background leaking through the drawing, which looks like this:
![image](https://user-images.githubusercontent.com/489601/139595467-e1e1d9af-73c7-4330-b610-07e849cd83bc.png)

A have a fix in the works, will either push here or open a new PR, depending on the resulting size.

2021-10-31 18:55 UTC, a1exsh commented
Alright, I'm now content with this change myself — please have a look when you have time. :)

2021-11-02 12:20 UTC, Branikolog commented
Hi, @a1exsh !
I've noticed one thing, related to shadows. While pressing "Hero info" or "Marketplace" buttons, shadow becomes more bold. While common "Yes"/"NO" buttons have same shadow in a pressed state:
![image](https://user-images.githubusercontent.com/55348946/139841396-4efff6b6-26aa-4100-820c-5139245ba9cb.png)
![image](https://user-images.githubusercontent.com/55348946/139841427-747553df-afb0-43be-b5fc-e4664a17a69e.png)
Actually, this PR becomes really huge. So this could be fixed in a separate one, if you wish. Anyway, you've done a ton of work with buttons already! Thanks!

I've also found out, that "GIFT" and "EXIT" buttons at evil interface become surrounded with gray frame once being pressed:
![image](https://user-images.githubusercontent.com/55348946/139842816-6e871f4f-f39c-41e5-af4d-4c56202f1a08.png)
The same to Surrender buttons:
![image](https://user-images.githubusercontent.com/55348946/139843139-e70e57b3-1b33-4f14-894c-99de2110118e.png)
![image](https://user-images.githubusercontent.com/55348946/139843179-fe1bf966-4d4a-4802-9fe3-92e13c9b1d01.png)
And "GIFT" window:
![image](https://user-images.githubusercontent.com/55348946/139843588-f17330d3-603e-45f0-9c11-72720b7cc849.png)
![image](https://user-images.githubusercontent.com/55348946/139843641-5d14af22-d48e-4d28-b284-f6b7034f751a.png)
A small piece of background changes while pressing OK button at setting window:
![image](https://user-images.githubusercontent.com/55348946/139844122-f6aff67f-7133-4a1f-9ae4-698d95f25325.png)
![Corner](https://user-images.githubusercontent.com/55348946/139844261-6f66aa00-c159-4df2-9f1c-8f7ab902cc51.png)
And same to evil:
![image](https://user-images.githubusercontent.com/55348946/139844786-84df98aa-6183-43bf-9cbf-f515656fd4c0.png)

2021-11-02 12:56 UTC, a1exsh commented
@Branikolog thanks for having a look — I have a fix for the button corners as well, just didn't push it yet to avoid bloating the PR. Will check the rest of your findings later. :)

2021-11-02 12:57 UTC, Branikolog commented
@a1exsh 
Thank You!

2021-11-02 18:26 UTC, a1exsh commented
> While pressing "Hero info" or "Marketplace" buttons, shadow becomes more bold.
 ![image](https://user-images.githubusercontent.com/55348946/139841427-747553df-afb0-43be-b5fc-e4664a17a69e.png)

Good catch — will fix it.

> I've also found out, that "GIFT" and "EXIT" buttons at evil interface become surrounded with gray frame once being pressed:
![image](https://user-images.githubusercontent.com/55348946/139842816-6e871f4f-f39c-41e5-af4d-4c56202f1a08.png)

This was the case before changes from this PR — let's fix it separately (I already know how to do that).

> The same to Surrender buttons:
![image](https://user-images.githubusercontent.com/55348946/139843139-e70e57b3-1b33-4f14-894c-99de2110118e.png)

Also was the case before, need to check how to fix it.

> And "GIFT" window:
![image](https://user-images.githubusercontent.com/55348946/139843588-f17330d3-603e-45f0-9c11-72720b7cc849.png)

Was the case, fixing seems easy.

> A small piece of background changes while pressing OK button at setting window:
![image](https://user-images.githubusercontent.com/55348946/139844122-f6aff67f-7133-4a1f-9ae4-698d95f25325.png)

Here I set a trap for myself: need to figure out why I did change the button ICN in this code :sweat_smile:

2021-11-02 19:10 UTC, a1exsh commented
> While pressing "Hero info" or "Marketplace" buttons, shadow becomes more bold.
> A small piece of background changes while pressing OK button at setting window:

@Branikolog fixed for both evil and good modes —- please have a look.  Let's fix other issues separately. :)

2021-11-02 19:32 UTC, Branikolog commented
@a1exsh 

> @Branikolog fixed for both evil and good modes —- please have a look. Let's fix other issues separately. :)

Sure!

2021-11-10 07:57 UTC, a1exsh commented
@Branikolog would you have time for another look on this? :)

2021-11-10 11:07 UTC, Branikolog commented
Hi, @a1exsh !
I'm not sure, if all the cases are related to current PR. So be free to postpone some of them to future.

I've noticed, that Creature info window has smaller shadows for buttons.
![image](https://user-images.githubusercontent.com/55348946/141099207-01d6b3c8-c1c6-47b3-91f6-05c5e769e3ae.png)
Also, unavailable "ACCEPT" button has a small black line along left and bottom border.
![image](https://user-images.githubusercontent.com/55348946/141099474-9b2b261f-00ef-40a2-bd22-d7aa63634c39.png)
Pretty sure, we haven't discussed it before, but I'm not sure it is related to the current PR.
And the same to Dig and supposedly other system buttons.
![image](https://user-images.githubusercontent.com/55348946/141101765-4d9283f3-210e-414c-b7dd-5a2e11e2c7cb.png)

2021-11-10 18:28 UTC, a1exsh commented
> Hi, @a1exsh ! I'm not sure, if all the cases are related to current PR. So be free to postpone some of them to future.
> 
> I've noticed, that Creature info window has smaller shadows for buttons.
![image](https://user-images.githubusercontent.com/55348946/141099207-01d6b3c8-c1c6-47b3-91f6-05c5e769e3ae.png)

Right.  This inconsistency comes from OG resources.  Not sure if we would try to make all of UI consistent one day, but at least we should be consistent within a single dialog window.

> Also, unavailable "ACCEPT" button has a small black line along left and bottom border.
![image](https://user-images.githubusercontent.com/55348946/141099474-9b2b261f-00ef-40a2-bd22-d7aa63634c39.png)
> Pretty sure, we haven't discussed it before, but I'm not sure it is related to the current PR.
> And the same to Dig and supposedly other system buttons.
![image](https://user-images.githubusercontent.com/55348946/141101765-4d9283f3-210e-414c-b7dd-5a2e11e2c7cb.png)

Nicely spotted — I can see it as well.  This is caused by our generic logic of producing disabled button sprites by applying a darkening palette.  All evil disabled buttons might suffer from it.  We might want to tackle it separately, if at all.

2021-11-11 07:29 UTC, a1exsh commented
@Branikolog I'd like to wrap this change up and move on to the next one: I've got a few in the pipeline, but they depend on this one being merged first. ;)

2021-11-11 08:46 UTC, Branikolog commented
@a1exsh 

> @Branikolog I'd like to wrap this change up and move on to the next one: I've got a few in the pipeline, but they depend on this one being merged first. ;)

Please, don't hesitate making small changes one my one, rather than merging huge part of new code.
You know, I'm always complaining on new issues being noticed. Ignore it! :D

2021-11-11 08:58 UTC, a1exsh commented
@ihhub please have another look when you have a minute. :)

2021-11-13 13:19 UTC, a1exsh commented
@ihhub maybe you could have a look on the code — the changes related to shadows are now complete, but I have more related improvements in pipeline. :)

2021-11-13 16:04 UTC, ihhub requested changes
Hi @a1exsh , I raised few design related questions here. Would you mind to take a look at them?

2021-11-13 16:04 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +            btnMarket.captureBackground();
Can you please explain the logic for this code? Are we drawing a shadow and then we're copying a background? If yes shouldn't it be easier to create a factory function which will accept a background image and 2 button images? The function will just return either a pair of images or a a button? We know that the background is not going to be changed.

2021-11-13 16:08 UTC, a1exsh commented on src/engine/image.cpp
> +    }
Good point :sweat_smile:  I think I've had some extra logic there, but after removing that it's not really different from plain `memcpy()`.

2021-11-13 16:12 UTC, a1exsh commented on src/fheroes2/battle/battle_dialogs.cpp
> +            btnMarket.captureBackground();
That's a good question: now I will have to recall everything, it has been a few weeks since I was last working on this...

2021-11-13 16:14 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +            btnMarket.captureBackground();
I think a single function should fulfill all our needs in this greatly reducing the code complexity.

2021-11-14 06:46 UTC, a1exsh commented on src/fheroes2/battle/battle_dialogs.cpp
> +            btnMarket.captureBackground();
@ihhub thanks a lot for your suggestions — I think I've addressed them all and the code is indeed much cleaner now.  I've added a special `AutoShadowButton` class to work with the shadows.  Please have another look!

2021-11-14 06:53 UTC, a1exsh commented
@Branikolog I did some code refactoring per @ihhub 's request.  To my eye everything looks good, but a slight problem remains with the pressed state of the Hero and Marketplace buttons in the Level Up and Army Joining dialogs (and that precisely because we do not draw shadows for them there, so also not capturing the background to restore it before drawing the pressed state).  I prefer to address this separately, as it is not related to adding shadows, which is the title of the PR. :)

2021-11-14 07:14 UTC, Branikolog commented
@a1exsh 
Sure! I believe it's much easier to work on fixes in separate PRs (even separate for each button) as well as test the changes. 
I'll check the PR once again in a few hours.

2021-11-14 07:27 UTC, a1exsh commented
> a slight problem remains with the pressed state of the Hero and Marketplace buttons in the Level Up and Army Joining dialogs

Hm, I just went through the changes once again and I see that this was handled by custom code before, so it can be seen as a regression.  I will still try to fix it right here, it shouldn't be too much of additional code.

2021-11-14 08:03 UTC, a1exsh commented
>  I will still try to fix it right here, it shouldn't be too much of additional code.

Fixed :)

2021-11-15 18:33 UTC, a1exsh commented
@Branikolog I've found and fixed an issue with the `OKAY` button shadow in the battle summary dialog, introduced by refactoring.
@ihhub please have another look at the code. :)

2021-11-16 10:14 UTC, Branikolog commented
Hi, @a1exsh !
Found an issue with "Town Portal" buttons being pressed.
![image](https://user-images.githubusercontent.com/55348946/141966367-02e740fb-095e-4061-9cf9-cc1c35fb066b.png)

2021-11-16 10:22 UTC, a1exsh commented
> Hi, @a1exsh ! Found an issue with "Town Portal" buttons being pressed. ![image](https://user-images.githubusercontent.com/55348946/141966367-02e740fb-095e-4061-9cf9-cc1c35fb066b.png)

If the issue you're referring to is with button corners — it is not new and I'm waiting for this PR to be merged before addressing these. I think it was discussed already in the comments here.

2021-11-16 10:42 UTC, Branikolog commented
Sorry, @a1exsh. I have too much tasks now. :) Missed this moment.
I was just confused by the fact, the latest commit version doesn't have these corners.

2021-11-16 10:55 UTC, a1exsh commented
@Branikolog 
> I was just confused by the fact, the latest commit version doesn't have these corners.

It may be, but the issue is definitely present in the latest release and it's not directly related to the shadows, so let's address it separately.

2021-11-17 06:07 UTC, a1exsh commented
@ihhub please find the time to have a look — I've extracted the relevant code to new subclasses of the base button class.

2021-11-21 10:55 UTC, ihhub requested changes
Hi @a1exsh , I left few more comments in this pull request. Could you please take a look at them and check if they make sense, especially from architectural point of view?

2021-11-21 10:55 UTC, ihhub commented on src/engine/image.h
> +    Sprite makeShadow( const Sprite & in, const Point & shadowOffset, const uint8_t transformValue );
Please put these functions to places to have alphabetical order of function names. You can ignore that these function names don't start from a capital letter.

2021-11-21 10:55 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                Sprite fixed( pressed.width(), pressed.height(), pressed.x(), pressed.y() );
Can we place name this variable by more understandable name? Right now `fixed` is a confusing name.

2021-11-21 10:55 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                _icnVsSprite[id][1] = fixed;
Please use `std::move` instead of copying the image.

2021-11-21 10:55 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                _icnVsSprite[id][1] = fixed;
Even better: we can directly use `_icnVsSprite[id][1]` instead of `fixed`.

2021-11-21 10:55 UTC, ihhub commented on src/fheroes2/gui/ui_button.cpp
> +    }
This portion of the code worries me a lot. We're using `ButtonSprite` class as a base class which accepts images as constructor arguments. Here we're using ICN indexes to get images which later we copy to internal ButtonSprite members and then we're overriding them with new images within `_captureBackground` method. Also it's unknown what **in** image is for.

Name `AutoBackgroundButton` is misleading. Is it a button with automated background?

The same set of remarks is applied for `AutoShadowButton` class.

I'm suggesting to just create 2 or 4 functions, each will return ButtonSprite object. For example:
```cpp
ButtonSprite generateButtonWithShadow( int32_t offsetX, int32_t offsetY, const Sprite & released, const Sprite & pressed, const Sprite & disabled, const Image & background )
{
    // Prepare images
    ... // some magic code mostly the same like in `_captureBackground` method

    return { /* ButtonSprite constructor parameters */ };
}
```

On top of this `ButtonGroup` shouldn't know about shadow thing. We can pass ButtonSprite objects to it.

What do you think @a1exsh ?

2021-11-21 14:11 UTC, a1exsh commented on src/fheroes2/gui/ui_button.cpp
> +    }
Sure, we can do it with a function instead.

The trouble with `ButtonGroup` and adding buttons to it explicitly is that the code to calculate buttons positions is not reused.  I would like us to use the shared code more.

2021-11-21 14:55 UTC, a1exsh commented on src/fheroes2/gui/ui_button.cpp
> +    }
@ihhub well, that's nearly not as easy as it sounded.  Instances of `ButtonBase` or derived classes cannot be copied, due to embedded `unique_ptr`.

With the following code
```cpp
    fheroes2::ButtonSprite btnCancel = fheroes2::makeButtonWithShadow( pos_rt.x + buttonOffset + 129, pos_rt.y + 410, fheroes2::AGG::GetICN( buttonCancelICN, 0 ),
                                                                       fheroes2::AGG::GetICN( buttonCancelICN, 1 ), display );
```
I'm getting this error:
```
../fheroes2/battle/battle_dialogs.cpp: In member function ‘bool Battle::Arena::DialogBattleSummary(const Battle::Result&, const std::vector<Artifact>&, bool) const’:
../fheroes2/battle/battle_dialogs.cpp:501:125: error: use of deleted function ‘fheroes2::ButtonSprite::ButtonSprite(const fheroes2::ButtonSprite&)’
  501 |                                                                        fheroes2::AGG::GetICN( buttonCancelICN, 1 ), display );
      |                                                                                                                             ^
In file included from ../fheroes2/battle/battle_interface.h:33,
                 from ../fheroes2/battle/battle_dialogs.cpp:31:
../fheroes2/gui/ui_button.h:99:11: note: ‘fheroes2::ButtonSprite::ButtonSprite(const fheroes2::ButtonSprite&)’ is implicitly deleted because the default definition would be ill-formed:
   99 |     class ButtonSprite : public ButtonBase
      |           ^~~~~~~~~~~~
../fheroes2/gui/ui_button.h:99:11: error: use of deleted function ‘fheroes2::ButtonBase::ButtonBase(const fheroes2::ButtonBase&)’
../fheroes2/gui/ui_button.h:30:11: note: ‘fheroes2::ButtonBase::ButtonBase(const fheroes2::ButtonBase&)’ is implicitly deleted because the default definition would be ill-formed:
   30 |     class ButtonBase : public ActionObject
      |           ^~~~~~~~~~
../fheroes2/gui/ui_button.h:30:11: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = fheroes2::Sprite; _Dp = std::default_delete<fheroes2::Sprite>]’
In file included from /usr/include/c++/10/memory:83,
                 from ../fheroes2/system/players.h:26,
                 from ../fheroes2/army/army.h:30,
                 from ../fheroes2/battle/battle_dialogs.cpp:27:
/usr/include/c++/10/bits/unique_ptr.h:468:7: note: declared here
  468 |       unique_ptr(const unique_ptr&) = delete;
      |       ^~~~~~~~~~
```

Any idea how to overcome it?

2021-11-21 14:58 UTC, ihhub commented on src/fheroes2/gui/ui_button.cpp
> +    }
Ah, we have to define move-constructor and move operator but delete copy-constructor and copy operator for ButtonSprite class.

2021-11-21 17:27 UTC, a1exsh commented on src/fheroes2/gui/ui_button.cpp
> +    }
@ihhub I managed to convince the compiler, but not sure I can convince myself the code is now better :joy: 

This is getting really out of hand, and is really outside of my C++ capabilities...

2021-11-22 14:37 UTC, ihhub commented on src/fheroes2/gui/ui_button.cpp
> +    }
We all learn something new every day :) I'll take a look.

2021-11-23 00:18 UTC, ihhub requested changes
Hi @a1exsh , I put few more comments here. I feel we're almost there. Can you please check the comments?

2021-11-23 00:18 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> +    btnGroup.createButton( buttonCancel, Dialog::CANCEL );
`createButton` method should have this signature
```cpp
void addButton( ButtonSprite && button, const int returnValue )
{
    addButton( new ButtonSprite( std::move( button ) ),  returnValue );
}
```
In this case we don't need unique_ptr usage but can directly invoke `makeButtonWithShadow` call within `addButton` method.

2021-11-23 06:46 UTC, a1exsh commented on src/engine/image.cpp
> +    void ReplaceTransform( const Image & in, Image & out )
:heavy_check_mark:

2021-11-23 06:48 UTC, a1exsh commented on src/fheroes2/gui/ui_button.cpp
> +    ButtonSprite makeButtonWithBackground( int32_t offsetX, int32_t offsetY, const Sprite & released, const Sprite & pressed /*, const Sprite & disabled*/,
Oops, I thought I got rid of that one.

2021-11-23 06:48 UTC, a1exsh commented on src/fheroes2/gui/ui_button.h
> +        ButtonSprite( ButtonSprite && o ) noexcept;
OK

2021-11-23 07:02 UTC, a1exsh commented on src/fheroes2/heroes/heroes_spell.cpp
> +    btnGroup.createButton( buttonCancel, Dialog::CANCEL );
I had the same concerns, but didn't know how to solve it — thanks! :)

2021-11-23 07:36 UTC, a1exsh commented
@ihhub it complies and works, but I will not pretend I understood this `std::move()` magic :sweat_smile:

2021-11-28 07:43 UTC, ihhub requested changes
Hi @a1exsh , I left just few more optimization related comments. Could you please check them too?

2021-11-28 07:43 UTC, ihhub commented on src/fheroes2/gui/ui_button.cpp
> +        Sprite disabledWithBackground( croppedBackground, 0, 0 );
```cpp
Sprite disabledWithBackground( std::move( croppedBackground ) );
disabledWithBackground.setPosition( 0, 0 );
```

2021-11-28 07:43 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> +    const fheroes2::Sprite & buttonCancelIcn = fheroes2::AGG::GetICN( icnId, 3 );
These aren't ICNs but images. It's good to call them `buttonOkImage` and `buttonCancelmage`.

2021-11-28 07:43 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> -    std::unique_ptr<fheroes2::StandardWindow> frameborder( new fheroes2::StandardWindow( 290, 250 ) );
I remember that was done on purpose to avoid some drawing issues. Can you please explain why are we changing it?

2021-11-28 07:43 UTC, ihhub commented on src/fheroes2/dialog/dialog_giftresources.cpp
> +    const fheroes2::Sprite & buttonCancelIcn = fheroes2::AGG::GetICN( icnId, 3 );
These aren't ICNs but images. Shall we call them `buttonOkImage` and `buttonCancelImage` respectively?

2021-11-28 07:44 UTC, ihhub commented
> @ihhub it complies and works, but I will not pretend I understood this `std::move()` magic 😅

Move semantics are used to avoid memory copy and only for objects which are going to be destroyed just after the call. This is useful when you can just swap values instead of copy them. In case of images it's essential to avoid extensive memory manipulations.

2021-11-28 11:16 UTC, a1exsh commented
> Move semantics are used to avoid memory copy and only for objects which are going to be destroyed just after the call.

Well, that is clear.  What I don't get is why in some places it's OK to just call `new ButtonSprite( ... )` and in other places you have to specify `std::move()` explicitly...

2021-11-28 11:33 UTC, a1exsh commented on src/fheroes2/heroes/heroes_spell.cpp
> -    std::unique_ptr<fheroes2::StandardWindow> frameborder( new fheroes2::StandardWindow( 290, 250 ) );
@ihhub you are right, we should not change it.  I now see why it was done, after consulting the commit history: https://github.com/ihhub/fheroes2/commit/438257c7b7f7b206c319c514d83c2d83dc3f801c

I will put it back and add a comment for the next developer who comes across it and thinks we don't need the pointer there :D

2021-11-28 11:37 UTC, a1exsh commented on src/fheroes2/dialog/dialog_giftresources.cpp
> +    const fheroes2::Sprite & buttonCancelIcn = fheroes2::AGG::GetICN( icnId, 3 );
True.  They are actually Sprites, so called them like that.

2021-11-28 11:38 UTC, a1exsh commented on src/fheroes2/gui/ui_button.cpp
> +        Sprite disabledWithBackground( croppedBackground, 0, 0 );
This does feel like a micro-optimization, but doesn't seem to hurt readability too much. ;)

2021-11-28 12:26 UTC, ihhub commented
> Well, that is clear. What I don't get is why in some places it's OK to just call `new ButtonSprite( ... )` and in other places you have to specify `std::move()` explicitly...

std::move enforces in some sense to end object's lifetime within your code block. If you don't do this then you're passing by normal reference rather than by r-value.

2021-11-28 12:27 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> -    std::unique_ptr<fheroes2::StandardWindow> frameborder( new fheroes2::StandardWindow( 290, 250 ) );
Great!

2021-11-28 12:28 UTC, ihhub commented on src/fheroes2/gui/ui_button.cpp
> +        Sprite disabledWithBackground( croppedBackground, 0, 0 );
Haha. It's actually a huge performance boost as we don't make system calls to allocate and free memory on stack.

2021-11-28 12:31 UTC, ihhub approved these changes

2021-11-28 12:31 UTC, ihhub commented
@Branikolog please retest the latest build again as we changed a lot of internal code.

2021-12-02 07:27 UTC, a1exsh commented
appveyor build failed with an internal error, please re-trigger:
```
MSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure.
Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure. ---> Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
```

2021-12-03 00:13 UTC, merged

2021-12-03 00:14 UTC, ihhub commented
@a1exsh , a huge thanks for these changes!