Clarifying messages in battle mode
ihhub/fheroes2 pull request #4456
Opened 2021-10-19 14:00 UTC by pflugs30

Fixes #4416.  Changes:
- Standardized temporary popup messages for battles

2021-10-29 18:15 UTC, pflugs30 commented
@LeHerosInconnu or @1GodRage, I just pushed [a new commit](https://github.com/ihhub/fheroes2/pull/4456/commits/eb242406ac08ade286cf5df6f6b78574c21b69cc) with your suggested changes.  I did my best to carefully copy and paste, but would you mind taking a quick look?  Thanks!

@zenseii I've made some changes to the dialog boxes, in case you're interested in adding the Norwegian translation.

2021-10-30 10:00 UTC, LeHerosInconnu commented
Hello @pflugs30,

> @LeHerosInconnu or @1GodRage, I just pushed [a new commit](https://github.com/ihhub/fheroes2/pull/4456/commits/eb242406ac08ade286cf5df6f6b78574c21b69cc) with your suggested changes. I did my best to carefully copy and paste, but would you mind taking a quick look? Thanks!

Everything seems fine.

2021-10-30 11:38 UTC, zenseii commented
> @zenseii I've made some changes to the dialog boxes, in case you're interested in adding the Norwegian translation.

I will make the necessary changes to the Norwegian file and send them.

2021-10-31 13:56 UTC, pflugs30 commented
@ihhub update after looking at this again today:

* We've completed the French translations.
* @zenseii is working on the Norwegian translations.
* We still need the Polish and Russian translations.

Similar to #4436, can I get some help from @Arthusppp and @undef21, please?

2021-10-31 15:59 UTC, pflugs30 commented on files/lang/fr.po
> +msgid "Set the speed of combat actions and animations."
@LeHerosInconnu or @1GodRage, may I please get your review on [this file](https://github.com/ihhub/fheroes2/pull/4456/files#diff-4ee85dc130f9a8eb2b6b1b90466d98625cd6ec5d042e512d7fba57fa7f82c823)?

2021-10-31 15:59 UTC, pflugs30 commented on files/lang/pl.po
> +msgid "Set the speed of combat actions and animations."
@undef21 May I please have your review on these translations?  thank you.

2021-10-31 15:59 UTC, pflugs30 commented on files/lang/pl.po
> +msgid "Set the speed of combat actions and animations."
I'm sorry, I may have made a mistake.  @Arthusppp , I believe you did the last Polish review for me?

2021-10-31 15:59 UTC, pflugs30 commented on files/lang/ru.po
> +msgid "Set the speed of combat actions and animations."
@undef21 May I please have your review on these translations?  thank you.

2021-10-31 19:35 UTC, Arthusppp commented
Hello @pflugs30, 

The "Auto Spell Casting" is used in two contexts: Battle::DialogBattleSettings and Battle::RedrawBattleSettings (both in the battle_dialogs.cpp). 
My concern is that currently I have in the po file:

> msgid "Auto Spell Casting"
> msgstr "Automatyczne rzucanie zaklęć"

And in the OG this text is very short:

![image](https://user-images.githubusercontent.com/85434237/139598706-e90769b8-845a-4adc-879c-f8ea3b93b2fa.png)


Should I worry? Should we have two translations here?

2021-10-31 23:35 UTC, Arthusppp commented
@pflugs30 Polish translation updated in the https://github.com/pflugs30/fheroes2/pull/7.

2021-11-01 16:35 UTC, pflugs30 commented on files/lang/pl.po
> +msgid "Set the speed of combat actions and animations."
@Arthusppp, thanks for your translations.  I added them in [this commit](https://github.com/ihhub/fheroes2/pull/4456/commits/7dc2506ff6442ebb0a7ec8be8891887d453ac00a).

2021-11-01 17:50 UTC, undef21 commented on files/lang/ru.po
> +msgid "Set the speed of combat actions and animations."
[Here](https://github.com/pflugs30/fheroes2/pull/8)

2021-11-01 18:11 UTC, pflugs30 commented on files/lang/ru.po
> +msgid "Set the speed of combat actions and animations."
Thank you!

2021-11-01 18:26 UTC, pflugs30 commented on files/lang/fr.po
> +#, fuzzy
@LeHerosInconnu or @1GodRage, may I please get your review on this line?

2021-11-01 18:26 UTC, pflugs30 commented on files/lang/fr.po
> +msgid "Select spell target"
@LeHerosInconnu or @1GodRage, may I please get your review on lines 414 through 471?  I think I must have missed those in your first pass.

2021-11-02 06:07 UTC, 1GodRage requested changes
> msgstr "Le lâche %{name} fuit la bataille."

Le -> Le or La, depends the gender of the Hero.


> msgid "As you reach for the %{name}, it mysteriously disappears."
> msgstr ""
"Alors que vous vous approchez de l'artéfact, il disparait mystérieusement."
or, if we have "**du/de la/des**" inside the %{name}:
"Alors que vous vous approchez %{name}, il disparait mystérieusement."

> msgid "As your enemy reaches for the %{name}, it mysteriously disappears."
>msgstr ""
 if we have "**le/la/les/l'**" inside the %{name}:
msgstr "Tandis que votre ennemi atteint %{name}, il disparait mystérieusement."
or, if we have "**du/de la/des**" inside the %{name}:
msgstr "Tandis que votre ennemi s'approche %{name}, il disparait mystérieusement."

msgid "You have captured an enemy artifact!"
msgstr "Vous avez capturé un artéfact ennemi !"
Both English and French sounds like the artifact is the enemy... if it's the artifact from enemy, the sentence will be:
"Vous avez capturé un artéfact de l'ennemi !"


> msgid "%{name} the %{race}"
> msgstr "%{name} le %{race}"
"le" --> le/la/l' depends on gender and on the name of the race.

2021-11-02 06:07 UTC, 1GodRage commented on files/lang/fr.po
>  msgstr "Ombre de mouvement"
"Ombre : déplacements" would be a better wording. :)

2021-11-02 06:07 UTC, 1GodRage commented on files/lang/fr.po
>  msgstr "Curseur d'ombre"
"Ombre : curseur" then makes senses. :)
or "Ombre du curseur"
or "Ombre : hexagone présélectionné" ... but I guess it must remains short wording. ^^'

I would put "Ombre : curseur", the descriptions will make sense of it. :)

2021-11-02 11:23 UTC, LeHerosInconnu commented on files/lang/fr.po
>  msgstr "Ombre de mouvement"
Hello @1GodRage,

> "Ombre : déplacements" would be a better wording. :)

I think that to avoid the colon ":" it would be better to write:

"Ombre du déplacement"

2021-11-02 11:23 UTC, LeHerosInconnu commented on files/lang/fr.po
>  msgstr "Curseur d'ombre"
Hello @1GodRage,

> "Ombre : curseur" then makes senses. :) or "Ombre du curseur" or "Ombre : hexagone présélectionné" ... but I guess it must remains short wording. ^^'
> 
> I would put "Ombre : curseur", the descriptions will make sense of it. :)

Same here, to avoid the colon ":" it would be better to write as you suggested :

"Ombre du curseur"

2021-11-02 11:27 UTC, LeHerosInconnu commented on files/lang/fr.po
> +msgid "Select spell target"
Hello @pflugs30,

> @LeHerosInconnu or @1GodRage, may I please get your review on lines 414 through 471? I think I must have missed those in your first pass.

426 msgid "Allows the computer to fight out the battle for you."
msgstr "L'ordinateur joue le combat à votre place."

436 msgid "Allows you to customize the combat screen."
msgstr "Modifier les options de l'écran de combat."

msgid "Waits the current creature. The current creature delays its turn until after all other creatures have had their turn."
msgstr "Le peloton actif reporte son tour jusqu'à ce que tous les autres pelotons aient joué leur tour."

445 msgid "Skip"
msgstr "Passer"

msgid "Skips the current creature. The current creature ends its turn and does not get to go again until the next round."
msgstr "Le peloton actif passe son tour et ne peut pas jouer avant le prochain tour."

2021-11-02 14:24 UTC, pflugs30 commented
@LeHerosInconnu or @1GodRage, thanks for the translations.  I've submitted them in [this commit](https://github.com/ihhub/fheroes2/pull/4456/commits/8182083b316b2bd58682cba168d27344c653eb4d).

There are two other phrases for which I could use a translation, please;

1. View Hero's options
2. Enable auto combat

Once we have these two, then this PR can be done!

2021-11-02 16:48 UTC, LeHerosInconnu commented
@pflugs30.

> @LeHerosInconnu or @1GodRage, thanks for the translations. I've submitted them in [this commit](https://github.com/ihhub/fheroes2/pull/4456/commits/8182083b316b2bd58682cba168d27344c653eb4d).
> 
> There are two other phrases for which I could use a translation, please;
> 
> 1. View Hero's options

"Voir les options du héros"

> 2. Enable auto combat

"Activer le combat automatique"

2021-11-02 18:46 UTC, pflugs30 commented
> @pflugs30.
> 
> > @LeHerosInconnu or @1GodRage, thanks for the translations. I've submitted them in [this commit](https://github.com/ihhub/fheroes2/pull/4456/commits/8182083b316b2bd58682cba168d27344c653eb4d).
> > There are two other phrases for which I could use a translation, please;
> > 
> > 1. View Hero's options
> 
> "Voir les options du héros"
> 
> > 1. Enable auto combat
> 
> "Activer le combat automatique"

Thank you!  That should close out all questions on the French translations.

2021-11-02 18:47 UTC, pflugs30 commented
@ihhub I'm thrilled to say this PR should now be ready for merging, pending the successful CI/CD pipeline completions.  We've received final approval from our French, Polish, Russian, and Norwegian translators.  At least one other PR is waiting the merge of this PR so that they can do additional translation work, too.

Great work, team!

2021-11-05 16:03 UTC, merged

2021-11-05 16:03 UTC, ihhub commented
Good job @pflugs30 ! Thanks for these changes!