Add missing gettext translation calls and update POs
ihhub/fheroes2 pull request #4525
Opened 2021-10-31 03:38 UTC by zenseii

Gettext calls to several strings have been added to enable translation. 

Marking this as draft since I still need to finish updating all POs. Also, because I am not sure the chosen solution for a certain line is the best (edit upcoming). 

Several strings were changed to use the newer `fheroes2::Text` and some of the files needed the added headers `ui_text.h` and `translations.h`.

Other minor changes are: Initial upper case for single-worded strings like `need: `,  `min` etc.

2021-11-08 14:00 UTC, zenseii commented
Alright, @ihhub, this PR is now ready for review.

2021-11-08 14:26 UTC, ihhub requested changes
Hi @zenseii , I left several minor comments here, some of them are related to the old code. Can you please check them and see if they make sense?

2021-11-08 14:26 UTC, ihhub commented on src/fheroes2/battle/battle_only.cpp
> +    message.append( " " );
Please use `message += ' ';` instead as **" "** is 2 symbols while **' '** is just one so it's faster.

2021-11-08 14:26 UTC, ihhub commented on src/fheroes2/battle/battle_only.cpp
> +    message.append( " " );
Please use `message += ' ';` instead as **" "** is 2 symbols while **' '** is just one so it's faster.

2021-11-08 14:26 UTC, ihhub commented on src/fheroes2/dialog/dialog_armyinfo.cpp
> +    TextSprite tsTotal( std::to_string( gold ) + " " + "(" + _( "Total: " ) + std::to_string( world.GetKingdom( hero.GetColor() ).GetFunds().Get( Resource::GOLD ) )
Can we please combine `" " + "("` into`" ("` since we're touching this code?

2021-11-08 14:26 UTC, ihhub commented on src/fheroes2/dialog/dialog_chest.cpp
> +    text.Set( std::to_string( gold ) + " " + "(" + _( "Total: " ) + std::to_string( world.GetKingdom( hero.GetColor() ).GetFunds().Get( Resource::GOLD ) ) + ")",
Can we please combine `" " + "("` into`" ("` since we're touching this code?

2021-11-08 14:26 UTC, ihhub commented on src/fheroes2/dialog/dialog_chest.cpp
> +    text.Set( std::to_string( expr ) + " " + "(" + _( "Need: " ) + std::to_string( Heroes::GetExperienceFromLevel( hero.GetLevel() ) - hero.GetExperience() ) + ")",
Can we please combine `" " + "("` into`" ("` since we're touching this code?

2021-11-08 14:26 UTC, ihhub commented on src/fheroes2/battle/battle_only.cpp
> +#include "ui_text.h"
if we use new `fheroes2::Text` over old `Text` class should we then remove **#include "text.h"** file inclusion?

2021-11-08 14:26 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
>  #include "text.h"
if we use new `fheroes2::Text` over old `Text` class should we then remove **#include "text.h"** file inclusion?

2021-11-09 00:07 UTC, merged

2021-11-09 00:07 UTC, ihhub commented
@zenseii , well done! Thank you so much for these changes!

2022-01-21 19:23 UTC, Arthusppp commented on files/lang/pl.po
> +#, fuzzy
:(