Allow to use mouse wheel to change system options
ihhub/fheroes2 pull request #4553
Opened 2021-11-04 18:32 UTC by a1exsh

Mouse wheel is enabled on the following options:

- Music
- Effects
- Hero Speed
- AI Speed
- Scroll Speed

Any adjustments made using the wheel do not wrap over max. value, as opposed
to clicking.  Clicking still works as before.

Also unify the value wrapping math.

2021-11-05 16:08 UTC, ihhub requested changes
Hi @a1exsh , I left one comment here. Could you please take a look?

2021-11-05 16:08 UTC, ihhub commented on src/fheroes2/dialog/dialog_system_options.cpp
> +                }
Shouldn't we combine these two conditions (through logical OR) as they're doing the same thing?

I think the same question for the rest of options.

2021-11-05 17:33 UTC, a1exsh commented on src/fheroes2/dialog/dialog_system_options.cpp
> +                }
Not exactly: clicking wraps over max value, while scrolling doesn't.

See the linked discussion, maybe we change the behavior as the outcome, then we could simplify the code here. But I do like the implemented behavior better without wrapping on scroll. ;)

2021-11-07 05:08 UTC, ihhub commented on src/fheroes2/dialog/dialog_system_options.cpp
> +                }
Got it. Thanks for the explanation!

2021-11-07 05:18 UTC, merged

2021-11-07 05:19 UTC, ihhub commented
@a1exsh , thanks a lot for this improvement!