Set starting army in Archibald 7 scenario
ihhub/fheroes2 pull request #4560
Opened 2021-11-06 11:37 UTC by a1exsh

Fix #4379

2021-11-06 11:38 UTC, a1exsh commented
Here is just a very dirty hack to make it work.  I don't see a suitable bonus type or an award that could help us here (unless we abuse "carry over troops" somehow).

I'm now wondering if maybe the starting army is part of the map file, but just don't use this data?

2021-11-06 11:40 UTC, zenseii commented
> I'm now wondering if maybe the starting army is part of the map file, but we just don't use this data?

I can check this for you quickly with the OG editor if you want?

2021-11-06 11:42 UTC, a1exsh commented
> I can check this for you quickly with the OG editor if you want?

How do you open campaign maps in OG editor?  The map file is called `CAMPE07.H2C` and the title is `Evil 7`, which I don't see in the list in my editor.  Is there a trick?

2021-11-06 11:43 UTC, zenseii commented
> How do you open campaign maps in OG editor? The map file is called `CAMPE07.H2C` and the title is `Evil 7`, which I don't see in the list in my editor. Is there a trick?

Yep, just rename the .H2C to .mp2 and you're good. So this specific becomes: CAMPE07.mp2

2021-11-06 11:44 UTC, a1exsh commented
> Yep, just rename the .H2C to .mp2 and you're good. 

Thanks, will give it a try :D

2021-11-06 11:49 UTC, a1exsh commented
Doesn't look like the army is set in the editor — there is just random town and hero, no special army (maybe it's still part of the file, but not something that editor exposes).

2021-11-06 13:57 UTC, ihhub commented
> 
> 
> Doesn't look like the army is set in the editor — there is just random town and hero, no special army (maybe it's still part of the file, but not something that editor exposes).

No, the army is set within the game.

2021-11-06 15:05 UTC, a1exsh commented
> No, the army is set within the game.

@ihhub alright.  Do you maybe have a suggestion how to organize the code better?  I'm thinking, could we make the starting army an optional field in the `STARTING_RACE` bonus?  We also don't need to save the army to the file, I guess, as it only matters when starting the scenario — the file format can be kept as is.

2021-11-06 15:28 UTC, a1exsh commented
Note to self: the starting hero characteristics should be also part of the bonus, not only the army.

2021-11-06 15:57 UTC, ihhub commented
> 
> 
> > No, the army is set within the game.
> 
> @ihhub alright. Do you maybe have a suggestion how to organize the code better? I'm thinking, could we make the starting army an optional field in the `STARTING_RACE` bonus? We also don't need to save the army to the file, I guess, as it only matters when starting the scenario — the file format can be kept as is.

Yes, it's good to add a new Bonus type called `STARTING_RACE_AND_ARMY` (or something more human readable) which will have the same code as this:
```cpp
case ScenarioBonusData::STARTING_RACE:
    objectName = Race::String( _subType );
    break;
```

Then add logic inside `void SetScenarioBonus( const Campaign::ScenarioBonusData & scenarioBonus )` and modify `std::vector<Campaign::ScenarioBonusData> getArchibaldCampaignBonusData( const int scenarioID )` function to use newly added type. However, the structure of bonuses doesn't allow us to add multiple monsters as well as hero stats so we hardcode these values within `SetScenarioBonus` (or within another function which is called from this function).

I think it make the code clean.

2021-11-06 16:48 UTC, a1exsh commented
> Yes, it's good to add a new Bonus type called STARTING_RACE_AND_ARMY

Tried that.

> I think it make the code clean.

Didn't happen so far :)  There is an additional trouble that setting the race has to be done before starting the game, but adding army to the best player's hero — after.  Either we will end up calling `SetScenarioBonus` twice, or we need to call a different function for setting the army.

2021-11-08 04:43 UTC, ihhub requested changes
Hi @a1exsh , I left several comments here. Would you mind to take a look?

2021-11-08 04:43 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +        for ( uint32_t i = 0; i < troops.size(); ++i )
Please use `size_t` here as **size()** returns such type.

2021-11-08 04:43 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +                uint32_t exp = hero->GetExperience();
Please make this variable `const` as we don't modify it.

2021-11-08 04:43 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +        switch ( campaignID ) {
This switch case requires at least **default** case. Please add it with an assertion to remind a future developer to add appropriate logic.

2021-11-08 04:43 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +            case 6:
I think switch for this case is not needed. We can do like this:
```cpp
// Only one scenario in Archibald campaign has this bonus.
if ( currentScenarioID != 6 ) {
    return;
}
```

2021-11-08 04:43 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +                replaceArmy( hero->GetArmy(), startingTroops );
I think we can do like this:
```cpp
switch ( hero->GetRace() ) {
case Race::NECR:
    replaceArmy( hero->GetArmy(), { { Monster::SKELETON, 50 }, { Monster::ROYAL_MUMMY, 18 }, { Monster::VAMPIRE_LORD, 8 } } );
    break;
case Race::WRLK:
    replaceArmy( hero->GetArmy(), { { Monster::CENTAUR, 40 }, { Monster::GARGOYLE, 24 }, { Monster::GRIFFIN, 18 } } );
    break;
case Race::BARB:
    replaceArmy( hero->GetArmy(), { { Monster::ORC_CHIEF, 12 }, { Monster::OGRE, 18 }, { Monster::GOBLIN, 40 } } );
    break;
default:
    assert( 0 ); // bonus changed?
}
```
In this case the lifetime of std:;vector will be much shorter.

2021-11-08 04:43 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
>                  }
I think this will break one of scenarios as best hero is not always the last one.

2021-11-08 07:57 UTC, a1exsh commented on src/fheroes2/game/game_campaign.cpp
> +        for ( uint32_t i = 0; i < troops.size(); ++i )
Hm, sure, but I wonder why do we have clang-tidy robot and it doesn't report this (but tends to find all sorts of non-issues) ;)

2021-11-08 08:00 UTC, a1exsh commented on src/fheroes2/game/game_campaign.cpp
> +                replaceArmy( hero->GetArmy(), startingTroops );
Ah, vector literals: that's a really nice trick, thank you! :)

2021-11-08 08:02 UTC, a1exsh commented on src/fheroes2/game/game_campaign.cpp
>                  }
OK, will change it back.  I just had the impression that all cases in this function were added independently without looking at the rest, so it became quite messy: tried to clean it up.

2021-11-08 13:48 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +                const Campaign::ScenarioBonusData temp( Campaign::ScenarioBonusData::STARTING_RACE, scenarioBonus._subType, scenarioBonus._amount );
Just a small correction: should we name this variable as **tempBonus**?

2021-11-08 17:20 UTC, a1exsh commented on src/fheroes2/game/game_campaign.cpp
> +                const Campaign::ScenarioBonusData temp( Campaign::ScenarioBonusData::STARTING_RACE, scenarioBonus._subType, scenarioBonus._amount );
I've removed it completely: no need to improve the name if it doesn't have one ;)

2021-11-09 00:03 UTC, merged

2021-11-09 00:03 UTC, ihhub commented
@a1exsh , good job and keep it up!