Load palette from AGG file
ihhub/fheroes2 pull request #4584
Opened 2021-11-08 15:54 UTC by ihhub

icn2img tool now requires original kb.pal file.

The solution is not ideal as Display class needs valid palette at the initialization.

2021-11-08 18:52 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few suggestions here, please take a look when you have a free time.

2021-11-08 18:52 UTC, oleg-derevenetz commented on src/engine/image_palette.cpp
> +        std::array<uint8_t, 768> gamePalette;
I'd suggest to do this as follows:

```
constexpr size_t paletteSize = 768;
[...]
std::array<uint8_t, paletteSize> gamePalette;
```

2021-11-08 18:52 UTC, oleg-derevenetz commented on src/tools/icn2img.cpp
> +    std::string intpuFileName( argv[1] );
I suppose there is a typo: `intpuFileName` -> `inputFileName`.

2021-11-09 13:03 UTC, ihhub commented on src/engine/image_palette.cpp
> +        std::array<uint8_t, 768> gamePalette;
Ah, yes. I missed it after third work redo...

2021-11-10 07:22 UTC, a1exsh commented on src/engine/screen.cpp
> +    const uint8_t * PALPalette()
Any chance to keep only this function or the one with the same name from `image_tool.cpp`?

2021-11-10 07:31 UTC, a1exsh reviewed
@ihhub please have a look on my comments when you have time. :)

2021-11-10 07:31 UTC, a1exsh commented on src/tools/icn2img.cpp
> +    if ( argc < 4 ) {
```suggestion
    if ( argc != 4 ) {
```

Extra parameters should not be accepted either.

2021-11-10 07:31 UTC, a1exsh commented on src/tools/icn2img.cpp
> +    fheroes2::setGamePalette( palette );
I'd pass palette as a parameter to `SaevImage()` rather than relying on the global value.

2021-11-10 07:31 UTC, a1exsh commented on src/tools/icn2img.cpp
> -                fs << " <sprite index=\"" << ii + 1 << "\" name=\"" << shortdstfile.c_str() << "\" ox=\"" << head.offsetX << "\" oy=\"" << head.offsetY << "\"/>"
I know nobody likes XML, but the offset information is important for loading the sprites back to the game from a set of images: we should not just discard it.  Maybe just print it on the console so that the user can capture it to a text file?

2021-11-11 14:42 UTC, ihhub commented on src/tools/icn2img.cpp
> +    fheroes2::setGamePalette( palette );
The original palette is not suitable for this. All values in this palette are in 4 times smaller they should be.

2021-11-11 15:23 UTC, a1exsh commented on src/tools/icn2img.cpp
> +    fheroes2::setGamePalette( palette );
I'm not sure you got my point. Currently, the result of calling SaveImage depends on the globally set palette. I suggest to pass it as a parameter to SaveImage instead of using the global definition (relying on side-effects).

2021-11-11 16:03 UTC, ihhub commented on src/engine/screen.cpp
> +    const uint8_t * PALPalette()
icn2img tool shouldn't even have an access to screen code. We have to remove such dependency. Also this function has a static member while image_tool's doesn't. This function must be removed completely but as stated in the description of this pull request we still have a problem on using palette before even reading it.

The purpose of this pull request is to remove `palette_h2.h` completely as it must not belong to this project.

2021-11-11 16:12 UTC, ihhub commented
Hi @a1exsh , please take a look an my answers as well as I addressed some of your comments.

2021-11-11 17:07 UTC, a1exsh reviewed
Spotted two small issues: please have a look.

2021-11-11 17:07 UTC, a1exsh commented on fheroes2-vs2015.vcxproj
> +	<ClInclude Include="src\engine\image_palette.h" />
Is this a TAB char? ;)

2021-11-11 17:07 UTC, a1exsh commented on src/tools/icn2img.cpp
> +            std::cout << "Image " << ii + 1 << " has offset of [" << head.offsetX << ", " << head.offsetY << "]" << std::endl;
```suggestion
            std::cout << "Image " << ii + 1 << " has offset of [" << static_cast<int32_t>( head.offsetX ) << ", " << static_cast<int32_t>( head.offsetY ) << "]" << std::endl;
```
Otherwise negative offsets look really funny (-1 becomes 65535 and so on) ;)

2021-11-13 14:08 UTC, merged