Fix peasant damage in well
ihhub/fheroes2 pull request #4600
Opened 2021-11-09 16:50 UTC by zenseii

This currently only affects peasants.

OG:
![image](https://user-images.githubusercontent.com/12501091/140966724-7729aee6-4a9c-4c47-9c24-fd1cf7dec8fd.png)

fheroes2:
![image](https://user-images.githubusercontent.com/12501091/140966841-694292f5-4759-499b-a93e-dfb94b3858bb.png)

This is most likely why Damage is written "Damg" in OG:
OG:
![image](https://user-images.githubusercontent.com/12501091/140967430-71de11da-5c31-4d6a-b0e0-29bb70104ddb.png)
fheroes2:
![image](https://user-images.githubusercontent.com/12501091/140967182-d6d550bc-e5ba-41b9-87ee-62a806cb7fbc.png)

2021-11-10 13:44 UTC, ihhub requested changes

2021-11-10 13:44 UTC, ihhub commented on src/fheroes2/castle/castle_well.cpp
> +
Since we touched this code I'd suggest to do some optimization to avoid extra memory copying:
```cpp
str = _( "Damg" );
str += ": ";

const uint32_t monsterMinDamage = monster.GetDamageMin();
const uint32_t monsterMaxDamage = monster.GetDamageMax();

str += std::to_string( monsterMinDamage );

if ( monsterMinDamage != monsterMaxDamage ) {
    str += '-';
    str += std::to_string( monsterMaxDamage );
}
```

What do you think?

2021-11-10 14:16 UTC, zenseii commented on src/fheroes2/castle/castle_well.cpp
> +
Yes, this much better.

2021-11-11 06:05 UTC, zenseii commented
@ihhub I see that this code optimization can be applied for more of the strings for the well so I'll extend the scope of this PR to change those as well and while I'm at it I'll replace `text.h` with `ui_text.h.`

2021-11-11 15:03 UTC, ihhub requested changes
Hi @zenseii , I put few comments here. I didn't repeat them to avoid polluting this pull request. Could you please take a look?

2021-11-11 15:03 UTC, ihhub commented on src/fheroes2/castle/castle_well.cpp
>          std::string str;
Please move the declaration of this variable to line 341 just where we assign the value to it.

2021-11-11 15:03 UTC, ihhub commented on src/fheroes2/castle/castle_well.cpp
> +
Please remove this empty line.

2021-11-11 15:03 UTC, ihhub commented on src/fheroes2/castle/castle_well.cpp
> +        str += std::to_string( monsterAttack );
This variable is used only in the line below. Please use the call directly to avoid extra memory copy.

2021-11-11 15:03 UTC, ihhub commented on src/fheroes2/castle/castle_well.cpp
> +        int32_t statsOffsetY = statsInitialOffsetY;
Please move these variable declaration just before the place where they used. It is much easier to read the code when declaration follows by usage.

2021-11-12 14:04 UTC, ihhub requested changes
Hi @zenseii , I left one more comment here. Could you please take a look again?

2021-11-12 14:21 UTC, zenseii commented on src/fheroes2/castle/castle_well.cpp
> +                    Dialog::Message( "", _( "Not enough resources to buy monsters." ), int( fheroes2::FontSize::LARGE ), Dialog::OK );
An alternative could be to write "2" instead of Font::BIG so you don't have to include text.h just for this. Not optimal, but I imagine it is not as error prone.

2021-11-12 15:20 UTC, merged

2021-11-12 15:24 UTC, zenseii commented
You're welcome and thank you for taking the time and having the patience to go through this noob code! 😅