Refactoring of code
ihhub/fheroes2 pull request #4607
Opened 2021-11-11 07:21 UTC by Vaskozlov

For loops modernization.
Some methods are inlined.

2021-11-11 08:07 UTC, oleg-derevenetz commented
Hi @Vaskozlov

> Some methods are inlined.

This is useless in cases that I see in this PR because all methods defined inside a class definition are implicitly `inline` (and meaning of `inline` keyword in C++ have nothing in common with code inlining BTW).

2021-11-11 08:25 UTC, Vaskozlov commented
> Hi @Vaskozlov
> 
> > Some methods are inlined.
> 
> This is useless in cases that I see in this PR because all methods defined inside a class definition are implicitly `inline` (and meaning of `inline` keyword in C++ have nothing in common with code inlining BTW).

Fixed

2021-11-11 09:47 UTC, Vaskozlov commented
Sorry, I have forgotten to enable clang-format :(

2021-11-11 14:52 UTC, ihhub requested changes
Hi @Vaskozlov , I left few comments here. Could you please explain the benefit of changing loops to range loops except code cleanup and not using `auto`?

2021-11-11 14:52 UTC, ihhub commented on src/engine/image.h
> +            return _data.get() + static_cast<ptrdiff_t>( width() * height() );
`std::ptrdiff_t` is int32_t for 32-bit systems and int64_t for 64-bit systems. Can you please explain why do we need this static casting?

2021-11-11 14:52 UTC, ihhub commented on src/engine/pal.cpp
> +    for ( const auto & it : set ) {
**it** name is used only for iterators. Please change it to more human-readable one. Also we don't recommend auto unless it's an iterator as it impacts code readability (and not only). This is range loop so we're dealing with non-iterators. The same comment applies for all other places which were changed.

2021-11-11 14:52 UTC, ihhub commented on src/engine/image.h
> +            return _data.get() + static_cast<ptrdiff_t>( width() * height() );
Also these 2 methods were left non-inlined by purpose as it's done for `image` methods. There could be a benefit to make them inlined but we don't have places where we extensively call these methods.

2021-11-12 16:17 UTC, ihhub commented
Hi @Vaskozlov , could you please answer previous asked question: what's the benefit of these changes besides making code beautification? We're fully aware that there are many places which are written badly but we should **not** focus on just rewriting them. We have a plenty of bugs in the code and normally a developer who is working on a certain issue might do needed code beautification or when a new architecture code design is needed. I feel that change iterator-based loop to range loops brings no value to the project right now because reviewers must spend time checking these changes.

Also please do **not** add any new changes after a pull request review has been started. A reviewer in this case will have to redo all the work.

2021-11-12 17:35 UTC, Vaskozlov commented
Again I have broken something. This time I have stage own cmake file. I am sorry for making so many stupid things. I will chat with ihhub to fix problems.

2021-11-12 17:37 UTC, Vaskozlov commented
> Again I have broken something. This time I have staged own cmake file. I am sorry for making so many stupid things. I will chat with ihhub to fix problems.

2021-11-13 16:09 UTC, ihhub commented
Hi @Vaskozlov , I think this pull request going to be even bigger :) Why don't we take step back and do things one by one. I'd recommend to start with easy approach and keep only inlined function changes in this pull request and then we can create another pull request for other changes. What do you think?

2021-11-18 17:03 UTC, Vaskozlov commented
> Hi @Vaskozlov , I think this pull request going to be even bigger :) Why don't we take step back and do things one by one. I'd recommend to start with easy approach and keep only inlined function changes in this pull request and then we can create another pull request for other changes. What do you think?

Hello, I am a little bit busy this week. What shall I do with this pull request? Should I revoke some of the changes and leave only inlined function? Or what else should I do?

2021-11-20 15:20 UTC, ihhub commented
> > Hi @Vaskozlov , I think this pull request going to be even bigger :) Why don't we take step back and do things one by one. I'd recommend to start with easy approach and keep only inlined function changes in this pull request and then we can create another pull request for other changes. What do you think?
> 
> Hello, I am a little bit busy this week. What shall I do with this pull request? Should I revoke some of the changes and leave only inlined function? Or what else should I do?

Yes. Let's focus in this pull request only on inlined functions.

2021-11-22 14:34 UTC, ihhub requested changes
Hi @Vaskozlov, I left multiple comments in this pull request. We can grouped required changes into few categories:
- revert all changes related to code style
- all methods with static variable must have implementation in source file
- don't move function declarations to other places
- remove **void** as an input argument only from modified functions

Can you please take a look?

2021-11-22 14:34 UTC, ihhub commented on src/engine/localevent.h
> -    bool KeyPress() const;
Please don't move methods to other places. Add the method's body right here. This eases code change tracking.

2021-11-22 14:34 UTC, ihhub commented on src/engine/pal.cpp
> +        static const std::vector<CyclingColorSet> cycleSet = { { 0xD6, 4, false }, { 0xDA, 4, false }, { 0xE7, 5, true }, { 0xEE, 4, false } };
Please revert this file as it's just code style, which is unrelated to inline functions.

2021-11-22 14:34 UTC, ihhub commented on src/engine/system.cpp
> +// shellapi.h must be included after windwos.h
Misspelled `windwos.h`.

2021-11-22 14:34 UTC, ihhub commented on src/fheroes2/game/game_interface.cpp
> -}
This method **must** have implementation within source file as it contains static object.

2021-11-22 14:34 UTC, ihhub commented on src/fheroes2/game/game_interface.h
> +        }
Please revert the changes for this method.

2021-11-22 14:34 UTC, ihhub commented on src/fheroes2/game/game_interface.h
> -        const fheroes2::Rect & GetScrollBottom( void ) const;
Please put the body of each method within it's declaration. Don't move them around as it complicates code changes tracking.

2021-11-22 14:34 UTC, ihhub commented on src/fheroes2/game/game_interface.h
> +        const fheroes2::Rect & GetScrollLeft( void ) const
Since we touched these methods please remove **void** as input argument only from modified functions. We want to keep changes minimal.

2021-11-22 14:34 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> -            other_hero->IncreaseExperience( res.GetExperienceDefender() );
Revert changes in this file. They don't belong to inlined functions.

2021-11-22 14:34 UTC, ihhub commented on src/fheroes2/heroes/skill.cpp
> -        = {Secondary::PATHFINDING, Secondary::ARCHERY,   Secondary::LOGISTICS, Secondary::SCOUTING,   Secondary::DIPLOMACY, Secondary::NAVIGATION, Secondary::LEADERSHIP,
Please revert changes in this file.

2021-11-22 14:34 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> -            = {Resource::WOOD, Resource::ORE, Resource::MERCURY, Resource::SULFUR, Resource::CRYSTAL, Resource::GEMS, Resource::GOLD, Resource::UNKNOWN};
Please revert changes in this file.

2021-11-22 14:34 UTC, ihhub commented on src/fheroes2/system/settings.h
> +    }
This method must have implementation in source file.

2021-11-23 13:23 UTC, Vaskozlov commented
> Hi @Vaskozlov, I left multiple comments in this pull request. We can grouped required changes into few categories:
> 
>     * revert all changes related to code style
> 
>     * all methods with static variable must have implementation in source file
> 
>     * don't move function declarations to other places
> 
>     * remove **void** as an input argument only from modified functions
> 
> 
> Can you please take a look?

OK

2021-11-23 13:33 UTC, Vaskozlov commented on src/fheroes2/kingdom/kingdom.cpp
> +        const static int resources[]
At the moment it is not static anymore, however it should be. If it is not static, compiler allocates memory on the stack and copies values to it.

2022-01-06 04:29 UTC, ihhub approved these changes

2022-01-06 11:23 UTC, oleg-derevenetz approved these changes
LGTM with one minor note (more like surprise) :)

2022-01-06 11:23 UTC, oleg-derevenetz commented on src/fheroes2/game/game_interface.cpp
> +#include "game_interface.h"
Funny, how the `clang-format` passed this? :) Usually it requires an alphabetical order of inclusion.

2022-01-06 11:56 UTC, ihhub commented on src/fheroes2/game/game_interface.cpp
> +#include "game_interface.h"
The header of the source file always goes first.

2022-01-06 11:56 UTC, merged

2022-01-06 11:56 UTC, ihhub commented
@Vaskozlov , thank you very much for your contribution to the project!