Fix max music/sound volume
ihhub/fheroes2 pull request #4609
Opened 2021-11-11 07:57 UTC by a1exsh

1. The max value is 10, but we were going only up to 9 previously.
2. Move min/max logic from dialog to settings (it was partially there already).

2021-11-11 14:56 UTC, ihhub requested changes
Hi @a1exsh , I left just 2 comments. Could you please take a look?

2021-11-11 14:56 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +    scroll_speed = clamp( static_cast<int>( speed ), static_cast<int>( SCROLL_SLOW ), static_cast<int>( SCROLL_FAST2 ) );
Please remove static casting from **speed** as it's already **int**.

2021-11-11 14:56 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +    scroll_speed = clamp( static_cast<int>( speed ), static_cast<int>( SCROLL_SLOW ), static_cast<int>( SCROLL_FAST2 ) );
Also declare the enumeration containing scroll values as `int` to drop static casts everywhere.

2021-11-11 17:33 UTC, a1exsh commented on src/fheroes2/system/settings.cpp
> +    scroll_speed = clamp( static_cast<int>( speed ), static_cast<int>( SCROLL_SLOW ), static_cast<int>( SCROLL_FAST2 ) );
> Also declare the enumeration containing scroll values as `int` to drop static casts everywhere.

I've tried now and I'm running into this error:
```
error: declaration of ‘ScrollSpeed Settings::ScrollSpeed() const’ changes meaning of ‘ScrollSpeed’ [-fpermissive]
```

May we change the function's name to `GetScrollSpeed()`?  We would have to rename all related functions as well though.

2021-11-11 17:35 UTC, a1exsh commented on src/fheroes2/system/settings.cpp
> +    scroll_speed = clamp( static_cast<int>( speed ), static_cast<int>( SCROLL_SLOW ), static_cast<int>( SCROLL_FAST2 ) );
This is the new enum:
```
enum class ScrollSpeed : int
{
    SLOW = 1,
    NORMAL = 2,
    FAST1 = 3,
    FAST2 = 4
};
```

2021-11-11 18:11 UTC, a1exsh commented on src/fheroes2/system/settings.cpp
> +    scroll_speed = clamp( static_cast<int>( speed ), static_cast<int>( SCROLL_SLOW ), static_cast<int>( SCROLL_FAST2 ) );
Or we can name the enum differently, to avoid the conflict, e.g. `MapScrollSpeed`.

Still it doesn't eliminate the need for all static casts, e.g. to do arithmetic one still has to cast to `int` and then back to enum type.  Or am I doing something wrong? :)

2021-11-12 13:46 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +    scroll_speed = clamp( static_cast<int>( speed ), static_cast<int>( SCROLL_SLOW ), static_cast<int>( SCROLL_FAST2 ) );
Hi @a1exsh , what I meant is to declare the enumeration as `enum : int` instead of `enum` without adding a name. Yes, it's a half solution but it solves the issue with casting.

2021-11-12 16:19 UTC, a1exsh commented on src/fheroes2/system/settings.cpp
> +    scroll_speed = clamp( static_cast<int>( speed ), static_cast<int>( SCROLL_SLOW ), static_cast<int>( SCROLL_FAST2 ) );
Ah, I haven't seen this use before (also not in this project).  My compiler is still unhappy about it with the casts when calling `clamp()`:
```
error: no matching function for call to ‘clamp(int&, <unnamed enum>, <unnamed enum>)’
  650 |     scroll_speed = clamp( speed, SCROLL_SLOW, SCROLL_FAST2 );
```

The arithmetic seems to just work though.

2021-11-12 16:32 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +    scroll_speed = clamp( static_cast<int>( speed ), static_cast<int>( SCROLL_SLOW ), static_cast<int>( SCROLL_FAST2 ) );
-_- fine. Let's leave static cast for now. We can come back to this enumeration later.

2021-11-12 17:13 UTC, ihhub commented on src/fheroes2/dialog/dialog_system_options.cpp
> +                conf.SetScrollSpeed( conf.ScrollSpeed() % 4 + 1 );
Should we use `SCROLL_FAST2` here instead?

2021-11-12 17:56 UTC, a1exsh commented on src/fheroes2/dialog/dialog_system_options.cpp
> +                conf.SetScrollSpeed( conf.ScrollSpeed() % 4 + 1 );
Eh, why not ;)

2021-11-13 03:35 UTC, merged

2021-11-13 03:35 UTC, ihhub commented
@a1exsh , thank you very much for this fix!