Add title for most of dialogs from map's objects
ihhub/fheroes2 pull request #4628
Opened 2021-11-13 05:36 UTC by ihhub

close #4615
close #4614
close #4613
close #4612

2021-11-13 06:02 UTC, ihhub commented
Hi @LeHerosInconnu, please take a look at these changes.

2021-11-13 09:29 UTC, a1exsh commented on src/fheroes2/heroes/heroes_action.cpp
> +                Dialog::ArtifactInfo( hdr, msg, art );
Hm, everywhere else this was named `title`...

2021-11-13 16:06 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +                Dialog::ArtifactInfo( hdr, msg, art );
The function had pre-defined variable called **hdr** so it was used here to fix missing header.

2021-11-13 16:07 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +                Dialog::ArtifactInfo( hdr, msg, art );
I understand that it's good to have a consistency in the code and make proper code but I haven't renamed the variable to minimize the number of changes in this file for now. It has a lot of problematic places.

2021-11-13 22:42 UTC, oleg-derevenetz requested changes
Hi @ihhub I left a few minor notes here, please take a look when it's convenient for you.

2021-11-13 22:42 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_action.cpp
> +    if ( Dialog::YES == Dialog::Message( MP2::StringObject( objectType ), ask, Font::BIG, Dialog::YES | Dialog::NO ) ) {
Shouldn't we also use `title` here instead of calling `MP2::StringObject( objectType )` once again?

2021-11-13 22:42 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_action.cpp
>      if ( Dialog::YES == Dialog::Message( MP2::StringObject( objectType ), ask, Font::BIG, Dialog::YES | Dialog::NO ) ) {
Shouldn't we also use `title` here instead of calling `MP2::StringObject( objectType )` once again?

2021-11-14 12:26 UTC, LeHerosInconnu commented
Hello @ihhub,

> Hi @LeHerosInconnu, please take a look at these changes.

- The yellow title "Abandoned Mine" is still missing for this window.
Also, the word "gold" has not been added if you wanted to do so in this PR.

Suggestion:
Also, I think the word "gold" should be added before the word "mine" in the text of the window after defeating the Ghosts.

"...restore the gold mine to production."

Instead of:

"...restore the mine to production."

![Yellow title check 01](https://user-images.githubusercontent.com/43583994/141679564-21fc8343-28c6-4ec1-8fbc-27ead8cbb29c.png)

- And in this window the word "the" was not added if you wanted to do it in this PR too.

Suggestion:
Also, I think the word "the" should be added before the name of the artifact.

"...you find the Golden Horseshoe."

Instead of:

"...you find Golden Horseshoe."

![Yellow title check 02](https://user-images.githubusercontent.com/43583994/141679576-262f0987-9f92-42ca-8ef4-a7356621e980.png)

Note that the word "the" is present in the text of the artifact in the Wagon window when the hero finds an artifact there.

![Yellow title check 03](https://user-images.githubusercontent.com/43583994/141680921-a72969e9-d782-4d8b-9b41-09b15ba4ea84.png)

For the other windows everything is correct.

2021-11-16 00:50 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +    if ( Dialog::YES == Dialog::Message( MP2::StringObject( objectType ), ask, Font::BIG, Dialog::YES | Dialog::NO ) ) {
Ah, yes! I was reverting some changes in the code and forgot to add back.

2021-11-16 00:50 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
>      if ( Dialog::YES == Dialog::Message( MP2::StringObject( objectType ), ask, Font::BIG, Dialog::YES | Dialog::NO ) ) {
Yes, here as well. I was doing code refactoring but then decided not to expand this pull request.

2021-11-21 09:55 UTC, ihhub commented
Hi @oleg-derevenetz , I addressed your comments.

Hi @LeHerosInconnu , I added `the` word but haven't changed into gold mine to keep it as in the original game for now.

2021-11-21 17:25 UTC, oleg-derevenetz approved these changes

2021-11-22 14:22 UTC, merged