Marketplace gift button placement
ihhub/fheroes2 pull request #4631
Opened 2021-11-13 06:52 UTC by zenseii

This makes the gift button always available in the marketplace instead of conditionally hidden.

Code for updating the trade area had to be added to the gift condition to avoid being able to gift a resource and then trade that same resource again and therefore twice, in the case when you select two resources to trade right before you open the trade menu.

This relates to discussion:
https://github.com/ihhub/fheroes2/discussions/4621_

2021-11-13 09:23 UTC, a1exsh commented
LGTM :+1:

2021-11-16 16:30 UTC, ihhub requested changes

2021-11-16 16:30 UTC, ihhub commented on src/fheroes2/dialog/dialog_marketplace.cpp
> +            resourceTo = resourceFrom = Resource::UNKNOWN;
Please use one operation per line:
```cpp
resourceTo = Resource::UNKNOWN;
resourceFrom = Resource::UNKNOWN;
```

2021-11-16 16:47 UTC, zenseii commented on src/fheroes2/dialog/dialog_marketplace.cpp
> +            resourceTo = resourceFrom = Resource::UNKNOWN;
Sure! I saw that it was used like this but that must have been part of the old code. I fixed this where I saw it as well now.

2021-11-21 09:27 UTC, ihhub commented
Hi @Branikolog , are you okay with this change?

2021-11-21 09:27 UTC, ihhub approved these changes

2021-11-24 12:37 UTC, Branikolog commented
Fix works well, but in my opinion, this rarely used button takes too "front" place in this window. On the other hand I cannot suggest anything better without complete reworking of this window... So... 👍

2021-11-24 23:57 UTC, zenseii commented
> Fix works well, but in my opinion, this rarely used button takes too "front" place in this window. On the other hand I cannot suggest anything better without complete reworking of this window... So... 👍

Yes, I agree with these points and that is also why I proposed to implement av way for the gift button to only appear in case you're playing a multiplayer scenario, maybe even specifically only if there are other human players since I'm not sure there really is much point in gifting to a friendly AI? Maybe if you're playing a scenario where you're depending on your AI teammate to survive or you want to help them survive? This would all be part of a different PR though.

2021-11-27 06:57 UTC, zenseii commented
@ihhub this PR has gotten a good-to-go by enough people now that I feel confident in saying that it is ready to be merged.

2021-12-04 02:21 UTC, merged

2021-12-04 02:21 UTC, ihhub commented
@zenseii , thanks a lot for this change!