Add translation context for color and syntax flexibility to Traveller's Tent and Barrier
ihhub/fheroes2 pull request #4697
Opened 2021-11-26 05:58 UTC by zenseii

This concerns the right-click quick-info you get from these two objects.

This gives specific translation contexts for the colors of the Traveller's Tent and the Barrier, and this PR gives the translator the possibility to rearrange the sequence of the words of the string.

2021-12-03 00:30 UTC, ihhub requested changes
Hi @zenseii , I left few comments here. Can you please take a look at them?

2021-12-03 00:30 UTC, ihhub commented on src/fheroes2/kingdom/color.h
> +    const char * String( int );
Please add the name of input parameter and make it `const`.

2021-12-03 00:30 UTC, ihhub commented on src/fheroes2/kingdom/color.h
> +        NONE = 0,
Can you point where do we use this enumeration? Also the enumeration for Barrier as well.

2021-12-03 00:30 UTC, ihhub commented on src/fheroes2/kingdom/color.cpp
> +        return _( "barrier|Aqua" );
We changed translation strings. We must update translation files.

2021-12-03 01:43 UTC, zenseii commented on src/fheroes2/kingdom/color.h
> +        NONE = 0,
Do you mean this item 0? In that case I can't find anywhere we use it. There does not exist any "None" Tent nor Barrier. Removing it does not cause any issues.

2021-12-03 02:45 UTC, ihhub commented on src/fheroes2/kingdom/color.h
> +        NONE = 0,
I meant the whole enumeration.

2021-12-03 03:06 UTC, zenseii commented on src/fheroes2/kingdom/color.h
> +        NONE = 0,
They are used in this method for Tent color at `line 366` of `dialog_quickinfo.cpp`:
`std::string ShowTentInfo( const Maps::Tiles & tile, const Kingdom & kingdom )`

And this for Barrier color at `line 358`:
`std::string ShowBarrierInfo( const Maps::Tiles & tile )`

In the original code they were the same method here:

https://github.com/ihhub/fheroes2/blob/c9024a717c40abe2ed4ac03a46129463ed6000b6/src/fheroes2/dialog/dialog_quickinfo.cpp#L358

2021-12-03 15:30 UTC, zenseii commented
Hi! @LeHerosInconnu, @undef21 and @Arthusppp !could

2021-12-03 20:00 UTC, Arthusppp commented
@zenseii I do not have write access, so [here you have the Polish update](https://github.com/zenseii/fheroes2/pull/2).

2021-12-03 23:44 UTC, LeHerosInconnu commented
Hello @zenseii,

> Hi @LeHerosInconnu, @undef21 and @Arthusppp ! Could I ask for your help in translating the added strings with `tent|` and `barrier|` and `%{color} Barrier` and `%{color} Tent` that have been added with this PR to the French, Russian and Polish translations?
> 
> Other strings like castle names were added too since all translations got updated up against the latest strings in the source code, but you do not need to focus on these, especially considering if you are fine with leaving them with the English names then leaving those entries as is, even with the fuzzy comment, will turn out fine in the game. The most important things to translate are the ones I noted above.
> 
> Poedit is a nice program to make these changes, but use whatever you are comfortable with since you have added translations before.
> 
> Thank you in advance!

I used the same terms as in the French scenario editor.

In the French scenario editor:

![Tente obstacle 001](https://user-images.githubusercontent.com/43583994/144686552-dd0ccc3b-b210-4738-903d-946727d5ac1a.png)

![Tente obstacle 002](https://user-images.githubusercontent.com/43583994/144686557-9ae1e7a8-2867-482e-932f-eded9a958045.png)

5957 #, fuzzy
msgid "barrier|Aqua"
msgstr "Obstacle aqua"

#, fuzzy
msgid "barrier|Blue"
msgstr "Obstacle bleu"

#, fuzzy
msgid "barrier|Brown"
msgstr "Obstacle marron"

#, fuzzy
msgid "barrier|Gold"
msgstr "Obstacle doré"

#, fuzzy
msgid "barrier|Green"
msgstr "Obstacle vert"

#, fuzzy
msgid "barrier|Orange"
msgstr "Obstacle orange"

#, fuzzy
msgid "barrier|Purple"
msgstr "Obstacle violet"

#, fuzzy
msgid "barrier|Red"
msgstr "Obstacle rouge"

#, fuzzy
msgid "tent|Aqua"
msgstr "Tente du voyageur aqua"

msgid "Brown"
#, fuzzy
msgid "tent|Blue"
msgstr "Tente du voyageur bleu"

#, fuzzy
msgid "tent|Brown"
msgstr "Tente du voyageur marron"

msgid "Gold"
#, fuzzy
msgid "tent|Gold"
msgstr "Tente du voyageur doré"

#, fuzzy
msgid "tent|Green"
msgstr "Tente du voyageur vert"

#, fuzzy
msgid "tent|Orange"
msgstr "Tente du voyageur orange"

#, fuzzy
msgid "tent|Purple"
msgstr "Tente du voyageur violet"

msgid "tent|Red"
msgstr "Tente du voyageur rouge"

2021-12-03 23:57 UTC, zenseii commented
> Hello @zenseii,
> 
> > Hi @LeHerosInconnu, @undef21 and @Arthusppp ! Could I ask for your help in translating the added strings with `tent|` and `barrier|` and `%{color} Barrier` and `%{color} Tent` that have been added with this PR to the French, Russian and Polish translations?
> > Other strings like castle names were added too since all translations got updated up against the latest strings in the source code, but you do not need to focus on these, especially considering if you are fine with leaving them with the English names then leaving those entries as is, even with the fuzzy comment, will turn out fine in the game. The most important things to translate are the ones I noted above.
> > Poedit is a nice program to make these changes, but use whatever you are comfortable with since you have added translations before.
> > Thank you in advance!
> 
> I used the same terms as in the French scenario editor.
> 
> In the French scenario editor:
> 
> ![Tente obstacle 001](https://user-images.githubusercontent.com/43583994/144686552-dd0ccc3b-b210-4738-903d-946727d5ac1a.png)
> 
> ![Tente obstacle 002](https://user-images.githubusercontent.com/43583994/144686557-9ae1e7a8-2867-482e-932f-eded9a958045.png)
> 
> 5957 #, fuzzy msgid "barrier|Aqua" msgstr "Obstacle aqua"
> 
> #, fuzzy msgid "barrier|Blue" msgstr "Obstacle bleu"
> 
> #, fuzzy msgid "barrier|Brown" msgstr "Obstacle marron"
> 
> #, fuzzy msgid "barrier|Gold" msgstr "Obstacle doré"
> 
> #, fuzzy msgid "barrier|Green" msgstr "Obstacle vert"
> 
> #, fuzzy msgid "barrier|Orange" msgstr "Obstacle orange"
> 
> #, fuzzy msgid "barrier|Purple" msgstr "Obstacle violet"
> 
> #, fuzzy msgid "barrier|Red" msgstr "Obstacle rouge"
> 
> #, fuzzy msgid "tent|Aqua" msgstr "Tente du voyageur aqua"
> 
> msgid "Brown" #, fuzzy msgid "tent|Blue" msgstr "Tente du voyageur bleu"
> 
> #, fuzzy msgid "tent|Brown" msgstr "Tente du voyageur marron"
> 
> msgid "Gold" #, fuzzy msgid "tent|Gold" msgstr "Tente du voyageur doré"
> 
> #, fuzzy msgid "tent|Green" msgstr "Tente du voyageur vert"
> 
> #, fuzzy msgid "tent|Orange" msgstr "Tente du voyageur orange"
> 
> #, fuzzy msgid "tent|Purple" msgstr "Tente du voyageur violet"
> 
> msgid "tent|Red" msgstr "Tente du voyageur rouge"

Thanks! I can see that the original game does not conjugate the adjectives correctly for tent in this case since it is a feminine noun and the color adjectives should take that into consideration, because the way it is written now it sounds like it is a blue traveller and not a blue tent (an avatar?). I'll adjust these now when I add them to the translations so don't worry about doing anything more.

Also as a point for later, whenever it says `tent|` or anything with the pipe symbol: `|` you only need to translate what comes afterwards. Ex `morale|Normal` only needs a translation of `Normal`. It is my mistake that I did not explain this, probably because I've been too deep into the translation-side of things that I forgot that others don't know this.

2021-12-04 00:22 UTC, LeHerosInconnu commented
@zenseii.

> @LeHerosInconnu
> 
> Thanks! I can see that the original game does not conjugate the adjectives correctly for tent in this case since it is a feminine noun and the color adjectives should take that into consideration, because the way it is written now it sounds like it is a blue traveller and not a blue tent (an avatar?). I'll adjust these now when I add them to the translations so don't worry about doing anything more.

I was also inclined to accord the adjective in the feminine and thought that maybe it was the exact translation of the French game that was desired. That's why I added the images (more for "Obstacle" than for "aqua"). :)
I think it's okay to accord them then.
And I think "aqua" can be translated into "turquoise" then as it was proposed, and "Obstacle" can stay as "Barrière magique".

> Also as a point for later, whenever it says `tent|` or anything with the pipe symbol: `|` you only need to translate what comes afterwards. Ex `morale|Normal` only needs a translation of `Normal`. It is my mistake that I did not explain this, probably because I've been too deep into the translation-side of things that I forgot that others don't know this.

Thanks for the clarification. :)

2021-12-04 00:31 UTC, zenseii commented
> be translated into "turquoise" then as it was proposed, and "Obstacle" can stay as "Barrière magique"
Right! I just realised I set it as Aqua one place and Turquoise in another so I'll have to correct that. Thanks for making me realize that.

My impression is that the OG did it like this since they call the same text string for both tent and barrier sort of like we did before this PR (in which case they would've been better off using barrière to stick with just the feminine gender...).

2021-12-05 09:16 UTC, zenseii commented
@ihhub We now have translated strings for Russian, Polish, French, Italian and Norwegian and this PR is ready for your opinion.

2021-12-10 16:20 UTC, ihhub requested changes

2021-12-10 16:20 UTC, ihhub commented on src/fheroes2/kingdom/color.h
> +namespace TentColor
Let's then rename existing `BarrierColor` enumeration into **fheroes2** and give the name of existing enumeration as `ObjectColor`. Then we'll have 2 functions: **getBarrierColorName( const int color );** and **getTentColorName( const int color );**.

In this case we won't need extra enumeration and extra namespace.

2022-01-03 08:22 UTC, yvesgurcan commented on src/fheroes2/kingdom/color.h
> +namespace TentColor
Does this still need to be done? Unfortunately, it seems that this PR is getting a little old. The new strings added have already been added in a recently merged PR and it looks like merging this PR with these new strings would result in duplicate translations, unfortunately.

2022-01-03 10:50 UTC, zenseii commented on src/fheroes2/kingdom/color.h
> +namespace TentColor
Did another PR add the possibility to translate the traveller's tent and barriers? I've been completely busy and haven't had time to look at these, but I should be able to tomorrow. If other strings than those have been translaged then that isn't a big problem.

2022-01-03 11:53 UTC, yvesgurcan commented on src/fheroes2/kingdom/color.h
> +namespace TentColor
No, the translation strings for the traveller's tents are still unique but some, like the name of the castles, would end up being present twice in the translation files, since I noticed that they were added recently in this PR: https://github.com/ihhub/fheroes2/pull/4851/files

2022-01-03 12:13 UTC, zenseii commented on src/fheroes2/kingdom/color.h
> +namespace TentColor
Okay, well those aren't really an issue, just some simple merge conflicts I would have to go through, and they aren't the main aim of this PR. Thanks for checking anyways!

2022-01-04 08:03 UTC, zenseii commented
@ihhub I've added the changes you requested and solved all merge conflicts. This PR is ready for your review and eventual merge.

2022-01-06 04:21 UTC, merged

2022-01-06 04:21 UTC, ihhub commented
@zenseii , good job! Thank you so much for these changes!