Fix position of armies in castle and hero quick info
ihhub/fheroes2 pull request #4711
Opened 2021-11-27 06:24 UTC by zenseii

This relates to and gives a solution for issue https://github.com/ihhub/fheroes2/issues/4367

The OG implementation has its flaws so trying to replicate it 100% is no use. Here's an example of the original Heroes 2:
![image](https://user-images.githubusercontent.com/12501091/143670386-8519d24a-8662-414d-8bea-b3992c3aca8e.png)

This is fheroes2 after my fix:
![image](https://user-images.githubusercontent.com/12501091/143670228-101b832f-79c1-4b30-96d4-962608d0e0a5.png)

Changes made:
* Moved creatures in castle quick info  higher and  central to the window
* Made creature quantity  and quantity text below the middle of the creature icon (which do note is not always beneath a bipedal creature's feet!)
* Changed to fheroes2::Text and made necessary adaptments
* Added parantheses in a short-hand if else inline statement for readability

The current implementation in the code (which I believe is part of the old code) doesn't let you use a different space between the first and second row of creatures in an army and in a castle - the space is shared between them. This is why creatures in an enemy army appear slightly closer than before my fix. In the current code you can only choose where to display the entire block of the army.

Here is an enemy hero army after my fix:

![image](https://user-images.githubusercontent.com/12501091/143670349-4285934b-0929-415e-9e81-3b8dc1093067.png)

Black Dragons are used because they take up the most space from what I could tell. The Titan's mohawk is at a good distance from whatever is above it now too.

2021-11-27 07:00 UTC, zenseii commented
It would be great if @LeHeroesInconnu could have a look at this with his pixel perfect sight 👍

2021-11-27 19:20 UTC, LeHerosInconnu commented
Hello @zenseii,

> It would be great if @LeHerosInconnu could have a look at this with their pixel perfect sight +1

I'll take a look at this tomorrow, it's time to quit. :)

2021-11-27 19:52 UTC, zenseii commented
> Hello @zenseii,
> 
> > It would be great if @LeHerosInconnu could have a look at this with their pixel perfect sight +1
> 
> I'll take a look at this tomorrow, it's time to quit. :)

Thanks! Yeah, don't feel any pressure - do it when you feel like it 👍

2021-11-28 03:27 UTC, ihhub requested changes
Hi @zenseii , I put few comments in this pull request. Would you mind to take a look at them?

2021-11-28 03:27 UTC, ihhub commented on src/fheroes2/army/army.cpp
> -        Text text;
I'm thinking that this method should not belong to this file at all. This is the only function which does some UI stuff while the rest of code is for logic. It's always good to separate logic and UI. Can we please do this:
- create 2 files: **army_ui_helper.h** and **army_ui_helper.cpp**
- in the header file we add similar method within **fheroes2** namespace
- in the source file we add the code
- in this **army.cpp** we include newly added header and call the respective method

?

I know it looks a bit of counterproductive but it eases the code readability. What do you think?

2021-11-28 03:27 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +    fheroes2::Text text;
Please remove this line and declare **text** at line 692 instead of **set** call.

2021-11-28 03:27 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +                        fheroes2::Blit( monster, fheroes2::Display::instance(), cx - monster.width() / 2 + monster.x() + 2, cy + offsetY + monster.y() );
Please use **display** here instead of `fheroes2::Display::instance()`.

2021-11-28 03:27 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +                        fheroes2::Blit( monster, fheroes2::Display::instance(), cx - monster.width() / 2 + monster.x() + 2, cy + offsetY + monster.y() );
I'd even go further and accept **Image & output** parameter in this function. This will be useful for the future upgrade of rendering when we're going to implement up-scaling.

2021-11-28 13:15 UTC, zenseii commented on src/fheroes2/army/army.cpp
> -        Text text;
Yes, this sounds like a good solution. I'm working on it. I noticed that there are two instances of DrawMons32Line in two classes, Army and Troop. Should I bring them over like this to the new namespace in the source file? There's also the method DrawMonsterLine which I've brought over to the new header and source file.

2021-11-28 20:14 UTC, LeHerosInconnu commented
Hello @zenseii,

> > Hello @zenseii,
> > > It would be great if @LeHerosInconnu could have a look at this with their pixel perfect sight :+1:
> > 
> > 
> > I'll take a look at this tomorrow, it's time to quit. :)
> 
> Thanks! Yeah, don't feel any pressure - do it when you feel like it :+1:

Here are my comments.

- The vertical position of the creature icons and creature numbers in the hero information window can be moved down one pixel vertically, which will put them at the same distance from the bottom of the window as in the city information window, and at the same time will move the top of the Dragon and Titan sprites away from the line of text just above them.

![Info window PR test coupé 006](https://user-images.githubusercontent.com/43583994/143783966-98563150-6eab-48e8-a3ec-fe14905b25ae.png)

Anyway this window will need to be enlarged later, if only to put the frame around the hero's portrait. :) (https://github.com/ihhub/fheroes2/discussions/3330, https://github.com/ihhub/fheroes2/discussions/4687)

- In the city information window, the city name can be moved down one pixel vertically, which will put it at the same distance from the top of the window as the hero name in the hero information window.

![Info window PR test coupé 007](https://user-images.githubusercontent.com/43583994/143783986-05ed81a3-f052-4f6e-8ed9-76a06ace86e7.png)

Everything else seems fine.
Nice. :)

2021-11-29 15:05 UTC, zenseii commented on src/fheroes2/army/army.cpp
> -        Text text;
So the problem I have been struggling with is that two of the methods in `army.h` depend on the class `Troops` by taking this as a parameter: `const Troops & troops`. The methods are `Army::DrawMons32Line` and `Army::DrawMonsterLine`, they are found in the class `Army` which inherits the class `Troops`.

Here is what I currently have for  `army_ui_helper.h` (the class identifiers are WIP):
```c++
#pragma once

#include <string>
#include <vector>

#include "army.h"

namespace fheroes2
{
    class TroopMonsters : public Troops
    {
    public:
        void DrawMons32Line( int32_t, int32_t, uint32_t, uint32_t, uint32_t, uint32_t, bool, bool ) const;
    };

    class ArmyMonsters : public Army, public TroopMonsters
    {
    public:
        static void DrawMons32Line( const Troops &, s32, s32, u32, u32 = 0, u32 = 0 );
        static void DrawMonsterLines( const Troops & troops, int32_t posX, int32_t posY, uint32_t lineWidth, uint32_t drawPower, bool compact = true,
                                      bool isScouteView = true );
    };
}
```

The error message is not surprisingly : 'DrawMons32Line' is not a member of 'Troops'.
Changing the method parameters to `const TroopMonsters & troops` to give access to `DrawMons32Line` gives the issue where other code in the project that uses this function expects to be able to call other methods found in the original `Troops` when using the object `troops`.

2021-11-29 17:18 UTC, zenseii commented on src/fheroes2/army/army.cpp
> +                        fheroes2::Blit( monster, fheroes2::Display::instance(), cx - monster.width() / 2 + monster.x() + 2, cy + offsetY + monster.y() );
Sure! I'll do this once I'm able to refactor `Troop::DrawMons32Line` from "army.h" into army_"ui_helper.h".

2021-12-03 14:28 UTC, ihhub requested changes

2021-12-03 14:28 UTC, ihhub commented on src/fheroes2/army/army.cpp
> -        Text text;
Actually I asked to move only this function and then call this function within `void Army::DrawMons32Line` and `void Army::DrawMonsterLines` methods. Please revert changes for these function but move this function into newly created files.

2021-12-03 18:15 UTC, zenseii commented
@ihhub I've attempted to move the declaration and definition of `void Troops:DrawMons32Line` and call it from the new location `void fheroes2::DrawTroops::DrawMonsLine32` within `Army::DrawMons32Line` and `Army::DrawMonsterLine`. 

I made it into a class so that I could inherit from `Troops` because if not the functions local to Eroops like `GetCount()` and `isValid()` would not be accessible.

I mostly understand what the issues are, like the definition of `Army::DrawMons32Line` ends up with an unused parameter `const Troops & troops`, but changing this to `const fheroes2::DrawTroops` gives this error from functions that used `Troops::DrawMons32Line`: "cannot convert argument 1 from 'const Troops' to 'const fheroes2::DrawTroops &'. Maybe I shouldn't be passing by reference.

I also need to figure out how to pass `Image & output` as an argument in the places needed, because initializing it like I have done is obviously wrong.

2021-12-04 00:45 UTC, zenseii commented on src/fheroes2/army/army.cpp
>      troops.DrawMons32Line( cx, cy, width, first, count, Skill::Level::EXPERT, false, true );
@ihhub this here is basically the problem with moving the method.

2021-12-04 00:51 UTC, zenseii commented on src/fheroes2/army/army.cpp
> -        Text text;
Yes, I've done this now and left a comment further down about the issues I've run into.

2021-12-04 01:47 UTC, ihhub requested changes
Hi @zenseii , I left several more comments here. Would you mind to check them?

2021-12-04 01:47 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.h
> +    class DrawTroops : public Troops
Please remove this class completely here. This function must be just a part of fheroes2 namespace.

2021-12-04 01:47 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.h
> +#include "army.h"
We don't need this file inclusion after removing the class.

2021-12-04 01:47 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +        for ( const_iterator it = begin(); it != end(); ++it ) {
This function should receive an extra parameter `const Army & army` from where we can get all individual troops and iterate through them.

2021-12-04 01:47 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +
Please remove this empty line.

2021-12-04 01:47 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +#include "game.h"
Do we need this file header inclusion?

2021-12-04 01:47 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +#include "monster.h"
Do we need this file header inclusion?

2021-12-04 01:47 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +    if ( isValid() ) {
We can do this:
```cpp
if ( !army.isValid() ) {
    return;
}

...
// the rest of the code.
```
In this case we don't need to have text indentation.

2021-12-04 01:47 UTC, ihhub commented on src/fheroes2/army/army.cpp
>      troops.DrawMons32Line( cx, cy, width, first, count, Skill::Level::EXPERT, false, true );
Hi @zenseii , as I explained in a comment below we shouldn't make this function as a method of a class. Please check my suggestions.

2021-12-04 02:04 UTC, zenseii commented on src/fheroes2/army/army_ui_helper.cpp
> +#include "game.h"
game.h is needed for this part

```cpp
fheroes2::Text text( isScouteView ? Game::CountScoute( ( *it )->GetCount(), drawPower, compact )
				   : Game::CountThievesGuild( ( *it )->GetCount(), drawPower ),
```

2021-12-04 02:40 UTC, zenseii commented on src/fheroes2/army/army_ui_helper.cpp
> +#include "monster.h"
It seems not.

2021-12-04 03:02 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +#include "game.h"
Oh, okay.

2022-01-24 14:39 UTC, zenseii commented
@ihhub I've looked at this code up and down for quite a while now and I'm still not able to come up with a solution.

Here's a summary of what the 2 outstanding problems are as far as I understand:

Problem 1:

The for loop cannot iterate through the creatures to draw because const_iterator and the functions begin() and end() are inaccessible due to the class Troops having these from protected inheritance from std::vector<Troop *> :

https://github.com/ihhub/fheroes2/blob/52453798ce3572577b45520f7b9b802a07ccbadf/src/fheroes2/army/army.h#L42

https://github.com/ihhub/fheroes2/blob/52453798ce3572577b45520f7b9b802a07ccbadf/src/fheroes2/army/army.cpp#L731




Problem 2:

The Army::DrawMonsterLine32() cannot take class Army as a parameter because it needs to use const Troops, because other places in the code refering to this function use the class type Troops. 
Example of where this happens in battle_dialogs.cpp:

https://github.com/ihhub/fheroes2/blob/52453798ce3572577b45520f7b9b802a07ccbadf/src/fheroes2/battle/battle_dialogs.cpp#L382

https://github.com/ihhub/fheroes2/blob/52453798ce3572577b45520f7b9b802a07ccbadf/src/fheroes2/battle/battle_dialogs.cpp#L471-L472

Visual studio would give this message if using const Army & as parameter: "no suitable user-defined conversion from "const Troops" to "const Army" exists."


My current solution to this is to give the new fheroes2::DrawMonsterLine32 the const Troops & parameter instead of const Army:

```cpp
namespace fheroes2
{
    void DrawMons32Line( const Troops & troops, int32_t cx, int32_t cy, uint32_t width, uint32_t first, uint32_t count, uint32_t drawPower, bool compact,
                         bool isScouteView );
}
```

2022-01-26 12:51 UTC, ihhub commented
Hi @zenseii , 

Problem 1: the class has `size_t Size( void ) const;` method which returns the number of slots used by monsters and `const Troop * GetTroop( size_t ) const;` method to get a pointer to a certain troop.

Problem 2: yes, we're expecting only `Troops` class instance. `Army` is a child class of it so we should use `Troops`.

2022-01-26 14:34 UTC, zenseii commented on src/fheroes2/army/army_ui_helper.cpp
> +                fheroes2::Text text( isScouteView ? Game::CountScoute( troop->GetCount(), drawPower, compact )
@ihhub Is there anything I need to do about this warning and the one below?

2022-01-26 14:34 UTC, zenseii commented on src/fheroes2/army/army_ui_helper.cpp
> +                                                  : Game::CountThievesGuild( troop->GetCount(), drawPower ),
See above.

2022-01-26 14:35 UTC, zenseii commented on src/fheroes2/army/army_ui_helper.cpp
> +void fheroes2::DrawMons32Line( const Troops & troops, int32_t cx, int32_t cy, uint32_t width, uint32_t first, uint32_t count, uint32_t drawPower, bool compact,
@ihhub Is there anything I need to do about this one? I'm working on adding Image & output as a parameter to this function like you requested too, so in the end there will be 32 parameters.

2022-03-09 23:54 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +void fheroes2::DrawMons32Line( const Troops & troops, int32_t cx, int32_t cy, uint32_t width, uint32_t first, uint32_t count, uint32_t drawPower, bool compact,
Nope.

2022-03-10 12:18 UTC, ihhub requested changes
Hi @zenseii , I left multiple comments in this pull request. Could you please take a look at them?

2022-03-10 12:18 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +        if ( troop && troop->isValid() ) {
To reduce complexity highlighted by clang-tidy please do this trick:
```cpp
if ( troop == nullptr || !troop->isValid() ) {
    continue;
}
... // the rest of the code
```

It will greatly improve code readability as well.

2022-03-10 12:18 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +                --first;
Please add {} around this code block:
```cpp
else {
    --first;
}
```

2022-03-10 12:18 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.h
> +    void DrawMons32Line( const Troops & troops, int32_t cx, int32_t cy, uint32_t width, uint32_t first, uint32_t count, uint32_t drawPower, bool compact,
I am thinking that this name is not human-readable (not blaming you for this as it is just copy-paste). Since we are modifying this code I suggest to name the function as `drawMiniMonsters`. No point to specify magical number 32. What you think?

2022-03-10 12:18 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +    text.set( castle.GetName(), smallWhiteFont );
Please combine these 3 lines into one:
```cpp
fheroes2::Text text( castle.GetName(), fheroes2::FontType::smallWhite() );
```

2022-03-10 12:18 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +        text.set( guardian->GetName(), smallWhiteFont );
Please use this call instead of the current:
```cpp
text.set( guardian->GetName(), fheroes2::FontType::smallWhite() );
```

2022-03-10 12:18 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +        text.set( _( "Defenders:" ), smallWhiteFont );
Please `fheroes2::FontType::smallWhite()` and for the rest of places in the code below.

2022-03-10 12:18 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +            if ( 0 == first && count ) {
Also to reduce the complexity of this code we can do like this:
```cpp
if ( first != 0 || count == 0 ) {
    --first;
    continue;
}
... // the rest of the code without else part.
```

2022-03-10 12:18 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.h
> +    void DrawMons32Line( const Troops & troops, int32_t cx, int32_t cy, uint32_t width, uint32_t first, uint32_t count, uint32_t drawPower, bool compact,
Please make the names of input arguments the same as in implementation of the function.

2022-03-10 12:18 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +                                     { fheroes2::FontSize::SMALL, fheroes2::FontColor::WHITE } );
Please use `fheroes2::FontType::smallWhite()` instead of this code.

2022-03-10 12:18 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +                --first;
With the proposed above complexity reduction approach we do not need to do this change.

2022-03-10 18:20 UTC, zenseii commented on src/fheroes2/army/army_ui_helper.h
> +    void DrawMons32Line( const Troops & troops, int32_t cx, int32_t cy, uint32_t width, uint32_t first, uint32_t count, uint32_t drawPower, bool compact,
@ihhub I believe the names of the input arguments are the same between the header and the code file, but maybe I'm missing something?

2022-03-11 06:01 UTC, zenseii commented
Thank you so much for the comments and feedback, @ihhub . I have addressed them and checked that everything works well. When it suits you it would be nice if you could have another look and see if this code is now ready.

2022-03-17 20:24 UTC, ihhub reviewed
Hi @zenseii , I left just 2 comments related to file header inclusion. The rest looks good. Could you please check them?

2022-03-17 20:24 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +#include "image.h"
We can remove this header inclusion as it is included in screen.h file.

2022-03-17 20:24 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +#include "army.h"
Do we need this file inclusion?

2022-03-18 15:24 UTC, zenseii commented on src/fheroes2/army/army_ui_helper.cpp
> +#include "army.h"
`army.h` is needed for the class type Troops, while `army_troop.h` is needed for the class type Troop.

2022-03-18 15:24 UTC, zenseii commented on src/fheroes2/army/army_ui_helper.cpp
> +#include "image.h"
Done! Thanks!

2022-03-18 15:55 UTC, zenseii commented on src/fheroes2/army/army_ui_helper.cpp
> +#include "image.h"
Oh wait I did the opposite...

2022-03-18 15:59 UTC, zenseii commented on src/fheroes2/army/army_ui_helper.cpp
> +#include "image.h"
Although it seems to be the logical choice to only include image.h since we don't need the extra stuff from screen.h anymore.

2022-03-18 17:23 UTC, merged

2022-03-18 17:23 UTC, ihhub commented
@zenseii , thanks a lot for fixing this issue!