Allow to select player class using mouse wheel
ihhub/fheroes2 pull request #4720
Opened 2021-11-28 12:32 UTC by a1exsh

Makes it easier to go back (and forward) through the player classes.

2021-12-05 02:16 UTC, ihhub requested changes
Hi @a1exsh , I put several comments in this pull request. Can you please check them once you have time?

2021-12-05 02:16 UTC, ihhub commented on src/fheroes2/gui/player_info.cpp
> +    else { // if ( le.MouseClickLeft() )
Please remove this commented code.

2021-12-05 02:16 UTC, ihhub commented on src/fheroes2/gui/player_info.cpp
> +    else { // if ( le.MouseClickLeft() )
Actually it'll be even better if we add this condition explicitly.

2021-12-05 02:16 UTC, ihhub commented on src/fheroes2/gui/player_info.cpp
> +        }
Please don't do two commands in one line (I totally understand it was copy-pasted from another code):
```cpp
        player = GetFromClassClick( le.GetMouseCursor() );
        if ( player != nullptr ) ) {
            if ( conf.AllowChangeRace( player->GetColor() ) ) {
                changeRaceToPrev( *player );
            }
        }
```
The same applies for the condition below.

2021-12-05 02:16 UTC, ihhub commented on src/fheroes2/gui/player_info.cpp
> +            break;
I'd suggest to add an assertion here:
```cpp
// Did you add a new race? Add the logic above
assert( 0 );
```

2021-12-05 02:16 UTC, ihhub commented on src/fheroes2/gui/player_info.cpp
> +            break;
I'd suggest to add an assertion here:
```cpp
// Did you add a new race? Add the logic above
assert( 0 );
```

2021-12-05 09:08 UTC, a1exsh commented on src/fheroes2/gui/player_info.cpp
> +    else { // if ( le.MouseClickLeft() )
Was my idea as well, but we have a `const LocalEvent` here and somehow of all the checks that we do here `MouseClickLeft()` is not declared `const`.  I don't really want to open that can of worms :)

2021-12-05 09:13 UTC, a1exsh commented on src/fheroes2/gui/player_info.cpp
> +    else { // if ( le.MouseClickLeft() )
@ihhub if you have ideas what to do here, please suggest

2021-12-10 16:28 UTC, merged

2021-12-10 16:28 UTC, ihhub commented
@a1exsh , thank you so much for these changes!