Fix pressed buttons background
ihhub/fheroes2 pull request #4748
Opened 2021-12-04 17:53 UTC by a1exsh

1. Accept / Decline buttons.
2. Position of pressed OKAY button in Extended Settings and System Options dialogs.
3. Fix X-offset of buttons with a shadow. Overlooked that shadow correction was missing.
4. Fix ICNs used for OKAY and CANCEL buttons in some dialogs:
   - Battle Only
   - Gift Resources
   - Town Portal spell
5. Fix too dark background on TRADE, EXIT and GIFT evil buttons

2021-12-04 17:54 UTC, a1exsh commented
This is a follow-up on pressed button issues found in the course of #4350
/cc @Branikolog

2021-12-05 02:00 UTC, ihhub requested changes
Hi @a1exsh , I left multiple code optimization comments. Would you mind to take a look at them?

2021-12-05 02:00 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    for ( uint32_t i = 16; i < 19; i += 2 ) {
Shall we just write like this:
```cpp
for ( const uint32_t i : { 16, 18 } )
```
As now it's not easy to understand the range of values **i** has.

2021-12-05 02:01 UTC, ihhub commented
Hi @Branikolog , can you please test these changes?

2021-12-05 09:06 UTC, a1exsh commented on src/fheroes2/agg/agg_image.cpp
> +                    for ( uint32_t i = 0; i < 3; i += 2 ) {
Nice trick — didn't know about it :)

2021-12-05 09:06 UTC, a1exsh commented on src/fheroes2/agg/agg_image.cpp
> +                        _icnVsSprite[id][i + 1] = std::move( out );
Yep, makes sense.

2021-12-05 10:58 UTC, Branikolog commented
Hello, @a1exsh !
Nice work!
I've found some issues, but as usual I'm not sure, they're related to current topic.
So I'll post them, to be sure, you're aware of the problem. ;)

Disabled OKAY button in hiring dialog:
![image](https://user-images.githubusercontent.com/55348946/144742388-2c67baa3-ba1c-4141-bac0-c4e033784013.png)

Right part of CONFIG button's shadow looks like straight vertical. Or is it just merged with background here?
![image](https://user-images.githubusercontent.com/55348946/144742430-58f5faa4-817d-43fb-b36e-740b574098a3.png)

Left part of OKAY button in experimental settings has some dark places (looks like a shadow near both upper and bottom corners) in it's pressed state:
![image](https://user-images.githubusercontent.com/55348946/144742463-48117d3e-ba28-4bc3-8666-61545745e84b.png)
![image](https://user-images.githubusercontent.com/55348946/144742475-e4f68041-3f7c-4203-ac61-cc5807de112e.png)
Seems like not pressed button is missing this dark line there...

Shadow for scrollbar is missing:
![image](https://user-images.githubusercontent.com/55348946/144742789-f4cb1b73-20c5-4a9b-ad81-f73c6934e15c.png)

No shadows for buttons in this window:
![image](https://user-images.githubusercontent.com/55348946/144742961-8afd2ee8-e8a7-4d3a-82d1-447620f9de54.png)

Pressed OKAY button in battle options window is rendered wrong:
Letters are shifted only in vertical dimension and we can also watch double left button side (The same to bottom part of disabled "Dismiss hero" button):
![image](https://user-images.githubusercontent.com/55348946/144743143-c637d37a-a7e6-4c57-a12b-5315eaf8b2a2.png)
![image](https://user-images.githubusercontent.com/55348946/144743140-3d0e7f24-37f8-4e6e-9dc5-50b22deeb4a4.png)

Dismiss button also doesn't have horizontal shifting of letters, while EXIT button works well:
![image](https://user-images.githubusercontent.com/55348946/144743735-fdefbbc7-787d-48e1-8efc-f6424df1445e.png)
![image](https://user-images.githubusercontent.com/55348946/144743741-97948e04-726e-4dc7-850c-df2726ba8675.png)

2021-12-05 11:35 UTC, a1exsh commented
@Branikolog thank you for having a look :)

> Disabled OKAY button in hiring dialog: ![image](https://user-images.githubusercontent.com/55348946/144742388-2c67baa3-ba1c-4141-bac0-c4e033784013.png)

I have to guess what you see as a problem here — please be more specific :)

Do you mean the corners that seem darker than the background?
![image](https://user-images.githubusercontent.com/489601/144744464-16d12ab8-589b-465a-99f4-a2f3d47d78eb.png)

> Right part of CONFIG button's shadow looks like straight vertical. Or is it just merged with background here? ![image](https://user-images.githubusercontent.com/55348946/144742430-58f5faa4-817d-43fb-b36e-740b574098a3.png)

Oh, man, it all started with this button and after all the changes it's still not right :facepalm: 
![image](https://user-images.githubusercontent.com/489601/144744524-1957a84f-11ee-4fbe-b250-1c0fb6dd4a49.png)

> Left part of OKAY button in experimental settings has some dark places (looks like a shadow near both upper and bottom corners) in it's pressed state: ![image](https://user-images.githubusercontent.com/55348946/144742463-48117d3e-ba28-4bc3-8666-61545745e84b.png) ![image](https://user-images.githubusercontent.com/55348946/144742475-e4f68041-3f7c-4203-ac61-cc5807de112e.png) Seems like not pressed button is missing this dark line there...

Yep, the released button sprite in the original resources is missing that line present on the pressed state.  We can actually fix it if we like.

> Shadow for scrollbar is missing: ![image](https://user-images.githubusercontent.com/55348946/144742789-f4cb1b73-20c5-4a9b-ad81-f73c6934e15c.png)

That's a known issue.  Also the same scrollbar is not changing in evil interface mode: we most likely even have an issue about that already. ;)

> No shadows for buttons in this window: ![image](https://user-images.githubusercontent.com/55348946/144742961-8afd2ee8-e8a7-4d3a-82d1-447620f9de54.png)

Ah, this dialog I've never seen before: my installation only supports English.  How do you enable it in the first place?  Do you need a special version of OG for that?

> Pressed OKAY button in battle options window is rendered wrong: Letters are shifted only in vertical dimension and we can also watch double left button side (The same to bottom part of disabled "Dismiss hero" button): ![image](https://user-images.githubusercontent.com/55348946/144743143-c637d37a-a7e6-4c57-a12b-5315eaf8b2a2.png)

Cool find — I will check that!

> ![image](https://user-images.githubusercontent.com/55348946/144743140-3d0e7f24-37f8-4e6e-9dc5-50b22deeb4a4.png) ![image](https://user-images.githubusercontent.com/55348946/144743788-41b67292-340a-4bf3-884e-2d362157fac9.png)

> Dismiss button also doesn't have horizontal shifting of letters, while EXIT button works well: ![image](https://user-images.githubusercontent.com/55348946/144743735-fdefbbc7-787d-48e1-8efc-f6424df1445e.png) ![image](https://user-images.githubusercontent.com/55348946/144743741-97948e04-726e-4dc7-850c-df2726ba8675.png)

I will have a look at Dismiss button as well (we have an issue about it, I think this one: #4537).

2021-12-05 12:14 UTC, Branikolog commented
@a1exsh 

>Oh, man, it all started with this button and after all the changes it's still not right

The game changed much with you help! OG has a tons of UI problems, which are already not the case for fheroes2. There're only "a few" issues left to become flawless. ;)

>I have to guess what you see as a problem here — please be more specific :)
>
>Do you mean the corners that seem darker than the background?

Sorry for being not clear enough. :)
Yes. 3 of 4 corners have darker background nearby.

>Yep, the released button sprite in the original resources is missing that line present on the pressed state. We can actually fix it if we like.

I believe all buttons and their shadows should have same visuals within the whole game. :)

>I will have a look at Dismiss button as well (we have an issue about it, I think this one: #4537).

True. But the issue is about disabled button's bottom line.

Today I found out, that letters are shifted here in wrong manner, comparing to other buttons in game.
Actually, I've noticed that Russian version of game has even more drastic flaw here: letters for pressed and released buttons are seem to be messed and while clicking the button the word shifts in upper right direction. :)

2021-12-05 12:34 UTC, a1exsh commented
> > I have to guess what you see as a problem here — please be more specific :)
> > Do you mean the corners that seem darker than the background?
> 
> Sorry for being not clear enough. :) Yes. 3 of 4 corners have darker background nearby.

No worries: it was almost obvious after zooming in. ;)  Fixed.

> > Yep, the released button sprite in the original resources is missing that line present on the pressed state. We can actually fix it if we like.
> 
> I believe all buttons and their shadows should have same visuals within the whole game. :)

Fixed by adding the missing parts of these buttons.

> > I will have a look at Dismiss button as well (we have an issue about it, I think this one: #4537).
> 
> True. But the issue is about disabled button's bottom line.

I will have a closer look on this now.

2021-12-05 13:02 UTC, Branikolog commented
>Ah, this dialog I've never seen before: my installation only supports English. How do you enable it in the first place? Do you need a special version of OG for that?

You can visit language selection dialog using any version of the game. Fheroes2 is going to support any language we like, generating all letters from the OG resources soon.

Can we also add shadows for that radio buttons?

2021-12-05 13:06 UTC, a1exsh commented
> > Ah, this dialog I've never seen before: my installation only supports English. How do you enable it in the first place? Do you need a special version of OG for that?
> 
> You can visit language selection dialog using any version of the game. Fheroes2 is going to support any language we like, generating all letters from the OG resources soon.

In my case I'm always getting "Your version of Heroes of Might and Magic II does not support any languages except English.", but I've just changed the condition locally to test.

> Can we also add shadows for that radio buttons?

Do we already have it some other dialog I can have a look at as example?

2021-12-05 13:07 UTC, zenseii commented
> > Ah, this dialog I've never seen before: my installation only supports English. How do you enable it in the first place? Do you need a special version of OG for that?
> 
> You can visit language selection dialog using any version of the game. Fheroes2 is going to support any language we like, generating all letters from the OG resources soon.
> 
> Can we also add shadows for that radio buttons?

Right now the only thing you need to get that menu to show is by having an .mo translation file of the languages German, French and Polish in your `files/lang` folder of your build. You can either compile them yourself with make or just grab them from the public release `files/lang` folder

2021-12-05 13:27 UTC, Branikolog commented
@a1exsh 

>In my case I'm always getting "Your version of Heroes of Might and Magic II does not support any languages except English.", but I've just changed the condition locally to test.

I've downloaded compiled version of current PR. It already contains languages. 
I think, you can experience lacking of language selection due to using debug mode.

>Do we already have it some other dialog I can have a look at as example?

![image](https://user-images.githubusercontent.com/55348946/144748451-f22b2e82-3f7f-496d-9c9d-55996218aba2.png)


>Edit:
>Note that the button there also should be changed to allow for the evil Okay button, which I imagine is the case for other buttons too.

Oh my, I completely forgot to test evil interface. :)

2021-12-05 14:22 UTC, a1exsh commented
@Branikolog 

> ![image](https://user-images.githubusercontent.com/55348946/144748451-f22b2e82-3f7f-496d-9c9d-55996218aba2.png)

Nah, these are very different radio-buttons.  Let's not touch this for now: it's out of scope of the PR anyway.

> Oh my, I completely forgot to test evil interface. :)

Please do: I always try to test both, but I cannot spot all issues :)

I've also made an improvement for the Dismiss hero button.  Turns out the original resources are inconsistent here: the pressed state is not shifted to the left as it should be.

2021-12-05 14:38 UTC, a1exsh commented
@Branikolog all comments addressed.  Also found that the EXIT button on the High Scores dialog didn't hold the pressed state properly due to handling the monster animations fixed that too.

2021-12-05 15:29 UTC, Branikolog commented
@a1exsh 
I'll take a look a bit later. 
>EXIT button on the High Scores dialog didn't hold the pressed state properly due to handling the monster animations 

Noticed that too, but thought it was not related to the issue. :)

2021-12-05 16:40 UTC, ihhub commented
Hi @a1exsh , unrelated to this issue but previous one: if I change resolution of the game OKAY button has incorrect rendering:
![image](https://user-images.githubusercontent.com/19829520/144755225-7f18cbcb-08dd-4f20-af0f-f1ebba79a214.png)

Do you observe such in your build?

2021-12-05 16:47 UTC, a1exsh commented
@ihhub yeah, I can also see it: some artifacts appear on the button after changing the resolution.  Do you have ideas why would that happen and how to fix it?

2021-12-05 16:51 UTC, ihhub commented
> @ihhub yeah, I can also see it: some artifacts appear on the button after changing the resolution. Do you have ideas why would that happen and how to fix it?

No ideas yet. I'll check what's wrong.

2021-12-07 13:41 UTC, ihhub commented
Hi @a1exsh , I think it happens because we use `display` as a background image. If we do we mustn't do this as display can be changed in a separate thread.

2021-12-07 13:48 UTC, a1exsh commented
> Hi @a1exsh , I think it happens because we use `display` as a background image. If we do we mustn't do this as display can be changed in a separate thread.

Wow, really? I thought it's single-threaded...

2021-12-07 13:49 UTC, ihhub commented
> > Hi @a1exsh , I think it happens because we use `display` as a background image. If we do we mustn't do this as display can be changed in a separate thread.
> 
> Wow, really? I thought it's single-threaded...

No, it's not. Please add `assert( &background != &fheroes2::Display::instance() );` for both functions to catch all possible cases. We should pass the image which is the real background.

2021-12-07 13:53 UTC, a1exsh commented
> display can be changed in a separate thread.

But wouldn't that mean that we should not modify display image unless we coordinate with other threads potentially doing the same? And yet I haven't seen us doing it, and all worked fine.

There must be something special to the code changing the resolution that breaks it, not related to threads, IMO.

2021-12-07 22:20 UTC, Branikolog commented
Hi, @a1exsh ! Could you, please, look at some problems I've found?

I like, how you managed to handle text shifting in DISMISS button! Really nice!

But the background is not ok near top left corner, being too bright.
![image](https://user-images.githubusercontent.com/55348946/145107220-7ad59282-d68c-4bce-80f9-0514a5c7d547.png)

Also, while being inactive we have doubled left side of the button:
![image](https://user-images.githubusercontent.com/55348946/145107700-9882e58f-ab45-47e7-b65f-fe4e4301c440.png)
The same to fixed bottom line of this button right before last changes.

Also, I've noticed the same double edges (left and bottom edges) of inactive MAX button in hiring dialog.
![image](https://user-images.githubusercontent.com/55348946/145108408-866ecef8-f216-4302-ba8d-4d54c92dbad2.png)

Pressed "Exit  Puzzle" button also have a tiny background flaw near upper left corner.
![image](https://user-images.githubusercontent.com/55348946/145110833-30769e63-4107-48fd-998d-d9a48d544d91.png)

Similar case for Exit button from "View World" mode.
![image](https://user-images.githubusercontent.com/55348946/145111093-4d7c7fbd-e339-4813-860d-30c669879f5e.png)
But, actually, original shadows near both this "EXIT" buttons look not good... I'm not sure, we should fix the issues above right now, since in future we will ( I hope :) ) fix the whole button. 

Also it seems to me, that shadows of buttons in scenario info have a small pieces missing. Am I right? Or it's just my eyes tired of pixel-hunting?
![Btn Shadow](https://user-images.githubusercontent.com/55348946/145114097-73b28544-8e55-455b-a791-881a78986a01.png)

2021-12-08 06:54 UTC, a1exsh commented
> Do you observe such in your build?

@ihhub I've opened a separate issue to track this: https://github.com/ihhub/fheroes2/issues/4762

2021-12-08 07:13 UTC, a1exsh commented
> Hi, @a1exsh ! Could you, please, look at some problems I've found?

Will do :)

> I like, how you managed to handle text shifting in DISMISS button! Really nice!
> 
> But the background is not ok near top left corner, being too bright. ![image](https://user-images.githubusercontent.com/55348946/145107220-7ad59282-d68c-4bce-80f9-0514a5c7d547.png)

Yeah, I need to invent some new way to mess the original resources — looks like all the magic we have so far is insufficient :joy: 

> Also, while being inactive we have doubled left side of the button: ![image](https://user-images.githubusercontent.com/55348946/145107700-9882e58f-ab45-47e7-b65f-fe4e4301c440.png) The same to fixed bottom line of this button right before last changes.

I've noticed it as well: need to check what happens in the disabled button code.

> Also, I've noticed the same double edges (left and bottom edges) of inactive MAX button in hiring dialog. ![image](https://user-images.githubusercontent.com/55348946/145108408-866ecef8-f216-4302-ba8d-4d54c92dbad2.png)

Yay, it's actually the same code as for the Dismiss button.  Will check it as well.

> Pressed "Exit Puzzle" button also have a tiny background flaw near upper left corner. ![image](https://user-images.githubusercontent.com/55348946/145110833-30769e63-4107-48fd-998d-d9a48d544d91.png)
> 
> Similar case for Exit button from "View World" mode. ![image](https://user-images.githubusercontent.com/55348946/145111093-4d7c7fbd-e339-4813-860d-30c669879f5e.png) But, actually, original shadows near both this "EXIT" buttons look not good... I'm not sure, we should fix the issues above right now, since in future we will ( I hope :) ) fix the whole button.

Nice catch!  There are entirely too many buttons in this game, that drives me crazy %)

> Also it seems to me, that shadows of buttons in scenario info have a small pieces missing. Am I right? Or it's just my eyes tired of pixel-hunting? ![Btn Shadow](https://user-images.githubusercontent.com/55348946/145114097-73b28544-8e55-455b-a791-881a78986a01.png)

I continue to be amazed by your pixel-hunting skills, @Branikolog ! :)  In this case it's a defect of the OG button resource: one pixel of the darkest shade is missing.

2021-12-08 12:08 UTC, Branikolog commented
@a1exsh 

Talking about pixel-hunting...

I've found out a small flaws near "OKAY" button in experimental settings... :D
![ezgif com-gif-maker (30)](https://user-images.githubusercontent.com/55348946/145205957-30d3f6cc-c878-4317-97b7-e4556f5765b7.gif)

2021-12-08 17:10 UTC, a1exsh commented
> Talking about pixel-hunting...
> 
> I've found out a small flaws near "OKAY" button in experimental settings... :D ![ezgif com-gif-maker (30)](https://user-images.githubusercontent.com/55348946/145205957-30d3f6cc-c878-4317-97b7-e4556f5765b7.gif)

Part of original resource as well... :(

2021-12-10 07:50 UTC, a1exsh commented
@Branikolog I've fixed the background corners around the Dismiss button — please have a look again :)

Regarding the disabled state of Dismiss and Max buttons: there is no easy solution for that, unfortunately, as these buttons are not provided separately from the background in OG resources, and our algorithm cannot tell the difference between background and parts of the button.  We might invent something new one day, but for now let's leave them like they are right now.  Also, the PR topic is _pressed_ buttons ;)

We might want to do something about the View Puzzle / World buttons at some point, but I'd like to wrap this changeset first.

2021-12-10 12:59 UTC, Branikolog commented
Hi, @a1exsh !
One more pixel found at scenario adjustment window! :)
![ezgif com-gif-maker (31)](https://user-images.githubusercontent.com/55348946/145577766-994853ba-b953-47af-bc96-0402adaee662.gif)

2021-12-10 19:36 UTC, a1exsh commented
> One more pixel found at scenario adjustment window! :)

Eagle-Eye! :)

It should be fixed now.

2021-12-13 06:52 UTC, a1exsh commented
@ihhub I think this is now ready for the code review, as all found pixels flaws are addressed. ;)

2021-12-20 12:30 UTC, ihhub requested changes
Hi @a1exsh , I left few comments in this pull request. Could you please check them?

2021-12-20 12:30 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                        Blit( out, 0, 1, tmp, 1, 0, tmp.width() - 1, tmp.height() - 1 );
If tmp is reset then Blit call below is equal to Copy function according to this code:
```cpp
if ( *transformInX > 0 && *transformOutX == 0 ) { // apply a transformation
    *imageOutX = *( transformTable + ( *transformInX ) * 256 + *imageOutX );
}
else { // copy a pixel
    *transformOutX = *transformInX;
    *imageOutX = *imageInX;
}
```
as `transformOutX` is always 1.

The same applies for:
```
out.reset();
Blit( tmp, 1, 0, out, 0, 1, tmp.width() - 1, tmp.height() - 1 );
```

Could you please check this? If yes then we should replace Blit with Copy as the last one is a much faster function.

2021-12-20 13:12 UTC, a1exsh commented on src/fheroes2/agg/agg_image.cpp
> +    void invertTransparency( fheroes2::Image & image )
But it is already in `agg_image.cpp`, not in the general `image.cpp`... ;)

2021-12-20 13:18 UTC, a1exsh commented on src/fheroes2/agg/agg_image.cpp
> +                        Blit( out, 0, 1, tmp, 1, 0, tmp.width() - 1, tmp.height() - 1 );
Yes, this also works.

2021-12-20 13:20 UTC, a1exsh commented on src/fheroes2/agg/agg_image.cpp
> +            }
We don't really need it: I've added it as a hint to the reader that we didn't forget to check other possible values for the transform layer.  We can remove the empty else and add it as a comment before the checks, or remove the comment if you think it's not needed here.

2021-12-20 13:30 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +            }
This comment should contain the explanation. I'm suggesting to do this:
```cpp
if ( *transform == 0 ) {
    *transform = 1;
}
else if ( *transform == 1 ) {
    *transform = 0;
}
// Other values which are used for transformation are excluded.
```
Simple and without threatening words :)

2021-12-20 13:34 UTC, a1exsh commented on src/fheroes2/agg/agg_image.cpp
> +            }
> Simple and without threatening words :)

Right, this is what I mean more or less :)  like "we don't touch other values", not "don't touch this code or else" :D

2021-12-20 14:10 UTC, merged

2021-12-20 14:10 UTC, ihhub commented
@a1exsh , thank you so much for these changes!

Also there are some extra performance improvement we could have done but let's skip them for now :)