[WIP] Define UNICODE for Windows builds
ihhub/fheroes2 pull request #4802
Opened 2021-12-19 14:16 UTC by oleg-derevenetz

2021-12-21 14:16 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left few minor comments here. Would you mind to take a look at them?

2021-12-21 14:16 UTC, ihhub commented on src/engine/system.cpp
> +
**You can ignore it if you like**: we can remove an extra space from variable definition and it's usage here and on lines 442, 458 and 466.

2021-12-21 14:16 UTC, ihhub commented on src/engine/system.cpp
> +    acpToUtf8[str] = result;
As of now we can ignore but I think let's put a TODO comment above this code:
```
// TODO: use a single variable for memory storage without copying it to a temporary string.
```

2021-12-21 14:16 UTC, ihhub commented on src/engine/system.cpp
> +    return result;
I'd recommend to do this way to avoid extra memory copy:
```cpp
const inter insertedIter = acpToUtf8.insert( std::string result( uStr.get() ) );
return insertedIter->second;
```

2021-12-21 14:16 UTC, ihhub commented on src/engine/system.cpp
> +    if ( str.empty() ) {
It's optional. You can ignore it.

2021-12-21 14:29 UTC, oleg-derevenetz commented on src/engine/system.cpp
> +    return result;
@ihhub I suppose we can't really use `insert()` here because there is already an item for this key in map. There is `insert_or_assign()`, but it requires C++17.

2021-12-21 14:34 UTC, ihhub commented on src/engine/system.cpp
> +    return result;
How about this?
```cpp
// In case of any issues, the original string will be returned, so let's put it to the cache right away
auto insertedIter = acpToUtf8.insert( str );
...
// some code here
...
insertedIter->second = std::string( result( uStr.get() ) );
return insertedIter->second;
```

2021-12-21 17:40 UTC, oleg-derevenetz commented on src/engine/system.cpp
> +    return result;
@ihhub Honestly, it looks like there will be no benefit. Consider:

```
S f1(const S &s)
{
    static std::map<int, S> m;

    m[0] = s; // Default constructor for S and then operator=(const S&) will be called

    S s1;

    m[0] = s1; // operator=(const S&) will be called once again

    return s1; // Copy elision
}
```

```
S f2(const S &s)
{
    static std::map<int, S> m;

    auto emplaceRes = m.emplace(0, s); // Copy constructor will be called for S

    emplaceRes.first->second = S(); // operator=(S&&) will be called

    return emplaceRes.first->second; // No copy elision, copy constructor will be called once again
}
```

So we have two copies in the first case (via `operator=()`), and one movement and the same two copies in the second case (via copy constructor). In fact, it looks like we even have [more operations in the second case](https://godbolt.org/z/aqhadbjbn) :)

2021-12-21 17:43 UTC, oleg-derevenetz commented on src/engine/system.cpp
> +    acpToUtf8[str] = result;
@ihhub Temporary string encourages copy elision, while other approaches do not (see below).

2021-12-22 02:36 UTC, ihhub commented on src/engine/system.cpp
> +    return result;
Ah, I forgot that we're returning the value, not const reference. Then yes, you're absolutely right.

2021-12-22 09:37 UTC, oleg-derevenetz commented on src/engine/system.cpp
> +    return result;
@ihhub I already thought about returning a const reference here, but I don't like this because of non-Windows version of this function. Consider some clever guy that likes to live dangerously (image with Austin Powers included) and writes code like this:

```
const std::string & s = FileNameToUTF8( someFunctionReturningString() );
```

In Windows version it will always be OK, because currently we get a reference to temporary with lifetime extension, and in case of `const std::string &` as return type we will get just a reference to the static container element. However, in case of non-Windows and `const std::string &` as return type, we will have a dangling reference.

2021-12-22 14:35 UTC, merged

2021-12-22 14:35 UTC, ihhub commented
@oleg-derevenetz , huge thanks for these fixes!