Centered Knowledge sprite
ihhub/fheroes2 pull request #4844
Opened 2021-12-25 18:02 UTC by felix642

closes #4835 

Here's what it looks like with my changes:
![image](https://user-images.githubusercontent.com/60141446/147390931-ce5d7dc5-41dd-42e1-8562-8163d3f2c3a5.png)

2021-12-25 19:34 UTC, LeHerosInconnu commented
Hello @felix642,

Nice. :)
Would it be possible to copy the first column of pixels on the left of the original graphic and paste it on the last column of pixels on the right of the modified graphic in this change to avoid having this "doubling" of the last two columns of pixels on the right of the graphic of this change.

In fheroes2:

Open the three images in different tabs in your browser, enlarge the images and switch between the three tabs alternately.
First, original Knowledge, second, Knowledge with this modification, third, Knowledge with the first column of pixels copied and pasted:
![Arena original knowledge 01](https://user-images.githubusercontent.com/43583994/147392302-a711ba36-9d46-4860-8959-e2655fb91913.png) ![Arena modified knowledge 01](https://user-images.githubusercontent.com/43583994/147392301-dbd02404-ca1b-4948-8980-8e7301dbab68.png) ![Arena first pixel column used knowledge 01](https://user-images.githubusercontent.com/43583994/147392299-cd040f4f-1d5b-4fd3-99ba-af05b31f70f2.png)

2021-12-26 02:38 UTC, felix642 commented
Hi @LeHerosInconnu,
I added the changes that you requested. It's hard to tell if I did perfectly since it is just a line of pixel and I would appreciate if you could take a look at it to make sure that everything looks perfect now.

2021-12-26 12:32 UTC, LeHerosInconnu commented
Hello @felix642,

> Hi @LeHerosInconnu, I added the change that you requested. It's hard to tell if I did perfectly since it is just a line of pixel and I would appreciate if you could take a look at it to make sure that everything looks perfect now.

Almost. :)

The graphic inside the frame is 35 columns wide.
The pixel column was pasted on the second to last column (column 34) to the left of the yellow frame of the Knowledge graphic instead of the last column (column 35) just to the left of the yellow frame. :)

In fheroes2:

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
First, Knowledge with current modification, second, Knowledge with the first column of pixels copied and pasted:
![Arena first pixel column used second knowledge 01](https://user-images.githubusercontent.com/43583994/147408041-fc6717ee-986e-4266-a1ec-e19615c13830.png) ![Arena first pixel column used knowledge 01](https://user-images.githubusercontent.com/43583994/147392299-cd040f4f-1d5b-4fd3-99ba-af05b31f70f2.png)

2021-12-27 14:35 UTC, LeHerosInconnu commented
Hello @felix642,

I checked, everything is fine.
Thanks for the change. :)

2021-12-28 14:41 UTC, ihhub requested changes
Hi @felix642 , I left multiple comments here. Could you please take a look?

2021-12-28 14:41 UTC, ihhub commented on src/fheroes2/dialog/dialog_arena.cpp
> +        constexpr int32_t BORDER_WIDTH = 2;
Please use `const` over `constexpr` and name the variable in camelCase.

2021-12-28 14:41 UTC, ihhub commented on src/fheroes2/dialog/dialog_arena.cpp
> +        constexpr int32_t BORDER_WIDTH = 2;
The same applies for the line 194.

2021-12-28 14:41 UTC, ihhub commented on src/fheroes2/dialog/dialog_arena.cpp
> +        fheroes2::Blit( croppedICN, display, rect4.x + BORDER_WIDTH, rect4.y + BORDER_WIDTH );
Please use `knowledgeICN` directly without cropping an image. `fheroes2::Blit` function has other variant just to cover this case.

2021-12-28 14:41 UTC, ihhub commented on src/fheroes2/dialog/dialog_arena.cpp
> +        fheroes2::Blit( pixelLine, display, rect4.x + rect4.width - BORDER_WIDTH - 1, rect4.y );
Please use `knowledgeICN` directly without cropping an image. `fheroes2::Blit` function has other variant just to cover this case.

2021-12-28 14:41 UTC, ihhub commented on src/fheroes2/dialog/dialog_arena.cpp
> +            fheroes2::Blit( pixelLine, display, rect4.x + rect4.width - BORDER_WIDTH - 1, rect4.y );
Please use `knowledgeICN` directly without cropping an image. `fheroes2::Blit` function has other variant just to cover this case.

2021-12-28 16:01 UTC, felix642 commented on src/fheroes2/dialog/dialog_arena.cpp
> +        constexpr int32_t BORDER_WIDTH = 2;
I'm sorry, I'm just a bit curious. What is the motivation behind using const over constexpr in this kind of situation ?

2021-12-30 00:46 UTC, ihhub commented on src/fheroes2/dialog/dialog_arena.cpp
> +        constexpr int32_t BORDER_WIDTH = 2;
`constexpr` is only useful when a compiler needs to calculate something at the time of compilation. Here we have nothing to calculate.

2022-01-02 14:28 UTC, ihhub requested changes

2022-01-02 14:28 UTC, ihhub commented on src/fheroes2/dialog/dialog_arena.cpp
> +        const int32_t BORDER_WIDTH = 2;
Hi @felix642 , please use camelCase variable naming here and for the same variable below.

2022-01-06 04:19 UTC, merged

2022-01-06 04:20 UTC, ihhub commented
@felix642 , huge thanks for fixing this issue!