Adding handshake between client <-> server
ihhub/fheroes2 pull request #4847
Opened 2021-12-25 21:33 UTC by vincent-grosbois

This is a first networking step that will allow a client and server to exchange an handhshake through network.

The part that will need to be improved later on are about the server.
For now the server is basically handling the same kind of resources as a the client, ie it can only have a single connection open with a peer.
I think that the next step would be to make the server a real server and being able to handle connection from different clients, and dispatch messages to clients etc

2021-12-25 21:35 UTC, vincent-grosbois commented
@oleg-derevenetz @ihhub is there a way to have automatically build checks etc for this branch too?

2021-12-25 23:30 UTC, oleg-derevenetz commented
Hi @vincent-grosbois yes, of course, you can even make it yourself in this PR. Just replace

```
on:
  pull_request:
    branches: [ master ]
```

by

```
on:
  pull_request:
    branches: [ master, network ]
```

in `.github/workflows/*.yml` files.

2021-12-25 23:39 UTC, oleg-derevenetz commented
Hi @vincent-grosbois Yes, of course, #4848

2021-12-26 13:12 UTC, vasilenkoalexey commented on src/fheroes2/network/ConnectionManager.cpp
> +    while ( signal == -1 ) {
Are you sure code like this should be used with non-blocking sockets and asynchronous I/O?

2021-12-26 13:17 UTC, vasilenkoalexey commented on src/fheroes2/network/ConnectionManager.cpp
> +    std::atomic<int> signal = -1;
What is the reason to use atomics here? I do not see a single modification operation in which the new value is in any way dependent on the previous value, or the need to follow the correct sequence of changing several variables.

2021-12-26 19:00 UTC, vincent-grosbois commented on src/fheroes2/network/ConnectionManager.cpp
> +    while ( signal == -1 ) {
I'm not sure what "should" be used really
The idea of this function is to make a blocking call to get whatever is available to read, within a timeout period.
I'm not sure how it's possible to handle this differently, since the game logic is synchronous it needs to go through methods that are similar to this

2021-12-26 19:02 UTC, vincent-grosbois commented on src/fheroes2/network/ConnectionManager.cpp
> +    std::atomic<int> signal = -1;
the modification operations are happening in the handler line 175, which can occur in a separate thread.
All the times I've used atomic in this review is to go from async world to synchronous world, so the atomic is waiting on the completion handler to execute

2021-12-27 20:10 UTC, vasilenkoalexey commented on src/fheroes2/network/ConnectionManager.cpp
> +    while ( signal == -1 ) {
This is a completely wrong approach to implementing asynchronous IO, which negates all the benefits of asynchrony. If a certain timeout is required during the game, a time counter must be created and updated in the main loop. In general, the whole implementation looks like a synchronous IO, which they tried to make "asynchronous" through multithreading.

2021-12-27 20:10 UTC, vasilenkoalexey commented on src/fheroes2/network/ConnectionManager.cpp
> +    std::atomic<int> signal = -1;
"Asynchronous" and "multithreading" are completely different concepts. "Atomic" is part of the "multithreaded world". Moreover, the "atom" is not needed here, nothing "terrible" will happen to a variable if several threads just write and just read it.

2021-12-27 20:54 UTC, vincent-grosbois commented on src/fheroes2/network/ConnectionManager.cpp
> +    std::atomic<int> signal = -1;
Here there are a few threads handling async io in an event loop (the threads that receive an io_context and call run() on it)
The atomic<int> is needed for sure as it is the variable through which we can signal to the main thread that processing is finished in the async thread.
It's required to be atomic because it's used in multithreaded context (it's news to me why it would be possible to have read / write concurrently working without atomics), and also it works as memory barrier to prevent incorrect instruction re-ordering by the compiler

2021-12-27 21:04 UTC, vincent-grosbois commented on src/fheroes2/network/ConnectionManager.cpp
> +    while ( signal == -1 ) {
I assure you it's asynchonous ;) there are a few threads that are executing the io context, so all io operations are completely asynchronous, ie they won't block any threads when nothing is happening.
What is happening indeed, is that the game logic that is used currently to check the handshake is synchronous, ie it will ask this class "give me your latest message or let me wait 10 msec max before I get it". 
I've done this so that game code can still be written in synchronous way and we don't have to refactor the whole codebase to be fully async. If you run this PR you will see that we never block waiting for socket data anyway, and the code for the hanshake is still readable

I would be interested to know how you would handle the handshake code in a way that is pure async and that still managed to be easy to read and debug

2021-12-28 15:17 UTC, Killbrum commented on src/fheroes2/network/ConnectionManager.cpp
> +    while ( signal == -1 ) {
Why not boost::asio?

The whole point here is that... well.. let me be honest with all of you. The code of core fheroes2 is not so good. It's made using the approach "nah. It's ok, let's ship it". Thus in the past couple of years, guys have been trying to polish it. Yep, I don't have commits, but I track this repo carefully. Why do they do this? Because the game engine is already created, and it works. There is no point in redesigning everything from scratch since it's an endless story. BUT! The network module never worked here, AFAIK. So, it's a new area. 

@vincent-grosbois, I really appreciate your work, no jokes. But if I were you, I would start with a design document and generic discussion about approach, toolset, libraries, architecture, etc.

Please, believe me, by having 5+ years of full-time developing MMO - it's not what you are looking for. The first thing here is that we have to talk about architecture and whether we want to see a Peer-To-Peer connection or have some host anywhere (like a dedicated instance to host games). The second thing that we have to answer is protocol. Should we use protobuf? Should we use any message broker instead? What about network load? Perhaps it will be minimal, so...? should we use REST or SOAP then?

Well... no... definitely no. I hope that @oleg-derevenetz @vasilenkoalexey agree with me. Designing networking stuff shouldn't go this way. You always have to predict one additional step. Moreover... we have to think about ladder, rank board, easy integration with the web (API) and etc.

@vincent-grosbois please don't think that I want to blame you. No, of course not. I really appreciate all of your work, but please let's start with a generic discussion first.

2021-12-28 15:30 UTC, oleg-derevenetz commented on src/fheroes2/network/ConnectionManager.cpp
> +    while ( signal == -1 ) {
Hi @Killbrum

Personally, I look at this branch as a kind of research on the possibilities of integrating an asynchronous network framework into an existing game engine, as far as it can be done at all.

2021-12-28 16:16 UTC, vincent-grosbois commented on src/fheroes2/network/ConnectionManager.cpp
> +    while ( signal == -1 ) {
Hi @Killbrum 
> Why not boost::asio?
AFAIK regular asio and boost::asio are the same, except here we don't pull boost and other dependencies (and asio is header-only)

I'm all for creating a "design doc" or whatever, and indeed in the discord we started talking about the subject a little bit, which indeed requires some think ahead, I agree.
However, here are a few points to consider:
- we are not super organized in terms of project management for this project, so I have no idea what the governance would be for a "design doc" knowing that it requires that some people be familiar with both the game engine and networking for them to have a meaningful opinion IMO
- you're discussing about features (ladder, rank board, API etc) that are totally out of scope for this project since we never discussed this anywhere. I don't see why the "design" for the networking should take into account things that are not planned
- for the design itself, keep in mind that HOMM2 is relatively simple in terms of networking. There are a few things that I think are real-time (like choosing your race in the lobby?) but most of the game is turn-based so this simplifies things a lot.

What I had in mind, was something that I think is close to how the initial games are handling multiplayer:
- one player is a server, with connection to all clients
- clients are only connected to server
- server gathers the client events and broadcast the correct game state to clients
I don't really think that there is much to it to networking. In terms of features, maybe we can add something so that if there is a deconnection of a player, the game is saved and can be reloaded later. This really doesn't change how the networking should be designed, as we don't need anything specific in the networking code for this.

In terms of adapting the game code to handler multiplayer, there a indeed a few things that need to be changed:
- for combat, the server needs to run the logic and push the update to the board state to client. So it probably means refactoring the combat code
- for the regular gameplay I think it will have to be similar even though I think the refacto can be less drastic

In terms of sync / async, IMO we can just keep for the game the regular pattern of checking events in the game loop. Except that now, some additional events to handle are coming from network. It seems simpler to me to do this rather than suddently forcing the whole game to work with async events everywhere, which is going to be a nightmare to make work

2022-01-03 00:00 UTC, vincent-grosbois commented on src/fheroes2/network/ConnectionManager.cpp
> +    while ( signal == -1 ) {
@ihhub do you have time to chime in on this?

2022-01-16 14:03 UTC, ihhub commented
Hi, everyone,

Please take a look at [this wiki page](https://github.com/ihhub/fheroes2/wiki/Network-architecture-design) where I tried to explain a vision of architecture design for networking. We can continue discussion if needed in a separate discussion topic.

2022-01-21 18:14 UTC, vasilenkoalexey commented on src/fheroes2/network/ConnectionManager.cpp
> +    _timeoutForConnecting.async_wait( _readStrand.wrap( [self, this, acceptor, &signal]( asio::error_code ) {
What problem is solved by adding a timeout for accept incoming connections?

2022-01-21 20:58 UTC, vincent-grosbois commented on src/fheroes2/network/ConnectionManager.cpp
> +    _timeoutForConnecting.async_wait( _readStrand.wrap( [self, this, acceptor, &signal]( asio::error_code ) {
in this version it's just so that the UI will display a message on timeout and stop accepting new connection, it's not really needed

2022-01-22 08:00 UTC, ihhub requested changes
Hi @vincent-grosbois , I left multiple design related questions. Some flaws were highlighted by you during the discussion in Discord channel. Before making another steps could you please check the proposed architecture design on wiki page and express your opinion. The design solves the problems highlighted by you.

2022-01-22 11:29 UTC, vincent-grosbois commented on src/fheroes2/network/NetworkHandshake.cpp
> +    std::string getHostIpAddress()
yes it's possble, tbh I just did this as a helper to get external IP, it may not be worth putting this into the real code

2022-01-22 11:31 UTC, vincent-grosbois commented on src/fheroes2/network/NetworkGameMessage.h
> +        OutgoingGameMessage createHandshake3Message();
adding player name is just so we have less state transitions to handle later. I'm assuming that when someone connects to the server they already know their own player name, and they would try to send it anyway just afterwards. I can remove it though

2022-01-22 11:33 UTC, vincent-grosbois commented on src/fheroes2/network/ConnectionManager.cpp
> +                close();
I'm not a TCP expert but this seems like it's not possible that the connection has some noise or leftovers.
Moreover how do you want to handle it ? it would require ton of code to try to recover from this, is this really a needed feature ? Keep in mind that the true game could just save and stop in that case so it can be restarted later

2022-01-22 11:34 UTC, vincent-grosbois commented on src/fheroes2/network/NetworkHandshake.cpp
> +    ConnectionResourcesHandler gResourceHandlerServer;
As stated in the design doc I shared on discord, this is mostly because for now I didn't know exactly where to put this. Indeed it should really be moved to some better location but I thought this was OK for now

2022-01-22 11:40 UTC, vincent-grosbois commented on src/fheroes2/network/NetworkHandshake.cpp
> +            bool gotMessage = getNextGameMessage( server, gameMessage );
Indeed, this comes from the fact that I'm handling the handshaking logic in synchronous way, and I went for the most readable approach. We can obviously increase the timeout if needed but I have the feeling you want to move to full async here?

2022-01-22 11:40 UTC, vincent-grosbois commented on src/fheroes2/network/ConnectionManager.cpp
> +        std::array<uint8_t, 6> header = { 0xFE, 0xEF };
no reason.... that's the point of magical numbers....

2022-01-22 11:41 UTC, vincent-grosbois commented on src/fheroes2/network/ConnectionManager.cpp
> +    }
well, spinlocks have pros and cons. I can replace this by mutex obviously but then it also adds going back and forth between kernel and process etc
i'm fine with both

2022-01-22 11:42 UTC, vincent-grosbois commented on src/fheroes2/network/ConnectionManager.h
> +            std::atomic<bool> _isConnecting;
yes because we access / set these from different threads potentially

2022-01-22 11:50 UTC, vincent-grosbois commented on src/fheroes2/network/NetworkHandshake.cpp
> +                gotMessage = getNextGameMessage( server, gameMessage );
well at some point there needs to be a value for timeout no?

2022-01-22 11:51 UTC, vincent-grosbois commented on src/fheroes2/network/NetworkHandshake.cpp
> +            std::replace( ipAddress.begin(), ipAddress.end(), '>', '.' );
I think it's an other issue actually, maybe it could be solved in another PR indeed.
I think the problem is that fheroes2 forces my keyboard to be QWERTY, but mine is AZERTY, so when I type a dot "." this is stored as ">" even though it shows a "." on screen

2022-01-22 11:52 UTC, vincent-grosbois commented on src/fheroes2/network/NetworkHandshake.cpp
> +            std::atomic<int> signal = { 0 };
i guess no reason if it only takes 2 values

2022-01-22 11:55 UTC, vincent-grosbois commented on src/fheroes2/network/NetworkHandshake.h
> +            void init( const std::string & name, const int nbConnections )
How familliar are you with asio ? All async tasks posted in asio still have to execute at some point, it doesn't happen "magically". They are executed by calling run( ) on the io_context instance. This call is blocking so the usual pattern I've seen is to create a thread that handles the execution of the asio tasks.
Asio is  quite low-level, how to run the io_context (with how many threads etc) is still left to the lib user

2022-01-22 12:00 UTC, vincent-grosbois commented on src/fheroes2/network/NetworkHandshake.cpp
> +            const int connectionResult = Dialog::MessageUntilSignal( "Connecting", dialogMessage.str(), signal, Font::BIG );
I don't see why it "should".
IMO the only thing that matter is the behavior for the program at the end and the clarity of the code.
I tried to find a solution that is still readable, without bugs and that provides the features we would except (ie, you can cancel the connection, UI the is not blocked etc)
It can probably be done in async but I'm not sure what part exactly you want to change to async, and why. It's not like I can just move the body of this function to an async function and keep everything the same

2022-01-22 12:08 UTC, vincent-grosbois commented
Hi @ihhub thanks for the comments, I left some replies on most of them.

I'm not sure exactly what you're saying with your design doc. Are you saying I should change the overall architecture of this PR to follow the design doc ? If so I'll let you continue the work on this PR as it will be simpler

2022-01-22 16:56 UTC, vasilenkoalexey commented on src/fheroes2/network/NetworkHandshake.cpp
> +            std::atomic<int> signal = { 0 };
std;;atomic dont needed since there are no two or more variables shared by different CPU cores, and for which the order of changing the values is important

2022-01-22 17:59 UTC, vincent-grosbois commented on src/fheroes2/network/NetworkHandshake.cpp
> +            std::atomic<int> signal = { 0 };
I think you're mistaken here, this is exactly the use case you are mentionning that is going on.
`Dialog::MessageUntilSignal` is running in the main thread, as usual with Dialog things in this repo.
`acceptConnectionAsync` method will trigger async connect operation, that is executed in the io_context, so in another thread. I'm using the signal variable to signal the main thread dialog function when the connection status of the network actually changed, so this is where the order of changing values is important.

@ihhub I checked again, it has to be int because there are several possibilities:
0 when we are waiting for the signal variable to change
1 when what we are waiting for suceeded (ie connection suceeded)
-1 when what we are waiting for failed (in that case, that's the connection failed, or timeout)

2022-01-22 19:03 UTC, vasilenkoalexey commented on src/fheroes2/network/NetworkHandshake.h
> +            void init( const std::string & name, const int nbConnections )
> They are executed by calling run( ) on the io_context instance.

This is the most naive implementation, for demonstrating "Hello world!" examples in the asio world.

> This call is blocking so the usual pattern I've seen is to create a thread that handles the execution of the asio tasks.

If you carefully read the documentation for asio, you can find non-blocking functions [io_context::poll](http://think-async.com/Asio/asio-1.20.0/doc/asio/reference/io_context/poll.html) or even [io_context::poll_one](http://think-async.com/Asio/asio-1.20.0/doc/asio/reference/io_context/poll_one.html) that allow you to get the maximum benefit from asynchrony. As I wrote earlier, you implemented synchronous I/O via multithreading and asynchronous I/O. This is pointless and fundamentally wrong approach that does not provide any advantage over conventional blocking sockets.

> do we need thread management?
I did i created a small game-demo (even RTS not TBS) where in SINGLE thread processed
1. events from mouse\keyboard
2. game state changing
3. network client async events
4. network server async events (with incoming connection accepting)
5. rendering

[asio-test](https://github.com/vasilenkoalexey/asio-test/blob/master/main.cpp)

So, we definitely don't need multithreading.  Using multithreading is justified only if we have a blocking call or when developing extremely high-loaded applications for better CPU utilization.

2022-01-22 19:18 UTC, vasilenkoalexey commented on src/fheroes2/network/NetworkHandshake.cpp
> +            std::atomic<int> signal = { 0 };
> that is executed in the io_context, so in another thread. I'm using the signal variable to signal the main thread

Do you think that any variable is changed from another thread, it should be wrapped to `std::atomic` for more "reliability"? This is a wrong statement. I paid special attention to variables which shared by different CPU cores, and I'm sure you don't understand what "ordering" means in this context. I hope this [explanation](https://preshing.com/20120710/memory-barriers-are-like-source-control-operations/) will help.

2022-01-22 19:50 UTC, vincent-grosbois commented on src/fheroes2/network/NetworkHandshake.h
> +            void init( const std::string & name, const int nbConnections )
So you suggest to interleave code that calls io_context.poll() everywhere in the codebase ? Ie in the main thread that processes the user event loop, to also sometimes call poll ? this will just execute asio events but it's not even garantueed to execute useful asio events, like for instance you could just execute some partial read of the socket and not even retrieve a full game message, etc.
I'm not sure what's the big deal with multithreading, it seems to be a legimate use here. We are not so constrained by resources that it's suddently impossible to spawn 2 threads to handle network io.

In your example, I can't really understand what's going on. What is changed in term of "gameplay" when you call server.poll() and client.poll() ? it seems either nothing happens, or something is happening but it's not easily readable what is changing, due to it being hidden in callbacks code.

I think a more fair comparison could be discussed if you implemented something with the same level of features as this PR, inside the already-existing fheroes2 code.
Otherwise, calling others's attempt to actually solve the issue "pointless" and "wrong" is just toxic and non-constructive feedback

2022-01-22 23:09 UTC, vasilenkoalexey commented on src/fheroes2/network/NetworkHandshake.h
> +            void init( const std::string & name, const int nbConnections )
> this will just execute asio events but it's not even garantueed to execute useful asio events, like for instance you could just execute some partial read of the socket and not even retrieve a full game message, etc.

Wrong due to asio library misunderstanding.
```
asio::async_read(socket,
                     asio::buffer(&ih, sizeof(ih)), [this](std::error_code ec, std::size_t /*length*/) {...
```
callback lambda will be executed only if size of the data in the socket's internal buffer satisfies specified data size when declaring event heandler (in the example above `sizeof(ih)`). That's why only the fixed length header is read first, the size of the message body is taken from it and then only the body of the size specified in the header is read. Therefore, only a message of the size specified in the header will always be read.

> In your example, I can't really understand what's going on. What is changed in term of "gameplay" when you call server.poll() and client.poll() ?

Asynchronous I/O is very hard to understand, and a comment in this issue is not the best place to explain it....
server.poll() initiates an asynchronous operation to send data (if any) to all connected clients.
client.poll() checks if there is data in the internal buffer of the socket, and if so, calls the callbacl lamdba (which is defined in  Clinet constructor ).

When i run it, i got 
```
Connected 
Message: ЃЎ?Ўaъ????
...
```
which means calling client callback lambda and sending data by server to all clients (which could be hundreds and which also could be serviced directly in this thread and this loop with server). 

>I think a more fair comparison could be discussed if you implemented something with the same level of features as this PR, inside the already-existing fheroes2 code.

It makes no sense until the design of the network part is ready.

2022-01-23 01:53 UTC, oleg-derevenetz commented on src/fheroes2/network/NetworkHandshake.cpp
> +            std::atomic<int> signal = { 0 };
Hi @vincent-grosbois @vasilenkoalexey

> Do you think that any variable is changed from another thread, it should be wrapped to std::atomic for more "reliability"? This is a wrong statement.

Well, if one thread is writing to the certain memory location while one or more threads at the same time read or modify the same memory location, then there is a need to use `std::atomic` or some other synchronization primitive.

> std;;atomic dont needed since there are no two or more variables shared by different CPU cores, and for which the order of changing the values is important

Number of CPU cores (and how exactly shared variables are accessed by them) is not so important here. Consider the following [example code](https://godbolt.org/z/G67WqTYv6):

```cpp
#include <iostream>
#include <thread>

int main()
{
    int counter {0};

    std::thread t{[&counter]() {
        while (counter < 2000) counter++;
    }};

    while (counter < 1000) {}

    t.join();
}
```

Latest clang (with `-O2` at least) turns this line:

```cpp
    while (counter < 1000) {}
```

into the following assembly code:

```asm
        [...]
        cmp     dword ptr [rsp + 12], 999
        jg      .LBB0_8
.LBB0_4:                                # Infinite loop
        jmp     .LBB0_4
.LBB0_8:
        [...]
```

Why? Because it looks at the code and thinks that if `counter` wasn't greater than 999 before entering this loop, it will never exceed this value in future, so it optimized everything out and just made an infinite loop, period. Compiler has no idea that the value of `counter` may be changed from another thread. Let's rewrite it [the following way](https://godbolt.org/z/sc35M1s65):

```cpp
#include <atomic>
#include <iostream>
#include <thread>

int main()
{
    std::atomic<int> counter {0};

    std::thread t{[&counter]() {
        while (counter < 2000) counter++;
    }};

    while (counter < 1000) {}

    t.join();
}
```

In this case the code generated for the same loop will be:

```asm
        [...]
.LBB0_3:
        mov     eax, dword ptr [rsp + 8]
        cmp     eax, 1000
        jl      .LBB0_3
        [...]
```

No infinite loop. Now compiler knows that `counter` is not so "simple" and honestly loads its value from memory to the register and checks that it still less than 1000 at the each loop iteration.

2022-01-23 03:30 UTC, vincent-grosbois commented
@vasilenkoalexey  whatever man, I honestly got better things to do than arguing endlessly with people on network io things about a 25 year-old game where literally any solution would be good enough, when it  seems you have very limited grasp of the project constraints as a whole and also have your own shortcoming about C++ primitive. If my efforts on this are constantly shot down I don't why I should contribute to this project. Have fun try to implement your version I guess, we'll see how it turns out
Feel free to do whatever you want with this PR but I'm out

2022-01-23 08:12 UTC, ihhub commented
@vincent-grosbois , this is not how a developer should react and behave on the given comments. Showing mood swings is not acceptable in any work environment. The same happened in [this pull request](https://github.com/ihhub/fheroes2/pull/2538). @vasilenkoalexey , just expressed his vision on solving the problem. Even if it's a wrong opinion the reply must be based on facts, not on emotions.

As pointed by multiple reviewers as well as yourself personally this implementation has multiple issues. In this case we simply cannot accept the code in such state. Even being a recreation of 25 years old game and an open source source project, we always try to develop the software in the most right way how it's done in any software company.

Once again thank you very much for your efforts and time!

I'm closing this pull request as the author is not willing to continue work on it.

2022-01-23 08:12 UTC, closed without merging

2022-02-17 18:19 UTC, vasilenkoalexey commented on src/fheroes2/network/NetworkHandshake.cpp
> +            std::atomic<int> signal = { 0 };
> then there is a need to use `std::atomic` or some other synchronization primitive.

To be completely accurate, what is needed here is not a synchronization primitive, but an optimization prevention. Thus, `volatile` which is principally designed to prevent compiler optimizations is sufficient here. But in your example there is nothing related to memory ordering, or anything that requires atomic access. So `std::atomic` redundant and not needed here, and can be replaced by just `volatile`.

2022-02-17 18:27 UTC, oleg-derevenetz commented on src/fheroes2/network/NetworkHandshake.cpp
> +            std::atomic<int> signal = { 0 };
@vasilenkoalexey Data race is undefined behavior, even if you have only one conflicting memory location (i.e. one thread writes to this memory location and another thread reads or modifies the same memory location). See "Threads and data races" here:

https://en.cppreference.com/w/cpp/language/memory_model

So no, `volatile` is not enough in case of multiple threads. `volatile` is for signal handlers or some memory location that is updated from external source in relation to your code (such as some hardware port mapped to memory or such).

2022-02-17 19:08 UTC, vasilenkoalexey commented on src/fheroes2/network/NetworkHandshake.cpp
> +            std::atomic<int> signal = { 0 };
> So no, `volatile` is not enough in case of multiple threads.

You just can check your example with `volatile` instead of `std::atomic` :)

> See "Threads and data races" here: 
> https://en.cppreference.com/w/cpp/language/memory_model

To be more completely accurate, effects of runtime memory reordering (to which you tried to refer here) are only visible in multicore and multiprocessor systems, 
> Number of CPU cores (and how exactly shared variables are accessed by them) is not so important here.

So, number of CPU cores (and how exactly shared variables are accessed by them) is VERY important here. But, yes, this effect has nothing to do with your example, since this effect occurs when accessing at least two variables from at least two different CPU cores, so std::atomic at your exаmple is redundant (since the ordering implies at least two elements that follow one after the other). There are very useful [explanation](https://preshing.com/20120710/memory-barriers-are-like-source-control-operations/)

2022-02-17 19:16 UTC, oleg-derevenetz commented on src/fheroes2/network/NetworkHandshake.cpp
> +            std::atomic<int> signal = { 0 };
@vasilenkoalexey That's why it called "undefined behavior" - because it even may work sometimes :) However let's suppose for a minute that we are writing code for some architecture that implies cache synchronization between different CPU cores "by hand" - i.e. using special CPU instruction. In this case `volatile` will not insert such an instruction, while `std::atomic` access will. So in general you still need to use `std::atomic`, `volatile` offers not enough guarantees.

2022-02-17 21:00 UTC, oleg-derevenetz commented on src/fheroes2/network/NetworkHandshake.cpp
> +            std::atomic<int> signal = { 0 };
Hi @vasilenkoalexey

> As you've already seen, your example works great using just volatile, because it is enough to implement your example.

Yeah, but it will not work just with `volatile` on that architecture with separate CPU instruction for cache synchronization - because when one thread will change that `volatile` variable, there will be no way for another thread to know about this :) So no, all these "`volatile` works in this particular case on this particular architecture, and because of this I will not use atomics" leads to non-portable buggy code with UB. I don't write code like that. Anyway, let's agree to disagree :) This dispute doesn't make sense to me.