Update FR translation:
ihhub/fheroes2 pull request #4851
Opened 2021-12-26 14:32 UTC by dimag0g

- translate new strings
- remove incorrect c-string specifiers
- minor fixes

2021-12-26 20:21 UTC, felix642 reviewed
Hi @dimag0g, I left a few comments regarding the french translation. Would you mind taking a look ?

2021-12-26 20:21 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Experimental"
Expérimental

2021-12-26 20:21 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Charger la langue du jeu."
Changez

2021-12-26 20:21 UTC, felix642 commented on files/lang/fr.po
> +"langue autre que l’anglais."
That's a bit weird to say but okay ? 😁

2021-12-26 20:21 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Cadeau de la part de %{name}"
On one translation it's "cadeau" and on the other it's "don". I think that both of them should be "cadeau"? What do you think ?

2021-12-26 20:21 UTC, felix642 commented on files/lang/fr.po
> +msgstr "' mais la langue actuelle du jeu est '"
We lost the first word here. Do you know what the complete sentence is suppose to be ?

2021-12-26 20:21 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Charger la langue, la résolution et les paramètres du jeu."
Changez

2021-12-26 20:21 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Ultime artéfact"
Artéfact Ultime ?

2021-12-26 20:21 UTC, felix642 commented on files/lang/fr.po
>  "you that he is willing to give %{art} if you have %{skill}."
There's a mistake in the id ? 
"He tells is you that he is"

2021-12-26 20:21 UTC, felix642 commented on files/lang/fr.po
> +"paix maintenant.\""
We should use french quotation marks here.

2021-12-26 20:21 UTC, felix642 commented on files/lang/fr.po
> -#, c-format
Hmm, can you actually remove this without breaking anything ?

2021-12-26 20:21 UTC, felix642 commented on files/lang/fr.po
> +"Ce sort convoque\n"
"invoque" ?

2021-12-26 20:41 UTC, dimag0g commented on files/lang/fr.po
> +msgstr "Charger la langue du jeu."
"changer" is used in 8 translations, while "changez" is not used at all. Shall we stick to the existing phrasing?

2021-12-26 20:44 UTC, dimag0g commented on files/lang/fr.po
> +msgstr "' mais la langue actuelle du jeu est '"
"Cette partie sauvegardée est localisée en 'en' mais la langue actuelle du jeu est 'fr'" I could add the word "langue" before the locale name if you like

2021-12-26 20:45 UTC, dimag0g commented on files/lang/fr.po
> +msgstr "Cadeau de la part de %{name}"
cadeau it is...

2021-12-26 20:49 UTC, dimag0g commented on files/lang/fr.po
> +msgstr "Ultime artéfact"
It's "L'Ultime Artefact" in the GoG version.

2021-12-26 20:51 UTC, dimag0g commented on files/lang/fr.po
>  "you that he is willing to give %{art} if you have %{skill}."
Good catch!

2021-12-26 20:56 UTC, dimag0g commented on files/lang/fr.po
> +"paix maintenant.\""
I suggest we do this as a separate PR. There are plenty of translations to modify, and the makefile must be adapted too, in order to replace the French quotation marks back to English one, as French marks will not work in the game anyway.

2021-12-26 20:58 UTC, dimag0g commented on files/lang/fr.po
> -#, c-format
This comment actually **must** be removed: in all these strings the % character is a literal percent sign, not a printf format specifier. With the comments in place, my translation checker rightfully complains about broken format specifier in translated text.

2021-12-26 21:35 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Charger la langue du jeu."
Yes, my bad. I meant "Changer" instead of "Charger". The word is incorrect in this translation.

2021-12-26 21:39 UTC, felix642 commented on files/lang/fr.po
> +msgstr "' mais la langue actuelle du jeu est '"
No, now that I know what the full sentence is I think that's fine like this ! :) 
I wanted to make sure that you simply didn't forget the word when translating it.

2021-12-26 21:40 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Charger la langue, la résolution et les paramètres du jeu."
The same applies here, it should be changer instead of changez. My bad..

2021-12-26 21:40 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Ultime artéfact"
Then "l'ultime artéfact" it is!

2021-12-26 21:41 UTC, dimag0g commented on files/lang/fr.po
> -#, c-format
I now see these comments come back after every merge. I'll see if I can deal with them at the source. Worst case, I suggest we run the fheroes2.pot through `sed -i s/, c-format//`. AFAIK we don't use `printf` and friends anywhere in the project.

2021-12-26 21:43 UTC, felix642 commented on files/lang/fr.po
>  "you that he is willing to give %{art} if you have %{skill}."
Oh, that's not exactly what I meant.. We have to fix it yes but by doing so you will break this translation. I took a look at the code and the mistake appears to be in every single file. That means that to fix it we will have to change the id in every .po file and in the heroes_action.cpp file.

I feel like this a bit out of the scope of this pull request and it think it would be better to do it in a different pull request what do you think @dimag0g ? 
I can also do it if you're unsure how to fix it.

2021-12-26 21:44 UTC, felix642 commented on files/lang/fr.po
> +"paix maintenant.\""
Oh, I was not aware of that. That's perfect then we'll wait for that one!

2021-12-26 21:45 UTC, felix642 commented on files/lang/fr.po
> -#, c-format
Wow, I didn't realize that! Good catch.

2021-12-26 21:54 UTC, dimag0g commented on files/lang/fr.po
>  "you that he is willing to give %{art} if you have %{skill}."
I added a change to  heroes_action.cpp to this PR. Indeed this will break other translations until they are merged with the new POT template, but I guess that's OK. No translation file is 100% complete in a project where the code is being worked on.

2021-12-26 22:01 UTC, dimag0g commented on files/lang/fr.po
> +"langue autre que l’anglais."
I just machine-translated it. If you have a better phrasing in mind, let me know.

2021-12-26 22:04 UTC, felix642 commented on files/lang/fr.po
> +"langue autre que l’anglais."
No, I simply meant that it's weird to tell a player that his game only supports english in french. If the player sees this message that means that the game definitely supports other languages.
There's nothing wrong with your translation here!

2021-12-26 22:10 UTC, felix642 commented on files/lang/fr.po
> -#, c-format
> I now see these comments come back after every merge. I'll see if I can deal with them at the source. Worst case, I suggest we run the fheroes2.pot through `sed -i s/, c-format//`. AFAIK we don't use `printf` and friends anywhere in the project.

You probably now how .pot files work better than me. But I can confirm, we are not using the printf family (other than fprintf to display error messages to the console) so I don't think that would be an issue.

2021-12-26 22:11 UTC, felix642 approved these changes

2021-12-26 22:29 UTC, dimag0g commented on files/lang/fr.po
> +"langue autre que l’anglais."
AFAIK this message is displayed when French-specific characters such as `à` are not found in the game resources. French translation will still be there of course, but it will not display text correctly.

2021-12-27 00:31 UTC, felix642 commented
@dimag0g, one last question.
Can we close #4797 with this PR or not ?

2021-12-27 12:18 UTC, dimag0g commented
@felix642 Thanks for pointing me to this bug report. I'll go though it and fix whatever I can, hopefully later today.

2021-12-28 05:59 UTC, yvesgurcan requested changes
Hooray for a better French translation! I'm a little sad that you stole my thunder as I was working on some of the things you addressed but, at the same time, this work is more robust than mine and I was working on getting set up anyway. Great job! :)

2021-12-28 05:59 UTC, yvesgurcan commented on files/lang/fr.po
> +"paix maintenant.\""
Yay! French quotation marks are awesome!

2021-12-28 05:59 UTC, yvesgurcan commented on files/lang/fr.po
> +"Lorsque vous entrez dans la Tour de l’Alchimiste, un homme entravé et "
I would suggest "boiteux" (https://en.wiktionary.org/wiki/boiteux) here instead of "entravé."
```suggestion
"Lorsque vous entrez dans la Tour de l’Alchimiste, un homme boiteux et "
```

2021-12-28 05:59 UTC, yvesgurcan commented on files/lang/fr.po
> +"l’artefact maudit et le jette dans son chaudron magique."
So, to my surprise, it seems that the word for "artifact" in French has two different spellings: "artéfact" and "artefact." Since it looks like the French strings use "artéfact" everywhere else, I would suggest keeping that spelling for the translation of the word "artifact" here and in the diff below.
```suggestion
"l’artéfact maudit et le jette dans son chaudron magique."
```

2021-12-28 05:59 UTC, yvesgurcan commented on files/lang/fr.po
> +"Le Sphinx soupire, l'air un peu déçu. Vous avez répondu à mon énigme, voici "
Getting rid of these quotes or not is a tough call. They most likely should be present in English but they aren't. So, the question is, do we want to remain faithful to the English text or would we rather be typographically correct in French?

2021-12-28 05:59 UTC, yvesgurcan commented on files/lang/fr.po
> +msgstr "Le livre de sorts n'est pas présent."
I remember seeing the word "grimoire" to translate "spell book" somewhere else in this file. While I'm tempted to use "livre de sorts" instead of "grimoire," I'm a little on the fence and can't decide which one would work better. They both do the job well. I guess the only thing is that I suspect that it would be better to remain consistent with our translation of "spell book" and pick one of the two options throughout the entire file.

2021-12-28 05:59 UTC, yvesgurcan commented on files/lang/fr.po
> +msgstr "Le sort n'est pas trouvé."
It seems that there might be something a little funky going on with the English text. I'm tempted to say that it should be either "Spell not found." or "The spell has not been found." or "The spell wasn't found." but I might be incorrect.
No matter what, "Le sort n'est pas trouvé." seems awkward in French. I would suggest:
```suggestion
msgstr "Le sort n'a pas été trouvé."
```
Or:
```suggestion
msgstr "Sort introuvable."
```

2021-12-28 05:59 UTC, yvesgurcan commented on files/lang/fr.po
> +msgstr "Hasard"
I've noticed these prefixed strings before and I suspect that it might be necessary to keep the prefix? I'm not entirely sure.
```suggestion
msgstr "race|Hasard"
```

2021-12-28 05:59 UTC, yvesgurcan commented on files/lang/fr.po
> +msgstr "Burma shave."
It looks like "shave" was maybe kept untranslated? Is it supposed to be "Burma shaves." in English?
```suggestion
msgstr "Burma se rase."
```

2021-12-28 05:59 UTC, yvesgurcan commented on files/lang/fr.po
> +msgstr "Cet espace est à louer."
To convey the succinct aspect of the phrase conveyed by the lack of "is" in "This space for rent." (instead of "This space is for rent."), I would suggest to keep the phrase shorter in French as well and drop the verbe "est" as well as "Cet."
```suggestion
msgstr "Espace à louer."
```

2021-12-28 05:59 UTC, yvesgurcan commented on files/lang/fr.po
> +msgstr "Connectez-vous avec nous sur"
The phrase "Connectez-vous avec nous" doesn't seem to work here since it implies to literally use a device to connect to the internet (I think) whereas the English word "connect" here is about getting in touch with somebody. Or maybe this is an intentional use of the word "connect" to both mean connecting through a device and getting in touch with somebody? :) If that's the case, the use of a single word to mean both things does not seem possible in French, so if we were to take "connect" as "use your machine to go online," it seems that the proper translation would be "Connectez-vous sur."

```suggestion
msgstr "Entrez en contact avec nous sur"
```

2021-12-28 05:59 UTC, yvesgurcan commented on files/lang/fr.po
> +msgstr "Ultime artéfact aléatoire."
We might want to stick to capitalized first letter for now? And no period.
```suggestion
msgstr "Artéfact Ultime Aléatoire"
```

2021-12-28 05:59 UTC, yvesgurcan commented on files/lang/fr.po
> +"Transforme la créature affectée en pierre.  Une créature pétrifiée reçoit la "
For clarity purposes, I would suggest to move "en pierre" closer to "Transforme" as to avoid confusion about "affectée" having something to do with "en pierre" (even if this is not very likely that such a confusion might happen, really).
```suggestion
"Transforme en pierre la créature affectée. Une créature pétrifiée reçoit la "
```

2021-12-28 16:09 UTC, felix642 commented on files/lang/fr.po
> +"langue autre que l’anglais."
It doesn't really matter @yvesgurcan, I simply thought it was funny to say that the game only supports english in french.
If we really consider this to be an issue then we should do that in a different pull request. Since the fix for that would be to remove the translation of this string by changing the file dialog_game_Settings.cpp. But I feel like this is a bit out of the scope of this PR and isn't a major issue. :)

2021-12-28 16:11 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Mana"
@yvesgurcan,  Take a look at  #4797,  this is where they proposed this change!

2021-12-28 16:18 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Burma shave."
This translation appears on signs in the game. I think you should take a look at that: https://en.m.wikipedia.org/wiki/Burma-Shave ;)

2021-12-28 17:20 UTC, dimag0g commented on files/lang/fr.po
> +msgstr "Multiple"
This for a player who has several kinds of castles at once. It's translated as "Varié" in GoG version, perhaps we reuse that?
![Untitled](https://user-images.githubusercontent.com/10945319/147591059-fe8c9f6f-3b2b-4601-81fd-7542c81ff947.png)

2021-12-28 17:21 UTC, dimag0g commented on files/lang/fr.po
> +msgstr "Troupes de %{count} alignements -%{penalty}"
Moral modifiers, e.g. "Troops of 3 alignments -1"

2021-12-28 17:24 UTC, dimag0g commented on files/lang/fr.po
> +msgstr "Mana"
@yvesgurcan It's a hard choice between an ugly shortening and liberal word choice. However, the French GoG version of the game uses "Mana" in a lot of places, which tilted the balance towards this word.

2021-12-28 17:36 UTC, dimag0g commented on files/lang/fr.po
> +msgstr "N/A"
I didn't think much about this one. What about "N/C" as in "non concerné"?

2021-12-28 17:45 UTC, dimag0g commented on files/lang/fr.po
>  msgstr "Massue"
When it comes to artifact names, I try to follow the GoG translation as close as possible.  "Bouclier furtif" is spelled exactly like that in this version, no idea why they didn't capitalize the second word. And thanks for bringing up the Thunder Mace - it's actually "Massue du Tonnerre".

2021-12-28 17:50 UTC, dimag0g commented on files/lang/fr.po
> +msgid "Blackridge"
This was done for languages like Russian, to let the translator spell "Blackridge" with Cyrillic letters. For languages with Latin alphabet no translation is planned AFAIK.

2021-12-28 17:56 UTC, dimag0g commented on files/lang/fr.po
> +msgstr "L'armée à joindre"
Would "L'armée à rallier" be better? This is a dialog title which is displayed when you move the hero to the garrison.

2021-12-28 18:08 UTC, dimag0g commented on files/lang/fr.po
>  msgstr "Gardien"
AFAIK "Set Guardian" refers to an army protecting a mine. "Régler" wouldn't sound right here, "affecter", "fixer", "assigner" ou "nommer" would be better.

I don't think it's a good idea to mark manual translations as "fuzzy" - this is what you get when `make merge` tries to translate stuff for you, usually with rather poor results (eg. "Max" -> "Maximus"). It is of much worse quality than a poor manual translation.

2021-12-28 18:19 UTC, dimag0g commented on files/lang/fr.po
>  msgstr "Tournante"
Thanks for catching this! A gang rape game is indeed not what HoMM users would expect ;-)
I'll put "Hot Seat" in. Just FYI, the GoG version calls it "jeu à plusieurs" which I personally find confusing, because it essentially means "multiplayer".

2021-12-28 18:33 UTC, dimag0g commented on files/lang/fr.po
> +msgstr "Hasard"
Prefixes should not be kept, exactly because of the character coding of the French version of the game, which maps `|` to `ê`. As a result, the code which removed prefixes during rendering of the translated text was removed, and "race|Hasard" will be printed as "raceêHasard".

The code which removes prefixes from the English text is still there, so "race|Random" is still rendered as "Random"

2021-12-28 18:39 UTC, dimag0g commented on files/lang/fr.po
> +msgstr "Connectez-vous avec nous sur"
How about "Prenez contact avec nous sur"?

2021-12-28 18:49 UTC, dimag0g commented on files/lang/fr.po
> +"Le Sphinx soupire, l'air un peu déçu. Vous avez répondu à mon énigme, voici "
I'd put quotes in English text, where they belong (and in all translations as a consequence). @ihhub What do you think?

2021-12-28 19:14 UTC, yvesgurcan commented on files/lang/fr.po
> +msgstr "Multiple"
Oh, I see! Yes, "Multiple" seems to work. :)

2021-12-28 19:16 UTC, yvesgurcan commented on files/lang/fr.po
> +msgstr "Troupes de %{count} alignements -%{penalty}"
Oh, so, the alignment is like the kind of the monster (necromantic, barbarians, etc?).

2021-12-28 19:22 UTC, yvesgurcan commented on files/lang/fr.po
> +msgstr "Mana"
That's fair. Would it be complicated to make the size of these dialog windows bigger either for all languages or depending on the language? It seems probable that this problem can occur in other languages as well. Alternatively, we can drop "Pt de" and just go for "Magie," which should be sufficient enough to imply that this is an amount of something (just like "Mana" here implies that these are "Pt de Mana").

2021-12-28 19:32 UTC, yvesgurcan commented on files/lang/fr.po
> +msgstr "N/A"
It does not seem that "non communiqué" conveys the same meaning than "not applicable." I like the Quebec alternative of "sans object" as it's closer to the idea that something is irrelevant but I suspect that this phrase could surprise francophones from France, especially if we abbreviate it to "s.o." Maybe keeping it closer to the English phrase with "n/a" ("non applicable") is the best solution here.
```suggest
"n/a"
```

2021-12-28 19:37 UTC, yvesgurcan commented on files/lang/fr.po
>  msgstr "Massue"
Oh, great, that translation for the Mace is better than mine. As concerns the case of "furtif," well, if you want to keep it lowercase it doesn't hurt much but a capitalized "F" would be more consistent with other translated artifact names. I'm wondering about the GOG translation. How did they do it? Was it done by professional translators?

2021-12-28 19:38 UTC, yvesgurcan commented on files/lang/fr.po
> +msgid "Blackridge"
Ok! That's good to know.

2021-12-28 19:42 UTC, yvesgurcan commented on files/lang/fr.po
> +msgstr "L'armée à joindre"
Oh, of course! Now that you mentioned that this is a dialog title, this translation makes a lot more sense. It seems that the English phrase means that you are somewhat joining two armies together. In that case, "Armée à joindre" seems to work.

2021-12-28 19:45 UTC, yvesgurcan commented on files/lang/fr.po
>  msgstr "Gardien"
Oooh, these are great suggestions. "Assigner Guardien" sounds good.

2021-12-28 19:47 UTC, yvesgurcan commented on files/lang/fr.po
>  msgstr "Tournante"
Great! Yes, "Jeu à plusieurs" sounds confusing because it does convey the meaning that it is indeed a multiplayer game but it does not convey the meaning that players are sharing a seat to play.

2021-12-28 19:50 UTC, yvesgurcan commented on files/lang/fr.po
> +msgstr "Hasard"
Ooooh, I get it. This is a way to signify that this is a string that applies to a specific case with a specific translation.

2021-12-28 19:52 UTC, yvesgurcan commented on files/lang/fr.po
> +msgstr "Burma shave."
lol!
In this case, it looks like both the English and French strings should be "Burma-Shave."

2021-12-28 19:54 UTC, yvesgurcan commented on files/lang/fr.po
> +msgstr "Connectez-vous avec nous sur"
It seems like it would work. 🙂

2021-12-28 19:55 UTC, yvesgurcan commented
Thank you for putting up with my comments. This translation is going to look stellar!

2021-12-28 21:15 UTC, yvesgurcan commented on files/lang/fr.po
> +"langue autre que l’anglais."
Haha! That's fair. :)

2021-12-28 22:51 UTC, dimag0g commented
I have pushed the changes implemented so far. I left out the changes related to quotes ("the Sphynx sighs"), I prefer we do it as a separate PR later, perhaps together with transition from English quotes to French ones.

2021-12-31 00:50 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> -                    msg = _( "You've encountered a strange person with a hat and an owl on it. He tells is you that he is willing to give %{art} if you have %{skill}." );
Please make an appropriate change in the rest of po files, otherwise other languages will have non-translated string for this case.

2021-12-31 01:03 UTC, ihhub requested changes
Hi @dimag0g , I left few comments here. Would you mind to take a look?

2021-12-31 01:03 UTC, ihhub commented on files/lang/fr.po
> +msgstr "Burma shave."
We can put any French-related innocent joke here. Like "Baget est là" (Google translation).

2021-12-31 18:00 UTC, dimag0g commented on src/fheroes2/heroes/heroes_action.cpp
> -                    msg = _( "You've encountered a strange person with a hat and an owl on it. He tells is you that he is willing to give %{art} if you have %{skill}." );
I suggest we leave the translation in for now. Later, when the useless message is removed from the game, it will simply not be used for a while, until the unused strings are cleaned from translation files.

I can merge the new string in the rest of the translation files, but I'd rather not update translations in languages I don't speak. It's preferable that this string gets marked as "fuzzy" by the merge (because the match is not exact), and translators will know they have to check the phrasing.

2021-12-31 18:04 UTC, dimag0g commented on files/lang/fr.po
> +msgstr "Le prix de la loyauté"
These strings are translated in some places but not others. I'll make sure they are translated everywhere, with caps as in English, unless others object to the idea.

2021-12-31 18:05 UTC, dimag0g commented
I'm not familiar with the "Baget est là" joke, could someone enlighten me, or perhaps suggest a better-known one?

2022-01-01 09:36 UTC, dimag0g commented
I rebased and force-pushed my old commits, together with two additional ones:
- undo Price of Loyalty / Succession Wars translations. Let's keep them in English just like the French GoG version did.
- merge all translation files with the latest POT. Some strings moved around, but as far as I can tell this reflects changes to the source code.

2022-01-02 02:55 UTC, ihhub commented
Hi @dimag0g , are we good merging this pull request?

2022-01-02 02:55 UTC, ihhub approved these changes

2022-01-02 10:41 UTC, dimag0g commented
@ihhub I have nothing to add, so I think we can merge this!

2022-01-02 13:59 UTC, yvesgurcan approved these changes
Amazing work! This is such a great improvement!

2022-01-02 13:59 UTC, yvesgurcan commented on files/lang/fr.po
> +"langue autre que l’anglais."
That seems like a good idea!

2022-01-02 13:59 UTC, yvesgurcan commented on files/lang/fr.po
> +msgstr "Burma shave."
Haha! I like the idea of putting a joke that's more relevant to French in the translation. However, I'm not sure I know what "Baget est là" would refer to. 😋 What's the original text?

2022-01-02 14:26 UTC, merged

2022-01-02 14:26 UTC, ihhub commented
@dimag0g , thank you so much for this work!