Fix use of plural/singular translation
ihhub/fheroes2 pull request #4858
Opened 2021-12-29 07:07 UTC by a1exsh

Close #4837

2021-12-29 07:08 UTC, a1exsh commented on src/fheroes2/resource/artifact.cpp
> -        { 0, 12, TYPE3, _( "Ultimate Book of Knowledge" ), _( "The %{name} increases your knowledge by %{count}." ) },
Use of `_()` here was incorrect.

2021-12-29 07:09 UTC, a1exsh commented on src/fheroes2/resource/artifact.cpp
> -    const char * GetPluralDescription( const Artifact & art, u32 count )
This function seems pointless: we know the correct form for each artifact anyway.

2021-12-29 10:49 UTC, oleg-derevenetz requested changes
Hi @a1exsh I just left one question here, please take a look when it's convenient for you.

2021-12-29 10:49 UTC, oleg-derevenetz commented on src/fheroes2/resource/artifact.cpp
> +        { 0, 12, TYPE3, "Ultimate Book of Knowledge", "The %{name} increases your knowledge by %{count}." },
Where will these lines (artifact names and descriptions) in the `.pot` file come from after such changes? These `_()`'s are needed to let the `xgettext` to include these strings in the `.pot`.

2021-12-29 13:07 UTC, a1exsh commented on src/fheroes2/resource/artifact.cpp
> +        { 0, 12, TYPE3, "Ultimate Book of Knowledge", "The %{name} increases your knowledge by %{count}." },
Haven't thought about that, obviously.  Let me revert this part.

2021-12-29 13:45 UTC, oleg-derevenetz commented on src/fheroes2/resource/artifact.cpp
> -    const char * GetPluralDescription( const Artifact & art, u32 count )
@a1exsh

> we know the correct form for each artifact anyway

How do we know that? For example, let's take the Endless Cord of Wood. In the singular form, the description should look like "The %{name} provides %{count} **_unit_** of wood per day." and in the plural form it should be "The %{name} provides %{count} **_units_** of wood per day." Who will replace "unit" by "units" in the proposed version of code?

2021-12-29 14:54 UTC, a1exsh commented on src/fheroes2/resource/artifact.cpp
> -    const char * GetPluralDescription( const Artifact & art, u32 count )
Well, that's easy: all the resource-producing artifacts actually always only produce _one_ unit per day, so there is no need for the plural form.  The same goes for the Wizard's Hat and the Enchanted Hourglass: the exact number of turns is known in advance, so there is no need for any variation in the translation messages.

2021-12-29 15:08 UTC, oleg-derevenetz commented on src/fheroes2/resource/artifact.cpp
> -    const char * GetPluralDescription( const Artifact & art, u32 count )
Yes it looks like it's a fossil from the time when the characteristics of artifacts were stored in separate xml files for modders. Now it's really unnecessary.

2021-12-29 15:11 UTC, oleg-derevenetz approved these changes

2021-12-30 16:39 UTC, a1exsh commented on src/fheroes2/maps/mp2.cpp
> +        return _n( "Water Wheel", "Water Wheels", 1 );
@ihhub The reason to change anything at all is explained in the linked issue: `xgettext` warnings at compile time.

What do you suggest to do instead of the proposed change?

2021-12-31 00:48 UTC, ihhub commented on src/fheroes2/maps/mp2.cpp
> +        return _n( "Water Wheel", "Water Wheels", 1 );
In this case I'm suggesting to remove `getPluralObjectName` function and add to `StringObject` an extra parameter called `const int count` with default value 1.

2021-12-31 07:12 UTC, a1exsh commented on src/fheroes2/maps/mp2.cpp
> +        return _n( "Water Wheel", "Water Wheels", 1 );
@ihhub done in b7122ee4

2022-01-01 04:48 UTC, merged

2022-01-01 04:48 UTC, ihhub commented
@a1exsh , thank you so much for this fix!

2022-01-27 07:35 UTC, a1exsh commented on src/fheroes2/resource/artifact.cpp
> +        { 0, 12, TYPE3, "Ultimate Book of Knowledge", "The %{name} increases your knowledge by %{count}." },
@ihhub @oleg-derevenetz should we actually change these uses of `_()` to `gettext_noop()`, so that no translation is attempted, but the `pot` file is populated?..

2022-01-28 09:49 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +        { 0, 12, TYPE3, "Ultimate Book of Knowledge", "The %{name} increases your knowledge by %{count}." },
Yes, we can.