Document and improve translation process
ihhub/fheroes2 pull request #4895
Opened 2022-01-04 02:54 UTC by yvesgurcan

- Adds documentation on how to work on translations.
- Updates README with minor improvements.
- Updates translation `Makefile` to enable copying MO files to build folders and clean up after creating MO files.
- Add `.dat` files to the list of ignored files (can be found in the `/data` folder).

2022-01-04 08:30 UTC, zenseii commented
Would you be able to make a preview of your .md changes similar to the one I made here for the translation.md mock-up:
https://github.com/zenseii/fheroes2/wiki/Translation-Guide ? 

Also, the translation guide should keep in mind that it should be possible to understand for people with zero background in programming, which is why an explanation of terminology is necessary.

2022-01-04 16:15 UTC, oleg-derevenetz requested changes
Hi @yvesgurcan I just left a few notices and questions regarding this pull request, please take a look when it's convenient for you.

2022-01-04 16:15 UTC, oleg-derevenetz commented on files/lang/Makefile
> +	cp *.mo ../../build/x86/Release-SDL2/files/lang 2>/dev/null || :
How exactly are these build directories created and why are they exactly like this and not some others? In general, binary should either be launched from the root of the source tree or `FHEROES2_DATA` environment variable should be set if for some reason it is launched from a non-standard location. There is also the `CONFIGURE_FHEROES2_DATA` preprocessor definition to set the location of `files/data` and `files/lang` directories at compile time. This is not a matter of the location of the translation files alone - for example, `resurrection.h2d` will not be found too, and `data` and `maps` directories from the source tree will not be found as well without this.

2022-01-04 16:15 UTC, oleg-derevenetz commented on files/lang/Makefile
> +	rm -f $<.tmp $<.2.tmp
All these `*.tmp` files will be removed at the `make clean` stage, is there any real reason to delete them immediately?

2022-01-05 12:59 UTC, ihhub requested changes
Hi @yvesgurcan , I left few comments as well. Could you please take a look?

2022-01-05 12:59 UTC, ihhub commented on docs/TRANSLATION.md
> +# [**fheroes2**](README.md) translation guide
We need to add a note that this documentation is only for Linux / MacOS users. An ordinary Windows user can't do such commands.

2022-01-05 12:59 UTC, ihhub commented on docs/TRANSLATION.md
> +Translatable strings can be found in the code source as arguments to the `_` function (which is a short name for `gettext`). The string below, for example, can be translated in PO files:
We also have `_n` function which is for plural forms.

2022-01-05 20:17 UTC, dimag0g commented on docs/TRANSLATION.md
> +The PO files are located in `/files/lang`. We encourage you to use [*poedit**](https://poedit.net/) to edit translations.
I suggest we at least mention [gtranslator](https://wiki.gnome.org/Apps/Gtranslator) for those who would like to use completely open-source software. Poedit has an open-source version too (https://github.com/vslavik/poedit), but the version from https://poedit.net/ is not.

2022-02-16 16:48 UTC, ihhub commented
Hi @oleg-derevenetz , I am thinking that for now we should remove **copy** stage and revert all changes within Makefile. This will make the documentation smaller and we can proceed with merging the rest of changes. What do you think?

2022-02-16 21:36 UTC, oleg-derevenetz commented
Hi @ihhub yes, I think so too. We will also need to remove the mention of `make copy` from the `TRANSLATION.md`.

2022-02-17 04:43 UTC, ihhub approved these changes

2022-02-17 07:42 UTC, a1exsh commented on docs/TRANSLATION.md
> +This project uses portable object (PO) files to handle localization in various languages. The current instruction is design for Linux/MacOS users. Windows users should install [Cygwin](https://www.cy
```suggestion
This project uses portable object (PO) files to handle localization in various languages. The current instruction is designed for Linux/MacOS users. Windows users should install [Cygwin](https://www.cygwin.com/) in order to be able to work with translations.

```

2022-02-17 07:43 UTC, a1exsh commented on docs/TRANSLATION.md
> +Translatable strings can be found in the source code as arguments to the `_` or `_n` functions (which are short names for `gettext` and `ngettext` functions respectively). The string below, for examp
What about `gettext_noop`?

2022-02-17 12:01 UTC, ihhub commented
Hi @a1exsh , I addressed your given comments.

2022-02-17 14:42 UTC, oleg-derevenetz approved these changes

2022-02-17 15:49 UTC, merged

2022-02-17 15:49 UTC, ihhub commented
@yvesgurcan , thank you so much for your contribution to the project!