AIWorldPathfinder: add support for paving the way through Whirlpools
ihhub/fheroes2 pull request #4904
Opened 2022-01-06 18:50 UTC by oleg-derevenetz

Continuation of #4894. That's how it currently works ([WRLTEST.ZIP](https://github.com/ihhub/fheroes2/files/7824054/WRLTEST.ZIP)):

<img width="1247" alt="Path through the whirlpool" src="https://user-images.githubusercontent.com/32623900/148433433-423736c9-7354-424d-892a-2b9a812a8c86.png">

The debugging principle is just like in #4894 (right-click by the mouse when debug hero is selected).

Please note that `World::GetWhirlpoolEndPoints()` has been rewritten and now it is perfectly deterministic, so it can be used just like `World::GetTeleportEndPoints()` in the AI-related code.

Hi @ihhub what do you think?

2022-01-07 00:07 UTC, ihhub commented
Hi @oleg-derevenetz , sadly we have merge conflicts here 😞 I'll take a look at this pull request later today.

2022-01-07 00:10 UTC, oleg-derevenetz commented
@ihhub No problem, I'll rebase this now.

2022-01-07 13:14 UTC, ihhub commented
Hi @oleg-derevenetz , it makes sense for AI to exploit such trick if it benefits from it.

2022-01-07 13:29 UTC, oleg-derevenetz commented
> it makes sense for AI to exploit such trick if it benefits from it.

Yeah, but unfortunately human player can't do that, because in his case the surfacing tile is chosen randomly :)

2022-01-07 13:48 UTC, oleg-derevenetz commented
@ihhub which would be better - merge this PR just with new `AIPathfinder`functionality (and implement whirlpool-related improvements for AI in a separate PR) or do everything within one PR?

2022-01-08 01:22 UTC, ihhub commented
Hi @oleg-derevenetz , since this pull request is specific only to a certain object on the map we should make all changes in one shot. I'll check how we can make AI to be smart enough to use both ways.

2022-01-10 15:14 UTC, ihhub commented
Hi @oleg-derevenetz , I've added simplest logic to determine if AI hero is able to pass throw whirlpools.

2022-01-10 19:42 UTC, oleg-derevenetz commented
Hi @ihhub I added the logic to handle Whirlpools in the `AIToWhirlpool()` just like Teleports (to preserve the path while going through the Whirlpool), and if AI sees the whole map, it attacks my castle immediately on the test map (as soon as AI is able to reach it). However, if AI doesn't see the whole map, it shows no interest in the whirlpool - it just visits a nearby island by boat and that's all. Maybe we need to tweak something else?

2022-01-11 19:00 UTC, oleg-derevenetz commented
BTW with the savefile from [here](https://github.com/ihhub/fheroes2/pull/4894#issuecomment-1006520512) AI still behaves the same way - endlessly dives into the whirlpool.

2022-01-13 12:24 UTC, ihhub commented
> Hi @ihhub I believe that I have managed to solve all the problems related to the whirlpool here. Key ideas are:
> 
>     * Enable the fog discovery through the stone liths and whirlpools in a transparent manner;
> 
>     * Do not consider stone liths and whirlpools as objects from an AI perspective (just like boats);
> 
>     * Pre-arrange AI army to minimize whirlpool losses;
> 
>     * Considering the previous point, I propose to allow all hero types to use whirlpools, but it's optional and debatable, and may be reverted.
> 
> 
> Could you please take a look? As I can see, AI behaves well on all test maps, you can try it yourself. The only minor issue is when AI tries to pave the way through the whirlpool and gets to a wrong tile (because whirlpools are unpredictable) - in such cases it tries again, and this can happen multiple times.

Finally I have some free time. I'm looking right now.

2022-01-13 14:44 UTC, ihhub commented
Hi @oleg-derevenetz , I've tested multiple scenarios. AI heroes are still obsessed with whirlpools but only to pave the path. To reduce this obsession we can introduce a penalty from moving from one cell of a whirlpool to another one. But this can be done in a separate pull request.

2022-01-13 14:56 UTC, ihhub commented
@oleg-derevenetz , also regarding allowance of every AI hero to use whirlpools: AI heroes has classes and not every hero should be allowed to use whirlpool and a very strong hero might loose a chunk of an important army. However, if it's easy to change in the future we can leave it as it is for now.

2022-01-13 15:01 UTC, ihhub requested changes
Hi @oleg-derevenetz , everything looks fine except few small issues which I pointed out. Could you please take a look at them?

2022-01-13 15:01 UTC, ihhub commented on src/fheroes2/world/world_pathfinding.cpp
> +            if ( MP2::isActionObject( newTileObject ) && newTileObject != MP2::OBJ_STONELITHS && newTileObject != MP2::OBJ_WHIRLPOOL ) {
Should we then add a Sign object as well? At least we can add a TODO comment to add "allowed" objects here.

2022-01-13 15:41 UTC, oleg-derevenetz commented on src/fheroes2/world/world_pathfinding.cpp
> +                                              hero.GetMovePoints(), hero.GetMaxMovePoints() );
@ihhub We did the same copying before, just like this:

```cpp
const int startIndex = hero.GetIndex();
const int color = hero.GetColor();
const double armyStrength = hero.GetArmy().GetStrength();
const uint32_t skill = hero.GetLevelSkill( Skill::Secondary::PATHFINDING );
const uint32_t remainingMovePoints = hero.GetMovePoints();
const uint32_t maxMovePoints = hero.GetMaxMovePoints();
```

The difference is that now we mention each parameter being compared exactly once, and there is no way to compare it but forget to update and so on.

2022-01-13 15:54 UTC, oleg-derevenetz commented on src/fheroes2/ai/ai_hero_action.cpp
> +        // TODO: remove this assertion, this should never happen
Discussed above.

2022-01-13 15:54 UTC, oleg-derevenetz commented on src/fheroes2/world/world_pathfinding.cpp
> +    auto currentSettings = std::forward_as_tuple( _pathStart, _pathfindingSkill, _currentColor, _remainingMovePoints, _maxMovePoints, _armyStrength );
Discussed above.

2022-01-13 16:20 UTC, oleg-derevenetz commented
Hi @ihhub

>  I've tested multiple scenarios. AI heroes are still obsessed with whirlpools but only to pave the path. To reduce this obsession we can introduce a penalty from moving from one cell of a whirlpool to another one. But this can be done in a separate pull request.

Most of the obsession is related to scenarios like this: consider that AI-controlled hero needs to get to the point marked by the cross:

![1](https://user-images.githubusercontent.com/32623900/149365823-e004a5f9-5a7c-4948-b8ab-e79c6a4a1b40.jpg)

and AI thinks that this can be done like this (and yes, it can be done like this - with a certain amount of luck):

![2](https://user-images.githubusercontent.com/32623900/149365958-9222ffe5-f972-4ee1-bab4-65e95785efb3.jpg)

But then happens this:

![3](https://user-images.githubusercontent.com/32623900/149366174-e4717f1d-be37-4bf7-af02-1b6ab8de0c8b.jpg)

and AI is like this: "OMG, what to do? I just did the task recalculation, and I still need to get to that point marked by the cross! I will try once again." And then he comes up again in the wrong whirlpool. Issues like this can't be reliably mitigated by penalties. We can try to mitigate it by cheating (no random for AI in whirlpools and stone liths - because stone liths with multiple exits are vulnerable to this as well), but I prefer AI to suffer the same way as a human in this regard. Anyway, this can be discussed separately.

>  also regarding allowance of every AI hero to use whirlpools: AI heroes has classes and not every hero should be allowed to use whirlpool and a very strong hero might loose a chunk of an important army. However, if it's easy to change in the future we can leave it as it is for now.

The problem here is that a strong AI-controlled hero might hesitate to capture the unguarded castle (or eliminate the weak enemy hero) because of his fear of whirlpools. I saw this even on the test map - the hero with the Titans did not want to attack the unguarded castle because of the whirlpool. That's why I added that logic instead, that does the auto-arrangement of the hero's army before the whirlpool (or, technically, before calculating losses) to minimize that losses.

2022-01-14 00:53 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +    // TODO: remove this assertion, this should never happen
I'm okay to leave the assertion as it is to make sure that someone else in the future won't break the logic. Let's leave it as it is🙂

2022-01-14 15:38 UTC, ihhub commented on src/fheroes2/world/world_pathfinding.cpp
> +            if ( MP2::isActionObject( newTileObject ) && newTileObject != MP2::OBJ_STONELITHS && newTileObject != MP2::OBJ_WHIRLPOOL ) {
There could be a scenario where the only way to discover more area is to pass through a sign.

2022-01-14 15:39 UTC, ihhub commented on src/fheroes2/world/world_pathfinding.cpp
> +            if ( MP2::isActionObject( newTileObject ) && newTileObject != MP2::OBJ_STONELITHS && newTileObject != MP2::OBJ_WHIRLPOOL ) {
Let's leave it as it is for now.

2022-01-14 15:40 UTC, ihhub approved these changes

2022-01-14 15:40 UTC, ihhub commented
@oleg-derevenetz , looks good to me. If you have no more changes pending then we can proceed with merging.

2022-01-14 15:42 UTC, oleg-derevenetz commented
Hi @ihhub 

> looks good to me. If you have no more changes pending then we can proceed with merging.

No changes pending so far, if there are new ideas, it will be possible to make separate PRs :)

2022-01-14 15:43 UTC, merged

2022-01-14 15:43 UTC, ihhub commented
@oleg-derevenetz , wonderful job! Well done!