Fix translation of saved default player names
ihhub/fheroes2 pull request #4908
Opened 2022-01-08 13:34 UTC by oleg-derevenetz

fix #4906

2022-01-10 15:06 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left few comments here. Could you please take a look?

2022-01-10 15:06 UTC, ihhub commented on src/fheroes2/system/save_format_version.h
> +    FORMAT_VERSION_0912_RELEASE = 9702,
We added a new version but don't use it in the code. I think we should have some logic related to it.

2022-01-10 15:08 UTC, oleg-derevenetz commented on src/fheroes2/system/save_format_version.h
> +    FORMAT_VERSION_0912_RELEASE = 9702,
Hi @ihhub version field size is just 16bit AFAIK. Am I missing something?

2022-01-10 15:10 UTC, oleg-derevenetz commented on src/fheroes2/system/save_format_version.h
> +    FORMAT_VERSION_0912_RELEASE = 9702,
@ihhub The new version is required due to the fact that new savefiles will be incompatible with old game releases. But there is no need for any fixups in the case of new releases loading old savefiles.

2022-01-10 15:17 UTC, ihhub commented on src/fheroes2/system/save_format_version.h
> +    FORMAT_VERSION_0912_RELEASE = 9702,
Oh, I missed this. Then this is bad. Shall we put at least 9800?

2022-01-10 15:18 UTC, oleg-derevenetz commented on src/fheroes2/system/save_format_version.h
> +    FORMAT_VERSION_0912_RELEASE = 9702,
OK. But it seems that these 16 bits are exhausting too fast :)

2022-01-13 12:16 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left one suggestion here. Could you please take a look at it?

2022-01-17 12:25 UTC, merged

2022-01-17 12:25 UTC, ihhub commented
@oleg-derevenetz , thank you very much for this fix!