Adjust AI spell estimates
ihhub/fheroes2 pull request #4913
Opened 2022-01-10 13:55 UTC by idshibanov

Related to #3239 (partial fix).

Separate tactical and strategic magic estimates to make sure AI's archer strength wouldn't be overvalued. Tune values to account for number of spell casts possible.

2022-01-10 15:03 UTC, ihhub commented
Welcome back, @idshibanov ! 👍

2022-01-11 15:36 UTC, ihhub commented
Hi @Branikolog , could you please test these changes? The changes are made to adjust estimation by AI towards a castle attacker and overall army strength.

2022-01-11 15:36 UTC, ihhub requested changes
Hi @idshibanov , I left few styling comments. Could you please check them?

2022-01-11 15:36 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal.h
> +        static double CommanderDamageValue( const HeroBase & commander );
Please start method's name from non-capital letter.

2022-01-11 15:36 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal.h
> +        static double CommanderDamageValue( const HeroBase & commander );
Shall we call it `commanderMaximumSpellDamageValue`? As right now the name is misleading.

2022-01-11 23:35 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal.h
> +        static double CommanderDamageValue( const HeroBase & commander );
> Please start method's name from non-capital letter.

Even for static method?

> Shall we call it commanderMaximumSpellDamageValue? As right now the name is misleading.

A bit too long for my taste, especially `BattlePlanner::commanderMaximumSpellDamageValue()`. Naming things is always hard.

2022-01-12 08:26 UTC, Branikolog commented
Hi, @ihhub and @idshibanov !
I'm not sure, what exactly I should test here.
Currently, with this changes in a case we eliminate AI's rangers he's still waiting inside castle, relying on towers, while he can do more efficiently rushing my shooters (since he has considerable army):
![image](https://user-images.githubusercontent.com/55348946/149090846-b532ed1b-f91f-41e2-b4fb-e6c6ae06dacf.png)

2022-01-13 12:17 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal.h
> +        static double CommanderDamageValue( const HeroBase & commander );
It's better to have a long name than a short cryptic one :)

2022-01-18 14:56 UTC, idshibanov commented
@Branikolog this case looks like a tower issue rather than spells. Do you still have the save for the siege so I can check it?

2022-01-24 13:53 UTC, ihhub commented
Hi @idshibanov and @Branikolog , what we decided to do? Are we good with these changes or do we need to do some modifications?

2022-02-11 03:10 UTC, idshibanov commented
> Hi @idshibanov and @Branikolog , what we decided to do? Are we good with these changes or do we need to do some modifications?

I believe that this particular PR is hard to test without siege (and tower strength) changes. I'll probably make the tower change separately then we can come back to this.

2022-03-30 18:00 UTC, merged

2022-03-30 18:00 UTC, ihhub commented
@idshibanov , thanks a lot for these changes!