Reduce SDL dependency and warnings on Visual Studio
ihhub/fheroes2 pull request #4925
Opened 2022-01-13 12:07 UTC by ihhub

from 75 to 50. Little more efforts and we can make all warnings to be treated as errors.

2022-01-13 18:45 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few notes, please take a look when you have time.

2022-01-13 18:45 UTC, oleg-derevenetz commented on src/engine/image.cpp
> +            std::fill( transform(), transform() + totalSize, static_cast<uint8_t>( 0 ) );
If the problem here (and in other such places) is the sign incompatibility, we just can use the unsigned integer literal (`0U`) instead of the `static_cast`.

2022-01-13 18:45 UTC, oleg-derevenetz commented on src/engine/tools.cpp
> +    size_t dataReaded = 0;
I'd rename this as `dataAlreadyRead` or something like this. AFAIK there is no such form as "readed" :) The past tense of "read" is also "read".

2022-01-13 18:45 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +    ptrdiff_t finish = 0;
Using `ptrdiff_t` for a plain counter that has nothing to do with pointer arithmetic looks a bit odd. I suggest to use `int` and just convert the result of the `std::count_if()` call below to `int` using `static_cast`.

2022-01-14 00:50 UTC, ihhub commented on src/engine/tools.cpp
> +    size_t dataReaded = 0;
Okay, this is  a dumb mistake 🤣

2022-01-14 00:51 UTC, ihhub commented on src/engine/image.cpp
> +            std::fill( transform(), transform() + totalSize, static_cast<uint8_t>( 0 ) );
Sure. Let me try if VS will complain about this.

2022-01-14 00:51 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    ptrdiff_t finish = 0;
Yeah, it'll work too. I wanted to avoid casting but you're right about pointer related types.

2022-01-17 12:18 UTC, ihhub commented on src/engine/image.cpp
> +            std::fill( transform(), transform() + totalSize, static_cast<uint8_t>( 0 ) );
Nope. Visual Studio still complains about them.

2022-01-17 12:52 UTC, oleg-derevenetz approved these changes

2022-01-17 14:12 UTC, merged