Update Polish translation
ihhub/fheroes2 pull request #4938
Opened 2022-01-21 22:00 UTC by Arthusppp

Update Polish translation.

2022-01-25 09:19 UTC, michkry commented on files/lang/pl.po
> +msgstr "Wybierz zaklęcia:"
Since the word "Spell" is in singular form, the translation should also be written in singular. Shouldn't it be "Wybierz zaklęcie" instead of "Wybierz zaklęcia:"?

2022-01-25 09:30 UTC, michkry commented on files/lang/pl.po
> +msgstr "Wojna o Sukcesję (podstawka)"
The word "podstawka" in parenthesis means "base game". I think we should remove it because in the english version of the title there is no such annotation

2022-01-25 09:31 UTC, michkry commented on files/lang/pl.po
> +msgstr "Cena Lojalności (rozszerzenie)"
The word "rozszerzenie" in parenthesis means "expansion". I think we should remove it because in the english version of the title there is no such annotation

2022-01-25 09:35 UTC, michkry commented on files/lang/pl.po
> +msgstr "Typ mapy"
The letter "m" of "mapy" should be uppercase. The translation should be "Typ Mapy"

2022-01-25 09:42 UTC, michkry commented on files/lang/pl.po
> +msgstr "Partie wokalne"
In my opinion better translation of the word "Vocalists" is "Wokaliści". Don't know what "Partie wokalne" means

2022-01-26 10:05 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Wojna o Sukcesję (podstawka)"
Ok, let's stick literally to the OG.

2022-01-26 10:06 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Cena Lojalności (rozszerzenie)"
As the previous comment.

2022-01-26 10:09 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Typ mapy"
Disagree. Because the whole window uses this casing. If we want to change it, then we should update the whole window. 
Also (not an argument, but...) he OG uses "Typ mapy" here as well.

2022-01-26 10:13 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Partie wokalne"
For me, this suits here very well. "Partie wokalne" is used with classical or medieval music. "Wokaliści" is used more in modern genres.

> Partia wokalna jest to ta część utworu muzycznego, którą wykonuje się śpiewem. Wszystkie inne instrumenty w takim utworze to akompaniament.

2022-01-26 22:12 UTC, michkry approved these changes

2022-01-29 01:10 UTC, ihhub requested changes
Hi @Arthusppp , I left few comments here. Could you please check them?

2022-01-29 01:10 UTC, ihhub commented on files/lang/pl.po
> +"Wskazuje czy mapa jest mała (36 x 36), średnia (72 x 72), duża (108 x 108), czy też bardzo duża (144 x 144)."
Could you please explain why we changed these lines?

2022-01-29 01:10 UTC, ihhub commented on files/lang/pl.po
> +# msgstr "Populacja %{monster} zwiększa się o +%{count}."
Please remove this commented line.

2022-01-29 19:44 UTC, Arthusppp commented on files/lang/pl.po
> +"Wskazuje czy mapa jest mała (36 x 36), średnia (72 x 72), duża (108 x 108), czy też bardzo duża (144 x 144)."
Reverted. I will keep "80 chars line length" rule.

2022-01-29 19:44 UTC, Arthusppp commented on files/lang/pl.po
> +# msgstr "Populacja %{monster} zwiększa się o +%{count}."
Removed.
Many thanks for your review! :)

2022-01-30 08:10 UTC, merged

2022-01-30 08:10 UTC, ihhub commented
@Arthusppp , thank you so much for your valuable contribution to the project!

2022-01-30 09:52 UTC, dimag0g commented
@Arthusppp @michkry 

FIY I have rebased my changes in #4930 with this update. My update is a merge of `pl.po` with an updated template, which is mostly an automated process. It has a nasty tendency to eagerly reuse existing translations for untranslated strings, based on very loose heuristics (e.g. in Russian it translated "Weed Patch" with the existing translation for "Gold Watch"). Since `pl.po` still has quite a couple of hundreds of missing translations, you may want to take another look at `pl.po` once #4930 is merged.