modify army order setting
ihhub/fheroes2 pull request #4947
Opened 2022-01-22 15:06 UTC by ihhub

Now it's a part of battle settings window and can be changed anytime during battle. The current unit has the same cycling color as the current monster. Moved creatures have grayed icons. Border of rectangles associates with the color of monsters.

2022-01-22 15:26 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few comments, please take a look when you have time.

2022-01-22 15:26 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_dialogs.cpp
> +            saveShowArmyOrder = true;
I believe there is some inconsistency. Why we are setting the `saveShowArmyOrder` here but calling the `conf.setBattleAutoSpellcast()`?

2022-01-22 15:26 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_dialogs.cpp
> +            saveAutoSpellCast = true;
The same inconsistency as earlier. We are setting the `saveAutoSpellCast` here but calling the `conf.setBattleShowArmyOrder()`.

2022-01-22 15:35 UTC, oleg-derevenetz commented
Is there no more suitable picture for this setting? I can't even say for sure what is drawn in the picture used now :)

2022-01-23 01:47 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +            saveShowArmyOrder = true;
It's a bug.

2022-01-23 01:48 UTC, ihhub commented
> Is there no more suitable picture for this setting? I can't even say for sure what is drawn in the picture used now - some sort of a paper with cooking recipe may be :)

Haha! You're right. It feels ugly. I'll try to come up with some background image for this.

2022-01-26 12:41 UTC, ihhub commented
Hi @oleg-derevenetz , I honestly out of ideas to replace these images with something better :(

2022-01-26 13:09 UTC, oleg-derevenetz commented
@ihhub

> Hi @oleg-derevenetz , I am honestly out of ideas to replace these images with something better :(

Well, let's leave it as is for now :) May be in future some volunteer artist will be able to create something.

2022-01-26 13:22 UTC, merged

2022-02-05 10:50 UTC, oleg-derevenetz commented
Hi @ihhub BTW what is the procedure of making a new entry in `resurrection.h2d`? What are requirements for images? If I have some BMP/JPG/PNG file, how can I add it to the `resurrection.h2d` and use it as an sprite in the game?

2022-02-06 05:14 UTC, ihhub commented
Hi @oleg-derevenetz ,

First of all you need to convert your image into readable by the game format. This can be done by `fheroes2::Load()` call. To see how it looks like in the same you can save it right after loading by calling `fheroes2::Save()`.

Once your image is loaded you need to load `resurrection.h2d` file. For this purpose use `fheroes2::H2RReader` class. Then create a new instance of `fheroes2::H2Writer` class and call `add` method with `fheroes2::H2RReader` instance. After this use `fheroes2::writeImageToH2D` function to add your newly loaded image into H2RWriter and then call `write` method of the class.