Fix the "week of monsters"
ihhub/fheroes2 pull request #4948
Opened 2022-01-22 20:42 UTC by oleg-derevenetz

fix #4944

Regression after #4688 - week type was calculated too late.

This PR also fixes potential dangling pointer issue with the `World::_rumor` (if `World::vec_rumors` was cleared, we could get a dangling pointer) and also removes the unused `World::week_next` (partially, because it is present in a savefile, and I don't want to clash with #4931 yet, so I left a TODO comment for now).

2022-01-24 12:13 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left one comment here. Could you please take a look?

2022-01-24 12:13 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +    // TODO: remove this
Shouldn't we then not to even write week data? We can still read it for older versions.

2022-01-24 12:22 UTC, oleg-derevenetz commented on src/fheroes2/world/world.cpp
> +    // TODO: remove this
Hi @ihhub Yes, I'll do this for sure, but the problem is in #4931 - it also messes with savefiles, so I do not want to add the code here that I'll need to rewrite anyway when #4931 will be merged. So we can either wait until #4931 will be merged, rebase this PR and add the corresponding logic, or we can make a separate PR for this.

2022-01-24 13:50 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +    // TODO: remove this
Let's merge #4931 first. I left there just one comment. Please take a look.

2022-01-24 21:55 UTC, oleg-derevenetz commented
Hi @ihhub I have an idea to make the world week seed dependent only on map seed and number of the week.

Pros:

* We can calculate different things (such as week type and rumor) on the fly in a deterministic manner. No need to save this data in the savefile and periodically recalculate (what is possible to forget about);
* Such an approach can (in perspective) be used to deal with issues described in the #4265.

Cons:

* This approach does not depend on the player's actions, and thus is somewhat more predictable.

What do you think?

2022-01-26 12:46 UTC, ihhub commented
> Hi @ihhub I have an idea to make the world week seed dependent only on map seed and number of the week.
> 
> Pros:
> 
>     * We can calculate different things (such as week type and rumor) on the fly in a deterministic manner. No need to save this data in the savefile and periodically recalculate (what is possible to forget about);
> 
>     * Such an approach can (in perspective) be used to deal with issues described in the [New week, week of the creature, available heroes, generated resources, etc. should be the same if a save file is loaded #4265](https://github.com/ihhub/fheroes2/issues/4265).
> 
> 
> Cons:
> 
>     * This approach does not depend on the player's actions, and thus is somewhat more predictable.
> 
> 
> What do you think?

I think it should be dependent on monsters on the map. If I remember correctly this is how it works in the original game.

2022-01-26 13:08 UTC, oleg-derevenetz commented
@ihhub

> I think it should be dependent on monsters on the map. If I remember correctly this is how it works in the original game.

I don't see any dependency on the map monsters in week of/month of generation code (`kingdom/week.cpp`) As I can see, it depends only on a week/month number and the seed.

2022-01-26 13:24 UTC, ihhub commented
> @ihhub
> 
> > I think it should be dependent on monsters on the map. If I remember correctly this is how it works in the original game.
> 
> I don't see any dependency on the map monsters in week of/month of generation code (`kingdom/week.cpp`) As I can see, it depends only on a week/month number and the seed.
> 
> P.S. So if I kill some monster of the map, it should somehow affect the week/month type?

You should. @Branikolog  can you please shed some light on this question?

2022-01-26 14:39 UTC, oleg-derevenetz commented
@ihhub

> You should. @Branikolog can you please shed some light on this question?

OK, I reverted this part, now the seed used for the calculation of week/month type depends on map state as before.

2022-01-27 00:10 UTC, ihhub commented
@oleg-derevenetz , hold on please with reverting back changes :) We didn't even hear the expert @Branikolog . I wrote "should" based on my observations and I still might be wrong.

@LeHerosInconnu could you please tell us whether new week type depends on monsters on the map?

2022-01-27 17:54 UTC, oleg-derevenetz commented
Hi @ihhub I just did a few tests - started the multiplayer game on a apecially crafted map for 2 players, just always skipped turns for every player (no hero moves, no attacks, etc), and loaded the AUTOSAVE several times on 121 (thus effectively repeating the new week's event). Each time I got a new week of a different type. Thus, it seems that in OG the type of a new week is not deterministic. You can try it yourself: load [NEWWEEK.zip](https://github.com/ihhub/fheroes2/files/7952751/NEWWEEK.zip) and just skip the turn, then load it again and skip the turn once again and so on. In each case, you will receive a different type of new week.

2022-01-27 19:37 UTC, LeHerosInconnu commented
Hello @ihhub and @oleg-derevenetz,

> @oleg-derevenetz , hold on please with reverting back changes :) We didn't even hear the expert @Branikolog . I wrote "should" based on my observations and I still might be wrong.
> 
> @LeHerosInconnu could you please tell us whether new week type depends on monsters on the map?

There is information about "Week of" and "Month of" from the linked page (towards the end of the page) in this discussion: https://github.com/ihhub/fheroes2/discussions/4676. :)

2022-01-27 19:50 UTC, oleg-derevenetz commented
Hi @LeHerosInconnu

> There is information about "Week of" and "Month of" from the linked page (towards the end of the page) in this discussion: #4676. :)

Yes, but the information I need is not there :) I need to know is the probability of every single week of/month of fully random or deterministic, and, if it is deterministic, what does it depend on. My experiments above have shown that in OG this probability is (apparently) completely random, but I have a proposal to make it deterministic (depending on the map seed and week/month number).

2022-01-28 21:32 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu
> 
> > There is information about "Week of" and "Month of" from the linked page (towards the end of the page) in this discussion: #4676. :)
> 
> Yes, but the information I need is not there :) I need to know is the probability of every single week of/month of fully random or deterministic, and, if it is deterministic, what does it depend on. My experiments above have shown that in OG this probability is (apparently) completely random, but I have a proposal to make it deterministic (depending on the initial map seed and week/month number).

It's random in the original game but not sure if it is "fully random".
When reloading saves, the "Week of" and "Month of" changes.
I always found it a bit too easy to influence these events in this way (reloading saves), and I would prefer a deterministic way of working. :)
I think it would be a good improvement over the original game.
But it's okay to keep the randomness from the original game.

Here are some save files to test this:
[New week and month 01.zip](https://github.com/ihhub/fheroes2/files/7961941/New.week.and.month.01.zip)

2022-01-29 09:22 UTC, oleg-derevenetz commented
> It's random in the original game but not sure if it is "fully random".

By "fully random" I mean that it doesn't depend on player's actions. Since I always start from he same map state (by loading the same savefile) and then repeat the same set of actions (or rather, no actions) and get different results each time, then it's "fully random" :)

2022-01-29 14:52 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

> > It's random in the original game but not sure if it is "fully random".
> 
> By "fully random" I mean that it doesn't depend on player's actions. Since I always start from the same map state (by loading the same savefile) and then repeat the same set of actions (or rather, no actions) and get different results each time, then it's "fully random" :)

One thing I noticed in the original game is that for the Month of the Plague it is sometimes possible to avoid it by reloading a save and moving a hero or buying creatures but other times no matter what you change the Month of the Plague always happens.

2022-01-30 14:56 UTC, ihhub commented
Hi @oleg-derevenetz  and @LeHerosInconnu , am I right to say that dependency on monsters is considered more random than dependency from date only making it close to the original? If yes then we can proceed with merging.

2022-01-30 15:04 UTC, oleg-derevenetz commented
Hi @ihhub I'd say that in OG there is no dependency on anything :) Also I understand so that @LeHerosInconnu is not against an additional determinism in this regard.

2022-01-30 15:06 UTC, merged

2022-01-30 15:06 UTC, ihhub commented
In this case @oleg-derevenetz huge thanks for this work!