German Button generation
ihhub/fheroes2 pull request #4951
Opened 2022-01-25 02:07 UTC by Laserlicht

Generation of "Kampf" button.

![image](https://user-images.githubusercontent.com/13953785/150897408-55b6a5df-3896-4e14-8ad6-fc7350ce8ffe.png)

Solves #3116

2022-02-03 14:29 UTC, ihhub requested changes
Hi @Laserlicht , I left few comments and suggestions regarding this pull request. Could you please have a look at them?

2022-02-03 14:29 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +#include "settings.h"
This file inclusion is the main concern from my side. It mustn't be included as agg_image logic should not depend on settings of the game. Also the proposed solution won't work for cases when a player switches between languages. Once ICN is loaded it doesn't change.

2022-02-03 14:29 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +        void generateICNEnglish( int id )
Why don't we detect CRC32 of each English and then choose the logic suitable for the detected resources? Having English based game and using German language will lead to very interesting issues. The same applies for English language within German resources. Could you please verify this?

2022-02-04 20:42 UTC, Laserlicht commented on src/fheroes2/agg/agg_image.cpp
> +#include "settings.h"
Okay, I see. Of course, I'm not that into it yet.

2022-02-04 20:43 UTC, Laserlicht commented on src/fheroes2/agg/agg_image.cpp
> +        void generateICNEnglish( int id )
I changed it and used the function from ui_language.cpp for it. Is that better?

2022-03-21 08:20 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +        void generateICNEnglish( int id )
Yes, it is.

2022-03-21 08:20 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +        void generateICNEnglish( int id )
Yes, it is.

2022-04-02 17:19 UTC, merged

2022-04-02 17:19 UTC, ihhub commented
@Laserlicht , thank you very much for your contribution to the project!