Log the auto battle break event
ihhub/fheroes2 pull request #4980
Opened 2022-02-04 02:21 UTC by oleg-derevenetz

Currently the usage of `Battle::Arena::BreakAutoBattle()` is not logged.

2022-02-05 08:12 UTC, ihhub requested changes
Hi @oleg-derevenetz , I put few comments in this pull request. Could you please check them if they make sense?

2022-02-05 09:37 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_arena.cpp
> +        if ( !actions.empty() ) {
@ihhub `MSG_BATTLE_AUTO` is already ignored for the purpose of seed generation. And other possible future pure GUI-related actions should be ignored too. There is nothing new in this PR in this regard.

2022-02-06 01:13 UTC, ihhub commented on src/fheroes2/battle/battle_arena.cpp
> +        if ( !actions.empty() ) {
Thank you very much for the explanation!

2022-02-06 01:13 UTC, merged

2022-02-06 01:13 UTC, ihhub commented
@oleg-derevenetz , thanks a lot for improving the code!