Update Polish translation
ihhub/fheroes2 pull request #4988
Opened 2022-02-05 23:20 UTC by Arthusppp

Update Polish translation

2022-02-06 14:14 UTC, ihhub requested changes
Hi @Arthusppp , I left 2 comments with my limited knowledge of Polish. Could you please take a look?

2022-02-06 14:14 UTC, ihhub commented on files/lang/pl.po
> +msgstr "Krwi!"
I think this message is used when we show a popup window for moral and it includes in the sentence. If it's true then we shouldn't set an exclamation mark at the end.

2022-02-06 14:14 UTC, ihhub commented on files/lang/pl.po
>  msgstr "Czar nie udany!"
It's better to keep `%{spell}` as it shows the name of the spell.

2022-02-06 14:21 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Krwi!"
This is somehow easter egg from the OG which I like very much!

![image](https://user-images.githubusercontent.com/85434237/152685341-3e2dc335-48b1-4127-80f5-8051a116f6fd.png)

2022-02-06 14:22 UTC, Arthusppp commented on files/lang/pl.po
>  msgstr "Czar nie udany!"
Oh gosh, you are totally right! I am updating it.

2022-02-06 14:25 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Krwi!"
The fheroes2 screen: 
![image](https://user-images.githubusercontent.com/85434237/152685506-099ad7b3-8a0a-47e5-b09c-318e813e8b0b.png)

2022-02-06 14:35 UTC, ihhub commented on files/lang/pl.po
> +msgstr "Krwi!"
This window uses the following translation:
```
msgid "morale|Blood!"
msgstr "Krwi!"
```
which is present in the file. The line you've modified corresponds to a popup window if you click on the moral icon in the top right corner of hero's dialog.

2022-02-06 14:36 UTC, ihhub commented on files/lang/pl.po
> +msgstr "Krwi!"
![image](https://user-images.githubusercontent.com/19829520/152685933-82cd8e2e-178a-4898-8fef-1d25c17e51e2.png)

2022-02-06 14:44 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Krwi!"
Oh gosh, I have missed it. I will withdraw my change.

2022-02-06 16:59 UTC, michkry commented on files/lang/pl.po
>  msgstr "Czar nie udany!"
I think we should change "nie udany" to "nieudany", in addition to the change exposed by ihhub

2022-02-06 17:30 UTC, michkry commented on files/lang/pl.po
> +msgstr "%{name} daje ci %{count} jednostkę siarki dziennie."
In my opinion "zapewnia" fits better than "daje ci". It reflects more accurately the meaning of the original sentence

2022-02-06 17:31 UTC, michkry commented on files/lang/pl.po
> +msgstr "%{name} daje ci %{count} jednostkę rtęci dziennie."
Same as above

2022-02-06 17:32 UTC, michkry commented on files/lang/pl.po
> +msgstr "%{name} daje ci %{count} jednostkę klejnotów dziennie."
Same as above

2022-02-06 17:48 UTC, michkry commented on files/lang/pl.po
> +"do swojej księgi czarów?\n"
In the line 5149 we refer to Spell Book as "Księga Magii". Here "Magic Book" is called "Księga czarów". Shouldn't we use "Księga Magii" here as well?

2022-02-06 17:56 UTC, michkry commented on files/lang/pl.po
> +msgstr "Koszt punktów ruchu: %{mp}"
I'm unaware of the context in which this literal is used but I think that "Punkty ruchu" expresses better its original meaning

2022-02-06 18:12 UTC, michkry commented on files/lang/pl.po
> +msgstr "bohaterowie: pozwól kupować księgę magii z kaplic"
I think that we should change "z kaplic" to "w kaplicach"

2022-02-06 18:55 UTC, michkry commented on files/lang/pl.po
> +"%{name} przywraca twemu bohaterowi dodatkowe %{count} punkty magii na turę."
Shouldn't we use "twojemu" instead of "twemu"?

2022-02-06 19:23 UTC, michkry commented on files/lang/pl.po
>  msgstr "%{name} zwiększa twoją umiejętność nekromancji."
I think we should change "twoją umiejętność" to "twoje umiejętności"

2022-02-06 19:46 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "%{name} daje ci %{count} jednostkę siarki dziennie."
Ok, let's change all towards "zapewnia".

2022-02-06 19:48 UTC, Arthusppp commented on files/lang/pl.po
> +"do swojej księgi czarów?\n"
Correct and correct! I am updating the translation! :)

//and I promise, some day I will look holistically at all inconsistencies like this: "księga magii/księga zaklęć", "stwór/potwór/jednostka", "czar/zaklęcie", etc. ;)

2022-02-06 19:49 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Koszt punktów ruchu: %{mp}"
I suggest to keep as I proposed. The whole message here is:

> "Czy chcesz wykorzystać swoją wiedzę magiczną, aby zapisać %{spell} ze zwoju "
> "do swojej księgi zaklęć?\n"
> "Zwój zostanie wykorzystany.\n"
> "Koszt punktów magii: %{sp}"
> "Koszt punktów ruchu: %{mp}"

2022-02-06 19:50 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "bohaterowie: pozwól kupować księgę magii z kaplic"
Ok.

2022-02-06 19:51 UTC, Arthusppp commented on files/lang/pl.po
> +"%{name} przywraca twemu bohaterowi dodatkowe %{count} punkty magii na turę."
"Krótsze formy (np. ma, me, mej, twe) mają charakter książkowy i są używane rzadko." So - fheroes2 is not a book! Changing to "twojemu"! Thanks for catching this!

2022-02-06 20:24 UTC, Arthusppp commented on files/lang/pl.po
>  msgstr "%{name} zwiększa twoją umiejętność nekromancji."
I do not think so, as the "nekromancja" is singular only.

2022-02-07 00:15 UTC, merged

2022-02-07 00:16 UTC, ihhub commented
@Arthusppp , thank you so much for these changes!