Fix multiple compilation warnings
ihhub/fheroes2 pull request #5005
Opened 2022-02-12 04:27 UTC by ihhub

- reduce the amount of static_cast usages
- use correct variable types
- add extra checks to avoid future code breaks

2022-02-12 13:31 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left two recommendations here, please take a look when it's convenient for you.

2022-02-12 13:31 UTC, oleg-derevenetz commented on src/engine/pal.cpp
> +            }
We can take declaration of the `newColorID` and palette update out of the `if` statement to avoid code duplication:

```cpp
uint32_t newColorID;

if ( colorSet.forward ) {
[...]
}
else {
[...]
}

palette[colorSet.start + id] = static_cast<uint8_t>( newColorID );
```

But it's a matter of taste.

2022-02-13 06:29 UTC, idshibanov approved these changes
Tentative approval. Good to merge once you address the comment above.

2022-02-13 15:38 UTC, oleg-derevenetz approved these changes

2022-02-14 16:04 UTC, merged