AI should save current unit if retreating
ihhub/fheroes2 pull request #5038
Opened 2022-02-19 05:19 UTC by idshibanov

Fixes #4656 .

Happens when AI makes last spell cast before fleeing the battle and planning to invoke power mass spell like Armageddon.

2022-02-19 10:22 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +                if ( retreating && unit->isUID( currentUnit.GetUID() ) && std::fabs( valueLost - unit->GetStrength() ) < 0.001 ) {
Hi @idshibanov just curious, is there a reason to use `isUID( GetUID() )` in such cases instead of pointer comparison? I see that UIDs are used mostly within commands (I suppose to support gaming over the network, because pointers cannot be passed over the network), and in other places pointers are simply compared.

2022-02-19 15:27 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +                if ( retreating && unit->isUID( currentUnit.GetUID() ) && std::fabs( valueLost - unit->GetStrength() ) < 0.001 ) {
I always thought that pointer comparison is unreliable especially since `currentUnit` reference is passed in from somewhere else and not directly a part of `friendly` collection.

2022-02-19 15:51 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +                if ( retreating && unit->isUID( currentUnit.GetUID() ) && std::fabs( valueLost - unit->GetStrength() ) < 0.001 ) {
Passing by reference doesn't change an address of an object, so we can apply `&` to the reference to an object and get the same pointer as if we applied `&` to the object itself, because references [are not separate objects](https://isocpp.org/wiki/faq/references#reseating-refs) and cannot be considered separately from the objects they refer to. However if somewhere in the call chain object was passed via a copy, then it's naturally a different story :) But AFAIK it's not the case in the battle-related code. Anyway it's up to you of course.

2022-02-19 16:15 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +                if ( retreating && unit->isUID( currentUnit.GetUID() ) && std::fabs( valueLost - unit->GetStrength() ) < 0.001 ) {
> if somewhere in the call chain object was passed via a copy, then it's naturally a different story

That's what I'm trying to avoid exactly. Although not the case today this is outside of the BattlePlanner class realm. Plus UIDs are already there and perfectly fit the need :)

2022-02-19 16:29 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +                if ( retreating && unit->isUID( currentUnit.GetUID() ) && std::fabs( valueLost - unit->GetStrength() ) < 0.001 ) {
@idshibanov Yeah, that's true. I'll propose a PR today that explicitly disables copy and move constructors and assignment operators for `Battle::Unit` and descendants, because current code in many places relies on the fact that all units are in heap and their addresses can be freely compared.

2022-02-22 13:57 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +                if ( retreating && unit->isUID( currentUnit.GetUID() ) && std::fabs( valueLost - unit->GetStrength() ) < 0.001 ) {
Hi @idshibanov and @oleg-derevenetz , since copy and move constructors are disabled should we change the code here?

2022-02-22 13:57 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +                        if ( retreating && target.defender->isUID( currentUnit.GetUID() ) && std::fabs( valueLost - target.defender->GetStrength() ) < 0.001 ) {
I think the same question highlighted by @oleg-derevenetz is applied for this line as well.

2022-02-22 13:58 UTC, ihhub requested changes
Hi @idshibanov , I am marking this pull request as requires changes just to notify you about highlighted by @oleg-derevenetz possible improvement.

2022-02-22 13:59 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +                        if ( retreating && target.defender->isUID( currentUnit.GetUID() ) && std::fabs( valueLost - target.defender->GetStrength() ) < 0.001 ) {
Hi @ihhub this is not necessary, I'm OK with both variants.

2022-02-22 14:02 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_spell.cpp
> +                        if ( retreating && target.defender->isUID( currentUnit.GetUID() ) && std::fabs( valueLost - target.defender->GetStrength() ) < 0.001 ) {
Well, in this case let's proceed with merging :)

2022-02-22 14:02 UTC, merged