Use move constructor instead of copying strings by value
ihhub/fheroes2 pull request #5062
Opened 2022-03-03 11:40 UTC by ihhub

In this case we avoid extra memory copy. Also this pull request contains some small code cleanup.

2022-03-03 19:27 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few optional suggestions, please take a look when it's convenient for you.

2022-03-03 19:27 UTC, oleg-derevenetz commented on src/fheroes2/gui/ui_dialog.h
> +        ResourceDialogElement( const int32_t resourceType, std::string && text );
Instead of these two constructors we can have just one here and in other similar places:

```cpp
ResourceDialogElement( const int32_t resourceType, std::string text );
```

and initialize member `_text` using `std::move()`:

```cpp
_text( std::move( text ) )
```

In this case, the code would be a little simpler (and we will not need the separate `init()`), BUT we will perform two movements where we currently do just one. Considering that moving is a cheap operation, the simpler code may be worth it, but it's up to you.

2022-03-03 19:27 UTC, oleg-derevenetz commented on src/fheroes2/gui/text.h
> +    TextBox() = delete;
Since we have other user-defined constructors here, we can just remove this.

2022-03-04 13:16 UTC, ihhub commented on src/fheroes2/gui/ui_dialog.h
> +        ResourceDialogElement( const int32_t resourceType, std::string && text );
This is quite tricky. On the one hand, you are absolutely right. We must reduce code duplication. On the other hand, other developer might tend to change passing by value to passing by reference. Also static analyzers might complain about this.

What do you think?

2022-03-04 13:17 UTC, ihhub commented on src/fheroes2/gui/text.h
> +    TextBox() = delete;
It is removed.

2022-03-04 16:32 UTC, oleg-derevenetz commented on src/fheroes2/gui/ui_dialog.h
> +        ResourceDialogElement( const int32_t resourceType, std::string && text );
Regarding static analyzers, `clang-tidy` is not against this idiom and suggests it in its `modernize-pass-by-value` check:

https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html

But the current approach would work as well, but it's up to you :)

2022-03-05 09:32 UTC, ihhub commented on src/fheroes2/gui/ui_dialog.h
> +        ResourceDialogElement( const int32_t resourceType, std::string && text );
Tough decision :)

2022-03-06 05:43 UTC, merged

2022-03-06 05:44 UTC, ihhub commented
@oleg-derevenetz , I decided to keep the same style we have right now as I can still see some small potential issues with other developers not being used move operators :(