Add MP3 file support
ihhub/fheroes2 pull request #5109
Opened 2022-03-11 13:09 UTC by ihhub

Reworked the way how we read music files. Previous implementation was slow and incorrect. We were expecting ogg files to be present while searching flac files.

Expanded the support of file types to MP3 ( close #5063 ).

2022-03-11 13:10 UTC, ihhub commented
Hi @Kreeblah, please take a look at this pull request.

2022-03-11 16:50 UTC, Kreeblah commented
That's definitely an improved implementation and simplifies things quite a bit.  I do have a couple of thoughts on it, though they're more around organization than specific code.

First, since it's easier now to add a new format or re-order the existing formats, it might be worth changing the search order to FLAC, then Ogg, then MP3.  My thinking in this is that if somebody's gone through the trouble of creating FLAC files, they're likely to be making a deliberate choice about the audio quality vs. space tradeoff, so it would make sense to give them the highest-quality audio available.  Then, for the lossy formats, if somebody has both, Ogg has a bit-for-bit quality advantage over MP3.  Obviously, this assumes that both the Ogg and MP3 files were encoded at the same bitrates, but barring testing each file and making a determination based on the encoding characteristics (which seems like way too much effort here), having Ogg take precedence over MP3 seems like a good rule of thumb.

Second, with the methods here no longer making an assumption that the music is encoded in Ogg format, and requiring a file extension to be passed in, it might make sense to also rename the `OGG_MUSIC_TYPE` enum to something that doesn't imply an inherent Ogg format.

2022-03-11 19:42 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few suggestions here, please take a look when you have a free time.

2022-03-11 19:42 UTC, oleg-derevenetz commented on src/fheroes2/agg/agg.cpp
> +
I suppose we should either remove this empty line or add an empty line between L99 and L100 below :)

2022-03-11 19:42 UTC, oleg-derevenetz commented on src/fheroes2/agg/agg.cpp
> +        if ( filename.empty() ) {
I suppose we can just call the `Music::Play()` if filename is not empty and return. In this case we can remove the `isSongFound` completely.

2022-03-11 19:42 UTC, oleg-derevenetz commented on src/fheroes2/agg/agg.cpp
> +            DEBUG_LOG( DBG_ENGINE, DBG_TRACE, MUS::getFileName( mus, MUS::OGG_MUSIC_TYPE::MAPPED, ".ogg" ) )
While just not print the `filename` here? The resulting music file is not necessary an OGG file, it might as well be MP3 or FLAC.

2022-03-11 19:42 UTC, oleg-derevenetz commented on src/engine/audio.cpp
> +            DEBUG_LOG( DBG_ENGINE, DBG_TRACE,
I'd use the `DBG_WARN` here instead of the `DBG_TRACE`, because it's serious inconsistency.

2022-03-12 01:34 UTC, ihhub commented
Hi @Kreeblah and @oleg-derevenetz , I addressed all given comments. Please take a look again.

2022-03-12 08:34 UTC, Kreeblah commented
@ihhub - That looks good to me!  :^)

2022-03-12 11:13 UTC, oleg-derevenetz approved these changes

2022-03-12 12:29 UTC, merged