Fix translation and UI in Tavern dialog
ihhub/fheroes2 pull request #5113
Opened 2022-03-12 15:36 UTC by ihhub

- introduce new dynamic image UI element used for animations within a dialog
- introduce text UI element which can be used together with other UI elements
- fix incorrect translation of Tavern's rumors ( close #4795 )
- fix animation speed in Tavern's dialog

2022-03-12 17:48 UTC, catadropa commented on src/fheroes2/world/world.cpp
> +        return _( "An unknown force is being ressurected..." );
Misspelled: it's resurrected

2022-03-12 18:26 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few minor notes here, please take a look when possible.

2022-03-12 18:26 UTC, oleg-derevenetz commented on src/fheroes2/gui/ui_dialog.cpp
> +    DynamicImageDialogElement::DynamicImageDialogElement( const int icnId, const std::vector<uint32_t> & backgroundIndecies, const uint64_t delay )
I believe there is a typo here and in other similar places: `backgroundIndecies` -> `backgroundIndices` or `backgroundIndexes`?

2022-03-12 18:26 UTC, oleg-derevenetz commented on src/fheroes2/gui/ui_dialog.cpp
> +        assert( _delay > 0 );
We can join these assertions:

```cpp
assert( !_backgroundIndecies.empty() && _delay > 0 );
```

2022-03-13 05:23 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +        return _( "An unknown force is being ressurected..." );
Great catch!

2022-03-13 05:28 UTC, ihhub commented
Hi @oleg-derevenetz and @catadropa , I addressed your given comments. Please take a look again.

2022-03-13 07:22 UTC, oleg-derevenetz approved these changes

2022-03-13 09:59 UTC, merged