Build player influence map to inform AI kingdom development decisions
ihhub/fheroes2 pull request #5148
Opened 2022-03-20 19:11 UTC by idshibanov

Fixes #5046 .

AI players will upgrade magic guild more often when there's heroes with appropriate Wisdom skill and current map region is considered to be safe.

Also includes bug fixes related to region generation and AI map scan at the beginning of the turn

2022-03-20 19:18 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +        std::sort( regionsToCheck.begin(), regionsToCheck.end(), []( const auto & x, const auto & y ) { return x.second > y.second; } );
Yeah... It would be good to use C++17 features in this project (generic lambdas with `auto` parameters is the C++14 feature), but...

2022-03-21 07:46 UTC, ihhub requested changes
Hi @idshibanov , I left few comments here. Could you please check them?

2022-03-21 07:46 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_castle.cpp
> +        const RegionStats & stats = _regions[regionID];
We could move these 2 variables into else branch because it is the only place where they're in use.

2022-03-21 07:46 UTC, ihhub commented on src/fheroes2/world/world_regions.cpp
> +                otherList.insert( reg._id );
Since this is a set wouldn't it more efficient to just use `otherList.insert( reg._id );` without the check since set stores only unique values?

2022-03-22 07:18 UTC, merged

2022-03-22 07:18 UTC, ihhub commented
@idshibanov , thank you so much for these changes!