Fix army order option related crash
ihhub/fheroes2 pull request #5176
Opened 2022-03-28 14:24 UTC by ihhub

close #5167

2022-03-28 17:37 UTC, oleg-derevenetz commented
Hi @ihhub crash is not observed anymore, but there is problem with rendering:

<img width="641" alt="Screenshot" src="https://user-images.githubusercontent.com/32623900/160454822-1c7d6524-eb0c-40e3-8b7c-fc4d424958c6.png">

Cavalry unit in upper left corner is never grayed out, although he skipped the turn.

2022-03-30 14:51 UTC, ihhub commented
> Hi @ihhub crash is not observed anymore, but there is problem with rendering:
> 
> <img alt="Screenshot" width="641" src="https://user-images.githubusercontent.com/32623900/160454822-1c7d6524-eb0c-40e3-8b7c-fc4d424958c6.png">
> 
> Cavalry unit in upper left corner is never grayed out, although he skipped the turn.

Hi @oleg-derevenetz , I addressed it. Please take a look.

2022-03-30 17:58 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left one suggestion here, could you please take a look?

2022-03-30 17:58 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +        if ( unit == nullptr || !unit->isValid() ) {
If `unit` from `orders` is `nullptr` then something is definitely wrong - it is already assumed that it may not be `nullptr` when `validUnitCount` is initialized. I suggest to add an assertion regarding this either on `validUnitCount` initialization or both here and on `validUnitCount` initialization, and remove this condition, because it's too late to check it here anyway.

2022-03-30 18:09 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        if ( unit == nullptr || !unit->isValid() ) {
Hi @oleg-derevenetz , I've added in both places.

2022-03-30 18:24 UTC, oleg-derevenetz approved these changes

2022-03-30 18:25 UTC, merged

2022-04-17 12:43 UTC, LeHerosInconnu commented
Hello @ihhub,

> Hi @LeHerosInconnu, I partially addressed your suggestion for #5166 here.

I tried it, works fine. :)