Changed AI's turn to be repeated multiple times
ihhub/fheroes2 pull request #5202
Opened 2022-04-04 01:26 UTC by felix642

Improved AI's logic. At the end of every turn we check if new heroes have been recruited. If so we redo every steps to possibly reach new locations / recruit new heroes / Collect resources / etc.

Relates to #2498 and #3720

2022-04-04 01:56 UTC, ihhub commented
Hi @felix642 , please fix code styling issues in order to make the pipeline to succeed.

2022-04-04 20:10 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +            purchasedHeroesCount = 0;
Hi @felix642 this value is never used because it will be always overwritten at line 361 (the Clang Analyzer also complains about this). I suggest to remove this line completely, because it's useless. Or you may even turn this loop into the infinite loop, remove the declaration at line 243 and do something like this:

```cpp
while ( true ) {
[...]
  uint8_t purchasedHeroesCount = purchaseNewHeroes(...);
[...]
  if ( purchasedHeroesCount == 0 ) {
    break;
  }
}
```

2022-04-04 21:11 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +            purchasedHeroesCount = 0;
I would prefer infinite loop as well.

2022-04-04 21:20 UTC, idshibanov requested changes
This will probably be merged after the upcoming release as we'll need some time to test this change out. I'm not convinced we should repeat all turn calculations every time, this might slow down AI turns considerably.

Test on L and XL maps as hero counts will be higher there. I doubt there will be any impact on Small though.

2022-04-04 21:20 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +                return true;
Change `purchaseNewHeroes` method definition so it returns a boolean instead of uint8_t.

Also `++availableHeroCount;` does nothing in this case, you can remove it.

2022-04-04 21:20 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +        const bool moreTasksForHeroes = HeroesTurn( heroes );
`const bool moreTasksForHeroes = HeroesTurn( heroes );`
This line executes all hero moves and definitely shouldn't be in this method.

Change method definition to pass in `const bool moreTasksForHeroes` instead of `VecHeroes & heroes` and move it back into turn loop.

2022-04-06 14:10 UTC, felix642 commented
Hi @idshibanov,
I definitely agree with you, we must test this change thoroughly before merging this branch. We don't want to break anything. I did test a bit the new logic to see how it goes and it seems to be working pretty well for now but I haven't made enough tests to make sure that everything is working perfectly.

> I'm not convinced we should repeat all turn calculations every time, this might slow down AI turns considerably.

I have updated to scan the visible map only once instead of doing this multiple times. It should improve the AI's performances but I still need to test before pushing those changes.

2022-04-11 03:28 UTC, idshibanov approved these changes

2022-04-11 04:44 UTC, ihhub requested changes
Hi @felix642 , I left few comments here. Would you mind to take a look?

2022-04-11 04:44 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal.h
> +        bool purchaseNewHeroes( const std::vector<AICastle> & sortedCastleList, const std::set<int> & castlesInDanger, int32_t availableHeroCount,
This method should be at least `private` as no other external code calls it.

2022-04-11 04:44 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +        std::set<int> castlesInDanger;
Please move these variables to the place just before the loop where they are used. It would be easier to read the code.

2022-04-11 04:44 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +            status.RedrawTurnProgress( 6 );
Won't we have a moving backwards progress sand hourglasses? At least it would just from 7 to 6 again.

2022-04-11 04:44 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +            status.RedrawTurnProgress( 6 );
Since we don't have a call of `RedrawTurnProgress( 8 );` I suggest to do this way:
```cpp
// before the loop
uint32_t progressStatus = 6;

// inside the loop
if ( progressStatus == 6 ) {
    status.RedrawTurnProgress( 6 );
    ++progressStatus;
}
else {
    status.RedrawTurnProgress( 8 );
}

...
if ( progressStatus == 7 ) {
    status.RedrawTurnProgress( 7 );
}
else {
    status.RedrawTurnProgress( 8 );
}
```
What do you think?

2022-04-11 04:44 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
>          if ( availableHeroCount < heroLimit ) {
Please use fast return logic:
```cpp
if ( availableHeroCount >= heroLimit ) {
    return false;
}
...
// the rest of the code.
```

This makes the code more readable.

2022-04-25 20:17 UTC, felix642 commented
Hi @ihhub, sorry for the delay. I have resolved the comments on this PR.

2022-04-29 12:56 UTC, ihhub approved these changes

2022-04-29 12:56 UTC, merged

2022-04-29 12:56 UTC, ihhub commented
@felix642 , thank you so much for the improvement!