Generate French Battle Only button
ihhub/fheroes2 pull request #5219
Opened 2022-04-08 13:51 UTC by zenseii

2022-04-08 14:48 UTC, zenseii commented
Hi @ihhub ! The button fonts are clean and I tried to be as greedy as possible with the generation of it, but if you see need for further optimization and ways to optimize it then I'm all ears. Also this font has 4 "layers" (I wish it had just 2 like German") which means I had to use some tricks like multiplication for the 'T' to get it clean and properly generated.

Also there is some slight dithering in the deepest/brightest layer for the 'Mode' part and for the 'AI' part. Unless there's a magic trick to uniform these colors I don't really see any need to put effort into fixing that.

2022-04-08 16:57 UTC, ihhub requested changes
Hi @zenseii , I put few comments here. Would you mind to take a look at them?

2022-04-08 16:57 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    Copy( uniform, 0, 0, out, 25, 18, uniform.width(), uniform.height() );
We can use something like this:
```cpp
const uint8_t fillColor = ( i == 0 ) ? GetColorId( 216, 184, 152 ) : GetColorId( 184, 136, 96 );
Fill( out, 25, 18, 88, 23, fillColor );
```
At the time of initial button creation (it was actually changing the old image generation code) Fill function didn't exist.

This solution is much faster and easier to read. Could you please also do this for German and English?

2022-04-08 16:57 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +        }
Please add an empty line to separate 2 functions.

2022-04-08 16:57 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    // add 'LLE'
To be consistent: please make **a** as a capital letter.

2022-04-08 17:08 UTC, zenseii commented on src/fheroes2/agg/agg_image.cpp
> +                    Copy( uniform, 0, 0, out, 25, 18, uniform.width(), uniform.height() );
Sure, I was actually wondering why Fill() was not used.

2022-04-09 02:30 UTC, ihhub approved these changes

2022-04-09 02:30 UTC, merged

2022-04-09 02:30 UTC, ihhub commented
@zenseii , a lot of thanks for working on translations!