This commit was made in order to fix one function requirement from is…
ihhub/fheroes2 pull request #5295
Opened 2022-04-17 18:43 UTC by srmoll

This commit was written for issue #4804. It replaces the call to Game::GetStep4Player(...) with an inlined change that uses integer ceiling arithmetic to replace Game::GetStep4Player(...). The functional requirement was to ensure that the colored squares representing players would be evenly spaced was met.

2022-04-17 21:59 UTC, srmoll commented
@oleg-derevenetz I wanted to figure out the other functional requirements for issue #4804.  ie: "Your Funds" and "Planned Gift" are not centered horizontally in relation to the edges of the window frame. I looked at the code, and I'm unsure on where in the code this discrepancy comes from, but I was thinking would it be from adding 25 (px) to the width in the ResourceBar for each?

2022-04-17 22:06 UTC, zenseii commented
> @oleg-derevenetz I wanted to figure out the other functional requirements for issue #4804. ie: "Your Funds" and "Planned Gift" are not centered horizontally in relation to the edges of the window frame. I looked at the code, and I'm unsure on where in the code this discrepancy comes from, but I was thinking would it be from adding 25 (px) to the width in the ResourceBar for each?

Hi @srmoll ! You are right about this assumption. Here is what happens if you set it to + 0 instead of 25
![image](https://user-images.githubusercontent.com/12501091/163733910-896ec4f6-7410-4cba-aa59-59274825ad32.png)

2022-04-18 09:40 UTC, zenseii commented on src/fheroes2/dialog/dialog_giftresources.cpp
> +        int32_t playerCtnrWidth = 2 * sprite.width() + ( colorCount - 1 ) * 22; // original spacing = 22
How about dividing by 2 on both sides of the plus symbol so that we don't have to divide by 2 in the line below?

Also, what does Ctnr stand for? Maybe we could just write it out? I'm not sure it's intuitive.

2022-04-18 13:39 UTC, srmoll commented on src/fheroes2/dialog/dialog_giftresources.cpp
> +        int32_t playerCtnrWidth = 2 * sprite.width() + ( colorCount - 1 ) * 22; // original spacing = 22
The two is a typo, I put that there to test out how it would look with 2 players. It should say colorCount. Ctnr = Container, and yes, writing it out is more intuitive

2022-04-21 13:13 UTC, ihhub submitted a review, later dismissed
Hi @srmoll , I left multiple comments here. Could you please take a look at them?

2022-04-21 13:13 UTC, ihhub commented on src/fheroes2/dialog/dialog_giftresources.cpp
> +        const fheroes2::Rect box( frameborder.activeArea() );
If the intention was to get the future position of the dialog then please do this way:
```cpp
const fheroes2::Display & display = fheroes2::Display::instance();
const fheroes2::Rect box( ( display.width() - 320 ) / 2, ( display.height() - 234 ) / 2, 320, 234 );
```

and since we use 320 and 234 in another place I recommend to create a separate variable in anonymous namespace after header inclusions:
```cpp
namespace
{
    const fheroes2::Size giftDialogSize( 320, 234 );
}
```

2022-04-21 13:13 UTC, ihhub commented on src/fheroes2/dialog/dialog_giftresources.cpp
> +            int32_t posx = startx + i * ( 22 + sprite.width() );
This variable can be `const`.

2022-04-21 13:13 UTC, ihhub commented on src/fheroes2/dialog/dialog_giftresources.cpp
>          fheroes2::Blit( sprite, fheroes2::Display::instance(), posx, posy );
Please use `display` here instead of **fheroes2::Display::instance()**.

2022-04-21 13:13 UTC, ihhub commented on src/fheroes2/dialog/dialog_giftresources.cpp
> +    int32_t posx = box.x + 160 - ( sprite.width() + 240 ) / 2; // 160 = half width of brown box, fixed
Please name this variable using `camelCase` and also make it `const`.

2022-04-21 13:13 UTC, ihhub commented on src/fheroes2/dialog/dialog_giftresources.cpp
> +    int32_t posx = box.x + 160 - ( sprite.width() + 240 ) / 2; // 160 = half width of brown box, fixed
I think 160 could be used as `giftDialogSize.width / 2` to avoid hardcoded values. Then we won't need this comment.

2022-04-21 13:13 UTC, ihhub commented on src/fheroes2/dialog/dialog_giftresources.cpp
>  #include "text.h"
I think we can remove this file inclusion since we replaced all instances of the old class.

2022-04-21 20:16 UTC, srmoll commented
text.h cannot yet be deleted due to the uses of Font::BIG, which I am not sure how to replace, would fheroes2::FontType::largeWhite() work?

2022-04-21 21:21 UTC, zenseii commented
> text.h cannot yet be deleted due to the uses of Font::BIG, which I am not sure how to replace, would fheroes2::FontType::largeWhite() work?

Hi @srmoll ! I do not believe that function does not exist and infact most of the places where text.h hasn't been removed is because of these instances of text.h's fontsize call.

2022-04-22 14:05 UTC, oleg-derevenetz requested changes
Hi @srmoll Good job! I have only one additional suggestion regarding getting rid of another anonymous literal. Could you please take a look when you have some free time?

2022-04-22 15:38 UTC, srmoll commented on src/fheroes2/dialog/dialog_giftresources.cpp
> +        const int32_t playerContainerWidth = colorCount * sprite.width() + ( colorCount - 1 ) * 22; // original spacing = 22
Thank you for the feedback, just pushed that change

2022-04-22 16:24 UTC, merged

2022-04-22 16:25 UTC, oleg-derevenetz commented
@srmoll Thank you very much and welcome to the project contributors!

2022-04-22 16:46 UTC, srmoll commented
> @srmoll Thank you very much and welcome to the project contributors!

Thank you @oleg-derevenetz and thank you also to @ihhub and @zenseii for all of their support!