Update Polish translation
ihhub/fheroes2 pull request #5366
Opened 2022-05-03 17:59 UTC by michkry

2022-05-05 22:58 UTC, Arthusppp requested changes

2022-05-05 22:58 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Pokazuje rezultat akcji wykonanych przez indiwidualną jednostkę."
"indywidualną" zamiast "indiwidialną"

2022-05-05 22:58 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Obrona Corlagonu"
To jest Lord Corlagon, więc powiedziałbym, że "Obrona Corlagona".

2022-05-05 22:58 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Zabić Krasnoludy"
Czy to jest nazwa czwartego scenariusza? OG tutaj używa "Zniszcz Krasnoludy". I w sumie trochę lepiej pasuje, ponieważ w misji nie trzeba zabić konkretnych czy wszystkich kransoludów tylko zdobyć wszystkie wrogie zamki. Do rozważenia.

2022-05-05 22:58 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Kolczata tarcza"
Potwierdź pls, że w kampanii tak się ten artefakt nazywa. W singlu mam jednak "Rogata tarcza":
![image](https://user-images.githubusercontent.com/85434237/167036505-17913dd8-bd5b-4ad2-9653-6a4448e91482.png)
![image](https://user-images.githubusercontent.com/85434237/167036585-a98c1bdb-b0ff-4e91-b576-563f10ec954f.png)

2022-05-05 22:58 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Podstawowe łucznictwo"
Pytanie: czy odpalałeś to w grze? Znaczy: kiedyś był problem z długimi nazwami i była akcja, aby skracać. Więc: jeśli w grze wygląda ok, to ok. Ale jeśli nie, to trzeba będzie wszystkie długie skracać.

2022-05-05 22:58 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Grupowa Klątwa"
Konwencja nazewnictwa do przegadania. Znaczy: kupuję, że "Klątwa" jest też samodzielnym czarem. Ale z drugiej strony, jeśli piszemy dużymi, to pewnie wszędzie powinniśmy też, np. "Łańcuch Piorunów", "Lustrzane Odbicie", "Ożywienie Martwych", "Zabójca Smoków", "Pokaż Artefakty", "Promień Osłabienia"... 

Kurcze - ja bym chyba jednak szedł w "pierwsza duża reszta mała". Czyli: "Grupowa tarcza", "Grupowe leczenie", "Grupowa klątwa".

2022-05-05 22:58 UTC, Arthusppp commented on files/lang/pl.po
> +"zapisujących grę."
W zasadzie to nie uwaga do tłumaczenia, ale pewnie do mechanizmu. Jak ja mogę się upewnić, że używam najnowszego typu pliku? Przecież albo mam albo nie mam. Pewnie nie skonwertuję sobie. Bo jak się mogę upewnić?? (ja nie wiem, pytam :))

Czyli raczej komunikat powinien iść w stronę: "Ten zapis gry nie jest obsługiwany przez aktualną wersję gry."

2022-05-07 22:38 UTC, michkry commented on files/lang/pl.po
> +msgstr "Pokazuje rezultat akcji wykonanych przez indiwidualną jednostkę."
Corrected

2022-05-07 22:38 UTC, michkry commented on files/lang/pl.po
> +msgstr "Obrona Corlagonu"
Corrected

2022-05-07 22:42 UTC, michkry commented on files/lang/pl.po
> +msgstr "Kolczata tarcza"
Changing to "Rogata tarcza" since it is the name of the artifact in OG

2022-05-07 22:44 UTC, michkry commented on files/lang/pl.po
> +"zapisujących grę."
Changin the translation to "Ten zapis gry nie jest obsługiwany przez aktualną wersję gry.". But in the future we will have to debate on the original message in english because as you say it's misleading.

2022-05-07 22:52 UTC, michkry commented on files/lang/pl.po
> +msgstr "Podstawowe łucznictwo"
Changed all campaignBonus secondary skills to have no more than 19 characters (it's the maximum number of characters that fit well in the bonus box). I also saw that there is a problem with names of skills in the hero view screen. There are only 3 strings to express the level of skills of the hero: skill|Basic, skill|Advanced and skill|Expert. In Polish the ending of nouns changes depending on the context. So in the future we will have to debate on how to tackle this.

![image](https://user-images.githubusercontent.com/11597098/167274360-c801698c-8daa-435a-a64b-99af02b22dfe.png)

2022-05-07 22:53 UTC, michkry commented on files/lang/pl.po
> +msgstr "Grupowa Klątwa"
Corrected

2022-05-07 22:54 UTC, michkry commented on files/lang/pl.po
> +msgstr "Zabić Krasnoludy"
Corrected

2022-05-08 22:32 UTC, Arthusppp approved these changes

2022-05-10 14:03 UTC, merged

2022-05-10 14:05 UTC, Arthusppp commented
Actually, here kudos are for @michkry!