Make AI aware about map conditions
ihhub/fheroes2 pull request #5381
Opened 2022-05-06 15:34 UTC by ihhub

Map conditions must affect the behavior of AI.

2022-05-07 08:37 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few notes regarding this PR, could you please take a look when it is convenient for you?

2022-05-07 08:37 UTC, oleg-derevenetz commented on src/fheroes2/world/world_loadmap.cpp
> +    // Make AI aware of a special castle to be defended in order not to loose it.
AFAIK there can not be a map with `LOSS_TOWN` and town in question belonging to a AI-controlled player - I just tried to make such a map, and in OG you will lose at the end of the first turn (and in fheroes2 you will lose immediately). Also this condition is not respected for multiplayer maps (both in OG and in feroes2) - it is just ignored and everything looks like the `LOSS_ALL` condition is in effect. However, may be the `CAPITAL` flag is used as a suggestion for the AI to capture this particular human-controlled castle ASAP?

2022-05-08 09:27 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few notes, please take a look when possible.

2022-05-08 09:27 UTC, oleg-derevenetz commented on src/fheroes2/world/world_loadmap.cpp
> +    // Make AI aware of a special castle which is a winning condition for a human player.
Please note that this castle may be a winning condition for AI too - usually if this is a neutral castle and "Comp also wins" map setting is in effect. In this case, the AI and the human player(s) should try to capture it in a race. BTW with this setting, if this castle is already belong to an AI player, AI immediately wins.

2022-05-08 09:27 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +    bool isCastleLossConditionForHuman( const Castle * castle )
Please note that this castle will be a loss condition in a single-player only. In a multiplayer, it's just an ordinary castle. In the `GameOver::Result::LocalCheckGameOver()`, single-player mode is detected in the following way:

```cpp
const bool isSinglePlayer = ( Colors( Players::HumanColors() ).size() == 1 );
```

You might want to add the corresponding check here, otherwise in a multi-player mode AI will try to capture this castle like a maniac, despite the fact that it will not give him any advantage.

2022-05-19 15:09 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +        if ( ( conf.ConditionLoss() & ( GameOver::LOSS_TOWN | GameOver::LOSS_ENEMY_WINS_TOWN ) ) == 0 ) {
Hi @ihhub please note that `LOSS_ENEMY_WINS_*` values are used only as return values from the `World::CheckKingdomLoss()` to let the logic inside the `GameOver::Result::LocalCheckGameOver()` know why exactly did this particular kingdom lose. They do not participate in the map win/loss conditions (stored by the `Maps:FileInfo`) by themselves.

2022-05-19 15:10 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +        if ( ( conf.ConditionLoss() & ( GameOver::LOSS_TOWN | GameOver::LOSS_ENEMY_WINS_TOWN ) ) == 0 ) {
Yeah, I understand this. That's why I converted to WIP state as many things are in mess...

2022-05-19 18:24 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few notes, please take a look when you have time.

2022-05-19 18:24 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            // This is a multiplayer mode. Town related conditions are not applied for such game.
This is not quite true. `WINS_TOWN` condition is applied in the multiplayer mode just fine (all players, possibly including AI players - depending on the "Comp also wins via Special VC" setting, should capture the town in question in a race).

`LOSS_TOWN` condition, however, does not seem to apply. OG in the single-player mode:

https://user-images.githubusercontent.com/32623900/169367172-9eca5fd7-dd79-47f6-8277-9b6c16226b20.mp4

OG in the multiplayer mode on the same map:

https://user-images.githubusercontent.com/32623900/169367691-c9791b55-9181-4db4-8b00-4ce288e0f216.mp4

The castle in question is considered as a regular castle, loss of this castle by the starting player is not considered as the loss of the game. Currently in fheroes2 `LOSS_TOWN` is not applied in multiplayer mode as well.

2022-05-20 01:56 UTC, ihhub commented on src/fheroes2/world/world_loadmap.cpp
> +
Nope. We don't.

2022-05-20 12:45 UTC, oleg-derevenetz reviewed
Hi @ihhub LGTM, just one (optional) suggestion regarding the abundance of parentheses :)

2022-05-20 12:45 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +        if ( isSinglePlayer && ( ( conf.ConditionLoss() & GameOver::LOSS_TOWN ) != 0 ) && ( castle->GetCenter() == conf.LossMapsPositionObject() ) ) {
It looks like there are too many parentheses here :) Wouldn't it be better this way:

```cpp
if ( isSinglePlayer && ( conf.ConditionLoss() & GameOver::LOSS_TOWN ) != 0 && castle->GetCenter() == conf.LossMapsPositionObject() ) {
```

?

2022-05-20 12:45 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +        if ( ( conf.WinsCompAlsoWins() && ( conf.ConditionWins() & GameOver::WINS_TOWN ) != 0 ) && ( castle->GetCenter() == conf.WinsMapsPositionObject() ) ) {
```cpp
if ( conf.WinsCompAlsoWins() && ( conf.ConditionWins() & GameOver::WINS_TOWN ) != 0 && castle->GetCenter() == conf.WinsMapsPositionObject() ) {
```

?

2022-05-20 12:56 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +        if ( isSinglePlayer && ( ( conf.ConditionLoss() & GameOver::LOSS_TOWN ) != 0 ) && ( castle->GetCenter() == conf.LossMapsPositionObject() ) ) {
I've removed them.

2022-05-20 13:27 UTC, merged