Implement Spanish language
ihhub/fheroes2 pull request #5389
Opened 2022-05-07 23:27 UTC by zenseii

This  adds a Spanish langauge option to the game. The existing Spanish PO has a substantial amount of translated strings.

Spanish uses CP1252 so I added the fonts in a new function `generateCP1252Alphabet()`.

Tidied up so that German, Norwegian and Italian all use CP1252 too.

Some small font generation improvements to CP1252 fonts like lowercase `ì`.

`Ññ` has not been implemented yet and are just replaced with `Nn`.

All normal font special characters are currently just replaced with their nearest latin alphabet counterpart.

![image](https://user-images.githubusercontent.com/12501091/167275151-3766c6d7-b4b9-4f2d-9fa1-f40cde2ef3f0.png)

2022-05-09 10:46 UTC, zenseii commented
Hi @ihhub ! This PR is ready for you review when you should have the time.

All characters necessary for Spanish have been added.

I suggest to move the French characters in a separate PR as it will require some more attention to preserve OG encoding compatibility.

2022-05-13 14:03 UTC, ihhub requested changes
Hi @zenseii , I left one optimization suggestion here. Would you mind check it in your free time?

2022-05-14 04:34 UTC, ihhub reviewed
Hi @zenseii ,  I left very tiny suggestions about comments. Could you please check again?

2022-05-14 04:34 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +                // TODO: add proper Flip function variant.
This comment is not needed since it works fine with full images.

2022-05-14 04:34 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +                // TODO: add proper Flip function variant.
This comment is not needed since it works fine with full images.

2022-05-14 04:34 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +                // TODO: add proper Flip function variant.
This comment is not needed since it works fine with full images.

2022-05-14 04:34 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +                // TODO: add proper Flip function variant.
This comment is not needed since it works fine with full images.

2022-05-14 11:19 UTC, ihhub approved these changes

2022-05-14 11:20 UTC, merged

2022-05-14 11:20 UTC, ihhub commented
@zenseii , thank you so much for these font related changes!