Improved Artifact's Evaluation
ihhub/fheroes2 pull request #5396
Opened 2022-05-10 02:13 UTC by felix642

closes #4226.

Improved the getArtifactValue() function based on what @LeHerosInconnu in #4226.

Artifacts value is based on multiple factors :
+1 per skill level
+1 per spell tier

The other effects add +1 to the value based on the weakest artifact.

For example, Gold Income gives +1 per 1000 gold/day

2022-05-10 02:16 UTC, felix642 commented on src/fheroes2/resource/artifact.cpp
> +        case fheroes2::ArtifactBonusType::VIEW_MONSTER_INFORMATION:
Not a fan of this case, but I feel like the issue is related to the enum and not my function. 

I feel like *_IMMUNITY should be similar to ADD_SPELL and only have 1 enum (SPELL_IMMUNITY) with the corresponding spell.
The same logic should apply for *_EXTRA_EFFECTIVENESS_PERCENT AND *_DAMAGE_REDUCTION

2022-05-19 10:03 UTC, ihhub requested changes
Hi @felix642 , I left 2 comments in this pull request. Would you mind to check them in your free time?

2022-05-19 10:03 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +    artifactValue += std::accumulate( bonuses.begin(), bonuses.end(), 0, []( int sum, const fheroes2::ArtifactBonus & bonus ) {
Shouldn't a normal switch-case code be sufficient? For example,
```cpp
int artifactValue = 0;
for ( const fheroes2::ArtifactBonus & bonus : bonuses ) {
    switch ( bonus ) {
    case fheroes2::ArtifactBonusType::ADD_SPELL:
        artifactValue += Spell( bonus.value ).Level();
        break;
    case fheroes2::ArtifactBonusType::GOLD_INCOME:
        artifactValue -= bonus.value / 1000;
        break;
    ...
    default:
        // Did you add a new artifact bonus type? Add the logic above!
        assert( 0 );
        break;
    }
}
```
This code will be also faster as no lambda-function would be called. Also we must handle unknown bonuses and not to add any value for them. What do you think?

2022-05-22 14:55 UTC, felix642 commented on src/fheroes2/resource/artifact.cpp
> -    // TODO: this method should return a value of the artifact based on its bonuses and curses.
Here's the list of artifacts with their corresponding values.

| Artifact's id | Value |
|--|--|
| 0 | 12 |
| 1 | 12 |
| 2 | 12 |
| 3 | 12 |
| 4 | 12 |
| 5 | 12 |
| 6 | 16 |
| 7 | 10 |
| 8 | 4 |
| 9 | 2 |
| 10 | 2 |
| 11 | 3 |
| 12 | 1 |
| 13 | 1 |
| 14 | 1 |
| 15 | 1 |
| 16 | -2 |
| 17 | 1 |
| 18 | 1 |
| 19 | 1 |
| 20 | 1 |
| 21 | 1 |
| 22 | 2 |
| 23 | 3 |
| 24 | 2 |
| 25 | 3 |
| 26 | 2 |
| 27 | 3 |
| 28 | 4 |
| 29 | 5 |
| 30 | 1 |
| 31 | 0 |
| 32 | 0 |
| 33 | 2 |
| 34 | 1 |
| 35 | 1 |
| 36 | 1 |
| 37 | 1 |
| 38 | 1 |
| 39 | 2 |
| 40 | 2 |
| 41 | 1 |
| 42 | 1 |
| 43 | 2 |
| 44 | 1 |
| 45 | 1 |
| 46 | 1 |
| 47 | 1 |
| 48 | 1 |
| 49 | 1 |
| 50 | 1 |
| 51 | 1 |
| 52 | 2 |
| 53 | 2 |
| 54 | 1 |
| 55 | 1 |
| 56 | 1 |
| 57 | 1 |
| 58 | 1 |
| 59 | 1 |
| 60 | 1 |
| 61 | 1 |
| 62 | 1 |
| 63 | 1 |
| 64 | 1 |
| 65 | 1 |
| 66 | 5 |
| 67 | 2 |
| 68 | 1 |
| 69 | -1 |
| 70 | -1 |
| 71 | 1 |
| 72 | 1 |
| 73 | 1 |
| 74 | 1 |
| 75 | 1 |
| 76 | 1 |
| 77 | 2 |
| 78 | 4 |
| 79 | 2 |
| 80 | 4 |
| 81 | 0 |
| 82 | 0 |
| 83 | 0 |
| 84 | 0 |
| 85 | 0 |
| 86 | 0 |
| 87 | 2 |
| 88 | 5 |
| 89 | -1 |
| 90 | 26 |
| 91 | 1 |
| 92 | 0 |
| 93 | 0 |
| 94 | 5 |
| 95 | 5 |
| 96 | 8 |
| 97 | 2 |
| 98 | 3 |
| 99 | 5 |
| 100 | 5 |
| 101 | 5 |
| 102 | 1 |
| 103 | 0 |

2022-05-23 14:21 UTC, ihhub requested changes
Hi @felix642 , I left few comments here. Would you mind to take a look?

2022-05-23 14:21 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> -    // TODO: this method should return a value of the artifact based on its bonuses and curses.
The original range of values was [0;5] while we have [-2;26]. This will definitely change AI behavior in general. Also `ENDLESS_BAG_GOLD` and `ENDLESS_PURSE_GOLD` have values of 0 which shouldn't be the case. We need to switch from **int** to **double** as a first step so that some artifacts will have more than 0 values. Then update `BagArtifacts::getArtifactValue()` method to return **double** as well.

2022-05-23 14:21 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +            artifactValue += bonus.value;
Here we shouldn't do anything but to add an assertion to handle unknown bonuses.

2022-05-23 14:21 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +            artifactValue -= curse.value;
Here we shouldn't do anything but to add an assertion to handle unknown curses.

2022-05-23 14:21 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +    const std::vector<fheroes2::ArtifactCurse> & curses = fheroes2::getArtifactData( id ).curses;
It is better to cache a return value of `getArtifactData` function to make the code faster.

```cpp
const fheroes2::ArtifactData & data = fheroes2::getArtifactData( id );
const std::vector<fheroes2::ArtifactBonus> & bonuses = data.bonuses;
const std::vector<fheroes2::ArtifactCurse> & curses = data.curses;
```

2022-05-23 15:13 UTC, felix642 commented
> The original range of values was [0;5] while we have [-2;26]. This will definitely change AI behavior in general. Also ENDLESS_BAG_GOLD and ENDLESS_PURSE_GOLD have values of 0 which shouldn't be the case. We need to switch from int to double as a first step so that some artifacts will have more than 0 values. Then update BagArtifacts::getArtifactValue() method to return double as well.

@ihhub, do you think  we should normalize the values between something like [-5, 5] ?

2022-05-24 14:17 UTC, ihhub commented
> > The original range of values was [0;5] while we have [-2;26]. This will definitely change AI behavior in general. Also ENDLESS_BAG_GOLD and ENDLESS_PURSE_GOLD have values of 0 which shouldn't be the case. We need to switch from int to double as a first step so that some artifacts will have more than 0 values. Then update BagArtifacts::getArtifactValue() method to return double as well.
> 
> @ihhub, do you think we should normalize the values between something like [-5, 5] ?

No we shouldn't. The negative effect of artifacts is not that big as a positive. Let's do step by step. We will reach the ideal state eventually :)

2022-05-24 14:34 UTC, ihhub requested changes
Hi @felix642 , I left few suggestions. Could you please update the table of artifact values after this so other members evaluate these numbers and we can adjust them properly?

2022-05-24 14:34 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +            artifactValue += Spell( bonus.value ).Level();
Spell Scroll has value of 0 so this will not work. I suggest to just assign 1 to the value as a rough estimation. Also it would be more accurate because while picking scrolls on map AI shouldn't know their real value.

2022-05-24 14:34 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +            artifactValue += static_cast<double>( bonus.value ) / 1000.0;
I would say that division by 800 would be more accurate to bring Golden Goose to the same value as the rest of Ultimate Artifacts. Also Gold is a very valuable resource in the game. For 250 gold you can hire a decent monster which is better than +1 to a primary skill.

2022-05-24 14:34 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +            artifactValue += static_cast<double>( bonus.value ) / 300.0;
200 would be even better. Land mobility is much more valuable than sea mobility. Nomad Boots is a very powerful artifact.

2022-05-24 14:34 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +            artifactValue -= static_cast<double>( curse.value ) / 250.0;
200 as for the same ability.

2022-05-28 04:12 UTC, idshibanov commented on src/fheroes2/resource/artifact.cpp
> +            artifactValue += static_cast<double>( bonus.value ) / 1000.0;
Also take into account that Endless Sack of Gold (+1000 gold) is a major tier 3 artifact (in map editor) and should be comparable to at least other +3's.

2022-05-28 04:16 UTC, idshibanov commented
> > > The original range of values was [0;5] while we have [-2;26]. This will definitely change AI behavior in general. Also ENDLESS_BAG_GOLD and ENDLESS_PURSE_GOLD have values of 0 which shouldn't be the case. We need to switch from int to double as a first step so that some artifacts will have more than 0 values. Then update BagArtifacts::getArtifactValue() method to return double as well.
> > 
> > 
> > @ihhub, do you think we should normalize the values between something like [-5, 5] ?
> 
> No we shouldn't. The negative effect of artifacts is not that big as a positive. Let's do step by step. We will reach the ideal state eventually :)

Don't worry about normalizing ultimate artifacts since they are never placed on the map. I think AI should be ok even without additional changes.

2022-06-12 04:39 UTC, ihhub requested changes

2022-06-12 04:39 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +    for ( const fheroes2::ArtifactBonus & bonus : bonuses ) {
Some artifact bonuses are not covered here like `KNOWLEDGE_SKILL` or `ATTACK_SKILL`. Please add them and run
```cpp
for ( int i = 0; i < Artifact::UNKNOWN; ++i ) {
    ERROR_LOG( Artifact( i ).GetName() << " - " << Artifact( i ).getArtifactValue() )
}
```
somewhere in the code to verify the results.

2022-08-07 19:24 UTC, felix642 commented
Hi @ihhub, sorry for the delay I forgot I had an open PR..

I added the required logic for the missing artifacts.

2022-08-08 12:30 UTC, ihhub commented
Hi @felix642 , could you please update your branch from master branch as we made a lot of changes and on Visual Studio it's impossible to test without rerunning all scripts?

2022-08-31 14:24 UTC, ihhub approved these changes

2022-08-31 14:43 UTC, merged

2022-08-31 14:43 UTC, ihhub commented
@felix642 , thank you so much for this improvement!