Extend CMakeLists.txt with icon, desktop-file and appdata.xml
ihhub/fheroes2 pull request #5405
Opened 2022-05-11 22:13 UTC by Laserlicht

Required for flatpak packaging.

2022-05-11 22:14 UTC, Laserlicht commented
See here: https://github.com/flathub/flathub/pull/3114#pullrequestreview-965446869

2022-05-12 07:11 UTC, oleg-derevenetz commented on CMakeLists.txt
> +			)
I'm not sure if we need to always install all these files. Why do this if the installation has nothing to do with Flatpak?

2022-05-12 08:12 UTC, Laserlicht commented on CMakeLists.txt
> +			)
The files are used for freedesktop integration. To create a menu item in the start menu. This is part of a "clean installation" anyway (independent of flatpak), isn't it?

2022-05-13 22:00 UTC, zenseii commented on script/packaging/common/fheroes2.appdata.xml
> +    <p>Free Heroes of Might and Magic II (fheroes2) is a recreation of HoMM2 game engine.</p>
Hi @Laserlicht! The right name of the project is this.
```suggestion
  <summary>fheroes2 is a recreation of HoMM2 game engine.</summary>
  <description>
    <p>fheroes2 is a recreation of HoMM2 game engine.</p>
```

2022-05-19 00:54 UTC, ihhub requested changes
Hi @Laserlicht , I left few comments here. Could you please check them?

2022-05-19 00:54 UTC, ihhub commented on script/packaging/common/fheroes2.appdata.xml
> +      <image>https://raw.githubusercontent.com/ihhub/fheroes2/4ce7b1148b0c2ec4e5da67aeb79522942c7d6a95/docs/images/screenshots/screenshot_world_map.png</image>
Please use direct links here: `https://github.com/ihhub/fheroes2/blob/master/docs/images/screenshots/screenshot_world_map.png?raw=true` as we will update these images in the future.

2022-05-19 00:54 UTC, ihhub commented on CMakeLists.txt
> +			)
I have the same question: it looks like we are installing these files for Windows as well.

2022-05-19 01:32 UTC, Laserlicht commented on script/packaging/common/fheroes2.appdata.xml
> +    <p>fheroes2 is a recreation of HoMM2 game engine.</p>
done :)

2022-05-19 01:34 UTC, Laserlicht commented on CMakeLists.txt
> +			)
It should only installed on Linux (it's in the else path):
https://github.com/ihhub/fheroes2/blob/78e489b51216d663f8c73f1ba4e3b155b5fe5716/CMakeLists.txt#L187
Otherwise shellscripts would also be installed under windows.

2022-05-19 06:34 UTC, ihhub commented on CMakeLists.txt
> +			)
Hmmm... could you please then make the correct indentation for lines 201-215?

2022-05-19 09:54 UTC, ihhub commented on CMakeLists.txt
> +			)
Never mind. It's something wrong with editor on GitHub.

2022-05-19 12:08 UTC, oleg-derevenetz approved these changes

2022-05-19 12:09 UTC, merged

2022-05-19 12:09 UTC, ihhub commented
@Laserlicht , thank you very much for this change!