ukrainian translation (skills)
ihhub/fheroes2 pull request #5436
Opened 2022-05-21 05:22 UTC by burrbull

2022-05-22 15:33 UTC, felix642 commented
Hi @burrbull, I see that you added a bunch of #, fuzzy above the translations. This usually means that the translation are not ready yet. Did you mean to do that ?

2022-05-22 15:36 UTC, felix642 requested changes

2022-05-22 15:36 UTC, felix642 commented on files/lang/uk.po
> +msgstr "содиниці руху героя по воді на %{count} відсотків."
In the msgid there is a %{skill}, but it's not there in the msgstr. Is there a reason ?

2022-05-22 15:57 UTC, burrbull commented
> Hi @burrbull, I see that you added a bunch of #, fuzzy above the translations. This usually means that the translation are not ready yet. Did you mean to do that ?

I just following @kant2002  recommendation:
https://github.com/ihhub/fheroes2/pull/5406#issuecomment-1131432398

2022-05-22 16:03 UTC, burrbull commented on files/lang/uk.po
> +msgstr "содиниці руху героя по воді на %{count} відсотків."
No reason. Just typo. Fixed

2022-05-22 16:21 UTC, felix642 commented on files/lang/uk.po
> +msgstr "содиниці руху героя по воді на %{count} відсотків."
Ok that's perfect :) Just wanted to make sure that was not a mistake.

2022-05-22 16:21 UTC, felix642 approved these changes

2022-05-22 16:22 UTC, felix642 commented
> > Hi @burrbull, I see that you added a bunch of #, fuzzy above the translations. This usually means that the translation are not ready yet. Did you mean to do that ?
> 
> I just following @kant2002 recommendation: [#5406 (comment)](https://github.com/ihhub/fheroes2/pull/5406#issuecomment-1131432398)

Ok that's perfect :) Just wanted to make sure that was not a mistake.

2022-06-01 15:39 UTC, burrbull commented
yes, please

2022-06-01 22:15 UTC, felix642 approved these changes

2022-06-02 15:50 UTC, merged

2022-06-02 15:50 UTC, ihhub commented
@burrbull , thank you very much for contribution to the project!