Migrate to C++17
ihhub/fheroes2 pull request #5472
Opened 2022-05-28 12:50 UTC by oleg-derevenetz

With all the benefits.

I have converted the VS2015 project files to VS2017 in case someone wants to build the game for WinXP.

2022-05-28 13:13 UTC, ihhub commented
I would suggest to move this pull request for the next release and merge it after the current one.

2022-05-28 13:22 UTC, oleg-derevenetz commented
Hi @ihhub

> I would suggest to move this pull request for the next release and merge it after the current one.

No problem, I'll move it to 0.9.17.

2022-06-04 05:46 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left few comments here. Could you please take a look? Also for files where we changed to `std::clamp` we might need to remove `tool.h` file inclusion.

2022-06-04 05:46 UTC, ihhub commented on fheroes2-vs2017.vcxproj
> -﻿<?xml version="1.0" encoding="utf-8"?>
Hi @oleg-derevenetz , this is interesting why the whole file is marked as changed but you modified only few line.

2022-06-04 05:46 UTC, ihhub commented on src/fheroes2/kingdom/luck.cpp
>  #include "tools.h"
We can remove this header as it was used for `clamp` function.

2022-06-04 05:46 UTC, ihhub commented on src/fheroes2/kingdom/morale.cpp
>  #include "tools.h"
We can remove this header as it was used for `clamp` function.

2022-06-04 09:10 UTC, oleg-derevenetz commented on fheroes2-vs2017.vcxproj
> -﻿<?xml version="1.0" encoding="utf-8"?>
@ihhub That's because the previous version always included the `\r` character at the end of lines, even on Linux - `git` was unable to properly recode it for some reason. Now this should work properly - `\r\n` on Windows and `\n` on Linux.

2022-06-04 10:37 UTC, ihhub commented on fheroes2-vs2017.vcxproj
> -﻿<?xml version="1.0" encoding="utf-8"?>
Oh, it was actually created by Visual Studio itself.

2022-06-04 10:38 UTC, ihhub commented
Hi @oleg-derevenetz , could you please resolve merge conflict here? I think it is because I added few files into the project.

2022-06-04 10:40 UTC, oleg-derevenetz commented on fheroes2-vs2017.vcxproj
> -﻿<?xml version="1.0" encoding="utf-8"?>
@ihhub I have no idea why `git` was unable to properly recode it - maybe it thinks that this was binary file. Nevertheless, this is just an XML and can be recoded just fine.

2022-06-04 12:55 UTC, ihhub approved these changes

2022-06-04 12:57 UTC, ihhub commented on src/fheroes2/system/save_format_version.h
> +    FORMAT_VERSION_0917_RELEASE = 10000,
Mmm... since we decided to push it for 0.9.16 should we rename `FORMAT_VERSION_0916_RELEASE` into FORMAT_VERSION_PRE_0916_RELEASE` and then add `FORMAT_VERSION_0916_RELEASE`?

2022-06-04 12:58 UTC, oleg-derevenetz commented on src/fheroes2/system/save_format_version.h
> +    FORMAT_VERSION_0917_RELEASE = 10000,
@ihhub Well yes, we can do this way then.

2022-06-04 12:58 UTC, ihhub commented on src/fheroes2/system/save_format_version.h
> +    FORMAT_VERSION_0917_RELEASE = 10000,
Thank you!

2022-06-04 13:17 UTC, oleg-derevenetz commented on fheroes2-vs2017.vcxproj
> -﻿<?xml version="1.0" encoding="utf-8"?>
@ihhub probably `git` was unable to recode this file because these `vcxproj` files have Unicode BOM at start (however it's a bit strange because BOM by itself is not a reason to consider the file as binary and not recode between CRLF and LF AFAIK). I just added the BOM to the VS2017 project file just in case.

2022-06-05 03:09 UTC, merged

2022-06-05 03:09 UTC, ihhub commented
@oleg-derevenetz , well done! I hope we don't break anything :)

2022-06-05 05:54 UTC, oleg-derevenetz commented
Hi @ihhub

> I hope we don't break anything :)

It shouldn't be, but of course a ton of code smells have been added :) Mostly about `[[nodiscard]]` and code modernization - usage of structured bindings, init-statements, etc. Sorry about that :)

2022-06-05 05:55 UTC, ihhub commented
Nooooo... hehe🙂

2022-06-05 08:46 UTC, ihhub commented
@oleg-derevenetz , I deactivated both checks in SonarQube. For now they are polluting the results.