WIP: add 3D audio effects for Adventure Map objects
ihhub/fheroes2 pull request #5473
Opened 2022-05-28 14:47 UTC by ihhub

2022-05-29 08:24 UTC, oleg-derevenetz commented on src/fheroes2/agg/agg.cpp
> +        }
Hi @ihhub I am aware that this PR is currently WIP, but I still put my two cents :) `std::map::erase()` should return the valid iterator, pointing to the element following the last removed element, so you can just assign its return value to the `iter`, something like this:

```cpp
if ( effects.empty() ) {
  iter = soundEffects.erase( iter );
}
else {
  ++iter;
}
```

2022-05-29 14:59 UTC, ihhub commented on src/fheroes2/agg/agg.cpp
> +        }
Good point. I forgot about this. Thank you!

2022-05-29 15:50 UTC, oleg-derevenetz commented on src/fheroes2/agg/agg.cpp
> +    const bool is3DAudioEnabled = Settings::Get().is3DAudioEnabled();
Hi @ihhub just one more remark: please don't call the `Settings`-related methods from the auxiliary threads, because there may be the race condition if the same setting will be updated from the main thread via the game UI (if not now then in the future). It is better to get this value in advance and then pass it as the function's argument, like it happens with the `soundVolume` arg.

2022-05-29 20:01 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few suggestions, please take a look when possible. Also I left the separate notice earlier regarding usage of `Settings` in the background thread.

2022-05-30 01:31 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +        GLOBAL_3D_AUDIO = 0x00010000,
Actually, no. By default we still keep normal volume based approach like in the original game. We need thoughtfully test 3D audio mode before enabling it by default.

2022-05-30 04:25 UTC, ihhub commented
Hi @oleg-derevenetz , as usual once I touched one thing I had to change a lot of stuff in other places. I added more TODO comments for the future work as I found many places for improvements.

2022-05-30 10:15 UTC, oleg-derevenetz reviewed
Hi @ihhub I just left a few questions and minor optional suggestions, please take a look when you have time.

2022-05-30 10:15 UTC, oleg-derevenetz commented on src/fheroes2/agg/agg.cpp
> +    assert( mus != MUS::UNUSED );
Shouldn't we check for the `MUS::UNKNOWN` as well?

2022-05-30 10:26 UTC, ihhub commented on src/engine/audio.cpp
> +        //       "Any previous music will be halted, or if it is fading out it will wait (blocking) for the fade to complete." we do not need to even call this function.
I tested with and without stop (you can use fheroes2::Time for measurements). After loading a map Stop() call usually takes 0.1 second while music play is 0.25. When I remove Stop call the music play call remains the same.

We do not have fading out music effect but we can branch it out if needed for the case of fading out.

2022-05-30 10:26 UTC, ihhub commented on src/engine/audio.cpp
>          // You are trying to play an empty file. Check your logic!
It's a good catch.

2022-05-30 10:28 UTC, ihhub commented on src/engine/audio.cpp
> +int Mixer::setVolume( const int channel, const int volumePercentage )
To possibly support something else except SLD Mixer we can add `getVolume` function for such purposes.

2022-05-30 10:55 UTC, oleg-derevenetz commented on src/engine/audio.cpp
> +int Mixer::setVolume( const int channel, const int volumePercentage )
@ihhub Well, since there's no need for that right now, we can wait with that.

2022-05-31 00:39 UTC, merged