Update Polish translation: added polish descriptions of all campaign …
ihhub/fheroes2 pull request #5487
Opened 2022-05-31 19:41 UTC by michkry

…chapters

2022-06-04 05:04 UTC, Arthusppp requested changes
Hello @michkry, I have left few comments. Can you review them? And apply them, if necessary.

2022-06-04 05:04 UTC, Arthusppp commented on files/lang/pl.po
> +"cię odkryje i zaatakuje szybko wzmocnij swoją armię! Zajmij region i pokonaj "
"Zanim cię odkryje i zaatakuje, szybko wzmocnij swoją armię" (tu chyba powinien być przecinek)

2022-06-04 05:04 UTC, Arthusppp commented on files/lang/pl.po
> +"Piratów. Nie wolno ci stracić Gallavanta, algo twoja przygoda się skończy."
"albo" (zamiast "algo")

2022-06-05 18:17 UTC, michkry commented on files/lang/pl.po
> +"Czarodziejowie zajęli zamek nekromantów. Musisz go odbić, aby zwyciężyć. "
Zmieniam na Czarodzieje

2022-06-05 18:18 UTC, michkry commented on files/lang/pl.po
> +"zwyciężyć, zdobądź wszystkie zamki i miasta wroga i nie pozwól na utratę "
Z "oraz" tekst brzmi lepiej. Zmieniam "i" na "oraz"

2022-06-05 18:20 UTC, michkry commented on files/lang/pl.po
> +"zamek Scabsdale, albo nekromanci będą dla ciebie zbyt silni."
Faktycznie forma ktora proponujesz bardziej tu pasuje.

2022-06-05 18:20 UTC, michkry commented on files/lang/pl.po
> +"Piratów. Nie wolno ci stracić Gallavanta, algo twoja przygoda się skończy."
Zmieniam "algo" na "albo".

2022-06-05 18:22 UTC, michkry commented on files/lang/pl.po
> +"cię odkryje i zaatakuje szybko wzmocnij swoją armię! Zajmij region i pokonaj "
Tez sie nad tym zastanawialem. Jesli oboje mamy ta sama watpliwosc to najprawdopodobniej powinien tam byc przecinek. Dodaje przecinek po "zaatakuje".

2022-06-05 20:16 UTC, Arthusppp approved these changes

2022-06-05 20:17 UTC, Arthusppp commented
@michkry many thanks!

@ihhub this is ready for your review.

2022-06-07 15:47 UTC, merged

2022-06-07 15:47 UTC, ihhub commented
@michkry , thanks a lot for improving Polish translation!