ukrainian translation, part 3
ihhub/fheroes2 pull request #5497
Opened 2022-06-03 06:53 UTC by burrbull

2022-06-03 08:08 UTC, shprotru requested changes

2022-06-03 08:08 UTC, shprotru commented on files/lang/uk.po
>  msgstr ""
```suggestion
msgstr "Гноми визнають своїх союзників і з радістю приєднуються до Вас."
```

2022-06-03 08:08 UTC, shprotru commented on files/lang/uk.po
> +msgstr "Гноможер"
Точно Гноможер? Я не знаю такого слова. В російському перекладі це в одному місці просто `Гном` та в інших місцях `вбивця гномів`.

2022-06-03 08:08 UTC, shprotru commented on files/lang/uk.po
> +msgstr "Подорож додому"
```suggestion
msgstr "Подорож Додому"
```

2022-06-03 08:29 UTC, burrbull commented on files/lang/uk.po
> -msgid "The %{attacker} cast %{spell} on %{target}!"
Мабуть випадково

2022-06-03 08:36 UTC, burrbull commented on files/lang/uk.po
> +msgstr "Гноможер"
Звісно в словнику немає такого слова. Але як одним словом назвати гном'ячого маніяка?
Чи може я не зрозумів контекст і це якесь прокляття?

2022-06-03 08:38 UTC, burrbull commented on files/lang/uk.po
> +msgstr "%{spell} завдає %{damage} шкоди одній немертвій істоті."
Нежить це коли соплі з носа :)

2022-06-03 08:43 UTC, shprotru commented on files/lang/uk.po
> +msgstr "Гноможер"
В Російській може будет таке веселе слово як `Гномосек`, спроба перекласти на Українську - `Гномокат`, гра слів від `гном` та `кат`. Можна ще так: `Гноморуб`. Ще мені до вподоби використання двох слів `Винищувач Гномів`, `Вбивця Гномів`.

2022-06-03 08:45 UTC, shprotru commented on files/lang/uk.po
> +msgstr "%{spell} завдає %{damage} шкоди одній немертвій істоті."
Так, але я десь в дитинстві натикався на мультики що переклали `нежить` в контексті `undead`

2022-06-03 08:46 UTC, shprotru commented on files/lang/uk.po
>  msgstr ""
Звісно, `ворожого` краще!

2022-06-03 08:51 UTC, burrbull commented on files/lang/uk.po
> +msgstr "Гноможер"
`Гномокат` схоже на самокат. Тоді вже `Гномів Кат`
`Гноморуб` краще, але більше підходить для назви сокири

Поки видалю це з перекладу.

2022-06-03 09:04 UTC, burrbull commented on files/lang/uk.po
> +msgstr "%{spell} завдає %{damage} шкоди одній немертвій істоті."
Звісно натикався, бо русизм
https://uk.wikipedia.org/wiki/%D0%9D%D0%B5%D0%BC%D0%B5%D1%80%D1%82%D0%B2%D1%96

2022-06-03 10:49 UTC, shprotru commented on files/lang/uk.po
> +msgstr "%{spell} завдає %{damage} шкоди одній немертвій істоті."
Що до мене, то я не вважаю `нежить` запозиченням з Російської, як про це мовить наведене посиляння до вікіпедії. Є такий фразеологізм [Ні живий ні мертвий](https://dovidka.biz.ua/ni-zhiviy-ni-mertviy-znachennya-frazeologizmu), то до мене не зрозуміло, чому ми повинні обмежувати себе в використанні слова `нежить`, бо в мене воно асоциюється як раз с наведеним фразеологізмом.

2022-06-26 14:53 UTC, ihhub commented
Hi @burrbull , would you mind to address given comments in this pull request?

2022-06-27 06:26 UTC, burrbull commented
Done

2022-06-28 00:16 UTC, merged

2022-06-28 00:16 UTC, ihhub commented
@burrbull , huge thanks for improving this translation!