Improve loop sound playback logic
ihhub/fheroes2 pull request #5504
Opened 2022-06-05 02:44 UTC by ihhub

The original approach is based on using last in an array elements. This leads to some "jumping" sounds during hero's walk. Such effect exists due to a fact that we were trying to replace angles and volumes by absolutely different values.

For example, we have existing sounds:
```
sound A, angle 0, volume 20
```

Then we want to play these sounds:
```
sound A, angle 0, volume 20
sound A, angle 80, volume 70
```
In this case **sound A, angle 0, volume 20** would be replaced by **sound A, angle 80, volume 70** which is absolutely incorrect.

The proposed approach contains logic to first detect sounds which are exact copies of existing played sounds and keep existing sounds without touching them. Then, find angles which are closest to each other and update the existing sound so the listener would hear a smallest change in sound effects.

This correction requires further testing but so far results are much better than before, especially for 3D audio.

2022-06-05 11:44 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few suggestions, please take a look when you have time.

2022-06-05 11:44 UTC, oleg-derevenetz commented on src/fheroes2/audio/audio_manager.cpp
> +                    if ( bestAngleDiff == angleDiff && volumeDiff > bestVolumeDiff ) {
Hmm, if we are already here, then `bestAngleDiff` is already greater than `angleDiff`, so expression `bestAngleDiff == angleDiff` is always false.

2022-06-05 11:44 UTC, oleg-derevenetz commented on src/fheroes2/audio/audio_manager.cpp
> +        // Sort all sounds by angle. This will help with search methods below.
Do you mean it will help with `std::find()` when you are searching for an existing sound? Maybe, if `std::find()` has some heuristics about sorted data, but maybe not. Maybe it worth to think about replacing the `std::vector` by a more suitable container? How about the `std::multimap`? It has `find` to find an exact match and `lower_bound`/`upper_bound` that may be used to find the "close enough" match.

2022-06-05 11:44 UTC, oleg-derevenetz commented on src/fheroes2/audio/audio_manager.cpp
> +    void getClosestSoundIdPairByAngle( const std::vector<AudioManager::AudioLoopEffectInfo> & soundToAdd, const std::vector<ChannelAudioLoopEffectInfo> & soundToReplace,
How about returning the `std::pair<size_t, size_t>` here, since `bestSoundToAddId` and `bestSoundToReplaceId` are rewritten anyway in any case?

2022-06-05 13:15 UTC, ihhub commented on src/fheroes2/audio/audio_manager.cpp
> +                    if ( bestAngleDiff == angleDiff && volumeDiff > bestVolumeDiff ) {
Oh, yes. It supposed to be `>=`

2022-06-05 13:16 UTC, ihhub commented on src/fheroes2/audio/audio_manager.cpp
> +        // Sort all sounds by angle. This will help with search methods below.
There are 2 options:
- do this in the current pull request to increase the amount of changes
- remove this sorting for now

I would suggest to remove and add a TODO comment for a possible optimization. What do you think?

2022-06-05 13:17 UTC, ihhub commented on src/fheroes2/audio/audio_manager.cpp
> +    void getClosestSoundIdPairByAngle( const std::vector<AudioManager::AudioLoopEffectInfo> & soundToAdd, const std::vector<ChannelAudioLoopEffectInfo> & soundToReplace,
Reading `std::pair` as a return value is not clear what these variables are.

2022-06-05 13:22 UTC, oleg-derevenetz commented on src/fheroes2/audio/audio_manager.cpp
> +        // Sort all sounds by angle. This will help with search methods below.
Yeah, I suppose leaving the `TODO` comment would be enough for now.

2022-06-05 13:39 UTC, zenseii commented on src/fheroes2/audio/audio_manager.cpp
> +                    if ( bestAngleDiff == angleDiff && volumeDiff > bestVolumeDiff ) {
Wouldn't `>=` always be true anyways here due to already having checked that in the previous if condition.

2022-06-05 13:47 UTC, zenseii reviewed
Hi @ihhub! I've read through the code and found some typos, and I tested the changes and they do indeed improve alot when moving along a coastline.

2022-06-05 13:47 UTC, zenseii commented on src/fheroes2/audio/audio_manager.cpp
> +                // Find the most closest angles to those which are going to be added.
Just a small correction.
```suggestion
                // Find the closest angles to those which are going to be added.
```

2022-06-05 13:47 UTC, zenseii commented on src/fheroes2/audio/audio_manager.cpp
> +        // TODO: use another containers for sound effects to support more efficient sort and find operations based on the code below.
Either the suggested change or `use other containers`.
```suggestion
        // TODO: use another container for sound effects to support more efficient sort and find operations based on the code below.
```

2022-06-05 13:58 UTC, ihhub commented on src/fheroes2/audio/audio_manager.cpp
> +                    if ( bestAngleDiff == angleDiff && volumeDiff > bestVolumeDiff ) {
Nope, `angleDiff` can be bigger than `bestAngleDiff`.

2022-06-05 14:10 UTC, zenseii commented on src/fheroes2/audio/audio_manager.cpp
> +                    if ( bestAngleDiff == angleDiff && volumeDiff > bestVolumeDiff ) {
I see! I thought the change was about the nested if statement 👍

2022-06-05 16:56 UTC, oleg-derevenetz requested changes
Hi @ihhub I found another suspicious place, please take a look to ensure that everything is by design.

2022-06-05 16:56 UTC, oleg-derevenetz commented on src/fheroes2/audio/audio_manager.cpp
> +                    bestAngleDiff = angleDiff;
I see the place where `bestAngleDiff` is updated, but I do not see a place where `bestVolumeDiff` is updated, it always remains `100`.

2022-06-05 16:58 UTC, ihhub commented on src/fheroes2/audio/audio_manager.cpp
> +                    bestAngleDiff = angleDiff;
Yes! This is a bug. I didn't notice this since all values were unique per angle.

2022-06-05 17:01 UTC, ihhub commented on src/fheroes2/audio/audio_manager.cpp
> +                    bestAngleDiff = angleDiff;
and I also should stop coding while almost sleeping...

2022-06-06 04:32 UTC, ihhub commented
Hi @oleg-derevenetz , the logic is correct according to design.

2022-06-06 09:37 UTC, oleg-derevenetz approved these changes

2022-06-06 09:54 UTC, merged

2022-06-06 09:54 UTC, ihhub commented
@oleg-derevenetz , thanks a lot for finding bugs in my code :)