WIP: add music resume ability
ihhub/fheroes2 pull request #5505
Opened 2022-06-05 13:00 UTC by ihhub

2022-06-05 13:11 UTC, ihhub commented
Hi @oleg-derevenetz , can we please disable `[[nodiscard]]` check for clang-tidy for now?

2022-06-05 13:23 UTC, oleg-derevenetz commented
Hi @ihhub

> can we please disable `[[nodiscard]]` check for clang-tidy for now?

Yes, I believe so.

2022-06-05 19:14 UTC, oleg-derevenetz reviewed
Hi @ihhub I just left a few comments, please take a look when you have time.

2022-06-05 19:14 UTC, oleg-derevenetz commented on src/engine/thread.cpp
> +            manager->doStuff();
All this behavior with calling the `unlock()` in the separate function looks error-prone of course. Maybe separate the `doStuff()` in two distinct functions and call the first of them in a separate block with `std::lock_guard` (BTW this can be done in lines 66-68 as well) or at least add the TODO comment to think about this later?

2022-06-05 19:19 UTC, oleg-derevenetz commented
> now we are keeping all music tracks in memory, do we need to do this?

If we have enough memory, then why not.

> should all songs in the game be resumed while played?

No. For example, `MUS::BATTLEWIN`, `MUS::BATTLELOSE`, music during battle, `MUS::PUZZLE`, objects music (such as `MUS::TREEHOUSE`, `MUS::EXPERIENCE`, etc, etc) should be played from scratch every time.

> should we use cached music tracks before even checking their presence in a storage?

Why not. If user removed the file from storage while the music is cached, then it's the user's problem.

2022-06-06 04:25 UTC, ihhub commented on src/engine/audio.cpp
> +                _musicCache.try_emplace( musicUID, MusicInfo{ mix, position } );
The compiler is unhappy about this so I added `MusicInfo`

2022-06-06 04:25 UTC, ihhub commented on src/engine/thread.cpp
> +            manager->doStuff();
I fixed it.

2022-06-06 11:09 UTC, ihhub commented
Hi @Branikolog , could you please help to test this pull request?

2022-06-06 11:21 UTC, oleg-derevenetz commented on src/fheroes2/audio/audio_manager.h
> +    void PlayMusic( const int trackId, const bool loop, bool rewindToStart = false );
Hi @ihhub how about making the `rewindToStart = true` for non-async variant (that is used primarily for dialog/object sounds) and `rewindToStart = false` for the async variant (`PlayMusicAsync`), since it is used for background music? Currently a lot of sounds that should always start from the beginning are not covered - for example, here:

https://github.com/ihhub/fheroes2/blob/7f21ff123dbd547d1348326ad83fb5610776de7e/src/fheroes2/battle/battle_dialogs.cpp#L419-L434

and here:

https://github.com/ihhub/fheroes2/blob/7f21ff123dbd547d1348326ad83fb5610776de7e/src/fheroes2/heroes/heroes_action.cpp#L259

and here:

https://github.com/ihhub/fheroes2/blob/7f21ff123dbd547d1348326ad83fb5610776de7e/src/fheroes2/heroes/heroes_action.cpp#L959

etc, etc. Or maybe somehow link this up to the `loop`, because I don't know a single case when non-looped music should be resumed (but I know the reverse examples - for example, the music in battle).

2022-06-06 11:23 UTC, ihhub commented on src/fheroes2/audio/audio_manager.h
> +    void PlayMusic( const int trackId, const bool loop, bool rewindToStart = false );
Hi @oleg-derevenetz , all music track which are not looped **always** start from the beginning.

2022-06-06 11:27 UTC, ihhub commented on src/fheroes2/audio/audio_manager.h
> +    void PlayMusic( const int trackId, const bool loop, bool rewindToStart = false );
Two ways we can do:
- add a comment explaining the cases
- add an enumeration instead of these 2 variables

To be safe it's good to go with enumeration. What do you think?

2022-06-06 11:28 UTC, oleg-derevenetz commented on src/fheroes2/audio/audio_manager.h
> +    void PlayMusic( const int trackId, const bool loop, bool rewindToStart = false );
@ihhub I think that enum is obviously better, because this reduces the number of arguments and outlines "incompatible" variations.

2022-06-06 12:38 UTC, ihhub commented on src/fheroes2/audio/audio_manager.h
> +    void PlayMusic( const int trackId, const bool loop, bool rewindToStart = false );
It is done.

2022-06-06 12:41 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_dialogs.cpp
> +        AudioManager::PlayMusic( MUS::BATTLELOSE, AudioManager::MusicPlaybackMode::REWIND_AND_PLAY_INFINITE );
Hi @ihhub We need to use `PLAY_ONCE` here and in other places above, because first `false` meant `loop = false` (unless you deliberately want to change it).

2022-06-06 12:41 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +        AudioManager::PlayMusic( MUS::BATTLELOSE, AudioManager::MusicPlaybackMode::REWIND_AND_PLAY_INFINITE );
Oh, nice catch!

2022-06-06 12:55 UTC, oleg-derevenetz commented on src/engine/audio.h
> +    bool Play( const uint64_t musicUID, const bool loop, const bool rewindToStart );
@ihhub I propose to use the same approach with `enum` here as well, because `loop = false` is incompatible with `rewindToStart = false`.

2022-06-06 12:56 UTC, ihhub commented on src/engine/audio.h
> +    bool Play( const uint64_t musicUID, const bool loop, const bool rewindToStart );
Eh... Sure, I will move the enumeration here.

2022-06-06 13:55 UTC, zenseii commented on src/engine/audio.cpp
> +            assert( mix != nullptr );
Hi @ihhub!
I just built from the latest commit and whenever I try to load up a scenario or exit the game this assertion fails:
`Assertion failed: mix != nullptr, file D:\Documents\GitHub\fheroes2-zenseii\src\engine\audio.cpp, line 186`

I have the sound files in flac and they're named `homm2_01.flac` up to 42.

2022-06-06 13:57 UTC, ihhub commented on src/engine/audio.cpp
> +            assert( mix != nullptr );
Hi @zenseii , can you please attach a call stack to see where it is called? We have few places where this method can be called.

2022-06-06 14:49 UTC, ihhub commented
Somehow the code doesn't work for SDL 2...

2022-06-06 17:30 UTC, zenseii approved these changes

2022-06-06 20:06 UTC, oleg-derevenetz requested changes
Hi @ihhub I expressed my concerns regarding possible issues with music looping implementation. I'll try to think regarding possible solutions...

2022-06-06 20:06 UTC, oleg-derevenetz commented on src/engine/audio.cpp
> +        musicSettings.currentTrackUID = musicUID;
Suppose that currently played track is ended and thread that should run the `replayCurrentMusic()` is currently waiting/sleeping at line 247. Suppose that `currentTrackUID` is now, say, 5, as well as `asyncTrackUID`. While that thread is sleeping, this function is called by the main thread or by another auxiliary thread to switch to track with id, say, 10. It sets the `asyncTrackUID` to 10 at line 315 of this function, then starts the playback of track 10, then sets the `currentTrackUID` to 10 here and finishes. And then, say, after 5 seconds (because why not) that thread with `replayCurrentMusic()` is woken up and continued execution. It will call this function again and will rewind the track 10 to the start, and will not able to detect that track has been already changed.

Need to think how to better implement the looping to avoid situations like this...

2022-06-07 00:03 UTC, oleg-derevenetz commented on src/engine/audio.cpp
> +        musicSettings.currentTrackUID = musicUID;
Hi @ihhub I just added the commit that should fix situations like this, please take a look when you have time. If you wish, you are free to revert it.

2022-06-07 09:08 UTC, oleg-derevenetz commented
What's interesting, `Mix_HookMusicFinished()` has its own mutex (what is not mentioned anywhere in the documentation), which is held at least while the handler is executing and which can cause a deadlock in the situation like this:

1. `Music::Stop()` is called, it acquires the `audioMutex`;
2. Hook handler is started by another thread, it waits on `audioMutex`;
3. `Music::Stop()` calls the `Mix_HookMusicFinished( nullptr )`, it tries to acquire its internal mutex, but it is not able to, because hook handler is currently waiting on the `audioMutex`;
4. Deadlock.

2022-06-07 10:07 UTC, oleg-derevenetz commented
BTW, we have the same issues currently with the `Mix_ChannelFinished()` hook: it can be executed from the background thread, it calls SDL_Mixer functions, and it now messing with `audioEffectLedger` without holding the `audioMutex`.

2022-06-07 14:06 UTC, oleg-derevenetz commented
Hi @ihhub it's probably good for your review.

2022-06-07 14:24 UTC, ihhub commented
> Hi @ihhub just one more thing (C) lieutenant Columbo: currently there is an issue with sound from streams (at first I thought that that's my fault, but this is observed on the `master` branch too). How to reproduce:
> 
>     1. Start any map with streams nearby, for example, "Broken Alliance";
> 
>     2. Ensure that stream sound is loud and clear (you may even set the hero right on the stream);
> 
>     3. Open Castle screen for any castle and then exit from it;
> 
>     4. Select the hero standing on stream. You will not be able to hear stream sound anymore - any sounds (sawmill, magic shrine, campfire) will remain just fine except that one. Even if you move the hero over stream, sound of the stream won't be back.

This is extremely weird but I think I know why.

2022-06-07 14:25 UTC, oleg-derevenetz commented on src/engine/audio.cpp
> +    Mix_ChannelFinished( freeChannel );
Since we don't hold a lock here, in theory if there is a some background thread trying to call, say, `Mixer::Play()` or `Music::Play()` during the `Audio::Init()` execution, there may be a sort of race and these callbacks may in theory not be called, if `Mixer::Play()` or `Music::Play()` will finish first and the audio track will be short enough. But in practice this is highly unlikely, because when `Audio::Init()` is called, there should not be such threads yet.

2022-06-07 15:08 UTC, ihhub commented on src/engine/audio.cpp
> +        }
In SDL2 this function will be called every time we stop current music playback. Then we create a new thread where we check whether the current track is okay to play. I feel it is some sort of overkill by doing this. I think we need to add at least these checks before creating a thread:
```cpp
// The current track managed to change during the start of this thread
if ( currentTrackChangeCounter != musicSettings.currentTrackChangeCounter ) {
    return;
}

// All other cases should be handled by the Mix_PlayMisic() itself
if ( musicSettings.currentTrackPlaybackMode != Music::PlaybackMode::CONTINUE_TO_PLAY_INFINITE ) {
    return;
}
```

@oleg-derevenetz , what do you think?

2022-06-07 15:14 UTC, ihhub commented on src/engine/audio.cpp
> +        }
I edited the first post.

2022-06-07 15:27 UTC, ihhub commented
Hi @oleg-derevenetz , besides this change I don't have any more remarks. I will hold it a bit and review again tomorrow morning to see if we missed something.

2022-06-07 15:54 UTC, ihhub commented
@oleg-derevenetz , I could say more that I didn't expect audio related changes to be so huge when I had started cleaning it up. Anyway, we are almost there to complete this chapter of code changes.

2022-06-07 15:57 UTC, ihhub commented on src/engine/audio.cpp
> +    Mix_ChannelFinished( freeChannel );
Yes, it is safe to so such in our codebase.

2022-06-07 20:17 UTC, oleg-derevenetz commented
BTW wile testing all this music stuff, I noticed another issue - sound effect volume is not changing "on the fly" anymore while increasing/decreasing its value in the adventure map's settings window. They actually changed only when I move the hero.

2022-06-08 10:56 UTC, ihhub commented
> BTW wile testing all this music stuff, I noticed another issue - sound effect volume is not changing "on the fly" anymore while increasing/decreasing its value in the adventure map's settings window. They actually changed only when I move the hero. I suppose this is somehow related to the new implementation of the `EnvironmentSoundMixer`.

I know why. I will fix it in a separate pull request.

2022-06-08 11:10 UTC, ihhub commented
Hi @oleg-derevenetz , I've checked the code and looks like it is good to go unless we missed something.

2022-06-08 11:12 UTC, oleg-derevenetz commented
Hi @ihhub

> unless we missed something.

Yeah, this is encouraging :)

2022-06-08 12:04 UTC, oleg-derevenetz approved these changes

2022-06-08 12:11 UTC, merged

2022-06-08 12:11 UTC, ihhub commented
@oleg-derevenetz , thank a lot for your help in this feature!

2022-06-08 12:14 UTC, oleg-derevenetz commented
@ihhub

> thank a lot for your help in this feature!

Hope we are not missed anything :)

2022-06-08 15:36 UTC, ihhub commented
> Hi @ihhub just one more thing (C) lieutenant Columbo: currently there is an issue with sound from streams (at first I thought that that's my fault, but this is observed on the `master` branch too). How to reproduce:
> 
>     1. Start any map with streams nearby, for example, "Broken Alliance";
> 
>     2. Ensure that stream sound is loud and clear (you may even set the hero right on the stream);
> 
>     3. Open Castle screen for any castle and then exit from it;
> 
>     4. Select the hero standing on stream. You will not be able to hear stream sound anymore - any sounds (sawmill, magic shrine, campfire) will remain just fine except that one. Even if you move the hero over stream, sound of the stream won't be back.

Hi @oleg-derevenetz , do you still observe this issue on the latest commit?

2022-06-08 15:39 UTC, oleg-derevenetz commented
@ihhub

>  do you still observe this issue on the latest commit?

Yes, just tested this on master branch. The same issue with streams (and only streams).

2022-06-08 15:53 UTC, ihhub commented
> @ihhub
> fheroes2.engine.version_.0.9.15.2022-06-08.18-41-58.mp4
> 
> Turn the sound on while watching.

This issue appears only on SDL 2.