Multiple fixes for the AsyncManager
ihhub/fheroes2 pull request #5527
Opened 2022-06-11 13:49 UTC by oleg-derevenetz

2022-06-11 14:32 UTC, oleg-derevenetz commented on src/engine/thread.h
> +        std::atomic<bool> _exitFlag{ false };
This flag should be atomic, because `_workerThread` doesn't hold any locks when checking it.

2022-06-11 14:32 UTC, oleg-derevenetz commented on src/engine/thread.h
> +        // The _mutex should be acquired while calling this method
This method changes `_runFlag` which should be protected by the `_mutex`.

2022-06-11 21:33 UTC, oleg-derevenetz commented on src/engine/thread.cpp
> +            _workerNotification.notify_all();
There is no need to hold a lock while calling any of the `notify*()` methods of `std::condition_variable` here and in other similar places.

2022-06-11 21:33 UTC, oleg-derevenetz commented on src/engine/thread.h
> +        std::atomic<bool> _exitFlag{ false };
This flag should be atomic, because `_workerThread` doesn't hold any locks when checking it.

2022-06-11 21:33 UTC, oleg-derevenetz commented on src/engine/thread.h
> +        void stopWorker();
We can't reliably join the worker thread in the destructor because this class has virtual methods that could be called by the worker thread. This leads to so-called [vptr race](https://github.com/google/sanitizers/wiki/ThreadSanitizerPopularDataRaces#data-race-on-vptr) (which I personally observed during testing today), so we need to do this in the separate method.

2022-06-11 21:33 UTC, oleg-derevenetz commented on src/engine/thread.h
> +        void notifyWorker();
This method modifies the `_runFlag` while not holding a lock by itself, so we need to acquire the `_mutex` beforehand.

2022-06-12 05:54 UTC, ihhub commented
Hi @oleg-derevenetz , is this pull request ready for review?

2022-06-12 05:56 UTC, oleg-derevenetz commented
> Hi @oleg-derevenetz , is this pull request ready for review?

Hi @ihhub yes, I believe so.

2022-06-12 06:29 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left one suggestion here. Would you mind to take a look at it?

2022-06-12 06:29 UTC, ihhub commented on src/engine/thread.h
> +        virtual ~AsyncManager() = default;
I recommend to at least assert that `_worker` is empty in the destructor.

2022-06-12 06:41 UTC, oleg-derevenetz commented on src/engine/thread.h
> +        virtual ~AsyncManager() = default;
@ihhub If joinable `std::thread` is still running while being destructed, `std::terminate()` will be called. There is no way for joinable thread to outlive this destructor.

2022-06-12 06:54 UTC, ihhub approved these changes

2022-06-12 06:55 UTC, merged

2022-06-12 06:55 UTC, ihhub commented
@oleg-derevenetz , thanks again for polishing this code!