AI should keep some creatures in reserve for castle defense
ihhub/fheroes2 pull request #5571
Opened 2022-06-25 04:29 UTC by idshibanov

Fixes #5304 .

2022-06-25 15:14 UTC, ihhub requested changes
Hi @idshibanov , I put 2 comments here. Could you please in your free time check them?

2022-06-25 15:14 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +                // 5% of total army for Figthers 10% otherwise
This comment does not correct the line below.

2022-06-25 15:14 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +        if ( castle.isCastle() && _regions[regionID].safetyFactor <= 100 && !garrison.isValid() ) {
Shouldn't it be `_regions[regionID].safetyFactor < 0`? For example I started "Great War II" map. All regions have safety factor >= 0 where no enemy heroes exist.

2022-06-25 15:39 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +        if ( castle.isCastle() && _regions[regionID].safetyFactor <= 100 && !garrison.isValid() ) {
Negative safety is when there's enemy heroes/castles in the region present. I actually thought of excluding those as well.

Safety 0 to 100 should be a neutral region that can have unexplored on dangerous regions nearby. If AI is too lazy to explore it they can leave some questionable empty castles. Only 100 to 200 (max) safety can be considered really safe (they have to be deep into friendly territory when having more than 1 castle).

2022-06-25 17:11 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +                // 5% of total army for Figthers 10% otherwise
This comment is justifying magic values for `significanceRatio`. If you think it's clear as is I can remove.

2022-06-26 04:25 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +        if ( castle.isCastle() && _regions[regionID].safetyFactor <= 100 && !garrison.isValid() ) {
What if we make percentage of the army based on safety factor? Firstly, it will prevent players to abuse AI behavior as it will be unknown how much army AI hero would leave. Secondly, it would make more stronger AI heroes in regions which have close to 100 safety factor. What do you think?

2022-06-26 06:53 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +        if ( castle.isCastle() && _regions[regionID].safetyFactor <= 100 && !garrison.isValid() ) {
As an alternative we can leave a TODO comment to the future adjustments.

2022-06-26 07:23 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +        if ( castle.isCastle() && _regions[regionID].safetyFactor <= 100 && !garrison.isValid() ) {
Yes, let's review it later after all changes will be merged and tested together.

2022-06-27 10:23 UTC, ihhub approved these changes

2022-06-27 13:34 UTC, oleg-derevenetz requested changes
Hi @idshibanov I just left one question, could you please take a look when you have time?

2022-06-27 13:34 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes.cpp
> +        Troop * troop = army.GetSlowestTroop();
Is there a reason to remove `const` here? Usually we can't remove the `const` qualifier safely, but we [always can add ](https://godbolt.org/z/59nnv4Yje)it.

2022-06-28 09:26 UTC, oleg-derevenetz approved these changes

2022-06-28 11:26 UTC, merged

2022-06-28 11:26 UTC, ihhub commented
@idshibanov , excellent work on AI!