Fix multiple audio issues
ihhub/fheroes2 pull request #5582
Opened 2022-06-28 19:39 UTC by oleg-derevenetz

fix #5580
fix #5581

Scenario of the #5581 is as follows:

* The music type is changed for the first time, the current music is set to `MUS::UNKNOWN`, `MusicRestorer` started the preparation for the background music playback in the worker thread, BUT actual music playback is not started yet.
* The music type is quickly changed for the second time, BUT, since the actual music playback is still not started, the current music is still the `MUS::UNKNOWN`, so `MusicRestorer` has nothing to restore.
* The previously planned music playback is actually started by the worker thread.

The proposed solution is to always start music playback in sync mode when changing the music type.

2022-06-28 20:13 UTC, oleg-derevenetz commented
BTW, this PR solves the #5581, but for some reason on Windows the external music sounds quieter after a quick switch (when I select the MIDI music and then quickly press twice on the music type icon to switch to the External music) than after a gradual switch (when I'm waiting for the actual launch of the MIDI Expansion music playback before switching to the External music). And it sounds quieter even if I then quit the game and completely restart it from scratch, and even if I then change the music volume in the game settings! WTF. Another one funny issue with MIDI on Windows? This issue is not observed on macOS.

2022-07-02 00:40 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left 2 comments in this pull request. Could you please take a look at them?

Regarding #5581 : we can use a combination of `Mix_FadingMusic` function and checking the type of music before stopping the current music track.

2022-07-02 09:04 UTC, oleg-derevenetz commented
Hi @ihhub

> Regarding https://github.com/ihhub/fheroes2/issues/5581 : we can use a combination of Mix_FadingMusic function and checking the type of music before stopping the current music track.

I have an impression that this might add an extra delay when stopping the music in cases when it might be undesirable, because, if we are using MIDI music on Windows, then we have that famous extra 200ms delay, the completion of which `Mix_FadingMusic()` will also wait for.

2022-07-03 23:55 UTC, ihhub approved these changes

2022-07-03 23:56 UTC, merged

2022-07-03 23:57 UTC, ihhub commented
@oleg-derevenetz , thank you so much for these changes!

I was thinking even further: what if we try to play MIDI as sounds? In this case we won't care about overall volume on Windows. This is of course just in theory and I'm not sure that this would work.

2022-07-04 09:11 UTC, oleg-derevenetz commented
Hi @ihhub

> what if we try to play MIDI as sounds?

As far as I understand, `Mix_Chunk` cannot be created from `MIDI`. It is created by `Mix_LoadWAV()`/`Mix_LoadWAV_RW()` and these functions are able to create the `Mix_Chunk` from (naturally) `WAV`, `AIFF`, `RIFF`, `OGG` and `VOC`, but not from `MIDI`.

2022-07-05 08:48 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz and @ihhub,

I thought of this to add the Wasteland and Beach/Ocean terrain type music, among other things, which do not exist in MIDI.
But why not save **all** MIDI music as audio files (.ogg or .wav) and when the player selects "MIDI" or "MIDI expansion" it is the audio file versions of the MIDI music that are used?

Unless the developers have fun solving problems by keeping the MIDI mode. :smile:

2022-07-05 09:11 UTC, ihhub commented
Hi @LeHerosInconnu , MIDI is not an ordinary audio file. It's a collection of instructions for instruments to be played opposed to recorder sounds in WAV or MP3 which are limited by frequencies.

2022-07-05 09:43 UTC, LeHerosInconnu commented
@ihhub.

> Hi @LeHerosInconnu , MIDI is not an ordinary audio file. It's a collection of instructions for instruments to be played opposed to recorder sounds in WAV or MP3 which are limited by frequencies.

Yes, I know how MIDI files work. :)
At first my idea was to play the music in MIDI format and record it while it is being played to be transformed into an audio file format, but this can be done by using a MIDI to OGG converter.

Isn't WAV hi-res, almost similar to FLAC?

Related link: https://videoconverter.wondershare.com/ogg/ogg-to-midi.html

2022-07-05 10:08 UTC, oleg-derevenetz commented
Hi @LeHerosInconnu

> At first my idea was to play the music in MIDI format and record it while it is being played to be transformed into an audio file format

If you mean doing it on the fly on the user's machine, then it's not trivial to do it in a portable way on all supported platforms, because the game itself may not even have an access to the resulting audio stream (to record it in a file) in case when external synthesizers are used for the MIDI playback. If you mean doing it in advance and then distribute the recorded audio files as part of the game, then there are licensing issues arise.

2022-07-05 10:36 UTC, LeHerosInconnu commented
@oleg-derevenetz.

> Hi @LeHerosInconnu
> 
> > At first my idea was to play the music in MIDI format and record it while it is being played to be transformed into an audio file format
> 
> If you mean doing it on the fly on the user's machine, then it's not trivial to do it in a portable way on all supported platforms, because the game itself may not even have an access to the resulting audio stream (to record it to a file) in case when external synthesizers are used for the MIDI playback (I even believe it's most of the cases - MIDI files are just passed to the external software or hardware synthesizer and it plays them directly). If you mean doing it in advance and then distribute the recorded audio files as part of the game, then there are licensing issues arise.

My idea is to make it "ready to use" for the player, so yes, the files would have to be converted first.

What if the program converts the MIDI files into memory and uses them that way without generating audio files (to avoid licensing issues)?

2022-07-05 10:49 UTC, oleg-derevenetz commented
@LeHerosInconnu

> What if the program converts the MIDI files into memory and uses them that way without generating audio files (to avoid licensing issues)?

Then we have to bundle some software synthesizer with the game to convert MIDI to WAV or some other audio format on the fly. Technically this may be possible (for example, there is [FluidSynth](https://www.fluidsynth.org/) in active development). We may even use it on Windows only, because issues with MIDI are usually Windows-specific.