Add The Price of Loyalty team to credits
ihhub/fheroes2 pull request #5599
Opened 2022-07-06 14:37 UTC by ihhub

close #5223

2022-07-06 14:41 UTC, ihhub commented
It is important to verify all names once again. I checked every letter manually but I might miss something.

2022-07-06 15:45 UTC, zenseii requested changes
Some names are missing from the second page. I'm not sure if this is intentional but here is a screenshot I took ingame of the credits:
<details>

![image](https://user-images.githubusercontent.com/12501091/177590507-1d403722-fbf8-4022-a709-38058bb83177.png)
</details>

Basically Manual, Package Design, German Consultant, Playtesters and Map Designers.

The rest looks good. I've checked all names down to their single letters.

EDIT: I just noticed the third page containing these.

EDIT 2: I've checked the rest of the names and they are all correct. I'll have another look once code duplication adjustments have been done.

2022-07-06 15:49 UTC, ihhub commented
I think we nee to address code duplication issue here. I'll introduce helper functions to tackle this problem.

2022-07-07 08:44 UTC, zenseii approved these changes

2022-07-07 10:08 UTC, merged