First BG Translation changes
ihhub/fheroes2 pull request #5632
Opened 2022-07-12 08:59 UTC by Effektus

2022-07-12 10:08 UTC, zenseii requested changes
Hi @Effektus!

Thank you so much for your contribution here. I left some comments. I decided to leave a comment for every place where there are conflicts with the new bg.po. Luckily they are not many and can easily be solved. Also now that you have made a fork and are using github desktop these things will not be a problem anymore since your local bg.po can easily be kept up to date by fetching and merging the latest changes on your github fork using this button on `effektus/fheroes2-EffektusBG`:
![image](https://user-images.githubusercontent.com/12501091/178466920-f67a81d5-436b-40d1-a1b3-c5c1239f0d88.png)


The most important issue is to change the file to use UTF-8 encoding via poedit as I explained over in the issue thread. This will fix the wrong characters being used here on github since github doesn't support CP1251 encoding.

Don't hesitate to ask if anything is unclear.

2022-07-12 10:08 UTC, zenseii commented on files/lang/bg.po
> -msgid "warlock|Red Tower"
The same as for the comment above probably goes for this one too. These lines should not be removed.

2022-07-12 10:08 UTC, zenseii commented on files/lang/bg.po
> -
These changes are also due to the bg.po being older.

2022-07-12 10:08 UTC, zenseii commented on files/lang/bg.po
> +"Some items may be unavailable."
These lines are due to the older bg.po.

2022-07-12 10:08 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Campaign Game"
I suspect this is a typo and it should either be translated or left empty for now instead of being in English.

2022-07-12 10:13 UTC, zenseii commented on files/lang/bg.po
> +"Content-Type: text/plain; charset=CP1251\n"
Basically using CP1251 within poedit is fine when you want to test your changes within the game, but whenever you want to upload your changes as a PR you will need to change back to UTF-8 encoding due to github.

2022-07-12 10:33 UTC, zenseii commented on files/lang/bg.po
> +msgid "%{name} half the enemy troops!"
I believe these changes should be reverted due to being an older bg.po.

2022-07-12 10:34 UTC, zenseii commented on files/lang/bg.po
> +msgid "%{attacker} do %{damage} damage."
These changes should probably be reverted too?

2022-07-12 10:41 UTC, Effektus commented on files/lang/bg.po
> +"Content-Type: text/plain; charset=CP1251\n"
I did it

2022-07-12 10:42 UTC, Effektus commented on files/lang/bg.po
> +msgid "Red Tower"
Yes my bg.po not last version. And i ask before how to solve this problem. Last time I rewrite all my translations.

2022-07-12 10:53 UTC, zenseii commented on files/lang/bg.po
> +msgid "Red Tower"
You won't have to copy over every single translation anymore. To solve these conflicts now I would personally just use github by using "Suggestions" that you can find by going to the "Files changed" pane:
![image](https://user-images.githubusercontent.com/12501091/178473421-48f7e3bf-c914-4a2b-92d5-df0d033c166a.png)

And then making single comments with suggestions for changes by clicking this symbol:
![image](https://user-images.githubusercontent.com/12501091/178473887-3af7e754-4d0d-46c7-9e3d-f4640bc95dc3.png)
This will let you write suggestions like the one below which you can choose to commit directly.
```suggestion
msgid "sorceress|Red Tower"
```

Note that you need to comment on lines that are either added or present, you cannot make suggestions on removed lines for some reason.

2022-07-12 10:58 UTC, Effektus commented on files/lang/bg.po
> +msgid "Red Tower"
can I use VS Code? for comparing and after this to comit new po file?
![image](https://user-images.githubusercontent.com/12934196/178475116-d4a90020-1747-49e7-9074-a4f0a0d23c31.png)

2022-07-12 10:59 UTC, zenseii commented on files/lang/bg.po
>  msgid ""
```suggestion
msgid ""
"Required video files for campaign selection window are missing. Please make "
"sure that all necessary files are present in the system."
msgstr ""

msgid ""
```

2022-07-12 11:01 UTC, zenseii commented on files/lang/bg.po
> +msgid "Red Tower"
I have no experience with VS Code but from the looks of it yes. You just have to make the changes to bg.po with that and then commit those changes with github desktop. It's completely up to you how you want to do this. You will know that you have made the correct changes when they no longer show up as changes in the "Files changed" pane in this PR.

2022-07-12 11:01 UTC, Effektus commented on files/lang/bg.po
> +msgid "Red Tower"
I will do it with VS Code and all be OK 
![image](https://user-images.githubusercontent.com/12934196/178475641-1c64edff-2279-4038-b626-54234d354630.png)

2022-07-12 11:38 UTC, zenseii requested changes

2022-07-12 11:38 UTC, zenseii commented on files/lang/bg.po
> +"The Sphere of Negation artifact is in effect for this battle, disabling all combat "
It seems the line length for the file was increased. This should easily be solvable by opening the bg.po in poedit and saving it after making sure that the line length is set to 79 in the settings. I believe I explained how to do this in the github issue.

2022-07-12 12:18 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Campaign Game"
This line still needs to be solved as I wrote above.

2022-07-12 12:24 UTC, zenseii requested changes
I've left a couple of comments. It would be great if you could address them. I would also like to ask if you can change the PR title to have Bulgarian instead of the abbreviated BG since this makes it easier to search for later on if necessary.

I've asked in our discord server if there is anyone capable in Bulgarian that can review this, but if we do not get any response within a reasonable time we will use the powers of technology to review the translations ourselves.

2022-07-12 12:24 UTC, zenseii commented on files/lang/bg.po
> +"Last-Translator: Effektus <effektus@live.co.uk>\n"
As a rule we leave this email line as the fheroes2 one because there could be more people contributing to the translation in the future so this keeps it simple.

2022-07-12 12:31 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Campaign Game"
![image](https://user-images.githubusercontent.com/12934196/178490218-30387886-07b5-41de-af22-dffd741d72b2.png)

2022-07-13 12:45 UTC, zenseii commented on files/lang/bg.po
> +msgstr "армия|Малко"
Hi, @Effektus.

The "army|" part should not be translated, nor any other strings with a `|` - they are just there to give a context for the string. The translation should therefore only be "Малко"

2022-07-13 13:22 UTC, zenseii commented on files/lang/bg.po
> +msgstr "army|Малко"
I see I was ambiguous but what I meant was to not write the "army|" part, neither translated or in English. Like this:
```suggestion
msgstr "Малко"
```

2022-07-13 13:35 UTC, Effektus commented on files/lang/bg.po
> +msgstr "army|Малко"
I am Sorry

2022-07-13 19:13 UTC, zenseii requested changes
Hi @Effektus.

I've reviewed your translations using DeepL now. I left some comments and it would be great if you could take a look at them and address them when you should have the time to.

Thank you!

2022-07-13 19:13 UTC, zenseii commented on files/lang/bg.po
> +"или за „Цената на лоялността“."
These special quotation signs do not exist in the engine yet. I'm not sure what the best approach here is,
but we might need to add some code to address it for the time being.

Could you please share your opinion on this @ihhub?

2022-07-13 19:13 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Посртугалски"
My translation gives "Португалски" without the `c`. Is this just a typo?

2022-07-14 04:48 UTC, ihhub commented on files/lang/bg.po
> +"или за „Цената на лоялността“."
fheroes2 does not support such quotation Please use `\"` combination.

2022-07-14 08:15 UTC, zenseii commented on files/lang/bg.po
> +"или за „Цената на лоялността“."
By the way, note that if you're using poedit you only need to write the quotation sign ", not the backslashes \. They will be handled by poedit.

2022-07-15 14:19 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Пакет"
Maybe not, is there a difference or not?

2022-07-15 14:21 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Изненада"
My mistake sorry

2022-07-15 14:28 UTC, Effektus commented on files/lang/bg.po
> +"силите на начинаещ герой."
No problem here

2022-07-15 23:06 UTC, zenseii commented
Hi @Effektus.

I'm currently going through your latest translations, but could you please add any other translations you make to a separate branch of yours that you afterwards can make a PR from as soon as this PR has been approved and merged?

This makes it possible to merge this current PR soon and for you to continue your work without interruptions on that separate branch in the meantime. Not to mention, this is also much easier for us reviewers to handle without needing to check many strings.

The work done in this PR is more than enough to warrant a merge at this point, I just need to check over it, which hopefully I'll be able to do tomorrow.

2022-07-16 09:35 UTC, ihhub requested changes
Hi @Effektus , I left few comments in this pull request. Could you please take a look to check whether they make sense?

2022-07-16 09:35 UTC, ihhub commented on files/lang/bg.po
> +msgstr "fheroes2 Отбор възкрасяване представя"
Google says that this translates into `fheroes2 Team Beautification presents`. Are we sure that this is the correct translation?

2022-07-16 09:35 UTC, ihhub commented on files/lang/bg.po
> +msgstr "Черно и бяло"
This should be translated in terms of `Black & White cursor` (but without cursor), not `Black & White` in general.

2022-07-16 09:35 UTC, ihhub commented on files/lang/bg.po
> +msgstr "Резолюция"
This is screen resolution. Is is a correct translation?

2022-07-16 09:35 UTC, ihhub commented on files/lang/bg.po
> +msgstr "Звук"
Here we should use an adjective rather than a noun because a full English sentence is `Audio settings`.

2022-07-16 09:35 UTC, ihhub commented on files/lang/bg.po
> +msgstr "Цвят"
This should be an adjective in relation to cursor: `Color cursor`.

2022-07-16 09:35 UTC, ihhub commented on files/lang/bg.po
> +msgstr "Текст"
I believe this is not the correct translation. This option adds an additional text support, not just showing or hiding text.

2022-07-16 16:21 UTC, Effektus commented on files/lang/bg.po
> +msgstr "fheroes2 Отбор възкрасяване представя"
I am sure about this on yes. 
![image](https://user-images.githubusercontent.com/12934196/179363381-3756798a-35f7-4a74-b622-eb905faee038.png)

2022-07-16 16:22 UTC, Effektus commented on files/lang/bg.po
> +msgstr "fheroes2 Отбор възкрасяване представя"
but now I see I have one wrong char. Sorry

2022-07-16 16:31 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Резолюция"
yes it is not

2022-07-16 23:57 UTC, zenseii requested changes
Hi, @Effektus.
I've finished reviewing the last strings you added. When you have the time and feel like it, it would be great if you could address them.

Additionally noomorph from our Discord server said they know some Bulgarian and that they might be able to look over your translations tomorrow.

2022-07-16 23:57 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Изчакайте тази единица"
The English here isn't very good but what it should say is "Make this unit wait". Using deepL it seems that in Bulgarian it is saying "Wait for this unit", which is not correct, you're not waiting for the unit, it will await its turn.

2022-07-16 23:57 UTC, zenseii commented on files/lang/bg.po
> +"Изчаква текущото създание. Текущото създание отлага реда си, докато не дойде "
The same comment I made above might be valid here about waiting for and awaiting?

2022-07-16 23:57 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Нападението на %{attacker}' заслепява %{target}!"
Is it correct to have the apostrophe `'` after `%{attacker}` ?

2022-07-16 23:57 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Погледът на %{attacker}' превръща %{target} в камък!"
The same about apostrophe goes for this string.

2022-07-16 23:57 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Проклятието %{attacker}' пада върху %{target}!"
The same about apostrophe goes for this string.

2022-07-16 23:57 UTC, zenseii commented on files/lang/bg.po
> +msgstr "всеки с +%{attack} бонус към своето нападащо умение."
This string is a continuation of the one above actually, but is done like this for some reason. I believe this one starts with a capital letter?
In other words is this complete combined string correct
`"%{name} стреля със силата на %{count} стрелци всеки с +%{attack} бонус към своето нападащо умение."` ?

2022-07-17 06:01 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Изчакайте тази единица"
In a case like this, I agree with corrections and I am grateful for the clarification, but for the corrections to be made by a person who knows "SOME" Bulgarian is, to put it mildly, frivolous considering that I am Bulgarian by birth and I am 40 years old and I think that I know my native language much better than even the younger generations of Bulgarians.

2022-07-17 06:06 UTC, Effektus commented on files/lang/bg.po
> +"Изчаква текущото създание. Текущото създание отлага реда си, докато не дойде "
This is correct no need to fix

2022-07-17 06:07 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Нападението на %{attacker}' заслепява %{target}!"
will fix this one

2022-07-17 06:07 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Погледът на %{attacker}' превръща %{target} в камък!"
will fix this one

2022-07-17 06:08 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Проклятието %{attacker}' пада върху %{target}!"
will fix this one

2022-07-17 06:13 UTC, Effektus commented on files/lang/bg.po
> +msgstr "всеки с +%{attack} бонус към своето нападащо умение."
it is not i will fix

2022-07-17 08:14 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Изчакайте тази единица"
Yes, you are right and I apologize if it seemed like a critique of your Bulgarian. To clarify we want every translation added to be checked before merged. This doesn't mean we have expectations of the translations to be done so well that they get the nobel in literature. Of course we appreciate them being done as well as possible, but the main goal is to get the message across. This is why it is (barely) good enough for me and @ihhub to check with translation apps, but if someone else that knows the language to a certain degree can do it then they might spot typos or other things more easily.

From my own work on translating into several languages, even my native, mistakes crop up especially because reading so much English gets confusing at some point, and sometimes I misunderstand what the English original meaning was, or maybe there are interesting alternatives to what I wrote.

So I hope this cleared things up and that this is more to speed things up. Let me underline that we are very appreciative of the work you've done!

2022-07-17 08:37 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Изчакайте тази единица"
Also, I want to add that when I said noomorph "knows some Bulgarian" this was an understatement as it became apparent later on that they are very passionate about languages, especially Slavic languages.

2022-07-17 08:51 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Изчакайте тази единица"
I see in Discord server

2022-07-17 10:10 UTC, Effektus commented on files/lang/bg.po
> +"Зони от\n"
Благодаря

2022-07-17 10:12 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Врагът се предаде!"
Това не правилно

2022-07-17 10:16 UTC, noomorph commented on files/lang/bg.po
> +msgstr "Врагът се предаде!"
Добре.

2022-07-17 11:29 UTC, zenseii requested changes

2022-07-17 11:29 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Дяволски много"
This is my last remark. As I explained in Discord, all strings beginning with "army|" have a length limit due to restrictions of the UI. Hopefully in the future this can be solved, but right now it might be better to try to not make the strings too long.
Here is when using the current translation:
![image](https://user-images.githubusercontent.com/12501091/179395951-ded9c690-f9a1-452d-84ec-0b1205647d26.png)

The length limit is around 8 characters. Is it possible to only write "Дяволски" and this would still be understood by the player?

Note that this length limit does not count for the other zounds string. In other words this is completely fine in the game:
"Дяволски много \n"
"%{monster}"

2022-07-17 11:32 UTC, ihhub commented on files/lang/bg.po
> +msgstr "Дяволски много"
I think a translation from "thousands" - хиляди would be good as well.

2022-07-17 11:36 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Дяволски много"
The problem with "thousands" is that it is both unrelated to the english original and doesn't make sense considering the numbers of troops they refer to 500-999.

I know some earlier translations went this way, but my personal opinion is that this is not a good translation as the original intent is lost and you end up confusing the player.

2022-07-17 11:50 UTC, ihhub commented on files/lang/bg.po
> +msgstr "Дяволски много"
Then I would suggest to use шайка for Horde and орда for Zounds which makes more sense.

2022-07-17 12:13 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Дяволски много"
I'm fine with this. This will only lost the sort of humorous intent of the original. A much more modern equivalent of "zounds" would be something like "Yikes!":
![image](https://user-images.githubusercontent.com/12501091/179397708-6c4c4adf-440e-49f2-ae83-6edf33ef6bf9.png)

Let's hear what @Effektus has to say then? 😊

2022-07-17 15:25 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Дяволски много"
For this reason I was added Изненада - Surprise in my first translation of zonds

2022-07-17 16:18 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Дяволски много"
Yes, I believe we have discussed this single string enough for now and I'm confident we all know all the ups and downs and we have shared good viewpoints and understood them. It's time to make a decision.

I'm personally fine with all suggestions so far. Heck even "hundreds"  `стотици` (?) isn't bad because it would mean we get to preserve horde as the closest to English word `орда`.

As always this isn't final so if we realize at a later point that something else would have been better then we can always change this.

2022-07-17 19:46 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Дяволски много"
In my opinion hundreds (Стотици) is well.

2022-07-18 11:41 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Дяволски много"
I'm fine with this.

2022-07-18 12:24 UTC, zenseii requested changes
Your last commit made me noticed some very small but important things, @Effektus.
It would be great if you could address them.

2022-07-18 12:24 UTC, zenseii commented on files/lang/bg.po
> +"Тълпа от \n"
Could you please remove the unnecessary white space here` "Тълпа от\n"` ?
This is not just nitpicking since in this case they affect how the line will be center-aligned in the dialog.

2022-07-18 12:24 UTC, zenseii commented on files/lang/bg.po
> +"Стотици \n"
Another unnecessary white space here as well.

2022-07-18 12:44 UTC, Effektus commented
How much translated rows is good for each milestone?

2022-07-18 12:52 UTC, zenseii approved these changes
This looks good to me now.

I would say between 100-200 lines is fine for something like this translation where there are a lot of lines left. The max is as stated 1000 lines.

2022-07-19 15:00 UTC, ihhub approved these changes

2022-07-19 15:00 UTC, merged

2022-07-19 15:00 UTC, ihhub commented
@Effektus , thank you so much for contribution to the project!

2022-07-22 12:55 UTC, Effektus commented
Someone explane to me this wrod "Dwarfbane". I know Dwarf is Джудже

2022-07-22 14:03 UTC, Effektus commented
@zenseii What to do with this one?
![image](https://user-images.githubusercontent.com/12934196/180455775-5466f4fb-3931-42e8-864d-85f2914df819.png)

2022-07-22 14:05 UTC, zenseii commented
> Someone explane to me this wrod "Dwarfbane". I know Dwarf is Джудже

Hi, @Effektus !
This means sort of Dwarf-slayer, Dwarf-killer, Dwarf-murderer. A bane is something lethal to someone or something, in this case it is a title given to a hero who is famous for slaying dwarves.

2022-07-22 14:09 UTC, zenseii commented
> @zenseii What to do with this one? ![image](https://user-images.githubusercontent.com/12934196/180455775-5466f4fb-3931-42e8-864d-85f2914df819.png)

This simply means your branch has changes that are conflicting with the main ihhub/fheroes2 repository. You can make a pull-request as it says and try to push the changes to that.

What I would do is just merge and update your `master` branch with latest changes and create a new branch. This is quicker. Then just make a PR from your temp branch to the new branch with the changes you've made. I think this should create the least amount of headaches. Not sure how this happened though.

2022-07-22 14:28 UTC, Effektus commented
> > @zenseii What to do with this one? ![image](https://user-images.githubusercontent.com/12934196/180455775-5466f4fb-3931-42e8-864d-85f2914df819.png)
> 
> ~This simply means your branch has changes that are conflicting with the main ihhub/fheroes2 repository. You can make a pull-request as it says and try to push the changes to that.~
> 
> ~What I would do is just merge and update your `master` branch with latest changes and create a new branch. This is quicker. Then just make a PR from your temp branch to the new branch with the changes you've made. I think this should create the least amount of headaches. Not sure how this happened though.~
> 
> **EDIT: No, I was wrong. This is just telling you that you can press that button to create a PR with the changes to your temp branch.**

I want to merge effektusbg-Temp with effektus BG

2022-07-22 14:36 UTC, zenseii commented
> I want to merge effektusbg-Temp with effektus BG

Yes, and is there a problem with pressing the green button?

2022-07-22 14:36 UTC, Effektus commented
> > I want to merge effektusbg-Temp with effektus BG
> 
> Yes, and is there a problem with pressing the green button?

No

2022-07-22 14:41 UTC, Effektus commented
> > > I want to merge effektusbg-Temp with effektus BG
> > 
> > 
> > Yes, and is there a problem with pressing the green button?
> 
> No

Done

2022-07-22 14:52 UTC, zenseii commented
Great! Could you please solve merge conflicts: 
![image](https://user-images.githubusercontent.com/12501091/180464961-540664eb-eaf9-40ca-87c0-a125b763ed4b.png)


Also I'm confused by why many of these lines are reported as changed/new when I recognize them from the last PR:
Latest PR:
![image](https://user-images.githubusercontent.com/12501091/180465466-9f45054e-8c21-4c79-903d-ab91191cea1c.png)

Previous PR (the one we are currently discussing in):
![image](https://user-images.githubusercontent.com/12501091/180465702-e9fc3c53-46c9-4c0c-8ad0-0a2ecc51c4f2.png)