Use right graphic for create upgrades at adventure objects
ihhub/fheroes2 pull request #5636
Opened 2022-07-12 19:45 UTC by Verlf-Cerf

2022-07-12 20:38 UTC, zenseii requested changes

2022-07-12 20:38 UTC, zenseii commented on src/fheroes2/heroes/heroes_action.cpp
> +            fheroes2::renderMonsterFrame( (*mons[i]).GetUpgrade(), surface, { 6 + offsetX, 6 + offsetY } );
Hi, @Verlf-Cerf!

Thank you very much for your contribution. Could you please make the small changes to adhere to clang formatting that this project uses, which is also why the code style check fails. You can check it in the action details in case you didn't know.

2022-07-12 20:49 UTC, zenseii approved these changes

2022-07-12 23:32 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_action.cpp
> +            fheroes2::renderMonsterFrame( ( *mons[i] ).GetUpgrade(), surface, { 6 + offsetX, 6 + offsetY } );
While this syntax for dereferencing a pointer is valid, there is a less clunky one:

```suggestion
            fheroes2::renderMonsterFrame( mons[i]->GetUpgrade(), surface, { 6 + offsetX, 6 + offsetY } );
```

2022-07-13 01:20 UTC, merged

2022-07-13 01:20 UTC, ihhub commented
@Verlf-Cerf , thank you so much for your contribution to the project!