Effektus bg
ihhub/fheroes2 pull request #5685
Opened 2022-07-22 14:40 UTC by Effektus

Next 100 rows

2022-07-22 15:14 UTC, Effektus commented
@zenseii  Sorry but I don't know how to resolve conflicts here

2022-07-22 16:30 UTC, zenseii commented
> @zenseii Sorry but I don't know how to resolve conflicts here

I should have time to look at it tomorrow. My first guess would be some kind of formatting even though it says you're using utf-8 encoding. Maybe it's using windows line endings (CLRF) instead of unix (LF)?

2022-07-25 08:02 UTC, zenseii commented
Hi, @Effektus!

I've looked into the various things with this PR.

First off, resolving conflicts is quite easy with github:
1. Click "Resolve conflicts"
![image](https://user-images.githubusercontent.com/12501091/180726683-00ff04e3-57a3-491d-9543-e2476b4b0e4a.png)

2. Find a conflict, in this case there are 3 present, and choose which lines to keep
![image](https://user-images.githubusercontent.com/12501091/180726842-38860464-d1ce-4859-a560-178e0822e1bf.png)
3. In the example above we want to keep the most recent date of editing so we edit the lines directly and leave this:
![image](https://user-images.githubusercontent.com/12501091/180727041-ace9529c-f050-414c-b1fa-41a3973ff41b.png)

4. Click next to go to the next conflict:
![image](https://user-images.githubusercontent.com/12501091/180727212-c92dfdc5-67ef-4337-8f42-bc9a2357014a.png)


Secondly, I checked the bg.po and it was indeed using CRLF for line endings. This is possible to see when enabling to view this in Notepad++:
![image](https://user-images.githubusercontent.com/12501091/180727560-b4697960-8d50-4172-8b2f-b8e3b17e56e7.png)

Disabling this option in POedit will solve this problem for all line endings when you save the PO file:
![image](https://user-images.githubusercontent.com/12501091/180727957-1c533de8-a768-4f0a-9408-a0c1e4e1d4d2.png)

This can be found in File->Preferences->Advanced.

Github desktop should recognize that changes have been made to the file but it won't show that line endings have changed. Just reopen the file in something like Notepad++ to confirm that the line endings are correct now, that is, "LF".

![image](https://user-images.githubusercontent.com/12501091/180728293-a28ade38-c29c-452c-936f-eb9ec94e9a60.png)

2022-07-25 08:35 UTC, Effektus commented
> Hi, @Effektus!
> 
> I've looked into the various things with this PR.
> 
> First off, resolving conflicts is quite easy with github:
> 
> 1. Click "Resolve conflicts"
>    ![image](https://user-images.githubusercontent.com/12501091/180726683-00ff04e3-57a3-491d-9543-e2476b4b0e4a.png)
> 2. Find a conflict, in this case there are 3 present, and choose which lines to keep
>    ![image](https://user-images.githubusercontent.com/12501091/180726842-38860464-d1ce-4859-a560-178e0822e1bf.png)
> 3. In the example above we want to keep the most recent date of editing so we edit the lines directly and leave this:
>    ![image](https://user-images.githubusercontent.com/12501091/180727041-ace9529c-f050-414c-b1fa-41a3973ff41b.png)
> 4. Click next to go to the next conflict:
>    ![image](https://user-images.githubusercontent.com/12501091/180727212-c92dfdc5-67ef-4337-8f42-bc9a2357014a.png)
> 
> Secondly, I checked the bg.po and it was indeed using CRLF for line endings. This is possible to see when enabling to view this in Notepad++: ![image](https://user-images.githubusercontent.com/12501091/180727560-b4697960-8d50-4172-8b2f-b8e3b17e56e7.png)
> 
> Disabling this option in POedit will solve this problem for all line endings when you save the PO file: ![image](https://user-images.githubusercontent.com/12501091/180727957-1c533de8-a768-4f0a-9408-a0c1e4e1d4d2.png)
> 
> This can be found in File->Preferences->Advanced.
> 
> Github desktop should recognize that changes have been made to the file but it won't show that line endings have changed. Just reopen the file in something like Notepad++ to confirm that the line endings are correct now, that is, "LF".
> 
> ![image](https://user-images.githubusercontent.com/12501091/180728293-a28ade38-c29c-452c-936f-eb9ec94e9a60.png)

Sorry, but I can find the Resolve Conflicts button. I had found it on Friday, but it was inactive. But now I can find it!

2022-07-25 08:36 UTC, Effektus commented
> > Hi, @Effektus!
> > I've looked into the various things with this PR.
> > First off, resolving conflicts is quite easy with github:
> > 
> > 1. Click "Resolve conflicts"
> >    ![image](https://user-images.githubusercontent.com/12501091/180726683-00ff04e3-57a3-491d-9543-e2476b4b0e4a.png)
> > 2. Find a conflict, in this case there are 3 present, and choose which lines to keep
> >    ![image](https://user-images.githubusercontent.com/12501091/180726842-38860464-d1ce-4859-a560-178e0822e1bf.png)
> > 3. In the example above we want to keep the most recent date of editing so we edit the lines directly and leave this:
> >    ![image](https://user-images.githubusercontent.com/12501091/180727041-ace9529c-f050-414c-b1fa-41a3973ff41b.png)
> > 4. Click next to go to the next conflict:
> >    ![image](https://user-images.githubusercontent.com/12501091/180727212-c92dfdc5-67ef-4337-8f42-bc9a2357014a.png)
> > 
> > Secondly, I checked the bg.po and it was indeed using CRLF for line endings. This is possible to see when enabling to view this in Notepad++: ![image](https://user-images.githubusercontent.com/12501091/180727560-b4697960-8d50-4172-8b2f-b8e3b17e56e7.png)
> > Disabling this option in POedit will solve this problem for all line endings when you save the PO file: ![image](https://user-images.githubusercontent.com/12501091/180727957-1c533de8-a768-4f0a-9408-a0c1e4e1d4d2.png)
> > This can be found in File->Preferences->Advanced.
> > Github desktop should recognize that changes have been made to the file but it won't show that line endings have changed. Just reopen the file in something like Notepad++ to confirm that the line endings are correct now, that is, "LF".
> > ![image](https://user-images.githubusercontent.com/12501091/180728293-a28ade38-c29c-452c-936f-eb9ec94e9a60.png)
> 
> Sorry, but I can find the Resolve Conflicts button. I had found it on Friday, but it was inactive. But now I can find it!

![image](https://user-images.githubusercontent.com/12934196/180734552-45dddd89-8de8-46c7-9148-dfdbea0ef8c6.png)

2022-07-25 08:37 UTC, Effektus commented
> > > Hi, @Effektus!
> > > I've looked into the various things with this PR.
> > > First off, resolving conflicts is quite easy with github:
> > > 
> > > 1. Click "Resolve conflicts"
> > >    ![image](https://user-images.githubusercontent.com/12501091/180726683-00ff04e3-57a3-491d-9543-e2476b4b0e4a.png)
> > > 2. Find a conflict, in this case there are 3 present, and choose which lines to keep
> > >    ![image](https://user-images.githubusercontent.com/12501091/180726842-38860464-d1ce-4859-a560-178e0822e1bf.png)
> > > 3. In the example above we want to keep the most recent date of editing so we edit the lines directly and leave this:
> > >    ![image](https://user-images.githubusercontent.com/12501091/180727041-ace9529c-f050-414c-b1fa-41a3973ff41b.png)
> > > 4. Click next to go to the next conflict:
> > >    ![image](https://user-images.githubusercontent.com/12501091/180727212-c92dfdc5-67ef-4337-8f42-bc9a2357014a.png)
> > > 
> > > Secondly, I checked the bg.po and it was indeed using CRLF for line endings. This is possible to see when enabling to view this in Notepad++: ![image](https://user-images.githubusercontent.com/12501091/180727560-b4697960-8d50-4172-8b2f-b8e3b17e56e7.png)
> > > Disabling this option in POedit will solve this problem for all line endings when you save the PO file: ![image](https://user-images.githubusercontent.com/12501091/180727957-1c533de8-a768-4f0a-9408-a0c1e4e1d4d2.png)
> > > This can be found in File->Preferences->Advanced.
> > > Github desktop should recognize that changes have been made to the file but it won't show that line endings have changed. Just reopen the file in something like Notepad++ to confirm that the line endings are correct now, that is, "LF".
> > > ![image](https://user-images.githubusercontent.com/12501091/180728293-a28ade38-c29c-452c-936f-eb9ec94e9a60.png)
> > 
> > 
> > Sorry, but I can find the Resolve Conflicts button. I had found it on Friday, but it was inactive. But now I can find it!
> 
> ![image](https://user-images.githubusercontent.com/12934196/180734552-45dddd89-8de8-46c7-9148-dfdbea0ef8c6.png)

I found it now but it is not active for me

2022-07-25 08:38 UTC, Effektus commented
I don't have write accsess may be

2022-07-25 09:31 UTC, zenseii commented
> I don't have write accsess may be

I'm not sure this is the reason. I was able to solve conflicts with my PRs when I was a contributor. Maybe Github have changed something or the permissions in this repo have changed.

Anyways, since the conflicts are so few I can edit them then. Note you have to edit all of them in order to be able to "Mark as resolved".

Which is the preferred translations of these if you don't mind me asking?
Conflict 1:
![image](https://user-images.githubusercontent.com/12501091/180745525-d9ce8f23-e40b-4862-902a-4ec79bbd9c21.png)
Conflict 2:
![image](https://user-images.githubusercontent.com/12501091/180745618-b1ce3ca8-ca43-42e8-a33e-ab67370a67f2.png)

2022-07-29 10:47 UTC, zenseii requested changes
Hi @Effektus !

I've read through your translation. It looks very good from what I can tell! I left a few comments, so if you have time it would be great if you could take a look.

Also could you change the title of this PR like I mentioned for the last PR? Something like "Update Bulgarian translation" should be fine. We don't put the names of the contributors in the title of PRs.

Thanks for resolving the conflicts and for addressing the line ending issues.

2022-07-29 10:47 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Мините на Уредника"
The translation here gives me the "mines of the curator". "Carator" is just a name and should be pronounced as similar as possible in Bulgarian.

2022-07-29 10:47 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Сила на оръжията"
The translation here gives me the literal meaning "Power of weapons". Force of arms means to capture or take something by using violence or by using weapons. https://www.merriam-webster.com/dictionary/by%20force%20of%20arms

2022-07-29 10:47 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Ръкавицата"
This one is tricky, but it does not refer to a "gauntlet" as in a glove, but as a challenge/trial/race. This refers to how this scenario needs to be beaten within 8 weeks.

2022-07-29 10:47 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Магьосници"
Why isn't something like "некроманти" used here? The translation says that your translation is closer to "magicians".

2022-07-29 10:47 UTC, zenseii commented on files/lang/bg.po
> +"Огритата ви разпознават като Джуджеубиец и желаят да се присъединят към вас."
The translation here tells me that the ogres are "eager to join you". I interpreted "lumber over" here to refer to them walking in a very noisy and unorganized way over to you, in a way reflecting how ogres are not considered very intelligent.

This is the definition I used from dictionary.com "to move clumsily or heavily, especially from great or ponderous bulk:
overloaded wagons lumbering down the dirt road." See the second definition further down: https://www.dictionary.com/browse/lumber

2022-07-29 10:47 UTC, zenseii commented on files/lang/bg.po
> +"внимават. Той им крещи: \"Кой от вас е достатъчно смел да се присъедини към "
This is a tricky sentence "As you approach the group of elves, their leader calls them all to attention."
It refers to how a military leader can call soldiers to "stand at attention". If you google this you should find images showing what it means.

The Bulgarian translation I see says that they are told to be careful, which isn't correct in this context.

2022-07-29 10:47 UTC, zenseii commented on files/lang/bg.po
> +"Елфите стоят мирно, докато се приближавате. Техният водач ви казва: \"Нека "
The same comment I made about "standing at attention" is valid here. DeepL translates your string as "standing peacefully" which is not correct in this context.

2022-07-29 10:47 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Първият свитък"
DeepL gives me "First scroll" for this. Does this also mean something like "the best scroll"? That is what foremost refers to here - a scroll which is much better than the average scroll.

2022-07-29 10:47 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Доп. информация"
This seems to translate to "Additional information". This is not what this string refers to. It is an option that outputs all text as well as other information in the game to a console for people with visual impairments to use with a program that generates audio from it. Think of it more as "Text mode". Does "Текстов режим" work?

2022-07-29 11:17 UTC, Effektus commented on files/lang/bg.po
> +"Елфите стоят мирно, докато се приближавате. Техният водач ви казва: \"Нека "
this is ok for me

2022-07-29 11:22 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Доп. информация"
Yes I'm changing this one because on Bulgarian this is more accurate. Shows and hides additional information about units, battle or building.

2022-07-29 13:14 UTC, zenseii reviewed
This has my approval as soon as the PR title is changed.

2022-07-29 13:41 UTC, zenseii approved these changes
I've looked over this PR now, so should you have a moment to spare, @ihhub, then this PR is ready for your review.

2022-07-30 15:01 UTC, merged

2022-07-30 15:01 UTC, ihhub commented
@Effektus , thanks a lot for improving Bulgarian translation!