Cleanup hero rendering code as a part of Adventure Map rendering
ihhub/fheroes2 pull request #5686
Opened 2022-07-22 15:40 UTC by ihhub

- fix image saving code
- fix boat flag asset issue: the flag suppose to be 4 pixel height but in reality 248
- update comments in relation to Adventure Map rendering
- huge cleanup of hero rendering
- add the code to split hero sprites into tiles needed for the upcoming Adventure Map rendering

2022-07-23 04:42 UTC, ihhub commented
Hi @Branikolog and @LeHerosInconnu, I need your quick help of verifying that hero rendering remains the same as before with this pull request. I don't want to break rendering just now :)

2022-07-23 09:18 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left one suggestion, please take a look when you have time.

2022-07-24 03:47 UTC, ihhub commented on src/engine/image_tool.cpp
> +                memcpy( reinterpret_cast<int8_t *>( surface->pixels ) + surface->pitch * i, imageIn + width * i, static_cast<size_t>( width ) );
`int8_t` is a copy-paste mistake from screen.cpp. I will fix there as well.

2022-07-24 10:13 UTC, LeHerosInconnu commented
Hello @ihhub,

> Hi @Branikolog and @LeHerosInconnu, I need your quick help of verifying that hero rendering remains the same as before with this pull request. I don't want to break rendering just now :)

I did a test up to Month: 2 Week: 3 Day: 5 on the Broken Alliance scenario, :) everything seems fine.
Should I do a longer test?

Another thing.
For a while now, when I download files to test PRs, the downloaded file is put in an additional .zip file.
For example, the file "fheroes2_windows_x64_SDL2.zip" is saved as "fheroes2_windows_x64_SDL2.zip.zip".
And this is not the case for the files of the Snapshots (latest builds).
Any idea why this happens?

2022-07-24 10:29 UTC, oleg-derevenetz commented
@LeHerosInconnu

> For a while now, when I download files to test PRs, the downloaded file is put in an additional .zip file.

That's because GitHub [creates additional ZIP file on the fly](https://github.com/actions/upload-artifact#limitations) when the artifact is downloaded. Currently there is no workaround.

2022-07-24 10:44 UTC, oleg-derevenetz approved these changes

2022-07-24 10:48 UTC, ihhub commented
@LeHerosInconnu , thank you!

2022-07-24 10:48 UTC, merged