WIP: redesign rendering of Adventure Map
ihhub/fheroes2 pull request #5692
Opened 2022-07-24 07:51 UTC by ihhub

This pull request fixes most of issues related to rendering of Adventure Map, especially in relation to heroes, boats and monsters.

close #1038
close #1103
close #1293
close #1428
close #1516
close #1933
close #2186
close #2307
close #2321
close #2500
close #3183
close #3187
close #3188
close #3277
close #3344
close #3363
close #3608
close #3746
close #4120
close #4132
close #4134
close #4135
close #4236
close #4237
close #4481
close #4526
close #4754
close #4939
close #5257

2022-07-26 12:32 UTC, oleg-derevenetz commented on src/fheroes2/gui/interface_gamearea.h
> +        BaseObjectAnimationInfo operator=( const BaseObjectAnimationInfo & ) = delete;
Hi @ihhub `operator=()` should return a reference, that's why we have this error here. It's funny that MSVC distinguished himself in this regard (as always) - apparently it thinks that as long as operator is deleted, we shouldn't need to generate an instance of this abstracts class anyway, so it's OK to return a copy :)

BTW if copy constructor and copy assignment operator are explicitly defined as deleted, there is no need to explicitly delete the move constructor and move assignment operator - they will not be generated anyway.

2022-07-26 13:05 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.h
> +        BaseObjectAnimationInfo operator=( const BaseObjectAnimationInfo & ) = delete;
That's for pointing out! I am still in the middle of this mess change... I am trying some multiple approaches.

2022-08-06 16:52 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +    tile.AddonsPushLevel1( Maps::TilesAddon( Maps::TERRAIN_LAYER, GetUniq(), obj, idx ) );
This one might be questionable. We might need to use `BACKGROUND_LAYER` here so that digging would check if any objects of `BACKGROUND_LAYER` or `ACTION_OBJECT_LAYER` are present.

2022-08-06 19:14 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few comments here (what caught my eye), please take a look when you have time.

2022-08-07 03:18 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +                const bool isFog = drawFog && tile.isFog( friendColors );
This is a leftover from the old code.

2022-08-07 03:18 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.h
> +        UNUSED_LEVEL = 0x08,
Good point!

2022-08-07 03:19 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +                animationObject.reset( new Interface::ObjectFadingOutInfo( tile.GetObjectUID(), tile.GetIndex(), tile.GetObject() ) );
Sure!

2022-08-07 04:01 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.h
> +        uint8_t alphaValue{ 255 };
`alphaValue` is used during rendering  of the object. Either we do casting or use virtual function or just a member of the structure.

I will move `alphaStep` to child classes.

2022-08-07 04:11 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +                if ( world.GetTiles( currentStep->GetFrom() ).isRoad() && tileTo.isRoad() ) {
Yes, you are right. This is again an old code which I reused but I verified the logic and your suggestion is absolutely valid. This is before:
![image](https://user-images.githubusercontent.com/19829520/183274904-adbb88be-9d68-489c-82dd-5f605da0ef79.png)

Notice that the forth arrow is very long. And this is after your suggestion:
![image](https://user-images.githubusercontent.com/19829520/183274926-5807a444-3eff-456e-ad03-e0fb77768168.png)

2022-08-07 04:16 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +                animationObject.reset( new Interface::ObjectFadingOutInfo( tile.GetObjectUID(), tile.GetIndex(), tile.GetObject() ) );
I restructured a bit so we don't need to declare a variable for these places.

2022-08-07 04:17 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +void Interface::GameArea::runFadingAnimation( const std::shared_ptr<BaseObjectAnimationInfo> info )
Fixed.

2022-08-07 04:32 UTC, ihhub commented
Hi @oleg-derevenetz , I addressed all your comments (except one `alphaValue` place). Could you please take a look again?

2022-08-07 10:30 UTC, oleg-derevenetz approved these changes

2022-08-08 01:01 UTC, merged