Fix experience from Tree of Knowledge
ihhub/fheroes2 pull request #5697
Opened 2022-07-25 16:45 UTC by undef21

fix #5695

2022-07-25 16:56 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_action.cpp
> +        const uint32_t possibleExperience = Heroes::GetExperienceFromLevel( level + 1 ) - Heroes::GetExperienceFromLevel( level );
Hi @undef21 as it [turned out recently](https://github.com/ihhub/fheroes2/pull/5678#discussion_r926491549) the name of `GetExperienceFromLevel ()` is misleading - it returns not the value needed to reach the specified level, but the value that is needed to reach the NEXT level after the specified, so for example `GetExperienceFromLevel( 1 )` returns 1000, and with 1000XP the hero will become a level 2 hero. So I suppose you need to set the `possibleExperience` just to `Heroes::GetExperienceFromLevel( hero.GetLevel() )`.

2022-07-25 17:19 UTC, undef21 commented on src/fheroes2/heroes/heroes_action.cpp
> +        const uint32_t possibleExperience = Heroes::GetExperienceFromLevel( level + 1 ) - Heroes::GetExperienceFromLevel( level );
@oleg-derevenetz  we need difference between levels. GetLevel(10) returns 15500 exp :)

2022-07-25 17:41 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_action.cpp
> +        const uint32_t possibleExperience = Heroes::GetExperienceFromLevel( level + 1 ) - Heroes::GetExperienceFromLevel( level );
@undef21 But not between `level + 1` and `level`. For example if our hero is of level 2, `Heroes::GetExperienceFromLevel( level + 1 )` will return 3200 points and `Heroes::GetExperienceFromLevel( level )` will return 2000 points, so the difference will be 1200 points, while he will need just 1000 points (2000-1000) to progress to level 3, right?

2022-07-25 18:04 UTC, undef21 commented on src/fheroes2/heroes/heroes_action.cpp
> +        const uint32_t possibleExperience = Heroes::GetExperienceFromLevel( level + 1 ) - Heroes::GetExperienceFromLevel( level );
Fixed:)

2022-07-25 19:05 UTC, oleg-derevenetz requested changes

2022-07-25 19:05 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_action.cpp
> +        const int level = hero.GetLevel();
I would add the following assertion here:

```
assert( level > 0 );
```

I may be wrong, but `GetExperienceFromLevel()` may go to the infinite recursion if level is negative.

2022-07-30 14:59 UTC, merged

2022-07-30 14:59 UTC, ihhub commented
@undef21 , thanks a lot for this fix!