Update sv.po
ihhub/fheroes2 pull request #5777
Opened 2022-08-21 19:47 UTC by Mr-Bajs

Updated swedish translation

2022-08-21 23:13 UTC, zenseii requested changes
Hi, @Mr-Bajs !

Thank you so much for this great contribution. I've checked this PR and the translations were very well done (I might borrow some for the Norwegian translation...) and I only have some minor remarks and some questions.

I'm not a native speaker of Swedish so please forgive me for any obvious questions.

It would be great if you could take a look at these comments when you should feel at ease to.

Don't hesitate to ask if anything is unclear.

Also Jimstrom from Discord server said they had already translated some things so if you could avoid translating more until we've found out what so that we can avoid you guys doing the same things.

2022-08-21 23:13 UTC, zenseii commented on files/lang/sv.po
> +msgstr "Åskvigg"
Does this refer to an actual bolt of lightning or a sort of rock/thunderstone. This is just a genuine question.

2022-08-21 23:13 UTC, zenseii commented on files/lang/sv.po
> +msgid "game: remember last focus"
These lines need to be removed since thaat option doesn't exist anymore.

2022-08-21 23:13 UTC, zenseii commented on files/lang/sv.po
> +msgid "world: show terrain penalty"
This option doesn't exist anymore.

2022-08-22 10:22 UTC, Mr-Bajs commented on files/lang/sv.po
> +msgstr "Visa Ballista information"
One word. Ballistainformation is the correct one.

2022-08-22 10:22 UTC, Mr-Bajs commented on files/lang/sv.po
> +msgstr "Se Hjältealternativ"
I don't think its grammatically correct to have capital letter for nouns in swedish. Don't think most swedish readers would mind though in terms of style. Though it should be consistent.

"Visa hjältealternativ" is probably be best translation though.

2022-08-22 10:22 UTC, Mr-Bajs commented on files/lang/sv.po
> +msgstr "Förräderi!"
No, the exlamation point should be removed.

2022-08-22 10:22 UTC, Mr-Bajs commented on files/lang/sv.po
> +msgstr ""
Sure!

2022-08-22 10:32 UTC, Mr-Bajs commented on files/lang/sv.po
> +msgstr "Tur"
Sure. Regarding luck, it feels very odd to have the Grundläggande, Avancerad and Professionell levels for Luck. I'm not really sure about Expert ->Professionell translation but guess it will do as for now. I just some translations so that most translations is done, then do a second review.

Should the prefix campaignBonus| be added in the translation?

2022-08-22 10:34 UTC, Mr-Bajs commented on files/lang/sv.po
> +msgstr "Åskvigg"
Åskblixt is probably the best translation.

2022-08-22 10:54 UTC, zenseii commented on files/lang/sv.po
> +msgstr "Tur"
Yep, there's enough flexibility in the code to allow for different naming schemes for the various mastery levels of each secondary skill. Some original translations do this.

All prefixes like "campaignBonus|" should be omitted in the translated string. They are just there to give the translator a hint about what context this particular string is in, since there exist at least two strings with the same name.

The reason the campaignBonus| context exists is because in an older version of fheroes2 we had to try to shorten all the bonuses but this is not really the case anymore since strings that are "too long" will just be cut with a "..." replacing the too long part.

2022-08-22 10:57 UTC, zenseii commented
Also @Mr-Bajs , could you please change the title of the PR to "Update Swedish translation"? This makes it easier to search for later and more easily understandable. Thanks!

2022-08-31 14:33 UTC, ihhub commented
Hi @Mr-Bajs , I fixed merging conflict for this pull request. Could you please address comments given by @zenseii ?

2022-11-13 15:49 UTC, Mr-Bajs commented
So to address these issues, I go to Files changes and then edit? Or how is the process?

2022-11-13 16:22 UTC, zenseii commented
> So to address these issues, I go to Files changes and then edit? Or how is the process?

It depends on your setup, but you can do edits here on github. I prefer doing that for translations.
1. Just go to files changed, open a comment for a line by hovering your mouse cursor over that area and pressing the blue button with a white cross:
![image](https://user-images.githubusercontent.com/12501091/201532121-c8aba89f-151e-4352-8e79-458f70d8da2d.png)
2. Add a suggestion by clicking the icon highlighted below. This can only be done in the "Files Changed" pane:
![image](https://user-images.githubusercontent.com/12501091/201532182-a598d53b-62fc-40ba-956d-65615eeeeb93.png)
3. Change the string:
![image](https://user-images.githubusercontent.com/12501091/201532243-2011d04e-21f0-408e-ad96-0e9541268241.png)
4. Click "Add a single comment":
![image](https://user-images.githubusercontent.com/12501091/201532316-f3fa5117-5518-4de1-bc9f-5dc975459145.png)
5. Click commit suggestion (it is disabled because I chose start a review":
![image](https://user-images.githubusercontent.com/12501091/201532368-472441b8-a9ac-4562-9d06-666309e7fb85.png)

2022-11-13 16:52 UTC, zenseii commented
We need to fix merge conflicts so I'll do that now.

2023-01-15 06:46 UTC, alexanderlindstrom commented on files/lang/sv.po
> +msgstr "Åskvigg"
I'd say just "blixt" would be more precise and common word. Åskblixt really doesn't mean anything and ljusblixt is something you'd get from a gunshot.

2023-03-17 11:13 UTC, closed without merging