Polish translation - Artifacts' little stories
ihhub/fheroes2 pull request #5811
Opened 2022-09-07 11:12 UTC by Pulfiarz

Hi, I've translated the artifacts' stories, when you pick it up from the map. 

Mostly I've added new translations, but I've made a few changes. Allow me to switch into Polish language now.

- zmieniłem tłumaczenia Nomad na Nomada
- zmieniłem Sekstans na Astrolabium, bo obrazek przedstawia właśnie to urządzenie
- zmieniłem niestygnącą lawę na niestygnącą skałę wulkaniczną. Powodem jest poprawność petrologiczna, jak coś już jest poza wnętrzem Ziemi to przestaje być magmą, zwłaszcza jeśli przybiera formę skały.
- Thunder Mace - zmieniłem z maczugi na kiścień, bo grafika przedstawia właśnie taką broń.
- Giant Flail - sytuacja się komplikuje, bo tak naprawdę, to zarówno ta broń jak i Thunder Mace to są "flail". Dotychczas 'flail' tłumaczony był na 'korbacz', ale problem z tym, że korbacz to tak naprawdę rodzaj bata (ale i sera :D). Kiedyś w światku fantasy pojawił się taki trend, żeby używać słowa korbacz na 'kolczatą kulę na łańcuchu', która powinna być nazwana kiścieniem. Dla przykładu podręczniki do WFRP podają taką błędną nazwę. Ale chyba czas zerwać z tą niesłuszną tradycją. Jednak nie chciałem jeszcze raz dawać artefaktu z kiścieniem w nazwie. Słowo 'flail' może być jednak oznaczać też 'cep bojowy', co w miarę pasuje do grafiki (broń zilustrowano w sposób sugerujący dwuręczne użycie), a warto dodać, że używanie cepów bojowych rzeczywiście nie jest łatwe i może zakończyć się uderzeniem samego siebie jednym z bijaków. I na takie tłumaczenie się zdecydowałem.

Może się trafić jeszcze jakaś niewielka zmiana, ale teraz nie kojarzę.

2022-09-07 14:31 UTC, zenseii requested changes
Hi, @Pulfiarz.

Thank you so much for these contributions! I've left some comments and should you want to and have the time then it would be great it you could address them.

In general I noticed that you added many "fuzzy" marks. Adding these marks will make a string always show up as the English one and not the translated string. In Poedit they will show up as orange lines. There is really no reason to add these, so I would like to ask if you can remove the ones you added. We can easily find your changes by going to the "Files changed" tab in the PR, so there is no need to use fuzzy marks for this.

The reason fuzzy marks are sometimes found in translations is because we run a script that automatically adds them to new strings or strings that have been changed in the source code.

2022-09-07 14:31 UTC, zenseii commented on files/lang/pl.po
> +#| msgid "Are you sure you want to dismiss this army?"
Could you please give some insight into why this line is needed? If it is not needed then please remove it as well as the other similar ones below.

Also if the translation is good then please remove the fuzzy mark.

2022-09-07 14:31 UTC, zenseii commented on files/lang/pl.po
> +#| msgid "Are you sure you want to retreat?"
Same as the one above. Also if the the translation is good then you should remove the fuzzy mark.

2022-09-07 14:31 UTC, zenseii commented on files/lang/pl.po
> +#| msgid "Game Difficulty"
Same as the comments above.

2022-09-07 14:31 UTC, zenseii commented on files/lang/pl.po
> +#| msgid "luck|Normal"
Same as the comments above.

Also note that this normal refers to the difficulty. Just to be sure.

2022-09-07 14:31 UTC, zenseii commented on files/lang/pl.po
>  #, fuzzy
Should this be unfuzzied?

2022-09-07 14:31 UTC, zenseii commented on files/lang/pl.po
> +#, fuzzy
Why is a fuzzy mark added here?

2022-09-07 15:25 UTC, Pulfiarz commented on files/lang/pl.po
> +#| msgid "Are you sure you want to dismiss this army?"
Well, I think I know what could have happened...  I downloaded the .po file some time ago, worked with it in POEdit, but meanwhile some changes were made in the translation file. Wanting to have the most update version, I merged the new file with the old one using POEdit. Maybe  that caused some fuzzies, because I haven't done anything to some lines that you have highlighted.  The fuzzies next to the artifacts descriptions are on me ... Sorry, I'm really new at this ... Of course, I can remove all the fuzzies.

2022-09-07 16:41 UTC, zenseii commented on files/lang/pl.po
> +#| msgid "Are you sure you want to dismiss this army?"
No worries! I figured some things were still a bit unclear about how this works.
If you could remove only the fuzzies that are added in this PR then that would be great.

2022-09-08 07:55 UTC, Pulfiarz commented on files/lang/pl.po
> +#| msgid "Are you sure you want to dismiss this army?"
Ok, I've updated the file and most of the 'fuzzies' are gone, but not all of them. e.g. line 533 in my repository has no fuzzy mark and here it does have one. Don't know how to handle it. :(

2022-09-08 07:56 UTC, Pulfiarz commented on files/lang/pl.po
> +#, fuzzy
Corrected

2022-09-08 08:55 UTC, zenseii commented on files/lang/pl.po
> +#| msgid "Are you sure you want to dismiss this army?"
Good job with solving these things!

The fuzzy marks you are referring to are also removed in this PR, that is why they have a minus sign "-" at the start of them, and this is because they are actually fuzzied currently in master and you are proposing to unfuzzy them with this PR.

2022-09-08 09:00 UTC, zenseii commented on files/lang/pl.po
> +#| msgid "Are you sure you want to dismiss this army?"
Also Btw you can also make changes to this PR by clicking on the lines in the Files changed tab and then selecting the "Suggestion" symbol which is the leftmost one.

It's just imoortant to make sure this doesn't create a mess when trying to sync your local pl.po file.

2022-09-08 09:41 UTC, Pulfiarz commented on files/lang/pl.po
> +#| msgid "Are you sure you want to dismiss this army?"
Oh, then it's ok, I think.
Should I do something now? Sorry for asking, but I just don't know if i should "resolve conversation" or click somewhere etc.  The next PR i will be more aware of everything, I promise ;P

2022-09-08 09:52 UTC, zenseii commented on files/lang/pl.po
> +#| msgid "Are you sure you want to dismiss this army?"
It's fine and this is a very good PR for being a first PR. Yes, you can resolve this conversation.

2022-09-08 12:22 UTC, Arthusppp requested changes

2022-09-08 12:22 UTC, Arthusppp commented on files/lang/pl.po
> +"Wybierz stopień trudności.  Tego ustawienia nie będziesz mógł później "
Two spaces between "." and "Tego". Please remove one.

2022-09-08 12:22 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "WIedźmia Brosza Magii"
Second letter is upper, should be lower ("Wiedźma" instead of "WIedźma").

2022-09-08 12:22 UTC, Arthusppp commented on files/lang/pl.po
> +"topora i bez wysiłku  wyciągasz go."
Two spaces between "wysiłku" and "wyciągasz". Please remove one.

2022-09-08 12:32 UTC, Arthusppp commented on files/lang/pl.po
> +"powiedzenie leprekaunów \"Znalezione - nie kradzione\" zabierasz worek i "
Or "leprechaunów"?

2022-09-08 12:35 UTC, Pulfiarz commented on files/lang/pl.po
> +"Malutki leprekaun tańczy radośnie wokół magicznego worka. Widząc, że "
Słowo 'leprekaun' występowało już w tłumaczeniu wcześniej (przy okazji magicznych ogródków) dlatego na taką wersję się zdecydowałem.

2022-09-08 12:38 UTC, Arthusppp commented on files/lang/pl.po
> +"Kierując się panicznymi okrzykami damy o opałach zauważasz młodą kobietę "
"Kierując się panicznymi okrzykami damy **w** opałach**,** zauważasz (...)"?
("w" instead of "o" and a comma)

2022-09-08 12:40 UTC, Pulfiarz commented on files/lang/pl.po
> +"Krótki postój w niespotykanie wiejskiej gospodzie zaowocowała wymianą "
Yes... "zaowocowała" because at first i used not 'postój' but 'przerwa', Of course, I will correct this.

2022-09-08 12:43 UTC, Arthusppp commented on files/lang/pl.po
> +"Wypoczywając w trakcie postoju dostrzegasz jak żbik wdrapuje się na niskie "
"Wypoczywając w trakcie postoju, dostrzegasz (...)" (add a comma)

2022-09-08 12:44 UTC, Pulfiarz commented on files/lang/pl.po
> +"Kierując się panicznymi okrzykami damy o opałach zauważasz młodą kobietę "
Yes, "w" it should be. I missed coma on purpose, because these are not two separate parts of a sentence, but one part. Like in "Pracując dziś przy biurku zobaczyłem, że mam za dużo papierów."

2022-09-08 12:44 UTC, Arthusppp commented on files/lang/pl.po
> +"drzewo, by dostać się do kruczego gniazda. Działając pod wpływem impulsu sam "
"Działając pod wpływem impulsu, sam (...)" (add a comma)

2022-09-08 12:44 UTC, Pulfiarz commented on files/lang/pl.po
> +"Twą uwagę przykuwa sopel sodu, który zdaje się opierać słońcu świecącemu w "
Oh yes, that's for sure :) Sorry ;p

2022-09-08 12:45 UTC, Pulfiarz commented on files/lang/pl.po
> +"Wypoczywając w trakcie postoju dostrzegasz jak żbik wdrapuje się na niskie "
The same as in the previous comment, I did it on purpose.

2022-09-08 12:53 UTC, Arthusppp commented on files/lang/pl.po
> +"Leprekaun, którego była to własność, nie mogąc cię powstrzymać przed "
Same as earlier: "leprekaun" or"leprechaun"?

2022-09-08 14:03 UTC, Pulfiarz commented on files/lang/pl.po
> +msgstr "WIedźmia Brosza Magii"
Will be corrected

2022-09-08 14:38 UTC, Pulfiarz commented on files/lang/pl.po
> +"topora i bez wysiłku  wyciągasz go."
Done

2022-09-08 14:39 UTC, Pulfiarz commented on files/lang/pl.po
> +msgstr "WIedźmia Brosza Magii"
Done

2022-09-08 14:42 UTC, Pulfiarz commented on files/lang/pl.po
> +"Wybierz stopień trudności.  Tego ustawienia nie będziesz mógł później "
Done

2022-09-08 21:43 UTC, Arthusppp commented on files/lang/pl.po
> +"powiedzenie leprekaunów \"Znalezione - nie kradzione\" zabierasz worek i "
"Znalezione - nie kradzione" - this should start from a lower letter. ("znalezione - nie kradzione")

2022-09-08 23:05 UTC, Pulfiarz commented on files/lang/pl.po
> +"powiedzenie leprekaunów \"Znalezione - nie kradzione\" zabierasz worek i "
Done

2022-09-09 10:44 UTC, zenseii commented
Hi @Arthusppp ! Could you please leave an approval or write a message when you are done reviewing this? Thank you!

2022-09-09 10:51 UTC, Arthusppp approved these changes

2022-09-09 10:51 UTC, Arthusppp commented
> Hi @Arthusppp ! Could you please leave an approval or write a message when you are done reviewing this? Thank you!

Done!

2022-09-09 11:14 UTC, zenseii approved these changes

2022-09-09 11:14 UTC, zenseii commented on files/lang/pl.po
> +msgstr "STOPIEŃ TRUDNOŚCI"
Hi @ihhub,
Special letters aside, would this text be too long for the space permitted for this button?

2022-09-10 02:51 UTC, ihhub commented on files/lang/pl.po
> +msgstr "STOPIEŃ TRUDNOŚCI"
Difficulty is the maximum length we can use so no more than 10 characters.

2022-09-10 06:11 UTC, ihhub commented on files/lang/pl.po
> +msgstr "STOPIEŃ TRUDNOŚCI"
@Pulfiarz and @zenseii , I believe the translation should be `trudność` in capital letters.

2022-09-10 06:24 UTC, Pulfiarz commented on files/lang/pl.po
> +msgstr "STOPIEŃ TRUDNOŚCI"
That's a pitty... I will change it to "trudność" then, but it's an unfortunate translation :-(

2022-09-10 06:26 UTC, ihhub commented on files/lang/pl.po
> +msgstr "STOPIEŃ TRUDNOŚCI"
We have limitations in UI elements so we can't put a super lengthy sentence on a button.

2022-09-10 06:40 UTC, Pulfiarz commented on files/lang/pl.po
> +msgstr "STOPIEŃ TRUDNOŚCI"
Changed

2022-09-10 12:17 UTC, zenseii approved these changes

2022-09-10 12:49 UTC, merged

2022-09-10 12:49 UTC, ihhub commented
@Pulfiarz , thank you very much for your contribution to the project!

2022-09-10 13:07 UTC, Pulfiarz commented
I'm glad that I could help :-)