Luck / Morale related objects are now reset after meeting / battle
ihhub/fheroes2 pull request #5826
Opened 2022-09-11 23:51 UTC by felix642

closes #3717

2022-09-22 15:31 UTC, ihhub requested changes
Hi @felix642 , I left few comments here. Would you mind to take a look?

2022-10-09 16:14 UTC, felix642 commented on src/fheroes2/heroes/heroes_action.cpp
> +    hero.resetLuckAndMoraleVisitedState();
I have removed those useless functions and replaced the calls with Heroes::ActionAfterBattle();

2022-10-09 16:14 UTC, felix642 commented on src/fheroes2/heroes/heroes.cpp
> +    visit_object.remove_if( [objectType]( const IndexObject & v ) { return std::find( objectType.begin(), objectType.end(), v.second ) != objectType.end(); } );
I have removed those useless functions and replaced the calls with Heroes::ActionAfterBattle();

2022-10-29 11:40 UTC, ihhub commented
Hi @felix642 , can you please update this pull request?

2022-10-29 15:28 UTC, felix642 commented on src/fheroes2/ai/ai_hero_action.cpp
> +            hero.ActionAfterBattle();
Sorry @ihhub, I must've missed this comment.
I think that makes sense. We are already calling this function after a battle in battle_main.cpp in the Battle::Loader function().

I will make the required changes.

2022-10-29 15:44 UTC, felix642 commented on src/fheroes2/ai/ai_hero_action.cpp
> +            hero.ActionAfterBattle();
Actually, after checking the code I do not think anymore this is a good idea.
The reason is that in most situations we would end up calling the function ActionAfterBattle() twice or we would have to add multiple calls based on the scenario. 

For example, when attacking a neutral enemy, there are multiple scenarios that might arise.

The neutral create might join us for money, they might also join us for free because they are free or because of an alliance, they might run away or we might have to fight them.

In most cases, we don't fight then so the HeroesAfterBattle() function is not called. We would have to manually call actionAfterBattle() in each case or we could call it at the end of the function, but the HeroesAfterBattle call becomes worthless.

2022-10-30 08:13 UTC, ihhub commented on src/fheroes2/ai/ai_hero_action.cpp
> +            hero.ActionAfterBattle();
Object visit state is not reset when monsters join an army or when 2 heroes met each other. I think the original issue description is incorrect (yes, written by me as well). We can reset only after battle.

When do we call `ActionAfterBattle()`  twice?

2022-10-30 13:43 UTC, felix642 commented on src/fheroes2/ai/ai_hero_action.cpp
> +            hero.ActionAfterBattle();
If we only have to update the Object visit state after a battle, it makes a lot of sense to implement the proposed change. I will update this PR later today.

2022-11-03 00:44 UTC, ihhub commented on src/fheroes2/ai/ai_base.cpp
> +    void Base::HeroesAfterBattle( HeroBase & hero, bool )
clang-tidy is correct about it. @felix642 , can you please apply this suggestion?

2022-11-08 17:14 UTC, zenseii commented
Hi, @felix642.

What is the state of this PR. Is it ready for review?

2022-11-08 19:03 UTC, felix642 commented
> Hi, @felix642.
> 
> What is the state of this PR. Is it ready for review again or are we waiting for @idshibanov to have a look at it?

HI @zenseii, this PR is ready for review

2022-11-09 07:27 UTC, ihhub approved these changes

2022-11-09 10:01 UTC, merged

2022-11-09 10:01 UTC, ihhub commented
@felix642 , thank you very much for this fix!