Patch 1
ihhub/fheroes2 pull request #5830
Opened 2022-09-12 15:58 UTC by dmitry-pshenitsin

2022-09-14 21:01 UTC, undef21 requested changes
Hello @dmitry-pshenitsin. I left several comments.

2022-09-22 15:32 UTC, ihhub commented
Marking this pull request as WIP since the author has no been updating it for a long time.

2022-10-10 16:36 UTC, a1exsh commented on files/lang/ru.po
> +msgstr "Безумный дядя Ваня"
I think that didn't fit in the UI.

2022-10-16 14:19 UTC, ihhub commented
I am closing this pull request as stalled.

2022-10-16 14:19 UTC, closed without merging