Generate gift button with new approach
ihhub/fheroes2 pull request #5836
Opened 2022-09-15 11:38 UTC by zenseii

This generates a default Gift button for all languages and makes the letter G available for button generation.

Close https://github.com/ihhub/fheroes2/issues/5237

2022-09-15 11:50 UTC, ihhub commented
Hi @zenseii , how about Evil interface? The code should be almost the same as for Good interface.

2022-09-15 11:56 UTC, zenseii commented
> Hi @zenseii , how about Evil interface? The code should be almost the same as for Good interface.

Yes, I thought about this and the only difference between them is whether to use `ICN::SYSTEM` or `ICN::SYSTEME`.

I don't think it should be necessary to repeat so much code so I'm thinking of a way to avoid this.

2022-09-15 11:57 UTC, ihhub commented
> > Hi @zenseii , how about Evil interface? The code should be almost the same as for Good interface.
> 
> Yes, I thought about this and the only difference between them is whether to use `ICN::SYSTEM` or `ICN::SYSTEME`.
> 
> I don't think it should be necessary to repeat so much code so I'm thinking of a way to avoid this.

And font colors :)

2022-09-15 12:02 UTC, zenseii commented
> > > Hi @zenseii , how about Evil interface? The code should be almost the same as for Good interface.
> > 
> > 
> > Yes, I thought about this and the only difference between them is whether to use `ICN::SYSTEM` or `ICN::SYSTEME`.
> > I don't think it should be necessary to repeat so much code so I'm thinking of a way to avoid this.
> 
> And font colors :)

Yes, my thought was that the font color would be adjusted automatically when you have chosen the evil interface but I haven't looked much into that part yet.

I was looking for code code where Evil button font generation is. Still trying to figure out this new approach.

2022-09-16 11:40 UTC, LeHerosInconnu commented
Hello @zenseii and @ihhub,

I find the "oblique strokes" a little too present in this version of the letter "G".

In fheroes2:
Compare with the letter "G" already present:

![G letter on button 01](https://user-images.githubusercontent.com/43583994/190630458-88acd586-d837-4796-960f-763c64f4776f.png)

2022-09-16 15:29 UTC, ihhub commented
Hi @zenseii and @LeHerosInconnu , the algorithm to generate letters is not ideal and as highlighted by @zenseii make some differences in one outer color of a letter. We will fix it later.

2022-09-17 02:31 UTC, ihhub requested changes
Hi @zenseii , good job! I left few suggestions in this pull request. Would you mind to take a look at them?

2022-09-17 02:31 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +            case ICN::BUTTON_DIFFICULTY_ARCHIBALD: {
I think we can reduce code duplication, especially with your changes:
```cpp
case ICN::BUTTON_DIFFICULTY_ARCHIBALD:
case ICN::BUTTON_DIFFICULTY_ROLAND:
case ICN::BUTTON_DIFFICULTY_POL: {
    std::array<fheroes2::Rect, 2> clearArea;
    int baseIcnId = ICN::UNKNOWN;
    fheroes2::Point textOffset;

    switch ( id ) {
    case ICN::BUTTON_DIFFICULTY_ARCHIBALD:
        ....
        break;
    case ICN::BUTTON_DIFFICULTY_ROLAND:
        ....
        break;
    case ICN::BUTTON_DIFFICULTY_POL:
        ....
        break;
    default:
        assert( 0 );
        break;
    }
....
```

However, it might be a bit complex to read. So why don't we expand `getSupportedText()` function usage by adding a new function:
```cpp
void renderTextOnButton( fheroes2::Image & releasedState, fheroes2::Image & pressedState, const char * text, const fheroes2::Point & releasedTextOffset, const fheroes2::Point & pressedTextOffset, const int32_t maxTextWidth, const fheroes2::FontColor fontColor )
{
    const fheroes2::FontType releasedFont{ fheroes2::FontSize::BUTTON_RELEASED, fontColor };
    const fheroes2::FontType pressedFont{ fheroes2::FontSize::BUTTON_PRESSED, fontColor };

    const char * text = getSupportedText( gettext_noop( "DIFFICULTY" ), releasedFont );

    fheroes2::Text releasedText( text, releasedFont );
    fheroes2::Text pressedText( text, pressedFont );

    releasedText.draw( releasedTextOffset.x + ( maxTextWidth - releasedText.width() ) / 2, releasedTextOffset.y, releasedState );
    pressedText.draw( pressedTextOffset.x + ( maxTextWidth - pressedText.width() ) / 2, pressedTextOffset.y, pressedState );
}
```

Then we can use this function to make such calls:
```cpp
renderTextOnButton( _icnVsSprite[id][0], _icnVsSprite[id][1], gettext_noop( "DIFFICULTY" ),  { 10, 5 }, { 10, 6 }, 132, fheroes2::FontColor::GRAY );
```
This will be applied to all new buttons.

What do you think?

2022-09-17 11:21 UTC, zenseii commented on src/fheroes2/agg/agg_image.cpp
> +            case ICN::BUTTON_DIFFICULTY_ARCHIBALD: {
Thanks! It should be implemented the way you suggested now. 

I attempted writing something similar last evening but your way is much tidier and will be easier to adjust later on, not to mention this structure can probably be used in other future similar cases.

2022-09-17 11:22 UTC, zenseii commented on src/fheroes2/game/game_campaign.cpp
> +        fheroes2::Sprite releasedImage;
Done!

2022-09-17 11:22 UTC, zenseii commented on src/fheroes2/agg/agg_image.cpp
> +            case ICN::BTNGIFT_GOOD: {
Done!

2022-09-17 14:58 UTC, ihhub requested changes
Hi @zenseii , I left few more comments here. Could you please check them?

2022-09-17 14:58 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                const fheroes2::FontColor releasedFontColor = ( isGoodInterface ) ? fheroes2::FontColor::WHITE : fheroes2::FontColor::GRAY;
Please remove parenthesis for `isGoodInterface` variable.

2022-09-17 14:58 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                const fheroes2::FontType releasedFont{ fheroes2::FontSize::BUTTON_RELEASED, releasedFontColor };
This code should use `renderTextOnButton()` function.

2022-09-17 14:58 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
>                  const fheroes2::FontType releasedFont{ fheroes2::FontSize::BUTTON_RELEASED, fheroes2::FontColor::WHITE };
This code should use `renderTextOnButton()` function.

2022-09-17 14:58 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +            case ICN::BUTTON_DIFFICULTY_POL:
Actually your previous implementation was cleaner. I was suggesting at the end to use `renderTextOnButton()` function for the later code to make it cleaner :)

2022-09-17 15:09 UTC, zenseii commented on src/fheroes2/agg/agg_image.cpp
> +            case ICN::BUTTON_DIFFICULTY_POL:
I see now. Then I'll revert back to the structure where every campaign button is its own case.

2022-09-17 15:17 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +            case ICN::BUTTON_DIFFICULTY_POL:
Great!

2022-09-17 15:19 UTC, zenseii commented on src/fheroes2/agg/agg_image.cpp
> +            case ICN::BUTTON_DIFFICULTY_POL:
BTW it seems that with the current `renderTextOnButton()` the translated string is never shown, even if the letters exist?
I'll look into it, but would it have anything to do with using `gettext_noop()`?

2022-09-17 15:22 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +            case ICN::BUTTON_DIFFICULTY_POL:
`gettext_noop()` function literally returns the same string. You forgot to call `getSupportedText` within `renderTextOnButton`.

2022-09-17 16:12 UTC, zenseii commented on src/fheroes2/agg/agg_image.cpp
> +            case ICN::BUTTON_DIFFICULTY_POL:
I've added `getSupportedText`, yet the text is still not translated:

As an example, if I translate MIN to DIF:
![image](https://user-images.githubusercontent.com/12501091/190865937-4a6e3e16-e33f-4cf0-8a72-e2a3bb948cc1.png)
and have  use `_gettext_noop( "MIN" )` in `renderTextOnButton()` then the button will render as `MIN`:
![image](https://user-images.githubusercontent.com/12501091/190865994-f0cd3b09-f157-4c6c-b984-0da0d124a186.png)
If I set `_("MIN")` then it will render as `DIF` :
![image](https://user-images.githubusercontent.com/12501091/190866036-f0c7c3b9-731f-4547-9984-4cb24d963154.png)

Setting breakpoints I can see that with `gettext_noop()` the parameter `const char * text` of `renderTextOnButton()` has a value of `MIN`, so it would seem that only MIN gets sent from the call to `renderTextOnButton()` when generating the MIN button, no matter what the current translated file in use says.

2022-09-17 16:25 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +            case ICN::BUTTON_DIFFICULTY_POL:
I'll take a look tomorrow.

2022-09-17 16:42 UTC, zenseii commented on src/fheroes2/agg/agg_image.cpp
> +            case ICN::BUTTON_DIFFICULTY_POL:
Thanks. I'll keep looking at it to see if I can figure something out.

It seems that the text does get translated in `getSupportedText()`, since the value of `translatedText` changes to `DIF` but still the untranslated MIN is what is ultimately used when rendering...

```cpp
const char * getSupportedText( const char * text, const fheroes2::FontType & font )
    {
        const char * translatedText = _( text );
        return fheroes2::isFontAvailable( translatedText, font ) ? translatedText : text;
    }
```

It seems like something isn't going right at `return fheroes2::isFontAvailable(...)` since `text` aka MIN is the outcome of that statement rather than DIF.

2022-09-18 04:26 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +            case ICN::BUTTON_DIFFICULTY_POL:
For me even with this check everything works fine. I removed it. Could you please check again? Also please do a clean build.

2022-09-18 11:14 UTC, zenseii commented on src/fheroes2/agg/agg_image.cpp
> +            case ICN::BUTTON_DIFFICULTY_POL:
I've tested it with a clean build while the comma character check is still there and it still returns false:
![image](https://user-images.githubusercontent.com/12501091/190899187-729efe5b-f19d-4f50-abfc-1fbf61df8b01.png)

![image](https://user-images.githubusercontent.com/12501091/190899200-511ec636-4ba7-4fca-a281-be27c12a1995.png)
Maybe I've misunderstood but shouldn't the comma character indeed be missing from the `BUTTON_RELEASED` font since we haven't generated that character?

And yes, removing that check makes the translated string show up.

2022-09-18 11:30 UTC, zenseii commented on src/fheroes2/agg/agg_image.cpp
> +            case ICN::BUTTON_DIFFICULTY_POL:
Changing it to check for a D makes it not return false so the string gets translated
```cpp
const Sprite & commaCharacter = AGG::getChar( 'D', fontType );
        if ( commaCharacter.empty() ) {
            return false;
        }
```

2022-09-18 12:34 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +            case ICN::BUTTON_DIFFICULTY_POL:
A comma doesn't exist for buttons. I haven't seen any button using it. D is the same random character as well as comma. Removing this check just makes to execute the loop below so no harm except few extra CPU cycles.

2022-09-18 12:36 UTC, ihhub approved these changes

2022-09-18 12:38 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    Fill( out, 4, 3 + i, 132 - i, 16, out.image()[5 * 132] );
This is not a part of this pull request but `out.image()[...]` is very dangerous without checks. We need to come up with an extra function which checks the value and throws an exception when we are trying to access out of boundaries array element.

2022-09-18 12:43 UTC, zenseii commented on src/fheroes2/agg/agg_image.cpp
> +                    Fill( out, 4, 3 + i, 132 - i, 16, out.image()[5 * 132] );
If `Blit()` is safer then we can use that instead. Sadly `getButtonFillingColor()` does not work because the Evil campaign buttons have a different color in their pressed state and the Expansion buttons have different colors for both pressed and released.

2022-09-18 12:44 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    Fill( out, 4, 3 + i, 132 - i, 16, out.image()[5 * 132] );
We can just create an issue do not to forget to fix this possible application crash :)

2022-09-18 12:59 UTC, merged

2022-09-18 13:00 UTC, ihhub commented
@zenseii , thank you so much for these changes!