Add Handicap feature present in the OG
ihhub/fheroes2 pull request #5839
Opened 2022-09-17 08:03 UTC by ihhub

2022-09-17 11:42 UTC, zenseii reviewed
Hi @ihhub ,

Since this PR removes the swap arrows in the single player scenario window, then it is highly related to this issue, and might even close it:
https://github.com/ihhub/fheroes2/issues/4721

It is also relevant to this discussion about these arrows:
https://github.com/ihhub/fheroes2/discussions/4701

To summarize these two discussions, these arrows should be removed, however we shouldn't forget about the functionality to change order of players in single player mode, and what we should do with that at a later point, whether to keep it or just not have it like the OG.

2022-09-17 13:33 UTC, ihhub commented
Hi @zenseii , these are valid points. We should get rid of these confusing arrows.

2022-09-17 16:34 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few suggestions, please take a look when you have time :)

2022-09-17 16:34 UTC, oleg-derevenetz commented on src/fheroes2/gui/player_info.cpp
> +        const PlayerInfo & info = *iter;
What do you think about adding an assertion somewhere here to verify that `info.player` is not `nullptr`?

2022-09-17 16:34 UTC, oleg-derevenetz commented on src/fheroes2/gui/player_info.h
> +        /// show_play_info: show game info with color status (play/not play)
I believe this comment is a bit outdated :) How about this: "displayInGameInfo: use colored and grayscale race icons to distinguish between players who are still in the game and vanquished players respectively"?

2022-09-17 16:34 UTC, oleg-derevenetz commented on src/fheroes2/system/players.h
> +    }
How about something like this:

```cpp
if ( status == HandicapStatus::NONE ) {
  _handicapStatus = status;
  return;
}

assert( control & CONTROL_HUMAN );

_handicapStatus = status;
```

? This should help catch potential errors in handicap logic instead of masking them.

2022-09-18 12:39 UTC, ihhub commented on src/fheroes2/gui/player_info.cpp
> +        const PlayerInfo & info = *iter;
An assertion was added in `void Interface::PlayersInfo::UpdateInfo()` method at the time of inserting these pointers (line 121).

2022-09-18 12:40 UTC, ihhub commented on src/fheroes2/gui/player_info.h
> +        /// show_play_info: show game info with color status (play/not play)
Yes. It makes sense.

2022-09-18 12:47 UTC, ihhub commented on src/fheroes2/system/players.h
> +    }
This is a good point.

2022-09-18 12:58 UTC, ihhub commented
Phew. I committed an experimental code by mistake which generated a lot of clang-tidy warnings...

2022-09-18 13:11 UTC, oleg-derevenetz commented on src/fheroes2/gui/player_info.cpp
> +        const PlayerInfo & info = *iter;
Ah yes, they are checked in another function while populating the `PlayersInfo`. If you believe that's enough, I'm fine with that.

2022-09-18 13:13 UTC, oleg-derevenetz approved these changes

2022-09-18 13:32 UTC, merged