Bulgarian Translation Update 5
ihhub/fheroes2 pull request #5845
Opened 2022-09-17 19:41 UTC by Effektus

2022-09-17 20:47 UTC, zenseii requested changes
Hi @Effektus ! Thank you again for your continued work on this translation. I left a few comments and I hope you can find the time to have a look at them should you want to.

2022-09-17 20:47 UTC, zenseii commented on files/lang/bg.po
> +msgstr "МИНИМАЛНО"
This needs to be 3 letters max to fit on the "MIN" button:
![image](https://user-images.githubusercontent.com/12501091/190875585-bec58a86-894b-43be-b86a-1f595ef675c0.png)

2022-09-17 20:47 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Вербувайте"
Is there a specific reason the %{name} is missing here?

2022-09-17 20:47 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Оставащи Истрели"
It seems like the word Истрели starts with a capital letter? Is this consistent with the other similar terms like Hit points etc?

2022-09-18 13:27 UTC, zenseii requested changes
Hi @Effektus,
I've checked the latest additions.
While testing some of them ingame I noticed this as well:
![image](https://user-images.githubusercontent.com/12501091/190904509-ed588dee-57db-4855-b8f7-440ac356dd8c.png)

2022-09-18 13:27 UTC, zenseii commented on files/lang/bg.po
> +msgstr "МАК"
This MAX appears in a different location than MIN, so making it 3 letters isn't strictly necessary, but if what you wrote works then don't bother changing it:
![image](https://user-images.githubusercontent.com/12501091/190903779-23acde7f-d8c1-4d8f-a7f2-30e07e51561f.png)

2022-09-18 14:23 UTC, zenseii reviewed
@Effektus, I left one comment here which you can take a look at should you have the time.

2022-09-18 14:23 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Виж информация за Катапулт"
Note that this refers to the Towers defending your castles by shooting at the enemies.

2022-09-18 15:08 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Виж информация за Катапулт"
It is reasonable

2022-09-19 17:18 UTC, zenseii approved these changes

2022-09-20 01:09 UTC, ihhub approved these changes

2022-09-20 01:09 UTC, merged

2022-09-20 01:09 UTC, ihhub commented
@Effektus , thank you so much for your dedication regarding this translation!