Bulgarian Translation Update 8
ihhub/fheroes2 pull request #5860
Opened 2022-09-20 09:25 UTC by Effektus

1000 rows translated

2022-09-20 12:59 UTC, zenseii requested changes
Hi @Effektus.
I left a couple of comments. It would be great if you could take a look at them. Thanks!

2022-09-20 12:59 UTC, zenseii commented on files/lang/bg.po
> +msgstr "ПОДАРЪК"
This has to be within 4 Letters since it's in the marketplace. Also this is better to translate as "GIVE" or "SEND" since that's what you're doing.

2022-09-20 12:59 UTC, zenseii commented on files/lang/bg.po
> +msgstr "MIDI"
Should this be in cyrillic?

2022-09-21 12:12 UTC, zenseii requested changes
Hi @Effektus,

I left some minor comments.
Also when checking the bg.po in poedit I found this string to have a comment:

![image](https://user-images.githubusercontent.com/12501091/191500569-99a4659e-3494-432b-a592-bf30c1f99de7.png)

Should it start that way or have a capital letter?

Thanks!

2022-09-21 12:12 UTC, zenseii commented on files/lang/bg.po
> +msgstr "път"
Should this have a capital letter?

2022-09-21 12:12 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Местоположение:"
This needs a white space at the end.

2022-09-21 12:25 UTC, Effektus commented
> Hi @Effektus,
> 
> I left some minor comments. Also when checking the bg.po in poedit I found this string to have a comment:
> 
> ![image](https://user-images.githubusercontent.com/12501091/191500569-99a4659e-3494-432b-a592-bf30c1f99de7.png)
> 
> Should it start that way or have a capital letter?
> 
> Thanks!
there is no space for 2 words "points" (точки) or (т.) What points is this "hit poins"? Еxperience points ?

2022-09-21 12:40 UTC, Effektus commented
> > > Hi @Effektus,
> > > I left some minor comments. Also when checking the bg.po in poedit I found this string to have a comment:
> > > ![image](https://user-images.githubusercontent.com/12501091/191500569-99a4659e-3494-432b-a592-bf30c1f99de7.png)
> > > Should it start that way or have a capital letter?
> > > Thanks!
> > > there is no space for 2 words "points" (точки) or (т.) What points is this "hit poins"? Еxperience points ?
> 
> They are "Life points", I guess. This is is the only place it appears: ![image](https://user-images.githubusercontent.com/12501091/191503698-84d11f14-eaf6-4451-895f-e1cdb986c197.png)
> 
> There should be enough space, no?
> 
> Meanwhile HP appears here: ![image](https://user-images.githubusercontent.com/12501091/191504100-a25578bb-5627-4e6c-ba80-4895731c1692.png)

"Life points" and "HP" (health points) are the same yes i note this. Ok I will translate both positions - "Life" in Bulgarian "Живот". This is sufficient explanation in Bulgarian.

2022-09-21 12:44 UTC, Effektus commented
> Живот

how to translate this 
![image](https://user-images.githubusercontent.com/12934196/191506917-40838115-ea08-42a9-9983-3e7b4164a8db.png)
this is not eagle?

2022-09-21 12:47 UTC, zenseii commented
> > Живот
> 
> how to translate this ![image](https://user-images.githubusercontent.com/12934196/191506917-40838115-ea08-42a9-9983-3e7b4164a8db.png) this is not eagle?

A Roc or Rokh is a Persian mythological bird. Maybe there's a wikipedia page about it in Bulgarian that might help you find the native translation?
https://bg.wikipedia.org/wiki/%D0%A0%D1%83%D1%85

2022-09-21 13:00 UTC, Effektus commented
> > > > Hi @Effektus,
> > > > I left some minor comments. Also when checking the bg.po in poedit I found this string to have a comment:
> > > > ![image](https://user-images.githubusercontent.com/12501091/191500569-99a4659e-3494-432b-a592-bf30c1f99de7.png)
> > > > Should it start that way or have a capital letter?
> > > > Thanks!
> > > > there is no space for 2 words "points" (точки) or (т.) What points is this "hit poins"? Еxperience points ?
> > 
> > 
> > They are "Life points", I guess. This is is the only place it appears: ![image](https://user-images.githubusercontent.com/12501091/191503698-84d11f14-eaf6-4451-895f-e1cdb986c197.png)
> > There should be enough space, no?
> > Meanwhile HP appears here: ![image](https://user-images.githubusercontent.com/12501091/191504100-a25578bb-5627-4e6c-ba80-4895731c1692.png)
> 
> "Life points" and "HP" (health points) are the same yes i note this. Ok I will translate both positions - "Life" in Bulgarian "Живот". This is sufficient explanation in Bulgarian.

here translation not working in my opinion!
![image](https://user-images.githubusercontent.com/12934196/191510349-85114dfb-77f4-450c-9cfd-ba4b2bcd8903.png)

2022-09-21 13:00 UTC, Effektus commented
> > > > > Hi @Effektus,
> > > > > I left some minor comments. Also when checking the bg.po in poedit I found this string to have a comment:
> > > > > ![image](https://user-images.githubusercontent.com/12501091/191500569-99a4659e-3494-432b-a592-bf30c1f99de7.png)
> > > > > Should it start that way or have a capital letter?
> > > > > Thanks!
> > > > > there is no space for 2 words "points" (точки) or (т.) What points is this "hit poins"? Еxperience points ?
> > > 
> > > 
> > > They are "Life points", I guess. This is is the only place it appears: ![image](https://user-images.githubusercontent.com/12501091/191503698-84d11f14-eaf6-4451-895f-e1cdb986c197.png)
> > > There should be enough space, no?
> > > Meanwhile HP appears here: ![image](https://user-images.githubusercontent.com/12501091/191504100-a25578bb-5627-4e6c-ba80-4895731c1692.png)
> > 
> > 
> > "Life points" and "HP" (health points) are the same yes i note this. Ok I will translate both positions - "Life" in Bulgarian "Живот". This is sufficient explanation in Bulgarian.
> 
> here translation not working in my opinion! ![image](https://user-images.githubusercontent.com/12934196/191510349-85114dfb-77f4-450c-9cfd-ba4b2bcd8903.png)

I translated this but .... Nothing hapens

2022-09-21 13:03 UTC, Effektus commented
> > > > > > Hi @Effektus,
> > > > > > I left some minor comments. Also when checking the bg.po in poedit I found this string to have a comment:
> > > > > > ![image](https://user-images.githubusercontent.com/12501091/191500569-99a4659e-3494-432b-a592-bf30c1f99de7.png)
> > > > > > Should it start that way or have a capital letter?
> > > > > > Thanks!
> > > > > > there is no space for 2 words "points" (точки) or (т.) What points is this "hit poins"? Еxperience points ?
> > > > 
> > > > 
> > > > They are "Life points", I guess. This is is the only place it appears: ![image](https://user-images.githubusercontent.com/12501091/191503698-84d11f14-eaf6-4451-895f-e1cdb986c197.png)
> > > > There should be enough space, no?
> > > > Meanwhile HP appears here: ![image](https://user-images.githubusercontent.com/12501091/191504100-a25578bb-5627-4e6c-ba80-4895731c1692.png)
> > > 
> > > 
> > > "Life points" and "HP" (health points) are the same yes i note this. Ok I will translate both positions - "Life" in Bulgarian "Живот". This is sufficient explanation in Bulgarian.
> > 
> > 
> > here translation not working in my opinion! ![image](https://user-images.githubusercontent.com/12934196/191510349-85114dfb-77f4-450c-9cfd-ba4b2bcd8903.png)
> 
> I translated this but .... Nothing hapens

And how to translate this buttons and all like them?
![image](https://user-images.githubusercontent.com/12934196/191511162-0be58a20-9eeb-437f-bd27-3543062e2166.png)

2022-09-21 13:04 UTC, zenseii commented
> > > > > > > Hi @Effektus,
> > > > > > > I left some minor comments. Also when checking the bg.po in poedit I found this string to have a comment:
> > > > > > > ![image](https://user-images.githubusercontent.com/12501091/191500569-99a4659e-3494-432b-a592-bf30c1f99de7.png)
> > > > > > > Should it start that way or have a capital letter?
> > > > > > > Thanks!
> > > > > > > there is no space for 2 words "points" (точки) or (т.) What points is this "hit poins"? Еxperience points ?
> > > > > 
> > > > > 
> > > > > They are "Life points", I guess. This is is the only place it appears: ![image](https://user-images.githubusercontent.com/12501091/191503698-84d11f14-eaf6-4451-895f-e1cdb986c197.png)
> > > > > There should be enough space, no?
> > > > > Meanwhile HP appears here: ![image](https://user-images.githubusercontent.com/12501091/191504100-a25578bb-5627-4e6c-ba80-4895731c1692.png)
> > > > 
> > > > 
> > > > "Life points" and "HP" (health points) are the same yes i note this. Ok I will translate both positions - "Life" in Bulgarian "Живот". This is sufficient explanation in Bulgarian.
> > > 
> > > 
> > > here translation not working in my opinion! ![image](https://user-images.githubusercontent.com/12934196/191510349-85114dfb-77f4-450c-9cfd-ba4b2bcd8903.png)
> > 
> > 
> > I translated this but .... Nothing hapens
> 
> And how to translate this buttons and all like them? ![image](https://user-images.githubusercontent.com/12934196/191511162-0be58a20-9eeb-437f-bd27-3543062e2166.png)

Currently these buttons cannot be translated, but work is being done towards making that possible. Only a few buttons are translateable so far, and they only support the Latin alphabet for the moment.

2022-09-21 13:08 UTC, zenseii commented
> > > > > Hi @Effektus,
> > > > > I left some minor comments. Also when checking the bg.po in poedit I found this string to have a comment:
> > > > > ![image](https://user-images.githubusercontent.com/12501091/191500569-99a4659e-3494-432b-a592-bf30c1f99de7.png)
> > > > > Should it start that way or have a capital letter?
> > > > > Thanks!
> > > > > there is no space for 2 words "points" (точки) or (т.) What points is this "hit poins"? Еxperience points ?
> > > 
> > > 
> > > They are "Life points", I guess. This is is the only place it appears: ![image](https://user-images.githubusercontent.com/12501091/191503698-84d11f14-eaf6-4451-895f-e1cdb986c197.png)
> > > There should be enough space, no?
> > > Meanwhile HP appears here: ![image](https://user-images.githubusercontent.com/12501091/191504100-a25578bb-5627-4e6c-ba80-4895731c1692.png)
> > 
> > 
> > "Life points" and "HP" (health points) are the same yes i note this. Ok I will translate both positions - "Life" in Bulgarian "Живот". This is sufficient explanation in Bulgarian.
> 
> here translation not working in my opinion! ![image](https://user-images.githubusercontent.com/12934196/191510349-85114dfb-77f4-450c-9cfd-ba4b2bcd8903.png)

I'm not sure how to show this string in the game.

If it's this then it works for me:

![image](https://user-images.githubusercontent.com/12501091/191512069-c0725817-f718-47c4-9302-3345555bbf63.png)


Maybe you haven't compiled the latest bg.mo that you are testing with?

2022-09-21 13:17 UTC, Effektus commented
> > > > > > Hi @Effektus,
> > > > > > I left some minor comments. Also when checking the bg.po in poedit I found this string to have a comment:
> > > > > > ![image](https://user-images.githubusercontent.com/12501091/191500569-99a4659e-3494-432b-a592-bf30c1f99de7.png)
> > > > > > Should it start that way or have a capital letter?
> > > > > > Thanks!
> > > > > > there is no space for 2 words "points" (точки) or (т.) What points is this "hit poins"? Еxperience points ?
> > > > 
> > > > 
> > > > They are "Life points", I guess. This is is the only place it appears: ![image](https://user-images.githubusercontent.com/12501091/191503698-84d11f14-eaf6-4451-895f-e1cdb986c197.png)
> > > > There should be enough space, no?
> > > > Meanwhile HP appears here: ![image](https://user-images.githubusercontent.com/12501091/191504100-a25578bb-5627-4e6c-ba80-4895731c1692.png)
> > > 
> > > 
> > > "Life points" and "HP" (health points) are the same yes i note this. Ok I will translate both positions - "Life" in Bulgarian "Живот". This is sufficient explanation in Bulgarian.
> > 
> > 
> > here translation not working in my opinion! ![image](https://user-images.githubusercontent.com/12934196/191510349-85114dfb-77f4-450c-9cfd-ba4b2bcd8903.png)
> 
> I'm not sure how to show this string in the game.
> 
> If it's this then it works for me:
> 
> ![image](https://user-images.githubusercontent.com/12501091/191512069-c0725817-f718-47c4-9302-3345555bbf63.png)
> 
> Maybe you haven't compiled the latest bg.mo that you are testing with?

![image](https://user-images.githubusercontent.com/12934196/191513809-2e757151-e004-4e1a-960a-d1ab21be3823.png)
this is here and I search this string eksaktli to translate and translate all similar strings.

2022-09-21 13:24 UTC, zenseii commented
> 

You haven't translated this. It refers to the skill:
![image](https://user-images.githubusercontent.com/12501091/191515678-db7d1ba9-e352-49f8-87b7-0a7aeabf2f16.png)

2022-09-21 15:52 UTC, zenseii commented
Hi @Effektus.

Do you need help solving the merge conflicts? It shouldn't be much since only one string was added to source.

2022-09-21 15:54 UTC, Effektus commented
> Hi @Effektus.
> 
> Do you need help solving the merge conflicts? It shouldn't be much since only one string was added to source.

Yes please

2022-09-21 16:32 UTC, Effektus commented
> > Yes please
> 
> I'll show you the way I solve them then 😊
> 
> 1. Click here:
>    ![image](https://user-images.githubusercontent.com/12501091/191554050-17e454a6-b4b7-4f02-a09e-8a4e0c675087.png)
> 2. This is the conflict:
>    ![image](https://user-images.githubusercontent.com/12501091/191554250-110c6a00-66eb-474b-bc11-40fc10329219.png)
> 3. Keep the most recent dates and remove the rest:
>    ![image](https://user-images.githubusercontent.com/12501091/191554426-53fcb85d-5562-4fdb-af47-4f5f8bfce84d.png)
> 4. Mark as solved:
>    ![image](https://user-images.githubusercontent.com/12501091/191554487-a7b11de2-79fe-4bda-b03c-1b2a71f8bd4d.png)
> 5. Press Commit merge:
>    ![image](https://user-images.githubusercontent.com/12501091/191554604-b02064f6-15b6-498f-886f-9c657c259404.png)

![image](https://user-images.githubusercontent.com/12934196/191560693-5a1b40fa-e72e-4e27-aa62-1acf0f78106f.png)

2022-09-21 16:38 UTC, zenseii commented
> ![image](https://user-images.githubusercontent.com/12934196/191560693-5a1b40fa-e72e-4e27-aa62-1acf0f78106f.png)

That is weird since you are allowed to commit to this PR since it is yours and doing what I described is just another way of merging a commit to this PR that you are the publisher of, and I was able to resolve conflicts myself before I became a contributor so unless something has changed since then it should be possible for you as well.

Anyways I'll solve it for this time.

2022-09-21 16:55 UTC, zenseii reviewed
Hi @Effektus,
I left one small comment. Please have a look when you should feel at ease to.

2022-09-21 16:55 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Изразходване на точките живот"
Deepl makes this sound like you are spending life points. If this is wrong then just disregard this.
This is the ability of vampire lords in which they "suck the HP points" from creatures to get life. If your translation fits with this then don't mind this.

2022-09-21 18:25 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Изразходване на точките живот"
Fixed thaks for explanation

2022-09-21 20:00 UTC, zenseii approved these changes

2022-09-22 15:21 UTC, ihhub commented on files/lang/bg.po
> +msgstr "Osnowen"
Are we sure that this is the correct translation? I think it's bulgarian but written in Latin :)

2022-09-22 16:32 UTC, zenseii requested changes
Hi @Effektus ,
I noticed another similar issue that you might want to have a look at.

2022-09-22 18:16 UTC, zenseii approved these changes

2022-09-22 21:35 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Бирма бръснене."
This Burma shave shouldn't be translated literally since it refers to a type of old ad from the US that were placed on ad signs along roads.
https://commons.wikimedia.org/wiki/File:BurmaShaveSigns_Route66.jpg

Since the intent here is to have something funny written on a random sign in the game, you're a bit free to come up with something humerous, but that can't be offensive or commit any trademark issues etc.

2022-09-22 21:44 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Гореща седалка"
I have a slight suspicion that this is translated directly as a "seat that is hot/warm"? It can also be called Hotseat in one word in English:
https://en.wikipedia.org/wiki/Hotseat_(multiplayer_mode)

This is the multiplayer game mode where you play on the same PC and "take turns/rotate between whos playing", this way the seat is kept hot because someone is always sitting there.

2022-09-22 21:44 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Поздравления!"
DeepL translates this as "Congratulations". Not sure if this is correct by Deepl, if it isn't then just ignore this. Anyways this is the header of the dialog you are presented with the first time you start the game and is as it says a greetings or a hello/welcome.

2022-09-22 21:57 UTC, zenseii commented
Hi @Effektus,

I think we have enough changes within this PR now so after you've addressed these last comments of mine and gotten an approval we can go towards merging it, and then if you have more updates post them in another PR after this one is merged. This is easier for us and it shouldn't introduce any delay, but keep things more tidy.

2022-09-23 04:26 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Поздравления!"
This is good

2022-09-23 04:27 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Гореща седалка"
This is good

2022-09-23 11:07 UTC, zenseii approved these changes

2022-09-23 12:15 UTC, Effektus commented
> Hi @Effektus,
> 
> I think we have enough changes within this PR now so after you've addressed these last comments of mine and gotten an approval we can go towards merging it, and then if you have more updates post them in another PR after this one is merged. This is easier for us and it shouldn't introduce any delay, but keep things more tidy.

Sorry but how to translate this "Gems, Cr, Slf & Mer:"

2022-09-23 12:43 UTC, zenseii commented
> > Hi @Effektus,
> > I think we have enough changes within this PR now so after you've addressed these last comments of mine and gotten an approval we can go towards merging it, and then if you have more updates post them in another PR after this one is merged. This is easier for us and it shouldn't introduce any delay, but keep things more tidy.
> 
> Sorry but how to translate this "Gems, Cr, Slf & Mer:"

It is found within this screen:
![image](https://user-images.githubusercontent.com/12501091/191962679-29641b4b-b862-45be-94b5-1a69c26968a7.png)


They are abbreviations for Gems, Crystal, Sulfur & Mercury as you can see the space is limited.

2022-09-23 15:48 UTC, merged

2022-09-23 15:49 UTC, ihhub commented
@Effektus thank you so much for keeping the translation up to date!