fixed CreateDirectoryA for win and msc & icn ICNHeader signed offsets
ihhub/fheroes2 pull request #5867
Opened 2022-09-21 16:23 UTC by tarboss

2022-09-22 15:18 UTC, ihhub requested changes
Hi @tarboss , I put several comment in this pull request. Could you please take a look?

2022-09-22 15:18 UTC, ihhub commented on src/tools/icn2img.cpp
> +            std::cout << "Image " << ii + 1 << " has offset of [" << static_cast<int16_t>( head.offsetX ) << ", " << static_cast<int16_t>( head.offsetY ) << "]"
There is not reason then to have this casting as it is redundant. Please remove it.

2022-09-22 15:18 UTC, ihhub commented on src/engine/system.cpp
> +    bool createDir = CreateDirectoryA( path.c_str(), nullptr );
The return value of this function is `BOOL`, not `bool`. Also this variable should be `const`.

2022-09-22 15:18 UTC, ihhub commented on src/engine/system.cpp
> +    return !createDir; // makedir compatible now!
We are casting here from bool to integer. While it is still valid I think for better understanding it is good to do like this:
```cpp
// CreateDirectoryA returns 0 in case of failure and nonzero in case of success.
if ( returnValue == 0 ) {
    ERROR_LOG( "Unable to create a directory. Error: " << getLastErrorStr() )
   return -1;
}

return 0;
````

So we need to create a separate function in anonymous namespace at the top of this file with a body which is present in `getLastErrorStr` lambda function to be used in multiple functions.

2022-09-22 15:18 UTC, ihhub commented on src/engine/agg_file.h
> +        int16_t offsetX;
There is another place where we need to remove casting after changing the type:
```cpp
= decodeICNSprite( data, sizeData, header1.width, header1.height, static_cast<int16_t>( header1.offsetX ), static_cast<int16_t>( header1.offsetY ) );
```

2022-09-22 15:54 UTC, tarboss commented on src/engine/system.cpp
> +    bool createDir = CreateDirectoryA( path.c_str(), nullptr );
yes, but read this:
https://stackoverflow.com/questions/6420526/what-is-the-difference-between-bool-and-bool
(11 years old)
- bool is a built-in C++ type 
- BOOL is a Microsoft specific type int
- const make the line even longer

2022-09-22 15:55 UTC, tarboss commented on src/tools/icn2img.cpp
> +            std::cout << "Image " << ii + 1 << " has offset of [" << static_cast<int16_t>( head.offsetX ) << ", " << static_cast<int16_t>( head.offsetY ) << "]"
i remove the cast complete

2022-09-22 15:57 UTC, ihhub commented on src/engine/system.cpp
> +    bool createDir = CreateDirectoryA( path.c_str(), nullptr );
Hi @tarboss , I'm fully aware about this difference and I'm pointing it out that this variable must be `BOOL` aka `int` as this is the value what the function returns. It is always important to avoid implicit conversion of types.

`const` marks that the variable is not modifiable. This is present in most of our code base.

2022-09-22 15:58 UTC, tarboss commented on src/engine/system.cpp
> +    return !createDir; // makedir compatible now!
no fan of lambda, i wana go small steps

2022-09-22 15:59 UTC, tarboss commented on src/engine/system.cpp
> +    bool createDir = CreateDirectoryA( path.c_str(), nullptr );
okay chief

2022-09-22 15:59 UTC, ihhub commented on src/engine/system.cpp
> +    return !createDir; // makedir compatible now!
I did **not** ask to create a lambda function, I asked transform existing one into a normal function.

2022-09-22 16:01 UTC, tarboss commented on src/engine/system.cpp
> +    bool createDir = CreateDirectoryA( path.c_str(), nullptr );
const BOOL createDir = CreateDirectoryA( path.c_str(), nullptr );

2022-09-22 16:39 UTC, tarboss commented on src/engine/agg_file.h
> +        int16_t offsetX;
u can do it, its in agg_image.cpp, i dont touched that file!

2022-12-17 15:18 UTC, ihhub commented
Closing this pull request as most of work was completed in a separate pull request recently.

2022-12-17 15:18 UTC, closed without merging