UI improvements of the Settings dialog
ihhub/fheroes2 pull request #5868
Opened 2022-09-22 01:17 UTC by zenseii

This changes the settings dialog to allow for double-lined headers and subtexts.
Several strings are adjusted.

Relates to https://github.com/ihhub/fheroes2/issues/5244

![image](https://user-images.githubusercontent.com/12501091/191636391-cdbe8d7b-961f-41b8-8632-700022c5e1bd.png)

![image](https://user-images.githubusercontent.com/12501091/191636555-d2ceeafd-65a9-405c-afc6-0994ca18440e.png)

Whatever issues there are with overlapping texts now should be no problem to solve for the translators.

2022-09-22 15:11 UTC, ihhub requested changes
Hi @zenseii , I left several comment here. Would you mind to take a look at them?

2022-09-22 15:11 UTC, ihhub commented on src/fheroes2/dialog/dialog_game_settings.cpp
> +    const fheroes2::Point textOffset = { 11, 12 };
`const fheroes2::Point textOffset{ 11, 12 };` will do even better.

2022-09-22 15:11 UTC, ihhub commented on src/fheroes2/dialog/dialog_game_settings.cpp
> +        const int16_t textMaxWidth = 87;
Is there a reason why we need to use `int16_t` over `int32_t`?

2022-09-22 15:11 UTC, ihhub commented on src/fheroes2/dialog/dialog_game_settings.cpp
> +                    body( _( "Toggle colored cursor on or off. The colored cursor looks nicer, but sometimes it does not move as smoothly as a black and white one." ),
Actually this statement is not true at all. I think we need to remove the last sentence as from performance point of view both cursor types behave the same.

2022-09-22 15:58 UTC, zenseii commented on src/fheroes2/dialog/dialog_game_settings.cpp
> +                    body( _( "Toggle colored cursor on or off. The colored cursor looks nicer, but sometimes it does not move as smoothly as a black and white one." ),
Haha, I always thought this last statement was meant as a joke, but yeah we can easily remove it.

2022-09-22 16:09 UTC, zenseii commented on src/fheroes2/dialog/dialog_game_settings.cpp
> +    const fheroes2::Point textOffset = { 11, 12 };
Thanks!

2022-09-23 08:12 UTC, ihhub commented on src/fheroes2/dialog/dialog_game_settings.cpp
> +                fheroes2::Text body( _( "Change the language of the game." ), fheroes2::FontType::normalWhite() );
I think for all sentences at lines 108, 275, 281, 287 and in `dialog_resolution.cpp` file, line 107 we have to manually update translation files, otherwise every translation will be lost. These changes are specific only to English so we shouldn't redo translations for other languages.

2022-09-23 08:45 UTC, zenseii commented on src/fheroes2/dialog/dialog_game_settings.cpp
> +                fheroes2::Text body( _( "Change the language of the game." ), fheroes2::FontType::normalWhite() );
Sure! They shouldn't be many languages that have this translated anyways.

2022-09-28 15:56 UTC, ihhub commented
Hi @zenseii , is this pull request ready for re-review?

2022-09-28 16:00 UTC, zenseii commented
Hi, @ihhub .
Yes, sorry I completely forgot about this one.

2022-09-28 16:05 UTC, ihhub approved these changes

2022-09-28 16:05 UTC, merged

2022-09-28 16:05 UTC, ihhub commented
@zenseii , thank you so much for these changes!