Add a feature to give human player control to AI
ihhub/fheroes2 pull request #5879
Opened 2022-09-25 09:24 UTC by ihhub

This feature is very useful for checking AI behavior and testing maps. All suggestions are welcome. including those making it as a debug build only option.

2022-09-25 09:43 UTC, ihhub commented
Hi @oleg-derevenetz , @idshibanov , @zenseii and @Branikolog , I would like to know your opinion about this feature.

2022-09-25 12:31 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left one question, please take a look when you have time. This feature looks useful indeed, but I suggest to enable it only on debug builds (maybe also check for `IS_DEVEL()`).

2022-09-25 12:31 UTC, oleg-derevenetz commented on src/fheroes2/system/players.h
> +    CONTROL_AI = 4
Why not sort them here by value, just like in other places?

2022-09-25 12:32 UTC, ihhub commented on src/fheroes2/system/players.h
> +    CONTROL_AI = 4
Oops, I missed. The intention was exactly to sort.

2022-09-25 12:33 UTC, ihhub commented on src/fheroes2/system/players.h
> +    CONTROL_AI = 4
Fixed!

2022-09-25 14:08 UTC, zenseii commented
Hi, @ihhub and @oleg-derevenetz,

I think this is a huge addition and will help speed up the development of the AI greatly. I also believe that in the current state of the AI it should only be available in debug mode.

In the future I think this could be a very good accessibility option for players having motorial limitations, and we've already heard a couple of fans request such a feature, however as long as there are issues like the ones @ihhub discovered, there is no reason to make this available in release builds.

One thing I noticed is that when you want to end AI mode it only gets into effect the next turn and doesn't immediately hand control over to you.

Here's a vid showcasing it although after asking to regain control the human player is in control whenever a castle is visited:
<details>

https://user-images.githubusercontent.com/12501091/192147772-c1846532-764a-482d-871a-47f3621b3fe0.mp4

</details>


Another thing is that any battle will be shown when the AI is in control, and this might be nice to be able to auto-resolve.

2022-09-25 14:11 UTC, ihhub commented
Hi @zenseii , I intentionally enable all battles to see how AI behaves. Since at least 2 people express concerns not to include this feature into release build I shall do it.

2022-09-25 14:14 UTC, zenseii commented
> Hi @zenseii , I intentionally enable all battles to see how AI behaves. Since at least 2 people express concerns not to include this feature into release build I shall do it.

Yes I can see it being very useful. My idea was just that when working on improving the AI you might be focusing on just the adventure map logic of the AI and not both battle and adventure map at the same time. There are cases where you could want this and cases where you don't want it.

2022-09-25 14:22 UTC, zenseii requested changes
I also left this small text adjustment. Please have a look.

2022-09-25 14:22 UTC, zenseii commented on src/fheroes2/game/game_startgame.cpp
> +                                            fheroes2::Text( _( "Do you want to transfer control from you into AI?" ), fheroes2::FontType::normalWhite() ),
```suggestion
                                            fheroes2::Text( _( "Do you want to transfer control from you to the AI?" ), fheroes2::FontType::normalWhite() ),
```

2022-09-25 14:22 UTC, ihhub commented
Hi @zenseii and @oleg-derevenetz , I made this for debug build as of now.

2022-09-25 14:33 UTC, Branikolog commented
Hi!

> this might be nice to be able to auto-resolve.

True. Could it work according to the selected battle mode in options? Or would it be better to initiate battle skip by "Q" button right during AI fight?

2022-09-25 14:44 UTC, ihhub commented
Hi @zenseii , I updated and expanded the  description. Please take a look.

2022-09-25 14:45 UTC, ihhub commented
Hi @zenseii and @Branikolog , as this is only for debug mode we can leave battles as it is. We still have some issues with battles so it is better to show them for this mode.

2022-09-25 14:46 UTC, Branikolog commented
@ihhub 
I've noticed, that after cancelling the AI mode, game shows all dialog windows and you need to click them all to proceed.

2022-09-25 14:47 UTC, ihhub commented
Hi @Branikolog , I am aware of this and that's why I accepted to move it only for debug build.

2022-09-25 14:53 UTC, zenseii requested changes

2022-09-25 14:53 UTC, zenseii commented on src/fheroes2/game/game_startgame.cpp
> +                                      fheroes2::Text( _( "Do you want to transfer control from you into the AI? The effect will take place only on the next turn." ),
The use of "into" is not correct here.
```suggestion
                                      fheroes2::Text( _( "Do you want to transfer control from you to the AI? The effect will take place only on the next turn." ),
```

2022-09-25 14:54 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +                                      fheroes2::Text( _( "Do you want to transfer control from you into the AI? The effect will take place only on the next turn." ),
Ah, yes. I missed it.

2022-09-25 14:59 UTC, zenseii approved these changes

2022-09-25 17:09 UTC, oleg-derevenetz approved these changes

2022-09-25 18:57 UTC, idshibanov approved these changes
Great change, will help out a ton

2022-09-25 23:06 UTC, zenseii commented
Another great way of using this is to make a multiplayer game with a some human players and then give AI control of all of them. This way you can take control of different AI players on the same map at any point.

2022-09-25 23:12 UTC, zenseii reviewed
Hi, @ihhub.

I believe some text was placed in the wrong dialog. Please have a look when you have the time to.

2022-09-25 23:12 UTC, zenseii commented on src/fheroes2/ai/ai_hero_action.cpp
> +                                                fheroes2::Text( _( "Do you want to regain control from AI?" ), fheroes2::FontType::normalWhite() ),
I believe the text below was intended to be in this dialog since it's the regaining of the control which happens on the next turn.
`The effect will take place only on the next turn.`
```suggestion
                                                fheroes2::Text( _( "Do you want to regain control from AI? The effect will take place only on the next turn." ), fheroes2::FontType::normalWhite() ),
```

2022-09-25 23:12 UTC, zenseii commented on src/fheroes2/game/game_startgame.cpp
> +                                            fheroes2::Text( _( "Do you want to transfer control from you to the AI? The effect will take place only on the next turn." ),
Related to the above comment: the AI takes control immediately, not the next turn.
```suggestion
                                            fheroes2::Text( _( "Do you want to transfer control from you to the AI?" ),
```

2022-09-26 09:04 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +                                            fheroes2::Text( _( "Do you want to transfer control from you to the AI? The effect will take place only on the next turn." ),
It is on the next turn. Please check this video:

https://user-images.githubusercontent.com/19829520/192236982-848c8148-005a-493c-a3c2-ec748f75c78c.mp4

2022-09-26 09:33 UTC, zenseii commented on src/fheroes2/game/game_startgame.cpp
> +                                            fheroes2::Text( _( "Do you want to transfer control from you to the AI? The effect will take place only on the next turn." ),
Ah you're right. My bad then. It looked like it happened on the same day for me.

2022-09-26 12:06 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +                                            fheroes2::Text( _( "Do you want to transfer control from you to the AI? The effect will take place only on the next turn." ),
Sure. I will add an extra sentence.

2022-09-26 12:15 UTC, zenseii approved these changes

2022-09-26 12:17 UTC, merged