Add code for generating button fonts for different code pages
ihhub/fheroes2 pull request #5886
Opened 2022-09-25 22:31 UTC by zenseii

Changes:

1. Added functions that generates extra needed fonts if necessary.
2. `getCurrentLanguage()` was added to get the pass current language to button font generation.
3. A comment was changed to not make it sound like we have to write manually code for pressed state too:
`// The downside of this font is that code is necessary for the generation of released and pressed states of each letter.`
4. Minor spelling corrections in comments I discovered.
5. Generated all currently needed button letters needed for Norwegian currrently.
6. Gave a basic solution for how letters with diacritics need to be offset in y-axis, like É or Å in this case.

This relates to:
https://github.com/ihhub/fheroes2/pull/5875

2022-09-27 13:40 UTC, ihhub requested changes
Hi @zenseii , I put few comments in this pull request. Could you please take a look?

2022-09-29 00:21 UTC, zenseii commented
Hi, @ihhub.

I've written it in the proper approach now. Note that when doing this I initially thought I could get away with just preserving `ICN::BUTTON_GOOD_FONT_RELEASED` but what happened was that all pressed and the evil button fonts would get cleared as soon as a another language than English was set. 

Reapplying effects to the entire set of letters after changing alphabet, so letters 0-255, wasn't something I found a way to do since at that point the original good released button font, which the others would be generated from, would already have the effects applied to it.

Anyways this is ready for your review when you should have the time and would feel like looking at it.

2022-09-29 09:07 UTC, zenseii commented on src/fheroes2/gui/ui_font.cpp
> +        for ( size_t i = 96; i < icnVsSprite[ICN::BUTTON_GOOD_FONT_RELEASED].size(); ++i ) {
The initial thought behind using the magic number 96 here was that thr base 96 letters (0-95) in any of the code pages are always the English/Latin ones.

However, I'd prefer for the Polish font generation to be able to regenerate these letters as well to match the Polish button font. This would probably also require a different set of effects applied to the letters however.

2022-09-29 14:13 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +        for ( size_t i = 96; i < icnVsSprite[ICN::BUTTON_GOOD_FONT_RELEASED].size(); ++i ) {
Hi @zenseii , why don't we just call `generateBaseButtonFont()` function to run through all letters? This will avoid any hardcoded values as well as corner cases as Polish?

2022-09-29 14:14 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +        for ( size_t i = 96; i < icnVsSprite[ICN::BUTTON_GOOD_FONT_RELEASED].size(); ++i ) {
Ah, my bad. We're generating the code there as well... I think we can do something else...

2022-09-29 14:20 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +        for ( size_t i = 96; i < icnVsSprite[ICN::BUTTON_GOOD_FONT_RELEASED].size(); ++i ) {
Hi @zenseii , I pushed one commit to simplify your work. Please take a look.

2022-09-29 14:21 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                generateExtraButtonFont( language, _icnVsSprite );
To keep the similar naming I suggest to use `generateButtonAlphabet()`.

2022-09-29 14:38 UTC, zenseii commented on src/fheroes2/agg/agg_image.cpp
> +                generateExtraButtonFont( language, _icnVsSprite );
Yep I agree.

2022-09-29 14:45 UTC, zenseii commented on src/fheroes2/gui/ui_font.cpp
> +        for ( size_t i = 96; i < icnVsSprite[ICN::BUTTON_GOOD_FONT_RELEASED].size(); ++i ) {
Maybe it's better to preserve the released font before it has the effects applied to it?

2022-09-29 15:04 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +        for ( size_t i = 96; i < icnVsSprite[ICN::BUTTON_GOOD_FONT_RELEASED].size(); ++i ) {
How about calling `generateGoodButtonFontBaseShape();` at the start of `generateExtraButtonFont()` function? I think it solves the problem.

2022-09-29 15:06 UTC, zenseii commented on src/fheroes2/gui/ui_font.cpp
> +        for ( size_t i = 96; i < icnVsSprite[ICN::BUTTON_GOOD_FONT_RELEASED].size(); ++i ) {
Ah, of course. That's better.

2022-09-29 15:26 UTC, ihhub approved these changes

2022-09-29 15:27 UTC, zenseii commented
@ihhub, should we add the empty Code Page functions for the other languages while working on them? 
There is a clang-tidy comment about this above.

2022-09-29 15:34 UTC, ihhub commented
> @ihhub, should we add the empty Code Page functions for the other languages while working on them, or should I do it now in this PR? There is a clang-tidy comment about this above.

You can add them during your work. No need to add empty functions.

2022-09-29 15:49 UTC, merged

2022-09-29 15:49 UTC, ihhub commented
@zenseii , great job! Thanks a lot for doing this!