Hide console window for Windows build #
ihhub/fheroes2 pull request #5890
Opened 2022-09-27 15:41 UTC by 44zb

> Hide console window 
> Write logs into file, similar with Switch build

related issue #5744

2022-09-27 16:01 UTC, shprotru commented on src/engine/logging.cpp
> +#if defined( TARGET_NINTENDO_SWITCH ) || defined( _WIN32 ) || defined( _WIN32 )
```suggestion
#if defined( TARGET_NINTENDO_SWITCH ) || defined( _WIN32 ) || defined( _WIN64 )
```

2022-09-28 15:55 UTC, ihhub requested changes
Hi @44zb , I put several comments in this pull request. Could you please take a look?

2022-09-28 15:55 UTC, ihhub commented on src/engine/logging.h
> +#if defined( TARGET_NINTENDO_SWITCH ) || defined( _WIN32 ) || defined( _WIN64 )
Most of developers who work on Windows would still prefer to have the debug info being displayed in the window as it is very useful. I suggest to add this at first:
```cpp
#if defined( _WIN32 ) && defined( WITH_DEBUG )
#define COUT( x )                                                                                                                                                        \
    {                                                                                                                                                                    \
        const std::scoped_lock<std::mutex> _logfile_lock( Logging::logMutex ); /* The name was chosen on purpose to avoid name collisions with outer code blocks. */     \
                                                                                                                                                                         \
        Logging::logFile << x << std::endl;                                                                                                                              \
        Logging::logFile.flush();                                                                                                                                        \
        std::cerr << x << std::endl;                                                                                                                                     \
    }
elif #if defined( TARGET_NINTENDO_SWITCH ) || defined( _WIN32 ) <--- notice that _WIN64 is not needed as _WIN32 is always enabled for Win64 applications.
// the rest of the code
```

2022-09-28 15:55 UTC, ihhub commented on src/engine/logging.cpp
> +#if defined( TARGET_NINTENDO_SWITCH ) || defined( _WIN32 ) || defined( _WIN64 )
Please remove `defined( _WIN64 )` as it is redundant. You can read about this [here](https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?redirectedfrom=MSDN&view=msvc-170).

2022-09-28 15:55 UTC, ihhub commented on src/engine/logging.cpp
> +#elif defined( _WIN32 ) || defined( _WIN64 )
Please remove `defined( _WIN64 )` as it is redundant.

2022-09-28 15:55 UTC, ihhub commented on src/engine/logging.cpp
>          logFile.open( "fheroes2.log", std::ofstream::out );
While for Nintendo Switch all dynamically created files are within the root of the directory this is not the case for Windows. The path should be as `System::ConcatePath( System::GetConfigDirectory( "fheroes2" ), "fheroes2.log" )`.

2022-09-28 15:55 UTC, ihhub commented on src/engine/logging.cpp
>          logFile.open( "fheroes2.log", std::ofstream::out );
Did you test if it is not possible to open a file for writing? Does the application work?

2022-09-28 18:17 UTC, 44zb commented on src/engine/logging.cpp
>          logFile.open( "fheroes2.log", std::ofstream::out );
Yes, I have done some tests. With changed file rights(remove read/write permission) or if file marked as read-only application working.

But of course, log file will be empty without rights.

2022-09-29 08:47 UTC, zenseii commented
Hi, @44zb.

Would you be able to address the code style issues pointed out by the check below? Thank you!

2022-09-29 15:33 UTC, ihhub requested changes
Hi @44zb , I put 2 more comments here. Could you please take a look at them?

2022-09-29 15:33 UTC, ihhub commented on src/engine/logging.h
> +namespace Logging
Please add an extra empty line to separate header inclusions and the namespace for better code readability.

2022-09-29 15:33 UTC, ihhub commented on src/engine/logging.h
>  #include <fstream>
Please remove these header inclusions since we added them at lines 70-71.

2022-09-29 15:40 UTC, 44zb commented
@ihhub done

2022-09-29 15:41 UTC, ihhub approved these changes

2022-09-29 15:55 UTC, ihhub commented on src/engine/logging.cpp
> +        logFile.open( log_path, std::ofstream::out );
Actually, I missed this part: please make this variable const and use camelCase variable naming: `logPath`.

2022-09-29 16:01 UTC, 44zb commented on src/engine/logging.cpp
> +        logFile.open( log_path, std::ofstream::out );
done

2022-09-29 16:04 UTC, ihhub commented on src/engine/logging.cpp
> +        logFile.open( log_path, std::ofstream::out );
Good job! We need to get an approval of other reviewer before proceeding with merging this pull request as it touches the core code of the project.

2022-09-29 16:29 UTC, 44zb commented on src/engine/logging.cpp
> +#endif
I had thoughts that it is not a perfect placement for this code, but I had no idea about a better place. 
I will move it to begin of `initCoreInternally`

2022-09-29 20:30 UTC, oleg-derevenetz reviewed
Hi @44zb @ihhub I just left a comment with my concerns regarding this approach.

2022-09-30 00:16 UTC, oleg-derevenetz commented
I suggest trying a different approach: use `SDLmain.lib`/`SDL2main.lib` (to avoid `main()`/`WinMain()` torment) and also use different link options for `Debug-SDLx` and `Release-SDLx` configurations, namely:

```
<Link>
  <SubSystem>Console</SubSystem>
</Link>
```

for debug builds and

```
<Link>
  <SubSystem>Windows</SubSystem>
</Link>
```

for release builds. I did a quick try and for SDL2 this works just fine "out of the box", but there are some link errors with SDL1, maybe some quirk is needed.

2022-09-30 17:28 UTC, 44zb commented
@oleg-derevenetz So I figure out how to fix SDL1 problems. It's work for all windows build configuration as expected, but fixes for `__imp__*` may look a bit tricky

2022-09-30 19:23 UTC, oleg-derevenetz reviewed
Hi @44zb @ihhub I just left a few comments regarding @44zb approach and added my own commit with proposed changes. Please take a look.

2022-10-01 03:27 UTC, 44zb commented on src/fheroes2/game/fheroes2.cpp
> +extern "C" FILE * __cdecl __iob_func( void )
There were 3 unresolved symbols with SDL1, this one for `__imp_iob`, but now look unnecessary

2022-10-01 03:50 UTC, 44zb commented on src/fheroes2/game/fheroes2.cpp
> +INT WINAPI WinMain( HINSTANCE, HINSTANCE, PSTR, INT )
I find a few ways to fix  `__imp_setbuf ` and `__imp_freopen` symbols, and one of them is changing property Runtime Library to `Multi-threaded DLL (/MD)`, but there was a runtime error in MSVC files trying call `WinMain`.
So i decide to add `WinMain` that will just forward call to `main` and it's fixed everything.  

Now it looks like just having `WinMain` it's will fix all unresolved symbols and runtime errors without multi-threaded DLL or `_iob`

If cut everything extra, this will work for both SDL version
```cpp
#if defined( _WIN32 )

#if defined( WITH_DEBUG )
#undef main
#elif !SDL_VERSION_ATLEAST(2, 0, 0)
#include <windows.h>

int main( int, char ** );

INT WINAPI WinMain( HINSTANCE, HINSTANCE, PSTR, INT )
{
    return main( __argc, __argv );
}
#endif

#endif
```

2022-10-01 04:16 UTC, 44zb commented on src/fheroes2/game/fheroes2.cpp
> +INT WINAPI WinMain( HINSTANCE, HINSTANCE, PSTR, INT )
I create another branch with these fixes for SDL1, in case you decide to keep SDL1 as it is 
https://github.com/44zb/fheroes2/commit/e21c2e87f85734b3ddf5e0b9f8a2314455549ed0

2022-10-01 04:34 UTC, ihhub commented
Hi @44zb and @oleg-derevenetz , if fixing SDL1 takes a lot of effort I suggest not to change it at all as SDL1 will be deprecated in the future.

2022-10-01 04:35 UTC, ihhub commented on src/fheroes2/game/fheroes2.cpp
> +extern "C" FILE * __cdecl __iob_func( void )
Let's leave SDL1 as it is as it's a legacy library. It is fine to have a console window for this build, not many users download SDL1 based on statistical data.

2022-10-01 08:44 UTC, oleg-derevenetz commented on src/fheroes2/game/fheroes2.cpp
> +extern "C" FILE * __cdecl __iob_func( void )
Hi @44zb @ihhub

> I find a few ways to fix __imp_setbuf and __imp_freopen symbols, and one of them is to change property Runtime Library to Multi-threaded DLL (/MD)

That's strange, because when I tried to build fheroes2 (at least with MSVC2017) with your original changes (including this one) I still got the linker error regarding these symbols.

Implementing our own `WinMain` solely for SDL1 and throwing away the `SDLmain.lib` should help indeed with linker errors. I just added the commit regarding this, let's see how it goes.

2022-10-01 08:45 UTC, oleg-derevenetz commented
Hi @44zb @ihhub

> I find a few ways to fix __imp_setbuf and __imp_freopen symbols, and one of them is to change property Runtime Library to Multi-threaded DLL (/MD)

That's strange, because when I tried to build fheroes2 (at least with MSVC2017) with your original changes (including this one) I still got the linker error regarding these symbols.

Implementing our own `WinMain` solely for SDL1 and throwing away the `SDLmain.lib` should help indeed with linker errors. I just added the commit regarding this, let's see how it goes.

2022-10-01 12:23 UTC, oleg-derevenetz commented on src/fheroes2/game/fheroes2.cpp
> +    main( __argc, __argv );
There is a typo: in fact there should be `return main(...)`.

2022-10-02 04:48 UTC, ihhub commented
Hi @44zb and @oleg-derevenetz , I've realized that by doing this change we will kill text support feature. Maybe it's time to introduce text to speech module and use something like SAPI.

2022-10-02 07:36 UTC, oleg-derevenetz commented
Hi @ihhub

> I've realized that by doing this change we will kill text support feature. Maybe it's time to introduce text to speech module and use something like SAPI.

But the log file is still there. Can the text to speech tools read from the log file instead of the console?

2022-10-02 08:41 UTC, ihhub commented
Hi @oleg-derevenetz , I will check it with our users of this feature and come back soon with an answer.

2022-10-02 08:56 UTC, 44zb commented
Hi @oleg-derevenetz @ihhub. I add some Microsoft SAPI functionality, it can be done with something like this.
https://github.com/44zb/fheroes2/commit/f21389abd03f39ff876b038802658039092594a7

for test purposes, I replace TTS macro only for the main menu screen

2022-10-02 13:56 UTC, ihhub commented
Hi @44zb and @oleg-derevenetz , I got reply from our users and we can proceed with this pull request. We can implement SAPI integration in a separate pull request.

2022-10-02 13:58 UTC, oleg-derevenetz commented
Hi @ihhub

> I got reply from our users and we can proceed with this pull request. We can implement SAPI integration in a separate pull request.

That's good. So their tools work with the logfile just fine?

2022-10-02 14:07 UTC, ihhub commented
> Hi @ihhub
> 
> > I got reply from our users and we can proceed with this pull request. We can implement SAPI integration in a separate pull request.
> 
> That's good. So their tools work with the logfile just fine?

Yes.

2022-10-02 14:20 UTC, ihhub approved these changes

2022-10-02 14:22 UTC, ihhub commented
I tested all builds and they work fine.

2022-10-02 14:30 UTC, merged

2022-10-02 14:30 UTC, ihhub commented
@44zb , thank you so much for your contribution to the project!

2022-10-02 15:19 UTC, oleg-derevenetz commented
She said "Console is gone, but log files still here
You know I've been waiting twenty four years"
And the big limousine disappeared...