Add CP1250 button font generation
ihhub/fheroes2 pull request #5903
Opened 2022-09-29 19:21 UTC by zenseii

This generates letters for the Polish alphabet.
Only Ś and Ć are made, the rest are replaced with their closest Latin couterparts.

![image](https://user-images.githubusercontent.com/12501091/193123113-e9b59569-6527-4507-9555-9c526cb1d251.png)

2022-09-30 01:12 UTC, ihhub requested changes
Hi @zenseii , I put several comments here. Would you mind to take a look at them in your spare time?

2022-09-30 01:12 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +    void generateGoodCP1250ButtonFont( std::vector<fheroes2::Sprite> & released )
Please add an empty line before this function to have a visual separation of functions.

2022-09-30 01:12 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +    void generateGoodCP1251ButtonFont( std::vector<fheroes2::Sprite> & released )
Please add an empty line before this function to have a visual separation of functions.

2022-09-30 01:12 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
>      void generateGoodCP1252ButtonFont( std::vector<fheroes2::Sprite> & released )
Please add an empty line before this function to have a visual separation of functions.

2022-09-30 01:12 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +            generateGoodCP1250ButtonFont( icnVsSprite[ICN::BUTTON_GOOD_FONT_RELEASED] );
To keep naming the same I propose to use `generateCPXXXGoodButtonFont()` as we did for `generateBaseButtonFont()`.

2022-09-30 01:12 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +            fheroes2::Sprite temp = fheroes2::Flip( released[168], true, false );
I will add an overloaded version of `Flip()` function to avoid this way of doing thigs.

2022-10-01 04:53 UTC, ihhub commented
Hi @zenseii , is this pull request ready for review?

2022-10-01 05:02 UTC, zenseii commented
@ihhub, this PR can be review now or when the checks have finished, and of course when you should feel like doing it.

2022-10-01 06:19 UTC, ihhub approved these changes

2022-10-01 06:19 UTC, merged

2022-10-01 06:19 UTC, ihhub commented
@zenseii , a bunch of thanks for improving this part of the code!