Add proper icons for Petrification spell
ihhub/fheroes2 pull request #5907
Opened 2022-09-30 14:47 UTC by ihhub

Petrification spell had a very ugly mini icon and no icon for the spell itself. This is how it looks in monster info dialog:
![image](https://user-images.githubusercontent.com/19829520/193295965-da619bac-b6b5-47c5-a1bb-e4ef797f6c60.png)

and spell information window:
![image](https://user-images.githubusercontent.com/19829520/193296090-d7cab9a0-0d0d-48c7-8acc-fd93effc679e.png)

The whole art work was done by @1GodRage

close #4336

2022-09-30 15:26 UTC, zenseii requested changes
The rest of the code looks great so I only have this small comment to add.

2022-09-30 15:26 UTC, zenseii commented on src/fheroes2/agg/agg_image.cpp
> +                // Petrification spell does not have its icon in the original game.
```suggestion
                // The Petrification spell does not have its own icon in the original game.
```

2022-09-30 15:28 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                // Petrification spell does not have its icon in the original game.
Fixed.

2022-09-30 19:52 UTC, oleg-derevenetz approved these changes

2022-10-01 01:58 UTC, merged

2022-10-01 10:44 UTC, LeHerosInconnu commented
Hello @ihhub,

Why choose icons with different postures for the same spell?
All the other spells have the same icons at different sizes.

There is also a smaller icon, but it is not yet used in fheroes2:
In original game (with the sprite corrected):
![Medusa stone effect 02](https://user-images.githubusercontent.com/43583994/136420955-d0832b7c-cd7c-49d1-9f64-fa8a16e16073.png)

2022-10-01 11:17 UTC, ihhub commented
Hi @LeHerosInconnu , the problem is that the original size icon is too wide so we had to use slightly different posture to keep a square proportion of the icon.

Yes, we don't use micro-icons anywhere in fheroes2.

2022-10-01 11:26 UTC, ihhub commented
@LeHerosInconnu , I believe we can improve it later. I see no issues not doing it.

2022-10-01 11:27 UTC, LeHerosInconnu commented
@ihhub.

> Hi @LeHerosInconnu , the problem is that the original size icon is too wide so we had to use slightly different posture to keep a square proportion of the icon.

Why not also adjust the sprite position of the largest icon to be similar to the medium sized icon then? :)

> Yes, we don't use micro-icons anywhere in fheroes2.

Is this not planned in the future?

> @LeHerosInconnu , I believe we can improve it later. I see no issues not doing it.

Okay.

2022-10-01 11:29 UTC, ihhub commented
@LeHerosInconnu , after looking at both sprites I realized that we can adjust sword's position a bit on the large image and leg position and sword on the smaller icon. I am sure we can do something even better than we have right now!

2022-10-01 11:29 UTC, Branikolog commented
Hi, @LeHerosInconnu 
There're some original icons, which are different:
![image](https://user-images.githubusercontent.com/55348946/193407371-9d4a1a86-83ca-4de9-bb46-c78d47c52088.png)
![image](https://user-images.githubusercontent.com/55348946/193407378-44ebd7a2-96de-4c86-aa42-d0aef1cf9431.png)
Look at the sword of "Haste" spell.

2022-10-01 11:36 UTC, LeHerosInconnu commented
Hello @Branikolog.

> Hi, @LeHerosInconnu There're some original icons, which are different: ![image](https://user-images.githubusercontent.com/55348946/193407371-9d4a1a86-83ca-4de9-bb46-c78d47c52088.png) ![image](https://user-images.githubusercontent.com/55348946/193407378-44ebd7a2-96de-4c86-aa42-d0aef1cf9431.png)
Look at the sword of "Haste" spell.

Yes, it's true.
But the general allure remains the same, only the sword has been shortened. :)