Update ro.po - add translations to file
ihhub/fheroes2 pull request #5909
Opened 2022-09-30 17:03 UTC by zghp

Translated until line 725

2022-09-30 19:04 UTC, zenseii requested changes
Hi, @zghp !

Thank you so much for this contribution. This translation is very well made and I only found one small mistake that if you have the time and want to it would be great if you could take a look at.

Don't hesitate to ask if you have any doubts.

2022-09-30 19:04 UTC, zenseii commented on files/lang/ro.po
> +msgstr "armată|Câțiva"
The part before the `|` needs to be left in its untranslated English because this is only there to give context and distinguish it from similar text elsewhere in the code, and it will actually be removed before shown in the game.

In other words the correct way to translate this would be:
```suggestion
msgstr "Câțiva"
```

Could you also correct this for the other lines below please?

2022-09-30 23:56 UTC, zenseii requested changes
Hi @zghp.

I left some more comments. It'd be great if you could have a look at them. Thanks!

2022-09-30 23:56 UTC, zenseii commented on files/lang/ro.po
> +msgstr "CADOU"
This translation seems to be "a gift" or "a present". The button this text appears on refers to "to gift" or "to give". You use it to open the dialog where you can send/give/gift resources to other players.

2022-09-30 23:56 UTC, zenseii commented on files/lang/ro.po
> +msgstr "O haită de"
The reason we have two instances of "Pack", "Lots" etc. is because they appear in different places. In this case in this window which has limited space between creatures and that's why in English it is written as "Pack" and not "A pack of".

Would "Haită" work?

Also this is relevant for the other strings of this `army|` context too.

![image](https://user-images.githubusercontent.com/12501091/193370215-3619558e-3bac-428a-8513-fe9a00241002.png)

2022-10-01 00:15 UTC, zenseii commented
Also, @zghp, could you please change the PR title to something more intuitive like "Add Romanian translation" or similar?
Thanks!

2022-10-01 16:42 UTC, zghp commented on files/lang/ro.po
> +msgstr "O haită de"
Made the requested changes -- one thing to notice, for "mai multe" and "extrem de multe" I couldn't find a better and shorter translation yet, everything that I could think of so far would change the meaning. What I can do is make  'army|zounds' as "O, Doamne!" maybe but for monsters it should be left as "extrem de multi". 

Please let me know what you think:)

2022-10-01 16:48 UTC, zenseii commented on files/lang/ro.po
> +msgstr "O haită de"
Hi @zghp,

I think these pictures describe best what the problem is:
![image](https://user-images.githubusercontent.com/12501091/193419595-545af0a3-7ffd-4513-8847-aacac0a4f128.png)
![image](https://user-images.githubusercontent.com/12501091/193419635-9537c197-823b-4a75-a6c9-088019f5aaf3.png)


Currently we have no way of enlarging these dialogs so preferrably these strings should be max 8 characters long.

2022-10-01 16:53 UTC, zenseii commented on files/lang/ro.po
> +msgstr "O haită de"
As for having different for army versus wandering creatures, I'm not sure if it is good from a player perspective since they would have to remember that those terms describe the same quantity.

In English they are:

Few - 1-4
Several - 4-9
Band  - 10-19
Lots - 20-49
Horde - 50-99
Throng - 100-249 
Legion - 250-499
Zounds - 500-999
Swarm - 1000++

2022-10-01 16:56 UTC, zenseii commented on files/lang/ro.po
> +msgstr "O haită de"
In the worst case we can do like in the French translation and just have quantities written out in numbers like `(1 - 4)` for armies and use text for wandering creatures. This had to be done because no short enough words were found.

This would therefore remain like this (ignore the fact that I haven't implemented all the special characters yet):
![image](https://user-images.githubusercontent.com/12501091/193419980-3c1b6f23-d7f7-4dd5-b1bc-9373d6a5f6a5.png)

2022-10-01 23:28 UTC, zenseii commented on files/lang/ro.po
> +msgstr "O haită de"
I've looked over your entire PR now and the only part that remains are these two strings that are too long. Leave a comment or re-request a review once you want me to take a look at it again.

It is up to you to decide which approach we take for this problem.

2022-10-02 22:02 UTC, zenseii commented on files/lang/ro.po
> +msgstr "O haită de"
I saw that finding an expression that fits is tough for this one. One example of a more modern English variant is "Yikes!" which conveys the same idea as "Zounds" should do, as you can see in the picture below. Yes in English "Zounds of peasants" makes just as much sense as "Yikes of peasants", but that's part of the underlying joke. Like "OMGs of peasants". I guess "Oof!" would be even more modern. It doesn't have to be a literal translation as long as the meaning is sort of preserved. In other words, I'd be surprised if there's a euphemism in Romanian that stems from "God's wounds" just like Zounds originally does.

![image](https://user-images.githubusercontent.com/12501091/193478176-94ed1c2f-1ba0-4dda-8168-1ffef95ba612.png)

And yes, any experienced Heroes player would go "Yikes!" if they saw such a high number of those troops.

2022-10-03 01:53 UTC, ihhub commented
Hi @zghp , I fixed merge conflict for you.

2022-10-03 09:03 UTC, ihhub approved these changes
Hi @zghp , the changes look good to me.

2022-10-03 19:28 UTC, zghp commented
replaced the army[zounds, swarm, legion, etc.. ] with the equivalent numerals for now as i couldn't find appropriate translations that would also be sort of equal in length (otherwise they would look bad displayed on a player's screen)

2022-10-03 19:55 UTC, zenseii commented
> Hi, replaced the army[zounds, swarm, legion, etc.. ] with the equivalent numerals for now as i couldn't find appropriate translations that would also be sort of equal in length (otherwise they would look bad displayed on a player's screen)

Don't worry about it! Could you please add parentheses around the numbers? Ex. (1-4) . This will look better in game because the numbers will be properly separated.

2022-10-03 19:59 UTC, zghp commented
fixed it:)

2022-10-03 20:07 UTC, zenseii approved these changes
Hi @ihhub.

This PR is ready for your review.

Note that numbers were chosen for the same reason as the official French translation, i.e. no word short enough could be found at this moment.

2022-10-04 12:01 UTC, merged

2022-10-04 12:01 UTC, ihhub commented
@zghp , thank you so much for your contribution to the project!