Added turkish translation
ihhub/fheroes2 pull request #5910
Opened 2022-09-30 17:13 UTC by Bedovan

translated until line 733, with a few empty strings left for later

2022-10-01 13:35 UTC, zenseii requested changes
Hi, @Bedovan.

I've done the first review of your PR and noticed just some minor format and typos.

Could you please have a look at them when you have the time and feel like it? 

Thank you!

2022-10-01 13:35 UTC, zenseii commented on files/lang/tr.po
> +msgstr "MİNİMUM"
The size of this button fits around 3 letters:
![image](https://user-images.githubusercontent.com/12501091/193411566-8f1ae2f7-0a5f-4edd-a6fe-4028e277cde7.png)

2022-10-01 13:35 UTC, zenseii commented on files/lang/tr.po
> +msgstr "SADECE SAVAŞ"
I would suggest to add the `\n` to force a line break because the white space will slightly mess with the centering of this text on that button.

2022-10-01 13:35 UTC, zenseii commented on files/lang/tr.po
> +msgstr "ordu|Birkaç"
The `army|` or any string with `something|` should not be translated nor brought into the translation. They will never be shown directly in the game and serve only the purpose of differentiating them from other strings with the same exact text.
The correct translation would be this:
```suggestion
msgstr "Birkaç"
```

Could you please do the same for all the other strings of this type?

2022-10-01 13:35 UTC, zenseii commented on files/lang/tr.po
> +msgstr "%{name}  orduları birleştir"
Please remove the extra white space after ther curly bracket.

2022-10-01 13:35 UTC, zenseii commented on files/lang/tr.po
> +msgstr "%{name2} 'ı   %{name} ile değiştir"
Please remove the extra white spaces.

2022-10-01 13:35 UTC, zenseii commented on files/lang/tr.po
> +msgstr "Savaş cesareti için  %{name}  %{exp} tecrübe kazandı."
Please remove the two extra white spaces

2022-10-01 13:35 UTC, zenseii commented on files/lang/tr.po
> +msgstr "%{name}düşmana teslim oldu, ve utanç içinde ayrıldı."
Should there be a white space after the name?

2022-10-01 13:35 UTC, zenseii commented on files/lang/tr.po
> +msgstr "Büyü Puanları"
I don't know the rules in Turkish, but just as a note you don't have to use the same uppercasing of both words as in the English language, if this is more correct to do this in Turkish. This is completely up to you.

2022-10-01 13:35 UTC, zenseii commented on files/lang/tr.po
> +msgstr "%{attacker}''ın laneti %{target}'in üzerine geldi!"
Should there be two `''` here?

2022-10-01 13:35 UTC, zenseii commented on files/lang/tr.po
> +msgstr "%{name}  %{count}Okçu gücüyle ateş ediyor"
please remove the extra white space here. Also should there be a white space after %{count}?

2022-10-01 22:19 UTC, zenseii requested changes
Hi, @Bedovan!

I've looked over all of your changes and it looks very good. I just found one very small thing that I hope you can take a look at 😊

2022-10-01 22:19 UTC, zenseii commented on files/lang/tr.po
> +"SADECE \n"
There seems to be a white space still here 😅
```suggestion
"SADECE\n"
```

2022-10-03 09:38 UTC, Bedovan commented on files/lang/tr.po
> +"SADECE \n"
im gonna fix that asap haha

2022-10-06 07:04 UTC, zenseii approved these changes
I've checked this and it looks good @ihhub.

2022-10-06 10:36 UTC, merged

2022-10-06 10:37 UTC, ihhub commented
@Bedovan , thank you so much for your contribution to the project!