Do not ask Player's name if the score is too low for High score board
ihhub/fheroes2 pull request #5912
Opened 2022-10-01 06:08 UTC by ihhub

close #5892

2022-10-01 09:24 UTC, oleg-derevenetz approved these changes

2022-10-01 09:24 UTC, oleg-derevenetz commented on src/fheroes2/game/game_highscores.cpp
> +            assert( !campaignHighscoreData.empty() );
I hope that there are no players left with `hgs` files created long ago and therefore empty :)

2022-10-01 12:32 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +            assert( !campaignHighscoreData.empty() );
Hi @oleg-derevenetz , I think we need to expand `HighScoreDataContainer::load()` method to exclude this case. I can do it in this pull request or separate one.

2022-10-01 12:50 UTC, oleg-derevenetz commented on src/fheroes2/game/game_highscores.cpp
> +            assert( !campaignHighscoreData.empty() );
Hi @ihhub it's up to you :) I suppose that the probability of this scenario is very low.

2022-10-01 13:03 UTC, zenseii reviewed
Hi @ihhub.

This looks good. I tested a game and got a low enough score. However, the high score board is still shown, which I noticed doesn't happen in the OG. You just go straight back to the main menu if you have a low score.

Also with the current implementation the player will not even be told what score they got, since the end of the dragon animation doesn't show this yet. This was already a problem before this PR anyways.

2022-10-04 14:14 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +            assert( !campaignHighscoreData.empty() );
Done.

2022-10-04 14:35 UTC, zenseii requested changes
Hi, @ihhub.

I tested getting a low score and when you end up on the main menu it is impossible to open the high score from there.
Here's a save right before winning with a low score (not sure how much).
[LowScoreTest.zip](https://github.com/ihhub/fheroes2/files/9707803/LowScoreTest.zip)


<details>

https://user-images.githubusercontent.com/12501091/193847785-48e5e539-b321-4fa9-8273-c6aa6a827733.mp4
</details>

EDIT: All other dialogs can be opened. It is just the high score.

2022-10-04 14:44 UTC, ihhub commented
Hi @zenseii , thanks a lot for pointing the problem. It is fixed now.

2022-10-04 14:47 UTC, zenseii approved these changes
I've tested it and it works as it should.

2022-10-04 15:08 UTC, merged