Update polish translation
ihhub/fheroes2 pull request #5914
Opened 2022-10-01 12:33 UTC by KaspianDev

Hope it looks good!

2022-10-01 12:43 UTC, zenseii requested changes
Hi @KaspianDev,
Thank you for this contribution! We currently have this Polish PR https://github.com/ihhub/fheroes2/pull/5870 going, but it should hopefully be wrapped up soon. I'm not sure how these two are compatible, but we'll find out once it's merged.

I noticed one small error that it would be great if you could have a look at.

I would like to request @Pulfiarz's help in reviewing this if they should feel like it and have time to.

2022-10-01 12:43 UTC, zenseii commented on files/lang/pl.po
> +msgstr "Przeniesiono %{monster} z: [%{src}] do [%{dst}]."
These square brackets needs to be replaced with curly braces `{ }`.

2022-10-01 15:09 UTC, KaspianDev commented on files/lang/pl.po
> +msgstr "Przeniesiono %{monster} z: [%{src}] do [%{dst}]."
You mean i should remove them?

2022-10-01 15:12 UTC, zenseii commented on files/lang/pl.po
> +msgstr "Przeniesiono %{monster} z: [%{src}] do [%{dst}]."
Ah I'm mistaken. I thought you had replaced them. Just ignore this then.

2022-10-02 07:31 UTC, zenseii commented
Hi @KaspianDev.
The other Polish translation PR has been merged now. Could you solve the merge conflicts that you can find below?

Please ask if you have any questions.

2022-10-02 08:29 UTC, KaspianDev commented
Resolved, let me know if there are any problems.

2022-10-02 08:50 UTC, zenseii commented
> Resolved, let me know if there are any problems.
Thanks for solving the merge issues!

I've asked our regular Polish translators if they could have a look at your changes. Hopefully they can find the time to.

2022-10-02 12:57 UTC, Arthusppp requested changes

2022-10-02 12:57 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Konfiguruj"
Proponuję jednak "Dostosuj" (ewentualnie "Ustaw").

2022-10-02 12:57 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Wokal Basowy"
Jeśli już chcemy zmienić, to "basowy" z małej (bo przymiotnik). Ale ja bym wolał pozostawić to tłumaczenie (i te bliźniacze też, np. "Sopran"). @Pulfiarz masz preferencje?

2022-10-02 12:57 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Niemiecki Konsultant"
Czy możemy pozostać przy wcześniejszym? Jestem niemal pewien, że Dr Summers to Amerykanin.

2022-10-02 12:57 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Nie posiadasz Magicznej Księgi, więc nie możesz rzucić zaklęcia."
Odnośnie pierwszej części: czy możemy pozostawić "Księgę Zaklęć"? Zmieniamy wszystkie "księgi magii", "księgi czarów", itp. na jeden termin, właśnie "Księga Zaklęć".

2022-10-02 13:07 UTC, KaspianDev commented on files/lang/pl.po
> +msgstr "Wokal Basowy"
Zostawić w sensie jako "Bas (partie wokalne)" ?

2022-10-02 13:11 UTC, Pulfiarz commented on files/lang/pl.po
> +msgstr "Wokal Basowy"
Ja użyłem takiej formy, bo już występowała w tłumaczeniu w innym miejscu. Zostawionym tak, jak było.

2022-10-02 13:20 UTC, Pulfiarz reviewed
Ogólnie to szkoda, że się nie dogadaliśmy wcześniej na Discordzie, byłoby łatwiej :-P

Kwestie różnic w nazwach członków zespołów zostawionym do rozstrzygnięcia @Arthusppp , bo tak to jest moje zdanie kontra Twoje, zależy jak się podoba. Nie naciskam na moją wersję. A tak to tylko kilka rzeczy, wypisałem je poniżej, a część już poruszył @Arthusppp

2022-10-02 13:20 UTC, Pulfiarz commented on files/lang/pl.po
> +msgstr "Projektowanie Muzyki i Dźwięku"
Tu bym zostawił muzykę osobno, raczej nie mówi się o projektowaniu muzyki.

2022-10-02 13:20 UTC, Pulfiarz commented on files/lang/pl.po
> +msgstr "Kierownik Projektowania"
Nie pamiętam dokładnie, ale tam było chyba kilka osób. Jeśli jednak byłam jedna, to oczywiście Kierownik będzie lepszy.

2022-10-02 13:29 UTC, KaspianDev commented on files/lang/pl.po
> +msgstr "Kierownik Projektowania"
Gdzie znajdę taką informację?

2022-10-02 13:57 UTC, Pulfiarz commented on files/lang/pl.po
> +msgstr "Kierownik Projektowania"
Ja w grze sprawdziłem. Jednak jedna osoba, więc Kierownik :)

2022-10-02 18:22 UTC, zenseii approved these changes
Hi @ihhub.

This PR is ready for you to have a look at when you have the time.

2022-10-02 18:28 UTC, Pulfiarz commented
@KaspianDev , czy przeczytałeś może ten komentarz dotyczący pisowni nazw stanowisk? Odnośnie stosowania malych liter w dalszych członach? Bo to jest wg PWN zasada językowa i bym ją zachował.

2022-10-02 20:02 UTC, KaspianDev commented
> @KaspianDev , czy przeczytałeś może ten komentarz dotyczący pisowni nazw stanowisk? Odnośnie stosowania malych liter w dalszych członach? Bo to jest wg PWN zasada językowa i bym ją zachował.



> @KaspianDev , czy przeczytałeś może ten komentarz dotyczący pisowni nazw stanowisk? Odnośnie stosowania malych liter w dalszych członach? Bo to jest wg PWN zasada językowa i bym ją zachował.

Właśnie go zauważyłem, wszystko powinno już być poprawione ([a50cb0b](https://github.com/ihhub/fheroes2/pull/5914/commits/a50cb0b4207779070235b2fbf935a751a4f5b1a7))

2022-10-03 08:41 UTC, zenseii approved these changes
This PR is ready for you to look at it when you have the time @ihhub.

2022-10-03 14:34 UTC, merged

2022-10-03 14:34 UTC, ihhub commented
@KaspianDev , thank you so much for your contribution to the project!

2022-10-03 16:26 UTC, zenseii commented
@KaspianDev, if you have a Discord user you can get the Contributor role in the server. We just need to know your nick there.

2022-10-03 16:33 UTC, KaspianDev commented
Kaspian#0870