Add date to logging
ihhub/fheroes2 pull request #5918
Opened 2022-10-03 10:55 UTC by ihhub

This is useful for the future support of issues and logs provided by players.

2022-10-03 11:37 UTC, oleg-derevenetz requested changes
Hi @ihhub I just expressed my concerns regarding proposed implementation, please take a look when you have time.

2022-10-03 12:03 UTC, oleg-derevenetz commented on src/engine/logging.cpp
> +        std::array<char, 32> buf{ 0 };
Or maybe just use "large enough" buffer on stack (say, 128 or 256 bytes), but still indicate the `strftime()` failure in the resulting string.

2022-10-03 12:08 UTC, ihhub commented on src/engine/logging.cpp
> +        std::array<char, 32> buf{ 0 };
Hi @oleg-derevenetz , after a bit of thinking we can use `tm` structure directly as my intention to show day/month/year only together with time.

2022-10-03 12:12 UTC, oleg-derevenetz commented on src/engine/logging.cpp
> +        std::array<char, 32> buf{ 0 };
Hi @ihhub what do you mean by "use directly"?

2022-10-03 12:13 UTC, ihhub commented on src/engine/logging.cpp
> +        std::array<char, 32> buf{ 0 };
`printf` or `std::to_string()` :)

2022-10-03 12:13 UTC, ihhub commented on src/engine/logging.cpp
> +        std::array<char, 32> buf{ 0 };
Sorry, I mean tm structure has members which we can use with combination of printf or std::to_string() usage to construct a string we need.

2022-10-03 14:33 UTC, ihhub commented on src/engine/logging.cpp
> +        std::array<char, 32> buf{ 0 };
That's even better solution!

2022-10-03 15:22 UTC, oleg-derevenetz commented on src/engine/logging.cpp
> +        std::array<char, 32> buf{ 0 };
We can also use resizeable storage (such as `std::vector<char>`), but with `static thread_local` specifier (or just `thread_local`, because `static` is implied for `thread_local` in C++ (but not in C).

2022-10-05 15:32 UTC, ihhub commented on src/engine/logging.cpp
> +        std::array<char, 32> buf{ 0 };
Hi @oleg-derevenetz , I just increased the stack buffer size to 256 which is large enough to hold any reasonable timestamp information. I also added an assertion and returned string.

2022-10-05 15:58 UTC, oleg-derevenetz commented on src/engine/logging.cpp
> +        const size_t writtenBytes = std::strftime( buf.data(), buf.size() - 1, "%d.%m.%Y %H:%M:%S", &tmi );
Hi @ihhub I believe we can pass just the `buf.size()` here instead of `buf.size() - 1`, because `strftime` [takes the terminating null character into account](https://godbolt.org/z/PsqP1KMT3) when checking the buffer size. It is not quite obvious in the cppreference article, but it is clearly stated in the `strftime` man page:

```
If the length of  the  result string (including the terminating null byte) would exceed max bytes, then strftime() returns 0, and the contents of the array are undefined.
```

2022-10-06 04:57 UTC, ihhub commented on src/engine/logging.cpp
> +        const size_t writtenBytes = std::strftime( buf.data(), buf.size() - 1, "%d.%m.%Y %H:%M:%S", &tmi );
It is fixed.

2022-10-06 11:19 UTC, merged