Display detailed information about the composition of alliances in the scenario info window
ihhub/fheroes2 pull request #5926
Opened 2022-10-05 22:36 UTC by oleg-derevenetz

fix #5793

2022-10-06 09:42 UTC, zenseii commented on src/fheroes2/game/game_over.cpp
> +                                         "You and %{allies}, who is in alliance with you, must defeat the enemy alliance of %{enemies}.", enemiesCount );
Hi @oleg-derevenetz.

How about
"Your alliance, consisting of you, Red [...], must defeat [...]".

This solves the problem of is/are.

Not sure how to solve the fact that "and" should be placed between the second last and last component of that listing of allies. This wouldn't be the only place in the code where that happens so it's not too big of a deal.

2022-10-06 09:45 UTC, oleg-derevenetz commented on src/fheroes2/game/game_over.cpp
> +                                         "You and %{allies}, who is in alliance with you, must defeat the enemy alliance of %{enemies}.", enemiesCount );
Hi @zenseii Well maybe, but "your alliance consisting of you"? :) Maybe just "Alliance consisting of you, ..."?

2022-10-06 09:48 UTC, zenseii commented on src/fheroes2/game/game_over.cpp
> +                                         "You and %{allies}, who is in alliance with you, must defeat the enemy alliance of %{enemies}.", enemiesCount );
> Hi @zenseii Well maybe, but "your alliance consisting of you"? :) Maybe just "Alliance consisting of you, ..."?

Yes, that's better. Just add a "The" before "alliance".

2022-10-06 10:28 UTC, zenseii approved these changes

2022-10-06 11:26 UTC, zenseii approved these changes
This was a clever solution to it.

2022-10-06 13:48 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left 2 small remarks. Could you please take a look at them?

2022-10-06 13:48 UTC, ihhub commented on src/fheroes2/game/game_over.cpp
> +#include <utility>
We do not need these headers to be included.

2022-10-06 13:48 UTC, ihhub commented on src/fheroes2/game/game_over.cpp
> +                if ( ++result.second > 1 ) {
Please make variable increment on a separate line.

2022-10-06 13:59 UTC, oleg-derevenetz commented on src/fheroes2/game/game_over.cpp
> +#include <utility>
Hi @ihhub `<utility>`is for `std::pair`, `cstddef` is for `size_t`. I prefer to not rely on another modules' headers :)

2022-10-06 14:00 UTC, ihhub commented on src/fheroes2/game/game_over.cpp
> +#include <utility>
This is strange since Visual Studio allow to compile but I'm not surprised.

2022-10-07 00:32 UTC, ihhub approved these changes

2022-10-07 00:32 UTC, merged

2022-10-07 00:33 UTC, ihhub commented
@oleg-derevenetz , a huge thanks for this fix!