Fix neutral town unit growth
ihhub/fheroes2 pull request #5927
Opened 2022-10-06 14:53 UTC by ihhub

The growth should not be affected by game's difficulty. close #5905

2022-10-06 14:54 UTC, ihhub commented
@Branikolog , please test these changes.

2022-10-07 01:36 UTC, zenseii reviewed
Hi @ihhub,

I did some tests and the creature dwelling growth for neutral cities is now correct. The only exception is the case noted by @Branikolog in week 5 when the growth is doubled.

Here's my numbers:
<details>

<summary>Growth numbers</summary>
easy

week 1
peasant = 12
archer = 8

week 2
peasant = 18
archer = 12

week3 
peasant = 24
archer = 16

week 4
peasant = 30
archer = 20

week 5
peasant = 42
archer = 28

normal

week 1
peasant = 12
archer = 8

week 2
peasant = 18
archer = 12


</details>

2022-10-07 09:15 UTC, Branikolog approved these changes
Hi, @ihhub .
Growth is no more affected by difficulty.
But @zenseii is right, 5th week is still increased.

2022-10-07 10:06 UTC, oleg-derevenetz commented on src/fheroes2/castle/castle.cpp
>                  if ( isNeutral && !world.BeginMonth() )
It seems that for neutral towns the growth modifier is always 0.5, even in the beginning of a new month, so I believe that we should remove `&& !world.BeginMonth()` from here (and update the comment accordingly).

2022-10-07 10:07 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a proposal regarding the 5th week, please take a look when you have time.

2022-10-07 10:20 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
>                  if ( isNeutral && !world.BeginMonth() )
Fixed.

2022-10-07 10:21 UTC, ihhub commented
Hi @zenseii , @Branikolog and @oleg-derevenetz , I fixed growth for neutral towns at the beginning of a month. Please take a look.

2022-10-07 10:26 UTC, oleg-derevenetz approved these changes

2022-10-07 10:27 UTC, zenseii approved these changes

2022-10-07 12:05 UTC, merged