Add checks when the [] operator was used at risk
ihhub/fheroes2 pull request #5937
Opened 2022-10-08 09:22 UTC by bjauny

Fixes #5848 

I added checks when it seemed needed, the rest was already in bounds.

2022-10-12 15:10 UTC, ihhub requested changes
Hi @bjauny , I put several comments here. Could you please take a look?

2022-10-12 15:10 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +            if ( image.transform()[position] != 0 ) {
Please combine these 2 conditions under one if.

2022-10-12 15:10 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    int32_t colorId = 13 - 7 * i + ( 5 + i ) * ( 145 - ( 4 * i ) );
This is not color ID but a pixel position. Also this variable can be `const`.

2022-10-12 15:10 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    int32_t colorId = 5 * 132;
This is not color ID but a pixel position. Also this variable can be `const`.

2022-10-13 06:52 UTC, bjauny commented on src/fheroes2/agg/agg_image.cpp
> +            if ( image.transform()[position] != 0 ) {
Done.

2022-10-13 06:52 UTC, bjauny commented on src/fheroes2/agg/agg_image.cpp
> +                    int32_t colorId = 13 - 7 * i + ( 5 + i ) * ( 145 - ( 4 * i ) );
Done.

2022-10-13 06:52 UTC, bjauny commented on src/fheroes2/agg/agg_image.cpp
> +                    int32_t colorId = 5 * 132;
Done.

2022-10-14 02:05 UTC, merged

2022-10-14 02:05 UTC, ihhub commented
@bjauny , thank you so much for this fix!