Add a part of the Dutch translations
ihhub/fheroes2 pull request #5940
Opened 2022-10-08 11:15 UTC by piano1029

Due to the 1000 changes limit for translations I've had to split the translations. This is the first part.

2022-10-08 12:46 UTC, ihhub requested changes
Hi @piano1029 , I left several comments here. Could you please take a look?

2022-10-08 12:46 UTC, ihhub commented on files/lang/nl.po
> +# piano1029 <https://github.com/piano1029>, 2022
Please revert this change as we do not add any personal information within files for this project. This is done to avoid confusing of contributions as a file could be modified by many people and it's hard to tell whom to blame in case of issues.

2022-10-08 12:46 UTC, ihhub commented on files/lang/nl.po
> +"Last-Translator: piano1029 <https://github.com/piano1029>\n"
Please revert this change as well.

2022-10-08 12:46 UTC, ihhub commented on files/lang/nl.po
> +"GEVENCHTEN"
This is too long. The button does not have enough space to display so many symbols per line. Could you please come up with something shorter?

2022-10-08 12:46 UTC, ihhub commented on files/lang/nl.po
> +msgstr "MOEILIJKHEID"
I'm not sure that the button has enough space for such a lengthy word. @zenseii , could you please verify it?

2022-10-08 12:46 UTC, ihhub commented on files/lang/nl.po
> +msgstr "1-4"
We use words just few lines above like `Een paar` or `Een zwerm van`. Is there a reason we use numbers here?

2022-10-08 12:54 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "MOEILIJKHEID"
There is no synonym for difficulty in Dutch that makes sense for a game

2022-10-08 12:55 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "1-4"
When translating I took a look at the French translations to see how do translate stuff as I've never worked with this type of translation files before. Ive replaced it with words

2022-10-08 12:58 UTC, ihhub commented on files/lang/nl.po
> +msgstr "MOEILIJKHEID"
Mmm... @zenseii , do we have support for Dutch within game's resources?

2022-10-08 13:31 UTC, zenseii requested changes
Hi, @piano1029.

I've reviewed all you changes and left some comments. Please have a look at them when you feel like it and have the time.

Please ask if you have any doubts.

2022-10-08 13:31 UTC, zenseii commented on files/lang/nl.po
> +msgstr "De vlucht van Arrow"
Should this be "Pijl"?

2022-10-08 13:31 UTC, zenseii commented on files/lang/nl.po
> +msgstr "Verdediger Helm"
Should this be two words?

2022-10-08 13:31 UTC, zenseii commented on files/lang/nl.po
> +msgstr "Macht bijl"
Should this be two words?

2022-10-08 13:31 UTC, zenseii commented on files/lang/nl.po
> +msgstr "Donder Mace"
Should this be two words?

2022-10-08 13:33 UTC, zenseii commented on files/lang/nl.po
> +msgstr "MOEILIJKHEID"
I will check if it can fit now.

Dutch is covered by CP1252 so it should be no trouble adding support, @ihhub.

2022-10-08 13:38 UTC, piano1029 commented on files/lang/nl.po
> +"Schakel aan of uit of schaduwen worden weergegeven waar je schepsels kunnen bewegen en aanvallen."
Yes, the first `of` is as `or` and the second `of` means that shadows are enabled when its enabled

2022-10-08 13:39 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "Niet genoeg gound (%{gold})"
Yes, that was a typo

2022-10-08 14:03 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "Drakentand"
I've removed the not translated items

2022-10-08 14:05 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "Fizbin Medaille"
This should be 2 words

2022-10-08 14:06 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "De %{spell} doet %{damage} schade aan een ondode schepsel."
Fixed

2022-10-08 14:07 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "Poortwachter"
I've replaced it with "Dwarf murderer" (Translated of course)

2022-10-08 14:08 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "Draai Punt"
No, has been fixed

2022-10-08 14:08 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "De Handschoen"
I'm unsure how to translate that so I've removed the item

2022-10-08 14:08 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "Draken Meester"
No, has been fixed

2022-10-08 14:09 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "De vlucht van Arrow"
Yes

2022-10-08 14:11 UTC, piano1029 commented on files/lang/nl.po
> +msgstr " zal bereid zijn om zich bij je leger aan te sluiten.."
Has been fixed

2022-10-08 14:12 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "Caster's Armband"
When translating I thought it was a name, has been fixed

2022-10-08 14:14 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "MINIMUM"
Ive replaced with it with "MIN" as it works the same

2022-10-08 14:15 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "CADEAU"
Replaced it with "to donate"

2022-10-08 14:15 UTC, piano1029 commented on files/lang/nl.po
> +"Zounden van\n"
I've replaced it with "Hundreds of"

2022-10-08 14:16 UTC, zenseii commented on files/lang/nl.po
> +msgstr "MOEILIJKHEID"
@piano1029, as @ihhub the word "MOEILIJKHEID" is too long and gets separated in two lines due to that. We cannot currently extend the length of this button so the best thing would be to come up with some alternatives.

In Norwegian, which should be somewhat relateable, we chose the word "Nivå" which taken from French "Niveau" is similar to the English "Level". If not maybe something like Challenge.
![image](https://user-images.githubusercontent.com/12501091/194711908-b8bfb580-f854-4b2b-9100-0f14d0639d8e.png)

2022-10-08 14:17 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "Ketting Bliksem"
This should be 2 words. Ketting is both a chain and chain of events

2022-10-08 14:19 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "MOEILIJKHEID"
Replaced it with "Niveau" (in Dutch a lot of words are exactly the same as in French)

2022-10-08 14:43 UTC, zenseii requested changes
I left a few more comments after the last fixes, @piano1029. Please have a look when you have the time to.

2022-10-08 14:43 UTC, zenseii commented on files/lang/nl.po
> +msgstr "Een paar"
Earlier you use "Een paar" to translate "A few" while here it is used for "Several". This needs to be consistent for the player. This goes for all the other strings too.

2022-10-08 14:43 UTC, zenseii commented on files/lang/nl.po
> +msgstr "Zounds"
Here there's still "Zounds"

2022-10-08 14:43 UTC, zenseii commented on files/lang/nl.po
> +msgstr "\"The Dwarfbane!!!!, ren voor je leven.\""
Dwarfbane should be translated the same as elsewhere here.

2022-10-08 14:43 UTC, zenseii commented on files/lang/nl.po
> +"STIJD"
Is there an "R" missing here?

2022-10-08 14:49 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "Een paar"
Has been fixed

2022-10-08 14:49 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "Zounds"
Has been fixed

2022-10-08 14:50 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "\"The Dwarfbane!!!!, ren voor je leven.\""
Fixed

2022-10-08 14:50 UTC, piano1029 commented on files/lang/nl.po
> +"STIJD"
There was, its been fixed

2022-10-08 15:03 UTC, zenseii approved these changes
This is ready for you to look at, @ihhub.

2022-10-08 16:44 UTC, piano1029 commented on files/lang/nl.po
> +msgstr "Corlagons Verdediging"
Has been fixed

2022-10-09 00:17 UTC, zenseii approved these changes

2022-10-09 01:22 UTC, ihhub approved these changes

2022-10-09 01:22 UTC, merged

2022-10-09 01:22 UTC, ihhub commented
@piano1029 , thank you very much for your contribution to the project!