Bulgarian Translation 12
ihhub/fheroes2 pull request #5942
Opened 2022-10-08 16:51 UTC by Effektus

76% translated

2022-10-09 01:27 UTC, ihhub requested changes

2022-10-09 01:27 UTC, ihhub commented on files/lang/bg.po
> +"fheroes2/издания"
Please do not translate a part of web URL.

2022-10-09 20:30 UTC, zenseii requested changes
Hi, @Effektus.

I left a couple of comments here. Please have a look at it when you can.

2022-10-10 13:48 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Конфигуриране"
Of course you're free to decide what way to make this fit. You can also shorten the Text mode string below.

2022-10-10 14:16 UTC, zenseii commented
Hi @Effektus, could you please solve the merge conflicts?

2022-10-11 00:17 UTC, ihhub requested changes
Hi @Effektus , I put several comments here. Could you please take a look at them?

2022-10-11 00:17 UTC, ihhub commented on files/lang/bg.po
> +msgstr "Имунитет към"
Please add a space at the end of the line.

2022-10-11 00:17 UTC, ihhub commented on files/lang/bg.po
> +msgstr "% имунитет към"
Also please add a space at the end of this line.

2022-10-11 00:17 UTC, ihhub commented on files/lang/bg.po
> +msgstr "% щети от"
Please add a space at the end of the line.

2022-10-11 00:17 UTC, ihhub commented on files/lang/bg.po
>  #~ msgid "Moved %{monster}"
Please remove all lines starting from this one till the end of the file since they are not in use anymore.

2022-10-11 11:24 UTC, zenseii commented on files/lang/bg.po
> +"fheroes2/releases"
Hi @Effektus.

Please add a new line after "fheroes2/releases" like the warning is talking about here. This is the follow the standard of this project.

2022-10-11 11:40 UTC, zenseii approved these changes

2022-10-12 15:06 UTC, merged

2022-10-12 15:06 UTC, ihhub commented
@Effektus , huge thanks for updating this translation!