correcting an error in french translation file
ihhub/fheroes2 pull request #5956
Opened 2022-10-10 14:18 UTC by morgane-du-tweize

lines 9098 and 9099
original french translation : defense incresases by one
pull request correction : defense increases by %{count}

2022-10-10 16:11 UTC, felix642 approved these changes

2022-10-10 20:56 UTC, zenseii reviewed
Hi, @morgane-du-tweize.

Thank you for this great contribution! I left some comments that it would be nice if you could have a look at.

2022-10-10 20:56 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Guilde des Nécromanciens"
Note that these two were written like this in order to fit within the limits of the game UI:
![image](https://user-images.githubusercontent.com/12501091/194949494-fc31dcde-dce2-4990-9bb3-994e6da67152.png)


However, this isn't really a problem anymore so I'm fine with these changes. Just in case any other reviewers comment it.

2022-10-10 20:56 UTC, zenseii commented on files/lang/fr.po
> +msgstr "La Pierre de Lave brûlante"
Here and the other strings further down we made a conscious decision to have underscored letters since that seems to be the rule in French? Please correct me if I'm wrong.

2022-10-11 13:10 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Déplacement %{monster} : %{src}, %{dst}"
Hi @morgane-du-tweize.

You seem to have reverted all the changes done in the last commit to the French translation. Unless you have a specific reason to do this, could you please undo this change?

2022-10-11 13:15 UTC, zenseii commented on files/lang/fr.po
> +"He presents you with a gift:  A wand that prevents the use of the dispel "
Changes to the English text need to be done in the source code and not in the PO file since the string in the PO file needs to be exactly the same as in source for the string to get translated.

2022-10-11 15:04 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "La Pierre de Lave brûlante"
I'm not aware of this rule. Though I'm not an expert in any extent. If several french-speaking people made the choice of having first letter in lowercase in french please tell me, I'll revert capital first letters.

2022-10-11 15:30 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Déplacement %{monster} : %{src}, %{dst}"
Sorry.
I seem to have a problem with pull requests. Changes weren't reverted in my repertory. I'm asking on the discord, change will be undone when I'll figure out about my git commands mistakes.

2022-10-11 15:39 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Déplacement %{monster} : %{src}, %{dst}"
I've made new commit then pushed.
Changes are correctly made in fheroes2 of my repository,  nothing in original repository. Is this normal ?
Sorry I'm beginner

2022-10-11 16:19 UTC, zenseii commented on files/lang/fr.po
> +"Retirer votre héros de la bataille, en abandonnant vos créatures. Votre héro "
I believe this didn't need to be reverted since `héros` is the correct spelling, right?

2022-10-11 16:33 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"Retirer votre héros de la bataille, en abandonnant vos créatures. Votre héro "
yes, right.

2022-10-11 16:34 UTC, zenseii commented on files/lang/fr.po
> +"vous sauvez l'homme et placez un farfadet sur la terre ferme pendant quelque temps. "
I see that we are translating `Sprite` as both `Lutin` and `Farfadet` here. In general `Sprite` has been translated as `Fée` in this translation. Should we stay consistent and use that for both of these instances? This is up to you to decide. I figure a `river sprite` can be imagined as something different than a normal `sprite` too.

2022-10-11 16:36 UTC, zenseii commented on files/lang/fr.po
> +"seule et mourante. Voua vous occupez de ses ultimes besoins "
I believe this is a typo and should be `Vous vous occupez`.

2022-10-11 19:51 UTC, zenseii commented on files/lang/fr.po
> +"protège les morts vivants sous votre contrôle contre les sorts saints. "
Currently I believe they're called "morts-vivants" with the hyphen in the translation. We should probably try to stay consistent with either your way or the current way.

2022-10-11 19:55 UTC, zenseii commented on files/lang/fr.po
> +"Vous apercevez un Sorcier qui se sauve d'un Griffon, courant à toute allure. "
Should we have these nouns like "Griffon" with lowercase letter, @morgane-du-tweize ?

2022-10-11 20:39 UTC, zenseii commented on files/lang/fr.po
> +"pour vous bénir et pour vous offrir un charme contre les malédictions.  "
I see that most of your translations have one or several trailing white spaces after the final punctuation mark of the string.
```suggestion
"pour vous bénir et pour vous offrir un charme contre les malédictions."
```

Only the final line shouldn't have whitespaces after the punctuation mark. The other lines need the white space before the line is broken.

2022-10-11 20:39 UTC, zenseii commented on files/lang/fr.po
> +msgstr ""
Please revert this change.

2022-10-11 20:39 UTC, zenseii commented on files/lang/fr.po
> +msgstr ""
Please revert this change.

2022-10-11 20:45 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Mandigal"
Please revert this change and the change of the fuzzy comment above.

2022-10-12 02:32 UTC, felix642 requested changes

2022-10-12 02:32 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Verifier les raccourcis clavier du jeu."
Why did we remove this translation? 
I see that we marked the new one as fuzzy but I feel like the old translation was accurate, no?

2022-10-12 02:32 UTC, felix642 commented on files/lang/fr.po
> +"peuvent ne pas être aussi fluides que celui en noir et blanc."
I feel like we are lying here. The color of the cursor does not impact the performance of the game... Why did we add this sentence?

2022-10-12 02:32 UTC, felix642 commented on files/lang/fr.po
> +msgstr[0] "Défaire le héros '%{name}'."
Wow, good catch on this one the translation was definitely wrong and broken! 

Since this is marked as "fuzzy" and the current translation is wrong do we really want to keep it or should we leave it empty for now?

2022-10-12 02:32 UTC, felix642 commented on files/lang/fr.po
> +msgstr[0] ""
From what I can see we've removed this translation. 
I do agree that the old translation wasn't perfect but we should at least mark it as "fuzzy" for now or add a new translation.

We don't want to display empty strings to the user ;)

2022-10-12 02:32 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Adversaires :"
This might be ok, I'm not 100% familiar with the french translation.

I see that there is a space between the word and the punctuation. Is that something that we do throughout the file or should we remove the space?

2022-10-12 02:32 UTC, felix642 commented on files/lang/fr.po
> -"Voulez-vous passer le contrôle du jeu à l'IA ? Cela prendra effet au "
Why did we remove this string ?

2022-10-12 02:32 UTC, felix642 commented on files/lang/fr.po
> -"Il est vain de chercher l'Ultime Artefact. Votre héros ne pourrait pas "
Why did we remove this string?

2022-10-12 02:32 UTC, felix642 commented on files/lang/fr.po
> -"Cela vous permet de modifier la pénalité d'un joueur particulier. Seuls les "
I'm not quite sure to understand why we removed so many translations.

I won't add a comment to all of them since I suppose that the reason is the same. But if that was not supposed to happen I would appreciate it if we could please revert this change.

2022-10-12 02:32 UTC, felix642 commented on files/lang/fr.po
> +msgstr "La stalactite glaciale"
Looking at the definition I'm not convinced by the word "stalactite"

"Concrétion calcaire qui se forme au plafond des grottes."

In the case of the artifact, it's literally a "glaçon" why did we change it? 

I think I saw a discussion on discord related to that.. I'll check it to find the reason...

2022-10-12 02:32 UTC, felix642 commented on files/lang/fr.po
> +"Une stalactite qui résiste à la pleine chaleur du soleil de midi attire "
I don't know if the word "pleine" is needed here? 

I think it sounds better to simply say : "Une stalactite qui résiste à la chaleur du soleil de midi..."

2022-10-12 02:32 UTC, felix642 commented on files/lang/fr.po
> +msgstr "La Croix Egyptienne"
Égyptienne ?

2022-10-12 02:32 UTC, felix642 commented on files/lang/fr.po
> +"mais les voleurs ont oublié dans l'obscurité une croix égyptienne "
I'm not convinced by the "ont oublié" since in the original text they overlooked they did not forget

2022-10-12 02:32 UTC, felix642 commented on files/lang/fr.po
> +"qui s'amusent à plonger un viel homme dans l'eau. Epris de revanche, "
un vieil homme

2022-10-12 02:32 UTC, felix642 commented on files/lang/fr.po
> +"à point nommé fait basculer la bataille à la faveur du viel homme, "
"faveur du vieil homme"

2022-10-12 02:32 UTC, felix642 commented on files/lang/fr.po
> +"Vous tombez sur une très vielle dame, rendue aveugle par la cataracte, "
"une très vieille dame"

2022-10-12 02:32 UTC, felix642 commented on files/lang/fr.po
> +"transformé. Incapable de l'aider, vous vous emparez de l'anneau magique. "
Would it be better to say : "Puisque vous ne pouvez pas l'aider, vous vous emparez de l'anneau magique." ?

2022-10-12 04:46 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Adversaires :"
Hi @felix642. Yes we use something called espace insécable
for punctuations in the translation since that is apparently what French uses. https://storylearning.com/learn/french/french-tips/french-punctuation

2022-10-12 04:48 UTC, zenseii commented on files/lang/fr.po
> -"Voulez-vous passer le contrôle du jeu à l'IA ? Cela prendra effet au "
Hi @felix642. All the ones you have wondered why were removed is because they were diffs that got mistakenly everted when solving merge conflicts. Most of them should be reverted back, but some should be improved as you noted.

2022-10-12 08:57 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"protège les morts vivants sous votre contrôle contre les sorts saints. "
Fixed everything

2022-10-12 08:59 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"Vous apercevez un Sorcier qui se sauve d'un Griffon, courant à toute allure. "
All right.
Griffon in lowercase, as sorcier, magicien...

2022-10-12 09:12 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Verifier les raccourcis clavier du jeu."
You are right. My bad, thank you for noticing

2022-10-12 09:12 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Coloré"
Couleur was chosen in a recent discussion in the Discord channel.

2022-10-12 09:15 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr[0] "Défaire le héros '%{name}'."
thank you. fixed

2022-10-12 09:20 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"mais les voleurs ont oublié dans l'obscurité une croix égyptienne "
Chenged for :
"Une violente tempête vous révèle l'entrée d'un tombeau enseveli. "
"En faisant des recherches vous découvrez que le tombeau a déjà été pillé, "
"mais les voleurs n'ont pas remarqué une croix égyptienne accrochée "
"à une chaîne d'argent qui se trouvait dans l'obscurité."

Please tell me if it's better.

2022-10-12 09:21 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"Vous tombez sur une très vielle dame, rendue aveugle par la cataracte, "
Thank you. Fixed.

2022-10-12 09:22 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"transformé. Incapable de l'aider, vous vous emparez de l'anneau magique. "
Thank you. Fixed.

2022-10-12 09:41 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"des sorts de dissipation. "
Pour dispel, j'ai toujours vu "dissipation". Surtout, dispel était utilisé juste un peu plus haut dans la description.
J'en parle dans le discord.

Pour Sorcier/sorcier je crois déjà avoir vu des "Sorcier", "Nécromacien" 1ère lettre MAJ dans le texte ailleurs que dans ma trad. Il faudrait virer toutes les majuscules.

2022-10-12 09:45 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Mandigal"
Fixed. Thank you.

2022-10-12 09:51 UTC, zenseii commented on files/lang/fr.po
> +"des sorts de dissipation. "
Great! Yes, dissipation sounds better, but we should ask this to the other French speakers because they might be used to the term contre-sort.

2022-10-12 10:04 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"peuvent ne pas être aussi fluides que celui en noir et blanc."
Yes this was an error.
Translated correctly in main branch.
"
msgid "Toggle colored cursor on or off. This is only an esthetic choice."
msgstr "Basculer le curseur en couleur. Il ne s'agit que d'un choix esthétique."
"

 Fixed.

2022-10-12 10:07 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"qui s'amusent à plonger un viel homme dans l'eau. Epris de revanche, "
Fixed. Thank you.

2022-10-12 15:12 UTC, felix642 commented on files/lang/fr.po
> +"mais les voleurs ont oublié dans l'obscurité une croix égyptienne "
That looks good to me.

2022-10-13 07:29 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"des sorts de dissipation. "
According to discord french translation channel :
"%{name} empêche le contre-sort d'affecter vos troupes."

2022-10-13 09:49 UTC, zenseii commented on files/lang/fr.po
> +"des sorts de dissipation. "
If my suggestion sounds good in French then you can go for it. I'm not a native speaker so this is up to you.

2022-10-13 10:08 UTC, zenseii requested changes
Hi, @morgane-du-tweize.

I left some comments. Please have a look when you have the time.

2022-10-13 10:08 UTC, zenseii commented on files/lang/fr.po
> +msgstr[0] "Défaire le héros '%{name}'."
Using héros here will not work. This phrase will become something like "You must defeat the enemy Red." Red refers to team red. The phrase bellow is for when there are more enemy teams, like red, blue and yellow.
 
Akso please remove the fuzzy comment.

2022-10-13 10:08 UTC, zenseii commented on files/lang/fr.po
> +#, fuzzy
Please remove the fuzzy comment.

2022-10-13 10:08 UTC, zenseii commented on files/lang/fr.po
> +"Rechercher l'artéfact ultime est vain. Même s'il le trouvait, hotre héros "
Typo - Votre.

2022-10-13 10:08 UTC, zenseii commented on files/lang/fr.po
> -"commencent avec moins de ressources et reçoivent 15 ou 30 % de ressources en "
Please revert the removal of this string.

2022-10-13 10:08 UTC, zenseii commented on files/lang/fr.po
> +msgstr ""
Please revert this change.

2022-10-13 10:08 UTC, zenseii commented on files/lang/fr.po
> -"Pas de diminution des ressources de départ ni de celles reçus à chaque tour."
Please revert this change.

2022-10-13 10:08 UTC, zenseii commented on files/lang/fr.po
> +msgstr ""
Please revert this change.

2022-10-13 10:08 UTC, zenseii commented on files/lang/fr.po
> -"Les joueurs avec la pénalité sévère commenceront avec moins de ressources et "
Please revert this change.

2022-10-13 10:08 UTC, zenseii commented on files/lang/fr.po
> +msgstr "L'Anneau-serpent"
Should Anneau be lowercase?

2022-10-13 10:14 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Type d'interface"
The reason we wrote Interface is because Type d'interface doesn't fit in the UI of the game.

2022-10-13 11:46 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr ""
Fixed. Thank you for reporting.

2022-10-13 11:46 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Expérimentaux"
Fixed. Thank you for reporting.

2022-10-13 11:48 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Curseur de la souris"
Fixed. Thank you for reporting.

2022-10-13 11:48 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Raccourcis clavier"
Fixed. Thank you for reporting.

2022-10-13 11:50 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Type d'interface"
Fixed. Thank you for reporting.

2022-10-13 11:50 UTC, morgane-du-tweize commented on files/lang/fr.po
> +#, fuzzy
Fixed. Thank you for reporting.

2022-10-13 11:52 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr[0] "Défaire le héros '%{name}'."
Fixed. Thank you for reporting.

2022-10-13 11:53 UTC, morgane-du-tweize commented on files/lang/fr.po
> +#, fuzzy
Fixed. Thank you for reporting.

2022-10-13 11:53 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"Rechercher l'artéfact ultime est vain. Même s'il le trouvait, hotre héros "
Fixed. Thank you for reporting.

2022-10-13 11:56 UTC, morgane-du-tweize commented on files/lang/fr.po
> -"commencent avec moins de ressources et reçoivent 15 ou 30 % de ressources en "
Fixed. Thank you for reporting.

2022-10-13 11:58 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr ""
Sorry I don't understand, seems that it has already be reverted on my file.

2022-10-13 12:03 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr ""
Fixed. Thank you for reporting.

2022-10-13 12:04 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr ""
Fixed. Thank you for reporting.

2022-10-13 12:07 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr ""
Also seems that my PR removed sentence descripting mild handicap. Reverted this change also.

2022-10-13 12:07 UTC, morgane-du-tweize commented on files/lang/fr.po
> -"Les joueurs avec la pénalité sévère commenceront avec moins de ressources et "
Fixed. Thank you for reporting.

2022-10-13 12:08 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "L'Anneau-serpent"
Yes, it should. Fixed. Thank you for reporting.

2022-10-13 12:30 UTC, zenseii requested changes

2022-10-13 12:30 UTC, zenseii commented on files/lang/fr.po
> -"Les joueurs avec la pénalité sévère commenceront avec moins de ressources et "
This doesn't seem to have been fixed with the last commit, @morgane-du-tweize ?

2022-10-13 12:30 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Pas de diminution des ressources de départ ni de celles reçus à chaque tour."
Please move this to the line below like originally to avoid it showing up as a diff.

2022-10-13 12:30 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Basculer le curseur en couleur. Il ne s'agit que d'un choix esthétique."
Please move this to the line below like originally to avoid it showing up as a diff.

2022-10-13 12:30 UTC, zenseii commented on files/lang/fr.po
> +msgstr "La stalactite glaciale"
We still need to adress this comment.

2022-10-13 12:30 UTC, zenseii commented on files/lang/fr.po
> +"Une stalactite qui résiste à la pleine chaleur du soleil de midi attire "
We still need to address this comment.

2022-10-13 14:23 UTC, zenseii requested changes

2022-10-13 14:23 UTC, zenseii commented on files/lang/fr.po
> +"recevront 30 % de ressources en moins à chaque tour."
Now I see what happened. This description was moved to where it should say "Pénalité sévère.

2022-10-13 16:09 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Pas de diminution des ressources de départ ni de celles reçus à chaque tour."
Fixed. Thank you for reporting.

2022-10-13 16:13 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Basculer le curseur en couleur. Il ne s'agit que d'un choix esthétique."
Fixed. Thank you for noticing.

2022-10-13 16:19 UTC, morgane-du-tweize commented on files/lang/fr.po
> -"Les joueurs avec la pénalité sévère commenceront avec moins de ressources et "
My bad, mixed name and description. Fixed.

2022-10-13 16:22 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"recevront 30 % de ressources en moins à chaque tour."
Fixed. Thank you for noticing.

2022-10-15 08:30 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"Une stalactite qui résiste à la pleine chaleur du soleil de midi attire "
As original english uses "full" + "noonday", I'd like to use equivalent words in french. I mean you have two words to highlight how sunlight is hot.
I've replaced "pleine" by "forte".
Please tell me if it's okay.

2022-10-15 08:32 UTC, zenseii commented on files/lang/fr.po
> +"Une stalactite qui résiste à la pleine chaleur du soleil de midi attire "
Yep, this sounds good to me.

2022-10-15 08:34 UTC, zenseii commented on files/lang/fr.po
> +msgstr "La stalactite glaciale"
The argument on discord seems to be that stalactite is more fitting when it is broken off and no longer attached, from what I understand.

2022-10-15 08:38 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "La stalactite glaciale"
English text  line 8387 :
"...Intrigued, you break it off...". French translation of "break something off" is "détacher (quelque chose)". IMHO, stalactite is more appropriate here. In addition, wordreference.com website translates firts "icicle" by "stalactite".
Please tell me what do you think about.

2022-10-15 08:45 UTC, zenseii commented on files/lang/fr.po
> +msgstr "La stalactite glaciale"
I just checked wordreference and it is indeed stalactite. Glaçon is written as being Canadian French. I think our translation is based on mainland France French so we should probably try to be as consistent with that, and if needed we can meter add a separate Canadian French. I believe that also the white spaces added before ! etc. is not done in Canadian French.

2022-10-15 08:46 UTC, zenseii commented on files/lang/fr.po
> +msgstr "La stalactite glaciale"
In other words I think we can leave stalactite.

2022-10-15 08:46 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "La stalactite glaciale"
Sorry, I realise that @ felix642 is right, we cannot use "stalactite" unless we are in a grotto or cave.
I don't like "glaçon", I just think it doesn't fit when used as artifact name.
What do you think : "morceau de glace".

2022-10-15 09:05 UTC, zenseii requested changes
I left some comments. Please have a look when you have the time.

2022-10-15 09:05 UTC, zenseii commented on files/lang/fr.po
>  "qu'elle ne fond pas dans votre main."
Should it be "qu'il ne fond pas"?

2022-10-15 09:05 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Guilde des Sorcières"
Should Sorcières have lower case S?

2022-10-15 09:05 UTC, zenseii commented on files/lang/fr.po
> +"Vous devez acheter un Grimoire pour utiliser la Guilde des magiciens, mais "
Should grimoire have lowercase G?

2022-10-15 09:05 UTC, zenseii commented on files/lang/fr.po
> +"\"Aideront les gens à voir les choses à votre façon    d'\"."
The white spaces and d' at the end should be fixed.

2022-10-15 09:21 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Guilde des Sorcières"
No, it shouldn't.
There are many others 1st case letters anyway.
I'm fixing that but as said on discord this needs a separate PR due to the lenght of the file

2022-10-15 09:21 UTC, zenseii commented on files/lang/fr.po
> +"Vous devez acheter un Grimoire pour utiliser la Guilde des magiciens, mais "
I know that Grimoire is probably uppercase in most of the translation but we can address those in a later PR. I'm only commenting it here because we are already changing this line.

2022-10-15 09:23 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"Vous devez acheter un Grimoire pour utiliser la Guilde des magiciens, mais "
No, it shouldn't. Fixed. Thank you for reporting.

2022-10-15 09:25 UTC, morgane-du-tweize commented on files/lang/fr.po
>  "qu'elle ne fond pas dans votre main."
Yes, it should.
Thank you for noticing this.

2022-10-15 09:45 UTC, zenseii requested changes
I left some small comments.

2022-10-15 09:45 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Fils D=dévoyé"
There's a typo here.

2022-10-15 09:45 UTC, zenseii commented on files/lang/fr.po
> +"qu'un dollar aille au financement de la campagne pour l'élection pésidentielle."
Missing R in présidentielle

2022-10-15 09:45 UTC, zenseii commented on files/lang/fr.po
> +"et votre visage se change en une affreuse grimace! Oh, non !  "
Missing white space before !

2022-10-15 10:09 UTC, FlorianBaba commented on files/lang/fr.po
> +"protège les morts-vivants sous votre contrôle contre les sorts saints."
Not sure on this one

```suggestion
"protège les morts-vivants sous votre contrôle contre les sorts divins."
```

2022-10-15 10:09 UTC, FlorianBaba commented on files/lang/fr.po
> +"qu'un dollar aille au financement de la campagne pour l'élection pésidentielle."
```suggestion
"qu'un dollar aille au financement de la campagne pour l'élection présidentielle."
```

2022-10-15 10:09 UTC, FlorianBaba commented on files/lang/fr.po
> +"Un arrêt bref chez une tour de sorcier abandonnée en vitesse fait refaire surface "
```suggestion
"Un arrêt dans une tour de sorcier abandonnée vous permet de trouver "
```

2022-10-15 10:10 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"qu'un dollar aille au financement de la campagne pour l'élection pésidentielle."
Fixed. Thank you for noticing this.

2022-10-15 10:14 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"\"Aideront les gens à voir les choses à votre façon    d'\"."
Silly typo. Fixed. Thank you for noticing!

2022-10-15 10:15 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Fils D=dévoyé"
Fixed. Thank you for noticing.

2022-10-15 10:16 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"et votre visage se change en une affreuse grimace! Oh, non !  "
Fixed. Thank you for noticing.

2022-10-15 10:19 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"Retirer votre héros de la bataille, en abandonnant vos créatures. Votre héros "
Removed this.

2022-10-15 10:19 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"Un rétameur itinérant à la recherche de provisions vous offre un casque"
Fixed. thank you for noticing.

2022-10-15 10:20 UTC, zenseii commented on files/lang/fr.po
> +"Un arrêt bref chez une tour de sorcier abandonnée en vitesse fait refaire surface "
I believe by "hastily abandonned" they mean that the tower was abandonned in a hurry, as in one could see that they had to leave immediately for whatever reason.  Not sure how easy this is to translate.

2022-10-15 10:20 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Fils D=dévoyé"
That was a typo. Fixed, thank you for noticing.

2022-10-15 10:22 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"à une chaîne d'argent qui se trouvait dans l'obscurité."
Yes, I agree, that's better. Fixed. Thank you.

2022-10-15 10:25 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"récompense avec une copie du livre des éléments."
Yes, this is better. Thank you.
I've changed by :
"Vous acceptez, et en récompense "
"il vous offre une copie du livre des éléments."

2022-10-15 10:30 UTC, zenseii commented on files/lang/fr.po
> +"Un arrêt bref chez une tour de sorcier abandonnée en vitesse fait refaire surface "
Maybe `abandonnée à la hâte`?

2022-10-15 11:10 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"En accourant vers des appels à l'aide, vous trouvez des fées de rivière "
yes, definitively better !
Many of your suggestions are very nice anyway. Thank you!
Fixed.

2022-10-15 11:13 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"Au cours de vos pérégrinations, vous croisez un hermite qui vit dans une petite cabane bien rangée. "
Fixed! Thank you.

2022-10-15 11:15 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"et mourante. Vous vous occupez de ses ultimes besoins "
Yes, definitively better! Thank you.

2022-10-15 11:16 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"protège les morts-vivants sous votre contrôle contre les sorts saints."
Yes, pretty more accurate. Thank you!

2022-10-15 11:21 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"Un arrêt bref chez une tour de sorcier abandonnée en vitesse fait refaire surface "
Yes, "à la hâte" if definitively better. Fixed. Thank you two!

2022-10-15 14:07 UTC, felix642 requested changes
Hi, I've left a few more comments. Would you mind taking a look?

2022-10-15 14:07 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Le morceau de glace éternelle"
"Le morceau de glace **éternel**"

2022-10-15 14:07 UTC, felix642 commented on files/lang/fr.po
> +msgstr "La fiole source infinie de mercure"
I'm not convinced by this translation, it sounds weird to me.

I feel like the old one was better.

2022-10-15 14:41 UTC, zenseii commented on files/lang/fr.po
> +msgstr[0] "L'alliance composée de %{allies} et vous doit vaincre %{enemies}."
Hi @felix642. It's "L'alliance.... doit vaincre....". This should be correct?

2022-10-15 14:41 UTC, zenseii commented on files/lang/fr.po
> +"L'alliance composée de %{allies} et vous doit vaincre l'alliance ennemie "
Same comment as above.

2022-10-15 14:44 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr[0] "Défaire l'ennemi %{name}."
Fixed. Thank you for noticing !

2022-10-15 14:48 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr[0] "L'alliance composée de %{allies} et vous doit vaincre %{enemies}."
Fixed, thank you !

2022-10-15 14:49 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"L'alliance composée de %{allies} et vous doit vaincre l'alliance ennemie "
Fixed. Thank you for noticing this!

2022-10-15 14:50 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"Pas de diminution des ressources de départ ni de celles reçus à chaque tour."
Fixed. Thank you for noticing this!

2022-10-15 14:51 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Le morceau de glace éternelle"
Here, I've though that "éternelle" was applying to ice word.
I'll change if confirmed.

2022-10-15 14:56 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "La fiole source infinie de mercure"
I've found "inépuisable". Sounds good to me.

2022-10-15 15:08 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Le morceau de glace éternelle"
Honestly, I think it's the same. "Glace éternelle" suggests to me that there exists a type of ice that lasts forever, while "morceau... éternel" seems like that is a specific piece of ice that is famous for lasting for eternity.

Looking at the story/description of this artifact, you break it off from something else. It isn't explained if that is from a larger piece of snow/ice or if it's from a house or similar. I would imagine the latter since you wouldn't only comment on just the ice not melting in the sunlight but also the larger piece of ice it was attached to.

So "Le morceau de glace éternel" seems more logical.

2022-10-15 17:08 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Le morceau de glace éternelle"
Fixed. Thank you two!

2022-10-15 17:49 UTC, felix642 commented on files/lang/fr.po
> +msgstr[0] "L'alliance composée de %{allies} et vous doit vaincre %{enemies}."
Isn't it "L'alliance et vous" ?

2022-10-15 18:31 UTC, zenseii commented on files/lang/fr.po
> +msgstr[0] "L'alliance composée de %{allies} et vous doit vaincre %{enemies}."
Hmm no since you are a part of the Alliance, I guess maybe a comma could be used to better emphasize it?
"L'alliance, composée de %{allies} et vous, doit vaincre %{enemies}."

2022-10-15 18:34 UTC, zenseii commented on files/lang/fr.po
> +msgstr[0] "L'alliance composée de %{allies} et vous doit vaincre %{enemies}."
The reason `et vous` comes after is because there we don't have code to add an `"et"` between the two last components of a list.

So if `vous` came first then it would look like `"L'alliance composée de vous, Rouge, Bleu, Jeune doit vaincre %{enemies}."`

2022-10-15 19:35 UTC, felix642 requested changes

2022-10-15 19:35 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Fils D=dévoyé"
There is still a typo here

2022-10-15 19:35 UTC, felix642 commented on files/lang/fr.po
> +"qui s'amusent à plonger un viel homme dans l'eau. Épris de revanche, "
It should be vieil instead of viel

2022-10-15 19:35 UTC, felix642 commented on files/lang/fr.po
> +"\"Aideront les gens à voir les choses à votre façon    d'\"."
There is a space and a D that shouldn't be there at the end

2022-10-15 19:35 UTC, felix642 commented on files/lang/fr.po
> +msgstr "%{name} augmente votre défense de %{count} et votre attaque de 1."
In the original translation both defense and attack are increased by 1, that leads me to think that%{count} is invalid here.

2022-10-15 19:43 UTC, zenseii commented on files/lang/fr.po
> +msgstr "%{name} augmente votre défense de %{count} et votre attaque de 1."
I think this is just because maybe an artifact could be made in the future and this allows this string to be used for that or something. I'm not sure if there are more artifacts calling this string. Might be.

2022-10-16 07:31 UTC, ihhub commented
Are we close to the end of this pull request review? It is a very lengthy one as I see.

2022-10-16 15:57 UTC, felix642 commented on files/lang/fr.po
> +msgstr "%{name} augmente votre défense de %{count} et votre attaque de 1."
Never mind, I didn't read this line correctly. I thought that this was invalid but the new translation is better now. You can ignore this comment

2022-10-16 16:03 UTC, felix642 commented
> Are we close to the end of this pull request review? It is a very lengthy one as I see.

We should be ready to merge soon! There are a few minor typos left and we should be good to go :)

2022-10-17 08:55 UTC, morgane-du-tweize commented
IMPORTANT
I have 2 repositories :
main & master
There are conflicts between the two, generating Conflicts or typos.
I'm newbie so right now I'm learning merging correctly with my editor. And I may continue doing mistakes.
I may continue make stupid pushes.

When I'll be ok I will merge correctly the two branches and I'll notice.

2022-10-17 13:14 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"qui s'amusent à plonger un viel homme dans l'eau. Épris de revanche, "
thank you for noticing. sorry, problems with git. hope this is good now.

2022-10-17 14:27 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"Reprendre le château des portes d'ivoire, qui est tombé à cause de la trahison."
I don't like "à cause de la trahison".
Is better :
"à cause d'une trahison" ?
"à cause de trahisons" ?
"pour cause de trahison" ?
?

2022-10-17 14:58 UTC, zenseii commented
Hi @morgane-du-tweize,

It seems something is wrong with the format which is why the build checks failed.

Checking the clang-analyzer details below.
This is the relevant line telling you where in the file the error is:
`<stdin>:2841:41: syntax error`

2022-10-17 17:11 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Fils D=dévoyé"
Fixed. Thank you for noticing!

2022-10-17 17:13 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"\"Aideront les gens à voir les choses à votre façon    d'\"."
Fixed. Thank you for noticing this.

2022-10-17 17:32 UTC, zenseii requested changes
Hi, @morgane-du-tweize.

I just left two comments. Please have a look at them when you have the time.

2022-10-17 17:32 UTC, zenseii commented on files/lang/fr.po
> +"qu'un dollar aille au financement de la campagne pour l'élection présidentielle."
Should we use dollar here or could we use a word in French to say this and still keep the joke in tact?

2022-10-17 17:32 UTC, zenseii commented on files/lang/fr.po
> +"Reprendre le château des portes d'ivoire, qui est tombé à cause de la trahison."
Basically this treachery is only mentioned in this sentence so it is just a general note about why this castle got lost to the enemy. It isn't refering to some sort of treachery we had already heard about.

I'm not sure what sounds best in French here so I can't really help with it.

2022-10-17 18:15 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"Reprendre le château des portes d'ivoire, qui est tombé à cause de la trahison."
OK. Translated by "à la suite d'une trahison", I found this fluid.

2022-10-17 18:16 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"qu'un dollar aille au financement de la campagne pour l'élection présidentielle."
Yeah, translated by "euro", thank you!

2022-10-17 19:18 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Balistique de base"
Hi, @morgane-du-tweize.
I believe we made a conscious decision to name every "Basic ...." skill as "Principes de ...".

If we want to do such a change we need to discuss it with the rest.

2022-10-17 19:22 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Malédiction massive"
I believe Grande malédiction is the original name for it. Also Mass Curse gets its name because it curses the whole "mass" as in everyone, like a wide-reaching curse.

2022-10-17 19:24 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Voir les héros"
This should be Voir tous les héros in this case, but I'm not sure what's the best translation. This will need to be discussed.

2022-10-17 19:25 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Balistique de base"
Oh, sorry.
Launched discussion in discord. Will discard these changes for now.

2022-10-18 07:52 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Malédiction massive"
Oh, I understand. Fixed.

2022-10-18 07:57 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Voir les héros"
Yes, I also agree for "voir tous les héros".
I reversed the change, I agree for discussing on discord.

2022-10-19 14:19 UTC, felix642 approved these changes

2022-10-19 14:50 UTC, zenseii requested changes
Hi @morgane-du-tweize.

I've left several comments. Please have a look at them when you have the time to. Thanks!

2022-10-19 14:50 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Le Combat épique"
Should "Combat" have lower case C here?

2022-10-19 14:50 UTC, zenseii commented on files/lang/fr.po
> +" des gladiateurs vous propose d'entraîner le talent de votre choix."
There's a white space at the start of this line that should be removed:
```suggestion
"des gladiateurs vous propose d'entraîner le talent de votre choix."
```

2022-10-19 14:50 UTC, zenseii commented on files/lang/fr.po
> +msgstr[0] "L'alliance composée de %{allies} et vous devez vaincre %{enemies}."
If this looks right to you then I'm fine with this change:
![image](https://user-images.githubusercontent.com/12501091/196723064-2b958cd3-e5d5-4e78-8a89-df5e13a6de27.png)


The same comment applies to the line below.

2022-10-19 14:50 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Le sac d'or inépuisable"
Were we going to stick with "sans fin" here?

2022-10-19 14:50 UTC, zenseii commented on files/lang/fr.po
> +"vous forçant à l'abbatre. Vous emportez son boucier à pointes "
Typo "bouclier".

2022-10-20 07:59 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Le Combat épique"
No, it souldn't. Thank you for noticing

2022-10-20 08:00 UTC, morgane-du-tweize commented on files/lang/fr.po
> +" des gladiateurs vous propose d'entraîner le talent de votre choix."
Fixed. Thank you.

2022-10-20 08:03 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr[0] "L'alliance composée de %{allies} et vous devez vaincre %{enemies}."
Sorry, I don't understand.
Does that mean that the change is correct and I just have to resolve conversation ?

2022-10-20 08:04 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Le sac d'or inépuisable"
No, we don't. Messed with git - again. Thank you for noticing.

2022-10-20 08:05 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"vous forçant à l'abbatre. Vous emportez son boucier à pointes "
Fixed. Thank you for noticing !

2022-10-20 11:50 UTC, zenseii commented on files/lang/fr.po
> +msgstr[0] "L'alliance composée de %{allies} et vous devez vaincre %{enemies}."
I'm sorry for not being clear. It is a question. If you think that picture with text sounds good in French, then I am fine with this change. You are the expert here so I need your input. I just had some worry that this string wasn't clear in how it would be shown in the game.

2022-10-20 12:17 UTC, zenseii commented on files/lang/fr.po
> +msgstr "de l'oryctérope du Cap"
Should Cap be lowercase?

2022-10-20 12:18 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Pont du troll"
Should this maybe be plural? "Pont des trolls". It's a place where you can recruit many trolls for your army.

2022-10-20 13:54 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Pont du troll"
I've read several stories about one troll under the bridge.
If the game tells about recruiting many trolls, I fix this. I need confirmation, I don't know the game.

2022-10-20 13:55 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "de l'oryctérope du Cap"
Fixed. Thank you for  noticing.

2022-10-20 14:42 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Pont du troll"
Agreed. "Pont des trolls" now

2022-10-21 22:40 UTC, zenseii requested changes
I left three small comments, @morgane-du-tweize.

It'd be great if you could have a look when you have the time.

2022-10-21 22:40 UTC, zenseii commented on files/lang/fr.po
>  "tout devient flou. Les Zombies gisent sur le sol, le marteau dégouline de "
Zombies with lowercase Z.
```suggestion
"tout devient flou. Les zombies gisent sur le sol, le marteau dégouline de "
```

2022-10-21 22:40 UTC, zenseii commented on files/lang/fr.po
> +" bataille désespérée, vous tuez le monstre et trouvez l'artéfact '%{art}' "
```suggestion
"bataille désespérée, vous tuez le monstre et trouvez l'artéfact '%{art}' "
```

2022-10-21 22:40 UTC, zenseii commented on files/lang/fr.po
> +msgstr "de l'oryctérope du cap"
```suggestion
msgstr "de l'oryctérope"
```

2022-10-22 00:41 UTC, felix642 commented
Hi @morgane-du-tweize, this PR seems to have a lot of changes. We usually try to keep translation PRs as small as possible to simplify merge conflicts and reviews. I think that we should try to resolve the current comments and merge this PR afterward. We should fix other translations in another branch to limit the number of changes per PR.

What do you think @zenseii.

2022-10-22 00:58 UTC, felix642 requested changes

2022-10-22 00:58 UTC, felix642 commented on files/lang/fr.po
> -msgstr "Image miroir"
Why was this changed? The current translation seems more accurate are we constrained by the space?

2022-10-22 00:58 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Voir Villages et châteaux."
You have removed the 'C' from château but not the 'V' from village?

2022-10-22 00:58 UTC, felix642 commented on files/lang/fr.po
> +msgstr "de la frelon"
"du frelon"

2022-10-22 00:58 UTC, felix642 commented on files/lang/fr.po
> +"bataille. Ce sort est une version améliorée de onde mortelle."
```suggestion
"bataille. Ce sort est une version améliorée d'onde mortelle."
```

2022-10-22 00:58 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Invoquer l'élémentaire de l'eau"
```suggestion
msgstr "Invoquer élémentaire de l'eau"
```
This one was inconsistent with the others.

2022-10-22 05:29 UTC, zenseii commented on files/lang/fr.po
> +msgstr "de la frelon"
Ah yeah this was my fault when solving merge conflicts..

2022-10-22 15:31 UTC, morgane-du-tweize commented on files/lang/fr.po
>  "tout devient flou. Les Zombies gisent sur le sol, le marteau dégouline de "
Fixed. Thank you for noticing this.

2022-10-22 15:32 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "de l'oryctérope du cap"
Fixed

2022-10-22 15:35 UTC, morgane-du-tweize commented on files/lang/fr.po
> -msgstr "Image miroir"
Ligne 9633 : "miroir"
je pensais qu'il y avait une raison (je ne connais pas assez le jeu).
Si confirmation je mets "image miroir"

2022-10-22 15:37 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "de la frelon"
Fixed

2022-10-22 15:37 UTC, zenseii commented
> What do you think @zenseii.

Hi, @felix642.
Yes I think after addressing our comments here and the last ones from Discord this PR will be good-to-go. Anything new, if possible, will have to be added in another PR.

2022-10-22 15:38 UTC, morgane-du-tweize commented on files/lang/fr.po
> +"bataille. Ce sort est une version améliorée de onde mortelle."
Fixed. Thank you

2022-10-22 15:38 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Invoquer l'élémentaire de l'eau"
Oh, thank you!

2022-10-22 16:39 UTC, zenseii commented on files/lang/fr.po
> +msgstr "autre dimension"
This "a" should be uppercase.

2022-10-22 16:43 UTC, zenseii commented on files/lang/fr.po
> -msgstr "Image miroir"
This is the original game:
![image](https://user-images.githubusercontent.com/12501091/197352147-d55b3706-7f7d-4b53-a8d4-84807d9fbf7f.png)

For me any of them are fine.

2022-10-22 18:46 UTC, zenseii commented on files/lang/fr.po
> -msgstr "Image miroir"
Space is not a problem for using "Image miroir".

2022-10-23 12:34 UTC, morgane-du-tweize commented on files/lang/fr.po
> -msgstr "Image miroir"
All right this is image miroir now

2022-10-23 12:35 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "autre dimension"
Damn me... Thank you

2022-10-23 12:57 UTC, zenseii approved these changes
Very good job with this translation fix and update @morgane-du-tweize ! 

I've checked the latest updates and this PR is ready for you to have a look at @ihhub.

2022-10-23 17:48 UTC, felix642 approved these changes
LGTM !

2022-10-24 15:21 UTC, merged

2022-10-24 15:22 UTC, ihhub commented
@morgane-du-tweize , thank you so much for your contribution to the project!