Select Scenario Window Elements Position (#1235)
ihhub/fheroes2 pull request #5961
Opened 2022-10-11 08:23 UTC by HaveFun91

2022-10-11 08:38 UTC, HaveFun91 commented
Close #1235

2022-10-11 11:14 UTC, zenseii commented
Hi @HaveFun91.

I've linked the issue to this PR. The clang-tidy comments are valid so please have a look at them when you can and feel like it. Also it would be great if you could have a look at the Code style check that failed when you have the time.

Don't hesitate to ask if you have any questions.

2022-10-12 16:14 UTC, ihhub requested changes
Hi @HaveFun91, I put multiple comments in this pull request. Could you please check them?

2022-10-12 16:14 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +                                                curDifficulty.x, curDescription.x, curDifficulty.width );
Here we are storing 2 sets of the same coordinates and usage of structures is not exactly beneficial.

What if we create an enumeration in unnamed namespace which will contain all these magic numbers and then pass only x and y offset into ScenarioListBox? The biggest problem is not how we pass or process data but how we set this data and right now is this place. For example.
```cpp
const fheroes2::Rect curCountPlayer( rt.x + 45, rt.y + 264, 18, 18 );
```
could be (need to play with enumeration entry names):
```cpp
const fheroes2::Rect curCountPlayer( rt.x + CURRENT_PLAYER_OFFSET_X, rt.y + ICONS_OFFSET_Y, ICON_SIZE, ICON_SIZE );
```

What do you think?

2022-10-12 16:14 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.h
> +    const short _offsetY = 4;
Please do not use `short` variable type in the code as this is implementation dependent type.

2022-10-12 16:14 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.h
> +    const fheroes2::Sprite & _getLossConditionsIcon( uint8_t condition );
All these methods must be static and their input arguments should be `const`.

2022-10-12 16:14 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    fheroes2::Image undefinedMapSizeIcon;
We should avoid using global variable unless it's the only way to implement things.

2022-10-12 16:14 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +const fheroes2::Image & ScenarioListBox::_getMapSizeIcon( uint16_t size )
Instead of returning an image and have a global variable to handle a corner case why don't we just create methods to draw stuff within them?

2022-10-12 20:55 UTC, HaveFun91 commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    return fheroes2::AGG::GetICN( ICN::REQUESTS, mapIconIndex );
I believe this is no longer a case.

2022-10-12 20:56 UTC, HaveFun91 commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +                                                curDifficulty.x, curDescription.x, curDifficulty.width );
Yes, moving that values to enum makes sense. Commited fix on this, but couldn't get rid of magic calculations in total.

2022-10-12 21:23 UTC, zenseii requested changes
Hi @HaveFun91.

I left a couple of small comments. Please have a look when you have the time to.

2022-10-12 21:23 UTC, zenseii commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    Text text;
Hi @HaveFun91 since we are touching this part of the code, `Text` is an old method that we are replacing with `fheroes2::Text` which is found in `ui_text.cpp`.

2022-10-12 21:23 UTC, zenseii commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    text.Set( info.name, Font::BIG );
We usually initialize and declare at once in the project.
Something like:
```cpp
fheroes2::Text text( info.name, fheroes2::FontType::normalWhite() );
```

Note that the old `Font::BIG` is called `normalWhite()` now.


Also note that `fheroes2::Text` has the methods `set()` and `draw()` instead of `Set` and `Blit`.
Another point is that the y-coordinate needs to be offset with the new draw compared to the old Blit. There should be a comment about this in the beginning of `ui_text.cpp`.

2022-10-12 21:52 UTC, zenseii requested changes

2022-10-12 21:52 UTC, zenseii commented on .gitignore
> +.DS_Store
Could you please add a newline at the end of this file?

2022-10-12 23:45 UTC, oleg-derevenetz commented
Hi all! Please note that some issues still present in this PR were not reported by our Clang-Tidy machinery due to recent regression in the upstream [clang-tidy-pr-comments](https://github.com/platisd/clang-tidy-pr-comments) workflow. The fix [is already on the way](https://github.com/platisd/clang-tidy-pr-comments/pull/31) and (I hope) will be merged shortly.

2022-10-14 07:18 UTC, HaveFun91 commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    Text text;
I removed all `Text.h` dependecies.

2022-10-14 07:19 UTC, HaveFun91 commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    text.Set( info.name, Font::BIG );
I have applied some changes. Not sure whether i got what you mean in terms of `draw()` method - was it about including offset within y-coordinate?

2022-10-14 07:21 UTC, zenseii commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    Text text;
Great! Thanks!

2022-10-14 07:24 UTC, zenseii commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    text.Set( info.name, Font::BIG );
> I have applied some changes. Not sure whether i got what you mean in terms of `draw()` method - was it about including offset within y-coordinate?

To be honest it's easier to figure out by looking at the game. IIRC when replacing Blit with draw you have to add an extra 2 in value to the y-coordinate.

Again it's easier to verify in the game so if it has looked right when you've checked it then it's nothing to worry about.

2022-10-14 07:27 UTC, HaveFun91 commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    int32_t GetCenteredTextXCoordinate( const int32_t startCoordX, const int32_t textBoxWidth, const int32_t textWidth )
I don't get it - this warning makes no sense to me. For example why then
`virtual void draw( const int32_t x, const int32_t y, Image & output ) const = 0;` this is allowed - same considerations here.

2022-10-14 07:30 UTC, HaveFun91 commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    int32_t GetCenteredTextXCoordinate( const int32_t startCoordX, const int32_t textBoxWidth, const int32_t textWidth )
Is it about similar name of `textBoxWidth` and `textWidth`?

2022-10-14 07:54 UTC, oleg-derevenetz commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    int32_t GetCenteredTextXCoordinate( const int32_t startCoordX, const int32_t textBoxWidth, const int32_t textWidth )
Hi @HaveFun91 it's a new warning from Clang-Tidy 14, it means that two (or more) parameters of the same (or convertible) types follow each other, so it is possible for a caller to swap/reorder them by mistake - for example, call the function `f(int x, int y)` as `f(y, x)`. You can ignore this warning for now, maybe we will turn it off later completely.

2022-10-14 07:55 UTC, zenseii commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    int32_t GetCenteredTextXCoordinate( const int32_t startCoordX, const int32_t textBoxWidth, const int32_t textWidth )
Looking at the definition it seems it's suggesting you to change it into a struct. https://clang.llvm.org/extra/clang-tidy/checks/bugprone/easily-swappable-parameters.html

Not sure this is desirable or the right interpretation, @oleg-derevenetz ?

2022-10-14 08:01 UTC, oleg-derevenetz commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    int32_t GetCenteredTextXCoordinate( const int32_t startCoordX, const int32_t textBoxWidth, const int32_t textWidth )
Hi @zenseii Yes, but it may be redundant to make a separate structure for each function that have several arguments of convertible types, so we need to think about the usefulness of this warning.

2022-10-14 08:25 UTC, HaveFun91 commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    int32_t GetCenteredTextXCoordinate( const int32_t startCoordX, const int32_t textBoxWidth, const int32_t textWidth )
There are some configuration possibilities here - maybe this setting: `MinimumLength` mentioned in doc would make sense to somekind of force user to create more complex object storing e.g. 5 parameters. Inventing brand new type for each of situation seems to be a mistake from my perspective.

2022-10-14 08:26 UTC, HaveFun91 commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    int32_t GetCenteredTextXCoordinate( const int32_t startCoordX, const int32_t areaWidth, const int32_t textWidth )
As agreed - to be ignored for now.

2022-10-14 08:30 UTC, oleg-derevenetz commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    int32_t GetCenteredTextXCoordinate( const int32_t startCoordX, const int32_t textBoxWidth, const int32_t textWidth )
@HaveFun91 you can ignore this warning for now (unless you really want to introduce structs in some cases).

2022-10-14 08:31 UTC, HaveFun91 commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    int32_t GetCenteredTextXCoordinate( const int32_t startCoordX, const int32_t textBoxWidth, const int32_t textWidth )
I will ignore this warning in that case.

2022-10-15 05:55 UTC, ihhub requested changes
Hi @HaveFun91, we are almost there. I put few comments related to code styling in general. Could you please take a look? Also please rebase your branch from master branch of this repo to use `fheroes2::showStandardTextMessage()` function.

2022-10-15 05:55 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +        fheroes2::showMessage( fheroes2::Text( header, fheroes2::FontType::normalYellow() ), fheroes2::Text( body, fheroes2::FontType::normalWhite() ), Dialog::ZERO );
Please use `fheroes2::showStandardTextMessage()` here and in other places because some of them use **white** color instead of **yellow** for the header.

2022-10-15 05:55 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +        fheroes2::Blit( fheroes2::AGG::GetICN( ICN::REQUESTS, mapIconIndex ), display, coordX, coordY );
I would suggest to add an assertion before this line to make that `mapIconIndex` is really >=0 because the second parameter of `GetICN()` function expects an unsigned int.

2022-10-15 05:55 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    int iconIndex = 30 + condition;
This variable should be `uint32_t`.

2022-10-15 05:55 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    int iconIndex = 36 + condition;
This variable should be `uint32_t`.

2022-10-15 15:39 UTC, HaveFun91 commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +        fheroes2::Blit( fheroes2::AGG::GetICN( ICN::REQUESTS, mapIconIndex ), display, coordX, coordY );
Assertion here doesn't make sense in my opinion - we have switch/case statement that sets specific values and on init it's -1. I mean - I can add it, but i don't see any benefit of putting assertion here.

2022-10-16 07:26 UTC, ihhub approved these changes

2022-10-16 07:26 UTC, ihhub commented
Hi @LeHerosInconnu, could you please test these changes?

2022-10-16 15:13 UTC, zenseii approved these changes
Hi @HaveFun91.

This looks good to me. I suggest to add a screenshot or some description showing the new changed dialog of this PR to quicker grasp the changes made from a visual perspective.

2022-10-16 16:33 UTC, ihhub commented
Before changes:
![image](https://user-images.githubusercontent.com/19829520/196047023-a3fda446-8fd0-4c6c-9334-6779ee283884.png)
After changes:
![image](https://user-images.githubusercontent.com/19829520/196047030-dc9309df-0952-481a-866c-e61986cbfdae.png)

@Branikolog and @LeHerosInconnu, I will need your opinion about this.

2022-10-17 09:34 UTC, HaveFun91 commented
@Branikolog Tbh it compared two images above and i don't see any difference between S, M, XL, L buttons. Could you provide some more info about this? Or what should be done to correct placement?

2022-10-17 10:12 UTC, HaveFun91 commented
I tried to move buttons... but seems like there are more underneath:
![image](https://user-images.githubusercontent.com/627531/196151774-e8a43728-cff4-4d88-9923-de72256dcd67.png)

2022-10-17 10:16 UTC, HaveFun91 commented
@Branikolog is it ok now?
![image](https://user-images.githubusercontent.com/627531/196152508-da64f8ab-449f-42ab-ac30-812dc640dc9b.png)

2022-10-17 10:26 UTC, Branikolog commented
@HaveFun91 
![OG menu](https://user-images.githubusercontent.com/55348946/196154600-db76b264-3789-4671-a219-6350a07c03c1.png)
![fheroes2 menu](https://user-images.githubusercontent.com/55348946/196154609-1c1043fa-935c-4dcb-b659-49be29607a58.png)
There's some horizontal shifting left.

2022-10-17 19:37 UTC, HaveFun91 commented
@Branikolog I have moved buttons to the left:
![image](https://user-images.githubusercontent.com/627531/196266973-e42591f6-12d3-479e-a7de-9732418b82de.png)

2022-10-18 13:27 UTC, LeHerosInconnu commented
Hello @HaveFun91 and @Branikolog,

> @Branikolog I have moved buttons to the left:
![image](https://user-images.githubusercontent.com/627531/196266973-e42591f6-12d3-479e-a7de-9732418b82de.png)

Everything looks good, except the spacing between the "L" and "XL" buttons is 8 pixels instead of 7 pixels.

![Broken AllFlags in box 01](https://user-images.githubusercontent.com/43583994/196441569-81672763-5a3b-483c-b001-862f81a69902.png)

Also, in the example, the scenario name "Broken AllFlags" is not centered horizontally in the box (15 pixels on the left and 17 pixels on the right).

What do you think about moving the text line of the scenario file name up 1 pixel so that the lettering with jamb, in the example the "g" in the word "AllFlags", is not too close to the bottom of the text box (the text line would then have the same vertical position as the word "Normal" in the box for the scenario difficulty)?

2022-10-18 15:53 UTC, HaveFun91 commented
@LeHerosInconnu  i uploaded fix.
See attached screenshot:
![image](https://user-images.githubusercontent.com/627531/196481267-ffcf0c5f-25cd-47d0-8255-fcb941c65ee0.png)

2022-10-19 11:42 UTC, LeHerosInconnu commented
Hello @HaveFun91,

> @LeHerosInconnu i uploaded fix. See attached screenshot:
![image](https://user-images.githubusercontent.com/627531/196481267-ffcf0c5f-25cd-47d0-8255-fcb941c65ee0.png)

Everything looks correct according to the screenshot provided.

2022-10-19 15:17 UTC, merged

2022-10-19 15:18 UTC, ihhub commented
@HaveFun91 , huge thanks for fixing this issue!