(#1240) Memorize Selected Scenario in Scenario Selection Window
ihhub/fheroes2 pull request #5975
Opened 2022-10-14 10:21 UTC by HaveFun91

2022-10-14 14:47 UTC, oleg-derevenetz commented
Hi @HaveFun91 hint: to indicate that this PR should close one or more issues upon its merge, refer to these issues in the PR description using the following syntax:

fix #ISSUE_1_ID
fix #ISSUE_2_ID

or

close #ISSUE_1_ID
close #ISSUE_2_ID

2022-10-19 15:47 UTC, HaveFun91 commented
@ihhub or @oleg-derevenetz feel free to review - already rebased on fresh master :)

2022-10-20 14:20 UTC, ihhub requested changes
Hi @HaveFun91 , I left few suggestions here. Could you please take a look at them?

2022-10-20 14:20 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    }
Will this construction work?
```cpp
    fheroes2::ButtonBase * SwitchPressedMapSizeButtons( fheroes2::Button & newlyPressedButton )
    {
        newlyPressedButton.press();
        return &newlyPressedButton;
    }
...

currentPressedButton = SwitchPressedMapSizeButtons( newlyPressedButton );
```

My concern is `*&` usage which is very tricky.

2022-10-20 14:20 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    this->setScrollBarImage( updatedScrollbarSlider );
Usage of `this->` is redundant. Please remove it here and in other places.

2022-10-20 14:20 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +}
Please add an empty line at the end of this file.

2022-10-20 14:20 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.h
> +    Maps::mapsize_t selectedSize{ Maps::ZERO };
I suggest to do this way:
- set an explicit data type for the enumeration:
```cpp
enum mapsize_t : int
```
- use **int** here and in `SelectMapSize()` method  and remove `#include "maps.h"`

2022-10-20 14:28 UTC, HaveFun91 commented on src/fheroes2/dialog/dialog_selectscenario.h
> +    Maps::mapsize_t selectedSize{ Maps::ZERO };
I'm afraid I cannot remove maps.h as this is also used in `dialog_selectscenario.cpp` and i'm getting compilation errors. Other than this - changes applied.

2022-10-20 14:29 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.h
> +    Maps::mapsize_t selectedSize{ Maps::ZERO };
Sure.

2022-10-20 15:45 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.h
> +    enum mapsize_t : int;
I actually meant to change the enumeration in maps.h file, not to add a line here :)

2022-10-21 01:09 UTC, ihhub commented
Hi @LeHerosInconnu, can you please verify this pull request?

2022-10-21 17:31 UTC, LeHerosInconnu commented
Hello @ihhub,

> Hi @LeHerosInconnu, can you please verify this pull request?

Works great, and I would say better than in the original game. :)

2022-10-22 01:44 UTC, merged

2022-10-22 01:45 UTC, ihhub commented
@HaveFun91 , huge thanks for fixing this issue!