Scenario Window UI Items position fix (#1250);
ihhub/fheroes2 pull request #5983
Opened 2022-10-15 18:25 UTC by HaveFun91

Close #1250

2022-10-21 08:57 UTC, HaveFun91 commented
@ihhub or @oleg-derevenetz - feel free to review :)

2022-11-11 14:41 UTC, zenseii commented
Hi @LeHerosInconnu.

I addressed your last concern about the alignment of the Normal difficulty text:
![image](https://user-images.githubusercontent.com/12501091/201362854-4a4e57a5-b9c9-4165-93af-8958a78a4bde.png)

Please have a look and if it is all good now please confirm this so that this PR can move towards being merged.
Thank you!

2022-11-11 14:48 UTC, oleg-derevenetz commented
Hi @zenseii could you please merge the master branch to this PR to run the lately introduced checks against it?

2022-11-12 03:24 UTC, ihhub requested changes
Hi @HaveFun91 and @zenseii , I put several comments in this pull request. Can you please take a look?

2022-11-12 03:24 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +int32_t TextUtils::GetCenteredTextXCoordinate( const int32_t startCoordX, const int32_t areaWidth, const int32_t textWidth )
I believe that a proper fix is to change `void Text::draw( const int32_t x, const int32_t y, const int32_t maxWidth, Image & output ) const` and `void MultiFontText::draw( const int32_t x, const int32_t y, const int32_t maxWidth, Image & output ) const` methods to make auto alignment. `void Text::draw()` method is used in 33 places while `void MultiFontText::draw()` isn't used anywhere. Since these methods accept an input parameter for maximum width we can update the documentation (comments) stating that the text will be centered.

Alternatively, we can add text alignment option which might cover all possible cases in the game. I will try to take a look at it.

2022-11-12 03:24 UTC, ihhub commented on src/fheroes2/gui/player_info.cpp
> +        const std::string & className = _( "playerInfo|" + Race::String( info.player->GetRace() ) );
This is an incorrect approach: `Race::String()` returns **translated** string. Our translation tools do not understand string concatenation.

2022-11-12 03:24 UTC, ihhub commented on src/fheroes2/gui/player_info.cpp
> +        fheroes2::Text text( className, fheroes2::FontType::smallWhite() );
This variable can be **const**.

2022-11-12 03:24 UTC, ihhub commented on src/fheroes2/game/game_scenarioinfo.cpp
> +        fheroes2::Text text( str, fheroes2::FontType::normalWhite() );
This variable can be **const**.

2022-11-12 03:24 UTC, ihhub commented on src/fheroes2/game/game_scenarioinfo.cpp
> +            // Add offset shift because the original difficulty icons have irregular spacing.
Should we modify assets instead of having such hacks? Can you provide images with different difficulties?

2022-11-12 03:32 UTC, zenseii commented on src/fheroes2/game/game_scenarioinfo.cpp
> +            // Add offset shift because the original difficulty icons have irregular spacing.
Since it is only a column of 1 pixel in width it might be doable to modify the background of this asset. You could maybe copy from the side of another Icon in this dialog.

2022-11-12 12:44 UTC, LeHerosInconnu commented
Hello @zenseii,

> Hi @LeHerosInconnu and @ihhub.
> 
> I made the minor necessary changes to address the last issues with this PR that were noted by @LeHerosInconnu. Please have a look at it when you have the time to, @ihhub.
> 
> @LeHerosInconnu, I addressed your last concern about the alignment of the Normal difficulty text:
![image](https://user-images.githubusercontent.com/12501091/201362854-4a4e57a5-b9c9-4165-93af-8958a78a4bde.png)
> 
> Please have a look, @LeHerosInconnu, and if it is all good now please confirm this so that this PR can move towards being merged. Thank you!

The word "Normal" is correctly centered in relation to the corresponding difficulty graphic.

2022-11-16 00:56 UTC, zenseii commented on src/fheroes2/game/game_scenarioinfo.cpp
> +            // Add offset shift because the original difficulty icons have irregular spacing.
![image](https://user-images.githubusercontent.com/12501091/202056923-c7f11176-836c-4486-96ab-e5409b0bd8db.png)

2022-11-16 01:25 UTC, zenseii commented on src/fheroes2/game/game_scenarioinfo.cpp
> +            // Add offset shift because the original difficulty icons have irregular spacing.
At this point I think it is better to add better code that accounts for this irregular spacing...

2022-11-22 16:20 UTC, zenseii commented on src/fheroes2/dialog/dialog_gameinfo.cpp
> +        // CALCULATED
Hi, @ihhub.

I'm not entirely sure what the purpose of this comment is. Since I'm wrapping up this PR on @HaveFun91's behalf I'd need to address this too.

2022-11-22 16:26 UTC, HaveFun91 commented on src/fheroes2/game/game_scenarioinfo.cpp
> +            // Add offset shift because the original difficulty icons have irregular spacing.
I guess modifying all that stuff is going to be difficult as difficulty level graphics are melted into background and there is no way to move them.

2022-11-22 18:13 UTC, zenseii commented
Hi, @oleg-derevenetz.

I'm struggling a bit with IWYU's suggestions and would like to ask your assistance. It suggests to add `bits/utility.h` in `interface_gamearea.cpp` and `bits/chrono.h` in `ui_tools.h`. However, if I include them I'm told that these files are not found. I assume they are supposed to replace the inclusion of `<algorithm>` since removing that is another suggested change.

2022-11-22 18:36 UTC, oleg-derevenetz commented
Hi @zenseii those `bits/*` headers are private headers, they shouldn't be included directly. Sometimes IWYU cannot recognize a situation like this:

`include/some_public_header.h`:

```
[...]
#include <bits/some_private_header.h>
[...]
```

`include/some_private_header.h`:

```
struct SomeStruct { [...] };
```

Your code:

```
#include <some_public_header.h>

SomeStruct s;
```

It thinks that you should include `some_private_header.h` instead because it's really that header that defines the `SomeStruct`. There is the `iwyu.map` file in the project's root used to define such relationships when IWYU cannot detect them by itself.

2022-11-22 18:51 UTC, zenseii commented
Thanks, @oleg-derevenetz ! I was about to attempt addressing this, but you beat me to it in https://github.com/ihhub/fheroes2/pull/6244. We should add your PR's changes to this PR once yours has been merged.

2022-11-28 22:19 UTC, ihhub commented on src/fheroes2/game/game_scenarioinfo.cpp
> +            // Add offset shift because the original difficulty icons have irregular spacing.
In this case we will leave it as it is.

2022-11-28 22:42 UTC, ihhub reviewed
Hi @HaveFun91 and @zenseii , I put few more comments here. Could you please check them?

2022-11-28 22:42 UTC, ihhub commented on src/fheroes2/kingdom/race.cpp
> +std::string Race::DoubleLinedString( int race )
Please return const char * here as _() call returns the same type.

2022-11-28 22:42 UTC, ihhub commented on src/fheroes2/kingdom/race.cpp
> +        break;
Here we should actually assert because it is not an expected logic.

2022-11-28 22:42 UTC, ihhub commented on src/fheroes2/gui/player_info.cpp
> -
We can revert this change. No harm in having an empty line for separation🙂

2022-11-30 00:14 UTC, zenseii commented
Hi @ihhub.

I've addressed all the things I wanted to with this PR. It'd be great if you could review this too. There's a slight misaligning of 1px of the single lined necromancer class string, but all the other classes are correctly aligned so I'm not sure what to do there and I don't really want to spend time trying lots of different values for max lenght and for the x offset.

2022-12-03 01:03 UTC, ihhub approved these changes

2022-12-03 01:04 UTC, merged

2022-12-03 01:04 UTC, ihhub commented
@HaveFun91 and @zenseii , thank you so much for handling this issue!