Fixed issue with kingdom overview scrollabar not remembering position
ihhub/fheroes2 pull request #5990
Opened 2022-10-16 19:14 UTC by felix642

closes #1497

To preserve compatibility with the old save files. I have decided to store both scroll bars position in the same variable (_topItemInKingdomView). 16 first bits are used for the castle index and 16 last bits are used for the hero index.

This means that we can have a maximum of 32 000 heroes before something start to break which looks safe to me.

2022-10-16 19:24 UTC, oleg-derevenetz commented
Hi @felix642 there is apparently wrong issue linked to this PR.

2022-10-16 20:05 UTC, felix642 commented
> Hi @felix642 there is apparently a wrong issue linked to this PR.

You are right! I have update the description.

2022-10-16 20:57 UTC, oleg-derevenetz commented
> To preserve compatibility with the old save files. I have decided to store both scroll bars position in the same variable (_topItemInKingdomView). 16 first bits are used for the castle index and 16 last bits are used for the hero index.

Although this approach is undoubtedly a working one, it looks unnecessary quirky IMHO. Initially, a similar approach was used when storing adventure map data, but we are now gradually moving away from it by using separate variables for each kind of data instead of packing many different fields into the one variable and using bitmasks to load and store these fields. So I suggest to consider another approach: use different variables and make the backwards-compatible changes to the savefile structure in a usual way (bump the savefile version and use temporary code to handle the previous savefile versions).

2022-10-19 15:45 UTC, felix642 commented
HI @oleg-derevenetz, I have updated the implementation and both values are stored in different variables now.

I'm not super familiar with the versioning system of saving files, so I would appreciate it if you could double-check to make sure that I correctly implemented everything. I ran some tests and everything seems to be working smoothly but I just want to make sure.

2022-10-19 19:15 UTC, oleg-derevenetz requested changes
Hi @felix642 I just left a few comments, please take a look when you have time.

2022-10-19 19:15 UTC, oleg-derevenetz commented on src/fheroes2/kingdom/kingdom.cpp
> +    if ( Game::GetLoadVersion() >= FORMAT_VERSION_0921_RELEASE ) {
This check is not needed here, just write the new field to the stream as usual, because we always create the save file of the latest possible version.

2022-10-19 19:15 UTC, oleg-derevenetz commented on src/fheroes2/kingdom/kingdom.cpp
> +    if ( Game::GetLoadVersion() >= FORMAT_VERSION_0921_RELEASE ) {
It would be good to add the `static_assert()` before this line:

```cpp
static_assert( LAST_SUPPORTED_FORMAT_VERSION < FORMAT_VERSION_0921_RELEASE, "Remove the check below." );
```

This will automatically break the build when the `LAST_SUPPORTED_FORMAT_VERSION` become equal to `FORMAT_VERSION_0921_RELEASE` and we will not forget to remove this check, that will become obsolete.

2022-10-19 19:15 UTC, oleg-derevenetz commented on src/fheroes2/kingdom/kingdom.cpp
> +        kingdom._topHeroInKingdomView = kingdom._topCastleInKingdomView;
Are you sure they should be the same if there is no `_topHeroInKingdomView` in the savefile? Maybe set it to -1 by default?

2022-10-19 19:15 UTC, oleg-derevenetz commented on src/fheroes2/system/save_format_version.h
> +    FORMAT_VERSION_0921_RELEASE = 9950,
Please set the `CURRENT_FORMAT_VERSION` below to the `FORMAT_VERSION_0921_RELEASE`. The idea is that we always create save files of the latest possible version, but we have special fallbacks if we are trying to load an older save file.

2022-10-19 19:38 UTC, felix642 commented on src/fheroes2/kingdom/kingdom.cpp
> +    if ( Game::GetLoadVersion() >= FORMAT_VERSION_0921_RELEASE ) {
You are right! Thank you.

2022-10-19 19:39 UTC, felix642 commented on src/fheroes2/kingdom/kingdom.cpp
> +    if ( Game::GetLoadVersion() >= FORMAT_VERSION_0921_RELEASE ) {
Done, thank you.

2022-10-19 19:39 UTC, felix642 commented on src/fheroes2/kingdom/kingdom.cpp
> +        kingdom._topHeroInKingdomView = kingdom._topCastleInKingdomView;
The default constructor already sets the value to -1. So I have simply removed this branch.

2022-10-19 19:53 UTC, oleg-derevenetz reviewed
Hi @felix642 I just left two questions (in fact one :), please take a look when possible.

2022-10-19 19:53 UTC, oleg-derevenetz commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +            _topHeroInKingdomView = listStats->getTopId();
Why we are remembering the top hero before switching to the hero screen (while in fact we are currently on the castle screen)?

2022-10-19 19:53 UTC, oleg-derevenetz commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +            _topCastleInKingdomView = listStats->getTopId();
Why we are remembering the top castle before switching to the castle screen (while in fact we are currently on the hero screen)? Shouldn't it be vice-versa?

2022-10-19 19:58 UTC, felix642 commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +            _topCastleInKingdomView = listStats->getTopId();
See previous comment.

2022-10-19 20:49 UTC, oleg-derevenetz approved these changes

2022-10-21 01:00 UTC, ihhub approved these changes

2022-10-21 01:00 UTC, ihhub commented
Hi @Branikolog , can you please verify this pull request?

2022-10-21 10:29 UTC, Branikolog approved these changes
Everything works fine!

2022-10-21 13:49 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +    }
Hi @felix642 , I forgot to check this but for else condition we need to reset the newly added variable to `-1`. Could you please add this?

2022-10-22 15:23 UTC, merged

2022-10-22 15:23 UTC, ihhub commented
@felix642 , a bunch of thanks for fixing this problem!