add and fix hungarian translation
ihhub/fheroes2 pull request #5995
Opened 2022-10-19 13:06 UTC by leinadsened

2022-10-19 13:14 UTC, zenseii commented
Hi, @leinadsened.

Thank you for this contribution!

Funny, I was just thinking about adding Hungarian as an option within the game. I'll try to make a PR with that shortly.

I'll also ask if someone who knows Hungarian can review your changes.

2022-10-19 13:50 UTC, zenseii requested changes
Hi, @leinadsened.

I've just reviewed your PR using deepl because I don't know Hungarian but this is our minimum requirement for langauge reviews.

It looks good and I only had two small comments which it would be great if you could have a look at when you have the time.

We were also lucky enough to have user anon569 from our Discord server swiftly review this PR and give it a good-to-go.

2022-10-19 13:50 UTC, zenseii commented on files/lang/hu.po
> +msgstr "%{name} következő szintre lépett"
This seems to state that a hero gained a level. This is not what the English phrase says.

2022-10-19 13:50 UTC, zenseii commented on files/lang/hu.po
> +msgstr "%{name} következő szintre lépett"
This seems to state that a hero gained a level. This is not what tht eEnglish phrase says.

2022-10-19 13:59 UTC, leinadsened commented
Hi, @zenseii.

Thanks for reviewing my contribution, I've fixed what you requested.

2022-10-19 15:26 UTC, leinadsened commented on files/lang/hu.po
> +msgstr "%{name} kikapcsolta az automata harcot"
Sorry, my bad, it should be fixed now.

2022-10-19 15:31 UTC, zenseii requested changes
Hi @leinadsened.

I left a few more comments thanks to the review of @undef21.
Please have a look at them when you have the time to.

2022-10-19 15:31 UTC, zenseii commented on files/lang/hu.po
> +msgstr "Egy- vagy többszemélyes játék indítása."
Should there be a space after the hyphen here?
```suggestion
msgstr "Egy-vagy többszemélyes játék indítása."
```

2022-10-19 15:31 UTC, zenseii commented on files/lang/hu.po
> +msgstr "morál|Örjöngő!"
The part of "morale|" should not be translated or written in the string. This part is just there to give the translator a context about where the string is located and to differentiate it from equal strings elsewhere in the code.

This would be correct in this case:
```suggestion
msgstr "Örjöngő!"
```

This goes for all similar strings like the ones above and others that have "army|" etc. I haven't checked that this is the case

2022-10-19 15:34 UTC, zenseii requested changes

2022-10-19 15:34 UTC, zenseii commented on files/lang/hu.po
> +msgstr "Automata Varázslás"
Should this "V" be uppercase?

2022-10-19 15:36 UTC, zenseii commented
@leinadsened, could you also rename the PR to "Update the Hungarian translation" to fit in with the naming standard for translations for this project? Thanks!

2022-10-19 15:48 UTC, leinadsened commented on files/lang/hu.po
> +msgstr "Egy- vagy többszemélyes játék indítása."
The space is neccessary here, compound words are divided like that. "vagy" means "or" the hypen indicates that "Egy" (meaning single) belongs to "személyes" (meaning "number of people").

2022-10-19 15:51 UTC, zenseii commented on files/lang/hu.po
> +msgstr "Egy- vagy többszemélyes játék indítása."
I see, then you can simply ignore this comment 👍

2022-10-19 15:59 UTC, leinadsened commented on files/lang/hu.po
> +msgstr "Automata Varázslás"
Since the english string contains uppercase beggining words only, I thought it applies to hungarian too.

2022-10-19 16:02 UTC, zenseii commented on files/lang/hu.po
> +msgstr "Automata Varázslás"
No, this is only because in English the rule is to have such things like titles with all uppercase for the first letters of the words. Basically the translation should try to follow only Hungarian rules for writing.

2022-10-19 16:07 UTC, zenseii commented on files/lang/hu.po
> +msgstr "morál|Örjöngő!"
Yes, this is fine. By commit do you still mean within this same PR or in a new PR?

Whichever you choose is fine because this PR already has enough line changes to pass our minimum requirements for changes.

2022-10-19 16:50 UTC, zenseii requested changes
Thank you for the swift changes, @leinadsened!

I left some more comments here. One addresses why the build checks failed.

Please have a look at them when you have the time.

2022-10-19 16:50 UTC, zenseii commented on files/lang/hu.po
> +msgstr "Kevés (1-4)"
I'm aware this is from the the old translation but if you don't mind changing it then we should either only have `"Kevés" `or `"(1-4)"`. However, we need to be consistent with all these strings and preferrably we will use only letters like ex. `"Kevés"`, because this is most true to the intent of the English original.

2022-10-19 16:50 UTC, zenseii commented on files/lang/hu.po
> +msgstr "%{morale} Morál
This is missing a `"` at the end.
Also please remove the `#, fuzzy` from above. It is used to mark a string as not good and will force the use of the English original instead of the translation when Hungarian is selected.

In addition I believe "Morál" should be lowercase here because %{morale} will be replace with either Good or Bad.
What do you think, @leinadsened ?

2022-10-19 16:50 UTC, zenseii commented on files/lang/hu.po
> +msgstr "%{luck} Szerencse"
Should `Szerencse` be lowercased?

2022-10-19 16:59 UTC, zenseii requested changes
I left some repetitive comments about more fuzzied strings so that they are easier to track and solve.
I'm only commenting these since you touched on the strings. I'm not asking you to go through every fuzzy mark in the translation.

2022-10-19 16:59 UTC, zenseii commented on files/lang/hu.po
>  #, fuzzy
Please unfuzzy this is the translation is good.

2022-10-19 16:59 UTC, zenseii commented on files/lang/hu.po
>  #, fuzzy
Please unfuzzy this is the translation is good.

2022-10-19 16:59 UTC, zenseii commented on files/lang/hu.po
>  #, fuzzy
Please unfuzzy this is the translation is good.

2022-10-19 17:41 UTC, anon569 commented on files/lang/hu.po
> +"Nyisd meg a Hős Képernyőt hogy megnézhesd az összes információt a hősről."
A hogy előtt nincs vessző.

2022-10-20 10:21 UTC, leinadsened commented on files/lang/hu.po
> +msgstr "Állítsd be a harci műveletek és animációk gyorsaságát."
Szia. Köszönöm az észrevételt, javítottam mindkét részt.

2022-10-20 10:22 UTC, leinadsened commented on files/lang/hu.po
> +msgstr "%{morale} Morál
Thanks, this is the same case as the "Auto Spell Casting" one, I've fixed it both, and unfuzzied the strings.

2022-10-20 11:08 UTC, zenseii approved these changes
This looks good to me!
@anon569, could you enter the latest commit to only view the changes there and see if your comments were addressed? Thanks!

2022-10-20 12:02 UTC, zenseii commented
Hi @ihhub, this PR is ready for you to take a look at when you have the time to.

2022-10-20 14:37 UTC, merged

2022-10-20 14:37 UTC, ihhub commented
@leinadsened , huge thanks for your contribution to the project!