Update extract_homm2_resources.ps1
ihhub/fheroes2 pull request #5999
Opened 2022-10-19 19:45 UTC by GeorgeK1ng

Added support for extracting resources from orignal game released in Gold Edition by CDPROJEKT in Czech Republic in 2002. All needed files are automatically grabbed from installed game path + drive path too. In my original release is needed CD to play as it also have some of game files.

With this modification is not needed manual input and everything is done automatically. In my tests was mounted game ISO, then installed game, ISO keep mounted and then launch grabbing script. No issues detected. Test was done under Windows XP SP3

2022-10-19 20:04 UTC, oleg-derevenetz commented
Hi @GeorgeK1ng please put the indentation in order and keep changes minimal.

2022-10-19 20:16 UTC, GeorgeK1ng commented
I have fixed spacing and minimized changes in last code modification

2022-10-19 20:45 UTC, oleg-derevenetz requested changes
Hi @GeorgeK1ng I just left a few comments, please take a look when you have time.

It is also interesting what will happen with this script if there will be no disk in the CD drive when it is launched by the user?

2022-10-19 20:45 UTC, oleg-derevenetz commented on script/homm2/extract_homm2_resources.ps1
> +            	$DrivePath = $subkey.GetValue("CDDrive")
I have an impression that this temporary variable is not needed, because it is not used anywhere except the assignment below, so we just can assign the `$subkey.GetValue("CDDrive")` to the `$homm2DrivePath` below directly.

2022-10-19 20:45 UTC, oleg-derevenetz commented on script/homm2/extract_homm2_resources.ps1
> +
Now `$homm2Dir` may become `$null` (because `$homm2DrivePath` may become `$null`, moreover, this is its "usual value" in most cases), we need to check this before entering the inner loop:

```
if ($null -Eq $homm2Dir) {
    continue
}
```

2022-10-19 20:56 UTC, GeorgeK1ng reviewed
As this is my first attempt in PowerShell script, I'm happy you improved my mod

2022-10-19 20:58 UTC, GeorgeK1ng reviewed
OK

2022-10-19 21:00 UTC, GeorgeK1ng commented on script/homm2/extract_homm2_resources.ps1
> +
Thanks, I haven't expected this behaviour with $null

2022-10-19 21:13 UTC, oleg-derevenetz commented
Hi @GeorgeK1ng I have an impression that you forgot to push the requested changes.

2022-10-19 22:10 UTC, GeorgeK1ng commented
@oleg-derevenetz I commited it now

2022-10-20 00:51 UTC, oleg-derevenetz commented
Hi @GeorgeK1ng I just made a few minor modifications, could you please verify whether this script still works for your case (for a legacy installation with CD)?

2022-10-20 13:13 UTC, GeorgeK1ng commented
Yes it works

![image](https://user-images.githubusercontent.com/98261225/196958247-c9f0c32d-d5b2-475c-a1ee-c6a7c4c8040f.png)

2022-10-20 13:16 UTC, oleg-derevenetz approved these changes

2022-10-20 14:27 UTC, merged

2022-10-20 14:28 UTC, ihhub commented
@GeorgeK1ng , thank you very much for your contribution to the project!

2022-10-20 14:29 UTC, oleg-derevenetz commented
> [offtopic] Windows XP with fheroes2. Wow!

It won't be for long 🙋‍♂️