View World Map Symbols positioning (#4753)
ihhub/fheroes2 pull request #6017
Opened 2022-10-21 16:14 UTC by HaveFun91

Close #4753

2022-10-21 16:27 UTC, HaveFun91 commented
@LeHerosInconnu i've made some improvements also based on Zoom Level of the map. Could you check whether it is ok now?

2022-10-21 17:40 UTC, oleg-derevenetz commented on src/fheroes2/kingdom/view_world.h
> +struct IconOffset
Hi @HaveFun91 if this struct is used just in the `view_world.cpp`, please move it to the anonymous namespace in this file. There is no reason to have it in the header file.

2022-10-21 18:24 UTC, LeHerosInconnu commented
@HaveFun91.

I will take a look at it tomorow. :)

2022-10-22 02:06 UTC, ihhub requested changes
Hi @HaveFun91 , I left several comments in this pull request. Would you mind to take a look at them?

2022-10-22 02:06 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        std::pair<MP2::MapObjectType, ViewWorld::ZoomLevel> key = std::make_pair( objectType, zoomLevel );
This variable can be `const`.

2022-10-22 02:06 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    IconOffset GetIconOffset( MP2::MapObjectType objectType, ViewWorld::ZoomLevel zoomLevel )
Since this function is only called from one place we can accept `const std::pair<MP2::MapObjectType, ViewWorld::ZoomLevel> & key` instead of copying parameters 2 times. And call this function with making a pair.

2022-10-22 02:06 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +            return iconsOffsetMap.at( key );
Here we are doing 2 search calls. We need to use an iterator:
```cpp
auto iter = iconsOffsetMap.find( key );
if ( iter != iconsOffsetMap.end() ) {
    return iter->second;
}
```

2022-10-22 02:06 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    };
Please remove this structure and use `fheroes2::Point` structure.

2022-10-22 12:28 UTC, HaveFun91 commented on src/fheroes2/kingdom/view_world.cpp
> +    IconOffset GetIconOffset( MP2::MapObjectType objectType, ViewWorld::ZoomLevel zoomLevel )
Well... but wouldn't it be better to leave implementation details to inside function? I know we use it once, but I think it's nice encapsulation and maybe it's better to leave it as it is? Since anyway we have to create a pair I don't see any performance overhead here.

2022-10-22 12:33 UTC, HaveFun91 commented on src/fheroes2/kingdom/view_world.cpp
> +    IconOffset GetIconOffset( MP2::MapObjectType objectType, ViewWorld::ZoomLevel zoomLevel )
I made some change to pass value by reference so no copy happens if i get it right.

2022-10-22 19:21 UTC, LeHerosInconnu commented
@HaveFun91.

> @HaveFun91.
> 
> I will take a look at it tomorow. :)

I get this window when I try to run the executable ([fheroes2_windows_x64_SDL2.zip](https://github.com/ihhub/fheroes2/suites/8908943617/artifacts/407960487)) :

![Crash 22 10 2022 01](https://user-images.githubusercontent.com/43583994/197358721-80f312e6-dea6-4d01-8487-2f165f2189a7.png)

2022-10-23 03:09 UTC, ihhub requested changes

2022-10-23 03:09 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +    fheroes2::Point GetIconOffset( const MP2::MapObjectType & objectType, const ViewWorld::ZoomLevel & zoomLevel )
Passing parameters by const reference is not advisable for POD (plain old data) such as int. Please remove `&` from both of variables.

2022-10-23 10:24 UTC, ihhub commented
Hi @HaveFun91 , could you please rebase this branch from master so @LeHerosInconnu will be able to test it?

2022-10-23 18:27 UTC, HaveFun91 commented
@ihhub, @LeHerosInconnu rebased, should work now.

2022-10-24 05:08 UTC, ihhub approved these changes

2023-02-23 16:53 UTC, ihhub commented
Hi @Districh-ru , did we fix it recently?

2023-02-23 17:02 UTC, ihhub commented
I am closing this pull request as the fix was implemented in another pull request.

2023-02-23 17:02 UTC, closed without merging

2023-02-23 17:02 UTC, Districh-ru commented
> Hi @Districh-ru , did we fix it recently?

Hi, @ihhub. Yes, the fix was made in #6562. But @LeHerosInconnu has some questions which I think were solved by #6624.