Generate several MAX/MIN buttons with new method
ihhub/fheroes2 pull request #6031
Opened 2022-10-23 19:28 UTC by zenseii

2022-10-24 08:59 UTC, ihhub requested changes

2022-10-24 08:59 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    out.resize( GetICN( ICN::RECRUIT, 4 + i ).width() - 6, GetICN( ICN::RECRUIT, 4 + i ).height() - 5 + i );
Since `GetICN()` is not an inline-function it should be good to cache it:
```cpp
Sprite & originalButton = GetICN( ICN::RECRUIT, 4 + i );
```

2022-10-24 10:27 UTC, Branikolog commented
> Hi @ihhub
> 
> I believe I might need to make the button wider to allow for languages that use 4 letters? ![image](https://user-images.githubusercontent.com/12501091/197502436-8f1c9f04-4375-45f5-a273-d6f952bab8af.png)
> 
> This would also become a problem in the creature recruit dialog when that MAX button will be generated, so I'm not sure how we want to deal with this exactly. The MIN and MAX buttons need to be the same width too.
> 
> Maybe we could find the width of the translated text and use that to determine how wide the buttons should be? This should probably be a generally available function.

Hi, @zenseii !

In Russian resources developers managed to fit the text into this button by making letters more tight and reducing the spaces between letters where possible.
![MAX](https://user-images.githubusercontent.com/55348946/197505844-77964c6c-b1df-4397-910c-d8ee6ae3015e.png)

2022-10-24 10:32 UTC, zenseii commented
> In Russian resources developers managed to fit the text into this button by making letters more tight and reducing the spaces between letters where possible.

Hi @Branikolog.

I've seen that the Russian original has very tight space between the letters. I know how to simply make all letters tighter just for Cyrillic, but I'm not sure this is the best way to go either... Also, note that these Russian original buttons were made in an image editing program and were not generated by code like we do, which is why they were able to adjust the text on every single button. Ours will need to be a general solution.

2022-10-24 10:44 UTC, Branikolog commented
@zenseii 

>Also, note that these Russian original buttons were made in an image editing program and were not generated by code like we do, which is why they were able to adjust the text on every single button. Ours will need to be a general solution.

Yeah, it's obvious. 
On the other side we can redraw some letters so they become more tight and the needed text would fit without individual adjustment of the text itself. I also believe, there could be even implemented a special law that could adjust spacing depending on edge pixels of both nearby letters. But I'm not sure it would be a trivial task... :)

2022-10-24 12:54 UTC, ihhub commented
Hi @zenseii and @Branikolog , we can make the button wider but I would suggest to keep the width the same for all languages.

I can check how to do it nicely.

2022-10-24 15:21 UTC, zenseii commented
I believe we can easily adjust the button length of any of these buttons using the template buttons we are currently using anyways:
![image](https://user-images.githubusercontent.com/12501091/197563285-29f0df39-9ff3-498a-84c8-7bbc8ae85726.png)

It's just a matter of extending the middle part, and if we want to we can use them for larger buttons too by extending upwards.

2022-10-27 15:46 UTC, ihhub commented
> I believe we can easily adjust the button length of any of these buttons using the template buttons we are currently using anyways: ![image](https://user-images.githubusercontent.com/12501091/197563285-29f0df39-9ff3-498a-84c8-7bbc8ae85726.png)
> 
> It's just a matter of extending the middle part, and if we want to we can use them for larger buttons too by extending upwards.

Yes, we can. I suggest to do everything in stages. We can proceed with changes in this pull request as of now and later add a separate chunk of code to extend the button width.

2022-10-27 15:52 UTC, zenseii commented on src/fheroes2/agg/agg_image.cpp
> +                    out.resize( GetICN( ICN::RECRUIT, 4 + i ).width() - 6, GetICN( ICN::RECRUIT, 4 + i ).height() - 5 + i );
I've done this in the latest commit.

2022-10-27 15:57 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    fheroes2::Copy( GetICN( baseIcnId, 11 + i ), 0, 0, out, 0, 0, originalButton.width() - 13 + i, originalButton.height() - 5 + i );
A small optimization: we can also cache `GetICN( baseIcnId, 11 + i )` call and it will slightly improve code readability.

2022-10-29 02:41 UTC, merged

2022-10-29 02:41 UTC, ihhub commented
@zenseii , huge thanks for making this change!