Bulgarian Translation 13
ihhub/fheroes2 pull request #6034
Opened 2022-10-24 09:50 UTC by Effektus

Left 500 Rows

2022-10-24 11:01 UTC, zenseii requested changes
Hi, @Effektus.

I left some comments here. Please have a look at them when you have the time.

2022-10-24 11:05 UTC, Effektus commented on files/lang/bg.po
> +"научих те на всичко, което мога."
No

2022-10-24 11:07 UTC, Effektus commented on files/lang/bg.po
> +"научих те на всичко, което мога."
No

2022-10-24 11:31 UTC, zenseii requested changes

2022-10-24 11:31 UTC, zenseii commented on files/lang/bg.po
>  "Включване/изключване на цветните курсори. Цветните курсори изглеждат по-"
The Bulgarian translation does not seem to have been updated to the changes to this phrase?

2022-10-24 11:31 UTC, zenseii commented on files/lang/bg.po
>  msgstr "Провери всички горещи клавиши, използвани в играта."
The translation should say that you can configure the hotkeys too. This string was marked as fuzzy because the English string had been changed and therefore the translated string needed to be changed too.

2022-10-24 12:05 UTC, zenseii requested changes

2022-10-24 12:05 UTC, zenseii commented on files/lang/bg.po
> +#, fuzzy
It seems all the fuzzy marks have returned.

2022-10-24 13:11 UTC, Effektus commented on files/lang/bg.po
> +#, fuzzy
How to translate this one?
![image](https://user-images.githubusercontent.com/12934196/197533544-d9583ca9-c005-43b7-826f-8a81ef4526cd.png)

2022-10-24 14:35 UTC, zenseii commented on files/lang/bg.po
> +#, fuzzy
It's in the credits and refers to someone who knows how to play the instrument called Alto Sax.

2022-10-24 14:39 UTC, Effektus commented on files/lang/bg.po
> +#, fuzzy
Ok Thanks

2022-10-25 17:05 UTC, zenseii commented
Hi @Effektus.

When you've commited the fix to the fuzzy marks we can move ahead with finalizing this PR.

2022-10-25 18:13 UTC, Effektus commented
> When you've commited the fix to the fuzzy marks we can move ahead with finalizing this PR.

I can't understand what more to fix???

2022-10-25 18:15 UTC, zenseii commented
> I can't understand what more to fix???

Please relax. I believe you didn't commit the corrections of the fuzzy marks being reverted. Just have a look at the "Files changed" pane.

2022-10-25 18:22 UTC, Effektus commented
> > I can't understand what more to fix???
> 
> Please relax. I believe you didn't commit the corrections of the fuzzy marks being reverted. Just have a look at the "Files changed" pane.

I committed the corrections of the fuzzy marks.

2022-10-25 18:24 UTC, zenseii commented
> I committed the corrections of the fuzzy marks.

It has not been commited in this PR as you can see. Maybe it got commited to a different branch?

2022-10-25 18:25 UTC, zenseii commented
Like here:
![image](https://user-images.githubusercontent.com/12501091/197852310-2b797d06-75c3-47d8-8d68-8016d8a05245.png)

2022-10-25 18:47 UTC, zenseii approved these changes
I just left one optional thing to look at, @Effektus. Please have a look when you have the time.

2022-10-25 18:47 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Каменни литове"
I'm not suggesting this translation should change, but the building is this:
![image](https://user-images.githubusercontent.com/12501091/197856372-36bfa893-2a69-4b5a-ba16-98a33953b00f.png)
In case you're not familiar with it it's a portal/teleporter. Some translations have translated it as portal or transporter in fact.

2022-10-25 18:59 UTC, zenseii approved these changes

2022-10-27 15:07 UTC, ihhub approved these changes

2022-10-27 15:07 UTC, merged

2022-10-27 15:07 UTC, ihhub commented
@Effektus , thank you so much for this translation improvement!