Modify and fix base font characters
ihhub/fheroes2 pull request #6043
Opened 2022-10-25 18:05 UTC by zenseii

This adds logic that will modify the base fonts on the fly.

The modifying logic was placed in `ui_font.cpp` to maintain current structure and because the function updating the font shadow is local to that file.

Lowercase k for both normal and small font have been edited as an example and these were also requested by many users.
This PR fixes other font issues like the `%` and `-`.

New `k`:
![image](https://user-images.githubusercontent.com/12501091/197849520-91cd86a6-4cfb-4fec-be76-3cf6ad9cdd83.png)
![image](https://user-images.githubusercontent.com/12501091/197849597-0dc90b3c-4416-4d68-a341-276a0f4fbecc.png)

Fixed `%` sign:
![image](https://user-images.githubusercontent.com/12501091/198538334-34e9df3a-a960-4fb9-a086-c31109d1d5bb.png)
![image](https://user-images.githubusercontent.com/12501091/198538380-a5a7ac09-026d-4972-846b-d1e160153da6.png)

Fixed hyphen `-` (only normal font has issues):
![image](https://user-images.githubusercontent.com/12501091/198538467-eb174460-579c-451d-b6a5-50cc0f05d99d.png)

The Cyrillic `к` in CP1251 has been readjusted because it uses lowercase k for its generation.

Close #5514 
Close #4799

2022-10-27 15:14 UTC, ihhub requested changes

2022-10-27 15:14 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +        if ( normalFont ) {
Are we going to expand this function in the future? If not then I suggest to just put the code within `LoadModifiedICN()` function itself.
Also to not have any crashes it is good to check the size of `_icnVsSprite[id]` array to avoid out of boundaries element access.

2022-10-27 15:15 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +        if ( normalFont ) {
Ah, I got the point why we put this code to a separate function.

2022-10-27 15:18 UTC, ihhub requested changes

2022-10-27 15:18 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +    void editOriginalFont( std::vector<fheroes2::Sprite> & icnVsSprite, const bool normalFont )
Let's name it as `modifyBaseFont` as editing is usually done by humans.

2022-10-27 15:18 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +    void editOriginalFont( std::vector<fheroes2::Sprite> & icnVsSprite, const bool normalFont )
Also does it make more sense to just have 2 separate functions? It would improve code readability.

2022-10-27 15:18 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +            fheroes2::FillTransform( icnVsSprite[75], 4, 1, 5, 8, 1 );
We must check the size of `icnVsSprite` before doing something.

2022-10-28 05:37 UTC, zenseii commented on src/fheroes2/gui/ui_font.cpp
> +    void editOriginalFont( std::vector<fheroes2::Sprite> & icnVsSprite, const bool normalFont )
Sure! I will make `modifyBaseNormalFont` and `modifyBaseSmallFont` in `fheroes2` namespace and call these within `LoadModifiedICN`.

2022-10-28 05:57 UTC, zenseii commented on src/fheroes2/gui/ui_font.cpp
> +            fheroes2::FillTransform( icnVsSprite[75], 4, 1, 5, 8, 1 );
The functions now assert that `icnVsSprite` is not empty before doing anything.

2022-10-29 03:33 UTC, ihhub requested changes
Hi @zenseii , I put 2 more comments here. Could you please take a look at them?

2022-10-29 03:33 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +        assert( !icnVsSprite.empty() );
I would highly suggest to add this instead of the assertion:
```cpp
if ( icnVsSprite.size() < 96 ) {
    return;
}
```
as here we might try to access elements outside the container.

2022-10-29 03:33 UTC, ihhub commented on src/fheroes2/gui/ui_font.cpp
> +        assert( !icnVsSprite.empty() );
I would highly suggest to add this instead of the assertion:
```cpp
if ( icnVsSprite.size() < 96 ) {
    return;
}
```
as here we might try to access elements outside the container.

2022-10-29 06:06 UTC, ihhub approved these changes

2022-10-29 06:06 UTC, merged

2022-10-29 06:06 UTC, ihhub commented
@zenseii , thank you so much for polishing fonts!