Don't overwrite focus on game load
ihhub/fheroes2 pull request #6051
Opened 2022-10-28 00:07 UTC by felix642

When loading a save file, the current focus was being overwritten by the first hero. This PR changes this default behavior.

2022-10-29 03:37 UTC, ihhub requested changes
Hi @felix642 , I left 2 comments in this pull request. Would you mind to take a look when you have time?

2022-10-29 03:37 UTC, ihhub commented on src/fheroes2/gui/interface_focus.cpp
> +        iconsPanel.Select( castle );
It would be good to add a check whether the pointer is not nullptr.

2022-10-29 03:37 UTC, ihhub commented on src/fheroes2/gui/interface_focus.cpp
> +        iconsPanel.Select( hero );
It would be good to add a check whether the pointer is not nullptr.

2022-10-30 14:05 UTC, ihhub commented
Hi @Branikolog , can you please test this change?

2022-10-31 13:45 UTC, Branikolog commented
Hello, @ihhub & @felix642 !
I've noticed, that after loading game music doesn't start. Music starts only after refocus.

2022-11-03 00:42 UTC, felix642 commented
Hi @Branikolog, I have updated my PR. The sounds should now work properly when loading a save. Would you mind testing this PR again to make sure that everything works great? Thank you :)

2022-11-05 09:54 UTC, Branikolog approved these changes
Everything works fine now!

2022-11-05 17:16 UTC, merged

2022-11-05 17:16 UTC, ihhub commented
@felix642 , thank you very much for the fix!