Bulgarian Translation 14
ihhub/fheroes2 pull request #6053
Opened 2022-10-28 16:36 UTC by Effektus

400 Rows Left

2022-10-28 17:47 UTC, zenseii requested changes
Hi, @Effektus.

I left some few comments. Please have a look should you have the possibility.

2022-10-28 17:47 UTC, zenseii commented on files/lang/bg.po
> +"Фарът вече е под твой контрол и всичките ти кораби ще се придвижват всеки "
Using deepl it seems that this says that your ships will move every day and not that they will move further every day? Please ignore this if it's wrong.

2022-10-28 17:47 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Всичките ти %{monsters} са надградени до %{monsters 2}."
Please remove the white space from here.
```suggestion
msgstr "Всичките ти %{monsters} са надградени до %{monsters2}."
```

2022-10-28 17:47 UTC, zenseii commented on files/lang/bg.po
> +msgstr "„Имам нужда от %{count} %{res}.“"
Please use different quotation marks.

2022-10-30 21:01 UTC, zenseii approved these changes

2022-10-31 11:44 UTC, ihhub commented on files/lang/bg.po
> +"шепот: „Защо си дошъл? Тук си, за да призовеш силите на въздуха ли?“"
Hi @zenseii , do we have these quotation marks for Bulgarian? If not then we have to use `\"` symbol for these cases?

2022-10-31 11:45 UTC, ihhub commented on files/lang/bg.po
> +"шепот: „Защо си дошъл? Тук си, за да призовеш силите на въздуха ли?“"
@Effektus and @zenseii , I believe we should use `\"` as it is done everywhere else in the code.

2022-10-31 11:46 UTC, ihhub commented on files/lang/bg.po
> +"„Искаш ли да призовеш силите на водата?“"
The same comment here.

2022-10-31 11:46 UTC, zenseii commented on files/lang/bg.po
> +"шепот: „Защо си дошъл? Тук си, за да призовеш силите на въздуха ли?“"
Yep, I missed these.

2022-10-31 11:47 UTC, ihhub commented
Hi @Effektus , I left 2 comments here. Could you please take a look?

2022-11-01 01:30 UTC, merged

2022-11-01 01:31 UTC, ihhub commented
@Effektus , a huge thanks for polishing this translation!