Changed "Manual" string to "autoBattle|Manual" to separate it from game credits "Manual".
ihhub/fheroes2 pull request #6061
Opened 2022-10-29 15:27 UTC by Districh-ru

The word "Manual" has different meanings and is translated differently for the "game manual" and for "manual battales".

For example, it could not be correctly translated into Russian:
- for autobattles it should be translated: "Вручную";
- for game titles it should be translated: "Руководство по игре".

So, now in game credits there is incorrect translation:
![изображение](https://user-images.githubusercontent.com/113276641/197329797-63f93797-d9e3-44e5-b13f-87e4e7ee3b5b.png)
But it cannot be fixed in the translation file. Because this string ("Manual") is also used in autobattles settings dialog:
![изображение](https://user-images.githubusercontent.com/113276641/197329910-67dda95d-9e3a-4967-94de-32d0037f5adf.png) ![изображение](https://user-images.githubusercontent.com/113276641/197329963-c2f59cd2-4eaf-4eb6-a622-badef86709a8.png)

This PR replaces "Manual" with "autoBattle|Manual" in the 'dialog_system_options.cpp' and 'dialog_game_settings.cpp' files.

PS
This is my first PR for the game code, so I hope for your help with it. :)

2022-10-29 15:43 UTC, zenseii requested changes
Hi @Districh-ru.

The changes look good to me, however I believe we should add a context to the "Manual" string in the credits too then. Something like "credits|Manual", because this will remove any ambiguity.

2022-10-29 15:58 UTC, zenseii approved these changes

2022-10-29 15:58 UTC, Districh-ru commented
Hi @zenseii 
I did it. The string "Manual" is only in these three files.

2022-10-29 16:06 UTC, zenseii commented
> Hi @zenseii I did it. The string "Manual" is only in these three files.

Yep, thanks! I should also note that technically the engine tries to differentiate between "auto battle" and "auto resolve" of battles, in which the former refers to entering a battle and giving the computer the control of the moves and watching these take place, while the latter is the one where the battle is automatically solved before even entering the battle screen.

However, this terminology is admittedly not very clear so to me "autoBattle", which is also what I suggested in the other PR if I recall correctly, works perfectly fine and will be understood correctly by the translator.

2022-10-29 16:14 UTC, Districh-ru commented
> However, this terminology is admittedly not very clear so to me "autoBattle", which is also what I suggested in the other PR if I recall correctly, works perfectly fine and will be understood correctly by the translator.

So maybe change it to "battle|Manual", because "Manual" string is used for battle configuration. (The other two settings for Battle is "Auto Resolve" and "Auto, No Spells").

2022-10-29 16:24 UTC, zenseii commented
> > However, this terminology is admittedly not very clear so to me "autoBattle", which is also what I suggested in the other PR if I recall correctly, works perfectly fine and will be understood correctly by the translator.
> 
> So maybe change it to "battle|Manual" 

I'm not sure this is any better because you still have ambiguity which type of automatic battle this is talking about. While "Auto Battle" is a term most can understand. I don't think there's much need to spend more time figuring out what to call these things right now because the context you provided works perfectly fine, as I said.


> (The other two settings for Battle is "Auto Resolve" and "Auto, No Spells").

I believe "Auto, No spells" is just short for "Auto Resolve, No Spells" because the space is limited, so really as far as I've understood "Auto Battle" is technically when you click the "Auto" button in the lower left corner in the battle screen, while "Auto Resolve" is when you don't even enter the battle screen. My point is also that a context like "autoResolve" is too vague for a translator to easily understand.

In later games in the series Auto Resolve is referred to as "Quick Combat" and "Auto Battle" is exactly what I described it as above. However, we have not adopted these terms in fheroes2.  At least not yet.

2022-10-29 16:34 UTC, Districh-ru commented
@zenseii 
Thanks for the detailed explanation! :)

2022-11-01 01:34 UTC, ihhub commented
Hi @Districh-ru and @zenseii , we need to change translation files as well because we modified the original English sentence.

2022-11-01 03:03 UTC, Districh-ru commented
Hi @ihhub , ok, I'll do it today in the evening (after 9 hours).
I thought that translation files will be modified automatically)

2022-11-01 03:08 UTC, zenseii commented
> Hi @Districh-ru and @zenseii , we need to change translation files as well because we modified the original English sentence.

We would need to ask the translators for help for that because we don't know what is the correct translation for every language here.

2022-11-01 03:15 UTC, zenseii commented
@Districh-ru, I made an update to my comment.

2022-11-01 16:35 UTC, Districh-ru commented
@zenseii, thanks for the tip!
I installed and configured Cygwin, made a POT file and updated the PO files for translation.
I made a Russian translation and also tried to keep the correct translation for languages where "Manual" has already been translated.

2022-11-01 20:23 UTC, zenseii commented on files/lang/nb.po
> +msgstr "Guide"
```suggestion
msgstr "Håndbok"
```

2022-11-01 20:23 UTC, zenseii commented on files/lang/nb.po
>  msgstr "Manuelt"
```suggestion
msgstr "Manuell"
```

2022-11-01 20:25 UTC, zenseii commented on files/lang/it.po
> +msgstr "Manualmente"
```suggestion
msgstr "Manuali"
```

2022-11-02 02:55 UTC, Districh-ru commented on files/lang/it.po
> +#, fuzzy
```suggestion

```

2022-11-02 03:00 UTC, Districh-ru commented on files/lang/nb.po
> +msgstr "Guide"
```suggestion
msgid "credits|Manual"
msgstr "Håndbok"
```

2022-11-02 03:06 UTC, Districh-ru commented on files/lang/nb.po
> +msgstr "Guide"
@zenseii, thanks for correcting translations!
I applied your suggestions.

2022-11-02 03:09 UTC, Districh-ru commented on files/lang/nb.po
> +msgstr "Guide"
This suggestion didn't show up in the Files Changed tab (probably a Github bug), so I made my suggestion with those changes.

2022-11-03 18:09 UTC, zenseii requested changes
I requested some help from some of our contributors to the actively maintained translations, @Districh-ru . Hopefully they will have the time to help out.

I've already covered the languages I can help out with.

2022-11-03 18:09 UTC, zenseii commented on files/lang/fr.po
>  msgstr "Manuel"
Please remove the fuzzy too, @Districh-ru .
```suggestion
msgstr "Manuelles"
```

2022-11-03 18:09 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Guide"
Hi @1GodRage and @LeHerosInconnu.
According to the dictionary this translation works,
But I feel something more akin to Handbook is better.

2022-11-03 18:09 UTC, zenseii commented on files/lang/it.po
> +msgstr "Manuali"
Please remove fuzzy mark too, @Districh-ru 
```suggestion
msgstr "Manuale"
```

2022-11-03 18:09 UTC, zenseii commented on files/lang/pl.po
> +msgstr "Ręcznie"
Hi @Arthusppp, @Pulfiarz and @KaspianDev.

I would like to ask your help with these two strings if you have the time of course.

2022-11-03 18:46 UTC, Districh-ru commented on files/lang/fr.po
> +#, fuzzy
```suggestion
```

2022-11-03 18:49 UTC, Districh-ru commented on files/lang/fr.po
>  msgstr "Manuel"
OK

2022-11-03 18:54 UTC, Districh-ru commented on files/lang/it.po
> +#, fuzzy
```suggestion
```

2022-11-03 18:55 UTC, Districh-ru commented on files/lang/it.po
> +msgstr "Manuali"
OK

2022-11-03 18:56 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Guide"
Also if you have some ideas about how to translate this best too, @morgane-du-tweize , then please share 👍

2022-11-03 19:39 UTC, Effektus commented on files/lang/bg.po
> +msgid "autoBattle|Manual"
автоматичната битка/Ръчно
or
авто битка/Ръчно

2022-11-03 19:44 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Ръководство за играта"
Руководство по игре

2022-11-04 03:56 UTC, Districh-ru commented on files/lang/bg.po
> +msgstr "Ръководство за играта"
```suggestion
msgstr "Руководство по игре"
```
Thank you, @Effektus !

2022-11-04 03:56 UTC, Districh-ru commented on files/lang/bg.po
> +#, fuzzy
```suggestion
```

2022-11-04 03:57 UTC, Districh-ru commented on files/lang/bg.po
>  msgstr "Ръчно"
```suggestion
msgstr "Вручную"
```

2022-11-04 08:30 UTC, morgane-du-tweize commented on files/lang/fr.po
> +msgstr "Guide"
It depends on the context.
Basically : "manuel" : basic instructions. Tells how to play. Usually given with the game when you buy a physical copy (well it was like that in the 90's)
On steam, when browsing a game hub : guides tells you how to win (wakthroughs, achievements...) and it's directly translated to "guide" in french.

2022-11-04 08:57 UTC, zenseii commented on files/lang/fr.po
> +msgstr "Guide"
Thanks @morgane-du-tweize.
I vote for "Manuel" here in this case.

2022-11-04 14:54 UTC, Districh-ru commented on files/lang/fr.po
> +msgstr "Guide"
Thanks @morgane-du-tweize and @zenseii !
I'll also remove the fuzy mark.
```suggestion
msgstr "Manuel"
```

2022-11-04 14:55 UTC, Districh-ru commented on files/lang/fr.po
> +#, fuzzy
```suggestion
```

2022-11-06 06:31 UTC, Districh-ru commented on files/lang/ru.po
> +"POT-Creation-Date: 2022-11-01 18:49+0300\n"
Removed duplicate line
```suggestion
```

2022-11-06 06:37 UTC, Districh-ru commented on files/lang/bg.po
> +msgid "autoBattle|Manual"
The suggestion has applied. Thank you.

2022-11-07 20:03 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Ręcznie"
I suggest "Ręczna" here.

2022-11-07 20:03 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Przewodnik"
This is ok, please remove "#, fuzzy".

2022-11-08 03:03 UTC, Districh-ru commented on files/lang/pl.po
> +msgstr "Ręcznie"
```suggestion
msgstr "Ręczna"
```

2022-11-08 03:04 UTC, Districh-ru commented on files/lang/pl.po
> +#, fuzzy
```suggestion
```

2022-11-08 03:05 UTC, Districh-ru commented on files/lang/pl.po
> +msgstr "Przewodnik"
Hi @Arthusppp, thank you!

2022-11-08 03:05 UTC, Districh-ru commented on files/lang/pl.po
> +#, fuzzy
```suggestion
```

2022-11-08 14:05 UTC, Districh-ru commented
@zenseii, I applied the translators suggestions.

2022-11-08 17:18 UTC, zenseii approved these changes
All actively maintained translations have been covered.
This PR is ready for you to have a look at it when you have the time, @ihhub.

2022-11-11 00:47 UTC, merged

2022-11-11 00:47 UTC, ihhub commented
@Districh-ru , thanks a lot for this improvement!