Update AI logic for monster distribution and recruitment
ihhub/fheroes2 pull request #6063
Opened 2022-10-29 16:40 UTC by ihhub

- while hiring monsters in a castle put monsters to the slots with the same type of monsters
- while attending dwellings on map try to redistribute army before joining monsters
- add logic to hire some monsters from dwellings if they are payable

2022-10-29 19:05 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few proposals, please take a look when possible.

2022-10-29 19:05 UTC, oleg-derevenetz commented on src/fheroes2/army/army.h
> +    bool JoinTroop( const Monster & mons, uint32_t count, bool emptySlotFirst );
Are you sure there is a need to remove the default value for this argument? Default arguments are handy sometimes :)

2022-10-30 01:42 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +        if ( troop == nullptr || !troop->isValid() ) {
Sure. We also need to remove this weird way to allocate memory for individual members instead of storing values / objects.

2022-10-30 01:44 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +    for ( auto & [id, slotCount] : monsterIdVsSlotCount ) {
Not, no reason.

2022-10-30 01:51 UTC, ihhub commented on src/fheroes2/army/army.h
> +    bool JoinTroop( const Monster & mons, uint32_t count, bool emptySlotFirst );
I removed the default value during the development to make sure that the logic is correct everywhere. The biggest problem with default values in cases like this that it is hard to understand what's going on in the code before you check these default arguments. So once I removed the value I found the place which was causing the incorrect logic.

If you think that it is good to put the default value back I am okay to do this :)

2022-10-30 10:47 UTC, oleg-derevenetz commented on src/fheroes2/army/army.h
> +    bool JoinTroop( const Monster & mons, uint32_t count, bool emptySlotFirst );
Hi @ihhub Well, as far as I can see, in the vast majority of places this argument is `false`, so it might be handy to have it `false` by default. But it's up to you to decide :) LGTM.

2022-10-30 10:47 UTC, oleg-derevenetz approved these changes

2022-10-30 12:46 UTC, ihhub commented on src/fheroes2/army/army.h
> +    bool JoinTroop( const Monster & mons, uint32_t count, bool emptySlotFirst );
Let's stick to no default parameter then since it would be obvious in the future for the new code.

2022-10-30 12:46 UTC, merged