Fix touchscreen and mouse software emulation
ihhub/fheroes2 pull request #6092
Opened 2022-11-05 14:22 UTC by ihhub

relates to #6008
relates to #5466
relates to #5419
close #5778

2022-11-05 16:26 UTC, oleg-derevenetz commented
I got the impression that it would be difficult to distinguish "left press/click" from "right press/click". If first touch event arrives a bit earlier, then we already have a "left press/click", and if both events arrive at the same time, then where should be the cursor - under the first finger or under the second finger?

2022-11-05 17:03 UTC, ihhub commented
> 

Hi @oleg-derevenetz , yes, if a user presses two fingers at the same time then it's impossible to know which one. The idea is to press one finger first and then another. I haven't found any better way to do this as of now.

2022-11-05 17:47 UTC, oleg-derevenetz commented
@ihhub I was not able to get it to work this way yet :) For example, when I put my first finger on the "NEW GAME" item in the main menu, and then put my second finger somewhere else, I don't see the help dialog. When I release both fingers, I usually get the "New game" menu. But, when I put both fingers on screen at the same time, I usually get that hep dialog, but sometimes it is related to a thing under my first finger and sometimes - to a thing under my second finger :)

2022-11-05 17:57 UTC, ihhub commented
Hi @oleg-derevenetz , the idea is different. I put my first finger outside the rendering area (black area). Then the second finger on the item I want to left click. If my second finger blocks the view I still hold it and move it away keeping the popup dialog active.

2022-11-05 18:01 UTC, oleg-derevenetz commented
@ihhub Ah yes, this works :) But this definitely needs some guide, because this mechanics is not obvious (although undoubtedly witty).  Also we need to always maintain that black area somewhere.

2022-11-05 18:49 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few suggestions, please take a look when possible.

2022-11-05 18:49 UTC, oleg-derevenetz commented on src/engine/localevent.cpp
>          if ( ( modes & MOUSE_MOTION ) && redraw_cursor_func ) {
The `modes & MOUSE_MOTION` check seems redundant here, because we just set this mode a few lines above.

2022-11-05 18:49 UTC, oleg-derevenetz commented on src/engine/localevent.cpp
> +            if ( ( modes & MOUSE_MOTION ) && redraw_cursor_func ) {
The `modes & MOUSE_MOTION` check seems redundant here, because we just set this mode a few lines above.

It seems that the same extra check is in the `LocalEvent::ProcessControllerAxisMotion()` as well - we set the `MOUSE_MOTION` and then check for it a few lines below, although it does not seem that this flag could have been reset between these lines.

2022-11-05 19:09 UTC, oleg-derevenetz commented
Also I have an impression that cursor is shifted in regard to the touch point, and the farther the touch point is from the upper left edge of the screen (0:0), the greater the shift.

2022-11-06 02:57 UTC, Laserlicht commented
> Hi @oleg-derevenetz , the idea is different. I put my first finger outside the rendering area (black area). Then the second finger on the item I want to left click. If my second finger blocks the view I still hold it and move it away keeping the popup dialog active.

I would find the other solution better. So touch the relevant element and then touch anything with the second finger to open the window. This is how it is implemented in VCMI. Works quite well.

Because the "outside the rendering area" does not always exist. If you take a suitable resolution (aspect ratio), there is no black area. Besides, this is not intiutive.

But can imagine that this is more difficult to implement.

2022-11-06 03:41 UTC, ihhub commented
As I see multiple concerns with the proposed approach I will create another pull request to address mouse positioning with software rendering mode as touchscreen is a separate topic.

2022-11-10 18:52 UTC, oleg-derevenetz commented
Hi @ihhub I believe we can use the "right mouse button" part of this PR in the new release (but not the part with software-rendered mouse cursor, because it has objective issues). While "right mouse button" logic here is definitely not obvious, it at least works and can be used until a new logic is invented.

2022-11-11 00:40 UTC, ihhub commented
> Hi @ihhub I believe we can use the "right mouse button" part of this PR in the new release (but not the part with software-rendered mouse cursor, because it has objective issues). While "right mouse button" logic here is definitely not obvious, it at least works and can be used until a new logic is invented.

We can do this. I will update this PR today.

2022-11-11 16:49 UTC, ihhub commented
@oleg-derevenetz , now I spot another bug: the application crashes when I try to switch into fullscreen mode on an Android phone :(

2022-11-11 16:52 UTC, oleg-derevenetz commented
@ihhub

> now I spot another bug: the application crashes when I try to switch into fullscreen mode on an Android phone :(

I never tried to switch fullscreen mode on Android dynamically, only by changing the config file. Did this work at all at least once?

2022-11-11 16:53 UTC, zenseii commented
> @ihhub
> 
> > now I spot another bug: the application crashes when I try to switch into fullscreen mode on an Android phone :(
> 
> I never tried to switch fullscreen mode on Android dynamically, only by changing the config file. Did this work at all at least once?

I did it today with a snapshot build from master from today and did not experience this. I'll find out the exact commit I grabbed.

2022-11-11 16:54 UTC, ihhub commented
@oleg-derevenetz and @zenseii , the crash happens with my changes. I tested master branch and it works fine. I shall create a separate PR for `__linux__` macro fix.

2022-11-11 16:59 UTC, ihhub commented
> @ihhub
> 
> > now I spot another bug: the application crashes when I try to switch into fullscreen mode on an Android phone :(
> 
> I never tried to switch fullscreen mode on Android dynamically, only by changing the config file. Did this work at all at least once?

Don't change config file. Use our new fancy UI option within the game!😀

2022-11-11 17:36 UTC, oleg-derevenetz commented
@ihhub

> Don't change config file. Use our new fancy UI option within the game!😀

When I tried the fullscreen mode on Android, there wasn't any fancy option yet :)

2022-11-11 23:40 UTC, oleg-derevenetz commented
To be honest, after a cursory glance, I have no idea how this code can cause a crash after switching to the fullscreen.

2022-11-15 19:40 UTC, DmitrySokolov commented
> I would find the other solution better. So touch the relevant element and then touch anything with the second finger to open the window. This is how it is implemented in VCMI. Works quite well.

Have you considered just a long tap as rmb?

2022-11-15 20:00 UTC, zenseii commented
> > I would find the other solution better. So touch the relevant element and then touch anything with the second finger to open the window. This is how it is implemented in VCMI. Works quite well.
> 
> Have you considered just a long tap as rmb?

We have considered this and it would be very annoying considering how often you sometimes do this in this game.

2022-11-20 09:35 UTC, zenseii approved these changes
Tested on my Android phone and it works very well. Great job, @ihhub !

2022-11-20 10:26 UTC, oleg-derevenetz commented on src/engine/localevent.cpp
> +#define TOUCHSCREEN_SUPPORT
Hi @ihhib maybe call it something like `TOUCH_SUPPORT`, because the relevant code relates not just to devices with touchscreens, but also to devices with touchpads?

2022-11-20 10:27 UTC, ihhub commented on src/engine/localevent.cpp
> +#define TOUCHSCREEN_SUPPORT
Touchpads is actually a mouse but in a different form. Touchpads control mouse position. Please correct me in this if I am wrong.

2022-11-20 10:32 UTC, oleg-derevenetz commented on src/engine/localevent.cpp
> +#define TOUCHSCREEN_SUPPORT
@ihhub Not quite. For example, touchpad on my macbook has a concept of gestures using multiple fingers: slide by two fingers is scrolling event, pinching by two fingers is zoom in/out, [and so on](https://support.apple.com/en-us/HT204895).

2022-11-20 10:33 UTC, ihhub commented on src/engine/localevent.cpp
> +#define TOUCHSCREEN_SUPPORT
Okay, in this case we can just rename it to `TOUCH_SUPPORT` to avoid confusion.

2022-11-20 11:02 UTC, oleg-derevenetz approved these changes

2022-11-20 11:02 UTC, merged