Add more right click quick info for hero and castle captain
ihhub/fheroes2 pull request #6107
Opened 2022-11-06 14:08 UTC by Districh-ru

close #5298 & fix #1724

Added the ability to view quick info about the castle captain in the castle and quick info about the hero for the hero meeting dialog, hero recruit dialog, castle dilaog.
![изображение](https://user-images.githubusercontent.com/113276641/200175077-bfa2d94c-cbbe-4c58-9ced-6eaf24554b07.png)
![изображение](https://user-images.githubusercontent.com/113276641/200175128-74151a75-73bd-4919-b9f9-a78dd8d38c50.png) ![изображение](https://user-images.githubusercontent.com/113276641/200175227-3d0bc36d-d6aa-493e-8ad9-ef0c490d1372.png)

Have not made quick info for heroes in Theves guid and in oasis. So not all issues in #1724 are fixed :(

2022-11-06 16:39 UTC, ihhub commented
Hi @Districh-ru , hero information in Thieves Guild and in Oracle dialogs must **NOT** be shown so you don't need to implement it. Right-clicking reveals the whole army of a hero which shouldn't be the case for these aforementioned dialogs.

2022-11-06 16:59 UTC, Districh-ru commented
> Hi @Districh-ru , hero information in Thieves Guild and in Oracle dialogs must **NOT** be shown so you don't need to implement it. Right-clicking reveals the whole army of a hero which shouldn't be the case for these aforementioned dialogs.

Hi @ihhub , OK, I won't implement this.
At first I wanted to try to implement hiding the information, not shown in Thieves Guild or in Oracle for enemies and show all info for player's hero. But this task is complicated for me and such a quik info window does not make sense.

2022-11-07 12:24 UTC, ihhub requested changes
Hi @Districh-ru , I left several comments in this pull request. Could you please take a look?

I also think that we shouldn't show neutral flags for heroes. It is better to show with no flags at all. What do you think @Branikolog and @zenseii ?

2022-11-07 12:24 UTC, ihhub commented on src/fheroes2/castle/castle_town.cpp
> +    fheroes2::Rect heroPortraitArea( dst_pt.x, dst_pt.y, portrait_frame.width(), portrait_frame.height() );
Please make this variable `const`.

2022-11-07 12:24 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +    const bool showFullInfo = hero.GetColor() == 0 || isFriend || isUnderIdentifyHeroSpell || kingdom.IsTileVisibleFromCrystalBall( hero.GetIndex() );
Please avoid using hardcoded values. Use `Color::NONE` instead of `0`. Also add parenthesis for the newly added statement.

2022-11-07 16:25 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +    const bool showFullInfo = hero.GetColor() == 0 || isFriend || isUnderIdentifyHeroSpell || kingdom.IsTileVisibleFromCrystalBall( hero.GetIndex() );
With neutral flags disabled, it would look like this:
![picture](https://user-images.githubusercontent.com/113276641/200361443-49ad36f9-9976-442f-9706-ad063ddf9bf2.png)

2022-11-07 16:27 UTC, Districh-ru commented on src/fheroes2/castle/castle_town.cpp
> +    fheroes2::Rect heroPortraitArea( dst_pt.x, dst_pt.y, portrait_frame.width(), portrait_frame.height() );
OK, I made the appropriate changes.

2022-11-07 18:13 UTC, zenseii commented
Yes, @ihhub, I agree that it's better to have no flag on recruitable heroes.

2022-11-07 18:15 UTC, zenseii commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +    const bool showFullInfo = hero.GetColor() == 0 || isFriend || isUnderIdentifyHeroSpell || kingdom.IsTileVisibleFromCrystalBall( hero.GetIndex() );
Without the flag is much better.

2022-11-08 00:59 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +    const bool showFullInfo = hero.GetColor() == 0 || isFriend || isUnderIdentifyHeroSpell || kingdom.IsTileVisibleFromCrystalBall( hero.GetIndex() );
Yes, let's go with this approach.

2022-11-08 14:19 UTC, ihhub approved these changes

2022-11-09 11:50 UTC, Branikolog approved these changes

2022-11-09 12:02 UTC, merged

2022-11-09 12:02 UTC, ihhub commented
@Districh-ru , thank you so much for this improvement!