Update German
ihhub/fheroes2 pull request #6112
Opened 2022-11-06 21:59 UTC by Laserlicht

2022-11-08 17:11 UTC, zenseii requested changes
Hi, @Laserlicht.

Great contribution! I've added some comments that I found regarding the format etc. I don't speak German and therefore I've only looked over the translations with deepL.

Hopefully we can have someone who speaks it, like @a1exsh, to help out if they have the time and want to!

2022-11-08 17:11 UTC, zenseii commented on files/lang/de.po
> +msgstr "szenarioName|Verteidiger"
Please remove the `"szenarioName|"` part. This is only for context for the translator and the English string will have this removed before being displayed.
Like this:
```suggestion
msgstr "Verteidiger"
```

2022-11-08 17:11 UTC, zenseii commented on files/lang/de.po
> +msgstr "sorceress|Roter Turm"
Please remove the context here too like above.

2022-11-08 17:11 UTC, zenseii commented on files/lang/de.po
> +msgstr "warlock|Roter Turm"
Please remove the context here like above.

2022-11-08 17:11 UTC, zenseii commented on files/lang/de.po
> +msgstr "Konfigurieren"
This might be too long for the line it is placed on. Please check the main menu settings if this fits or if not
add a hyphen and a forced line break: `"-\n"`

2022-11-08 17:11 UTC, zenseii commented on files/lang/de.po
> +msgstr "Heroes of Might and Magic II: The Succession Wars Team"
I don't know how German works so please ignore this if it's wrong but should there be a hyphen here?
```suggestion
msgstr "Heroes of Might and Magic II: The Succession Wars-Team"
```

2022-11-08 17:11 UTC, zenseii commented on files/lang/de.po
> +msgstr "Heroes of Might and Magic II: The Price of Loyalty Team"
Same comment as above.

2022-11-08 17:11 UTC, zenseii commented on files/lang/de.po
> +msgstr "week|Ratte"
Please remove the context here like previous comments.

2022-11-08 17:11 UTC, zenseii commented on files/lang/de.po
> +msgstr "week|Hund"
Please remove the context.

2022-11-08 17:11 UTC, zenseii commented on files/lang/de.po
> +msgstr "week|Unbenannt"
Please remove the context.

2022-11-09 22:15 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "SCHWIERIGKEIT"
Yes - was to long :(

2022-11-09 22:16 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "Konfigurieren"
It fits :)

2022-11-09 22:17 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "Heroes of Might and Magic II: The Succession Wars Team"
Yes, it's better!

2022-11-10 10:36 UTC, a1exsh requested changes
@Laserlicht Appreciate your focused approach, but please see the comments. :)

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Verschiebt den %{name}"
I think it was done previously that way for a reason, i.e. to avoid using the article.  Does it now read "Verschiebt den Zwergen", for example?

If you are keen to use a verb that you think is better suited here, then let's do it this way, keeping the order of words:
```suggestion
msgstr "%{name} verschieben"
```

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Verschiebt den %{name} "
This looks very similar to the next one, but seems like the phrase is built from some pieces by the code.  This is problematic and is not recommended with `gettext`.  Have you found the place in code where this string is used?

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Optionen für den Kapitän"
```suggestion
msgstr "Möglichkeiten für den Kapitän"
```

I think that's a more direct translation?

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Seid Ihr sicher, dass ihr den Kampf im Automodus beenden wollt?"
```suggestion
msgstr "Seid Ihr sicher, dass Ihr den Kampf im Automodus beenden wollt?"
```

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Seid Ihr sicher, dass ihr den Kampf im Automodus beenden wollt?"
By the way, when did we switch from "Sie" to "Ihr"?  Is it as in "Ihre Hochheit"?

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Der Angriff des %{attacker} blendet das %{target}!"
Why "das"?  Is it now "... blendet das Elfen"?..

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Der %{attacker} verbannt alle guten Zaubersprüche auf dein %{target}!"
"Dein" is incorrect here.  Should be some form of "Sie", depending on the context.

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Seid Ihr sicher, dass ihr den Autokampf unterbrechen wollt?"
Same as above: please use consistent capitalization of "Sie"/"Ihr".

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Klickt, um die ausgewählte Auflösung anzuwenden."
Some consistency here would be appreciated as well.  In the current state of the translation I see a number of possible ways to address the player in such context being used concurrently...

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Kampagnenschwierigkeit"
Wasn't "Campaign" translated as "Feldzug" elsewhere?  E.g. the original DE buttons from the main menu.

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Highscores für Standardkarten anzeigen."
"Bestenliste" was good, no?

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +"Willkommen bei Heroes of Might and Magic II (powered by fheroes2) engine! "
```suggestion
"Willkommen bei der/dem Heroes of Might and Magic II (powered by fheroes2) Engine! "
```

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +"Bitte stellt sicher, dass alle erforderlichen Dateien im System vorhanden "
```suggestion
"Stellt bitte sicher, dass alle erforderlichen Dateien im System vorhanden "
```
Sounds more German to me. ;)

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +"Entweder Rolands oder Archibalds Kampagne aus dem ursprünglichen Heroes of "
Why this change of word now?

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +"Die Suche nach dem Ultimativen Artefakt ist erfolglos. Ihr Held könnte es "
Should we phrase it more in the future tense (as a possibility)?  Otherwise it also reads as something done.

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +"Die Suche nach dem Ultimativen Artefakt ist erfolglos. Ihr Held könnte es "
Also:
```suggestion
"Die Suche nach dem ultimativen Artefakt ist erfolglos. Ihr Held könnte es "
```

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +"30 % weniger Ressourcen pro Zug."
```suggestion
"Spieler mit einem schwerem Handicap beginnen mit weniger Ressourcen und erhalten "
"30% weniger Ressourcen pro Zug."
```

Consistency. ;)

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +"Dieser %{name} gibt eurem Helden die Fähigkeit, den %{spell} zu wirken, wenn "
Capitalization?

2022-11-10 10:36 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Helden: bei Rückzug oder Kapitulation Bewegungspunkte nicht vergessen"
```suggestion
msgstr "Helden: bei Rückzug oder Kapitulation Bewegungspunkte merken"
```

2022-11-10 11:53 UTC, zenseii commented on files/lang/de.po
> +msgstr "Kampagnenschwierigkeit"
Yep, I'm pretty sure it's Feldzug in the OG.

2022-11-11 01:13 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "Seid Ihr sicher, dass ihr den Kampf im Automodus beenden wollt?"
This is indeed a point that would have to be looked at again at a later time over the complete translation. To be consistent there. I'm not sure how it is in the original right now.

2022-11-11 01:17 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "Verschiebt den %{name} "
No, have not found the string yet. Do you have a suggestion?

2022-11-11 01:21 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "Klickt, um die ausgewählte Auflösung anzuwenden."
Yes, this is still a general problem, I think.

2022-11-11 01:27 UTC, Laserlicht commented
@a1exsh & @zenseii   Thank you very much. :)
I have implemented your changes. maybe you can take a second look.

2022-11-11 02:11 UTC, zenseii commented on files/lang/de.po
> +msgstr "Verschiebt den %{name} "
Strings are placed in the PO file according to their location in the code, so looking at the strings before and agter this tells me it has to do with the army bar and moving a troop around in your army or to another army/castle garrison.

2022-11-11 07:53 UTC, a1exsh commented on files/lang/de.po
> +"Willkommen bei der/dem Heroes of Might and Magic II (powered by fheroes2) Engine! "
@Laserlicht `der/dem` wasn't meant to be applied that literally! %)

2022-11-11 07:55 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Verschiebt den %{name} "
@zenseii can you paste a code link here?  Github search isn't too helpful and I don't have the code checked out locally at hand.

2022-11-11 07:56 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Der Angriff des %{attacker} blendet die %{target}!"
But what about `die Grüner Drache`?..  it's all too tricky with the German grammar.

2022-11-11 07:58 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Seid Ihr sicher, dass ihr den Kampf im Automodus beenden wollt?"
> ... in the original right now.

Do you mean the original game?  We don't have to follow that precisely, I think, but whatever style we've chosen we should apply consistently.

2022-11-11 08:00 UTC, a1exsh commented on files/lang/de.po
>  msgstr "Kampagne"
```suggestion
msgstr "Feldzug"
```
?

2022-11-11 08:02 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Möglichkeiten für den Kapitän"
Makes me thinking about Sorceress castles... `Kapitänin`?

2022-11-11 13:01 UTC, zenseii commented on files/lang/de.po
> +msgstr "Verschiebt den %{name} "
Here you go @a1exsh:
https://github.com/ihhub/fheroes2/blob/13ba260250a092060c1891ff3233af12e890e161/src/fheroes2/army/army_bar.cpp#L301-L309

It is called when you are moving 1 single unit troop:
![image](https://user-images.githubusercontent.com/12501091/201345723-c8d6e52a-ae79-4beb-8d1f-ba60d273cd4b.png)

2022-11-11 13:05 UTC, zenseii commented on files/lang/de.po
> +msgstr "Möglichkeiten für den Kapitän"
I think this would have to be made into a bigger change because you also have the "Captain's quarters" building

2022-11-11 13:20 UTC, zenseii commented on files/lang/de.po
> +"Willkommen bei der/dem Heroes of Might and Magic II (powered by fheroes2) Engine! "
You should use the article fitting for what essentially is `"Welcome to the video game Heroes of Might and Magic II powered by the fheroes2 engine! [...] "`.
Also by having `Engine` outside of the parenthesis it sounds like you are welcoming them to the Heroes 2 engine, which is wrong. 

BTW why isn't `(powered by the fheroes2 engine)` translated to German to begin with? Instead of `powered by` you can translate it as something like `"(with the fheroes2 engine)"`.
```suggestion
"Willkommen bei dem Heroes of Might and Magic II (mit der fheroes2-Engine) ! "
```

2022-11-11 13:53 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Verschiebt den %{name} "
@zenseii thank you.  So it looks like the trailing space in the original string is just overlooked, it's not because some further text is concatenated in the following code, which was my guess.

@Laserlicht in any case, `den` is not going to cut it for German.  We need to find an approach that works for all monster names, which for now may involve just not using the article as it was before, e.g:
```suggestion
msgstr "%{name} verschieben"
```

2022-11-12 00:02 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "Der Angriff des %{attacker} blendet die %{target}!"
Hmm... Yes. German language, difficult language. I think we can't solve that problem right now either.

2022-11-12 00:07 UTC, Laserlicht commented on files/lang/de.po
> +"Willkommen bei der/dem Heroes of Might and Magic II (powered by fheroes2) Engine! "
> @Laserlicht `der/dem` wasn't meant to be applied that literally! %)

I should not make any changes this late at night. 😅

@zenseii @a1exsh What do you think of the new variant?

2022-11-12 12:15 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Die Anzahl der Tage, die für diese Kampagne aufgewendet wurden."
So, let's be consistent and use "Feldzug" everywhere (including pre-existing translations)?

2022-11-12 12:16 UTC, a1exsh commented on files/lang/de.po
> +msgstr "%{name} verschieben"
By the way, I'm not sure "verschieben" is better than "umstellen" in this context.  Can you briefly explain the subtlety here? @Laserlicht

2022-11-12 12:20 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Der Angriff des %{attacker} blendet die %{target}!"
Should we try to find a way to dodge the problem?  E.g:
```suggestion
msgstr "%{target} wegen des Angriffs von %{} geblendet!"
```

2022-11-12 15:13 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "Die Anzahl der Tage, die für diese Kampagne aufgewendet wurden."
You're right!

2022-11-12 15:14 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "%{name} verschieben"
Yes, I changed it back once.

2022-11-12 15:14 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "Der Angriff des %{attacker} blendet die %{target}!"
Good idea!

2022-11-12 16:36 UTC, zenseii commented on files/lang/de.po
> +"Willkommen bei der/dem Heroes of Might and Magic II (powered by fheroes2) Engine! "
As I stated earlier I don't actually speak German so @a1exsh would know better. From a format/style perspective it looks good.

2022-11-12 18:09 UTC, a1exsh commented
@Laserlicht please check _all_ places where "Kampagne" is used and change it to "Feldzug", not only limited to the lines you have changed in this PR.  Also, let's carefully review the "der/die/das" in each case where it's introduced by the PR and see if we can avoid the mismatch by phrasing it differently.

2022-11-12 18:48 UTC, Laserlicht commented
> @Laserlicht please check _all_ places where "Kampagne" is used and change it to "Feldzug", not only limited to the lines you have changed in this PR.

Done 😉

2022-11-13 08:54 UTC, a1exsh commented
> > @Laserlicht please check _all_ places where "Kampagne" is used and change it to "Feldzug", not only limited to the lines you have changed in this PR.
> 
> Done wink

Very good. :+1: 

And what about der/die/das?  Do you need help to rearrange the affected phrases?

2022-11-13 11:42 UTC, Laserlicht commented
> > > @Laserlicht please check _all_ places where "Kampagne" is used and change it to "Feldzug", not only limited to the lines you have changed in this PR.
> > 
> > 
> > Done wink
> 
> Very good. 👍
> 
> And what about der/die/das? Do you need help to rearrange the affected phrases?

If you want, very much. :)

2022-11-13 18:00 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Der Blick des %{attacker} verwandelt das %{target} in Stein!"
```suggestion
msgstr "%{target} wegen des Blicks von %{attacker} in Stein verwandelt!"
```
Seems pretty straightforward, no? :)

2022-11-13 18:03 UTC, a1exsh commented on files/lang/de.po
> +msgstr "%{target} wegen des Angriffs von %{attacker} geblendet!"
```suggestion
msgstr "%{target} ist wegen des Angriffs von %{attacker} geblendet!"
```
Actually, according to the German grammar, it should be like that, shouldn't it?

2022-11-13 18:04 UTC, a1exsh commented on files/lang/de.po
> +msgstr "Der Blick des %{attacker} verwandelt das %{target} in Stein!"
Can you follow the pattern for the rest of the strings?

2022-12-17 13:02 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "Der Blick des %{attacker} verwandelt das %{target} in Stein!"
Shouldn't we cover something like this in a separate PR? Grammar Rework or something. Der PR ist ja schon recht umfangreich.

2022-12-17 13:31 UTC, Laserlicht commented
I think we should merge the PR.

It's been open for so long and you have to do a lot of things.

Other changes (e.g. grammar) should then be made separately, I think.

2022-12-17 16:08 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "ein"
`on/off` corresponds to `ein/aus` (or `an/aus`)

2022-12-17 16:14 UTC, Laserlicht commented
Yes, I think the dot would be more important. The fields are also partly somewhat smaller (or the font larger) than in the original German assets, so that I had to abbreviate them partly.

The Eszet (`ß`) I have replaced as already seen by `ss`. This is also the case in the original. But of course `ß` would be nicer.

2022-12-22 20:54 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "Sehen Sie sich die Intro-Videos zum aktuellen Stand des Feldzuges an."
I've changed it back to "Sie". As in the original translation.

HoMM3 used "Ihr". A little bit confusing. 😅

2022-12-22 20:54 UTC, Laserlicht commented
@zenseii please have a look 😊

2022-12-22 22:58 UTC, Laserlicht commented
@zenseii done 😊

2022-12-30 14:48 UTC, ihhub reviewed
Hi @Laserlicht , I left one comment in this pull request. Could you please take a look?

2022-12-30 14:48 UTC, ihhub commented on files/lang/de.po
> +msgstr "BEEND."
Do we need a full stop here? This is for a button and buttons usually don't contain a dot.

The same comment applies for the rest of cases with dots below.

2022-12-30 14:51 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "BEEND."
The problem here is that German is usually longer than English. "QUIT" actually means "BEENDEN". Which is too long for the button. The official german translation does the same by the way.

2022-12-30 14:52 UTC, ihhub commented on files/lang/de.po
> +msgstr "BEEND."
Got it. We have a pull request which will address this issue in the future but for now let's stick to this approach.

2022-12-30 14:52 UTC, merged

2022-12-30 14:52 UTC, ihhub commented
@Laserlicht , huge thanks for improving this translation!