Bulgarian Translation 17
ihhub/fheroes2 pull request #6163
Opened 2022-11-12 17:53 UTC by Effektus

99.9% Finished

2022-11-12 17:54 UTC, Effektus commented
[zenseii](https://github.com/zenseii) Ivan please check fuzzy marks. I have difficult to translate this one

2022-11-12 18:22 UTC, zenseii requested changes
Hi @Effektus.

I've left a comment about the fuzzied string. I'll review the rest of the translation later.

2022-11-12 18:22 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Заглавие"
This means the top of a mast that you have on sail boats.
This is what the artifact looks like:
![image](https://user-images.githubusercontent.com/12501091/201488956-fb79264a-8a03-4e5a-a952-ec1e9b2e2ca7.png)

2022-11-12 20:24 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Заглавие"
Is this right? 
![image](https://user-images.githubusercontent.com/12934196/201493172-30b36550-e9c7-4cfc-9989-027f8efc1d42.png)

2022-11-12 20:45 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Заглавие"
Yep, in Heroes 2 the orcs look a lot like pigs. Not sure if that's what you're asking.

2022-11-12 23:33 UTC, zenseii requested changes
Hi, @Effektus.

I left a couple of comments. Please have a look.

2022-11-12 23:33 UTC, zenseii commented on files/lang/bg.po
> +"без това предпочитам да летя.“"
Please use the other quotation mark.
```suggestion
"без това предпочитам да летя.\""
```

2022-11-12 23:33 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Кара Въздушни елемнетали да пазят мина срещу вражески армии."
Small typo
```suggestion
msgstr "Кара Въздушни елементали да пазят мина срещу вражески армии."
```

2022-11-13 19:08 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Кара Въздушни елемнетали да пазят мина срещу вражески армии."
What is the difference here?

2022-11-13 19:56 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Кара Въздушни елемнетали да пазят мина срещу вражески армии."
не and ен
`елемнетали`
`елементали`

2022-11-14 09:01 UTC, zenseii requested changes

2022-11-14 17:21 UTC, zenseii approved these changes

2022-11-21 12:42 UTC, zenseii approved these changes

2022-11-24 14:51 UTC, zenseii reviewed
Hi, @Effektus.

I left one comment. Please have a look at it.

2022-11-24 14:51 UTC, zenseii commented on files/lang/bg.po
> +msgstr "Ненаситника"
Is there a specific reason this was changed? I can't seem to find any reference showing that Ненаситника refers to a grasshopper/locust in Bulgarian. It seems to mean "insatiable"?

2022-11-24 15:11 UTC, zenseii approved these changes

2022-11-25 12:29 UTC, ihhub requested changes

2022-11-25 13:13 UTC, Effektus commented on files/lang/bg.po
> +"Твойте сили претърпяват горчиво поражение и %{name} изоставя каузата ти."
Because in Bulgarian the official form "ви" is used quite often and for the plural.

2022-11-25 22:50 UTC, ihhub approved these changes

2022-11-25 22:50 UTC, merged

2022-11-25 22:51 UTC, ihhub commented
@Effektus , thanks a lot for this update!