Generate resizable button for both interfaces
ihhub/fheroes2 pull request #6169
Opened 2022-11-13 07:51 UTC by ihhub

relates to #6155, #6105

2022-11-20 17:20 UTC, zenseii reviewed
I've checked and tested it and it looks very good.
There is a slight pixel issue shared with both the Good and Evil buttons. It doesn't bother me but maybe someone else will notice.
![image](https://user-images.githubusercontent.com/12501091/202916159-f340ede3-ab73-4dac-8d75-bbc0529ccfb0.png)

2022-11-21 17:45 UTC, zenseii requested changes
Hi, @ihhub.

I left some very minor comments. Please have a look when you have the time to.

2022-11-24 11:43 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +            fheroes2::Copy( original, originalWidth - width / 2, 0, output, output.width() - width / 2, 0, width - width / 2, height );
No. This is the correct calculation:
width = 5
width / 2 = 2
width - width / 2 = 3

2022-11-24 11:49 UTC, zenseii approved these changes

2022-11-24 12:33 UTC, oleg-derevenetz approved these changes

2022-11-24 21:48 UTC, merged