Rework credits page
ihhub/fheroes2 pull request #6199
Opened 2022-11-16 14:39 UTC by ihhub

To support multiple links for donation and social networks as well as to expand the list of participants.

2022-11-16 15:42 UTC, zenseii requested changes
This looks good to me I just left two suggestions, @ihhub. Please have a look when you have the time to.

2022-11-16 15:42 UTC, zenseii commented on src/fheroes2/game/game_credits.cpp
> +        name.Blit( textInitialOffsetX + ( textInitialOffsetX - name.w() ) / 2, offsetY + ( constributorsHeight - supportersHeight ) / 2, output );
Should we line these two columns equally?
![image](https://user-images.githubusercontent.com/12501091/202225857-32e55009-de2e-428b-ae98-1a04a90fcf76.png)

Also maybe add the titles to each colum "Contributors" "Supporters" ?

2022-11-17 01:30 UTC, oleg-derevenetz commented on src/fheroes2/game/game_credits.cpp
> +        name.Blit( textInitialOffsetX + ( textInitialOffsetX - name.w() ) / 2, offsetY + ( constributorsHeight - supportersHeight ) / 2, output );
I suppose they are just vertically centered, and since they have a different height, there is a shift between lines. IMHO they looks good as is.

2022-11-17 12:32 UTC, ihhub commented on src/fheroes2/game/game_credits.cpp
> +        name.Blit( textInitialOffsetX + ( textInitialOffsetX - name.w() ) / 2, offsetY + ( constributorsHeight - supportersHeight ) / 2, output );
It is fixed.

2022-11-17 12:55 UTC, oleg-derevenetz approved these changes

2022-11-17 15:19 UTC, merged