Danish language project (Stisen1)
ihhub/fheroes2 pull request #6237
Opened 2022-11-21 09:16 UTC by Stisen1

I have made about 150 translations from english to danish, that focuses on naming monstertypes

2022-11-21 12:25 UTC, zenseii requested changes
Hi, @Stisen1.

This is a very good translation and thank you for contributing! I've left some comments and if you have the time it would be great if you could have a look at them and address them.

In general I would say that we don't need comments that explain the grammar of the language. That is why I commented some of them.

Don't hesitate to ask if you have any questions.

2022-11-21 12:25 UTC, zenseii commented on files/lang/dk.po
> +# In this case, singular and plural is spelled the same (danish).
We can remove this comment because this happens in other translations too.

2022-11-21 12:25 UTC, zenseii commented on files/lang/dk.po
> +# ‪‪In danish these terms are spelled the same, no matter whether you are perishing one og more.
Not sure how this happened but there are bidirectional Unicode characters here, and this is giving us a warning.
Since this comment isn't needed, because other languages also behave like this, I suggest to delete this comment. What do you think, @Stisen1 ?
```suggestion
```

2022-11-21 12:35 UTC, zenseii commented on files/lang/dk.po
> +msgstr "åndssvagt mange"
Here you can see what exactly happens and why the UI has a limit:
![image](https://user-images.githubusercontent.com/12501091/203056668-03442f3e-7246-47dd-b683-29f2c3d4bc02.png)

2022-11-21 12:37 UTC, zenseii commented on files/lang/dk.po
> +msgstr "åndssvagt mange"
Note that this limit does not exist for the other phrase "Zounds of\n %{monster}" but these two should use recognizably similar words for the player to not have to deal with two words for the same quantity.

2022-11-21 13:03 UTC, zenseii commented on files/lang/dk.po
> +msgstr "GAVE"
Here is where it appears:
![image](https://user-images.githubusercontent.com/12501091/203062027-e208e1cd-83d8-41c1-96cf-30424507cf6b.png)

2022-11-21 13:10 UTC, zenseii commented on files/lang/dk.po
> +msgstr "Hobbit"
Here is a reference:
https://dungeonsdragons.fandom.com/wiki/Halfling#Original_D&D

2022-11-30 21:18 UTC, Stisen1 commented
Hey Zenseii

I went through your comments, and you are quite thorough and precise, so I
get what  you are saying. Hobbit is conveniently spelled the same in both
danish and english, but I changed it to the danish word for halfling =>
"halvlang". The thing about "Trolls" is hard though. Goblins, Ogres and
Trolls are all the same in danish. The definitions of each characteristics
seems to slide into each other, the more I search for the right separate
names for them, in danish... One thing is certain though, "vætter" can ONLY
be goblins. "jætter" and "trolde" is harder to distinct from each other.
A "trold" is typically big and stupid, or small and annoying. They never
seem to have wits or capable of reasoning. A "jætte" is a "jotun", that
comes in many sizes, but sometimes they also have wits. Some of them can
even do magic. The "trolls" in Heroes 2 is more threatening and stronger
than ogres are. They regenerate and can even throw stones, that magically
replenishes between their bare hands! I believe that a dane will understand
this translation, due to our mainstream cultural knowledge of norse
mythological lore. I grew up with Heroes 1, and the huge, fit purple
monstrosity of a troll, was so very imtimidating to me as a kid. They
seemed big, strong and tough as nailes, and, to me at least, they seemed
just as intelligent as the race of men. The Heroes 1 ogre on the other
hand. They look just like a stereotypical caveman from the Stone Age!!!
Haha..

I am of course aware of the reference to fairytales with trolls underneath
bridges, but then again, these tales stem from norse mythology to. The
norse gods often crossed jotuns on paths between worlds, and sometimes even
on the Bifrost bridge.

Anyway... I shall continue my translations soon. I've got myself a brand
new daughter, two weeks ago!

When do you expect to launch another patch?

Best regards Rasmus (Lord Knightmare)

Den man. 21. nov. 2022 kl. 13.26 skrev Zenseii ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Hi, @Stisen1 <https://github.com/Stisen1>.
>
> This is a very good translation and thank you for contributing! I've left
> some comments and if you have the time it would be great if you could have
> a look at them and address them.
>
> In general I would say that we don't need comments that explain the
> grammar of the language. That is why I commented some of them.
>
> Don't hesitate to ask if you have any questions.
> ------------------------------
>
> In files/lang/Makefile
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1027858691>:
>
> > @@ -39,7 +39,7 @@ be.mo bg.mo ru.mo uk.mo: %.mo: %.po
>
>  	$(call MSGFMT,CP1251)
>
>
>
>  # German, French, Italian, Dutch, Norwegian, Portuguese, Spanish and Swedish translations use CP1252
>
>
> We should add Danish to this commented line too.
> ⬇️ Suggested change
>
> -# German, French, Italian, Dutch, Norwegian, Portuguese, Spanish and Swedish translations use CP1252
>
> +# German, French, Italian, Dutch, Norwegian, Portuguese, Spanish and Swedish translations use CP1252
>
>
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1027860865>:
>
> > @@ -0,0 +1,8607 @@
>
> +# Dutch translation for fheroes2
>
>
> This should say Danish. This can be changed by opening the file in a code
> editor like you did with the makefile.
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1027865083>:
>
> > +"MIME-Version: 1.0\n"
>
> +"Content-Type: text/plain; charset=UTF-8\n"
>
> +"Content-Transfer-Encoding: 8bit\n"
>
> +"Plural-Forms: nplurals=2; plural=(n != 1);\n"
>
> +"X-Launchpad-Export-Date: 2010-05-27 09:12+0000\n"
>
> +"X-Generator: Poedit 3.2\n"
>
> +
>
> +msgid ""
>
> +"BATTLE\n"
>
> +"ONLY"
>
> +msgstr ""
>
> +"KUN\n"
>
> +"KAMP"
>
> +
>
> +msgid "GIFT"
>
> +msgstr "GAVE"
>
>
> This button refers to the button in the Marketplace which lets you
> send/donate resources to the opponents so the English button is referring
> more to the verb "to gift" rather than "a gift". The English button should
> probably be changed to Give/Donate.
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1027868785>:
>
> > +
>
> +msgid "Warning"
>
> +msgstr "Advarsel"
>
> +
>
> +msgid ""
>
> +"Do you want to regain control from AI? The effect will take place only on "
>
> +"the next turn."
>
> +msgstr ""
>
> +"Vil du genoptage kontrollen fra AI'en? Dette vil kun have effekt på næste "
>
> +"tur."
>
> +
>
> +msgid ""
>
> +"A few\n"
>
> +"%{monster}"
>
> +msgstr ""
>
> +"Få\n"
>
>
> Should there be "Nogle" before?
> ⬇️ Suggested change
>
> -"Få\n"
>
> +"Nogle få\n"
>
>
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1027870916>:
>
> > +msgid ""
>
> +"Zounds of\n"
>
> +"%{monster}"
>
> +msgstr ""
>
> +"Åndssvagt mange\n"
>
> +"%{monster}"
>
> +
>
> +msgid ""
>
> +"A legion of\n"
>
> +"%{monster}"
>
> +msgstr ""
>
> +"En legion af\n"
>
> +"%{monster}"
>
> +
>
> +msgid "army|Few"
>
> +msgstr "få"
>
>
> This line should have a capital letter. POEdit will put a warning but it
> should be ignored.
> The same goes for all the sequent lines that start with "army|".
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1027874051>:
>
> > +msgstr "flok"
>
> +
>
> +msgid "army|Lots"
>
> +msgstr "mange"
>
> +
>
> +msgid "army|Horde"
>
> +msgstr "horde"
>
> +
>
> +msgid "army|Throng"
>
> +msgstr "skare"
>
> +
>
> +msgid "army|Swarm"
>
> +msgstr "sværm"
>
> +
>
> +msgid "army|Zounds"
>
> +msgstr "åndssvagt mange"
>
>
> This will become too long for the game's UI. It can be a maximum of 8
> letters. It should also be more or less the same as the other line above
> with zounds, although that one does not have a limit of 8 letters.
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1027880291>:
>
> > +msgstr ""
>
> +"Artefaktet Negationens Kugle er i kraft, hvilket deaktiverer brug af enhver "
>
> +"kamp-besværgelser."
>
> +
>
> +msgid "You have already cast a spell this round."
>
> +msgstr "Du har allerede kastet en besværgelse i denne runde."
>
> +
>
> +msgid "That spell will affect no one!"
>
> +msgstr "Dén besværgelse vil ikke påvirke nogen!"
>
> +
>
> +msgid "You may only summon one type of elemental per combat."
>
> +msgstr "Du må kun hidkalde én slags Elemental per kamp."
>
> +
>
> +msgid "There is no open space adjacent to your hero to summon an Elemental to."
>
> +msgstr ""
>
> +"Der er ingen åben plads ved siden af din helt til at hidkalde en Elemental "
>
>
> Same comment as above about capital letter.
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1027885564>:
>
> > +
>
> +msgid ""
>
> +"The Sphere of Negation artifact is in effect for this battle, disabling all "
>
> +"combat spells."
>
> +msgstr ""
>
> +"Artefaktet Negationens Kugle er i kraft, hvilket deaktiverer brug af enhver "
>
> +"kamp-besværgelser."
>
> +
>
> +msgid "You have already cast a spell this round."
>
> +msgstr "Du har allerede kastet en besværgelse i denne runde."
>
> +
>
> +msgid "That spell will affect no one!"
>
> +msgstr "Dén besværgelse vil ikke påvirke nogen!"
>
> +
>
> +msgid "You may only summon one type of elemental per combat."
>
> +msgstr "Du må kun hidkalde én slags Elemental per kamp."
>
>
> Should Danish have capital letters for nouns? The English original does it
> either because this was a thing in American English in the 1800s, or
> because of code limitations.
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1027889306>:
>
> > +msgstr ""
>
> +
>
> +msgid "Artifact"
>
> +msgstr ""
>
> +
>
> +msgid "Boat"
>
> +msgstr ""
>
> +
>
> +msgid "Ran [...]

2022-12-01 07:14 UTC, Stisen1 commented
Hi Zenseii

I am overwhelmed by your lengthy private responses to my emails! I am
honored! It really helps me being motivated about finishing this project.

Funny to know, that your are a scandinavian yourself. I thought you were
russian or ukranian, due to the fact that many Heroes fans and modders are
from there. I am a college teacher in danish, so I know quite a bit about
scandinavian literature, folklore and such, although I am not an expert
within a particular field. I am also a teacher in "oldtidskundskab", where
greek mythology and mythical creatures is present. So... I also know a bit
about oldgreek and latin. I am therefore very considerate, when it comes to
translating old shiat :-D The "zounds" term keeps me awake at night!
Haha!... I have even consulted my wife about that word in particular. She
believes that "hobetal" or "overflod" will do. I would like "du fredsens",
but that is two words and too long...

I am soon without a job, by Christmas to be exact. So I will soon have
plenty of time on my hands, in order to make the perfect danish translation!

Med venlig hilsen, Rasmus

Den ons. 30. nov. 2022 kl. 23.26 skrev Zenseii ***@***.***>:

> Hi, @Stisen1 <https://github.com/Stisen1>!
>
> First off congratulations with having a daughter! You must be very happy
> and I hope both you parents and your daughter are doing well. Obviously I
> figure you are also exhausted.
>
> This gives us even more of a reason to make a Danish translation so that
> your daughter can play it when she is old enough without having to learn
> English first!
>
> When do you expect to launch another patch?
>
> We have both a Roadmap
> <https://github.com/ihhub/fheroes2/wiki/Project-roadmap> for the project
> and an overview of tentative release dates for the next releases called
> milestones <https://github.com/ihhub/fheroes2/milestones>. You can see
> the date for the next release there, but it can still be subject to change
> if we discover something important.
>
> Note that we don't call them patches because that is something different.
>
> Hobbit is conveniently spelled the same in both danish and english, but I
> changed it to the danish word for halfling => "halvlang".
>
> I agree and ideally we would be able to call them hobbits, but sadly we
> can't until the trademark/copyright of The Hobbit expires. The official
> translations of this game into Italian and French are quite funny due to
> this, especially if you consider that Heroes 2 came out before a "hobbit"
> was mainstream knowledge because of the realse of the LoTR movies.
>
> The thing about "Trolls" is hard though. Goblins, Ogres and Trolls are all
> the same in danish.
>
> As a fellow Scandinavian, Norwegian to be precise, and having done the
> whole Norwegian translation myself, I know how hard these things can be to
> translate. I've even looked up Danish online dictionaries and wikipedia
> pages for translations just to have some ideas. If you have any pages to
> suggest then please share. I also use this Norwegian dictionary page
> <https://naob.no/ordbok/jette_1> frequently because it covers the
> etymology very well. It might help you too given our shared roots and that
> this page often references literature and the written language from when
> Norway was a part of Denmark, so essentially Danish to me :P
>
> I believe that a dane will understand this translation, due to our
> mainstream cultural knowledge of norse mythological lore.
>
> Like I said in the beginning, I'm fine with you calling them "Jætte",
> precisely because I suspected that "jætte" and "trold" in Danish are used
> interchangeably, whereas in Norwegian there is no doubt about it being a
> troll - The Three Billy Goats Gruff book is by a Norwegian author, but
> obviously based on our common Norse folklore/mythology. Still, this is a
> Danish translation so you are the linguistic and cultural expert here, I'm
> just giving help wherever I think I can.
>
> The Heroes 1 ogre on the other hand. They look just like a stereotypical
> caveman from the Stone Age!!! Haha..
>
> It is also a good point you are making about continuity with the other
> games in the series, so it might be helpful to look at how these creatures
> are visually represented before and later on in the series like you have
> mentioned doing and I've done myself.
>
> If you have the time and possibility to address my comments here then that
> would be great. I would also like to ask that you write a comment in each
> of the separate conversations here on this page so that it is easier to
> keep track of every single point made.
>
> Since I imagine you will have more than enough in your hands right now, I
> will make the necessary changes to have Danish included in the game options
> now. It takes me less than 10 minutes to do this and it will be very
> helpful for the work on the translation.
>
> We also have a couple of Danes in the fheroes2 Discord server that earlier
> have shown interest in a Danish translation, so I will ask them to have a
> look at this PR too.
>
> Also I wanted to tell you good job in translating "Zounds" so well the
> first time. This is one of the hardest lines to find a good translation for
> and most translators just give up and settle for "Hundreds" as a
> compromise. If it weren't for the length restrictions I mentioned, there
> would be no problem with your choice.
>
> Take care and I hope to hear from you soon.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ihhub/fheroes2/pull/6237#issuecomment-1332816517>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4HS6FJ7CMMORDSGLJJI2YLWK7ICHANCNFSM6AAAAAASGNHLTU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-03 01:01 UTC, ihhub commented
Hi @Stisen1 , it would be great if we can close this pull request before 15 December to include Danish into the list of supported languages for 1.0 release. I hope it would motivate even more🙂

2022-12-03 09:40 UTC, Stisen1 commented
Hi @Zenseii. I don't know whether my changes is updated as soon as I change
my "dk.po" file or not. Can you see the changes I made this morning, or is
it only visible to me in GitHub?

Den lør. 3. dec. 2022 kl. 02.02 skrev Ihar Hubchyk ***@***.***
>:

> Hi @Stisen1 <https://github.com/Stisen1> , it would be great if we can
> close this pull request before 15 December to include Danish into the list
> of supported languages for 1.0 release. I hope it would motivate even more
> 🙂
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ihhub/fheroes2/pull/6237#issuecomment-1335995141>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4HS6FIQBPH4D3YGFYRJ3BDWLKLYRANCNFSM6AAAAAASGNHLTU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-03 15:06 UTC, undef21 commented
Hello @Stisen1. Could you replace "da" with "dk" in these files because you use "dk" abbreviation?
```
src/engine/translations.cpp:376:        else if ( str == "da" || str == "danish" )
src/fheroes2/gui/ui_language.cpp:67:            { "da", fheroes2::SupportedLanguage::Danish },     { "danish", fheroes2::SupportedLanguage::Danish }
 };
src/fheroes2/gui/ui_language.cpp:230:            return "da";

```

2022-12-04 16:15 UTC, Stisen1 commented
I have no idea whether I did it correctly this time (just minutes before
this writing this email), but I hope it worked as intended. And when it
comes to changing "da", "dutch" and whatever into "da" and "danish", I have
no clue how to do that!... But I suppose someone recently did it for me. Am
I supposed to work in some program besides Poedit?

Mvh. Rasmus

Den lør. 3. dec. 2022 kl. 15.06 skrev Zenseii ***@***.***>:

> Hi, @Stisen1 <https://github.com/Stisen1>.
>
> I do not see any changes. To make changes to this PR you need to have
> selected the branch for this PR in github desktop, make changes to the
> dk.po file, then commit them, and finally push them with github desktop. In
> this case you have made the PR from your master branch, which is fine for
> this time but generally not recommended.
>
> I can walk you through it more if you need help.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ihhub/fheroes2/pull/6237#issuecomment-1336167592>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4HS6FIFYMJTUWQYYTGMVRTWLNHXZANCNFSM6AAAAAASGNHLTU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-04 17:01 UTC, Stisen1 commented
Well that is exactly what I thought I did everytime. However, these email
correspondences seem to be threaded inside GitHub Desktop too. But the only
way for me to find it, is by following links in this email-thread. When I
finally get inside GitHub, I don't understand how to respond to your
messages directly inside the program. I'll just continue with the
email-thingy until I do understand that GitHub-part... Also... I am very
tired these days due to my new born baby constantly needing my attention at
night... Sigh...

Rasmus / Stisen1

Den søn. 4. dec. 2022 kl. 17.36 skrev Zenseii ***@***.***>:

> Hi, @Stisen1 <https://github.com/Stisen1>.
>
> Yes, POedit is just a program that lets you edit a file containing the
> text to translate. You need to share your changes here in another way. The
> easiest way is to download a program called "Github Desktop". I have a
> guide somewhere on how to use it so I'll try to share that here, but in
> short you have to log in with your github account on it, clone your
> fheroes2 repo, add your changes to your local repo (by copy-pasting your
> dk.po over the online one) and then choose commit in github desktop and
> then push to this branch.
>
> I'm not sure how you were able to make the PR without doing this however?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ihhub/fheroes2/pull/6237#issuecomment-1336462576>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4HS6FPIZVWWKXM5PSL2EILWLTCARANCNFSM6AAAAAASGNHLTU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-07 19:53 UTC, Stisen1 commented
Whups! Jeg er ikke helt vågen for tiden! Det er da nogle værre stavefejl,
jeg har lavet!

Hvad er der med "spell | sløvning"? Jeg troede man skulle skrive "spell |"
fordi kodningen krævede det

ons. 7. dec. 2022 19.29 skrev Zenseii ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Hei, @Stisen1 <https://github.com/Stisen1>.
>
> Jeg har sett over oversettelsene og fant et par skrivefeil og noen ting
> jeg hadde spørsmål om.
> Det hadde vært supert om du kunne tatt en kikk på disse. Igjen må du bare
> se bort ifra de kommentarene som kommer av forskjeller mellom norsk og
> dansk.
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1042096701>:
>
> >
>
>  msgid "Low morale causes the %{monster} to freeze in panic."
>
> -msgstr ""
>
> +msgstr "Lav morale vækker frysende panik i troppen med %{monster}."
>
>
> "Morale" med "e" ser ut til å bare referere til moralen i en fortelling på
> dansk i følge denne ordboken. Stemmer det? Vennligst se bort ifra dette
> hvis det er helt feil.
> https://ordnet.dk/ddo/ordbog?aselect=moral,a&query=morale
> Det er ett oppslag for moral og morale, og et annet for kun moral til
> høyre på nettsiden.
>
> Dette gjelder også for de andre stedene der morale er brukt.
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1042104023>:
>
> >
>
>  msgid "Upg. Archery Range"
>
> -msgstr ""
>
> +msgstr "Opg. Bueskydningsbane"
>
>
> Burde disse ha stor bokstav, her "Bueskydningsbane", selv etter en
> forkortelse? Dette gjelder også for andre lignende tilfeller.
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1042108478>:
>
> >
>
>  msgid "sorceress|Red Tower"
>
> -msgstr ""
>
> +msgstr "Rødt tårn"
>
>
> I fheroes2 har vi gjort det mulig å gi forskjellige oversettelser til
> røddragenes røde tårn og føniksenes røde tårn.
> Dette er opp til deg om du for eksempel vil kalle føniksenes tårn for noe
> sånt som "Ildtårn" eller andre ting bare for å gi litt mer variasjon i
> spillet.
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1042116165>:
>
> >
>
>  msgid "Slows target to half movement rate."
>
>  msgstr ""
>
>
>
>  msgid "spell|Slow"
>
> -msgstr ""
>
> +msgstr "spell|Sløvning"
>
>
> Her har konteksten "spell|" sneket seg inn.
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1042116405>:
>
> > @@ -8141,10 +8141,10 @@ msgid "Clouds the affected creatures' eyes, preventing them from moving."
>
>  msgstr ""
>
>
>
>  msgid "spell|Blind"
>
> -msgstr ""
>
> +msgstr "spell|Blinding"
>
>
> Her har også konteksten sneket seg inn.
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1042118174>:
>
> >
>
>  msgid "Berserker"
>
> -msgstr ""
>
> +msgstr "Berserker"
>
>
> Skal det være "æ" her? Bare se bort fra dette dersom det er feil fra min
> side.
> https://ordnet.dk/ddo/ordbog?query=bers%C3%A6rk
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1042118919>:
>
> >
>
>  msgid ""
>
>  "Damages all living (non-undead) units in the battle.  This spell is an "
>
>  "improved version of Death Ripple."
>
>  msgstr ""
>
>
>
>  msgid "Dragon Slayer"
>
> -msgstr ""
>
> +msgstr "Drage Dræber"
>
>
> Burde dette være ett ord?
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1042120466>:
>
> >
>
>  msgid "Summon Earth Elemental"
>
> -msgstr ""
>
> +msgstr "Hidkald Jord-elemental"
>
>
> Her er det ikke brukt stor E for "elemental", men ellers er det brukt stor
> E.
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1042532694>:
>
> > +
>
> +msgid ""
>
> +"Toggle on or off a shadow showing the current hex location of the mouse "
>
> +"cursor."
>
> +msgstr ""
>
> +"Vælg om der skal være skygger, som viser musemarkørens nuværende hex-"
>
> +"lokation, eller ej."
>
> +
>
> +msgid "The enemy has surrendered!"
>
> +msgstr "Fjenden har overgivet sig!"
>
> +
>
> +msgid "The enemy has fled!"
>
> +msgstr "Fjenden er flygtet!"
>
> +
>
> +msgid "A glorious victory!"
>
> +msgstr "En gloværdig sejr!"
>
>
> Mangler det en R her? "glorværdig"?
> https://ordnet.dk/ddo/ordbog?query=glorv%C3%A6rdig
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1042535675>:
>
> > +msgstr "Magikraft"
>
> +
>
> +msgid "Knowledge"
>
> +msgstr "Kundskab"
>
> +
>
> +msgid "Morale"
>
> +msgstr "Morale"
>
> +
>
> +msgid "Luck"
>
> +msgstr "Held"
>
> +
>
> +msgid "Spell Points"
>
> +msgstr "Magipoint"
>
> +
>
> +msgid "Hero's Options"
>
> +msgstr "Helts træk"
>
>
> Lengre ned blir dette oversatt som "Helts muligheder". Er dette med vilje?
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1042540412>:
>
> > +msgstr "%{race2} %{name2}"
>
> +
>
> +msgid "Monsters"
>
> +msgstr "Monstre"
>
> +
>
> +msgid "N/A"
>
> +msgstr "Ingen"
>
> +
>
> +msgid "Left Turret"
>
> +msgstr "Venstre tårn"
>
> +
>
> +msgid "Right Turret"
>
> +msgstr "Højre tårn"
>
> +
>
> +msgid "The %{name} fires with the strength of %{count} Archers"
>
> +msgstr "Borgens %{name} med en styrke af %{count} Bueskyttere"
>
>
> Mangler det "skyter" her?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ihhub/fheroes2/pull/6237#pullrequestreview-1208258849>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4HS6FPGRYRGUI2C3MLXMKTWMDJSHANCNFSM6AAAAAASGNHLTU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-08 12:26 UTC, Stisen1 commented on files/lang/dk.po
> +msgstr "Hidkald Jord-elemental"
Jeg forstår ikke hvad du mener. Det er ét ord med bindestreg. Hvor bruger jeg ellers stort E? Mener du når jeg blot fx i ID50 skriver : "Der er ingen åben plads ved siden af din helt til at hidkalde en Elemental på."?

2022-12-10 09:46 UTC, Stisen1 commented
Puha. Hvor meget skal jeg helst have oversat, før dansk kan komme med i
næste version af spillet? 😅 Jeg mangler at oversætte 1800 tekst-ID'er.
Hvis jeg nu springer over alt det, som har med campaign at gøre, kan jeg
vel opnå et delmål?

tor. 8. dec. 2022 13.36 skrev Zenseii ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In files/lang/dk.po
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1043305234>:
>
> >
>
>  msgid "Summon Earth Elemental"
>
> -msgstr ""
>
> +msgstr "Hidkald Jord-elemental"
>
>
> Jepp, jeg ser at noen steder skrives elemental med stor E og her er det
> med liten e, men det gir vel mening at når det er bindestrek så skrives det
> med liten e. Det er helt opp til deg om du vil gjøre noe med dette eller la
> det stå sånn.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ihhub/fheroes2/pull/6237#discussion_r1043305234>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4HS6FKB4BFGGHQHEIGVPYLWMHI3XANCNFSM6AAAAAASGNHLTU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-10 16:19 UTC, Stisen1 commented
Jeg har forsøgt at rette de fejl, som du fandt frem til sidst. Jeg har
desuden tilføjet en 150 stykker.

Kan jeg uploade det via GitHub i browseren? Jeg sidder på min
arbejdscomputer, som desværre ikke har tilladelse til at installere GitHub
Desktop

Den lør. 10. dec. 2022 kl. 14.01 skrev Zenseii ***@***.***>:

> Hei, @Stisen1 <https://github.com/Stisen1>.
>
> Som sagt tidligere så er delmålet allerede nådd og vel så det. Vi har som
> sagt en grense på 400 linjer oversatt per PR. Din PR inneholder nå rundt
> 500 linjer. Fokuset som sagt er nå å ta stilling til og evt rette opp de
> tingene jeg fant og kommenterte sist gang jeg gikk gjennom alt.
>
> Du har forresten ikke lastet opp noen flere endringer her. Husk å sjekk at
> du har gjort dette ved å gå inn på selve nettsiden til PRen din.
>
> Bare spør hvis det er noe du lurer på!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ihhub/fheroes2/pull/6237#issuecomment-1345260189>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4HS6FKJ3T5WFGVOGWOAP5TWMR5LFANCNFSM6AAAAAASGNHLTU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-16 01:39 UTC, ihhub commented
Hi @Stisen1 , please revert newly added lines for translation otherwise it would be extremely difficult to progress with this pull request. Despite of fact that translation might look easy to make the review process takes more time than the actual work. Also you made some changes in your last commit like removing comments or modifying language name. Please revert them back as well.

If you aren't sure how to do it I can revert your last commit and you can add changes only requested by @zenseii so we can progress with this pull request and eventually accept and merge it.

2022-12-16 08:27 UTC, Stisen1 commented
Oh. I thought I was requested to make changes to modifying the language
name. But I must have done it the wrong way. I am sorry.

Also, I am aware of the immense work, that must be put into reviewing the
pull requests. Although I thought that Zenseii didn't have to go through
everything, every time I add changes to the po-file.

So... Am I supposed to just wrap up the changes Zenseii suggested, first,
and when they are accepted, I can close the pull and start a new one?

I don't know how to rollback changes. But I have an old version of the
po-file on my PC. The one that Zenseii reviewed the last time.

I am really having a hard time, understanding how GitHub and all this pull
this and fetch that works. It seems that I keep making new pull requests,
but I am not doing this on purpose! Zenseii shouldn't review files, that I
have uploaded incorrectly! Let's do this right, ones and for all... from
now on...

Stisen1

Den fre. 16. dec. 2022 kl. 02.39 skrev Ihar Hubchyk <
***@***.***>:

> Hi @Stisen1 <https://github.com/Stisen1> , please revert newly added
> lines for translation otherwise it would be extremely difficult to progress
> with this pull request. Despite of fact that translation might look easy to
> make the review process takes more time than the actual work. Also you made
> some changes in your last commit like removing comments or modifying
> language name. Please revert them back as well.
>
> If you aren't sure how to do it I can revert your last commit and you can
> add changes only requested by @zenseii <https://github.com/zenseii> so we
> can progress with this pull request and eventually accept and merge it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ihhub/fheroes2/pull/6237#issuecomment-1354057340>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4HS6FKVPDDA5PPXQTKTSFDWNPB35ANCNFSM6AAAAAASGNHLTU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-16 09:59 UTC, ihhub commented
Hi @Stisen1 , no worries. We are here not to criticize anyone's work but to create an awesome product. I can revert your latest commit if you don't mind. No need to close this pull request but just stick to the same amount of lines being translated for ease of progress. Once we review and merge the translation for these lines you can create another pull request to add more translated text.

2022-12-17 06:55 UTC, Stisen1 commented
I have tried to revert the changes back to 7. december.

Den fre. 16. dec. 2022 kl. 11.03 skrev Zenseii ***@***.***>:

> Hi, @Stisen1 <https://github.com/Stisen1>.
>
> I see that there is some misunderstanding of the Github terminology too.
> So far you have only opened 1 Pull Request (PR), and every time you have
> been uploading/pushing changes online they have been "commits" to this PR.
>
> When this PR is merged with its changes you are free to open a new PR, but
> not before because we have a limit on 1 PR existing per language at a time
> to avoid duplicate work and to keep things tidy.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ihhub/fheroes2/pull/6237#issuecomment-1354495298>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4HS6FLRAYGRWN7AVVMK2J3WNQ47VANCNFSM6AAAAAASGNHLTU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-18 19:32 UTC, Stisen1 commented
I have moved files from "ny mappe" to the right directory. I could have
sworn, that I already did that ones way back... The way GitHubs interface
works really doesn't make a lot of sense to me. I must constantly be
confused by something, and then I keep messing up things that must be
absolutely easy for you to understand.

Am I supposed to merge something now? Or can you do it for me?

Stisen1

Den lør. 17. dec. 2022 kl. 10.55 skrev Zenseii ***@***.***>:

> Hi, @Stisen1 <https://github.com/Stisen1>.
>
> You have uploaded many new files in a new folder named "Ny mappe" with the
> last commit. Please refer to the info about your latest commit that you can
> find here: e376530
> <https://github.com/ihhub/fheroes2/commit/e376530e7b6a62104ddf3981592b6e429ec88e2e>
> Anything that github desktop notices that is changed within you fheroes2
> source folder that you have it set to, will be uploaded and regarded as a
> change.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ihhub/fheroes2/pull/6237#issuecomment-1356149092>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4HS6FN2MBTE6YHJ2RUAMKTWNWEXPANCNFSM6AAAAAASGNHLTU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-16 10:06 UTC, Stisen1 commented
Is this danish translation project still going? Maybe you forgot to respond
my last comment, due to the immense work you guys have put into releasing
1.0 version :-D

Stisen1

Den søn. 18. dec. 2022 kl. 20.31 skrev rasmus vestergaard stisen <
***@***.***>:

> I have moved files from "ny mappe" to the right directory. I could have
> sworn, that I already did that ones way back... The way GitHubs interface
> works really doesn't make a lot of sense to me. I must constantly be
> confused by something, and then I keep messing up things that must be
> absolutely easy for you to understand.
>
> Am I supposed to merge something now? Or can you do it for me?
>
> Stisen1
>
> Den lør. 17. dec. 2022 kl. 10.55 skrev Zenseii ***@***.***>:
>
>> Hi, @Stisen1 <https://github.com/Stisen1>.
>>
>> You have uploaded many new files in a new folder named "Ny mappe" with
>> the last commit. Please refer to the info about your latest commit that you
>> can find here: e376530
>> <https://github.com/ihhub/fheroes2/commit/e376530e7b6a62104ddf3981592b6e429ec88e2e>
>> Anything that github desktop notices that is changed within you fheroes2
>> source folder that you have it set to, will be uploaded and regarded as a
>> change.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ihhub/fheroes2/pull/6237#issuecomment-1356149092>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/A4HS6FN2MBTE6YHJ2RUAMKTWNWEXPANCNFSM6AAAAAASGNHLTU>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2023-01-16 20:30 UTC, Stisen1 commented
Okay. No worries. There is no stress on my part. I only want to deliver the
goods, if the community and your project needs it. I am worried, if the
danish translation project turns over to other hands, due to my
incompetence! 😅

man. 16. jan. 2023 13.28 skrev Zenseii ***@***.***>:

> Hi, @Stisen1 <https://github.com/Stisen1>. There are still lots of new
> folders and changes to unrelated files due to the creation of "ny mappe"
> etc. I'll have a look at sorting this out for you and look at the changes
> you added the last commit as soon as I have time.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ihhub/fheroes2/pull/6237#issuecomment-1383983582>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4HS6FIINLUQMYODS2DGVTTWSU5HXANCNFSM6AAAAAASGNHLTU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-31 13:51 UTC, merged

2023-01-31 13:52 UTC, ihhub commented
@Stisen1 , thank you very much for your contribution to the project!

2023-01-31 14:40 UTC, Stisen1 commented
Hi, @Zenseii

I have just pulled down the updated files to my local directory and made a
copy of the "dk.po" file as it is NOW!

I guess I have to merge my newest file from 17th december with the new one
from 25th january. Then I'll use Edit Notepad++ to merge them properly, and
then make a new PR with the updated file.

I will try to do the aforementioned things WITHOUT corrupting your version
of the dk.po-file! I'll keep it safe and unchanged in another local
directory.

Den man. 16. jan. 2023 kl. 13.28 skrev Zenseii ***@***.***>:

> Hi, @Stisen1 <https://github.com/Stisen1>. There are still lots of new
> folders and changes to unrelated files due to the creation of "ny mappe"
> etc. I'll have a look at sorting this out for you and look at the changes
> you added the last commit as soon as I have time.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ihhub/fheroes2/pull/6237#issuecomment-1383983582>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4HS6FIINLUQMYODS2DGVTTWSU5HXANCNFSM6AAAAAASGNHLTU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-31 16:08 UTC, Stisen1 commented
Some 80-100 lines have been changed and is up for a PR. I hope it works as
it should this time :P

Den tir. 31. jan. 2023 kl. 16.54 skrev Zenseii ***@***.***>:

> Sounds good, @Stisen1 <https://github.com/Stisen1> and welcome to the
> contributor role!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ihhub/fheroes2/pull/6237#issuecomment-1410636104>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4HS6FJZYJMYI5NAHAWYYT3WVEYUHANCNFSM6AAAAAASGNHLTU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>