[experimental] logarithmic sound volume
ihhub/fheroes2 pull request #6242
Opened 2022-11-22 08:52 UTC by undef21

related issue #6230

2022-11-22 08:57 UTC, undef21 commented
@ihhub, @Branikolog could you check sound levels in this PR? I changed music level in the options dialog in the main menu. Please use external music.

2022-11-24 12:29 UTC, Branikolog commented
Hi, @undef21 Actually, I cannot hear much difference comparing with current version.

2022-11-24 15:59 UTC, undef21 commented
@Branikolog could you check this PR again?

2022-11-24 18:53 UTC, Branikolog commented
Hi, @undef21 
Now's much better!
I only hear sometimes a short click sound (something similar to pluging headphones into 3.5 jack) , while increasing volume to the higher values, but I'm not sure, it's not my local problem of OS or notebook speakers. I'll check tomorow on my other PC.

2022-11-24 19:18 UTC, undef21 commented
> I'm not sure, it's not my local problem of OS or notebook speakers.

Also check this in the master branch please.

2022-11-25 10:37 UTC, Branikolog commented
Hi, @undef21 .
On my other PC everything seems to be OK. Probably my home PC speakerphones seem to be a bit overloaded on high volume setting, that's why I can hear sometimes a little noise while rising it up.

2022-11-28 09:41 UTC, undef21 commented
Hello @Branikolog. Could you listen this PR again?

2022-12-01 12:41 UTC, Branikolog commented
Hi, @undef21 !
Sorry, for late response!
Everything looks fine!

2022-12-03 00:54 UTC, ihhub requested changes

2022-12-03 00:54 UTC, ihhub commented on src/engine/audio.cpp
> +        return static_cast<int>( ( std::exp( std::log( 10 + 1 ) * volumePercentage / 100 ) - 1 ) / 10 * MIX_MAX_VOLUME );
Could you please explain why we use a logarithm of 11 instead of 10? Also this formula needs a bit of explanation.

2022-12-03 08:08 UTC, undef21 commented on src/engine/audio.cpp
> +        return static_cast<int>( ( std::exp( std::log( 10 + 1 ) * volumePercentage / 100 ) - 1 ) / 10 * MIX_MAX_VOLUME );
Hello, @ihhub. The good explanation is [here](https://www.dr-lex.be/info-stuff/volumecontrols.html#ideal2). I used that article.

Resulting curve is:
```
y = ae^(bx) + c
a = 1/10
c = -1/10
b = ln(1 + 1/a) = ln 11
```

2022-12-08 08:30 UTC, ihhub commented on src/engine/audio.cpp
> +        return static_cast<int>( ( std::exp( std::log( 10 + 1 ) * volumePercentage / 100 ) - 1 ) / 10 * MIX_MAX_VOLUME );
I would suggest to at least add a comment with this link for any possible future questions.

2022-12-09 12:07 UTC, undef21 commented on src/engine/audio.cpp
> +        return static_cast<int>( ( std::exp( std::log( 10 + 1 ) * volumePercentage / 100 ) - 1 ) / 10 * MIX_MAX_VOLUME );
Done.

2022-12-10 09:37 UTC, oleg-derevenetz approved these changes

2022-12-12 00:40 UTC, ihhub approved these changes

2022-12-12 12:50 UTC, merged

2022-12-12 12:50 UTC, ihhub commented
@undef21 , thank you so much for this great improvement!