Add Android installation and usage documentation
ihhub/fheroes2 pull request #6243
Opened 2022-11-22 15:56 UTC by zenseii

2022-11-22 16:46 UTC, zenseii commented on docs/README_android.md
> +
Not sure how that managed to sneak in there.
```suggestion
```

2022-11-22 20:58 UTC, oleg-derevenetz requested changes
Hi @zenseii I just left a few comments, please take a look when it's convenient.

2022-11-22 20:58 UTC, oleg-derevenetz commented on docs/README_android.md
> +Copy HEROES2.AGG and HEROES2X.AGG (if you own the Price of Loyalty expansion) from the original game's "DATA" folder into
AFAIK, these are not the only files that need to be copied. There are also some SMK files here that are needed for campaign, for example, `IVYDES.SMK`. IMHO it is better to recommend copying the entire contents of the `DATA` folder.

2022-11-22 20:58 UTC, oleg-derevenetz commented on docs/README_android.md
> +The music files should be placed in the "internalStorage:Android/data/org.fheroes2/files/maps/" folder.
Do you mean `.../files/music/` folder?

2022-11-22 20:58 UTC, oleg-derevenetz commented on docs/README_android.md
> +To simulate a right click to get info on various items, you need to first touch and keep touching anywhere on the screen
"anywhere on the screen outside the game window"... or something like that. I admit that "game window" doesn't fit well.

2022-11-22 21:05 UTC, zenseii commented on docs/README_android.md
> +To simulate a right click to get info on various items, you need to first touch and keep touching anywhere on the screen
I agree that my original phrasing could do with improvement. By saying "anywhere on the screen" I'm trying to include the area of the screen that has the game rendered to it, because this works too, as well as a potential border for lower-than-native resolutions like 640x480.

2022-11-22 21:12 UTC, zenseii commented on docs/README_android.md
> +To simulate a right click to get info on various items, you need to first touch and keep touching anywhere on the screen
You are right that this could happen. It can be avoided if you first raise the initial finger you pressed down. We should also remember if someone uses the device's full resolution then there is no area outside game window.

2022-11-22 21:18 UTC, oleg-derevenetz commented on docs/README_android.md
> +To simulate a right click to get info on various items, you need to first touch and keep touching anywhere on the screen
> We should also remember if someone uses the device's full resolution then there is no area outside game window.

When using full resolution on a handheld device, all objects will be tiny. Also aspect ratio on phones is non-standard, so usually there are black bars on the sides.

2022-11-22 21:26 UTC, zenseii commented on docs/README_android.md
> +To simulate a right click to get info on various items, you need to first touch and keep touching anywhere on the screen
Full native resolution on phones is mostly useless right now, unless you mirror/cast or connect your phone to a separate monitor for playing fheroes2 (which is a good idea btw), Aside from this there are also Android tablets with larger screens, and native resolution would be relevant for them.

2022-11-22 21:32 UTC, oleg-derevenetz commented on docs/README_android.md
> +To simulate a right click to get info on various items, you need to first touch and keep touching anywhere on the screen
It would be desirable to at least recommend to place the first finger outside the game area, if possible, to avoid false "clicks".

2022-11-22 21:33 UTC, zenseii commented on docs/README_android.md
> +To simulate a right click to get info on various items, you need to first touch and keep touching anywhere on the screen
Yes, this is a good point. I'll try to come up with something that fits the various scenarios.

2022-11-23 23:25 UTC, oleg-derevenetz commented on docs/README_android.md
> +item. It is recommended to place the first touch outside the rendered game area to avoid performing a left-click after
How about "... to avoid accidental left-click ..."?

2022-11-24 09:57 UTC, oleg-derevenetz approved these changes

2022-11-25 12:45 UTC, ihhub commented on docs/README_android.md
> +Copy the the contents of the original game's "DATA" folder into the "internalStorage:Android/data/org.fheroes2/files/data/"
How about "Copy data, music, maps and anim directories into ..."? I think this is much easier to do then creating folders and copying files. What do you think?

2022-11-25 14:30 UTC, zenseii commented on docs/README_android.md
> +Copy the the contents of the original game's "DATA" folder into the "internalStorage:Android/data/org.fheroes2/files/data/"
Yes, this is better.

2022-11-25 18:21 UTC, oleg-derevenetz approved these changes

2022-11-25 22:43 UTC, ihhub approved these changes

2022-11-25 22:44 UTC, merged

2022-11-25 22:44 UTC, ihhub commented
@zenseii , thank you so much for this update!