add cross building for ARM64
ihhub/fheroes2 pull request #6246
Opened 2022-11-23 11:37 UTC by undef21

2022-12-09 04:20 UTC, ihhub requested changes
Hi @undef21 , I put several comments here. Can you please check them?

2022-12-09 04:20 UTC, ihhub commented on .github/workflows/make.yml
> +          release_tag: fheroes2-linux-sdl2_dev
We have an old release tag used for Ubuntu ARM SDL2 builds: fheroes2-linux-arm-sdl2_dev. Please use this.

2022-12-09 04:20 UTC, ihhub commented on .github/workflows/make.yml
> +        - name: Linux ARM64 SDL2 Release
What's about SDL1?

2022-12-09 04:20 UTC, ihhub commented on .github/workflows/make.yml
> +          package_name: fheroes2_ubuntu_amd64_SDL1.zip
If we update package names we should update them in the documentation files as they point to the links. However, do we need to update them? amd64 is not intuitive for every user.

2022-12-09 04:20 UTC, ihhub commented on .github/workflows/make.yml
> +          release_name: Ubuntu (Linux) build with SDL2 (latest commit)
This name should have an explicit ARM word usage.

2022-12-12 10:12 UTC, undef21 commented on .github/workflows/make.yml
> +          release_tag: fheroes2-linux-sdl2_dev
Done.

2022-12-12 10:13 UTC, undef21 commented on .github/workflows/make.yml
> +        - name: Linux ARM64 SDL2 Release
Added SDL1 Release and Debug.

2022-12-12 10:14 UTC, undef21 commented on .github/workflows/make.yml
> +          package_name: fheroes2_ubuntu_amd64_SDL1.zip
Reverted package names for x86.

2022-12-12 10:15 UTC, undef21 commented on .github/workflows/make.yml
> +          release_name: Ubuntu (Linux) build with SDL2 (latest commit)
Done.

2022-12-19 12:39 UTC, oleg-derevenetz approved these changes

2022-12-20 10:22 UTC, oleg-derevenetz commented
Hi @ihhub I believe we can merge this PR since it does not affect the game code itself, just our build system.

2022-12-20 12:11 UTC, ihhub approved these changes

2022-12-20 12:11 UTC, merged

2022-12-20 12:11 UTC, ihhub commented
@undef21 , thanks you very much for this change!