An attempt to recreate the original rainbow animation (battlefield)
ihhub/fheroes2 pull request #6257
Opened 2022-11-26 13:25 UTC by Districh-ru

This PR changes the way the rainbow is drawn for the "good luck" event on the battlefield:

https://user-images.githubusercontent.com/113276641/204090850-53f04cc6-e391-43a2-bb5f-36271947d441.mp4

(In this video "good luck" is force set to 'true')

![изображение](https://user-images.githubusercontent.com/113276641/204091172-3b7500ea-570b-4b63-b33d-9563294be0ab.png)

2022-11-27 01:58 UTC, oleg-derevenetz commented
I've always been a little concerned about the duration of this animation. If the unit is located unsuccessfully, then the rainbow can be drawn for a long time :)

2022-11-27 05:05 UTC, Districh-ru commented
> I've always been a little concerned about the duration of this animation. If the unit is poorly positioned, then the rainbow can be drawn for a long time :)

Hi @oleg-derevenetz, I was also concerned about it and in the beginning the animation step was `const int32_t drawStep = borderDistance / 30;`. But later I changed it to a constant to reproduce the original game behavior.

@Branikolog, @LeHerosInconnu, what do you think: rainbow should have constant animation step or constant animation time?

2022-11-27 11:54 UTC, ihhub requested changes
Hi @Districh-ru , I left multiple comments here. Can you please check them?

2022-11-27 11:54 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +            // normalize 'x' coordinate to 4.6 (for 'fheroes2' rainbow colors) regions, each region is 256 units long
The comment says 4.6 but in the code it is 4.65. Please correct.

2022-11-27 11:54 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    // for positive width arc will start from y = 0, for negative it will end at y = 0
It is optional but having a capital letter at the beginning of the comments and a full stop make them slightly better to read :)

2022-11-27 11:54 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    for ( int x = 0; x < std::abs( width ); ++x ) {
To avoid unnecessary computations by calling `std::abs()` please accept this variable without const and then reassign it using this function.

2022-11-27 11:54 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +fheroes2::Image DrawRainbow( const std::vector<double> & rainbowArc, const int32_t & rainbowThickness, bool isVertical = false )
Please remove the default parameter since all usages of this function provide 3 parameters.

2022-11-27 11:54 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    for ( int x = 0; x < std::abs( width ); ++x ) {
Please use `int32_t` instead of `int` to be consistent with types.

2022-11-27 11:54 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +fheroes2::Image DrawRainbow( const std::vector<double> & rainbowArc, const int32_t & rainbowThickness, bool isVertical = false )
Please remove reference symbol from `rainbowThickness` as passing POD is always recommended by value.

2022-11-27 11:54 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +            pow1 = 2, pow2 = 10, pow3 = 2, pow4 = 2;
Please do not use multiple operations at single line. Always put one operation on a separate line.

2022-11-27 11:54 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        fheroes2::Image luckSprite = fheroes2::Flip( DrawRainbow( rainbowArc, rainbowThickness, isVerticalRainbow ), isRainbowFromRight, false );
Here we create 2 images. I suggest to do this way:
```cpp
fheroes2::Image luckSprite;
if ( isRainbowFromRight ) {
    luckSprite = fheroes2::Flip( DrawRainbow( rainbowArc, rainbowThickness, isVerticalRainbow ), true, false );
}
else {
    luckSprite = DrawRainbow( rainbowArc, rainbowThickness, isVerticalRainbow );
}
```
This code is bit longer but for cases when `isRainbowFromRight` is **false** it works much faster.

2022-11-27 11:54 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +            const int32_t normalized = static_cast<int32_t>( ( i - frac ) * 256 * 4.65 / rainbowThickness );
`256 * 4.65 / rainbowThickness` could be cached outside the double loop.

2022-11-27 11:54 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        arc.push_back( y );
We can combine these 2 lines and directly pass the calculated value to `push_back()` call.

2022-11-27 11:54 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +                break;
We are missing here the default case.

2022-11-27 11:54 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        const bool isRainbowFromRight = ( unit.GetCurrentColor() == arena.GetArmy2Color() );
Please use `isReflect()` method instead of this approach.

2022-11-27 12:12 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +            // normalize 'x' coordinate to 4.6 (for 'fheroes2' rainbow colors) regions, each region is 256 units long
Thank you @ihhub, it should be 4.6 in the code.
I was seeking the theshold where purple turns to red and forgot to correct here. :(

2022-11-27 12:38 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +    for ( int x = 0; x < std::abs( width ); ++x ) {
Part of the game code uses 'int' and the other 'int32_t' so I'm confused what to use. Initially, I wrote 'int' everywhere, later I changed it to 'int32_t' and, of course, forgot to change it in this place.

2022-11-27 13:31 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +        fheroes2::Image luckSprite = fheroes2::Flip( DrawRainbow( rainbowArc, rainbowThickness, isVerticalRainbow ), isRainbowFromRight, false );
Made this by integrating the flip operation into the `DrawRainbow` function, so the `Flip` function is no longer needed.

2022-11-27 13:43 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +        const bool isRainbowFromRight = ( unit.GetCurrentColor() == arena.GetArmy2Color() );
@ihhub, `isReflect()` checks if the unit sprite is reflected and, for example, if the right army creature (with `isReflect()=1`) attacks from the left if turns and then we check the `isReflect()` and it returns `0`.
I wanted the rainbow to ascend from the side of the creature's hero.

2022-11-27 14:07 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +        const bool isRainbowFromRight = ( unit.GetCurrentColor() == arena.GetArmy2Color() );
@ihhub, thanks a lot for reviewing my code and for optimization tips! I will take them into account.

2022-11-27 14:17 UTC, Branikolog commented
Hi, @Districh-ru 

> what do you think: rainbow should have constant animation step or constant animation time?

I cannot tell precisely right now. It would be easier to tell, if I'd test both versions. :)
I think, I would prefer constant animation time more, since on high speeds I can't even notice that short rainbow.
Btw, the work you've done looks really nice! 👍 
I noticed only a small difference in colours. 
Don't blame me much, but I like your previous implementation of rainbow for higher sells you've shown at https://github.com/ihhub/fheroes2/pull/6179#issuecomment-1325462651 . I personally would love to have in game something in between current (original) and the one I mentioned above. Something a little bit more parabolic-like. Just my thoughts, anyway. :)

2022-11-27 15:18 UTC, Districh-ru commented
> Hi, @Districh-ru
> 
> > what do you think: rainbow should have constant animation step or constant animation time?
> 
> I cannot tell precisely right now. It would be easier to tell, if I'd test both versions. :) I think, I would prefer constant animation time more, since on high speeds I can't even notice that short rainbow. Btw, the work you've done looks really nice! 👍 I noticed only a small difference in colours. Don't blame me much, but I like your previous implementation of rainbow for higher sells you've shown at [#6179 (comment)](https://github.com/ihhub/fheroes2/pull/6179#issuecomment-1325462651) . I personally would love to have in game something in between current (original) and the one I mentioned above. Something a little bit more parabolic-like. Just my thoughts, anyway. :)

Hi, @Branikolog 
On the video you mentioned, the animation time is constant.
I can set minimum draw parts to avoid super fast rainbow rendering for small rainbows, and set maximum draw parts for long ones. What do you think?
All rainbow parameters are calculated by linear equations and depend on the rainbow length. We can set a minimum rainbow arc height for small rainbows. (In my first video, the arc height was constant.) 
For example we can change it to start from about 10px:

https://user-images.githubusercontent.com/113276641/204142849-57e75059-951e-4576-9aa9-180120486380.mp4


But it won't be the same as original. Both options (orginal or not) will suit me as well.
...maybe in the future these parameters will be set by some game presets and maybe by the players themselves...

2022-11-27 15:41 UTC, Districh-ru commented
@Branikolog, what do you think of this:

https://user-images.githubusercontent.com/113276641/204143877-bd8857a9-735c-4819-9ffb-47d339142fc3.mp4



In this video, the maximum number of animation steps is set to 40 and the minimum to 20. So we don't have very slow and very fast animations.
If it is ok, I'll add it to the next commit.

2022-11-27 18:56 UTC, Branikolog commented
Hi, @Districh-ru 
For me personally, rainbows from the last video have acceptable generation speed and nice-looking ark height. But lets listen to other members, probably, they would be satisfied with more original-like behaviour.

2022-11-27 19:36 UTC, zenseii commented
Hi, guys. I'm fine with whichever.
My only concern is that it should speed up according to the battle speed that is set, but if that doesn't happen now in this PR then I wouldn't worry and just open that can in the future.

2022-11-27 20:14 UTC, LeHerosInconnu commented
Hello everyone,

I think that the duration of the rainbow animation should be the same whatever the length of the rainbow.

The rainbow animation should be finished before the end of the rainbow sound.

In the original game, the rainbow does not necessarily originate on the same side of the screen as the troop (coming from the right side of the screen for troops positioned on the right side of the screen at the beginning of the combat).

In the original game, the rainbow does not necessarily originate on the right or left side of the screen, it can also originate at the top of the screen.

In original game:

https://user-images.githubusercontent.com/43583994/204157298-8f2056c3-a40c-4b42-b034-25ca98add5ab.mp4

![vlcsnap-2022-11-27-21h02m27s027](https://user-images.githubusercontent.com/43583994/204157372-a0da905f-ce5d-422e-b341-c8102abf1a7f.png)

![vlcsnap-2022-11-27-21h03m57s136](https://user-images.githubusercontent.com/43583994/204157378-4b692964-728b-4d94-9ea2-f39d982541ab.png)

![vlcsnap-2022-11-27-21h04m15s302](https://user-images.githubusercontent.com/43583994/204157383-f4e76958-81b2-4d6a-8c22-04ff249ea498.png)

![vlcsnap-2022-11-27-21h04m32s732](https://user-images.githubusercontent.com/43583994/204157390-485f187e-c9f9-4ae2-8257-0e9ba8c89825.png)

Here is the test scenario file:
[0 9926.zip](https://github.com/ihhub/fheroes2/files/10099124/0.9926.zip)

2022-11-27 21:34 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    for ( int x = 0; x < std::abs( width ); ++x ) {
Yes, it's a mix of here and there. In such cases use the majority rule 🙂

2022-11-27 21:35 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        const bool isRainbowFromRight = ( unit.GetCurrentColor() == arena.GetArmy2Color() );
@Districh-ru , in this case make sure that such logic covers cases like Berserk spell. I'll check later this again.

2022-11-28 07:37 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +        const bool isRainbowFromRight = ( unit.GetCurrentColor() == arena.GetArmy2Color() );
@ihhub , for Berserk spell (color == -1) and in other similar cases the rainbow will always be from the left. In this case (color < 0) I cuold use unit.GetColor. I'll do this in next commit.

2022-11-28 08:04 UTC, Districh-ru commented
Hello @zenseii , @LeHerosInconnu ,
The animation speed depends on the 'battle speed' setting.
I can make a constant count of drawing steps so on zero speed the animation time will be the same as rainbow sound time.
As I noticed, the original game draws a horisontal rainbow for the cretures in the upper 3 hexes and starting from the side of creatures army.
For the lower creatures the rainbow always comes from the top of the screen ("vertical rainbow"). And in original game its direction is not clear.
For such vertical rainbows I can set its direction according to the position of the creature. So it will always have full size and its trajectory will not be squeezed like in my last videos. (I'll try to implement this in the evening.)
What do you think?

2022-11-28 15:48 UTC, Districh-ru commented
Implementation of the vertical rainbow orientation approach mentioned above with corrected draw speed:

https://user-images.githubusercontent.com/113276641/204320997-d367d153-88c9-422f-b071-fc26f62a107c.mp4

2022-11-28 18:42 UTC, Districh-ru commented
What do you think about making the rainbow colors completely look like the original ones (from the center of the luck sprite)?

https://user-images.githubusercontent.com/113276641/204354329-a241cc36-ffe4-4dee-ab18-759ef8aa5d37.mp4

It is simpler and requires less computing resources. (Why did I choose the hardest way in the first place??? - Because I wanted to make a smoother transition of rainbow colors in the curve.)

2022-11-28 19:35 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +        rainbowLine = fheroes2::Crop( luckSprite, luckSprite.width() / 2, 0, 1, rainbowThickness );
Changed luckSprite type to fheroes2::Image

2022-12-02 02:04 UTC, ihhub requested changes
Hi @Districh-ru , I put several more comments here. Could you please take a look at them?

2022-12-02 02:04 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +            // Formula for rainbowTop corresponding to the original game was: 0.616 * rainbowLength + 31.5.
I don't think that we need to highlight what was in the original game as it rises questions where this data came from.

2022-12-02 02:04 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        const fheroes2::Sprite luckSprite = DrawRainbow( rainbowArc, rainbowThickness, isVerticalRainbow, isRainbowFromRight );
This variable should be `fheroes2::Image` type.

2022-12-02 16:55 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +        rainbowLine = fheroes2::Crop( luckSprite, luckSprite.width() / 2, 0, 1, rainbowThickness );
I have changed `fheroes2::Crop` to `fheroes2::Copy` as 'Crop' returns type `Sprite`.

2022-12-02 17:01 UTC, Districh-ru commented
Hi @ihhub, thanks for the comments. I have updated the code. Could you please check it out when you have time.

2022-12-02 22:24 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        rainbowLine = fheroes2::Crop( luckSprite, luckSprite.width() / 2, 0, 1, rainbowThickness );
It is absolutely valid. Crop is used in cases when we are unknown about the size we want to copy.

2022-12-02 22:38 UTC, ihhub requested changes

2022-12-02 22:38 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        const int32_t pow1 = 2;
My only concern is about this place: we declare a lot of variables without default values. By human nature we might forget to set a value to one of them. Can we please add initialisation values to them like 0?

[Optional] you can use C++11 initialization style to avoid any implicit conversions. For example:
const int32_t pow1{ 2 };
This approach makes sure that use the correct types.

2022-12-03 05:50 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +        const int32_t pow1 = 2;
Made appropriate changes to the code.
@ihhub, thank you for tips and explanations!

2022-12-03 05:52 UTC, ihhub approved these changes

2022-12-03 06:34 UTC, merged

2022-12-03 06:35 UTC, ihhub commented
@Districh-ru , thank you so much for this improvement!

2023-02-21 13:50 UTC, LeHerosInconnu commented
Hello everyone,

I made some tests on this subject, for now it seems fine to me. :)