Hexagon shading improvement (Battlefield)
ihhub/fheroes2 pull request #6265
Opened 2022-11-29 18:30 UTC by Districh-ru

In addition to #6216: made generation of two hexagon shadows.
- shadow that fits the grid
![изображение](https://user-images.githubusercontent.com/113276641/204610466-e0c601a7-1b4a-422a-8236-565815f65f3a.png)

-  shadow with space between hexagons for use without grid
![изображение](https://user-images.githubusercontent.com/113276641/204610599-6fcc40f8-cedc-44a2-819f-2d36fac9e88c.png)

(Cursor shadow size is set to fit the grid.)

2022-12-01 13:16 UTC, Branikolog approved these changes

2022-12-02 02:10 UTC, ihhub requested changes
Hi @Districh-ru , I added few comments here. Would you mind to take a look at them?

2022-12-02 02:10 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +fheroes2::Image DrawHexagonShadow( const uint8_t alphaValue, const uint8_t horizSpace )
`horizSpace` variable should be `int32_t` to avoid implicit type conversions.

2022-12-02 15:05 UTC, Districh-ru commented
Hi @ihhub, I've updated the code.
Thanks for the optimization suggestions!

2022-12-03 00:35 UTC, ihhub approved these changes
@Districh-ru , now the code is clean and nice to read. Well done!

2022-12-03 00:37 UTC, merged

2022-12-03 00:37 UTC, ihhub commented
@Districh-ru , thank you so much for this improvement!