Add double-lined class name translations
ihhub/fheroes2 pull request #6287
Opened 2022-12-03 02:53 UTC by zenseii

This adds translations to the double-lined class names in case there are more than 4 players in a scenario.

Relates to https://github.com/ihhub/fheroes2/issues/5248 and https://github.com/ihhub/fheroes2/issues/5244

Follow up to #5983

2022-12-03 06:12 UTC, Districh-ru commented on files/lang/ru.po
>  msgstr "Некромант"
Hi @zenseii ,
Necromancer is the longest class name, so it should be split into two lines.
![изображение](https://user-images.githubusercontent.com/113276641/205427403-a805ea0e-3499-426c-9e3e-0bb0bd7a612d.png)

```suggestion
msgstr "Некро-\nмант"
```

Wizard also has a long class name, but we have a 2px space between its class names, so we can leave it unsplitted.

2022-12-03 06:14 UTC, Districh-ru commented on files/lang/ru.po
> +msgstr "По сценарию"
![изображение](https://user-images.githubusercontent.com/113276641/205427489-334b1ab9-9c53-4afb-a5c1-237d7214c710.png)

```suggestion
msgstr "По\nсценарию"
```

2022-12-03 15:33 UTC, srzkptrsk commented
> when there are 6 players.
> Thank you in advance for your help!

Something wrong with string for translate
`#, fuzzy
msgid ""
"doubleLined|Necro-\n"
"mancer"
msgstr "Некра-\n"
"мант"`

<img width="1072" alt="Screenshot 2022-12-03 at 16 30 23" src="https://user-images.githubusercontent.com/24893257/205448847-b52a9cf2-4f2f-4821-af77-f0d3ad42b677.png">

2022-12-03 20:42 UTC, Arthusppp requested changes

2022-12-03 20:42 UTC, Arthusppp commented on files/lang/pl.po
>  msgstr "Czarodziejka"
msgid "doubleLined|Sorceress"
msgstr "Czaro-\ndziejka"

2022-12-03 20:42 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Czarnoksiężnik"
msgid "doubleLined|Warlock"
msgstr "Czarno-\nksiężnik"

2022-12-03 20:42 UTC, Arthusppp commented on files/lang/pl.po
>  msgstr "Nekromanta"
msgid ""
"doubleLined|Necro-\n"
"mancer"
msgstr "Nekro-\nmanta"

2022-12-03 20:42 UTC, Arthusppp commented on files/lang/pl.po
>  msgstr "Barbarzyńca"
msgid "doubleLined|Barbarian"
msgstr "Barba-\nrzyńca"

2022-12-05 13:22 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Магьосник"
Магьос- \n
ник

2022-12-05 13:22 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Вълшебник"
Вълшеб- \n
ник

2022-12-05 13:23 UTC, Effektus commented on files/lang/bg.po
> +msgstr "Комбинация"
Комбина- \n
ция

2022-12-05 13:25 UTC, Effektus requested changes
Done

2022-12-07 13:34 UTC, Branikolog commented
Hi, @zenseii 

> Hi, @srzkptrsk.
> 
> I only need your input on how to split "Чараўніца", or if you think there is no need for that to be split then please correct me.

I think we can leave them as it is now:
![image](https://user-images.githubusercontent.com/55348946/206192620-1af7f00d-fd8a-4bfe-9eea-c103680186a5.png)
Personally, I would like make the word at least 1px thinner, so there would be at least 1 pixel between class names. I believe this could be achieved by future corrections of Cyrillic font.

2022-12-07 13:36 UTC, srzkptrsk commented
> Hi, @zenseii
> 
> > Hi, @srzkptrsk.
> > I only need your input on how to split "Чараўніца", or if you think there is no need for that to be split then please correct me.
> 
> I think we can leave them as it is now: ![image](https://user-images.githubusercontent.com/55348946/206192620-1af7f00d-fd8a-4bfe-9eea-c103680186a5.png) Personally, I would like make the word at least 1px thinner, so there would be at least 1 pixel between class names. I believe this could be achieved by future corrections of Cyrillic font.

Чараў-/nніца will be better.

2022-12-07 13:57 UTC, Branikolog commented
> > Hi, @zenseii
> > > Hi, @srzkptrsk.
> > > I only need your input on how to split "Чараўніца", or if you think there is no need for that to be split then please correct me.
> > 
> > 
> > I think we can leave them as it is now: ![image](https://user-images.githubusercontent.com/55348946/206192620-1af7f00d-fd8a-4bfe-9eea-c103680186a5.png) Personally, I would like make the word at least 1px thinner, so there would be at least 1 pixel between class names. I believe this could be achieved by future corrections of Cyrillic font.
> 
> Чараў-/nніца will be better.

If we make capital letters 1 px thinner, class names would look acceptable:
![Thin letters](https://user-images.githubusercontent.com/55348946/206197570-7c834131-f4ab-4018-b086-e2b99cf63747.png)
But anyway, we can return to it later and for now split word into 2 lines, as @srzkptrsk proposed.

2022-12-08 08:22 UTC, ihhub approved these changes

2022-12-08 08:25 UTC, ihhub commented
Hi @zenseii , could you please resolve merge conflicts? It's hard for me to do right now as I'm using a phone. Alternatively, I'll do it few hours later.

2022-12-08 09:12 UTC, ihhub commented
@zenseii , they appeared after the latest translation PR merge.

2022-12-08 09:39 UTC, merged