Fix multiline word splitting for short phrases with a long first word
ihhub/fheroes2 pull request #6293
Opened 2022-12-03 17:37 UTC by Districh-ru

close #6288
relates to #6165 

before: ![translation 1](https://user-images.githubusercontent.com/113276641/205437205-78ae717f-bd1c-4983-9fe1-0873781e5e75.png)   after: ![translation 2](https://user-images.githubusercontent.com/113276641/205454069-52e98e00-c422-4416-9181-0f10e3dd6a50.png)

2022-12-04 03:42 UTC, ihhub commented
Hi @Districh-ru , what's the original width of the area where we render text and what's the width of the first word?

2022-12-04 04:39 UTC, Districh-ru commented
Hi @ihhub, the original width of the area is set to 87px and the width of the first word is 60px.
In #6289, I tried to solve a similar problem by changing the original max width, but with no success.
The current logic wants to avoid drawing phrases with very long one line and very short other (the last line). This is good. The algorithm starts at (1+87)/2px and but if the first word is too long, thr algorithm cannot reach the end of this word: the word is automatically split. the phrase fits into the resulting number of lines, and the algorithm considers that everything is in order.
In this PR, I change the initial "corrected width" value from 1 to the maximum word width. So the corrected width will be no less than the width of the longest word. If the first word is longer than the given maximum 87px, the algorithm uses this value (87px) for the the "corrected width".

2022-12-04 06:36 UTC, Districh-ru commented
> Hi @Districh-ru , please take a look at getMultiRowInfo() function which calculates row information. See if this function behaves properly as it must handle words separated by a space.

@ihhub, this function works properly. :)
To draw text, the function is first called with the `maxWidth` parameter (for the current example it is 87) and as a result we get the number of lines needed to draw the text (`offsets.size()`). If it is greater than 1 - we have a multiline text and another algorithm is launched here: it recursively tries to set a new `currentWidth[ i ] = ( maxWidth+ currentWidth[ i - 1 ] ) / 2` (where currentWidth[0]=startWidth=1) and checks if the number of resulting lines is no more than needed.
While doing this `getMultiRowInfo()` function is called with the `currentWidth` parameter, which may be less than required for the word to fit. And the function should put the text into the given `currentWidth` and automatically breaks the long word into several lines (it must do this for these conditions).
I don't think that we have to change the `getMultiRowInfo()` function.

Maybe we have to change the width correction algorithm (this PR only changes its `startWidth` value) ... or maybe get rid of it, since it uses the computing resources? :)

For comparison, text with this algorithm we get:
![изображение](https://user-images.githubusercontent.com/113276641/205477392-b93acdce-7ee7-4f33-a5fc-c389da6d56c0.png)   ![изображение](https://user-images.githubusercontent.com/113276641/205477780-d2f40ec2-a9b7-45ce-a71a-4a6eb282d441.png)

And without:
![изображение](https://user-images.githubusercontent.com/113276641/205477399-418bfd5b-e61c-4e19-8d3f-98fe9e345cb2.png)  ![изображение](https://user-images.githubusercontent.com/113276641/205477759-7bc2ff58-5774-4a82-b4f7-62f9d8c460de.png)

The original game:
![изображение](https://user-images.githubusercontent.com/113276641/205477465-491144a0-d396-40f3-96ee-73b0bca9d2ad.png)

2022-12-04 07:19 UTC, ihhub commented
Hi @Districh-ru , the current logic for multi-line text (which is applicable for `draw()` method of **Text** and **MultiFontText** classes is indeed imperfect. It uses a binary search algorithm to detect the minimum number of characters which can evenly fit on all lines. However, this algorithm does not account words which are longer that this limit. How we should do:
- scan the whole text and find the longest word in pixels (don't forget about MultiiFontText class)
- set the found value into `startWidth`
- run binary search algorithm code

So your idea is correct but it should be flexible for every case. Right now it is based on some hardcoded values which is incorrect. Also add implementation for **MultiFontText**.

2022-12-04 07:25 UTC, ihhub requested changes

2022-12-04 07:25 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +        if ( size < 51 ) {
Please remove this hardcoded value.

2022-12-04 07:25 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +    int32_t getMaxWordWidth( const uint8_t * data, const int32_t size, const fheroes2::FontType & fontType )
`size` should be **int32_t**.

2022-12-04 07:25 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +                        maxWidth = width;
Please add parenthesis for this block. Also swapping values will keep the code more "consistent":
```cpp
if ( maxWidth < width ) {
    maxWidth = width;
}

width = 0;
```

2022-12-04 07:25 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +                maxWidth = width;
Just a small correction:
```cpp
if ( maxWidth < width ) {
    maxWidth = width;
}
```
It would be easier to read :)

2022-12-04 07:25 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +            int32_t startWidth = getMaxWordWidth( reinterpret_cast<const uint8_t *>( _text.data() ), static_cast<int32_t>( _text.size() ), _fontType );
Please add implementation for **MultiFontText** class as well. There you will need to get max of results.

2022-12-04 07:39 UTC, Districh-ru commented on src/fheroes2/gui/ui_text.cpp
> +        if ( size < 51 ) {
Ok. 👍 
In the beginning there was no condition with hardcoded value. I did this to reduce the processor usage in thoughts that for the long phrases the first iteration or `currentWidth` will be grater than the word.

2022-12-04 07:56 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +        if ( size < 51 ) {
This implementation will be faster than the current one due to reduce number of iteration for binary search.

2022-12-04 08:01 UTC, Districh-ru commented on src/fheroes2/gui/ui_text.cpp
> +            int32_t startWidth = getMaxWordWidth( reinterpret_cast<const uint8_t *>( _text.data() ), static_cast<int32_t>( _text.size() ), _fontType );
Here we are dealing with different types of fonts, so I changed this part to be the same as calling `getMulti RowInfo`.

2022-12-04 08:03 UTC, Districh-ru commented on src/fheroes2/gui/ui_text.cpp
> +        if ( size < 51 ) {
Oh yes, you're right!
@ihhub, thanks a lot for helping with this PR!

2022-12-04 08:14 UTC, ihhub approved these changes

2022-12-04 08:14 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +                // If it is the end of line ("\n") or a space (""), then the word has ended.
A tiny comment correction: `space ("")` should be `space (" ")` with a space :)

2022-12-04 08:18 UTC, Districh-ru commented on src/fheroes2/gui/ui_text.cpp
> +                // If it is the end of line ("\n") or a space (""), then the word has ended.
You have Expert Eagle Eye skill 👍

2022-12-05 04:43 UTC, merged

2022-12-05 04:43 UTC, ihhub commented
@Districh-ru , thank a lot for this important fix!