Optimize defensive strategy for AI castles
ihhub/fheroes2 pull request #6297
Opened 2022-12-04 09:42 UTC by ihhub

2022-12-05 09:57 UTC, oleg-derevenetz requested changes

2022-12-05 09:57 UTC, oleg-derevenetz commented on src/fheroes2/army/army.cpp
> +    clear();
Hi @ihhub this is not quite right - since raw pointers are stored here, and not smart pointers, we should call `delete` for them first, and only after that we can call `clear()`, otherwise we will get a memory leak.

2022-12-05 11:18 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +    clear();
Oh, yes. I forgot about this. We should call `Clear()` which does the correct logic.

2022-12-05 11:19 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +    clear();
Actually, we need to add extra logic to deallocate pointers :(

2022-12-05 11:24 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +    clear();
OMG-OMG-OMG:
```cpp
Troops troops;
troops.Assign( otherTroops );
```
and it does nothing. I will skip fixing this class for now...

2022-12-05 11:31 UTC, oleg-derevenetz commented on src/fheroes2/army/army.cpp
> +    clear();
`Assign()` is good for `Army`, which pre-allocates the slots :) And `Troops` doesn't pre-allocate them because while it stores just `Troop` objects, `Army` stores `ArmyTroop` objects. The legacy logic :)

2022-12-05 11:34 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +    clear();
I just deleted the method as used another method to avoid any weird logic.

2022-12-05 11:38 UTC, oleg-derevenetz commented on src/fheroes2/army/army.cpp
> +    clear();
@ihhub In fact, the current logic is also weird, because if we have an `Army` object upcasted to `Troops` and then we want to make a copy of it, then we will get the copies of `Troop` instead of `ArmyTroop` :) Maybe it even right, but maybe not - it depends.

2022-12-05 11:39 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +    clear();
We need to rewrite it but for 1.0 let's keep as it is.

2022-12-05 11:42 UTC, oleg-derevenetz commented on src/fheroes2/army/army.h
> +    Troops & operator=( const Troops & rhs ) = delete;
We don't need to name a parameter here then.

2022-12-05 11:44 UTC, oleg-derevenetz commented on src/fheroes2/army/army.h
>      Troops( const Troops & troops );
Maybe we don't need this copy constructor at all?

2022-12-05 11:48 UTC, oleg-derevenetz commented on src/fheroes2/army/army.h
>      Troops( const Troops & troops );
Eh, no, we still need it.

2022-12-05 12:13 UTC, ihhub commented on src/fheroes2/army/army.h
> +    Troops & operator=( const Troops & rhs ) = delete;
Fixed.

2022-12-05 20:42 UTC, oleg-derevenetz reviewed
Hi @ihhub I just left a few questions, could you please take a look when you have time?

2022-12-05 20:42 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_castle.cpp
> +        // Call internally checks if it's valid (space/resources) to buy one.
Could you please elaborate, which call checks what? The current wording gives the impression that `GetKingdom()` does this.

2022-12-05 20:42 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            // TODO: once it is done, check if the tile does not have a hole. If it does not mark it as a valid object.
Do you want to give the AI an ability to dig for the Ultimate Artifact in future? I think it will be a little too much, because there will be no way for a human player to capture this artifact in battle. Most likely it will be lost.

2022-12-05 22:32 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            // TODO: once it is done, check if the tile does not have a hole. If it does not mark it as a valid object.
The original Heroes2 AI is dumb, so it's OK for it. fheroes2 AI is too smart IMHO to allow it to dig.

2022-12-05 22:52 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            // TODO: once it is done, check if the tile does not have a hole. If it does not mark it as a valid object.
I think we should still implement it in the future. We can feature-gate it behind game difficulty so AI would only dig on higher ones.

2022-12-05 23:15 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            // TODO: once it is done, check if the tile does not have a hole. If it does not mark it as a valid object.
But people are screaming to give them challenge :)

I am okay to put it for higher difficulties only.

2022-12-07 00:32 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_castle.cpp
> +        // Call internally checks if it's valid (space/resources) to buy one.
Sure. It's an old comment but I'll change it.

2022-12-10 09:41 UTC, oleg-derevenetz commented
Hi @ihhub could you please resolve the merge conflicts here?

2022-12-11 13:24 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_castle.cpp
> +            if ( castle.GetActualArmy().getTotalCount() > 0 ) {
Nope. AI doesn't always leave troops as there could be no hero and no monsters to be hired.

2022-12-11 13:44 UTC, ihhub commented
> Hi @ihhub could you please resolve the merge conflicts here?

It is done.

2022-12-11 13:57 UTC, oleg-derevenetz approved these changes

2022-12-12 00:17 UTC, merged