Fix the smoke animation when demolishing a castle building (Battlefield).
ihhub/fheroes2 pull request #6298
Opened 2022-12-04 10:35 UTC by Districh-ru

close #6222 
close #3242

https://user-images.githubusercontent.com/113276641/205485764-20edabf9-387c-4e29-a52d-fd9394fa8dbd.mp4

2022-12-05 13:13 UTC, ihhub requested changes
Hi @Districh-ru , I left multiple comments in this pull request. Could you please take a look at them when you have time?

2022-12-05 15:08 UTC, Districh-ru commented on src/fheroes2/battle/battle_action.cpp
> +                        _interface->RedrawAfterDemolitionSmoke( target );
Hi @ihhub, I agree.
However, I suggest renaming `RedrawActionCatapult` to `RedrawActionCatapultPart1` and the introduced method to `RedrawActionCatapultPart2` to match the names of other methods.

2022-12-05 15:37 UTC, Districh-ru commented on src/fheroes2/battle/battle_arena.cpp
> -
This change was made to match the original game: after the boulder hits, the bridge lift breaks and the bridge falls and collapses - that's why we have a second smoke cloud.

2022-12-05 15:50 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +    while ( le.HandleEvents() && frame < maxAnimationFrame ) {
If we miss this method is not called:
```cpp
                if ( hit ) {
                    SetCastleTargetValue( target, GetCastleTargetValue( target ) - damage );
                    if ( _interface ) {
                        // Continue animating the smoke cloud after changing the "health" of the building.
                        _interface->RedrawActionCatapultPart2( target );
                    }
                }
```

2022-12-05 16:07 UTC, Districh-ru commented on src/fheroes2/battle/battle_arena.cpp
> -
Original game:

https://user-images.githubusercontent.com/113276641/205684780-178f2e34-6081-4ba2-aaba-8b622990bb6a.mp4

2022-12-05 16:13 UTC, Districh-ru commented on src/fheroes2/battle/battle_arena.cpp
> -
And if the bridge is alerady open, we also have a second smoke cloud.
Maybe the bridge mechanism and the wall fragments fall on the bridge and break it. (while the creature on the bridge somehow manages to dodge)
Original game:

https://user-images.githubusercontent.com/113276641/205686212-ad32fe3c-b1a5-48c8-9254-1b79e6fc97a1.mp4

2022-12-05 23:03 UTC, ihhub commented on src/fheroes2/battle/battle_action.cpp
> +                        _interface->RedrawAfterDemolitionSmoke( target );
Looks like to me. Not the greatest but it's better than now.

2022-12-05 23:04 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    while ( le.HandleEvents() && frame < maxAnimationFrame ) {
Ah, got it.

2022-12-05 23:22 UTC, ihhub approved these changes
Hi @Districh-ru , I essentially approve this pull request. I left one optional code style comment but it's up to you to change it.

2022-12-05 23:22 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    LocalEvent & le = LocalEvent::Get();
A usual practice is to declare variables just before their usage (ignore the most of the code in this file as it was mostly written before us). I suggest to put this variable at line 4246 just before the loop.

2022-12-06 05:46 UTC, ihhub commented
Hi @Districh-ru , based on your great work in animations during battle I recommend to try your skills in fixing these issues: #5701, #2314, #1229 and #1041. 🙂

2022-12-06 05:46 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    LocalEvent & le = LocalEvent::Get();
You're welcome!

2022-12-06 09:15 UTC, Branikolog approved these changes
Well done!

2022-12-06 09:25 UTC, merged

2022-12-06 09:25 UTC, ihhub commented
@Districh-ru , a bunch of thanks for this improvement!

2022-12-06 14:26 UTC, Districh-ru commented
> Hi @Districh-ru , based on your great work in animations during battle I recommend to try your skills in fixing these issues: #5701, #2314, #1229 and #1041. 🙂

Hi @ihhub, thanks ;)
I was already thinking about #5701