Do not copy images while rendering Adventure Map
ihhub/fheroes2 pull request #6300
Opened 2022-12-04 12:50 UTC by ihhub

2022-12-04 15:16 UTC, oleg-derevenetz commented on src/fheroes2/gui/interface_gamearea.cpp
> +                    tileUnfit.bottomBackgroundImages[imagePos + offset].emplace_front( std::move( objectInfo ) );
Hi @ihhub we can add the [compile-type check](https://en.cppreference.com/w/cpp/types/is_trivially_copyable) whether the `objectInfo` is trivially copyable and remove these redundant `std::move()` calls.

2023-02-23 13:58 UTC, Districh-ru commented on src/engine/image.cpp
> +            const int32_t offsetInY = inY * widthIn + width - 1 + inX;
It is better to revert this logic as these function is widely used in the code and we will need to correct many places in the code then.
Also the original logic here was made to make the same calculation for flipped and non-flipped sprites render regions.
```suggestion
            const int32_t offsetInY = inY * widthIn + widthIn - 1 - inX;
```

2023-02-23 13:59 UTC, Districh-ru commented on src/engine/image.cpp
> +            const int32_t offsetInY = inY * widthIn + width - 1 + inX;
The same as for 793 line:
```suggestion
            const int32_t offsetInY = inY * widthIn + widthIn - 1 - inX;
```

2023-02-23 14:06 UTC, Districh-ru requested changes
Hi @ihhub! I left a couple suggestions to fix rendering of flipped images. Could you take a look when you have time.

2023-02-23 14:09 UTC, Districh-ru commented on src/engine/image.cpp
>                  }
As now we are using `Blit` later and here are doing only coordinates calculation we do not need to use `const bool flip` and make the same calculations for flipped and non-flipped sprites:
```cpp
        for ( int32_t y = 0; y < stepPerDirection.y; ++y ) {
            for ( int32_t x = 0; x < stepPerDirection.x; ++x ) {
                const Rect roi( x * squareSize, y * squareSize, squareSize, squareSize );
                const Rect intersection = relativeROI ^ roi;
                assert( intersection.width > 0 && intersection.height > 0 );

                outputSquareId.emplace_back( offset + Point( x, y ) );

                outputImageInfo.emplace_back( fheroes2::Point( intersection.x - roi.x, intersection.y - roi.y ),
                                              fheroes2::Rect( intersection.x - spriteRelativeOffset.x, intersection.y - spriteRelativeOffset.y, intersection.width,
                                                              intersection.height ) );
            }
        }
```

2023-02-23 15:59 UTC, oleg-derevenetz commented
Hi @ihhub please address IWYU suggestions :)

2023-02-23 16:13 UTC, ihhub commented
> Hi @ihhub please address IWYU suggestions :)

As usual :)

2023-02-23 18:30 UTC, oleg-derevenetz reviewed
Hi @ihhub I just left one question, could you please take a look when possible?

2023-02-24 13:28 UTC, oleg-derevenetz commented on src/fheroes2/gui/interface_gamearea.cpp
> +    static_assert( std::is_trivially_copyable<fheroes2::ObjectRenderingInfo>::value, "This class is not trivially copyable anymore. Add std::move where required." );
Ah, I got the idea.

2023-02-24 13:28 UTC, oleg-derevenetz approved these changes

2023-02-24 13:58 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +    static_assert( std::is_trivially_copyable<fheroes2::ObjectRenderingInfo>::value, "This class is not trivially copyable anymore. Add std::move where required." );
It was initially proposed by you :)

2023-02-24 14:25 UTC, Districh-ru approved these changes
I played fully one M map (also using boats) and did not notice rendering bugs.

2023-02-24 14:41 UTC, merged

2023-02-24 14:44 UTC, Branikolog commented
I also haven't found any new issues.