Make File Dialog and Adventure Dialog buttons translatable
ihhub/fheroes2 pull request #6331
Opened 2022-12-08 17:15 UTC by zenseii

Both Evil and Good interfaces.

The cancel button will be handled later.

Relates to #6105 

![image](https://user-images.githubusercontent.com/12501091/206586592-4d08e99b-dda1-4044-b2e2-17429867a2f3.png)
![image](https://user-images.githubusercontent.com/12501091/206586625-05d00d06-6962-4212-8427-97e6d68c824b.png)

2022-12-09 01:01 UTC, ihhub requested changes
Hi @zenseii, I left several comments here. Would you mind to take a look at them?

2022-12-09 22:47 UTC, ihhub approved these changes

2022-12-10 09:11 UTC, Branikolog commented
Hi, @zenseii !
It would be nice, if we still support original buttons from the russian version of the game.
![image](https://user-images.githubusercontent.com/55348946/206842660-42f94da8-9502-4fe3-bfaf-762dc210b94f.png)

2022-12-10 14:19 UTC, Branikolog commented
Hi, @zenseii !
Everything is ok now! Thanks for quick fix!

2022-12-10 14:23 UTC, Districh-ru commented
Hi, @zenseii!
Yes, everything is OK! 👍 

<details>

![изображение](https://user-images.githubusercontent.com/113276641/206860032-2cf7c6dc-fb2c-4f52-bd23-6d5a79beb307.png)

</details>

2022-12-10 14:36 UTC, Districh-ru commented
@zenseii,
I don't know if there are other translated Heroes 2 resources besides Russian or Polish. If there are, maybe we should support its buttons.
And should we replace button text for English language when using English resources?
So maybe do this check:
```cpp
    bool isSameCurrentLanguageAndResourceFile()
    {
        return fheroes2::getCurrentLanguage() == fheroes2::getResourceLanguage();
    }

```
What do you think? :)

2022-12-11 12:40 UTC, Branikolog approved these changes

2022-12-11 13:13 UTC, ihhub requested changes
Hi @zenseii , I left one more comment. Can you please take a look?

2022-12-11 13:13 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +
We should name this function more generically like `useOriginalResources`. We should also cache function's return values as they aren't inlined:
```cpp
bool useOriginalResources()
{
    const fheroes2::SupportedLanguage currentLanguage = fheroes2::getCurrentLanguage();
    const fheroes2::SupportedLanguage resourceLanguage = fheroes2::getResourceLanguage();

    return ( currentLanguage == fheroes2::SupportedLanguage::Polish && resourceLanguage == fheroes2::SupportedLanguage::Polish )
           || ( currentLanguage == fheroes2::SupportedLanguage::Russian && resourceLanguage == fheroes2::SupportedLanguage::Russian );
}
```

2022-12-11 23:42 UTC, ihhub approved these changes

2022-12-11 23:43 UTC, merged

2022-12-11 23:43 UTC, ihhub commented
@zenseii , thank a lot for making this improvement!