Make the regular small buttons translatable
ihhub/fheroes2 pull request #6337
Opened 2022-12-09 14:20 UTC by zenseii

This generates and adds the small buttons to the engine.

Relates to #6331 #6194 https://github.com/ihhub/fheroes2/issues/1794
Part of solution to #6105 and https://github.com/ihhub/fheroes2/issues/3350

close #6155 

Buttons done:
CANCEL
OKAY
ACCEPT
DECLINE
S
M
L
X-L
ALL
NO
YES
TRADE
EXIT
DISMISS
UPGRADE
RESTART (Battle summary)
MAX (Recruit and fast split)

**Buttons for separate PRs:**

Campaign buttons (needs 3 variants):
VIEW INTRO
OKAY
CANCEL
RESTART

Irregular square buttons:
SKIP
AUTO
SELECT
MAX (WELL)
EXIT (Well, View Puzzle, View World)

2022-12-16 23:47 UTC, ihhub requested changes
Hi @zenseii , I left several comments in this pull request. Can you please take a look at them?

2022-12-16 23:47 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                fheroes2::Point releasedOffset;
I'm thinking that we might need to reduce code duplication as we so many identical cases. How about we create a function:
```cpp
void createNormalButton( fheroes2::Sprite & released, fheroes2::Sprite & pressed, int32_t textWidth, const char * text, const bool isEvilInterface )
{
    fheroes2::Point releasedOffset;
    fheroes2::Point pressedOffset;
    getCustomNormalButton( released, pressed, isEvilInterface, textWidth, releasedOffset, pressedOffset );

    const fheroes2::FontColor buttonFontColor = isEvilInterface ? fheroes2::FontColor::GRAY : fheroes2::FontColor::WHITE;

    renderTextOnButton( released, pressed, text, releasedOffset, pressedOffset, { textWidth, 16 }, buttonFontColor );
}
```

What do you think?

2022-12-16 23:47 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                if ( useOriginalResources() && ( id == ICN::BUTTON_SMALLER_OKAY_EVIL || id == ICN::BUTTON_SMALLER_OKAY_GOOD ) ) {
I suggest to cache `useOriginalResources()` into a separate variable call as it is not instant to avoid double function call or we can do this:
```cpp
if ( useOriginalResources() ) {
    if ( id == ICN::BUTTON_SMALL_OKAY_EVIL || id == ICN::BUTTON_SMALL_OKAY_GOOD ) {
        _icnVsSprite[id][0] = GetICN( isEvilInterface ? ICN::SPANBTNE : ICN::SPANBTN, 0 );
        _icnVsSprite[id][1] = GetICN( isEvilInterface ? ICN::SPANBTNE : ICN::SPANBTN, 1 );
    }
    else if ( id == ICN::BUTTON_SMALLER_OKAY_EVIL || id == ICN::BUTTON_SMALLER_OKAY_GOOD ) {
        _icnVsSprite[id][0] = GetICN( isEvilInterface ? ICN::WINCMBBE : ICN::WINCMBTB, 0 );
        _icnVsSprite[id][1] = GetICN( isEvilInterface ? ICN::WINCMBBE : ICN::WINCMBTB, 1 );
    }
    else {
        assert( 0 );
    }
    break;
}

2022-12-17 14:05 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                int32_t textWidth = 86;
Can we please add empty lines in this block between sections of the code? :)

2022-12-17 14:45 UTC, ihhub approved these changes

2022-12-17 21:32 UTC, Branikolog approved these changes
Besides of...

>There is an issue with the background shadow on the right side when pressed...

... which is relevant for almost every button on such stone-like background, everything seems to look nice. :+1:

2022-12-18 02:19 UTC, merged

2022-12-18 02:19 UTC, ihhub commented
@zenseii , thank you so much for this improvement!