Death Wave spell animation fix (Battlefield)
ihhub/fheroes2 pull request #6344
Opened 2022-12-10 20:15 UTC by Districh-ru

close #5710 and probably #1041

Redone the animation sequence for Death Wave, Death Ripple, Holy Word and Holy Shout shout.
Now the flame animation (after the spell animation) is made only after applying damage from the spell. And during this flame animation the death animation and the wince animation is applied to the corresponding creatures.
To do this I had to make a copy of part of the code from `RedrawActionWincesKills` method. :(
To reduce the size of this duplication a new (small) method was made.

fheroes2 Death Wave animation:

https://user-images.githubusercontent.com/113276641/206873319-46c319f1-9d8c-4cfc-9c0a-806823f83273.mp4

fheroes2 Holy Shout animation:

https://user-images.githubusercontent.com/113276641/206873326-8d8bfcba-0955-449d-8e9d-c172a139c202.mp4

2022-12-10 21:01 UTC, oleg-derevenetz commented
> close https://github.com/ihhub/fheroes2/issues/5710

#5701 :)

2022-12-10 21:04 UTC, Districh-ru commented
Hello, everyone.
After opening this PR I noticed that after the creatures death the flame animation shifts down. It is because the spell position is calculated for every frame based on creatures sprite. I'll try to fix this tomorrow.

2022-12-10 21:07 UTC, Districh-ru commented
> > close #5710
> 
> #5701 :)

Hi, @oleg-derevenetz.  thanks for finding the typo. :)

2022-12-11 04:57 UTC, Districh-ru commented
> I think, Death Wave (level 3) should have larger and faster wave effect than smaller Death Ripple(level 2) spell.

Hi, @Alucard648.
In original game both Death Wave and Death Ripple have the same speed (5px/frame), Death Ripple height is about 7px and Death Wave height is about 14px.
I used this parameters in the current implementation.

Here is a video from original game for comparison:


https://user-images.githubusercontent.com/113276641/206887219-44e3a4c3-8a93-4f9e-b54c-9c91eb0d64a4.mp4

2022-12-11 06:42 UTC, Districh-ru commented
Hello, @Branikolog and @LeHerosInconnu!
Could you please review this PR when you have time.

2022-12-11 09:53 UTC, oleg-derevenetz commented on src/fheroes2/gui/ui_tool.cpp
> +            const uint8_t * outImageYEnd = outImageX + static_cast<int64_t>( height + *pntX ) * width;
It's highly unlikely that the result of this multiplication will overflow `int`. However if you want to silence the clang-tidy, it would probably be better to convert to `std::ptrdiff_t` instead (here and on the following line), because currently on 32-bit machines there is one extra conversion performed - first to `int64_t` and then, when adding the multiplication result to pointer, it will be converted once again to `std::ptrdiff_t` which is 32-bit on these machines.

2022-12-11 10:14 UTC, Districh-ru commented on src/fheroes2/gui/ui_tool.cpp
> +            const uint8_t * outImageYEnd = outImageX + static_cast<int64_t>( height + *pntX ) * width;
Hi @oleg-derevenetz, thanks for the explanations. I'll replace <int64_t> with <ptrdiff_t> to have less type conversions on 32 systems.
But, please, help me to make these lines more clean (without possible overflow).
If I convert the left part of the multiplication to <ptrdiff_t> I thought that the right part will be automatically converted. Or I should do the same conversion for the right part (`static_cast<ptrdiff_t>( width )`)?

2022-12-11 11:25 UTC, oleg-derevenetz commented on src/fheroes2/gui/ui_tool.cpp
> +            const uint8_t * outImageYEnd = outImageX + static_cast<int64_t>( height + *pntX ) * width;
> If I convert the left part of the multiplication to <ptrdiff_t> I thought that the right part will be automatically converted.

Yes, both operands of arithmetic operation are promoted/converted to the same type first, so there is no need to manually convert each operand. See the "Conversions" section here:

https://en.cppreference.com/w/cpp/language/operator_arithmetic

and the link regarding integral promotion in that section.

2022-12-11 12:49 UTC, Branikolog commented
Hello, @Districh-ru !
I've already made few tests.
Here's an issue I've found:
Red fog is drawn over troops standing in front of the target.
![Wave](https://user-images.githubusercontent.com/55348946/206904320-e33b589a-5f2a-4e97-9ca4-8ddc883a400b.png)

In the OG:
![image](https://user-images.githubusercontent.com/55348946/206904176-236d6458-004f-416f-9a97-ac1f78679b54.png)

2022-12-11 13:23 UTC, Districh-ru commented
> Hello, @Districh-ru ! I've already made few tests. Here's an issue I've found: Red fog is drawn over troops standing in front of the target. 

It is because the `RedrawArmies();` method , which draws the whole army on the battlefield is called first and then the red fog for is drawn.
To fix this issue we need to redesign `RedrawArmies();` method to add ability to draw each unit one by one and spells one by one from the farest to the closest. 
But we have spells with more than one cell blast radius, for example the Cold Ring spell:

https://user-images.githubusercontent.com/113276641/206905837-62154df6-3be4-4e35-a583-330cb0c20526.mp4

It should be drawn under the second peasant, but if the peasant was one cell upper, it should be drawn over him.
I think this issue will happen to every spell animation.

2022-12-11 13:50 UTC, ihhub commented
Hi @Districh-ru , the best strategy to avoid heavy redevelopment is to do in steps. I believe that restructuring of `RedrawArmies()` method will require a lot of code changes. If yes it would be wiser to do it in a separate pull request.

2022-12-11 13:54 UTC, Branikolog commented
@Districh-ru 
I've also noticed differences with splash animations position:
![ezgif com-gif-maker (99)](https://user-images.githubusercontent.com/55348946/206907776-f812f540-bffc-4c55-a38c-c246600e61c0.gif)
![image](https://user-images.githubusercontent.com/55348946/206907788-68c23ab5-cd4a-4e38-8dd1-8af25926d2ce.png)

2022-12-11 15:41 UTC, Districh-ru commented
> @Districh-ru I've also noticed differences with splash animations position

@Branikolog, I tried to fix it, but I think OG has some kind of coordinate table for such sprite positions for each creature. So I set the horizontal position of the sprites close to OG. For the vertical position, I used the unit's cell position because I don't want to rely on the sprite's parameters. Therefore, the vertical position is not as close to OG. But, with such sprites (fog or explosions), it's probably better to snap to grid coordinates, not the parameters of the creature.

2022-12-11 15:50 UTC, Districh-ru commented
> Hi @Districh-ru , the best strategy to avoid heavy redevelopment is to do in steps. I believe that restructuring of `RedrawArmies()` method will require a lot of code changes. If yes it would be wiser to do it in a separate pull request.

Hi @ihhub, I think there will be changes that will affect the displaying creatures on the battlefield in different situations. We also have to decide which spell and under what conditions should be drawn under or over each creature.

2022-12-12 01:15 UTC, ihhub commented
> > Hi @Districh-ru , the best strategy to avoid heavy redevelopment is to do in steps. I believe that restructuring of `RedrawArmies()` method will require a lot of code changes. If yes it would be wiser to do it in a separate pull request.
> 
> Hi @ihhub, I think there will be changes that will affect the displaying creatures on the battlefield in different situations. We also have to decide which spell and under what conditions should be drawn under or over each creature.

I think we should do this in a separate PR.

2022-12-13 10:32 UTC, Branikolog commented
Hi, @Districh-ru !
Now spell effect has consistent position for both sides.
![image](https://user-images.githubusercontent.com/55348946/207264613-f60f0099-8be1-439b-a40b-513d9cd66282.png)
Currently, spell effect appears on the back side of the creature sprite. I find it a bit shifted, since it appears not over the creature, but a little behind it. How do you think, is it intended animation, or can we shift those red demons appear closer to the middle of creature hex (for 1-hex creatures) and to the border of adjoining hexes (for 2-hex creatures)?

2022-12-13 11:15 UTC, Branikolog commented
Also, I've noticed some differences in creatures sprites animations.
While red splash appears, all creatures perform "taking damage" animation. They freeze for a while being leaned back and then return to standing state.
Original Game:
https://user-images.githubusercontent.com/55348946/207298697-6b73cf64-4aa0-45df-ab5d-e942f02cc3c5.mp4
fheroes2:
https://user-images.githubusercontent.com/55348946/207298791-1e38f33b-53f0-4a6f-9354-bfa8d0e6a8d7.mp4
Take a look at halflings and champions in the current implementation.
Halflings freeze in a state which is not the most leaned back, and after freezing they continue leaning back and then returning to standing state.
Champions are on a contrary, freeze in a state after maximum leaning back. It looks like animation stops on the last "taking damage" frame.

2022-12-13 11:55 UTC, Districh-ru commented
Hi, @Branikolog!
I'll shift the red fog sprite as you suggested and try to place it in the middle of two-hex creatures.
Also I'll will do a more thorough analysis of the frame number with maximum wince for each creature.

2022-12-14 08:26 UTC, Branikolog commented
Hi, @Districh-ru 
Now wincing seems to happen in correct timings, but It looks like there's last frame missing. Or it happens too promptly, so I couldn't even notice it.

https://user-images.githubusercontent.com/55348946/207544248-ea7226e5-7410-4f84-99da-f3e68ee8cbbd.mp4

2022-12-14 09:10 UTC, ihhub requested changes
Hi @Districh-ru, I left several comments in this pull request. Could you please take a look at them in your spare time?

2022-12-14 09:10 UTC, ihhub commented on src/fheroes2/gui/ui_tool.cpp
> +        if ( x < 0 || ( x - waveWidth ) >= width )
If `deathWaveCurve` is empty we don't need to do anything but just return from the function.

2022-12-14 09:10 UTC, ihhub commented on src/fheroes2/gui/ui_tool.cpp
> +        const std::vector<int32_t>::const_iterator endX = deathWaveCurve.end() - ( x > width ? x - width : 0 );
Here we don't check the boundaries of our container. We have to check that `( x < waveWidth ? waveWidth - x : 0 )` is smaller than `deathWaveCurve.size()` (or clamp to its size) and the same for `( x > width ? x - width : 0 )`.

2022-12-14 09:10 UTC, ihhub commented on src/fheroes2/gui/ui_tool.cpp
>              }
Would we have out of boundaries read if `*pntX` value is bigger than `height`?

2022-12-14 09:10 UTC, ihhub commented on src/fheroes2/gui/ui_tool.cpp
> +            const uint8_t * inImageY = inImageX - static_cast<ptrdiff_t>( *pntX + 1 ) * width;
I think we should have a loop to check that all values in `deathWaveCurve` are within accepted range of values. At least in debug mode.

2022-12-14 09:27 UTC, Districh-ru commented
> Hi, @Districh-ru Now wincing seems to happen in correct timings, but It looks like there's last frame missing. Or it happens too promptly, so I couldn't even notice it.

Hi, @Branikolog. Yes, there is a small logic problem: I change the type of animation and then I increase the frame number. It will be fixed in next commit.

2022-12-14 10:03 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +    bool isDefenderAnimatimg = wnce;
I left a misprint here. It has to be `isDefenderAnimating`.
I named this variable so because it is true if for all units their animation sequence is not finished.

2022-12-14 10:08 UTC, Districh-ru commented on src/fheroes2/gui/ui_tool.cpp
> +        if ( x < 0 || ( x - waveWidth ) >= width )
If it is so and if it is outside of the battlefield we return the input image unchanged, as the caller function waits for an image.
I'll add the check for the size of deathWaveCurve.

2022-12-14 10:31 UTC, Districh-ru commented on src/fheroes2/gui/ui_tool.cpp
>              }
I'll add a check for each *pntX if it is in the boundaries of the input image at the start of the loop. After this *pntX could not et higher, than the height.

2022-12-14 14:11 UTC, Branikolog approved these changes
Duration of the wave and red fog is still a bit different, from the original game, but it could be polished later. Current fix is a huge improvement!
Great work, @Districh-ru !

2022-12-14 14:22 UTC, Districh-ru commented
Thanks, @Branikolog!
I set the step of Death Wave equal to the original game. The original game has different speed settings and, I think, different frame delays when drawing spell effects. Yes, later we can more carefully set this delays.
And did you check the corrected spell effect for Holy Word and Holy Shout? Does this PR fix the #1041 issue? :)

2022-12-14 14:52 UTC, Branikolog commented
@Districh-ru 

> And did you check the corrected spell effect for Holy Word and Holy Shout? Does this PR fix the #1041 issue? :)

Yes. Spells look 95% identical.
I've only noticed that in the OG there's a slight difference in colour between the Word and the Shout spells. The Shout spell has a little bit darker (or adding red colur) in the middle of animation. I've tried to make several screenshots of the OG and every time middle frame has slight colour difference, but I'm not sure, if I simply missed needed frame and spells are 100% identical.
![ezgif com-gif-maker (100)](https://user-images.githubusercontent.com/55348946/207628461-0123da65-ad77-45b7-a462-4bb05c5d121b.gif)

Anyway, this difference is barely noticeable. (Like ripple and wave for me. :) )

2022-12-16 00:48 UTC, ihhub requested changes
Hi @Districh-ru , I put few more comments in this pull request. Can you please take a look at them when you have time?

2022-12-16 00:48 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( deathColor != Color::UNUSED ) {
This is optional but to reduce the indentation we can do this:
```cpp
if ( deathColor == Color::UNUSED ) {
    return;
}
....
The rest of code
```

2022-12-16 00:48 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        const bool attackersTurn = deathColor == arena.GetArmy2Color();
Please add parenthesis for this line: `const bool attackersTurn = ( deathColor == arena.GetArmy2Color() );` to be easier to read.

2022-12-16 00:48 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +
To be consistent please either add an empty line before `default` or remove empty line here.

2022-12-16 00:48 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +            fheroes2::Blit( fheroes2::CreateDeathWaveEffect( copy, position, waveLength, deathWaveCurve ), _mainSurface );
Here we are wasting resources for copying a full frame for no reason. It is not related to your chances as it is an old code. Can you please add a TODO comment here for the future optimization:
```cpp
// TODO: instead of rendering the whole frame for the wave effect we should render only the area where the effect is active.
```

2022-12-16 00:48 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +                        // If the death animation is still in process then set isDefenderAnimatimg to false.
Please correct this comment: `isDefenderAnimatimg` --> `isDefenderAnimating`.

2022-12-16 00:48 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( wnce && !mirrorImages.empty() ) {
We can remove `wnce` check since we populate `mirrorImages` only when `wnce` is **true**.

2022-12-16 00:48 UTC, ihhub commented on src/fheroes2/gui/ui_tool.cpp
> +    Image CreateDeathWaveEffect( const Image & in, const int32_t x, const int32_t waveWidth, const std::vector<int32_t> & deathWaveCurve )
According to the code we create `deathWaveCurve` of the size of `waveWidth`. In this case I suggest to remove `waveWidth` as an input argument and declare this variable within the function:
```cpp
const int32_t waveWidth = static_cast<int32_t>( deathWaveCurve.size() );
```

2022-12-16 00:48 UTC, ihhub commented on src/fheroes2/gui/ui_tool.cpp
> +                DEBUG_LOG( DBG_BATTLE, DBG_WARN, "Death Wave curve is out of range (" << -height << ", 0): " << *pntX )
Based on the past problems with the code I suggest to just add `assert( 0 );` instead of logging the error so the issue will be immediately detected and fixed. If such a case happens with logging we would be a lot of log messages as this function is called many times as well as many values could be present.

2022-12-16 04:40 UTC, ihhub commented
Hi @Districh-ru , I updated your initial message to link #1041 and to be closed upon merging this pull request.

2022-12-16 05:02 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +            fheroes2::Blit( fheroes2::CreateDeathWaveEffect( copy, position, waveLength, deathWaveCurve ), _mainSurface );
I'll try to do this in a new PR.

2022-12-16 05:07 UTC, Districh-ru commented
> Hi @Districh-ru , I updated your initial message to link #1041 and to be closed upon merging this pull request.

Hi. @ihhub. Thanks!

2022-12-16 05:34 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +            fheroes2::Blit( fheroes2::CreateDeathWaveEffect( copy, position, waveLength, deathWaveCurve ), _mainSurface );
Yes, we don't need to do it here.

2022-12-16 05:39 UTC, ihhub approved these changes

2022-12-16 05:41 UTC, merged

2022-12-16 05:42 UTC, ihhub commented
@Districh-ru , huge thanks for upgrading these animations!