Fix bridge logic after morale event, simplify Bridge class, minor code cleanup
ihhub/fheroes2 pull request #6372
Opened 2022-12-17 01:10 UTC by oleg-derevenetz

Before this PR:

https://user-images.githubusercontent.com/32623900/208215297-a937516d-89cb-41c5-8564-9367dc27cce2.mp4

Now:

https://user-images.githubusercontent.com/32623900/208215374-7a51bcb7-23df-49be-b8fb-c547999a9134.mp4

Plus minor cleanup and simplification of overcomplicated castle bridge logic.

2022-12-17 01:51 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +        unit.SwitchAnimation( { Monster_Info::FLY_LAND, Monster_Info::STAND_STILL } );
Hi @Districh-ru I simplified your code a bit here and in another similar place.

2022-12-17 01:53 UTC, oleg-derevenetz commented
Hi @ihhub there is no hurry with this PR - this bug is minor, so you can leave this PR for 1.01 if you wish.

2022-12-17 04:25 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +        unit.SwitchAnimation( { Monster_Info::FLY_LAND, Monster_Info::STAND_STILL } );
Hi, @oleg-derevenetz, thanks, now this code is easier to read and easier to link `SwitchAnimation` with the comment! And also no 'push_back' calls.

2022-12-17 04:32 UTC, Districh-ru commented on src/fheroes2/battle/battle_bridge.cpp
> +    const int32_t headIdx = unit.GetHeadIndex();
I also read the code changes, now the bridge logic is more clear. :)

But here `unit.GetHeadIndex()` is used to check the position from where the walking unit will walk onto the bridge. So maybe it would be better to call variable as `curIdx` as we have `dstIdx` as the destination: 
```cpp
const int32_t curIdx = unit.GetHeadIndex();
```

2022-12-17 10:54 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_bridge.cpp
> +    const int32_t headIdx = unit.GetHeadIndex();
I would agree with this if the unit somehow moved right in this function, and there would be some sort of `curHeadIdx` and `thenHeadIdx`, in other words, if the result of `GetHeadIndex()` changed during the call of this function, but this is not really the case. There is no value for it other than "current" inside this function, so adding a prefix just lengthens the variable name without adding any value IMHO.

2022-12-17 11:18 UTC, Districh-ru commented on src/fheroes2/battle/battle_bridge.cpp
> +    const int32_t headIdx = unit.GetHeadIndex();
From this point of view, it is true. I looked from the point of the caller of this function.
It is OK to keep `headIdx` as it is always 'current' inside the function.

2022-12-18 09:49 UTC, ihhub requested changes
Hi @oleg-derevenetz , I put few comments here. Would you mind to take a look at them?

2022-12-18 09:49 UTC, ihhub commented on src/fheroes2/battle/battle_bridge.cpp
>  bool Battle::Bridge::isValid() const
Since we modify this code I suggest to make this method **inlined**. We can also make `isValid()`, `isDown()` and `AllowUp()` **inlined** as well.

2022-12-18 09:49 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    // TODO: remove this temporary assertion
Do we still need this comment and assertion?

2022-12-18 09:49 UTC, ihhub commented on src/fheroes2/battle/battle_bridge.h
> -        void Action( const Unit &, int32_t );
Just a side correction: shall we make this class `final`? :)

2022-12-18 10:56 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +    // TODO: remove this temporary assertion
I converted some temporary assertions to the permanent ones and added a few more temporary assertions just to check that previous assignments really were redundant :)

2022-12-18 10:58 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_bridge.h
> -        void Action( const Unit &, int32_t );
I made it `final`, but I should note though that there is not too much sense in making `final` classes without virtual methods. `final` is mainly useful to regulate the use of virtual methods.

2022-12-18 11:36 UTC, ihhub commented on src/fheroes2/battle/battle_bridge.h
> -        void Action( const Unit &, int32_t );
Oops... completely forgot about virtual.

2022-12-18 11:36 UTC, ihhub approved these changes

2022-12-18 11:45 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_bridge.h
> -        void Action( const Unit &, int32_t );
At least, there will be no harm anyway :) No one is going to inherit from `Bridge` anyway.

2022-12-18 12:05 UTC, Districh-ru approved these changes

2022-12-18 13:52 UTC, Branikolog approved these changes

2022-12-18 13:54 UTC, merged

2022-12-18 13:54 UTC, ihhub commented
@oleg-derevenetz , huge thanks for this fix!