Don't lowercase creature name (or other string) when it is put first in phrase
ihhub/fheroes2 pull request #6379
Opened 2022-12-17 12:55 UTC by Districh-ru

close #6328

![изображение](https://user-images.githubusercontent.com/113276641/208242680-84bddaeb-6eb1-4d60-9af2-53d7ade6c9a8.png)

2022-12-17 16:32 UTC, Districh-ru commented on src/engine/tools.cpp
> +    while ( std::string::npos != ( position = workString.find( pattern ) ) ) {
It also concerned me when I took this code it directly from `StringReplace()` function. Than I thought that the author of `StringReplace` didn't do it randomly. :)
But this is redundant. So I will change it to simple declaration without initialization.

2022-12-17 17:28 UTC, Districh-ru commented
> Let's say a translation would want to put the `%{monsters2}` at the start of that second sentence, `position` would not be `0` but the string should nevertheless not be lowercased.

@zenseii this issue also came to my mind, but we need to set a rule how to detect that the word is the first in sentence. We can check if there is a dot ('.') before it by adding a condition:`workString.at( position - 2 ) == '.'`  (-2 is because after dot there is a space). But also there could be many spaces, or `\n` ...
If it is needed I can try make such a check.

And also if we have a monster name with double words, in example, Power Liches, should we lowercase the second word if we put this name at the first place?

2022-12-17 18:13 UTC, Districh-ru commented
> Yes, this seems like the best check.
> 
> > But also there could be many spaces, or `\n` ... If it is needed I can try make such a check.
> 
> If such cases exist then yes, we would need a check, but if we don't have any then I don't think we need to spend time on it right now? There are many potential cases that I haven't checked like the use of `?`, `!` and other symbols before something that is to be replaced. I don't think we need to take all of these into consideration right now.
> 
> Line breaks do indeed exist like : `A few\n%{monster}`

I'll make a check for '.', '!' and '?' as the end of sentence.

> Hmm, yes, you're right. The second word should be lowercased in such situations. Nice catch!

Here is an example from the game:
![изображение](https://user-images.githubusercontent.com/113276641/208255653-2a84489c-157b-4774-94df-56442e429a56.png)

2022-12-17 21:26 UTC, oleg-derevenetz commented on src/engine/tools.cpp
> +        const char prevWordEnd = ( position > 1 ) ? workString.at( position - 2 ) : '\0';
This looks a bit too optimistic. There can be multiple space-like characters between sentences, say "\n\n" or even "\n \n" (not exactly our case, just to demonstrate that such separators really exist):

https://github.com/ihhub/fheroes2/blob/4dd7423a79a94bd39b93fc0fc1ad1f0a3e4b2378/src/fheroes2/heroes/heroes_action.cpp#L3201

IMHO it's better to really perform a reverse search, something like this:

```cpp
const char prevWordEnd = [&workString, position]() {
    assert( position < workString.size() );

    const auto iter = std::find_if_not( workString.rbegin() + ( workString.size() - position ), workString.rend(), []( const unsigned char c ) { return std::isspace( c ); } );
    if ( iter != workString.rend() ) {
        return *iter;
    }

    return '\0';
}();
```

2022-12-18 06:41 UTC, Districh-ru commented on src/engine/tools.cpp
> +        const char prevWordEnd = ( position > 1 ) ? workString.at( position - 2 ) : '\0';
Hello, @oleg-derevenetz. Thanks for suggestion!
To my shame, I am not familiar with the construction you used, but I understand what is happening. :)
Could you tell me what it is called and where I can read about it?

2022-12-18 07:47 UTC, oleg-derevenetz commented on src/engine/tools.cpp
> +        const char prevWordEnd = ( position > 1 ) ? workString.at( position - 2 ) : '\0';
This is called [lambda expressions](https://en.cppreference.com/w/cpp/language/lambda).

2022-12-19 00:09 UTC, ihhub requested changes
Hi @Districh-ru , I added multiple comments here. Would you mind to take a look at them when you have time?

2022-12-19 00:26 UTC, ihhub commented
I'm making this pull request for 1.0.1 as it does not have very critical priority.

2022-12-19 00:32 UTC, oleg-derevenetz commented on src/engine/tools.cpp
> +        if ( position == 0 || prevWordEnd == '.' || prevWordEnd == '?' || prevWordEnd == '!' ) {
Hi @ihhub Tabs, newlines and all kind of space characters should be skipped by lambda because of the `isspace()` check.

2022-12-19 00:33 UTC, ihhub commented on src/engine/tools.cpp
> +        if ( position == 0 || prevWordEnd == '.' || prevWordEnd == '?' || prevWordEnd == '!' ) {
Ah, got it.

2022-12-19 00:39 UTC, oleg-derevenetz commented on src/engine/tools.cpp
> +        // Also if the instert position equals to zero, than it is the first word in a sentence.
Lambda performs the reverse search and returns character with code 0 either if `position` is zero or if there are only spaces before the `position`. In either case, the character at `position` is at the beginning of a sentence, so we need to check that `prevWordEnd` is zero and not the `position`. Current logic does not take into account the case when there are only spaces before the `position`.

2022-12-19 07:07 UTC, Districh-ru commented on src/engine/tools.cpp
> +            const size_t spacePosition = inString.find( ' ' );
Hi, @ihhub, this operation is only needed here, when we put 'patternReplacement' ('inString') as the first word in a sentence. In other cases we lowercase the entire 'patternReplacement', no matter how many words there are. :)
I expanded the comment to clarify this issue.

2022-12-19 07:30 UTC, Districh-ru commented on src/engine/tools.cpp
> +        // Also if the instert position equals to zero, than it is the first word in a sentence.
@ihhub, the comment is about `position` variable, which tells where to instert the `pattern`. And lambda function returns its value to `prevWordEnd`.
@oleg-derevenetz, we can change the logic and check `prevWordEnd == '/0'` instead of `position == 0`. But we can have the parts of phrase, stored in separated strings. And such string can begin from space, followed by the word, which is not first in sentence.
This example string does not have a pattern to replace, it is to demonstrate such string that continues the phrase:

https://github.com/ihhub/fheroes2/blob/9e81adb24a6f64112fcb2024b57fc41e6edae983/src/fheroes2/heroes/heroes.cpp#L646

Lets assume that the beginning of the sentence either has a punctuation mark in front of it, or starts from the very beginning of the line.

2022-12-19 10:45 UTC, oleg-derevenetz commented on src/engine/tools.cpp
> +        // Also if the instert position equals to zero, than it is the first word in a sentence.
> But we can have the parts of phrase, stored in separated strings.

Yeah, forgot about this (not very correct in case of translatable strings) string concatenation practice. You are right, let's not treat string beginning with spaces as a beginning of a sentence.

2022-12-22 03:43 UTC, ihhub commented on src/engine/tools.cpp
> +            const size_t spacePosition = inString.find( ' ' );
Thank you for explanation!

2022-12-22 03:43 UTC, ihhub commented on src/engine/tools.cpp
> +        // Also if the instert position equals to zero, than it is the first word in a sentence.
Got it. Thank you very much for explanation!

2022-12-22 03:44 UTC, ihhub approved these changes

2022-12-22 11:12 UTC, oleg-derevenetz approved these changes

2022-12-22 14:57 UTC, Districh-ru commented on src/engine/tools.cpp
> +    // This function converts all letters in 'patternReplacement' to lowercase, except when it is the first word in a sentence.
Hi, @zenseii, I can leave a short comment in H file and also leave this comment.

2022-12-22 14:57 UTC, Districh-ru commented on src/engine/tools.cpp
> +        // Also if the insert 'position' equals to zero, than it is the first word in a sentence.
Sorry for my grammar.. :(

2022-12-22 15:41 UTC, oleg-derevenetz commented on src/engine/tools.cpp
> +    // This function converts all letters in 'patternReplacement' to lowercase, except when it is the first word in a sentence.
Hi @Districh-ru comments near function declarations in header files are preferred because usually people look into the header files when they search for the way to do something, since header files are relatively small. And only when they want to take a look on the implementation details, they will look into the cpp file.

2022-12-22 15:59 UTC, Districh-ru commented on src/engine/tools.cpp
> +    // This function converts all letters in 'patternReplacement' to lowercase, except when it is the first word in a sentence.
Hi, @oleg-derevenetz, thanks for the clarification on placing comments for functions!

2022-12-22 21:10 UTC, oleg-derevenetz commented on src/engine/tools.cpp
> +    // This function converts all letters in 'patternReplacement' to lowercase before replacing the 'pattern' in 'workString',
Hi @zenseii if @Districh-ru believes that there is some value in this comment even if the same thing is already described in the header file, then let it be.

2022-12-23 03:05 UTC, Districh-ru commented on src/engine/tools.cpp
> +    // This function converts all letters in 'patternReplacement' to lowercase before replacing the 'pattern' in 'workString',
Hi, @zenseii, I removed it not to duplicate the existing one in H file.

2022-12-30 14:39 UTC, merged

2022-12-30 14:39 UTC, ihhub commented
@Districh-ru , thanks a lot for this improvement!