Add global hotkey to toggle the text support mode
ihhub/fheroes2 pull request #6382
Opened 2022-12-17 15:36 UTC by oleg-derevenetz

close #6370

F10 by default.

2022-12-17 19:52 UTC, oleg-derevenetz commented
@ihhub I assigned the 1.01 milestone for this PR, but it's up to you to decide whether you will risk it or not :)

2022-12-17 23:50 UTC, oleg-derevenetz commented
> The only thing I noticed is that the state of this option does not visually change in the config dialog when you press F10.

Yeah, I forgot about that config dialog. Thought it was still only set via the configuration file.

2022-12-18 02:35 UTC, ihhub requested changes
Hi @oleg-derevenetz , I put several comments in this pull request. Could you please take a look?

2022-12-18 02:35 UTC, ihhub commented on src/fheroes2/dialog/dialog_game_settings.cpp
> +                display.render();
Please use this call `display.render( { emptyDialogRestorer.x(), emptyDialogRestorer.y(), emptyDialogRestorer.width(), emptyDialogRestorer.height()} );` to avoid whole screen re-rendering. Or you can create a **fheroes2::Rect** before the loop and use it here.

2022-12-18 02:35 UTC, ihhub commented on src/fheroes2/dialog/dialog_game_settings.cpp
> +                isTextSupportModeEnabled = Settings::Get().isTextSupportModeEnabled();
Please use `conf` over `Settings::Get()`. This variable is declared at the beginning of the function.

2022-12-18 02:35 UTC, ihhub commented on src/fheroes2/dialog/dialog_game_settings.cpp
> +        bool isTextSupportModeEnabled = Settings::Get().isTextSupportModeEnabled();
Please use `conf` over `Settings::Get()`. This variable is declared at the beginning of the function.

2022-12-18 08:06 UTC, ihhub approved these changes

2022-12-18 08:07 UTC, merged

2022-12-18 08:07 UTC, ihhub commented
@oleg-derevenetz , thanks a lot for these changes!