Rework AI hero task priority logic
ihhub/fheroes2 pull request #6389
Opened 2022-12-18 08:20 UTC by ihhub

2023-02-26 08:46 UTC, idshibanov approved these changes

2023-02-26 15:07 UTC, oleg-derevenetz requested changes
Hi @ihhub found only a few typos in old comments so far :) Please take a look when you have time.

2023-02-26 15:07 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                return -dangerousTaskPenalty; // no reason to visit with a maximum moral
```suggestion
                return -dangerousTaskPenalty; // No reason to visit with maximum luck
```

2023-02-26 15:07 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                return -4000; // moral is good enough to avoid visiting this object
```suggestion
                return -4000; // Luck is good enough to avoid visiting this object
```

2023-02-26 15:07 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                return -2000; // is it worth to visit this object with little better than neutral moral?
```suggestion
                return -2000; // Is it worth visiting this facility with a luck slightly better than neutral?
```

2023-02-26 15:07 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
>                  return -dangerousTaskPenalty; // no reason to visit with a maximum moral
```suggestion
                return -dangerousTaskPenalty; // No reason to visit with maximum morale
```

2023-02-26 15:07 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
>                  return -4000; // moral is good enough to avoid visiting this object
```suggestion
                return -4000; // Morale is good enough to avoid visiting this object
```

2023-02-26 15:07 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
>                  return -2000; // is it worth to visit this object with little better than neutral moral?
```suggestion
                return -2000; // Is it worth visiting this facility with a morale slightly better than neutral?
```

2023-02-27 08:11 UTC, oleg-derevenetz approved these changes

2023-02-27 16:22 UTC, Districh-ru approved these changes

2023-02-28 11:02 UTC, merged