Optimize Death Wave spell effect rendering. Battlefield.
ihhub/fheroes2 pull request #6413
Opened 2022-12-24 18:04 UTC by Districh-ru

Reworked the rendering of the Death Wave spell effect. Now the game only renders the part of the screen where the effect is located. This effect now renders approximately 3 times faster.
Also in this PR before the spell effect, all creatures are now forced to stop their `IDLE` animation and their unit counter is now turned off, as it is not so aesthetic when the creature freezes in some `IDLE` pose during the spell animation and when the unit counters, that are part of the user interface , are distorted by the spell. The same applies to the Holy Shout spell.

<details><summary>A video of Death Wave spell effect</summary>

https://user-images.githubusercontent.com/113276641/209446836-30a4f65d-3acd-4739-ba2d-0040ca8fde31.mp4

</details>

2022-12-25 14:35 UTC, ihhub requested changes
Hi @Districh-ru , I put several comments for further optimization. Could you please take a look when you have time?

2022-12-25 14:35 UTC, ihhub commented on src/fheroes2/gui/ui_tool.cpp
>      Image CreateDeathWaveEffect( const Image & in, const int32_t x, const std::vector<int32_t> & deathWaveCurve )
We can accept another input parameter `Image & out` and then call resize lower in the code. For cases when we render the death wave effect in outside image borders the size remains the same which means that `out.resize()` call will do nothing. It will save resources for memory allocation and deallocation.

2022-12-25 14:35 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +            const fheroes2::Image spellEffect = fheroes2::CreateDeathWaveEffect( copy, position, deathWaveCurve );
If we declare an image outside the loop and pass it into the function we can save resources for memory management operations.

2022-12-25 14:35 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
>      const fheroes2::Sprite & copy = fheroes2::Crop( _mainSurface, area.x, area.y, area.width, area.height );
I just realized that the name of this variable is very tricky. Please rename it to avoid confusion from `copy()` calls for memory management.

2022-12-25 14:35 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
>      const fheroes2::Sprite & copy = fheroes2::Crop( _mainSurface, area.x, area.y, area.width, area.height );
`_mainSurface` should be the same size as `area`. If this is the case then simple call like this would save time:
```cpp
const fheroes2::Image mainSurfaceCopy( _mainSurface );
```

2022-12-25 14:35 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
>      AudioManager::PlaySound( M82::MNRDEATH );
To synchronize the audio with visual effect even better (we have some calculations before we render the next frame) please put this line just before the **while** loop. Of course we're talking here about few CPU ticks but still it's better to avoid them.

2022-12-25 14:35 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +            }
This is actually tricky we draw the whole log but render only a part of it. In this case we expect a frame with the rest of log to be present on screen. We have 2 options here:
- render the whole area of the battle (just the battlefield itself). Slower but no issues.
- in case of open listlog we don't need to copy the whole `_mainSurface` but only a part:
```cpp
fheroes2::Image mainSurfaceCopy;

if ( listlog && listlog->isOpenLog() ) {
    const int32_ width = _mainSurface.width();
    const int32_t height = _mainSurface.height() - listlog->GetArea().height();
    mainSurfaceCopy.resize( width, height );
    fheroes2::Copy( _mainSurface, 0, 0, mainSurfaceCopy, 0, 0, width, height );

    area.height -= listlog->GetArea().height();
}
else {
    mainSurfaceCopy = _mainSurface
}
```
as you can see from the screenshot we don't need to care about the log part:
![image](https://user-images.githubusercontent.com/19829520/209471860-7e7d9493-c13a-4da8-a919-58823c5fa0a3.png)

then we don't need to care about log list in the loop.

2022-12-25 15:24 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
>      const fheroes2::Sprite & copy = fheroes2::Crop( _mainSurface, area.x, area.y, area.width, area.height );
Hi, @ihhub, the `_mainSurface` also contains the bottom panel with buttons (Auto, Skip) and battle status log. So we always crop 36 pixels from the bottom.

2022-12-25 16:28 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +            }
As we always have the status bar and we always have to crop the `_mainSurface` I've only added this:
```cpp
    area.height -= status.height;
    // And if listlog is open, then cut off it too.
    if ( listlog && listlog->isOpenLog() ) {
        area.height -= listlog->GetArea().height;
    }
```

PS
Maybe we have to close the listlog before any human action on the battlefield?
@Branikolog, @zenseii, what do you think? :)

2022-12-25 18:17 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +            }
Yes, @zenseii, I mean auto-hide of the log list.

2022-12-26 03:56 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
>      const fheroes2::Sprite & copy = fheroes2::Crop( _mainSurface, area.x, area.y, area.width, area.height );
Oh, yes. Could you please create a variable in anonymous namespace at the beginning of this file to store 36 value? Something like `const int32_t statusBarHeight{ 36 };`

2022-12-26 03:57 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
>      const fheroes2::Sprite & copy = fheroes2::Crop( _mainSurface, area.x, area.y, area.width, area.height );
We don't need to crop but to copy. Crop is slightly slower operation than Copy.

2022-12-26 15:01 UTC, ihhub approved these changes

2022-12-26 15:02 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +            }
I suggest to keep it as it is for now and create an issue or discussion topic to find the best solution.

2022-12-26 19:37 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +            }
I only asked this question here because I ran into this situation here (I rarely open battle log). :)
Indeed, this issue needs to be discussed separately, and if we decide to implement auto-hide of the battle log, then this should be done in a separate PR. I've opened a discussion: #6420

2022-12-27 10:24 UTC, oleg-derevenetz approved these changes

2022-12-27 11:56 UTC, merged

2022-12-27 11:56 UTC, ihhub commented
@Districh-ru , thank you so much for this improvement!

2022-12-30 13:03 UTC, Branikolog commented
Sorry for being out of project for several days, guys. 
@Districh-ru 
It's a nice improvement, but I'm afraid turning off creature counters makes it impossible to understand, how many troops demolished, when you're focused on the most important stack at the moment. :)
Everything  else is fine, but I'd like to see how counters have changed after spell applied.

2022-12-30 13:34 UTC, Districh-ru commented
Hello, @Branikolog!
I've turned the counters off only for the wave effect.
I can revert this change.
But the counters are also turned off for wince animation. After wince animation they are turned on. (The counters are displayed only for `STATIC` and `IDLE` animations).

2022-12-30 14:27 UTC, Branikolog commented
@Districh-ru 
In the original game, creature counter updates after wincing and after appearing of counter itself: сreature winces -> counter appears -> number is changed. I suppose it's a separate issue, right? 
But I personally prefer looking at counters during animation, so I can prepare myself for a drastic losses and try to save in my memory each single face of my troop, that faced that terrifying spell. :D

2022-12-30 14:38 UTC, ihhub commented
@Branikolog , I think this is beyond the scope of this particular pull request. The changes here were targeted only to improve the performance of the algorithm.

2022-12-30 14:43 UTC, Branikolog commented
Hi, @ihhub !
The PR made creature counters hidden which resulted in not clear losses after spell applied. I personally find it a bit uncomfortable to track what creatures I've lost.

2022-12-30 14:45 UTC, Districh-ru commented
@ihhub, I also made the change that counter now is not displayed during the render of wave effect.
That's why I asked @Branikolog for review. :)
I can easily revert it in a new PR by changing `SwitchAllUnitsAnimation( Monster_Info::STAND_STILL );` to `SwitchAllUnitsAnimation( Monster_Info::STATIC );`
The counter update algorithm is beyond this PR, but currently in out engine: calculation of units kills (without updating the counter) -> disable counter + render wince animation -> change animation to 'static' with enabling the counters that displays the new value of live creatures.