Improvements to the French translation
ihhub/fheroes2 pull request #6418
Opened 2022-12-26 17:31 UTC by hlabrand

Hi! I read the whole .po file and found several improvements to be made: typos, inconsistencies, sentences that didn't sound great, sentences that were gendered but shouldn't be (wouldn't work for female heroes for instance), etc.

There is only one change I am not sure of: the translation of "UPGRADE". It used to be "ÉVOLUER", which works in some contexts (like Pokémon, where creatures grow into other ones) but didn't feel right and was inconsistent with other game messages, which used "améliorer" (improve, which is much better). However "AMÉLIORER" is 9 letters, 2 letters longer than the original; from the uppercase I assume this is used in a button, and so is the text going to overflow the button?

2022-12-30 16:27 UTC, felix642 requested changes
Hi @hlabrand, I've left a few comments. Would you mind taking a look ? :)

2022-12-30 16:27 UTC, felix642 commented on files/lang/fr.po
> +msgstr "%{name} se rend à l'ennemi et part, son nom couvert de honte."
I don't agree with this change. I feel like the original translation was fine, why did we add "son nom" ?

2022-12-30 16:27 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Voulez-vous vraiment finir la bataille en mode combat auto ?"
I'm assuming that those changes were done to improve consistency? 

We were using "Voulez-vous" at some places and "Êtes-vous sûr" at other ?

2022-12-30 16:27 UTC, felix642 commented on files/lang/fr.po
> +"matés. Ils sont riches et puissants, alors préparez-vous à un combat "
Not quite sure to know what "maté" is ? 

From the larousse it seems to be a drink, are you sure you're using the right word here ?

2022-12-30 16:27 UTC, felix642 commented on files/lang/fr.po
> +"votre mission avant le premier jour du septième mois, sinon le royaume "
You removed a word here, but now the sentence does not make sense anymore "sinon le royaume sûrement s'effondrer"

2022-12-30 16:27 UTC, felix642 commented on files/lang/fr.po
> +"Les nains vous saluent, \"Tous les ami des Roland sont nos amis. Vous pouvez "
```suggestion
"Les nains vous saluent, \"Tous les amis de Roland sont nos amis. Vous pouvez "
```

2022-12-30 18:09 UTC, hlabrand commented on files/lang/fr.po
> +msgstr "%{name} se rend à l'ennemi et part, son nom couvert de honte."
This is because if the hero is a female, the gender doesn't work - "Gwenneth part couvert de honte" doesn't work. If we imply her name is covered in shame, instead, the "son nom" works for both genders and it works. I thought it was an elegant way to avoid the gender issue but what do you think?

2022-12-30 18:10 UTC, hlabrand commented on files/lang/fr.po
> +msgstr "Voulez-vous vraiment finir la bataille en mode combat auto ?"
There was a few "voulez-vous" yes, and "êtes-vous sûr de vouloir" is longer and (this is minor but) if the player is not a man that doesn't quite work. I thought it was more elegant to use the compact formulation that works either way.

2022-12-30 18:12 UTC, hlabrand commented on files/lang/fr.po
> +"matés. Ils sont riches et puissants, alors préparez-vous à un combat "
https://dictionnaire.reverso.net/francais-synonymes/mater+la+r%C3%A9bellion
It's a verb used specifically in a military context, "squashing the rebellion", "suppressing the uprising" kind of thing. I think it's the preferred word instead of "you must submit them".

2022-12-30 18:12 UTC, hlabrand commented on files/lang/fr.po
> +"votre mission avant le premier jour du septième mois, sinon le royaume "
Oh oops totally an oversight, thank you!

2022-12-30 18:14 UTC, hlabrand commented
Thank you so much for your comments! :D

2022-12-30 22:52 UTC, felix642 commented on files/lang/fr.po
> +msgstr "%{name} se rend à l'ennemi et part, son nom couvert de honte."
Oh, that makes sense! Perfect !

2022-12-30 22:53 UTC, felix642 commented on files/lang/fr.po
> +msgstr "Voulez-vous vraiment finir la bataille en mode combat auto ?"
Sounds good to me !

2022-12-30 22:55 UTC, felix642 commented on files/lang/fr.po
> +"matés. Ils sont riches et puissants, alors préparez-vous à un combat "
You are right, for some reasons I didn't realize it was a verb and searched "maté" instead of "mater". You can resolve this comment, thank you :)

2022-12-30 22:56 UTC, felix642 approved these changes
LGTM !

2022-12-31 04:09 UTC, hlabrand commented on files/lang/fr.po
> +msgstr "AMÉLIORER"
Sorry, is the question addressed to me? Do I need to try to build from source to see how this looks? Not sure I'll have time, maybe we can forego this change for now..

2023-01-03 07:46 UTC, hlabrand commented on files/lang/fr.po
> +msgstr "AMÉLIORER"
(It took me over an hour to install this correctly... Go figure)
After replacing with my mo here is what it looks like
![ameliorer](https://user-images.githubusercontent.com/1617462/210316805-bc7bdcd8-fc7e-45eb-98e5-2c73d63ad134.png)

I did not touch "renvoyer" so the issue was already there before... This makes me think the French version wasn't thoroughly tested for such UI artefacts? But i dont know if we want to shove it in this PR; I'm running out of vacation time :)

2023-01-03 08:03 UTC, hlabrand commented on files/lang/fr.po
> +msgstr "AMÉLIORER"
That makes total sense, thanks for explaining! Resolving this now :)

2023-01-04 15:20 UTC, merged

2023-01-04 15:20 UTC, ihhub commented
@hlabrand , thank you so much for your contribution to the project!