[1228] Persisting window position between sessions (SDL2)
ihhub/fheroes2 pull request #6419
Opened 2022-12-26 17:45 UTC by VestinVestin

Works under SDL2, ignores (but doesn't break) SDL1. From what I've seen, it's not worth it to get into the black magic of per-platform hackery necessary to make the SDL1 version work.

2022-12-27 00:48 UTC, ihhub commented
Hi @VestinVestin ,

You are trying to include headers which don't belong there. `settings.h` is a part of `fheroes2` code part while `screen.h` is a part of engine. Engine part shouldn't have any implementation related information.

2022-12-27 22:59 UTC, VestinVestin commented
> Hi @VestinVestin ,
> 
> You are trying to include headers which don't belong there. `settings.h` is a part of `fheroes2` code part while `screen.h` is a part of engine. Engine part shouldn't have any implementation related information.

Yeah, I knew I was doing something wrong there. I got too excited by getting any solution to work locally.
I've added a callback / hook instead. The only thing I don't like is that it persists the settings every time someone moves the window, but I guess logic like "Save on exit if modified" would belong in another PR.

2022-12-29 14:03 UTC, ihhub requested changes
Hi @VestinVestin , I left several comments in this pull request. Could you please take a look?

2022-12-29 14:03 UTC, ihhub commented on src/fheroes2/system/settings.h
> +    }
Please name this method as per our coding rules: `getWindowPosition()` and it should return const reference.

2022-12-29 14:03 UTC, ihhub commented on src/fheroes2/system/settings.h
> +    void SetWindowPosition( fheroes2::Point position );
This method should be `inlined`.

2022-12-29 14:03 UTC, ihhub commented on src/fheroes2/system/settings.h
> +    fheroes2::Point window_position{ 0, 0 };
Please use correct `_camelCase` naming.

2023-03-21 17:34 UTC, VestinVestin commented
> Hi @VestinVestin , could you please address given comments in this pull request as well as fix merge conflicts here?

Yeah, sorry, life got in the way ^^". I'll try to sort this out relatively soon.

2023-07-20 01:04 UTC, VestinVestin commented on src/engine/localevent.h
> +#if SDL_VERSION_ATLEAST( 2, 0, 0 )
Alright, as far as I can tell, I've removed it where it was unnecessary.

2023-07-21 12:26 UTC, ihhub requested changes
Hi @VestinVestin , I put multiple comments in this pull request. Could you please take a look at them?

2023-07-21 12:26 UTC, ihhub commented on src/engine/localevent.h
> +    static fheroes2::Point getCenterPosition();
I suggest to name this method to be more accurate: `getWindowCenteredPosition()` as it is not obvious what this position for.

2023-07-21 12:26 UTC, ihhub commented on src/engine/localevent.h
> +    inline static std::function<void( const int, const int )> _onWindowMoved;
Could you please explain why we need to use **inline** and **static** on a member of this class if it is a singleton?

2023-07-21 12:26 UTC, ihhub commented on src/fheroes2/game/fheroes2.cpp
> +    conf.SaveIfNecessary();
Please do not put any code outside the exception catching block.

2023-07-21 12:26 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +    fheroes2::Point center_position = LocalEvent::getCenterPosition();
Please use camelCase variable naming, not C style.

2023-07-21 12:26 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +    fheroes2::Point center_position = LocalEvent::getCenterPosition();
Is there a reason why we need to declare this variable? It is not used anywhere except one line below.

2023-07-21 12:26 UTC, ihhub commented on src/fheroes2/system/settings.h
> +    bool config_modified = false;
Do not declare public variables in a class. Put it in a private section and use camelCase naming with an underscore symbol for members.

2023-07-21 12:26 UTC, ihhub commented on src/fheroes2/system/settings.h
> +    inline void SetWindowPosition( const fheroes2::Point & position )
Please remove **inline** keyword. Modern compilers do not need this anymore.

2023-07-21 12:26 UTC, ihhub commented on src/fheroes2/system/settings.h
> +    fheroes2::Size video_mode;
This member is not used anywhere.

2023-07-21 12:26 UTC, ihhub commented on src/fheroes2/game/game.cpp
> +#include <SDL_version.h>
Please do not put SDL dependency on files within fheroes2 directory. All SDL dependencies must be only **engine** directory.

2023-07-21 12:26 UTC, ihhub commented on src/engine/localevent.h
> +    static void setWindowMovedEventHook( std::function<void( const int, const int )> hook )
Please make this method non-static as **_onWindowMoved** is going to be non-static as well.

2023-07-21 12:26 UTC, ihhub commented on src/fheroes2/game/fheroes2.cpp
> +    conf.SaveIfNecessary();
If we are saving everything just at the time of closing application would be it better to just query the current window position and avoid all these function calls, variable settings and etc.? I think this would be just few lines of code solution.

2023-08-23 04:17 UTC, ihhub commented
Marking this pull request as WIPas the author doesn't respond.

2023-12-01 20:39 UTC, closed without merging