update man page
ihhub/fheroes2 pull request #6425
Opened 2022-12-28 15:55 UTC by undef21

- add info about files/soundfonts directory;
- rephrase a sentence about music.

2022-12-29 13:27 UTC, ihhub approved these changes

2022-12-29 17:56 UTC, oleg-derevenetz requested changes
Hi @undef21 LGTM in general, just one typo that needs to be fixed :)

2022-12-29 17:56 UTC, oleg-derevenetz commented on docs/fheroes2.6.in
> +Additional SoundFont files for MIDI synthesier. sf2 and sf3 formats are supported.
It looks like there is a typo: `synthesier` -> `synthesizer`.

2022-12-29 18:22 UTC, undef21 commented on docs/fheroes2.6.in
> +Additional SoundFont files for MIDI synthesier. sf2 and sf3 formats are supported.
Thanks. Fixed.

2022-12-29 18:27 UTC, oleg-derevenetz approved these changes

2022-12-30 02:05 UTC, merged

2022-12-30 02:05 UTC, ihhub commented
@undef21 , thank you very much for these changes!