Better support of commandline arguments to check_copyright_headers
ihhub/fheroes2 pull request #6428
Opened 2022-12-29 13:43 UTC by drevoborod

Improved support of command line arguments. It allows to simplify future changes and adds auto formatting of usage messages.
Now error message will look like this:

```
usage: check_copyright_headers.py [-h] full_header_file header_template_file source_file [source_file ...]
check_copyright_headers.py: error: the following arguments are required: full_header_file, header_template_file, source_file
```

2022-12-29 16:02 UTC, oleg-derevenetz commented
Hi @drevoborod This script in general is not intended to be run by hand, it is internal script for our CI, so "user friendliness" is not an essential requirement for it :)

2022-12-29 17:40 UTC, oleg-derevenetz commented on script/tools/check_copyright_headers.py
> +        self.exit(1, gettext('%(prog)s: error: %(message)s\n') %
LGTM in general, but `gettext` usage is really redundant here: no one will do localization/internationalization of this purely service script, so I believe that we can remove this dependency and use English-only messages with a calm soul.

2022-12-29 17:41 UTC, oleg-derevenetz requested changes

2022-12-29 17:41 UTC, oleg-derevenetz commented on script/tools/check_copyright_headers.py
> +                  {'prog': self.prog, 'message': message})
LGTM in general, but `gettext` usage is really redundant here: no one will do localization/internationalization of this purely service script, so I believe that we can remove this dependency and use English-only messages with a calm soul.

2022-12-29 18:48 UTC, drevoborod commented on script/tools/check_copyright_headers.py
> +                  {'prog': self.prog, 'message': message})
> LGTM in general, but `gettext` usage is really redundant here: no one will do localization/internationalization of this purely service script, so I believe that we can remove this dependency and use English-only messages with a calm soul.

I agree. It was just a copy-paste from original .error() method. Ok, I removed it.

2022-12-29 18:53 UTC, drevoborod commented
> Hi @drevoborod This script in general is not intended to be run by hand, it is internal script for our CI, so "user friendliness" is not an essential requirement for it :)

I know :) Actually more important part is that I gave human-readable names to all commandline params variables in code. For example, not sys.argv[1] but args.full_header_file. It helps to remember what it is and not to make mistakes in case there will be some changes needed. Also, it's much more flexible solution - for example, one can add not position but named arguments or even optional arguments and so on. But it's up to you, I don't insist :)

2022-12-29 19:37 UTC, oleg-derevenetz approved these changes

2022-12-30 14:33 UTC, ihhub approved these changes

2022-12-30 14:34 UTC, merged

2022-12-30 14:34 UTC, ihhub commented
@drevoborod , thank you very much for your contribution to the project!