Battle log text overflowing
ihhub/fheroes2 pull request #6433
Opened 2022-12-30 17:13 UTC by felix642

When messages in the battle log are too long, we split it in 2 messages using the first space character we see.

closes #6357

2023-01-05 14:35 UTC, felix642 commented
> Hi, @felix642. Could you please address the IWYU check's failure? Either there's either a header that needs to be included or excluded.

Oh, didn't realize a check had failed. Thank you for letting me know. I will fix that as soon as possible and let you know once this PR is ready for review.

2023-01-25 15:52 UTC, felix642 commented
Hi @zenseii,

Thank you for reminding me. I did notice that the Style check failed and even flagged the email I received from GitHub. But for some reason, I still forgot to fix it. I'll commit my fix later tonight.

2023-02-01 15:39 UTC, Branikolog commented
Hi, @zenseii !
I see at least three solutions to the problem with insufficient space for a string in battle log. 
First of all, I believe cutting line into two is not the best solution, as we simply won't see both lines at the same time below the battlefield. Unless we change the rules for showing info on hovering with the mouse over the battlefield (which could be a 4th solution to the problem, actually 😄). For instance, make a pause for 3-5 seconds, before, the first line comes up and we watch the info as it is on your screenshot.
As a solution I propose such things:
- shorten the entire string, so it'd fit info box. Rephrasing or cutting off something not essential. Like showing `Swordsmen do xxx damage` instead of `Master Swordsmen do xxx damage` (I hope player won't be confused with missing the first word, since he clearly understands, what troop he's currently sending into battle ). This is applied only for bottom info box with a separate rule. The entire battle log can show non-shortened string, as it has more space. But this approach could have some problems for other languages. For instance, there're "Цари минотавров" in Russian and cannot just cut off the first word without changing the second one. :)
- Make text line smoothly shifting, similar to advertising boards in the city. This could be a single movement and stop on reaching the end of the line, or looped shifting of the text from left to right.
- As 99% of modern devices have widescreens, we can change the default game width (I mean change the lowest resolution to become wider, from 640x480 to 720x480 or so) so we would be able move "skip" "auto", "settings" buttons somewhere else and expand bottom info box to fit the entire battle screen field. We have an issue with tiny auto&settings buttons for small mobile screens. To make them bigger we have to get some space and move them to the sides. In future, there could appear even some new buttons, and we'd definitely require more space for them, so we can start rearranging game UI from expanding battle info box and moving buttons.

2023-02-02 03:36 UTC, Districh-ru commented
Hi @zenseii , @felix642 , @Branikolog ,
We can cut every long string in the battle status bar ("Someone did sonething to another one and ...") and show the full string in the battle log separated into 2 lines if needed.
Or we can make a narrow font for the long phrases in the status bar to fit them.
Or ... we can use creatures icons instead of their names in status bar. :)

2023-02-04 07:54 UTC, Districh-ru commented
Hi, @felix642, IMHO currently we can use approach suggested by @zenseii, but split phrase in battle log if it does not fit (the Battle log, not the status bar). And later when we will (and if we will) have special narrow fonts for such cases we can change the display of phrases in status bar.

2023-02-04 15:30 UTC, felix642 commented
@Districh-ru Sounds good to me.

2023-02-07 12:19 UTC, Branikolog commented
Splitting line and showing only the first part of the line could be a solution for now.
Between, I've noticed, that if we point mouse on a place, where no action could be done, we watch "Turn xx" line. Can we show second line (which was previously cut off) in such situations? I think turn number is not such an essential information, and hovering on some inactive places for showing full line is quite predictable behaviour for battle log. How do you think?
![crop log](https://user-images.githubusercontent.com/55348946/217242571-7b5645d7-5209-4778-a282-78307bf23817.png)

2023-02-08 15:58 UTC, ihhub requested changes
Hi @felix642 , I put few comments here. Would you mind to take a look when you have free time?

2023-02-08 15:58 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        static std::vector<std::string> splitMessage( const std::string & message, size_t maxLength )
I suggest to put this function into **tools.h|cpp** files as it belongs there.

2023-02-08 15:58 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        static std::vector<std::string> splitMessage( const std::string & message, size_t maxLength )
`maxLength` can be **const** as we don't modify it within the function.

2023-02-08 15:58 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +                nextEnd = message.find( ' ', currentEnd + 1 );
Should we add a third parameter which accept **char** as a delimiter to be more generic of handling things?

2023-02-08 15:58 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        static std::vector<std::string> splitMessage( const std::string & message, size_t maxLength )
Would it be even more efficient to pass `std::vector<string>` as an output parameter to add elements in place instead of creating a temporary array to later move elements from there?

2023-02-19 03:04 UTC, felix642 commented on src/fheroes2/battle/battle_interface.cpp
> +        static std::vector<std::string> splitMessage( const std::string & message, size_t maxLength )
Hi @ihhub,

It would in fact be more efficient to add the elements in place rather than copy them from one vector to another. The issue is that the method will have 2 responsibilities (split the string and insert it into another vector) and the code might lose readability. I'm not against the idea, but I think we should find a way to name the method properly and I can't find any good idea right now.

2023-02-19 23:50 UTC, ihhub requested changes
Hi @felix642 , I left one suggestion about a different approach to tackle this issue. Could you please take a look at it?

2023-02-19 23:50 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +            const int maxBattleLogSize = 72;
This number really depends on a font and letter sizes in general. For instance:
72 times letter W is not equal 72 times letter i by width. Of course such text won't appear on the screen but this is a bright example of size differences.
I suggest to switch to fheroes2::Text within this class instead of old Text class. fheroes2::Text class has an embedded functionality to divide a string based on maximum width. Such a solution would be much more flexible.

Note: fheroes2::Text class renders text with 2 pixel offset by Y axis so please remember this.

What do you think?

2023-02-20 01:35 UTC, felix642 commented on src/fheroes2/battle/battle_interface.cpp
> +            const int maxBattleLogSize = 72;
Hi @ihhub, I did not know such class existed and I think this is a great idea. I'll take a look at the class and how to implement it properly within the battle log. Thank you for the suggestion :)

2023-02-20 18:23 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +            const int maxBattleLogSize = 72;
Hi @felix642 and @ihhub. `fheroes2::Text` could be used here like (it is a quick example):
```cpp
        void RedrawItem( const std::string & str, int32_t px, int32_t py, bool ) override
        {
            fheroes2::Display & display = fheroes2::Display::instance();
            const fheroes2::Text text( str, fheroes2::FontType::normalWhite() );
            const int32_t logWidth{ 600 };
            text.draw( px, py, logWidth, display );
        }
```
But we will have issues when the text is split into two lines, as the game makes a vector `messages` and considers each message as a single line text. It will result in overlapping of the bottom part of split text with the next message string.
So we will have to use something like `text.rows( logWidth);` and put the result in a new vector to keep row info about each message and use this vector in loop that calls `RedrawItem()` in `interface_list.h`. (we could make `RedrawItem()` to return the number of rendered rows).
So we will have to do changes in `ListBox` class (in `interface_list.h`) and these changes should not affect the other places where we use this class. 
And also one notice: currently all battle log massages are left aligned and  `.draw()` makes the text center aligned.

2023-03-21 15:29 UTC, felix642 commented
Hi @ihhub, I'll do my best to address those comments as soon as possible. I'll mark this PR as a draft while I make the required changes and let you know once they are ready.

2023-09-30 12:36 UTC, ihhub commented
Closing this pull request in favor of #7847.

2023-09-30 12:36 UTC, closed without merging