Changelog in appdata.xml
ihhub/fheroes2 pull request #6439
Opened 2022-12-31 20:45 UTC by Laserlicht

Script for parsing the `changelog.txt` into `*.appdata.xml`. Copies the whole changlog (except the oldest entry) in the appdata.xml.

Appdata can be updated after changelog update by executing `python3 script/tools/changelog_update_appdata.py changelog.txt script/packaging/common/fheroes2.appdata.xml`.

@ihhub Do you think that's a good idea, or should we rather discard it?

Furthermore I have also added the donate link.

Changelogs looks like this in the software center (sorry for german):
![grafik](https://user-images.githubusercontent.com/13953785/210155152-5bf11fe2-f074-4f3e-9367-53820f777a1a.png)

2022-12-31 23:57 UTC, oleg-derevenetz requested changes
Hi @Laserlicht I found one missing import in your script and left one comment, please take a look when you have time.

2022-12-31 23:57 UTC, oleg-derevenetz commented on script/tools/changelog_update_appdata.py
> +        self.print_usage(sys.stderr)
Please add `import sys` at the imports section, otherwise this will not work:

```
$ ./changelog_update_appdata.py
Traceback (most recent call last):
  File "/home/oleg/Temp/./changelog_update_appdata.py", line 61, in <module>
    main()
  File "/home/oleg/Temp/./changelog_update_appdata.py", line 25, in main
    args = parse_arguments()
  File "/home/oleg/Temp/./changelog_update_appdata.py", line 22, in parse_arguments
    return parser.parse_args()
  File "/usr/lib/python3.10/argparse.py", line 1826, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.10/argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.10/argparse.py", line 2100, in _parse_known_args
    self.error(_('the following arguments are required: %s') %
  File "/home/oleg/Temp/./changelog_update_appdata.py", line 14, in error
    self.print_usage(sys.stderr)
NameError: name 'sys' is not defined
```

2022-12-31 23:57 UTC, oleg-derevenetz commented on script/tools/changelog_update_appdata.py
> +    changelog = open(args.changelog_file, encoding='utf-8').read()
Nice looking one-liner, but `changelog_file` will remain opened until the whole script exits :) However, in script like this it's OK.

2023-01-01 00:16 UTC, Laserlicht commented on script/tools/changelog_update_appdata.py
> +        self.print_usage(sys.stderr)
Oh! Yes of course. :)

2023-01-01 00:17 UTC, Laserlicht commented on script/tools/changelog_update_appdata.py
> +    changelog = open(args.changelog_file, encoding='utf-8').read()
Yes, you're right. :)

2023-01-01 04:12 UTC, ihhub commented
Hi @Laserlicht , please rebase your branch from `master`. @oleg-derevenetz fixed the issue with code style.

2023-01-01 04:14 UTC, ihhub commented
@Laserlicht , I think displaying the changes is always good so players can see that the project is evolving.

2023-01-01 04:25 UTC, ihhub requested changes
Hi @Laserlicht , I left multiple comments in this pull request. Could you please take a look? On top of this I have a question: where and when this script should be executed?

2023-01-01 04:25 UTC, ihhub commented on script/tools/changelog_update_appdata.py
> +#!/usr/bin/env python3
Is there a reason we want to use Python 3 over 2?

2023-01-01 04:25 UTC, ihhub commented on script/tools/changelog_update_appdata.py
> +#!/usr/bin/env python3
This file is missing copyright header.

2023-01-01 04:25 UTC, ihhub commented on script/tools/changelog_update_appdata.py
> +    </release>\n'''[1:]
Here we take all symbols except the first one. Should it be better to just remove **<** from the beginning of the line instead of making a copy of the string?

2023-01-01 11:23 UTC, oleg-derevenetz commented
> On top of this I have a question: where and when this script should be executed?

I believe it's a purely service script that should be executed by hand when the next release being prepared, after the `changelog.txt` was updated.

2023-01-01 11:28 UTC, oleg-derevenetz commented on script/tools/changelog_update_appdata.py
> +    </release>\n'''[1:]
Hi @ihhub the first symbol here is a newline, not `<` :) I believe this is done for the sake of code formatting. However I have an impression that if this script will be used on Windows, there will be in fact two symbols at the beginning - `\r\n` :) Probably it's better to use `strip()` instead.

2023-01-01 13:13 UTC, Laserlicht commented on script/tools/changelog_update_appdata.py
> +#!/usr/bin/env python3
The script is only running under python3 right now. The question is whether it is really worth the effort to support python2 (it has been out of support for three years now).

2023-01-01 13:18 UTC, oleg-derevenetz commented on script/tools/changelog_update_appdata.py
> +#!/usr/bin/env python3
As far as I understand, this script is not intended to be run by end user in any way. It's just an utility script for internal use. I believe that there is no need to support the python 2, because it will be run mostly by @ihhub in the controlled environment, right?

2023-01-01 13:20 UTC, ihhub commented on script/tools/changelog_update_appdata.py
> +#!/usr/bin/env python3
This is correct.

2023-01-01 13:25 UTC, Laserlicht commented on script/tools/changelog_update_appdata.py
> +#!/usr/bin/env python3
Yes, it is currently missing from all scripts. Maybe this should be corrected in a separate commit for all?

2023-01-01 13:26 UTC, oleg-derevenetz commented on script/tools/changelog_update_appdata.py
> +    </release>\n'''.lstrip("\r\n")
Just `lstrip()` (without parameters) will be enough, because it will strip any whitespace characters, including newlines, carriage returns, spaces, tabs, etc, etc.

2023-01-01 13:26 UTC, Laserlicht commented on script/tools/changelog_update_appdata.py
> +    </release>\n'''[1:]
Right. Is only for styling. Have now converted it to `lstrip`.

2023-01-01 13:29 UTC, Laserlicht commented on script/tools/changelog_update_appdata.py
> +    </release>\n'''.lstrip("\r\n")
@oleg-derevenetz Not really. It breaks the format. The indentation before `<release>` is lost.

2023-01-01 13:30 UTC, oleg-derevenetz commented on script/tools/changelog_update_appdata.py
> +    </release>\n'''.lstrip("\r\n")
@Laserlicht Ah yes, the indentation, right.

2023-01-01 13:30 UTC, Laserlicht commented
> I believe it's a purely service script that should be executed by hand when the next release being prepared, after the `changelog.txt` was updated.

Exactly. I don't think it's really worth building that into the CI/CD here.

2023-01-01 14:03 UTC, oleg-derevenetz commented on script/tools/changelog_update_appdata.py
> +#!/usr/bin/env python3
If we want to have copyright headers in all scripts, we should prepare the infrastructure first to verify their presence. The difference of scripts is that they should have a shebang in the first line. I propose to address this later in separate PR.

2023-01-02 19:47 UTC, oleg-derevenetz approved these changes

2023-01-03 15:43 UTC, merged

2023-01-03 15:43 UTC, ihhub commented
@Laserlicht , a bunch of thanks for this change!