Render spell effect animation so as not to cover the front troops. Battlefield.
ihhub/fheroes2 pull request #6442
Opened 2023-01-01 17:08 UTC by Districh-ru

This PR makes the spell that effect is only rendered above the creature it is applied and creatures on the same row or higher (farther), while not overlapping the front (closer) creatures.
![fheroes2 2023-01-01 19-40-05-667](https://user-images.githubusercontent.com/113276641/210178576-9dbb20f6-3959-4f29-80a9-efbe2804062f.gif) ![fheroes2 2023-01-01 19-36-55-469](https://user-images.githubusercontent.com/113276641/210178579-bd0dac30-68ee-4ae9-b1b0-90f04ce341af.gif)

To implement this the 'overlaySprite' structure was added to 'Unit' class. And this structure is used in `RedrawArmies()` function.

<details><summary>The description of the issue.</summary>
Here's an issue I've found:
Red fog is drawn over troops standing in front of the target.

![Wave](https://user-images.githubusercontent.com/55348946/206904320-e33b589a-5f2a-4e97-9ca4-8ddc883a400b.png)

In the OG:
![image](https://user-images.githubusercontent.com/55348946/206904176-236d6458-004f-416f-9a97-ac1f78679b54.png)

</details>

_Issue originally posted by @Branikolog in https://github.com/ihhub/fheroes2/issues/6344#issuecomment-1345546298_

2023-01-01 17:21 UTC, Districh-ru commented
Hi, @ihhub! I don't think that my implementation of this idea is good enough. Could you please check it in your spare time.
Also the `RedrawArmies()` function has duplicate code (and I added new ones). I'll want to rewrite it soon to reduce duplication and to fix a couple of issues.

2023-01-05 15:21 UTC, ihhub commented on src/fheroes2/battle/battle_troop.h
> +#include "image.h"
Mixing logic and UI is not the best approach. I would restrain from doing such. As an alternative we can have a map of monsters IDs vs their overlay images which is stored either in `Battle::Interface` class. What do you think?

2023-01-05 15:22 UTC, ihhub commented on src/fheroes2/battle/battle_troop.h
> +        bool reflect = false;
Please use C++11 initialization list:
```cpp
const fheroes2::Sprite * overlaySprite{ nullptr };
fheroes2::Point position; <-- no need as default constructor sets zeroes
bool reflect{ false };
```

2023-01-05 15:24 UTC, ihhub commented on src/fheroes2/battle/battle_troop.h
> +        void ResetOverlaySprite();
If we move to usage of a map then most of these methods disappear as during rendering we will have the direct access to all structures.

2023-01-05 15:52 UTC, Districh-ru commented on src/fheroes2/battle/battle_troop.h
> +#include "image.h"
Hi, @ihhub, thanks for the advice, I'll try this approach soon.

2023-01-14 17:15 UTC, Districh-ru commented on src/fheroes2/battle/battle_troop.h
> +#include "image.h"
Hi @ihhub, I've tried to implement the overlay sprite for spells in `Battle::Interface`.
Could you please check my implementation when you have time.

2023-01-16 04:38 UTC, ihhub requested changes
Hi @Districh-ru , I put several comments in this pull request. Could you please take a look when you have time?

2023-01-16 04:38 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +            }
Let's add this part just in case:
```cpp
if ( frame == maxFrame ) {
    _unitOverlaySprite.erase( overlaySpriteBegin, overlaySpriteEnd );
}
else {
    assert( frame < maxFrame );
}
```
This is to make sure that we don't screw up logic above.

The same comment for lines 5893-5896.

2023-01-16 04:38 UTC, ihhub commented on src/fheroes2/battle/battle_interface.h
> +        bool reflect{ false };
Can we please name it like `isReflectedImage`? In this case it would be obvious what this member is for.

2023-01-16 04:38 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +                std::vector<Battle::OverlaySprite>::iterator overlaySprite = overlaySpriteBegin;
Can we please name this variable differently to differ it from **overlaySprite** of `OverlaySprite` structure? Something like `overlaySpriteIter` would work.

2023-01-16 04:38 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +                _unitOverlaySprite.back().overlaySprite = &fheroes2::AGG::GetICN( icn, frame );
This is very dangerous to do. We have a code to even clear some images during runtime. What if we store **icnId** and **icnIndex** in the structure and then call `fheroes2::AGG::GetICN()` at the time we need to blit an image?

2023-01-16 14:35 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +                                    troopOverlaySpriteBeforeWall.emplace_back( &overlaySprite );
Hi @ihhub, many thanks for the review and suggestions.
Here I made a mistake (forgot to rename after the copy-paste), you are right it should be `troopOverlaySpriteAfterWall`.

2023-01-16 14:41 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +                fheroes2::Blit( *overlaySprite->overlaySprite, _mainSurface, overlaySprite->position.x, overlaySprite->position.y, overlaySprite->reflect );
I've added an assertion here and in the similar code.

2023-01-16 14:46 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.h
> +    struct OverlaySprite
For now it is used only for rendering spell effects for units, so the name `UnitSpellEffectImage` will be OK. If we plan to use it for some other effects, maybe in expansion, we will rename it then.

2023-01-16 14:55 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +            }
The loop can go further than `maxFrame` when we have a long wince or death animation, like for Bone Dragons or Phoenixes. So if I put an assertion here, we will get it in such 'legal' animations. :)

2023-01-16 16:33 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +                _unitOverlaySprite.back().overlaySprite = &fheroes2::AGG::GetICN( icn, frame );
Hi @ihhub, I've tried to implement like you suggested. 
Could you please check the code in your spare time.

2023-01-17 15:06 UTC, ihhub requested changes
Hi @Districh-ru , I put few more comments here. Would you mind check them and see if they make sense?

2023-01-17 15:06 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +                                if ( overlaySprite.unitId == deadUnits[i]->GetUID() && overlaySprite.icnId != ICN::UNKNOWN ) {
Is there a case when **icnId** is going to be **ICN::UNKNOWN**? I see no place where we possibly set this value or create an instance of `UnitSpellEffectImage` structure using default constructor. If there is no such a case please remove all checks but add an assertion before calling **fheroes2::AGG::GetICN()** to make sure that **icnId** is not **ICN::UNKNOWN**.

2023-01-17 15:06 UTC, ihhub commented on src/fheroes2/battle/battle_interface.h
> +        std::vector<UnitSpellEffectImage> _unitOverlaySprite;
Since this is an array of `UnitSpellEffectImage` should we name this member as `_unitSpellEffectImages` / `_unitSpellEffectInfos` ?

2023-01-17 15:06 UTC, ihhub commented on src/fheroes2/battle/battle_interface.h
> +    struct UnitSpellEffectImage
How about name it as **UnitSpellEffectInfo**? This structure is not exactly an image but a bucket of data for rendering an image. What do you think?

2023-01-17 15:50 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.h
> +    struct UnitSpellEffectImage
Hi @ihhub, yes, with the current structure contents this name is better. 👍 It will be like `PopupDamageInfo`. But near to `UnitSpellEffectInfo` we have `OpponentSprite` class, which does not contain a sprite image, but has info. :) So maybe it should be also renamed to something like **OpponentSpriteInfo** or **OpponentImageInfo**? If you think so, I can rename this class in this PR.

2023-01-17 15:54 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +                        ( *overlaySpriteIter ).icnIndex = frame;
Yeah, I'm not looking for easy ways :)))

2023-01-17 16:09 UTC, ihhub commented on src/fheroes2/battle/battle_interface.h
> +    struct UnitSpellEffectImage
Let's do old code cleanup in a separate pull request. I have no objections of doing so but it's better to keep this pull request as small as possible for the future track of changes.

2023-01-17 16:10 UTC, ihhub approved these changes

2023-01-17 16:15 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.h
> +    struct UnitSpellEffectImage
Sure!

2023-01-17 19:54 UTC, oleg-derevenetz requested changes
Hi @Districh-ru I just left one suggestion (accompanied by a question), please take a look when you have time.

2023-01-17 19:54 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +    _unitSpellEffectInfos.reserve( targets.size() );
According to the logic below, there can already be some elements in the `_unitSpellEffectInfos`, right? (BTW, where will they come from there?) If yes, then we should call `_unitSpellEffectInfos.reserve( _unitSpellEffectInfos.size() + targets.size() );` because we need to take into account the already existing elements.

2023-01-18 19:18 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +    _unitSpellEffectInfos.reserve( targets.size() );
> I made this implementation for possible future use if we decide (for example in the expansion) to display some sprites above the troops for some time.

I have no objections against this, but then please add the corresponding TODO comment to the declaration of `_unitSpellEffectInfos` in the `battle_interface.h` describing that while we currently don't need to persist the `UnitSpellEffectInfo`s, this may be needed in the future to [... describe why ...]. Also maybe we can add assertions at the beginning or at the end of methods where `_unitSpellEffectInfos` is currently used (`RedrawTargetsWithFrameAnimation()` and `RedrawTroopWithFrameAnimation()`?) to verify that `_unitSpellEffectInfos` is empty at the beginning and remains empty at the end (or maybe just at the beginning or at the end - at your discretion).  When there is a need to display some permanent effects, we will remove them, but in the meantime it's good to make sure that the logic works correctly.

2023-01-19 13:08 UTC, Branikolog approved these changes
Excellent!

2023-01-19 18:15 UTC, oleg-derevenetz approved these changes

2023-01-19 23:49 UTC, merged

2023-01-19 23:50 UTC, ihhub commented
@Districh-ru , huge thanks for improving this part of the game!