PS Vita fixes and gamepad mapping improvements
ihhub/fheroes2 pull request #6478
Opened 2023-01-10 23:44 UTC by Northfear

Bunch of fixes related to PS Vita
- Disabled rear touchpad
- Added gamepad mapping for cursor speedup
- Fixed fullscreen/windowed toggle in display options

2023-01-16 04:50 UTC, ihhub requested changes
Hi @Northfear , I added few comments here. Would you mind to take a look when you have time?

2023-01-16 04:50 UTC, ihhub commented on src/engine/localevent.cpp
> +        else if ( button.button == SDL_CONTROLLER_BUTTON_DPAD_RIGHT ) {
Are these changes only Vita specific? Would they affect Switch?

2023-01-16 04:50 UTC, ihhub commented on src/engine/screen.cpp
> +        void _calculateScreenScaling( int32_t width_, int32_t height_, bool isFullScreen )
Please make all input arguments as `const`.

2023-01-16 04:50 UTC, ihhub commented on src/engine/screen.cpp
> +            if ( width_ != VITA_FULLSCREEN_WIDTH || height_ != VITA_FULLSCREEN_HEIGHT ) {
Let's do the opposite logic to remove extra text indentation of the code:
```cpp
 if ( width_ == VITA_FULLSCREEN_WIDTH && height_ == VITA_FULLSCREEN_HEIGHT ) {
    // Nothing to do more.
    return;
}

if ( !isFullScreen ) {
    // Center game area.
    _destRect.x = ( VITA_FULLSCREEN_WIDTH - width_ ) / 2;
    _destRect.y = ( VITA_FULLSCREEN_HEIGHT - height_ ) / 2;
    return;
}

...
the rest of the code
```

2023-01-16 04:50 UTC, ihhub commented on src/engine/screen.cpp
> +                    vita2d_texture_set_filters( _texBuffer, isNearestScaling() ? SCE_GXM_TEXTURE_FILTER_POINT : SCE_GXM_TEXTURE_FILTER_LINEAR,
Can we create a separate variable for:
```cpp
isNearestScaling() ? SCE_GXM_TEXTURE_FILTER_POINT : SCE_GXM_TEXTURE_FILTER_LINEAR
```
and use it within **vita2d_texture_set_filters** call to reduce code duplication and possible bugs?

2023-01-16 04:50 UTC, ihhub commented on src/engine/screen.cpp
> +        void toggleFullScreen() override
In this case should we modify `bool System::isHandheldDevice()` to set fullscreen by default for Vita and Switch?

2023-01-16 04:50 UTC, ihhub commented on src/engine/localevent.cpp
> +        if ( button.button == SDL_CONTROLLER_BUTTON_RIGHTSHOULDER ) {
Please combine these else and if statements.

2023-01-20 21:20 UTC, Northfear commented on src/engine/localevent.cpp
> +        else if ( button.button == SDL_CONTROLLER_BUTTON_DPAD_RIGHT ) {
Yeah, should affect anything with a gamepad. But those changes are pretty good IMO. DPad buttons were free anyway and "cursor speedup" is really useful for thumbstick cursor control.

2023-01-20 21:31 UTC, Northfear commented on src/engine/screen.cpp
> +        void toggleFullScreen() override
Hard to say. I like the "sharp" look of unscaled image. Even if it's not fullscreen.
Most people prefer fullscreen image tho, so yeah. Defaulting to it is probably a good idea

2023-01-25 11:10 UTC, ihhub commented on src/engine/screen.cpp
> +        void toggleFullScreen() override
What's the resolution in fullscreen mode?

2023-01-25 11:34 UTC, Northfear commented on src/engine/screen.cpp
> +        void toggleFullScreen() override
The resolution is always 960x544. "Fullscreen" toggle just decides whether the game screen is centered or stretched.

2023-01-30 10:30 UTC, zarkone commented
tested on vita, works great for me :+1:

2023-01-30 13:14 UTC, ihhub approved these changes

2023-01-30 22:01 UTC, oleg-derevenetz reviewed
LGTM, just one single-click suggestion. BTW, since key mapping changes in this PR may affect Switch, maybe it's worth to update the `docs/README_switch.md` regarding controls. Maybe someone who uses Switch will want to do this as a separate PR.

2023-01-31 09:46 UTC, oleg-derevenetz approved these changes

2023-01-31 13:56 UTC, merged

2023-01-31 13:56 UTC, ihhub commented
@Northfear , thank you so much for these changes!