Rework the battle pathfinding
ihhub/fheroes2 pull request #6479
Opened 2023-01-11 00:15 UTC by oleg-derevenetz

fix #6291

<details>
<summary>Issue from #6291</summary>

https://user-images.githubusercontent.com/32623900/211687971-377623be-02d0-46c5-a5a3-38b389674a9c.mp4

https://user-images.githubusercontent.com/32623900/211688066-6eca86c3-2d1d-4216-a71a-06ff6f6c9b32.mp4
</details>

<details>
<summary>Famous issue with wide units retreating one step back diagonally</summary>

https://user-images.githubusercontent.com/32623900/211688089-e640f2db-2d39-4f44-b886-425062ddc225.mp4

https://user-images.githubusercontent.com/32623900/211688110-7712c9a2-1cfc-41b3-b250-5acad30c30cd.mp4
</details>

2023-01-13 23:28 UTC, oleg-derevenetz commented
Also rewrote some `Battle::Board` methods, especially `Battle::Board::GetDistanceIndexes()`, my eyes were literally bleeding when I looked at the original implementation. There is a purely mathematical solution for this case.

2023-01-14 08:06 UTC, Branikolog commented
Hi, @oleg-derevenetz !
I've tested this PR and everything seems to work good. 👍 
The only thing I found and I'm concerning... It's probably not even related to current PR. You can consider this as offtop or side question...
Standing in front of towers for wide and small creatures works slightly different:

https://user-images.githubusercontent.com/55348946/212462561-cf6b99b6-2de3-408e-a129-7581b931edb9.mp4

I mean, small creature can pass through the wall near the bridge, while wide one cannot. How do you think, do we need to make passability here consistent for both types of creatures, or wide creatures should suffer a penalty for being so big?

2023-01-14 08:46 UTC, oleg-derevenetz commented
Hi @Branikolog Cavalry moves "from moat to moat" here (its tail cell is still in the moat after the end of the movement) and therefore cannot move further, while Paladins move from moat to the dry land and therefore is not limited in their subsequent movement. I believe everything is consistent here.

2023-01-14 08:52 UTC, Branikolog approved these changes

2023-01-14 09:02 UTC, oleg-derevenetz commented
@Branikolog

I mean, currently wide units cannot from one moat cell to a different one "with their tail in a moat":

https://user-images.githubusercontent.com/32623900/212464371-d76741bb-5050-46fa-92b3-7fcf65eef513.mp4

In theory, Unicorns could just move here forward down diagonally, but they are forced to completely get out of the moat first, and I think it's the right thing. The same logic is applicable to your case: wide units could move in the forward direction through the moat cell they're already occupied at the beginning of the turn, but they still couldn't move through a different moat cell either through their head or tail.

2023-01-14 09:53 UTC, Branikolog commented
@oleg-derevenetz 
That's a reasonable point. I don't refuse the current logic. The fact, that champions are stuck at that place in moat is absolutely expected for me, considering native pathfinding logic. I was concerned only by the fact, we have two creature types, that behave different in the same condition: when they step in moat in front of the tower. So this is going to be some sort of penalty wide creatures have. Like they cannot pass in some thin places.

2023-01-14 09:55 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz and @Branikolog,

> I mean, small creature can pass through the wall near the bridge, while wide one cannot. How do you think, do we need to make passability here consistent for both types of creatures, or wide creatures should suffer a penalty for being so big?

> @oleg-derevenetz That's a reasonable point. I don't refuse the current logic. The fact, that champions are stuck at that place in moat is absolutely expected for me, considering native pathfinding logic. I was concerned only by the fact, we have two creature types, that behave different in the same condition: when they step in moat in front of the tower. So this is going to be some sort of penalty wide creatures have. Like they cannot pass in some thin places.

As explained above, the hex between the two towers is directly accessible to a one-hex creature, while a two-hex creature must pass through another hex in the moat to move, it is normal for it to suffer the penalty of entering another moat hex.
Now, the AI should be taught not to place a two-hex creature in such a position. :)

2023-01-14 10:47 UTC, oleg-derevenetz commented
> Now, the AI should be taught not to place a two-hex creature in such a position. :)

AI could deliberately put units closer to the walls when all walls are still in place, but target cells will be 7, 28, 49, 72, 95 (see cell numbers in my video below), i.e. cells located opposite the breaking walls or castle gates, not the towers.

Also AI knows that it couldn't attack a unit on the other side of the moat right after the movement, so it will not place a wide unit in a cell near a tower in order to perform a cross-moat attack. And it knows that there is a big penalty for further cross-moat movements, so it shouldn't place a wide unit in such a cell just to move inside the castle.

The only option when it can place a wide unit here is if he needs to attack the enemy unit on the attacker's side of the moat - in this case a wide unit will be able to attack, because wide units are able to attack with the part of them that is not in the moat, in this case this will be the tail cell:

https://user-images.githubusercontent.com/32623900/212468014-46be3f99-bb0f-4728-9e26-018de8d3385a.mp4

In this video Cavalry is not able to perform a cross-moat attack against Unicorns, but it is able to attack Phoenixes to the left of the moat because Phoenixes will be attacked from the Cavalry's tail cell located on dry land.

2023-01-15 06:13 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left multiple suggestions in this pull request. Can you please take a look once you have time?

2023-01-15 06:13 UTC, ihhub commented on src/fheroes2/battle/battle_pathfinding.h
> +        Indexes getAllAvailableMoves() const;
Can we please add an empty line after each method declaration to improve readability a bit so it would be obvious which comment belongs to which method?

2023-01-15 08:30 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_pathfinding.cpp
> +        return result;
@ihhub I'm not sure that in your case `reserve()` will be called by the constructor and there will be no unnecessary reallocations.

2023-01-15 08:46 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_board.cpp
> +    const int32_t centerQ = centerX - ( centerY + centerY % 2 ) / 2;
For pogrommers who haven't attended elementary school? :)

2023-01-15 09:46 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

> > Now, the AI should be taught not to place a two-hex creature in such a position. :)
> 
> AI could deliberately put units closer to the walls when all walls are still in place, but target cells will be 7, 28, 49, 72, 95 (see cell numbers in my video below), i.e. cells located opposite the breaking walls or castle gates, not the towers.
> 
> Also AI knows that it couldn't attack a unit on the other side of the moat right after the movement, so it will not place a wide unit in a cell near a tower in order to perform a cross-moat attack. And it knows that there is a big penalty for further cross-moat movements, so it shouldn't place a wide unit in such a cell just to move inside the castle.
> 
> The only option when it can place a wide unit here is if it needs to attack the enemy unit on the attacker's side of the moat - in this case a wide unit will be able to attack, because wide units are able to attack with the part of them that is not in the moat, in this case this will be the tail cell:
> 
>  [fheroes2.engine.version_.1.0.0.2023-01-14.13-35-33.mp4 ](https://user-images.githubusercontent.com/32623900/212468014-46be3f99-bb0f-4728-9e26-018de8d3385a.mp4)
> 
> In this video Cavalry is not able to perform a cross-moat attack against Unicorns, but it is able to attack Phoenixes to the left of the moat because Phoenixes will be attacked from the Cavalry's tail cell located on dry land.

In the example, moving the cavalries into the moat to attack the phoenixes is not a good move.
The positioning does not bring any benefit, on the contrary the cavalries suffer a penalty in defense and can be attacked by the unicorns.
They will also have to move to another moat hex to be able to enter the castle.
So there is no benefit to be gained by positioning the cavalries at this position.
There are enough other locations available to attack the phoenixes without entering the moat, while allowing reachable locations for the other close combat attacking units.
So, unless this is the last possible location to attack an opposing unit, there is no good reason to position the cavalries at this location in the moat.
The only useful reason would be to block an opposing unit's path by preventing it from moving to that position in the moat, or to attack an enemy unit in the castle enclosure (at the location of a broken wall) next turn.

2023-01-15 09:54 UTC, oleg-derevenetz commented
> The positioning does not bring any benefit, on the contrary the cavalries suffer a penalty in defense and can be attacked by the unicorns.

No one is arguing :) But currently this AI move is theoretically possible.

2023-01-15 10:02 UTC, LeHerosInconnu commented
@oleg-derevenetz,

> > The positioning does not bring any benefit, on the contrary the cavalries suffer a penalty in defense and can be attacked by the unicorns.
> 
> No one is arguing :) But currently this AI move is theoretically possible.

This is my point, IA should only consider this positioning as a last resort, or as a tactical placement. :)

2023-01-15 10:04 UTC, Branikolog commented
Hi, @LeHerosInconnu 

> The only useful reason would be to block an opposing unit's path by preventing it from moving to that position in the moat, or to attack an enemy unit in the castle enclosure (at the location of a broken wall) next turn.

Which is actually a good step. Cavalry will beat unicorns defending hole in castle wall on the next turn and give opportunity to paladins to enter castle right after cavalry attack unicorns..

2023-01-15 10:19 UTC, LeHerosInconnu commented
Hello @Branikolog,

> Hi, @LeHerosInconnu
> 
> > The only useful reason would be to block an opposing unit's path by preventing it from moving to that position in the moat, or to attack an enemy unit in the castle enclosure (at the location of a broken wall) next turn.
> 
> Which is actually a good step. Cavalry will beat unicorns defending hole in castle wall on the next turn and give opportunity to paladins to enter castle right after cavalry attack unicorns. :)

In the example, I would see it more this way:
The ten unicorns should decimate the remaining two cavalries, or, if there are any left, the next turn the phoenixes should decimate them by attacking the paladins horizontally and also hitting the remaining cavalries. :)

2023-01-15 10:24 UTC, Branikolog commented
@LeHerosInconnu 

> In the example, I would see it more this way:
> The ten unicorns should decimate the remaining two cavalries, or, if there are any left, the next turn the phoenixes should decimate them by attacking the paladins horizontally and also hitting the remaining cavalries. :)

Sure. I was keeping in mind other creature quantity for my example. :)
Also, such positioning could be used to make phoenixes "friendly fire" troop, standing on 6th cell during retaliation in particular circumstances.

2023-01-15 10:32 UTC, LeHerosInconnu commented
@Branikolog.

> @LeHerosInconnu
> 
> > In the example, I would see it more this way:
> > The ten unicorns should decimate the remaining two cavalries, or, if there are any left, the next turn the phoenixes should decimate them by attacking the paladins horizontally and also hitting the remaining cavalries. :)
> 
> Sure. I was keeping in mind other creature quantity for my example. :)
> Also, such positioning could be used to make phoenixes "friendly fire" troop, standing on 6th cell during retaliation in particular circumstances.

The AI should be smart enough to avoid "friendly fire". :rofl:

2023-01-15 10:51 UTC, oleg-derevenetz commented
> The AI should be smart enough to avoid "friendly fire". 🤣

It tries to avoid if if possible, but if it is not possible, then it will attack anyway.

2023-01-15 11:05 UTC, LeHerosInconnu commented
@oleg-derevenetz.

> > The AI should be smart enough to avoid "friendly fire". :rofl:
> 
> It tries to avoid it if possible, but if it is not possible, then it will attack anyway.

Okay, I see.
But that's not necessarily a good thing.
For example, sometimes it can be more interesting to preserve your troops (instead of an attack that doesn't really bring important damage) to allow the use of an attack spell the next turn (because a troop hasn't been decimated and is still present on the battlefield).

2023-01-15 15:29 UTC, ihhub commented on src/fheroes2/battle/battle_pathfinding.cpp
> +        return result;
Hmm... that's a valid point.

2023-01-16 13:59 UTC, ihhub approved these changes

2023-01-16 14:01 UTC, merged