Combat, Adding tooltip damage info for single target attack spells
ihhub/fheroes2 pull request #6493
Opened 2023-01-14 23:45 UTC by kfishster

As mentioned in #1625, the super helpful damage info tooltip that shows the range of damage when attacking the enemy troop does not show anything when using spells. When using a single-target damage spell such as a Lightning Bolt, Arrow, or Coldray, the spell in the magic book shows you the exact damage it would deal, but when hovering over an enemy troop, you have to cancel the spell, check the troop's health to calculate how many troops will perish, and then go back to using the spell again. Additionally, the spellbook does not show the spell adjustments you might encounter when targeting special troops, for example when using a cold ray on an Air Elemental (cold spells have 2x damage on air type monsters).

This damage tooltip, however, will ignore defending hero's artifacts - if the defending hero has an artifact reducing the damage of certain spells (such as the Ice Heart to reduce cold spell damage by half), the tooltip should not show that, as that is not known to the attacking hero.

_Before:_
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/4021245/212501907-8b302472-ee07-48db-ab97-7436bd7af570.png">

_After:_
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/4021245/212501813-57362494-8217-4954-bcb4-7b570b6ec843.png">

Interesting open question - **should magic resistance be mentioned in the tooltip**? Spell will not do any damage 25% of the time on dwarves.

2023-01-15 10:53 UTC, LeHerosInconnu commented
Hello @kfishster,

> This damage tooltip, however, will ignore defending hero's artifacts - if the defending hero has an artifact reducing the damage of certain spells (such as the Ice Heart to reduce cold spell damage by half), the tooltip should not show that, as that is not known to the attacking hero.

If this is applied it should only be for the first attack with the spell, because by the second attack with the spell (or the same type of spell, e.g. Lightning Bolt and Chain Lightning) the player has noticed that the damage of the spell is reduced.
And how to deal with this for another combat against the same opposing hero knowing that he has artifacts that reduce the damage of the same spells?
Maybe it would be easier to display the damage taking into account the artifacts, or whatever, of the opposing hero.
In my case, it would not bother me.

> Interesting open question - should magic resistance be mentioned in the tooltip? Spell will not do any damage 25% of the time on dwarves.

Both ways are fine for me.
The player will quickly learn that dwarves have a percentage chance of resisting bad spells (and this is indicated in the creature's info window).

2023-01-15 23:21 UTC, kfishster commented
@LeHerosInconnu thanks for the feedback. The way I think about this is that there is _public info_ and _private info_ when it comes to any combat scenario. The _public info_ is the kind of thing you can see at any point in combat, Attack/Defense skill, troop size, troop skills, etc. All these things are used to calculate your potential attack damage from a troop, and in the case of this PR, the total spell damage. The _private info_ is the "face down cards" that you or the opposing player will have, this is meant to be hidden, and if you make some sort of move that will uncover this information, you have to keep track of it yourself, it shouldn't be available in the same way as the _public info_. This also means that if you missed any of the clues or the _private info_ changed, you should not be basing any of the tooltips on that info. For example, if the opposing hero battles you the first time with an artifact that reduces damage, and then you face them again, there is no way for you to know whether they still have that artifact or not, so making that assumption on the basis of prior information would be incorrect.

So in this case, I would prefer to keep the behavior as implemented, codifying the _private info_ into the damage tooltip would take away a part of the Heroes experience.

2023-01-16 08:03 UTC, LeHerosInconnu commented
Hello @kfishster,

> For example, if the opposing hero battles you the first time with an artifact that reduces damage, and then you face them again, there is no way for you to know whether they still have that artifact or not, so making that assumption on the basis of prior information would be incorrect.

If the two combats are consecutive and take place in the same player's turn, or if the opposing hero is visible on the adventure map and has not encountered any other hero, it results that the opposing hero still possesses the same artifact, thus with the same results.

> So in this case, I would prefer to keep the behavior as implemented, codifying the _private info_ into the damage tooltip would take away a part of the Heroes experience.

I see your point, the problem is that incorrect information is displayed when it is known, and players will report this as a bug.
I am okay with doing it this way for now, and let's see how it's received. :)

2023-01-16 19:52 UTC, kfishster commented
@LeHerosInconnu I see your point, but I'd still argue that information should not be codified. In the same example, if I am about to attack an opposing hero and I see their army as "pack of wolves", "horde of peasants", if I attack, lose the battle, and am about to attack with a different hero, the game will still show me the "pack of wolves", "horde of peasants" display, not the exact numbers, although, as a player, I know the exact troop numbers.

> I see your point, the problem is that incorrect information is displayed when it is known, and players will report this as a bug.

Yea, this is a valid point. I was trying to find a similar example with attacking, where an enemy hero might have an artifact that reduces the damage they receive, but I don't believe it exists in HoMM2. Might be worth adding some documentation to the wiki on what this tooltip takes into account, or something of the sort.

2023-01-17 15:29 UTC, ihhub requested changes
Hi @kfishster , I put several comments in this pull request. Could you please take a look at them?

2023-01-17 15:29 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +void Battle::PopupDamageInfo::SetInfo( const Cell * cell, const Unit * attacker, const Unit * defender, const Spell * spell )
Would it be cleaner to just create a separate method for setting up spell information? I can see that the existing method is complex and we are adding even more logic on top of this. The existing method then could be renamed into `SetPhysicalDamageInfo()`.

2023-01-17 15:29 UTC, ihhub commented on src/fheroes2/battle/battle_troop.cpp
> +uint32_t Battle::Unit::CalculateDamage( const Spell * spell, uint32_t spoint, const HeroBase * hero, uint32_t target_damage, bool ignoreDefendingHero ) const
There is no reason to change from a reference to pointer. Please revert this change.

2023-01-17 15:29 UTC, ihhub commented on src/fheroes2/battle/battle_troop.h
> +        uint32_t CalculateDamage( const Spell *, uint32_t, const HeroBase *, uint32_t, bool ) const;
As per our coding style please add all input argument variables. The old code was written in not a very logical way.

2023-01-17 15:29 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    assert( ( _cell != nullptr && _defender != nullptr && _attacker != nullptr ) );
Could you please explain the reason why we need to change this line? It seems to me exactly the same as well as extra parenthesis was added.

2023-01-17 15:29 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( _spell != nullptr && _spell->isSingleTarget() && _spell->isDamage() ) {
We should check spell conditions before setting it as in the proposed new method like `SetSpellDamageInfo()`.

2023-01-17 15:29 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        const uint32_t spoint = hero ? hero->GetPower() : DEFAULT_SPELL_DURATION;
Please name the variable according to our coding standard using `camelCase`. A name like **spellCost** or **spellPoints** would be much easier to read.

2023-01-17 15:29 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        uint32_t spellDmg = _defender->CalculateDamage( _spell, spoint, hero, 0 /* targetInfo damage */, true /* ignore defending hero */ );
This variable can be **const**.

2023-01-17 15:29 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        if ( cell && _currentUnit && humanturn_spell.isSingleTarget() && humanturn_spell.isDamage() ) {
I suggest to add spell checks in the proposed `SetSpellDamageInfo()` method to make the code cleaner.

2023-01-17 15:29 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +            const Unit * b_enemy = cell->GetUnit();
Please use camelCase variable naming. A name like **defenderUnit** is much better to read and understand.

2023-01-18 10:42 UTC, Branikolog commented
Hi, @kfishster !
It's a useful addition to the game UI! Showing how much creatures would be decimated after spell cast is definitely the information everyone would like to see during battles.
I'm ok with proposed implementation (without taking into consideration opposite hero's spell reducing artifacts), but what about golems, which has native -50% damage ability for some spells? I think, for golems in particular, info tooltip should display reduced damage, since this is permanent reduction.

2023-01-19 07:17 UTC, kfishster commented on src/fheroes2/battle/battle_interface.cpp
> +    assert( ( _cell != nullptr && _defender != nullptr && _attacker != nullptr ) );
Artifact of refactoring, reverting this line change!

2023-01-19 08:16 UTC, kfishster commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( _spell != nullptr && _spell->isSingleTarget() && _spell->isDamage() ) {
Refactored this logic to set the damage via separate methods for normal attack and for spell attack

2023-01-19 08:17 UTC, kfishster commented on src/fheroes2/battle/battle_interface.cpp
> +void Battle::PopupDamageInfo::SetInfo( const Cell * cell, const Unit * attacker, const Unit * defender, const Spell * spell )
Refactored this logic to have a separate `SetInfo()` method for the two attack cases

2023-01-19 08:45 UTC, kfishster commented
> I'm ok with proposed implementation (without taking into consideration opposite hero's spell reducing artifacts), but what about golems, which has native -50% damage ability for some spells? I think, for golems in particular, info tooltip should display reduced damage, since this is permanent reduction.

@Branikolog, the current implementation accounts for the known unit modifiers such as golems taking half the damage or air elementals taking twice as much damage when hit with a cold spell. This reuses the same logic that calculates spell damage, but the only part that it ignores is the defending hero's artifact effects on spell damage.

2023-01-22 03:46 UTC, ihhub requested changes
Hi @kfishster , I left several more comments in this pull request. Could you please check them in your spare time?

2023-01-22 03:46 UTC, ihhub commented on src/fheroes2/battle/battle_troop.cpp
> +uint32_t Battle::Unit::CalculateDamage( const Spell & spell, uint32_t spoint, const HeroBase * hero, uint32_t target_damage, bool ignoreDefendingHero ) const
Please use **camelCase** style of variable naming.

2023-01-22 03:46 UTC, ihhub commented on src/fheroes2/battle/battle_troop.cpp
> +        bool useDefendingHeroArts = defendingHero && !ignoreDefendingHero;
This variable can be **const**.

2023-01-22 03:46 UTC, ihhub commented on src/fheroes2/battle/battle_troop.cpp
> +uint32_t Battle::Unit::CalculateDamage( const Spell & spell, uint32_t spoint, const HeroBase * hero, uint32_t target_damage, bool ignoreDefendingHero ) const
**CalculateDamage** is a very broad name to be used. For any reader it means that this method calculates damage while attacking which is not the case here. Something like `calculateSpellDamage` will be an accurate name for this method. What do you think?

2023-01-22 03:46 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( !( spell.isSingleTarget() && spell.isDamage() ) ) {
The opposite condition would be easier to read because **!( ... )** is usually ignored while fast reading:
```cpp
if ( !spell.isSingleTarget() || !spell.isDamage() ) {
```

2023-01-22 03:46 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    // if defender unit immune to magic, do not show the tooltip
Can we please start this comment from a capital letter while we do in other comments? This is to keep the consistency in the code.

2023-01-22 03:46 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    StringReplace( str, "%{max}", (int)_maxDamage );
Please do not use C-style casting in C++ code. Is there a need to even do casting here? If yes please use **static_cast**.

2023-01-22 03:46 UTC, ihhub commented on src/fheroes2/battle/battle_interface.h
> +        bool SetDamageInfoBase( const Cell * cell, const Unit * attacker, const Unit * defender );
Please add an empty line after the declaration of this method to have visual separation of members and methods.

2023-01-22 03:46 UTC, ihhub commented on src/fheroes2/battle/battle_interface.h
> +        uint32_t _maxDamage;
These members must be initialized in the constructor.

2023-01-22 03:46 UTC, ihhub commented on src/fheroes2/battle/battle_troop.cpp
> +    uint32_t dmg = CalculateDamage( spell, spoint, hero, target.damage, false /* ignore defending hero */ );
This variable can be **const**.

2023-01-22 03:46 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +void Battle::PopupDamageInfo::SetAttackInfo( const Cell * cell, const Unit * attacker, const Unit * defender )
We don't use **attacker** anywhere. I believe we can simply remove this variable usage everywhere in **PopupDamageInfo** subsequently simplifying the code.

2023-01-22 21:30 UTC, kfishster commented on src/fheroes2/battle/battle_interface.cpp
> +    StringReplace( str, "%{max}", (int)_maxDamage );
This change was due to `clang-tidy` marking this as a narrow conversion (`StringReplace` requires an int, the variable is a `uint32_t`), although this could also be accomplished with an overloaded `StringReplace` that takes in a uint32_t, so I'll probably just do that

2023-01-22 21:46 UTC, kfishster commented on src/fheroes2/battle/battle_interface.cpp
> +void Battle::PopupDamageInfo::SetAttackInfo( const Cell * cell, const Unit * attacker, const Unit * defender )
I removed the attacker from the shared logic, but it still needed for determining damage in the regular combat damage calculation. Let me know if this is simpler, I can certainly refactor even more by passing in only the attacker properties we need (such as whether attacker has a bless/curse spell and damage ranges), but I'd argue that makes things a bit more complex rather than simple.

2023-01-22 21:50 UTC, kfishster commented on src/fheroes2/battle/battle_troop.cpp
> +uint32_t Battle::Unit::CalculateDamage( const Spell & spell, uint32_t spoint, const HeroBase * hero, uint32_t target_damage, bool ignoreDefendingHero ) const
Great point!

2023-01-24 13:23 UTC, ihhub requested changes
Hi @kfishster , I added just few more comments. We are almost there. Could you please take a look at them?

2023-01-24 13:23 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    StringReplace( str, "%{max}", _maxDamage );
If we want to avoid creating another overloaded version of the same function would this code work better:
```cpp
StringReplace( str, "%{min}", std::to_string( _minDamage ) );
StringReplace( str, "%{max}", std::to_string( _maxDamage ) );
```
?

We can create multiple copies of the same function but I think it might be a mess and harder to understand the code. What do you think?

2023-01-24 13:23 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( !spell.isSingleTarget() || !spell.isDamage() ) {
I see no big reason not to show for mass spells like Chain Lighting or Cold Ring. We should add such support in the future. Therefore I suggest to at least add a TODO comment explaining what is missing.

2023-01-24 13:23 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( !spell.isSingleTarget() || !spell.isDamage() ) {
These checks should go before the first if where we call **!SetDamageInfoBase()** method. This method is computational heavy.

2023-01-24 13:23 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( hero == nullptr || !SetDamageInfoBase( cell, defender ) ) {
If there a possibility that a hero who suppose to cast a spell is absent? If not we should just add an assertion for nullptr check for **hero** input argument.

2023-01-30 04:44 UTC, kfishster commented on src/fheroes2/battle/battle_interface.cpp
> +    StringReplace( str, "%{max}", _maxDamage );
Overloading the `StringReplace` might be best for consistency. There is already an `int` overloaded method in `tools.cpp`, so we would have a situation where some classes are calling into the overload (although they could be just using `to_string` to use the main method). I would suggest keeping the `uint32_t` overload for consistency. Does that align with your thinking?

2023-01-30 04:45 UTC, kfishster commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( !spell.isSingleTarget() || !spell.isDamage() ) {
Will do. The multi-target spell problem is outlined in the initial issue #1625, it's mostly a UI issue - how do we display it effectively.

2023-01-30 04:53 UTC, kfishster commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( hero == nullptr || !SetDamageInfoBase( cell, defender ) ) {
I'll add an assertion - I don't believe we can have a case where a spell is cast by a neutral troop without a hero/captain. Could you think of a scenario where that would happen?

2023-01-31 15:54 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( hero == nullptr || !SetDamageInfoBase( cell, defender ) ) {
There is no such a scenario.

2023-01-31 15:57 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    StringReplace( str, "%{max}", _maxDamage );
Overloading a function while changing **int32_t** to **uint32_t** is doing almost the same as just doing static_cast. The functions are identical and we know that we don't handle values over 2 billion so it is safe to do just casting.

But let's hear a third person's opinion to handle this properly. @oleg-derevenetz , what do you think?

2023-01-31 17:04 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +    StringReplace( str, "%{max}", _maxDamage );
Hi @ihhub I think that it is worth to just remove the overload with `int` completely and use the `std::to_string()` instead.

2023-02-02 02:17 UTC, kfishster commented on src/fheroes2/battle/battle_interface.cpp
> +    StringReplace( str, "%{max}", _maxDamage );
Thanks for the feedback. I've removed the `uint32_t` overload for `StringReplace` and just used `std::to_string` for the string interpolation. Removing the `int` overload would be much trickier - there are about 191 invocations throughout code that use it, so it is best to keep it intact.

2023-02-08 15:52 UTC, ihhub approved these changes

2023-02-11 00:22 UTC, oleg-derevenetz approved these changes

2023-02-12 13:37 UTC, merged

2023-02-12 13:38 UTC, ihhub commented
@kfishster , thank you very much for this improvement!