Code cleanup for map tile structures
ihhub/fheroes2 pull request #6502
Opened 2023-01-18 12:35 UTC by ihhub

2023-01-25 14:48 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few questions and suggestions, could you please take a look?

2023-01-25 14:48 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_objects.cpp
> +    if ( !message.empty() ) {
```suggestion
    if ( message.empty() ) {
```

?

2023-01-25 14:48 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_tiles.cpp
> -        // Random monster placeholder "MON"
I propose not to remove these comments because numbers like "67", "67", ... are not very clear.

2023-01-25 14:48 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_tiles.cpp
> +        DEBUG_LOG( DBG_GAME, DBG_WARN, "Failed to set an artifact over a random articat on tile " << tile.GetIndex() )
```suggestion
        DEBUG_LOG( DBG_GAME, DBG_WARN, "Failed to set an artifact over a random artifact on tile " << tile.GetIndex() )
```

2023-01-25 14:48 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_tiles.h
>          // TODO: move first 2 bits out of this member to keep only object type.
Aren't these comments already outdated?

2023-01-25 14:48 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_tiles.h
>          // TODO: move first 2 bits out of this member to keep only object type.
Aren't these comments already outdated?

2023-01-25 14:48 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_tiles.cpp
> +    msg >> ta._imageIndex;
How about the loading/saving of `_hasObjectAnimation` and `_isMarkedAsRoad`?

2023-01-26 15:44 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.cpp
> -        // Random monster placeholder "MON"
These comments were incorrect. There are no Mon 1, 2, 3 placeholders but weak, medium and strong which is readable from **MP2::OBJ_** type. These are image indexes so they have no particular meaning after all.

2023-01-26 15:59 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_tiles.cpp
> -        // Random monster placeholder "MON"
I mean, in map editor they looks like a circle with an inscription like "MONX".

2023-01-26 16:04 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.cpp
> -        // Random monster placeholder "MON"
A fair point. I will add them back then.

2023-01-26 17:09 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_tiles.cpp
> +        ta._isMarkedAsRoad = false;
Hi @ihhub Shouldn't the logic here be a bit more sophisticated? I mean, shouldn't these fields be dependent on first two bits of `temp` here and below in the `StreamBase & Maps::operator>>( StreamBase & msg, Tiles & tile )`?

2023-01-27 00:20 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.cpp
> +        ta._isMarkedAsRoad = false;
It is done.

2023-01-27 00:36 UTC, oleg-derevenetz approved these changes

2023-01-27 00:38 UTC, merged