Optimize mini-map rendering
ihhub/fheroes2 pull request #6514
Opened 2023-01-23 18:28 UTC by Districh-ru

An attempt to reduce CPU usage on mini-map (radar) rendering:

- [X] remove the use of "transform" image layer since mini-map is always non-transparent,
- [X] remove code for not square maps,
- [X] use direct mini-map image fill without many calls for `SetPixel` or `Fill` functions,
- [X] update the mini-map image only if it could be changed,
- [ ] try to update only the changed part of mini-map image where possible.

2023-01-26 04:11 UTC, ihhub commented
Hi @Districh-ru , if the last stage takes too much time we can do this is a separate pull request.

2023-01-26 05:30 UTC, Districh-ru commented
> Hi @Districh-ru , if the last stage takes too much time we can do this is a separate pull request.

Hi @ihhub , I plan to push the commit with the last stage today evening. I've done setting ROI for radar using hero's `GetScoute()` and `GetCenter()` methods. I need to test it.
I don't like redrawing the whole radar on hero move. On big maps it takes up to 12-15 ms (much CPU time is used for drawing castles). Usung ROI might speed up radar rendering up to 10 times on hero move.
And this will be a first step, which might be also optimized in future PRs (redraw not ROI, but only the scouted points and captured objects).
Sorry, but on working days I don't have much spare time. :(

2023-01-26 09:17 UTC, ihhub commented
Hi @Districh-ru , no pressure. I just proposed a way to have some progress on your work but since you are going to update it soon it is fine to wait.

2023-01-27 23:56 UTC, oleg-derevenetz commented on src/fheroes2/game/game_startgame.cpp
> +                            const int32_t & heroDirection = hero->GetDirection();
Hi @Districh-ru this trick is called "temporary lifetime extension": `Heroes::GetDirection()` returns a temporary object, and then lifetime of this temporary object is extended by binding of a `const` lvalue or rvalue reference to this temporary. Usually lifetime of a temporary ends at the end of an expression (in this case at the terminating `;`), but by binding a reference this lifetime is "extended" and becomes approximately equal to lifetime of the reference - once the reference is out of scope, temporary object will be destroyed as well.

This technique was once popular, especially somewhere near C++98, because it performs a some sort of guaranteed copy elision: no copy constructor is called when a reference is created. But, since C++11 and especially C++17 we have [guaranteed copy elision](https://en.cppreference.com/w/cpp/language/copy_elision) in typical use cases.

Also this technique should be used with caution, because it is [very easy to use it incorrectly](https://godbolt.org/z/GheKPxjan). Uncomment the commented fragments and see what happens. I recommend paying special attention to the last two examples with the [range-based for](https://en.cppreference.com/w/cpp/language/range-for), because, as you can see in the range-based for's "Explanation" section, it uses the temporary lifetime extension under the hood.

While this technique is absolutely legal, I recommend NOT to use it (unless absolutely necessary) and count on copy elision instead. Also there is absolutely no need to use it for basic types, like in this case and other similar cases in this PR.

2023-01-28 07:31 UTC, Districh-ru commented on src/fheroes2/game/game_startgame.cpp
> +                            const int32_t & heroDirection = hero->GetDirection();
Hi @oleg-derevenetz, many thanks for warning and the detailed explanation with an example!
I'll take this into account in future PRs.
And I want to clarify: in current code we have
``` CPP
const fheroes2::Point & destPos = Maps::GetPoint( dst_index );

...

fheroes2::Point Maps::GetPoint( const int32_t index )
{
    return fheroes2::Point( index % world.w(), index / world.w() );
}

```
Is it safer (better) to declare `const fheroes2::Point destPos = ...` ?

2023-01-28 10:56 UTC, oleg-derevenetz commented on src/fheroes2/game/game_startgame.cpp
> +                            const int32_t & heroDirection = hero->GetDirection();
> Is it safer (better) to declare `const fheroes2::Point destPos = ...` ?

I would say this way: with modern C++ standards and compilers there is usually no gain in using temporary lifetime extension (except, probably, for some exotic cases). In this case `destPos` is guaranteed to be created in-place and no copies will be made. However, this is still a valid mechanism, and there is no need to rewrite all existing places where it is used (a lot of the fheroes2 code was written in pre-C++11 manner and there's nothing particularly wrong with that). I recommend simply not using this mechanism in new code unless absolutely necessary.

2023-01-28 15:58 UTC, ihhub requested changes
Hi @Districh-ru , I put several comments in this pull request. Would you mind to take a look at them?

2023-01-28 15:58 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +        const bool isJumpHeroSpeed = ( 10 == conf.HeroesMoveSpeed() );
Is there a reason why we created this variable since it is used only in one place?

2023-01-28 15:58 UTC, ihhub commented on src/fheroes2/gui/interface_radar.cpp
> +void Interface::Radar::SetRedraw() const
This method can be inlined.

2023-01-28 15:58 UTC, ihhub commented on src/fheroes2/gui/interface_radar.cpp
> +    _roi = fheroes2::Rect( 0, 0, world.w(), world.h() );
We can use C++11 initialization list which checks for implicit conversions:
```cpp
_roi = { 0, 0, world.w(), world.h() };
```

2023-01-28 15:58 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +                        radar.SetMapRedraw();
This is actually a problem: **_roi** in `Interface::Radar` class is being updated only after an explicit call of **SetMapRedraw()** methods. This might lead to some issues in the future when somebody might add a code to redraw the mini-map but forgets to call **SetMapRedraw()**.

What if we set `_roi = { 0, 0, world.w(), world.h() };` at the end of `Interface::Radar::RedrawObjects()` method default to full image every time we render the mini-map. Yes, it might be a little bit slower (few more CPU cycles) but this might prevent from the described before mistakes.

What do you think?

2023-01-28 15:58 UTC, ihhub commented on src/fheroes2/gui/interface_radar.h
> +        bool _hide;
It is better to be consistent. Please add a default value for this member as well.

2023-01-28 15:58 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> +        const fheroes2::Point & toPosition = hero.GetCenter();
Let's be consistent and make this variable as const variable only (without &).

2023-01-28 15:58 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> +        const int32_t & scoutRange = hero.GetScoute();
This is definitely not needed. All POD (plain old data) types must not be as const reference. Please make it as a normal variable.

2023-01-28 15:58 UTC, ihhub commented on src/fheroes2/gui/interface_radar.h
> +        void SetMapRedraw( const fheroes2::Rect & roi );
Shall we rename it into something like `setRenderArea` or `setRenderRoi` or use a word refresh? Right now it is not exactly cleat what these methods do.

2023-01-28 17:24 UTC, Districh-ru commented on src/fheroes2/game/game_startgame.cpp
> +        const bool isJumpHeroSpeed = ( 10 == conf.HeroesMoveSpeed() );
Hi @ihhub, this is a leftover from one of optimization approaches. :)
I'll revert this.

2023-01-28 17:35 UTC, Districh-ru commented on src/fheroes2/game/game_startgame.cpp
> +                        radar.SetMapRedraw();
Sure, it'll be safer. And as we set the whole `_roi` here, I'll remove this from `SetMapRedraw()` and make this method in-lined.

2023-01-28 18:11 UTC, Districh-ru commented on src/fheroes2/gui/interface_radar.h
> +        void SetMapRedraw( const fheroes2::Rect & roi );
OK, there will be `SetRenderWholeMap()` to render objects for entire mini-map in and `SetRenderArea(...)`.

2023-01-28 18:14 UTC, Districh-ru commented on src/fheroes2/gui/interface_radar.cpp
> +void Interface::Radar::SetRedraw() const
In this method we call `SetRedraw(...)` method  from `Interface::Basic` and we cannot make it inlined.

2023-01-30 15:31 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +            I.GetRadar().SetRenderWholeMap();
Do we need this call to be present since we reset ROI after each render?

2023-01-30 18:27 UTC, Districh-ru commented on src/fheroes2/heroes/heroes_action.cpp
> +            I.GetRadar().SetRenderWholeMap();
Hi @ihhub, this method besides setting the `_roi` to whole map also sets `_needMapRedraw` to `true`. So we need to call it if we want to update the map image part of radar. Without this call only the cursor position will be updated.
I've renamed this method to `SetRenderMap()`, removed setting of `_roi` as it is now set after every `RedrawObjects()` call. Also I made it inline and changed its comment a bit.

2023-01-30 18:34 UTC, Districh-ru commented on src/fheroes2/game/game_startgame.cpp
> +                        radar.SetMapRedraw();
`SetRenderWholeMap()` is called at the start of `HumanTurn()`.
I've added `_roi = { 0, 0, world.w(), world.h() };` to `Build()` method which is called at the start of scenario.
Now it works OK with map change.

2023-01-31 14:00 UTC, ihhub approved these changes

2023-01-31 20:47 UTC, oleg-derevenetz reviewed
Hi @Districh-ru I just left a few suggestions and questions, could you please take a look when you have some free time?

2023-01-31 20:47 UTC, oleg-derevenetz commented on src/fheroes2/gui/interface_radar.cpp
> +                        // This is a visible tile and not covered by other objets, so fill it with the ground tile data.
```suggestion
                        // This is a visible tile and not covered by other objects, so fill it with the ground tile data.
```

2023-01-31 20:47 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes.cpp
> +fheroes2::Rect Heroes::GetScoutRoi( const bool noDirection /* = false */ ) const
I suggest calling this parameter `ignoreDirection`, but this is optional.

2023-01-31 20:47 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_action.cpp
> +    // Update radar image without checking for the direction as the boat may have different direction.
It seems that the direction of the hero is not ignored here, what does this comment mean?

2023-01-31 20:47 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_action.cpp
> +    // Before entering a Teleport the Hero makes a move into it, so set the scout area of this move to update radar image.
This is not quite true, because player may just hit the space button and re-use the Teleport (the same logic applies to the Whirlpool BTW). JFYI.

2023-01-31 20:47 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes.cpp
> +        return { heroPosition.x - scoutRange, heroPosition.y - scoutRange, heroPosition.x + scoutRange + 1, heroPosition.y + scoutRange + 1 };
How exactly does it work? `Rect` is `{ x, y, width, height }` and according to this logic (and to similar logic below) calculations of `width` & `height` depend on `heroPosition`, although they should depend only on `scoutRange`. Am I missing something?

2023-02-01 16:18 UTC, Districh-ru commented on src/fheroes2/heroes/heroes.cpp
> +fheroes2::Rect Heroes::GetScoutRoi( const bool noDirection /* = false */ ) const
Hi @oleg-derevenetz!
Making a new check of possible scout radius change I found that it might be drastically changed without clearing the fog (rescue from jail, capture artifact). And the fog is cleared only on the next move, so the mini-map cannot be correctly rendered using hero direction.
So I removed the code using direction data.

2023-02-01 16:20 UTC, Districh-ru commented on src/fheroes2/heroes/heroes_action.cpp
> +    // Update radar image without checking for the direction as the boat may have different direction.
Thanks for pointing this out! This comment is left over from one of the previous approaches.
I've changed it.

2023-02-01 16:29 UTC, Districh-ru commented on src/fheroes2/heroes/heroes.cpp
> +        return { heroPosition.x - scoutRange, heroPosition.y - scoutRange, heroPosition.x + scoutRange + 1, heroPosition.y + scoutRange + 1 };
I used a not clear `roi` implementation. I was using `width` and `height` as the max coordinates of `roi`. It was a bit easier to use.
I've changed this to a regular `fheroes2::Rect` implementation. Now width is `width`.

2023-02-01 16:35 UTC, Districh-ru commented
> Hi, @Districh-ru.
> I ran a test of your changes and found that the mini map is not updated if you visit an observation tower. I'm blue player and visited the tower down to the left. 
> I don't know a map that has the cartographer but I wanted to check that too. I tested the Eye of the Magi and it worked as it should.

Hi, @zenseii!
Thanks for finding this bug!
I've made a fix for Observation Tower and also for Castle capture.

For cartographer (Magelan Maps) I render the whole map. I use this map for checks, it contains a cartographer: [221.zip](https://github.com/ihhub/fheroes2/files/10559289/221.zip)

2023-02-01 19:56 UTC, oleg-derevenetz reviewed
Hi @Districh-ru I just left a few notes and questions, could you please take a look?

In general, of course, the complication of the radar API is somewhat alarming. Where before it was enough to call `iface.Redraw( Interface::REDRAW_RADAR )`, now we need a lot more calls, including proper ROI calculations, what can be very easily done wrong or completely forgotten. Maybe somehow it is possible to encapsulate this (maybe in the future PRs) with simpler API.

2023-02-01 19:56 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes.cpp
> +             ( ( direction == Direction::TOP || direction == Direction::BOTTOM ) ? 0 : scoutRange ) + scoutRange + 1 };
Hmm, suppose that `scoutRange` is 2 and hero is moving to the right:

```
v previous hero position
*>**
   ^ a newly discovered tile
0123
```

So we need to redraw 4 tiles beginning from tile 0, right? With this logic:

```
return { 1 - 1, ..., 0 + 2 + 1, ... };
```

So just 3 tiles will be redrawn instead of 4, right?

2023-02-01 19:56 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes.h
> +    fheroes2::Rect GetScoutRoi( const bool ignoreDirection = false ) const;
Maybe call it `GetRadarScoutRoi()` to emphasize that this ROI is related to radar? Or maybe somehow emphasize that this ROI is measured in tiles (maybe in the describing comment) and therefore make this method more "generic" and not related to the radar only?

2023-02-01 19:56 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_action.cpp
> +            I.SetRedraw( Interface::REDRAW_CASTLES | Interface::REDRAW_RADAR );
What do you think about putting this code to a local lambda to avoid the code duplication?

2023-02-01 19:56 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_meeting.cpp
> +        Scoute( otherHero.GetIndex() );
IMHO this looks wrong. This call will scout tiles **_as-if_** the current hero is scouting, but while standing on the other hero's position, which is wrong, because the other hero may have different scouting radius.

2023-02-02 02:58 UTC, Districh-ru commented on src/fheroes2/heroes/heroes.cpp
> +             ( ( direction == Direction::TOP || direction == Direction::BOTTOM ) ? 0 : scoutRange ) + scoutRange + 1 };
Hi @oleg-derevenetz, yes, now radar calls are complicated as now radar API does 3 functions:
1. Render a new cursor position on every `iface.Redraw( Interface::REDRAW_RADAR )` without rendering the map
2. Set ROI and set bit to render the map in ROI on the next `iface.Redraw( Interface::REDRAW_RADAR )`
3. Render the whole map on the next `iface.Redraw( Interface::REDRAW_RADAR )`
We can separate `Interface::REDRAW_RADAR` into `Interface::REDRAW_RADAR_MAP` and `Interface::REDRAW_RADAR_CURSOR` to call them both from `iface.Redraw()`. And if ROI was not set before `iface.Redraw()` then the whole map will be rendered.

And about `scoutRange`: if it is 2, then: `return { 1 - 2, ..., 0 + 2 + 1, ...} and there will be 4 tiles : `-1, 0, 1, 2`
Currently the last tile number in ROI is the tile number after the last rendered tile (like vector.end() ). If it is complicated I can change it and remove extra `+ 1` in ROI logic.

2023-02-02 03:02 UTC, Districh-ru commented on src/fheroes2/heroes/heroes_action.cpp
> +            I.SetRedraw( Interface::REDRAW_CASTLES | Interface::REDRAW_RADAR );
Thanks for the suggestion!
I'll do it in the evening.

2023-02-02 03:04 UTC, Districh-ru commented on src/fheroes2/heroes/heroes_meeting.cpp
> +        Scoute( otherHero.GetIndex() );
Yes, it is wrong, it should be `otherHero.Scoute( otherHero.GetIndex() );`

2023-02-02 04:18 UTC, Districh-ru commented on src/fheroes2/heroes/heroes.cpp
> +             ( ( direction == Direction::TOP || direction == Direction::BOTTOM ) ? 0 : scoutRange ) + scoutRange + 1 };
Yes, there is a bug in setting ROI. I'll fix this bug today in the evening.

2023-02-02 04:37 UTC, Districh-ru commented on src/fheroes2/heroes/heroes.cpp
> +             ( ( direction == Direction::TOP || direction == Direction::BOTTOM ) ? 0 : scoutRange ) + scoutRange + 1 };
```suggestion
             ( ( direction == Direction::LEFT || direction == Direction::RIGHT ) ? 1 : scoutRange ) + scoutRange + 1,
             ( ( direction == Direction::TOP || direction == Direction::BOTTOM ) ? 1 : scoutRange ) + scoutRange + 1 };
```

2023-02-02 14:44 UTC, Districh-ru commented
Hi, @oleg-derevenetz, I've tried to simplify the radar API and also made a lambda function for Castle capture. This is my first lambda function. :)
Please check it when you have time.

2023-02-02 15:01 UTC, Districh-ru commented
Hi @oleg-derevenetz, I've tried to change the radar API to get rid of many sets. Now `REDRAW_RADAR` redraws mini-map fully or in a ROI if it is set with a cursor over it and `REDRAW_MAP_CURSOR` renders the previously generated mini-map with a cursor over it.
Could you please check the committed changes when you have time.

2023-02-02 19:56 UTC, oleg-derevenetz reviewed
Hi @Districh-ru Yes, it seems like many boilerplate were removed. Let's see if we can simplify the code even more. I left a few suggestions, could you please take a look when you have time?

2023-02-02 19:56 UTC, oleg-derevenetz commented on src/fheroes2/gui/interface_radar.h
> +        // To redraw the radar map image and render a cursor over it call "Interface::Basic::Get().SetRedraw( Interface::REDRAW_RADAR );".
What do you think about passing an argument for this `SetRedraw()`? Something like this:

```cpp
void SetRedraw( const uint32_t redrawMode ) const
{
    // Only these values are allowed here
    assert( ( redrawMode & ~( REDRAW_RADAR_CURSOR | REDRAW_RADAR ) ) == 0 );

    _interface.SetRedraw( redrawMode  );
}
```

This should help to simplify many places where `Radar::SetRedraw()` is used because there will be no need to use the `Interface::Basic::Get()` boilerplate anymore.

2023-02-02 19:56 UTC, oleg-derevenetz commented on src/fheroes2/gui/interface_events.cpp
> +            I.SetRedraw( REDRAW_RADAR );
We are already inside the `Interface::Basic` here. We can either remove the `const` qualifier here and do the following:

```cpp
radar.SetRenderArea( { 0, 0, world.w(), world.h() } );
SetRedraw( REDRAW_RADAR );
```

or, if we change the `Radar::SetRedraw()`, we can keep the `const` and do the following:

```cpp
radar.SetRenderArea( { 0, 0, world.w(), world.h() } );
radar.SetRedraw( REDRAW_RADAR );
```

I suggest looking at the rest of the places where this can potentially be simplified.

2023-02-02 19:56 UTC, oleg-derevenetz commented on src/fheroes2/game/game_startgame.cpp
> +                        Redraw( REDRAW_RADAR );
There we can delay the redraw, because we perform another `Redraw()` call two lines below. We can use either the `SetRedraw( REDRAW_RADAR )` or `radar.SetRedraw( REDRAW_RADAR )` if we rewrite the `Radar::SetRedraw()`.

2023-02-03 14:52 UTC, Districh-ru commented on src/fheroes2/gui/interface_events.cpp
> +            I.SetRedraw( REDRAW_RADAR );
Hi, @oleg-derevenetz, many thanks for the suggestions!
I used the second variant here, but I could not keep `const` as `SetRenderArea()` is not a `const` method.

2023-02-03 18:40 UTC, oleg-derevenetz commented on src/fheroes2/gui/interface_radar.cpp
> +    assert( redrawMode & ( REDRAW_RADAR_CURSOR | REDRAW_RADAR ) );
Hi @Districh-ru

The whole point of this check is to verify that ONLY `REDRAW_RADAR_CURSOR` and/or `REDRAW_RADAR` are passed as `redrawMode`. What if `redrawMode` will be equal to, say, `REDRAW_RADAR_CURSOR | REDRAW_BUTTONS`? In this case this `assert()` will not fail, while this one:

```cpp
assert( ( redrawMode & ~( REDRAW_RADAR_CURSOR | REDRAW_RADAR ) ) == 0 );
```

will fail, right?

2023-02-03 18:58 UTC, Districh-ru commented on src/fheroes2/gui/interface_radar.cpp
> +    assert( redrawMode & ( REDRAW_RADAR_CURSOR | REDRAW_RADAR ) );
Hi @oleg-derevenetz, yes, you are absolutely right.
Thanks for explanation!

2023-02-03 20:06 UTC, oleg-derevenetz approved these changes
LGTM, but I suggest postponing the merge after the 1.0.1 release, because this release will be literally tomorrow(?), and this PR contains a lot of various changes, so we will have an additional month for their thorough testing until the next release. @ihhub what do you think?

2023-02-03 23:42 UTC, oleg-derevenetz commented
> because this release will be literally tomorrow(?)

Ah no, it's not tomorrow.

2023-02-04 13:36 UTC, ihhub commented
Hi @oleg-derevenetz , do you still suggest to postpone?

2023-02-04 13:38 UTC, oleg-derevenetz commented
@ihhub Well, there are still many reviewers left. Let's make a decision after the full review.

2023-02-04 13:38 UTC, ihhub commented
I am going to review every critical pull request today and tomorrow.

2023-02-04 15:21 UTC, ihhub requested changes
Hi @Districh-ru , I left multiple comments in this pull request. Could you please take a look when you have time?

2023-02-04 15:21 UTC, ihhub commented on src/fheroes2/gui/interface_radar.h
> +        // Set the "need" of render the radar map only in geven 'roi' on next radar Redraw call.
Misspelled **geven** --> **given**. Also please add **the** before this word.

2023-02-04 15:21 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +        if ( std::find( bonuses.begin(), bonuses.end(), fheroes2::ArtifactBonus( fheroes2::ArtifactBonusType::AREA_REVEAL_DISTANCE ) ) != bonuses.end() ) {
Please use `art.isArtifactBonusPresent( fheroes2::ArtifactBonusType::AREA_REVEAL_DISTANCE )` instead of this code.

Also note that there is a chance that assembled artifact could appear so we need to check for it as well. I suggest to go this way:
```cpp
bool isScoutingUpdateRequired = false;
if ( art.isArtifactBonusPresent( fheroes2::ArtifactBonusType::AREA_REVEAL_DISTANCE ) ) {
    isScoutingUpdateRequired = true;
}

for ( const auto & assembledArtifact : assembledArtifacts ) {
    if ( Artifact( assembledArtifact ._assembledArtifactID).isArtifactBonusPresent( fheroes2::ArtifactBonusType::AREA_REVEAL_DISTANCE ) ) {
        isScoutingUpdateRequired = true;
        break;
    }
}

if ( isScoutingUpdateRequired  ) {
    Scoute( this->GetIndex() );
    ScoutRadar();
}
```

2023-02-04 15:21 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +            // When Scouting skill is learned we reveal the fog and redraw the radar map image in a new sout area of the hero.
Misspelled **sout** --> **scout**.

2023-02-04 15:21 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +    I.GetRadar().SetRenderArea( this->GetScoutRoi( true ) );
Please remove `this->`:
```cpp
I.GetRadar().SetRenderArea( GetScoutRoi( true ) );
```
is shorter.

2023-02-04 15:21 UTC, ihhub commented on src/fheroes2/heroes/heroes_meeting.cpp
> +        Scoute( this->GetIndex() );
Please remove `this->`:
```cpp
Scoute( GetIndex() );
```

2023-02-04 15:25 UTC, oleg-derevenetz commented on src/fheroes2/dialog/dialog_system_options.cpp
>                  basicInterface.Redraw( Interface::REDRAW_ALL );
@ihhub There was some issue with rendering if we did not render the radar first separately. There is a comment regarding this.

2023-02-04 15:26 UTC, ihhub commented on src/fheroes2/dialog/dialog_system_options.cpp
>                  basicInterface.Redraw( Interface::REDRAW_ALL );
No-no. What I suggest is this:
```cpp
basicInterface.Redraw( Interface::REDRAW_RADAR_CURSOR );
basicInterface.Redraw( Interface::REDRAW_ALL & ~( Interface::REDRAW_RADAR | Interface::REDRAW_RADAR_CURSOR ) );
```
so we don't render the radar twice.

2023-02-04 15:43 UTC, Districh-ru commented on src/fheroes2/gui/interface_radar.cpp
>      if ( !hideInterface || conf.ShowRadar() ) {
Hi, @ihhub, the next condition is not the opposite here.
In the first condition we render the borders for mini-map only in "Hide Interface" mode and only if it is visible (`conf.ShowRadar()`).
The code in the second condition renders the mini-map if we are not in "Hide Interface" mode and mini-map is visible.
I'll change the code to this:
``` cpp
    const Settings & conf = Settings::Get();
    if ( conf.isHideInterfaceEnabled() ) {
        if ( conf.ShowRadar() ) {
            BorderWindow::Redraw();
        }
        else {
            // We are in "Hide Interface" mode and radar is turned off so we have nothing to render.
            return;
        }
    }

... the rest of the code without if condition
```

2023-02-04 15:52 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_system_options.cpp
>                  basicInterface.Redraw( Interface::REDRAW_ALL );
OK, I've tested this suggestion and slightly changed it:
```cpp
// We need to redraw radar first due to the nature of restorers. Only then we can redraw everything.
// And we do a full radar redraw as it could be hidden in "Hide Interface" mode so it was not updated.
basicInterface.Redraw( Interface::REDRAW_RADAR );
basicInterface.Redraw( Interface::REDRAW_ALL & ~( Interface::REDRAW_RADAR_CURSOR | Interface::REDRAW_RADAR ) );
```

2023-02-04 15:53 UTC, ihhub commented on src/fheroes2/gui/interface_radar.cpp
>      if ( !hideInterface || conf.ShowRadar() ) {
Hi @Districh-ru , in this case please just cache **conf.ShowRadar()** and use in both places.

2023-02-04 15:53 UTC, ihhub commented on src/fheroes2/dialog/dialog_system_options.cpp
>                  basicInterface.Redraw( Interface::REDRAW_ALL );
Nice! A faster solution :)

2023-02-04 16:35 UTC, Districh-ru commented on src/fheroes2/game/game_interface.h
> +        REDRAW_RADAR_CURSOR = 0x01,
Both of these flags calls radar `Radraw()` method, with only difference:
`REDRAW_RADAR` redraws the mini-map pixel-by-pixel in a ROI (if it was set) or fully and renders a cursor over it
and `REDRAW_RADAR_CURSOR` restores the image under the cursor position and render the new position of cursor without redrawing the mini-map.
Without these 2 enumerations we have to make a method to set some `bool isMapRedrawNeeded` in radar class before `SetRedraw(  REDRAW_RADAR );` or `Redraw(  REDRAW_RADAR );` if we want to update the radar map. <- this was implemented earlier and it was more complicated radar API.

2023-02-04 16:50 UTC, Districh-ru commented on src/fheroes2/heroes/heroes.cpp
> +        if ( std::find( bonuses.begin(), bonuses.end(), fheroes2::ArtifactBonus( fheroes2::ArtifactBonusType::AREA_REVEAL_DISTANCE ) ) != bonuses.end() ) {
`isArtifactBonusPresent` is the member of `BagArtifacts` class and we have `const Artifact & art`. So we can't use this method to `art`. That's why I used this code.
I'll add the same check if any artifact was assembled.

2023-02-04 16:51 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +        if ( std::find( bonuses.begin(), bonuses.end(), fheroes2::ArtifactBonus( fheroes2::ArtifactBonusType::AREA_REVEAL_DISTANCE ) ) != bonuses.end() ) {
Oh, yes, You're right.

2023-02-04 17:16 UTC, Districh-ru commented on src/fheroes2/heroes/heroes.cpp
> +        if ( std::find( bonuses.begin(), bonuses.end(), fheroes2::ArtifactBonus( fheroes2::ArtifactBonusType::AREA_REVEAL_DISTANCE ) ) != bonuses.end() ) {
@ihhub, I've made a lambda-function to do checks for `art` and `assembledArtifact `. Could you please check it.

2023-02-04 17:27 UTC, ihhub reviewed
Hi @Districh-ru , I left one more suggestion. Could you please check it?

2023-02-04 17:27 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +        if ( !assembledArtifacts.empty() ) {
This check is no needed as the for-loop will handle it. Please remove it.

2023-02-04 17:29 UTC, Districh-ru commented on src/fheroes2/gui/interface_radar.cpp
>      if ( !hideInterface || conf.ShowRadar() ) {
I removed `conf.ShowRadar()` from the second place as now there is no need to check it. We do all checks in shown above double `if` condition. In "Show Interface" mode the check of `conf.ShowRadar()` is not needed.

2023-02-04 17:31 UTC, Districh-ru commented on src/fheroes2/heroes/heroes.cpp
> +        if ( !assembledArtifacts.empty() ) {
Oh, yes, you are right. :)

2023-02-05 01:41 UTC, ihhub approved these changes

2023-02-08 15:51 UTC, ihhub commented
Hi @Branikolog and @zenseii , could you please re-review this pull request when you have spare time?

2023-02-10 20:28 UTC, Districh-ru commented
> Hi, @Districh-ru.
> 
> I got an assertion failure when visiting the observation tower on the Slugfest map (Small), but not on Broken Alliance (Medium) `at line 277 in interface_radar.cpp`:
> 
> ```c++
> assert( _roi.x >= 0 && _roi.y >= 0 && ( _roi.width + _roi.x ) <= world.w() && ( _roi.height + _roi.y ) <= world.h() );
> ```

Hi, @zenseii!
Thanks for finding this bug! As the scout area is too big (41 tiles width and height) it originally starts from `roi.x`=-1 and `roi.y`=-3. The code changes these values to 0, but when checking `roi.width` and `roi.height` the value correction uses non corrected `x` and `y`, so we get `roi.width`=36-(-1)=37 and `roi.heigh`=36-(-3)=39 and then we get an assertion.
I've fixed this issue and checked this map and the test map for scouting near the map edges.

2023-02-11 17:42 UTC, Branikolog commented
Hi, @Districh-ru 
I've noticed, when you buy a hero with improved scouting skill, the area around castle is not revealed.
Also, When you step out with this hero, fog is extra revealed only on a lower part of castle area.
![image](https://user-images.githubusercontent.com/55348946/218272846-b62cd1a9-5bec-43d8-b1b3-e2bdd3c41aca.png)

2023-02-11 19:08 UTC, Districh-ru commented
> Hi, @Districh-ru I've noticed, when you buy a hero with improved scouting skill, the area around castle is not revealed. Also, When you step out with this hero, fog is extra revealed only on a lower part of castle area. 

Hi, @Branikolog. Thanks for bug-tracking!
I've updated the code. Now the map will be revealed (with the update of mini-map) with every possible hero recruitment.

2023-02-11 19:48 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes.cpp
> +    ScoutRadar();
Hi @Districh-ru what if this hero is not controlled by local human player (for example, this hero is hired by AI)?

2023-02-11 20:09 UTC, Districh-ru commented on src/fheroes2/heroes/heroes.cpp
> +    ScoutRadar();
Hi, @oleg-derevenetz!
`Scoute()` calls `ClearFog()` and as we reveal the map for human player we should do it also for AI for equality. :)
But `ScoutRadar()` will only waste some resources, thanks for the note. So lets call it only for human players.

2023-02-11 20:48 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes.cpp
> +    ScoutRadar();
@Districh-ru yes, I meant the `ScoutRadar()` part, because there is no need to redraw the radar in this case.

2023-02-12 14:41 UTC, Districh-ru commented
> Hi, @Districh-ru.
> I've tested the changes and everything works. Please resolve the merge conflicts when you have the time to.

Hi, @zenseii.
I've resolved the merge conflicts and also did minor optimization available after this merge: before this merge the View world map was render on the whole screen so we had to render radar image over it every time. Now we can render radar image only once and then only redraw the cursor.

2023-02-13 20:49 UTC, Branikolog approved these changes

2023-02-14 01:26 UTC, merged

2023-02-14 01:27 UTC, ihhub commented
@Districh-ru , great thanks for this improvement!