Add support for scaled resolutions
ihhub/fheroes2 pull request #6516
Opened 2023-01-24 08:08 UTC by ihhub

Based on the demand from users with high resolution displays. This feature is available only on SDL 2.

relates to #5373
relates to #4946

2023-01-24 10:22 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few suggestions, please take a look when you have time. In addition, this `scale` is actually not really used anywhere yet, as far as I understand?

2023-01-24 10:22 UTC, oleg-derevenetz commented on src/fheroes2/dialog/dialog_resolution.cpp
> +             && ( selectedResolution.width != currentResolution.width || selectedResolution.height != currentResolution.height
Since `ResolutionInfo` already has `operator=()`, we can just add `operator!=()` and use it here and in other similar places.

2023-01-24 15:17 UTC, oleg-derevenetz reviewed
Hi @ihhub I just left a few questions and suggestions, could you please take a look when you have time?

2023-01-24 15:17 UTC, oleg-derevenetz commented on src/engine/screen.cpp
> +        for ( size_t currentId = resolutionCountBefore - 1; currentId > 1; --currentId ) {
Suppose that we have two resolutions:

2x2 (1x1 with scale factor 2)
1x1

We will not be able to offer the first resolution as a scaled version of the second one because at the first iteration of this `for` loop `currentId` will be 1 and condition `currentId > 1` will be immediately `false`, right?

2023-01-24 15:17 UTC, oleg-derevenetz commented on src/engine/screen.cpp
> +                ++scaleFactor;
Maybe alter the logic a bit here and just check is the another "bigger" resolution is divisible by the current "smaller" resolution (i.e.

```cpp
biggerResolution.width / smallerResolution.width == biggerResolution.height / smallerResolution.height && biggerResolution.width % smallerResolution.width == 0 && biggerResolution.height && smallerResolution.height == 0
```

? Also of course check that both `biggerResolution` and `smallerResolution` doesn't have zero width or height.

2023-01-24 15:17 UTC, oleg-derevenetz commented on src/fheroes2/dialog/dialog_resolution.cpp
> +        if ( selectedResolution.width > 0 && selectedResolution.height > 0 && selectedResolution.scale > 0 && ( selectedResolution != currentResolution ) ) {
The inner parentheses looks redundant here.

2023-01-24 18:03 UTC, Districh-ru requested changes
Hi @ihhub, I found one bug, could you please address it when you have time:
If I set the 2x resolution in windowed mode (i.e. `960x540(x2)`) and then switch to fullscreen mode by clicking the `Mode` icon (not F4), the engine switches to 960x540 without x2.
If I press F4 in windowed mode for the first time the engine correctly switches to 960x540(x2). But if I press F4 two more times the engine first switches to 960x540(x2) windowed and then to 960x540 fullscreen without x2.
Changing resolution without switching fullscreen/windowed mode works correctly.
I use Windows OS.

2023-01-25 11:18 UTC, ihhub commented on src/engine/screen.cpp
> +        for ( size_t currentId = resolutionCountBefore - 1; currentId > 1; --currentId ) {
Actually, you're right. This is bug. It should be **currentId > 0**.

2023-01-25 11:27 UTC, ihhub commented on src/engine/screen.cpp
> +            for ( size_t biggerId = currentId - 1;; ) {
**size_t** is unsigned int. currentId is 1, biggerId can be and will be 0. Then after the iteration we decrement biggerId leading to overflow.

2023-01-25 11:29 UTC, oleg-derevenetz commented on src/engine/screen.cpp
> +            for ( size_t biggerId = currentId - 1;; ) {
Oh, maybe not because of that case of just 2 resolutions.

2023-01-25 11:34 UTC, oleg-derevenetz commented on src/engine/screen.cpp
> +                     && ( resolutions[biggerId].width / resolutions[currentId].width ) == ( resolutions[biggerId].height / resolutions[currentId].height ) ) {
Hi @ihhub BTW is there a possibility that there will be 2 equal resolutions in the list? If yes, then we should handle this case somehow to avoid additional resolutions such as "640x480x1" :)

2023-01-26 16:00 UTC, ihhub commented on src/engine/screen.cpp
> +                     && ( resolutions[biggerId].width / resolutions[currentId].width ) == ( resolutions[biggerId].height / resolutions[currentId].height ) ) {
It is not possible. This function receives a set of resolutions. Then we add resolutions which are smaller than the smallest in the set. And then we run through the whole list of resolutions adding the scaled ones. However, to be more accurate I will change **possibleResolutions** into a set.

2023-01-26 16:15 UTC, ihhub commented on src/engine/screen.cpp
> +                     && ( resolutions[biggerId].width / resolutions[currentId].width ) == ( resolutions[biggerId].height / resolutions[currentId].height ) ) {
I think no harm to actually return std::set from this function to make sure that all resolutions are unique. What do you think?

2023-01-26 16:27 UTC, oleg-derevenetz commented on src/engine/screen.cpp
> +                     && ( resolutions[biggerId].width / resolutions[currentId].width ) == ( resolutions[biggerId].height / resolutions[currentId].height ) ) {
Yes, I believe that this will look more logical.

2023-01-30 14:10 UTC, ihhub commented on src/engine/screen.cpp
> +                     && ( resolutions[biggerId].width / resolutions[currentId].width ) == ( resolutions[biggerId].height / resolutions[currentId].height ) ) {
I pushed the change but it looks a bit ugly...

2023-02-04 13:56 UTC, ihhub commented
> Hi @ihhub, I found one bug, could you please address it when you have time: If I set the 2x resolution in windowed mode (i.e. `960x540(x2)`) and then switch to fullscreen mode by clicking the `Mode` icon (not F4), the engine switches to 960x540 without x2. If I press F4 in windowed mode for the first time the engine correctly switches to 960x540(x2). But if I press F4 two more times the engine first switches to 960x540(x2) windowed and then to 960x540 fullscreen without x2. Changing resolution without switching fullscreen/windowed mode works correctly. I use Windows OS.

Hi @Districh-ru , could you please test the latest changes in this pull request and see if this issue is gone?

2023-02-04 14:15 UTC, Districh-ru commented
> Hi @Districh-ru , could you please test the latest changes in this pull request and see if this issue is gone?

Hi, @ihhub, I've tested the last commit. The issue is gone, now the Fullscreen mode is correctly set for scaled resolutions.

2023-02-04 14:18 UTC, Districh-ru approved these changes

2023-02-04 14:28 UTC, ihhub commented
Hi @oleg-derevenetz , I addressed your concerns about uniqueness of elements as well I made extra optimization of the code. Please take a look again when you have time.

2023-02-04 14:29 UTC, ihhub commented
Hi @Branikolog , could you please test this pull request as the highest priority as we need this change for the upcoming release?

2023-02-04 17:36 UTC, oleg-derevenetz reviewed
Hi @ihhub I just left a few questions and suggestions, could you please take a look?

2023-02-04 17:36 UTC, oleg-derevenetz commented on src/engine/screen.cpp
> +            static std::vector<fheroes2::ResolutionInfo> filteredResolutions;
We can make the `filteredResolutions` `static const` and use a lambda to initialize it once and for all. This initialization will be also guaranteed thread-safe (although this may not be so important here, but why not, if we can have the thread safety for free).

2023-02-04 17:36 UTC, oleg-derevenetz commented on src/engine/screen.cpp
> +            static std::vector<fheroes2::ResolutionInfo> filteredResolutions;
Here we also can make the `filteredResolutions` `static const` and initialize it using a lambda.

2023-02-04 17:36 UTC, oleg-derevenetz commented on src/engine/screen.cpp
> +            static std::vector<fheroes2::ResolutionInfo> filteredResolutions;
Here we also can make the `filteredResolutions` `static const` and initialize it using a lambda.

2023-02-04 17:36 UTC, oleg-derevenetz commented on src/fheroes2/system/settings.cpp
> +    os << "screen scale ratio = " << display.scale() << std::endl;
What do you think about integrating this into `videomode`? Say, there will be two formats of this setting: good old `videomode = 640x480` and the new one `videomode = 640x480x2`?

2023-02-04 20:42 UTC, Branikolog commented
Hi, @ihhub 
Everything works stable.
A few things I don't get...
This PR adds an ability to double only one resolution for my device:
![image](https://user-images.githubusercontent.com/55348946/216788185-b955d396-342e-4d1a-a2e0-b2848344e577.png)
My monitor is 1080p, but for some reason none of custom resolutions are available for being x2.
Also, while choosing x2 resolution in window mode or even full screen I have blurred image:
![image](https://user-images.githubusercontent.com/55348946/216788293-7b761010-29c7-4b57-b9f4-e65faf0dda3b.png)
I suppose, this feature was made to create a precise x2 picture increase, but currently it works the same to software cursor mode with linear filtering as if I manually resize game window....
Sorry, if I understood somethig wrong...

2023-02-04 20:57 UTC, oleg-derevenetz commented
> My monitor is 1080p, but for some reason none of custom resolutions are available for being x2.

640x480x2 resolution is 1280x960, but with in-game picture linearly scaled x2, so GUI elements doesn't look small, like with just 1280x960. To have, say, 800x600x2, you should have 1600x1200 in the list of supported resolutions, and to have 928x520x2 you should have 1856x1040 in the list of supported resolutions. Do you have them in this list?

> Also, while choosing x2 resolution in window mode or even full screen I have blurred image

Yes, it was to be expected because of upscaling.

> I suppose, this feature was made to create a precise x2 picture increase, but currently it works the same to software cursor mode with linear filtering as if I manually resize game window....

There is still one of SDL upscaling algorithms is applied. It's in fact really as-if you resized your window x2 linearly in both dimensions.

2023-02-04 21:13 UTC, Districh-ru commented
> Hi, @ihhub Everything works stable. A few things I don't get... This PR adds an ability to double only one resolution for my device: My monitor is 1080p, but for some reason none of custom resolutions are available for being x2. Also, while choosing x2 resolution in window mode or even full screen I have blurred image: I suppose, this feature was made to create a precise x2 picture increase, but currently it works the same to software cursor mode with linear filtering as if I manually resize game window.... Sorry, if I understood somethig wrong...

Hi, @Branikolog.
Interesting, I have also 1080p display, but fheroes2 allowed me to use two 2x resolutions:
![изображение](https://user-images.githubusercontent.com/113276641/216788933-6bfe9f4e-0037-44a0-a43a-4cde4204e194.png)
As I know, this depends on resolutions supported by graphics card. Some drivers allow to set custom resolutions. After I added new resolutions fheroes2 allowed me to use them:
![изображение](https://user-images.githubusercontent.com/113276641/216789352-be9c3e4a-0136-4c64-b727-87421d386e9d.png)

(There would be good in future to have non integer scales, for example set in-game resolution to 1366x768 and upscale it to fullscreen 1920x1080.)

2023-02-04 22:37 UTC, Branikolog commented
Hi, @oleg-derevenetz !

> Do you have them in this list?

That's a valid point. I've added this custom resolution and one more x2 option appeared for me. :+1: 

>There is still one of SDL upscaling algorithms is applied. It's in fact really as-if you resized your window x2 linearly in both dimensions.

Well, I've expected, if I set 640x480 x2 (window more) I would get a clear image with each game pixel include 2 pixels of my monitor. But it works the same (I mean being blurred while custom stretched) as if I stretched the game window by hand for some unknown, non-integer size.
That looks a bit weird, applying this x2 resolution in fullscreen mode in hardware mode looks blurry, while choosing 640x480 x1 which looks completely the same in fullscreen mode, except of scaled cursor, and it works crispy. 

Anyway, Thanks for clarification, @oleg-derevenetz , very much. :)

Hi, @Districh-ru !

>Interesting, I have also 1080p display, but fheroes2 allowed me to use two 2x resolutions:

My monitor is rather old and supports quite a poor set of resolutions. I had to add manually some low widescreen resolutions, as the lowest default available 16:9 for me was  1280x768.

>As I know, this depends on resolutions supported by graphics card. Some drivers allow to set custom resolutions. After I added new resolutions fheroes2 allowed me to use them:

Worked for me as well. :)

>(There would be good in future to have non integer scales, for example set in-game resolution to 1366x768 and upscale it to fullscreen 1920x1080.)

Isn't it upscaled if we run the application fullscreen? I mean each of the available resolutions are stretching the image on running application fullscreen.
For me, this particular PR changes almost nothing, since I mostly play fullscreen so any resolution I choose shows the image upscaled to fullscreen. Even more, while playing with hardware cursor mode I enjoy crisp and clear image, no matter what resolution I've chosen. However playing with software emulated cursor mode turned on, makes image blurred. If I want to play in a window mode I simply stretch game window by hand to any size I want, which brings the same quality as software emulated cursor mode (I mean scaled and blurred image). So those fixed x2 options could be useful only for the cases where user runs application fullscreen, but without stretching on default (in the middle of the screen with black borders). But I'm not sure anyone uses such video driver setting for any application in OS.
I've expected these x2 resolutions scaling the game for an integer x2 value in window mode at least, keeping crisp image while playing in stretched window mode, but unfortunately it doesn't work for me.

More anticipated feature for me is to allow to set a custom resolutions, as I have to manually set them for my OS, before it appears in resolution selection window.
Many players (same as me) are missing widescreen resolutions, lower than default availabe (which is ~1280x768... I've noticed the majority of streamers choose this resolution, as it's the lowest available widescreen one, otherwise they set lower resolutions, but 4:3 ratio). As you can see on my screenshot I've had to set a custom 928x520 resolution within my OS to be able to play 16:9 with satisfying size of battle screen. 
I wish an option to be able to paste a custom resolution at least for software emulated cursor mode (since in hardware mode OS itself switches to the resolution we select, which couldn't be possible, if it's not in the OS list, I suppose), but I'm not sure it's possible though.

2023-02-04 23:04 UTC, Branikolog approved these changes

2023-02-05 01:27 UTC, ihhub commented on src/engine/screen.cpp
> +        const fheroes2::ResolutionInfo lowestResolution = *std::min_element( resolutions.begin(), resolutions.end() );
Yes, we should do this.

2023-02-05 01:28 UTC, ihhub commented on src/engine/screen.cpp
>              }
There were users who had literally one 4K resolution in the list. This hack fixes the issues for them.

2023-02-05 01:28 UTC, ihhub commented on src/engine/screen.cpp
> +                   []( const fheroes2::ResolutionInfo & first, const fheroes2::ResolutionInfo & second ) { return first < second; } );
Sure'!

2023-02-05 01:29 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +    os << "screen scale ratio = " << display.scale() << std::endl;
This can be done as well.

2023-02-05 01:32 UTC, oleg-derevenetz commented on src/engine/screen.cpp
>              }
Aha, that's why. OK then :)

2023-02-05 05:30 UTC, Districh-ru commented
> > (There would be good in future to have non integer scales, for example set in-game resolution to 1366x768 and upscale it to fullscreen 1920x1080.)
> 
> Isn't it upscaled if we run the application fullscreen? I mean each of the available resolutions are stretching the image on running application fullscreen. 

Not exact. Any resolution changes the Desktop resolution ans the upscale is done by monitor or graphic card driver. This causes a problem in Windows OS: Opened windows change their size to match the set resolution, changing their inner arrangement. And after exiting the game some of opened windows do not restore its original size and inner arrangement. Also some windows are force dropped to my second monitor, which is TV and is mostly turned off, so I have to get them back from the switched off TV "to the touch". :)  This is the Windows OS issue and it causes with many applications. But if fheroes2 would set the in-game resolutuion to chosen and in fullscreen do not change the Desktop resolution it would be very nice for me. :)
Setting `x2` resolution the upscale is done by fheroes2 engine (actually by SDL2) and not by monitor or graphics driver.

2023-02-05 10:38 UTC, Branikolog commented
> Not exact. Any resolution changes the Desktop resolution ans the upscale is done by monitor or graphic card driver. This causes a problem in Windows OS: Opened windows change their size to match the set resolution, changing their inner arrangement. And after exiting the game some of opened windows do not restore its original size and inner arrangement. Also some windows are force dropped to my second monitor, which is TV and is mostly turned off, so I have to get them back from the switched off TV "to the touch". :) This is the Windows OS issue and it causes with many applications. But if fheroes2 would set the in-game resolutuion to chosen and in fullscreen do not change the Desktop resolution it would be very nice for me. :)

I experience the same problems, but I prefer image quality over my OS windows arrangement. :)

Isn't this problem was fixed while running on software emulated cursor mode? (which lowers quality as well, but makes it possible to run engine on any resolution plus scaling the cursor)

> Setting `x2` resolution the upscale is done by fheroes2 engine (actually by SDL2) and not by monitor or graphics driver.

I see.

2023-02-05 10:59 UTC, oleg-derevenetz approved these changes

2023-02-05 11:00 UTC, merged

2023-02-05 12:44 UTC, Districh-ru commented
> I experience the same problems, but I prefer image quality over my OS windows arrangement. :)

Then in would be great if the next improvements could give the ability to set the scaler, i.e. like in Homm3HD :)
![изображение](https://user-images.githubusercontent.com/113276641/216819260-0a1e69c7-d915-4305-9943-23dcf6d152a4.png)

2023-02-05 13:01 UTC, oleg-derevenetz commented
@Districh-ru you are already able to choose the scaling method (among supported by SDL) via `fheroes2.cfg`.

2023-02-05 13:10 UTC, Districh-ru commented
Thanks, @oleg-derevenetz, I forgot about this. I prefer Bilinear scaling, so I did not search the сап file for it.
Setting `screen scaling type = nearest` disables blurring. @Branikolog is that what you expected from the "x2" resolutions?

2023-02-05 13:25 UTC, Branikolog commented
@Districh-ru 
I'll check it later once more to be sure... I've checked that mode yesterday, but with nearest scaling the image on x2 resolutions looked like scaled not for integer value.

2023-02-07 11:49 UTC, Branikolog commented
> Setting `screen scaling type = nearest` disables blurring. @Branikolog is that what you expected from the "x2" resolutions?

I believe, nearest scaling should be turned on as a default while selecting x2 resolutions in window mode.
Is it time to add software/hardware modes and scaling toggles in game, so player could easily adjust the image? Right now I have to edit .cfg file each time I want to switch to that x2 resolutions