Fix scroll bar bottom position when dragging and fix high FPS rate when dragging scroll bar by mouse
ihhub/fheroes2 pull request #6531
Opened 2023-01-28 12:46 UTC by Districh-ru

close #5840

This PR also makes the render of scrollbar only if mouse position was changed and if mouse position is in range of scrollbar.

2023-01-29 11:54 UTC, ihhub requested changes
Hi @Districh-ru , I put few comments and a suggestion. Could you please take a look?

2023-01-29 11:54 UTC, ihhub commented on src/fheroes2/gui/ui_scrollbar.cpp
> -            const int32_t maxYPos = _area.y + roiHeight + height() - scrollbarImageMiddle - 1;
Could you please verify that all scrollbars in the game behave properly after this change?

2023-01-29 11:54 UTC, ihhub commented on src/fheroes2/gui/interface_list.h
> +        fheroes2::Point _mousePosition;
I suggest to name this member as **_prevMousePosition** to be even more clear about its purpose.

2023-01-29 11:54 UTC, ihhub commented on src/fheroes2/gui/interface_list.h
> +                const fheroes2::Point mousePosition = le.GetMouseCursor();
What if we remember the position of the scrollbar before and then check where it should be after. If there are no change we don't draw. What do you think?

2023-01-29 12:52 UTC, Districh-ru commented on src/fheroes2/gui/ui_scrollbar.cpp
> -            const int32_t maxYPos = _area.y + roiHeight + height() - scrollbarImageMiddle - 1;
Hi @ihhub, I've checked the scrollbars in Language/Video Mode selection, Load, Save, choose map, Kingdom view, Hero and Town scroll, Battle log, Town Portal dialogs. It works OK.
The problem was in rounding the result of division by 2. I've just simplified the expression: 
_area.y + roiHeight + height() - scrollbarImageMiddle - 1 = _area.y + roiHeight + height() - height() / 2 - 1 = _area.y + roiHeight + height() / 2 -1 = _area.y + roiHeight + scrollbarImageMiddle - 1.
And removed extra -1, which was added to patch this division rounding problem, which was leading to render the scrollbar one pixel down than its lowest position in some conditions.

2023-01-29 13:01 UTC, Districh-ru commented on src/fheroes2/gui/interface_list.h
> +        fheroes2::Point _mousePosition;
As we don't check the mouse position now this part of code is removed.

2023-01-29 15:40 UTC, ihhub approved these changes

2023-02-01 12:11 UTC, Branikolog approved these changes
👍

2023-02-01 12:11 UTC, merged

2023-02-01 12:12 UTC, ihhub commented
@Districh-ru , thanks a lot for this fix!