Optimize View World rendering
ihhub/fheroes2 pull request #6562
Opened 2023-02-04 21:32 UTC by Districh-ru

This PR slightly optimizes the View World rendering, as the most CPU expensive is rendering of Adventure map (`gamearea.Redraw( temporaryImg, drawingFlags );`).

In this PR:
- Filling black borders is done without using `Transform` layer (without calling `Fill`).
- Map objects are rendered once on View World open for each zoom level.
- Removed creation of vector on every loop of map objects render.
- Interface elements are rendered once on View World open, using `Copy` instead of `Blit`.

Also fix #4753

2023-02-05 04:38 UTC, ihhub requested changes
Hi @Districh-ru , I put several comments in this pull request. Would you mind please to take a look at them?

2023-02-05 04:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        // There could be maximum 2 objects.
Could we please expand this comment a bit? Maximum 2 object for what?

2023-02-05 04:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        // There could be maximum 2 objects.
We could also use **std::array<MP2::MapObjectType, 2>** to allocate memory on stack.

2023-02-05 04:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        uint32_t objects{ 0 };
Should we name it as **objectCount** to be more clear what this variable is about?

2023-02-05 04:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +                    }
To avoid extra function calls I suggest to do this way:
```cpp
objectTypes[1] = tile.GetObject( true );
objectCount = ( objectTypes[0] == objectTypes[1] ) ? 1 : 2;
```
In this case we have only one call and the same number of comparisons. What do you think?

2023-02-05 04:38 UTC, ihhub commented on src/fheroes2/kingdom/view_world.h
> +        std::vector<fheroes2::Rect> _roiForZoomLevels{ 4 };
We can use **std::array<fheroes2::Rect, 4>** to allocate memory on stack.

2023-02-05 07:04 UTC, Districh-ru commented on src/fheroes2/kingdom/view_world.cpp
> +#ifdef VIEWWORLD_DEBUG_ZOOM_LEVEL
Hi @ihhub, I've made 1:1 scale available, so now we have:
- *1 (23:32),
- *0,375 (12:32) - selected by default,
- *0,1875 (6:32)
- *0,125 (4:32) zooms.

2023-02-05 07:05 UTC, Districh-ru commented on src/fheroes2/kingdom/view_world.cpp
> +        uint32_t objects{ 0 };
Sure!)

2023-02-05 07:06 UTC, Districh-ru commented on src/fheroes2/kingdom/view_world.cpp
> +        // There could be maximum 2 objects.
I've expanded the comment and changed `std::vector` to `std::array` everywhere in this file as we always know the exact number of array elements.

2023-02-05 07:07 UTC, Districh-ru commented on src/fheroes2/kingdom/view_world.cpp
> +                    }
Sure, it looks better, faster and does the same. 👍

2023-02-05 07:16 UTC, Districh-ru commented
Hi @LeHerosInconnu, could you, please, check does this PR solve the symbols positioning issue.

2023-02-05 14:13 UTC, LeHerosInconnu commented
Hello @Districh-ru,

> Hi @LeHerosInconnu, could you, please, check does this PR solve the symbols positioning issue.

Yes, I will take a look at it sometime next week.

2023-02-06 06:33 UTC, Districh-ru commented on src/fheroes2/kingdom/view_world.cpp
> +#ifdef VIEWWORLD_DEBUG_ZOOM_LEVEL
Hi @ihhub!
Allowing the 1:1 zoom makes the engine to use extra 40 MB of memory on X-L maps. This is OK for PC, but maybe it is critical for mobile devices.
If it is so then we have to revert back and do not use 1:1 scale untill we rewrite the render for this scale (in another PR): for 1:1 scale we have to render the adventure map as usual, plus render the View World objects.

2023-02-08 15:59 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +#ifdef VIEWWORLD_DEBUG_ZOOM_LEVEL
This is a valid argument not to do. Let's not add 1:1 scale then.

2023-02-11 08:20 UTC, ihhub requested changes
Hi @Districh-ru , I put few very small comments. Could you please take a look?

2023-02-11 08:20 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +            for ( size_t i = 0; i < zoomLevels; ++i ) {
Pleas make this variable `int32_t` as **zoomLevels**.

2023-02-11 08:20 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        // Render hero/atrifact icon.
Misspelled **atrifact**.

2023-02-11 08:20 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +        // There could be maximum 2 objects on the tile to analyze (in example: a Hero and a Catle).
Misspelled **Catle**.

2023-02-11 08:20 UTC, ihhub commented on src/fheroes2/kingdom/view_world.cpp
> +                            if ( colorOffset != 7 ) {
This is absolutely optional but I would suggest to avoid hardcoded values here and at line 392 but I understand why it is done.

2023-02-11 09:03 UTC, Districh-ru commented on src/fheroes2/kingdom/view_world.cpp
> +                            if ( colorOffset != 7 ) {
Hi @ihhub, I made `const uint32_t unknownIndex = UINT32_MAX;` for this.

2023-02-11 11:53 UTC, ihhub approved these changes

2023-02-11 15:50 UTC, oleg-derevenetz approved these changes

2023-02-12 13:38 UTC, merged

2023-02-12 13:38 UTC, ihhub commented
@Districh-ru , huge thanks for improving the code!

2023-02-13 13:33 UTC, LeHerosInconnu commented
Hello @Districh-ru,

> Hello @Districh-ru,
> 
> > Hi @LeHerosInconnu, could you, please, check does this PR solve the symbols positioning issue.
> 
> Yes, I will take a look at it sometime next week.

Here are my observations.

At the farthest zoom level, the icon positions are consistent with the original game.

In original game:

![Icons View World 005](https://user-images.githubusercontent.com/43583994/218462827-cac450fa-413e-4b57-8851-ef034eb36806.png)

In fheroes2:

![Icons View World 006](https://user-images.githubusercontent.com/43583994/218462844-03778c74-f67f-4d59-a8b4-cce0b9bb8dbd.png)

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
Heroes 2 first, fheroes2 second.

![Icons View World 011](https://user-images.githubusercontent.com/43583994/218470902-ef794ed9-150a-4da1-821b-421e5ef38222.png) ![Icons View World 012](https://user-images.githubusercontent.com/43583994/218470906-9201126e-c412-4dd0-a531-a0dd0b0b5283.png)

At the intermediate zoom level, in order to have an icon position that is consistent with the original game, it would be necessary to shift the icons one pixel down and one pixel to the right.

In original game:

![Icons View World 003](https://user-images.githubusercontent.com/43583994/218462785-83ed40b7-0f24-4317-80b4-33bf465ca3be.png)

In fheroes2:

![Icons View World 004](https://user-images.githubusercontent.com/43583994/218462809-49deada2-9bc2-4d73-bf96-c42b3f3eb6c9.png)

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
Heroes 2 first, fheroes2 second.

![Icons View World 009](https://user-images.githubusercontent.com/43583994/218470997-9fd6f70b-6058-4012-a32e-1fdf2c72fced.png) ![Icons View World 010](https://user-images.githubusercontent.com/43583994/218471005-9834cb82-cae6-4b55-b7a7-b7ba266b8573.png)

At the highest zoom level, there is a problem with the display of the adventure map area depending on the positioning of the crosshair (https://github.com/ihhub/fheroes2/issues/6618).
I think that this problem should be corrected first before checking and possibly correcting the position of the icons.

In original game;

![Icons View World 001](https://user-images.githubusercontent.com/43583994/218461890-d61c8ff4-dae9-4ad1-b3ec-8b9a685bc0f0.png)

In fheroes2:

![Icons View World 002](https://user-images.githubusercontent.com/43583994/218461925-20b3ceb0-2444-49a8-8285-89f9aabdea41.png)

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
Heroes 2 first, fheroes2 second.

![Icons View World 007](https://user-images.githubusercontent.com/43583994/218471082-b9381499-9390-47fb-8ff4-a12b798e2c9f.png) ![Icons View World 008](https://user-images.githubusercontent.com/43583994/218471088-612b9d01-fced-4b8a-a1dd-5c0a04f57998.png)

2023-02-13 17:28 UTC, Districh-ru commented
Hello @LeHerosInconnu, thanks for the review!
The issue here is in the default map position and also in fact that tiles in OG and in fheroes2 are rendered differently: in fheroes2 it is a resize of original adventure map, while in original game at highest zoom level it is parts of original tiles (scaled by an integer factor and not 32/12 like in fheroes2) and at other zoom levels ... something else (generated from some points of original tile ???). So we cannot rely on tile images to check the position of icons.
In my first post you can see screenshots which are made by positioning the view to the right-bottom corner of the map, and the icon positions there looks consistent with OG.

I've opened a PR #6624 to fix the default map position on opening the View World.