feature: Add lighthouse information popup in kingdom overview
ihhub/fheroes2 pull request #6590
Opened 2023-02-07 12:53 UTC by Osmodium

For the issue https://github.com/ihhub/fheroes2/issues/6558

2023-02-07 13:19 UTC, oleg-derevenetz commented
Hi @Osmodium you can use special keywords in the PR description to automatically link issue(s) to it as described here:

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2023-02-07 13:26 UTC, oleg-derevenetz commented
Also if you are using MSVC for development, there is a handy plugin that will properly format the code literally in two clicks:

https://marketplace.visualstudio.com/items?itemName=LLVMExtensions.ClangFormat

I use it myself on Windows. If you use Linux or macOS for development, I recommend to install and use the `clang-format` tool.

2023-02-07 13:36 UTC, Osmodium commented
@oleg-derevenetz Thank you, I wasn't familiar with these, but I will use these going forward 👍

2023-02-07 14:51 UTC, Osmodium commented
I don't know why it fails in files I haven't touched 🤔

2023-02-07 15:03 UTC, oleg-derevenetz commented
> I don't know why it fails in files I haven't touched 🤔

You touched 3 files: `ui_kingdom.cpp`, `ui_kingdom.h` and `kingdom_overview.cpp`, and in all of them copyright date remains ending in 2022. Since you touched them, you should as well update the copyright date to end in 2033, as suggested by code style check.

2023-02-07 15:11 UTC, Osmodium commented
Ahh I see. I was cheated by the fact that it referenced a `.tmp` file 😅

2023-02-07 15:45 UTC, oleg-derevenetz commented
@Osmodium According to IWYU diagnostics:

https://github.com/ihhub/fheroes2/pull/6590/commits/e4368c9b450e51c4f3a17b10503c0ceb1db83374

you should have added a few headers to `ui_kingdom.cpp` (please note that you should use `cstdint` instead of `stdint.h`). Why did you removed so many headers from `kingdom_overview.cpp`?

2023-02-07 15:52 UTC, oleg-derevenetz commented
> I got the extension you suggested, but that does nothing to add or cleanup headers in the file, so I manually cleaned them up to the bare minimum, or that was the idea.

Just let the IWYU manage this and follow its suggestions. "Bare minimum" is objectionable because it depends on how headers include each other internally, and it's dangerous to count on it.

2023-02-07 15:55 UTC, Osmodium commented
> > I got the extension you suggested, but that does nothing to add or cleanup headers in the file, so I manually cleaned them up to the bare minimum, or that was the idea.
> 
> Just let the IWYU manage this and follow its suggestions. "Bare minimum" is objectionable because it depends on how headers include each other internally, and it's dangerous to count on it.

Is there a way to do this locally so I don't have to rely on the report in github?

2023-02-07 16:03 UTC, oleg-derevenetz commented
@Osmodium regarding style: normally we using the following inclusion style in some hypothetical `file.cpp`:

```cpp
#include "file.h" // this module's header

#include <some_std_header>
#include <another_std_header>

#include "some_another_local_module_header"
#include "another_one_header_of_another_local_module"
```

Headers in each group are sorted alphabetically (`clang-format` checks this).

2023-02-07 16:05 UTC, Osmodium commented
> @Osmodium regarding style: usually we use the following inclusion style in some hypothetical `file.cpp`:
> 
> ```c++
> #include "file.h" // this module's header
> 
> #include <some_std_header>
> #include <another_std_header>
> 
> #include "some_another_local_module_header.h"
> #include "another_one_header_of_another_local_module.h"
> ```
> 
> Headers in each group are sorted alphabetically (`clang-format` checks this).

Okay thanks :).
It seems like it this time wanted to move the standard libraries includes down under the local includes?
https://github.com/ihhub/fheroes2/actions/runs/4115736768/jobs/7104876677

2023-02-07 16:07 UTC, oleg-derevenetz commented
> It seems like it this time wanted to move the standard libraries includes down under the local includes?

Each group of headers (this module's header, library headers, other module's headers) should be separated by an empty line.

2023-02-07 16:11 UTC, Osmodium commented
> > It seems like it this time wanted to move the standard libraries includes down under the local includes?
> 
> Each group of headers (this module's header, library headers, other module's headers) should be separated by an empty line.

Yeah, I just couldn't see that from the report.
Btw. thank you for being patient with me :)

2023-02-07 18:25 UTC, oleg-derevenetz commented on src/fheroes2/gui/ui_kingdom.cpp
> +        const Text lighthouseControlledText( _( "Controlled: " ) + std::to_string( lighthouseCount ), FontType::smallWhite() );
Plain string concatenations are in general not very good for localizations - for example, it is assumed here that localized version of this string will always be left-to-right and the number of controlled lighthouses will always be at the end of the string :) I'd rather prefer something like this instead:

```cpp
std::string lighthouseControlledString = _( "Controlled: %{count}" );
StringReplace( lighthouseControlledString, "%{count}", std::to_string( lighthouseCount ) );

const Text lighthouseControlledText( lighthouseControlledString, ... );
[...]
```

I believe that this version offers a better control to the translator. What do you think?

2023-02-07 18:45 UTC, Osmodium commented on src/fheroes2/gui/ui_kingdom.cpp
> +        const Text lighthouseControlledText( _( "Controlled: " ) + std::to_string( lighthouseCount ), FontType::smallWhite() );
I thought about how to best go about that and yes I agree that your approach is more flexible and thus gives more control to the translator. I will look at implementing it like that, thanks! :)

2023-02-07 19:27 UTC, Osmodium commented on src/fheroes2/gui/ui_kingdom.cpp
> +        const Text lighthouseControlledText( _( "Controlled: " ) + std::to_string( lighthouseCount ), FontType::smallWhite() );
Added in [b048aac](https://github.com/ihhub/fheroes2/pull/6590/commits/b048aac8de36a5ac58fd47f23080b9ee15acd359)

2023-02-08 15:48 UTC, ihhub commented
Hi @Osmodium , can you please attach a screenshot for the dialog to see how it looks like?

2023-02-08 18:50 UTC, Osmodium commented
> Hi @Osmodium , can you please attach a screenshot for the dialog to see how it looks like?

Hi @ihhub.
I have attached 2 screenshots in the issue here: https://github.com/ihhub/fheroes2/issues/6558#issuecomment-1420704617

2023-02-09 00:23 UTC, ihhub commented
Hi @Osmodium , based on your screenshots the projector in the lighthouse is missing as well as the lower part of it.

2023-02-09 01:11 UTC, Osmodium commented
> Hi @Osmodium , based on your screenshots the projector in the lighthouse is missing as well as the lower part of it.
Is it possible to achieve with the `CustomImageDialogElement` in the dialog? Also is there a way to browse icons?

2023-02-09 15:49 UTC, Osmodium commented
> Hi @Osmodium , please use multiple images from ICN:OBJNMUL2, ranging from 59 to 73. I believe you need to create a combined image using 59, 60, 61, 62, 71, 72, 73 indexes with proper shifts. Then you create a separate image which will be a combination of all these sprites and feed it into `CustomImageDialogElement`. Moreover, to be really cool we can use `DynamicImageDialogElement` class to provide the animation of Lighthouse.

HI @ihhub, okay I was wondering if this was what you meant :) I will have a look at how to do this.
Do you have any example or know where this is already done in the game so I have something to go by regarding constructing the lighthouse?

2023-02-09 16:06 UTC, ihhub commented
Hi @Osmodium , it is done as a part of Adventure Map rendering inside interface_area.cpp but there is no code specific to Lighthouse at all.

2023-02-09 16:22 UTC, Osmodium commented
@ihhub Cool! I'll have a look at it, thanks for the pointer :)

2023-02-09 22:49 UTC, Osmodium commented
Hi @ihhub 
I have looked at the ICN's of the lighthouse and can see that the base of the lighthouse includes a part of the shadow.
I'm not sure it would make sense to include the shadow in the dialog and if not that it might look wierd with the cutoff on the base.

![image](https://user-images.githubusercontent.com/234248/217956716-0bb076c0-dd85-455f-befe-215ea3b72e7e.png)

2023-02-10 00:37 UTC, ihhub commented
Hi @Osmodium , I suggest to include shadow as well. We have the similar case when we display Mage Guild building as well. Also please don't forget to include the inner mirror image🙂

Now it looks much better!

2023-02-10 00:38 UTC, ihhub commented
@Osmodium , I also think that we should just display a number over "Controlled: N" as the description above states it. Please use normal font for it.

2023-02-10 15:25 UTC, Osmodium commented
Hi @ihhub, Ah I wasn't aware that it was used for the mage guild, will look at that for a bit of inspiration.
Yeah the image was just to show a bit of the progress along with the cut-off shadow 😄. I think, however, that in order to make it animate a constructed image, I'd have to extend the `DynamicImageDialogElement` to support this. Or do you have another idea?

2023-02-11 08:24 UTC, ihhub commented
Hi @Osmodium , we can do this in 2 stages (and 2 pull requests):
- complete a full static image of Lighthouse with a shadow
- add animation later (you can create a new issue for later work)

In this case you won't be overwhelmed with work and it's easier to review small chunks of code.

2023-02-11 19:32 UTC, Osmodium commented
Hi @ihhub!
I think to split it into 2 different PR's sounds like a good idea.
So, the current code has the dialog looking like this:
![image](https://user-images.githubusercontent.com/234248/218277575-c47b2e77-d78f-487e-9c62-b311a45e10bc.png)
I changed the text to resemble the dialog that pops up when visiting a lighthouse:
![image](https://user-images.githubusercontent.com/234248/218277596-33edbedc-b1d7-4a4e-82b6-921ff8e90c6a.png)
Hope this is closer to what you had in mind :)

2023-02-12 13:48 UTC, ihhub requested changes
Hi @Osmodium , I put several comments in this pull request. Could you please take a look at them?

2023-02-12 13:48 UTC, ihhub commented on src/fheroes2/gui/ui_kingdom.cpp
> +        Blit( AGG::GetICN( ICN::OBJNMUL2, 60 ), combined, 2, 33 );
Please use **Copy** over **Blit** as `combined` image is fully empty.

2023-02-12 13:48 UTC, ihhub commented on src/fheroes2/gui/ui_kingdom.cpp
> +        const std::string header( _( "Lighthouses" ) );
Please modify `MP2::StringObject()` function to handle multiple Lighthouses like it is done for few other objects and call it within **showMessage()** function call.

2023-02-12 13:48 UTC, ihhub commented on src/fheroes2/gui/ui_kingdom.cpp
> +        StringReplace( lighthouseControlledString, "%{count}", std::to_string( lighthouseCount ) );
There is no need to translate a number. **std::to_string()** would be sufficient.

2023-02-12 13:48 UTC, ihhub commented on src/fheroes2/gui/ui_kingdom.cpp
> +        Blit( AGG::GetICN( ICN::OBJNMUL2, 60 ), combined, 2, 33 );
To avoid hardcoded values please consider 2 factors:
- a size of tile on Adventure Map is always fixed and equal to **TILEWIDTH**
- each fheroes2::Sprite image returned from **AGG::GetICN()** call has an offset

A combination of these 2 ideas will lead to much smaller usage of hardcoded values.

2023-02-12 13:48 UTC, ihhub commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +            fheroes2::showLighthouseInfo( *this, 0 );
Please use **Dialog::ZERO** instead of **0**.

2023-02-12 19:23 UTC, Osmodium commented on src/fheroes2/gui/ui_kingdom.cpp
> +        StringReplace( lighthouseControlledString, "%{count}", std::to_string( lighthouseCount ) );
Fixed in [c11025b](https://github.com/ihhub/fheroes2/pull/6590/commits/c11025b2d4d988d812516cc8a780ede1c9ff8d90)

2023-02-12 19:26 UTC, Osmodium commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +            fheroes2::showLighthouseInfo( *this, 0 );
Changed in [a55eba7](https://github.com/ihhub/fheroes2/pull/6590/commits/a55eba7b7c09c1a7516f460729a72c92041b2c8d)

2023-02-12 20:13 UTC, Osmodium commented on src/fheroes2/kingdom/kingdom_overview.cpp
> +            fheroes2::showLighthouseInfo( *this, 0 );
Fixed in [a55eba7](https://github.com/ihhub/fheroes2/pull/6590/commits/a55eba7b7c09c1a7516f460729a72c92041b2c8d)

2023-02-12 20:17 UTC, Osmodium commented on src/fheroes2/gui/ui_kingdom.cpp
> +        const std::string header( _( "Lighthouses" ) );
[7d2d744](https://github.com/ihhub/fheroes2/pull/6590/commits/7d2d7444487252b25b84da2c8d220bd912ae682d) & [6a38e74](https://github.com/ihhub/fheroes2/pull/6590/commits/6a38e7404ddf4a93d9a16ade3822763c0ac12161)

2023-02-12 21:30 UTC, Osmodium commented on src/fheroes2/gui/ui_kingdom.cpp
> +        Blit( AGG::GetICN( ICN::OBJNMUL2, 60 ), combined, 2, 33 );
Use **TILEWIDTH** and sprite offsets to place parts in [d93891f](https://github.com/ihhub/fheroes2/pull/6590/commits/d93891f863bdd28936d7b4aa10a8e21abb85485c)

2023-02-12 21:38 UTC, Osmodium commented on src/fheroes2/gui/ui_kingdom.cpp
> +        Blit( AGG::GetICN( ICN::OBJNMUL2, 60 ), combined, 2, 33 );
Use **Copy** over **Blit** [eb7ef61](https://github.com/ihhub/fheroes2/pull/6590/commits/eb7ef612763380db144741b5146d0b873c901b26)

2023-02-13 16:21 UTC, ihhub requested changes
Hi @Osmodium , I added just few more comments. Could you please take a look at them?

2023-02-13 16:21 UTC, ihhub commented on src/engine/image.cpp
> +
Please remove this new function. I understand the intention of adding it but we should avoid it because the signature of the function is not the same as others. It contains only 1 input image with no coordinates and an output image with coordinates. We should explicitly state either for both or for nobody.

2023-02-13 16:21 UTC, ihhub commented on src/fheroes2/gui/ui_kingdom.cpp
> +        const Sprite & lighthouse_light = AGG::GetICN( ICN::OBJNMUL2, 62 );
Please name the variable with **camelCase**. The current naming is not suitable.

2023-02-13 16:21 UTC, ihhub commented on src/fheroes2/gui/ui_kingdom.cpp
> +        showMessage( Text( StringObject( MP2::OBJ_LIGHTHOUSE, 2 ), FontType::normalYellow() ), Text( body, FontType::normalWhite() ), buttons,
I suggest to add a comment above explaining why we set number 2 here.

2023-02-13 16:43 UTC, Osmodium commented on src/fheroes2/gui/ui_kingdom.cpp
> +        showMessage( Text( StringObject( MP2::OBJ_LIGHTHOUSE, 2 ), FontType::normalYellow() ), Text( body, FontType::normalWhite() ), buttons,
Added in [1ba0809](https://github.com/ihhub/fheroes2/pull/6590/commits/1ba080900cb0ee1a213c60a241441ead5aa365ac)

2023-02-13 16:44 UTC, Osmodium commented on src/fheroes2/gui/ui_kingdom.cpp
> +        const Sprite & lighthouse_light = AGG::GetICN( ICN::OBJNMUL2, 62 );
Renamed in [1ba0809](https://github.com/ihhub/fheroes2/pull/6590/commits/1ba080900cb0ee1a213c60a241441ead5aa365ac)

2023-02-13 16:44 UTC, Osmodium commented on src/engine/image.cpp
> +
Removed in [7da9544](https://github.com/ihhub/fheroes2/pull/6590/commits/7da9544856332647b6ff254f0fb468dcb9fed2ec)

2023-02-14 00:25 UTC, ihhub commented on src/fheroes2/gui/ui_kingdom.cpp
> +        const int32_t top_offset = TILEWIDTH - lighthouseTop.height();
Please rename this variable too :)

2023-02-14 08:41 UTC, Osmodium commented on src/fheroes2/gui/ui_kingdom.cpp
> +        const int32_t top_offset = TILEWIDTH - lighthouseTop.height();
Haha omg 😂

2023-02-14 08:46 UTC, Osmodium commented on src/fheroes2/gui/ui_kingdom.cpp
> +        const int32_t top_offset = TILEWIDTH - lighthouseTop.height();
@ihhub there we go :) [26bee86](https://github.com/ihhub/fheroes2/pull/6590/commits/26bee86aeab5b929a52921f6199695e6f530c0d6)

2023-02-14 15:40 UTC, ihhub approved these changes
@Osmodium , well done!

2023-02-14 19:17 UTC, oleg-derevenetz approved these changes

2023-02-15 02:41 UTC, merged

2023-02-15 02:42 UTC, ihhub commented
@Osmodium , thank you so much for your contribution to the project!

2023-02-15 08:57 UTC, Osmodium commented
> @Osmodium , thank you so much for your contribution to the project!

@ihhub , thank you for being patient with me :) It's a great project for one of the games I played alot, I hope to be able to contribute even more :)