Automate the work with AGG extraction tools
ihhub/fheroes2 pull request #6601
Opened 2023-02-09 21:36 UTC by oleg-derevenetz

Related to #6553

2023-02-11 08:39 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left few comments here. My biggest concern here is that we must separate tools for artists and put them into a separate package. My point is that if we ship them together with the application it might rise even more questions like why and what these tool do, are they needed to run the game, why they don't do anything and etc. What do you think?

2023-02-11 08:39 UTC, ihhub commented on .github/workflows/make.yml
> +            ./src/tools/icn2img
I recommend not to mix the main application with these tools. Knowing the reaction of users they will start asking questions and run these for no reason.

2023-02-11 08:39 UTC, ihhub commented on VisualStudio/tools/bin2txt/sources.props
> +    <ClCompile Include="..\engine\agg_file.cpp" />
I think this tool doesn't have so many dependencies on files. At least it shouldn't.

2023-02-11 08:39 UTC, ihhub commented on src/tools/bin2txt.cpp
> + *   Copyright (C) 2009 by Andrey Afletdinov <fheroes2@gmail.com>          *
Actually I wrote this tool completely few years ago (yeah, it's ugly as the purpose was to study bin files) so this copyright header is not needed :)

2023-02-11 09:55 UTC, oleg-derevenetz commented on src/tools/bin2txt.cpp
> + *   Copyright (C) 2009 by Andrey Afletdinov <fheroes2@gmail.com>          *
Yeah, that's what happening when using one specific file as a template :)

2023-02-11 15:42 UTC, oleg-derevenetz commented
Hi @ihhub

> My biggest concern here is that we must separate tools for artists and put them into a separate package.

I addressed your concerns in the latest commits. Also could you please take a look at images generated by the `til2img` tool? Are they fine?

2023-02-11 15:59 UTC, ihhub commented
Hi @oleg-derevenetz , I think we need to move TIL image reading to a separate place to be used by the engine and the tool. I can do this tomorrow.

2023-02-12 13:30 UTC, ihhub commented
Hi @oleg-derevenetz , the only question besides til2img tool I have why we removed the scripts? I thought they were very useful :(

2023-02-12 13:35 UTC, oleg-derevenetz commented
Hi @ihhub

> Hi @oleg-derevenetz , the only question besides til2img tool I have why we removed the scripts? I thought they were very useful :(

I can bring them back, but all they did was run `extractor` and then `icn2img` with certain parameters :) There is no complex logic or directory traversal. Why they are useful? :)

2023-02-12 14:27 UTC, ihhub commented
> Hi @ihhub
> 
> > Hi @oleg-derevenetz , the only question besides til2img tool I have why we removed the scripts? I thought they were very useful :(
> 
> I can bring them back, but all they did was run `extractor` and then `icn2img` with certain parameters :) There is no complex logic or directory traversal. Why they are useful? :)

They are very useful. I faced many people in my life who can't work in command line but they are experts in their field. So having a one-click solution is much better for them.

2023-02-12 14:58 UTC, oleg-derevenetz commented
Hi @ihhub

> They are very useful. I faced many people in my life who can't work in command line but they are experts in their field. So having a one-click solution is much better for them.

OK, I'll bring them back.

Regarding `til2img`, I see no difference with the new API :) Hope these images are fine. Here's what they look like (`ground32.til`):

![screen1](https://user-images.githubusercontent.com/32623900/218318653-0125b1d3-e055-45ba-af66-d6ef583bab68.jpg)
![screen2](https://user-images.githubusercontent.com/32623900/218318665-63caf574-822c-4f70-97f0-99c019eea20e.jpg)

2023-02-12 15:25 UTC, ihhub commented
Hi @oleg-derevenetz , I think I know why: please load KB.PAL palette within the application.

2023-02-12 15:32 UTC, oleg-derevenetz commented
@ihhub

> I think I know why: please load KB.PAL palette within the application.

Yeah, now they look much better :) Original `til2img` implementation didn't use a palette for some reason.

2023-02-12 15:33 UTC, ihhub commented
> @ihhub
> 
> > I think I know why: please load KB.PAL palette within the application.
> 
> Yeah, now they look much better :) Original `til2img` implementation didn't use a palette for some reason.

Hi @oleg-derevenetz , the original code had hardcoded palette from the game. We removed it and only few colors are present used in a message about missing resources.

2023-02-13 00:26 UTC, ihhub approved these changes

2023-02-13 00:26 UTC, merged

2023-02-13 00:27 UTC, ihhub commented
@oleg-derevenetz , huge thanks for your tremendous work!