Rewrite standard window generation code
ihhub/fheroes2 pull request #6605
Opened 2023-02-11 17:59 UTC by Districh-ru

fix #6547

Made rendering of a Standard window using game resources and connecting them by using simple transition pattern: 
![pattern](https://user-images.githubusercontent.com/113276641/218273365-5b9802ae-e535-4c45-8528-ccc50a8a3fa0.png)

Also added ability not to render the window background if only the borders are needed (in example for Castle, Battle dialogs).

![castle dialog](https://user-images.githubusercontent.com/113276641/218273157-f200b62c-435a-47d8-8d6a-714f542c322b.png)

<details><summary>Standard Window for Evil interface with and without background</summary>

![evil with background](https://user-images.githubusercontent.com/113276641/218273184-465da02e-1aef-4a2d-b0d3-46f9a3e58b39.png)

![evil without background](https://user-images.githubusercontent.com/113276641/218273192-6ffae5c4-50b6-4c63-a21a-001c38348b9b.png)

</details>

2023-02-11 22:54 UTC, oleg-derevenetz commented on src/engine/image.cpp
> +                const int32_t stepY = 1 << ( ( halfWidth - x ) / 2 + 1 );
What if `halfWidth` is more than 31?

2023-02-12 14:25 UTC, ihhub requested changes
Hi @Districh-ru , I left several comments in this pull request. Would you mind to take a look at them in your spare time?

2023-02-12 14:25 UTC, ihhub commented on src/engine/image.cpp
> +                    if ( isReverse ? ( ( y % stepY ) != offsetY ) : ( ( y % stepY ) == offsetY ) ) {
Could you please create a separate variable for **( y % stepY )** expression as it is difficult to read this condition?

Also we can optimize the condition:
```cpp
if ( isReverse == ( offset != offsetY ) )
```

2023-02-12 14:25 UTC, ihhub commented on src/engine/image.cpp
> +                        if ( !in.singleLayer() && out.singleLayer() && ( *( transformIn + offsetInX ) == 1 ) ) {
We can cache **!in.singleLayer() && out.singleLayer()** expression outside the loops.

2023-02-12 14:25 UTC, ihhub commented on src/engine/image.cpp
> +            uint8_t * transformOut2 = transformOut + width - 1;
We should avoid cryptic variable naming involving numbers. It is not easy to understand what number 2 stands for.

2023-02-12 14:25 UTC, ihhub commented on src/fheroes2/gui/ui_window.cpp
> +        const fheroes2::Sprite & horizontalSprite = fheroes2::AGG::GetICN( ( Settings::Get().isEvilInterfaceEnabled() ? ICN::SURDRBKE : ICN::SURDRBKG ), 0 );
Please cache **Settings::Get().isEvilInterfaceEnabled()** value in a separate variable.

2023-02-12 14:25 UTC, ihhub commented on src/fheroes2/gui/ui_window.cpp
> +                fheroes2::DitheringTransition( _output, backgroundOffsetX, backgroundOffsetY, _output, backgroundOffsetX, _windowArea.y + toOffsetY - transitionSize,
I can see that this is the only place (within this if-body where we use output image as input. Is it possible not to use it? If yes then we can simplify logic in **fheroes2::DitheringTransition()** in relation to **singleLayer()** calls.

2023-02-12 14:25 UTC, ihhub commented on src/fheroes2/gui/ui_window.cpp
> +        const fheroes2::Sprite & horizontalSprite = fheroes2::AGG::GetICN( ( Settings::Get().isEvilInterfaceEnabled() ? ICN::SURDRBKE : ICN::SURDRBKG ), 0 );
This class is in **fheroes2** so all calls within this method should be without **fheroes2**. This will improve readability of the code.

2023-02-12 17:14 UTC, Districh-ru commented on src/engine/image.cpp
> +                const int32_t stepY = 1 << ( ( halfWidth - x ) / 2 + 1 );
Hi @oleg-derevenetz, you are right it should not be more than 30.
I have not thought about so big transition length...
I've added a limit (`min(30,...)`).
But in practice so big transition length woun't be used. :)

2023-02-12 17:21 UTC, oleg-derevenetz commented on src/engine/image.cpp
> +                const int32_t stepY = 1 << ( ( halfWidth - x ) / 2 + 1 );
> But in practice so big transition length woun't be used. :)

Well, anyway it's better be safe than sorry :) There is a (wrong) opinion exists that shifting the variable to the left by the number of bits which is more than the variable size in bits will left the variable with zero value, although in fact it is an undefined behavior - not only the variable may in theory have a literally ANY value after this, but also the optimizer counts on the fact that such a shift will never ever happen.

2023-02-12 17:22 UTC, Districh-ru commented on src/fheroes2/gui/ui_window.cpp
> +                fheroes2::DitheringTransition( _output, backgroundOffsetX, backgroundOffsetY, _output, backgroundOffsetX, _windowArea.y + toOffsetY - transitionSize,
Hi @ihhub, here we use output as input because previously we rendered there copies of background image horizontally with transitions and now we use this duplicated image to make its copies vertically. I use `_output` to avoid making a temporary image.
All cases of `singleLayer()` are present in `DitheringTransition()` for possible future use in other places.
(We could also add there a scale factor for pattern: currently it changes step every 2 line, but it could bу not 2 ... but let's leave this to another PR when this feature will be needed.)

2023-02-12 17:25 UTC, Districh-ru commented on src/engine/image.cpp
> +            uint8_t * transformOut2 = transformOut + width - 1;
I'll try to avoid them in future. But sometimes it's hard to come up with names for variables. ;)

2023-02-12 17:26 UTC, Districh-ru commented on src/fheroes2/gui/ui_window.cpp
> +        const fheroes2::Sprite & horizontalSprite = fheroes2::AGG::GetICN( ( Settings::Get().isEvilInterfaceEnabled() ? ICN::SURDRBKE : ICN::SURDRBKG ), 0 );
Sure!

2023-02-12 17:29 UTC, Districh-ru commented on src/engine/image.cpp
> +                const int32_t stepY = 1 << ( ( halfWidth - x ) / 2 + 1 );
> Well, anyway it's better be safe than sorry :)

Absolutely agree!

2023-02-14 16:11 UTC, ihhub requested changes
Hi @Districh-ru , I put several suggestions here. Would you mind to take a look at them in your free time?

2023-02-14 16:11 UTC, ihhub commented on src/engine/image.cpp
> +                        if ( !out.singleLayer() ) {
Let's please simplify reading of this function as it is hard to read so many incapsulated blocks:
```cpp
if ( out.singleLayer() ) {
    continue;
}
... // the rest of the code.
```

The same for lines 1537, 1609 and 1630.

2023-02-14 16:11 UTC, ihhub commented on src/engine/image.cpp
> +                            }
If the input image is a single-layer image would be more efficient to just memset before the loops and later in the code only use `if ( !in.singleLayer() ) {` check?

Moreover, combining this comment and the comment above we can have:
```cpp
memset(...);
const bool copyTransform = !in.singleLayer() && !out.singleLayer();
...
// inside the loop
if ( copyTransform ) {
    *( transformOut + offsetOutX ) = *( transformIn + offsetInX );
}
```
What do you think?

2023-02-14 16:11 UTC, ihhub commented on src/fheroes2/gui/ui_window.cpp
> +            const Sprite & backgroundSprite = AGG::GetICN( ( isEvilInterface ? ICN::STONEBAK_EVIL : ICN::STONEBAK ), 0 );
If it is not difficult can we please move this if-body into a separate private method to simplify reading of the code?

2023-02-14 16:32 UTC, Districh-ru commented on src/engine/image.h
> +    // Make a transition to "in" image from left to right or vertically - from top to bottom. The direction of transition can be reversed.
Hi @ihhub, I'll add a link to https://en.wikipedia.org/wiki/Dither, but I didn't find this algorithm, I looked at dithered gradient images and decided to make our function as it is. :)

2023-02-14 16:55 UTC, Districh-ru commented on src/engine/image.cpp
> +                            }
We copy image and transform layer only for some particular pixels and if we set the whole transform layer to 0 before the loops we will also set the pixels, that are not rewritten in the loop and can have transform layer other than 0.
So I think it is not suitable here. :(

2023-02-14 17:20 UTC, Districh-ru commented on src/fheroes2/gui/ui_window.cpp
> +            const Sprite & backgroundSprite = AGG::GetICN( ( isEvilInterface ? ICN::STONEBAK_EVIL : ICN::STONEBAK ), 0 );
I've moved not the whole if-body but only the render of background sprite. I left here the transitions from borders to background as to move them to a new method we have to transfer many variables or compute them once again in this method.

2023-02-15 16:33 UTC, ihhub commented on src/engine/image.cpp
> +                            }
Ah, you're right. This is sad.

2023-02-15 16:42 UTC, ihhub commented
I included @zenseii into the list of reviewers as his button-related work depends on this pull request.

2023-02-15 16:49 UTC, ihhub approved these changes
Hi @Districh-ru , I approve this pull request but I will test it later for other window sizes to see how the algorithm behaves.

2023-02-15 18:52 UTC, Districh-ru commented
> Look at the shadow of the dialog overlaying the ocean between the town portal dialog and the file options dialog: ![image](https://user-images.githubusercontent.com/12501091/219122027-182e8c5b-b052-42d3-a796-ae89e5fb8b27.png)
> 
> In one it looks dithered in the other it is completely uniform.

Hi, @zenseii.
I'll try to fix this tomorrow: the original windows use the shadow from ICN, while the Standard Windows code makes shadow with `ApplyTransform` function. We can try to use shadow from ICN for this window also.

2023-02-17 00:36 UTC, ihhub commented
Hi @zenseii and @Districh-ru , if the original windows do not have proper shadows with effects let's fix them separately. This pull request is big enough 🙂

2023-02-17 15:23 UTC, Districh-ru commented
Hi @ihhub, @zenseii!
I found a simple solution to fix the window shadow and couldn't resist implementing it:
![изображение](https://user-images.githubusercontent.com/113276641/219694340-57773cf6-2225-4511-bed3-e394c02f8b5a.png)

2023-02-18 14:45 UTC, merged

2023-02-18 14:45 UTC, ihhub commented
@Districh-ru , thank you so much for this fix! I tested it on my side and the solution looks great! If we find something buggy we can fix it later.