Add a guide for graphical artists
ihhub/fheroes2 pull request #6625
Opened 2023-02-13 18:48 UTC by zenseii

This adds a guide for people looking to help with the graphical assets of the project.

Relates to https://github.com/ihhub/fheroes2/issues/6553

~~This still needs the part about the palette to image tool https://github.com/ihhub/fheroes2/pull/6621 so this guide will need to be merged after that PR.~~

~~This will also need to be amended once this PR is merged: https://github.com/ihhub/fheroes2/pull/6626~~

~~I also need to add links to the main page etc.~~

~~As stated in the first mentioned issue, this guide needs to be included in the relevant archive. I suppose the precompiled tools?~~

2023-02-14 15:35 UTC, ihhub requested changes
Hi @zenseii , I left several comments in this pull request. Could you please take a look at them when you have time?

2023-02-14 15:35 UTC, ihhub commented on docs/GRAPHICAL_ARTISTS.md
> +pack Price of Loyalty is present. These two AGG containers are located in the `DATA` folder of the original Heroes 2 installation.
**The Price of Loyalty** to be more precise :)

2023-02-14 15:35 UTC, ihhub commented on docs/GRAPHICAL_ARTISTS.md
> +The original game has its graphical assets stored in the `HEROES2.agg` container and potentially the `HEROES2X.agg` container if the expansion
Shall we call files instead of containers to be simpler?

2023-02-14 15:35 UTC, ihhub commented on docs/GRAPHICAL_ARTISTS.md
> +graphical assets into viewable PNG image files.
We can remove **image** word as just state **PNG files**.

2023-02-14 15:35 UTC, ihhub commented on docs/GRAPHICAL_ARTISTS.md
> +You can download the precompiled tools for your OS of choice here:
**operating system (OS)** just to avoid abbreviations without explanation.

2023-02-15 20:00 UTC, oleg-derevenetz approved these changes

2023-02-15 20:02 UTC, oleg-derevenetz commented
> "GRAPHICAL_ARTISTS" does sound like it contains credits for the graphical artists of the project.

Maybe something like "GRAPHICAL_ASSETS" then?

2023-02-17 00:47 UTC, ihhub commented on docs/GRAPHICAL_ARTISTS.md
> +[Linux Ubuntu ARM 64-bit](https://github.com/ihhub/fheroes2/releases/download/fheroes2-linux-arm-sdl2_dev/fheroes2_tools_ubuntu_arm64_SDL2.zip)
I have no clear opinion at the moment about including or excluding them from releases.

2023-02-17 00:49 UTC, ihhub approved these changes

2023-02-17 00:53 UTC, ihhub commented on docs/GRAPHICAL_ARTISTS.md
> +[Linux Ubuntu ARM 64-bit](https://github.com/ihhub/fheroes2/releases/download/fheroes2-linux-arm-sdl2_dev/fheroes2_tools_ubuntu_arm64_SDL2.zip)
If we decide to add the tools into the releases we cannot change these links as no releases contain the tools at the moment.

2023-02-17 00:53 UTC, merged

2023-02-17 00:53 UTC, ihhub commented
@zenseii , huge thanks for tackling this feature!