Memorize zoom level of the View World screen
ihhub/fheroes2 pull request #6640
Opened 2023-02-14 17:58 UTC by Districh-ru

close #6619

2023-02-14 18:00 UTC, Districh-ru commented
Hello @LeHerosInconnu!
Could you please check this PR in your spare time.

2023-02-15 16:31 UTC, ihhub requested changes
Hi @Districh-ru , I put few comments here. Would you mind to check them?

2023-02-15 16:31 UTC, ihhub commented on src/fheroes2/kingdom/view_world.h
> -        ZoomLevel _zoomLevel{ ZoomLevel2 };
I suggest to keep the previous code to avoid having an uninitialized member.

2023-02-15 16:31 UTC, ihhub commented on src/fheroes2/system/settings.h
> +    int32_t _viewWorldZoomLevel{ 2 };
It is good to avoid using hardcoded values. To minimize file dependencies I suggest to create a separate header file which will contain only `ViewWorldZoomLevel` enumeration (by the way it can be uint8_t as it doesn't have too many entries. Use this enumeration for `ViewWorld` and `Settings` classes. What do you think?

2023-02-15 16:43 UTC, Districh-ru commented on src/fheroes2/system/settings.h
> +    int32_t _viewWorldZoomLevel{ 2 };
Hi @ihhub!
In `settings.h` we already have enumerations for `AdventureMapScrollSpeed` and `MusicSource`. What if we put `enum class ViewWorldMode : uint8_t` there, as `zoomLevel` becomes a part of global game configuration?

2023-02-15 16:44 UTC, ihhub commented on src/fheroes2/system/settings.h
> +    int32_t _viewWorldZoomLevel{ 2 };
I think it will be better than just hardcoded values.

2023-02-15 16:50 UTC, Districh-ru commented on src/fheroes2/kingdom/view_world.h
> -        ZoomLevel _zoomLevel{ ZoomLevel2 };
I'll also change it to ZoomLevel1, as it is the default value in original game.

2023-02-16 15:07 UTC, ihhub approved these changes

2023-02-19 10:52 UTC, Branikolog approved these changes

2023-02-19 10:54 UTC, merged

2023-02-19 10:54 UTC, ihhub commented
@Districh-ru , many thanks for adding this improvement!

2023-02-21 12:32 UTC, LeHerosInconnu commented
Hello @Districh-ru,

> Hello @LeHerosInconnu! Could you please check this PR in your spare time.

I did some tests, it seems to work correctly.