Fix a few code smells, remove unused code
ihhub/fheroes2 pull request #6661
Opened 2023-02-16 21:27 UTC by oleg-derevenetz

2023-02-17 00:45 UTC, ihhub commented
Hi @oleg-derevenetz , it was used in the new map XML format which we scrapped over time.

2023-02-17 12:51 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left one question here. Could you please check it?

2023-02-17 12:51 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +        msg >> dummy;
This will work only if `dummy` is 0 but what if it is not? Should we at least add an assertion?

2023-02-17 12:57 UTC, oleg-derevenetz commented on src/fheroes2/world/world.cpp
> +        msg >> dummy;
Hi @ihhub If `dummy` is no 0, then it will be handled lust like any other corrupted save file. If we add an assertion here, app will crash on the failed assertion instead.

2023-02-17 13:00 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +        msg >> dummy;
In this case can we at least error log this case?

2023-02-18 12:28 UTC, ihhub approved these changes

2023-02-18 12:29 UTC, merged

2023-02-18 12:29 UTC, ihhub commented
@oleg-derevenetz , huge thanks for maintaining code quality!