Fix golem animation frames copy issue
ihhub/fheroes2 pull request #6694
Opened 2023-02-22 20:04 UTC by Districh-ru

fix #6689

2023-02-22 21:07 UTC, oleg-derevenetz commented
Hi @ihhub BTW we have a lot of the code like this:

https://github.com/ihhub/fheroes2/blob/3af8445a243f645e5ae6a06c27e61d3040644dc0/src/fheroes2/agg/agg_image.cpp#L1875

or this:

https://github.com/ihhub/fheroes2/blob/3af8445a243f645e5ae6a06c27e61d3040644dc0/src/fheroes2/gui/ui_font.cpp#L142

The problem here in both cases is that `insert()` takes the last parameter by const reference, and if reallocation occurs during an insertion, then this reference will be invalidated.

2023-02-22 21:25 UTC, Districh-ru commented
> Hi @Districh-ru it seems that situation is a bit worse then I thought:
> 
> https://en.cppreference.com/w/cpp/container/vector/insert
> 
> Using `insert()` with `first` and `last` iterators pointing into `*this` is undefined behavior in any case (see description of overload N 4), even if no reallocation occurs, so `reserve()` is not enough. It seems that there is no other way than using a temporary vector to be guaranteed to be safe.

Hi @oleg-derevenetz, and what do you think of using `push_back` (or `emplace_back`) in a loop for this case?

2023-02-22 21:32 UTC, oleg-derevenetz commented on src/fheroes2/agg/agg_image.cpp
> +                        _icnVsSprite[id].push_back( _icnVsSprite[id][copyFrame] );
Hi @Districh-ru this solution suffers from the same issue. `push_back()` gets the value to insert by const reference. Suppose that there is no room left and vector is forced to reallocate. Suppose it will reallocate first and only then it will access the reference that is passed as `push_back()` argument.

2023-02-23 00:23 UTC, ihhub commented
Hi @Districh-ru and @oleg-derevenetz , this is indeed a huge problem. We must fix it immediately.

2023-02-23 08:08 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                        _icnVsSprite[id].push_back( _icnVsSprite[id][copyFrame] );
Hi @oleg-derevenetz, I changed the code to make a copy of a vector element and then `std::move` it in in `emplace_back` to a vector.

2023-02-23 08:10 UTC, Districh-ru commented
Hi @ihhub and @oleg-derevenetz, I also made some changes to other parts of the code where I found `push_back` or `emplace_back` of a vector element to the same vector.

2023-02-23 09:53 UTC, oleg-derevenetz requested changes
Hi @Districh-ru It's really not THAT bad :) I just left a few comments, please take a look when you have time.

2023-02-23 09:53 UTC, oleg-derevenetz commented on src/fheroes2/campaign/campaign_data.cpp
> -                monsters.emplace_back( monsters.back().GetUpgrade() );
There is a different situation: `Monster::GetUpgrade()` returns a temporary, which is then will be added to the vector. So the temporary will be created first, and then inside `emplace_back()` only this temporary will be accessed through the rvalue reference (i.e. moved to the vector), not any of already existing vector elements, so this operation is safe.

2023-02-23 09:53 UTC, oleg-derevenetz commented on src/fheroes2/campaign/campaign_data.cpp
> -                monsters.emplace_back( monsters.back().GetUpgrade() );
The same situation as above: `emplace_back()` deals with temporary, not with existing element of `monsters`.

2023-02-23 09:53 UTC, oleg-derevenetz commented on src/fheroes2/dialog/dialog_recruit.cpp
> -        upgrades.emplace_back( upgrades.back().GetDowngrade() );
`Monster::GetDowngrade()` returns a temporary, not a reference to some already existing element of `upgrades`, so this operation is safe as well.

2023-02-23 09:53 UTC, oleg-derevenetz commented on src/fheroes2/gui/ui_campaign.cpp
> -                monsters.emplace_back( monsters.back().GetUpgrade() );
The same logic as above - the temporary object is added to the vector, not some element of the same vector.

2023-02-23 10:28 UTC, Districh-ru commented on src/fheroes2/campaign/campaign_data.cpp
> -                monsters.emplace_back( monsters.back().GetUpgrade() );
Hi @oleg-derevenetz, thanks for the explanations.
I reverted the changes in these files.

2023-02-23 10:50 UTC, oleg-derevenetz approved these changes

2023-02-23 14:03 UTC, ihhub requested changes
Hi @Districh-ru , I left one comment here. Could you please take a look?

2023-02-23 14:03 UTC, ihhub commented on src/engine/screen.cpp
> +                    const int32_t biggerResolutionWidth = resolutions[biggerId].width;
Would it makes sense to calculate a scale factor instead of width?

2023-02-23 14:15 UTC, Districh-ru commented on src/engine/screen.cpp
> +                    const int32_t biggerResolutionWidth = resolutions[biggerId].width;
Hi @ihhub, certainly, we can cache the scale factor here.

2023-02-23 14:31 UTC, ihhub approved these changes

2023-02-23 14:32 UTC, merged

2023-02-23 14:32 UTC, ihhub commented
@Districh-ru , thank you so much for these fixes!