Adjust recruitment window position on castle well and kingdom overview
ihhub/fheroes2 pull request #6709
Opened 2023-02-24 19:29 UTC by Kazhuu

Solves https://github.com/ihhub/fheroes2/issues/4749. The recruitment windows is lowered 2 pixels on castle well view and in kingdom overview centered over top part of the window.

2023-03-08 08:43 UTC, Branikolog commented
Sorry for the late response.
What about adjusting creature info window position too?
![image](https://user-images.githubusercontent.com/55348946/223664519-e5d16d15-e66d-4f33-bf7f-e81dabd5d8e6.png)
The same as recruiting window was made.

2023-03-11 16:25 UTC, Kazhuu commented
> Sorry for the late response. What about adjusting creature info window position too? ![image](https://user-images.githubusercontent.com/55348946/223664519-e5d16d15-e66d-4f33-bf7f-e81dabd5d8e6.png) The same as recruiting window was made.

Good catch! I now moved these as well Hopefully now all windows are centered like they should.

2023-03-16 18:37 UTC, LeHerosInconnu commented
Hello @Kazhuu and Branikolog,

> Hi, @Kazhuu ! Sorry for the late response.
> 
> > Hopefully now all windows are centered like they should.
> 
> Unluckily, windows in castle and hero info are shifted now too:
> ![image](https://user-images.githubusercontent.com/55348946/225640948-50d92bb5-bd0f-4185-b2dc-2853995446b3.png)

For this one, I think it would be better to center the window in the lower part of the screen so that it is possible to see clearly the numbers of the hero's primary skills:
![Hero screen cadre rouge 001](https://user-images.githubusercontent.com/43583994/225720075-278f2eb3-5d67-4037-9b43-c6e7c20de01e.png)

> ![image](https://user-images.githubusercontent.com/55348946/225641232-4a66aad1-dcb3-41c9-8a2d-aa5419abfff4.png)

For this one, I would leave it as it is, because it allows to see the creatures and their numbers below the window.

2023-03-19 02:23 UTC, ihhub commented
Hi @LeHerosInconnu , let's focus in this pull request only on changes which are related to the original issue. It is good to keep track on them.

2023-03-19 09:28 UTC, Kazhuu commented
I now did the changes so that the only kingdom overview troop info and recruit windows are moved, not those shown on castle and hero windows. I also adjusted the troop info window on kingdom overview when heroes and their troops are shown. This was not adjusted before.
![image](https://user-images.githubusercontent.com/11016113/226165974-b144ab4c-2198-4238-9fb5-f5444e3797e8.png)

2023-03-23 16:26 UTC, ihhub commented
Hi @Branikolog , please review this pull request.

2023-03-24 10:44 UTC, Branikolog approved these changes
I haven't found any issues here. 👍

2023-03-24 14:40 UTC, ihhub requested changes
Hi @Kazhuu , I put several comments here. Could you please take a look when you have time?

2023-03-24 14:40 UTC, ihhub commented on src/fheroes2/army/army_bar.h
> +    int32_t troopWindowOffsetY;
Please name newly added member of the class with an underscore character: **_troopWindowOffsetY**.

2023-03-24 14:40 UTC, ihhub commented on src/fheroes2/dialog/dialog.h
> +    int ArmyInfo( const Troop & troop, int flags, bool isReflected = false, int32_t windowOffsetY = 0 );
Please add **const** for `windowOffsetY`.

2023-03-24 15:38 UTC, Kazhuu commented
@ihhub I did the changes requested :+1:

2023-03-25 01:52 UTC, ihhub approved these changes

2023-03-25 01:52 UTC, merged

2023-03-25 01:52 UTC, ihhub commented
@Kazhuu , thank you so much for this improvement!