Gray out summon boat, town gate and town portal spells
ihhub/fheroes2 pull request #6729
Opened 2023-02-27 20:07 UTC by Kazhuu

Solves https://github.com/ihhub/fheroes2/issues/5822 by graying Town Gate and Town Portal spells instead of not showing them in the spell book while on a boat.

More discussion is needed on this. I also grayed out Summon Boat spell when on a boat, but of course this spell should be grayed out when not by the water or you summoned the boat already. What is the general idea what should be done here?

2023-02-28 13:58 UTC, LeHerosInconnu commented
Hello @Kazhuu,

There is a related discussion on this subject here: https://github.com/ihhub/fheroes2/discussions/4845. :)

2023-02-28 18:38 UTC, Kazhuu commented
I'll fix the town gate, town portal and summon boat spells in this PR to become grayed out. Then on the issue https://github.com/ihhub/fheroes2/discussions/4845 we fix the rest of the spells.

2023-03-02 19:28 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_spell.cpp
> +        int32_t boatDestination = fheroes2::getPossibleBoatPosition( &hero );
Hi @Kazhuu I recommend to add an assertion here like this:

```cpp
assert( Maps::isValidAbsIndex( boatDestination ) );
```

just in case to catch the potentially invalid use of Summon Boat spell due to some logic error now or in future.

2023-03-03 18:38 UTC, Kazhuu commented on src/fheroes2/heroes/heroes_spell.cpp
> +        int32_t boatDestination = fheroes2::getPossibleBoatPosition( &hero );
Good point! I added the assert here.

2023-03-03 20:40 UTC, oleg-derevenetz requested changes
LGTM except a few minor style issues.

2023-03-03 20:40 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_spell.cpp
> +        int32_t boatDestination = fheroes2::getPossibleBoatPosition( &hero );
BTW, I believe that this variable can now be `const`?

2023-03-03 20:40 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_base.cpp
> +            int32_t boatDestination = fheroes2::getPossibleBoatPosition( hero );
This variable can be `const`.

2023-03-03 20:47 UTC, oleg-derevenetz commented on src/fheroes2/spell/spell_info.cpp
> +    {
Also I recommend here to return `-1` immediately if `hero` is `nullptr` or is not a hero, because castle captains are not able to cast adventure spells. Something like this maybe:

```cpp
if ( hero == nullptr || !hero->isHeroes() ) {
    return -1;
}
```

2023-03-04 08:22 UTC, Kazhuu commented on src/fheroes2/heroes/heroes_spell.cpp
> +        int32_t boatDestination = fheroes2::getPossibleBoatPosition( &hero );
:+1:

2023-03-04 08:22 UTC, Kazhuu commented on src/fheroes2/heroes/heroes_base.cpp
> +            int32_t boatDestination = fheroes2::getPossibleBoatPosition( hero );
:+1:

2023-03-04 08:47 UTC, Kazhuu commented on src/fheroes2/spell/spell_info.cpp
> +    {
Yes this makes sense. I'll add these. However I was thinking would it better to take HeroBase as a const reference instead of a pointer. This way the first nullptr check can be skipped. However, now the `dynamic_cast` can throw `bad_cast` error. What is the policy of raised errors in this project. I saw few try ... catch blocks used. Or would it better we stick to the pointer here?

2023-03-04 10:17 UTC, oleg-derevenetz commented on src/fheroes2/spell/spell_info.cpp
> +    {
Hi @Kazhuu I just checked this and it seems that we can just get rid of `HeroBase` in this function completely and replace it by `Heroes`, because it is never called for a `HeroBase` instance. This way we get rid of `dynamic_cast` as well. I added the corresponding commit.

2023-03-04 10:21 UTC, oleg-derevenetz approved these changes

2023-03-04 10:46 UTC, Kazhuu commented on src/fheroes2/spell/spell_info.cpp
> +    {
Yeah much better. Thank you!

2023-03-05 16:25 UTC, ihhub reviewed
Hi @Kazhuu , I left just one small suggestion. Could you please take a look when you have free time?

2023-03-05 16:25 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> -        apply = isShipMaster() ? false : ActionSpellTownGate( *this );
Just in case I would recommend to add assertions in **ActionSpellTownGate() and ActionSpellTownPortal()** that a hero is not on water and the opposite assertion inside **ActionSpellSummonBoat()**. This is to prevent any bad coding in the future.

2023-03-05 18:42 UTC, Kazhuu commented on src/fheroes2/heroes/heroes_spell.cpp
> -        apply = isShipMaster() ? false : ActionSpellTownGate( *this );
Yes good idea! I added not on water assertions on town gate, town portal and summon boat spells. Not sure what you mean the opposite of hero is not on water to summon boat? Because summon boat can only be used form the land, not on water.

2023-03-06 16:02 UTC, ihhub approved these changes

2023-03-06 16:02 UTC, merged

2023-03-06 16:02 UTC, ihhub commented
@Kazhuu , thank you so much for this improvement!

2023-04-05 18:08 UTC, LeHerosInconnu commented
Hello @Kazhuu,

I did some tests with the summon boat spell.
It turns out that if there are no more neutral boats (not belonging to any player) or player-built boats available and there is at least one free square adjacent to the hero, the spell is not grayed out, as it should be, and if the hero casts the summon boat spell the message "Summon Boat failed!!!" is displayed.
This is what we want to remove with these improvements.


- Save file: Before boats 02.savh (multiplyer game)(video below).
There are two neutral boats (not belonging to any player) at the beginning of the scenario.
Troyan casts the summon boat spell twice, the two neutral boats are summoned near Troyan.
After that, the summon boat spell is not grayed out in Troyan's magic book, although it should be because there is no other boat to summon.
There is one free square adjacent to Natasha, but there is no additional boat available.
If Troyan casts the non-greyed spell, the message "Summon Boat failed!!!" is displayed. This is what we want to remove with these improvements.

https://user-images.githubusercontent.com/43583994/230159377-38156be6-52ef-4447-becd-e4026053ea6c.mp4

- Save file: Before boats 01.savh (multiplyer game)(video below).
There are four boats available, two neutral boats from the beginning of the scenario and two boats built at the Weed Patch shipyard.
Natasha casts the summon boat spell four times, the four boats are summoned near Natasha.
After that, the summon boat spell is grayed out in Natasha's magic book.
There is no free square adjacent to Natasha (and furthermore, there is no additional boat available).
In this case, everything works as intended.

https://user-images.githubusercontent.com/43583994/230160100-e0c07105-cdc0-4b7b-bfac-7f8352a0c9f4.mp4

- Save file: Before boats 02.savh (multiplyer game)(video below).
There are two neutral boats (not belonging to any player) at the beginning of the scenario.
Troyan casts the summon boat spell twice, the two neutral boats are summoned near Troyan.
After that, the summon boat spell is not grayed out in Troyan's magic book, although it should be because there is no other boat to summon.
There is one free square adjacent to Natasha, but there is no additional boat available.
If Troyan casts the non-greyed spell, the message "Summon Boat failed!!!" is displayed.
A boat is built at the Weed Patch shipyard.
Troyan casts the summon boat spell, the just built boat is summoned near Troyan.
After that, the summon boat spell is grayed out in Troyan's magic book.

https://user-images.githubusercontent.com/43583994/230160243-bf68e704-7641-47fc-ac65-f42bbb8adfad.mp4

- Save file: Before boats 03.savh (multiplyer game)(video below).
There are two neutral boats (not belonging to any player) at the beginning of the scenario.
A boat is built at the Bloodreign shipyard.
Troyan casts the summon boat spell twice, the two neutral boats are summoned near Troyan.
After that, the summon boat spell is not grayed out in Troyan's magic book, although it should be because there is no other boat to summon.
There is one free square adjacent to Troyan, but there is no additional boat available.
If Troyan casts the non-greyed spell, the message "Summon Boat failed!!!" is displayed.

https://user-images.githubusercontent.com/43583994/230160448-89c3153c-aee5-4896-af32-50b6afecd3c0.mp4

- Save file: Before boats 04.savh (multiplyer game)(video below).
There are two neutral boats (not belonging to any player) at the beginning of the scenario.
Troyan casts the summon boat spell twice, the two neutral boats are summoned near Troyan.
After that, the summon boat spell is not grayed out in Troyan's magic book, although it should be because there is no other boat to summon.
There is at least one free square adjacent to Natasha, but there is no additional boat available.
If Troyan casts the non-greyed spell, the message "Summon Boat failed!!!" is displayed.
A boat is built at the Bloodreign shipyard.
Troyan casts the summon boat spell, the just built boat is summoned near Troyan.
Then Troyan casts the summon boat spell and boats are built at the Bloodreign shipyard until all free squares adjacent to Troyan are occupied by boats.
After that, the summon boat spell is grayed out in Troyan's magic book.

https://user-images.githubusercontent.com/43583994/230160582-fa3030b1-8401-4b9e-9914-9f5bac8a97c4.mp4

Here are the save files (multiplyer game):
[Before boats 01 04.zip](https://github.com/ihhub/fheroes2/files/11161581/Before.boats.01.04.zip)

If the hero tries to cast the spell while it is grayed out, a message is displayed depending on the case.
Something like this:
Yellow title for all message windows:
"Summon Boat"

Window Texts;
If there is no boat available:
"There is no boat available to cast this spell."

If there is no free square near the hero:
"There is no free location at sea near the hero to cast this spell."

If there is no boat available and no free square near the hero:
"There is no boat available and no free location at sea near the hero to cast this spell."

2023-04-06 05:40 UTC, Kazhuu commented
hello @LeHerosInconnu could you make another issue with the same description? I could fix this separately. Commented here it gets lost easily because this PR is already merged.