Clean up AI priority tasks if attacker was killed
ihhub/fheroes2 pull request #6745
Opened 2023-03-03 07:44 UTC by idshibanov

Currently AI could rush to castle defence even if enemy hero threatening it was taken out. Adding more information to track & finally taking advantage of attack tasks.

2023-03-04 19:24 UTC, oleg-derevenetz reviewed
Hi @idshibanov I just left an optional proposal, could you please take a look?

2023-03-04 19:24 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                        _priorityTargets.erase( secondaryTask );
Is there a possibility that one of the secondary tasks will have the same tile index as the primary task? In this case `task` reference will be invalidated right during iteration over the `task.secondary`. As far as I understand, this should not happen now, but I propose to add `assert( secondaryTask != tileIndex )` before this line just in case.

2023-03-05 07:07 UTC, ihhub requested changes
Hi @idshibanov , I put several comments in this pull request. Could you please take a look?

2023-03-05 07:07 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal.h
> +        std::vector<int> secondary;
Are we expecting to have more than 1 task on a single tile? Should we use **std::set**?

2023-03-05 07:07 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                        _priorityTargets.erase( secondaryTask );
Since **_priorityTargets** is a map we can break from this loop afterwards.

2023-03-05 13:04 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                        _priorityTargets.erase( secondaryTask );
Although _priorityTargets is a map, there could be multiple castles threatened by the same hero, so we need to clean it up anyway. At the same time thinking about this I'll have to cover another edge case (multiple heroes beside 1 castle) so I'll update this logic shortly.

2023-03-05 13:06 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal.h
> +        std::vector<int> secondary;
I could switch to a set to make it more explicit for the future.

2023-03-05 15:05 UTC, ihhub approved these changes

2023-03-05 18:04 UTC, Districh-ru approved these changes
I played one test map and one original map making threats for AI player and allowing to kill my hero and the AI heroes returned to their deals after defeating my hero.
👍

2023-03-05 18:54 UTC, oleg-derevenetz approved these changes

2023-03-05 21:19 UTC, merged