Add virtual keyboard support for touch devices
ihhub/fheroes2 pull request #6750
Opened 2023-03-03 15:06 UTC by ihhub

2023-03-03 16:19 UTC, oleg-derevenetz commented
I suggest to remove the "LANG" button for now, because I anticipate questions from users like "why can't I switch the language?"

2023-03-03 16:25 UTC, ihhub commented
> I suggest to remove the "LANG" button for now, because I anticipate questions from users like "why can't I switch the language?" and add it later when this feature will be fully supported.

Hi @oleg-derevenetz , I disabled the button for now. We need it to at least align the last row properly.

2023-03-03 16:31 UTC, ihhub commented
Hi @zenseii , could you please add 7, 8 and 9 letters to button's font in a separate pull request if you have spare time?

2023-03-03 16:32 UTC, ihhub commented
I will try to add 7, 8 and 9 letters tomorrow.

2023-03-03 19:51 UTC, oleg-derevenetz reviewed
Hi @ihhub I just left a few proposals, please take a look when you have time :)

2023-03-03 19:51 UTC, oleg-derevenetz commented on src/fheroes2/dialog/dialog_selectcount.cpp
>      le.OpenVirtualKeyboard();
I suppose we need to do something with external virtual keyboard here and in other similar places - I mean, there should be no situation when we show both the system virtual keyboard and the our own at the same time. Currently `System::isHandheldDevice()` does not intersect with `LocalEvent::OpenVirtualKeyboard()`, but It would be good to make the logic more explicit. Maybe add something like `System::isNativeVirtualKeyboard()`...?

2023-03-03 19:51 UTC, oleg-derevenetz commented on src/fheroes2/gui/ui_keyboard.cpp
> +    std::vector<std::vector<uint8_t>> getNumericCharacterLayout( const fheroes2::SupportedLanguage language )
Why `uint8_t` here and in other similar places, and not just `char`?

2023-03-03 19:51 UTC, oleg-derevenetz commented on src/fheroes2/gui/ui_keyboard.cpp
> +                singleCharString = StringLower( singleCharString );
Since we have the single-character buttons (I mean, they are not multibyte), we can just `StringLower()` them all at once: convert `letters` to the `std::string()`, then apply `StringLower()` to the whole string and then replace individual letters using the new characters from that string instead of creating a special `std::string` for every single character.

2023-03-03 19:51 UTC, oleg-derevenetz commented on src/fheroes2/gui/ui_keyboard.cpp
> +            buttons.back().emplace_back( _( "Keyboard|BACK" ), 60, isEvilInterface, []( KeyboardRenderer & renderer ) {
It would be good to verify somewhere here that target vector (`buttons` in this particular case) is not empty before calling `back()`, because if it is empty, then it is undefined behavior. And maybe use intermediate variables like `lastButtonRow` or something to not call `back()` everywhere.

2023-03-03 19:51 UTC, oleg-derevenetz commented on src/fheroes2/gui/ui_keyboard.cpp
> +            buttons.back().back().button.disable();
In C++17, `emplace_back()` returns a reference to the inserted element (and `emplace()` returns an iterator pointing to the emplaced element) which might be handy in cases like this (to not write these cryptic `back().back()` and `back().front()`) :)

2023-03-03 19:52 UTC, Districh-ru reviewed
Hi @ihhub!
For the first glance I have a couple of small suggestions:
1. For me the buttons are small enough (on my cell phone) and we have enough space (640x480 px) for the bigger keyboard window. So I suggest to enlarge the buttons or to add extra space between them.
<details><summary>fheroes2 on a cell phone</summary>

![2023-03-03_224058](https://user-images.githubusercontent.com/113276641/222812117-41bdb35c-1c04-4840-8b69-f92efdbccd54.png)
</details><details><summary>Keyboard that I use on a cell phone (for comparison)</summary>

![2023-03-03_223502](https://user-images.githubusercontent.com/113276641/222812326-c7df82ab-ceb3-4887-9ce9-9aa004191ac5.png)
</details>

2. Maybe besides of adding "7", "8", and "9" we could add the symbols for Shift key ("▲") and Backspace ("◄"). Or rename them to something like "CAPS L" and "BKSP" - this is discussible.

2023-03-04 00:40 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
> +    std::vector<std::vector<uint8_t>> getNumericCharacterLayout( const fheroes2::SupportedLanguage language )
Ah, this is a leftover from the initial implementation. I will fix it.

2023-03-04 00:42 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
> +                singleCharString = StringLower( singleCharString );
Moreover, we can return `std::string` from layouts since we work with single-char strings.

2023-03-04 04:20 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
> +            buttons.back().back().button.disable();
Yup. I just wanted to not overcomplicate code but I will try to redo it a bit.

2023-03-04 04:21 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
> +            buttons.back().emplace_back( _( "Keyboard|BACK" ), 60, isEvilInterface, []( KeyboardRenderer & renderer ) {
That's a good point. I will add checks and assertions.

2023-03-04 04:22 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
>      le.OpenVirtualKeyboard();
I was thinking about this. Ideally we should have only one virtual keyboard. I will ask players who use Vita to show how the keyboard looks like.

2023-03-04 09:29 UTC, Districh-ru requested changes
Hi @ihhub, I found a small bug. Could you address it please when you have time. :)

The "UPP" button flashes twice when pressed:

https://user-images.githubusercontent.com/113276641/222890586-3fa2cdf4-b156-4a00-b934-3e816a1dcb53.mp4

The same behavior is on my cell phone, but not noticeable as at this time the button is covered with my finger. :)

2023-03-05 10:00 UTC, Districh-ru reviewed
Hi @ihhub. I have a couple of suggestions for the keyboard appearance. Could you take a look in your spare time.

2023-03-05 10:00 UTC, Districh-ru commented on src/fheroes2/gui/ui_keyboard.cpp
> +    const int32_t inputAreaOffset{ 2 };
When we are talking about handheld devices we have to take into account that they have higher density of pixels, so the resulting image is smaller than on PC monitor.
I ran fheroes2 on my cell phone in 640x480 and found that the keyboard buttons are located to close to each other IMHO.
I changed the keyboard parameters and got this variant, which is better for me. (This variont was tested only on PC).
![изображение](https://user-images.githubusercontent.com/113276641/222952599-edd897ae-4527-4ba1-be5a-457d6028eb62.png)
<details><summary>The changed parameters</summary>

```cpp
    const int32_t buttonOffset{ 10 };
    const int32_t defaultButtonWidth{ 35 };
    const int32_t defaultButtonHeight{ 35 };
    const fheroes2::Size windowSize{ 560, 330 };
    const fheroes2::Point offsetFromWindowBorders{ 25, 70 };
```

</details>

But I can set the native phone resolution 1440x720 and will get a small keyboard:
![изображение](https://user-images.githubusercontent.com/113276641/222953687-8aa00b98-df20-416e-a9cc-61f1b9517168.png)

So I can also propose not to use the constants here, but calculate the variables according to the current resolution. This could be done in a new PR. :)

2023-03-05 10:00 UTC, Districh-ru commented on src/fheroes2/gui/ui_keyboard.cpp
> +                                    []( const KeyboardRenderer & ) { return DialogAction::LowerCase; } );
I suggest placing the Caps Lock and Backspace buttons on the bottom row next to the space (123 and LANG can be placed to the left and right of OKAY), as other languages can have more than 7 letters in the bottom row, for example in Russian in each row of the keyboard there are 2 letters more than in English.

2023-03-05 12:51 UTC, LeHerosInconnu commented
Hello @ihhub,

> This feature is applicable for Android, PS Vita and Switch devices.

This could possibly be useful on a PC too. :)
This could be configurable, at least, in the game settings file.
What do you think?

2023-03-05 15:13 UTC, ihhub commented
> Hello @ihhub,
> 
> > This feature is applicable for Android, PS Vita and Switch devices.
> 
> This could possibly be useful on a PC too. :) This could be configurable, at least, in the game settings file. What do you think?

This can be done in a separate pull request. This PR is a basis for the future work so we need to keep the changes minimally required here.

2023-03-05 15:15 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
> +    const int32_t inputAreaOffset{ 2 };
I will update the parameters to have bigger buttons but we need to keep in mind that the number of letters per row can be much more as you pointed out in a separate comment. We have to preserve the size of buttons for any layout.

2023-03-05 15:15 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
> +                                    []( const KeyboardRenderer & ) { return DialogAction::LowerCase; } );
I took an idea from my phone's layout :) I think these nitpicks we can do in a separate pull request as the code structure allows to easily change any layout.

2023-03-05 15:58 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
> +    const int32_t inputAreaOffset{ 2 };
I enlarged the window keeping some space for longer letter rows. This is just a bit shorter than your proposal. Ideally for big resolutions we have to resize the whole window, not only buttons as edit box should be visible as well.

2023-03-05 16:02 UTC, ihhub commented
Hi @Districh-ru , what do you think about LANG button? Should we create an icon for it as well? On my phone it is a globe for example.

2023-03-05 17:25 UTC, Districh-ru commented
> Hi @Districh-ru , what do you think about LANG button? Should we create an icon for it as well? On my phone it is a globe for example.

Hi @ihhub, yes we can make something like globe.
In the next two days I can try to make something looking like a globe in 10x10 (or 12x12) pixels and put it instead of another unused letter. It will look like this: ![изображение](https://user-images.githubusercontent.com/113276641/222975716-e49f46fa-339f-4167-9a78-30cf10fe98b0.png)   
![изображение](https://user-images.githubusercontent.com/113276641/222975737-d5e3063d-28a6-4871-8a62-ad9237557606.png)

But in current PR we can fully hide this button as currently we support only English. And also disabled LANG button may produce questions from users - "how to enable it?", or "maybe something is wrong with my game files", so I propose to hide it if there is no other language to be switched.

2023-03-05 17:33 UTC, Districh-ru requested changes
Hi @ihhub, I have one comment. Could you please address it when you have time:
According to [Microsoft documentation](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file) and the [Linux naming rules](https://www.cyberciti.biz/faq/linuxunix-rules-for-naming-file-and-directory-names/) the ":" symbol should be removed from our keyboard for naming files or there would be a save error.

2023-03-05 17:44 UTC, oleg-derevenetz commented
@Districh-ru

> According to [Microsoft documentation](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file) and the [Linux naming rules](https://www.cyberciti.biz/faq/linuxunix-rules-for-naming-file-and-directory-names/) the ":" symbol should be removed from our keyboard for naming files or there would be a save error.

There is no problem with colon on *NIX:

```
oleg@gentoo ~/Temp/xx $ ls -l
total 0
-rw-r--r-- 1 oleg oleg 0 Mar  5 20:41 :aaa:
```

And even though there will be problems with it on Windows, this will simply lead to the appearance of the "There was an issue during saving" dialog. Nothing terrible will happen.

2023-03-05 17:55 UTC, Districh-ru commented
> There is no problem with colon on *NIX:
> And even though there will be problems with it on Windows, this will simply lead to the appearance of the "There was an issue during saving" dialog. Nothing terrible will happen.

@oleg-derevenetz, thanks for clarifying this!
So as the keyboard will be used only on handheld devices (not on Windows) we can leave the colon.
If in future the keyboard will be used on Windows we could remove the colon symbol only for this OS.

2023-03-05 18:00 UTC, Districh-ru approved these changes

2023-03-06 05:40 UTC, ihhub commented
Hi @oleg-derevenetz and @Districh-ru , I am okay to remove LANG button but the space button might be centered. What are you thoughts?

2023-03-06 05:42 UTC, ihhub commented
Hi @Branikolog please review this pull request as the highest priority as it is must have for the release.

2023-03-06 06:29 UTC, oleg-derevenetz commented
> I am okay to remove LANG button but the space button might be centered. What are you thoughts?

Can't this button be hidden/not drawn? And as a last resort we can make two shift buttons :)

2023-03-06 06:55 UTC, Districh-ru commented
I agree with @oleg-derevenetz proposal.
If we hide LANG button there will be a blank space between Space and Backspace - I'm OK with it.

2023-03-06 11:18 UTC, Branikolog commented
@ihhub 
Also, backspace and shift arrows for evil interface are brown. Is it possible to make the more "grayish"?

2023-03-06 14:19 UTC, ihhub commented
Hi @oleg-derevenetz and @Districh-ru , I hid LANG button as well as UP button for Numeric layout. Please take a look at the screenshots.

2023-03-06 14:19 UTC, ihhub commented
> @ihhub Also, backspace and shift arrows for evil interface are brown. Is it possible to make the more "grayish"?

I believe we need to modify palette used for this operation.

2023-03-06 14:37 UTC, ihhub commented
> @ihhub Also, backspace and shift arrows for evil interface are brown. Is it possible to make the more "grayish"?

It is fixed as well.

2023-03-06 15:20 UTC, oleg-derevenetz commented
@ihhub

> I hid LANG button as well as UP button for Numeric layout. Please take a look at the screenshots.

IMHO LGTM. I'm OK with the blank space too.

2023-03-06 15:27 UTC, Districh-ru approved these changes
👍

2023-03-07 12:38 UTC, Branikolog approved these changes

2023-03-07 14:16 UTC, merged