Strategic AI economy update
ihhub/fheroes2 pull request #6756
Opened 2023-03-04 17:35 UTC by idshibanov

Adding a kingdom budget into consideration. AI heroes now should focus on collecting missing resources based on current castle build order.

2023-03-09 16:36 UTC, ihhub requested changes
Hi @idshibanov , I put just few comments here. Could you please check them?

2023-03-09 16:36 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_castle.cpp
> +        for ( BudgetEntry & budgetEntry : _budget ) {
Please add a separate line to differentiate 2 loops.

2023-03-21 15:16 UTC, ihhub commented
Hi @idshibanov , could you please address given comment in this pull request once you have spare time? We would like to merge these changes for the upcoming release.

2023-03-22 19:38 UTC, idshibanov commented
> Hi @idshibanov , could you please address given comment in this pull request once you have spare time? We would like to merge these changes for the upcoming release.

I've delayed coming back to this change because I wasn't totally happy with the AI's behaviour after. The values might need some fine tuning. I'll find some time.

2023-04-25 16:31 UTC, ihhub requested changes
Hi @idshibanov , I left 2 questions in this pull request. Could you please check them when you have spare time?

2023-04-25 16:31 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_castle.cpp
> +            }
I think this condition needs an adjustment that not all castles allow to build monster dwellings of level 6.

2023-04-25 16:31 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_castle.cpp
> +                    requirements = requirements.max( PaymentConditions::BuyBuilding( race, order.building ) );
We use payment conditions for a building as a requirement. Are we taking into account that for instance only one resource might be required like Gems and another case that we need only small part of the building price. For example, we need only extra 100 gold.

2023-04-27 15:18 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_castle.cpp
> +            }
Thanks for the explanation!

2023-04-27 17:24 UTC, oleg-derevenetz approved these changes

2023-04-28 00:49 UTC, merged

2023-04-28 00:50 UTC, ihhub commented
@idshibanov , thank you so much for this improvement!