Add missing part of Captain's Quarter in Sorceress Town
ihhub/fheroes2 pull request #6775
Opened 2023-03-07 15:51 UTC by ihhub

close #3843

all credits go to @golden-lining

![image](https://user-images.githubusercontent.com/19829520/223474751-e2f1c6fc-8535-43a6-9bef-78143f27f43c.png)

2023-03-07 16:27 UTC, oleg-derevenetz approved these changes

2023-03-07 16:40 UTC, Districh-ru reviewed
Great work, @golden-lining!
I have one suggestion/question. Cold you please address it when you have time.

The original image (the right part of the Captain's Quarter) as I think has a shadow on the roof from the castle. So maybe it'll be good to make it a bit brighter.
![изображение](https://user-images.githubusercontent.com/113276641/223488293-b1aa659a-3da5-452d-8684-eaee1dfca681.png) -> ![изображение](https://user-images.githubusercontent.com/113276641/223488702-467893d2-3cac-402e-8d66-40a62b66c71e.png)
(I edited the image by copy-paste, so it only represents the idea, not the real result)

What do you think? :)

2023-03-11 06:31 UTC, Districh-ru requested changes
Hi @ihhub! I left one suggestion for building ROI. Could you have a look when you have time.

The updated sprite for Captain's Quarter looks great. Well done @golden-lining! 👍

2023-03-11 06:31 UTC, Districh-ru commented on src/fheroes2/castle/castle_building_info.cpp
> +            return { 204, 122, 37, 52 };
If we move the `x` coordinate to еду left by 19 px we also have to increase the `width` by the same value as the right part of the sprite retains on the same place. :)
```suggestion
            return { 204, 122, 37, 71 };
```

As I checked the changed ROI does not overlap with others, but IMHO it should be different for Town and Castle as for the Castle case.
In this PR a click on the right part of the Castle wall gives the info about the Captain Quarters.
Maybe we have to adjust all ROIs for all Castle buildings in a separate PR.

2023-03-11 06:47 UTC, ihhub commented on src/fheroes2/castle/castle_building_info.cpp
> +            return { 204, 122, 37, 52 };
Sure. I will revert this change.

2023-03-11 06:56 UTC, Districh-ru approved these changes

2023-03-11 07:01 UTC, merged