Fix mini-map update when entering Teleport or Whirlpool
ihhub/fheroes2 pull request #6780
Opened 2023-03-08 10:39 UTC by Districh-ru

This PR fixes the absence of mini-map update before entering a Teleport or Whirlpool.

The condition used to check if Hero has moved to a Teleport does not work properly so I moved the mini-map redraw after every hero move to `heroes_move.cpp`.

fheroes2:

https://user-images.githubusercontent.com/113276641/223682822-7c3bd128-9f65-442b-825d-48ab74be2f2f.mp4

This PR:

https://user-images.githubusercontent.com/113276641/223691078-1787beca-26b3-4073-bbe3-bf4c622e1a0b.mp4

2023-03-10 10:40 UTC, Branikolog commented
Hello, @Districh-ru !
Minimap doesn't updates after disembarking. Only after another hero moves, the dot corresponding disembarked hero moves.

2023-03-10 10:59 UTC, Districh-ru commented
> Hello, @Districh-ru !
> Minimap doesn't updates after disembarking. Only after another hero moves, the dot corresponding disembarked hero moves.

Hello, @Branikolog !
Thanks for checking. I'll fix this bug a little later today.

2023-03-11 05:14 UTC, ihhub commented
Hi @Districh-ru , was the issue pointed by @Branikolog addressed?

2023-03-11 05:34 UTC, ihhub requested changes
Hi @Districh-ru , I put multiple suggestions in this pull request. I am not sure that all of them are valid so analyze them carefully. Could you please check them in your free time?

2023-03-11 05:34 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +    radar.SetRenderArea( { 0, 0, world.w(), world.h() } );
I notice one possible issue with radar code:
```cpp
void Interface::Radar::Redraw( const bool redrawMapObjects )
{
...
if ( _hide ) {
   ...
}
else {
   if ( redrawMapObjects ) {
       // Only here we update ROI.
       RedrawObjects( Players::FriendColors(), ViewWorldMode::OnlyVisible );
   }
}
...
}
```
It looks like we have 2 places where ROI is not reset properly:
- when radar is hidden
- when we don't want to render map objects

I think we should update the ROI for them. What do you think?

2023-03-11 05:34 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +        I.GetRadar().SetRenderArea( hero.GetScoutRoi( false ) );
I am just curious: **ignoreDirection** is used to expand radar ROI to be update. While I see the benefit not dong extra calculations the code is quite complex to maintain. What do you think if we always return enlarged by 1 ROI for hero's scouting?

2023-03-11 05:34 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +                I.GetRadar().SetRenderArea( { artifactPosition.x, artifactPosition.y, 1, 1 } );
In the future we need to use another approach in order to make the code flexible enough and to avoid explicit calls of radar. For instance, a callback function when a hero starts a movement, changes their position or have changes in their skills or inventory. We don't need to address it right now but it might be a long term solution for us.

2023-03-11 05:34 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +                fheroes2::Rect radarRoi( Maps::GetPoint( dst_index ), { 1, 1 } );
I understand the idea to minimize the size of radar's ROI to be updated but we shouldn't do such micro optimization as we could have a chance that a new capturing object would be added and somebody forget to update this code. I suggest to just update ROI which is equivalent of hero's scout area. The same applies for Haunt spell.
Moreover, we can just update radar ROI on a completion of any action, avoiding corner cases like for pickup resources, whirlpools and etc. What do you think?

2023-03-11 05:34 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.h
> +        void setAbandonedMineObjectType() const;
Please make this function static. We would like to move out all specific to objects functions out of the class.

2023-03-11 06:33 UTC, Districh-ru commented
> Hi @Districh-ru , was the issue pointed by @Branikolog addressed?

Hi, @ihhub. Yes, @Branikolog's issue was addressed in https://github.com/ihhub/fheroes2/pull/6780/commits/a75edf20d3adc6354f640fa335f4d03250ecae27. :)

2023-03-11 06:50 UTC, Districh-ru commented on src/fheroes2/game/game_startgame.cpp
> +    radar.SetRenderArea( { 0, 0, world.w(), world.h() } );
Hi @ihhub, you are right. I've protected from one possible case. I suddenly got it yesterday, and reproduced it only once.
I'll apply your suggestion as it will protect us from all possible cases including possible asynchronous setting of ROI and calling Redraw.

2023-03-11 07:06 UTC, Districh-ru commented on src/fheroes2/heroes/heroes_action.cpp
> +        I.GetRadar().SetRenderArea( hero.GetScoutRoi( false ) );
You mean always act like `ignoreDirections = true` ?
We can do this, the direction is only used for hero moving to the next tile. It is most often action, but enlarging the ROI will not drastically reduce the game performance. As after making proper radar updates for every hero action I thought to make (in a separate PR) a check "wasFogCleared" and if not - update only hero position (2x2 rect).

2023-03-11 07:27 UTC, Districh-ru commented on src/fheroes2/heroes/heroes_action.cpp
> +                I.GetRadar().SetRenderArea( { artifactPosition.x, artifactPosition.y, 1, 1 } );
Such function, which will give us tile numbers of updated tiles will be very useful not only for radar, but for adventure map also.
Currently resources and artifacts are located in one tile so we update the radar only for that tile. If we do not plan to bring the bigger objects to the game this will work for every resource/artifact. But in that case we will have the "big" object position and size ad we will than use something like: ` I.GetRadar().SetRenderArea( { artifact.x, artifact.y, artifact.width, artifact.height } );
And IMHO there is no need to update the whole hero scout ROI if we have to change only one tile and we know where it is .:)

Putting radar call into `tile.QuantityReset()` is also a not a good idea, but `QuantityReset()` might call some other UI function...

2023-03-11 08:42 UTC, Districh-ru commented on src/fheroes2/heroes/heroes_action.cpp
> +                fheroes2::Rect radarRoi( Maps::GetPoint( dst_index ), { 1, 1 } );
Than we have to decide what we want:
- Have an unified function witch is launched for about 90 cases of action objects in hero scout area and is needed only in about 10 cases in mostly in 1x1 or 2x2 area.
- Have explicit calls for radar but only when it is needed but with more complicated logic.
Before this PR the Scout ROI was updated every time after on the hero move after hero actions. But we have tracked all actions  and added all needed radar calls.
Also if we had 80 of 90 cases were the radar update is needed than the better solution will be to call it every time rather than calling it in each of 80 calls.
Talking about spells - it is other action and redrawing radar after every possible spell is also is not a solution.

And if we will add some new action object with a completely new action function and if we will display it on radar, yes we will have to make it properly render including removal after pickup or changing color after capture.

But a good Idea is to make a function that will automatically get the object size and tell it to radar like a reverse function to `Maps::Tiles::getIndexOfMainTile()`
I think such function might be introduced but in a separate PR. I'll ad a `TODO`.

2023-03-11 12:50 UTC, Branikolog approved these changes
Good work, @Districh-ru !
Thanks for your valuable contribution. :)

2023-03-11 14:28 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +        I.GetRadar().SetRenderArea( hero.GetScoutRoi( false ) );
Yes, I meant to just enlarge the whole area by 1 tile no matter if hero stands or walks. Seem like you did this so it is great.

2023-03-11 14:34 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +                fheroes2::Rect radarRoi( Maps::GetPoint( dst_index ), { 1, 1 } );
Hi @Districh-ru , evaluating the size of an object is very easy:
- get object ID via **Maps::Tiles::GetObjectUID()** call (or `getObjectIdByObjectIcnType()`)
- put into a stack all nearby tiles and run
- for each tile pushed in the stack run **doesObjectExist()** method
- if the method returns true push all neighbours and update ROI
- repeat till the stack is empty

2023-03-11 14:36 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +                fheroes2::Rect radarRoi( Maps::GetPoint( dst_index ), { 1, 1 } );
If you think that implementation of this function would take time then please leave a TODO comment in the code for the future change.

2023-03-11 14:37 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +                fheroes2::Rect radarRoi( Maps::GetPoint( dst_index ), { 1, 1 } );
Actually, you've done this :)

2023-03-11 14:37 UTC, Districh-ru commented on src/fheroes2/heroes/heroes_action.cpp
> +                fheroes2::Rect radarRoi( Maps::GetPoint( dst_index ), { 1, 1 } );
Thanks for the approach, @ihhub!
Something similar came into my mind. I'll do it in a separate PR.

2023-03-11 14:41 UTC, ihhub approved these changes

2023-03-11 15:15 UTC, ihhub commented
Hi @oleg-derevenetz and @zenseii could you please review this pull request today if you have time?

2023-03-11 21:11 UTC, oleg-derevenetz approved these changes

2023-03-12 01:58 UTC, merged

2023-03-12 01:58 UTC, ihhub commented
@Districh-ru , thank you so much for this fix!