[WIP] Optimize adventure map: cache fog directions and do not render objects under the fog
ihhub/fheroes2 pull request #6809
Opened 2023-03-10 20:00 UTC by Districh-ru

An attempt to optimize rendering of adventure map.
Fog direction is updated only:
1. On map load (fully).
2. On human turn start (fully).
3. When fog is cleared (only for the cleared tile and around it).

All map objects are not rendered if the map tile is fully under the fog.

2023-03-18 12:21 UTC, Branikolog approved these changes

2023-03-18 16:08 UTC, ihhub requested changes
Hi @Districh-ru , I left several comments in this pull request. Would you mind to take a look at them?

2023-03-18 16:08 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +                    }
To avoid code duplication we can do like this:
```cpp
const bool isFriendlyAI = conf.IsGameType( Game::TYPE_HOTSEAT ) && Players::isFriends( player->GetColor(), Players::HumanColors() );

#if defined( WITH_DEBUG )
if ( isFriendlyAI || player->isAIAutoControlMode() ) {
#else
if ( isFriendlyAI ) {
#endif
    // Fully update fog directions for allied AI players in Hot Seat mode as the previous move could be done by opposing player.
    Interface::GameArea::updateMapFogDirections();
}
```

What do you think about this?

2023-03-18 16:08 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +    Interface::GameArea::updateMapFogDirections();
Is there a reason of doing it or we are being precautious? Should we update directions after we load tiles from a save?

2023-03-18 16:08 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.cpp
> +    if ( DIRECTION_ALL == _fogDirection ) {
What if we cache all directions into a map? Would it be a faster solution?

2023-03-18 17:14 UTC, Districh-ru commented on src/fheroes2/ai/ai_hero_action.cpp
> +            if ( Players::isFriends( hero.GetColor(), Players::HumanColors() ) ) {
Hi, @ihhub.
I did not put this logic into `world.cpp` as it does not contain code for interface and does not `#include "interface_gamearea.h"` or `"map_tiles.h"`.
But this logic can be placed there and work for both Human and AI-friend player.
If you think it is OK I can move the **updateMapFogDirections()** to `world.cpp`.

2023-03-18 17:33 UTC, Districh-ru commented on src/fheroes2/game/game_startgame.cpp
> +    Interface::GameArea::updateMapFogDirections();
For a single player game we can update all fog directions after we load a map/save. In Hot Seat mode we need to update it for each player.
I'll put the fog directions update after map load and add a condition here: if `conf.IsGameType( Game::TYPE_HOTSEAT )`

2023-03-18 18:30 UTC, oleg-derevenetz commented on src/fheroes2/ai/ai_hero_action.cpp
> +            if ( Players::isFriends( hero.GetColor(), Players::HumanColors() ) ) {
Hi @ihhub to be honest I don't like an idea to over-mix the game logic with UI. They are already a bit over-mixed for my taste.

2023-03-18 18:32 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles.cpp
> -    const int around = GetFogDirections( color );
Calculating directions for the whole map is more computation expensive task comparing to a single render of Adventure map for 640x480 game resolution by currently used `around = GetFogDirections( color )` approach. Especially for big maps.
In map viewing mode (no hero moves) we render 4 frames per second. For 640x480 resolution we have 14*14=196 tiles to get fog direction. Computing fog directions for 144x144 map will be: 144*144/196 = 105,8 times more expensive (it is equal to 26,5 seconds of rendering with current approach).
Yes, it is expensive. :(
But if the player spends more than half of minute for a turn it reduces the mean CPU usage.
Also we have to take into account that player, as i think, use resolutions more than 640x480. And when hero moves or player drags the map the more Redraws per second are performed.

Also this information is used for rendering other parts of the map, which also reduces the CPU usage.

For a Single player I'll address your comment and make the full recalculation of fog directions only on map load.
For Hot Seat we can redo the shading adventure map on player change: not recalculate the fog, but simply render fog image in the place of adventure map.
I can try to do it in a separate PR, currently I'll put a TODO for this.

I'll also place a TODO for making an array for all human players. I thought about it, but did not do as when making this array we have to take into account that there are alliances and fog directions are the same in one alliance. This can be done. :)

I'll also try tomorrow to redo the **updateFogDirectionsInArea()** to avoid using of **!Maps::isValidDirection( _index, it )** and **Maps::GetDirectionIndex( _index, it )**

Thanks @ihhub the tip on how to do a better optimization.

2023-03-18 18:35 UTC, Districh-ru commented on src/fheroes2/game/game_startgame.cpp
> +                    }
Sure, thanks!

2023-03-18 18:35 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles.h
> +        uint16_t getFogDirection() const
OK. :)

2023-03-18 18:48 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles.cpp
> +    if ( DIRECTION_ALL == _fogDirection ) {
Do you mean to make an array in **World** class?
I made a cache in **Tiles** as we have to keep fog direction for every map tile. And while rendering the Adventure map the fog direction for current tile is mostly used (only in some places we check the fog direction of neighbor tile).
Maybe some calls will be faster, but we will have to calculate tile index for every fog direction call. While in this PR we simply call `if ( tile.getFogDirection() == DIRECTION_ALL && drawFog )` to check do we need to render map objects.

2023-03-19 06:55 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles.cpp
> -    const int around = GetFogDirections( color );
Hi @ihhub,  we calculate fog direction by checking an array of directions and if there is fog we logically add this direction to _fogDirection. So we can not avoid the use of directions and the best way to access tiles around knowing the direction is using **GetDirectionIndex()**.
But as we know the world size and the tile index we can check for index outside the world without use of **isValidDirection()**.
I redone the logic of this check and it gives up to 40% computation speed increase: from 0.8-1 ms to 0.45-0.55 ms full fog directions update for XL maps with uncovered fog.

The other approach could be: caching all fog data to avoid many calls of **isFog()** and than calculate fog direction using directions pattern and this cached fog. This approach will force us to make a vector for isFog data.

2023-03-19 19:55 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles.cpp
> -    const int around = GetFogDirections( color );
I updated the fog directions calculation logic and quick tested it on a couple maps. It gives a performance boost in the release build.
@ihhub, could you please check the new code when you have time.

2023-03-20 13:51 UTC, ihhub commented on src/fheroes2/ai/ai_hero_action.cpp
> +            if ( Players::isFriends( hero.GetColor(), Players::HumanColors() ) ) {
Good points, guys.

2023-03-20 14:52 UTC, ihhub requested changes
Hi @Districh-ru , I left few more suggestions in this pull request. Could you please check them when you have some time?

2023-03-20 14:52 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.cpp
> +            const int32_t fogTileIndex = x + y * worldWidth;
`y * worldWidth` can be cached in the loop above. The performance depends on the number of elements.

2023-03-20 18:19 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles.cpp
> +    std::vector<bool> isFog( static_cast<size_t>( fogWidth ) * fogHeight, true );
Hi @ihhub, thanks for the advice.
Using **uint8_t** here made fog directions calculation to run up to 2 times faster.

2023-03-20 18:49 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles.cpp
> +    std::vector<bool>::iterator isFogIter = isFog.begin();
Hi, @ihhub, I used access to the vector by index to avoid using of iterators. It also slightly simplified the vector accessing logic.

2023-03-23 15:33 UTC, ihhub commented
Hi @Districh-ru do these changes fix #2169 as well?

2023-03-23 16:21 UTC, ihhub requested changes
Hi @Districh-ru , I put few more comments and questions. Would you mind to check them?

2023-03-23 16:21 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +                        const bool isFriendlyAI = Players::isFriends( player->GetColor(), Players::HumanColors() );
Could you please explain more this new chunk of code? I don't really understand why we do only for hot-seat and why we can't directly use **player->GetFriends()** and use binary AND with **Players::HumanColors()**?

Also I suggest to move calculations of friend colors into a separate method and this function has become too large.

2023-03-23 17:13 UTC, Districh-ru commented on src/fheroes2/game/game_startgame.cpp
> +
Sure!)

2023-03-23 17:49 UTC, Districh-ru commented on src/fheroes2/game/game_startgame.cpp
> +                        const bool isFriendlyAI = Players::isFriends( player->GetColor(), Players::HumanColors() );
Hi @ihhub, I moved these calculations into a separate method in Anonymous namespace.

Currently in fheroes2 in Hot Seat mode all moves of all human players allies are shown and the enemy AI movement is shown on tiles discovered from fog by all human players.
In master build it is done "automatically" as fog directions are generated on every gameArea render.
In this PR we cache fog directions so we have to recalculate them in this case.
In Single player there is no need to do this as we always have one fog directions cache for the only human player (and his allies).

Maybe it is not perfectly correct, but this is how fheroes2 master build works now. And there could be quections: if human players are enemies in Hot Seat mode then they will be able to see area of each other while AI moves.
But lets first discuss (if needed) how Hot Seat mode should work in these situations (in a separate discussion) and solve Hot Seat related issues in a separate PR.

So we cannot simply use **player->GetFriends()** as it will give me current AI friends colors and this is needed only if this AI player is an ally of one of human players.

2023-03-23 17:49 UTC, Districh-ru commented on src/fheroes2/maps/maps.cpp
> +    const bool isHumanOrHumanFriend = Players::isFriends( playerColor, Players::HumanColors() ) || !isAIPlayer;
OK.

2023-03-24 13:10 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles.cpp
> +    const int32_t worldWidth = world.w();
Sure, I added assertion.

2023-03-24 13:11 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles.cpp
> +    const int32_t TopLeftDirectionOffset = -1 - fogDataWidth;
Ow, for some unknown reason I named it from a capital letter.
Done. :)

2023-03-25 01:49 UTC, ihhub reviewed
Hi @Districh-ru , everything looks good to me. I left 2 more comments to polish the code, which don't affect the logic.

2023-03-25 01:49 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +    void updateFogDirectionsForHotSeatAIMove( const Player * player )
I initially meant to create a function called **getAIFriends()** which will return an integer. Then inside the original switch case we could call:
```cpp
Maps::Tiles::updateFogDirectionsInArea( { 0, 0 }, { world.w(), world.h() }, getAIFriends( player ) );
```
To be consistent with the same code for human players which has **updateFogDirectionsInArea()** call as well.

I am still fine with the current approach, just the name of the function is too complex :)

2023-03-25 01:49 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +        int32_t friendColors = 0;
Should we check or assert that the player is AI? Also we should assert **player**.

2023-03-25 06:23 UTC, Districh-ru commented on src/fheroes2/game/game_startgame.cpp
> +    void updateFogDirectionsForHotSeatAIMove( const Player * player )
Hi @ihhub, the logic for friends is currently complex and in one case it returns friend color for one human player and in the other - for all human players (and they can be hostiles for the current AI). And it has to be currently used in Hot Seat mode. But IMHO it should be changed in future: uncovering for for friends of all human players is not a good idea, but first we have to discuss how to behave in Hot Seat at all.
So I made a separate function for all Hot Seat fog uncover for AI. Doing so I also slightly separated this mode from the unified code for all modes.
I renamed the function to **hotSeatAIFogColors()** and made it to return int for **updateFogDirectionsInArea()** as you proposed. :)

2023-03-25 06:26 UTC, Districh-ru commented on src/fheroes2/game/game_startgame.cpp
> +        int32_t friendColors = 0;
I added an assertion for **player** and another one to assert that it is AI move - it won't be worse if we check it as this function is not made for human players: it will work, but it is too complex for this case.

2023-03-25 09:49 UTC, ihhub approved these changes

2023-03-25 10:52 UTC, ihhub commented
Hi @oleg-derevenetz , could you please take a sneak peak on this pull request when you have time? I know that you haven't dig into rendering code but you might find some obvious mistakes which we missed🙂

2023-03-25 10:55 UTC, oleg-derevenetz commented
@ihhub yes of course, I'll do it later today.

2023-03-25 13:54 UTC, oleg-derevenetz reviewed
Hi @Districh-ru I usually don't touch map rendering, so I left a few questions, could you please take a look when you have time?

2023-03-25 13:54 UTC, oleg-derevenetz commented on src/fheroes2/gui/interface_gamearea.cpp
> +                if ( !drawHeroes || ( isTileUnderFog && ( isUpperTileUnderFog || !hero->isShipMaster() ) ) ) {
Why we still can draw heroes here even if `drawHeroes` is `false`?

2023-03-25 13:54 UTC, oleg-derevenetz commented on src/fheroes2/gui/interface_gamearea.h
> +        static void updateMapFogDirections();
It would be good to add/update the descriptions to the new/heavily reworked functions in headers to describe (in general terms) what they do and what they return.

2023-03-25 13:54 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_tiles.cpp
> +                fogDataIndex += topLeftDirectionOffset;
Can the `fogDataIndex` become negative here (for example near top left edge of the map)? Can it become too big (out of `fogData` range) later after all these increments?

2023-03-25 15:28 UTC, Districh-ru commented on src/fheroes2/gui/interface_gamearea.cpp
> +                if ( !drawHeroes || ( isTileUnderFog && ( isUpperTileUnderFog || !hero->isShipMaster() ) ) ) {
Hi @oleg-derevenetz, thanks for the review.
This is a regression: we will render all not moving AI heroes. I reverted the initial check for `!drawHeroes` and do all other checks after it.

2023-03-25 15:29 UTC, Districh-ru commented on src/fheroes2/gui/interface_gamearea.h
> +        static void updateMapFogDirections();
I added a short description for this function and for other new one in `game_startgame.cpp`

2023-03-25 15:29 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles.cpp
> +                fogDataIndex += topLeftDirectionOffset;
After the first implementation of this approach I put here assertions for these cases. And after checks I removed them to speed-up this code.

`fogDataIndex` is equal to x + fogCenterDataOffsetY =  x + y * fogDataWidth + 1 - minX + ( 1 - minY ) * fogDataWidth  =
= ( x + 1 - minX ) + ( y + 1 - minY ) * fogDataWidth

And if we add `topLeftDirectionOffset` = -1 - fogDataWidth we will get:
( x + 1 - minX ) + ( y + 1 - minY ) * fogDataWidth -1 - fogDataWidth =
=  ( x - minX ) + ( y - minY ) * fogDataWidth

For the top left edge where minX and MinY are equal to 0  we will get: ( 0 - 0 ) + ( 0 - 0 ) * fogDataWidth = 0.

The same is for the other edge case, fogDataWidth and fogDataHeight both includes extra 2 tiles and here we shift 2 tiles to the right and 2 to the bottom after all increments..

2023-03-25 16:10 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_tiles.cpp
> +                fogDataIndex += topLeftDirectionOffset;
I don't know whether the absence of assertions gives any noticeable gain, and if this gain is not actually noticeable, I recommend to bring them back. Even if now the logic looks good, assertions are useful to protect against programming errors in future if logic is changed somehow. They can be turned off if needed by defining the `NDEBUG`macro (it is defined for Android release builds, but not for Windows release builds yet).

2023-03-25 16:46 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles.cpp
> +                fogDataIndex += topLeftDirectionOffset;
Thanks for the explanation. I added assertions.

2023-03-25 19:32 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_tiles.cpp
> +    const int32_t centerfogDataIndexLimit = fogDataSize + topLeftDirectionOffset;
Shouldn't this be `fogDataSize + ( topLeftDirectionOffset * 2 )`?

2023-03-25 19:54 UTC, oleg-derevenetz approved these changes

2023-03-26 01:20 UTC, merged

2023-03-26 01:20 UTC, ihhub commented
@Districh-ru , huge thanks for these improvements!