Swedish translation update.po
ihhub/fheroes2 pull request #6841
Opened 2023-03-14 18:40 UTC by Mr-Bajs

2023-03-15 13:16 UTC, Mr-Bajs commented
> Hi, @Mr-Bajs. I left several comments. Please have a look when you have the time. Also I kindly ask that you make any future PRs follow our limit of 400 changed lines per translation PRs as per our Translation guide. Right now you have a total of 685 changed lines between deleted and added: ![image](https://user-images.githubusercontent.com/12501091/225312370-3f2730bd-5855-4a47-aff0-9d1356097ae2.png)

Sure

2023-03-15 13:17 UTC, Mr-Bajs commented on files/lang/sv.po
> +msgstr "Anfa"
Translated, but's unclear how it will look in the messagebar.

2023-03-15 13:28 UTC, Mr-Bajs commented on files/lang/sv.po
> +msgstr "%{attacker}' anfall förblindar %{target}!"
Okej, i added a -nas at the end of %{attacker} and a -na att the end of %{target}. 
It will output Enhörningarnas anfall förblindar alverna! which is more correct. It will be incorrect of there is just a single %{attacker} and a single %{target}, but i guess it will be more correct than not to add this.

I added a fuzzy tag because i'm unsure of whats the best approach.

2023-03-16 15:53 UTC, ihhub requested changes
Hi @Mr-Bajs , I put few comments here. Could you please take a look at them?

2023-03-16 15:53 UTC, ihhub commented on files/lang/sv.po
> +msgstr "Inte tillräckligt med guld (%{gold}"
Closing bracket is missing **)**.

2023-03-16 15:53 UTC, ihhub commented on files/lang/sv.po
> +msgstr "Flyttade %{monster}: från %{src} till %{dst}."
Square brackets are missing: **[** and **]**. These are x, y coordinates so brackets are important.

2023-03-16 15:53 UTC, ihhub commented on files/lang/sv.po
> +#, fuzzy
Are we going to translate these? fuzzy comment marks that the translation is going to be skipped.

2023-03-16 16:11 UTC, Mr-Bajs commented on files/lang/sv.po
> +#, fuzzy
The translation is very bad, more or less means large elves, same as for druids. Leave the fuzzy for know. Most creatures are decent enough for now. I'll review the creatures elves, ogres, druids, roc and liches thats not well translated in the next translation.

2023-03-17 00:38 UTC, ihhub approved these changes

2023-03-17 00:39 UTC, merged

2023-03-17 00:39 UTC, ihhub commented
@Mr-Bajs , thank you so much for this translation update!