Adjusted number of resources subtracted in event messages.
ihhub/fheroes2 pull request #6854
Opened 2023-03-17 16:46 UTC by slawomir-witkowski

fix #6795

2023-03-19 03:21 UTC, ihhub requested changes
Hi @slawomir-witkowski , I proposed an alternative approach to fix the problem. Could you please take a look at it and see if it is a valid one?

2023-03-19 03:21 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
>          if ( event.resource.GetValidItemsCount() ) {
I suggest to do a simplified version of this fix:
```cpp
void ShowEventDayDialog()
{
    const Kingdom & myKingdom = world.GetKingdom( Settings::Get().CurrentColor() );
    const EventsDate events = world.GetEventsDate( myKingdom.GetColor() );

    Funds funds = myKingdom.GetFunds();

    for ( const EventDate & event : events ) {
        Funds fundsToUpdate;
        if ( event.resource.GetValidItemsCount() ) {
            const Funds fundsBefore = funds;
            funds = funds + event.resource;
            funds.Trim();
            fundsToUpdate = funds - fundsBefore;
        }

        if ( fundsToUpdate ) {
            fheroes2::showResourceMessage( fheroes2::Text( event.title, fheroes2::FontType::normalYellow() ),
                                           fheroes2::Text( event.message, fheroes2::FontType::normalWhite() ), Dialog::OK, fundsToUpdate );
        }
        else if ( !event.message.empty() ) {
            fheroes2::showStandardTextMessage( event.title, event.message, Dialog::OK );
        }
    }
}
```
This should be enough to fix the initial problem. What do you think?

2023-03-19 05:48 UTC, slawomir-witkowski commented on src/fheroes2/game/game_startgame.cpp
>          if ( event.resource.GetValidItemsCount() ) {
Hi @ihhub, this doesn't work. The problem is that at this point myKingdom.GetFunds(); returns funds that have already been reduced by a call to AddFundsResource(event.resource) in kingdom.cpp:262.  
We need a way to store information about how much each event subtracted for each kingdom in the current day.

2023-03-19 07:42 UTC, Branikolog commented
Hello, @slawomir-witkowski 
After scenario restart I still got messages, which I got on previous game:
![image](https://user-images.githubusercontent.com/55348946/226160957-962b11c6-4ee0-42c4-b233-6cfb09ead00a.png)
![image](https://user-images.githubusercontent.com/55348946/226160971-5544a808-34dc-48b9-b667-c9a43ec1f5e7.png)
The second one is which I've established in map editor.
But the first (-1000) was showed on previous game, when a player didn't have resources anymore. Now It appears before the main message.

2023-03-19 16:00 UTC, slawomir-witkowski commented
Initially I focused on daily events. Now I added support for Map Events as well. @Branikolog Castle generates 1000gold/day, so a daily event can display -1000 every day. If you still see problems, can you attach your map to the issue?

2023-03-20 15:02 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
>          if ( event.resource.GetValidItemsCount() ) {
Ah, you are right. Actually we have a much bigger problem here:
**World::NewDay()** is called for the whole day which updates all statuses for players, especially updating resources. Let's imagine this situation:
- we play in hot-seat mode 1 vs 1
- my turn first, yours second
- you completed the turn and you know that you have 5000 gold in your kingdom
- a new day starts deducting 10,000 gold from each player
- I attack your hero and you need to surrender to save Dragon but you couldn't as your gold now is zero

In this case the logic is wrong as you haven't started your turn so you must have that 5,000 gold.

Hi @LeHerosInconnu, could you please verify this scenario?

2023-03-20 15:32 UTC, LeHerosInconnu commented on src/fheroes2/game/game_startgame.cpp
>          if ( event.resource.GetValidItemsCount() ) {
It works correctly in the original game.

2023-03-20 19:22 UTC, slawomir-witkowski commented on src/fheroes2/game/game_startgame.cpp
>          if ( event.resource.GetValidItemsCount() ) {
Hi guys, IMO this problem deserves a separate issue. We have to consider all resource updates and do them in the right moment.

Consider an opposite situation when players get +10k bonus. Player first to act can use the gold to buy an army and kill another player before he has a chance to use his bonus.

2023-03-21 01:10 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
>          if ( event.resource.GetValidItemsCount() ) {
Hi @slawomir-witkowski , as confirmed the logic for new day is not correct so your changes and the logic are actually correlate to each other. I foresee that even after your fix other would find that the number of resources in the bottom-right corner is not updated (@LeHerosInconnu missed that for now). Your proposed solution is indeed fixing the problem but since the original code is wrong the solution looks more like a temporary patch (any other solution would look the same to be honest).

If we move events out of NewDay() method and execute them once with and without windows then we could solve 3 existing problems at once. Right now even if we go with the proposed solution we would need to redesign it due to other 2 highlighted issues. What do you think?

2023-03-21 07:02 UTC, slawomir-witkowski commented on src/fheroes2/game/game_startgame.cpp
>          if ( event.resource.GetValidItemsCount() ) {
Ok, I added a change that will delay updating resources until your turn. Now you can save the dragon. However, I don't see the problem with resources in bottom-right corner not being updated.

2023-03-21 11:50 UTC, Branikolog commented
Hi, @slawomir-witkowski !
I've tested on daily events exactly. The problem is that there appear several messages from previously played games (which showed the substracted value on previous game). So, starting new game for several times comes up with several messages.
Your last fix solved the problem with restart.
But after we load the game on the next turn we'd see two messages for the player loaded the game. The same happens if we load the game, skip 1 turn and then restart the scenario.

https://user-images.githubusercontent.com/55348946/226594880-cc3ee58b-e782-4cdd-9899-612063abe245.mp4

2023-03-21 18:47 UTC, slawomir-witkowski commented
@Branikolog Thank you for this video. It allowed me to find and fix the problem.

2023-04-01 14:22 UTC, ihhub requested changes
Hi @slawomir-witkowski . I put few more suggestions in this pull request. Would you mind to take a look once you have spare time?

2023-04-01 14:22 UTC, ihhub commented on src/fheroes2/resource/resource.h
> +    Funds GetUpdate( const Funds & ) const;
It is not clear what exactly this method does at first place. I suggest to just remove it or rename in a way what it reflects what it actually does. Also please add the name of the input argument.

2023-04-01 14:22 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +const EventsDate Kingdom::ActionNewDayResourceUpdate()
In order to avoid unnecessary double event loops and also not to mix UI and logic this method can accept an `std::function`. For AI it is going to be nullptr while for humans it is going to be passed as a lambda function:
```cpp
[]( const EventDate & event, const Funds & funds ) {
    if ( funds ) {
        fheroes2::showResourceMessage( fheroes2::Text( event.title, fheroes2::FontType::normalYellow() ), fheroes2::Text( event.message, fheroes2::FontType::normalWhite() ), Dialog::OK, funds );
    }
    else if ( !event.message.empty() ) {
        fheroes2::showStandardTextMessage( event.title, event.message, Dialog::OK );
    }
};
```
so then we don't need to have extra functions to run events for the second time. After this we:
- remove **ShowEventDayDialog()** function
- within **Interface::Basic::HumanTurn()** method
```cpp
...
    if ( !isload ) {
        if ( 1 < world.CountWeek() && world.BeginWeek() ) {
            ShowNewWeekDialog();
        }

       auto lambdaFunction = ...;
        ActionNewDayResourceUpdate( lambdaFunction ); // or directly define here.
        ...
```
- inside **Interface::Basic::StartGame()** method after line `world.ClearFog( player->GetColor() );` for AI we call **ActionNewDayResourceUpdate( nullptr )**.

At the end the code becomes smaller and we still don't mix logic and UI. What do you think?

2023-04-02 10:10 UTC, slawomir-witkowski commented on src/fheroes2/kingdom/kingdom.cpp
> +const EventsDate Kingdom::ActionNewDayResourceUpdate()
Hi, I made the suggested changes.

2023-04-03 00:53 UTC, ihhub requested changes
Hi @slawomir-witkowski , I added few more comments and questions here. We've almost completed it. Would you mind to check them?

2023-04-03 00:53 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +                    world.ClearFog( player->GetColor() );
Could you please explain why we need to clear fog here?

2023-04-03 00:53 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +                    if ( !loadedFromSave )
Please add parenthesis for this if-body. It would be easier to read.

2023-04-03 00:53 UTC, ihhub commented on src/fheroes2/resource/resource.h
> +    Funds CalculateEventResourceUpdate( const Funds & eventFunds ) const;
I think this method shouldn't belong to this class as it's for a very specific case. Usually developers just create a separate helper function outside the class to address specific cases. For instance you can take on a mess which still exist in Maps::Tiles class where many non-generic methods were added in the past.

What do you think, @oleg-derevenetz ?

2023-04-03 00:53 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +        Funds fundsUpdate = GetFunds().CalculateEventResourceUpdate( event.resource );
Please make this variable const.

2023-04-03 00:53 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +            Funds fundsToUpdate = hero.GetKingdom().GetFunds().CalculateEventResourceUpdate( event_maps->resources );
Please make this variable const.

2023-04-03 15:35 UTC, slawomir-witkowski commented on src/fheroes2/game/game_startgame.cpp
> +                    world.ClearFog( player->GetColor() );
This shouldn't be here. My mistake.

2023-04-03 16:34 UTC, oleg-derevenetz commented on src/fheroes2/resource/resource.h
> +    Funds CalculateEventResourceUpdate( const Funds & eventFunds ) const;
@ihhub I'm fine with the current solution where this auxiliary function is moved to the namespace.

2023-04-04 01:11 UTC, ihhub approved these changes

2023-04-05 12:03 UTC, Branikolog approved these changes

2023-04-06 00:46 UTC, merged

2023-04-06 00:46 UTC, ihhub commented
@slawomir-witkowski , huge thanks for these changes!