sk.po created
ihhub/fheroes2 pull request #6867
Opened 2023-03-19 15:27 UTC by Jaromir-Skirkanic

Slovak translation file created

2023-03-20 13:41 UTC, ihhub requested changes
Hi @Roxterat , I added one comment here. Could you please take a look at it?

2023-03-20 13:41 UTC, ihhub commented on src/fheroes2/gui/ui_language.h
> +        Slovak,
Since you are adding a new language which uses CP1250 please modify `generateAlphabet()`, `generateButtonAlphabet()` and `isAlphabetSupported()` functions within **ui_font.cpp** to support it.

2023-03-20 19:11 UTC, Roxterat commented
> Hi, @Roxterat.
> 
> I believe you have set the file to use the Ukrainian plural forms so please change this use the default forms for your language. You can do this in Translation->Properties: ![image](https://user-images.githubusercontent.com/12501091/226435258-27368093-aa58-45f3-9240-f877ea1f0bdb.png)

You are right indeed, now the plural's 'n' variable even makes sense.

2023-03-20 21:46 UTC, joyinko commented
@Roxterat , nice to see Slovak translation effort! I am on the boat if you like me to help with. cheers!

2023-03-20 21:52 UTC, Roxterat commented
@joyinko Indeed I have just started with Slovak translation, though it will possibly end up similar to Czech I have thought of taking my own approach to make it as authentic as possible. And of course any contribution will help the development of the effort.

2023-03-20 22:10 UTC, joyinko commented
@Roxterat  that is the right way to go imo, just let me know how I can support you. Again, thanks for bringing this up.

2023-03-21 02:34 UTC, Roxterat commented
> Hi @Roxterat , I added one comment here. Could you please take a look at it?

@ihhub taken care of, waiting for review.

2023-03-21 02:58 UTC, ihhub approved these changes

2023-03-21 02:59 UTC, merged

2023-03-21 02:59 UTC, ihhub commented
@Roxterat , huge thanks for your contribution to the project!