Update dk.po (31.3.23)
ihhub/fheroes2 pull request #6868
Opened 2023-03-19 15:37 UTC by Stisen1

mostly skill naming

2023-03-20 08:58 UTC, Stisen1 commented
@zenseii 

Done. I thought this title would be to vague. But of course the reviewers must have a certain repetoire of pull request titles, in order to get as good of an overview as possible. 

Furthermore I will try to make lesser line-changes to the dk.po file in the future, so that it doesn't feel like too much of a chore to get through from time to time. 

Maybe I should go for 30-50 lines at a time?

2023-03-21 12:31 UTC, Stisen1 commented on files/lang/dk.po
> +msgstr "Ballisten"
I have no idea why I wrote "ballisten" there!... I think I have done what you asked me to do now. My local directory has been updated to this date, and I can see a list of your changes in the "history" channel. 

I have copied a version of this new file into another directory outside "fheroes2", so I finally can start editing my incomplete mess of a translation :D

2023-03-22 07:56 UTC, Stisen1 commented on files/lang/dk.po
> +msgstr "Ballisten"
Hi, @zenseii 

I had a crying baby and an angry wife by the time of my request process. I believe you should be able to see a pull request called "Update danish translation" accompanied with explainational comments just about now.

It really makes my work a lot easier, now that I can save my po-edits as a mo-file and test it directly inside the game itself. There's a lot of issues with the font-sizes and misunderstandings with what contexts the translations pop-up in, that I need to figure out and explore as I go on with the translation process. It just got way more fun :-D

2023-04-15 17:00 UTC, ihhub requested changes
Hi @Stisen1 , I left 2 comments in this pull request. Could you please check them?

2023-04-18 01:05 UTC, ihhub approved these changes

2023-04-18 01:06 UTC, merged

2023-04-18 01:06 UTC, ihhub commented
@Stisen1 , thanks a lot for this update!