Improve AI fog discovery logic
ihhub/fheroes2 pull request #6913
Opened 2023-03-30 11:19 UTC by ihhub

2023-03-30 13:40 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left one suggestion, please take a look when possible.

2023-03-30 13:40 UTC, oleg-derevenetz commented on src/fheroes2/world/world_pathfinding.cpp
> +                for ( size_t currentNodeId = lastProcessedNode + 1; currentNodeId < nodesToExplore.size(); ++currentNodeId ) {
Is there any way to rename this variable somehow? We already have `currentNodeIdx` and now we have also `currentNodeId` which is very similar and can be easily confused with the former one.

2023-03-30 13:41 UTC, idshibanov approved these changes

2023-03-30 13:56 UTC, ihhub commented on src/fheroes2/world/world_pathfinding.cpp
> +                for ( size_t currentNodeId = lastProcessedNode + 1; currentNodeId < nodesToExplore.size(); ++currentNodeId ) {
That's a tough task. Is **unprocessedNode** good in relation to **lastProcessedNode**?

2023-03-31 09:08 UTC, oleg-derevenetz approved these changes

2023-03-31 14:41 UTC, merged