Buttons and some hotkeys
ihhub/fheroes2 pull request #6985
Opened 2023-04-10 13:46 UTC by Mr-Bajs

2023-04-11 18:14 UTC, Mr-Bajs commented
@zenseii 
Ready for your review.

2023-04-13 12:33 UTC, Mr-Bajs commented on files/lang/sv.po
> +msgstr "Kartans svårighetsgrad för valda kartan. Kartans svårighets bestäms av kartans kreatör. "
Changed into "_Svårighetsgraden för den valda kartan._ " to refer to the map two times in the same scentence is redundant and a little bit wierd.

2023-04-13 12:37 UTC, Mr-Bajs commented on files/lang/sv.po
> +msgstr "Svårighetsgraden för valda kartan. Kartans svårighets bestäms av kartans kreatör. "
fixed.

2023-04-16 03:28 UTC, ihhub requested changes
Hi @Mr-Bajs , I left 2 comments here. Would you mind to take a look?

2023-04-16 03:28 UTC, ihhub commented on files/lang/sv.po
> +msgstr "Avsluta fheroes2."
Please revert this change. It was absolutely correct. Players play Heroes of Might and Magic II game powered by fheroes2, not fheroes2 game.

2023-04-16 03:28 UTC, ihhub commented on files/lang/sv.po
> +msgstr "Denna spelomgång är översatt till "
Symbol **'** is missing at the end.

2023-04-16 09:54 UTC, ihhub approved these changes

2023-04-16 09:54 UTC, merged

2023-04-16 09:54 UTC, ihhub commented
@Mr-Bajs , thank you so much for this update!