6952: Improve Summon Boat spell gayed out messages
ihhub/fheroes2 pull request #7020
Opened 2023-04-16 08:17 UTC by Kazhuu

Solves https://github.com/ihhub/fheroes2/issues/6952 by adding more logic to Summon Boat adventure spell when it is grayed out.

2023-05-08 16:14 UTC, ihhub requested changes
Hi @Kazhuu , I left multiple comments here. Could you please check them in your spare time?

2023-05-08 16:14 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> +        const int32_t boatSource = summonableBoats.at( 0 );
**summonableBoats.front()** will do the same.

2023-05-08 16:14 UTC, ihhub commented on src/fheroes2/spell/spell_info.cpp
> +    Maps::Indexes getSummonableBoats( const Heroes & hero )
The return array is never used and only first value from it is being used. I suggest to just return an index of a boat. If it is less than 0 then it is an invalid position. In this case the code will be faster.

In this case can we just use **getPossibleBoatPosition()** function for our needs?

2023-05-09 05:51 UTC, Kazhuu commented on src/fheroes2/spell/spell_info.cpp
> +    Maps::Indexes getSummonableBoats( const Heroes & hero )
I changed the function to return possible boat position as int32_t and if it's not found simply return -1 as a result. Reduces code coupling and makes the function simpler to use as well.

2023-05-09 05:52 UTC, Kazhuu commented
Hello @ihhub I made the changes. Very good comments. The code should now be simpler as well. Can you review again?

2023-05-09 15:37 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> +        int32_t boatSource = fheroes2::getSummonableBoat( hero );
This variable can be **const** as we don't modify it after. SonarCloud actually detects this but only for PRs from this main repo.

2023-05-09 15:38 UTC, ihhub commented on src/fheroes2/spell/spell_info.cpp
> +            const int heroColor = hero.GetColor();
This variable can be declared outside the loop. Since it is not inlined we will save some time doing this.

2023-05-09 18:28 UTC, Kazhuu commented
Hello @ihhub. Fixed the issues. Can you look again?

2023-05-10 21:53 UTC, Branikolog commented
I've made a couple of tests and graying seems to work correctly.
The only thing I'm concerning is wording in a case I summoned a few boats and there're no more available:

https://github.com/ihhub/fheroes2/assets/55348946/5d537cab-0a7b-44fa-9265-560e250875f0

I'm a little bit confused, as the message says, that no boat is available. Actually there're two boats at least available (which I summoned already) but this phrase makes an impression, that no boats can be summoned at all. I believe, this message is actual only for the case, when there're actually no free boats at all which could be summoned.
Maybe, if it would be spelled like: "There's no _more_ boat available to cast this spell.", it would make more clear, that I have available boats, but I simply can't summon more to the current location. How do you think?
Sorry, if I just understood this message incorrectly. :)

2023-05-11 14:47 UTC, Kazhuu commented
Good point @Branikolog. I changed to text that you suggested. What you think @LeHerosInconnu?

2023-05-26 12:28 UTC, Kazhuu commented
Sorry for the late answer. So what is the text that should be displayed and in what conditions @LeHerosInconnu and @Branikolog? It would be easier for me to fix this if stated clearly :)

2023-05-27 08:46 UTC, Branikolog commented
Hi, @Kazhuu !

For the case when there's no any boats available to summon, game should show the message: "There's no boat available to cast this spell."
For the case, when hero has already summoned 1 or more boats, which are standing empty nearby: "There's no more boat available to cast this spell."

2023-05-27 14:07 UTC, Kazhuu commented
Okay sounds good @Branikolog but how the text should be reflected on this message "There is no boat available and no free ocean location near the hero to cast this spell."? Should this text also have two variants? To be honest if so I think logic wise this gets quite complicated to implement and the benefit is only little bit better wording for the text.

2023-05-27 17:48 UTC, LeHerosInconnu commented
Hello @Kazhuu and @Branikolog,

> Hi, @Kazhuu !
> 
> For the case when there's no any boats available to summon, game should show the message: "There's no boat available to cast this spell." For the case, when hero has already summoned 1 or more boats, which are standing empty nearby: "There's no more boat available to cast this spell."

> Okay sounds good @Branikolog but how the new change should be reflected on this message "There is no boat available and no free ocean location near the hero to cast this spell."? Should this text also have two variants? To be honest if so I think logic wise this gets quite complicated to implement and the benefit is only little bit better wording for the text.

If this becomes too complicated to manage, for me it's okay to have only the sentence "There is no boat available to cast this spell." as it can encompass both cases and is "acceptable" for the description.
@Branikolog, what do you think?

2023-05-28 03:38 UTC, Kazhuu commented
I'd say it's not possible to implement, but I myself would like to keep the text more simple :+1:

2023-05-28 09:04 UTC, Branikolog commented
@Kazhuu 

Okay then. If it really doesn't worth overcomplicating then I'm OK with initial implementation without adding "more".

I'll probably create an issue for future improvement.

2023-05-28 09:04 UTC, Branikolog approved these changes

2023-05-29 02:26 UTC, Kazhuu commented
Thanks @Branikolog! Yeah another issue is good as well. I might work on it after a while, if nobody else takes it :+1:

2023-06-13 01:56 UTC, ihhub commented
We will merge this pull request for 1.0.6.

2023-06-14 19:43 UTC, merged

2023-06-14 19:43 UTC, ihhub commented
@Kazhuu , thanks a lot for these improvements!