Show map ratings in victory video, add subtitles, add color fade
ihhub/fheroes2 pull request #7025
Opened 2023-04-16 13:00 UTC by Districh-ru

This PR implements:
 - [x] simple subtitles in video playback,
- show Rating info in victory video (WIN.SMK) using subtitles:
  - [x] for singleplayer custom maps,
  - [x] for multiplayer custom maps,
  - [x] for campaign,
 - [x] the color fade algorithm at the end of video, originally made by @ihhub,
 - [x] the ability to show enter player name dialog (and use this name in the High scores) over the gray-scaled video frame.

Video of standard game "WIN.SMK" with ratings and demo subtitles (subtitle texts were added only for testing and are not present in current PR):

https://user-images.githubusercontent.com/113276641/233164312-993fe883-126f-4da5-80aa-8e2b1bb309ba.mp4

Campaign game "WIN.SMK" with ratings ([**Save file**](https://github.com/ihhub/fheroes2/files/11297741/Evil_test.zip))
![fheroes2 2023-04-20 19-33-16-697](https://user-images.githubusercontent.com/113276641/233431085-445e81aa-f85f-47d8-a9f5-4c8b9c55c207.jpg)

close #2918

2023-04-20 17:31 UTC, oleg-derevenetz commented on src/fheroes2/game/game_video.h
> +#include "ui_text.h" // IWYU pragma: keep
IWYU proposes the following:

```
/home/runner/work/fheroes2/fheroes2/src/fheroes2/game/game_video.h should add these lines:
namespace fheroes2 { class TextBase; }
/home/runner/work/fheroes2/fheroes2/src/fheroes2/game/game_video.h should remove these lines:
- #include "ui_text.h"  // lines 31-31
```

So yes, it proposes to remove it AND to add the forward declaration of `class TextBase` instead.

2023-04-20 17:47 UTC, Districh-ru commented on src/fheroes2/game/game_video.h
> +#include "ui_text.h" // IWYU pragma: keep
Hi, @oleg-derevenetz.
Thanks for pointing this out. For the fist glance I thought that it could be incorrect and I need to include the header which declares the whole class.
I applied this proposal.

2023-04-22 17:01 UTC, ihhub requested changes
Hi @Districh-ru , I put several comments in this pull request. Would you mind to check them in you free time?

2023-04-22 17:01 UTC, ihhub commented on src/fheroes2/game/game_video.cpp
> +    }
This method can be inlined.

2023-04-22 18:04 UTC, Districh-ru commented on src/fheroes2/game/game_video.cpp
> +        if ( palette.size() != 768 ) {
Hi, @ihhub.
I made variables to store '768' for palette colors and '256' for palette color indexes.

2023-04-22 18:05 UTC, Districh-ru commented on src/fheroes2/game/game_video.cpp
> +            endPalette[i * 3 + 2] = originalPalette[static_cast<size_t>( assignedValue[i] ) * 3 + 2] * 4;
Sure.
I also cached this as `const uint8_t valuePosition = assignedValue[i] * 3;` not to calculate it 3 times.

2023-04-22 18:07 UTC, Districh-ru commented on src/fheroes2/game/game_video.cpp
> +            fheroes2::delayforMs( delay );
I made a while loop using `validateCustomAnimationDelay()` so now the render will be better synchronized by the `delay`.

2023-04-22 18:07 UTC, Districh-ru commented on src/fheroes2/game/game_video.h
> +        void blitSubtitles( fheroes2::Image & output, const fheroes2::Rect & frameRoi ) const;
Sure!)

2023-04-22 18:09 UTC, Districh-ru commented on src/fheroes2/game/game_video.cpp
> +    }
Thanks for the proposal. I forgot to make it const as initially subtitles were modified inside ShowVideo().

2023-04-22 18:09 UTC, Districh-ru commented on src/fheroes2/game/game_video.h
> +        void setPosition( const fheroes2::Point position )
Sure!)

2023-04-22 18:10 UTC, Districh-ru commented on src/fheroes2/game/game_video.h
> +        fheroes2::Point _position{ 0, 0 };
I removed the `{ 0, 0 }`. :)

2023-04-22 18:13 UTC, Districh-ru commented on src/fheroes2/game/game_video.cpp
> +        _subtitleImage.resize( textWidth + 1, subtitleText.height( textWidth ) + 1 );
Yes, it includes the space for shadow, but shadow is only on the left and bottom sides and for small text it is only 1 pixel. So we have to add extra 1 pixel from the top and right sides to have space for contour (it needs 1 pixel from all sides of rendered text).

2023-04-22 18:13 UTC, Districh-ru commented on src/fheroes2/game/game_video.cpp
> +        const int32_t textWidth = subtitleText.width( ( maxWidth > 0 ) ? maxWidth : fheroes2::Display::DEFAULT_WIDTH );
Shure.)

2023-04-22 18:18 UTC, Districh-ru commented on src/fheroes2/game/game_video.cpp
> +                    }
The video rendering loop renders the current (prepared) frame and then prepare the next frame, so the subtitles render is also done after frame render.
It is done to have a better sync between audio and video during SMK playback.
I also added a precache of subtitles for the first video frame.

2023-04-22 18:19 UTC, Districh-ru commented on src/fheroes2/game/game_over.cpp
> +                Video::ShowVideo( "WIN.SMK", Video::VideoAction::WAIT_FOR_USER_INPUT, gameResults, true );
Yes, the code will be clearer.

2023-04-22 18:21 UTC, Districh-ru commented on src/fheroes2/game/game_video.cpp
> +    }
OK 👍

2023-04-23 03:47 UTC, ihhub commented on src/fheroes2/game/game_video.cpp
> +        _subtitleImage.resize( textWidth + 1, subtitleText.height( textWidth ) + 1 );
Thanks for the explanation!

2023-04-23 03:48 UTC, ihhub commented on src/fheroes2/game/game_video.cpp
> +                    }
Got it!

2023-04-23 16:10 UTC, ihhub requested changes
Hi @Districh-ru , I put few more comments here. Would you mind to check them?

2023-04-23 16:10 UTC, ihhub commented on src/fheroes2/game/game_video.cpp
> +            colorFade( palette, frameRoi, 1500, 8 );
Why are we doing this with such a low FPS? Can we do it with a higher FPS?

2023-04-23 16:10 UTC, ihhub commented on src/fheroes2/game/game_video.cpp
> +            colorFade( palette, frameRoi, 1500, 8 );
It is good not to have some hardcoded values in the common code. What if we move **colorFade** to `ui_tool.h|cpp` files and then **ShowVideo()** function can receive a **std::function** parameter (like **postPlayback**) which by default is nullptr. If the function is defined then call it at the end of the video playback.

Then in places where we call **ShowVideo()** function we just pass a lambda function wrapped over **colorFade()** with needed parameters.

Strictly speaking **colorFade()** function does not belong to video playback code.

What do you think?

2023-04-23 16:10 UTC, ihhub commented on src/fheroes2/game/game_video.cpp
> +                break;
I am not sure that we can interrupt this king of animation in the original game. Could you please verify this?

2023-04-23 17:30 UTC, Districh-ru commented on src/fheroes2/game/game_video.h
> +        uint32_t _endTimeMS{ UINT32_MAX };
Hi, @ihhub, sure lets make id 0 by default (if it was not properly initialized then there is no need to display these subtitles).

2023-04-23 17:31 UTC, Districh-ru commented on src/fheroes2/game/game_video.h
> +        }
I made this changes and removed `setPosition()`.

2023-04-23 17:31 UTC, Districh-ru commented on src/fheroes2/game/game_video.h
> +        Subtitle( const fheroes2::TextBase & subtitleText, const uint32_t startTimeMS, const uint32_t durationMS = UINT32_MAX,
Sure)

2023-04-23 17:32 UTC, Districh-ru commented on src/fheroes2/game/game_video.cpp
> +        _subtitleImage.reset();
OK, thanks for finding this leftover from the initial code.

2023-04-23 17:46 UTC, Districh-ru commented on src/fheroes2/game/game_video.cpp
> +        screenRestorer.changePalette( prevPalette.data() );
I checked several videos, including INTRO.SMK which has many palette changes and all is OK.
During prepare we change the screen palette and it will be used in the next screen render of the frame with this palette.
I tried to make code that do render screen immediately after delay has passed to better sync video and do all calculation after.
If we will notice rendering issues, we can place `changePalette()` right before `display.render()'

2023-04-23 17:47 UTC, Districh-ru commented on src/fheroes2/game/game_video.cpp
> +            colorFade( palette, frameRoi, 1500, 8 );
I used FPS from WIN.SMK. :)
I changed it to 15 and reduced the time to 1 second to match the OG.

2023-04-23 17:54 UTC, Districh-ru commented on src/fheroes2/game/game_video.cpp
> +            colorFade( palette, frameRoi, 1500, 8 );
Sure, I moved it to `ui_tool.h/cpp`.
But I did not use `std::function` as currently we don't need this. We currently use color fade only for WIN.SMK. And I don't think that it has to use different parameters for other video color fade.
If we will need to have these parameters to be configurable we can to this change.

2023-04-23 18:00 UTC, Districh-ru commented on src/fheroes2/game/game_video.cpp
> +                break;
In OG it is not interruptible. And as it currently lasts only for 1 second I made it uninterruptible in our engine.
But if we plan to use longer color fade duration some users may want to interrupt this. :)
(i.e. I always want to skip the pre-battle sound)

2023-04-24 04:43 UTC, ihhub requested changes
Hi @Districh-ru , I put few more tiny optimization comments. Could you please check them?

2023-04-24 04:44 UTC, ihhub commented
Hi @Branikolog , please review this pull request as a priority.

2023-04-24 14:50 UTC, Districh-ru commented on src/fheroes2/gui/ui_tool.cpp
> +        // The biggest problem here is that the palette can be not the same as in the game.
Hi, @zenseii. Thank you very much for the grammar corrections!
Your suggestion is correct. 👍

2023-04-24 14:54 UTC, Districh-ru commented on src/fheroes2/gui/ui_tool.h
> +    // Fade display image colors to greyscale part of default game palette.
I was taught to use the British English word "grey", so I write it automatically instead of the American English "gray". :)

2023-04-25 01:01 UTC, ihhub reviewed
Hi @Districh-ru , I left 2 more nitpick comments in this pull request. Overall, good job!

2023-04-25 03:12 UTC, Districh-ru commented on src/fheroes2/game/game_over.cpp
> +        // Set position (405,110) to render results over the black rectangle of burned picture in WIN.SMK video.
Thanks, @ihhub, I forgot to update the comments after testing.

2023-04-25 03:13 UTC, Districh-ru commented on src/fheroes2/gui/ui_tool.cpp
> +        assert( fps > 0 );
Sure)

2023-04-25 05:56 UTC, ihhub approved these changes

2023-04-25 05:57 UTC, merged

2023-04-25 05:57 UTC, ihhub commented
@Districh-ru , many thanks for these important changes!