Rework the search algorithm for available scaled resolutions
ihhub/fheroes2 pull request #7051
Opened 2023-04-22 21:06 UTC by oleg-derevenetz

2023-04-23 05:32 UTC, Districh-ru requested changes
Hi, @oleg-derevenetz.
I left one comment. Could you check it when you have time.

2023-04-23 05:33 UTC, Districh-ru requested changes

2023-04-23 05:33 UTC, Districh-ru commented on src/engine/screen.cpp
> +                if ( lowestResolution < resolution || lowestResolution == resolution ) {
`lowestResolution < resolution` returns true only if all elements of `resolution` are higher then ones of `lowestResolution`.
If only one parameter (i.e. height) is higher and the other (width) is not higher it will return `false`.
Maybe this condition can be replaced with `( !( lowestResolution > resolution ) )`.

So on my handheld devices I've got resolutions with initially unsupported height. For example my phone's screen resolution is 1440x720 and I get:

![2023-04-23_064824](https://user-images.githubusercontent.com/113276641/233820842-5fa9f8dd-441a-4ee4-8615-bfc2b9b898b7.png)

<details><summary>On master build I don't have these resolutions:</summary>

![2023-04-23_065650](https://user-images.githubusercontent.com/113276641/233821301-54236199-9d2d-4ea1-b5b0-1a4f615612fc.png)

</details>

2023-04-23 09:40 UTC, oleg-derevenetz commented on src/engine/screen.cpp
> +                if ( lowestResolution < resolution || lowestResolution == resolution ) {
Yes, these resolutions are clearly superfluous here. Now I use the logic from `master` here.

2023-04-23 09:46 UTC, oleg-derevenetz commented on src/engine/screen.cpp
> +                if ( lowestResolution < resolution || lowestResolution == resolution ) {
> `lowestResolution` < `resolution` returns true only if all elements of `resolution` are higher then ones of `lowestResolution`.

That's not quite true, `width` and `height` are compared in order using the short-circuit logic, so if `res1.width` is less than `res2.width`, then `res1.height` is not compared with `res2.height` at all.

2023-04-23 09:47 UTC, ihhub commented
Hi @oleg-derevenetz , my biggest fear not implementing this in the past is the amount of resolutions available for end users. Having tons of them seems like an overkill.

The biggest problem is the way how we add resolutions in case of having a single resolution returned by SDL. Logically we should add resolutions which are close to the aspect ration of the original one. For instance, having 1920x1080 and adding 1280x960 doesn't look right for some people. I don't have a strong opinion about the best solution we should choose at the moment.

2023-04-23 09:52 UTC, oleg-derevenetz commented
@ihhub

> my biggest fear not implementing this in the past is the amount of resolutions available for end users. Having tons of them seems like an overkill.

Well, it's up to you :) But IMHO having more scaled resolutions is fine, because existing resolutions usually doesn't fit the scaling well.

> The biggest problem is the way how we add resolutions in case of having a single resolution returned by SDL. Logically we should add resolutions which are close to the aspect ration of the original one. For instance, having 1920x1080 and adding 1280x960 doesn't look right for some people. I don't have a strong opinion about the best solution we should choose at the moment.

This logic left intact in this PR (apart from incorrect optimization of resolution comparison which is reverted).

2023-04-23 14:22 UTC, Districh-ru commented on src/engine/screen.cpp
> +                if ( lowestResolution < resolution || lowestResolution == resolution ) {
Thanks for the explanation.

2023-04-23 14:50 UTC, Districh-ru approved these changes
Now it works OK. 👍
On my cell phone I have only one scaled resolution (x1.5) as before this PR. On PC I have some new (x2.0) resolutions.

IMHO it will be better in future to set only the game resolution and have an option to use desktop resolution as screen resolution with scaling.
Talking about PC for me there is no difference - run the game in fullscreen using `640x480` or `640x480(x2.0)` - desktop resolution will be changed, all windows and icons will be rearranged. The only difference is that in first place there only will be used the video card or monitor built-in scaler. And running the game in a window I can always change the window size (i.e. maximize it) so (x1.0) and (x2.0) will give the same picture.
And, as I can see, on android the game always use native screen resolution and stretches the picture to fit it, keeping the aspect ratio. So there will be no difference between (x1.0) and other scales for the same resolution.

2023-04-23 15:02 UTC, oleg-derevenetz commented
> IMHO it will be better in future to set only the game resolution and have an option to use desktop resolution as screen resolution with scaling.

Technically there is no problem with this - all we need is to always use the `SDL_WINDOW_FULLSCREEN_DESKTOP` fullscreen mode (and always use the software cursor to properly scale it). Currently this mode is used almost everywhere except Windows. This mode is better than the "hardware" fullscreen mode (`SDL_WINDOW_FULLSCREEN`) in many aspects - for example, it properly works with multiple monitors and it doesn't cause negative effects such as rearranging shortcut icons on the desktop.

2023-04-25 15:03 UTC, ihhub approved these changes

2023-04-25 15:03 UTC, merged

2023-04-25 15:03 UTC, ihhub commented
@oleg-derevenetz , thank you so much for these improvements!