Do not reset castle or heroes scrollbars when hero moves
ihhub/fheroes2 pull request #7053
Opened 2023-04-23 13:35 UTC by Kazhuu

Solves https://github.com/ihhub/fheroes2/issues/6837. Now both castles and heroes scrollbars positions are retained when hero moves. Previously both of them were modified. Castle scrollbar always goes to the top and heroes scrollbar is either placed to the top or bottom of the scrollbar view depending on the hero's position on the list.

This might be not the cleanest fix out there. I'm open to modify this if needed.

2023-04-25 15:21 UTC, ihhub requested changes
Hi @Kazhuu , I put multiple suggestions here. Could you please check them and see if they make sense?

2023-04-25 15:21 UTC, ihhub commented on src/fheroes2/game/game_interface.h
> +        void ResetFocus( int priority, const bool resetScrollBarPosition = true );
Could you please make **priority** input argument as **const** and also remove the default value for the second argument? I know that this way is easier to make changes but default parameters usually lead to difficulties to debug code.

2023-04-25 15:21 UTC, ihhub commented on src/fheroes2/gui/interface_focus.cpp
>      if ( player ) {
Since we modify his function could we please do the following:
```cpp
if ( player == nullptr ) {
    return;
}
...
// the rest of the code.
```
?

This would definitely increase code readability as having many if-s and switch cases is hard to read.

2023-04-26 15:59 UTC, Kazhuu commented on src/fheroes2/game/game_interface.h
> +        void ResetFocus( int priority, const bool resetScrollBarPosition = true );
Indeed!

2023-04-27 00:57 UTC, ihhub approved these changes

2023-04-27 12:52 UTC, Branikolog commented
Hi, @Kazhuu 
I've found that once we change focus from castle to a hero, castle list updates:

https://user-images.githubusercontent.com/55348946/234865836-2145b877-d4ff-430e-a71a-2d259de4e68f.mp4

After battle, castle list is also updated in the current PR build.
Castle list shouldn't be updated during single turn, no matter what hero we choose or what action we make.

2023-04-28 15:02 UTC, Kazhuu commented
Hello @Branikolog I fixed the issue. The function that needed to be changed is also used elsewhere and what I tested manually everything seems to function as it should. Can you test again?

2023-04-28 15:05 UTC, Kazhuu commented on src/fheroes2/gui/interface_focus.cpp
> -    else if ( type == FOCUS_CASTLE && !iconsPanel.IsSelected( ICON_CASTLES ) ) {
This code was responsible for updating castle scrollbar back to the top. There is similar code for the heroes scrollbar but after debugging for a while it seems that code block is not executed like this one is when changing focus between castle and heroes lists. Now sure why. But removing these lines fix the issue and what I tested everything seems to function like it should.

2023-04-29 10:32 UTC, LeHerosInconnu commented
Hello @Kazhuu,

> Hello @LeHerosInconnu I did some changes. Also maybe it would be better to post this in the PR where the discussion is now happening to make it easier for people to follow :)
> 
> I noticed one issue that seems to exits before this change as well. When you double click the hero and press next hero in the down left or right corner and then exit. The focus is retained on the hero you double clicked before, not the one you press next to. This however works with castles. Maybe if this need to be fixed, create another issue about this?

_Originally posted by @Kazhuu in https://github.com/ihhub/fheroes2/issues/6837#issuecomment-1528664542_

In the original game, switching heroes or castles by accessing the hero or castle screen, or by accessing the hero or castle screen through one of the Kingdom Overview screens, does not change the hero or castle selected in the list of heroes or castles when exiting those screens.
The user may simply want to check something without changing his initial selection.
It should work the same way in fheroes2.

I tested this, everything seems to work as it should, except for the point described above where the castle should always remain selected in the castle list.
I can open a new issue for that if necessary.

2023-04-29 12:49 UTC, Branikolog commented
Hello, @Kazhuu !
I've found another issue. When hero uses Dimension Door spell both lists reset.

https://user-images.githubusercontent.com/55348946/235302267-c049b946-06b5-4c7d-905f-7c7e1c78ab9b.mp4

The same happens with Town Portal and Town Gate spells.

@LeHerosInconnu 

>In the original game, switching heroes or castles by accessing the hero or castle screen, or by accessing the hero or castle screen through one of the Kingdom Overview screens, does not change the hero or castle selected in the list of heroes or castles when exiting those screens.
>The user may simply want to check something without changing his initial selection.

At the same time user may want to scroll through castles and when he finds the one, he can exit and check its surroundings. Or scroll through castles till he finds the one with hero, to exit and instantly move the hero from this castle? But anyway, the logic should be consistent for all cases at least. Either not refocus on heroes/towns scrolling by small corner buttons, or focus on the town/hero that was the last shown on the screen.

2023-04-29 13:02 UTC, Kazhuu commented
Good find @Branikolog. Could you also provide me a save file so I can test this more easily :+1:

2023-04-29 13:13 UTC, Branikolog commented
@Kazhuu 
Sure.
[Scrollbar test DD+TP.zip](https://github.com/ihhub/fheroes2/files/11359242/Scrollbar.test.DD%2BTP.zip)
Check hero Wrathmont, he has DD and TP spells in his book.

2023-04-29 13:19 UTC, Branikolog commented
@Kazhuu 
Here's one more issue:

https://user-images.githubusercontent.com/55348946/235304779-8e3670de-2e39-4729-90fd-8c684a621537.mp4

2023-04-30 13:34 UTC, Kazhuu commented
@Branikolog I fixed the issues. Adventure spells like town portal now do not reset scrollbars and when hero loses a battle, the scrollbar is positioned correctly. Can you test one more time? And thanks for testing!

2023-05-04 18:42 UTC, Branikolog commented
Hi, @Kazhuu !
Sorry for the late response!
I've found out that when you enter a castle with a hero by pressing spacebar, scrollbars are reset:

https://user-images.githubusercontent.com/55348946/236293972-d9a95c6b-2c14-4217-b6ac-4acb02d60f48.mov

The same thing happens, when we press spacebar to visit some objects on the adventure map. Like creature dwelling.

Also, when you dismiss hero both scrollbars a reset to upper position. 

https://user-images.githubusercontent.com/55348946/236294568-e7ef19b0-9e58-46f8-ae54-9a5fec98b148.mov

For heroes list it's ok to be reset, since the first hero is selected, but I think castle list should keep its position unchanged.
I think, the last issue is a bit out of current PR, since the PR is supposed to fix issues with scrollbars for hero movement. If you wish, I can create a separate issue, which could be linked to some future PRs.

2023-05-09 06:26 UTC, Kazhuu commented
Hi @Branikolog I fixed the issue you described. Can you now test again?

2023-05-09 10:51 UTC, Branikolog approved these changes
I can't find any move-related issues here more.
Good work, @Kazhuu !
I'll create a separate issues relating hero dismiss and castle capturing later, where scrollbars reset too.

2023-05-09 10:57 UTC, Kazhuu commented
Thanks @Branikolog for testing. Could @ihhub or someone review this PR now?

2023-05-13 23:23 UTC, merged

2023-05-13 23:23 UTC, oleg-derevenetz commented
@Kazhuu thank you very much!