Android Toolset: implement animation extraction from HOMM2.GOG
ihhub/fheroes2 pull request #7055
Opened 2023-04-23 23:25 UTC by oleg-derevenetz

If `HOMM2.GOG` is present in a ZIP archive with HoMM2 assets. At the request of people writing reviews on Google Play.

2023-04-25 15:54 UTC, ihhub commented
Hi @oleg-derevenetz , since we are greatly expanding Java code I think we should enable Java code analysis within SonarQube. I don't remember that we enabled it. What do you think?

2023-04-25 16:06 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left just few comments here. Would you mind check them?

2023-04-25 16:06 UTC, ihhub commented on android/app/src/main/java/org/fheroes2/HoMM2AssetManagement.java
> +        boolean result = false;
Can we please rename it into something like **containsValidFile**? **result** is a very generic name :)

2023-04-25 16:09 UTC, oleg-derevenetz commented on android/app/src/main/java/org/fheroes2/HoMM2AssetManagement.java
> +        allowedSubdirNames.add( "anim" );
@ihhub The logic is the same as in `extractHoMM2AssetsFromZip()`: `getHoMM2AssetSubpath()` is called that contains case-insensitive logic (all path elements are lowercased via `String.toLowerCase()` before comparison).

2023-04-25 16:12 UTC, oleg-derevenetz commented on android/app/src/main/java/org/fheroes2/HoMM2AssetManagement.java
> +            if ( bytesRead < 0 ) {
@ihhub There is a [documented behavior](https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#read(byte[],%20int,%20int)): result of `read()` can be zero only if `len` is zero and this is impossible here.

2023-04-25 16:15 UTC, oleg-derevenetz commented on android/app/src/main/java/org/fheroes2/HoMM2AssetManagement.java
> +        boolean result = false;
Well, I often use the name `result` for a variable that will be used as a function return value (see the `extractHoMM2AssetsFromZip()` in this module, `extractAnimationsFromISO()` has absolutely the same logic). But if you insist, I can rename it :)

2023-04-25 16:16 UTC, ihhub commented on android/app/src/main/java/org/fheroes2/HoMM2AssetManagement.java
> +            if ( bytesRead < 0 ) {
Got it! Thank you for the explanation!

2023-04-28 11:05 UTC, merged

2023-04-28 11:05 UTC, ihhub commented
@oleg-derevenetz , thank you so much for this change!