AI should check for castles and funds before retreat
ihhub/fheroes2 pull request #7065
Opened 2023-04-25 22:51 UTC by idshibanov

Fixes edge case when AI doesn't have a Castle building or gold in the bank to purchase.

2023-04-26 13:24 UTC, ihhub requested changes
Hi @idshibanov , I left 2 suggestion in this pull request. Would you mind to check them?

2023-04-26 13:24 UTC, ihhub commented on src/fheroes2/ai/ai_common.cpp
> +        return kingdom.GetCountCastle() && kingdom.AllowRecruitHero( true );
Let's please be explicit and add **> 0** to `kingdom.GetCountCastle()`. This will be easier to read in the future.

2023-04-26 13:24 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +               && CanPurchaseHero( hero.GetKingdom() );
I suggest to slightly optimize this function to avoid extra call for **Difficulty::GetAIRetreatRatio()**:
```cpp
if ( !_considerRetreat || hero.isControlHuman() || !isHeroWorthSaving( hero ) || hero.isLosingGame() || !CanPurchaseHero( hero.GetKingdom() ) ) {
    return false;
}

return _myArmyStrength * Difficulty::GetAIRetreatRatio( Game::getDifficulty() ) < _enemyArmyStrength;
```

I just shuffled some conditions based on priorities. What do you think?

2023-04-27 15:47 UTC, oleg-derevenetz approved these changes

2023-04-27 16:33 UTC, merged

2023-04-27 16:33 UTC, ihhub commented
@idshibanov , thank you so much for this fix!