Add an ability to cancel waiting for pre-battle sound to over
ihhub/fheroes2 pull request #7067
Opened 2023-04-26 14:47 UTC by Districh-ru

This PR adds the ability to skip waiting for pre-battle sound to over and start the battle by pressing ESC, right mouse or middle mouse button. This does not interrupt the pre-battle sound playback.

2023-04-27 00:59 UTC, ihhub commented
I forsee that some players might see this as a bug :)

2023-04-27 03:16 UTC, Districh-ru commented
> I forsee that some players might see this as a bug :)

Hi, @ihhub.
Yes, this is a change in original game logic so some players can think so.
And some players say: in HoMM3 HD there is an option to skip the pre-battle sound and there will be good to have the same feature in fheroes2.
In this PR we give the ability, we are not forcing to always skip the pre-battle sound. So if player don't want to skip thу pre-battle waiting than he will not press the ESC, MMB and RMB and the geme will behave as original.
Always skipping the pre-battle sound is not a good idea as sometimes, when enemy attacks you and his turn is first in the battle you may want to observe enemy's army before starting a fight. And the pre-battle waiting gives you this time.
And if you have many battles on map (i.e. the "Alteris" map has lots of monsters to fight) than this ability will help to save your time.
Besides we already have a feature "Creature's movement area is divided into separate hexes" that is treated like bug by some players. And it is a good feature :)

2023-04-27 07:51 UTC, Branikolog approved these changes
Hi, @Districh-ru 
This feature works nice. 
I'm sure those players, who love fast playing will love it. Others could still enjoy the dramatic pause before the battle.

2023-04-27 10:40 UTC, oleg-derevenetz approved these changes
Why not in the end. I've always been annoyed by this pause.

2023-04-28 20:53 UTC, Branikolog commented
Hi, @zenseii 

> Less time waiting means more time playing.
> 
> My only concern is that the two musics overlapping can sound a bit jarring. IMO the best would be to interrupt the pre-battle music and go straight to the battle music.
> 
> I can see that what solution to choose can be a bit contentious so we can wait with that and just move ahead with this PR.

So precise ears you have! :)
I could barely hear battle music while pre-battle melody.
I propose to play opening melody full and then start playing battle music. To be consistent with the behaviour without cancelling of pre-battle sound.

2023-04-28 23:24 UTC, oleg-derevenetz commented
> I propose to play opening melody full and then start playing battle music.

There is currently no easy way to wait until specific sound (out of multiple, because if we start the battle, then there will be other overlapping sounds as well, such as steps, blows, shots, etc) will be finished. Stop the pre-battle sound on player's action is much easier (since it's the only sound played during the pre-battle pause).

2023-04-29 08:18 UTC, Districh-ru commented
Hi, @oleg-derevenetz, @zenseii, @Branikolog.
I added the ability to get the started sound channel ID so no we can monitor only this channel for sound to over. This allowed me to wait until the Pre-battle sound is over and only then start the music.
This ability can allow us to wait for the main battle sounds like unit move sounds and not play them many times without waiting tor them to over - this could reduce the cacophony of sounds on fast battle speeds. :)

2023-04-29 10:07 UTC, oleg-derevenetz requested changes
Hi @Districh-ru I just left a few notes, please take a look when you have time.

2023-04-29 10:49 UTC, Districh-ru commented on src/fheroes2/audio/audio_manager.cpp
> +    int32_t PlaySoundImp( const int32_t m82, const int32_t soundVolume );
Sure.)
I reverted all the changes of `int` to `int32_t` here.

2023-04-29 10:51 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( ( _preBattleSoundChannelId != -1 ) && !Music::isPlaying() && !Mixer::isPlaying( _preBattleSoundChannelId ) ) {
@oleg-derevenetz, I added the comment and checked that during the battle there are no `playSoundAsync()` calls.
Currently in our engine it used only for playing hero walking sounds on Adventure map.

2023-04-29 10:52 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.h
> +        int32_t _preBattleSoundChannelId{ -1 };
Sure!

2023-04-29 11:29 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( ( _preBattleSoundChannelId != -1 ) && !Music::isPlaying() && !Mixer::isPlaying( _preBattleSoundChannelId ) ) {
In fact, if we think about it, this race condition may happen even without the `playSoundAsync()`. Consider the following code somewhere in the `Battle::Interface`:

```cpp
AudioManager::PlaySound( [...] );

Redraw();
```

That's what may happen here:

```cpp
// The pre-battle sound is finished right here

AudioManager::PlaySound( [...] ); // This call takes the channel with the `_preBattleSoundChannelId` ID

Redraw(); // Now we wait for a wrong sound to finish.
```

Anyway, this race condition is relatively benign.

2023-04-29 11:51 UTC, oleg-derevenetz approved these changes

2023-04-29 12:08 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( ( _preBattleSoundChannelId == -1 || !Mixer::isPlaying( _preBattleSoundChannelId ) ) && !Music::isPlaying() ) {
Please note also that `Music::isPlaying()` holds a lock and this call may freeze for some time in certain cases: when MIDI playback with relatively slow backend (e.g. Windows native MIDI backend) is used and MIDI music track is starting in background thread in this very moment, then this lock will be held by a different thread until the MIDI track playback is fully launched.

2023-04-29 12:10 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( ( _preBattleSoundChannelId != -1 ) && !Music::isPlaying() && !Mixer::isPlaying( _preBattleSoundChannelId ) ) {
You are right, it can happen...
We can make a playback function for `battle_interface` which will first check the channel and set the state of something like "bool isPreBattleSoundOver" and then play the given sound. And use this function in battle_interface.cpp in the place of `PlaySound()`

2023-04-29 12:13 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( ( _preBattleSoundChannelId != -1 ) && !Music::isPlaying() && !Mixer::isPlaying( _preBattleSoundChannelId ) ) {
> We can make a playback function for `battle_interface` which will first check the channel and set the state of something like "bool isPreBattleSoundOver" and then play the given sound. And use this function in battle_interface.cpp in the place of `PlaySound()`

Let's not add unnecessary complications for the sake of eliminating a small potential pause before playing music. All sounds during the battle (except the pre-battle sound of course) are relatively short.

2023-04-29 12:18 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( ( _preBattleSoundChannelId != -1 ) && !Music::isPlaying() && !Mixer::isPlaying( _preBattleSoundChannelId ) ) {
OK)

2023-04-29 12:55 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +        // the game for some time in certain cases (e.g. slow MIDI backend).
First of all, if you decide to go this way, please use `std::optional` to reliably diagnose the _absence of a value_. Second, please note that `_preBattleSoundChannelId` may be `-1` if pre-battle sound failed to start for some reason and in this case you will effectively check `!Mixer::isPlaying( -1 )` here.

2023-04-29 12:55 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( ( _preBattleSoundChannelId == -1 || !Mixer::isPlaying( _preBattleSoundChannelId ) ) && !Music::isPlaying() ) {
In the new commit after starting the Battle music the `_preBattleSoundChannelId` will be set to `-2` and the `isPlaying()` checks will be skipped. If the sound effects are turned off then `_preBattleSoundChannelId` = -1, `!Mixer::isPlaying( _preBattleSoundChannelId )` and `!Music::isPlaying()` will return true as all sounds were stopped by `AudioManager::ResetAudio();` and the bre-battle sound was not started.

2023-04-29 14:12 UTC, Districh-ru commented
@oleg-derevenetz, thanks for the made changes.
I just finished reading about `std::optional` and started making changes. And I'm glad to see that my code is close to the one you did.
I only used `_preBattleSoundChannelId.has_value()` as the first condition. As I see it is the same as checking the `_preBattleSoundChannelId`.

2023-04-29 14:37 UTC, oleg-derevenetz commented
> In the future, please write if you are going to make changes so that we do not do the same thing in parallel. :)

I saw that you were busy with #7080 at that moment :)

2023-04-29 14:43 UTC, Districh-ru commented
> > In the future, please write if you are going to make changes so that we do not do the same thing in parallel. :)
> 
> I saw that you were busy with #7080 at that moment :)

It's OK.
I'm new to CPP programming and need time for some unknown for me things. But it is very interesting to learn new things and to make them work as planned.

2023-05-06 15:50 UTC, Branikolog approved these changes

2023-05-08 14:44 UTC, merged

2023-05-08 14:45 UTC, ihhub commented
@Districh-ru , huge thanks for this improvement!

2024-05-11 17:42 UTC, apcsb commented
Would be even more awesome to just have an option to disable the pre-battle sound altogether. I often play with sound off (late at night) and this pause bothers me every time. Is this hard to implement?

2024-05-11 18:20 UTC, oleg-derevenetz commented
> Would be even more awesome to just have an option to disable the pre-battle sound altogether. I often play with sound off (late at night) and this pause bothers me every time.

If you turn the sound effects off in the game itself, there will be no pre-battle pause at all.