Fix adventure map fog reveal on campaign scenario restart
ihhub/fheroes2 pull request #7080
Opened 2023-04-29 07:03 UTC by Districh-ru

This PR does these fixes:
- do not force set player color to -1 when you end current player turn not by "ending" it (i.e. restarting a campaign scenario);
- set the the only human player color before updating adventure map fog directions for Single player games;
- rework of `Players::FriendColors()` to return return current friends player colors, if player does not exist - return 0.

2023-04-29 07:18 UTC, Districh-ru commented
Hello @Branikolog, could you please test this fix when you have time. It affect the start/load of maps, and also the function that gets "friends colors" for mini-map and for reveal functions.
I tested Campaign restart, Campaign/Standard/Hot-Seat game start and load, played several turns on the map and did not find new bugs.

2023-04-29 13:00 UTC, Branikolog commented
Hi, @Districh-ru !
Could you please look at this save file (multiplayer game)?

https://user-images.githubusercontent.com/55348946/235303679-636ffd98-1ff9-4fbc-b180-fb852995a54b.mp4

[wide test.zip](https://github.com/ihhub/fheroes2/files/11359220/wide.test.zip)

2023-04-29 13:16 UTC, oleg-derevenetz commented
Hi @Districh-ru all these changes are superfluous and only mask the real problem. The real problem is that `Players::current_color` is not cleared on campaign map restart probably because `Players::SetStartGame()` is not called.

2023-04-29 13:37 UTC, Districh-ru commented
> Hi @Districh-ru all these changes are superfluous and only mask the real problem. The real problem is that `Players::current_color` is not cleared on campaign map restart probably because `Players::SetStartGame()` is not called.

Hi @oleg-derevenetz.
Thanks for the proposal, but starting a new campaign scenario and restarting it executes the same code:
https://github.com/ihhub/fheroes2/blob/529f226f464bfd097fdfdf5c869051374f3ac795/src/fheroes2/game/game_campaign.cpp#L1527
But is reset here and retains '-1' in `Interface::Basic::StartGame()` ...

2023-04-29 13:41 UTC, oleg-derevenetz commented on src/fheroes2/game/game_startgame.cpp
> -
The purpose of this piece of code (and the following one removed by you) was to properly draw the interface in case when loaded save file is "incorrect" in some way (e.g. it was created from already won/lost game). In this case player should see the UI with adventure map totally in fog first and then he gets a message from `gameResult.LocalCheckGameOver()` call (and no player will even get his turn).

2023-04-29 13:51 UTC, Districh-ru commented on src/fheroes2/game/game_startgame.cpp
> -
@oleg-derevenetz, thanks for the comment.
I reverted this change.

2023-04-29 14:33 UTC, oleg-derevenetz commented on src/fheroes2/game/game_startgame.cpp
> -
> The only concern is why we need to show the UI and the Adventure map if we will not give the player a turn. :)

Well, we should show something anyway (not some partially-drawn UI).

2023-04-29 14:35 UTC, oleg-derevenetz requested changes
Hi @Districh-ru there is still an issue with multiplayer save file from @Branikolog.

2023-04-29 14:40 UTC, Districh-ru commented
> Hi @Districh-ru there is still an issue with multiplayer save file from @Branikolog.

I discussed this with @Branikolog at Discord and the issue is in old saves and it is a different issue: this PR fixes the "fog directions update" not working correctly - it is only the UI issue (the mini-map is rendered correctly, you can move your heroes, only the adventure map is covered with fog).
In @Branikolog's save the whole fog data for the red player is set to unrevealed: the mini-map is black and you cannot move the heroes.
I'm analyzing this issue.

2023-04-29 15:25 UTC, Districh-ru commented
Hi, @Branikolog.
I made the changes to properly reveal fog in old multiplayer save files. Could you check it when you have time.

2023-04-29 16:35 UTC, oleg-derevenetz requested changes
Hi @Districh-ru I just left one suggestion, please take a look when you have time.

2023-04-29 16:35 UTC, oleg-derevenetz commented on src/fheroes2/game/game_startgame.cpp
> +        conf.SetCurrentColor( Players::HumanColors() );
I recommend to check that `Players::HumanColors()` really contains just one color here, something like this:

```cpp
assert( Color::Count( Players::HumanColors() ) == 1 );
```

or maybe even perform this check directly in `Settings::SetCurrentColor()`, because you can't have multiple "current colors" anyway.

2023-04-29 20:22 UTC, oleg-derevenetz approved these changes
Hi @Districh-ru I just left one minor suggestion. Hope that using `Color::NONE` instead of `-1` will not break anything.

2023-04-29 20:22 UTC, oleg-derevenetz commented on src/fheroes2/system/players.h
> +    void setCurrentColor( int color );
`color` can be `const` in this method.

2023-04-29 20:28 UTC, oleg-derevenetz commented on src/fheroes2/game/game_startgame.cpp
> +        if ( res == fheroes2::GameMode::END_TURN ) {
Hi @Districh-ru BTW it seems that now we can remove this check because current color will become `Color::NONE` in the `Players::SetStartGame()` anyway.

2023-04-29 20:28 UTC, Districh-ru commented on src/fheroes2/system/players.h
> +    void setCurrentColor( int color );
Hi @oleg-derevenetz, I quickly checked that using `Color::NONE` does not break the game. `-1` instead was the cause of this PR :)

2023-04-29 20:30 UTC, Districh-ru commented on src/fheroes2/game/game_startgame.cpp
> +        if ( res == fheroes2::GameMode::END_TURN ) {
Sure!

2023-05-02 01:08 UTC, ihhub reviewed
Hi @Districh-ru , I left just one question here. Could you please take a look?

2023-05-02 01:08 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +    if ( !loadedFromSave || world.CountDay() == 1 ) {
I assume that the second condition is only for old saves. Is it correct?

2023-05-02 03:05 UTC, Districh-ru commented on src/fheroes2/game/game_startgame.cpp
> +    if ( !loadedFromSave || world.CountDay() == 1 ) {
Hi, @ihhub.
Yes, you are right. It will not harm the new save files.

2023-05-02 16:34 UTC, ihhub approved these changes

2023-05-03 12:37 UTC, merged

2023-05-03 12:38 UTC, ihhub commented
@Districh-ru , thank you very much for this fix!