Improved troops in moat drawing.
ihhub/fheroes2 pull request #7157
Opened 2023-05-10 13:19 UTC by slawomir-witkowski

fix: #1954 
![image](https://github.com/ihhub/fheroes2/assets/46266059/aae6cf28-3a4a-4fcc-90a3-06ce988a49e1)

2023-05-13 23:37 UTC, oleg-derevenetz requested changes
Hi @slawomir-witkowski I just left a few suggestions, please take a look when you have time.

2023-05-13 23:37 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_arena.h
> +            CASTLE_BRIDGE_POS = 49
I recommend to place this value before the `CASTLE_GATE_POS` which is 50.

2023-05-13 23:37 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +    if ( moatCellId ) {
I recommend to replace this by

```cpp
if ( moatCellId == 0 ) {
    return;
}
[...]
```

to reduce code nesting.

2023-05-13 23:37 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +    const uint8_t moatCellIds[ARENAH] = { 7, 19, 28, 39, 49, 61, 72, 84, 95 };
In all other places, `int32_t` is used to represent the cell id and `-1` is used to represent the invalid/nonexistent/whatever cell id (because there is a valid cell with id `0`). While this logic is perfectly valid, it is somewhat out of the general series, so if there are no serious arguments for keeping it, I recommend doing "as everywhere". What do you think?

2023-05-14 20:04 UTC, oleg-derevenetz approved these changes
LGTM

2023-05-15 17:34 UTC, Districh-ru requested changes
Hi, @slawomir-witkowski.
Good work. I left 3 comments and one suggestion, could you take a look in your spare time.

Maybe we can cache the image from `_mainSurface` before rendering the troop by **RedrawTroopSprite()** with grid and shadow and use the cached image in **RedrawTroopMoat()** where we can get the troop sprite position and overlap only its legs in the moat: e.g. call `RedrawTroopMoat()` from `RedrawTroopSprite()` where we have the `drawnPosition` of troop sprite ... or return this Point from `RedrawTroopSprite()` function to use it in `RedrawTroopMoat()`.
What do you think?)

2023-05-15 17:34 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +    fheroes2::Blit( sprite, inX, inY, _mainSurface, outX, outY, width, height );
The grid is a little overlapped by the moat fragment:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/b0e454d0-567b-4e44-819e-9a018f52ddac)
The same if for the Bridge.
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/b3edcdb0-2166-4f7c-bab7-13345da09dfb)

 It is not a regression of current PR, but now it becomes noticeable.
 master build: 
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/b4fd8896-c71f-4156-be07-f168dd9fcad3)

2023-05-15 17:34 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +    const int32_t outX = rect.x + 1;
The moat fragment is shifted by one pixel to the right.
![fheroes2 2023-05-15 19-28-00-642](https://github.com/ihhub/fheroes2/assets/113276641/32e4c57d-0306-4408-9585-8fd1b932976a)

Also when troop is moving in the moat it moves on the water, not in it. :)

2023-05-18 15:44 UTC, ihhub requested changes
Hi @slawomir-witkowski , I left multiple comments and proposals. Would you mind to take a look at them in your spare time?

2023-05-18 15:44 UTC, ihhub commented on src/fheroes2/battle/battle_arena.h
> +            CASTLE_BRIDGE_POS = 49,
Can we reuse an existing enumeration entry **CELL_MOAT = 49,**?

2023-05-18 15:44 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +        return;
Just to be consistent with the rest code: please add parenthesis for this if-body as it is done for lines 1136-1138.

2023-05-18 15:44 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    const int32_t moatCellIds[ARENAH] = { 7, 19, 28, 39, 49, 61, 72, 84, 95 };
Could we please use std::array<int32_t> here as it does check the size of the array at initialization stage?

2023-05-18 15:44 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    const fheroes2::Sprite & sprite = fheroes2::AGG::GetICN( ICN::MOATWHOL, 0 );
The original image is made in a clumsy way as it is visible that this is a separate image. How about we change the logic of rendering the troops to be even better than in the original game? A simple algorithm to calculate the position of the unit and how much not to draw would solve the problem. What do you think?

2023-10-28 12:09 UTC, closed without merging

2023-10-28 12:11 UTC, slawomir-witkowski commented
Removed PR.