Update CP1250 font support - Slovak characters
ihhub/fheroes2 pull request #7184
Opened 2023-05-14 20:37 UTC by Roxterat

Update of CP1250 font support for characters:
ľ, ĺ, ô, ŕ, ä (both uppercase and lowercase, normal and small font, extra character "â" added too).
ť (lowercase t with caron) fixed.

2023-05-14 23:07 UTC, Roxterat commented
Trying to figure if "ľ " can exist and what's wrong with checks..

2023-05-14 23:34 UTC, Roxterat commented
Checks done, will see about lowercase L with caron.

2023-05-15 01:16 UTC, Roxterat commented
Lowercase L with caron solved, opening PR for review @zenseii .

2023-05-15 08:11 UTC, Roxterat commented
Oh, and also @Districh-ru , your review would be much appreciated as well, sorry I have mentioned only Zense, old habids from translations. :)

2023-05-15 15:28 UTC, Districh-ru requested changes
Well done, @Roxterat!
I have one question, could you take a look when you have time.

Also here is a screenshot from the game for letters from CP1250:
Š Ś Ť Ž Ź š ś ť ž ź Ł Ą Ş Ż ł µ ą ş Ľ ľ ż Ŕ Á Â Ă Ä Ĺ Ć Ç Č É Ę Ë Ě Í Î Ď Đ Ń Ň Ó Ô Ő Ö Ř Ů Ú Ű Ü Ý Ţ ß ŕ á â ă ä ĺ ć ç č é ę ë ě í î ď đ ń ň ó ô ő ö ř ů ú ű ü ý ţ 

![изображение](https://github.com/ihhub/fheroes2/assets/113276641/6dc6cdb3-4da6-439a-a9ac-3a046f0095dd)

Not to forget in future - there are still some letters to add to CP1250: [Ş](https://www.ascii-code.com/character/%C5%9E) [µ](https://www.ascii-code.com/character/%C2%B5) [Ă](https://www.ascii-code.com/character/%C4%82) [Ç](https://www.ascii-code.com/character/%C3%87) [Ë](https://www.ascii-code.com/character/%C3%8B) [Î](https://www.ascii-code.com/character/%C3%8E) [Đ](https://www.ascii-code.com/character/%C4%90) [Ţ](https://www.ascii-code.com/character/%C5%A2) [ß](https://www.ascii-code.com/character/%C3%9F) [ă](https://www.ascii-code.com/character/%C4%83) [ç](https://www.ascii-code.com/character/%C3%A7) [ë](https://www.ascii-code.com/character/%C3%AB) [î](https://www.ascii-code.com/character/%C3%AE) [đ](https://www.ascii-code.com/character/%C4%91) [ţ](https://www.ascii-code.com/character/%C5%A3)
They can be done later in a new PR when it will be needed. I don't request to add them in current PR. :)

2023-05-15 15:28 UTC, Districh-ru commented on src/fheroes2/gui/ui_font.cpp
> +            updateNormalFontLetterShadow( font[188 - 32] );
According to the available fonts I can notice that ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/a74d6a9f-36d4-4139-b922-202565fcf246) should have its caron not above the `L` but in the upper right corner of it, like in Normal font. What do you think?

Interesting, but in modern fonts the ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/94891d1a-5945-43ba-bfdf-2c26fe0589e8) ([Ľ](https://www.ascii-code.com/character/%C4%BD)) character is represented with apostrophe. :)
It is up to you @Roxterat what variant is better.

2023-05-15 17:47 UTC, Districh-ru commented
> Thank you for the better visuals, I shall attempt to present the work in PRs in better quality in further contributions myself. Yes, there are still characters that needs doing, I can safely make some of them but I am not completely certain about how all should be properly made, I might attempt in future whatsoever.

@Roxterat, I just replaced the translation for save file info in Polish translation file with all these letters. And now when I click the right mouse button on a save in load dialog I can see them rendered by the game engine. Here is the changed .mo file, you can use it in your tests: [pl.zip](https://github.com/ihhub/fheroes2/files/11480499/pl.zip)

2023-05-15 18:50 UTC, Roxterat commented
> > Thank you for the better visuals, I shall attempt to present the work in PRs in better quality in further contributions myself. Yes, there are still characters that needs doing, I can safely make some of them but I am not completely certain about how all should be properly made, I might attempt in future whatsoever.
> 
> @Roxterat, I just replaced the translation for save file info in Polish translation file with all these letters. And now when I click the right mouse button on a save in load dialog I can see them rendered by the game engine. Here is the changed .mo file, you can use it in your tests: [pl.zip](https://github.com/ihhub/fheroes2/files/11480499/pl.zip)

Nice, thanks for a set file for testing!

2023-05-16 13:46 UTC, Roxterat commented
@Districh-ru and @zenseii , commited fixes, charcters should be resolved accordingly.

![156](https://github.com/ihhub/fheroes2/assets/79506572/ce62cd82-f0c5-4c2f-a489-0c4f6b205304)
![156s](https://github.com/ihhub/fheroes2/assets/79506572/ac185cf2-f2f0-4a68-b42c-139af2d9abde)
![158](https://github.com/ihhub/fheroes2/assets/79506572/be1bf7df-62df-42fa-9877-156a1272544e)
![194](https://github.com/ihhub/fheroes2/assets/79506572/bfab62fb-4f2a-4ee2-8dfe-964041bf36a1)

line for Lowercase a with circumflex:
fheroes2::Copy( font[194 - 32], 7, 0, font[226 - 32], 3, 0, 3, 2 );

2023-05-16 13:46 UTC, Roxterat commented on src/fheroes2/gui/ui_font.cpp
> +            fheroes2::Copy( font[97 - 32], 1, 0, font[226 - 32], 5, 0, 1, 1 );
Solution in comments.

2023-05-16 13:46 UTC, Roxterat commented on src/fheroes2/gui/ui_font.cpp
> +            updateNormalFontLetterShadow( font[188 - 32] );
Solution in comments.

2023-05-16 15:45 UTC, Districh-ru approved these changes
👍

2023-05-16 18:54 UTC, oleg-derevenetz approved these changes

2023-05-16 18:55 UTC, merged

2023-05-16 18:55 UTC, oleg-derevenetz commented
@Roxterat thank you!