Update Spanish Translation
ihhub/fheroes2 pull request #7186
Opened 2023-05-15 10:29 UTC by diegombeltran

* Fix previous suggestions
* Adjust changes to PR limit
* Use UTF-8

2023-06-03 01:51 UTC, ihhub requested changes
Hi @diegombeltran , I left few comments here. Could you please take a look at them?

2023-06-03 01:51 UTC, ihhub commented on files/lang/es.po
> +msgstr "¿Quieres recuperar el control de la IA? "
Do we need a space at the end of the sentence? Also only the first sentence has been translated.

2023-06-03 01:51 UTC, ihhub commented on files/lang/es.po
>  #, fuzzy
For this case and at line 2017 `#, fuzzy` comment wasn't removed while for lines below it was. Both variations lead to the same results but it is good to be consistent.

2023-06-03 01:51 UTC, ihhub commented on files/lang/es.po
> +msgstr "Pts. de Daño Restantes"
Could you please check monster info dialog whether there is enough space to keep this long sentence?

2023-06-07 16:05 UTC, diegombeltran commented
Good afternoon.

I will check the comments and the conflicts before sunday.

Thank you for your time reviewing!

2023-06-22 16:41 UTC, Joarico commented on files/lang/es.po
> +msgstr "COMERCIAR"
If it doesn't fit it could be replace by "CAMBIAR" which is a bit shorter and means Exchange.

2023-06-22 16:43 UTC, Joarico commented on files/lang/es.po
> +msgstr "XL"
Why remove the dash between X and L in original text? That's not language dependant.

2023-06-22 16:47 UTC, Joarico commented on files/lang/es.po
Forgot to translate "ALL" which is "TODO"

2023-06-22 16:52 UTC, Joarico commented on files/lang/es.po
> +msgstr "ESCOGE"
zenseii is right, the verb form is not right. However, I would prefer SELECCIONAR if it fits available space, though, because it's more faithful to the original text.

2023-06-22 16:55 UTC, Joarico commented on files/lang/es.po
Second line not translated, should be "PARTIDA\n"
                                                             "ESTÁNDAR"

2023-06-22 16:56 UTC, Joarico commented on files/lang/es.po
Second line not translated, should be "PARTIDA\n"
"DE CAMPAÑA"

2023-06-22 17:00 UTC, Joarico commented on files/lang/es.po
Second line not translated, should be "CAMPAÑA\n"
"ORIGINAL"

2023-06-22 17:02 UTC, Joarico commented on files/lang/es.po
>  msgid "guildWell|EXIT"
Is "guildWell|EXIT" a proper string from the game? If it's so, which i doubt, the spanish translation has to be modified.

2023-06-22 17:04 UTC, Joarico commented on files/lang/es.po
> +msgstr "OK"
"VALE" makes a better translation than using english words, and it takes the same characters as the original text.

2023-06-22 17:17 UTC, Joarico commented on files/lang/es.po
> +msgstr "¿Quieres recuperar el control de la IA? "
Proper translation should be "¿Quieres recuperar el control de la IA? El efecto sólo tendrá efecto en "
                                               "el siguiente turno."
The space was already present on the original string.

2023-06-22 17:19 UTC, Joarico commented on files/lang/es.po
>  "A few\n"
Not translated. "Un puñado"

2023-06-22 17:25 UTC, Joarico commented on files/lang/es.po
> +msgstr "Toda la tropa %{race +1}"
The proper translation would be "Toda tropa de %{race} +1"

2023-06-22 17:29 UTC, Joarico commented on files/lang/es.po
>  msgstr ""
Missing translation "Orden del Ejército"

2023-06-22 17:31 UTC, Joarico commented on files/lang/es.po
>  msgstr "Conjuradores"
Proper translation should be "Lanzamiento Automático de Conjuros" or "Auto Conjurar" if space is problem.

2023-06-22 17:34 UTC, Joarico commented on files/lang/es.po
>  msgstr "OK"
"Vale" is better translation to avoid using english terms.

2023-06-22 17:37 UTC, Joarico commented on files/lang/es.po
>  msgstr "Conocimiento"
This won't fit. In original Heroes 2 spanish version, they've translated "Conocim." I suggest using "Saber" as translation, which means the same.

2023-06-22 17:37 UTC, Joarico commented on files/lang/es.po
> +msgstr "Pot. de Hech."
In the original Heroes 2 spanish version, they use Pot. Hechizo, but I think "Potencia" is a better solution.

2023-06-22 17:42 UTC, Joarico commented on files/lang/es.po
>  msgstr ""
missing translation "Ver info de la Balista"

2023-06-22 17:45 UTC, Joarico commented on files/lang/es.po
>  msgstr ""
Missing translation "¡La imagen espejada es destruida!"

2023-06-22 17:50 UTC, Joarico commented on files/lang/es.po
> +msgstr "Alianza Dragón"
"Alianza Dragontina" is a better translation

2023-06-22 17:55 UTC, Joarico commented on files/lang/es.po
> +msgstr "MIDI Extendido"
"MIDI Expansión" is the proper transaltion here. It refers to the new midi music for the towns in the expansion The Price of Loyalty, not to an extendend duration of the midi soundtrack.

2023-06-22 18:02 UTC, Joarico commented on files/lang/es.po
> +"Cargar\n"
If it's a button the translation it's OK cause otherwise won't fit. If not, refer to what zenseii said.

2023-06-22 18:02 UTC, Joarico commented on files/lang/es.po
>  msgstr "Comenzar una partida simple o multijugador."
"Comenzar una partida individual o multijugador." would make a better translation

2023-06-22 18:06 UTC, Joarico commented on files/lang/es.po
> +msgstr "Información de Sistema"
"Información del Sistema" or "Info. Sistema" if space is problem

2023-06-22 18:28 UTC, Joarico commented on files/lang/es.po
>  msgstr ""
If it refers to the turn order, "Orden del Turno" would make a better translation.

2023-06-26 18:13 UTC, diegombeltran commented on files/lang/es.po
> +msgstr "ESCOGE"
This was because of the available space. I'm checking all this buttons to see if they fit.

2023-06-26 18:15 UTC, diegombeltran commented on files/lang/es.po
> +msgstr "Pot. de Hech."
So be it!

2023-06-26 18:16 UTC, diegombeltran commented on files/lang/es.po
> +msgstr "ATRÁS"
Again, it was due to the button size

2023-06-26 18:21 UTC, diegombeltran commented on files/lang/es.po
> +msgstr "XL"
I think XL is the correct abbreviation. In fact, I would change it in the English language, instead of the Spanish file:
https://www.macmillandictionary.com/thesaurus-category/british/clothing-sizes

2023-06-26 18:24 UTC, diegombeltran commented on files/lang/es.po
The button is small, it doesn't fit. Until a solution is thought, I wouldn't change it.

2023-06-26 18:25 UTC, diegombeltran commented on files/lang/es.po
Size

2023-06-26 18:25 UTC, diegombeltran commented on files/lang/es.po
Size

2023-06-26 18:25 UTC, diegombeltran commented on files/lang/es.po
Size

2023-06-26 18:25 UTC, diegombeltran commented on files/lang/es.po
Button size

2023-06-26 18:29 UTC, diegombeltran commented on files/lang/es.po
> +msgstr "OK"
Looks like the RAE says so (Although capital OK is allowed). Changed to "VALE".

2023-06-26 18:30 UTC, Joarico commented on files/lang/es.po
> +msgstr "XL"
Then so be it, you seem to be better informed about this.

2023-06-26 18:39 UTC, Joarico commented on files/lang/es.po
> +msgstr "OK"
Thank you for your work Diego, great translation so far!

2023-06-26 18:46 UTC, diegombeltran commented on files/lang/es.po
> +msgstr "EN SITIO"
I had doubts with this one. I think "POR TURNOS" leads to confusion (At least for newcomers). "SILLA CALIENTE" would be the direct translation (maybe "ASIENTO CALIENTE" sounds better?). The translation breaks the button due to size in both cases. I would also leave "HOT SEAT" (as I would leave "OK" as confirm button), but I understand some people prefer to literally translate everything. My vote goes for "ASIENTO CALIENTE".

2023-06-26 18:47 UTC, diegombeltran commented on files/lang/es.po
>  "A few\n"
Not all the strings were translated in this PR. There's a limit of lines to avoid long reviews.

2023-06-26 18:47 UTC, Joarico commented on files/lang/es.po
> +msgstr "EN SITIO"
Asiento Caliente it's OK for me also, especially if it fits the button hehe

2023-06-26 18:49 UTC, diegombeltran commented on files/lang/es.po
>  msgstr "Conjuradores"
The string reviewed is "On".

2023-06-26 18:49 UTC, diegombeltran commented on files/lang/es.po
>  msgstr "OK"
The string reviewed is "Exit this menu"

2023-06-26 18:51 UTC, diegombeltran commented on files/lang/es.po
>  msgstr "Conocimiento"
The string reviewed is "Spell Power".
Anyways, "Conocimiento" fits, I tested it.

2023-06-26 18:53 UTC, diegombeltran commented on files/lang/es.po
> +msgstr "MIDI Extendido"
Changed

2023-06-26 18:53 UTC, diegombeltran commented on files/lang/es.po
>  msgstr "Comenzar una partida simple o multijugador."
Fixed

2023-06-26 19:15 UTC, diegombeltran commented on files/lang/es.po
>  msgstr ""
For the next PR

2023-06-26 19:17 UTC, diegombeltran commented on files/lang/es.po
There was another problem, the Ñ symbol was not available when I started to translate this strings. I'm not sure if this is already resolved @zenseii

2023-06-26 19:17 UTC, diegombeltran commented on files/lang/es.po
> +msgstr "XL"
@zenseii what do you think?

2023-06-26 19:18 UTC, diegombeltran commented
Good evening all,

I updated and fixed some of the strings you mentioned. There are some buttons that I can't change to avoid breaking buttons. Is there a solution planned for this?

2023-06-26 19:19 UTC, diegombeltran commented on files/lang/es.po
> +msgstr "Información de Sistema"
This is debatable, both work, but I'm going to change it to make you happy :D

2023-06-26 19:23 UTC, diegombeltran commented
> Hi, @diegombeltran. I've reviewed your PR and found some things you might want to look at if you have time.
> 
> In addition your PR now has 415 changes (total additions and removals). Could you please reduce this to 400 to stay within our limit for translation PRs?

Should I reduce? Maybe we can discard the problematic buttons until a better way comes up.

2023-06-26 19:28 UTC, diegombeltran commented on files/lang/es.po
> +msgstr "Pts. de Daño Restantes"
Hi @ihhub , unfortunately, no space left. I'm going to revert.

2023-06-26 19:31 UTC, diegombeltran commented on files/lang/es.po
> +"Cargar\n"
I think there are some strings like this one. I'm going to review them all.

2023-06-26 19:55 UTC, closed without merging