Slovak translation update
ihhub/fheroes2 pull request #7191
Opened 2023-05-16 10:25 UTC by Roxterat

Update of Slovak translation file, this time mostly using gtranslator.
Some creatures, mostly battle messages and effects, artifact descriptions.

2023-05-16 12:09 UTC, Roxterat commented
@zenseii ready for review.

2023-05-18 17:11 UTC, Roxterat commented
> Hi @Roxterat , @zenseii will take a look after some time as he is busy with another task at the moment.

No worries, I understand. There sure is much to be done and translation is not a priority to any of the core codes.

2023-06-03 16:50 UTC, ihhub requested changes
Hi @Roxterat , I left few comments here. Could you please take a look at them?

2023-06-03 16:50 UTC, ihhub commented on files/lang/sk.po
> +msgstr "OK"
Is EXIT called OKAY in Slovak?

2023-06-03 16:50 UTC, ihhub commented on files/lang/sk.po
> +msgstr "Náhodní bojovníci 1"
Shall we translate random monster(s) 2 and 3 as well?

2023-06-03 16:50 UTC, ihhub commented on files/lang/sk.po
> +msgstr "Cez dve polia"
I am not that this is correct naming of an ability as the word "monster" is missing. It is unknown that exactly 2 fields wide.

2023-06-03 17:59 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "OK"
> Is EXIT called OKAY in Slovak?

No, it's not. The reason why I have changed it for now is to let the text fit the size of it's button.

2023-06-03 18:00 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "Náhodní bojovníci 1"
I have reverted the translation of those since the amount of translated lines reached nearly 400.

2023-06-03 18:03 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "Cez dve polia"
> I am not that this is correct naming of an ability as the word "monster" is missing. It is unknown that exactly 2 fields wide.

I'm not sure if I understand what you mean by that. This should say that the monster is 2 tiles wide and the translated text says "Through (or across) two tiles".

2023-06-07 17:12 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "Odznak nešťastia"
This is indeed an indepth insight, however, I am not sure what Fizbin translates into in my language. I may search for Slovak translation of that particular Star Trek reference in order to make it as colse as possible.

2023-06-24 22:07 UTC, agiat86 requested changes
I like most of it. Good job.

2023-06-24 22:07 UTC, agiat86 commented on files/lang/sk.po
> +msgstr "UČIŤ"
UČIŤ SA or UČ SA, not UČIŤ, which means teach and not learn

2023-06-24 22:07 UTC, agiat86 commented on files/lang/sk.po
> +"%{name} znižuje cenu vzdania sa o %{count} percent celkovej ceny jednotiek, "
"vzdania sa" or "kapitulácie"? i like "kapitulácie" a bit better

2023-06-25 10:01 UTC, agiat86 commented on files/lang/sk.po
> +msgstr "Odznak nešťastia"
We might consider keeping it as "Fizbin", just like they left it untranslated in Star Trek. This is all I could find:
https://www.kontinuum.cz/databaze/hry-a-sporty/19/fizzbin

2023-06-25 12:28 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "OK"
I would leave it with PREČ for now despite the space limitations and term accuracy, ODÍĎ might be a possible alternative (uncertain due to the size of the word), with idas for improvement open. I do not know how to resolve this better as of yet.

2023-06-25 12:47 UTC, Roxterat commented
> I like most of it. Good job.

Based on the grammar changes you have made in the other PR I§d say it was rather painful to read. Perhaps I might not be that grammatically capable.

2023-06-25 15:10 UTC, agiat86 approved these changes

2023-06-25 23:15 UTC, Roxterat commented
@ihhub There is one conversation (so far) waiting to be resolved.

2023-06-27 06:40 UTC, ihhub commented on files/lang/sk.po
> +msgstr "Cez dve polia"
It's better to be specific about the size as there is another ability called 2-hex attack.

2023-06-28 08:40 UTC, Roxterat commented
> Hi @Roxterat , I left few comments here. Could you please take a look at them?

@ihhub The issues with this PR seem to be solved, potentially ready to be merged, at your discretion.

2023-06-28 10:00 UTC, ihhub approved these changes

2023-06-28 10:01 UTC, merged

2023-06-28 10:01 UTC, ihhub commented
@Roxterat , thank you so much for this translation update!