Add button shadow generation, rework Recruit dialog, add Evil interface to Recruit dialog.
ihhub/fheroes2 pull request #7192
Opened 2023-05-16 17:35 UTC by Districh-ru

Close #6670, relates to https://github.com/ihhub/fheroes2/issues/1893
This PR adds button (and not only button) shadows generation code and recreates the Recruit dialog to add Evil interface to Recruit dialog and give the ability to rearrange the UI elements.
![Recruit dialog](https://github.com/ihhub/fheroes2/assets/113276641/d14e416b-9855-40c0-9292-7c3ab358b7c2)

![Recruit info](https://github.com/ihhub/fheroes2/assets/113276641/9441342d-45e4-4d9f-a6b1-3969510055fc)

2023-05-24 13:33 UTC, Branikolog commented
Hi, @Districh-ru !
I've checked shadows for buttons (hope I haven't missed any).
Here's an issue I've found with upgrade arrows in recruit window:

https://github.com/ihhub/fheroes2/assets/55348946/42607560-5ea8-4a19-99c0-8ec4c2ee9e9f

Could you, please, look at this place?
Could you also point me which button shadow generation touches this PR exactly?

2023-05-24 14:15 UTC, Districh-ru commented
> Hi, @Districh-ru ! I've checked shadows for buttons (hope I haven't missed any). Here's an issue I've found with upgrade arrows in recruit window:

Hi, @Branikolog! Thanks for testing, I'll fix this issue soon.

> Could you, please, look at this place? Could you also point me which button shadow generation touches this PR exactly? I've looked through all possible buttons rendering and even found an issue (which is not related to current PR). :)

Only in the Recruit dialog all buttons has shadows, generated by a new algorithm.
When we will polish this PR and merge it, we can update button shadows for all other dialogs.

2023-05-24 15:27 UTC, Districh-ru commented
@Branikolog, the issue is fixed. Could you please take a look when you have time.

Also I want to mention that these shadows are also generated by the new algorithm: 
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/03c8d0f4-1bfa-44d1-8584-22553008f899) ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/3c20c383-cbbf-45b8-a0aa-fd99cb2138fa)

![изображение](https://github.com/ihhub/fheroes2/assets/113276641/40f1ebff-346e-4b8e-a8b3-35ea9475e250) ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/400e7549-1f04-421b-87f6-d2335bab0433)

2023-05-25 12:43 UTC, Branikolog approved these changes
Now everything relating shadows looks great!
The only issue I've noticed is left yellow arrow being pressed has yellow line on the north-west part.
![image](https://github.com/ihhub/fheroes2/assets/55348946/13ace4ad-dfaf-45d1-812e-b9a32fda033b)

But this issue is valid for master branch too and I suppose it's related to this particular button generation.
I think a new issue should be opened, since these buttons require some work to show proper pressing animation. Now it's a bit incorrect.

2023-05-25 13:29 UTC, ihhub requested changes
Hi @Districh-ru , I put several comments here. Would you mind to take a look at them?

2023-05-25 13:29 UTC, ihhub commented on src/fheroes2/gui/ui_button.cpp
> +            return false;
We never check the return value. We should remove it then.

2023-05-25 13:29 UTC, ihhub commented on src/fheroes2/gui/ui_button.h
> +        bool drawShadow( Image & output = Display::instance() ) const;
I don't think that we need to put this render specific method in the base class. I can see that we call this method only in one particular file where we know the input images for buttons. Shall we use this data and create just a separate helper function to handle the cases?

2023-05-25 17:36 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_recruit.cpp
> +        fheroes2::Copy( originalBackground, 138, 117, recruitWindow, 0, 63, 132, 4 );
We Copy only the header and the borders of "Cost per troop" window part. The other part of the image needs to be transparent to make shadows and to Blit it to the recruit dialog, so we need to reset the transform layer to "1".

2023-05-25 17:42 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_recruit.cpp
> +    fheroes2::Copy( originalBackground, 134, 159, background, 0, 0, 68, 19 );
👍

2023-05-25 17:48 UTC, Districh-ru commented on src/fheroes2/gui/ui_button.cpp
> +            return false;
Sure)
I used the `bool` type for this method to match the other `draw...` methods of the class.

2023-05-25 18:50 UTC, Districh-ru commented on src/fheroes2/gui/ui_button.h
> +        bool drawShadow( Image & output = Display::instance() ) const;
Sure, we can make a helper to render button shadows.
I only wanted to make it easy to use in any other file for dialog button shadows render (for the initialized button just call a method).
Currently this method was called in one file, but in future we may want to make shadows for buttons in other files, e.g. for the Virtual Keyboard (it is not done in current PR not to complicate it):
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/39ee87c7-bea0-453e-b3af-055a1a98c2fc)

If in future if it will be needed we may simply restore this method in a Button class.

2023-05-25 19:28 UTC, Districh-ru commented on src/engine/image.cpp
> +        const int32_t outWidth = out.width();
Sure)

2023-05-25 19:29 UTC, Districh-ru commented on src/engine/image.cpp
> +                                           || ( isInNonSingleLayer && ( *( transformIn + inOffset ) == 1 ) );
Done, now it looks better!

2023-05-26 14:28 UTC, ihhub requested changes
Hi @Districh-ru , I left few more tiny suggestions. Please take a look once you have time.

2023-05-26 14:28 UTC, ihhub commented on src/engine/image.h
> +    void addSoftShadow( const Sprite & in, Image & out, const Point & outPos, const Point & shadowOffset );
`Softly reduces` might not be understandable for many. How about **addGradientShadow**?

2023-05-26 14:28 UTC, ihhub commented on src/engine/image.cpp
> +                if ( transformTableId < 6 ) {
Shall we add the opposite check to reduce code complexity:
```cpp
if ( transformTableId == 6 ) {
    continue;
}
```
What do you think?

2023-05-26 14:28 UTC, ihhub commented on src/fheroes2/dialog/dialog_recruit.cpp
> +        if ( !button.isPressed() ) {
**isReleased()** does the same :)

2023-05-26 14:28 UTC, ihhub commented on src/fheroes2/dialog/dialog_recruit.cpp
> +    void drawButtonShadow( fheroes2::Image & output, const int buttonIcn, const uint32_t icnIndex, const fheroes2::Point offset )
**offset** input argument should be const reference instead of const value.

2023-05-26 14:28 UTC, ihhub commented on src/fheroes2/gui/ui_window.h
> +        }
Shall we call it more generic like **totalArea** (not the great name)? It doesn't matter whether it is with or without shadow. What do you think?

2023-05-26 14:48 UTC, Districh-ru commented on src/engine/image.h
> +    void addSoftShadow( const Sprite & in, Image & out, const Point & outPos, const Point & shadowOffset );
Hi, @ihhub.
:))
Yes, it would be better to name it Gradient (no Soft) shadow.

2023-05-26 15:02 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_recruit.cpp
> +    void drawButtonShadow( fheroes2::Image & output, const int buttonIcn, const uint32_t icnIndex, const fheroes2::Point offset )
Oops, missed it.
Thanks for your Eagle Eye skill!

2023-05-26 17:10 UTC, Districh-ru commented
> The only issue I've noticed is left yellow arrow being pressed has yellow line on the north-west part. ![upg arrow](https://user-images.githubusercontent.com/55348946/240915683-d7330d34-2212-4bca-b559-47abd816e85d.png)

Hi, @Branikolog, if forgot to say that it is fixed now. :)
![fheroes2 2023-05-26 20-06-11-575](https://github.com/ihhub/fheroes2/assets/113276641/b7ffafab-fcb9-4c8f-b39d-005947419402)
But these left/right arrow needs to be slightly redone in future as they are simply rotated up/down arrows and after the rotation they have incorrect shading.

2023-05-27 01:08 UTC, ihhub approved these changes

2023-05-27 01:23 UTC, merged

2023-05-27 01:23 UTC, ihhub commented
@Districh-ru , thank you so much for the changes!

2023-05-27 09:16 UTC, Branikolog commented
@Districh-ru 

> Hi, @Branikolog, if forgot to say that it is fixed now. :)

Glad to hear that! :)

> But these left/right arrow needs to be slightly redone in future as they are simply rotated up/down arrows and after the rotation they have incorrect shading.

That I was talking about here:

> I think a new issue should be opened, since these buttons require some work to show proper pressing animation. Now it's a bit incorrect.