Utilize zlib optimized impl of CRC32 checksum algorithm instead of reinventing wheel.
ihhub/fheroes2 pull request #7196
Opened 2023-05-17 22:13 UTC by KOLANICH

2023-05-18 00:04 UTC, oleg-derevenetz commented on src/engine/tools.cpp
> +#include "zlib.h"
Hi @KOLANICH Please use `#include <zlib.h>` and fix the overall code style.

2023-05-18 14:17 UTC, KOLANICH commented on src/engine/tools.cpp
> +                                     "Too large `length` provided to `calculateCRC32`. Must be no larger than 0xFFFFFFFF." );
I have fixed the message to show `std::numeric_limits<uInt>::max()` instead of numeric value. Using the real platform-specific value means we would have to either construct the string in runtime ( so use streams, bad, and IMHO is overkill), or construct it in compile-time, but this functionality is not within C++ standard library.

Of course we can use CMake to populate that, but IMHO it is also an overkill.

2023-05-18 14:38 UTC, oleg-derevenetz commented on src/engine/tools.cpp
> +                                     "Too large `length` provided to `calculateCRC32`. Must be no larger than 0xFFFFFFFF." );
In fact, this operation should never normally happen :) So, even if it works a little suboptimally, it doesn't mean anything. But the current solution is fine too, this is not a matter of principle. BTW, CMake is only one of the available build methods, you should not expect that it will always be used.

2023-05-18 14:40 UTC, KOLANICH commented on src/engine/tools.cpp
> +                                     "Too large `length` provided to `calculateCRC32`. Must be no larger than 0xFFFFFFFF." );
>In fact, this operation should never normally happen :)

I know. That's why there is no point to invest too much into it, investing a bit is OK, but if there is anything wrong, then one has to do debugging anyway.

2023-05-18 14:47 UTC, oleg-derevenetz approved these changes
LGTM. Hi @Districh-ru since you have the official non-English game assets, could you please verify that they are recognized correctly, because it's one of the main things that CRC32 calculation is used for.

2023-05-18 15:31 UTC, ihhub commented
Hi @Branikolog , please verify these changes as well. The engine should work as intended so a simple startup and few clicks would be sufficient.

2023-05-18 15:31 UTC, ihhub approved these changes

2023-05-18 16:26 UTC, Districh-ru requested changes
Hi @KOLANICH. I left one comment, could you take a look when you have time.

2023-05-18 16:26 UTC, Districh-ru commented on src/engine/tools.cpp
> +        return ~crc32( 0, data, static_cast<uInt>( length ) );
I tested this PR with Russian (Buka) assets.
The result of CRC32 calculation now is 0x2A30750C (707818764), in binary:
00101010001100000111010100001100
and should be: 0xD5CF8AF3 (3587148531), in binary:
11010101110011111000101011110011

As I can conclude now we don't need to invert the bits of returned value:
```suggestion
        return crc32( 0, data, static_cast<uInt>( length ) );
```

2023-05-18 18:39 UTC, Districh-ru approved these changes

2023-05-19 14:34 UTC, Branikolog approved these changes

2023-05-20 01:29 UTC, merged

2023-05-20 01:29 UTC, ihhub commented
@KOLANICH , thank you very much for this improvement!