Some refactorings in borderdrawing code.
ihhub/fheroes2 pull request #7204
Opened 2023-05-20 15:51 UTC by KOLANICH

2023-05-24 04:38 UTC, ihhub requested changes
Hi @KOLANICH , I put several comments in this pull request. Could you please take a look at them? Also as I understood correctly it is just code cleanup, isn't it?

2023-05-24 04:38 UTC, ihhub commented on src/fheroes2/gui/interface_border.cpp
> +    drawHeroesAndTownsHorizontalBorders();
Could you please explain the benefit of having a lambda-function and a single call of it just right its declaration? Wouldn't it be faster to just have normal code?

2023-05-24 04:38 UTC, ihhub commented on src/fheroes2/gui/interface_border.cpp
> +    auto drawLeftBorder = [&]() {
The same comment as for **drawHeroesAndTownsHorizontalBorders**: is there a benefit of having a lambda function and calling it only once? It does not solve code duplication issues.

2023-05-24 04:38 UTC, ihhub commented on src/fheroes2/gui/interface_border.cpp
> +    auto drawHorizontalBorder = [&]( bool isTop ) {
**isTop** can be **const** as we don't modify it within the function.

2023-05-24 04:38 UTC, ihhub commented on src/fheroes2/gui/interface_border.cpp
> +        auto PadWidthLeft = isTop ? topPadWidthLeft : bottomPadWidthLeft;
Please use camelCase variable naming as well as avoid using **auto** for plain old data types. Moreover, this variable can be const.

2023-05-24 12:46 UTC, KOLANICH commented on src/fheroes2/gui/interface_border.cpp
> +    auto drawHorizontalBorder = [&]( bool isTop ) {
Fixed.

2023-05-24 12:46 UTC, KOLANICH commented on src/fheroes2/gui/interface_border.cpp
> +        auto PadWidthLeft = isTop ? topPadWidthLeft : bottomPadWidthLeft;
Fixed.

2023-05-24 20:22 UTC, oleg-derevenetz commented on src/fheroes2/gui/interface_border.cpp
> +    drawHeroesAndTownsHorizontalBorders();
Then there is no need to give the lambda a name at all. You can just do this:

```cpp
  [](){
      [... do something ...]
  }();
```

Also, if you want to avoid name conflicts / reuse the same variable names in different blocks / manage variable scopes for RAII, then you can just use code blocks:

```cpp
{
  std::scoped_lock lock{m1};
  [... do something ...]
}

{
  std::scoped_lock lock{m1, m2};
  [... do something else...]
}
```

Lambdas for the purposes of code organization alone look redundant. Lambdas are useful mainly for reusable code, or maybe some complex code that needs to initialize a `static` or `const`/`constexpr` variable.

2023-05-24 22:12 UTC, KOLANICH commented on src/fheroes2/gui/interface_border.cpp
> +    drawHeroesAndTownsHorizontalBorders();
>Then there is no need to give the lambda a name

Of course there is a need. First it serves the purpose of documenting. So called "self-documenting code". Second, it can later be promoted to a non-lambda, leaving just a sequence of function calls within that method. If I wanted to have it anonymous + some wrapping, just a code block of `{}` without any lambda should have been OK.

2023-05-24 22:14 UTC, oleg-derevenetz commented on src/fheroes2/gui/interface_border.cpp
> +    drawHeroesAndTownsHorizontalBorders();
> Of course there is a need. First it serves the purpose of documenting. So called "self-documenting code". Second, it can later be promoted to a non-lambda, leaving just a sequence of function calls within that method.

It looks like over-engineering for a "future" that can never come.

2023-08-23 04:13 UTC, ihhub commented
I am closing this pull request as it brings no value to the code.

2023-08-23 04:13 UTC, closed without merging