Russian translation: fix some inaccuracies.
ihhub/fheroes2 pull request #7207
Opened 2023-05-20 17:51 UTC by KOLANICH

2023-05-21 08:19 UTC, Districh-ru requested changes
Hi, @KOLANICH.
I left some comments, could you take a look when you have time.

2023-05-21 08:19 UTC, Districh-ru commented on files/lang/ru.po
> +msgstr "Изначальная кампания"
Lets translate this by the name of the campaign:
```suggestion
msgstr "Войны за престол"
```

2023-05-21 08:19 UTC, Districh-ru commented on files/lang/ru.po
> +msgstr "Расширенная кампания"
```suggestion
msgstr "Цена верности"
```

2023-05-21 08:19 UTC, Districh-ru commented on files/lang/ru.po
> +msgstr "Абсолютный артефакт"
"Абсолютный" does not sounds good with the artifact. In Buka version it is translated as "Могущественный артефакт", it suits the better. But IMHO the current translation "Великий артефакт" is good and does not need to change.
@Branikolog and @KOLANICH, what do you think?

2023-05-21 08:19 UTC, Districh-ru commented on files/lang/ru.po
> +msgstr "Кастовать заклинание приключения."
Lets not use the loanwords. Or one day we will come to: "Кастовать адвенчурный спелл". :))
```suggestion
msgstr "Произнести заклинание приключения."
```

2023-05-21 08:42 UTC, KOLANICH commented on files/lang/ru.po
> +msgstr "оглядеть мир"
1. I think we shouldn't care what is written in official translations. We should make an own one.
2. It is a button, so the word `view` on it is a verb.

2023-05-21 08:46 UTC, KOLANICH commented on files/lang/ru.po
> +msgstr "Войны Престолонаследия"
In `Война Кольца` both words are capitalized because it is the name of the war. The same way, whether the word `Престолонаследия` should be capitalized depends on whether it is the name of the war. I assumed that it is the name of the war and not just convention in English language to capitalize words in titles, and so capitalized it.

2023-05-21 08:48 UTC, KOLANICH commented on files/lang/ru.po
> +msgstr "Изначальная кампания"
I don't think so. It is distortion of the original meaning. In `msgid` (which is assumed to be the string in English) it is clearly said "Original Campaign". If we want to translate it as the name of the campaign, then we should change `msgid` too.

2023-05-21 08:49 UTC, KOLANICH commented on files/lang/ru.po
> +msgstr "Расширенная кампания"
I don't think so. It is distortion of the original meaning. In msgid (which is assumed to be the string in English) it is clearly said "Expansion Campaign". If we want to translate it as the name of the campaign, then we should change msgid too.

2023-05-21 09:06 UTC, Districh-ru commented on files/lang/ru.po
> +msgstr "оглядеть мир"
This is a name of a hotkey:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/5b00e5ea-5acc-46e8-8f4a-d7806a1dc0a7)

I suggested to use the translation from assets as then the player can correlate the name of the hotkey with the other game. And if in one place it will be "Показать мир", in second "Обзор мира" and in the third "оглядеть мир" it will be a mess of different translations of one thing.
The word "Показать" is a verb so it can be used for an action of a button/hotkey and "Показать мир" describes what action will be performed if you press this button.
To better match the original phrase we can translate it as "Посмотреть мир". What do you think?

2023-05-21 09:13 UTC, KOLANICH commented on files/lang/ru.po
> +msgstr "Пазл"
![](https://static.wikia.nocookie.net/mightandmagic/images/e/e8/H2-PuzzleMap.jpg/revision/latest/scale-to-width-down/185?cb=20100722114215&path-prefix=en)

Looks like a https://en.wikipedia.org/wiki/Jigsaw_puzzle . The corresponding Russian article is just https://ru.wikipedia.org/wiki/Пазл - this way this kind of puzzles is called in Russian. So my translation is correct, and Buka's one is just another example of "надмозгового перевода".

2023-05-21 09:18 UTC, Districh-ru commented on files/lang/ru.po
> +msgstr "Изначальная кампания"
This was discussed earlier - Since we're going to add new Expansion campaign, Original/Expansion translations would make a mess. (https://github.com/ihhub/fheroes2/pull/6335#issuecomment-1433179145)
So we decided to name them not Original/Expansion but by the name of the campaign. This will add specificity.  Russian translation in this case is a little ahead. :)

@Branikolog what is your opinion?

2023-05-21 09:30 UTC, KOLANICH commented on files/lang/ru.po
> +msgstr "уже знает"
I think we need at least 2 sets of translation files. One is the maximally accurate translation. And another one as patches to the translation that don't claim they are the translation, but that modify the text of the game, fix original text bugs and so on. The patches should be opt-in in the settings.

2023-05-21 09:34 UTC, KOLANICH commented on files/lang/ru.po
> +"Указывает, создана ли карта для версии игры \"Войны Престолонаследия\" или \"Цена "
See https://github.com/ihhub/fheroes2/pull/7207#discussion_r1199723729

2023-05-21 09:41 UTC, KOLANICH commented on files/lang/ru.po
> +msgstr "Абсолютный артефакт"
Replaced with `Наилучший Артефакт`. All capitalized when in English it is capitalized, all lowercase when in English it is all lowercase (I think it is a bug of the original text). Also I have reworked the names of instances of Ultimate Artifacts: since in English they contain the word `Ultimate` I believe that in translation they should also contain the translation of the word `Ultimate`.

2023-05-21 09:44 UTC, Districh-ru commented on files/lang/ru.po
> +msgstr "уже знает"
Then the accurate translation should be "уже знает этот навык", not "уже знает".)
And it is a good idea to have in future something like: https://forum.heroesworld.ru/showthread.php?t=12632

2023-05-21 10:01 UTC, Branikolog commented on files/lang/ru.po
> +msgstr "Пазл"
Hi, @KOLANICH 
I agree with @Districh-ru , "Карта-загадка" suits better, as it has  "карта" which explains this game mechanic: a map to find something. I personally consider term "пазл" as some sort of quest to solve. Also, I prefer to have as much native literary speech as it possible, without contemporary loaned words.

2023-05-21 10:06 UTC, KOLANICH commented on files/lang/ru.po
> +msgstr "Кастовать заклинание приключения."
I guess we should discuss how are we going to translate the word [`cast`](https://en.wiktionary.org/wiki/cast) in the context of spells. I guess `cast` is there in the meaning very close to `to throw', `to direct (one's eyes, gaze etc.)`, since the most of spells in fantasy games settings are animated as wizards throwing something to enemies (and also the cursor in the game becomes an arrow), and `to throw out or emit (about smell)`. While casting a spell is not necessarily to be directed to anyone (though in a lot of cases it can be animated as a wizard casting some sheds of magic into the free space), for some it can be animated as a wizard glowing and emanating the magic.

From the other side a there is an established loanword "кастовать" as a translation of the word "cast" specifically in the context of magic and fantasy worlds. And there is nothing wrong with using loanwords. A language is a developing live system that constantly gets new words from other languages. And it is a good thing. And instead of trying to isolate a language one should make it better, creating the words for the concepts missing in a native language, including using the words of foreign languages.

So, if we decide "to preserve language purity", it is proposed to use the words `пустить`, `запустить` when a spell is directed to someone and `испустить` when it is undirected, as semantically similar to `to throw' and `to throw out or emit (about smell)`.

`колдовать` is not suitable, as it describes a long process usually over inanimate things, like an artifact, like a piece of computer software.

If we decide that using loanwords is OK for this concept, then `кастовать`.

2023-05-21 10:14 UTC, Branikolog commented on files/lang/ru.po
> +msgstr "оглядеть мир"
"Показать мир" couldn't be changed as it's the part of view window UI. So it would be better to keep consistent all similar translations regarding viewing map.
So I personally prefer "Показать мир" here. Having different translations for the same mechanic looks not so well.

2023-05-21 10:23 UTC, KOLANICH commented on files/lang/ru.po
> +msgstr "Пазл"
I think all "creativities" in translations should be clearly separated and disableable via prefs. I guess at least 2 additional sets of t4ranslation files are needed. The first one fixes bugs in original game texts. And another one is creativities their authors use trying to improve the game. The word "Карта" contains the meaning that wasn't present in the word "Puzzle". It is an attempt to improve the game, but it distorts the meaning the creators of the game have put into the game.

2023-05-21 11:59 UTC, Branikolog commented on files/lang/ru.po
> +msgstr "Пазл"
@KOLANICH 
Maintaining several translations for the same language is possible, for sure. Probably not so bad idea for future... But it's not a priority for now for the core team. Who is going to maintain and work on these "creative" translations? Homm2 has tons of texts and fheroes2 team and volunteers spent like months creating the current implementation in the past. I suggest to focus right now on the current translation, making it as much closer to the original as possible, fixing notable mistakes and keeping the entire text style (without loaned or contemporary words and slang). Otherwise we'd be stuck under dozens of debates on controvertible places for several different translations. Also, I believe, than 99% of users prefer a single classic translation, and choosing between several would be appreciated only by a few players. So working on  several translations is quite questionable from the time investment point.
"Пазл" is the least suited word in my opinion. I'd better prefer native russian word "головоломка", than loaned one(which is commonly used nowadays).
Also, "головоломка" is written in the puzzle UI, (the same to "view world") so I agree for this translation for the sake of consistency.
It could even be a "карта-головоломка", but definitely not a "пазл". Actually, I'm OK with current implementation too,

2023-05-21 12:26 UTC, KOLANICH commented on files/lang/ru.po
> +msgstr "Пазл"
>Maintaining several translations for the same language is possible, for sure.

Not the same, but a patch.

>Who is going to maintain and work on these "creative" translations?

People interested in the translations being "creative" I guess?

>I suggest to focus right now on the current translation, making it as much closer to the original as possible, 

This is what I'm doing :) Under "original" I mean the English version, not Buka "надмозговый" translation.

>Otherwise we'd be stuck under dozens of debates on controvertible places for several different translations

No problems with discussing things. It is how things should be done.

>99% of users prefer a single classic translation

Most of the users who use translations don't know the language of original and have never known about all the отсебятине inserted by translators. And a lot of will get disgusted when they learn the language and start getting familiar with original works. It is not so because translation is inherently lossy (yes, there are inevitable losses related to that some pieces of information are tightly coupled to languages they are in, it is **impossible** to translate poems and wordplay for example), but because the majority of translators abuse their positions and insert the stuff they think is creative instead of working hard to minimize the differences in the meaning to the original work.

>"Пазл" is the least suited word in my opinion. I'd better prefer native russian word "головоломка", than loaned one(which is commonly used nowadays).

OK, since it is written just `puzzle`, not `jigsaw puzzle`.

2023-05-21 12:34 UTC, KOLANICH commented on files/lang/ru.po
> +msgstr "уже знает"
>Then the accurate translation should be "уже знает этот навык", not "уже знает".)

You are right. Fixed.

2023-05-21 12:58 UTC, Districh-ru commented on files/lang/ru.po
> +msgstr "Абсолютный артефакт"
In English all artifact names and headers Have Every Word With Capital First Letter, but in Russian only the letter of the first word is capitalized.
Also why `Наилучший` is better than `Великий`?
This are the translations from Lingvo:
```
1) последний, конечный; завершающий, окончательный
2) максимальный; предельный, крайний
3) самый отдалённый
4) первичный, первоначальный, исходный, основной
5) конечный; предельный; совершенный; критический
```
From these words `совершенный` suits the word "артефакт" : `Совершенный артефакт`.

IMHO It is better to keep "Великий артефакт" as it suits the game well and correctly describes the value of this artifact.

2023-05-21 15:17 UTC, KOLANICH commented on files/lang/ru.po
> +msgstr "Абсолютный артефакт"
Wiktionary says

>* Final; last in a series.
>* (of a syllable) Last in a word or other utterance.
>* Being the greatest possible; maximum; most extreme.
>* Being the most distant or extreme; farthest.
>* That will happen at some time; eventual.
>* Last in a train of progression or consequences; tended toward by all that precedes; arrived at, as the last result; final.
>* Incapable of further analysis; incapable of further division or separation; constituent; elemental.

By choosing `Наилучший` (as the kind of `the greatest possible`) I have tried to reflect the meaning is that it is the unique artifact exceeding the capacities (the count by which stats increases) of all the artifacts of the same effect (increase of a stat). Maybe `предельный` then? Or `Величайший`?

I also would like to keep "Великий", but IMHO `великий` is a too weak translation for the word `ultimate` (though the word `ultimate` has been dis-valued a bit by the titles having it in itself). Again, for corrected texts IMHO we need a separate set of string mapping files.

2023-05-24 04:42 UTC, ihhub commented
Hi @KOLANICH , @Districh-ru and @Districh-ru , as we faced similar issues in the past if anyone is debating which was the translation should go we must follow these steps:
- how it is translated for Heroes 2 **official** translation
- how it is translation for other games in HoMM series within **official** translation
- follow the same translation as it is done for translated game resources

I hope it clarifies some things in this pull request :)

2023-05-24 12:51 UTC, closed without merging