Update the TRANSLATION.md file
ihhub/fheroes2 pull request #7221
Opened 2023-05-23 21:06 UTC by Arthusppp

A step to update the TRANSLATION.md file.

The idea behind this change is to slightly reorganise the file into the following sections:
- Intro
- Current status
- Adding new translations/localizations
- Editing translations - Before you start
- Editing translations - Your first or next translation
- Other topics (currently Updating PO templates and translatable strings in PO files)

The second idea is to add few high-level instructions on cooperating and using the Github.

This change tackles (but does not resolve) second topic of #7089.

2023-05-27 02:51 UTC, ihhub requested changes
Hi @Arthusppp , I left multiple comments here. Would you mind to take a look at them?

2023-05-27 02:51 UTC, ihhub requested changes
Hi @Arthusppp , I left multiple comments here. Would you mind to take a look at them?

2023-05-27 02:51 UTC, ihhub commented on docs/TRANSLATION.md
> +and you are happy to share it, you will have to prepare a Pull Request.
As a standard of any document we should add an abbreviation `(PR)` at the first place where the word is being used. We should remove the abbreviation introduction at line 125.

2023-05-27 02:51 UTC, ihhub commented on docs/TRANSLATION.md
> +### Finding translatable strings in the codebase
This section is questionable and should be rewritten. It is not clear what is the purpose of this section. I suggest to follow this idea:
```
All original translatable strings are located in the source code of the project. If you need to clarify where this string is being used you can search for ....
```
Does it sound better?

2023-05-27 06:35 UTC, Arthusppp commented on docs/TRANSLATION.md
> -## Current status
Oops, my bad, I did not take other docs into consideration. Updated.

2023-05-27 06:36 UTC, Arthusppp commented on docs/TRANSLATION.md
> +A fork is your copy of the fheroes2 repository. It gives you a safe space to prepare and test your changes. You can read here how to [create a fork](https://docs.github.com/en/get-started/quickstart/
Fixed.

2023-05-27 06:37 UTC, Arthusppp commented on docs/TRANSLATION.md
> +and you are happy to share it, you will have to prepare a Pull Request.
Updated. The main document uses always long form without abbreviation. The abbreviation is used in the last section ("Pull request (PR) restrictions")

2023-05-27 06:38 UTC, Arthusppp commented on docs/TRANSLATION.md
> +### Finding translatable strings in the codebase
It sounds much better. Thanks and take a look how I updated here.

2023-05-29 19:52 UTC, Arthusppp commented on docs/TRANSLATION.md
> +a pull request with your changes, you will have to save the PO file in UTF-8 encoding because this is what Github supports.
I disagree with this one, as in the document we use the "pull request" form. The short form is used later in the document, in the "Pull request (PR) restrictions" (line 119).

2023-05-30 20:40 UTC, Arthusppp commented
Hi @zenseii, many thanks for your review. I have applied all of your comments (except one). Please take a look.

2023-06-01 20:18 UTC, Arthusppp commented on docs/TRANSLATION.md
> +a pull request with your changes, you will have to save the PO file in UTF-8 encoding because this is what Github supports.
> This is why I would suggest to write "Pull Request (PR)" at the first occurence of this within the file, and then write PR for all subsequent occurrences.
> 
> This should also help familiarize contributors with the github-lingo, because most of the time we write "PR" and never the full "pull request".
> 
> What do you think?

Hi @zenseii,
I believe this is a matter of taste. For example, the GitHub instruction about PR never uses the PR form: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests. 

Also, I remember, when I joined the fherose2 - I knew nothing about PR. The github-lingo was new to me. That's why I find the "no abbreviation" form easier to read.

2023-06-02 11:25 UTC, Arthusppp commented on docs/TRANSLATION.md
> +a pull request with your changes, you will have to save the PO file in UTF-8 encoding because this is what Github supports.
Hi @zenseii, my proposition is to use "pull request" in the whole document. In the latest commit I have replaced all "PR" abbreviations with "pull request" word.

2023-06-03 16:42 UTC, ihhub approved these changes

2023-06-12 11:40 UTC, Arthusppp commented
> Hi, @ihhub. I made a PR to @Arthusppp's branch with my proposed changes and am awaiting his feedback.

Hi @zenseii, hi @ihhub, ohhh gosh, I have missed this PR. I have updated the Translation.md file as per Zenseii's input. I believe the latest commit contains all your comments.

2023-06-13 01:11 UTC, merged