Update Polish translation
ihhub/fheroes2 pull request #7232
Opened 2023-05-26 11:50 UTC by Arthusppp

Update hotkeys translation

2023-06-07 02:46 UTC, ihhub requested changes
Hi @Arthusppp , I left one comment in this pull request. Could you please take a look at it?

2023-06-07 02:46 UTC, ihhub commented on files/lang/pl.po
> +msgstr "BOHATEROWIE"
Please check how it looks in the game. It is a button in the Kingdom Overview screen. I believe we need to add line separator for this phrase.

2023-06-07 21:03 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "BOHATEROWIE"
Screenshot here: 
![image](https://github.com/ihhub/fheroes2/assets/85434237/3b88d9c2-155e-444a-a04e-5c150974aa8b)

2023-06-08 05:31 UTC, ihhub approved these changes

2023-06-08 05:32 UTC, merged

2023-06-08 05:32 UTC, ihhub commented
@Arthusppp , thank you so much for this update!