Reduce memory usage by the engine: do not allocate memory for the transform layer when it is not used (for single layer image case)
ihhub/fheroes2 pull request #7233
Opened 2023-05-26 14:46 UTC by Districh-ru

This PR disables the `transform` layer for images that are set as `singleLayer` and reworks the image processing functions not to work with this layer for such images.

For 1366x768 resolution with opened View World for XL map the engine takes 72 MB, in master build - 82 MB.

2023-05-28 05:36 UTC, ihhub requested changes
Hi @Districh-ru , I left several comments in this pull request. Would you mind to take a look at them?

2023-05-28 05:36 UTC, ihhub commented on src/engine/h2d_file.cpp
> +        }
As of now all images being stored in h2d file are dual-layer images. I suggest to revert changes as of now.

2023-05-28 05:36 UTC, ihhub commented on src/engine/image.h
> +        }
Please revert these changes. Virtual functions cannot be inlined.

2023-05-28 05:36 UTC, ihhub commented on src/engine/image.h
> +        Image( const int32_t width_, const int32_t height_, const bool singleLayer_ = false );
We must avoid using default parameters for arguments, especially for widely used classes and structures. I recommend to keep the same number of argument for the constructor and for player where we need to create a single-layer image just call the required method first and only then resize.

2023-05-28 05:36 UTC, ihhub commented on src/engine/image.h
> +        Sprite( const int32_t width_, const int32_t height_, const int32_t x_ = 0, const int32_t y_ = 0, const bool singleLayer_ = false );
The same as for Image: please do not use default parameters for an argument.

2023-05-28 05:36 UTC, ihhub commented on src/engine/image.h
>          int32_t _height;
We should provide default values for everything or for nothing to be consistent with the code.

2023-05-28 05:36 UTC, ihhub commented on src/engine/image.cpp
> +            // assert( _singleLayer == image_._singleLayer );
Please either remove the code and uncomment it.

2023-05-28 05:36 UTC, ihhub commented on src/engine/image.cpp
> +        const size_t size = _singleLayer ? static_cast<size_t>( width_ * height_ ) : static_cast<size_t>( width_ * height_ ) * 2;
Interesting that here we put width and height under a single static cast while for other places we put only width.

2023-05-28 05:36 UTC, ihhub commented on src/engine/image.cpp
> +            // Contour can be created only for non zero images with transform layer.
How about `A contour can be created only for non-empty images with the transform layer.` ?

2023-05-28 05:36 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> -    namespace AGG
Can we please revert the changes related to namespace text offset as almost the whole file was modified for this?

2023-05-28 05:36 UTC, ihhub commented on src/engine/image_tool.cpp
> +    Sprite decodeICNSprite( const uint8_t * data, const uint32_t sizeData, const int32_t width, const int32_t height, const int16_t offsetX, const int16_t offsetY,
The information related to the number of layers should come from ICN itself, not the opposite way around. Once we read an image we will know whether there are any transform pixels present. If they are not then we can convert the image into a single-layer. Yes, it is not the best approach in terms of performance but it is much more flexible. What do you think?

2023-05-28 05:53 UTC, Districh-ru commented on src/engine/h2d_file.cpp
> +        }
Hi @ihhub , yes, in h2d all images are double-layer, but if we want to get the single-layer image not to waste memory for storing transform layer with zeros (e.g. for "hotkeys_icon.image" and "graphics_icon.image") we can make `image` single-layer before calling `h2d::readImage()` and so the loader will not waste resources for reading the transform layer.
We can revert these changes and convert the image to single-layer after calling `h2d::readImage()` but we will waste resources for reading transform layer, and then for converting image data from double-layer to single-layer.

Can we change the h2d images format to store the `singleLayer` bit?

2023-05-28 05:56 UTC, Districh-ru commented on src/engine/image.h
> +        }
Sure!

2023-05-28 05:58 UTC, Districh-ru commented on src/engine/image.h
> +        Image( const int32_t width_, const int32_t height_, const bool singleLayer_ = false );
Or can we revert changes in this constructor and make a new constructor `Image( const int32_t width_, const int32_t height_, const bool singleLayer_ );` ?

2023-05-28 05:59 UTC, Districh-ru commented on src/engine/image.h
>          int32_t _height;
Sure!)

2023-05-28 06:00 UTC, Districh-ru commented on src/engine/image.cpp
> +            // assert( _singleLayer == image_._singleLayer );
I forgot to remove the comments after testing..

2023-05-28 06:01 UTC, Districh-ru commented on src/engine/image.cpp
> +        const size_t size = _singleLayer ? static_cast<size_t>( width_ * height_ ) : static_cast<size_t>( width_ * height_ ) * 2;
I'll fix this line.

2023-05-28 06:03 UTC, Districh-ru commented on src/engine/image.cpp
> +            // Contour can be created only for non zero images with transform layer.
Yes, it sounds better!

2023-05-28 06:04 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> -    namespace AGG
Sure)

2023-05-28 06:06 UTC, ihhub commented on src/engine/h2d_file.cpp
> +        }
Yes, we can change it as well as we should modify some existing images stored there as well. Therefore, I am proposing not to touch this part and address this in a separate pull request.

2023-05-28 06:08 UTC, ihhub commented on src/engine/image.h
> +        Image( const int32_t width_, const int32_t height_, const bool singleLayer_ = false );
I think it is not intuitive for the developers to have such a constructor as it rises questions:
- so what type of image a normal constructor creates?
- why we can't immediately create a single-layer image without resizing?

One way is to add to every constructor such an option or just have a single method to do this.

2023-05-28 06:11 UTC, Districh-ru commented on src/engine/image_tool.cpp
> +    Sprite decodeICNSprite( const uint8_t * data, const uint32_t sizeData, const int32_t width, const int32_t height, const int16_t offsetX, const int16_t offsetY,
Sure, I'll try this approach a little later.

2023-05-28 06:12 UTC, Districh-ru commented on src/engine/h2d_file.cpp
> +        }
OK, lets leave it to a separate PR, I'll revert the changes.

2023-05-28 06:17 UTC, Districh-ru commented on src/engine/image.h
> +        Image( const int32_t width_, const int32_t height_, const bool singleLayer_ = false );
OK, lets revert the changes for now and if ti will be needed in future we can make a method to create and resize the image or add the `const bool singleLayer_` to every constructor.

2023-05-30 14:34 UTC, ihhub commented
Hi @Districh-ru , something is wrong with `src/fheroes2/battle/battle_interface.cpp` file as it has 11k changed lines.

2023-06-10 07:04 UTC, ihhub requested changes
Hi @Districh-ru , I left several more comments here. Could you please check them?

2023-06-10 07:04 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                if ( isTransformLayerNotUsed( _icnVsSprite[id][i] ) ) {
Here we are running through all data twice. We should do such a check within `decodeICNSprite()` function. Otherwise, this code will slow down resource loading in twice.

2023-06-10 07:04 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                // Sorceress and Necromancer captains have incorrect transparent pixels.
What values do these pixels have?

2023-06-10 07:04 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                        _icnVsSprite[id][i]._disableTransformLayer();
Aren't we doing the same in `LoadOriginalICN()` function?

2023-06-10 12:22 UTC, Districh-ru commented on src/engine/h2d_file.cpp
> +        assert( !image.singleLayer() );
Hi, @ihhub, sure. I added a comment and a TODO to implement the single-layer images in H2D format.

2023-06-10 12:22 UTC, Districh-ru commented on src/engine/image.h
> +        // Fill 'image' layer with given value, setting the non single layer images 'transform' layer to 0.
Sure)

2023-06-10 12:22 UTC, Districh-ru commented on src/engine/image.cpp
> +        const size_t size = _singleLayer ? static_cast<size_t>( width_ ) * height_ : static_cast<size_t>( width_ ) * height_ * 2;
Thanks for the suggestion! It looks better and removes the duplication of `width_ * height_` in the code.

2023-06-10 12:23 UTC, Districh-ru commented on src/engine/image.cpp
> +        // Since the restorer is used to restore the screen part, the transform layer is not needed.
Currently this class is used to restore the `fheroes2::Display::instance()` which is single-layer. But maybe in future we will want to restore the double-layer images. So I left the class name unchanged and changed the logic to:
``` cpp
        if ( image.singleLayer() ) {
            _copy._disableTransformLayer();
        }
```

2023-06-10 12:23 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                if ( isTransformLayerNotUsed( _icnVsSprite[id][i] ) ) {
You are right. I made a check for the need of a transform layer while decoding ICN.

2023-06-10 12:23 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                // Sorceress and Necromancer captains have incorrect transparent pixels.
I checked the pixel numbers that needs a fix and picked up their color to fix these and some other images,

2023-06-10 12:24 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                        _icnVsSprite[id][i]._disableTransformLayer();
Yes, this is a leftover after the previous code implementation.
I removed this loop.
 :)

2023-06-15 17:06 UTC, Districh-ru commented
This PR became very big and is now marked as draft until #7316 (which contains some fixes made in this PR) is merged.
Also tomorrow I'll try to open a PR with code clean-up made here in `image.cpp` to make this PR focus only on making single-layer images not to use memory for the transform layer.

2024-01-07 11:14 UTC, Districh-ru commented
Closing this PR in favor to #8241

2024-01-07 11:14 UTC, closed without merging