Add Editor Main Menu
ihhub/fheroes2 pull request #7241
Opened 2023-05-27 14:27 UTC by Districh-ru

Relates to #6845.

This PR adds Map Editor menu.
![Editor menu](https://github.com/ihhub/fheroes2/assets/113276641/2158c2a5-b80c-4e09-8c4c-30e587e74ae5)

Currently it is accessible only in Debug builds by "e" hotkey.
Since the Map Editor functions are WIP this menu currently do not allow create/open maps.

2023-05-28 06:04 UTC, ihhub requested changes
Hi @Districh-ru , I put few comments here. Could you please check them in your spare time?

2023-05-28 06:04 UTC, ihhub commented on src/fheroes2/game/game_editor_mainmenu.cpp
> +
Please remove this empty line.

2023-05-28 06:04 UTC, ihhub commented on src/fheroes2/game/game_editor_mainmenu.cpp
> +    const MapsFileInfoList lists = Maps::PrepareMapsFileInfoList( false );
The new Editor will **not** support old map format due to copyright issues. It will support only the new format.

2023-05-28 06:09 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +            return id == ICN::EDITOR || id == ICN::HEROES || id == ICN::BTNSHNGL || id == ICN::SHNGANIM;
Also since we expand this function shall we change it to switch-case structure? It would be easier to read.

2023-05-28 06:11 UTC, ihhub commented on src/fheroes2/game/game_editor_mainmenu.cpp
> +                                                   fheroes2::FontType::normalWhite() },
You can use `showStandardTextMessage` here which is shorter to write.

2023-05-28 06:40 UTC, Districh-ru commented on src/fheroes2/game/game_editor_mainmenu.cpp
> +    const MapsFileInfoList lists = Maps::PrepareMapsFileInfoList( false );
Sure)

2023-05-28 07:37 UTC, Districh-ru commented on src/fheroes2/game/game_editor_mainmenu.cpp
> +                                                   fheroes2::FontType::normalWhite() },
Yes, it will reduce the code complexity.

2023-05-28 07:37 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +            return id == ICN::EDITOR || id == ICN::HEROES || id == ICN::BTNSHNGL || id == ICN::SHNGANIM;
Sure.

2023-05-29 13:28 UTC, ihhub requested changes
Hi @Districh-ru , I left few more comments here. Could you please check them?

2023-05-29 13:28 UTC, ihhub commented on src/fheroes2/editor/editor_mainmenu.cpp
> +        std::array<fheroes2::Button, 4> buttons;
Let's create a separate variable which has value 4 and use it everywhere below in the code.

2023-05-29 13:28 UTC, ihhub commented on src/fheroes2/editor/editor_mainmenu.cpp
> +        std::array<Game::HotKeyEvent, 4> buttonHotkey = { Game::HotKeyEvent::MAIN_MENU_MAP_SIZE_SMALL, Game::HotKeyEvent::MAIN_MENU_MAP_SIZE_MEDIUM,
This variable can be const.

2023-05-29 13:28 UTC, ihhub commented on src/fheroes2/editor/editor_mainmenu.cpp
> +                    std::string message = _( "Create a map that is %{size} squares wide and %{size} squares high." );
We are missing support for the text mode. At least we can add an empty function with a TODO comment for the future changes.

2023-05-29 15:05 UTC, Districh-ru commented on src/fheroes2/editor/editor_mainmenu.cpp
> +                    std::string message = _( "Create a map that is %{size} squares wide and %{size} squares high." );
Done)
```
----------
Map Editor

Press N to create a new map either from scratch or using the random map generator.
Press L to load an existing map.
Press ESCAPE to go back to Main Menu.
----------
----------
New Map

Press S to create a blank map from scratch.
Press R to create a randomly generated map.
Press ESCAPE to go back to Map Editor main menu.
----------
----------
Map Size

Press S to create a map that is 36 squares wide and 36 squares high.
Press M to create a map that is 72 squares wide and 72 squares high.
Press L to create a map that is 108 squares wide and 108 squares high.
Press X to create a map that is 144 squares wide and 144 squares high.
Press ESCAPE to go back to New Map menu.
----------
```

2023-05-29 15:10 UTC, Districh-ru commented on src/fheroes2/editor/editor_mainmenu.cpp
> +        std::array<fheroes2::Button, 4> buttons;
Sure)

2023-05-29 15:10 UTC, Districh-ru commented on src/fheroes2/editor/editor_mainmenu.cpp
> +        std::array<Game::HotKeyEvent, 4> buttonHotkey = { Game::HotKeyEvent::MAIN_MENU_MAP_SIZE_SMALL, Game::HotKeyEvent::MAIN_MENU_MAP_SIZE_MEDIUM,
And the next one too)

2023-05-30 00:44 UTC, ihhub approved these changes

2023-05-30 00:44 UTC, merged

2023-05-30 00:44 UTC, ihhub commented
@Districh-ru , thank you so much for this improvement!