Do not play same kill/wince sounds simultaneously
ihhub/fheroes2 pull request #7248
Opened 2023-05-28 17:50 UTC by Districh-ru

Close #7203

2023-05-29 00:52 UTC, ihhub requested changes
Hi @Districh-ru , I left one suggestion here. Could you please take a look?

2023-05-29 00:52 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    std::vector<int> unitSounds;
We should use std::set for these purposes :)

2023-05-29 14:13 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +    std::vector<int> unitSounds;
Yes, it will operate faster and the code will be more compact.)

2023-05-30 13:59 UTC, ihhub requested changes
Hi @Districh-ru , I left one more suggestion. Could you please take a look?

2023-05-30 13:59 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +    };
Since this code is used inside the if-condition please move it there to reduce its scope.

2023-05-30 14:27 UTC, ihhub approved these changes

2023-05-31 14:27 UTC, merged

2023-05-31 14:27 UTC, ihhub commented
@Districh-ru , thank you so much for this improvement!