Make text input cursor blink
ihhub/fheroes2 pull request #7251
Opened 2023-05-29 18:30 UTC by Districh-ru

This PR makes the text input cursor blink not to confuse the cursor with the underline.
Also the cursor is added to the Virtual keyboard. But currently its position on Virtual keyboard cannot be changed.

https://github.com/ihhub/fheroes2/assets/113276641/23cef069-264d-4eac-ad31-3eeecb83fd84

2023-06-02 15:49 UTC, ihhub requested changes
Hi @Districh-ru , I left several comments and questions. Would you mind to take a look at them?

2023-06-02 15:49 UTC, ihhub commented on src/fheroes2/gui/ui_tool.cpp
> +            positionOffset += Text::getCharacterWidth( static_cast<uint8_t>( text[i] ), Font::BIG );
Let's avoid using legacy code. We can use `fheroes2::AGG::getChar().width()` call here.

2023-06-02 15:49 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +            text.set( InsertString( res, charInsertPos, isCursorVisible ? "_" : "\x7F" ), fheroes2::FontType::normalWhite() );
Is there a reason we need to use `\x7F` character? Can we use a space character instead?

2023-06-02 15:49 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +            else if ( le.KeyPress() && ( fheroes2::Key::KEY_UP != le.KeyValue() ) && ( fheroes2::Key::KEY_DOWN != le.KeyValue() )
Is there any specific logic why we ignore Key UP and Key DOWN events? What's about Page UP and Page DOWN?

2023-06-02 15:49 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
>          void removeLastCharacter()
In this case we should rename this method as it doesn't remove the last character anymore.

2023-06-02 15:49 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
> -            _info += character;
I suggest to rename the method into **insertCharacter** as we can insert it in the middle of a string.

2023-06-02 15:49 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
> +        void setCursortPosition( const int32_t clickXPosition, const int32_t startXPosition )
Misspelled Cursor**t**.

2023-06-02 15:49 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
> +        const fheroes2::Rect textRoi{ windowRoi.x + ( windowRoi.width - inputAreaSize.width ) / 2 + inputAreaBorders,
I suggest to create a method in **KeyboardRenderer** class to return this Rect to keep the calculations in one place.

2023-06-03 10:38 UTC, Districh-ru commented on src/fheroes2/gui/ui_tool.cpp
> +            positionOffset += Text::getCharacterWidth( static_cast<uint8_t>( text[i] ), Font::BIG );
Hi @ihhub. Thanks for the suggestion!
Sure, lets use `getChar()` function.
But after making changes here I had to make some changes in `skill_bar.cpp`.

2023-06-03 10:38 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +            text.set( InsertString( res, charInsertPos, isCursorVisible ? "_" : "\x7F" ), fheroes2::FontType::normalWhite() );
The space character is 6 pixels wide, and '_' is 9. So we need to have a transparent character with the width of '_'.
Using Space we cannot avoid text shift:
![fheroes2 2023-06-03 13-34-20-587](https://github.com/ihhub/fheroes2/assets/113276641/cb8b1712-4424-433a-9cd9-a531be371d52)

2023-06-03 11:43 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +            else if ( le.KeyPress() && ( fheroes2::Key::KEY_UP != le.KeyValue() ) && ( fheroes2::Key::KEY_DOWN != le.KeyValue() )
We ignore Key UP/DOWN to allow user to switch between the existing saves using UP/DOWN keys.
And you are right, we need to check for all listbox changes not to overwrite its results.
I changed logic a bit, now if `const bool listboxEvent = listbox.QueueEventProcessing()` is true this `if` block is skipped and user can properly use UP/DOWN/Page_UP/Page_Down keys in save dialog.

2023-06-03 11:43 UTC, Districh-ru commented on src/fheroes2/gui/ui_keyboard.cpp
>          void removeLastCharacter()
OK)

2023-06-03 11:43 UTC, Districh-ru commented on src/fheroes2/gui/ui_keyboard.cpp
> -            _info += character;
Sure)

2023-06-03 11:43 UTC, Districh-ru commented on src/fheroes2/gui/ui_keyboard.cpp
> +        void setCursortPosition( const int32_t clickXPosition, const int32_t startXPosition )
Thanks.

2023-06-03 11:44 UTC, Districh-ru commented on src/fheroes2/gui/ui_keyboard.cpp
> +        const fheroes2::Rect textRoi{ windowRoi.x + ( windowRoi.width - inputAreaSize.width ) / 2 + inputAreaBorders,
OK)

2023-06-03 15:15 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +            text.set( InsertString( res, charInsertPos, isCursorVisible ? "_" : "\x7F" ), fheroes2::FontType::normalWhite() );
Got it. Thanks for the explanation!

2023-06-03 16:31 UTC, ihhub requested changes
Hi @Districh-ru , I put just 2 small suggestions. Would you mind to check them?

2023-06-03 16:31 UTC, ihhub commented on src/fheroes2/gui/skill_bar.cpp
> +        fheroes2::Display & display = fheroes2::Display::instance();
**fheroes2::** is not needed since it is within fheroes2 namespace.

2023-06-03 16:31 UTC, ihhub commented on src/fheroes2/gui/ui_tool.h
> +    size_t getTextInputCursorPosition( const std::string & text, const FontType & fontType, const size_t currentTextCursorPosition, const int32_t pointerCursorXPosition,
I suggest to name **pointerCursorXPosition** as **pointerCursorXOffset** and **textStartXPosition** as **textStartXOffset** to avoid confusion between symbol position in text and coordinate position.

2023-06-03 16:37 UTC, Districh-ru commented on src/fheroes2/gui/skill_bar.cpp
> +        fheroes2::Display & display = fheroes2::Display::instance();
Oh, yes)

2023-06-03 16:37 UTC, Districh-ru commented on src/fheroes2/gui/ui_tool.h
> +    size_t getTextInputCursorPosition( const std::string & text, const FontType & fontType, const size_t currentTextCursorPosition, const int32_t pointerCursorXPosition,
Sure)

2023-06-03 16:40 UTC, ihhub approved these changes

2023-06-03 22:14 UTC, oleg-derevenetz approved these changes

2023-06-05 14:34 UTC, merged