Fix missing logic for AI heroes to meet each other in the middle of a turn
ihhub/fheroes2 pull request #7254
Opened 2023-05-31 11:09 UTC by ihhub

We did not update map object cache when a hero moves so other heroes were using the old cached data and failed to find the hero if there is a need to meet each other. Such behavior is really hard to catch so you can use this save to test master branch and this branch (green AI hero moves to a castle and another hero ignores him in master branch):
[Great_War_II_0018_hero_inte.zip](https://github.com/ihhub/fheroes2/files/11612281/Great_War_II_0018_hero_inte.zip)

On top of this the change reduces the amount of objects being processed for a possible movement. Only action objects should be considered useful for any movement.

2023-05-31 19:09 UTC, oleg-derevenetz reviewed
Hi @ihhub I just left a few questions, could you please take a look when you have time?

2023-05-31 19:09 UTC, oleg-derevenetz commented on src/fheroes2/ai/ai_hero_action.cpp
> +            isAction = false;
What is the purpose of this separate `isAction` variable? Why we can't just use `isActionObject` here instead?

2023-05-31 19:09 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal.cpp
> +            }
Is it possible to use the `updateMapActionObjectCache()` here somehow instead of duplicating the code?

2023-05-31 23:47 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal.cpp
> +        if ( MP2::isActionObject( object ) ) {
Sure.

2023-05-31 23:48 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal.cpp
> +            }
Yup. We can do this.

2023-05-31 23:49 UTC, ihhub commented on src/fheroes2/ai/ai_hero_action.cpp
> +            isAction = false;
It's leftover before we changed pathfinding and removed Coast as an action object for AI. I will change it.

2023-06-01 09:25 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few suggestions, please take a look when you have time :)

2023-06-01 09:25 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                assert( tileHero != nullptr );
If fheroes2 would be built with `WITH_DEBUG` and also with `NDEBUG` (unlikely but nevertheless possible), there will be "unused variable" warnings. To avoid this we can either do this:

```cpp
assert( world.GetTiles( actionObject.first ).GetHeroes() != nullptr );
```

or this:

```cpp
if ( tileHero == nullptr ) {
  assert( 0 );
}
```

2023-06-01 09:25 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            objectIndexes.emplace( actionObject.first );
Here the same thing is done twice. We can do something like this instead:

```cpp
const auto [dummy, inserted] = objectIndexes.emplace( actionObject.first );
if ( !inserted ) {
  assert( 0 );
}
```

2023-06-01 10:49 UTC, oleg-derevenetz approved these changes

2023-06-01 18:35 UTC, Districh-ru approved these changes

2023-06-02 00:40 UTC, merged