Add shadows for the Virtual Keyboard buttons
ihhub/fheroes2 pull request #7262
Opened 2023-06-01 17:42 UTC by Districh-ru

This PR adds shadows for the Virtual keyboard buttons

![virtKB](https://github.com/ihhub/fheroes2/assets/113276641/d2152a10-f582-4967-917b-e04868d92c32)

2023-06-03 16:39 UTC, ihhub requested changes
Hi @Districh-ru , I left 2 comments in this pull request. Would you mind to check them if you have spare time?

2023-06-03 16:39 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
>          fheroes2::ButtonSprite okayButton( windowRoi.x + ( windowRoi.width - okayButtonReleasedImage.width() ) / 2, windowRoi.y + windowRoi.height - 35,
I suggest to move `windowRoi.x + ( windowRoi.width - okayButtonReleasedImage.width() ) / 2, windowRoi.y + windowRoi.height - 35` to a separate Point variable as we use it in 2 places.

2023-06-03 16:39 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
> +        for ( size_t i = 0; i < buttonRows; ++i ) {
I am not sure that this change will make the code faster as `size()` method is inlined and marked as const expression.

2023-06-03 16:58 UTC, Districh-ru commented on src/fheroes2/gui/ui_keyboard.cpp
> +        for ( size_t i = 0; i < buttonRows; ++i ) {
Hi, @ihhub, `buttonRows` is also used 2 times in the 497 line to I cached it as it it used here in the loop and in the line 497.

2023-06-03 16:59 UTC, Districh-ru commented on src/fheroes2/gui/ui_keyboard.cpp
>          fheroes2::ButtonSprite okayButton( windowRoi.x + ( windowRoi.width - okayButtonReleasedImage.width() ) / 2, windowRoi.y + windowRoi.height - 35,
Sure)

2023-06-07 02:43 UTC, ihhub approved these changes

2023-06-07 11:37 UTC, Branikolog approved these changes
Well done!

2023-06-08 05:28 UTC, merged

2023-06-08 05:28 UTC, ihhub commented
@Districh-ru , thank you so much for these changes!