Create basic Map Editor GUI
ihhub/fheroes2 pull request #7295
Opened 2023-06-11 18:32 UTC by Districh-ru

Relates to #6845

This PR adds Map Editor GUI. (Currently its functions are in development and are not implemented in this PR.)

https://github.com/ihhub/fheroes2/assets/113276641/b825ae21-ec5b-4136-88f0-7e40b2f16b58

2023-07-01 09:01 UTC, Districh-ru commented on src/fheroes2/ai/ai_hero_action.cpp
> +            Interface::AdventureMap & basicInterface = Interface::AdventureMap::Get();
Hi @ihhub, I prefer to do it in current PR as we need only to change several lines only in 4 cpp files. Also we already change some of these lines.
So we will not forget to do this rename in the future. :)

2023-07-01 10:34 UTC, Districh-ru commented on src/fheroes2/game/game_interface.h
> -    };
This enumeration is also used in `interface_radar.cpp`, `interface_radar.cpp` and some other places, common to both **AdventureMap**  and **Editor** and in method of base class `validateFadeInAndRender()`.
So we need to keep some enumerations for base class and leave others to AdventureMap and Editor.

2023-07-01 10:39 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.h
> +        uint32_t _selectedInstrument{ 0 };
Sure, `uint8_t` will be enough. :)

2023-07-01 10:51 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            res = Interface::Editor::eventFileDialog();
For New Map and Load Map we return to the Editor Main Menu so we need **res**.
But for Scenario Info it is not needed here, thanks. :)

2023-07-01 11:29 UTC, Districh-ru commented on src/fheroes2/gui/interface_radar.cpp
> +
To use `RedrawForViewWorld` we have to make, calculate and properly update `ViewWorld::ZoomROIs` which is not needed here. So until we make zoom for the gameArea it is better to use a separate function for radar.

2023-07-01 12:21 UTC, Districh-ru commented on src/fheroes2/gui/interface_base.h
> +        virtual void redraw( const uint32_t force = 0 ) = 0;
OK)

2023-07-01 12:21 UTC, Districh-ru commented on src/fheroes2/game/game_interface.h
> +    class AdventureMap : public BaseInterface
Sure)

2023-07-01 12:23 UTC, Districh-ru commented on src/fheroes2/game/game_interface.h
> -    };
I don't know how to do it better. @ihhub, I'm looking forward to your suggestion. :)

2023-07-02 08:07 UTC, ihhub commented
I added @oleg-derevenetz to the list of reviewers to have architecture design opinion.

2023-07-02 19:07 UTC, oleg-derevenetz commented on src/fheroes2/game/game_interface.h
> +    enum advMapRedraw_t : uint32_t
Hi @Districh-ru I am aware that old code regularly uses type names ending with `_t` in many places, but in C such names are [reserved identifiers](https://en.cppreference.com/w/c/language/identifier#Reserved_and_potentially_reserved_identifiers_in_the_library). It is better to name types (including enums) in PascalCase.

2023-07-03 15:45 UTC, ihhub commented on src/fheroes2/game/game_interface.h
> -    };
Honestly, based on the suggestions from clang-tidy and a possibility that we could introduce an error I am inclining towards the original solution to keep everything in one enumeration. My apologies if I am changing opinions :(

2023-07-03 15:46 UTC, ihhub commented on src/fheroes2/gui/interface_radar.cpp
> +
Thanks for the explanation!

2023-07-03 15:51 UTC, ihhub requested changes
Hi @Districh-ru , I left few more comments in this pull request. Could you please check them when you have free time?

2023-07-03 15:51 UTC, ihhub commented on src/fheroes2/editor/editor_interface.h
> +#if defined( WITH_DEBUG )
I think we can drop this macro check for the whole file and allow to compile for release build as well as no harm doing this since the Editor is not accessible at the moment. Plus we might catch some issues within GitHub Actions.

The same for the source file.

2023-07-03 15:51 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.h
> +#if defined( WITH_DEBUG )
We can also drop this macro as well.

2023-07-03 15:51 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.h
> +    const uint8_t instrumentsCount = 6;
I suggest to make it as a const static member of the class as this variable is not used anywhere else.

2023-07-03 17:17 UTC, Districh-ru commented on src/fheroes2/game/game_interface.h
> -    };
Its OK, lets revert to the original solution until we find a better one.

2023-07-03 17:20 UTC, Districh-ru commented on src/fheroes2/game/game_interface.h
> +    enum advMapRedraw_t : uint32_t
Hi @oleg-derevenetz, thanks for the explanation!
As we are now returning to one enumeration for all "redraws" it will be `Redraw`.

2023-07-05 13:31 UTC, ihhub approved these changes

2023-07-05 15:16 UTC, oleg-derevenetz approved these changes

2023-07-05 23:41 UTC, merged

2023-07-05 23:42 UTC, ihhub commented
@Districh-ru , huge thanks for doing these changes!