Rework game credits to keep aspect ratio
ihhub/fheroes2 pull request #7313
Opened 2023-06-14 18:42 UTC by Districh-ru

Close #7303

This PR keeps the aspect ratio if game credits and removes redundant resize on every render loop and render of an image when it is in NO_ACTION state (showing page for some time without any effects).

![creditsPage](https://github.com/ihhub/fheroes2/assets/113276641/cbe68df9-d0c5-4920-aae0-47e27a2a81f2)

This PR also reworks the code to reduce code repeating and not to use legacy 'Text' class.

2023-06-17 13:24 UTC, ihhub requested changes
Hi @Districh-ru , I left 2 comments in this pull request. Would you mind to take a look at them?

2023-06-17 13:24 UTC, ihhub commented on src/fheroes2/game/game_credits.cpp
> +    const int32_t resizedPageHeight = creditsRoi.width * pages.front().height() / pages.front().width();
This is not correct for devices with vertical orientation. Please take a look at `GetScaledICN()` function to handle this case as well.

2023-06-17 13:24 UTC, ihhub commented on src/fheroes2/game/game_credits.cpp
> +        renderText( output, offsetX, offsetY, textWidth - 10, _( "Original project before 0.7" ), "Andrey Afletdinov\nhttps://sourceforge.net/\nprojects/fheroes2/" );
The font for this particular text is different from others.

2023-06-17 14:29 UTC, Districh-ru commented on src/fheroes2/game/game_credits.cpp
> +    const int32_t resizedPageHeight = creditsRoi.width * pages.front().height() / pages.front().width();
Hi, @ihhub.
It would not be correct if here we were calculating the resizedwidth and height by display size.
As `creditsRoi` is set by using properly scaled Main Menu background image parameters (x, y, width, height) we can use width here to calculate the height if resized credits page.
All is correct for high height resolutions:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/28ace465-27f4-4017-bf9e-a7299592cd00)

2023-06-17 14:29 UTC, Districh-ru commented on src/fheroes2/game/game_credits.cpp
> +        renderText( output, offsetX, offsetY, textWidth - 10, _( "Original project before 0.7" ), "Andrey Afletdinov\nhttps://sourceforge.net/\nprojects/fheroes2/" );
Thanks for noticing this.
Fixed)

2023-06-18 00:40 UTC, ihhub approved these changes

2023-06-18 11:36 UTC, Districh-ru commented on src/fheroes2/game/game_credits.cpp
> +    // Resize the credits pages. 'creditsRoi' is made using MAin Menu background parameters that were already properly calculated for the current resolution.
Hi @zenseii. Fixed, thanks!

2023-06-18 12:08 UTC, merged

2023-06-18 12:08 UTC, ihhub commented
@Districh-ru , thank you so much for this improvement!