Redo ICN decode code and agg_image.cpp code clean-up
ihhub/fheroes2 pull request #7316
Opened 2023-06-15 17:02 UTC by Districh-ru

This PR contains changes made in #7233
While working on #7233 there were made some necessary for that PR changes in the code, but PR became very big. To reduce the size of that PR and to properly test and merge some changes this PR is made. It contains:
- rework of **decodeICNSprite()** function to gain 1-30% speed-up while decoding ICN images;
- clean-up of `agg_image.cpp` to make Clang-Tidy a little happier;
- fix of  some images which were containing invalid transparent pixels:
  - portraits of PoL heroes (Solmyr, Danwin, Gallavant, Ceallach);
  - Barbarian captain mini icon;
  - Sorceress and Necromancer captains (shown in Castle dialog);
  - Sphere of Negation artifact;
  - ship battlefield background;
  - first image in "ICH::BRCREST" (icon of blue player, shown during enemy turn);
  - Main Menu background;
- use `fheroes2::Copy()` instead of `fheroes2::Blit()` while rendering the Armageddon spell.

2023-06-18 13:44 UTC, ihhub requested changes
Hi @Districh-ru , I left several comments in this pull request. Could you please check them and see if they are valid?

2023-06-18 13:44 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    _icnVsSprite[id][0].image()[195460] = 31;
We have to check the correct size of the original game as it can be different. Also we can use **replaceTransformPixel** before **_disableTransformLayer()** call to have unified code.

2023-06-18 13:44 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    if ( original.width() == 30 && original.height() == 22 ) {
Could you please specify in the pull request description pixels of images which were fixed? It would help to verify the correctness of the solution.

2023-06-18 13:44 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                Copy( _icnVsSprite[ICN::ADVBTNS][releasedIndex + 1], _icnVsSprite[id][1] );
With the proposed code we must have a check for ICN::ADVBTNS size. GetICN() is just slightly slow but it checks the size of the image array inside it. Also image assignment operator changes the number of image layers (at least in the future) while Copy does not.

The same remark for **ICN::EVIL_MARKET_BUTTON** code.

2023-06-18 13:44 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    for ( int32_t index : { 88, 99 } ) {
**index** can be `const` here.

2023-06-18 13:44 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                Copy( _icnVsSprite[originalId][12], pressed );
`Copy()` does not change the number of layers for image while copy assignment does. I suggest to stick to it unless there is a reason to use `Copy()` function.

2023-06-18 13:44 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    if ( !original.empty() ) {
We must check the size here.

2023-06-18 14:40 UTC, oleg-derevenetz commented on src/engine/image_tool.cpp
> +                std::fill( imageTransform + posX, imageTransform + posX + pixelCount, static_cast<uint8_t>( 0 ) );
I believe that, if we work with array of chars, `std::fill()` hardly can be faster than `memset()`. `std::fill()` is more generic and applicable for a generalized templated code where the exact type of `T` is not known in advance, but this versatility may harm the optimization.

2023-06-18 14:56 UTC, Districh-ru commented on src/engine/image_tool.cpp
> +                std::fill( imageTransform + posX, imageTransform + posX + pixelCount, static_cast<uint8_t>( 0 ) );
Hi @ihhub, I just read some articles about `memset()` and `std::fill()` and most say that `memset()` is faster, but it has less code readability when the array type is not `uint8_t` (char). As our image arrays are `unt8_t` we can simply use `memset()` here and in `image.cpp` preserving code readability.

2023-06-18 15:36 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                    _icnVsSprite[id][0].image()[195460] = 31;
Sure. 
But using `replaceTransformPixel()` we make changes to the `transform` layer of this image which is never used. :)

2023-06-18 16:05 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                Copy( _icnVsSprite[ICN::ADVBTNS][releasedIndex + 1], _icnVsSprite[id][1] );
Sure, lets add this check.)

But image assignment operator calls `copy()` method which currently has this assertion:
https://github.com/ihhub/fheroes2/blob/d6d553a46d6085b6fe2d0ccfcf2b16c222d86816/src/engine/image.cpp#L536-L537

In future (in https://github.com/ihhub/fheroes2/pull/7233 and #7317) `Copy()` will copy data taking into account the number of layers of input and output image, while assignment operator will make a full copy of input image retaining the number of layers.

2023-06-20 00:48 UTC, ihhub approved these changes

2023-06-20 00:49 UTC, ihhub commented
Hi @Branikolog , please test all images highlighted in the description of this pull request.

2023-06-27 07:08 UTC, ihhub commented
Hi @drevoborod , could you please help testing these changes?

2023-06-27 20:15 UTC, drevoborod commented
> Hi @drevoborod , could you please help testing these changes?

Hello, actually I don't know how to check following changes:
1.  ICN decoding speed-up.
2. Actually, most of the pixels :) How should I found the correct ones?? Imho, it's nearly impossible to notice single transparent pixel of entire image without zooming it at least to 400%. Is there a way to do it?

2023-06-27 21:02 UTC, drevoborod commented
@ihhub , I noticed that there is different order of heroes portraits for the same map opened in different versions of fheroes2:
1: Release version 1.0.5

![1_1_0_5](https://github.com/ihhub/fheroes2/assets/10282847/0c1f259c-c227-4a95-a26e-76a7fd2eb540)

2 and 3: version from this PR:

![3_dev](https://github.com/ihhub/fheroes2/assets/10282847/0f30ed0a-3cbd-483e-a09f-6177b08e1db4)
![2_dev](https://github.com/ihhub/fheroes2/assets/10282847/7fe086a4-a925-4d10-bbad-357f5908559d)

2023-06-28 03:09 UTC, Districh-ru commented
> Hello, actually I don't know how to check following changes:

Hello, @drevoborod. Many thanks for starting test of this PR!

You can download "fheroes2_tools" from the latest commit for your system, run "extract_agg" script (extract_agg.bat) and locate the game images in ICN directory.

The transparent pixels are filled with gray color:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/bf9f570e-36be-45bd-b591-800e27a61d67)

The list of heroes can be viewed in Battle Only mode while adding a hero to the right player:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/11d0b4e4-c0a5-4968-9541-790619dba391)

2023-06-28 07:05 UTC, drevoborod commented
> You can download "fheroes2_tools" from the latest commit for your system, run "extract_agg" script (extract_agg.bat) and locate the game images in ICN directory.

Sorry, but I didn't get how to locate proper images. After extraction of HEROES2.agg file, I have a directory "icn/HEROES2" with lot of subdirectories inside it. Every subdirectory contains several .png files and one "offsets.txt". But none of *.png contains useful data - everything I looked at cosists just of several transparent pixels. Here is an example of one of such directories. Maybe something went wrong on extraction?
[curse.zip](https://github.com/ihhub/fheroes2/files/11891214/curse.zip)

2023-06-28 07:18 UTC, Districh-ru commented
> Sorry, but I didn't get how to locate proper images. After extraction of HEROES2.agg file, I have a directory "icn/HEROES2" with lot of subdirectories inside it. Every subdirectory contains several .png files and one "offsets.txt". But none of *.png contains useful data - everything I looked at cosists just of several transparent pixels. An example of one of such directories attached. Maybe something went wrong on extraction? My system is Linux, so I use fheroes2_tools_ubuntu_x86-64_SDL2.

Sorry, I forgot to mention that .png files are located in ICN name directories. ICN names and ICN index can be found when you view the changes made in "agg_image.cpp". In the evening, when I get to my PC, I'll update the PR description and write ICN name and index for each changed sprite.

2023-06-28 08:13 UTC, drevoborod commented
> Sorry, I forgot to mention that .png files are located in ICN name directories. ICN names and ICN index can be found when you view the changes made in "agg_image.cpp". In the evening, when I get to my PC, I'll update the PR description and write ICN name and index for each changed sprite.

Are directory names contained in lines like `case ICN::MINIPORT:`? So is "MINIPORT" a directory name? Sadly it's not enough to locate a correct image. Too complicated for me :) So I'll wait for further instructions. I found the directory (in the attachment), but it also contains only empty *.png. 
Also attached another example - PNG from directory "port0091" which is mentioned in the line 2720:
![000](https://github.com/ihhub/fheroes2/assets/10282847/f501075a-4f7d-4684-9389-49763044bd3d)


[miniport.zip](https://github.com/ihhub/fheroes2/files/11891817/miniport.zip)

2023-06-28 14:02 UTC, ihhub commented
Hi @Districh-ru , are you sure that tools utilize the changes in this pull request? From the code we don't use `agg_image.cpp` code to extract images.

2023-06-28 14:06 UTC, Districh-ru commented
> Hi @Districh-ru , are you sure that tools utilize the changes in this pull request? From the code we don't use `agg_image.cpp` code to extract images.

Hi, @ihhub, using tools we can get original images and find out what pixels are corrupted and compare them with rendering result in PR. :)

2023-06-28 14:07 UTC, ihhub commented
> > Hi @Districh-ru , are you sure that tools utilize the changes in this pull request? From the code we don't use `agg_image.cpp` code to extract images.
> 
> Hi, @ihhub, using tools we can get original images and find out what pixels are corrupted and compare them with rendering result in PR. :)

Yup, that's true.

2023-06-28 14:20 UTC, drevoborod commented
> > Hi @Districh-ru , are you sure that tools utilize the changes in this pull request? From the code we don't use `agg_image.cpp` code to extract images.
> 
> Hi, @ihhub, using tools we can get original images and find out what pixels are corrupted and compare them with rendering result in PR. :)

Seems like for some reason it doesn't work in my case :) As I mentioned before, all images contain only different transparent areas and nothing else. Could someone please check Linux version of tools - does it actually work as expected? Or just please ask someone else to check this PR - seems like in current situation I can't help with it.

2023-06-28 15:12 UTC, oleg-derevenetz commented
Hi @Districh-ru

> But until the tools are fixed the only way to check the sprites is to compare the rendering of two fheroes2 executables: this PR and master build.

In fact, tools work just fine if they built without `WITH_IMAGE` (i.e. without PNG support). They save images in BMP format just fine. The problem is observed only with PNG and this suggests that something wrong with the alpha channel handling in the `SaveImage()` function in the `engine/image_tool.cpp`.

2023-06-28 19:54 UTC, drevoborod commented
> In fact, tools work just fine if they built without WITH_IMAGE

How can I obtain such build? I tried to run Windows version with Wine but had no success - it fails with strange message:

```
Z:\home\user\apps\fheroes2_tools_windows_x64_SDL2>extractor agg *.AGG *.agg || exit /B 1
Processing .\HEROES2.AGG...00e0:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000021F8B0 1 C) semi-stub

Processing *.agg...
Cannot open file *.agg
Total extracted items: 00e0:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000021F8E0 1 C) semi-stub
00e0:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000021F520 1 C) semi-stub
1434, failed items: 0

```  

An AGG file extraction actually completed successfully, but no conversions were started.
Unfortunately, without reference images I can't check changes made in this PR - as I mentioned before, it seems nearly impossible to locate required pixels in the game.
By the way, what exactly does code added in this PR? Does it replace incorrect pixels in runtime?

2023-06-28 19:57 UTC, oleg-derevenetz commented
Hi @drevoborod

> How can I obtain such build?

You can download the corresponding artifact from #7365 (e.g. from [this](https://github.com/ihhub/fheroes2/actions/runs/5404275181) run).

2023-06-28 23:33 UTC, oleg-derevenetz commented
> It worked, thank you! Actually, it's a radical way to fix an issue - by just removing corresponding functionality :)

That was just a workaround, and #7366 looks like an actual fix. Could you please test it as soon as the build is ready?

2023-06-29 05:59 UTC, drevoborod commented
> That was just a workaround, and #7366 looks like an actual fix. Could you please test it as soon as the build is ready?

Sure. I tested it - and it works like a charm! :) 
Btw, there is an error on HEROES2X.agg extraction:

```
29.06.2023 08:51:22: [ERROR]    open:  agg/HEROES2X/*.til
Cannot open file agg/HEROES2X/*.til
Total extracted sprites: 0

```

But all images were extracted correctly (and previous version displayed the same error).

P.S. portraits fixed in this PR are also from HEROES2X.agg. It's not obvious how does the engine locate the correct image to fix because some other pictures have same file names in both .AGG files.

2023-06-29 06:43 UTC, oleg-derevenetz commented
> Btw, there is an error on HEROES2X.agg extraction:

That's because `HEROES2X. AGG` (Price of Loyalty expansion data file) doesn't contain any tile/terrain sprites. This is not a error. If there would be any real error, the extraction script would stop.

2023-06-29 20:54 UTC, drevoborod commented
Finally, checks of all images completed :) That's all that I can verify in this PR. Checked:

    mini portraits of PoL heroes (ICN::MINIPORT):
        + Solmyr (ICN id 60, pixels 5x0, 10x10, 28x11,4x14),
        + Dainwin (ICN id 61, pixels 21x1, 20x2, 21x2, 23x2, 25x14),
        + Gallavant (ICN id 65, pixels 19x16, 2x20, 1x21),
        + Ceallach (ICN id 67, pixel 12x1);
    + Barbarian captain mini icon (ICN::MINICAPT, id 1, pixel 22x2);
    + Sorceress captain (ICN::PORT0092, id 0, pixels 8x20 and 8x66)
    + Necromancer (ICN::PORT0095, id 0, pixel 8x22) captain (shown in Castle dialog);
    + Sphere of Negation artifact (ICN::ARTIFACT, id 99, black pixels of the shadow);
    + ship battlefield background (ICN::CBKGWATR, id 0, pixel 125x36);
    + first image in ICN::BRCREST (id 0, pixel 30x5) - icon of the blue player, shown during enemy turn;
    + Main Menu background (ICN::HEROES, id0, pixel at 260x305);

Map used to test changes:
[MAP_0003.MX2.zip](https://github.com/ihhub/fheroes2/files/11910438/MAP_0003.MX2.zip)

2023-06-30 06:11 UTC, drevoborod commented
Also checked Armageddon spell. Haven't noticed any differencies to 1.0.5 stable version of the engine. Here is video: 
[armageddon_new.zip](https://github.com/ihhub/fheroes2/files/11913399/armageddon_new.zip)

2023-07-01 02:40 UTC, merged

2023-07-01 02:40 UTC, ihhub commented
@Districh-ru , thank you so much for these changes!

@drevoborod , thanks a lot for the help with testing!