Reduce the amount of calls to get a singleton instance
ihhub/fheroes2 pull request #7348
Opened 2023-06-20 13:57 UTC by ihhub

Just a simple code cleanup to reduce the amount of useless work by CPU.

2023-06-20 15:45 UTC, Districh-ru requested changes
Hi @ihhub. I left a code clean-up suggestion. Could you take a look in your spare time.

2023-06-20 15:45 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
>          }
We can reduce code duplication a bit here. (And explicitly indicate the `normalWhite()` font type.) What do you think?
```cpp
        const fheroes2::Text text( mons.GetName(), current ? fheroes2::FontType::normalYellow() : fheroes2::FontType::normalWhite() );
        text.draw( dstx + 50, dsty + 10, display );

```

And to finally clean-up this function we can make **const** line 129: `const Monster mons( index );`. :)

Also the same clean-up, including introducing `fheroes2::Display & display = fheroes2::Display::instance();`, can be done to `SelectEnumHeroes::RedrawItem()` (lines 166-181) and `SelectEnumArtifact::RedrawItem()` (lines 197-214).

2023-06-20 15:45 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
>          }
The same comment as above.
```cpp
        const fheroes2::Text text( spell.GetName(), current ? fheroes2::FontType::normalYellow() : fheroes2::FontType::normalWhite() );
        text.draw( dstx + 80, dsty + 10, display );
```

2023-06-20 15:45 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
>          }
The same comment as above.
```cpp
        const fheroes2::Text text( skill.GetName(), current ? fheroes2::FontType::normalYellow() : fheroes2::FontType::normalWhite() );
        text.draw( dstx + 50, dsty + 10, display );
```

2023-06-27 05:33 UTC, Districh-ru requested changes
Hi @ihhub. I left one suggestion. Could you take a look when you have time.

2023-06-27 05:33 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
>              fheroes2::Blit( port, fheroes2::Display::instance(), dstx + 5, dsty + 3 );
As every hero in non-corrupted original assets has a portrait this condition will be true and `fheroes2::Display::instance()` is called twice: here and in line 171.
So we can reduce the number of these system calls.

2023-06-27 05:35 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
>              fheroes2::Blit( port, fheroes2::Display::instance(), dstx + 5, dsty + 3 );
Fixed.

2023-06-27 05:39 UTC, Districh-ru approved these changes

2023-06-27 06:37 UTC, merged