Gray out combat spells without closing spell book
ihhub/fheroes2 pull request #7350
Opened 2023-06-21 19:17 UTC by Kazhuu

This PR will gray out following spells:
* Bless and mass bless: when player's army only has peasants.
* Curse and mass curse: when opposing side only has peasants.
* Shield and mass shield: when opposing side does not have any archers.

Any ideas for better messages for the user to inform why the spell cannot be used?

2023-06-22 09:42 UTC, LeHerosInconnu commented
Hello @Kazhuu,

> * Bless and mass bless when player's army only has peasants.
> * Curse and mass curse when opposing side only has peasants.
> * Shield and mass shield when opposing side does not have any archers.
> * Dragonslayer when opposing side does not have any dragons.
> 
> Any ideas @LeHerosInconnu for better messages for the user to inform why the spell cannot be used?

I'll be making some proposals soon. :)

2023-06-22 10:41 UTC, LeHerosInconnu commented
Hello @Kazhuu,

> I'll be making some proposals soon. :)

So here are my proposals:

Player's army only has peasants, with "Bless" spells:

"Damage from peasant is constant, so there is no benefit to cast this spell."

Opposing side only has peasants, with "Curse" spells:

"Damage from peasant is constant, so there is no benefit to cast this spell."

It is also not possible to cast "Bless" spells and "Curse" spells on undead creatures.

Player's army only has undead, with "Bless" spells and "Curse" spells:

"Undead creatures cannot be affected by this spell."

It is also not possible to cast "Curse" spells on the Crusader.

Opposing side only has crusaders, with "Curse" spells:

"Crusader cannot be affected by this spell."

Opposing side only has crusaders and undead, with "Curse" spells:

"Crusader and undead creatures cannot be affected by this spell."

Opposing side only has crusaders and peasants, with "Curse" spells:

"Crusader cannot be affected by this spell.
Damage from peasant is constant, so there is no benefit to cast this spell."

Or, better:

Crusader cannot be affected by this spell and damage from peasant is constant, so there is no benefit to cast this spell."

Opposing side does not have any ranged creatures, with "Shield" spells:

"Opposing hero's army does not include any ranged creatures, so there is no benefit to cast this spell."

Opposing side does not have any dragons, with "Dragon Slayer" spell:

"Opposing hero's army does not include any dragons, so there is no benefit to cast this spell."

2023-07-16 13:35 UTC, Kazhuu commented
@LeHerosInconnu sorry for the delay. Now I added the strings you asked. Can you test this to verify it's working like you wanted?

2023-07-21 11:12 UTC, LeHerosInconnu commented
Hello @Kazhuu,

> @LeHerosInconnu sorry for the delay. Now I added the strings you asked. Can you test this to verify it's working like you wanted?

I'll test it when I have some time, maybe next week. :)

2023-07-23 19:36 UTC, oleg-derevenetz commented
Hi @Mr-Bajs

> Just to be clear, the spell Shield doesn't affect spells such as Magic Arrow?

No, it shouldn't affect any magic damage. Moreover, it shouldn't affect the damage from the castle towers, which is currently not the case in fheroes2 and should be fixed by #7466.

2023-08-16 18:10 UTC, Kazhuu commented
Hi @LeHerosInconnu any news on this one?

2023-08-16 18:16 UTC, LeHerosInconnu commented
Hello @Kazhuu,

> Hi @LeHerosInconnu any news on this one?

I don't have too much time at the moment, but don't worry it's still on my to-do list. :)

2023-09-15 11:48 UTC, ihhub commented
Hi @LeHerosInconnu , please provide your feedback for these changes.

2023-09-17 18:14 UTC, LeHerosInconnu commented
Hello @Kazhuu and @ihhub,

> Hi @LeHerosInconnu , please provide your feedback for these changes.

With bless and curse spells, for the strictly identical cases presented in the original post, the display of messages works correctly.

> * Bless and mass bless when player's army only has peasants.
> * Curse and mass curse when opposing side only has peasants.

Here are my observations with the shield and dragon slayer spells

> * Shield and mass shield when opposing side does not have any archers.
> * Dragonslayer when opposing side does not have any dragons.

In multiplayer mode, two human players, green and blue, blue player's hero attacking:
- The defending green hero can cast shield and mass shield even if there is no ranged creature in the opposing blue player's army, as long as he has a ranged creature in his army.
![Grayed combat spells 008](https://github.com/ihhub/fheroes2/assets/43583994/6227227f-8001-4d0a-af8b-488558d97b94)
- The defending green hero cannot cast the shield and mass shield spells even if there is a ranged creature in the opposing blue player's army as long as he does not have a ranged creature in his army.
![Grayed combat spells 009](https://github.com/ihhub/fheroes2/assets/43583994/7d4d95df-d3a8-47fe-95ab-479e105dac9a)
![Grayed combat spells 010](https://github.com/ihhub/fheroes2/assets/43583994/374f536a-38f8-4e39-b6b5-e6b133afab0b)
- The defending green hero can cast the dragon slayer spell even if there is no dragon in the opposing blue player's army as long as he has a dragon in his army.
![Grayed combat spells 011](https://github.com/ihhub/fheroes2/assets/43583994/68b7a346-03a6-4b27-be74-d3643a11848e)
![Grayed combat spells 012](https://github.com/ihhub/fheroes2/assets/43583994/df575956-9757-4cc0-b3ef-70c1faeb81da)

Also, the message should be adapted to the creatures still present when the spell is cast, and not to the creatures present at the start of the combat.
In the example, with curse spell, the peasants have been decimated and the message displays a description as if they are still alive and cannot be affected.
The message should adapt to the creatures still present, but not to those decimated.
![Grayed combat spells 006](https://github.com/ihhub/fheroes2/assets/43583994/61fb9953-361a-4dbe-9494-e787f6db95ef)
![Grayed combat spells 007](https://github.com/ihhub/fheroes2/assets/43583994/a1c8818e-b958-4382-8169-d222f6c22205)

This PR covers only the strictly identical cases presented in the original post.
There are other cases to be taken into consideration.

Here are the test scenario and the save files:
[Grayed combat spells 01.zip](https://github.com/ihhub/fheroes2/files/12643390/Grayed.combat.spells.01.zip)

2023-09-18 11:21 UTC, Kazhuu commented
Hello @LeHerosInconnu thanks for the feedback! I'll take a look at the code again and fix these soon. Could you elaborate what you mean by these?
> This PR covers only the strictly identical cases presented in the original post.
> There are other cases to be taken into consideration.
Is there some other cases as well we should cover to gray out spells? If so maybe do these in a separate PR.

2023-09-18 17:21 UTC, Alucard648 commented
Resurrection and True Ressurection, when there are no dead troops in non-elemental stacks:
"There are no dead troops in your army, the spell is useless...  for now."
Animate Dead when there are no destroyed undead creatures in stacks:
"There are no fallen undead troops in your army, the spell is useless...  for now."
Death Ripple and Death Wave spells, when all troops in enemy army are undead:
"This spell will cause death and decay to your army and do nothing to your enemy!"
Holy Word and Holy Shout when there are no undead troops in enemy army:
"This spell will devastate your undead army and do nothing to your enemy!"
Antimagic spell when enemy hero has 0 mana and there are no spellcasting creatures in his army:
"Enemy hero can`t cast any spells and none of his creatures can cast spells on attack. This spell is useless for now."
Earthquake spell outside siege battles:
"There are no castle walls to destroy using this spell"
Earthquake spell during castle defending:
"This spell will devastate your castle walls!"
Summon Elementals spells when other summoned elementals are present on battlefield:
"Those elemtal beings will kill each other, if not completely controlled."
Dispel and Mass Dispel, when there are no spells affecting your or enemy troops:
"Currently there are no magic effects affecting anyone on this battlefield, this spell is useless for now."

2023-09-20 21:04 UTC, LeHerosInconnu commented
Hello @Kazhuu,

> Hello @LeHerosInconnu thanks for the feedback! I'll take a look at the code again and fix these soon. Could you elaborate what you mean by this?
> 
> > There are other cases to be taken into consideration.
> 
> What other cases as well we should cover to gray out spells? Maybe if they are not related to here, I can do these in a separate PR.

In the game, as soon as the conditions are met, the message "That spell will affect no one!" is displayed.
All these conditions have already been anticipated, since the message is displayed.
This affects all combat spells, depending on the case (Armageddon, Resurrection True, etc.)
The place where the message is displayed should be moved from the battlefield, after the hero has cast the spell, to the magic book, at the moment when the hero attempts to cast the greyed-out spell (depending on the conditions already anticipated).
All this is indicated in the https://github.com/ihhub/fheroes2/discussions/4845 thread.
The spells bless, curse, etc. are special cases in that they can be cast even if they have no effect (e.g. the bless spell on peasants).
This PR can focus only on the four cases indicated in the original post, that's okay.

2023-09-23 18:56 UTC, Kazhuu commented
> Resurrection and True Ressurection, when there are no dead troops in non-elemental stacks: "There are no dead troops in your army, the spell is useless... for now."
> 
> Animate Dead when there are no destroyed undead creatures in stacks: "There are no fallen undead troops in your army, the spell is useless... for now."
> 
> Death Ripple and Death Wave spells, when all troops in enemy army are undead: "This spell will cause death and decay to your army and do nothing to your enemy!"
> 
> Holy Word and Holy Shout when there are no undead troops in enemy army: "This spell will devastate your undead army and do nothing to your enemy!"
> 
> Antimagic spell when enemy hero has 0 mana and there are no spellcasting creatures in his army: "Enemy hero can`t cast any spells and none of his creatures can cast spells on attack. This spell is useless for now."
> 
> Earthquake spell outside siege battles: "There are no castle walls to destroy using this spell"
> 
> Earthquake spell during castle defending: "This spell will devastate your castle walls!"
> 
> Summon Elementals spells when other summoned elementals are present on battlefield: "Those elemtal beings will kill each other, if not completely controlled."
> 
> Dispel and Mass Dispel, when there are no spells affecting your or enemy troops: "Currently there are no magic effects affecting anyone on this battlefield, this spell is useless for now."
> 
> Shield and Mass Shield spells when sieging enemy castle when only shooting enemies are arrow towers: "Castle towers use enchanted crossbow bolts that can penetrate any kind of defense, physical or magical, including effect of this spell"

Could all these cases be listed on discussion https://github.com/ihhub/fheroes2/discussions/4845. This way they don't get lost in PR comments after this PR is merged. Also if there are more cases that are not listed here. It would be nice to have them on there as well.

2023-09-23 19:10 UTC, Kazhuu commented
@LeHerosInconnu I fixed the issues you mentioned. Could please test again?

2023-09-23 21:18 UTC, LeHerosInconnu commented
Hello @Kazhuu,

> @LeHerosInconnu I fixed the issues you mentioned. Could please test again?

I'll look at it over the course of next week.

2023-09-25 10:13 UTC, LeHerosInconnu commented
Hello @Kazhuu,

> Hello @Kazhuu,
> 
> > @LeHerosInconnu I fixed the issues you mentioned. Could please test again?
> 
> I'll look at it over the course of next week.

Here are my observations with the last change.

In multiplayer mode, two human players, green and blue, blue player's hero attacking:

The attacking blue hero no longer has a "living" undead troop in his ranks, but the curse spell description indicates undead.
![Grayed combat spells 02 001](https://github.com/ihhub/fheroes2/assets/43583994/ab9a5fc1-377b-4ab2-91b2-289068b0e11d)
![Grayed combat spells 02 002](https://github.com/ihhub/fheroes2/assets/43583994/3937d03b-cc99-4cf9-99b1-777e22981ebe)

The defending green hero can cast the curse spell on the peasants, although the spell will have no effect.
![Grayed combat spells 02 003](https://github.com/ihhub/fheroes2/assets/43583994/36b3dd4e-cb93-4ead-a70e-9cb884abfb3d)

The attacking blue hero can cast the curse spell on the peasants, although the spell will have no effect.
![Grayed combat spells 02 004](https://github.com/ihhub/fheroes2/assets/43583994/64e525b8-1d46-4feb-8dbc-591b8f29d42d)

The attacking blue hero can cast the curse spell, the message "That spell will have no effect!" is displayed on the battlefield instead of the curse spells being grayed out.
![Grayed combat spells 02 005](https://github.com/ihhub/fheroes2/assets/43583994/1d953c9c-dcd5-45be-8ace-408d7bf417e9)
![Grayed combat spells 02 006](https://github.com/ihhub/fheroes2/assets/43583994/c5aaeb4f-94a9-4ca4-a08a-37695851194c)
![Grayed combat spells 02 007](https://github.com/ihhub/fheroes2/assets/43583994/9222a489-8884-4951-8fd0-7347041e083f)

The defending green hero can cast the curse spell, the message "That spell will have no effect!" is displayed on the battlefield instead of the curse spells being grayed out.
![Grayed combat spells 02 008](https://github.com/ihhub/fheroes2/assets/43583994/e377d28f-62ec-49db-8c3c-4a22ecb71981)
![Grayed combat spells 02 009](https://github.com/ihhub/fheroes2/assets/43583994/9eb18cf9-8b1c-43ed-b0e7-af3564e5db33)
![Grayed combat spells 02 010](https://github.com/ihhub/fheroes2/assets/43583994/0115d011-e7a6-4649-8369-585c4836e8e8)

The attacking blue hero can cast the bless spell on the peasants, although the spell will have no effect.
![Grayed combat spells 02 011](https://github.com/ihhub/fheroes2/assets/43583994/f31c745f-9fa8-46cd-9c82-ba4db597f5e1)

The defending green hero can cast the bless spell on the peasants, although the spell will have no effect.
![Grayed combat spells 02 012](https://github.com/ihhub/fheroes2/assets/43583994/73110c56-e86e-4e88-b47d-b8dc65c70978)

The attacking blue hero can cast the bless spell, the message "That spell will have no effect!" is displayed on the battlefield instead of the bless spells being grayed out.
![Grayed combat spells 02 013](https://github.com/ihhub/fheroes2/assets/43583994/92aa802a-4c45-475a-b112-ca494c5118d3)
![Grayed combat spells 02 014](https://github.com/ihhub/fheroes2/assets/43583994/affc661d-d513-4b37-be3d-73469d1f24ea)
![Grayed combat spells 02 015](https://github.com/ihhub/fheroes2/assets/43583994/df3f47d7-af2b-49af-b63d-15d1e1f4789a)

The defending green hero can cast the bless spell, the message "That spell will have no effect!" is displayed on the battlefield instead of the bless spells being grayed out.
![Grayed combat spells 02 016](https://github.com/ihhub/fheroes2/assets/43583994/80d5467f-a5af-4bc9-bdf2-061813c9d9b8)
![Grayed combat spells 02 017](https://github.com/ihhub/fheroes2/assets/43583994/987be172-7d5d-4c2e-a7f2-bec245f8acda)
![Grayed combat spells 02 018](https://github.com/ihhub/fheroes2/assets/43583994/180dd859-25f0-434b-9f3f-74d6a2e3d8ed)

2023-09-25 11:43 UTC, Kazhuu commented
Hi @LeHerosInconnu thank you a lot for your feedback and testing! Apparently I have not touched the functionality for these outside of the spell book usage. I'll add code to cover these cases as well and ping here when done.

2023-12-03 14:36 UTC, ihhub commented
Hi @Kazhuu  and @LeHerosInconnu , what's the status of this pull request? I suggest if the cannot do everything at once focus on one spell at the time.

2023-12-03 14:41 UTC, Kazhuu commented
Hello @ihhub! I still plan to work on this but currently being busy with work. This PR already has spell graying out functionality, but missing checks when the spell can be cast, but not on certain units. So I need to implement the checks for those cases where some units should display cross cursor indicating that spell cannot be used for this unit. I'll have more time to work on in coming weeks :+1:

2024-01-13 13:46 UTC, ihhub commented
We shall proceed with what changes we have to do not delay this pull request any longer.

2024-01-13 13:50 UTC, ihhub commented
Hi @Kazhuu , can you please copyright headers in your modified files?

2024-01-16 07:22 UTC, Kazhuu commented
Hi @ihhub. I updated the headers and fixed IWYU problems as well. Can you take a look?

2024-01-16 13:44 UTC, Kazhuu commented
I rephrased the texts like you asked @zenseii. Can you check?

2024-01-16 13:45 UTC, Kazhuu commented
> Shouldn't this also include the spell immunity for the living dragons (Green, Red and Black)?

I think it's better to merge this first and work on remaining ones in a separate PR.

2024-01-16 16:04 UTC, Kazhuu commented
Sorry I first didn't understand what you meant @Mr-Bajs. Yeah they should be included absolutely. Are there any other causes that we are missing? Also adding every cause adds more complexity to the code if this is required. However I guess at this point adding dragons is not a big work anymore if required. Whatever fits best this projects goals, I'll do the changes :+1:

2024-01-16 19:40 UTC, Kazhuu commented
Yeah I agree with @zenseii about questioning is this worth do effort. I'm fully okay to modify this PR and remove/modify added texts however needed :+1:

2024-01-17 22:09 UTC, LeHerosInconnu commented
@zenseii.

> > Yeah I agree with @zenseii about questioning is this worth do effort. I'm fully okay to modify this PR and remove/modify added texts however needed 👍
> 
> Then I vote for graying out the spell and displaying a message that says: "This spell will have no effect.".
> 
> What do you think @LeHerosInconnu and @ihhub ?

Personally, I agree with the simple sentence.

Both sentences are fine:

"That spell will affect no one!" (original sentence)

"This spell will have no effect!" (with an exclamation point at the end)

2024-01-18 07:29 UTC, Kazhuu commented
Hi @zenseii and @LeHerosInconnu. Now the game only reports "This spell will have no effect!" text when the spell is grayed out and cannot be used. However if you look at the latest change only. I basically only deleted the strings that were there and it simplified the code a bit but not that much that I originally thought... But I think going with this will do for now and if we want more specific strings, then we can open discussion for that if needed.

Note that this PR is still missing checks during the spell cast. For example you can still cast bless for peasants if you have some other unit that bless can be used on. You select bless from the spellbook and then just cast it on peasants. @LeHerosInconnu mentioned this earlier in this PR. Is this blocking the merge and should I implement it? Sorry to this PR has took so long, but I can still fix that if needed to this PR.

2024-01-18 10:17 UTC, Kazhuu commented
Okay sounds good @zenseii. Then this PR should be ready for rewiew and also maybe one more round of testing should not hurt as well @LeHerosInconnu

2024-01-31 20:34 UTC, Kazhuu commented
Hello @zenseii, I addressed your comments. Could you take a look?

2024-02-09 20:41 UTC, Kazhuu commented
Hello @zenseii I solved the merge conflict. Can you go forward now?

2024-03-10 05:42 UTC, Kazhuu commented
Hello! Any news on this one?

2024-03-11 15:02 UTC, ihhub requested changes
Hi @Kazhuu , I left one comment here. Can you please take a look at it?

2024-03-11 15:02 UTC, ihhub commented on src/fheroes2/battle/battle_army.cpp
> +bool Battle::Force::onlyHasMonster( const Monster & monster ) const
Please use `AllTroopsAreTheSame()`, `AllTroopsAreUndead()` and other methods of **Troops** class instead of creating new ones with the same logic.

2024-03-20 16:12 UTC, Kazhuu commented on src/fheroes2/battle/battle_army.cpp
> +bool Battle::Force::onlyHasMonster( const Monster & monster ) const
Yes I can use `AllTroopsAreUndead()` function to check for undead that is duplicate, but how I can check for only has specific monster? There seems to be no function in `Troops` class to check that. I can use `AllTroopsAreTheSame()` but I need to make additional call to get the information what the troop actually is. So I guess I refactor these functions to the `Troops` class and keep the ones needed, right?

2024-03-20 17:32 UTC, Kazhuu commented on src/fheroes2/battle/battle_army.cpp
> +bool Battle::Force::onlyHasMonster( const Monster & monster ) const
I tried to refactor the functions under `Troops` class but it seems that the counts of units are not updated during the battle. If I'm not wrong it seems `Unit` class is used for that purpose during the battle. How you see this should be done? Should I construct a new `Troops` instance when every time when function to check can the spell be cast is called? Or what should be the best approach here if we don't want to duplicate this logic?

2024-12-04 04:37 UTC, Kazhuu commented
Hello @ihhub I could look at this again if you still need. Have not been very active with this one for so long, sorry about that.

2024-12-04 05:16 UTC, ihhub commented
After having another look at the proposed logic from user perspective and these are my thoughts:
- the proposed changes try to tackle the same problem as as using **Disrupting Ray** on a monster with 1 defence. We don't gray out or say that the spell does nothing. The same principle must be applied for the proposed spells.
- we mustn't reply on monster name while making decisions. Only monster stats must be used. Even thought Peasant are the only monsters with fixed damage range it doesn't mean that other new monsters wouldn't have it later.

Overall, I see that we shouldn't do these micro-optimizations for users. Players should learn hard way what each spell do and where to apply.

What are your thoughts @Branikolog and @zenseii ?

2024-12-04 14:07 UTC, Branikolog commented
@ihhub
Hi! I'm not sure that maintaining so many corner cases when using spells worth it at the moment. The logic and the number of texts and translations required for implementing the full list of messages will take too much time and effort without real benefit. Also, all new spells that are going to be added in future could have issues affecting already implemented individual messages.
I'm absolutely OK with showing one uniform phrase, like "The spell will have no effect" over the book for each spell that really does not affect anyone or anything on the battlefield.

2024-12-09 07:25 UTC, Kazhuu commented
Thanks for the input @Branikolog. Should this PR just be abandoned?

2024-12-09 08:56 UTC, Alucard648 commented
> @ihhub Hi! I'm not sure that maintaining so many corner cases when using spells worth it at the moment. The logic and the number of texts and translations required for implementing the full list of messages will take too much time and effort without real benefit. Also, all new spells that are going to be added in future could have issues affecting already implemented individual messages. I'm absolutely OK with showing one uniform phrase, like "The spell will have no effect" over the book for each spell that really does not affect anyone or anything on the battlefield.

I think  "The spell will have no effect" should be a fallback string if no special string is used for this case.

2025-03-10 02:33 UTC, ihhub commented
I am closing this pull request as it has been in a stalled state for a very long time and we still haven't agreed what we want to do.

@Kazhuu , thank you for your work! Closing this pull request doesn't mean that you didn't do a good work. We should find just a better way for the problem.

2025-03-10 02:33 UTC, closed without merging