Slovak translation update
ihhub/fheroes2 pull request #7355
Opened 2023-06-25 12:11 UTC by agiat86

Translating a horde of lines in Slovak.

2023-06-28 15:47 UTC, Roxterat requested changes
I have reviewed this PR, @agiat86 and left several comments. Please take a look at them.

2023-06-28 15:47 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "Hniezdo zmijí"
Intended to be singular.

2023-06-28 15:47 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "Kapitánov kvartír"
Out of date to expressive

2023-06-28 15:47 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "Čarodejnica"
"Kúzelníčka" might be less witch-like and more charming way to call Sorceress.

2023-06-28 15:47 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "Červené draky"
"chlap" - draci

2023-06-28 15:47 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "Čierne draky"
"chlap" - draci

2023-06-28 15:47 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "Zelené draky"
"chlap" - draci

2023-06-28 17:12 UTC, agiat86 commented on files/lang/sk.po
> +msgstr "Zelené draky"
dub

2023-06-28 17:18 UTC, agiat86 commented on files/lang/sk.po
> +msgstr "Zelené draky"
... is what i thought but you're right

2023-06-28 17:35 UTC, agiat86 commented on files/lang/sk.po
> +msgstr "Čarodejnica"
True but "Kúzelníčka" might be too magician-like. It's a conundrum.

2023-06-28 17:36 UTC, agiat86 commented on files/lang/sk.po
> +msgstr "Najmi všetky tvory v meste."
Consistency is important. I should be more careful.

2023-06-28 17:37 UTC, agiat86 commented on files/lang/sk.po
> +msgstr "Kapitánov kvartír"
Later I was thinking something like "Kapitánsky priestor" but honestly "Kapitánova ubytovňa" is fine.

2023-06-28 17:39 UTC, agiat86 commented on files/lang/sk.po
> +msgstr "Hniezdo zmijí"
agreed, we should change it to "Hniezdo zmije"

2023-06-28 19:30 UTC, agiat86 commented on files/lang/sk.po
> +msgstr "Čarodejnica"
I know! "Zaklínačka"

2023-06-29 02:28 UTC, Roxterat reviewed
I left comments after a new review. Most of it is good.
Also be adviced, your PR might be merged if ready to be merged, all reviews are done and ihhub confirms the merge. If you want to keep working on it, change the PR into a Draft.

2023-06-29 02:28 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "%{monster} +%{count} jedincov."
Possible alternative:
"(N/n)árast %{monster} +%{count}." where the use of lowercase/capital depends on where this string is being used.
Up to you.

2023-06-29 02:28 UTC, Roxterat commented on files/lang/sk.po
> +msgstr " Všetky populácie sa znížia na polovicu."
"..sú znížené.."

2023-06-29 02:28 UTC, Roxterat commented on files/lang/sk.po
> +"mladších čias. Chceš si tieto mapy kúpiť?"
"1000" might be visually more appealing than "1 000", possibly with a separator. Might just be a subjective opinion, up to you.

2023-06-29 02:28 UTC, Roxterat commented on files/lang/sk.po
> +"budem rozdávať svoje mapy zadarmo!\""
Is this line replacing the original text instead of the translated part?

2023-06-29 02:33 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "Čarodejnica"
Sounds even more witch-like than "Čarodejnica" to me.. I suppose it's about the way we believe these Classes work, since there is no solid definition of those other than in instances like DnD, known stories, games, books etc. and they differ for each other.

2023-06-29 09:13 UTC, Roxterat reviewed
One more thing I have found..

2023-06-29 09:13 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "Obranca"
Does "Defender" and "scenarioName|Defender" have the same translation? I might have made a mistake because "Obránca" is rather Czech.

2023-06-29 20:08 UTC, agiat86 commented on files/lang/sk.po
> +msgstr "Obranca"
Oh yeah, good call, I'll fix it there too

2023-06-29 20:15 UTC, agiat86 commented on files/lang/sk.po
> +msgstr "%{monster} +%{count} jedincov."
I was trying to work around %{monster} being in Nominative. I can't work around the %{count} being 1, thought. This needs further edits in the future but for now I'll go with `%{monster} vzrástli o %{count}.`

2023-06-29 20:17 UTC, agiat86 commented on files/lang/sk.po
> +msgstr " Všetky populácie sa znížia na polovicu."
Yes.

2023-06-29 20:17 UTC, agiat86 commented on files/lang/sk.po
> +"mladších čias. Chceš si tieto mapy kúpiť?"
1000 would be more consistent too, fixing.

2023-06-29 20:19 UTC, agiat86 commented on files/lang/sk.po
> +"budem rozdávať svoje mapy zadarmo!\""
Unintentional. Fixing.

2023-06-30 01:45 UTC, Roxterat approved these changes
To this point the translated lines seem to be in the best possible form, good work @agiat86 .
There are still 117 lines for this PR to include if you want to fill some in, might include in initial statement as well (the first comment of the PR).

2023-06-30 15:07 UTC, Roxterat reviewed
I know it's bothering, but just had a few last thoughts about latest updates and it should be all done.

2023-06-30 15:07 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "Tieto priestory na prenájom."
I understand the original text is.. rather blunt and it is translated as such, but unless this is intended to be this way, I am not certain if the lack of grammar transfer is needed to be implemented.. depends on where is this line used, perhaps it is meant to be this way.

2023-06-30 16:18 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "Tieto priestory na prenájom."
It would be good to have a free hand on inventing own jokes instead of strictly holding on to the translation. If you have a good one, perhaps you might as well throw it in agiat86..

2023-06-30 16:18 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "Tieto priestory na prenájom."
..sign post compatible jokes that is.

2023-06-30 17:42 UTC, agiat86 commented on files/lang/sk.po
> +msgstr "Tieto priestory na prenájom."
Only thing that comes to mind is `Predám bojler` which means `Water boiler for sale`. It's a meme but a little obscure so idk. We'll think of something later.

2023-06-30 17:42 UTC, agiat86 commented on files/lang/sk.po
> +msgstr "Alchymistov labák"
You're right that it's too informal. And actually, it doesn't **need** to be short so f it, I'll go all in and call it `Alchymistické laboratórium`

2023-07-07 01:01 UTC, ihhub approved these changes

2023-07-07 01:01 UTC, merged

2023-07-07 01:01 UTC, ihhub commented
@agiat86 , huge thanks for this update!