Rework the spell generation in castle's Mage Guilds
ihhub/fheroes2 pull request #7362
Opened 2023-06-27 22:25 UTC by oleg-derevenetz

fix #7117
fix #7127

2023-06-28 11:17 UTC, oleg-derevenetz commented
Hi @LeHerosInconnu, could you please take a look at this PR and express your opinion regarding this new spell distribution across the Mage Guilds?

2023-06-29 11:38 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu, could you please take a look at this PR and express your opinion regarding this new spell distribution across the Mage Guilds?

Yes, that's much better.
I'll keep an eye on this in my next games once it's merged.
I hope you didn't suffer too much during the application of this change. :D

2023-06-29 13:33 UTC, oleg-derevenetz commented
> I hope you didn't suffer too much during the application of this change. :D

I'm still unhappy :(

2023-07-01 06:54 UTC, ihhub requested changes
Hi @oleg-derevenetz , I put 2 comments in this pull request. Would you mind to take a look at them?

2023-07-01 06:54 UTC, ihhub commented on src/fheroes2/castle/mageguild.cpp
> +        const uint32_t rand = Rand::Get( 0, 100 );
This should be `Rand::Get( 0, 99 )` as **std::uniform_int_distribution** uses an inclusive `[a,b]` range of values. The same for line67.

2023-07-01 06:54 UTC, ihhub commented on src/fheroes2/castle/mageguild.cpp
> +            addSpell( spell );
This is not an optimal way to populate data as there is a chance that this loop can be executed for a very long period of time while repeating the same values. I suggest to at least add a TODO comment to address this loop in the future.

2023-07-01 07:04 UTC, oleg-derevenetz commented on src/fheroes2/castle/mageguild.cpp
> +        const uint32_t rand = Rand::Get( 0, 100 );
Hi @ihhub that's how it implemented in the original game according to description above :)

> Аналогично пункту 2, на полки гильдии магов попадает одно из заклинаний третьей группы: Magic Arrow (20/101), Lightning Bolt (20/101), Fireball (20/101), Cold Ray (20/101), Cold Ring (21/101).

That's why we need `[0, 100]` here and not `[0, 99]`. The same is for line 67:

> Далее, независимо от типа города и его принадлежности (человек/компьютерный игрок), на полки гильдии попадает одно из заклинаний второй группы: Dispel Magic (25/101), Mass Dispel (25/101), Anti-Magic (25/101), Cure (26/101).

2023-07-01 07:07 UTC, oleg-derevenetz commented on src/fheroes2/castle/mageguild.cpp
> +            addSpell( spell );
Yes, but that's exactly how it works in the original game :) That's the original logic (besides the point that if 500 candidate spells in a row turn out to be doubles, the original game freezes).

2023-07-01 07:11 UTC, ihhub commented on src/fheroes2/castle/mageguild.cpp
> +        const uint32_t rand = Rand::Get( 0, 100 );
Thanks for the explanation!

2023-07-01 07:24 UTC, ihhub commented on src/fheroes2/castle/mageguild.cpp
> +            addSpell( spell );
This approach should be changed in the future to accommodate new spells being added. I suggest to do this way:
```cpp
std::vector<std::set<Spell>, 5> availableSpells;
for ( int i = Spell::NONE; i < Spell::SPELL_COUNT; ++i ) {
    if ( !Spell( i ).isValid() ) {
        continue;
    }

    availableSpells[Spell( i ).level()].emplace( Spell( i ) );
}

for ( const Spell & spell : general ) {
    availableSpells[spell.leve()].erase( spell );
}

for ( const Spell & spell : library) {
    availableSpells[spell.leve()].erase( spell );
}

for ( size_t level = 1; level <= mageGuildLevels.size(); ++level ) {
        const auto & [freeSlots, dummy] = mageGuildLevels[level - 1];

        while ( freeSlots > 0 && !availableSpells[level - 1].empty() ) {
            ...
    }
}
...

bool isValid() const
{
    return id != Spell::NONE && id < Spell::RANDOM && id > Spell::RANDOM5;
}

```

What do you think?

2023-07-01 07:28 UTC, oleg-derevenetz commented on src/fheroes2/castle/mageguild.cpp
> +            addSpell( spell );
@ihhub Well, if you prefer to have the optimized logic instead of the original one, I'll try to implement the optimized variant later today.

2023-07-01 07:46 UTC, ihhub commented on src/fheroes2/castle/mageguild.cpp
> +            addSpell( spell );
Thank you!

2023-07-01 18:04 UTC, LeHerosInconnu commented
Look at his joy at getting the Town Portal spell in a mage guild.
But the spell appears much more often in the mage guild than in Heroes 2; only once in his entire life as a Heroes 2 player! :D
He shouldn't get used to it for too long, otherwise he'll get jaded about getting the spell too easily. :)
https://www.youtube.com/watch?v=I3XwnKTcg3s&t=1909s

2023-07-01 18:15 UTC, oleg-derevenetz commented
> But the spell appears much more often in the mage guild than in Heroes 2; only once in his entire life as a Heroes 2 player!

I doubt it very much :) On maps with a large number of castles, you could periodically see this spell in the Mage Guilds, if you were not lazy to build the maximum level of Mage Guilds in all captured castles.

2023-07-01 19:01 UTC, oleg-derevenetz commented on src/fheroes2/castle/mageguild.cpp
> +            addSpell( spell );
Hi @ihhub I have made some effort to address your concerns, please take a look when you have time.

2023-07-02 01:39 UTC, ihhub approved these changes

2023-07-02 01:41 UTC, merged

2023-07-02 01:42 UTC, ihhub commented
@oleg-derevenetz , huge thanks for these changes!