Rework Castle Well render to reduce CPU usage
ihhub/fheroes2 pull request #7396
Opened 2023-07-08 16:19 UTC by Districh-ru

This PR optimizes the CPU use while rendering the Castle Well: cache the background image not to perform full render of all icons and texts for every creature animation frame.

2023-07-13 14:43 UTC, Districh-ru commented on src/fheroes2/castle/castle_well.cpp
> +        // This building is not build.
Hi, @zenseii!
Thank you for testing and for spell checking. :)

The vertical line to the right of EXIT button is fixed. In original assets this line is transparent. To speed-up rendering I did not clear the made image before copying Well background assuming that all transparent parts will be covered with building's images and buttons. Now this line is filled with black color.

2023-07-21 15:00 UTC, ihhub requested changes
Hi @Districh-ru , I left few comments in this pull request. Would you mind to check them?

2023-07-21 15:00 UTC, ihhub commented on src/fheroes2/castle/castle_well.cpp
> +                    }
I think we need to put a break here to avoid exit the loop.

2023-07-21 15:00 UTC, ihhub commented on src/fheroes2/castle/castle_well.cpp
> +                    Dialog::DwellingInfo( castleMonster[dwellingId], dwelling[dwellingId] );
I think we need to put a break here to avoid exit the loop.

2023-07-21 15:00 UTC, ihhub commented on src/fheroes2/castle/castle_well.cpp
> +void Castle::_wellRedrawMonsterAnimation( const fheroes2::Point & cur_pt, std::array<fheroes2::RandomMonsterAnimation, CASTLEMAXMONSTER> & monsterAnimInfo ) const
Since this is a new method please name variables using camelCase naming.

2023-07-21 16:44 UTC, Districh-ru commented on src/fheroes2/castle/castle_well.cpp
> +                    }
Sure, as we cannot do left click on more than one dwelling at one time. :)

2023-07-21 16:45 UTC, Districh-ru commented on src/fheroes2/castle/castle_well.cpp
> +                    Dialog::DwellingInfo( castleMonster[dwellingId], dwelling[dwellingId] );
Yes, we also cannot right click more than one dwelling at once.

2023-07-21 16:46 UTC, Districh-ru commented on src/fheroes2/castle/castle_well.cpp
> +void Castle::_wellRedrawMonsterAnimation( const fheroes2::Point & cur_pt, std::array<fheroes2::RandomMonsterAnimation, CASTLEMAXMONSTER> & monsterAnimInfo ) const
Thanks for noticing this!

2023-07-22 03:08 UTC, ihhub approved these changes

2023-07-22 03:08 UTC, merged

2023-07-22 03:09 UTC, ihhub commented
@Districh-ru , a bunch of thanks for polishing the engine!