Avoid redrawing the whole High Score screen while performing monsters animation
ihhub/fheroes2 pull request #7398
Opened 2023-07-09 07:24 UTC by Districh-ru

This PR optimizes the High Score screen render: cache background with the static part of animation and update only this part of screen while rendering next monsters animation frame.

2023-07-14 15:08 UTC, ihhub requested changes
Hi @Districh-ru , I left 2 comments in this pull request. Would you mind to take a look?

2023-07-14 15:08 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +    fheroes2::Copy( display, animationRoi.x, animationRoi.y, backgroundCopy, 0, 0, animationRoi.width, animationRoi.height );
Essentially we are trying to replicate `ImageRestorer` class logic. Should we use it here instead?

2023-07-14 16:32 UTC, Districh-ru commented on src/fheroes2/game/game_highscores.cpp
> +    const fheroes2::Rect backgroundCopyRoi( 512, 51, 76, 406 );
Hi @ihhub, I'll try to do this. but it will be a bit complex function: we have to check all mini monster sprites for their left and right offsets and get top and bottom offsets from the top and bottom monsters. :)

2023-07-14 16:33 UTC, Districh-ru commented on src/fheroes2/game/game_highscores.cpp
> +    fheroes2::Copy( display, animationRoi.x, animationRoi.y, backgroundCopy, 0, 0, animationRoi.width, animationRoi.height );
Yes, you are right. I'll use ImageRestorer class.

2023-07-15 05:56 UTC, ihhub approved these changes
Hi @Districh-ru , I just left one tiny code style related comment. The rest looks good to me.

2023-07-15 05:56 UTC, ihhub commented on src/fheroes2/game/game_highscores.cpp
> +
Please remove this empty line.

2023-07-15 06:08 UTC, Districh-ru commented on src/fheroes2/game/game_highscores.cpp
> +
Sure.
Done)

2023-07-15 06:24 UTC, merged

2023-07-15 06:24 UTC, ihhub commented
@Districh-ru , thank you so much for this improvement!