Add ability to select instruments and brush size in Editor UI
ihhub/fheroes2 pull request #7399
Opened 2023-07-09 11:48 UTC by Districh-ru

This PR relates to https://github.com/ihhub/fheroes2/issues/6845 and adds UI ability to:
- [x] select Brush size;
- [ ] select instrument type.

![brushSize](https://github.com/ihhub/fheroes2/assets/113276641/6ef47be9-7b97-4987-9a20-e0ba73960325)

2023-07-09 11:51 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.h
> +        uint8_t _selectedBrush{ Brush::WATER };
It will be used in the next commit. :)

2023-07-13 14:05 UTC, ihhub requested changes
Hi @Districh-ru , I left multiple comments here. Could you please check them?

2023-07-13 14:05 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +                fheroes2::showStandardTextMessage( _( "Treasures" ), _( "Used to place a resource or treasure." ), Dialog::ZERO );
Should we extra the text from these lines and from lines 222-269 into a container and use it?

2023-07-13 14:05 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            }
We are repeating the same text as lines 177-210. Should we store it in a separate container?

2023-07-13 14:18 UTC, ihhub commented
Hi @Districh-ru , I think creating separate functions to return text instead of the proposed container would be even better solution.

2023-07-13 14:47 UTC, Districh-ru commented
> Hi @Districh-ru , I think creating separate functions to return text instead of the proposed container would be even better solution.

Hi, @ihhub, sure. Initially I was thinking about making such function.. :)
I'll address your comments a little later.

2023-07-13 18:05 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            switch ( _selectedTerrain ) {
Sure, let's reduce the repetitions.

2023-07-14 15:28 UTC, ihhub requested changes
Hi @Districh-ru , I added several comments here. Could you please check them when you have time and see if them make sense?

2023-07-14 15:28 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            for ( uint8_t i = 0; i < BrushSize::BRUSH_SIZE_COUNT; ++i ) {
I suggest to avoid **BrushSize::BRUSH_SIZE_COUNT** here and use **_brushSizeButtonsRect.size()** as we handle std::array so the method is inlined. This will make the code more flexible for any future (if any) changes.

2023-07-14 15:28 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +        for ( uint8_t i = 0; i < Instrument::INSTRUMENTS_COUNT; ++i ) {
I suggest to avoid **Instrument::INSTRUMENTS_COUNT** here and use **_instrumentButtons.size()** as we handle std::array so the method is inlined. This will make the code more flexible for any future (if any) changes.

This is also applicable for any other cases where we use loops in the code within this file. This way we would also reduce the risk of mistakes in the code.

2023-07-14 15:28 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +    int EditorPanel::_getGroundId( uint8_t brushId )
This variable can be **const**.

2023-07-14 15:28 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +    std::string EditorPanel::_getObjectTypeName( uint8_t brushId )
This variable can be **const**.

2023-07-14 15:28 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            break;
Should we assert or it is okay to handle other cases?

2023-07-14 15:28 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +        if ( _selectedInstrument == Instrument::OBJECT ) {
Since we are not changing **_selectedInstrument** variable inside the above if-body then we should use **else** condition:
```cpp
if ( _selectedInstrument == Instrument::TERRAIN ) {
...
}
else if ( _selectedInstrument == Instrument::OBJECT ) {
...
}
```

This way it would be slightly faster :)

2023-07-14 15:28 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +                    if ( i != _selectedBrushSize ) {
Please combine else with if. SonarQube would be happy about this.

2023-07-14 15:28 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +    int EditorPanel::_getGroundId( uint8_t brushId )
I suggest to return `const char*` (or std::string) by this function and call **Maps::Ground::String()** internally. In this case we don't need to call **Maps::Ground::String** anywhere else in this code within this file, this function will return similar value as **_getObjectTypeName()** and we can avoid hardcoding values in line 334-360.

2023-07-14 18:03 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            for ( uint8_t i = 0; i < BrushSize::BRUSH_SIZE_COUNT; ++i ) {
Hi @ihhub, sure, let's make the code more flexible.

2023-07-14 18:03 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +        for ( uint8_t i = 0; i < Instrument::INSTRUMENTS_COUNT; ++i ) {
OK)

2023-07-14 18:10 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            break;
Sure, let's leave an assertion that if a new area is added, we must remember to give it a name.

2023-07-14 18:11 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +        if ( _selectedInstrument == Instrument::OBJECT ) {
Sure. :)

2023-07-14 18:22 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +    int EditorPanel::_getGroundId( uint8_t brushId )
OK)

2023-07-15 02:45 UTC, ihhub requested changes
Hi @Districh-ru , I left few more comments in this pull request. My apologies if it takes too much time. Could you please take a look at the comment again and validate if they make sense?

2023-07-15 02:45 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +        for ( uint8_t i = 0; i < static_cast<uint8_t>( _instrumentButtonsRect.size() ); ++i ) {
We can just use **size_t** without the need of casting.

2023-07-15 02:45 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +        for ( uint8_t i = 0; i < static_cast<uint8_t>( _brushSizeButtonsRect.size() ); ++i ) {
We can just use **size_t** without the need of casting.

2023-07-15 02:45 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.h
> +        uint8_t _selectedInstrument{ Instrument::TERRAIN };
I suggest to move all new member at the end of the class and put all **uint8_t** members at the end. In this case the class will be smaller by size due to padding rules.

2023-07-15 02:45 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.h
> +    enum Instrument : uint8_t
Are we going to use these enumerations somewhere else outside this class? If not let's declare then within the class in **private** section (just before any member) to reduce their scope and accessibility.

2023-07-15 02:45 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            for ( uint8_t i = 0; i < static_cast<uint8_t>( _terrainButtonsRect.size() ); ++i ) {
I suggest to keep **size_t** here and only later at the time of assignment to **_selectedTerrain** convert it. The same applies for other similar places.

2023-07-15 02:45 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +                    fheroes2::showStandardTextMessage( _getObjectTypeName( objectId ), text, Dialog::ZERO );
Should we add **break** here since only one element can active mouse right clicking?

2023-07-15 02:45 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +        return {};
fheroes2::Text class does not accept **nullptr** as it handle it as an error which is valid since we don't want to have empty texts. This line initiates default constructor for `const char*` which is in fact 0 or `nullptr`. To keep the code aligned with **_getTerrainTypeName** method I recommend to return something like **"Unknown object type"**. It would be easier to catch such an error.

2023-07-15 02:45 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +                    _redraw();
Should we add **break** here since we expect only one button to be pressed?

2023-07-15 02:45 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +                    _redraw();
Should we add **break** here since we expect only one button to be pressed?

2023-07-15 06:43 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.h
> +    enum Instrument : uint8_t
Hi @ihhub, for now we use them only in `EditorPanel` class. Later if we may want to use them outside of class we can move the needed enumeration outside of class and possibly to other H file (e.g. editor.h).
So let's put them now in the private section of class.

2023-07-15 06:44 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +        for ( uint8_t i = 0; i < static_cast<uint8_t>( _instrumentButtonsRect.size() ); ++i ) {
Sure)

2023-07-15 06:44 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +        for ( uint8_t i = 0; i < static_cast<uint8_t>( _brushSizeButtonsRect.size() ); ++i ) {
Sure)

2023-07-15 06:46 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.h
> +        uint8_t _selectedInstrument{ Instrument::TERRAIN };
Sure, it will also arrange class members by type to make it easier to maintain the class in future.

2023-07-15 06:46 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            for ( uint8_t i = 0; i < static_cast<uint8_t>( _terrainButtonsRect.size() ); ++i ) {
OK)

2023-07-15 06:47 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +                    fheroes2::showStandardTextMessage( _getObjectTypeName( objectId ), text, Dialog::ZERO );
Yes, it will reduce unneeded computations.

2023-07-15 06:48 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +        return {};
Thanks for the explanation!
Let's return "Unknown object type".

2023-07-15 06:48 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +                    _redraw();
Yes)

2023-07-15 06:48 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +                    _redraw();
Yes)

2023-07-16 04:23 UTC, ihhub approved these changes

2023-07-16 04:23 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +
Please remove this empty line.

2023-07-16 04:24 UTC, ihhub commented
@drevoborod , could you please test these changes? You will need a debug version of the game. Press E in the Main Menu to open the Editor.

2023-07-16 05:01 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +
Sure)

2023-07-16 20:02 UTC, drevoborod commented
Checked the following: 

- [x] select terrain/object type;
- [x] select Brush size;
- [x] add right click tips for Brush size;
- [x] add right click tips for terrain/object type;
- [x] add text for selected terrain/object type.

@Districh-ru , no issues, but:
1. is it OK that no type of selected brush actually allows to draw anything? And same to object selection - actual objects selection window does not appear on clicking to corresponding buttons?
2. Is this text correct? Actually this unlimited size brush can be used not for cleaning but for creation of large size areas. 
![изображение](https://github.com/ihhub/fheroes2/assets/10282847/482ab0d4-d4cd-45c2-81d3-814466d38651)
And in formal editor2.exe there is other text:
![изображение](https://github.com/ihhub/fheroes2/assets/10282847/879cad82-277c-497d-8503-e2e6d658a828)
Looks like you'we taken this text from the case when eraser is selected. In formal editor2.exe these two texts differ depending on what is selected: some terrain or the eraser, and in current editor's revision there is no separate text.
3. By the way, should all these texts be same as in formal editor? Some of them differ.
4. Seems like in these messages there should be a non-breaking space between an article and a noun: 
![изображение](https://github.com/ihhub/fheroes2/assets/10282847/372f8311-ef46-4a6b-8faa-035d8f206a2e)
![изображение](https://github.com/ihhub/fheroes2/assets/10282847/138edd47-6e51-4cf4-9c44-378ca96e61d4)
![изображение](https://github.com/ihhub/fheroes2/assets/10282847/53b576ed-9ea2-41f7-8fe6-029449cf1fb1)
![изображение](https://github.com/ihhub/fheroes2/assets/10282847/f45b97e9-e9f2-4e73-93c0-b7d7834be9c9)
![изображение](https://github.com/ihhub/fheroes2/assets/10282847/d05de097-4f24-4f09-af3f-74479ca7628b)

2023-07-17 14:03 UTC, Districh-ru commented
Hi @ihhub and @drevoborod, I'll address points 2 and 4 today a little later.

2023-07-17 17:20 UTC, Districh-ru commented
Hi @drevoborod, the brush size texts are now separated to draw/erase and a/an article in object type descriptions is moved to a new line.
Could you please check these changes when you have time.

2023-07-17 18:20 UTC, drevoborod commented
> the brush size texts are now separated to draw/erase and a/an article in object type descriptions is moved to a new line.

Checked it. Now it seems OK for me. But I noticed another minor issue. It's up to you to fix it or not:
![изображение](https://github.com/ihhub/fheroes2/assets/10282847/4542dd1d-6e76-46aa-aa29-66d562deaea3)
I suggest to place "4 by 4" and similar texts on the same line, so possibly it could be better to leave them on the first line.

2023-07-18 14:24 UTC, ihhub approved these changes

2023-07-18 14:24 UTC, merged

2023-07-18 14:24 UTC, ihhub commented
@Districh-ru , well done!