Maps Tiles related code cleanup
ihhub/fheroes2 pull request #7418
Opened 2023-07-16 05:24 UTC by ihhub

To make things easier for the Editor changes.

2023-07-16 08:07 UTC, Districh-ru requested changes
Hi @ihhub, I left one suggestion. Could you check it when you have time.

2023-07-16 08:07 UTC, Districh-ru commented on src/fheroes2/world/world_pathfinding.cpp
>  }
This method could be inlined, what do you think?

2023-07-16 08:14 UTC, oleg-derevenetz commented on src/fheroes2/world/world_pathfinding.cpp
>  }
In #7408 I made this variable `constexpr` because it does not change anywhere in reality.

2023-07-16 08:22 UTC, Districh-ru commented on src/fheroes2/world/world_pathfinding.cpp
>  }
It changes value only in this line in this code:
https://github.com/ihhub/fheroes2/blob/44f0f6b9e06e397f131ade88755cd7c7a5924fba/src/fheroes2/ai/normal/ai_normal_hero.cpp#L2116
In all other places its value is set to 0.5.
In #7408 this line is removed so there it can be `constexpr`.

2023-07-16 08:59 UTC, oleg-derevenetz commented on src/fheroes2/world/world_pathfinding.cpp
>  }
@Districh-ru Yes, in any case, this PR is still in some way "in flux".

2023-07-16 10:33 UTC, oleg-derevenetz approved these changes

2023-07-17 14:46 UTC, ihhub commented on src/fheroes2/world/world_pathfinding.cpp
>  }
Hi @Districh-ru , I revert these changes not to conflict with #7408

2023-07-17 15:40 UTC, merged