Make thieves guild adapt background to chosen interface
ihhub/fheroes2 pull request #7419
Opened 2023-07-16 11:56 UTC by zenseii

This makes the thieves guild show with evil stone background if that interface type is chosen.

When visiting the oracle the good interface will always show because the Oracle isn't playing on your team and should therefore not change their interface according to your alignment.

![image](https://github.com/ihhub/fheroes2/assets/12501091/d756b7ec-7d59-4712-be7b-bd23900172b8)

2023-07-16 12:13 UTC, Districh-ru commented
Hi, @zenseii.
Maybe we also should use "Evil" border for hero icon (`ICN::LOCATORE`)? :)

2023-07-16 13:28 UTC, Districh-ru requested changes
Hi, @zenseii. Well done!
I have one computation speed related suggestion with a question to discuss. Could you take a look when you have time.

2023-07-16 13:48 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_thievesguild.cpp
> +    const bool isEvilInterfaceTown = Settings::Get().isEvilInterfaceEnabled() && !oracle;
OK, let's consider the Oracle good for now. We can easily change this setting if necessary.

In future we will add "Auto" interface and then we probably might change this behavior to use Evil interface if it is set in options and Good - if it is set in options and if Auto is set in options.

2023-07-16 13:49 UTC, Districh-ru approved these changes

2023-07-17 14:22 UTC, ihhub approved these changes

2023-07-17 14:22 UTC, merged