Make campaign buttons translatable, add text adaptable button method, fix campaign button issues, make guildWell EXIT button adapt to text
ihhub/fheroes2 pull request #7421
Opened 2023-07-16 14:07 UTC by zenseii

This PR adds a function that takes a text and adapts a specified empty button template to the width of that text.

The campaign buttons and the smaller EXIT button in the guilds and the well are generated with this. 

Campaign buttons are made in sets which include the DIFFICULTY button now. This streamlines the code.

Empty templates for Price of Loyalty and smaller exit button for guilds/well were added to make this possible.

`BUTTON_GUILDWELL_EXIT` serves as a proof of concept of how the new function works and is used.

The Price of Loyalty buttons have been given transparency so that the parts of the released state of the buttons do not show when pressing the buttons.

To do this it was necessary to add a small piece of stone background `stonebak_pol` for Price of Loyalty buttons.

All campaign buttons have been given shadows, both when and when not using the same language as the provided assets.

To do this I chose to remove the already embedded shadows in the original GOOD and EVIL campaign buttons and use `addGradientShadow()` to all buttons. Thanks to @Districh-ru for this valuable advice.

Fix #7312
Fix #4977

Additionally I discovered that the pressed state of the empty good and evil buttons were missing dark edges on the left side. With this change they behave like the original buttons (NOTE that single bright pixel to the left of the text area of the released state has been fixed for both good and evil interfaces):

Before:
![image](https://github.com/ihhub/fheroes2/assets/12501091/6f4508df-c956-4328-aa04-3e30bf50cc25)
 After:
 ![image](https://github.com/ihhub/fheroes2/assets/12501091/4e4989c4-2d1a-4c88-a44e-b8274fd9b362)

Relates to #6105 

<details>
<summary>Pictures of the related screens with buttons in different languages</summary>

![image](https://github.com/ihhub/fheroes2/assets/12501091/3e7cfcb1-42e3-494a-96ce-4a2a32f6d56f)

![image](https://github.com/ihhub/fheroes2/assets/12501091/6a87e796-3bcd-4a69-9796-bbcede74f214)

![image](https://github.com/ihhub/fheroes2/assets/12501091/9be28e69-7aca-4cec-aba3-721eb961835d)

![image](https://github.com/ihhub/fheroes2/assets/12501091/4e86bf5d-3766-4e8c-bd46-e21a8c6cb517)

![image](https://github.com/ihhub/fheroes2/assets/12501091/8660bb58-cb1d-4414-8f50-24cd66b1113a)

</details>

2023-07-18 18:00 UTC, Districh-ru requested changes
Hi @zenseii! 
You did a great work, visually it looks perfect and at last I can translate the EXIT button in the castle Well.
Well done!

I left several comments, could you please check them when you have time?

2023-07-19 16:53 UTC, Districh-ru commented on src/fheroes2/gui/ui_button.cpp
> +        const char * translatedText = _( text );
My apologies, you are absolutely right!
There should be `_( )` as the `text` was made using `gettext_noop()`.
Thanks for the explanation. :)

2023-07-19 16:57 UTC, Districh-ru commented
> As for the actual text I realized that we might not even need the `guildWell|` context anymore because the button can fit any word you choose. Actually now the limiting buttons are the larger normal ones (until we generate them with this new function).
> I suppose we can remove this context. What do you think?

Hi, @zenseii, yes, now we can remove the `guildWell|` context.

2023-07-20 18:53 UTC, Districh-ru requested changes
Hi, @zenseii. The buttons in campaign info dialog looks great!
I left several comments. Could please you take a look when you have time.

2023-07-20 18:53 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                if ( originalReleased.width() != 94 && originalPressed.width() != 94 ) {
We should also check these images height as we are later accessing `pixelPosition` which is on the 4th row of image (`4 *96`), so the height should be more than 5.
If it is less than 5 (in case these images are corrupted) we may try to access this "pixel" outside of image data.

2023-07-20 18:53 UTC, Districh-ru commented on src/fheroes2/gui/ui_button.h
> +    void makeTransparentBackground( fheroes2::Sprite & released, fheroes2::Sprite & pressed, const int backgroundIcnID );
`Sprite & released` can be **const**.

2023-07-20 18:53 UTC, Districh-ru commented on src/fheroes2/game/game_campaign.cpp
> +    fheroes2::addGradientShadow( fheroes2::AGG::GetICN( buttonIconID, 8 ), display, { difficultyPlacement, top.y + 431 }, { -5, 5 } );
We can cache the button's vertical offset so we don't have to do the same calculation in these lines: 1325 - 1334.
```cpp
const int32_t buttonOffsetY = top.y + 431;
```

2023-07-20 18:53 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                    for ( uint32_t i = 0; i < 4; ++i ) {
As in this loop we use `i` four times multiplying it by 2 we can do this multiply once:
```suggestion
                    for ( uint32_t i = 0; i < 8; i += 2 ) {
```
and replace all `2 * i` by `i` on lines 1502, 1504, 1511, 1513.

Doing this we will reduce computations and also make Cland-Tydy happy. :)

2023-07-20 18:53 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                    for ( uint32_t i = 0; i < 4; ++i ) {
The same comment as above, we can do `i+=2` here instead of multiplying i by 2 every time in this loop. :)

2023-07-20 18:53 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +            fheroes2::getTextAdaptedButton( _icnVsSprite[campaignSetIcnId][2 * i], _icnVsSprite[campaignSetIcnId][2 * i + 1], texts[i], emptyButtonIcnID );
We could cache `2 * i` here:
```cpp
const size_t icnIndex = 2 * i;
```

2023-07-21 03:10 UTC, Districh-ru requested changes
Hi @zenseii, I left one comment, could you address it when you have time.

2023-07-21 03:10 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +            fheroes2::getTextAdaptedButton( _icnVsSprite[campaignSetIcnId][2 * i], _icnVsSprite[campaignSetIcnId][icnIndex + 1], texts[i], emptyButtonIcnID );
Please replace `2 * i` with the cached `icnIndex`.
```suggestion
            fheroes2::getTextAdaptedButton( _icnVsSprite[campaignSetIcnId][icnIndex], _icnVsSprite[campaignSetIcnId][icnIndex + 1], texts[i], emptyButtonIcnID );
```

2023-07-21 14:53 UTC, ihhub requested changes
Hi @zenseii , I put few small comments here. Could you please check them?

2023-07-21 14:53 UTC, ihhub commented on src/fheroes2/gui/ui_button.cpp
> +        for ( int32_t x = 0; x < pressed.width() * pressed.height(); ++x ) {
I suggest to cache **pressed.width() * pressed.height()** as a compiler won't do this.

2023-07-21 14:53 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                const bool isGoodInterface = id == ICN::EMPTY_GOOD_BUTTON;
Please bring back parenthesis for the expression. It helps with code readability.

2023-07-21 15:03 UTC, Districh-ru approved these changes
👍

2023-07-21 15:37 UTC, ihhub approved these changes

2023-07-21 15:54 UTC, merged

2023-07-21 15:54 UTC, ihhub commented
@zenseii , huge thanks for this improvements!