Really turn off the AIAutoControlMode only on the next turn
ihhub/fheroes2 pull request #7435
Opened 2023-07-20 22:36 UTC by oleg-derevenetz

2023-07-21 15:49 UTC, ihhub requested changes
Hi @oleg-derevenetz , I put few comments here. Would you mind to take a look at them?

2023-07-21 15:49 UTC, ihhub commented on src/fheroes2/gui/interface_focus.cpp
> +#if defined( WITH_DEBUG )
Would it be better to combine these two macro into one
```cpp
#if !defined( NDEBUG ) && defined( WITH_DEBUG )
```
?

2023-07-21 15:49 UTC, ihhub commented on src/fheroes2/game/game_hotkeys.cpp
> +            class RecursionGuard
I do not entirely understand the purpose of this class over normal code:
```cpp
recursiveCall = true;
... // do something
recursiveCall = false;
```
except RAII principle. Could you please explain it?

2023-07-21 16:03 UTC, oleg-derevenetz commented on src/fheroes2/game/game_hotkeys.cpp
> +            class RecursionGuard
@ihhub Except RAII, there is none :) I can change this if you want. I like RAII because it lets you not to care about additional `return`-like calls in future. It's very easy to forget to add another `recursiveCall = false` before such a `return`.

2023-07-21 16:10 UTC, ihhub commented on src/fheroes2/gui/interface_focus.cpp
> +#if defined( WITH_DEBUG )
Yeah, now I get it. Frankly speaking this code doesn't look nice but I see no other way to make it better :)

2023-07-21 16:14 UTC, ihhub commented on src/fheroes2/game/game_hotkeys.cpp
> +            class RecursionGuard
Let's do this way.

2023-07-21 16:14 UTC, ihhub approved these changes

2023-07-21 16:14 UTC, ihhub commented
Hi @drevoborod , would you mind to test these changes?

2023-07-21 18:01 UTC, Districh-ru approved these changes
Well done!
Now after switching back to human control AI correctly finishes the turn. And during this turn you can change your mind. :)
I let AI to play and win a map and found no issues.

2023-07-21 19:53 UTC, drevoborod commented
I agree - no issues. Testing completed :)

2023-07-22 03:09 UTC, merged

2023-07-22 03:09 UTC, ihhub commented
@oleg-derevenetz , thank you so much for this improvement!