Slovak translation
ihhub/fheroes2 pull request #7439
Opened 2023-07-21 14:53 UTC by agiat86

2023-07-21 15:00 UTC, ihhub commented
Hi @agiat86 , please fix merge conflict here.

2023-07-22 06:03 UTC, Roxterat requested changes
@agiat86 left some comments, mostly alternatives.

2023-07-22 06:03 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "Meteorický roj"
"Roj / (s)pád meteorov" could fit here perhaps.

2023-07-22 06:03 UTC, Roxterat commented on files/lang/sk.po
> +msgstr "Narušujúci lúč"
"Rušivý lúč" maybe..

2023-07-22 16:44 UTC, agiat86 commented on files/lang/sk.po
> +msgstr "Lamač mečov"
Oh, yeah, thanks.

2023-07-22 16:45 UTC, agiat86 commented on files/lang/sk.po
> +msgstr "Narušujúci lúč"
Sounds too much as "disturbing ray" and "cancelling ray" so idk

2023-07-22 16:46 UTC, agiat86 commented on files/lang/sk.po
> +msgstr "Anti-Mágia"
It could. Yeah, it sound kind of cool too!

2023-07-22 16:59 UTC, agiat86 commented on files/lang/sk.po
> +msgstr "Meteorický roj"
Pád meteorov? Meteor Shower meaning Meteorický roj is a correct translation but it's not really what's happening. It's really a small meteor disaster, instead. The russian translation is Камнепад. We can go with that. Pád kameňov. They are rocks, after all. Nice and short too. We can revisit that if needed.

2023-07-23 04:38 UTC, Roxterat approved these changes
Approved.

2023-07-23 14:50 UTC, ihhub approved these changes

2023-07-23 14:50 UTC, merged

2023-07-23 14:50 UTC, ihhub commented
@agiat86 , thank you very much for this update!