Disable transform layer for images where it is not needed (to speed-up image processing)
ihhub/fheroes2 pull request #7449
Opened 2023-07-22 14:20 UTC by Districh-ru

This PR is a part of #7233

This PR disables `transform()` layer for images that have no transparent (or shadow/bright transform) pixels:
- during ICN load;
- for battle arena fade effect (after the battle);
- for spell effects:
  - Death Wave;
  - Holy Shout;
  - Earthquake;
  - Armageddon;
- for Puzzle map.

2023-07-22 14:41 UTC, ihhub requested changes
Hi @Districh-ru , I left few comments here. Could you please take a look at them?

2023-07-22 14:41 UTC, ihhub commented on src/engine/image_tool.cpp
> +                }
I think this would be faster:
```cpp
noTransformLayer = noTransformLayer && ( static_cast<int32_t>( posX ) >= width );
```

2023-07-22 14:41 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                        original.image()[2314] = 70;
If speed is a concern then we need to cache **original.image()** is a virtual function and cannot be inlined.

2023-07-22 14:41 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                for ( fheroes2::Sprite & sprite : _icnVsSprite[id] ) {
I suggest to leave a TODO comment to modify the resources instead of adding a hack here. h2d file should contain the correct resources in order to speed up loading and avoid unneccessary computations.

2023-07-22 14:57 UTC, Districh-ru commented on src/engine/image_tool.cpp
> +                }
Hi @ihhub, thanks for the suggestion!

2023-07-22 14:57 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                        original.image()[2314] = 70;
Sure!)

2023-07-22 14:58 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                for ( fheroes2::Sprite & sprite : _icnVsSprite[id] ) {
I left a TODO in `h2d_file.cpp`

2023-07-22 16:12 UTC, ihhub approved these changes

2023-07-22 16:13 UTC, ihhub commented
Hi @Districh-ru , could you please update the description to specify the scope of testing? At least to verify that we don't break any rendering by these changes.

2023-07-22 16:48 UTC, Districh-ru commented
> Hi @Districh-ru , could you please update the description to specify the scope of testing? At least to verify that we don't break any rendering by these changes.

Hi, @ihhub, a short description is added.

2023-07-22 16:53 UTC, Districh-ru commented
Hi, @drevoborod, could you please test this PR when you have time.

2023-07-22 21:23 UTC, drevoborod commented
Testing completed, didn't find any issues. All mentioned cases were checked plus several extra.

2023-07-23 01:41 UTC, merged

2023-07-23 01:41 UTC, ihhub commented
@Districh-ru , thank you so much for this improvement!