Add Summon Boat spell support for AI
ihhub/fheroes2 pull request #7479
Opened 2023-07-27 13:49 UTC by oleg-derevenetz

close #7470

2023-07-27 14:34 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu just one question while you are here: in the original game, can AI use the Summon Boat spell? I couldn't get the AI to use it on the test map.

Not sure about that.
But I do know that AI doesn't make optimal use of boats. :)
I'll do a test about that.

2023-07-27 15:24 UTC, LeHerosInconnu commented
@oleg-derevenetz.

> Not sure about that. But I do know that AI doesn't make optimal use of boats. :) I'll do a test about that.

I did a single player test on the original game, color blue for the human player.
After a month, the AI player with the green color still hadn't used the Summon Boat spell, despite all the appetizing objects around.

In multiplayer mode, blue and green for human players.
The green player cannot use the Summon Boat spell ("Summon Boat failed!!!").

In single-player mode, green for the human player.
The green player can use the Summon Boat spell.

It seems that only the first human player can use the Summon Boat spell.
The AI doesn't seem to be able to use the Summon Boat spell in all cases.
I think this is by design, to avoid the AI "destroying" the scenario if boats are used in a scenario.

Here is the test scenario file:
[0 9916.zip](https://github.com/ihhub/fheroes2/files/12185115/0.9916.zip)

2023-07-27 15:33 UTC, oleg-derevenetz commented
@LeHerosInconnu thank you very much!

> The AI doesn't seem to be able to use the Summon Boat spell in all cases.
I think this is by design, to avoid the AI "destroying" the scenario if boats are used in a scenario.

OK, then why did we just add Summon Boat support for AI? :) This will ruin the gameplay :)

2023-07-27 15:55 UTC, ihhub commented
Hi @LeHerosInconnu , this is interesting that only one human player can summon a boat. How about more than 2 players?

2023-07-27 16:01 UTC, oleg-derevenetz commented
@ihhub

>  this is interesting that only one human player can summon a boat. How about more than 2 players?

According to my observations, in OG neutral boats are "assigned" to the first human player in queue, regardless of its color, and I've never seen AI summoning a boat, even if it built one.

2023-07-28 12:34 UTC, LeHerosInconnu commented
Hello @ihhub and @oleg-derevenetz,

> Hi @LeHerosInconnu , this is interesting that only one human player can summon a boat. How about more than 2 players?

I tested it with 3 human players and it works the same way.
Only the first human player can use the Summon Boat spell on boats marked as neutral at the start of the scenario.
The player's own boats built in a shipyard, neutral boats captured by one of the player's heroes, and boats captured from an opponent by one of the player's heroes can of course be summoned with the Summon Boat spell.
I have not observed an AI player using the Summon Boat spell on a boat built in one of his shipyards, or on a neutral boat captured, or on a boat captured from an opponent.

Here is the test scenario file:
[0 9916a.zip](https://github.com/ihhub/fheroes2/files/12194512/0.9916a.zip)

2023-07-28 13:47 UTC, Branikolog commented
Hi, @oleg-derevenetz 

>OK, then why did we just add Summon Boat support for AI? :) This will ruin the gameplay :)

Potentially yes. But looking at AI spamming boats from his shipyard wasting tons of resources (for instance on Seven Lakes map) makes me sad.

As a compromise I'm proposing to allow AI summon only **his** boats, not neutral ones. (for the cases, when mapmakers placed boats exactly for the human player)

2023-07-28 13:54 UTC, oleg-derevenetz commented
Hi @Branikolog

> As a compromise I'm proposing to allow AI summon only his boats, not neutral ones. (for the cases, when mapmakers placed boats exactly for the human player)

I suggest to thoroughly test the gameplay with this particular PR and then we'll see. This restriction is relatively easy to implement (in comparison with this PR), so it may be implemented later in a separate PR.

2023-07-29 15:28 UTC, idshibanov commented on src/fheroes2/world/world_pathfinding.cpp
> +        if ( hero.GetSpellPoints() < summonBoat.spellPoints( &hero ) + hero.GetMaxSpellPoints() * _spellPointsReserveRatio ) {
Should we check if there's a boat on the map?

2023-07-29 15:29 UTC, idshibanov approved these changes
Overall I like the approach

2023-07-29 15:44 UTC, oleg-derevenetz commented on src/fheroes2/world/world_pathfinding.cpp
> +        if ( hero.GetSpellPoints() < summonBoat.spellPoints( &hero ) + hero.GetMaxSpellPoints() * _spellPointsReserveRatio ) {
Hi @idshibanov currently this is checked later - in the `isMovementAllowedForColor()`, but I suppose we can check it here instead, because it's highly unlikely that the boat will arrive or disappear during the hero movement. I'll add this optimization later today.

2023-07-29 17:37 UTC, ihhub commented
I will thoughtfully review this pull request tomorrow or day after as I am running out of free time these days :(

2023-07-30 10:57 UTC, oleg-derevenetz commented on src/fheroes2/world/world_pathfinding.cpp
> +                if ( anotherNodeIdx == targetIndex && !isMovementAllowed( newIndex, Direction::Reflect( directions[i] ) ) ) {
The previous logic here led to the following invalid behavior:

https://github.com/ihhub/fheroes2/assets/32623900/98060939-77b2-4554-99b3-1f3e60aa980b

AI is "dancing" near the artifact on the coast because it thinks that the hero can take it. That's because the tile passability was checked in the wrong direction (artifact -> hero). After checking the passability in the right direction, the result is as follows:


Uploading fheroes2 engine, version_ 1.0.6 2023-07-30 13-50-24.mp4…

2023-07-30 11:12 UTC, Branikolog commented on src/fheroes2/world/world_pathfinding.cpp
> +                if ( anotherNodeIdx == targetIndex && !isMovementAllowed( newIndex, Direction::Reflect( directions[i] ) ) ) {
Hi, @oleg-derevenetz !
Will this also fix an issue with well from this video?

https://github.com/ihhub/fheroes2/assets/55348946/580847bd-903a-4950-a63f-9e9773be8097

Or it's related only to water positioning?

2023-07-30 11:31 UTC, oleg-derevenetz commented on src/fheroes2/world/world_pathfinding.cpp
> +                if ( anotherNodeIdx == targetIndex && !isMovementAllowed( newIndex, Direction::Reflect( directions[i] ) ) ) {
Hi @Branikolog no, this is not related just to the water positioning, but in your case, the previous logic should also have worked just fine, because you can't just go "through" the well object in the upper direction. Maybe it's a different issue.

2023-07-31 13:11 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left several comments here. Could you please take a look at them when you have spare time?

2023-07-31 13:11 UTC, ihhub commented on src/fheroes2/ai/ai.h
> +        virtual void HeroesFinishMovement( Heroes & hero );
Is it correct that at the moment we don't have any logic for this method?

2023-07-31 13:11 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> +        Interface::GameArea & gameArea = Interface::AdventureMap::Get().getGameArea();
I think this change was done during development as this is just variable relocation from one line to another :)

2023-07-31 13:11 UTC, ihhub commented on src/fheroes2/heroes/route.cpp
> +}
At least this method can be inline. **GetFrontFrom()** is optional as it depends on cassert.

2023-07-31 13:18 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +        const int32_t formerBoatIdx = HeroesCastSummonBoat( hero, boatIdx );
Hi @ihhub this check is in `AIWorldPathfinder::reEvaluateIfNeeded()`. There is an additional check in the `HeroesActionNewPosition()` with an explanation why it needed (because hero can spend mana in the battles with wandering monsters during his movement). There is no such risk at the beginning of the movement, though.

2023-07-31 13:20 UTC, oleg-derevenetz commented on src/fheroes2/ai/ai.h
> +        virtual void HeroesFinishMovement( Heroes & hero );
@ihhub yes, it's just in case. I added it for a "balance" and can remove it if you wish.

2023-07-31 13:21 UTC, oleg-derevenetz commented on src/Makefile.vita
> +                                           -lmodplug -lmpg123 -lvorbisfile -lvorbis -lopusfile -lopus -logg -lxmp
@ihhub I'd better merge the latest changes (including this one) from `master` later today.

2023-07-31 13:22 UTC, ihhub commented on src/fheroes2/ai/ai.h
> +        virtual void HeroesFinishMovement( Heroes & hero );
Nah, we can keep it.

2023-07-31 13:27 UTC, ihhub commented on src/Makefile.vita
> +                                           -lmodplug -lmpg123 -lvorbisfile -lvorbis -lopusfile -lopus -logg -lxmp
Yes, absolutely. This is even better.

By the way I can add a special condition that each PR should be rebase from master before merging. This creates a special button in a PR to do this. However, I find this condition too aggressive for our development.

2023-07-31 13:28 UTC, ihhub commented on src/fheroes2/heroes/heroes_spell.cpp
> +        Interface::GameArea & gameArea = Interface::AdventureMap::Get().getGameArea();
Got it.

2023-07-31 13:28 UTC, oleg-derevenetz commented on src/fheroes2/ai/ai_hero_action.cpp
> +            gameArea.runSingleObjectAnimation( std::make_shared<Interface::ObjectFadingOutInfo>( tileSource.GetObjectUID(), boatSource, MP2::OBJ_BOAT ) );
@ihhub Maybe you right, but the fog may hide the boat only partially, so currently this logic is tied to the summoning hero. I can try to tie it to the boat itself instead.

2023-07-31 13:32 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +        const int32_t formerBoatIdx = HeroesCastSummonBoat( hero, boatIdx );
@ihhub also there is a corresponding assertion in the function that casts this spell just in case :)

2023-07-31 13:33 UTC, ihhub commented on src/fheroes2/ai/ai_hero_action.cpp
> +            gameArea.runSingleObjectAnimation( std::make_shared<Interface::ObjectFadingOutInfo>( tileSource.GetObjectUID(), boatSource, MP2::OBJ_BOAT ) );
I suggest at least to add a check with **tile.getFogDirection() != DIRECTION_ALL** Such a check would verify if the boat is indeed completely in fog.

2023-07-31 13:33 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +        const int32_t formerBoatIdx = HeroesCastSummonBoat( hero, boatIdx );
Sure. This work for me. Thank you!

2023-07-31 15:33 UTC, oleg-derevenetz commented on src/Makefile.vita
> +                                           -lmodplug -lmpg123 -lvorbisfile -lvorbis -lopusfile -lopus -logg -lxmp
@ihhub

> By the way I can add a special condition that each PR should be rebase from master before merging. This creates a special button in a PR to do this. However, I find this condition too aggressive for our development.

Yeah, if the PR author appears here only occasionally, we may have to wait for him to perform the sync even for basic PRs, which may be inconvenient.

2023-08-01 12:57 UTC, oleg-derevenetz commented
.

2023-08-02 12:51 UTC, ihhub approved these changes

2023-08-02 12:52 UTC, ihhub commented
Hi @drevoborod , could you please help to test changes in this pull request?

2023-08-02 12:52 UTC, ihhub commented
Hi @oleg-derevenetz , how confident you are about merging this pull request for 1.0.7 and what is against doing it?

2023-08-02 13:23 UTC, oleg-derevenetz commented
Hi @ihhub

> how confident you are about merging this pull request for 1.0.7 and what is against doing it?

We can do it if there is time to test it thoroughly.

2023-08-02 13:26 UTC, ihhub commented
@oleg-derevenetz , yes. That's why I asked @drevoborod for a help.

2023-08-02 19:54 UTC, drevoborod commented
Btw, method name "Heroes::isFreeman()" looks a bit like an easter egg :)
![изображение](https://github.com/ihhub/fheroes2/assets/10282847/7aa1df09-7052-43f7-90ab-ec1a9ceaac70)

2023-08-02 19:57 UTC, oleg-derevenetz commented
> Btw, method name "Heroes::isFreeman()" looks a bit like an easter egg :)

This is a historical method name inherited from the previous team :)

2023-08-02 21:31 UTC, oleg-derevenetz commented
OK, after some thought, I decided to do some renaming:

`Heroes::isFreeman()` -> `Heroes::isAvailableForHire()`;
`Heroes::SetFreeman()` -> `Heroes::Dismiss()`;
`AllHeroes::GetFreeman()` -> `AllHeroes::GetHeroForHire()`;
`World::GetFreemanHeroes()` -> `World::GetHeroForHire()`.

This also has the advantage that there will be no confusion with use the old names in those PRs that have not yet been merged.

2023-08-03 07:36 UTC, oleg-derevenetz commented
@drevoborod

> because it's about many heroES

No, it's about just one hero. Another remnant from the previous team.


> what range should summon boat have? Seems like it's unlimited, right?

Yes, there is no limit for a distance to the boat being summoned. You are able summon a boat even from the other end of the map.

2023-08-03 17:30 UTC, drevoborod commented
For me everything seems OK. AI uses the spell in a quite adequate way.

2023-08-03 18:03 UTC, oleg-derevenetz commented
@drevoborod

> For me everything seems OK. AI uses the spell in a quite adequate way.

Thank you very much!

@ihhub I believe we can merge this PR, and if we see any issues on maps designed by their authors without taking into account the AI's ability to cast the Summon Boat spell, then we can always implement the @Branikolog's proposal and prohibit summoning neutral boats by AI, that would be a trivial change.

2023-08-05 03:37 UTC, merged

2023-08-05 03:37 UTC, ihhub commented
@oleg-derevenetz , awesome work!