Allow early exit from puzzle map during reveal
ihhub/fheroes2 pull request #7487
Opened 2023-07-28 20:35 UTC by Kazhuu

Solves https://github.com/ihhub/fheroes2/issues/7448 by allowing exiting puzzle map during reveal animation.

2023-07-29 09:58 UTC, Kazhuu commented
It seems Vita build is broken at the moment?

2023-07-29 11:38 UTC, oleg-derevenetz commented
> It seems Vita build is broken at the moment?

Please see #7486.

2023-07-31 13:14 UTC, ihhub requested changes
Hi @Kazhuu , I left a suggestion regarding the proposed approach. Would you mind to take a look?

2023-07-31 13:14 UTC, ihhub commented on src/fheroes2/kingdom/puzzle.cpp
> +    void revealPuzzle( const Puzzle & pzl, const fheroes2::Image & sf, int32_t dstx, int32_t dsty, fheroes2::Button & buttonExit,
Would it be better to just return true or false from this function and then check the return value from the place where we call the function? Passing information from a caller of a function to the function must be the last resort.

2023-07-31 19:40 UTC, Kazhuu commented
> Hi @Kazhuu , I left a suggestion regarding the proposed approach. Would you mind to take a look?

Okay I returned the first implementation with boolean return variable. Can you @ihhub take a look?

2023-08-02 13:34 UTC, ihhub commented on src/fheroes2/kingdom/puzzle.cpp
> +        return false;
I recommend to add an empty line before this return to have a visual separation of the code parts.

2023-08-02 18:02 UTC, Kazhuu commented
Hello @ihhub I was thinking because this version also need to pass exit button as a parameter, like you mentioned is not good. But do you think actually returning boolean value adds more code on the caller side and makes the code more complicated? Would you reconsider the implementation where the `revealPuzzle` function takes care of the exit button handling. Then I can remove those two while loops from the caller side. What do you think?

2023-08-05 19:30 UTC, Kazhuu commented
Hello @ihhub I made the changes you requested. Can you have a look again, thanks!

2023-08-16 15:08 UTC, ihhub approved these changes

2023-08-21 01:41 UTC, merged

2023-08-21 01:41 UTC, ihhub commented
@Kazhuu , big thanks for this change!