Remember map filter selection until you quit the game
ihhub/fheroes2 pull request #7490
Opened 2023-07-29 19:19 UTC by Kazhuu

Solves https://github.com/ihhub/fheroes2/issues/6888 by storing current map filter selection filter and applying it again when selection a scenario. Remember until you quit the game.

2023-07-31 13:25 UTC, ihhub requested changes
Hi @Kazhuu , I put 2 comments here. Could you please check them?

2023-07-31 13:25 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +                settings.setCurrentMapFilter( Maps::SMALL );
Since this is only UI related issue please keep the change only within UI space. Settings class are designed to store permanent information. As a solution just declare a separate variable within this file in anonymous namespace and use it as storage to memorize the selection.

2023-07-31 13:25 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    currentPressedButton->press();
We don't need **currentPressedButton** variable here. We can directly call **press();** method for each case.

2023-07-31 18:53 UTC, Kazhuu commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +    currentPressedButton->press();
Not sure did you mean that you call `press()` in each case or I remove the whole variable. I did the latter now.

2023-07-31 18:53 UTC, Kazhuu commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +                settings.setCurrentMapFilter( Maps::SMALL );
Yeah good idea :+1:

2023-07-31 18:54 UTC, Kazhuu commented
> Hi @Kazhuu , I put 2 comments here. Could you please check them?

I did the fixes and also I found a crash which I also fixed. When you select M size map for example in single player. Then go to multiplayer with 6 players, the game crashed. Now if the map list is empty, then default to all filter instead.

2023-08-02 13:22 UTC, ihhub requested changes
Hi @Kazhuu , I put few more comments here. Could you please take a look at them when you have time?

2023-08-02 13:22 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
>      listbox.SetCurrent( GetInitialMapId( all ) );
I suggest to add an empty line here for slightly better readability.

2023-08-02 13:22 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +            listbox.SelectMapSize( all, Maps::ZERO );
Should we change **currentMapFilter** value to `Maps::ZERO` here as well as in other places?

2023-08-02 13:22 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +                buttonSelectSmall.drawOnPress();
Please verify this situation:
1. You have no S size maps
2. You select XL maps
3. You press S size button

I suspect that S size button would be in a pressed state which is wrong. If this is the case please revert changes for **SwitchPressedMapSizeButtons** usage which was actually introduced in order to remember the last successful selection.

2023-08-05 19:47 UTC, Kazhuu commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +                buttonSelectSmall.drawOnPress();
Yes that was indeed the case. I reverted this.

2023-08-05 19:47 UTC, Kazhuu commented
Hello @ihhub! I did the requested changes. Can you check again?

2023-08-16 15:07 UTC, ihhub approved these changes

2023-08-21 01:39 UTC, merged

2023-08-21 01:40 UTC, ihhub commented
@Kazhuu , thank you so much for this improvement!