Prepare the code for the future AI resource trading logic
ihhub/fheroes2 pull request #7506
Opened 2023-08-02 14:12 UTC by ihhub

I haven't figured out how to make it the AI to use trading post efficiently so these changes are a basis for any future changes related to AI resource trading logic.

2023-08-10 17:10 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left one question and one minor suggestion. Could you please take a look when you have time?

2023-08-10 17:10 UTC, oleg-derevenetz commented on src/fheroes2/kingdom/resource_trading.cpp
> +            // What are trying to archive?
Possibly typo?

```suggestion
            // What are we trying to achieve?
```

2023-08-11 01:24 UTC, idshibanov approved these changes
> I haven't figured out how to make it the AI to use trading post efficiently

I can make the change once you merge this PR in. I agree with Oleg's comment though.

2023-08-11 14:30 UTC, ihhub commented on src/fheroes2/ai/ai.h
> +        virtual void tradingPostVisitEvent( Kingdom & kingdom ) = 0;
Hi @oleg-derevenetz , we have 2 ways:
- we put the whole AI logic for trading post within `ai_hero_action.cpp`. In this case we need to know the exact amount of resources to trade from and to to avoid any logic inside
- create a function which does logic upon visiting a trading post

I don't have a strong opinion which way is better but to move forward with my changes I am okay to revert changes related to AI in general.

2023-08-11 18:56 UTC, oleg-derevenetz approved these changes

2023-08-11 23:36 UTC, idshibanov commented on src/fheroes2/ai/ai.h
> +        virtual void tradingPostVisitEvent( Kingdom & kingdom ) = 0;
You can leave it in.

2023-08-12 01:32 UTC, merged