Make various EXIT, the well's MAX and some leftover buttons translatable and fix the castle EXIT button
ihhub/fheroes2 pull request #7515
Opened 2023-08-05 23:45 UTC by zenseii

This fixes the issues with EXIT buttons in the Puzzle, Dimension Door, Heroes Meeting, Town screens, and translates buttons found in buying a boat dialog, and the MAX button in the Well.

Fix #7461
Relates to #7496

Part of #6105

2023-08-07 11:23 UTC, Districh-ru approved these changes
Well done, @zenseii!

![изображение](https://github.com/ihhub/fheroes2/assets/113276641/86d0e006-6457-453f-bc97-4703287926cf) 
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/a9457640-df18-4deb-93be-4a7b264cd4de) 
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/d19a7e38-31a7-4428-86f8-e754bc1b1d80) ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/88f1ec79-87aa-40cb-a0ee-deb8f399a07f)

2023-08-08 11:12 UTC, ihhub requested changes
Hi @zenseii , I left few comments here. Could you please check them?

2023-08-08 11:12 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                _icnVsSprite[id].resize( 2 );
Please cache **_icnVsSprite[id]** for better performance and readability.

2023-08-08 11:12 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                                    isEvilInterface ? fheroes2::FontColor::GRAY : fheroes2::FontColor::WHITE );
Please either make **releasedOffset** and **pressedOffset** const (you can remove `=`) or just directly use { 6, 5 } and { 5, 6 } in the call below.

2023-08-08 11:12 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                                    { textWidth, fheroes2::getFontHeight( fheroes2::FontSize::BUTTON_RELEASED ) }, fheroes2::FontColor::WHITE );
Please either make **releasedOffset** and **pressedOffset** const (you can remove `=`) or just directly use { 7, 5 } and { 6, 6 } in the call below.

2023-08-08 16:12 UTC, ihhub approved these changes

2023-08-08 16:12 UTC, merged

2023-08-08 16:12 UTC, ihhub commented
@zenseii , thank you so much for these improvements!