Fix Army info button in level up dialog
ihhub/fheroes2 pull request #7519
Opened 2023-08-06 16:29 UTC by zenseii

Credits to @Districh-ru for the solution.

We have to use the `Copy()` function to avoid the `_singleLayer` attribute to be set to true, because this happens when you just use the `=-operator` since the regular Army button is rightly set to be single layered after the PR #7449

Fix #7514

2023-08-06 17:03 UTC, LeHerosInconnu commented
Hello @zenseii,

> Hi, @LeHerosInconnu. Could you please verify if this fixes the problem with the button?

I did a quick test with this save file: [Hero button 01.zip](https://github.com/ihhub/fheroes2/files/12267534/Hero.button.01.zip), and it works fine.

2023-08-06 17:05 UTC, Districh-ru requested changes
Hi, @zenseii, I left a couple of comments. Could you take a look when you have time.
And we also have to fix this button for the Evil interface the same way at these lines:
https://github.com/ihhub/fheroes2/blob/13c5cf9bd6ab784a8eaac208b8040cb095786985/src/fheroes2/agg/agg_image.cpp#L3180-L3181

2023-08-06 17:24 UTC, Districh-ru approved these changes
Well done!
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/e8995105-744e-4e25-92ad-4583087e19fb) ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/23819169-202c-4204-933d-187d6bc00b17)

2023-08-08 08:28 UTC, ihhub approved these changes

2023-08-08 08:28 UTC, merged

2023-08-08 08:28 UTC, ihhub commented
@zenseii , thank you so much for the fix!