Implement basic terrain draw in Map Editor (currently without terrain connections)
ihhub/fheroes2 pull request #7521
Opened 2023-08-06 17:58 UTC by Districh-ru

Relates to #6845

This PR adds Editor ability to place (draw) specified terrain on a map by 1x1, 2x2 or 4x4 brush or by selecting a rectangle area on map.
Terrain interconnections are not implemented in this PR and they will be done in one of the next Editor related PRs.
Currently you cannot hold mouse button and draw withe selected brush by moving the cursor as it is done in original Editor, jus one draw in the selected area by one mouse click. This function will be implemented after the implementation of terrain interconnection.

https://github.com/ihhub/fheroes2/assets/113276641/4cb8e4e7-d937-46d4-94fd-f41c8041ee53

2023-08-09 15:59 UTC, ihhub requested changes
Hi @Districh-ru , I left few comments in this pull request. Would you mind to take a look when you have free time?

2023-08-09 15:59 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +    int32_t brushAreaEndIndex( const int32_t brushSize, const int32_t startIndex )
Let's name it as **getBrushAreaEndIndex** to be more accurate about the function.

2023-08-09 15:59 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +                    }
Is there a valid scenario when **brushSize == 0** and **!_editorPanel.isAreaSelect()**? If not then we shouldn't check for **_editorPanel.isAreaSelect()**. According to the logic no harm to check **brushSize >= 0** as `brushAreaEndIndex` will always return the same tile id.

The same for line 543.

2023-08-09 15:59 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +                if ( !_gameArea.isDragScroll() && ( !_editorPanel.isAreaSelect() || _selectedTile == -1 ) ) {
I would suggest to at least add a TODO as later we are going to add objects and other things. This would help to remember to update this place.

2023-08-09 15:59 UTC, ihhub commented on src/fheroes2/editor/editor_interface.h
> +        bool useMouseDragMovment() override
**Movment** is misspelled.

2023-08-09 15:59 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            assert( 0 );
Please add break here just for the sake of good style practices.

2023-08-09 15:59 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.h
> +        bool isAreaSelect() const
I recommend to be more specific and include terrain word into the name as it is not obvious what kind of area it is.

2023-08-09 15:59 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.h
> +        }
Please add empty lines in between method for visual separation.

2023-08-09 15:59 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            return -1;
Would it be better to just return 0 together with default so the logic for (if any in the future) any new brush size would be still area rather than trying to handle 0-size areas?

Then the logic for line 120-125 would be much simplier.

2023-08-09 15:59 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.h
> +            _terrainFlags = static_cast<uint8_t>( verticalFlip ) + 2 * static_cast<uint8_t>( horizontalFlip );
Please do not use mathematical operations on boolean variables. While in theory a boolean variable should contain 0 or 1, in reality it depends :) I suggest to do this way:
```cpp
_terrainFlags = ( verticalFlip ? : 1 : 0 ) + ( horizontalFlip ? 2 : 0 );
```

2023-08-09 15:59 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +        }
Let's add a check for map size as well. It would be a case when **startTileId** or **endTileId** are beyond the map size.

2023-08-09 15:59 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.h
> +        void setTerrainImage( const uint16_t terrainImageIndex, const bool horizontalFlip, const bool verticalFlip )
Essential we don't set a terrain image here but terrain type / information. Should we just name it as **setTerrain**?

2023-08-09 15:59 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +void Interface::GameArea::renderTileCursor( fheroes2::Image & dst, const int32_t startTile, const int32_t endTile ) const
It is not a cursor but highlighted area / active area / selected area. **renderTileCursor** might be interpret as `call this function to render a cursor of a tile`.

2023-08-09 17:39 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +    int32_t brushAreaEndIndex( const int32_t brushSize, const int32_t startIndex )
Hi, @ihhub, sure!

2023-08-09 17:42 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +                    }
Yes, it is not a valid scenario right now and possibly ever.
I removed the `isAreaSelect()` method and now `brushSize == 0` will be for the tile area select.

2023-08-09 17:42 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +                if ( !_gameArea.isDragScroll() && ( !_editorPanel.isAreaSelect() || _selectedTile == -1 ) ) {
OK.

2023-08-09 17:42 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.h
> +        bool useMouseDragMovment() override
Thanks!

2023-08-09 17:43 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            assert( 0 );
Sure. :)

2023-08-09 17:45 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.h
> +        bool isAreaSelect() const
This method is not used anymore, but in future we will select an area to clear the objects using this logic for area selection. So if we will restore it in the future we will call it `isTileAreaSelect()`.

2023-08-09 17:47 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            return -1;
For Area Select we will return 0, but for the default I'll leave the assertion as if we will add a new brush size we will have to make aтв test the logic for it.

2023-08-09 17:48 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles.h
> +            _terrainFlags = static_cast<uint8_t>( verticalFlip ) + 2 * static_cast<uint8_t>( horizontalFlip );
Thanks!
I will take this into account in the future.

2023-08-09 17:51 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles.h
> +        void setTerrainImage( const uint16_t terrainImageIndex, const bool horizontalFlip, const bool verticalFlip )
OK.

2023-08-09 17:53 UTC, Districh-ru commented on src/fheroes2/gui/interface_gamearea.cpp
> +void Interface::GameArea::renderTileCursor( fheroes2::Image & dst, const int32_t startTile, const int32_t endTile ) const
Yes, lets name it `renderTileAreaSelect()` as we render the selection of map tiles (in this PR for filling the terrain).

2023-08-10 14:20 UTC, ihhub approved these changes

2023-08-10 14:20 UTC, ihhub commented
Hi @drevoborod , could you please also test this pull request as well?

2023-08-12 10:56 UTC, Branikolog commented
Hi, @Districh-ru !
Terrain generation works fine!
I've only caught some minor UI bugs.
Adventure map frame is not rendered correctly for my selected custom 976x550 resolution:
![frame corner](https://github.com/ihhub/fheroes2/assets/55348946/1fc784e8-5eaf-45f3-940d-36bf9c014e44)

144x144 button has 2px text shift on pressed state:
![ezgif com-resize (2)](https://github.com/ihhub/fheroes2/assets/55348946/8e8626e8-af7c-45ef-92e1-8c2acde3665c)

2023-08-12 11:06 UTC, ihhub commented
Hi @Branikolog and @Districh-ru , font related things we should fix in a separate pull request.

2023-08-12 11:27 UTC, Districh-ru commented
> Hi, @Districh-ru ! Terrain generation works fine! I've only caught some minor UI bugs. Adventure map frame is not rendered correctly for my selected custom 976x550 resolution: 

Hi, @Branikolog, this bug will be addressed later. There is a TODO in `editor_interface.cpp` near the Status window redraw call.
First we will modernize this Status window to display Editor related info. And then we will adopt it to the interface.

> 144x144 button has 2px horizontal text shift on pressed state:

Currently we use the resources form original game assets. Later we may make these buttons to have generated text or use a dialog instead of the menu to set the map size (as in future we may plan to have more than four original map sizes, e.g. like it is done in HoMM3: HotA map editor). So let's address it later after we make the new map format.

2023-08-12 11:31 UTC, Branikolog approved these changes
Glad to hear that, @Districh-ru !

2023-08-16 01:44 UTC, merged

2023-08-16 01:44 UTC, ihhub commented
@Districh-ru , huge thanks for this improvement!