Rework the "select from list" dialogs used in Battle only mode to use them in Editor in future
ihhub/fheroes2 pull request #7522
Opened 2023-08-06 19:24 UTC by Districh-ru

Relates to https://github.com/ihhub/fheroes2/issues/6845 as these "select from list" dialogs are proposed to use in Map Editor to select map objects, edit a hero, ... 

This PR implements generation of the text background for `StandardWindow` class. This will allow to make a shaded text background of any size for use in dialog boxes (for example, redesign the Save/Load dialog to allow more files in the list and display longer filenames).

This PR fixes some issues of https://github.com/ihhub/fheroes2/issues/4352:
- use background, scrollbar and buttons for the selected interface type ( Good / Evil );
- cut long phrases with "..." at the and not to overlap the scrollbar;
- add shadows to OKAY and CANCEL buttons (and the scrollbar).

This PR also fixes:
- add the right click info window for all current list types;
- redraw delay after pressing CANCEL in Select Secondary Skill dialog;
- possible rendering bug of scrollbar image restorer when closing dialog (which has its own image restorer, like "Standard Window") with the scroll bar on it. (This issue cloud be observed before the previous redraw issue was fixed.)
- the vertical size and the count of shown list elements are calculated from the current screen height.

<details><summary>Screenshots:</summary>

![1](https://github.com/ihhub/fheroes2/assets/113276641/9314c264-b02a-4ec2-b315-7436b5590fc8)
![2](https://github.com/ihhub/fheroes2/assets/113276641/f5824eb8-f2e1-4c34-872a-1db34471f6e4)
![3](https://github.com/ihhub/fheroes2/assets/113276641/9c2d7b03-dac2-45be-820c-7e5a426c8318)
![4](https://github.com/ihhub/fheroes2/assets/113276641/8cf1ab6e-316d-4a87-b7b6-3e2fcc7e8853)

</details>

2023-08-10 09:33 UTC, Districh-ru commented on src/fheroes2/gui/ui_scrollbar.h
> +            // We need to reset the ImageRestorer for the scroll bar to avoid its restoration by destructor and possible race with th dialog window restorer.
Hi @zenseii, thanks for the spell check!

https://github.com/ihhub/fheroes2/issues/7534 issue will be addressed later - we should exclude already used skills (and heroes) from the list in list constructor, e.g. by passing it a vector of already used skills.

2023-08-10 11:09 UTC, Districh-ru commented
> Well done! I see that the builds have failed. Not sure why.

This PR https://github.com/ihhub/fheroes2/pull/7532 should fix Linux build issues.

2023-08-10 13:41 UTC, Branikolog commented
Hi, @Districh-ru !
Everything is fine except text alignment in lists.
![text2](https://github.com/ihhub/fheroes2/assets/55348946/75e867ee-9f6f-40fd-89ce-ab84c816c1e1)
![text1](https://github.com/ihhub/fheroes2/assets/55348946/94ca4233-6d42-4bb8-9ce2-603b83236520)

2023-08-10 14:55 UTC, Districh-ru commented
Hi, @Branikolog, thanks for noticing this! Done.
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/287119aa-b7bf-4d48-800b-b65f1d70d931) ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/a098a3e2-9c84-4569-80e0-7f9ecea541e2)

2023-08-11 10:45 UTC, Branikolog approved these changes

2023-08-12 02:08 UTC, ihhub requested changes
Hi @Districh-ru , I left few small suggestions here. Would you mind to take a look at them?

2023-08-12 02:08 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +        }
Here we have a check for an empty unique pointer while we don't have such check for **background** in the code below. I suggest to delete default constructor forcing to use the defined constructor. In this case it is guaranteed that both unique pointers are initialized (std::make_unique will throw an exception if it is not the case).

What do you think?

2023-08-12 02:08 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +        constexpr int offset = 42;
**constexpr** is not useful for variables like this. Compiler will not optimize them. It is useful for expressions / formulas to be calculated during compilation.

2023-08-12 02:08 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    }
I think you would like to use **std::iota** for the same purpose.

2023-08-12 02:08 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    }
In the code above we used **for ( int i = 0; i < MAXSECONDARYSKILL * 3; ++i ) {** while here we rely on vector size. Let's be consistent :)

2023-08-12 02:08 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.h
> +    Artifact selectArtifact();
Nothing to do here: it is interesting that this function doesn't have a default parameter.

2023-08-12 09:03 UTC, Districh-ru commented on src/fheroes2/gui/ui_window.cpp
> +        fheroes2::Rect shadingRoi = roi ^ _activeArea;
Hi @ihhub, sure.

2023-08-12 09:03 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +        }
Yes, let's disable the default constructor so we don't need to check `listBackground` and `background` for `nullptr`.

2023-08-12 09:03 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +        constexpr int offset = 42;
Thanks for the explanation!

2023-08-12 09:04 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    }
Sure, thanks for the suggestion
Currently we may use it, but in future to address https://github.com/ihhub/fheroes2/issues/7534 we should pass a vector of skills to exclude and skip them (using `continue;`) in such loop. (Or we may find a better solution.)

2023-08-12 09:04 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    }
OK :)
Now all such loops are replaced with `std::iota()`.

2023-08-12 09:05 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.h
> +    Artifact selectArtifact();
Initially this functions and `selectSecondarySkill()` had no default parameters, but lets be consistent for future use (e.g. for selecting the existing artifact/skill and changing it in Editor).

2023-08-12 09:27 UTC, ihhub approved these changes

2023-08-12 09:27 UTC, merged

2023-08-12 09:27 UTC, ihhub commented
@Districh-ru , great job!