Creating the branch
ihhub/fheroes2 pull request #7540
Opened 2023-08-12 07:19 UTC by Stisen1

I am just creating the branch for now. Changes will come later

2023-08-18 07:20 UTC, Stisen1 commented
This PR is ready to be reviewed.

2023-08-18 08:50 UTC, Stisen1 commented on files/lang/dk.po
> +
Done

2023-08-18 08:51 UTC, Stisen1 commented on files/lang/dk.po
> +msgstr ""
Done

2023-08-18 08:55 UTC, Stisen1 commented on files/lang/dk.po
> +#, fuzzy
Donno. I have no idea what "Fuzzy?" is supposed to mean. The program makes it happen for some reason... This one might have been copied from a further developed dk.po file though, that already has been through the analyzer...

2023-08-18 08:55 UTC, Stisen1 commented on files/lang/dk.po
> +#, fuzzy
Removed

2023-08-18 08:57 UTC, Stisen1 commented on files/lang/dk.po
> +"Der er nogle få trolde tilbage. som kryber sammen under broen. De henvender "
Done

2023-08-18 08:58 UTC, Stisen1 commented on files/lang/dk.po
> +"Da du går ind i en bygning af hvide stensøjler, men du finder intet af værdi."
.... Only if you want the sentence to be invalid... "Da" has been removed.

2023-08-18 09:01 UTC, Stisen1 commented on files/lang/dk.po
> +"bevogtet af en nærliggende %{monster}. Vil du kæmpe mod %{monster}en for at "
Your right. It has been changed to something else, that now works for all the possible forms.

2023-08-18 09:10 UTC, Stisen1 commented on files/lang/dk.po
> +#, fuzzy
Well that sure is nice to know after spending 50+ hours on translating the game ;-)

2023-08-19 15:53 UTC, ihhub requested changes
Hi @Stisen1 , I put several comments in this pull request. Would you mind to take a look at them?

2023-08-19 15:53 UTC, ihhub commented on files/lang/dk.po
> +"du den og finder %{guld} guldstykker."
Misspelled **%{gold}**. This is not a translatable part of the text.

2023-08-19 15:53 UTC, ihhub commented on files/lang/dk.po
> +"indeholder %{guld} guldstykker."
Misspelled **%{gold}**. This is not a translatable part of the text.

2023-08-19 15:53 UTC, ihhub commented on files/lang/dk.po
> +"Alle de %{monstre}, du har i din hær, er blevet trænet af fortets "
Misspelled **%{monsters}**. This is not a translatable part of the text.

2023-08-19 19:11 UTC, Stisen1 commented on files/lang/dk.po
> +"Alle de %{monstre}, du har i din hær, er blevet trænet af fortets "
Done

2023-08-19 19:11 UTC, Stisen1 commented on files/lang/dk.po
> +"indeholder %{guld} guldstykker."
Done

2023-08-19 19:11 UTC, Stisen1 commented on files/lang/dk.po
> +"du den og finder %{guld} guldstykker."
Done

2023-08-21 02:31 UTC, ihhub approved these changes

2023-08-21 02:32 UTC, merged

2023-08-21 02:32 UTC, ihhub commented
@Stisen1 , thank you very much for the update!