AI should decline battles if passing by
ihhub/fheroes2 pull request #7553
Opened 2023-08-12 20:37 UTC by idshibanov

Fixes #7503 .

Had to expose HeroesValidObject call otherwise AI might choose to go to the Pyramid willingly and then decline the battle.

2023-08-13 17:32 UTC, oleg-derevenetz commented
Hi @idshibanov what do you think about making a minimal wrapper method in the `AI::Base`/`AI::Normal` classes that will take only necessary parameters and call the existing `HeroesValidObject()` method that will remain in the anonymous namespace? This would keep the necessary changes minimal.

2023-08-15 20:07 UTC, oleg-derevenetz commented
Hi @idshibanov I just integrated my `AIWorldPathfinder`-related changes in this PR, so we can get the best of the two approaches.

2023-08-15 20:35 UTC, idshibanov commented
> Hi @idshibanov I just integrated my `AIWorldPathfinder`-related changes into this PR, so we can get the best of the both approaches.

Updated and reverted the ValidObject changes. Should be good to go now.

2023-08-16 00:01 UTC, oleg-derevenetz commented
> Updated and reverted the ValidObject changes. Should be good to go now.

Yes, thank you! I just added a bit of minor changes:

* Call the `isValidHeroObject()` using the shortcut logic, i.e. `if (!isValidHeroObject(...)) return;`. Since `HeroesValidObject()` validates not just the army advantage, but also the utility of the object (e.g. whether it contains something useful), I don't see a reason not to use this validation;
* Added the ability to avoid visiting several more types of objects - objects that can offer recruits after fight (e.g. Troll Bridge) and Abandoned Mine;
* I slightly reworked the logging of the actions of the heroes (I wanted to do it for a long time). Previously, logging of an action for some reason was performed at its end, which looked weird, especially if something else was logged during the same action. Now logging of an action is performed at its beginning.

I'll do a couple more tests tomorrow.

2023-08-16 09:32 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> -                return -valueToIgnore;
Because of this typo, AI was a big fun of empty water chests, flotsams, etc - it might even prefer them to an empty enemy castle :)

2023-08-18 00:26 UTC, ihhub requested changes
Hi @idshibanov , I left one suggestion here. Could you please take a look?

2023-08-18 00:26 UTC, ihhub commented on src/fheroes2/ai/ai.h
> +        virtual bool isValidHeroObject( const Heroes & hero, const int32_t index, const bool underHero = false ) = 0;
Please do not use default parameters for virtual functions. You can take a look [here](https://stackoverflow.com/questions/3533589/can-virtual-functions-have-default-parameters) for an explanation.

2023-08-18 00:26 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> -                return -valueToIgnore;
Oops...

2023-08-18 02:36 UTC, ihhub approved these changes

2023-08-18 03:25 UTC, merged

2023-08-18 03:26 UTC, ihhub commented
@idshibanov and @oleg-derevenetz , thank you so much for the change!