Make vertical buttons translatable
ihhub/fheroes2 pull request #7582
Opened 2023-08-20 22:53 UTC by zenseii

This makes the vertical DISMISS and EXIT buttons in the hero screen translatable.

![image](https://github.com/ihhub/fheroes2/assets/12501091/e3566d8d-9f45-4eb3-9b60-7f8a576cad69)

2023-09-03 08:58 UTC, Districh-ru requested changes
Hi, @zenseii, I left several comments to the code. Could you please take a look in your spare time.

Also comparing original buttons to the new ones I noticed that the text vertical spacing is 1 pixel smaller in original buttons:
new (16px) <-> original (15px)
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/5294cc08-bcaa-408b-bcca-c020b284ca71) <->  ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/cfef278e-607b-4bfa-ab35-94cbd0ea648d)

Analyzing the main menu buttons I found the same difference:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/034e1486-c045-476f-8b2c-e02cca7ad711) <-> ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/a9d9ada8-b463-4d8f-b218-55dccd32dd77)


Maybe we should change the return value to 15 here:
https://github.com/ihhub/fheroes2/blob/edd2ca7b08b5b89b4c7cafa28b969e6e8aa90a91/src/fheroes2/gui/ui_text.cpp#L483

What do you think?

2023-09-03 08:58 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                    Copy( originalPressed, 9, 5, _icnVsSprite[id][1], 3, 5, 19, 111 );
For original EXIT button we need to use 2 and 3 image index and use different X offsets in these images when performing `Copy()`

```suggestion
                    const Sprite & originalReleased = GetICN( ICN::HSBTNS, 2 );
                    const Sprite & originalPressed = GetICN( ICN::HSBTNS, 3 );

                    Copy( originalReleased, 4, 2, _icnVsSprite[id][0], 4, 2, 21, 112 );
                    Copy( originalPressed, 3, 5, _icnVsSprite[id][1], 3, 5, 19, 111 );
```

2023-09-03 08:58 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                    FillTransform( released, released.width() - 3, released.height() - 1, 1, 1, 1 );
We can use `setButtonCornersTransparent( released );` here. It does the same for the released button. :)
In future we can also modify this function to make transparent corners for the pressed buttons (we can leave a TODO).

2023-09-03 08:58 UTC, Districh-ru commented on src/fheroes2/gui/ui_button.cpp
> +        const int32_t textWidth = releasedText.width( releasedText.width() );
In this line we are trying to get the width of `releasedText`, which is limited to the width of the same `releasedText`.
Maybe there is a typo here? :)

2023-09-03 09:42 UTC, Districh-ru commented on src/fheroes2/gui/ui_button.cpp
> +        const int32_t textWidth = releasedText.width( releasedText.width() );
We can currently use the `maximumTextAreaWidth` variable here (`const int32_t textWidth = releasedText.width( maximumTextAreaWidth );`) not to call the `.width()` method.

2023-09-03 10:08 UTC, Districh-ru commented on src/fheroes2/gui/ui_button.cpp
> +        const int32_t textWidth = releasedText.width( releasedText.width() );
Could you please add a TODO above `width()` and `height()` methods in ui_text.cpp (lines 509 and 514). Something like: "Properly handle strings with many text lines ('\n')".

2023-09-03 15:08 UTC, ihhub approved these changes
Hi @zenseii , everything looks good to me. I left 2 optional comments. Please ignore them if you think they are useless.

2023-09-03 15:08 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +    class ButtonFontRestorer
To be more accurate would it better to name this class as **ButtonFontOffsetRestorer**?

2023-09-03 15:08 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +        _originalXOffsets.reserve( _font.size() );
Just a very tiny nitpicking: here we use **_font** variable but a line lower we use **font**. It's better to be persistent :)

2023-09-03 15:47 UTC, Districh-ru approved these changes
Well done, @zenseii !

2023-09-03 16:12 UTC, Districh-ru approved these changes
👍

2023-09-04 01:13 UTC, ihhub approved these changes

2023-09-04 01:13 UTC, merged

2023-09-04 01:14 UTC, ihhub commented
@zenseii , great work!