Implement terrain transitions in Editor.
ihhub/fheroes2 pull request #7596
Opened 2023-08-21 15:22 UTC by Districh-ru

Relates to https://github.com/ihhub/fheroes2/issues/6845

This PR implements connection of nearby terrains by applying appropriate tile images.

https://github.com/ihhub/fheroes2/assets/113276641/3ce9775e-7477-4108-8810-dc27bdf2895b

There could be "incorrect" tiles when they cannot be properly connected (with transition) with the nearby terrains. This issue is not fully fixed in this PR and needs more polishing (which possibly should be done in one of the next PRs). :(

2023-08-22 14:10 UTC, ihhub requested changes
Hi @Districh-ru , I left several comments here. Would you mind please to check them?

2023-08-22 14:10 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +        if ( groundDirection == ( Direction::TOP_RIGHT | Direction::TOP | DIRECTION_BOTTOM_ROW | DIRECTION_CENTER_ROW ) ) {
For better code readability I suggest to cache **world.GetTiles( tileId )** just after the first if-body.

2023-08-22 14:10 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +            // Beach tile images does not have transition with the other terrains.
images **do** - plural form.

2023-08-22 16:17 UTC, Districh-ru commented on src/fheroes2/maps/ground.cpp
> +uint16_t Maps::Ground::getTerrainIageOffset( const int groundId )
Hi @ihhub, thanks!
I thought about such renaming and implementing `getTerrainEndImageIndex()`, but later decided not to introduce this new function.

2023-08-22 16:18 UTC, Districh-ru commented on src/fheroes2/maps/maps.cpp
> +        break;
Yes, this is not a valid case, in this case function returns {-1,0} (like the upper one function returns index = -1). But for debugging purposes it is better to add an assertion. :)

2023-08-22 16:19 UTC, Districh-ru commented on src/fheroes2/maps/maps.cpp
> +fheroes2::Point Maps::getDirectionPoint( const fheroes2::Point & from, int vector )
Sure.
I'll also update this name in the upper function.

2023-08-22 16:20 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +    inline bool hasBits( const int value, const int bits )
Sure, let's leave this optimization to the compilers. :)

2023-08-22 16:22 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +        for ( const int & direction : Direction::All() ) {
`getAroundIndexes()` skips indexes that are out or map boundaries while here we need to treat the nearby indexes for this case to get proper ground transitions on map edges.
Also we need to accumulate the directions while `getAroundIndexes()` returns indexes that should be converted into directions.

2023-08-22 16:28 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +        if ( groundDirection == ( Direction::TOP_RIGHT | Direction::TOP | DIRECTION_BOTTOM_ROW | DIRECTION_CENTER_ROW ) ) {
Sure)

2023-08-22 16:28 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +            // Beach tile images does not have transition with the other terrains.
Oh, sorry...

2023-08-22 16:45 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +        for ( const int & direction : Direction::All() ) {
But I'll use it in `updateTerrainTransitionOnArea()`.
Thanks for the suggestion!

2023-08-23 03:35 UTC, ihhub approved these changes

2023-08-24 01:20 UTC, ihhub commented
Hi @drevoborod , can you please help to test these changes?

2023-08-24 11:18 UTC, Branikolog commented
Hi, @Districh-ru !
I've tested this PR and find several issues.
Overall, I like how editor works now. You've done a great job!

https://github.com/ihhub/fheroes2/assets/55348946/4eba39cd-cea8-49aa-a267-d816b29715b9

https://github.com/ihhub/fheroes2/assets/55348946/1fe236fa-7375-4c5d-8fdc-d64191030289

https://github.com/ihhub/fheroes2/assets/55348946/f4ee47aa-87a3-4cd0-b09a-35d970c6fd01

https://github.com/ihhub/fheroes2/assets/55348946/32cfaf7c-8afb-4d91-a593-a2e72613cad2

https://github.com/ihhub/fheroes2/assets/55348946/ec1e50a6-5638-4919-ba04-ff4b62681662

https://github.com/ihhub/fheroes2/assets/55348946/152a2f47-6588-478a-be5f-d8596b50253e

https://github.com/ihhub/fheroes2/assets/55348946/57b80a94-6683-4dab-8b62-c33bc330a420

https://github.com/ihhub/fheroes2/assets/55348946/378849b8-7885-4bdf-b7f5-bca25928a30d

2023-08-24 11:27 UTC, Branikolog commented
The smallest brush is not working properly. I know, it will work better, when drag-to-paint will be implemented, but for now it sometimes creates a terrain, which is not selected, like water.

https://github.com/ihhub/fheroes2/assets/55348946/551b2c51-0279-4ddd-8b06-114c64d6e16d

2023-08-24 11:32 UTC, Districh-ru commented
Hi, @Branikolog, thanks for testing and for videos!
I'll try to fix most of the found issues in the next days.

2023-08-24 18:19 UTC, Districh-ru commented
Fixed issues on videos 5 and 9. Implemented behavior like in HotA map editor as it looks better. :)
<details><summary>Screenshot</summary>

![изображение](https://github.com/ihhub/fheroes2/assets/113276641/1b50455e-67ab-457c-9779-fcdd430a2df2)
</details>

2023-09-03 11:43 UTC, Districh-ru commented
Hi, @Branikolog, I tried to make a temporary patch for mentioned issues.
IMHO we should return to their fix and redo the terrain connecting algorithm after we implement the UNDO function and after we design new terrain transition images (using the existing ones).

2023-09-03 13:24 UTC, Branikolog approved these changes
After testing the latest build I can tell that everything works well now. Great job, @Districh-ru !

2023-09-03 15:21 UTC, merged

2023-09-03 15:21 UTC, ihhub commented
@Districh-ru , huge thanks for these new updates!