Improve Mage guild status message for learnt spells
ihhub/fheroes2 pull request #7597
Opened 2023-08-21 18:35 UTC by zenseii

Fix #4633

2023-08-21 19:04 UTC, Districh-ru requested changes
Hi, @zenseii. I left one suggestion for text positioning. Could you take a look when you have time.

2023-08-21 19:21 UTC, Districh-ru approved these changes
Well done!

2023-08-22 00:05 UTC, ihhub approved these changes

2023-08-22 00:06 UTC, merged

2023-08-22 00:06 UTC, ihhub commented
@zenseii , thank you so much for this change!