Center text in hero battle info window
ihhub/fheroes2 pull request #7606
Opened 2023-08-22 15:09 UTC by ihhub

close #7459

![image](https://github.com/ihhub/fheroes2/assets/19829520/9f668449-82ec-4319-88c7-610303c928be)

2023-08-22 15:30 UTC, Districh-ru requested changes
Hi, @ihhub, I left one suggestion. Could you please take a look in your spare time.

2023-08-22 15:30 UTC, Districh-ru commented on src/fheroes2/battle/battle_dialogs.cpp
> +    tp.y = statsTextOffset.y + statsTextRowHeight;
This and next `tp.y = ` lines can be simplified to:
```suggestion
    tp.y +=  statsTextRowHeight;
```

2023-08-23 06:02 UTC, Districh-ru approved these changes
👍

2023-08-23 11:19 UTC, Branikolog approved these changes

2023-08-23 12:07 UTC, merged