Use "Redmean" color distance calculation for GetPALColorId()
ihhub/fheroes2 pull request #7614
Opened 2023-08-23 11:54 UTC by Districh-ru

Relates to https://github.com/ihhub/fheroes2/issues/7574

This PR modifies the color distance calculation formula to better fit human perception (https://en.wikipedia.org/wiki/Color_difference).

One disadvantage of this PR is that it takes about 40% more time to calculate `rgbToId` array data (120 ms vs 85 ms) during game load.

For the comparison:
Ideal color transitions (click to view in non-scaled size):
![testBest](https://github.com/ihhub/fheroes2/assets/113276641/114acd3a-c2c8-439a-948d-6b0d86567d07)
![test2Best](https://github.com/ihhub/fheroes2/assets/113276641/23359a68-926a-4762-a1b3-750ffcde921f)

Master build:
![testOrig](https://github.com/ihhub/fheroes2/assets/113276641/fb09cf3c-0ba9-40f8-81e6-0995460cadd0)
![test2Orig](https://github.com/ihhub/fheroes2/assets/113276641/d05e920d-ae04-4949-b969-7f38cf2beb46)

This PR:
![testRedmean](https://github.com/ihhub/fheroes2/assets/113276641/39534ca5-ac66-461d-ad3f-1812d94b3e66)
![test2Redmean](https://github.com/ihhub/fheroes2/assets/113276641/f29e4a7f-7638-4ae2-95fe-ab6c0d86c6eb)

The change is noticeable for the dark colors: (there are less noticeable flashes wile fading the credits page)

Master build:
![fheroes2 master 2023-08-23 14-33-36-140](https://github.com/ihhub/fheroes2/assets/113276641/e30a1a18-a691-4a95-97a7-27bd0c99e659)

This PR:
![fheroes2 PR 2023-08-23 14-31-45-500](https://github.com/ihhub/fheroes2/assets/113276641/76fd49ae-f7d9-45fe-90a2-550c50dfd4c8)

<details><summary>Another comparison (castle screen)</summary>

Master build:
![fheroes2 master 2023-08-23 14-09-19-740](https://github.com/ihhub/fheroes2/assets/113276641/b209d4eb-40a1-4e63-88cf-71fce40d93d4)

This PR:
![fheroes2 PR 2023-08-23 14-10-36-540](https://github.com/ihhub/fheroes2/assets/113276641/0028d234-68e8-4045-9031-899b030197d2)

</details>

2023-08-23 14:26 UTC, ihhub requested changes
Hi @Districh-ru , I put just one minor remark here. Could you please check it?

2023-08-23 14:26 UTC, ihhub commented on src/engine/image.cpp
> +                    const int32_t sumRed = ( static_cast<int32_t>( *palette ) + r );
Please remove parenthesis for this line or add it for all other cases.

2023-08-23 15:33 UTC, Districh-ru commented on src/engine/image.cpp
> +                    const int32_t sumRed = ( static_cast<int32_t>( *palette ) + r );
Hi, @ihhub, sure)

2023-08-24 01:20 UTC, ihhub approved these changes

2023-08-24 05:06 UTC, idshibanov approved these changes

2023-08-24 06:22 UTC, merged

2023-08-24 06:22 UTC, ihhub commented
@Districh-ru , thank you so much for this improvement!