Show ... in Load/Save File dialog for long names
ihhub/fheroes2 pull request #7624
Opened 2023-08-24 15:14 UTC by ihhub

close #7497

Also small rendering optimization for text in multiple places to avoid extra memory copies.

![image](https://github.com/ihhub/fheroes2/assets/19829520/c3a88532-4eb8-4e6d-b5fc-96240eeb4730)

2023-08-24 16:39 UTC, Districh-ru requested changes
Hi, @ihhub, I left two comments regarding minor computational optimizations. Could you please take a look when you have time.

Also, IMHO, this PR will not close the mentioned in #7497 issue: "_Some saved game names are shortened so that they appear identical._"
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/2f0d9f92-159d-466f-b231-f2375b787e9d)

A solution would be to use **StandardWindow** class and make a new, wider (and possibly higher) dialog. We could redesign this dialog in one of the next PRs, e.g like we did for "Select ..." dialog in Battle Only. What do you think? :)

2023-08-24 16:39 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +        text.draw( dstx + 5, dsty + 2, display );
We can slightly optimize the code.
`dsty + 2` is used 4 times. We can cache it or simply do `dst += 2;` because `dsty` is not `const`.

2023-08-24 16:39 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +        text.draw( dstx + 245 - text.width(), dsty + 2, display );
Here we can also cache `dstx + 245` or do `dstx += 245;` to use it in the next `text.draw( dstx, ... )`.

2023-08-25 12:11 UTC, Branikolog approved these changes

2023-08-25 13:47 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +        text.draw( dstx + 245 - text.width(), dsty + 2, display );
While we usually do this I think one CPU tick is faster than caching a whole variable :)

2023-08-25 13:55 UTC, Districh-ru approved these changes

2023-08-25 14:16 UTC, merged