Speed up Hut of Magi reveal areas when the number of Eyes is too high
ihhub/fheroes2 pull request #7639
Opened 2023-08-25 15:43 UTC by ihhub

If a map contains a lot of eyes of magi it would take ages to show all of them. This is a solution to avoid such.

Try this save file on this branch and on master:
[Hut_of_Magi.zip](https://github.com/ihhub/fheroes2/files/12441063/Hut_of_Magi.zip)

2023-08-25 17:51 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left one suggestion and one question, could you please take a look when you have time?

2023-08-25 17:51 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_action.cpp
>                      const int32_t scoutRange = static_cast<int32_t>( GameStatic::getFogDiscoveryDistance( GameStatic::FogDiscoveryType::MAGI_EYES ) );
I suppose we can move this out of the loop since scouting range doesn't depend on eye position?

2023-08-25 17:51 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_action.cpp
> +                        --maxDelay;
It seems that after 7 eyes max delay becomes zero and player will not see the animation for remaining eyes at all, is this intentional?

2023-08-25 17:57 UTC, LeHerosInconnu commented
Related discussion: https://github.com/ihhub/fheroes2/discussions/7105.

2023-08-26 11:28 UTC, Branikolog commented
Hi, @ihhub 
I personally don't like the way how it's working in this PR. After 6 or 7 eye the revealing speed rises exponentially and the last areas are revealing too fast, appearing for milliseconds. Implementation looks not smooth and raw. I'd rather prefer to speed up for 0.5-1sec the whole revealing (optionally, as I'm ok with current speed) and allow player to skip by pressing any game button. This could be a click for each eye or even skipping the whole process at once.

2023-08-26 11:41 UTC, ihhub commented
Hi @Branikolog , please be very specific how exactly you see the implementation to be done. Also take a note about touchscreen devices.

2023-08-26 11:46 UTC, oleg-derevenetz commented
Hi @ihhub I recommend not to change the animation speed, but just to cancel the whole animation on key press or mouse button press.

2023-08-26 14:01 UTC, Branikolog commented
@ihhub 

I'm personally think that both implementations are fine. Probably the one, where we just need to make a single left click or press any button on keyboard to skip all animations at once, brings much more convenience, as @zenseii noticed, we can always check minimap for new areas to explore them more thoroughly.

2023-08-26 19:02 UTC, LeHerosInconnu commented
Hello @everyone,

> Hi @ihhub I recommend not to change the animation speed, but just to cancel the whole animation on key press or mouse button press.

Yes.
I stand by my proposal (https://github.com/ihhub/fheroes2/discussions/7105) to completely stop all animation(s) after a mouse click or press of any keyboard key.

The solution of stopping only one animation at a time may seem attractive, but would quickly become annoying, as the player would have to perform several actions in succession to stop all animations, which beyond three actions would be criminal for mouse survival or keyboard life, as the player would then frantically click the mouse button or hit the keyboard wildly to skip animations. :) :D

2023-08-27 02:45 UTC, ihhub commented
Based on the majority of people's opinion I am going to implement animation interruption and immediate reveal of the rest of eyes if a user clicks any button.

2023-08-28 16:26 UTC, Districh-ru requested changes
Hi, @ihhub, I like the implementation, but I noticed a delay after pressing a key to skip the rest of the "Eyes". I left one suggestion for rendering optimization in this case. Could you please take a look when you have time.

2023-08-28 16:26 UTC, Districh-ru commented on src/fheroes2/heroes/heroes_action.cpp
> +                    }
If we skip viewing the rest "Eyes" then we need only to redraw the radar part without gamearea redraw. Gamearea will be rendered after we finish this loop at line 3327.
So we can move `I.getGameArea().SetCenter( eyePosition );` (from line 3294) after the check for `skipAnimation` and if `skipAnimation` is `true` do only `REDRAW_RADAR`:

```suggestion
                    if ( skipAnimation ) {
                        I.redraw( Interface::REDRAW_RADAR );
                        continue;
                    }

                    I.getGameArea().SetCenter( eyePosition );
                    I.redraw( Interface::REDRAW_GAMEAREA | Interface::REDRAW_RADAR );
```

2023-08-29 14:49 UTC, ihhub commented
Hi @Districh-ru , I made an extra optimization. Please take a look.

2023-08-29 15:06 UTC, Districh-ru requested changes
Hi, @ihhub, The optimization with `clearRadarArea` is a good idea. 👍 

Also line 3295 can be moved to the line 3303 becauser if we skip veiwing the rest Eyes we don't need to center the view on them.
https://github.com/ihhub/fheroes2/blob/fd4b357aa500e7ce73a3ef9ba55136bf8809d565/src/fheroes2/heroes/heroes_action.cpp#L3295

2023-08-29 15:43 UTC, Districh-ru approved these changes

2023-08-29 18:38 UTC, oleg-derevenetz approved these changes
Hi @ihhub I just left one optional suggestion regarding variable naming. LGTM otherwise.

2023-08-29 18:38 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_action.cpp
> +                fheroes2::Rect clearRadarArea;
Let me join this nitpickers club and notice that `clearRadarArea` name is a bit misleading, because this is not exactly the area that will be cleared on the radar (in the sense that the fog will be removed in this area). I would call it something like `radarRenderArea`.

2023-08-29 19:01 UTC, Branikolog approved these changes

2023-08-30 00:33 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +                fheroes2::Rect clearRadarArea;
Haha, I will rename it.

2023-08-30 01:09 UTC, merged