Add small skill icons for Xanadu visit dialog
ihhub/fheroes2 pull request #7640
Opened 2023-08-26 01:48 UTC by ihhub

close #5242

![image](https://github.com/ihhub/fheroes2/assets/19829520/2845cbb6-e727-4751-bd1c-bce88a856cba)

You can test the change using this save file:
[xanadu.zip](https://github.com/ihhub/fheroes2/files/12444369/xanadu.zip)

2023-08-26 13:50 UTC, Branikolog commented
Hi, @ihhub 

There's too much free space in this window.
Could you, please, explain, why have you placed icons in a square? Why not in a row?

![xanadu](https://github.com/ihhub/fheroes2/assets/55348946/7d87dde1-1489-4c6a-ab88-9725b510ecfb)

2023-08-26 14:17 UTC, Branikolog commented
Hi, @zenseii !

It's not a problems in my head. :)

>It might confuse players into thinking that they can be selected. The arena and the Xanadu function differently and should be distinguished more, in my opinion.

Once player click on these icons and nothing happens - I believe everyone understands the way this objects operates.
Also, here we can see "+1", while in the arena window icons have just name of the skill below, which is quite easy to distinguish in my opinion. 

>It looks like we are just copying and reusing the look of the arena, which could leave an impression of lacking creativity and just copy pasting the same thing several places in the game.

For me it on contrary looks like a consistency in design and respecting the style of the game UI. 

I'm not strictly against current implementation and I just got curious, once I've seen this screenshot. The window seemed a little unusual to my eye.
Thanks for your answer, @zenseii .

If everyone is ok with this implementation I cannot insist on changing anything. :)

2023-08-26 18:40 UTC, LeHerosInconnu commented
Hello @everyone,

I stand by my position (https://github.com/ihhub/fheroes2/discussions/4877) and continue to think that this arrangement of elements best suits the game:

> ![xanadu](https://github.com/ihhub/fheroes2/assets/55348946/7d87dde1-1489-4c6a-ab88-9725b510ecfb)

The large font could eventually be used instead of the small font as there's enough room for it (we'd have to see the visual with the "+1" in large font), especially when screen resolutions larger than the original game's are used.

2023-08-27 10:24 UTC, ihhub commented
Okay. I will put all items in one row.

2023-08-27 12:39 UTC, ihhub commented
Hi @LeHerosInconnu , using normal font feels unnatural:
![image](https://github.com/ihhub/fheroes2/assets/19829520/422857c0-2cd2-4099-8a50-31f7b528f1c9)

So I kept small font for icons.

2023-08-27 14:29 UTC, Districh-ru requested changes
Hi, @ihhub. I like how Xanadu dialog looks now, well done!
I left one one minor comment. Could you check it when you have time.
Also it seems that currently `FrameDialogElement` class is never used. :(

2023-08-27 14:29 UTC, Districh-ru commented on src/fheroes2/gui/ui_dialog.cpp
> +            fheroes2::Copy( originalImage, 216, 150, output, offset.x, offset.y, _iconSize.width, _iconSize.height );
We can remove `fheroes2::` because we are in fheroes2 namespace. :)

2023-08-27 18:25 UTC, LeHerosInconnu commented
Hello @ihhub,

> Hi @LeHerosInconnu , using normal font feels unnatural: ![image](https://user-images.githubusercontent.com/19829520/263528955-422857c0-2cd2-4099-8a50-31f7b528f1c9.png)
> 
> So I kept small font for icons.

Effectively, thanks for the visual with the big font.

2023-08-29 08:18 UTC, merged

2023-08-31 10:13 UTC, oleg-derevenetz commented
Hi @ihhub this PR introduced (a kind of) regression - there are new object slicing warnings from the SonarCloud, because `Sprite` instances are passed not by reference now, but by value as `Image` instances. I believe that slicing is harmless in this case, but there are still "errors" from the SonarCloud's point of view.

2023-08-31 11:51 UTC, ihhub commented
@oleg-derevenetz , oh. I should revert changes then😞