Speed up translation file loading
ihhub/fheroes2 pull request #7642
Opened 2023-08-26 04:29 UTC by ihhub

relates to #6681

2023-08-26 07:51 UTC, ihhub commented
Hi @shprotru, could you please test this pull request for performance improvement? I believe it will be slightly faster than master branch.

2023-08-26 09:04 UTC, shprotru commented
Hi @ihhub ! I tested from the provided branch `file_reading_speedup`, and there is how it looks like. As fo me as user, there is no changes and technically there are couldn't be, because of speed of the hdd. And my own hdd is enough modern and advanced. This problem as I have been described could be only prettified with preloading window with animation.

https://github.com/ihhub/fheroes2/assets/53114202/11e6dcc5-f85b-4850-8346-b56c37b95788

2023-08-26 09:05 UTC, ihhub commented
Hi @shprotru , is Language selection screen remains the same in terms of loading?

2023-08-26 09:08 UTC, shprotru commented
the language selection window is opening with acceptable speed, but it's laggy a little bit

https://github.com/ihhub/fheroes2/assets/53114202/9185c231-55c4-4fb3-8545-b6be9cb1e8a3

2023-08-26 09:10 UTC, ihhub commented
> the language selection window is opening with acceptable speed, but it's laggy a little bit
> 
Is it faster than on master branch? Also is your storage HDD or SSD? For my laptop with SSD it's almost instant.

2023-08-26 09:18 UTC, shprotru commented
There are no noticeable differences on the eye between master branch and this one. My system is installed on SSD, and my `/home` directory is mounted to HDD, where are fheroes2 and maps installed, so answer is HDD.

2023-08-26 10:29 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left some questions and suggestions here. In general, the main reason for the pause is I/O, the impact of these changes is negligible. We can only "prettify" this pause by showing some "please wait" dialog or maybe changing the mouse cursor to the "wait" variant, but I'm still not sure if it's really necessary.

2023-08-26 10:29 UTC, oleg-derevenetz commented on src/engine/translations.cpp
> +        uint32_t length{ 0 };
These initializations are redundant here, because there is no default constructor for this `struct` anymore, and existing constructor initializes both fields:

https://godbolt.org/z/7nc1EEz1K

But in general it's harmless, they just will not be used :)

2023-08-26 10:29 UTC, oleg-derevenetz commented on src/engine/translations.cpp
> +    std::string getTag( const std::string_view & str, const std::string & tag, const std::string & sep )
There is no need to pass the `string_view` by reference.

2023-08-26 10:29 UTC, oleg-derevenetz commented on src/engine/translations.cpp
> +                const uint32_t crc = crc32b( msg1.data() );
Please note that `std::string_view` is not designed to be used this way, because it doesn't have to be null-terminated. For example, if `buf` contains something like "AABB", and `length1` is 1, you will get the full "AABB" string here, not just "A":

https://godbolt.org/z/Yvj9rePj4

Need to be careful when transforming `std::string_view` to a C string, you can't just do it "head-on".

2023-08-26 12:26 UTC, ihhub commented on src/engine/serialize.cpp
> +    uint8_t * it2 = itget + ( sz ? sz : sizeg() );
This is valid point and I copy-pasted the code.

2023-08-26 12:27 UTC, ihhub commented on src/engine/serialize.cpp
> +    itget = it1 + ( sz ? sz : sizeg() );
Mmmm... another copy-pasted code :(

2023-08-26 12:28 UTC, ihhub commented on src/engine/translations.cpp
> +                const uint32_t crc = crc32b( msg1.data() );
Oh, I think I should revert changes related to string_view (or some dangerous ones). Thank you so much for the explanation!

2023-08-26 12:53 UTC, oleg-derevenetz commented on src/engine/translations.cpp
> +                const uint32_t crc = crc32b( msg1.data() );
Also `crc32()` can be modified to accept the `string_view` instead of `char*`.

2023-08-27 07:37 UTC, ihhub commented on src/engine/serialize.cpp
> +    itget = it1 + ( sz ? sz : sizeg() );
There are places where we read from MP2 files and they have fixed sizes for elements but symbol '\0' can appear earlier. I will keep the same logic as before but beautified it a bit.

2023-08-27 12:13 UTC, Districh-ru requested changes
Hi, @ihhub, I left two suggestions. Could you please check if they are valuable in your spare time

2023-08-27 12:15 UTC, ihhub commented on src/engine/serialize.h
> +        return sizeg();
These are virtual functions. They cannot be inlined.

2023-08-27 12:56 UTC, Districh-ru approved these changes
👍 
I loaded several saves and started new maps, changed translations and found no issues.
On my hardware load of translations file is now about 7% faster.
<details>
Load of MO files in microseconds:

new | old | %
-- | -- | --
1916.2 | 2081.3 | 8.616011
1617 | 1843.2 | 13.98887
1842.9 | 1890 | 2.555755
1794.3 | 1889.5 | 5.30569
605.1 | 666.9 | 10.21319
920.1 | 997.3 | 8.390392
983.1 | 1098.1 | 11.69769
312.3 | 321.2 | 2.849824
1818.4 | 1894.2 | 4.1685
519.1 | 535.8 | 3.217107
339.3 | 351.8 | 3.684055
598.1 | 625 | 4.497576
1718.8 | 1883 | 9.553177
332.7 | 327.4 | -1.59303
185.6 | 197.2 | 6.25
1050 | 1179.5 | 12.33333
1353.4 | 1450.8 | 7.19669
167.5 | 182.4 | 8.895522
197 | 207.8 | 5.482234
594.5 | 650.4 | 9.40286

</details>

2023-08-27 14:37 UTC, oleg-derevenetz reviewed
Hi @ihhub I just left one notice and one question, and also added my own commit with changes related to detection of an error-prone behavior (`StreamBuf::reallocbuf()` should never be called for StreamBufs created from read-only memory blocks such as `const char *` or `const std::vector`) and minor optimizations (there is no need to `std::fill()` with zeroes when we just may [value-initialize](https://en.cppreference.com/w/cpp/language/value_initialization) the array). Could you please take a look when you have time?

2023-08-27 14:37 UTC, oleg-derevenetz commented on src/engine/translations.cpp
> +        if ( str.size() > tag.size() && str.rfind( tag, 0 ) == 0 ) {
In the `master` branch, there is a check that `str` starts with `tag`. Here the original check is replaced by the check that the `tag` could only be at the beginning of `str`. These checks are not equivalent, because if `str` is `tagtag`, then the check in `master` branch will return `true`, while this check will return `false`. Is this intentional?

2023-08-28 14:42 UTC, ihhub commented on src/engine/translations.cpp
> +        if ( str.size() > tag.size() && str.rfind( tag, 0 ) == 0 ) {
Hi @oleg-derevenetz , [rfind()](https://en.cppreference.com/w/cpp/string/basic_string/rfind) searches from right to left (from end to start) from the given position `(thus, the found substring, if any, cannot begin in a position following pos)`. If the position is 0 then it will search only at the start of the string and never proceeds further (see [this](https://stackoverflow.com/questions/1878001/how-do-i-check-if-a-c-stdstring-starts-with-a-certain-string-and-convert-a)).

However, I can just revert the change to avoid any confusion. It is not worth big debates :)

2023-08-28 14:44 UTC, ihhub commented on src/engine/serialize.cpp
> +    return { it1, it2 };
See these lines:
```cpp
name = dataStream.toString( 13 );
...
std::string answer = dataStream.toString( 13 );
```
We expect to have 13 bytes no matter what but the string can be shorter. I agree that the logic is not obvious and I can create 2 overloads of this function with and without input argument. What do you think?

2023-08-28 14:52 UTC, oleg-derevenetz commented on src/engine/serialize.cpp
> +    return { it1, it2 };
Hi @ihhub I think that we can leave it as is so far.

2023-08-28 14:53 UTC, oleg-derevenetz commented on src/engine/translations.cpp
> +        if ( str.size() > tag.size() && str.rfind( tag, 0 ) == 0 ) {
@ihhub Ah, yes, we are searching from the position 0. Let's leave it as is.

2023-08-28 15:03 UTC, merged