Rework the Save/Load game dialog to allow variable dialog size and support Evil interface
ihhub/fheroes2 pull request #7662
Opened 2023-08-29 18:14 UTC by Districh-ru

Close https://github.com/ihhub/fheroes2/issues/1892

![evilLoadInterface](https://github.com/ihhub/fheroes2/assets/113276641/2e75460c-54e2-40ac-a25c-29ca2c2f7f05)

![biSaveDialog](https://github.com/ihhub/fheroes2/assets/113276641/259bb16c-9ccc-4e56-b6d9-fa32caa80319)

2023-09-01 01:43 UTC, ihhub requested changes
Hi @Districh-ru , I put few comments here. My main notes are related to visual interpretation of the dialog:
- despite of the fact that the original game centered titles for save files I think having them shifted to right is visually better. This allows for faster search of specific files.
- I am not sure about the separator in the middle of the text. This separator works only for English date representation and also it differs from the rest of dialogs. Should we remove it?
- current selection text box should be the same length as the above text area. It seems unnatural having a truncated size text box. We accept that a user might enter a lengthy name but we show only that much in the above text box
- the screenshot for evil interface is missing virtual keyboard button. Is it intentional?

What do you think @Branikolog and @zenseii ?

2023-09-01 01:43 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectfile.cpp
>          }
Shall we put this check before getting display to avoid extra operations?

2023-09-01 01:43 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +        if ( !savname.empty() ) {
Since we are moving this code can we please use the opposite logic for fast return?
```cpp
if ( savname.empty() ) {
    return;
}
```

Then the number of changes would be less in this pull request and it would be easier to read in the future.

Moreover, we should put this code at the beginning of the function to avoid unnecessary operations:
```cpp
std::string savname( System::GetBasename( info.file ) );
if ( savname.empty() ) {
    return;
}
```

2023-09-01 01:43 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +        int32_t saveFileCount = 0;
Can we please use **size_t** here and drop static_cast call at line 267?

2023-09-01 04:51 UTC, Districh-ru commented
Hi, @ihhub.
> - I am not sure about the separator in the middle of the text. This separator works only for English date representation and also it differs from the rest of dialogs. Should we remove it?
> - current selection text box should be the same length as the above text area. It seems unnatural having a truncated size text box. We accept that a user might enter a lengthy name but we show only that much in the above text box

The separator could be removed, it was made to visually separate file name from date/time like in tables. In future we will add the ability to sort files by date.
Maybe we should make the headers **Save Name** and **Date** above the list?
Currently we have only English date representation. I left a TODO to implement date representation in system locale. And if we swap month and date the date text will have almost the same length and will fit the separator: "Sep 01,..." <-> "01 Сен,...".
The text input box should have the same width as the maximum displayedfile name width not to allow to input filenames longer than can be displayed. Or we will never fix #7497 (until we reach the OS file name length limit) :)
The part of the list is date/time and we do not input time and date. We can also introduce a separator in text input and display some extra info in the right part.


> - the screenshot for evil interface is missing virtual keyboard button. Is it intentional?

The screenshot for Evil interface is done for Load Game dialog, in this dialog we only select file by click and do not input its name. :)

2023-09-01 14:14 UTC, ihhub commented
@Districh-ru , also would be it be better to have the edit box the same length as the 2 text boxes above and for load mode show a date but not for the save mode?

2023-09-01 14:16 UTC, ihhub commented
@Branikolog and @zenseii , could you please express your opinion about this UI change? This is a must have feature for the release.

2023-09-01 14:18 UTC, ihhub commented
@Districh-ru , in meanwhile could you please address my comments as they don't affect the look of the window? :)

2023-09-01 18:18 UTC, Districh-ru commented
> Having read through the comments again, I believe we should have the extra box near the selected save show the in game time of the save, since we can see the real-life one above.

Done. This is how it looks now:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/530aa4ce-39f0-4f02-a2e0-833260b2d0f0)

2023-09-01 18:36 UTC, Districh-ru commented
> This looks very good to me. Out of curiosity and not having looked at the code. What happens when there are double digit months w/r to fitting in the boxed are? (Weeks and days only range from 1-7 and 1-4 and can't be double digit of course.)

There is a space for one digit:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/54288840-0c7e-4c19-8ecd-f54fdc389952)
We can always expand the "dateTime" area width if this space is not enough for the translated text (if it will have three wide letters).

2023-09-02 00:35 UTC, ihhub commented
Hi @Districh-ru and @zenseii , displaying just a date is not a great idea as players usually finish a map within 1-2 days. They pay more attention to time. Also we must be consistent and display exactly like in the box above. For save files we can display the datetime of opening the dialog. What do you think?

2023-09-02 07:22 UTC, Districh-ru commented
> Hi, @Districh-ru. I realized that we already have some UI design for headers present in the original game in the scenario selection dialog.
> 
> My proposal is that we can add buttons with the text "NAME" and "DATE" (and other options?), which pressing them would also sort the list accordingly. As a bonus, this would solve completly or partially the issues #1211 (@LeHerosInconnu's first issue so maybe it's about time😅) and #4053. 

Hi, @zenseii. Like this?

![изображение](https://github.com/ihhub/fheroes2/assets/113276641/c49d1707-b181-47d5-9ae5-d41216d0cb20)

But IMHO it'll be better to implement date sorting in a new PR because this one is already big (and I'm busy today :) ).

I'm marking this PR as ready for review.

2023-09-02 12:30 UTC, Branikolog commented
Hi, @Districh-ru !

I've checked your PR and I love it really much! 😇 

There're only a few minor issues I want to mention and hear your opinion as well as our team for sure.
![image](https://github.com/ihhub/fheroes2/assets/55348946/80a9fab3-4367-4b14-b29c-2ab6ab8f024f)
Save file with WWW fits the list well. But the bottom line shows "..." instead of the last symbol. Is it intended behaviour here? Since these boxes have the same width, I'm surprised to see that text doesn't fit into bottom line.

Since you've moved virtual keyboard button from the right bottom cornet to the central bottom line I believe the button with "..." could be a little wider, since there's enough space between "Okay" and "Cancel" buttons. This could be done in separate PR for sure.

And my biggest concern is about the window size itself. 
While on x480 resolutions it is comparable to other game windows and looks acceptable:
![image](https://github.com/ihhub/fheroes2/assets/55348946/fe5ca4a6-a84c-4bfd-a198-e8bd8d65cfcf)

On larger resolutions the list looks terrifying (It's too large and too many strings in it. I believe, that our programmers from the Team are got used to a large number of text strings 😅, but within the game UI it looks quite overwhelming.).
![image](https://github.com/ihhub/fheroes2/assets/55348946/37e3a90a-d25b-4642-8cb6-95207f701cbe)
I agree, that using higher resolutions we should employ all advantages. But I nevertheless suggest making it vertically smaller. Not the same as for x480 resolutions, but I prefer it being not larger, than system option menu (preferably in my opinion for smaller resolutions) or scenario info window (could be better for fHD etc).

2023-09-02 13:17 UTC, Branikolog commented
Hi, @zenseii and @ihhub 

> I believe we should left-side align the save names instead of right-side align them as @ihhub suggested. I don't feel too strongly about changing this from what it is originally.

I'm also got used to left-side text aligning, but after we've stretched the box with file names I'm afraid it would be difficult to correlate name and date (especially if the name is really short). So I think placing them in the middle is a way to go...

2023-09-02 13:21 UTC, ihhub commented
@Districh-ru , @Branikolog , @zenseii , let's leave any new features for this dialog outside this pull request and purely focus only on enhancing the existing dialog.

2023-09-02 13:54 UTC, ihhub approved these changes

2023-09-02 18:01 UTC, Branikolog commented
@zenseii 

> I believe one problem in your image is the jarring difference in resolution between the stretched out main menu background, and the non-stretched file select dialog.

Not exactly. The main thing bothers me is that it is the largest window in the game now. Even much bigger, than battle or castle screens. And whole internals of this window is full of text, like an excel file. The rest windows in the game are much smaller and more balanced, than this one, which looks like a bill. 😅 
From a usability point this window is great, as I don't have to scoll list to reach the lowest files. But from a design point, it stands out being too massive and monotonous containing just files, files and only files. 
I suggest making it not as short, as for 640x480, but to make it a little more uniform to existing UI elements, reducing its length up to ~ 22-25 strings.

2023-09-03 06:53 UTC, Districh-ru commented
> Save file with WWW fits the list well. But the bottom line shows "..." instead of the last symbol. Is it intended behaviour here? Since these boxes have the same width, I'm surprised to see that text doesn't fit into bottom line.

Hi, @Branikolog, this is intentional behavior because in the text input field we have "WWWWWWWWWW" with a '_' cursor at the end.
In the text input field, we limit the maximum length of the save file name so that it is displayed without truncation in the list.
Currently anyone can enter a very-very long phrase by using the Virtual Keyboard, we should implement such limit there in future PRs. Also everybody can rename the save file in OS explorer. In these cases we will have the file name larger than we can display.

We can change the parameters of this dialog at any time (minimum, maximum lines; dialog width, text aligning) if we get reasoned feedback.

2023-09-03 10:47 UTC, Branikolog approved these changes
Amazing work!

2023-09-03 11:22 UTC, merged

2023-09-03 11:23 UTC, ihhub commented
@Districh-ru , thank you so much for these changes!

2023-09-03 19:21 UTC, petar-stamenkov commented
Hello, while testing if everything's okay after merging the changes introduced in this PR to the branch of #7680, I noticed there is a crash if you click at the end of the save filename input and add a character to the filename. It looks like it's caused by the addition of underscore to the filename here:
https://github.com/ihhub/fheroes2/blob/117839baa6554684d360088f1e80442fc6561084/src/fheroes2/dialog/dialog_selectfile.cpp#L494

Changing it to pass the filename without underscore seems to fix the crash.

2023-09-04 07:41 UTC, Districh-ru commented
> Hello, while testing if everything's okay after merging the changes introduced in this PR to the branch of #7680, I noticed there is a crash if you click at the end of the save filename input and add a character to the filename. It looks like it's caused by the addition of underscore to the filename here:
> https://github.com/ihhub/fheroes2/blob/117839baa6554684d360088f1e80442fc6561084/src/fheroes2/dialog/dialog_selectfile.cpp#L494
> 
> Changing it to pass the filename without underscore seems to fix the crash.

Hi, @petar-stamenkov. Thanks for the bug report! I'll fix this regression later today.