Do not try to scout the area if the hero is in jail and gets an artifact assigned using the map editor
ihhub/fheroes2 pull request #7667
Opened 2023-08-29 23:58 UTC by oleg-derevenetz

fix #7663

2023-08-30 08:34 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left one suggestion here. Could you please check it?

2023-08-30 08:34 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +    if ( GetColor() == Color::NONE ) {
Should we check hero flag **JAIL** instead? I am just worrying what if someone tries to add a neutral hero on map but not in Jail.

2023-08-30 08:41 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes.cpp
> +    if ( GetColor() == Color::NONE ) {
Hi @ihhub We can't just swap them :) We need to rework the corresponding loading method a bit because it clears all flags (and it's right about that). OK, I'll try to rework this.

2023-08-30 08:42 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +    if ( GetColor() == Color::NONE ) {
mmm... then we can leave it as it is. If it takes too much time it is okay to use your approach.

2023-08-30 08:44 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes.cpp
> +    if ( GetColor() == Color::NONE ) {
@ihhub I'll try to do this later today.

2023-08-31 00:13 UTC, ihhub approved these changes

2023-08-31 00:13 UTC, merged

2023-08-31 00:13 UTC, ihhub commented
@oleg-derevenetz , thank you so much for these chnages!