Keep dialog opened on load game cancel
ihhub/fheroes2 pull request #7669
Opened 2023-08-30 11:20 UTC by lwollnikowski

2023-08-31 05:09 UTC, Districh-ru requested changes
Hi, @lwollnikowski. I left one comment, could you please take a look when you have time.

2023-08-31 05:09 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_file.cpp
>              }
We should not remove the `else` statement. This new code should be executed only if `ListFiles::isEmpty()` returned `false` because we should not open Load Game dialog if there are no saved games.

```suggestion
            else {
                if ( Interface::AdventureMap::Get().EventLoadGame() == fheroes2::GameMode::LOAD_GAME ) {
                    result = fheroes2::GameMode::LOAD_GAME;
                    break;
                }
            }
```

2023-08-31 07:20 UTC, lwollnikowski commented on src/fheroes2/dialog/dialog_file.cpp
>              }
You are right, fixed.

2023-08-31 07:29 UTC, Districh-ru approved these changes

2023-09-01 10:41 UTC, ihhub approved these changes

2023-09-01 14:03 UTC, merged