Do not show second brackets when hero can learn secondary skill from witch hut
ihhub/fheroes2 pull request #7671
Opened 2023-08-31 08:18 UTC by lwollnikowski

#7670

- hero does not know skill, has all skill slots occupied = 'already has max skills'
- hero does know skill, has all skill slots occupied = 'already knows this skill'
- hero does not know skill, can learn new skills = no second brackets
- hero does know skill, can learn new skills = 'already knows this skill'
![Screenshot 2023-08-31 10-10-56](https://github.com/ihhub/fheroes2/assets/26660595/71fa5088-6b1b-43e0-b37c-aa64a27ba762)
![Screenshot 2023-08-31 10-11-10](https://github.com/ihhub/fheroes2/assets/26660595/7d437f44-3387-4df3-b1ad-fc9f3b3d710f)
![Screenshot 2023-08-31 10-11-14](https://github.com/ihhub/fheroes2/assets/26660595/7d2ffbe3-f028-4f93-83a8-a16a0463ea5c)

![Screenshot 2023-08-31 10-11-23](https://github.com/ihhub/fheroes2/assets/26660595/13c9e27f-99c7-4021-8854-4291d7fdc0d2)
![Screenshot 2023-08-31 10-11-25](https://github.com/ihhub/fheroes2/assets/26660595/ce1ee2a5-3548-45c9-8d3b-d5926e08ffbb)
![Screenshot 2023-08-31 10-11-40](https://github.com/ihhub/fheroes2/assets/26660595/41f5602a-80cc-42e2-aee0-6e53f9a6ca25)

2023-08-31 12:41 UTC, ihhub requested changes
Hi @lwollnikowski , I left one suggestion here. Could you please check it when you have time?

2023-08-31 12:41 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +                std::string heroStr;
Let's use C-string here with nullptr by default. Then we won't have an extra std::string. What do you think?

2023-09-01 10:21 UTC, lwollnikowski commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +                std::string heroStr;
I can use it. I know std::string has little resources overhead over C-string, are there other reasons?

2023-09-01 10:42 UTC, ihhub approved these changes

2023-09-01 10:42 UTC, merged

2023-09-01 10:42 UTC, ihhub commented
@lwollnikowski , thank you so much for this fix!

2023-09-01 15:09 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +                std::string heroStr;
This is the only reason. We pay a lot of attention to performance so if it's possible to avoid extra computations it's better to do it. After all running a well optimized application on a mobile phone means longer battery life :)