Update danish translation (97% / 71)
ihhub/fheroes2 pull request #7712
Opened 2023-09-07 12:48 UTC by Stisen1

- Changes to misspellings and misunderstandable messages.

2023-09-09 03:35 UTC, ihhub requested changes
Hi @Stisen1 , I have several questions here. Could you please take a look at them?

2023-09-09 03:35 UTC, ihhub commented on files/lang/dk.po
> +msgstr "Øger hele din hærs bevægelseshastighed med 2 point."
Please do not use hardcoded values where we don't use them. This sentence might be used for other artifact in the future.

2023-09-09 03:35 UTC, ihhub commented on files/lang/dk.po
> +msgstr "Masse- forsløvning"
Is it valid to have a whitespace after **-**? The same question applies for other translation string below.

2023-09-09 03:35 UTC, ihhub commented on files/lang/dk.po
> +msgstr "Øger på magisk vis den valgte trops forsvarsevne med 3 point."
Could you please explain where number 3 comes from?

2023-09-09 03:35 UTC, ihhub commented on files/lang/dk.po
> +"Øger den valgte trops forsvarsevne med 5 point. Dette er en forbedret "
Could you please explain where number 5 comes from?

2023-09-09 03:35 UTC, ihhub commented on files/lang/dk.po
> +msgstr "Reducerer en fjendtlig trops forsvarsevne med 3 point."
Could you please explain where number 3 comes from?

2023-09-09 03:35 UTC, ihhub commented on files/lang/dk.po
> +msgstr "Øger en trops angrebsevne mod drager med 5 point."
Could you please explain where number 5 comes from?

2023-09-09 03:35 UTC, ihhub commented on files/lang/dk.po
> +msgstr "Øger en trops angrebsevne med 3 point."
Could you please explain where number 3 comes from?

2023-09-09 04:37 UTC, Stisen1 commented on files/lang/dk.po
> +msgstr "Øger hele din hærs bevægelseshastighed med 2 point."
I spoked with @zenseii in the scandinavian channel about why I had to do this. 

I beliede he made an "issue" on this, after we spoke. But I am not sure, whether it's gonna work with v.1.0.8 or v.1.0.9.
 
On the campaign scenario info-screen, the campaign bonus description for "mass-haste", shown when holding right-click, displays "%{count}" as "%.count." in the text, no matter if I write the number "2" or the letters "two" as placeholder. Ingame the "mass-haste" description is displayed as intended...

2023-09-09 04:59 UTC, Stisen1 commented on files/lang/dk.po
> +msgstr "Masse- forsløvning"
This is also a case I've been speaking with @zenseii on. The whitespace works as a "\n" normally would, but for some reason, this "\n" shows as a "?" symbol. If I remove the whitespace, the word looks like "masse-forsløvnin(\n)g". 

What do you prefer? A "?"-symbol inside the text or leave it as it is now?

2023-09-09 05:03 UTC, Stisen1 commented on files/lang/dk.po
> +msgstr "Øger på magisk vis den valgte trops forsvarsevne med 3 point."
When you cast stoneskin, you see that your unit has increased it's defense by 3, no matter how much spell power the hero has or how much defense the unit has. In some other original spell descriptions, you actually get the exact number spelled out to you. I wanted to add consistency troughout the game's spell descriptions.

2023-09-09 05:11 UTC, Stisen1 commented on files/lang/dk.po
> +"Øger den valgte trops forsvarsevne med 5 point. Dette er en forbedret "
I did some testing with "battle only". I had three times 1 stack phoenixes against 1 green, 1 red and 1 black dragon. I cast mass bless on my birdies and then dragon slayer on one of them. Then I calculated the damage differences for each dragon. Phoenix and green dragon has the same attack vs defense value, while red and black dragons have +1 and +2 defense against phoenix' attack value. Each attack value above the enemy creatures defence value results in 10% increased damage... You could argue that +5 attack value against dragons is the same as saying +50% damage against dragons, but since the enemy can change attack and defence values as a counter to dragon slayer, I figured that it gives a better understanding of the spell's effect to put it like this.

2023-09-09 05:12 UTC, Stisen1 commented on files/lang/dk.po
> +msgstr "Øger en trops angrebsevne mod drager med 5 point."
I did some testing with "battle only". I had three times 1 stack phoenixes against 1 green, 1 red and 1 black dragon. I cast mass bless on my birdies and then dragon slayer on one of them. Then I calculated the damage differences for each dragon. Phoenix and green dragon has the same attack vs defense value, while red and black dragons have +1 and +2 defense against phoenix' attack value. Each attack value above the enemy creatures defence value results in 10% increased damage... You could argue that +5 attack value against dragons is the same as saying +50% damage against dragons, but since the enemy can change attack and defence values as a counter to dragon slayer, I figured that it gives a better understanding of the spell's effect to put it like this.

2023-09-09 05:14 UTC, Stisen1 commented on files/lang/dk.po
> +"Øger den valgte trops forsvarsevne med 5 point. Dette er en forbedret "
When you cast Steelskin, you see that your unit has increased it's defense by 5, no matter how much spell power the hero has or how much defense the unit has. In some other original spell descriptions, you actually get the exact number spelled out to you. I wanted to add consistency troughout the game's spell descriptions.

2023-09-09 05:15 UTC, Stisen1 commented on files/lang/dk.po
> +msgstr "Reducerer en fjendtlig trops forsvarsevne med 3 point."
The original spell description litterally says "three". So what's the problem here?

2023-09-09 05:17 UTC, Stisen1 commented on files/lang/dk.po
> +msgstr "Øger en trops angrebsevne med 3 point."
When you cast Bloodlust, you see that your unit has increased it's attack by 3, no matter how much spell power the hero has or how much attack the unit or hero has. In some other original spell descriptions, you actually get the exact number spelled out to you. I wanted to add consistency troughout the game's spell descriptions.

2023-09-09 08:23 UTC, ihhub commented on files/lang/dk.po
> +msgstr "Masse- forsløvning"
I will take a look at this issue. This might be a problem with font generation.

2023-09-09 08:24 UTC, ihhub commented on files/lang/dk.po
> +msgstr "Reducerer en fjendtlig trops forsvarsevne med 3 point."
Ah, my bad.

2023-09-09 11:11 UTC, ihhub commented on files/lang/dk.po
> +msgstr "Masse- forsløvning"
Yup. This is my concern about the question mark as it shouldn't appear. Question mark is only for symbols which don't exist but `\n` does in some way.

2023-09-09 12:20 UTC, ihhub commented
@Stisen1 , please adjust the translation after #7724 and #7726 PRs are merged.

2023-09-10 07:27 UTC, Stisen1 commented on files/lang/dk.po
> +msgstr "Øger hele din hærs bevægelseshastighed med 2 point."
changed back to old phrase

2023-09-10 11:16 UTC, ihhub approved these changes

2023-09-10 11:54 UTC, merged

2023-09-10 11:54 UTC, ihhub commented
@Stisen1 , thanks a lot for this update!