Generate vertical high scores buttons
ihhub/fheroes2 pull request #7714
Opened 2023-09-07 18:58 UTC by zenseii

Part of #6105 

The horizontal centering of the N looks off in Standard probably because its width is an even number (+1 for x offset), like described in #7582 
![image](https://github.com/ihhub/fheroes2/assets/12501091/2f99fe32-762c-4137-8b18-9fab59daa5f1)

I used the original buttons due to the background which I'm not sure how to make a template background of.

2023-09-08 16:45 UTC, Districh-ru requested changes
Hi, @zenseii. I left one suggestion regarding computation optimization.

And what do you think about fixing the horizontal position of single-letter text lines?
This can be done in a new PR.

We can modify this line: 
https://github.com/ihhub/fheroes2/blob/3e6efc003eaeffc9fb051359baf0107d6145ac8c/src/fheroes2/gui/ui_text.cpp#L309

In example, by this code:
```cpp
// For button font single letters in a row we add extra 1 to the width to more properly center odd-length letters.
const int32_t esxtraOffsetX
    = ( size == 1 && ( fontType.size == fheroes2::FontSize::BUTTON_RELEASED || fontType.size == fheroes2::FontSize::BUTTON_PRESSED ) ) ? 1 : 0;
render( data, size, x + ( maxWidth - correctedLineWidth + esxtraOffsetX ) / 2, y, output, fontType );
```

![изображение](https://github.com/ihhub/fheroes2/assets/113276641/6f6797ff-b7fb-4f87-9643-a0aaaf3c7c5d) ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/702c47c3-cc65-4281-ac27-96c0586c7d0f)

2023-09-09 03:41 UTC, ihhub requested changes
Hi @zenseii , I left just few minor comments here. Would you mind to check them when you have time?

2023-09-09 03:41 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                }
Since we are handling only 3 cases I suggest to add another if-else branch with an assertion:
```cpp
else {
    assert( id == ICN::BUTTON_HSCORES_VERTICAL_CAMPAIGN );
}
```

2023-09-09 03:41 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +            case ICN::BUTTON_HSCORES_VERTICAL_EXIT: {
A very minor nit-picking: ideally it is good to sort cases in alphabetic order to easier reading. It's up to you if you want to keep this way.

2023-09-09 03:41 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    const Sprite & originalButton = GetICN( originalID, originalICNIndex + i );
We can avoid static_cast for the loop and do this:
```cpp
for ( size_t i = 0; i < _icnVsSprite[id].size(); ++i ) {
    const Sprite & originalButton = GetICN( originalID, originalICNIndex + static_cast<uint32_t>( i ) );
```
Please note that I changed from `int32_t` to `uint32_t`.

2023-09-09 04:59 UTC, Districh-ru commented
> Hi, @Districh-ru. I've addressed your comments. There's still a problem with words with "M" that are aligned incorrectly. Look at the C and N which are aligned wrongly in CAMPAIGN, especially when compared to how N is aligned in STANDARD. The same issue with alignment happens in vertical DISMISS so I believe it has to do with the width of M. It does not happen for a wider letter like W.

Hi, @zenseii.
In these cases the "M" letter is 18 pixels wide and it gives the text widths = 19 (odd again).
We can try to fix it by expanding the conditions for the extraOffsetX:
```cpp
// For button font single letters in a row we add 1 extra pixel to the width to more properly center odd-width letters only if 'maxWidth' is not odd.
const int32_t extraOffsetX
    = ( size == 1 && ( maxWidth % 2 == 0 ) && ( fontType.size == fheroes2::FontSize::BUTTON_RELEASED || fontType.size == fheroes2::FontSize::BUTTON_PRESSED ) )
        ? 1
        : 0;
```

![изображение](https://github.com/ihhub/fheroes2/assets/113276641/13fe9031-a0ae-49d6-adc5-fd9107eb63bc) ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/038743af-1804-4284-8bb5-0bbc4e465d21)
Comparing to original ones:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/7b44ffe9-2b0d-4226-bc55-7ac55a957945) ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/e895957a-d564-47b4-8c89-26b03a9ba36f)



After this the only one misplaced letter is "G"... Aтв currently I don't see a solution except making a special condition tor this letter, like `if (data[0]=='G') {extraOffsetX+=1;}`. But let's leave for the future when we will get a better solution. You can leave a TODO, if you want (like: Implement pixel perfect letters placement.). I believe we will be able to fix it after we implement adaptive spacing between letters (including spacing/width setting for single letters), like for WA, when '/' line of W is overlapped with '/' part of A.

2023-09-09 18:25 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                    Fill( out, 4 - static_cast<uint32_t>( i ), 4 + static_cast<uint32_t>( i ), 19, 123, getButtonFillingColor( i == 0 ) );
Hi, @zenseii, you can do `static_cast<int32_t>` here in both cases because `i` will not reach the maximum value for `int32_t` and `Fill()` accepts `int32_t` here.
It will make Clang-Tidy happy and avoid triple conversion (size_t -> uint32_t -> int32_t).

2023-09-09 18:40 UTC, Districh-ru requested changes
Hi, @zenseii, I left one comment. Could you please take a look when you have time.

2023-09-09 18:40 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                int32_t originalICNIndex = 0;
These two variables are used in `GetICN( int icnId, uint32_t index )`. So to avoid type conversions we can declare these variables using the corresponding types:
```suggestion
                const int originalID = ICN::HISCORE;
                uint32_t originalICNIndex = 0;
```

2023-09-09 18:50 UTC, Districh-ru approved these changes
Great, most of the buttons in the game can now be translated!

2023-09-10 01:48 UTC, ihhub approved these changes

2023-09-10 01:48 UTC, merged

2023-09-10 01:48 UTC, ihhub commented
@zenseii , huge thanks for this nice improvement!