Cursor no force redraw
ihhub/fheroes2 pull request #7735
Opened 2023-09-10 11:46 UTC by Districh-ru

Fix #7730, #7281, #7272

2023-09-10 12:45 UTC, Districh-ru commented
Hello, @LeHerosInconnu. Could you please test this PR for issue #7272 if you have time.

2023-09-11 15:03 UTC, Districh-ru commented
> Hi, @Districh-ru !
> 
> I've caught one issue during testing of this PR.

Hi, @Branikolog, many thanks for testing this PR!
Good catch! I played for 2 hours and did not notice this bug... :(
It is fixed now, could you please check it when you have time.

2023-09-12 21:05 UTC, LeHerosInconnu commented
Hello @Districh-ru,

> Hello, @LeHerosInconnu. Could you please test this PR for issue #7272 if you have time.

So I tested this and the problem described in issue #7272 is still present.

https://github.com/ihhub/fheroes2/assets/43583994/a7a07738-91cb-4be2-b335-fd30b4f3a786

![Shotcut_00_00_10_760](https://github.com/ihhub/fheroes2/assets/43583994/44b06cf2-0b7a-4b98-9fb6-35a0789a5f5a)

2023-09-13 15:31 UTC, Districh-ru commented
Hi, @LeHerosInconnu, many thanks for testing and for the video with the issue!

I found another place which caused the cursor change in the middle of fade animation. 
Now in such dialogs with fade effect the cursor restorer is removed. The cursor should now stay unchanged until fade animation finishes and the Game Area events handler will set the appropriate cursor.

Could you please take a look when you have time.

Cursor restorer is not needed in these dialogs (and probably in most others) because after closing the dialog, opened over the game area or the battlefield, the events handler will replace the restored cursor with the appropriate one. The cursor restoration is redundant here and also a little harmful because it restores the previous cursor image that is not always correct for the new cursor position.

2023-09-14 16:34 UTC, LeHerosInconnu commented
Hello @Districh-ru,

> Hi, @LeHerosInconnu, many thanks for testing and for the video with the issue!
> 
> I found another place which caused the cursor change in the middle of fade animation. Now in such dialogs with fade effect the cursor restorer is removed. The cursor should now stay unchanged until fade animation finishes and the Game Area events handler will set the appropriate cursor.
> 
> Could you please take a look when you have time.
> 
> Cursor restorer is not needed in these dialogs (and probably in most others) because after closing the dialog, opened over the game area or the battlefield, the events handler will replace the restored cursor with the appropriate one. The cursor restoration is redundant here and also a little harmful because it restores the previous cursor image that is not always correct for the new cursor position.

I tested this quickly with [Dominion_0064.zip](https://github.com/ihhub/fheroes2/files/11615881/Dominion_0064.zip) save file and the problem reported in issue #7272 seems to have been solved.
I'll keep an eye on this behavior in future games. :)
Thanks for the fix.

2023-09-14 16:39 UTC, Districh-ru commented
Hello, @LeHerosInconnu. 
> I tested this quickly with [Dominion_0064.zip](https://github.com/ihhub/fheroes2/files/11615881/Dominion_0064.zip) save file and the problem reported in issue #7272 seems to have been solved.
I'll keep an eye on this behavior in future games. :)
Thanks for the fix.

I am glad to hear it. :)
Thank you for testing!

2023-09-16 22:05 UTC, Branikolog approved these changes

2023-09-17 06:22 UTC, ihhub requested changes
Hi @Districh-ru , I left very minor comment related remarks. Could you please take a look at them in your free time?

2023-09-17 06:22 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +        // Set the cursor image.This dialog is called from the battlefield and does not require a cursor restorer.
Please add a white space after the first full stop.

2023-09-17 06:22 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +        // Battlefield event proccessror will set the appropriate cursor after this dialog is closed.
**proccessror** is misspelled.

2023-09-17 06:22 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    // Set the cursor image.This dialog does not require a cursor restorer.
Please add a white space after the first full stop.

2023-09-17 06:22 UTC, ihhub commented on src/fheroes2/castle/castle_dialog.cpp
> +    // Set the cursor image.This dialog does not require a cursor restorer. It is called from other dialogs that have the same cursor
Please add a white space after the first full stop.

2023-09-17 06:30 UTC, ihhub approved these changes

2023-09-17 06:30 UTC, Districh-ru commented on src/fheroes2/battle/battle_dialogs.cpp
> +        // Set the cursor image.This dialog is called from the battlefield and does not require a cursor restorer.
Hi, @ihhub. Thanks for the spell checking!

2023-09-17 06:30 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +                            assert( !isMovingHero );
My only worry with this assert is that when a moving hero steps on an event. Could you please verify that it doesn't assert for this case?

2023-09-17 06:55 UTC, Districh-ru commented on src/fheroes2/game/game_startgame.cpp
> +                            assert( !isMovingHero );
I checked, its OK.
When event is occurred the hero stops. And the event action is performed in `MoveStep()` called from `hero->Move()`. So at this moment the assertion will not blow up and the condition `hero->isAction()` will be false.

2023-09-17 12:18 UTC, merged

2023-09-17 12:18 UTC, ihhub commented
@Districh-ru , huge thanks for this awesome work!