Update Vietnamese Translation P5
ihhub/fheroes2 pull request #7748
Opened 2023-09-13 16:10 UTC by Nad-SK

Towns name and more

2023-09-29 15:56 UTC, ihhub requested changes
Hi @Nad-SK , I left several comments here. Can you please take a look at them?

2023-09-30 10:56 UTC, Nad-SK commented on files/lang/vi.po
> +msgstr "Pháp sư!"
Fixed!

2023-09-30 10:57 UTC, Nad-SK commented on files/lang/vi.po
> +msgstr "%{name} chủng tộc %{race}"
Fixed

2023-09-30 10:57 UTC, Nad-SK commented on files/lang/vi.po
> +msgstr "Màn hình Tướng"
Hero mean Anh Hùng, Tướng.
Chinese chess mean Cờ Tướng
So I keep this mean for my translate.

2023-09-30 10:57 UTC, Nad-SK commented on files/lang/vi.po
> +msgstr "Tình trạng của đội trưởng %{name}:"
I use this translate.

2023-10-07 02:10 UTC, ihhub commented on files/lang/vi.po
> +msgstr "Pháp sư!"
How is it fixed is nothing was changed?

2023-10-07 02:11 UTC, ihhub commented on files/lang/vi.po
> +msgstr "Tình trạng của đội trưởng %{name}:"
Status and state as a verb are 2 different things.

2023-10-07 14:11 UTC, Nad-SK commented on files/lang/vi.po
> +msgstr "Pháp sư!"
Done

2023-10-07 14:11 UTC, Nad-SK commented on files/lang/vi.po
> +msgstr "%{name} chủng tộc %{race}"
Done

2023-10-07 15:11 UTC, Nad-SK commented
Hi @ihhub, I checked the errors and fixed it.

2023-10-08 14:12 UTC, ihhub reviewed
Hi @Nad-SK , I left one more comment here. Could you please take a look?

2023-10-08 14:12 UTC, ihhub commented on files/lang/vi.po
> +msgstr "Máu"
Google says that this is **Blood** which is not the same as Health Points (HP).

2023-10-09 00:17 UTC, Nad-SK commented on files/lang/vi.po
> +msgstr "Máu"
OK man, Health Points ~ Điểm Sức khỏe 
In VN we call HP ~ Máu, Mana ~ Phép in some games like Diablo, HoMM series

2023-10-09 00:47 UTC, Nad-SK commented
Hi @ihhub, I checked your comment and fixed it.

2023-10-09 14:26 UTC, Nad-SK commented
> Hi @Nad-SK , my question about HP wasn't a demand for change but just a question. With your new changes I fear that there would be not enough space in the Well dialog: ![image](https://user-images.githubusercontent.com/19829520/273607799-bce84345-1b2b-4b08-9d3b-db6f04d444f6.png)

Now what??? I think HP~ Máu is OK for the space. Or no need to translate this, because in VN we know what is HP.

2023-10-09 15:28 UTC, Nad-SK commented
Hi @ihhub I translate HP ~ Máu for the space in well dialog and for some sentences with HP like: HP drain, HP regeneration...

2023-10-09 23:58 UTC, merged

2023-10-09 23:59 UTC, ihhub commented
@Nad-SK , thank you so much for this update!