Rework game settings on Adventure Map
ihhub/fheroes2 pull request #7751
Opened 2023-09-14 10:12 UTC by ihhub

2023-09-14 11:25 UTC, ihhub commented
Hi @zenseii , could you please this window's text:
![image](https://github.com/ihhub/fheroes2/assets/19829520/4b065344-34ef-4865-98df-1726e4f7a385)

?

2023-09-14 16:36 UTC, Districh-ru requested changes
Hi, @ihhub.
I like the changes in settings dialogs! Now we can change game resolution and language without going back to the main menu.
I left some suggestions regarding rendering optimizations. Could you please take a look in your spare time.

And maybe we could add hero speed change by mouse wheel, like it is done for the scroll speed and sound volume. What do you think? :)

2023-09-14 16:36 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_interface_settings.cpp
> +            if ( le.MouseClickLeft( windowScrollSpeedRoi ) ) {
I'm a little concerned that to simply change the scroll speed or cursor color we close this dialog, restore the image below it, and then completely redraw it and initialize all the restorers. Here we could only restore `emptyDialogRestorer` and call `drawOptions();` with `display.render()`. It applies to other dialogs with the same options (hero speed, quick-battle, ...).
But since the settings are changed not often and not much we can leave it as is. :)
So this is an optional comment. We could leave a TODO to optimize this part in the future if this optimization is needed. What do you think?

2023-09-14 16:36 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +        updateUI();
This UI update is probably redundant here: the previous settings dialog is closed after every action and its restorer restores the pure image without any dialogs.

2023-09-14 16:36 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_interface_settings.cpp
> +        updateUI();
The same comment about the redundant UI update: the action in the previous dialog closes it and restores the screen image.

2023-09-16 15:45 UTC, ihhub commented on src/fheroes2/dialog/dialog_interface_settings.cpp
> +            if ( le.MouseClickLeft( windowScrollSpeedRoi ) ) {
It is fixed.

2023-09-16 21:26 UTC, Branikolog approved these changes

2023-09-16 22:54 UTC, mihaimaruseac approved these changes

2023-09-17 06:40 UTC, Districh-ru requested changes
Hi, @ihhub, I left two similar comments regarding minimization of render area on dialog contents update. Could you take a look when you have time.

2023-09-17 06:40 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_interface_settings.cpp
> +            display.render();
In this case we do not need to render the full screen. We may render only the changed area:
```suggestion
            display.render( emptyDialogRestorer.rect() );
```

2023-09-17 06:40 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_system_options.cpp
> +            display.render();
The same comment as above.
```suggestion
            display.render( emptyDialogRestorer.rect() );
```

2023-09-17 06:57 UTC, Districh-ru approved these changes
Well done!
I really like the reworked game settings dialogs!

2023-09-17 07:05 UTC, merged