Remove TextSprite class
ihhub/fheroes2 pull request #7757
Opened 2023-09-15 16:17 UTC by ihhub

Here are few things this pull request handles:
- status bar does not allow to render beyond specified width (close #1689)
- SystemInfoRenderer is not a global variable anymore
- replace TextSprite class by MovableText

2023-09-16 07:53 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a couple of suggestions, please take a look when you have time.

2023-09-16 07:53 UTC, oleg-derevenetz commented on src/engine/localevent.h
> +    static void RegisterCycling( const std::function<void()> & preRenderDrawing = nullptr, const std::function<void()> & postRenderDrawing = nullptr );
We can use `= {}` here instead of `= nullptr`, it's the same: both create an empty function.

2023-09-16 07:53 UTC, oleg-derevenetz commented on src/fheroes2/game/fheroes2.cpp
> +            LocalEvent::RegisterCycling( [this]() { _systemInfoRenderer->preRender(); }, [this]() { _systemInfoRenderer->postRender(); } );
I recommend to perform this registration in the `SystemInfoRenderer`'s constructor and also unregister these methods in the `SystemInfoRenderer`'s destructor to ensure that these methods will not be called when it is destroyed. Also you can use the pointer to member function here instead of lambda using `std::bind()`, but that's optional.

2023-09-16 08:55 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left a few comments here, please take a look when you have time.

2023-09-16 08:55 UTC, oleg-derevenetz commented on src/fheroes2/gui/ui_tool.cpp
> +        LocalEvent::RegisterCycling( {}, {} );
`ColorCycling::registerDrawing()` does nothing in this case, it never unregisters the handlers.

2023-09-16 08:55 UTC, oleg-derevenetz commented on src/engine/localevent.h
> +        RegisterCycling( {}, {} );
Since `ColorCycling::registerDrawing()` should unregister the handlers in this case, I suppose this method should do something different.

2023-09-16 11:24 UTC, ihhub commented on src/fheroes2/gui/ui_tool.cpp
> +        LocalEvent::RegisterCycling( {}, {} );
Yes, you are right. The code is a mess here.

2023-09-16 11:46 UTC, Districh-ru requested changes
Hi @ihhub. I left two comments. Could you please take a look when you have time.

2023-09-16 11:46 UTC, Districh-ru commented on src/fheroes2/gui/statusbar.cpp
>      }
`fitToOneRow(()` already compares text width and `_roi.width` and returns from the function if `originalTextWidth <= maxWidth`.
IMHO this condition is redundant and we can leave only `text->fitToOneRow( _roi.width );`. If the text fits the `_roi.width` the `fitToOneRow()` will do nothing to it.

2023-09-16 11:46 UTC, Districh-ru commented on src/fheroes2/gui/statusbar.cpp
> +    const fheroes2::Rect messageRoi{ _roi.x + ( _roi.width - text->width() ) / 2, _roi.y, text->width(), text->height() };
We can cache the `text->width()` because it is used two times here.

2023-09-16 17:08 UTC, oleg-derevenetz reviewed
Hi @ihhub I just left a few questions, could you please take a look when you have time?

2023-09-16 17:08 UTC, oleg-derevenetz commented on src/engine/screen.cpp
> +            _postprocessing();
The same question - if `_postprocessing` is not set, we will get the `std::bad_function_call` here.

2023-09-16 17:08 UTC, oleg-derevenetz commented on src/engine/screen.cpp
> +            _postprocessing();
The same question - if `_postprocessing` is not set, we will get the `std::bad_function_call` here.

2023-09-16 17:08 UTC, oleg-derevenetz commented on src/fheroes2/gui/ui_tool.cpp
> +        RenderProcessor::instance().registerRenderers( [this]() { preRender(); }, [this]() { postRender(); } );
Shouldn't we unregister them in the destructor?

2023-09-17 07:14 UTC, Districh-ru approved these changes

2023-09-17 10:37 UTC, oleg-derevenetz approved these changes
Hi @ihhub what bothered me the most was that the pre/post-renderers should be registered and unregistered in one place, otherwise, later the logic will be unclear and it will be difficult to maintain, so I made the appropriate changes. Plus small changes that limit the ability to create and copy certain classes. Please take a look when you have time.

2023-09-17 12:07 UTC, ihhub commented
@oleg-derevenetz , your changes look great. Thank you!

2023-09-17 12:08 UTC, merged