Hero related code cleanup
ihhub/fheroes2 pull request #7763
Opened 2023-09-16 07:05 UTC by ihhub

- do not use empty structures **KingdomCastles** and **KingdomHeroes** as they doing literally nothing. It is hard to handle different variable types.
- change gold income logic for AI. It is better to avoid any floating point calculation errors
- do some code clean up in Heroes class to make the code human readable

2023-09-16 16:33 UTC, oleg-derevenetz approved these changes

2023-09-17 07:05 UTC, Districh-ru requested changes
Hi, @ihhub. I left one minor comment about function naming. Could you please take a look in your spare time.

2023-09-17 07:05 UTC, Districh-ru commented on src/fheroes2/game/difficulty.h
> +    double GetGoldIncomeBonusForAI( const int difficulty );
Since we are renaming this function we can name it from the lower character.
```suggestion
    double getGoldIncomeBonusForAI( const int difficulty );
```

2023-09-17 07:40 UTC, Districh-ru approved these changes

2023-09-17 07:40 UTC, merged