Implement roads placing in map editor.
ihhub/fheroes2 pull request #7772
Opened 2023-09-18 18:56 UTC by Districh-ru

This PR implements base Editor roads placing including roads connection.

![изображение](https://github.com/ihhub/fheroes2/assets/113276641/ab4b56ab-c6ef-4f7f-9c18-ede81f24728e)

TODO: We may combine some road images to make new roads connections possible, e.g. the "X" cross, the "(" and ")" turns.
A very simple Erase tool for only one tile is implemented in this PR for test purposes.

2023-09-22 00:37 UTC, ihhub commented
Hi @Districh-ru , please fix merge conflicts here.

2023-09-22 03:35 UTC, Districh-ru commented
> Hi @Districh-ru , please fix merge conflicts here.

Hi, @ihhub , done)
I'll add undo/redo for roads a little later.

2023-09-23 06:12 UTC, Districh-ru commented
I'm marking this PR as draft until #7796 and #7806 are merged.

2023-09-24 13:09 UTC, ihhub requested changes
Hi @Districh-ru , I put several comments in this pull request. Would you mind to take a look at them when you have time?

2023-09-24 13:09 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +            _redraw |= REDRAW_GAMEAREA | REDRAW_RADAR;
I think we need to **always** set these 2 flags no matter what. In this case what if we declare a const variable at the top of this file and use it instead of declaring this equation every time? We can call it something like **mapUpdateFlags**.

2023-09-24 13:09 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +            Maps::setRoadOnTile( tile, true );
In theory we do not always update tiles while calling this method so we don't need to redraw in these cases. **Maps::setRoadOnTile()** method can return `bool` stating if the operation was successful.

2023-09-24 13:09 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +            const fheroes2::ActionCreator action( _historyManager );
Please put this variable under the below if-condition and also the redraw flags must be set there as well.

2023-09-24 16:46 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +        tile.setRoad( setRoad );
Hi, @ihhub, it is a good solution for the cases when no possible road sprite is available - there will never be a tile marked a road without a road sprite. :)

2023-09-24 17:25 UTC, Districh-ru commented on src/fheroes2/maps/ground.cpp
> +    if ( allowExtraImages && Rand ::Get( 6 ) == 0 ) {
Ops...

2023-09-24 17:26 UTC, Districh-ru commented on src/fheroes2/maps/ground.cpp
>      // Terrain image main contain an extra image (rock, flowers, crack, etc.).
Sure, it sounds better.)

2023-09-24 17:30 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +                tile.setTerrain( Maps::Ground::getRandomTerrainImageIndex( ground, true ), false, false );
We are not forcing, but only allowing. :)
While generating terrains we can place a terrain with or without an extra object. But for placing roads we need terrain without extra objects: road cannot lay over a crack, a rock or a flower. :)
That is why I added this condition with is false only for roads placing (and for streams placing in future).

2023-09-24 18:17 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +    void setRoadOnTile( Tiles & tile, const bool setRoad )
Yea!

2023-09-24 18:17 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +    void updateRoadSpritesAround( const Maps::Tiles & centerTile, const int32_t centerToRectBorderDistance, const bool onlyNotMarkedAsRoad, const bool fromEdgesToCenter )
Sure)

2023-09-24 18:18 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +            updateRoadSpritesAround( tile, 2, true, true );
I made a separate function and combined these two `bool` conditions.

2023-09-24 18:19 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +            _redraw |= REDRAW_GAMEAREA | REDRAW_RADAR;
Done)

2023-09-24 18:21 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +            Maps::setRoadOnTile( tile, true );
Yes, we do nothing for water tiles and if road already exists.
I made the same changes for road erasing.

2023-09-24 18:21 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +            const fheroes2::ActionCreator action( _historyManager );
Done.

2023-09-25 05:01 UTC, ihhub requested changes
Hi @Districh-ru , I left few more minor comments here. Could you please check them in your spare time?

2023-09-25 16:12 UTC, Districh-ru commented on src/fheroes2/maps/ground.h
> +        uint16_t getRandomTerrainImageIndex( const int groundId, const bool allowExtraImages );
Hi, @ihhub, sure. This is a bit longer but easier to understand.

2023-09-25 16:13 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +                // We can do this because we have Direction::Bottom.
Done)

2023-09-25 16:16 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +        if ( setRoad == tile.isRoad() || ( setRoad && tile.GetGround() == Ground::WATER ) ) {
Yes, we can do this.

2023-09-25 16:16 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles.cpp
> +    this->_updateRoadFlag();
Sure)

2023-09-26 00:48 UTC, ihhub approved these changes

2023-09-26 13:56 UTC, Branikolog commented
Hi, @Districh-ru !
I've made a couple of tests comparing your work with the original editor... And I'm a little frustrated the original editor has so many flaws regarding roads construction. You implementation is really close and sometimes even better, than the original editor, where roads tend to be combined into a mess often. I expect really much work regarding roads in the future. 😅 
Here're some minor issues I've find.
I heard, that placing water should erase roads, but this happened not for all brushes. Is this aspect just postponed for the future?

https://github.com/ihhub/fheroes2/assets/55348946/9bdae9ef-1b0a-4f5d-a262-64ef212d0b8a

Also, placing a road inside such squares changes nothing, but the upper road is being cut a bit:

https://github.com/ihhub/fheroes2/assets/55348946/99fae3cb-271a-42a8-aeb0-43d67e566b5f

2023-09-26 17:02 UTC, Districh-ru commented
Hi, @ihhub, to address the second @Branikolog's issue I implemented a method to get the tile before the changes were made stored in `MapAction::_before` vector to restore the tile.
I plan to use this function in terrain editor to set ground more properly on the tiles where the user requested ground cannot be properly placed.
Could you please check if it is properly implemented when you have time?

2023-09-26 23:42 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +            }
Hi @Districh-ru , this approach works only is the action detects changes and saves this particular tile. However, it might not be always the case. The problem is in this part of the code:
```cpp
        if ( imageIndex == 255U ) {
            if ( !tile.isRoad() ) {
                // After update this tile should not contain a road sprite. We remove it.
                tile.removeObjects( MP2::OBJ_ICN_TYPE_ROAD );
            }

            return;
        }
```
The tile is not marked as a road because the image which is stored on this tile is not the main road image. However, we remove all MP2::OBJ_ICN_TYPE_ROAD images from this tile. The correct way would be to check associated tiles around the current tile and then do the action. For example, in my case a tile has image index 27, which I assume linked to image 28. So what we need to do is to verify this and only then remove the image.

What do you think?

2023-09-27 15:05 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +            }
Hi, @ihhub, thanks for the suggestion!
The changes in "history_manager" code are reverted. I'll do these changes when I start to polish the terrains editor.

2023-09-28 11:13 UTC, ihhub commented
Hi @Districh-ru , is it correct that we are going to address @Branikolog comments in a separate PR?

2023-09-29 15:08 UTC, merged

2023-09-29 15:08 UTC, ihhub commented
@Districh-ru , awesome work! Well done!