Add historical changes support for the Editor
ihhub/fheroes2 pull request #7779
Opened 2023-09-20 04:02 UTC by ihhub

relates to #6845

2023-09-20 17:22 UTC, Districh-ru requested changes
Hi, @ihhub, I tested the undo/redo feature and I like how it works. It could be easily used for all new editor actions.
I only found one issue with the radar update on undo/redo and left a couple of comments about it. Could you please check them when you have time.

Also currently we can make the unlimited number of undo history records. Maybe we should limit the history manager maximum size to, in example, 100 records. What do you think?

2023-09-20 20:59 UTC, oleg-derevenetz reviewed
Hi @ihhub I just left a few questions, could you please take a look when you have time?

2023-09-20 20:59 UTC, oleg-derevenetz commented on src/fheroes2/editor/history_manager.cpp
> +                world.GetTiles( tile.GetIndex() ) = std::move( temp );
It looks a bit odd - both here and in the `undo()` method below temporary tile is created first and then it is moved to the `world`. Why not just copy the `tile` to the `world` directly?

2023-09-20 20:59 UTC, oleg-derevenetz commented on src/fheroes2/editor/history_manager.cpp
> +            // If an exemption happens here then something is very wrong with the code.
```suggestion
            // If an exception happens here then something is very wrong with the code.
```

2023-09-20 20:59 UTC, oleg-derevenetz commented on src/fheroes2/editor/history_manager.h
> +        std::vector<std::unique_ptr<Action>> _actions;
What do you think about imposing some kind of sane limit on the action history size? For example, ~500 or ~1000 actions? Or do you think that there is no need for this?

2023-09-20 20:59 UTC, oleg-derevenetz commented on src/fheroes2/game/game_hotkeys.cpp
> +            = { HotKeyCategory::WORLD_MAP, gettext_noop( "hotkey|redo last action" ), fheroes2::Key::KEY_R };
BTW, why all editor's hotkeys are going to the `WORLD_MAP` category? Is this some kind of temporary solution?

2023-09-20 20:59 UTC, oleg-derevenetz commented on src/fheroes2/maps/maps_tiles.h
> +        }
And in C++20 we can just use the [default comparisons](https://en.cppreference.com/w/cpp/language/default_comparisons) :)

2023-09-21 14:19 UTC, ihhub commented on src/fheroes2/game/game_hotkeys.cpp
> +            = { HotKeyCategory::WORLD_MAP, gettext_noop( "hotkey|redo last action" ), fheroes2::Key::KEY_R };
Actually, no. I will move it to a separate category.

2023-09-21 14:19 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.h
> +        }
The biggest problem as we don't compare every member in this class :(

2023-09-21 14:21 UTC, ihhub commented on src/fheroes2/editor/history_manager.cpp
> +                world.GetTiles( tile.GetIndex() ) = std::move( temp );
**operator=** was not specified in order to avoid any tiles to be duplicated in the game by any dev mistake. However, the Editor requires it. I was thinking to keep it this wat but I am fine to allow the copy.

2023-09-21 14:29 UTC, oleg-derevenetz commented on src/fheroes2/editor/history_manager.cpp
> +                world.GetTiles( tile.GetIndex() ) = std::move( temp );
I'm OK with this. Will you find it appropriate to add some comment regarding this (to minimize the surprise), but it's up to you.

2023-09-21 14:34 UTC, ihhub commented on src/fheroes2/editor/history_manager.cpp
> +                world.GetTiles( tile.GetIndex() ) = std::move( temp );
It is done.

2023-09-21 15:23 UTC, Districh-ru approved these changes

2023-09-21 17:08 UTC, oleg-derevenetz commented on src/fheroes2/editor/history_manager.h
> +        }
I recommend to add

```cpp
assert( _actions.size() <= maxAction );
```

after that `if` clause just in case.

2023-09-22 00:36 UTC, oleg-derevenetz approved these changes

2023-09-22 00:37 UTC, merged