Hungarian translation update part 04
ihhub/fheroes2 pull request #7838
Opened 2023-09-28 20:32 UTC by big4billy

More translations and corrections till "MIDI"

2023-10-03 08:07 UTC, big4billy commented
Dear Admins, @ihhub @zenseii 

We plan to complete the whole Hungarian translation till milestone 1.0.10. I already have all the translations offline, so I just need to put (copy&paste) in pull requests in 400 peaces parts. Is it possible? May you help us with quick reviews?

Kind regards!

2023-10-06 14:03 UTC, ihhub requested changes
Hi @big4billy , I left one comment here. Could you please take a look?

2023-10-06 14:27 UTC, big4billy commented on files/lang/hu.po
> +
Sure. Removed

2023-10-07 02:09 UTC, ihhub approved these changes

2023-10-07 09:48 UTC, merged

2023-10-07 09:49 UTC, ihhub commented
@big4billy , thank you very much for this update!