AI should avoid splitting troops on easy difficulty
ihhub/fheroes2 pull request #7846
Opened 2023-09-30 04:34 UTC by idshibanov

Might be up for discussion but removing the optimization should make battles easier.

2023-09-30 09:53 UTC, oleg-derevenetz approved these changes
Technically this change is OK. However, I do not know how much this will make the task easier for inexperienced players on easy difficulties :)

2023-10-01 14:01 UTC, ihhub requested changes
Hi @idshibanov , I left 2 minor comments here. Could you please take a look?

Also I don't believe that it makes any significant difference in the gameplay but let's hear others.

2023-10-01 14:01 UTC, ihhub commented on src/fheroes2/game/difficulty.cpp
> +    return difficulty > Difficulty::NORMAL;
I recommend to still use switch case so it is easier to read the code and it handles all possible difficulties (if any new in the future as well).

2023-10-03 12:18 UTC, Branikolog approved these changes

2023-10-05 14:45 UTC, ihhub approved these changes

2023-10-05 14:45 UTC, merged

2023-10-05 14:45 UTC, ihhub commented
@idshibanov , huge thanks for this change!