Add functionality to place monsters in the Editor
ihhub/fheroes2 pull request #7852
Opened 2023-10-01 12:34 UTC by ihhub

relates to #6845

https://github.com/ihhub/fheroes2/assets/19829520/6185e4ee-d468-495e-9af2-1a95c6744956

2023-10-01 13:46 UTC, Districh-ru requested changes
Hi, @ihhub, I left a couple comments after a quick check. Could you please check them in your spare time.

Also there is a mouse cursor issue. We may address it in a new PR: if you open the quick info or any dialog (in example quit dialog) the cursor is set to the POINTER after the dialog is closed and returned back to the monster icon after you move it to the nearby tile. (In future we could show a POINTER cursor above the places were the monster can not be placed).

https://github.com/ihhub/fheroes2/assets/113276641/747050ea-c69d-459c-b91e-238f9a1a160f


And a question to discuss - maybe after choosing a monster we should open the `Dialog::SelectCount()` with the default monster count set by default?

2023-10-01 13:46 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +                _redraw |= mapUpdateFlags;
We should not place a monster if `_editorPanel.getMonsterId() == Monster::UNKNOWN`. Currently the Editor places a 0 (zero) count of peasants. :)

2023-10-01 13:46 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +                Maps::setMonsterOnTile( tile, _editorPanel.getMonsterId(), 0 );
An added monster always has zero uid and ICN object type.
```
******* Tile info *******
Tile index      : 260, point: (8, 7)
UID             : 0
MP2 object type : 152 (Отряд)
ICN object type : 0 (UNKNOWN)
image index     : 2
```

2023-10-01 14:21 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +                Maps::setMonsterOnTile( tile, _editorPanel.getMonsterId(), 0 );
This is bug which is present in the game as well.

2023-10-01 14:29 UTC, ihhub commented
Hi @Districh-ru , it is better to set monster count separately while you click on the monster. Doing it right after choosing a monster will limit your ability to quickly set them. I know that 0 doesn't mean 0 monsters but we can find a solution later.

2023-10-01 14:30 UTC, ihhub commented
@Districh-ru , I am aware of the cursor issue. This is due to cursor updater class. I am still thinking how to address it properly in a separate PR.

2023-10-01 14:40 UTC, ihhub commented
Hi @zenseii , could you please review the new text dialogs here?

2023-10-01 14:53 UTC, Districh-ru approved these changes
Well done!
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/f1c8338f-f5fa-4ad8-a438-3e1ca26eb26a)

In future we should also add random monster placing.

2023-10-04 08:14 UTC, Branikolog commented
Hi, @ihhub 
I've made a couple of tests. 👍 
The only tiny thing I would like to see is turning monster cursor into pointer while hovering over edges of the adventure map. But I suppose it is related to the issue you've discussed above with @Districh-ru . It's not urgent for sure. Everything else works well.

2023-10-04 13:41 UTC, ihhub commented
Hi @Branikolog , I addressed your concern regarding the cursor.

2023-10-04 13:47 UTC, Branikolog commented
Thanks, @ihhub !
There's an issue with positioning of the cursor after right click now:

https://github.com/ihhub/fheroes2/assets/55348946/1c4ec6b7-612f-41fc-9be0-0e74da73108f

2023-10-04 13:49 UTC, ihhub commented
Hi @Branikolog , this is the same problem which @Districh-ru spotted. This will be addressed in the separate pull request.

2023-10-04 14:11 UTC, Branikolog commented
@ihhub 
I mostly concern about the **position** of the cursor (creature sprite) and the highlighted cell of the map:
![image](https://github.com/ihhub/fheroes2/assets/55348946/142a5a7d-b986-42c1-b6ef-fecdfc74251b)
Creature sometimes appears on the map really far from the cursor.

The issue spotted by @Districh-ru , relates to showing the pointer cursor instead of creature sprite. Correct me if I'm wrong.

But I want to apologize, the issue I'm talking about is valid for a previous implementation too.

2023-10-04 18:48 UTC, Districh-ru commented
> Creature sometimes appears on the map really far from the cursor.

I also observe this issue: it appears only with disabled software cursor - the upper left corner of the monster sprite is set as the cursor center.
With software cursor turned on this issue does not appear - the center of monster sprite is set as the cursor center.

2023-10-05 12:35 UTC, ihhub commented
Hi @Branikolog , I fixed the issue with the cursor. Please take a look.

2023-10-05 13:41 UTC, merged