Combat victory window creature position
ihhub/fheroes2 pull request #7859
Opened 2023-10-03 20:30 UTC by paprocki

Fix #1611
Margins fixed and displaying starts from the right of the window so overlapping is more appealing. 
To test with different army sizes you can setup a hardcoded army in battle_dialogs.cpp, l. 500:
```
    Troops killedcustom = Troops(); 
    Troop troop = Troop(Monster::AIR_ELEMENT, 10);
    Troop troopBoar = Troop( Monster::BOAR, 10 );

    killedcustom.PushBack( troop, troop.GetCount() );
    killedcustom.PushBack( troopBoar, 5 );

    const Troops killed1 = killedcustom; //_army1->GetKilledTroops();
```
    
I'm new to c++ and memory management on this level, so if you could be extra alert on that while reviewing, then that would be great.

2023-10-04 15:25 UTC, ihhub commented
Hi @paprocki , please fix code style issues spotted by GitHub Actions.

2023-10-04 15:35 UTC, ihhub requested changes
Hi @paprocki , I left one comment about one optimization. Could you please take a look?

2023-10-04 15:35 UTC, ihhub commented on src/fheroes2/army/army.cpp
> +Troops Troops::GetReversed() const
We should avoid create a new method just to cover a single case in the code. We can archive the same by doing like this at line 57 of **army_ui_helper.cpp** file:
```cpp
Troops reversedTroops;

if ( troops.Size() > 0 ) {
    for ( size_t i = troops.Size() - 1; ; ) {
        const Troop * monster = troops.Get( i );
        reversedTroops.PushBack( *monster, monster->GetCount() );

        if ( i > 0 ) {
            --i;
        }
        else {
            break;
        }
    }
}
```

Troops class is very... bad written at the moment but this is better to complicate it even more.

2023-10-04 20:34 UTC, paprocki commented on src/fheroes2/army/army_ui_helper.cpp
> +        cx += width;
Fixed

2023-10-04 20:35 UTC, paprocki commented on src/fheroes2/army/army.cpp
> +Troops Troops::GetReversed() const
I did as requested.

2023-10-04 20:38 UTC, paprocki commented
I changed a bit more code than intended, because i saw an error with the compact army. Please review the code again

2023-10-05 14:43 UTC, ihhub requested changes
Hi @paprocki , I left few more comments here. Would you mind to check them?

2023-10-05 14:43 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +        if ( troops.Size() > 0 ) {
We can remove this check since at line 39 we have a similar check. To be safe we can replace this if-condition by an assertion:
```cpp
assert( troops.Size() > 0 );
for ( size_t i = troops.Size() - 1;; ) {
...
```

2023-10-05 14:43 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +        }
We should do this way to avoid extra calculations:
```cpp
const Troop * troop = nullptr;
if ( !isCompact ) {
    troop = troops.GetTroop( slot );
}
else {
    troop = reversedTroops.GetTroop( slot - slotOffset );
}
```

However, this pounders a question: do we need **reversedTroops** at first place?

Essentially, **reversedTroops** is just a reversed version of **troops** so accessing the first element of **reversedTroops** is accessing the last element of **troops**. In this case will this work
```cpp
troop = troops.GetTroop( troops.Size() - slot + slotOffset );
```
?

2023-10-05 14:43 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +                int OffsetX = -14;
Please name the variables from a non-capital letter as per our coding standard.

2023-10-05 14:43 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +            if ( slotsToSkip == 0 ) {
Please merge else with if.

2023-10-05 14:43 UTC, ihhub commented on src/fheroes2/army/army_ui_helper.cpp
> +        chunk = static_cast<int32_t>( ( width - marginLeft ) / ( count + ( slotsToSkip * 2 ) ) );
Could you please change the input argument type `const uint32_t width` into `const int32_t width` for this function as well as for **drawMultipleMonsterLines**? After this we don't need to do the static casting here and at line 81.

2023-10-08 08:14 UTC, ihhub approved these changes

2023-10-08 09:45 UTC, Districh-ru requested changes
Hi, @paprocki, good work!
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/709e9093-bc8b-47e5-aad9-33d991e152a5)

I left several comments regarding variables type consistency. Could you please take a look in your spare time.

2023-10-08 09:45 UTC, Districh-ru commented on src/fheroes2/army/army_ui_helper.cpp
> +    int slotOffset = 1;
The same comment as above :)

```suggestion
    int32_t slotsToSkip = 1;

    int32_t slotOffset = 1;
```

2023-10-08 09:45 UTC, Districh-ru commented on src/fheroes2/army/army_ui_helper.cpp
> +        chunk = static_cast<int32_t>( ( width - marginLeft ) / ( count + ( slotsToSkip * 2 ) ) );
Here we can also make variable types consistent and cast only `count` which is `uint32_t`:
```suggestion
        int32_t marginLeft = 18;
        chunk = ( width - marginLeft ) / ( static_cast<int32_t>( count ) + ( slotsToSkip * 2 ) );
```

2023-10-08 09:45 UTC, Districh-ru commented on src/fheroes2/army/army_ui_helper.cpp
> +        slots = troops.Size() + slotsToSkip;
`slots` is already made equal to `troops.Size()` in 48 line, so here we may speed-up the computations and do not call `.Size()` once more:
```suggestion
        slots += static_cast<size_t>( slotsToSkip );
```

2023-10-08 09:45 UTC, Districh-ru commented on src/fheroes2/army/army_ui_helper.cpp
> +            int y = cy + offsetY + monster.y();
`fheroes2::Blit()` accepts `int32_t` so to avoid unnecessary type conversions lets set these variables type to `int32_t`.
```suggestion
            int32_t x = ( cx - ( monster.width() / 2 ) ) + offsetX;
            int32_t y = cy + offsetY + monster.y();
```

2023-10-08 09:45 UTC, Districh-ru commented on src/fheroes2/army/army_ui_helper.cpp
>              const int offsetY = 28 - monster.height();
To be consistent with `fheroes2::Blit()` input variables types lets set the ёште32_её type for this variable:
```suggestion
            const int32_t offsetY = 28 - monster.height();
```

2023-10-08 09:45 UTC, Districh-ru commented on src/fheroes2/army/army_ui_helper.cpp
> +            int offsetX = -14;
The same comment as previous:
```suggestion
            int32_t offsetX = -14;
```

2023-10-08 11:01 UTC, Branikolog approved these changes

2023-10-09 03:10 UTC, Districh-ru approved these changes

2023-10-09 13:56 UTC, merged

2023-10-09 13:56 UTC, ihhub commented
@paprocki , huge thanks for this fix!