WIP: remove old Text classes
ihhub/fheroes2 pull request #7864
Opened 2023-10-04 10:49 UTC by ihhub

2023-10-05 17:57 UTC, Districh-ru requested changes
Hi @ihhub, I checked most of the changed places and found one issue with the lost empty line (`\n`). Could you check it when you have time.

One pixel text shift in some places is OK for me.
I also found some places to make minor optimizations, but this PR is big enough. Its better to make optimizations later in separate PRs and not only for the text render.

2023-10-05 17:57 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_levelup.cpp
> +    std::string header = _( "%{name} has gained a level.\n%{skill} +1" );
Was the empty text string removed for some reason? :)
```suggestion
    std::string header = _( "%{name} has gained a level.\n\n%{skill} +1" );
```

2023-10-07 09:29 UTC, ihhub commented on src/fheroes2/dialog/dialog_levelup.cpp
> +    std::string header = _( "%{name} has gained a level.\n%{skill} +1" );
Nope. I think my rendering was off with the old text. I fixed it.

2023-10-07 09:59 UTC, Districh-ru approved these changes
Well done!
Later I'll do some rendering optimizations for dialogs. For example we can optimize `dialog_armyinfo` like we did for the castle well: do not fully render all unchanged texts for every monster animation frame.

2023-10-07 13:04 UTC, Branikolog approved these changes

2023-10-07 13:12 UTC, merged