Fix German translation No.2
ihhub/fheroes2 pull request #7867
Opened 2023-10-05 12:54 UTC by erazortt

Fix the German translation, Part 2 of 8
See also https://github.com/ihhub/fheroes2/issues/7860
And https://github.com/ihhub/fheroes2/pull/7865

2023-10-05 20:30 UTC, Laserlicht requested changes

2023-10-05 20:30 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "Zauberkraft"
Can you verify if the text fits in the area? As far as I know this was extra abbreviated.

2023-10-05 20:30 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "Zauberpunkte"
same here

2023-10-05 20:30 UTC, Laserlicht commented on files/lang/de.po
> +"Holet sich Eure gefallenen Städte zurück und dringt dann in das "
```suggestion
"Holet Eure gefallenen Städte zurück und dringt dann in das "
```

2023-10-05 20:30 UTC, Laserlicht commented on files/lang/de.po
> +"Mission vor dem ersten Tag des siebten Monats, oder das Koenigreich wird "
```suggestion
"Mission vor dem ersten Tag des siebten Monats, oder das Königreich wird "
```

2023-10-05 20:30 UTC, Laserlicht commented on files/lang/de.po
> +"Beseitiget alle Fiende und verliert nicht Euren Helden Jarkonas VI."
```suggestion
"Beseitigt alle Feinde und verliert nicht Euren Helden Jarkonas VI."
```

2023-10-05 21:02 UTC, erazortt commented on files/lang/de.po
> +msgstr "Zauberpunkte"
I checked that as well: 
![grafik](https://github.com/ihhub/fheroes2/assets/4786333/a22b1212-0c2e-4d22-80bc-eada12d9a475)

2023-10-05 21:07 UTC, Laserlicht approved these changes

2023-10-06 20:41 UTC, Laserlicht approved these changes

2023-10-07 00:11 UTC, erazortt commented
@Laserlicht I think you need to approve the pull request, not only the changes. Or who can approve review?

2023-10-07 04:13 UTC, Laserlicht commented
Yea, but I haven't the permission. :)

2023-10-07 05:03 UTC, ihhub commented
@erazortt , a pull request can be approved an merged only by the core team (collaborators and owners). Please be patient as the team has limited time resources.

2023-10-07 09:48 UTC, ihhub approved these changes

2023-10-07 09:50 UTC, merged

2023-10-07 09:50 UTC, ihhub commented
@erazortt , a bunch of thanks for this update!