Fix German translation No.3
ihhub/fheroes2 pull request #7868
Opened 2023-10-05 12:55 UTC by erazortt

Fix the German translation, Part 3 of 8
See also https://github.com/ihhub/fheroes2/issues/7860
And https://github.com/ihhub/fheroes2/pull/7865

2023-10-05 20:34 UTC, Laserlicht requested changes

2023-10-05 20:34 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "Clicken um die nächste Stadt anzuzeigen."
```suggestion
msgstr "Klicken um die nächste Stadt anzuzeigen."
```

2023-10-05 20:34 UTC, Laserlicht commented on files/lang/de.po
> +msgstr "Clicken um die vorherige Stadt anzuzeigen."
```suggestion
msgstr "Klicken um die vorherige Stadt anzuzeigen."
```

2023-10-07 16:31 UTC, Laserlicht commented on files/lang/de.po
> +#, fuzzy
remove this?

2023-10-07 17:13 UTC, erazortt commented on files/lang/de.po
> +#, fuzzy
yeah right, this and the next fuzzy can go. I just pushed an update.

2023-10-08 14:18 UTC, ihhub requested changes
Hi @erazortt , I left 2 comments here. Would you mind to take a look at them?

2023-10-08 14:18 UTC, ihhub commented on files/lang/de.po
>  msgstr "%{name} hat eine neue Stufe erreicht."
Please translate the missing part as this string was recently modified. The full string is
```
"%{name} has gained a level.\n\n%{skill} +1"
```
Notice two **\n** symbols.

2023-10-08 14:18 UTC, ihhub commented on files/lang/de.po
> +msgstr "Ihr könnt lernen entweder:"
Please translate the missing part as this string was recently modified. The full string is
```
"You may learn either:\n%{skill1}\nor\n%{skill2}"
```
Notice three **\n** symbols and also **or** in between them.

2023-10-08 14:42 UTC, erazortt commented on files/lang/de.po
> +msgstr "Ihr könnt lernen entweder:"
ok done

2023-10-08 14:55 UTC, erazortt commented on files/lang/de.po
> +msgstr "Ein Feld wählen, das keine Objekt enthält."
I also just translated this new string and the one just above, which both were just added by another commit to master.

2023-10-08 14:55 UTC, ihhub approved these changes

2023-10-08 15:11 UTC, merged

2023-10-08 15:11 UTC, ihhub commented
@erazortt , thanks a lot for this update!