Fix German translation No.5
ihhub/fheroes2 pull request #7870
Opened 2023-10-05 12:57 UTC by erazortt

Fix the German translation, Part 5 of 8
See also https://github.com/ihhub/fheroes2/issues/7860
And https://github.com/ihhub/fheroes2/pull/7865

2023-10-05 20:39 UTC, Laserlicht approved these changes

2023-10-15 13:02 UTC, ihhub requested changes
Hi @erazortt ,  I left one question here. Can you please take a look at it?

2023-10-15 16:56 UTC, erazortt commented on files/lang/de.po
> +"Ihr habt die Geister besiegt und könn5 die Mine wieder in Betrieb nehmen."
Yeah, that was a typo. Fixed it.

2023-10-16 12:58 UTC, merged

2023-10-16 12:59 UTC, ihhub commented
@erazortt , thank you so much for the update!