Fix German translation No.6
ihhub/fheroes2 pull request #7871
Opened 2023-10-05 12:58 UTC by erazortt

Fix the German translation, Part 6 of 8
See also https://github.com/ihhub/fheroes2/issues/7860
And https://github.com/ihhub/fheroes2/pull/7865

2023-10-05 20:42 UTC, Laserlicht requested changes

2023-10-05 20:42 UTC, Laserlicht commented on files/lang/de.po
> +"Ueberraschung, einen gesunden, grünen, vierblättrigen Klee."
```suggestion
"Überraschung, einen gesunden, grünen, vierblättrigen Klee."
```

2023-10-18 15:14 UTC, ihhub approved these changes

2023-10-18 15:14 UTC, merged

2023-10-18 15:14 UTC, ihhub commented
@erazortt , huge thanks for this update!