Fix German translation No.7
ihhub/fheroes2 pull request #7872
Opened 2023-10-05 12:59 UTC by erazortt

Fix the German translation, Part 7 of 8
See also https://github.com/ihhub/fheroes2/issues/7860
And https://github.com/ihhub/fheroes2/pull/7865

2023-10-05 20:45 UTC, Laserlicht requested changes

2023-10-05 20:45 UTC, Laserlicht commented on files/lang/de.po
> +"Lagerfeuer zeiht Ihr einige Holzscheite aus dem Haufen. Dabei bemerkt Ihr, "
```suggestion
"Lagerfeuer zieht Ihr einige Holzscheite aus dem Haufen. Dabei bemerkt Ihr, "
```

2023-10-05 20:45 UTC, Laserlicht commented on files/lang/de.po
> +"Auf einem Huegel bietet sich Euch ein lächerlicher Anblick. Eine Fee "
```suggestion
"Auf einem Hügel bietet sich Euch ein lächerlicher Anblick. Eine Fee "
```

2023-10-24 14:50 UTC, ihhub requested changes
Hi @erazortt , I left one comment here. Could you please check it when you have time?

2023-10-24 14:50 UTC, ihhub commented on files/lang/de.po
>  #, fuzzy
Please remove this line.

2023-10-24 17:59 UTC, erazortt commented on files/lang/de.po
>  #, fuzzy
done

2023-10-25 00:44 UTC, ihhub approved these changes

2023-10-25 00:44 UTC, merged

2023-10-25 00:44 UTC, ihhub commented
@erazortt , thank you so much for the update!