WIP: Implement erase tool im editor
ihhub/fheroes2 pull request #7902
Opened 2023-10-07 18:49 UTC by Districh-ru

Relates to #6845 

This PR implements the following features of the Erase tool in the editor:
- [x] monsters erase;
- [x] erase in area;
- [ ] selection of object types to erase.

2023-10-15 02:08 UTC, ihhub commented
@Mr-Bajs , any improvements will be done later. We need to add functionality first.

2023-10-15 06:02 UTC, Districh-ru commented
> Great. A would be nice to have-feature would be a select all/deselect all button.

@Mr-Bajs, as a quick solution the select/deselect of all other (except the current) object types is implemented by the long left mouse button press. A video of this feature has been added to the PR description.

2023-10-15 06:05 UTC, Districh-ru commented
Hi, @zenseii, could you please check correctness of the new added "right-press" phrases when you have time.

2023-10-15 06:08 UTC, ihhub requested changes
Hi @Districh-ru , I left several comments in this pull request. Would you mind to take a look at them?

2023-10-15 06:08 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +        tile.removeObjects( objectIcnType );
This code will remove only objects on this tile. While now it is valid it won't be correct to multi-tile objects. We can leave it as it is for now.

2023-10-15 06:08 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +        tile.setAsEmpty();
This might not be true. For example, we remove a hero that stands right behind a windmill. Then this tile should be marked as Windmill, not as empty. At very least please add a TODO comment for the future.

2023-10-15 06:56 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
Hi @ihhub, sure.

2023-10-15 06:57 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.h
> +        std::array<uint8_t, 8> _eraseButtonObjectTypes{ Maps::ObjectEraseMask::TERRAIN_OBJECTS, Maps::ObjectEraseMask::CASTLES,   Maps::ObjectEraseMask::MONSTERS,
Done.

2023-10-15 06:57 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +        tile.removeObjects( objectIcnType );
I left a TODO to implement this when we will deal with the multi-tile objects.

2023-10-15 07:02 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +        tile.setAsEmpty();
I places a `switch()` to reset tile object and metadata only for the given ICN object types.
For heroes - currently in editor we do not place them as an ordinary heroes and set the ICN object type as mini-hero, which is not true for the game case. So I left a TODO to deal with the hero erase when we implement objects and find how to properly place them among with the mini-hero ICN data.

2023-10-15 08:19 UTC, ihhub requested changes
Hi @Districh-ru , I added few more comments here. Could you please check them?

2023-10-15 08:19 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    listbox.SetCurrent( heroType != -1 ? heroType : 0 );
Just to avoid any hardcoded values I suggest to use this condition:
```cpp
std::max( heroType, 0 )
```

2023-10-15 08:19 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +                    // fheroes2::Blit( selection, 0, 0, display, _eraseButtonsRect[i].x - 2, _eraseButtonsRect[i].y - 2, selection.width(), selection.height() );
Please remove this commented out line.

2023-10-15 08:19 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.h
> +    enum ObjectEraseMask : uint8_t
This enumeration does not contain masks but flags. Should we name it as **ObjectErasureFlag**? Or even better **ObjectErasureType**?

2023-10-15 08:19 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.h
> +        TERRAIN_OBJECTS = 0x01,
This entry needs elaboration as all objects can be considered as terrain. Do you mean the rest of objects such as cracks, dwellings, trees, mountains and etc?

2023-10-15 08:19 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.h
> +    bool eraseOjects( Tiles & tile, const uint8_t objectsToErase );
Should we name **objectsToErase** as **objectTypesToErase** to avoid any confusion with object IDs?

2023-10-15 08:19 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +    bool removeObjectFromTile( Tiles & tile, const MP2::ObjectIcnType objectIcnType )
It should be named as **removeObjectTypeFromTile** to imply that multiple objects can be removed, not only one.

2023-10-15 08:19 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            // const fheroes2::Sprite & selection = fheroes2::AGG::GetICN( ICN::TERRAINS, 9 );
Please remove this commented out line.

2023-10-15 08:19 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.cpp
> +    const bool isNewGroundWater = newGround == Ground::WATER;
A very nit picking comment: please add parenthesis for the condition. This will slightly improve readability.

2023-10-15 08:41 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    listbox.SetCurrent( heroType != -1 ? heroType : 0 );
Sure.

2023-10-15 08:42 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +                    // fheroes2::Blit( selection, 0, 0, display, _eraseButtonsRect[i].x - 2, _eraseButtonsRect[i].y - 2, selection.width(), selection.height() );
Ow, I tested with selection marks and forgot to remove the two test lines. :(
Done.

2023-10-15 08:43 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.h
> +    enum ObjectEraseMask : uint8_t
Let it be `ObjectErasureType`.

2023-10-15 08:47 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.h
> +        TERRAIN_OBJECTS = 0x01,
I left a comment about this entry. Currently this is for all objects, that are placed using terrain palette (cracks, trees, mountains, mines, dwellings, ...). After we implement placing these object types and the correct erase function for them we can add new types: dwellings, mines, non-action objects, etc.

2023-10-15 08:47 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.h
> +    bool eraseOjects( Tiles & tile, const uint8_t objectsToErase );
Sure!

2023-10-15 08:48 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +    bool removeObjectFromTile( Tiles & tile, const MP2::ObjectIcnType objectIcnType )
Yes, it will be more concrete.

2023-10-15 08:48 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles.cpp
> +    const bool isNewGroundWater = newGround == Ground::WATER;
Yes, there are many `=` in this line.

2023-10-15 12:48 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.h
> +        TERRAIN_OBJECTS = 0x01,
In this case should we make this enumeration as **uint32_t** as we are going to add more items? **uint16_t** or **uint32_t** makes no difference in terms of performance and memory.

2023-10-15 12:58 UTC, ihhub reviewed
Hi @Districh-ru , I put 2 more style relates comments only. The rest looks good to me.

2023-10-15 12:58 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.h
> +        const std::array<uint8_t, 8> _eraseButtonObjectTypes{ Maps::ObjectErasureType::TERRAIN_OBJECTS, Maps::ObjectErasureType::CASTLES,
I suggest to put this member just before **_interface** as this is the only member being **const**.

2023-10-15 12:58 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.h
> +        uint8_t _eraseMask{ Maps::ObjectErasureType::ALL_OBJECTS };
Since we use **type** in other places should we name this member and the corresponding method as **_eraseTypes**?

2023-10-15 13:18 UTC, Branikolog commented
Hi, @Districh-ru !
Nice work on editor!
I've find a few issues, could you, please, look, if they are relevant to fix within this PR?

![image](https://github.com/ihhub/fheroes2/assets/55348946/07887323-fcb4-4682-bd30-5f6644adaa55)
I'm not sure about the wording. "Off" seems not proper to me. Maybe "erase from" or even "erase away from". I'm counting on @zenseii participation on discussing this sentence. :)

![image](https://github.com/ihhub/fheroes2/assets/55348946/6e7580a1-f5d9-464d-bdc1-6bf03b17f8fa)
Not sure about the word "Toggle" here. Yellow name looks a little too long. Maybe simple "Erase xxx object" would be shorter and easier to perceive?

New settings window breaks the editor UI right now.

https://github.com/ihhub/fheroes2/assets/55348946/b7bfe375-9477-44be-973e-948d26ef242b

2023-10-15 14:18 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.h
> +        TERRAIN_OBJECTS = 0x01,
Yes, lets make it uint32_t for the future improvements.

2023-10-15 14:18 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.h
> +        const std::array<uint8_t, 8> _eraseButtonObjectTypes{ Maps::ObjectErasureType::TERRAIN_OBJECTS, Maps::ObjectErasureType::CASTLES,
Sure

2023-10-15 14:19 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.h
> +        uint8_t _eraseMask{ Maps::ObjectErasureType::ALL_OBJECTS };
Yes, I also renamed the method from `getEraseMask()` to `getEraseTypes()`.

2023-10-15 14:20 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                    // To select object types for erase we copy object buttons.
Hi, @zenseii, thanks a lot for correcting the spelling!

2023-10-15 14:25 UTC, Districh-ru commented
Hi, @Branikolog,  the phrases have been corrected as suggested by @zenseii.

> New settings window breaks the editor UI right now.

Yes, settings dialog was never tweaked for the editor and has these bugs (for interface change) for the long time. :(
We will polish the editor settings dialog later after we add the editor specific settings functionality (like the tile pass-ability).

2023-10-15 14:37 UTC, ihhub approved these changes

2023-10-15 14:56 UTC, Branikolog approved these changes
I personally OK with both "erasing of castle objects" and "the erasure of castle objects".
Leaving the last word to @zenseii in this question. :)

2023-10-16 00:49 UTC, merged

2023-10-16 00:50 UTC, ihhub commented
@Districh-ru , awesome work!