P6
ihhub/fheroes2 pull request #7920
Opened 2023-10-10 02:39 UTC by Nad-SK

2023-10-10 14:48 UTC, Nad-SK commented
PASSED!!!! Thanks @ihhub

2023-10-10 14:59 UTC, Nad-SK commented
> Hi, @Nad-SK. Please reduce the amount of changes by 28 lines. I also left two other comments. Please have a look.

Hi, @zenseii, how to reduce the changes line??? Open .po file and delete the translate strings???

2023-10-10 15:55 UTC, Nad-SK commented on files/lang/vi.po
> +"fheroes2/releases"
Done

2023-10-10 15:55 UTC, Nad-SK commented on files/lang/vi.po
> +msgid "Undo your last action. Press again to redo the action."
Done

2023-10-10 15:58 UTC, Nad-SK commented
Hi, @zenseii. It's OK??? Please take a look.

2023-10-15 13:06 UTC, ihhub commented
Hi @Nad-SK , just a small suggestion not related to this pull request: please avoid using an extensive amount of punctuation such as ??? because some people might think this as an aggressive manner of request :) A single question mark is sufficient.

2023-10-24 15:07 UTC, ihhub requested changes
Hi @Nad-SK , I left few comments here. Would you mind to take a look at them?

2023-10-26 14:29 UTC, ihhub approved these changes

2023-10-26 14:29 UTC, merged

2023-10-26 14:30 UTC, ihhub commented
@Nad-SK , thank you so much for the update!