Army split dialog
ihhub/fheroes2 pull request #7956
Opened 2023-10-17 22:06 UTC by lioror

fixing this [issue:](https://github.com/ihhub/fheroes2/issues/7551)

2023-10-22 20:44 UTC, lioror commented
can someone please assist?

2023-11-15 14:56 UTC, ihhub commented
Hi @lioror , please fix code style issues.

2023-11-16 10:47 UTC, lioror commented
@ihhub done

2023-11-16 13:33 UTC, ihhub requested changes
Hi @lioror, I left multiple comments in this pull request. Could you please take a look at them and also attach screenshots of this dialog after your changes in the first message of this PR aka PR's description?

Moreover, please correct the title of your pull request to reflect the changes you've done. Right now it is too generic and tells nothing what this PR is about.

2023-11-16 13:33 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +    std::string msg( _( "How many %{tropps} to move?" ) );
This sentence is misspelled.

2023-11-16 13:33 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +    fheroes2::Text text2( _( "Fast separation into slots:" ), fheroes2::FontType::normalWhite() );
Please name variables with human readable names. Having var1, var2 and etc doesn't make the code readable. Having `title` and `slotSeparationText` variable names is better.

2023-11-16 13:33 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +int Dialog::ArmySplitTroop( uint32_t freeSlots, const uint32_t redistributeMax, uint32_t & redistributeCount, bool & useFastSplit, const std::string & name )
Please rename the new input argument as `troopName` as right now it is not obvious what the variable stands for.

2023-11-16 13:33 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +    fheroes2::Text text( msg, fheroes2::FontType::normalWhite() );
This variable can be **const**.

2023-11-16 13:33 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +    fheroes2::Text text2( _( "Fast separation into slots:" ), fheroes2::FontType::normalWhite() );
This variable can be **const**.

2023-11-16 13:33 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +    fheroes2::Text text( msg, fheroes2::FontType::normalWhite() );
Could you please explain why we are changing the text and also reflect this in the description of this pull request?

2023-11-16 13:33 UTC, ihhub commented on src/fheroes2/army/army_bar.cpp
> +                = Dialog::ArmySplitTroop( ( freeSlots > overallCount ? overallCount : freeSlots ), maxCount, redistributeCount, useFastSplit, troopFrom.GetName() );
**GetName()** returns singular form of a creature. Then the final message is going to be `How many Peasant to move?` which is incorrect.

2023-11-17 15:38 UTC, lioror commented
Here is the new look:
![image](https://github.com/ihhub/fheroes2/assets/6975903/c389f4c2-fcf5-4b8c-9f83-f00ce170ca88)

2 lines:
![image](https://github.com/ihhub/fheroes2/assets/6975903/50836250-ec8d-4b2b-a9ce-4c45749f8159)

2023-11-17 15:39 UTC, lioror commented on src/fheroes2/army/army_bar.cpp
> +                = Dialog::ArmySplitTroop( ( freeSlots > overallCount ? overallCount : freeSlots ), maxCount, redistributeCount, useFastSplit, troopFrom.GetName() );
It actually gets the plural form

2023-12-13 15:39 UTC, ihhub requested changes
Hi @lioror , I put several comments here. Could you please take a look when you have time?

2023-12-13 15:39 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +    const int32_t text2Height = slotSeparationText.rows( BOXAREA_WIDTH ) * slotSeparationText.height();
Please avoid using cryptic names for variables. `textHeight` and `text2Height` don't bring clarify to readers of the code. This variable can be named as **bodyHeight** while `textHeight` is actually **titleHeight**.

2023-12-13 15:39 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +    sel.SetPos( fheroes2::Point( pos.x + 70, pos.y + 13 + textHeight ) );
Please create a new variable `textTopOffset` and use it instead of hardcoded value 13. We should avoid using hardcoded values in the code.

2023-12-13 15:39 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +    const fheroes2::Text title( msg, fheroes2::FontType::normalWhite() );
Please name the variable as **titleText** and then use `std::move` to avoid object copying within `fheroes2::Text` constructor.

2024-01-16 08:54 UTC, lioror commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +            vrts[i] = fheroes2::Rect( center + offset + deltaXStart + i * deltaX, pos.y + textTopOffset + titleHeight + bodyHeight + 45, spriteWidth, sprites[i].height() );
how to fix?

2024-02-16 02:26 UTC, Branikolog commented
Hi, @lioror , @zenseii and @ihhub .

English translation looks acceptable except the cases, when troops name is cut into two strings (I find it a little not pleasant visually, but still working for me).
![image](https://github.com/ihhub/fheroes2/assets/55348946/ce22023e-0112-4f87-b014-6b39d02720ed)

But I'm afraid for other translations there could be issues with the noun form (like Russian has) which is not supported by the engine yet.
Maybe adding just a header with the creature name and leaving the dialog text as it is (without creature name) would be easier 
to translate and more uniform?

2024-02-16 04:30 UTC, Branikolog approved these changes
For me it looks and works well. 👍

2024-03-06 00:44 UTC, ihhub approved these changes

2024-03-06 00:44 UTC, merged

2024-03-06 00:45 UTC, ihhub commented
@lioror , thank you so much for your contribution to the project!