Add support for the future new heroes
ihhub/fheroes2 pull request #7958
Opened 2023-10-18 12:40 UTC by ihhub

relates to #6845

2023-10-22 08:27 UTC, Districh-ru commented on src/fheroes2/heroes/heroes.cpp
> +                return fheroes2::AGG::GetICN( ICN::MINIPORT, BRAX );
```suggestion
                return fheroes2::AGG::GetICN( ICN::MINIPORT, BRAX - 1 );
```

2023-10-22 08:54 UTC, Districh-ru requested changes
Hi, @ihhub, I quickly reviewed the PR and left two comments. Could you please check them in your spare time.
I'll do a more thorough test of this PR a little later.

2023-10-22 08:54 UTC, Districh-ru commented on src/fheroes2/heroes/heroes.cpp
> +    push_back( new Heroes( Heroes::UNKNOWN, Race::KNGT ) );
Why do we store data for the **UNKNOWN** hero? Is it ever used? :)
The `isValid()` method returns false for the UNKNOWN hero. So, IMHO, we can remove this data and get data from this vector this way (line 2078): `return ( *this )[hid - 1];`.
What do you think?

2023-10-22 08:54 UTC, Districh-ru commented on src/fheroes2/heroes/heroes.cpp
> +                return fheroes2::AGG::GetICN( ICN::MINIPORT, BRAX );
ICN index for the small portrait of Debug hero should also be deducted by 1.
```suggestion
                return fheroes2::AGG::GetICN( ICN::MINIPORT, BRAX - 1 );
```

2023-10-23 11:56 UTC, Branikolog commented
Hi, @ihhub 

I've started testing your PR recently.

Here's the issue I've found:

https://github.com/ihhub/fheroes2/assets/55348946/4101d504-c1aa-4f1f-9545-3ddf66be7640

[Heroes test.zip](https://github.com/ihhub/fheroes2/files/13069707/Heroes.test.zip)

2023-10-23 12:07 UTC, Branikolog commented
@ihhub 

Debug Hero from old save has wrong portrait now:

PR:

![image](https://github.com/ihhub/fheroes2/assets/55348946/3d4f3a3c-d434-4bf1-8437-e8217d5dd727)

Master:

![image](https://github.com/ihhub/fheroes2/assets/55348946/34887254-134c-406f-986e-689243ca93bb)

[AUTOSAVE.zip](https://github.com/ihhub/fheroes2/files/13069840/AUTOSAVE.zip)

2023-10-23 13:24 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +                return fheroes2::AGG::GetICN( ICN::MINIPORT, BRAX );
Hi @Districh-ru , I don't understand. Why we need to change the ICN value as this pull request does not touch images?

2023-10-23 13:38 UTC, ihhub commented
> Hi, @ihhub
> 
> I've started testing your PR recently.
> 
> Here's the issue I've found:
> 
> [Heroes test.zip](https://github.com/ihhub/fheroes2/files/13069707/Heroes.test.zip)
It is fixed. It was a bug in inverse logic.

2023-10-23 13:45 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +                return fheroes2::AGG::GetICN( ICN::MINIPORT, BRAX );
Ah, my bad. You are absolutely right!

2023-10-23 13:46 UTC, Branikolog commented
@ihhub 

> It is fixed. It was a bug in inverse logic.

I'll continue testing then, once it is compiled. 👍

2023-10-24 11:36 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left one minor and one optional suggestion, please take a look when you have time.

2023-10-25 02:12 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +    push_back( new Heroes( Heroes::UNKNOWN, Race::KNGT ) );
Hi @Districh-ru , let's keep this first entry in the vector to have consistency with hero IDs as it is easier to debug the code. Later we should find another way how to avoid storing all this hero information as a more or less static array but it is beyond this pull request.

2023-10-25 16:21 UTC, Districh-ru commented on src/fheroes2/heroes/heroes.cpp
> +    push_back( new Heroes( Heroes::UNKNOWN, Race::KNGT ) );
Okay, let's do it this way.

2023-10-25 16:34 UTC, Districh-ru approved these changes

2023-10-26 01:23 UTC, merged