Fix the random generator usage by the non-Arena code
ihhub/fheroes2 pull request #7967
Opened 2023-10-20 01:44 UTC by oleg-derevenetz

fix #7964

2023-10-20 23:37 UTC, oleg-derevenetz commented
Hi @fheroes2bugs

Regarding #7964: I believe that in this PR I have eliminated the main reasons for the discrepancies that led to a different outcome of the battle when performing the same actions by the AI and the human player. According to my tests, now the outcome of the battle should be the same if the AI and the human player perform **exactly** the same actions (by "exactly" I mean maximum accuracy - for example, if you cast a spell on a wide unit, that spell must be cast on exactly the same cell of that unit).

Regarding #7965: according to my tests with this PR, the battle outcome is the same when performing absolutely the same actions in Debug and Release builds, if both Release and Debug builds were created from the same source code using the same compiler. Just in case, let me remind again that the same battle outcome in case of using different compilers is not currently guaranteed. And of course, this is not guaranteed in the case of using different versions of the game (built from different versions of the source code), because changes are regularly made to the logic of the combat AI.

2023-10-21 01:52 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left a set of comments and questions. Could you please take a look at them once you have free time?

2023-10-21 01:52 UTC, ihhub commented on src/fheroes2/battle/battle_action.cpp
> +Battle::TargetsInfo Battle::Arena::GetTargetsForSpell( const HeroBase * hero, const Spell & spell, const int32_t dst, bool applyRandomMagicResistance,
A tiny code perfection: please add **const** to `bool applyRandomMagicResistance` as you did in other methods.

2023-10-21 01:52 UTC, ihhub commented on src/fheroes2/battle/battle_arena.h
> +        TargetsInfo GetTargetsForSpell( const HeroBase * hero, const Spell & spell, const int32_t dst );
We can make this method **inlined** since it contains only one code line.

2023-10-21 01:52 UTC, ihhub commented on src/fheroes2/battle/battle_action.cpp
> +                DEBUG_LOG( DBG_BATTLE, DBG_TRACE, "target: " << static_cast<TargetUnderlyingType>( target ) << ", damage: " << damage << ", hit: " << hit )
This line should be under ifdef block as well since it defines a type which is used here.

2023-10-21 01:52 UTC, ihhub commented on src/fheroes2/battle/battle_command.h
> +        static constexpr std::integral_constant<CommandType, CommandType::MOVE> MOVE{};
I am just trying to understand this part of the code. We have an enumeration with items. We declare a set of structures (**struct integral_constant**) which is later used to interpret constructor in-place for **emplace_back()** calls (`Command( std::integral_constant<CommandType, cmd> /* tag */, const Types... params )`) and push necessary parameters into the **Command** class. Is my understanding correct?

2023-10-21 01:52 UTC, ihhub commented on src/fheroes2/battle/battle_command.h
> +                (void)( ( *this << params, dummy ) = ... );
Could you please explain how this part of the code works? I understand that we are calling **Command & operator<<( const int val );** but I am confused with dummy variable.

2023-10-21 03:39 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_action.cpp
> +Battle::TargetsInfo Battle::Arena::GetTargetsForSpell( const HeroBase * hero, const Spell & spell, const int32_t dst, bool applyRandomMagicResistance,
Hi @ihhub this argument cannot be const because it will be changed inside this method in certain circumstances.

2023-10-21 03:42 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_action.cpp
> +                DEBUG_LOG( DBG_BATTLE, DBG_TRACE, "target: " << static_cast<TargetUnderlyingType>( target ) << ", damage: " << damage << ", hit: " << hit )
@ihhub DEBUG_LOG macro is already under such an ifdef internally.

2023-10-21 03:54 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_command.h
> +        static constexpr std::integral_constant<CommandType, CommandType::MOVE> MOVE{};
@ihhub Yes. This is constructor template that allows to check the number of parameters at compile time depending on the command type. Since this check should be performed at compile time, the command type should be known at compile time, i.e. it should be a non-type template parameter. Since we cannot just set such a parameter for the constructor using an angle braces like `<CommandType::MOVE>foo()`, especially during various `emplace()` calls, the first parameter serves as a tag to let the template argument deduction figure out this non-type template parameter depending on type of the first argument.

2023-10-21 04:00 UTC, ihhub commented on src/fheroes2/battle/battle_action.cpp
> +Battle::TargetsInfo Battle::Arena::GetTargetsForSpell( const HeroBase * hero, const Spell & spell, const int32_t dst, bool applyRandomMagicResistance,
Ah, my bad.

2023-10-21 04:07 UTC, ihhub commented on src/fheroes2/battle/battle_command.h
> +        static constexpr std::integral_constant<CommandType, CommandType::MOVE> MOVE{};
Thanks for the explanation!

2023-10-21 04:20 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_command.h
> +                (void)( ( *this << params, dummy ) = ... );
@ihhub this is the fold expression that expands into `(*this << params[0], dummy) = ((*this << params[1], dummy) = ((*this << params[2], dummy) = ( ... = ((*this << params[n-1], dummy) = (*this << params[n], dummy)))))`. On each stage, the comma operator works as follows: it evaluates its left part first, then it evaluates its right part and returns the result of its evaluation - that is, it puts the Nth param to `this` first and then returns the value of `dummy` which will be reassigned to `dummy` on the next stage and immediately returned, and so on.

2023-10-21 08:17 UTC, ihhub approved these changes

2023-10-21 08:17 UTC, merged

2023-10-21 08:17 UTC, ihhub commented
@oleg-derevenetz , thank you so much for these useful changes!