WIP: Implement artifacts placing in Editor
ihhub/fheroes2 pull request #7969
Opened 2023-10-20 14:21 UTC by Districh-ru

Relates to https://github.com/ihhub/fheroes2/issues/6845
This PR implements artifact placing and erasing in editor. It also fixes information dialog for the Spell Scroll artifact and adds spell selection for this artifact.

https://github.com/ihhub/fheroes2/assets/113276641/15d593ed-cf82-4789-8ef8-33bad07fcb21

2023-10-22 11:53 UTC, ihhub requested changes
Hi @Districh-ru , I left several comments here. Could you please take a look once you have time?

2023-10-22 11:53 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    if ( includeRandomSpells ) {
Ultimate artifacts cannot be placed on the map as they do not have images (see ICN::OBJNARTI). We should exclude them from the Editor as well as Magic Book.

2023-10-22 11:53 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +        if ( artifact.GetID() == Artifact::SPELL_SCROLL ) {
Do we need to make a spell selection a scroll while placing it? Should we do this after putting it on the Adventure Map and changing its information?

2023-10-22 11:53 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +                            // First four ultimate artifacts have no map images. Show "Ult ART" image instead.
We should fix Ultimate artifact rendering. For now let's just put a TODO to do not forget.

2023-10-22 11:53 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +                        fheroes2::Copy( mainImage, 0, 0, image, shadowImageWidth, 0, mainImageWidth, mainImageHeight );
In the future we need to come up with a function in this file which will glue given images into one for objects that occupy more than 1 tile. Either we can add a TODO comment here or we can create a function.

2023-10-22 12:34 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                if ( _icnVsSprite[id].size() == 60 ) {
Sure!

2023-10-22 12:39 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                        Text text( "spell", FontType::smallWhite() );
Yes, I like this solution, thanks.
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/dcd3e7ce-82b7-48c9-95c1-b4aca0ae9bc0)

I left "lv." text and made it translatable. Later we will make the same texts for random items:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/6b003990-421a-460e-bc47-8a4854c849fb)

2023-10-22 12:50 UTC, Districh-ru commented on src/fheroes2/resource/artifact.h
> +        // Editor-related random artifacts.
In original game it is a little mess with these artifacts. On map Random artifact (any level) has the same object ICN ID as the Magic Book. To avoid this types overlap it is better to add a new entry for `RANDOM_ALL_LEVELS` artifact. We cannot have two descriptions for the Magic Book and Random Artifact with the same ID.
We can replace all "Dummy #" artifacts with "Ultimate" and "Random level #" artifact entries. But there is no free place for Random (all levels) artifact. :(
What is you opinion how we could better separate Magic Book and Random artifact but use the same ID for them to avoid new entries creation?

2023-10-22 12:53 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    if ( includeRandomSpells ) {
Done.
I made them placeable for test and also it can be a case when the map maker will want to place an ultimate artifact on the map protected by strong monsters and also place an other (diggable) Ultimate Artifact on the map.

2023-10-22 12:59 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +        if ( artifact.GetID() == Artifact::SPELL_SCROLL ) {
It is done in the original map editor, but it takes more actions to place a Spell Scroll with a certain spell.
If a map maker wants to place a spell scroll then it's very likely he will also want to select a spell for it. If he does not want to make a selection right now he can simply press OKAY and a random spell will be set for the scroll.

Hello, @Branikolog, what is your opinion about when we should select a spell for the Spell Scroll artifact when we want to select and place it on map?

2023-10-22 13:02 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +                            // First four ultimate artifacts have no map images. Show "Ult ART" image instead.
Done.
But if we do not plan to make them placeable on map like ordinary artifacts then these sprites are not necessary.

2023-10-22 13:03 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +                        fheroes2::Copy( mainImage, 0, 0, image, shadowImageWidth, 0, mainImageWidth, mainImageHeight );
This function will be implemented in the next "Castles placing in Editor" PR and this code will be replaced with a function.
I left a TODO.

2023-10-22 13:15 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                        Text text( "spell", FontType::smallWhite() );
Once the image is generated there is no way to translate the text. How about we use **normal yellow or white font** and just render a number as 1, 2, 3, 4 and 5?

2023-10-22 13:18 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                        Text text( "spell", FontType::smallWhite() );
Something like this:

![image](https://github.com/ihhub/fheroes2/assets/19829520/14de64a2-7400-48e1-b13c-4d784ba1b0ca)

2023-10-22 13:21 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                        Text text( "spell", FontType::smallWhite() );
Sure)
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/5a4488db-52d6-414d-ba92-94ee63fa77ae)

2023-10-22 13:22 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                        Text text( "spell", FontType::smallWhite() );
Nice!

2023-10-22 13:31 UTC, Districh-ru commented on src/fheroes2/resource/artifact.h
> +        // Editor-related random artifacts.
The Random and Ultimate artifacts set their own object IDs and I only added new ICN IDs for these artifacts so the logic should work fine because it is based on object Ids. :)

2023-10-23 14:08 UTC, ihhub commented on src/fheroes2/resource/artifact.h
> +        // Editor-related random artifacts.
The original Editor does not save random artifacts as **OBJ_ARTIFACT** but as **OBJ_RANDOM_ARTIFACT, OBJ_RANDOM_ARTIFACT_TREASURE, OBJ_RANDOM_ARTIFACT_MINOR and OBJ_RANDOM_ARTIFACT_MAJOR** so logically there is no overlap between Magic Book and Random Artifact.

I think we should rename Dummy into proper Random Artifacts. They aren't used anywhere else.

Magic Book does not have its own image for the Adventure Map (sadly). I believe it should but this is another topic for discussion. What we can do is to modify ICN::OBJNARTI array to add 2 empty images for Magic Book. Then IDs for random artifact will always correspond to their images. The only problem such a change would cause is PoL artifacts not having proper images on the Adventure Map. In this case we can add a fix for map loading and for saves. I can handle this change if you need my help.

What do you think about this?

2023-10-23 14:08 UTC, ihhub commented on src/fheroes2/spell/spell.cpp
> +    { gettext_noop( "Random spell" ), 0, 0, 0, 67, 0, gettext_noop( "Random selected any level spell." ) },
Hi @zenseii , could you please review these lines?

2023-10-23 14:11 UTC, ihhub commented on src/fheroes2/resource/artifact.h
> +        // Editor-related random artifacts.
For this matter should we use **OBJ_RANDOM_ARTIFACT_XXX** for random artifacts?

2023-10-23 17:45 UTC, Districh-ru commented on src/fheroes2/resource/artifact.h
> +        // Editor-related random artifacts.
> The original Editor does not save random artifacts as **OBJ_ARTIFACT** but as **OBJ_RANDOM_ARTIFACT, OBJ_RANDOM_ARTIFACT_TREASURE, OBJ_RANDOM_ARTIFACT_MINOR and OBJ_RANDOM_ARTIFACT_MAJOR** so logically there is no overlap between Magic Book and Random Artifact.

Yes, our editor does the same:
<details><summary>maps_tiles_helper.cpp, lines 3085-3104</summary>

```cpp
        switch ( artifactId ) {
        case Artifact::RANDOM_ALL_LEVELS:
            tile.SetObject( MP2::OBJ_RANDOM_ARTIFACT );
            break;
        case Artifact::RANDOM_1_LEVEL:
            tile.SetObject( MP2::OBJ_RANDOM_ARTIFACT_TREASURE );
            break;
        case Artifact::RANDOM_2_LEVEL:
            tile.SetObject( MP2::OBJ_RANDOM_ARTIFACT_MINOR );
            break;
        case Artifact::RANDOM_3_LEVEL:
            tile.SetObject( MP2::OBJ_RANDOM_ARTIFACT_MAJOR );
            break;
        case Artifact::RANDOM_ULTIMATE:
            tile.SetObject( MP2::OBJ_RANDOM_ULTIMATE_ARTIFACT );
            break;
        default:
            tile.SetObject( MP2::OBJ_ARTIFACT );
            break;
        }
```

</details> 

But the right mouse button artifact info and icon is not the same for the Magic Book and for the Random artifact. That is why I made a new entry for it instead of making hacks into right mouse button events handler. ... And placed all other random artifacts aside. :)

> I think we should rename Dummy into proper Random Artifacts. They aren't used anywhere else.

Sure, lets remove the Dummies and place Ult, Rand1, Rand2 and Rand3 instead. 

> Magic Book does not have its own image for the Adventure Map (sadly). I believe it should but this is another topic for discussion. What we can do is to modify ICN::OBJNARTI array to add 2 empty images for Magic Book. Then IDs for random artifact will always correspond to their images. The only problem such a change would cause is PoL artifacts not having proper images on the Adventure Map. In this case we can add a fix for map loading and for saves. I can handle this change if you need my help.

Yes, in future I was also planing to make ability to place the Magic Book on a map. So we should leave it.
I think we should place the `Artifact::RANDOM_ALL_LEVELS` after the PoL artifacts and do not change their indexes.
The new expansion artifacts will be added after this entry. Yes, this random artifact index will be not close to other random artifacts ... but is it so needed?
I just don't want to add new confusion that PoL artifact indexes will be shifted but SW will not. :)

2023-10-24 12:26 UTC, Branikolog commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +        if ( artifact.GetID() == Artifact::SPELL_SCROLL ) {
Hi, @Districh-ru !

I suggest selecting a spell right after we place an artifact on the adventure map.
Right now we select the spell and all scrolls we place have the same one, I suppose. Am I right?

https://github.com/ihhub/fheroes2/assets/55348946/bff22da7-d0e5-435c-a0fb-cc8b0498435d

It would be better to initiate spell selection dialog right after the scroll was placed on the adventure map, so we can place some different scrolls in a row.

2023-10-24 15:12 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +        if ( artifact.GetID() == Artifact::SPELL_SCROLL ) {
Hi, @Branikolog!
Yes, you are right. Your suggestion is reasonable. I'll do it in the next commit.

2023-11-03 12:17 UTC, ihhub commented
Hi @Districh-ru , could you please update this pull request with the latest changes for the Editor?

2023-11-05 01:40 UTC, ihhub commented
This pull request should be updated and merged after #8016.

2023-11-05 10:42 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +                        fheroes2::Copy( mainImage, 0, 0, image, shadowImageWidth, 0, mainImageWidth, mainImageHeight );
This was implemented recently :)

2023-11-05 10:42 UTC, ihhub commented on src/fheroes2/spell/spell.cpp
> +    { gettext_noop( "Random spell" ), 0, 0, 0, 67, 0, gettext_noop( "Random selected any level spell." ) },
We can revert these changes.

2023-11-05 12:18 UTC, Districh-ru commented on src/fheroes2/spell/spell.cpp
> +    { gettext_noop( "Random spell" ), 0, 0, 0, 67, 0, gettext_noop( "Random selected any level spell." ) },
> We can revert these changes.

The random spells will not be reverted. Only Random Artifact entries will be reverted.

2023-11-05 16:16 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +        if ( artifact.GetID() == Artifact::SPELL_SCROLL ) {
Hello, @Branikolog, this PR was updated: spells for the Spell Scroll are now selected when placing this artifact on map. Also a temporary sprite for the Magic Book was added.
Could you please review this PR when you have time.

2023-11-06 09:26 UTC, Branikolog commented
Hi, @Districh-ru 
I've found a few small issues. I'm not sure all of them are related to the current PR. I can create new topics for them in issues thread, if you wish.
So first of all I noticed that some artifacts are aligned differently in the list:
![image](https://github.com/ihhub/fheroes2/assets/55348946/bdb3fa6c-3911-42b5-b9a4-3914564c157b)
Scroll seemed to be closer to the right edge of artifact column.
While the book is placed aligned to the left:
![image](https://github.com/ihhub/fheroes2/assets/55348946/eea6b123-47f5-45f3-8e1f-09f93c639b46)
UA artifact fell out of column at all:
![image](https://github.com/ihhub/fheroes2/assets/55348946/eb7b4b36-d8b9-45be-80d1-ce09c841a0e9)

I personally would love to have all artifacts aligned to the center of the column, since some of them have wide sprites, and some - thin (like scroll).


https://github.com/ihhub/fheroes2/assets/55348946/136da897-23c2-4b18-8275-d784587eca97


When cancelling scroll selection we can still place it on the adventure map. But the cursor does not switched to scroll. We should continue showing the artifact cursor of the last selected one.

2023-11-06 10:39 UTC, Districh-ru commented
Hi, @Branikolog!
> Hi, @Districh-ru I've found a few small issues. I'm not sure all of them are related to the current PR. I can create new topics for them in issues thread, if you wish. So first of all I noticed that some artifacts are aligned differently in the list: 

They are aligned the same way as on the map. Spell scroll is right-aligned in the tile, while the magic book currently is left-aligned. We can fix it in and discuss a better sprite for the magic book a separate issue/PR.
All artifact sprites contains of two tile-images: main and shadow (to the left). The Ultimate artifact does not has a shadow, so it is centered, but not aligned with all other two-tile artifacts. In the last commit I temporary added an empty image for the shadow to this artifact to align it.
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/932d8dae-edaa-40ff-86d3-e38a662cf057) ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/f2e8de69-3e78-426b-91e4-af14619f3fad)

> When cancelling scroll selection we can still place it on the adventure map. But the cursor does not switched to scroll. We should continue showing the artifact cursor of the last selected one.

It is fixed in the last commit for Artifacts, Monsters, Treasures and Heroes.
Could you please check it in your spare time.

2023-11-06 12:44 UTC, Branikolog commented
@Districh-ru 

>We should return to sprites alignment after we implement placing more complex sprites, like mountains, Watchtowers, Castles and others to find a better way to display them.
Making a quick fix only for the artifacts might break rendering other objects, that are not implemented at the moment, but will use the seme sprite generation function.

Sure! A fix for just UA is enough as it looked the worst.

Cursor-artifact should be also shown in a case we return to artifact placing mode:

https://github.com/ihhub/fheroes2/assets/55348946/861ffe90-c0b4-4f03-b8c8-2b701382bc91

2023-11-06 14:02 UTC, Districh-ru commented
> Cursor-artifact should be also shown in a case we return to artifact placing mode:

@Branikolog, sure, fixed. :)

2023-11-06 14:21 UTC, Branikolog approved these changes
@Districh-ru 
Great!
Thanks for fixing this.

2023-11-06 18:50 UTC, ihhub commented on src/fheroes2/spell/spell.cpp
> +    { gettext_noop( "Random spell" ), 0, 0, 0, 67, 0, gettext_noop( "Random selected any level spell." ) },
My bad.

2023-11-06 19:58 UTC, ihhub requested changes
Hi @Districh-ru , I left a couple of comments here. Could you please take a look at them when you have time?

2023-11-06 19:58 UTC, ihhub commented on src/fheroes2/maps/map_object_info.cpp
> +        // Assign the Magic Book temporary made sprites.
Should we move this line before SPELL_SCROLL to be in a logical order with the enumeration?
```cpp
for ( uint32_t artifactId = Artifact::ARCANE_NECKLACE; artifactId < Artifact::MAGIC_BOOK; ++artifactId ) {
    addArtifactObject( artifactId, MP2::OBJ_ARTIFACT, artifactId * 2U - 1U );
}

// Assign the Magic Book temporary made sprites.
addArtifactObject( Artifact::MAGIC_BOOK, MP2::OBJ_ARTIFACT, 207U );

for ( uint32_t artifactId = Artifact::SPELL_SCROLL; artifactId < Artifact::ARTIFACT_COUNT; ++artifactId ) {
    addArtifactObject( artifactId, MP2::OBJ_ARTIFACT, artifactId * 2U - 1U );
}
```

2023-11-06 19:58 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +            for ( const Maps::TilesAddon & addon : currentTile.getTopLayerAddons() ) {
Please add an empty line above for easier readability.

2023-11-06 19:58 UTC, ihhub commented on src/fheroes2/spell/spell.cpp
> +    { gettext_noop( "Random spell" ), 0, 0, 0, 67, 0, gettext_noop( "Random selected any level spell." ) },
All spell names contains capital letters in their words. I suggest to use the same approach for Random Spells.

2023-11-06 19:58 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    // If we have the Price of Loyalty assets we nake a map sprite for the Magic Book artifact.
**nake** is misspelled.

2023-11-06 19:58 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            if ( _monsterType < 0 ) {
**setCustomCursor** function handles invalid cases. Is there a reason why we are doing the check here again as these cases aren't supposed to happen?

2023-11-06 19:58 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +        tile.setAsEmpty();
Please add a TODO comment as it might not be correct to do this. Consider this situation:
- put an artifact on a map
- put a Mine on the map that its top layer is on the same level as the artifact
- erase the artifact

I believe the tile will be marked as OBJ_NONE while in reality it should be OBJ_NON_ACTION_MINES.

#8019 add a logic to set tile's object type which is correlated to this logic.

2023-11-06 19:58 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +                if ( Maps::getObjectsByGroup( Maps::ObjectGroup::Artifact )[artifactType].metadata[0] == Artifact::SPELL_SCROLL ) {
This is risky. Please assert **artifactType** over the size of the returned array and logic check the type of the object.

2023-11-06 19:58 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +                        setObjectOnTile( tile, Maps::ObjectGroup::Artifact, _editorPanel.getArtifactType() );
This line of code can be moved outside the if-else-body and put before it since we don't have any rendering calls before setting the spell.

2023-11-06 19:58 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +    void setSpellScrollSpellId( Tiles & tile, const uint32_t spellId )
We can modify setSpellOnTile() function to handle OBJ_ARTIFACT and assert if the artifact is not SPELL_SCROLL. In this case we don't need a separate function to do the same thing..

2023-11-07 14:41 UTC, Districh-ru commented on src/fheroes2/maps/map_object_info.cpp
> +        // Assign the Magic Book temporary made sprites.
Hi, @ihhub, in original editor there is no Magic Book and PoL artifacts go right after the SW artifacts. Also we already brake the order not including "Dummy" artifacts. So I added the Magic Book to the end as a new map artifact.
Also maybe we should place Random artifacts in the start of the list, like in original editor.
@Branikolog what are your thought about the place for the Magic Book and Random artifacts?

2023-11-07 19:00 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            if ( _monsterType < 0 ) {
I did this change to `setCustomCursor()`. It can be reverted if you think that it is not good.

2023-11-07 19:01 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +        tile.setAsEmpty();
Sure, we need to better handle these cases and use other (new) function here.

2023-11-07 19:02 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +    void setSpellScrollSpellId( Tiles & tile, const uint32_t spellId )
You are right, thanks!

2023-11-07 19:52 UTC, ihhub commented on src/fheroes2/maps/map_object_info.cpp
> +        // Assign the Magic Book temporary made sprites.
Hi @Districh-ru , it doesn't matter how the list shows in the Editor as our artifact object list has no connection with the list there. My suggestion is to align with the enumeration for artifacts we have at the moment.

2023-11-07 20:10 UTC, ihhub requested changes
Hi @Districh-ru , I put a few more comment here. Could you please take a look at them when you have spare time?

2023-11-07 20:10 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +        if ( type < -1 || type >= static_cast<int32_t>( objectInfo.size() ) ) {
We should keep the original logic as it is more understandable even if we handle the **-1** case above.

2023-11-07 20:10 UTC, ihhub commented on src/fheroes2/maps/map_object_info.cpp
> +        // Assign the Magic Book temporary made sprites.
I also suggest to rename DUMMY into **UNUSED_83..86** so it will be clear what they are for, and update the corresponding comment.

2023-11-07 20:10 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +                    Maps::setSpellOnTile( tile, spellId );
**setSpellOnTile()** need the corresponding code to handle **MP2::OBJ_ARTIFACT**. It is missing at the moment.

2023-11-08 17:14 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +                    Maps::setSpellOnTile( tile, spellId );
Hi, @ihhub. The code is already there (lines 1428-1432) :)

https://github.com/Districh-ru/fheroes2/blob/e9ff79691f942290ac2bfdcbcc72d2aa23d9b376/src/fheroes2/maps/maps_tiles_helper.cpp#L1419-L1438

2023-11-08 18:57 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +                    Maps::setSpellOnTile( tile, spellId );
Oh, yes. I somehow totally missed this. My bad :(

2023-11-08 18:57 UTC, ihhub approved these changes

2023-11-08 18:58 UTC, merged

2023-11-08 18:58 UTC, ihhub commented
@Districh-ru , huge thanks for implementing this feature!