Fix the logic of purchasing a boat in shipyard
ihhub/fheroes2 pull request #7975
Opened 2023-10-21 14:56 UTC by ihhub

close #7970

2023-10-21 15:36 UTC, oleg-derevenetz commented on src/fheroes2/castle/castle.cpp
> +int Castle::getTileIndexToPlaceBoat() const
Hi @ihhub map indexes are usually `int32_t`, even in this function `index` is `int32_t`. It would be nice if this function followed the general logic and also returned `int32_t` instead of just `int`.

2023-10-21 15:37 UTC, oleg-derevenetz commented on src/fheroes2/castle/castle.cpp
> +    const int index = getTileIndexToPlaceBoat();
And accordingly, this variable should also be of type `int32_t`.

2023-10-21 15:59 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +int Castle::getTileIndexToPlaceBoat() const
Thanks for spotting it!

2023-10-21 20:03 UTC, oleg-derevenetz approved these changes

2023-10-22 06:04 UTC, Districh-ru requested changes
Hi, @ihhub, I left one comment regarding sea access check. Could you please take a look when you have time.

2023-10-22 11:34 UTC, Districh-ru approved these changes

2023-10-24 19:24 UTC, drevoborod commented
Now it's possible to buy a boat, but it's impossible to occupy it by a hero - it becomes unreacheable. And, of course, after that it's impossible to buy new boat, because there is one already. So, we have here some lock situation, which doesn't seem to be ok.

2023-10-24 19:38 UTC, oleg-derevenetz commented
Hi @drevoborod

> Now it's possible to buy a boat, but it's impossible to occupy it by a hero - it becomes unreacheable. And, of course, after that it's impossible to buy new boat, because there is one already. So, we have here some lock situation, which doesn't seem to be ok.

IIRC there is nothing we can do with this, because there is just one tile suitable for a boat near this castle and it is unreachable because of a tree. BUT this boat can be summoned once built, so it's still a progress.

2023-10-24 20:39 UTC, drevoborod commented
> P.S. In the original game there is funny behavior in this castle:
> DOSBox.0.74-2.1.Cpu.speed_.max.100.cycles.Frameskip.0.Program_.HEROES2.2023-10-24.22-50-20.mp4
> 
> There is no boat on the adventure map nearby, but there is a boat in the castle and Shipyard doesn't allow to buy another one.

Yes, I also checked the original game behaviuor and the result was same if there was already a shipyard on start; if there was no shipyard and I bought it myself, the message appeared (It's Knight castle but I don't think it matters): 
![изображение](https://github.com/ihhub/fheroes2/assets/10282847/8190ff8d-649b-470e-a84f-0383d23b681a)

2023-10-25 00:42 UTC, ihhub commented
Thanks @drevoborod !

2023-10-25 00:43 UTC, merged