Add ability to include any object to be placed on the Adventure Map
ihhub/fheroes2 pull request #7998
Opened 2023-10-28 13:24 UTC by ihhub

relates to #6845

2023-10-28 18:36 UTC, Districh-ru requested changes
Hi, @ihhub, I left several comments. Could you please take a look when you have time.

2023-10-28 18:36 UTC, Districh-ru commented on src/fheroes2/maps/map_object_info.cpp
> +    std::array<std::vector<Maps::ObjectInfo>, static_cast<size_t>( Maps::ObjectGroup::Group_Count ) + 1> objectData;
`Maps::ObjectGroup::Group_Count` represents the count of used object groups. The `Group_Count` is not used as the group so there is no need to add the `1`.
```suggestion
    std::array<std::vector<Maps::ObjectInfo>, static_cast<size_t>( Maps::ObjectGroup::Group_Count )> objectData;
```

2023-10-28 18:36 UTC, Districh-ru commented on src/fheroes2/maps/map_object_info.cpp
> +        }
Do we plan to place this artifact on the map?

2023-10-28 18:36 UTC, Districh-ru commented on src/fheroes2/maps/map_object_info.cpp
> +
We miss the Ultimate artifact:
```cpp
        {
            Maps::ObjectInfo object;
            object.objectType = MP2::OBJ_ARTIFACT;
            object.parts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNARTI, 164, fheroes2::Point{ 0, 0 }, MP2::OBJ_RANDOM_ULTIMATE_ARTIFACT, Maps::OBJECT_LAYER );

            objects.emplace_back( std::move( object ) );
        }

```

2023-10-28 18:36 UTC, Districh-ru commented on src/fheroes2/maps/map_object_info.cpp
> +        populateObjectData();
Should we populate ObjectData when Editor starts?
Or should we populate only the requested group instead of population all of them.
What do you think?

2023-10-29 13:57 UTC, ihhub commented on src/fheroes2/maps/map_object_info.cpp
> +
Hi @Districh-ru , Artifact enumeration does not have an Ultimate Artifact. It is introduced in #7969.

2023-10-29 13:58 UTC, ihhub commented on src/fheroes2/maps/map_object_info.cpp
> +        populateObjectData();
**populateObjectData()** populates data on a first call. We don't need to do any other changes. Please correct me if I am wrong.

2023-10-29 14:10 UTC, Districh-ru commented on src/fheroes2/maps/map_object_info.cpp
> +
Artifact enumeration also does not have other random artifacts that are introduced here. But they all exist in the game assets (OBJNARTI):
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/a4aae7e7-b07d-4788-b3ee-b9c11bda2ad1)

and we already have object types (`MP2::OBJ_RANDOM`...) for these artifacts (four random variants and one "Ult ART")
So we can add it here along with the four random artifacts, or we can add it later in #7969 :)

2023-10-29 14:13 UTC, Districh-ru commented on src/fheroes2/maps/map_object_info.cpp
> +        populateObjectData();
Yes, you are right, but do we need to populate all objects (in future there will be more of them) if a user wants to place only objects of one type now.
It is an optional suggestion, we can change this behavior in the future.

2023-11-02 01:01 UTC, ihhub commented
Hi @Districh-ru and @oleg-derevenetz , this PR is ready for your review.

2023-11-02 06:36 UTC, Districh-ru requested changes
Hi, @ihhub , I did a quick code review and left some comments. Could you please take a look when you have time.

2023-11-02 06:36 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +            Maps::Tiles & currentTile = world.GetTiles( tileIndex );
We can get tile by Point instead of calling `GetIndexFromAbsPoint()` and getting tile by index.
```suggestion
            Maps::Tiles & currentTile = world.GetTiles( pos.x, pos.y );
```

2023-11-02 06:36 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +            Maps::Tiles & currentTile = world.GetTiles( tileIndex );
The same comnent as previous:

```suggestion
            Maps::Tiles & currentTile = world.GetTiles( pos.x, pos.y );
```

2023-11-02 06:36 UTC, Districh-ru commented on src/fheroes2/world/world.cpp
> +void World::updatePassabilities()
In future we probably should update passabilities only in one tile area around the changed tiles.
We can address this in future PRs.

2023-11-02 13:31 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    int selectObjectType( const int objectType, const size_t objectCount, ObjectTypeSelection & objectSelection, const char * title )
I removed the hardcoded string and replaced it with **title** as it should be. It was a bug.

2023-11-02 13:32 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +void World::updatePassabilities()
Yes, optimization can be done later.

2023-11-02 14:48 UTC, ihhub commented
Hi @Branikolog , please briefly verify that the existing functionality of the Editor is not being broken by these changes?

2023-11-02 16:23 UTC, oleg-derevenetz approved these changes

2023-11-02 18:26 UTC, Districh-ru approved these changes

2023-11-03 12:16 UTC, merged