Rename .appdata.xml file to .emtainfo.xml and add <launchable/> tag
ihhub/fheroes2 pull request #8002
Opened 2023-10-29 14:33 UTC by Alexander-Wilms

2023-10-29 23:31 UTC, ihhub commented
Hi @Alexander-Wilms , could you please explain the purpose of this pull request?

2023-10-29 23:37 UTC, Alexander-Wilms commented
@ihhub The Free desktop spec recommends the more new and more universal .metainfo.xml extension:

https://freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location

Also, the launchable tag is needed to make the file pass validation:

`flatpak run org.freedesktop.appstream.cli validate --strict script/packaging/common/fheroes2.metainfo.xml`

2023-11-02 14:05 UTC, ihhub requested changes
Hi @Alexander-Wilms , I left one comment here. Could you please take a look at it?

2023-11-02 14:05 UTC, ihhub commented on script/tools/changelog_update_appdata.py
> -#!/usr/bin/env python3
Could you please revert this change and rename the original file using **git mv** command? In this case the file content will be preserved and only difference (if any) is going to be shown.

2023-11-02 14:23 UTC, Alexander-Wilms commented on script/tools/changelog_update_appdata.py
> -#!/usr/bin/env python3
Done. But it's only shown as being renamed when viewing that specific commit:

https://github.com/ihhub/fheroes2/pull/8002/commits/6a6a56d6459d556334ae24ef22606b2e80583b12

2023-11-02 14:46 UTC, ihhub approved these changes

2023-11-02 14:46 UTC, ihhub commented
@Laserlicht , could you please take a look a these changes as well?

2023-11-02 19:14 UTC, Laserlicht approved these changes

2023-11-02 23:44 UTC, merged

2023-11-02 23:45 UTC, ihhub commented
@Alexander-Wilms , thank you so much for your contribution to the project!