Rework the Thieves Guild (Oracle) dialog code and minor fixes to Hero dialog rendering
ihhub/fheroes2 pull request #8006
Opened 2023-11-01 15:16 UTC by Districh-ru

This PR reworks the code for the Thieves Guild (Oracle) dialog and:
- fix #7728;
- adds fade animation for dialog open/close;
- adds shadow to the Oracle dialog;
- implements a workaround for color names overlap (discussible, can be reverted):
   master build: ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/d45c7465-1063-4159-970c-a092b00a406b)
   this PR: ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/4c9cb3ee-d741-4f3f-a61e-22634d20c57b)
- does some optimizations in preparing the info for the dialog;
- also fixes variable names in hero_dialog.cpp;
- and makes `redraw()` calls in Hero dialog to update only the dialog area, not the whole screen.

2023-11-02 14:35 UTC, ihhub requested changes
Hi @Districh-ru , I put 2 comments here. Would you mind to take a look when you have time?

2023-11-02 14:35 UTC, ihhub commented on src/fheroes2/dialog/dialog_thievesguild.cpp
>      v.clear();
Should we add an assertion here to verify that **getValue** is not empty?

2023-11-02 14:35 UTC, ihhub commented on src/fheroes2/dialog/dialog_thievesguild.cpp
> +        }
We can skip this check and write this code:
```cpp
fheroes2::Copy( icon, 0, 0, output, offsetX - icon.width() / 2, pos.y, icon.width(), icon.height() );
```

**fheroes2::Copy()** function will immediately exit if **icon** is empty.

2023-11-02 15:34 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_thievesguild.cpp
> +        }
Sure!
Just a leftover from the old code. ;)

2023-11-04 09:31 UTC, Branikolog commented
Hi, @Districh-ru !
New element alignment looks nice.
I've only noticed that oracle on the adventure map and castle guild are rendered in different styles (Evil/Good):

https://github.com/ihhub/fheroes2/assets/55348946/4d4b2b7e-58f5-449b-992e-8096d1c2c57b

I know, that it's not related to the changes of the PR, and I can make a separate issue for that, if you wish.

2023-11-04 09:36 UTC, ihhub approved these changes

2023-11-04 09:37 UTC, ihhub commented
Hi @Branikolog , please create a separate issue. This pull request is huge enough.

2023-11-04 09:45 UTC, Branikolog approved these changes

2023-11-04 09:46 UTC, merged

2023-11-04 09:46 UTC, ihhub commented
@Districh-ru , big thanks for these improvements!

2023-11-04 17:24 UTC, Districh-ru commented
> Hi, @Districh-ru ! New element alignment looks nice. I've only noticed that oracle on the adventure map and castle guild are rendered in different styles (Evil/Good):
> 
> I know, that it's not related to the changes of the PR, and I can make a separate issue for that, if you wish.

Hi, @Branikolog, it was made by a reason in PR https://github.com/ihhub/fheroes2/pull/7419:

> About the choice to keep it good for oracle, I believe the interface here should reflect if the oracle himself is a good or a bad person, and not what interface the player has due to his own alignment. This is why I think you could argue that the oracle should not change their alignment to evil just because you are playing an evil faction.
>The descriptive text for the oracle doesn't say whether he is good or evil. In fact, it does make more sense for him to be neutral.
>
> ![image](https://github.com/ihhub/fheroes2/assets/12501091/dec2f6b4-119c-4aca-a189-2e1ca43b98b2)
>
> Anyways, this isn't important for me and if someone else feels strongly about adapting the oracle too then I have no problem with that.

_Originally posted by @zenseii in https://github.com/ihhub/fheroes2/pull/7419#discussion_r1264685978_

2023-11-06 08:31 UTC, Branikolog commented
@Districh-ru 
Hm.. I find it kind of questionable, actually. While choosing an "Evil" mode we have all interface changing, no matter castle, hero or adventure object interaction happens.
![image](https://github.com/ihhub/fheroes2/assets/55348946/dfff446d-c4b5-449b-a54f-c172b4b59059)
Oracle appears to be the only object which has "Good" colours. That looks even more obvious with the "Evil" frame on higher resolutions.

2023-11-06 09:20 UTC, Districh-ru commented
> @Districh-ru Hm.. I find it kind of questionable, actually. While choosing an "Evil" mode we have all interface changing, no matter castle, hero or adventure object interaction happens. 
Oracle appears to be the only object which has "Good" colours. That looks even more obvious with the "Evil" frame on higher resolutions.

You are right, the borders should match the background.
We can make the borders "Good" for the Oracle or make the Oracle background match the selected interface mode.
@Branikolog, @zenseii what is your opinion?

2023-11-06 09:37 UTC, Branikolog commented
@Districh-ru 
I still prefer using the same interface for all game windows.