Update Vietnamese Translation P8
ihhub/fheroes2 pull request #8011
Opened 2023-11-02 15:50 UTC by Nad-SK

P8

2023-11-08 19:03 UTC, ihhub requested changes
Hi @Nad-SK , I left one comment here. Could you please take a look at it?

2023-11-08 19:03 UTC, ihhub commented on files/lang/vi.po
> +"Một Hiệp sĩ già xuất hiện trên bậc thềm của vọng lâu. “Tôi xin lỗi, thưa bệ "
Please always use `\"` for the in-string usage of `"` symbol. Special `“` is not rendered by the engine. The same applies for the string below.

2023-11-09 01:01 UTC, Nad-SK commented on files/lang/vi.po
> +"Một Hiệp sĩ già xuất hiện trên bậc thềm của vọng lâu. “Tôi xin lỗi, thưa bệ "
Fixed!

2023-11-09 01:53 UTC, Nad-SK commented
Hi @ihhub, how to fix this error: not successful when checking.

2023-11-09 20:30 UTC, ihhub commented
@Nad-SK , please revert changes for the last commit and fix only the required lines.

2023-11-10 12:46 UTC, Nad-SK commented
> @Nad-SK , please revert changes for the last commit and fix only the required lines.

Fixed

2023-11-11 04:22 UTC, ihhub commented
@Nad-SK , I can still see 2.3k line changes in yhis pull request. Please revert them.

2023-11-11 08:21 UTC, Nad-SK commented
> @Nad-SK , I can still see 2.3k line changes in yhis pull request. Please revert them.

![Screenshot (7)](https://github.com/ihhub/fheroes2/assets/96630855/c9c668d0-f3ed-4768-8764-ab9b57030bb9)
@ihhub, how to fix this??? I can't revert.

2023-11-17 15:51 UTC, Nad-SK commented
Hi @ihhub, I revert a 1st Nov commit, but IDK why it has 2k lines changed?
![Screenshot (8)](https://github.com/ihhub/fheroes2/assets/96630855/17a3af27-ea33-40f9-8f87-6d13add7e3cd)

2023-11-28 07:40 UTC, Nad-SK commented
Hi, @ihhub thank you for the guideline. It's fixed.

2023-11-29 00:04 UTC, Nad-SK commented on files/lang/vi.po
>  "TẠO\n"
Thank @zenseii , It's fixed.

2023-11-30 13:03 UTC, ihhub approved these changes

2023-11-30 13:03 UTC, merged

2023-11-30 13:03 UTC, ihhub commented
@Nad-SK , thank you very much for the update!