Modernize cursor update for the game area
ihhub/fheroes2 pull request #8012
Opened 2023-11-02 17:53 UTC by Districh-ru

Based on #7808.

This PR also removes the forced cursor update setting on every `CURRENT_HERO_DELAY` pass.
The miss of cursor for 1 frame can not be fixed for all conditions, but the delay before it shows is minimized and not noticeable in this PR.

2023-11-09 08:36 UTC, Branikolog approved these changes
Everything works fine.
However, this PR does not fix #8026.

2023-11-09 20:38 UTC, ihhub commented
I am moving this change to the next release as we are pretty close to the current release.

2023-11-15 14:55 UTC, ihhub requested changes
Hi @Districh-ru , I put several comments in this pull request. Would you mind to take a look at them?

2023-11-15 14:55 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +                        // TODO: remove this assertion after testing.
Should we remove it? No harm keeping an assertion here.

2023-11-15 14:55 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +                // TODO: remove this assertion after testing.
Should we remove it? No harm keeping an assertion here.

2023-11-15 14:55 UTC, ihhub commented on src/fheroes2/gui/cursor.cpp
> +    }
**SetThemes()** method has the same check within so there is no need to do it here.

2023-11-15 14:55 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +        }
This part of the code is being duplicated at lines 981 - 999 and 692-709. I suggest to make a separate helper function for this matter in order to reduce code duplication.

2023-11-15 14:55 UTC, ihhub commented on src/fheroes2/gui/cursor.cpp
> +    }
Do we expect to call **restore()** method multiple times for a single object? If not then please move this check inside the function.

2023-11-15 14:55 UTC, ihhub commented on src/fheroes2/gui/interface_gamearea.cpp
> +        }
Why don't we do the same for lines 987-988? I also think that if it is needed the logic should be inside **updateCursor()** method, not here.

2023-11-15 14:55 UTC, ihhub commented on src/fheroes2/kingdom/puzzle.cpp
> +        adventureMapInterface.setRedraw( Interface::REDRAW_RADAR_CURSOR );
I can see that we set to update cursor if **Interface::REDRAW_RADAR_CURSOR** flag is set. Is it valid for all situations? If yes should we add an internal logic while redrawing adventure map to update the cursor?

2023-11-19 13:14 UTC, Districh-ru commented on src/fheroes2/kingdom/puzzle.cpp
> +        adventureMapInterface.setRedraw( Interface::REDRAW_RADAR_CURSOR );
Hi, @ihhub, you are right - `REDRAW_RADAR_CURSOR` is not needed here because we restore radar by restorer. I made the same restorer for the second puzzle function. It was called here because radar are is used to render EXIT button.

2023-11-19 13:15 UTC, Districh-ru commented on src/fheroes2/gui/interface_gamearea.cpp
> +        }
Sure, I made a helper function.

2024-01-13 13:51 UTC, ihhub commented
Hi @Districh-ru , do we need to change specific logic in this pull request since we separated Adventure Map and Editor classes and do not share quick info dialog code for the Editor?

2024-01-14 07:33 UTC, Districh-ru commented
> Hi @Districh-ru , do we need to change specific logic in this pull request since we separated Adventure Map and Editor classes and do not share quick info dialog code for the Editor?

Hi @ihhub, yes this PR needs some improvement for the new editor quick view. I'll update it on the next week.

2024-01-21 09:05 UTC, Districh-ru commented
Some parts of this PR are redone in separate PRs.
`QuickInfo()` was reworked recently and needs many conflicts to resolve.
Besides the approach in this PR is not perfect and involves many duplications and the need to transfer the `gameArea` instance to the `QuickInfo()` functions.
I'm closing this PR and will open a new one to fix `QuickInfo()` cursor update after I test another approach.

2024-01-21 09:05 UTC, closed without merging