WIP: add treasure placement within the Editor
ihhub/fheroes2 pull request #8016
Opened 2023-11-03 15:03 UTC by ihhub

2023-11-04 18:52 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left one suggestion, please take a look when you have time.

2023-11-04 18:52 UTC, oleg-derevenetz commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    const int32_t _offsetY{ 35 };
Since `_offsetY` is always 35 (and cannot be redefined via constructor) I suppose we can make it `static` and save a few bytes of heap or stack - here and in similar classes below.

2023-11-05 07:36 UTC, Districh-ru approved these changes

2023-11-05 09:03 UTC, oleg-derevenetz approved these changes

2023-11-05 09:13 UTC, merged