Town Portal dialog: use the same list code as for select lists in Battle Only mode (dialog_selectitems).
ihhub/fheroes2 pull request #8022
Opened 2023-11-05 19:20 UTC by Districh-ru

Fix #7906

Town Portal dialog will change its height according to the total towns in list, but maximum 12.

![screenshot](https://github.com/ihhub/fheroes2/assets/113276641/bf03dfae-9ec9-4541-b2f8-c0ed847f1a56)

This PR adds ability to add a text under the dialog title.

2023-11-06 12:59 UTC, Branikolog approved these changes

2023-11-07 19:47 UTC, ihhub requested changes
Hi @Districh-ru , I left 2 comments here. Would you mind to take a look at them?

2023-11-07 19:47 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    static const int32_t _offsetY{ 35 };
Please make this variable **public** and use it at lines 610-611.

2023-11-08 17:52 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    static const int32_t _offsetY{ 35 };
Hi, @ihhub, it will not help because we make this list object only after the 610-611 lines using the values, calulated in these lines.
I'll redo the constructor of **SelectEnum** class to use `_offsetY` value and calculate the dialog height taking list items count into account. not to have such dialogs:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/945fc611-fda7-430f-bb5f-919def204902)

But maybe it'll be good to make this improvement in a separate PR, what do you think?

2023-11-08 19:09 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    static const int32_t _offsetY{ 35 };
This class is defined at lines 389-420. It is used at line 662. I am asking to make this `_offsetY` **static** variable to be public.

2023-11-08 19:19 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    static const int32_t _offsetY{ 35 };
Oh, yes, we can do this. :)

2023-11-09 03:36 UTC, ihhub approved these changes

2023-11-09 03:36 UTC, merged

2023-11-09 03:36 UTC, ihhub commented
@Districh-ru , thank you so much for this change!