Focus on the hero when he starts to move by the Move button press
ihhub/fheroes2 pull request #8032
Opened 2023-11-09 15:10 UTC by Districh-ru

- Fix #8030 (a regression after #8000).

2023-11-09 20:29 UTC, ihhub requested changes
Hi @Districh-ru , I left one suggestion here. Could you please take a look once you have time?

2023-11-09 20:29 UTC, ihhub commented on src/fheroes2/gui/interface_events.cpp
> +void Interface::AdventureMap::_startHeroMove( Heroes * hero )
Please use a reference over the pointer. In both cases where we call this method we checked whether the pointer is **nullptr** so there is no need to do it again.

2023-11-10 04:45 UTC, ihhub approved these changes

2023-11-10 11:29 UTC, Branikolog approved these changes
Thank you, @Districh-ru !

2023-11-10 12:10 UTC, merged

2023-11-10 12:11 UTC, ihhub commented
@Districh-ru , thank you so much for the fix!