Properly evaluate potential attack positions for wide units
ihhub/fheroes2 pull request #8036
Opened 2023-11-10 18:54 UTC by oleg-derevenetz

fix #7786

2023-11-12 16:09 UTC, Branikolog commented
Hi, @oleg-derevenetz !
Before I start my tests, I have one question.
Does this PR fix only wide units logic? What about single cell troops? Or they are working just fine?

2023-11-12 16:31 UTC, oleg-derevenetz commented
Hi @Branikolog

> Does this PR fix only wide units logic? What about single cell troops? Or they are working just fine?

This question is not so easy to answer :) Currently in `master` branch, battle AI uses the concept of "position value", and by "position" it means "cell". So in this case:

```
| |S| <- shooting unit
|+|+| 
| |M| <- melee unit
| | |
| |M| <- melee unit
```

cells adjacent to shooting units have better "value" than other cells, so AI prefers to use these cells to block archers, even if it doesn't want to attack them immediately, and this works just fine with non-wide attacking units (and with wide attacking units when potential targets are not so far away from each other). BUT, since "position" in `master` means "cell", it doesn't properly understand cases like this (just like in your video):

```
|S| | |M|
```

or this:

```
|S| | | |
| | | | |
| | | |M|
```

Although in both cases a wide unit is able to simultaneously attack one unit and block another, AI has no idea about that, because both units do not have common adjacent cells. That's why in your video AI is not able to block Trolls and attack Titans at the same time.

With this PR, "position" means "position", i.e. a collection of one to two cells which an attacking unit may occupy, and not a "cell", so now AI understands that it can take a position like this (`A` means a single cell of a wide attacking unit):

```
|S| | | |
| |A|A| |
| | | |M|
```

to attack one unit and block another. I must say that although the behavior improves only for wide units, the code has been heavily rewritten, so the changes will indirectly affect the non-wide units as well (but they just should work as before, i.e. there should be no obvious regressions).

2023-11-15 14:00 UTC, ihhub requested changes
Hi @oleg-derevenetz , I left 2 comments here. Could you please take a look once you have free time?

2023-11-15 14:08 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
>              }
Hi @ihhub please note that `valuesOfAttackPositions` contains position values near ALL enemy units. Here we need to process just positions near the PARTICULAR enemy unit.

2023-11-15 14:11 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +                    }
Hi @ihhub due to sorting a few lines above, positions near melee units will be processed first (by choosing the maximum value among nearby melee units), and only then archer's values will be added on top of all this.

2023-11-15 14:12 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +                    }
Ah, I missed this part. Thanks for the explanation!

2023-11-15 14:14 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
>              }
Hi @oleg-derevenetz , **evaluatePotentialAttackPositions()** returns a map of values where we have distance checks (lines 235-240) then we use the returned value here (function **BestAttackOutcome()**) and at lines 309-314 we do the same checks. Please correct me if I miss something.

2023-11-15 14:33 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
>              }
Hi @ihhub `evaluatePotentialAttackPositions()` calculates and returns the map of attack positions not related to a particular target. For instance, in the following case we have two targets, `X` and `Y`:

```
| |+|X|
| |+|+|
| | | |
| |+|+|
| |+|Y|
```

The result of `evaluatePotentialAttackPositions()` will contain all positions marked by the "plus" sign. But in the `BestAttackOutcome()` we will deal just with one target (passed as `defender` parameter). So if `X` was passed as `defender`, then we need to use just the positions near the `X`, and ignore positions that are near only `Y`.

2023-11-15 14:36 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
>              }
Ah, I got it. Thanks for the answer!

2023-11-15 14:36 UTC, ihhub approved these changes

2023-11-16 03:13 UTC, ihhub commented
Hi @drevoborod , if you have time could you please test these changes? @Branikolog is not available the next few days.

2023-11-16 09:32 UTC, oleg-derevenetz commented
Hi @ihhub there is no hurry with this PR, it is not planned for the upcoming release.

2023-11-16 13:36 UTC, ihhub commented
Hi @oleg-derevenetz , this is true. @Branikolog is going to be busy with another side-tasks for a couple of days after the release.

Moreover, I added 1.0.11 release as we are not ready to release 1.1.0 as the primary feature of the release is a working Editor. I am changing the target release for this PR for 1.0.11.

2023-11-17 21:57 UTC, drevoborod commented
At first glance, everything seems to be ok - the AI learned to block archers which are two or one cells away from meelee attackers in any direction. 
But I noticed that the AI can not predict that response of its dragon on enemy attack can affect its another unit on the other side of the attacker because dragons have two-cells attack. I mean that my attacking unit (Titans) wasn't moving, it just attacked nearby dragons and the response affected minotaurs which were on the other side of the titans.

2023-11-17 23:01 UTC, oleg-derevenetz commented
> But I noticed that the AI can not predict that response of its dragon on enemy attack can affect its another unit on the other side of the attacker because dragons have two-cells attack.

The logic for performing evaluations of this type is not currently implemented. And in any case, this is not trivial, because there certainly will be cases in which AI will have to make a choice between blocking archers (or dealing maximum damage to multiple enemy units with a penetrating attack) and protecting a nearby friendly unit from a retaliatory penetrating attack.

2023-11-18 09:05 UTC, drevoborod commented
Found some quite strange behaviour: the AI moved its black dragons to attack my dragons instead of blocking the shooters. Maybe it's ok, but explanation required :) 
![изображение](https://github.com/ihhub/fheroes2/assets/10282847/c4b79b8a-6161-45fe-b9f7-45986990c409)
There are 4 red dragons and free space in front of shooters, but the AI tries to block them with first dragon squad. On the picture it's Gargoulies turn now. But shooters were attacked by another dragon squad later so it seems like AI takes move order into consideration. 
![изображение](https://github.com/ihhub/fheroes2/assets/10282847/80022673-ad5d-4b74-a9be-6ae13a85d353)

2023-11-18 09:20 UTC, oleg-derevenetz commented
> Found some quite strange behaviour: the AI moved its black dragons to attack my dragons instead of blocking the shooters.

If AI decided that it would be more profitable to attack your dragons at the moment, then it cannot block your shooters during this attack, because friendly dragons would be damaged by the penetrating attack from that angle.

2023-11-19 10:48 UTC, drevoborod commented
And here is same situation, I guess? Although shooters are open, all AI troops attack my dragons.
![Screenshot_20231119_134507](https://github.com/ihhub/fheroes2/assets/10282847/f862aaff-4486-4174-a135-0d977a1068d4)
![Screenshot_20231119_134553](https://github.com/ihhub/fheroes2/assets/10282847/c697ef90-ce78-4b7f-8290-2cba311757ef)

Actually, for me it seems that everything is OK and this MR can be merged.

2023-11-19 11:00 UTC, oleg-derevenetz commented
> And here is same situation, I guess? Although shooters are open, all AI troops attack my dragons.

AI will not try to block shooters at all costs. If there is more dangerous unit far away from shooters, AI will attack that unit, trying to eliminate a bigger threat. Blocking of archers is not an end in itself, but a nice bonus to attacking the most threatening unit (it can be the archers himself or one of his neighbors).

2023-11-19 11:10 UTC, drevoborod commented
Seems like AI does not know how to properly use Ghosts abilities :) In this case it attacks dragons instead of increase ghosts count by eliminating weaker units firstly:
![изображение](https://github.com/ihhub/fheroes2/assets/10282847/5cf29884-b1e9-48bb-b8e3-e4977dc6f4c9)

2023-11-19 11:15 UTC, oleg-derevenetz commented
> Seems like AI does not know how to properly use Ghosts abilities :) In this case it attacks dragons instead of increase ghosts count by eliminating weaker units firstly

Yeah, there is already #7685 about that.

2023-11-19 14:08 UTC, ihhub commented
Hi @drevoborod , are we good to go with this change?

2023-11-19 14:23 UTC, drevoborod commented
> Hi @drevoborod , are we good to go with this change?

In my opinion, yes, we are.

2023-11-19 14:51 UTC, merged

2023-11-19 14:52 UTC, ihhub commented
@oleg-derevenetz , huge thanks for this improvement!

@drevoborod , thanks a lot for your help!