Shipyard: Treat water with an object's shadow as water free of objects
ihhub/fheroes2 pull request #8040
Opened 2023-11-11 09:40 UTC by Districh-ru

Fix #8039

2023-11-11 11:25 UTC, Branikolog approved these changes
@Districh-ru 
Thanks for such a fast fix! I can now build a shipyard even in a previously generated game.

2023-11-11 11:31 UTC, Branikolog commented
@Districh-ru 
Oh, the only small issue here...
I'm not able to build a boat in this city.

2023-11-11 11:44 UTC, Districh-ru commented
> @Districh-ru 
> Oh, the only small issue here...
> I'm not able to build a boat in this city.

Sad. :)
I'll try to fix it tomorrow morning

2023-11-12 10:13 UTC, Branikolog approved these changes
Now shipyard is available and I can purchase a boat there. 👍

2023-11-15 11:13 UTC, ihhub requested changes
Hi @Districh-ru , I left one suggestion here. Could you please take a look at it when you have time?

2023-11-15 11:13 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +               || ( objectType == MP2::OBJ_NONE && tile.getLayerType() == Maps::ObjectLayerType::SHADOW_LAYER );
We are checking object layer only of main object on the tile, not the whole tile. I suggest to use `Maps::Tiles::isShadow()` that covers everything. However, this does no cover all possible cases. I think the logic should be like this:
```cpp
MP2::isPickupObject( objectType ) || // pickup objects can be removed later
objectType == MP2::OBJ_BOAT || // obviously, if boat exists then it can be removed later
!tile.isObjectOrBackgroundLayerType()
```
The last function does not exist but the idea is to check main tile addon and bottom layers addon that none of addons are on object and background layers.

By the way `isObjectOrBottomLayerType` is named incorrectly as it should be for OBJECT_LAYER and BACKGROUND_LAYER layers, not for bottom layer.

2023-11-15 15:36 UTC, Districh-ru commented on src/fheroes2/castle/castle.cpp
> +               || ( objectType == MP2::OBJ_NONE && tile.getLayerType() == Maps::ObjectLayerType::SHADOW_LAYER );
Hi, @ihhub, sure.
The `isObjectOrBottomLayerType()` function name is fixed now and moved to the tile and addon methods.
I used the suggested `!tile.isObjectOrBackgroundLayerType()` logic.
Thanks!

2023-11-16 13:20 UTC, ihhub requested changes
Hi @Districh-ru , I added few more comments here. Could you please take a look at them?

2023-11-16 13:20 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.h
> +        }
This is not entirely correct for all cases. There could be a situation when **_addonBottomLayer** can have an object with this layer type but the main addon doesn't. We should run through all entries of **_addonBottomLayer** as well.

I also suggest to rename this function to avoid misleading reading. Including a word **tile** will solve the issue.

2023-11-16 13:20 UTC, ihhub commented on src/fheroes2/maps/maps_tiles.h
> +        bool isObjectOrBackgroundLayerType() const
While addressing comments for Ocean Objects PR I was thinking how we properly name this function. How about we name it as `doesOccupyTile()`? Or even better `isPassabilityTransparent()` and use opposite logic as:
```cpp
bool isPassabilityTransparent() const
{
    return _layerType == SHADOW_LAYER || _layerType == TERRAIN_LAYER;
}
```

What do you think?

2023-11-16 13:40 UTC, ihhub commented
This pull request should be merged for the upcoming release as it is a regression fix. Therefore, I am marking it as the high priority PR.

2023-11-16 15:51 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles.h
> +        }
Hi, @ihhub, yes we should also check this case. I changed the function.

2023-11-16 15:53 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles.h
> +        bool isObjectOrBackgroundLayerType() const
Yes, lets do so. I named the tile function the same way.
I'm not good in naming functions and variables. :(

2023-11-17 00:43 UTC, ihhub approved these changes

2023-11-17 00:53 UTC, merged

2023-11-17 00:53 UTC, ihhub commented
@Districh-ru , thank you so much for these fixes!