Shifted the name of the Necromancy skill in the secondary skill bar l…
ihhub/fheroes2 pull request #8058
Opened 2023-11-19 19:41 UTC by JasonQorbin

This PR addresses issue #7491. The change makes th UI render more like the original game by rendering the name of the Necromancy skill one pixel to the left of center so that the long skill name doesn't overlap with the gold border on the righthand side of the secondary skill tile. The solution is not perfect because the text has a shadow that now touches the left side border but the original game looked like this also.

A few things to note about the code changes:

1.     I opted to add a check to see if the current skill is the necromancy skill and handle the special case instead of rounding the result of the padding calucation down because I didn't want to affect all the exiting content (which no one has complained about and is probably happy with).
2.     The problem pointed out by @ihhub is still relevant: This only fixes the visual bug for the english version of the game and for long strings in other languages we will need a better solution. Handling a special case for every long skill name in every language is not feasible.
3.     I added a lambda for the centering logic which is repeated several times in this function. This may be beyond the scope of the issue. Happy to revert that back.

Happy to take guidance on this to arrive at a better more general solution

2023-11-20 21:20 UTC, JasonQorbin commented
Sorry. Updated formatting with clang-format.

2023-11-22 05:03 UTC, ihhub commented
Hi @JasonQorbin , the root of the problem is in presence of shadow within the font which is 1 pixel wide. The shadow is present at left and bottom sides. Therefore, in order to tackle the problem we need to get width of the text, width of the icon and calculate with 1 pixel shift:
```cpp
xPos = ( iconWidth - textWidth + 1 ) / 2;
```
Essentially, the whole fix is
```cpp
text.draw( pos.x + ( pos.width - text.width() + 1 ) / 2, pos.y + 53, dstsf );
```

Please give a try.

2023-11-22 07:26 UTC, JasonQorbin commented
I didn't realize I could squish the text. Thanks for that. I'll take another look this evening.

2023-11-27 04:54 UTC, JasonQorbin commented
Hi @ihhub. I've tried a few approaches.

The fix you recomended solves the problem of the name overlapping the righthand border, which was the original problem we were trying to solve. However, it still casts a shadow on the lefthand border like so:

![Necromancy with 1px adjustment](https://github.com/ihhub/fheroes2/assets/117314288/ab3b0139-531e-40bc-8678-372c1602b8bf)

I then attempted the suggestion from @Branikolog in the original issue of "cutting the shadow for such cases".
So in the current version of the PR, if the text is just wide enough that the shadow would fall on the border then
I repaint that section of the border to remove the shadow. This is the result:

![Necromancy with 1px adjustment and border repainted](https://github.com/ihhub/fheroes2/assets/117314288/7aeaceb7-e009-4d2f-b2a5-ea7f5dc6ffc0)

2023-12-03 14:14 UTC, ihhub commented
Hi @JasonQorbin , I am adding changes to limit rendering of text within a given ROI. See #8101. With this approach it will be easier to avoid any hacky code.

2023-12-10 19:32 UTC, JasonQorbin commented
Text, centered, no more shadow, and no more hacky redrawing of the border thanks to the new text drawing function.
![Screenshot 2023-12-10 204357](https://github.com/ihhub/fheroes2/assets/117314288/85f29845-9107-4b29-9042-97eb09f0af71)

2023-12-11 00:58 UTC, ihhub reviewed
Now the code is very nice and neat :)

2023-12-11 00:58 UTC, ihhub commented on src/fheroes2/gui/skill_bar.cpp
> +        int skillNamePaddingX = ( pos.width - text.width() ) / 2 - 1;
This variable can be const.

2023-12-11 00:59 UTC, ihhub commented
Hi @Branikolog , please test these changes since you requested them.

2023-12-11 17:52 UTC, JasonQorbin commented on src/fheroes2/gui/skill_bar.cpp
> +        int skillNamePaddingX = ( pos.width - text.width() ) / 2 - 1;
Done. Also mirrored the same variable for the skill level text for consistency.

2023-12-12 00:54 UTC, ihhub approved these changes

2023-12-12 13:48 UTC, Branikolog commented
Hello, @JasonQorbin !
Thanks for working on this issue.
Necromancy skill name aligned properly in the hero info window now. 👍 
But lvlup window still has the issue.
![image](https://github.com/ihhub/fheroes2/assets/55348946/ff2dce49-fd39-48fb-8836-fb20b92f3e7d)

2023-12-12 13:49 UTC, ihhub commented
Hi @Branikolog , the level up window is a separate issue.

2023-12-12 13:51 UTC, ihhub commented
Hi @Branikolog , I suggest to check other languages and how it looks for skill names.

2023-12-12 13:51 UTC, Branikolog commented
Hi, @ihhub 
Okay.
What about skill info window?

![image](https://github.com/ihhub/fheroes2/assets/55348946/0f90ea39-4c0f-4ebc-a902-b1ad9f6449cd)

It is aligned properly, but there's a shadow on a frame, while in hero info window shadow was dismissed for the frame?

2023-12-12 13:57 UTC, Branikolog commented
@ihhub 

>Hi @Branikolog , I suggest to check other languages and how it looks for skill names.

Thanks to the ability to select language in the adventure map settings it was really easy and comfortable. :)

Symbols are cut for the names on other languages:

![image](https://github.com/ihhub/fheroes2/assets/55348946/8f448c60-ccd7-42c0-bf9b-046b657fbb91)

![image](https://github.com/ihhub/fheroes2/assets/55348946/fe7611d8-46bd-4987-b64b-a239be9094d3)

Such implementation is not OK in my opinion.

2023-12-12 14:56 UTC, JasonQorbin commented
I'm happy to apply the fix the other menus and windows. But I would appreciate some guidance on what sort of intervention would be considered OK for handling languages that, it would appear, the UI wasn't designed for. In that last screenshot, the text of the skill levels of adjacent skill would overlap if they aren't truncated. And those are single words so we can't render it out on two separate lines.

Maybe we can consider scaling the text down? Not sure that would look good and very long words would become illegible very quickly at some resolutions.

Maybe combined with scaling the UI up? Might be fine on higher resolutions and larger screens but that wouldn't work at the resolution shown in the screenshots above.

I'm just kicking around ideas to try to spark something. I'm not really sure what the answer is either.

2023-12-13 22:27 UTC, JasonQorbin commented
Hi everyone.

I've changed my local copy to truncate the text with ellipses ("...") if it is any longer than the max width of the block in the Hero Screen as suggested by @zenseii. 

Excuse the weird character encoding, but I think it gets the point across.

![Screenshot 2023-12-14 001606](https://github.com/ihhub/fheroes2/assets/117314288/5b6d85af-1f6f-4147-88f3-6c22f96170e6)

@Branikolog if you're happy with this then I'll update the pull request with this change and then we can create a new issue(s) to fix both the level-up window and the one that pops up when you right-click the skill.

2023-12-14 23:24 UTC, Branikolog commented
Hi, @JasonQorbin and @zenseii 
Yeah, that's a nice solution. We have some other names too long for these skill boxes. So showing "..." is definitely better than text overlapping the nearest icon text.
![image](https://github.com/ihhub/fheroes2/assets/55348946/ddaf334f-4209-469f-92da-f54bb37c7961)

2023-12-17 08:17 UTC, oleg-derevenetz commented
Hi @JasonQorbin there is something weird about this PR, too many changed lines (4036 lines added, 2276 lines removed, 70 files affected). Please sync it with `master` properly (e.g. by merging `master` into this PR's branch).

2023-12-17 21:04 UTC, JasonQorbin commented
Apologies. Should be fixed now. Should only be 11 lines in one file.

I rebased my commits together and ended up overwriting other peoples commits. Terribly sorry!!

2023-12-22 20:53 UTC, Branikolog approved these changes

2023-12-24 07:29 UTC, ihhub requested changes
Hi @JasonQorbin , I left several comments in this pull request. Can you please take a look a them?

2023-12-24 07:29 UTC, ihhub commented on src/fheroes2/gui/skill_bar.cpp
> +            text.fitToOneRow( pos.width );
Please add parenthesis for this if-body:
```cpp
if ( text.width() > 76 ) {
    text.fitToOneRow( pos.width );
}
```

The same applies for the code below.

2023-12-24 07:29 UTC, ihhub commented on src/fheroes2/gui/skill_bar.cpp
> +        text.drawInRoi( pos.x + ( pos.width - text.width() ) - 3, pos.y + pos.height - 10, dstsf, pos );
I don't think that we need to modify this code. There is literally only 1 digit to render. I suggest to revert these changes. This part of code is executed in Kingdom Overview dialog.

2023-12-24 07:29 UTC, ihhub commented on src/fheroes2/gui/skill_bar.cpp
> +        if ( text.width() > 76 )
We must avoid hardcoded values. This condition should be based on **sprite** width which is 75 pixels. In other words, the condition should be `if ( text.width() > sprite.width() + 1 )`.

2023-12-25 06:48 UTC, ihhub approved these changes

2023-12-25 07:34 UTC, merged

2023-12-25 07:35 UTC, ihhub commented
@JasonQorbin , thank you so much for your contribution and patience with this issue!