fix scroll location on file deletion
ihhub/fheroes2 pull request #8071
Opened 2023-11-22 23:54 UTC by MaMadDl

Fix for #8025

2023-11-23 17:50 UTC, Districh-ru requested changes
Hi @MaMadDl.
Thanks for fixing this issue!
We can make this fix a little better. I left one comment regarding this. Could you please check it out in your spare time.

2023-11-23 17:50 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectfile.cpp
>                      listbox.SetListContent( lists );
We can also remove this line to avoid list position reset: a reference to `lists` is already set for the contents of the `listbox` and the action of the `SetListContent()` method is the reset of selected item and list position. The other action is list scrollbar range update which is now done by the newly added `SetCurrent()` method. So we can safely remove this method call and preserve the list position.
What do you think?)

2023-11-25 03:50 UTC, Districh-ru approved these changes

2023-11-25 04:11 UTC, Branikolog commented
I haven't found any bugs in this implementation. 👍 
The only thing concerns me is that list jumps to the target list string **after** the file was deleted:

https://github.com/ihhub/fheroes2/assets/55348946/fb0098ce-4393-43cd-bc6a-1966f7079f33

Maybe the list should be updated right before delete dialog appears?
How do you think, @MaMadDl  @Districh-ru and @ihhub ? Is it a more common behaviour of lists in modern OSes?

2023-11-25 04:29 UTC, Districh-ru commented
> I haven't found any bugs in this implementation. 👍 The only thing concerns me is that list jumps to the target list string **after** the file was deleted:
> Maybe the list should be updated right before delete dialog appears? How do you think, @MaMadDl @Districh-ru and @ihhub ? Is it a more common behaviour of lists in modern OSes?

This can be implemented if we add between the lines 496 and 497 the code to show current file and redraw the list:
```cpp
                listbox.SetCurrent( listId );
                listbox.Redraw();
```

Then the list will act like it is done, in example, in Total Commander. :)

2023-11-25 10:35 UTC, MaMadDl commented
> I haven't found any bugs in this implementation. 👍 The only thing concerns me is that list jumps to the target list string **after** the file was deleted:
> 2023-11-25.12-04-52.mp4
> 
> Maybe the list should be updated right before delete dialog appears? How do you think, @MaMadDl @Districh-ru and @ihhub ? Is it a more common behaviour of lists in modern OSes?
> 
> The implementation from the PR works fine anyway.

I think this is expected behaviour because you are deleting a file that's not shown on the screen at the time. I have seen both behavoiours, but I think snapping to selected file should happen either way.

what @Districh-ru suggested can be a nice touch

2023-11-25 11:44 UTC, Branikolog approved these changes
No bugs detected. 👍

2023-11-26 01:08 UTC, ihhub approved these changes

2023-11-26 01:08 UTC, merged

2023-11-26 01:09 UTC, ihhub commented
@MaMadDl , thank you very much for your contribution to the project!