Multi monitor support
ihhub/fheroes2 pull request #8072
Opened 2023-11-23 07:56 UTC by MaMadDl

Adding Multi Monitor Support
Tested on Windows (Win 11) 
![Untitled](https://github.com/ihhub/fheroes2/assets/18714088/d8419132-0197-4961-b156-7f67c3764c26)

2023-11-23 08:21 UTC, ihhub commented
Hi @MaMadDl , can you please explain what problem this pull request solves?

2023-11-23 08:25 UTC, MaMadDl commented
when you have more than one monitor 
and you want the game to run on your second (or third) Monitor you can't really change it.
the Ctrl+Alt+WinKey doesnt always works
so i added the functionality to do so .

2023-11-23 13:24 UTC, MaMadDl commented
It should cause we are using SDL to handle monitor coordinates 
I have linux (ubuntu 20.04) as well but haven't got to test it yet

2023-11-23 16:07 UTC, ihhub commented
Hi @MaMadDl , what do you mean I can't change it if it is possible to drag a window in between monitors? I'm just trying to understand the problem before trying to analyze a solution for it.

Could you also elaborate "the Ctrl+Alt+WinKey doesnt always work"? In which cases it works and in which it doesn't?

2023-11-23 16:24 UTC, MaMadDl commented
when you are in fullscreeen (and you want to play in fullscreen not windowed)  game is pretty much stuck on the first monitor (primary monitor) connected. 
usually some engines allow moving between monitors using Crtrl+Alt+ ArrowKey to move game window between monitors. this engine doesn't ATM. 
so in order to play the game on fullscreen  on any other monitors than the first monitors you need to add functionality on engine level.  and that's what i did.

2023-11-24 12:42 UTC, MaMadDl commented
@Mr-Bajs 
Apparently X11 can correctly handle screen switch internally ( I could move game window between monitors using `WinKey+Shift+ArrowKey`)

2023-11-24 18:39 UTC, oleg-derevenetz commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +#include <SDL_video.h>
SDL is not welcome outside of the `engine`. You should not directly use SDL in `fheroes2`, only through the medium of `engine`.

2023-11-24 18:42 UTC, oleg-derevenetz requested changes

2023-11-24 18:42 UTC, oleg-derevenetz commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +#include <SDL_video.h>
I will not touch on the general need for these changes yet, but I should note that SDL is not welcome outside of the `engine`. You should not directly use SDL in `fheroes2`, only through the medium of `engine`.

2023-11-24 21:55 UTC, MaMadDl commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +#include <SDL_video.h>
I didn't add it voluntarily `IWYU` workflow forced that. check [20f480e](https://github.com/ihhub/fheroes2/pull/8072/commits/20f480ed394de3ed354f1e635b4c468c115d968c) build status

as for the need, I needed this kind of functionality when I'm playing the game so I tried to add it.

2023-11-24 22:05 UTC, oleg-derevenetz commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +#include <SDL_video.h>
I mean that only low-level engine (code in the `src/engine`) should work with SDL and it should offer an abstract interface for code in `src/fheroes2` to work with hardware. No code in `src/fheroes2` should work with the SDL directly. But this can be corrected later after a principled decision from @ihhub about taking this PR into work.

2023-11-25 00:28 UTC, ihhub requested changes
Hi @MaMadDl , I left multiple comments in this pull request. Could you please take a look at them?

2023-11-25 00:28 UTC, ihhub commented on src/engine/screen.h
> +        void setDisplayMonitor( int monitor )
The input argument can be const.

2023-11-25 00:28 UTC, ihhub commented on src/engine/screen.h
> +        void setDisplayMonitor( int monitor )
We have exactly the same methods and variable inside the class above. Why we repeat them here?

2023-11-25 00:28 UTC, ihhub commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +#include <SDL_video.h>
@oleg-derevenetz is right. We must not expose SDL code outside **engine**. However, the bigger concern of mine is these UI changes. The options are not aligned and the new option must have a new icon according to [this description](https://github.com/ihhub/fheroes2/wiki/Adding-a-new-option-into-the-game). Therefore, if you would like to proceed with this feature but do not have a solution for UI please revert all UI changes here.

2023-11-25 00:28 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +                    listbox.SetCurrent( std::max( listId - 1, 0 ) );
Please revert this change. This is not related to the current PR.

2023-11-25 00:28 UTC, ihhub commented on src/fheroes2/game/fheroes2.cpp
> +                display.setDisplayMonitor( 0 );
There is no reason to set to 0 as this is a default value we set in the member of **BaseRenderEngine** class.

2023-11-25 00:28 UTC, ihhub commented on src/engine/screen.cpp
> +                                        resolutionInfo.screenHeight, flags );
Could you please explain why we need this change?

2023-11-25 00:28 UTC, ihhub commented on src/engine/screen.cpp
> -
Please revert this line.

2023-11-25 00:28 UTC, ihhub commented on src/engine/screen.cpp
> -
Please revert this line.

2023-11-25 00:28 UTC, ihhub commented on src/engine/screen.h
>          bool _nearestScaling;
Either make every member to be initialized in place (and remove the default constructor) or initialize every member inside the constructor to be consistent with the code.

2023-11-25 09:00 UTC, MaMadDl commented on src/fheroes2/dialog/dialog_selectfile.cpp
> +                    listbox.SetCurrent( std::max( listId - 1, 0 ) );
Yes. this is included here by mistake

2023-11-25 09:15 UTC, MaMadDl commented on src/engine/screen.cpp
> +                                        resolutionInfo.screenHeight, flags );
In order for SDL to show display on a monitor, it need it's global coordinate which is calculated between all connected monitors. 
in a One monitor setup, `x` and `y` coordinates of monitor is always `0` and can be ignored in calculations. but in Multi-monitor setup starting position of monitor (top-left side) is moved in negative or positive side by the resolution of the monitor
so the calculation must be included when we are creating window (`SDL_CreateWindow()` )

2023-11-25 09:21 UTC, MaMadDl commented on src/engine/screen.h
>          bool _nearestScaling;
That is my Thoughts exactly. this is caused by Analyzer checks forcing changes
check the [Bot Review](https://github.com/ihhub/fheroes2/pull/8072#pullrequestreview-1746977179) for build [d88c6fd](https://github.com/ihhub/fheroes2/pull/8072/commits/d88c6fd8c0f5b53fc2e5bbd47786fa27cb549176)

2023-11-25 09:48 UTC, MaMadDl commented on src/engine/screen.h
> +        void setDisplayMonitor( int monitor )
I couldn't find a cleaner way to pass display number from `settings` to the `engine`. creating instance to setting inside engine was messier in my opinion.
and I thought in the future there might be a need to this in display class as well. so I kept a copy

2023-11-25 09:50 UTC, MaMadDl commented on src/engine/screen.h
> +        int DisplayMonitor() const
this is acceptable, changes made so fast I didn't thought of a better naming for the property and method

I will change this after all other comments resolved.

2023-12-01 15:50 UTC, ihhub commented
Hi @MaMadDl , I marked this pull request as a draft as it still requires some work from your side. Once you address all comments please re-request review.

2023-12-01 20:39 UTC, MaMadDl commented
@ihhub @oleg-derevenetz 
changed most of the reviews required changes

As for the dialog itself, instead of creating a new 5 button layout
I've added a button missing in the setting (Interface Type which is accessible only from in-game)
![5](https://github.com/ihhub/fheroes2/assets/18714088/bc5968fe-49de-410c-b7bb-040e2d96cde6)

2023-12-10 15:21 UTC, ihhub requested changes
Hi @MaMadDl , I put few comments here. Could you please take a look at them?

@Branikolog please check one comment I left here.

2023-12-10 15:21 UTC, ihhub commented on src/engine/screen.cpp
> +            SDL_Rect monRect;
As I explained previously we should not use a word **monitor** anywhere. Please use **display**. This is applicable for all newly added code and texts.

2023-12-10 15:21 UTC, ihhub commented on src/engine/screen.cpp
> +                                        resolutionInfo.screenHeight, flags );
Could you please explain why we have this code only for windows? Is there an SDL documentation regarding this?

2023-12-10 15:21 UTC, ihhub commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +
Interface does not below to **Graphics** group as it exists within **Interface Settings** group. Run any map and open System Options to see this.

@Branikolog what were your suggestions regarding extra Graphics options which we are missing?

2023-12-10 15:21 UTC, ihhub commented on src/fheroes2/game/fheroes2.cpp
> +                display.setDisplayId( 0 );
We don't need to set display ID for the first run as this is the default value.

2023-12-10 15:21 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +    os << std::endl << "# Display Monitor for Multi-Monitor Setups (defaults to first monitor)" << std::endl;
The comment is not entirely accurate. This option will still be present even if a device has one display. Also I suggest to put it right after **videomode** option.

2023-12-10 15:21 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +        setDisplayId( std::max( config.IntParams( "monitor" ), 0 ) );
We don't need a variable in this class. We can directly call **setDisplayId()** method of `BaseRenderEngine`.

2023-12-10 15:21 UTC, ihhub commented on src/fheroes2/system/settings.cpp
> +    os << "monitor = " << getDisplayId() << std::endl;
We can directly call a method of `BaseRenderEngine` class to retrieve the value.

2023-12-10 15:21 UTC, ihhub commented on src/engine/screen.h
> +
Initialize **_displayId** member here.

2023-12-10 23:45 UTC, MaMadDl reviewed
Hello @ihhub, I have made the requested changes. Could you please review them?

2023-12-12 13:28 UTC, ihhub requested changes
Hi @MaMadDl , I left few more comments. Please take a look.

2023-12-12 13:28 UTC, ihhub commented on src/engine/screen.cpp
> -
Please revert this change.

2023-12-12 13:28 UTC, ihhub commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +                fheroes2::engine().setDisplayId( ( fheroes2::engine().getDisplayId() + 1 ) % fheroes2::getNumberOfVideoDisplays() );
I tested this as a user. What exactly do we expect from this option? It does nothing for my setup: I have 2 monitors and Windows 10. Also, according to logic it also does nothing expect setting a variable to a new state. The change must be visible immediately to a user.

2023-12-12 13:28 UTC, ihhub commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +                              fheroes2::getDisplayName( fheroes2::engine().getDisplayId() ), fheroes2::UiOptionTextWidth::TWO_ELEMENTS_ROW );
Displaying a name is a bit useless. This is my setup:
![image](https://github.com/ihhub/fheroes2/assets/19829520/9a0133ad-b8a9-432b-b251-576384ca7be1)

I am clicking on it with no changes. This is because Windows detects both monitors (laptop and a separate monitor) just generic ones.

2023-12-12 13:28 UTC, ihhub commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +        DisplayList,
This is entirely correct: we do not show a display list but switching displays. So more accurate name should be `SwitchDisplay`.

2023-12-12 13:28 UTC, ihhub commented on src/fheroes2/game/fheroes2.cpp
> +                // set display monitor to first monitor available
Please revert this change.

2023-12-12 13:28 UTC, ihhub commented on src/fheroes2/system/settings.h
> +
Please revert these changes.

2023-12-12 13:28 UTC, ihhub commented on src/engine/screen.cpp
> +    }
This function must check return value of **SDL_GetNumVideoDisplays** according to https://wiki.libsdl.org/SDL2/SDL_GetNumVideoDisplays and log an error if any.

2023-12-12 13:28 UTC, ihhub commented on src/engine/screen.h
> +    const char * getDisplayName( const int display );
These methods should belong to **BaseRenderEngine** class and be overridden in child classes. We do not want to stick only to SDL 2.

2023-12-12 13:28 UTC, ihhub commented on src/engine/screen.h
> +        int _displayId;
Please move this member to the bottom. Right now the size of the class based on the variable declaration is 64 * 3 bits while moving this variable to the bottom makes it 64 * 2 bits.

2023-12-12 13:28 UTC, ihhub commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +
I suggest to completely remove this option and make the second row to have just 2 options aligned appropriately. We can copy-paste a part of 2x2 window just for these 2 options.

2023-12-12 13:28 UTC, ihhub commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +                fheroes2::showStandardTextMessage( _( "Monitor Selection" ), _( "Toggle Between available monitors, Restart Required to take Effect" ), 0 );
As explained before we shouldn't use word **monitor**.

2023-12-12 13:54 UTC, MaMadDl commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +                fheroes2::engine().setDisplayId( ( fheroes2::engine().getDisplayId() + 1 ) % fheroes2::getNumberOfVideoDisplays() );
@ihhub  changes require restart cause i didn't want to recreate window
I have mentioned this on right click help

2023-12-12 13:57 UTC, ihhub commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +                fheroes2::engine().setDisplayId( ( fheroes2::engine().getDisplayId() + 1 ) % fheroes2::getNumberOfVideoDisplays() );
No, they do not. See how the application changes the resolution. We recreate a window from scratch.

2023-12-12 13:57 UTC, MaMadDl commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +                              fheroes2::getDisplayName( fheroes2::engine().getDisplayId() ), fheroes2::UiOptionTextWidth::TWO_ELEMENTS_ROW );
@ihhub if both monitor are the same name you need to click once then restart to see changes since you can't see them at runtime

2023-12-12 14:14 UTC, MaMadDl commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +                fheroes2::engine().setDisplayId( ( fheroes2::engine().getDisplayId() + 1 ) % fheroes2::getNumberOfVideoDisplays() );
@ihhub I saw that you are calling `updateUI()` after each change 
I was concerned about incompatibilities might occur if resolution is not supported by the new display. so I decided to not do it.
I will add it

2023-12-12 14:51 UTC, MaMadDl commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +
@ihhub do you mean something like this ?
![000](https://github.com/ihhub/fheroes2/assets/18714088/33db46b6-b3a1-44a3-b5ea-4295153293f4)

this can be done but new resource needs to be added to ICNs
(can be done in runtime but i think it would be messy)

2023-12-13 14:57 UTC, ihhub commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +                              fheroes2::getDisplayName( fheroes2::engine().getDisplayId() ), fheroes2::UiOptionTextWidth::TWO_ELEMENTS_ROW );
As I wrote in another comment clicking on something should provide a feedback to user. We mustn't restart the app for this.

2023-12-13 14:58 UTC, ihhub commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +
This **should** be done during runtime like as we do in many other place. Just use `fheroes2::Copy()` function for this matter.

2023-12-13 15:20 UTC, MaMadDl commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +                              fheroes2::getDisplayName( fheroes2::engine().getDisplayId() ), fheroes2::UiOptionTextWidth::TWO_ELEMENTS_ROW );
@ihhub I Added `UpdateUI()` in the latest Review Update

2023-12-13 20:56 UTC, MaMadDl reviewed
Hi @ihhub 
display change function now works in runtime (without the need to restart)
and i have changed the layout to 5 button layout like so :

![Screenshot 2023-12-14 001522](https://github.com/ihhub/fheroes2/assets/18714088/f14ec0f5-fa68-41ae-9ca0-99fc39badd51)
![Screenshot 2023-12-14 001450](https://github.com/ihhub/fheroes2/assets/18714088/69f8d285-8675-4137-bc54-4b362a68800f)

Could you please review them?

2023-12-20 15:06 UTC, ihhub commented
Hi @MaMadDl , I've been thinking about the use case of this option. Usually, player just drag a window of any application between multiple monitors without going to specific settings to do some magic. I think saving display ID and the position of a window is good enough. Giving an option to somehow switch between monitors seems to me unnatural. At least I haven't seen such functionality in any software.

2023-12-20 15:16 UTC, MaMadDl commented
Hi @ihhub, I've seen this option in almost all of modern game engines (one example is COD Warzone or simpler game like Rimworld). of course this could be done using Windowed Mode. but I personally like trapping cursor to bounding of the game (which windowed mode can't provide). to me not having this option cause a lot of frustration for me (like in all _From Software_ Games) and feels unnatural. as I've said in before, I required this feature to play so I added and thought in case others also needed this feature should be present.

2023-12-21 14:41 UTC, ihhub commented
Hi @MaMadDl , that's a fair point. Thanks for the explanation!

2024-01-13 13:38 UTC, ihhub requested changes
Hi @MaMadDl , I left few comments here. I will review deeper in the future. Could you please take a look at them when you have time?

2024-01-13 15:02 UTC, MaMadDl commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +        fheroes2::Display & display = fheroes2::Display::instance();
Hello @ihhub 
this line is used in line 283 and it's required to have access to `changeDisplayEngine` function
I can make it inline while calling `changeDisplayEngine` .

2024-01-13 15:11 UTC, MaMadDl reviewed
Hello @ihhub 
I have changed Reviewed  requested Please take a look.

2024-01-13 15:53 UTC, ihhub commented on src/engine/screen.cpp
> +        if ( int displayCount = SDL_GetNumVideoDisplays(); displayCount > 0 ) {
clang-format is correct about this. if-condition must not have any variable declarations.

2024-01-13 15:53 UTC, ihhub commented on src/engine/screen.h
> +        int getNumberOfVideoDisplays();
clang-tidy is correct about this as well.

2024-01-13 16:04 UTC, MaMadDl commented on src/engine/screen.cpp
> +        if ( int displayCount = SDL_GetNumVideoDisplays(); displayCount > 0 ) {
This is if-initializer Style introduced in C++17

2024-01-13 16:48 UTC, ihhub requested changes
Hi @MaMadDl , I proposed another solution in the comments. Could you please take a look?

2024-01-13 16:48 UTC, ihhub commented on src/engine/screen.h
> +        int getDisplayId() const
After further thinking: this class should have only 5 methods, all are virtual methods (notice I changed ID to index as we handled indicies):
```cpp
virtual uint8_t getCurrentDisplayIndex() const
{
    return 0;
}

virtual void setDisplayIndex( const uint8_t )
{
    // Do nothing.
}

virtual uint8_t getMaximumDisplays() const
{
    return 1;
}

virtual const char * getDisplayName( const uin8_t )
{
    return "";
}

protected:
...
virtual bool isAllocated() const
{
    return false;
}
```

There is no need for an extra member of a class as it should not be used for other technologies expect SDL 2.

Then inside `Display::setResolution();` method add a check if `!_engine->isAllocated()` then skip resolution check. This will avoid code duplication present in **changeDisplayEngine()**.

Then for SDL2 Render Engine class add a member `_displayIndex` and within `setDisplayIndex()` method call **clear** method.

Upon changing the display index the code would look like this:
```cpp
fheroes2::BaseRenderEngine & engine = fheroes2::engine(); // don't forget to cache it!
engine.setDisplayIndex( ( engine.getCurrentDisplayIndex() + 1 ) % fheroes2::engine().getMaximumDisplays() );

const fheroes2::ResolutionInfo currentResolution{ display.width(), display.height(), display.screenSize().width, display.screenSize().height };

[display](fheroes2::Display::instance()).setResolution( selectedResolution );
```

2024-01-13 16:48 UTC, ihhub commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +        placeholder = fheroes2::Crop( placeholder, 50, 30, dialog.width() - BORDERWIDTH * 2 - 20, optionWindowSize + 20 );
Right now what we do:
- get an image, create another image and copy it
- Crop a part of an image and replace newly created image
- use this cropped image to draw stuff once
- keep the cropped image for the duration of this dialog life

We should do everything by using the original image (`fheroes2::AGG::GetICN()`  returns const reference) and Blit / render it using the same coordinates you used in `Crop()` function call.

2024-01-15 00:19 UTC, MaMadDl reviewed
Hello @ihhub 
I have made Changes based on the reviews. could you please take look

2024-01-15 00:20 UTC, MaMadDl commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +        placeholder = fheroes2::Crop( placeholder, 50, 30, dialog.width() - BORDERWIDTH * 2 - 20, optionWindowSize + 20 );
You mean removing Crop and use another overload of Blit ?

2024-01-15 00:24 UTC, MaMadDl commented on src/engine/screen.h
> +        int getDisplayId() const
i have kept `engine ` and `display ` inside case (as I didn't know what you mean by caching it if not putting them before `while` loop)

also i have inverted the logic of `isAllocated` method since true should mean engine is allocated

2024-01-16 15:10 UTC, ihhub requested changes
Hi @MaMadDl , I left several more comment here. Can you please take a look?

2024-01-17 22:16 UTC, MaMadDl commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +            drawDisplay( windowSwitchDisplayRoi );
@ihhub I think it should remain even for Single Monitor. Clicking will have no effect

2024-01-17 22:40 UTC, MaMadDl reviewed
Hello @ihhub. I have made changes requested. Could you please take a look ?

2024-01-18 14:22 UTC, ihhub commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +            drawDisplay( windowSwitchDisplayRoi );
Yes, and this is why this option must be disabled if no changes appear. If an option is enabled users always expect to be able to click on it and something to happen.

2024-01-18 14:56 UTC, MaMadDl commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +            drawDisplay( windowSwitchDisplayRoi );
I think the name and meaning of option is intuitive enough that users will understand that. it's just like `effect` or `music` in audio settings, although the option itself won't change, but you can see the effects of your click as increase to audio levels. if it was something that would happen occasionally, I would agree

there are some instances like this ( changing fullscreen has no beneficial effect, should we disable that too while we are in android ? )

2024-01-19 13:26 UTC, ihhub requested changes
Hi @MaMadDl , I left few more minor comments here. We are almost there. Could you please take a look at them?

2024-01-19 13:26 UTC, ihhub commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +        // The Offsets are staticly fixed based on original image to Fill the empty spaces on the second row alongside with it's shadow
There is no need to make Image or Offsets to start with a capital letter, as well as Fill word.

2024-01-19 13:26 UTC, ihhub commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +            drawDisplay( windowSwitchDisplayRoi );
We have a separate issue to disable some options on some platforms like text support on Android devices.

2024-01-19 15:03 UTC, MaMadDl commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +            drawDisplay( windowSwitchDisplayRoi );
Overall I'm not against adding functionality when there's only 1 display. but disabling doesn't sounds like a good route since it will already is disabled and we don't have disabled ICN for `GAME_OPTION_ICON` ( like how VSync has)
Maybe we can Show a dialog if there's only 1 display connected

2024-01-20 03:04 UTC, ihhub commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +            drawDisplay( windowSwitchDisplayRoi );
We have a way to make any object disabled: please use `fheroes2::ApplyPalette( yourImage, PAL::GetPalette( PAL::PaletteType::DARKENING ) );` This is how all buttons or any other UI objects are rendered in a disabled state.

2024-01-20 14:34 UTC, MaMadDl commented on src/fheroes2/dialog/dialog_graphics_settings.cpp
> +            drawDisplay( windowSwitchDisplayRoi );
Do you want this added now ?

2024-02-06 14:59 UTC, MaMadDl commented
Hi, @zenseii i have not been able to reproduce Problem 1 . but I suspect it has something to do when we check for engine allocation in line `#1202 of screen.cpp` 

as for the Problem 2, I think we should check if resolution is supported by the current display. 
in allocate method there's a way this is done using `GetNearestResolution` but the problem is the `resolutions` the method is checking against is calculated for first display (`getAvailableResolutions` method checking for display 0 `line #859`).  

@ihhub what do you think ?

2024-02-17 14:17 UTC, MaMadDl commented
Hi @zenseii 

could you get the higher resolution before the change ? sadly both my displays are 1920x1080 so I cannot test this myself. 

but as far as I could tell `getAvailableResolutions` was always checking for available display resolutions for first display. 
I have changed this to calculate list of resolutions based on the display the window is in.
After a quick google search it appears that SDL has issues with HIDPI on window for 4k displays but I'm not an expert in SDL.

the error is caused by calling to `SDL_GetNumVideoDisplays()` in `getMaximumDisplays()` before engine is allocated. it could be avoided by checking for engine allocation (still testing).

2024-02-17 15:07 UTC, MaMadDl commented
@zenseii 
changes are already commited in [0287e22](https://github.com/ihhub/fheroes2/pull/8072/commits/0287e22ecbc30188946a6c91b590743dc1972599)

2024-03-04 17:04 UTC, MaMadDl commented
Hi @zenseii 

the error on startup is fixed.

also for the 4K resolution I think I found the problem :
in `getAvailableResolutions()` the lambda function is calculated at the startup once (with default display index 0) and after that every time its called we get the result from startup 
`line #855`:
`static const std::vector<fheroes2::ResolutionInfo> filteredResolutions = [=]() {`
can you check for your resolutions after removing `static const` 
like `std::vector<fheroes2::ResolutionInfo> filteredResolutions = [=]() {`

2024-03-16 18:12 UTC, MaMadDl commented
Hi @zenseii 

the error happens because SDL trying to render on a display that does not exists. 

because this could happen in any stage of the game and not just in options
the only solution I could think of is using `SDL_AddEventWatch` on `SDL_DisplayEvent` and re-allocate the engine in case the display goes out of bound 

let me know what you think.

2024-03-28 14:20 UTC, MaMadDl commented
> Meanwhile, I found another bug. When you have your screens set up to extend the primary screen, and end fheroes2 while it is being displayed on what is the second screen, then if you change to single screen mode, which means you're only using the 2nd screen or the first screen, then the App will throw an exception in `xstring.cpp line 401` when clicking on the Graphics option in settings:

Hi @zenseii 
to fix this I have added `SDL_DISPLAYEVENT` to localevent polling. in any stage of the game a display disconnect this event is called and allocating last available display in case current display is out of bound.



> I'm also getting this message in the console upon booting the game:
> 
> ```
> fheroes2 engine, version: 1.0.11
> 13.02.2024 16:37:32: [ERROR]    `anonymous-namespace'::RenderEngine::getMaximumDisplays:  Failed to Get Number of Displays, description: Video subsystem has not been initialized
> ```

Also this error is handled.

2024-04-01 21:08 UTC, MaMadDl commented
Hi @zenseii 
I'm unable to reproduce this error. can you check the conf file to see if resolution is saved or changed?
I haven't changed how resolution is saved or even works. (it's in line `#261` in `dialog_graphics_settings.cpp`)

2025-06-21 16:42 UTC, ihhub commented
I am closing this pull request as it isn't ready for merging and it wasn't changed for more than a year. Also, #9853 will solve the original problem of having multiple monitors and remembering which one was used.

2025-06-21 16:42 UTC, closed without merging