Make terrain type random for Battle Only mode
ihhub/fheroes2 pull request #8077
Opened 2023-11-25 03:15 UTC by ihhub

Also reduce the number of tiles being generated for this mode.

2023-11-25 14:40 UTC, Branikolog approved these changes

2023-11-25 15:01 UTC, Districh-ru requested changes
Hi, @ihhub. The changes to Battle Only mode works properly, well done!
I just left three comments to the code. Could you please take a look when you have time.

2023-11-25 15:02 UTC, ihhub commented on src/fheroes2/battle/battle_only.h
> +        bool _backupCompleted;
Yes! I missed it.

2023-11-25 15:05 UTC, Districh-ru approved these changes

2023-11-25 18:36 UTC, oleg-derevenetz approved these changes
LGTM. By the way, to diversify the background in battles, you can sometimes plant trees on free cells on those types of terrain on which it is possible. But this is just an optional cosmetic effect :)

2023-11-25 22:07 UTC, oleg-derevenetz commented on src/fheroes2/game/game_startgame.cpp
> +            world.generateBattleOnlyMap();
Is there any reason to regenerate the map when the Reset button is pressed?

2023-11-26 00:22 UTC, ihhub commented on src/fheroes2/game/game_startgame.cpp
> +            world.generateBattleOnlyMap();
Hi @oleg-derevenetz , we need to reset all stats for heroes which a user might change within this dialog.

2023-11-26 00:25 UTC, merged

2023-11-26 00:26 UTC, ihhub commented
Hi @oleg-derevenetz , yes, we can improve it later. Here are more things that we can do for this dialog.