Add basic logic to load and save maps through UI
ihhub/fheroes2 pull request #8096
Opened 2023-12-01 12:20 UTC by ihhub

- add a new map format entry - RESURRECTION and make the corresponding logic in the code
- rename some Settings class related methods
- add basic logic to load and save new maps
- expand new map format
- make code cleanup in `Maps::FileInfo` class

relates to #6845

2023-12-01 19:37 UTC, oleg-derevenetz commented on src/fheroes2/maps/map_format_info.h
> +    struct BaseMapFormat
Hi @ihhub could you please explain why there are two map formats - "base" and "extended"(?) and why there is separate function to load the "base" map format? In which cases is it planned to use the basic format, and in which cases - the extended one?

2023-12-02 00:18 UTC, ihhub commented on src/fheroes2/maps/map_format_info.h
> +    struct BaseMapFormat
Hi @oleg-derevenetz , the separation was done to handle 2 cases:
- load basic map information when we display a list of maps in the Editor and when we are going to display them for normal New Game. We should avoid reading unnecessary data due to performance issues on some old machines with HDDs (#6681)
- Extended format is used to load the map fully for the Editor and for the future game loading

2023-12-02 09:25 UTC, Districh-ru requested changes
Hi, @ihhub, I left some comments. Could you please take a look when you have time?

2023-12-02 09:25 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +                    const std::string dataPath = System::GetDataDirectory( "fheroes2" );
Why do we want to save map files to a hidden folder (... "AppData\Roaming" ...) instead of normal Maps folder located near the fheroes2 executable?
I was surprised when I didn't find just saved map in the Maps folder along with the SW and PoL maps.
IMHO al least we should allow user to choose where to save a map.

Also if we have map files with the same file name in both folders (normal and "hidden") "save map" will save to the "hidden" folder and "load map" will show and load file from the normal folder. So if I change a map from the normal maps folder and save it with the same file name I'll not be able to load the changed file.
This issue can be addressed later when we will implement a map save dialog.

2023-12-02 09:25 UTC, Districh-ru commented on src/fheroes2/maps/maps_fileinfo.cpp
>      // TODO: set the proper resurrection map extension.
This comment can be removed now. :)

2023-12-02 11:05 UTC, oleg-derevenetz commented on src/fheroes2/editor/editor_interface.cpp
> +                    const std::string dataPath = System::GetDataDirectory( "fheroes2" );
> Why do we want to save map files to a hidden folder (... "AppData\Roaming" ...) instead of normal Maps folder located near the fheroes2 executable?

Because normal MAPS folder may not be writable for the regular user, when app is installed to the Program Files on Windows, /usr on Linux or /opt on macOS. This is more correct approach.

2023-12-02 15:03 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectscenario.cpp
> +                         _( "Indicates whether the map is made for \"The Succession Wars\", \"The Price of Loyalty\" or \"Resurrection\" version of the game." ) );
Good point. I will revert this change and add a TODO comment.

2023-12-02 15:04 UTC, ihhub commented on src/fheroes2/editor/editor_mainmenu.cpp
>              showWIPInfo();
Yup.

2023-12-03 09:24 UTC, Branikolog commented
Hi, @ihhub .
Could you please, check if everything goes well in a few cases I found.

First of all I've noticed, that on map loading there's a short screen flickering:

https://github.com/ihhub/fheroes2/assets/55348946/089a3b21-19e5-40b4-8a5d-c36f338f2f40

As for the second, we can change capitalized symbols while saving a map.
Do we need some confirmation dialog or warning message, that the map name is already exist and the map is going to be overwritten?
I'm afraid, that in future there could be a mess with map names.

https://github.com/ihhub/fheroes2/assets/55348946/5b6b45de-4d6d-4f6c-865f-62cf509b6286

2023-12-03 09:47 UTC, ihhub commented
Hi @Branikolog , short flickering was even before. My changes do not introduce it.

 File overriding confirmation is not implemented in this pull request. We will add it later. I attempted to make minimal changes to unblock the rest of work.

2023-12-03 15:22 UTC, Branikolog commented
@ihhub 
Okay. I just wanted to be sure you're aware of these issues.

One more question:

![image](https://github.com/ihhub/fheroes2/assets/55348946/8153ab7c-1f91-4a7f-a513-b6de24bd8aa0)

I've noticed, that we have a "Resurrection" type map even in the description. But all maps are showing "Succession wars map". Is this description differentiation is not implemented yet?

2023-12-03 18:06 UTC, Districh-ru approved these changes

2023-12-03 18:10 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +                    const std::string dataPath = System::GetDataDirectory( "fheroes2" );
Lets choose for now the easiest way that will work on all systems. And later, after Editor is released we may update map save/load to allow use of different paths.
Maybe we should not name the folder "maps" not to confuse with the folder "maps" with the original maps. Maybe something like "fh2maps". Then all users will know that this is a place for maps made by fheroes2 Editor.
What do you think, @ihhub?

2023-12-04 13:42 UTC, oleg-derevenetz commented
Hi @ihhub

> I noticed that clang-tidy complained about something different today. Looks like it was updated by its authors.

Yeah, by me - https://github.com/platisd/clang-tidy-pr-comments/pull/57 :)

2023-12-04 13:43 UTC, ihhub commented
> Hi @ihhub
> 
> > I noticed that clang-tidy complained about something different today. Looks like it was updated by its authors.
> 
> Yeah, by me - [platisd/clang-tidy-pr-comments#57](https://github.com/platisd/clang-tidy-pr-comments/pull/57) :)

But the new rule wasn't added by you :)

2023-12-05 00:20 UTC, merged