Increased width and height of the Campaign Difficulty selection dialog
ihhub/fheroes2 pull request #8111
Opened 2023-12-07 15:40 UTC by roman-yagodin

This one resolves #7511.

## Changes:

- Splitted difficulty icons for separate rendering to allow further changes.
- Recalculated things based on difficulty icon size and its shadow size.
- Increased dialog width, slightly inreased top margin for description text and also dialog height.

## Screenshots:

English, good interface:

![camp_difficulty_good_en_1](https://github.com/ihhub/fheroes2/assets/5691178/ee53895a-7303-4119-97d7-e94f495ee1ad)

Bulgarian, evil interface:

![camp_difficulty_evil_bg_1](https://github.com/ihhub/fheroes2/assets/5691178/80324896-ad87-477e-8cd8-73eefd2c3091)

Some difficulty options disabled (test):

![camp_difficulty_good_bg_dis_3](https://github.com/ihhub/fheroes2/assets/5691178/2f338e7b-ec91-4bec-94f6-d4a0b379d233)

![camp_difficulty_evil_bg_dis_2](https://github.com/ihhub/fheroes2/assets/5691178/092b6d5d-c77c-45a0-9f82-57da5877c536)

Dialog window width increased to 600 (test):

![camp_difficulty_good_en_2](https://github.com/ihhub/fheroes2/assets/5691178/08abde0b-b04b-4841-80f5-9a99622876d5)

2023-12-10 15:06 UTC, ihhub requested changes
Hi @roman-yagodin , I left 2 small optimization related comments. Would you mind to take a look once you have time?

2023-12-10 15:06 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +            const std::vector<uint8_t> goodToEvilPalette = PAL::GetPalette( PAL::PaletteType::GOOD_TO_EVIL_INTERFACE );
Please make this variable a const reference. Right no we are making a copy of the container.

2023-12-10 15:06 UTC, ihhub commented on src/fheroes2/game/game_campaign.cpp
> +                                    copyFromArea[2].height, goodToEvilPalette );
We can reduce code duplication and avoid hardcoded values by doing this:
```cpp
for ( size_t i = 0; i < copyToOffset.size(); ++i ) {
    fheroes2::ApplyPalette( display, copyToOffset[i].x, copyToOffset[i].y, display, copyToOffset[i].x, copyToOffset[i].y, copyFromArea[i].width,
        copyFromArea[i].height, goodToEvilPalette );
}
```

The same actually applies to lines 927-929.

2023-12-10 17:13 UTC, roman-yagodin commented
Hi, @ihhub! Sure.

2023-12-12 13:52 UTC, ihhub approved these changes

2023-12-12 13:55 UTC, ihhub approved these changes

2023-12-12 13:59 UTC, merged

2023-12-12 14:00 UTC, ihhub commented
@roman-yagodin , thank you so much for you contribution to the project!

2023-12-12 14:08 UTC, ihhub commented
@roman-yagodin , no worries. I did the changes because we are getting close to the release date and I would like to have more changes to be merged.