Hungarian language update #09
ihhub/fheroes2 pull request #8119
Opened 2023-12-10 13:44 UTC by big4billy

Systemathic fuzzy removals everywhere

2023-12-12 13:34 UTC, ihhub requested changes
Hi @big4billy , I put several comments here. Could you please check them?

2023-12-12 13:34 UTC, ihhub commented on files/lang/hu.po
> +"Ha iszol az oázisban, akkor az egységeid ereje és morálja feltöltődik."
Why a space was removed? It is a separation between 2 sentences.

2023-12-12 13:34 UTC, ihhub commented on files/lang/hu.po
> -"Ha iszol a vizesgödörnél, akkor az egységeid ereje és hangulata feltöltődik. "
Why a space was removed? It is a separation between 2 sentences.

2023-12-12 13:34 UTC, ihhub commented on files/lang/hu.po
> +"tárgyalást."
Please add a space at the end as there will be another sentence after.

2023-12-12 20:50 UTC, big4billy commented on files/lang/hu.po
> +"Ha iszol az oázisban, akkor az egységeid ereje és morálja feltöltődik."
space added back

2023-12-12 20:51 UTC, big4billy commented on files/lang/hu.po
> -"Ha iszol a vizesgödörnél, akkor az egységeid ereje és hangulata feltöltődik. "
space added back

2023-12-12 20:56 UTC, big4billy commented on files/lang/hu.po
> +"tárgyalást."
one space added at the end.

2023-12-13 14:59 UTC, ihhub approved these changes

2023-12-13 15:14 UTC, merged