Add Tree of Knowledge claimed and cost info to quick info dialog
ihhub/fheroes2 pull request #8147
Opened 2023-12-17 16:38 UTC by zenseii

<img width="147" alt="image" src="https://github.com/ihhub/fheroes2/assets/12501091/dcb6cbda-0c70-4417-af12-8772d70be6bc">

<img width="151" alt="image" src="https://github.com/ihhub/fheroes2/assets/12501091/f7df88d3-7767-4920-899a-852c660e9acb">

<img width="148" alt="image" src="https://github.com/ihhub/fheroes2/assets/12501091/05e4ff86-e3e7-4f17-b609-76e537969637">

2023-12-17 17:51 UTC, Districh-ru requested changes
Hi, @zenseii. I very like this improvement - currently when I have many heroes and there are many Trees of Knowledge on the map it is hard to remember what hero has visited what tree (I don't talk about remembering what resources each Tree demands).
I left one comment regarding getting "level gained" info. Could you please take a look when you have time.

2023-12-17 17:51 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +                str.append( hero->isObjectTypeVisited( objectType ) ? _( "(already gained)" ) : _( "(not gained)" ) );
We can not rely only on object type here: if you visit one Tree, then all other Trees will show "(already gained)" even if the level was not gained by that tree.
```suggestion
                str.append( hero->isVisited( tile ) ? _( "(already gained)" ) : _( "(not gained)" ) );
```

2023-12-17 19:39 UTC, Districh-ru approved these changes

2023-12-18 11:28 UTC, LeHerosInconnu commented
Hello @zenseii,

I haven't tested this PR, but I think the expressions already used in other places, i.e. "(already visited)" and "(not visited)" should be used.
This would give continuity to the expressions and be more "natural" according to the hero selected.
Also, when no hero is selected, the right-click information window should also indicate the cost, but without the expression "(already visited)" or "(not visited)".
In addition, in the current state of a hero's experience point progression, it may happen that a hero gains several levels when visiting a tree of knowledge.
The use of the word "level" therefore becomes problematic in this case if it does not correspond to the result of the visit to the location, one or more levels gained.

2023-12-18 13:59 UTC, ihhub requested changes
Hi @zenseii , I left 2 minor optimizations. Could you please take a look at them?

2023-12-18 13:59 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +                str.append( std::to_string( rc.second ) + " " );
Let's do this way:
```cpp
str.append( std::to_string( rc.second ) );
str += ' ';
```
This should be faster.

2023-12-18 13:59 UTC, ihhub commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +                str.append( "\n" );
Let's do this way:
```cpp
str += '\n';
```

2023-12-18 15:59 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_quickinfo.cpp
> +                str.append( std::to_string( rc.second ) + " " );
Hi, @zenseii, in the last commit the `str += ' ';` was added, so we should remove this inserted space from the upper line :)
```suggestion
                str.append( std::to_string( rc.second ) );
```

2023-12-18 16:33 UTC, Districh-ru approved these changes

2023-12-19 02:45 UTC, ihhub approved these changes

2023-12-19 02:54 UTC, merged

2023-12-19 02:54 UTC, ihhub commented
@zenseii , thank you so much for the improvement!

2023-12-19 11:56 UTC, LeHerosInconnu commented
Hello @zenseii,

> @LeHerosInconnu
> 
> > I wouldn't call it laziness here, but a convention for places that give a bonus. The hero has not yet benefited from the location bonus: "(not visited)". The hero has already benefited from the location bonus: "(already visited)". This seems clear to me and in line with the other bonus locations. And that's how it works in the original game.
> 
> I don't see the benefit of such continuity, compared to the clear benefits of unambiguity. Also, we are already fine with **not** having 100 % continuity in for example the Shrines, which state `(already learned)` and **not** `(already visited)` : <img alt="image" width="173" src="https://private-user-images.githubusercontent.com/12501091/291329603-69ca272b-1b23-4e4e-8229-40edb8a05ced.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODM0NTUsIm5iZiI6MTcwMjk4MzE1NSwicGF0aCI6Ii8xMjUwMTA5MS8yOTEzMjk2MDMtNjljYTI3MmItMWIyMy00ZTRlLTgyMjktNDBlZGI4YTA1Y2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDEwNTIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4M2MxNGI1NDVjYTE0ODViNjc1NDUyNjE3YzQ3ZGZjY2RmMTI5M2M4MjA5ZDA5MzZjYTg0OTc4YmY0Mjk5N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hIVy2ukydX5KnkfDVPXaWFUnphyQUipWWe3lD5dGO50">
> 
> Addiontally, the Witch's huts' `(already knows this skill)` would have to be `(already visited)` then : <img alt="image" width="167" src="https://private-user-images.githubusercontent.com/12501091/291330275-08871bc2-5632-4914-8b12-927288a26882.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODM0NTUsIm5iZiI6MTcwMjk4MzE1NSwicGF0aCI6Ii8xMjUwMTA5MS8yOTEzMzAyNzUtMDg4NzFiYzItNTYzMi00OTE0LThiMTItOTI3Mjg4YTI2ODgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDEwNTIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkOTMxNTY4YmEwYWIzZWU3YjRjYzRjYjg5NGFmZWQ1MGEyZWFhNzU0NGQ0ZTc3YjNlZjBhZTVhMjY4NTMyYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C2Xoe0n_ssGJ8a3ld2_BWW-KAJ9bNDraeH66SjC_V38">
> 
> If we seriously want to adopt this `(already visited)`, which **really** carries the meaning of "already visited and claimed whatever you can from", then we would have to change also the shrines, the witch's huts, etc., for continuity's sake.
> 
> To me having `(visited)` for the Tree of Knowledge makes as much sense as having `(talked to)` and `(not talked to)` for it.
> 
> On the contrary, I argue that variety in what words and expressions we use only enrichens the game and the experience, and self-imposed restrictions for the vocabulary of the game just so that a few words are used everywhere, is an unnecessary restriction with debatable benefits.

In the original game, for the shrine and witch's hut, the spell and secondary skill are not indicated in the right-click information window.
Also, these locations, unlike others such as the tree of knowledge, gazebo, mercenary camp, etc., do not systematically give a bonus when visited.
The hero can learn the spell or secondary skill in another way, making a visit to the place useless if he has already learned the spell or secondary skill.
A different, and added text compared to the original version of the game, can and should therefore be used.
For the tree of knowledge, the expressions "(not visited)" and "(already visited)" are already used in the original game, and I think they play their informative role well.

Also, for the witch's hut, I think the expression "(already learned)" could replace the expression "(already knows this skill)" to simplify the expression (we know it's a skill, and we don't indicate "(already knows this spell)" either).
And, for the shrine and witch's hut, when the hero doesn't know the spell or secondary skill, there's no expression to indicate this fact, only the name of the spell or secondary skill is indicated.
I think we should also display the expression "(not learned)" when a hero is selected and doesn't know the spell or secondary skill, as this is confusing with displaying the spell and secondary skill when no hero is selected.
I always tend to check that a hero is selected when I right-click on a shrine or witch's hut, which shouldn't be the case.
The interface in this case is not "uniform" in the way it indicates information to the player.
I can open a specific issue if necessary.