WIP: Rework editor instrument groups: add new buttons, rework instrument panel, add evil inerface
ihhub/fheroes2 pull request #8150
Opened 2023-12-18 18:52 UTC by Districh-ru

This PR expands the list of editor instrument buttons by one more row to divide objects into 4 global groups:
- Landscape objects
- Adventure objects
- Kingdom objects
- Monsters

It also makes instrument panel size flexible and adds the evil interface to the buttons and the panel.

TODO:
- [ ] implement temporary images for object groups;
- [ ] fix images on some evil interface buttons.

![изображение](https://github.com/ihhub/fheroes2/assets/113276641/220e837d-bdb9-4da7-b259-e71abdaa6d05) ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/4ea0a691-c861-4841-a76d-0544407b471b)

2023-12-20 11:30 UTC, ihhub requested changes
Hi @Districh-ru , I put several comment in this pull request. Could you please take a look at them?

2023-12-20 11:30 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +        }
Clicking on an empty space for monsters is not intuitive. We should open a dialog selection if no monster was chosen previously.

2023-12-20 11:30 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            // Adventure objects buttons.
No selection should be done until a user clicks on something. Otherwise, it is not obvious what is happening.

2023-12-20 15:59 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +        fheroes2::Blit( image, 0, 0, newImage, 2, 2, 35, 25 );
Hi, @ihhub, sure, I forgot to reset the image here!
Thanks for noticing it!

2023-12-20 16:00 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +        uint8_t * transform = image.transform();
OK. I added the assertion that image is not empty and not single-layer.

2023-12-20 16:01 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                        Copy( pressed, _icnVsSprite[id][35 + 1 + i] );
Yes, it will be faster.
Thanks!

2023-12-20 16:05 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                    ReplaceColorId( _icnVsSprite[id][8], 46U, 65U );
Valuable suggestion, thanks!

2023-12-20 16:06 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +        }
Done. I also added a text noticing where to click if user will cancel monster selection.

2023-12-20 16:06 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            // Adventure objects buttons.
Done.

2023-12-21 14:08 UTC, ihhub commented
Hi @Districh-ru , let's move it to the next release as we want to have enough time to test the release.

2023-12-21 14:37 UTC, ihhub requested changes
Hi @Districh-ru , I put several more comments in this pull request. Would you mind to check them?

2023-12-21 14:37 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +    void makeAllShadowsTransparent( fheroes2::Image & image )
Let's call it `setTransformLayerTransparent()` because there are some images have more than just shadows.

2023-12-21 14:37 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    }
We can use `std::iota` which does exactly the same :)

2023-12-21 14:37 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +        fheroes2::StandardWindow::renderBackgroundImage( background, { 0, 0, width, height }, 0, Settings::Get().isEvilInterfaceEnabled() );
This is a bit risky: **background** is not reset. We need to make sure that no other places in the image are uninitialized.

2023-12-21 14:37 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +                const fheroes2::Text text( _( "Click here to\nselect a monster." ), fheroes2::FontType::smallWhite() );
I suggest to keep this text even if a monster is drawn. This will be clear for every person to know what to do.

2023-12-21 17:37 UTC, Districh-ru commented
> Hi @Districh-ru , let's move it to the next release as we want to have enough time to test the release.

Hi, @ihhub, sure)

2023-12-21 17:37 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +    void makeAllShadowsTransparent( fheroes2::Image & image )
Yes, it's a better name for this function.

2023-12-21 17:38 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                    }
Sure. Initially I thought about using it, but left a for loop to be consistent with the other code. :)

2023-12-21 17:39 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +                const fheroes2::Text text( _( "Click here to\nselect a monster." ), fheroes2::FontType::smallWhite() );
Done, I also added the monster's name.

2023-12-21 17:52 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +        fheroes2::StandardWindow::renderBackgroundImage( background, { 0, 0, width, height }, 0, Settings::Get().isEvilInterfaceEnabled() );
`renderBackgroundImage()` draws the image to every pixel in given `roi` ( `{ 0, 0, width, height }` ) to the "background" image which is ( `width` x `height` ) size. Every pixel in this single-layer image will contain a correct image data (transform layer will be never used).
So IMHO it is redundant to write a zero to every pixel (and "1" to the unused transform layer) and then write the image over these zeros. :)

2023-12-24 04:05 UTC, ihhub commented
Hi @Districh-ru , I've tested this pull request and I found multiple issues:
1. The selection item name box is moving for heroes and towns while clicking on any type there:

https://github.com/ihhub/fheroes2/assets/19829520/196a3938-5c71-40f3-a7f6-ed6bd0a61651

2. We can move the selection item name box lower so the group icons will have more space in between them. I am attaching a screenshot of 640x480 resolution and the group with the highest amount of types.

![image](https://github.com/ihhub/fheroes2/assets/19829520/174e2872-8c32-4928-b942-4928469e4128)

We can easily have 3 rows of items. This is a mockup:
![image](https://github.com/ihhub/fheroes2/assets/19829520/4619069a-93c6-4900-a144-d3f2f11bc25b)

2023-12-24 04:36 UTC, ihhub requested changes
Hi @Districh-ru , I left several more comments here. Could you please take a look at them when you have time?

2023-12-24 04:36 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.h
> +            LANSCAPE_COUNT = 5,
`LANSCAPE_COUNT` is misspelled.

2023-12-24 04:36 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            }
In order to avoid code duplication we can create a template function for this:
```cpp
template <size_t TSize>
void updateItemSelection( const uint8_t objectId, const std::array<fheroes2::Rect, TSize> & areas, const std::function<const char *(uint8_t)> & getObjectTypeName, const fheroes2::Rect & area )
{
    fheroes2::Display & display = fheroes2::Display::instance();

    if ( objectId < 0 ) {
        drawInstrumentName( display, { area.x + 7, area.y + 76 }, _( "Select object type" ) );
    }
    else {
        drawObjectTypeSelectionRect( display, areas[objectId].getPosition() );
        drawInstrumentName( display, { area.x + 7, area.y + 76 }, getObjectTypeName( objectId ) );
    }
}
```

Name of variables and function are subject of change, And then we can call this function as:
```cpp
updateItemSelection<LandscapeObjectBrush::LANSCAPE_COUNT>( _selectedLandscapeObject, _landscapeObjectButtonsRect,
    _getLandscapeObjectTypeName, _rectInstrumentPanel );
```

Is this a better solution?

2023-12-24 04:36 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            fheroes2::Copy( originalPanel, 102, 68, display, _kingdomObjectButtonsRect[KingdomObjectBrush::HEROES].x,
We have a lot of hardcoded values in this file. We should use variables for them to improve code readability and to minimize any future changes.

2023-12-24 04:36 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            // Instrument name.
I think this is not a valid comment.

2023-12-24 04:36 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            terrainText.draw( _rectInstrumentPanel.x + 5, _rectInstrumentPanel.y + 8, _rectInstrumentPanel.width - 10, display );
Should we use another name instead of **terrainText**? It is misleading since for this and other cases in the code we do not refer to terrain.

2023-12-24 04:36 UTC, ihhub commented
Hi @zenseii , can you please review newly added texts for the Editor?

2023-12-24 04:54 UTC, ihhub commented
Hi @drevoborod , if you have a spare time can you please help to test this pull request?

2023-12-24 07:15 UTC, ihhub commented
Hi @Districh-ru , regarding my second note: we can do it later. This pull request should focus on functionality first.

2023-12-24 08:40 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.h
> +            LANSCAPE_COUNT = 5,
Thanks!

2023-12-24 08:43 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            }
Sure, its a much better solution!
But now IWYU wands to include <tuple> for array... We already include <array> in H file for array, but why <tuple> ??
@ihhub, should I please IWYU or I need fix the code, please help me to understand where I made a mistake. :)

2023-12-24 08:44 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            fheroes2::Copy( originalPanel, 102, 68, display, _kingdomObjectButtonsRect[KingdomObjectBrush::HEROES].x,
Most of such hardcoded values are for original ICN images.
I tried to make variables for most of such hardcoded variables.

2023-12-24 08:46 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            terrainText.draw( _rectInstrumentPanel.x + 5, _rectInstrumentPanel.y + 8, _rectInstrumentPanel.width - 10, display );
Ow.
I copy-pasted the code, adopted it to render the needed text, but forgot to change the variable name. :(
Thanks for noticing this!

2023-12-24 08:46 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            // Instrument name.
Now with the correct variable name there is no need for a comment here.

2023-12-24 08:48 UTC, Districh-ru commented
Hi @ihhub and @zenseii, I made the suggested changes. Could you please check them when you have time.

2023-12-24 10:34 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            }
Hi @Districh-ru , let's please IWYU by adding an extra header. No harm doing this.

2023-12-24 10:47 UTC, ihhub requested changes
Hi @Districh-ru , I left one more suggestion here. Can you please check it?

2023-12-24 10:47 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            fheroes2::Copy( originalPanel, originalArtifactsImageOffsetX, originalImagesOffsetY, display, _adventureObjectButtonsRect[AdventureObjectBrush::ARTIFACTS].x,
I can see that we have a lot of `fheroes2::Copy()` calls and it doesn't look readable. I suggest to add a new function within **image.h|cpp** files to accept Rect:
```cpp
void Copy( const Image & in, int32_t inX, int32_t inY, Image & out, const Rect & outRoi )
{
    Copy( in, inX, inY, out, out.x, out.y, out.width, out.height );
}
```
This will greatly simplify the code.

2023-12-24 11:07 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            }
OK

2023-12-24 11:08 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +            fheroes2::Copy( originalPanel, originalArtifactsImageOffsetX, originalImagesOffsetY, display, _adventureObjectButtonsRect[AdventureObjectBrush::ARTIFACTS].x,
Sure, there were some other places where such function will simplify the code.

2023-12-24 11:16 UTC, ihhub approved these changes

2023-12-24 11:21 UTC, merged

2023-12-24 11:21 UTC, ihhub commented
@Districh-ru , thank you very much for these changes!