Add text width-adapted CANCEL button, change to StandardWindow for Resolution, Language, Adventure, File and Scenario Info dialogs
ihhub/fheroes2 pull request #8154
Opened 2023-12-20 13:20 UTC by zenseii

This PR makes the single-lined CANCEL button adapt its width according to the text on it.

To make this possible it was necessary to switch to the StandardWindow class for the Language, Resolution, Adventure, File and Scenario Info dialogs. This also gives an evil interface mode for the first two mentioned dialogs plus the Scenario Info dialog.

The Uniform CANCEL button was adapted too and the Player name input dialog's keyboard button had to be moved to allow for that extra button width, since we don't have a way of widening that dialog yet.

The Scenario Info dialog's height was increased by a few pixels to avoid the overlapping of the handicap icons' shadow with the Okay and Cancel buttons.

2023-12-22 17:14 UTC, Districh-ru requested changes
Hi, @zenseii. Thanks for updating these dialogs. In the future, I'll try to improve StandardWindow to reduce code duplication in such dialogs.
I left several comments. Could you please take a look in your spare time.

2023-12-22 17:14 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_language_selection.cpp
> +            }
While holding the right mouse button (RMB) a user can press Up or Down key and select another language, but no dialog will be performed until RMB is released:

https://github.com/ihhub/fheroes2/assets/113276641/9b175395-ace1-4350-83f4-7b5ce23f4c5c

We can place this check before the 230 line and then no event processing will be done until the RMB is released.

2023-12-22 17:14 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_resolution.cpp
> +                continue;
The same comment as previous: we can move this condition before the 266 line.

2023-12-22 17:14 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_resolution.cpp
> +            bool needRedraw = listId != listBox.getCurrentId();
This variable also can be **const**. :)

2023-12-23 10:29 UTC, Districh-ru requested changes
Hi, @zenseii. The new dialogs works okay. I just left a minor speed-up suggestion. Could you please consider it when you have time.

2023-12-23 10:29 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_language_selection.cpp
> +            if ( !listBox.IsNeedRedraw() && !needRedraw ) {
We can simplify this check: `needRedraw` can be `true` only after `_currentId` is changed during the `QueueEventProcessing();`. And if it is changed then `listBox.IsNeedRedraw()` will be true.
So there is no need to check `needRedraw` here.
```suggestion
            if ( !listBox.IsNeedRedraw() ) {
```

2023-12-23 10:29 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_resolution.cpp
> +            if ( !listBox.IsNeedRedraw() && !needRedraw ) {
The same comment here :)
```suggestion
            if ( !listBox.IsNeedRedraw() ) {
```

2024-01-02 14:04 UTC, ihhub requested changes
Hi @zenseii , I left several comments here. Would you mind to take a look at them in your spare time?

2024-01-02 14:04 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    Copy( _icnVsSprite[id][0], 6, 5, _icnVsSprite[id][1], 6, 5, 359, 19 );
I am actually worried about this part of the code. Are we certain that we copy everything into the new image? If something is missing (like we forget to copy even a single pixel) then on release builds we are going to face some graphical artefacts. In this case we have 2 solutions:
1. Add `reset()` call after the creation of the image
2. Verify that we indeed populate the whole image completely

2024-01-02 14:04 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    Copy( croppedImage, 0, 0, _icnVsSprite[id][0], 123, 0, 123, 45 );
I think we can avoid having `Crop()` call here and directly call `Copy()` using the original image. It is going to be much faster.

2024-01-03 08:16 UTC, Districh-ru requested changes
Hi, @zenseii, I did a quick overview of PR and left some comments. Could you please check them when you have time.
I'll do a more thorough review tomorrow.

2024-01-03 08:16 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +            case ICN::METALLIC_BORDERED_TEXTBOX: {
In many other cases the Evil sprite has a different ICN id while here we have the same ICN id and different image index for Good and Evil interfaces.
IMHO it should be good to leave a comment about this. :)
Or should we change to the `METALLIC_BORDERED_TEXTBOX_GOOD` and `METALLIC_BORDERED_TEXTBOX_EVIL` ICNs to correspond the all other cases with Good/Evil interface sprites?

2024-01-03 08:16 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_adventure.cpp
> +            buttonDig.disable();
To render the disabled button we should also call `.draw()` method here:
```suggestion
            buttonDig.disable();
            buttonDig.draw();
```

2024-01-03 08:16 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_adventure.cpp
> +        display.render( background.totalArea() );
In the loop we can render only the `activeArea` (the inner dialog area where all dialog items can change). The `totalArea` should be rendered only when dialog is opened and closed to render also the dialod borders and its shadow.
```suggestion
        display.render( background.activeArea() );
```

This comment is also for other changed dialogs.

2024-01-04 08:13 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_adventure.cpp
> +        display.render( background.totalArea() );
@zenseii, you are absolutely right with these changes!

2024-01-04 09:31 UTC, Districh-ru requested changes
Hi, @zenseii, I left several comment. Could you please take a look when you have time?

2024-01-04 09:31 UTC, Districh-ru commented on src/fheroes2/gui/player_info.cpp
>              if ( conf.getCurrentMapInfo().AllowChangeRace( player->GetColor() ) ) {
To make Sonar a little happier we should combine these two conditions:
```suggestion
        if ( player != nullptr && conf.getCurrentMapInfo().AllowChangeRace( player->GetColor() ) ) {
```

2024-01-04 09:31 UTC, Districh-ru commented on src/fheroes2/gui/player_info.cpp
>              if ( conf.getCurrentMapInfo().AllowChangeRace( player->GetColor() ) ) {
These two conditions can also be combined.

2024-01-04 09:31 UTC, Districh-ru commented on src/fheroes2/game/game_scenarioinfo.cpp
>                  if ( playersInfo.QueueEventProcessing() ) {
These two conditions can also be combined. :)

2024-01-04 09:31 UTC, Districh-ru commented on src/fheroes2/game/game_scenarioinfo.cpp
> +        fheroes2::Text text( Settings::Get().getCurrentMapInfo().name, fheroes2::FontType::normalWhite() );
This variable can be `const`.

2024-01-04 09:31 UTC, Districh-ru commented on src/fheroes2/game/game_scenarioinfo.cpp
>                  display.render();
Here we can do render only in the `activeArea()`:
```suggestion
                display.render( roi );
```

2024-01-04 09:31 UTC, Districh-ru commented on src/fheroes2/game/game_scenarioinfo.cpp
> +                    ratingRoi = RedrawRatingInfo( roi.getPosition(), roi.width );
Rating text possibly can be better vertically aligned with the OK/Cancel buttons (about 3 pixels lower), what do you think?
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/b8012c0c-f5f0-4fdb-8b43-420d92986554)

2024-01-04 09:31 UTC, Districh-ru commented on src/fheroes2/game/game_scenarioinfo.cpp
> +                    display.render( background.activeArea() );
We can simply use `roi` here not to call once again the `activeArea()` method:
```suggestion
                    display.render( roi );
```

2024-01-04 09:31 UTC, Districh-ru commented on src/fheroes2/game/game_scenarioinfo.cpp
> +                    display.render( background.activeArea() );
And here too. :)
```suggestion
                    display.render( roi );
```

2024-01-04 09:31 UTC, Districh-ru commented on src/fheroes2/game/game_scenarioinfo.cpp
> +                    display.render( background.activeArea() );
```suggestion
                    display.render( roi );
```

2024-01-04 15:17 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_adventure.cpp
>  }
OK, we can leave it if it is safer and fixes some crashes. But having a lot of functions that only calls one next function can result in a mess of calls. :)
I never encountered such bugs on resolution change.... If I do I'll check what is happening.

2024-01-04 15:23 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_file.cpp
> +        fheroes2::ImageRestorer back( display, ( display.width() - totalDialogWidth - BORDERWIDTH ) / 2, ( display.height() - totalDialogHeight + BORDERWIDTH ) / 2,
It was needed before we started to use the `StandardWindow` which has its own restorer that is called in destructor.
`return Interface::AdventureMap::Get().EventSaveGame();` finises the execution of the current function and the lifeline of created instance of `StandardWindow`. So the destructor with the restorer will be called and there is no need to restore the background just before the destructor which will do the same.
If the new dialog was called in this function then we would need to use `back.restore();`.

2024-01-04 15:24 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_file.cpp
>  }
OK, lets leave the decision to @ihhub. :)

2024-01-04 15:42 UTC, Districh-ru commented on src/fheroes2/game/game_scenarioinfo.cpp
>                  display.render();
Ow, then its OK. :)

2024-01-04 15:48 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_file.cpp
> +        fheroes2::ImageRestorer back( display, ( display.width() - totalDialogWidth - BORDERWIDTH ) / 2, ( display.height() - totalDialogHeight + BORDERWIDTH ) / 2,
Sorry, I was wrong.

2024-01-04 16:00 UTC, Districh-ru commented
@zenseii, could you please resolve the merge conflicts.

2024-01-04 16:06 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_file.cpp
> +        fheroes2::ImageRestorer back( display, ( display.width() - totalDialogWidth - BORDERWIDTH ) / 2, ( display.height() - totalDialogHeight + BORDERWIDTH ) / 2,
Yes, the method `EventSaveGame()` is called from the `return`, so the `StandardWindow` destructor will be executed only after this function.
We can use a `std::unique_ptr` for `StandardWindow` instance and "release" it here just before the `return`.
But lets do it later, this PR focuses on the other things and is big enough. Lets merge it. :)

2024-01-04 16:48 UTC, Districh-ru approved these changes
Well done @zenseii, the GUI gets better and better!

2024-01-05 13:47 UTC, ihhub approved these changes

2024-01-05 13:48 UTC, merged

2024-01-05 13:48 UTC, ihhub commented
@zenseii , huge thanks for these essential updates!