Hide swap army/artifact buttons in the Battle Only
ihhub/fheroes2 pull request #8174
Opened 2023-12-24 16:29 UTC by a1exsh

The buttons are not actually active, so it's confusing to have them there:

- Before:
   ![image](https://github.com/ihhub/fheroes2/assets/489601/7543002a-075d-4627-96c3-79683400fa69)
- After:
  ![image](https://github.com/ihhub/fheroes2/assets/489601/099e48cd-576b-4d49-a6aa-8705e5004653)

Related: #4352

2023-12-24 18:35 UTC, Districh-ru requested changes
Hi, @a1exsh, thanks for your contribution!
I left one minor suggestion. Could you please take a look when you have time.

2023-12-24 18:35 UTC, Districh-ru commented on src/fheroes2/battle/battle_only.cpp
> +    fheroes2::Blit( moveButtonBackground, 292, 363, display, top.x + 292, top.y + 363, 48, 44 );
Since the original image (STONEBAK) has no shadows or transparency, we can use `Copy()` instead of `Blit()` to speed up rendering a bit.
```suggestion
    fheroes2::Copy( moveButtonBackground, 292, 270, display, top.x + 292, top.y + 270, 48, 44 );
    fheroes2::Copy( moveButtonBackground, 292, 363, display, top.x + 292, top.y + 363, 48, 44 );
```

2023-12-25 00:12 UTC, ihhub commented on src/fheroes2/battle/battle_only.cpp
> +    fheroes2::Blit( moveButtonBackground, 292, 363, display, top.x + 292, top.y + 363, 48, 44 );
No, `Blit()` behaves as `Copy()` only when handling single-layer images. By default images are double-layer images. Therefore, the complexity of the operation increases leading to slower execution.

2023-12-25 00:12 UTC, ihhub approved these changes

2023-12-25 03:02 UTC, Districh-ru approved these changes
👍

2023-12-25 03:07 UTC, merged

2023-12-25 03:07 UTC, ihhub commented
@a1exsh , thank you so much for the fix!