Hungarian language update #13
ihhub/fheroes2 pull request #8183
Opened 2023-12-25 20:28 UTC by big4billy

* Some grammar corrections (especialy on artifact names' capitals);
* Changes on speed names because of short place in dialogue windows;
* Newly appeared fuzzy removals on Editor section;
* Some new translations

2023-12-29 00:10 UTC, ihhub requested changes
Hi @big4billy , I have one common question in this pull request. Could you please check it?

2023-12-29 00:10 UTC, ihhub commented on files/lang/hu.po
> +msgstr "A %{name} napi %{count} ként biztosít neked."
Why are we modifying the same sentence again when we've just recently added it? This is true for many lines where we are removing **(z)**

2023-12-29 19:38 UTC, big4billy commented on files/lang/hu.po
> +msgstr "A %{name} napi %{count} ként biztosít neked."
That was a dilemma of us because of the Hungarian definite article grammar rules. There are two definite article in our language: "a" and "az". The meaning are the same "the" but "a" should stand before a consonant starting noun and "az" before a vowel starting word. In our case, it's important to know the starting letters of {name} parameters. There is azn universal solution using "a(z)" marking the possibility of both cases but it's not too aesthetic in look. I thought, if {name} parameter could be just one determined word, I try to fit the definite articles to the only possible parameter words. This round shows you these changes from "a(z)" to the fitted articles.

2023-12-29 19:42 UTC, big4billy commented on files/lang/hu.po
> +msgstr "A %{name} napi %{count} ként biztosít neked."
I'm trying to be not just accurate in meaning but grammarly correct in our language as well.

2024-01-03 07:35 UTC, big4billy commented on files/lang/hu.po
> +msgstr "A %{name} napi %{count} ként biztosít neked."
I hoped it's enough to explain our modifications. I didn't revert any sentence of changes with "a(z)", so yes, these is the current strings actually.

2024-01-04 10:02 UTC, big4billy commented on files/lang/hu.po
> +msgstr "A %{name} napi %{count} ként biztosít neked."
I think these changes are right and nothing to to with them. They might be approved.

2024-01-04 14:03 UTC, ihhub approved these changes

2024-01-04 14:03 UTC, merged

2024-01-04 14:04 UTC, ihhub commented
@big4billy , thank you so much for the changes!