Expand the map format
ihhub/fheroes2 pull request #8185
Opened 2023-12-26 09:47 UTC by ihhub

- add supported language (see comments in the code)
- add metadata structures for the objects. Castle metadata is not complete as we need to define what we want to store

2023-12-26 11:27 UTC, oleg-derevenetz commented on src/fheroes2/maps/map_format_info.h
> +        uint8_t supportedLanguage{ 0 };
I'm just wondering what we should do if we load a map that uses a language other than what is used in the game. The game does not use Unicode (and the fonts from the original game are not Unicode), so in any case, we most likely will not be able to show characters from another language from events, hero names, and so on.

2023-12-26 11:36 UTC, ihhub commented on src/fheroes2/maps/map_format_info.h
> +        uint8_t supportedLanguage{ 0 };
We can at least warn a user about this. Right now we have no such an ability. Are you suggesting that we should move to Unicode? Then we need to complete UTF-8 integration :(

2023-12-26 11:45 UTC, oleg-derevenetz commented on src/fheroes2/maps/map_format_info.h
> +        uint8_t supportedLanguage{ 0 };
> Are you suggesting that we should move to Unicode?

I don't know about this really, this can be done later (If we have to, because creating Unicode fonts for the whole game that will match the style of the original game is still a problem, and we need multiple fonts of this kind I suppose). Just wondering, because without Unicode fonts there is no way to show texts in multiple languages at the same time. But we can at least warn the user, yes.

2023-12-26 11:48 UTC, ihhub commented on src/fheroes2/maps/map_format_info.h
> +        uint8_t supportedLanguage{ 0 };
My idea was to at least to allow a creator of a map to choose a language they want (or multiple languages) to use while creating a map. Then the engine read this information, outputs properly (say hi to ??? ??? ??? in the list of maps) and displays these texts within the engine. I think this will require less development time than creation of fonts.

However, at first we can support only English and I can remove this member from the structure.

2023-12-26 12:11 UTC, oleg-derevenetz requested changes
Hi @ihhub I just left one suggestion, please take a look when you have time.

2023-12-26 12:11 UTC, oleg-derevenetz commented on src/fheroes2/maps/map_format_info.cpp
> +            assert( 0 );
Assertion may be fine for debug builds, but in release builds, if we can't read the field properly, then we should also set the data being loaded to some default sane values, I suppose (here and in other similar places).

2023-12-26 12:11 UTC, oleg-derevenetz commented on src/fheroes2/maps/map_format_info.h
> +        uint8_t supportedLanguage{ 0 };
No, I'm fine with it. IIRC the map format is versioned, so there is no problem with changing it later.

2023-12-26 12:12 UTC, ihhub commented on src/fheroes2/maps/map_format_info.cpp
> +            assert( 0 );
Good point.

2023-12-28 15:15 UTC, ihhub commented on src/fheroes2/maps/map_format_info.h
> +        uint8_t supportedLanguage{ 0 };
I reverted this change for now since we don't even use it.

2023-12-28 15:30 UTC, oleg-derevenetz approved these changes

2023-12-28 15:38 UTC, Districh-ru approved these changes

2023-12-29 00:02 UTC, merged