WIP: Implement Mines placing in Editor
ihhub/fheroes2 pull request #8233
Opened 2024-01-04 17:08 UTC by Districh-ru

![editor](https://github.com/ihhub/fheroes2/assets/113276641/41b8cd5c-a377-444a-9297-76c4aa58beb0)

2024-01-06 12:27 UTC, ihhub commented
Hi @Districh-ru , I am suggesting to expand the window to have space for resource type selection. As you can see gold selection is hard to spot:
![image](https://github.com/ihhub/fheroes2/assets/19829520/be4e822b-465e-42b9-acf7-f7e808da747d)

Also, while selection icon is good I think it's not the best. For now I am okay to keep it.

2024-01-06 12:53 UTC, Branikolog commented
Hi, @Districh-ru 
Fantastic work! I love new editor UI so much!

Here a few minor issues I've caught while testing this PR. They are not critical, initial logic for placing mines works fine.
1. I cannot select a mine and return back to adventure map when clicking on it for second time. I have to press OK button, while returning to adventure map works fine for artifacts, water objects etc. with just a double click.

https://github.com/ihhub/fheroes2/assets/55348946/057da1bb-3354-4cf6-a85f-2dc13582c7f7

2. Mines info windows are all the same for each resource type:
![image](https://github.com/ihhub/fheroes2/assets/55348946/8f2e226a-b3f3-4aea-b210-509f5a8865e1)

![image](https://github.com/ihhub/fheroes2/assets/55348946/b4f5b36b-0103-4e26-aebd-4a1c04d929c1)


One more unrelated issue I've found:
![image](https://github.com/ihhub/fheroes2/assets/55348946/abdb031c-2c68-4f6e-a2d4-4e31af8af2f8)

![image](https://github.com/ihhub/fheroes2/assets/55348946/6eebd7a8-910b-4803-a431-c07bf162c139)

2024-01-06 15:53 UTC, Districh-ru commented
> Would it be possible to implement so that the mine automaticly adapts to the underlying terrain, such as the castles foundations does? In 99,9% of the cases you want a snow gold mine on snow terrain and a swamp mine on swamp terrain, etc etc. That would remove an unnecessary step of choice for the mapmaker.

Hi, @Mr-Bajs, sure we may do this in future. But first we should decide how to choose the appearance (develop clear logic):
- the first mine appearance in the list is "generic" and in original editor appears for every terrain: how will we choose it?
- there are no sawmills and abandoned mines for some terrains.
So lets first implement the base editor features and then think how to implement new functions.
One of the new features will be the ability to choose the mine ownership (like in Heroes 3 editor), but it will also be implemented later.

2024-01-06 15:55 UTC, Districh-ru commented
Hi @ihhub  and @Branikolog, your comments are addressed.
The selection marker can be changed later.
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/0e8ec83a-2d04-408d-b7b5-6af5e8a88696)

Very tall object images are now resized in the list:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/edd143c9-fe4a-4b69-a6b3-07e82abee33b)

2024-01-06 17:49 UTC, Districh-ru commented
> Wouldn't it be best that the apperence checkmark also where the circledot one? Isn't the ✓ most used when you can check several options, but hence you can only choose apperence option the circle dot is better. Also it would look nice if both resource type and mine apperance used the same standard.

@Mr-Bajs, initially I only changed the marks in one place to check how well they fit.
Thanks for your opinion! Indeed, circle-dot marks are also better suited for mine appearance selection.
Done.

2024-01-07 04:53 UTC, ihhub requested changes
Hi @Districh-ru , I left several comments here. Could you please take a look at them?

2024-01-07 04:53 UTC, ihhub commented on src/fheroes2/editor/editor_interface_panel.cpp
> +        const int32_t maxResourceCount = 8;
I suggest to make it as a variable in unnamed namespace and use it here and in `getMineObjectProperties()` method to avoid hardcoded values.

2024-01-07 04:53 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +                        fheroes2::showStandardTextMessage( _( "Abandoned Mine" ), _( "Click to select Abandoned Mine placing." ), Dialog::ZERO );
I recommend to use `MP2::StringObject()` instead of `_( "Abandoned Mine" )` to keep strings in one place.

2024-01-07 04:53 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +                    if ( i == 7 ) {
Let's avoid using hardcoded values and use this: `objectInfo[listbox.getCurrentId()].objectType == MP2::OBJ_ABANDONED_MINE`.

2024-01-07 04:53 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +                                                           _( "Click to select this resource mine placing." ), Dialog::ZERO );
This is not entirely true as Sawmill and Alchemist Lab are not mines. @zenseii , can you help to rephrase this sentence?

2024-01-07 04:53 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +            if ( _resourceId > 1 && _resourceId < 7 ) {
Should we just use `Maps::ObjectInfo` information to decide a popup dialog? It should be done based on object type rather than hardcoded resource values. I believe it will improve code readability and we won't need the comment below.

2024-01-07 04:53 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +            if ( _color < 0 || _resourceId < 0 ) {
Is `_resourceId < 0` even possible? Also with my proposal to combine mine resource and mine object infos we will not need this member of the class.

2024-01-07 05:54 UTC, Districh-ru commented on src/fheroes2/maps/map_object_info.cpp
> +        for ( uint8_t resource = 0; resource < 5; ++resource ) {
Hi @ihhub, I'll try to it a little later, but probably I'll force some issues (unique offsets check for all parts and mine type filtering for the list).

2024-01-07 05:54 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +        const int32_t maxResourceCount = 8;
Sure!

2024-01-07 05:55 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +                                                           _( "Click to select this resource mine placing." ), Dialog::ZERO );
I've changer this whole part to display "Click to select %{object} placing."

2024-01-07 05:57 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +            if ( _resourceId > 1 && _resourceId < 7 ) {
Yes, you are right - it is more readable and simpler condition.

2024-01-07 09:49 UTC, Districh-ru commented on src/fheroes2/maps/map_object_info.cpp
> +        for ( uint8_t resource = 0; resource < 5; ++resource ) {
Done!
Yes, it is a better solution: we get rid of some functions and also some hardcoded values.

2024-01-07 11:28 UTC, ihhub requested changes
Hi @Districh-ru , I left one more comment here. Could you please check it?

2024-01-07 11:28 UTC, ihhub commented on src/fheroes2/maps/map_object_info.cpp
> +                    object.metadata[0] = Resource::ORE;
Doesn't Ore Mine suppose to produce 2 Ore a day? I suggest to put `object.metadata[1] = 1;` within any other case as well.

2024-01-07 11:54 UTC, Districh-ru commented on src/fheroes2/maps/map_object_info.cpp
> +                    object.metadata[0] = Resource::ORE;
Ow, my bad.
Thanks for noticing this!

2024-01-07 11:57 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +                    std::string description( _( "Click to select %{object} placing." ) );
@zenseii, many thanks for the rephrase and for spell checking in the PR!

2024-01-07 14:17 UTC, ihhub commented
Hi @Branikolog , please prioritize this pull request over other tasks.

2024-01-07 14:37 UTC, ihhub commented
Hi @Districh-ru , I noticed that in the OG some mines do not have the same passability as other mines:
![image](https://github.com/ihhub/fheroes2/assets/19829520/5c3b51ca-cae3-4319-a8ef-8e484274a1af)
![image](https://github.com/ihhub/fheroes2/assets/19829520/af254e56-6e5e-40f0-8b15-04caa5e7fb16)

I am not sure which version we need to stick to...

2024-01-07 14:47 UTC, Districh-ru commented
> Hi @Districh-ru , I noticed that in the OG some mines do not have the same passability as other mines:
> I am not sure which version we need to stick to...

I I choose the version with no passability above the mine entrance because there is the tunnel and it is impassable.
But we can change it: In original editor only Grass and Swamp mines does not have passability above the mine entrance.
Also I believe that all mine should have the same passability because they are the same objects.
@ihhub, @Branikolog, @zenseii, what do you think?

2024-01-07 15:16 UTC, ihhub commented
Consistency is important so I will vote for having an impassable tile on the top row to be present for all mines.

2024-01-07 21:35 UTC, Branikolog commented
Hi all!

I vote for the unpassable mine tile above the main entrance for all mines. 

@Districh-ru 

Application crashes when we select any mine and then click on the mines icon in the adventure objects mode in the right UI section.
Could you, please, look what went wrong there?

2024-01-08 05:35 UTC, Districh-ru commented
Hi, @Branikolog, 
the crash is fixed, thanks for noting it. I suggest to leave now passabilities as is and return to them a little later after more objects with questionable passability will be available. Mountains have more passability questions. After we decide how they are passable we will use the same approach here because mines are made in the mountains. :)

Hi, @zenseii,
Initially I did not use direct images from OBJNRSRC because it was not very easy to generate them. But I forgot that we can use map object image generation for already existent ADVENTURE_TREASURES group. :)
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/cf1755b4-dd85-4da8-b44a-48997e7bab99)

2024-01-08 12:13 UTC, Branikolog commented
Hi, @Districh-ru 
Thanks for the fix!
Unfortunately, I've found one more issue. Could you, please, look?

https://github.com/ihhub/fheroes2/assets/55348946/88f4dc11-1e71-4540-b84b-23851abe8d21

This relates to all mines.

2024-01-08 16:04 UTC, Districh-ru commented
Hi, @ihhub, could you please help me with this issue when you have some spare time?

> Hi, @Districh-ru Thanks for the fix! Unfortunately, I've found one more issue. Could you, please, look?
> This relates to all mines.

2024-01-09 10:40 UTC, ihhub commented
Hi @Branikolog , please test these changes. Your comment has been addressed.

2024-01-09 13:46 UTC, Branikolog commented
Hi, @ihhub !
An assertion occurs now, when I try to place a castle.

2024-01-09 13:49 UTC, ihhub commented
> Hi, @ihhub ! An assertion occurs now, when I try to place a castle.

Hi @Branikolog , it's fixed.

2024-01-09 14:03 UTC, Branikolog commented
Now everything works fine, except one little thing (not sure it's related to the current PR).
While selecting swordsmen - cursor remains as an arrow, while selecting other creatures cursor is turning into the creature sprite:

https://github.com/ihhub/fheroes2/assets/55348946/6cf2099e-5c71-4684-9a9f-766af6772d1f

I actually haven't tested all creatures. IF you wish, I can check every single creature later.

2024-01-09 14:18 UTC, ihhub commented
Hi @Branikolog , the issue has been fixed.

2024-01-09 15:14 UTC, ihhub commented
This pull request requires more work as saving of Roads and Streams is broken at the moment.

2024-01-09 15:38 UTC, ihhub commented
@Branikolog , this PR is ready to be reviewed again.

2024-01-09 22:30 UTC, Branikolog commented
Hi, @ihhub 
Undo function returns back all erased troops at the first click:

https://github.com/ihhub/fheroes2/assets/55348946/1069f008-935e-4124-9b13-abe8daeae170

2024-01-10 03:04 UTC, Districh-ru commented
> Hi, @ihhub Undo function returns back all erased troops on the first click:

Hi, @Branikolog, the Eraser tool needs and will be redone after all objects placing is implemented. So lets leave it for now. :)

2024-01-10 08:15 UTC, Branikolog approved these changes
No more issues found then. 👍

2024-01-10 08:46 UTC, merged

2024-01-10 08:46 UTC, ihhub commented
@Districh-ru , thank you so much for this improvement!