Improve AI heroes behavior on the Adventure Map
ihhub/fheroes2 pull request #8235
Opened 2024-01-05 15:12 UTC by ihhub

2024-01-05 18:16 UTC, oleg-derevenetz commented
Hi @ihhub

> remove hardcoded bonus values for Daemon Cave

Daemon Cave works as follows: you get a choice between fighting the demon's servants and the demon himself. In the first case, you get a fixed reward, in the second you will get a random outcome (including the outcome when hero will be eaten by a demon) with a random reward (by "random" I mean randomly set at the start of the game on the map). This random reward can be retrieved using the `getFundsFromTile()`, but not always - sometimes it's an artifact and in this case there is no sense to call `getFundsFromTile()`, and sometimes it's just experience and so on. Anyway, AI always choose to fight with demon servants and to get a fixed reward (which is hardcoded), because It doesn't want its hero to be eaten by a demon randomly.

2024-01-07 05:19 UTC, ihhub commented
Hi @oleg-derevenetz , I reverted this change.

2024-01-07 13:47 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
>                  // Nothing to uncover.
Actually, if we think about it, action objects are usually not used by a hero during the regular fog discovery, therefore, if the hero does not see more on this tower than without it, then it is still worth using this tower for the fog discovery.

2024-01-07 14:00 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
>                  // Nothing to uncover.
I revert the changes.

2024-01-07 14:05 UTC, ihhub commented on src/fheroes2/world/world_pathfinding.cpp
> +        int32_t maxTilesToReveal = 0;
How it was previously: iteratively go through every tile, check all neighbours and if any neighbour has fog to uncover, stop there and return this neighbour tile index.

Now: iteratively go through every tile, check all neighbours and if any neighbour has fog to uncover, remember this neighbour, continue through all other neighbours and find the one with highest number of tiles to uncover. Return the best.

2024-01-07 16:46 UTC, Districh-ru requested changes
Hi, @ihhub, I let AI to play an XL map and fond the AI movement actions good.
I left one minor speed-up suggestion. Could you please take a look.

2024-01-07 16:46 UTC, Districh-ru commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                    }
For the case when `world.CountDay() > period` the `/= 2` is redundant because the variable will be set to 0.
So we can slightly increase the performance:

```suggestion
                    if ( world.CountDay() > period ) {
                        fogDiscoveryValue = 0;
                    }
                    else {
                        // Increase the value of this action.
                        fogDiscoveryValue /= 2;
                        
                        fogDiscoveryValue = fogDiscoveryValue * ( period - world.CountDay() ) / period;
                    }
```

2024-01-07 16:51 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                    }
@Districh-ru  If so, there is no need to divide it by 2 first and then perform separate calculations, we can just write like this:

```cpp
else {
    fogDiscoveryValue = fogDiscoveryValue / 2 * ( period - world.CountDay() ) / period;
}
```

2024-01-07 16:53 UTC, Districh-ru commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                    }
Sure, I just left the division with the comment why the division is done from the previous code.

2024-01-08 00:29 UTC, oleg-derevenetz commented on src/fheroes2/world/world_pathfinding.cpp
> +        int32_t maxTilesToReveal = 0;
I pushed commit with my vision of `AIWorldPathfinder::getFogDiscoveryTile()`. It is somewhat simpler, it calls `Maps::getFogTileCountToBeRevealed()` more times, but this is compensated by not calling many other things. Here is a profiler's call tree for the `master` branch:

![master](https://github.com/ihhub/fheroes2/assets/32623900/c7d6a7d3-b405-465b-a40a-b9c2caba23fa)

and here is a call tree for this PR with my commit:

![pr](https://github.com/ihhub/fheroes2/assets/32623900/14d1fe59-157e-4c19-bb36-4a8f48688616)

Both are made from the same savefile made on XL map "Marooned" at 6-3-1 (that is, a sufficiently explored map by AI at that moment). I suggest testing this variant, but I don't insist :) This commit can be reverted.

2024-01-09 09:00 UTC, idshibanov approved these changes
Great change

2024-01-10 14:06 UTC, Branikolog approved these changes
Haven't found any issues.

2024-01-10 14:55 UTC, ihhub commented on src/fheroes2/world/world_pathfinding.cpp
> +    struct TileCharacteristics
Hi @oleg-derevenetz , what was the reason to remove whirlpool and teleport tiles?

2024-01-10 15:08 UTC, ihhub commented on src/fheroes2/world/world_pathfinding.cpp
> +    struct TileCharacteristics
Got it.

2024-01-10 15:37 UTC, merged