Applied the effect from #7491 to the skill popup dialog
ihhub/fheroes2 pull request #8240
Opened 2024-01-07 08:43 UTC by JasonQorbin

- Made the skill name and skill level text centre properly.
- Also truncate the text with '...' if the text is too long for the icon (happens in some languages). The full, unmodified skill name and skill level text can still be seen at the top of the popup dialog.
- Lastly limited the text to only draw within the icon boundary so that in edge cases the text shadow doesn't fall on the icon's gold border.

Related to issue #7491

![Screenshot 2024-01-07 095034](https://github.com/ihhub/fheroes2/assets/117314288/4a03cb40-0748-43e3-9013-8f90f22e1475)

2024-01-07 13:52 UTC, Districh-ru requested changes
Hi, @JasonQorbin. Many thanks for your contribution to the project!
 I left three suggestions. Could you please check them when you have time?

2024-01-07 13:52 UTC, Districh-ru commented on src/fheroes2/gui/ui_dialog.cpp
> +        const fheroes2::Rect textBoundary( iconOffsetX, iconOffsetY, icn.width(), icn.height() );
Since we are rendering the skill `icn` image and want to render text only in its boundaries we can first set the `Rect` for `icn` (to cache all needed values) and then use it everywhere. Also the skill image has no transparency or shadows so we can use `Copy()` here instead of `Blit()`:
```cpp
const fheroes2::Rect icnRect( offset.x + ( background.width() - icn.width() ) / 2, offset.y + ( background.height() - icn.height() ) / 2, icn.width(), icn.height() );
Copy( icn, 0, 0, output, icnRect );
```

2024-01-07 13:52 UTC, Districh-ru commented on src/fheroes2/gui/ui_dialog.cpp
> +        skillName.drawInRoi( offset.x + ( background.width() - skillName.width() ) / 2 - 1, offset.y + 8, output, textBoundary );
We can skip the text `width()` check because it is done in `fitToOneRow()` method.
Also as we want to render text only in the given `textBoundary` (or we can name it `icnRect` because it is a rectangle where `icn` is rendered) we the more proper way is to do text offsets relative to this Rect:
```cpp
skillName.fitToOneRow( icnRect.width );
skillName.drawInRoi( icnRect.x + ( icnRect.width - skillName.width() ) / 2, icnRect.y + 5, output, icnRect );
```

2024-01-07 13:52 UTC, Districh-ru commented on src/fheroes2/gui/ui_dialog.cpp
> +        skillDescription.drawInRoi( offset.x + ( background.width() - skillDescription.width() ) / 2 - 1, offset.y + 56, output, textBoundary );
The same comment as previous:
```cpp
skillDescription.fitToOneRow( icnRect.width );
skillDescription.drawInRoi( icnRect.x + ( icnRect.width - skillDescription.width() ) / 2, icnRect.y + 53, output, icnRect );
```

2024-01-09 03:11 UTC, Districh-ru approved these changes
👍

2024-01-10 15:12 UTC, ihhub approved these changes

2024-01-10 15:13 UTC, merged

2024-01-10 15:13 UTC, ihhub commented
@JasonQorbin , thank you so much for this fix!