Add surrender cost to battle result dialog
ihhub/fheroes2 pull request #8244
Opened 2024-01-08 11:19 UTC by zenseii

The window had to be widened to allow having two strings. This is better than increasing the height of the window since there's barely anything left to use in standard 640x480.

This phrasing was come up with thanks to the help of native speaker ObsessiveRepulsive:
<img width="381" alt="image" src="https://github.com/ihhub/fheroes2/assets/12501091/115ac54a-f9fa-40e5-adff-d00963b7a8f8">

Close #8221

2024-01-13 13:12 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +            surrenderText.append( _( "They hand over %{gold} gold in shame." ) );
Looks valid for me.

2024-01-13 13:29 UTC, ihhub requested changes
Hi @zenseii , I quickly checked this pull request and I left one suggestion here. Could you please take a look at it?

2024-01-13 13:29 UTC, ihhub commented on src/fheroes2/battle/battle_dialogs.cpp
> +    Copy( animationBorder, 0, 0, display, animationRoi.x - 4, animationRoi.y - 4, animationRoi.width, animationRoi.height );
We don't need to use `Crop` call to render this image later:
```cpp
const fheroes2::Sprite & originalBorderImage = fheroes2::AGG::GetICN( isEvilInterface ? ICN::WINLOSEE : ICN::WINLOSE, 0 );
const fheroes2::Rect animationBorderRoi{ 43, 32, 231, 133 };

const fheroes2::Rect & roi = background.activeArea(); // <--- notice that I changed to const reference
const fheroes2::Rect animationRoi{ roi.x + ( ( roi.width - animationBorderRoi.width ) / 2 ) + 4, roi.y + 21, animationBorderRoi.width, animationBorderRoi.height };
Copy( originalBorderImage, animationBorderRoi.x, animationBorderRoi.y, display, animationRoi.x - 4, animationRoi.y - 4, animationRoi.width, animationRoi.height );
```

I haven't tested it but I hope you understand the idea :)

2024-01-14 13:15 UTC, Districh-ru requested changes
Hi, @zenseii, all works great. I left several comments. Could you please check them when you have time?

2024-01-14 13:15 UTC, Districh-ru commented on src/fheroes2/battle/battle_dialogs.cpp
> +            fheroes2::Blit( sequenceCurrent, display, animationRoi.x + sequenceCurrent.x(), animationRoi.y + sequenceCurrent.y() );
We are rendering `base` Sprite so possibly we should use its offsets. And we can also render this `base` only when animation sequence is changed:
```cpp
        // animation
        int sequenceId = sequence.id();
        if ( Game::validateAnimationDelay( Game::BATTLE_DIALOG_DELAY ) && !sequence.nextFrame() ) {
            if ( sequenceId != sequence.id() ) {
                sequenceId = sequence.id();
                const fheroes2::Sprite & base = fheroes2::AGG::GetICN( sequenceId, 0 );

                Copy( base, 0, 0, display, animationRoi.x + base.x(), animationRoi.y + base.y(), base.width(), base.height() );
            }

            const fheroes2::Sprite & sequenceCurrent = fheroes2::AGG::GetICN( sequence.id(), sequence.frameId() );

            fheroes2::Blit( sequenceCurrent, display, animationRoi.x + sequenceCurrent.x(), animationRoi.y + sequenceCurrent.y() );
            display.render( animationRoi );
        }
```

2024-01-14 13:15 UTC, Districh-ru commented on src/fheroes2/battle/battle_dialogs.cpp
>                      }
The same comment as previous.

2024-01-14 13:33 UTC, Districh-ru commented on src/fheroes2/battle/battle_dialogs.cpp
> +                                            : ( allowToRestart ? ICN::BUTTON_SMALL_OKAY_GOOD : ICN::BUTTON_SMALLER_OKAY_GOOD );
I took me some time to understand this big ICN selection. Evil/Good is OK, but it was hard to find difference in SMALL/SMALLER. :)
Since we a changing this dialog and possible in future will make it wider to show more defeated monsters (if there are many) we can use a wider button IMHO.
@Branikolog, what is your opinion about OKAY button? Should we keep using "smaller" button to correspond the original dialog or use the wider "small" OKAY button?

2024-01-14 13:38 UTC, Districh-ru commented on src/fheroes2/battle/battle_dialogs.cpp
> +            fheroes2::Blit( sequenceCurrent, display, animationRoi.x + sequenceCurrent.x(), animationRoi.y + sequenceCurrent.y() );
@zenseii, a little fix: we should put `int sequenceId = sequence.id();` beforу the `while()` loop.
Also this ёшаё will trigger only on lose.
For Win there is only one sequence and its `base` is rendered before the loop

2024-01-14 13:44 UTC, Districh-ru commented on src/fheroes2/battle/battle_dialogs.cpp
> +            fheroes2::Blit( sequenceCurrent, display, animationRoi.x + sequenceCurrent.x(), animationRoi.y + sequenceCurrent.y() );
For the "loose" and "retreat" animation we have three sequences:
``` cpp
        sequence.push( ICN::CMBTFLE1, false );
        sequence.push( ICN::CMBTFLE2, false );
        sequence.push( ICN::CMBTFLE3, false );
```
```cpp
        sequence.push( ICN::CMBTLOS1, false );
        sequence.push( ICN::CMBTLOS2, false );
        sequence.push( ICN::CMBTLOS3, true );
```

2024-01-16 21:34 UTC, Branikolog commented on src/fheroes2/battle/battle_dialogs.cpp
> +                                            : ( allowToRestart ? ICN::BUTTON_SMALL_OKAY_GOOD : ICN::BUTTON_SMALLER_OKAY_GOOD );
Hello, @zenseii !
Sorry for the late response. 
I prefer wider "OKAY" button. I believe some languages require larger buttons.
And for consistent design with instant battle dialog:
![image](https://github.com/ihhub/fheroes2/assets/55348946/9340c36d-cd0e-46fb-b091-61227a93fb0a)

2024-01-16 21:52 UTC, Branikolog commented on src/fheroes2/battle/battle_dialogs.cpp
> +                                            : ( allowToRestart ? ICN::BUTTON_SMALL_OKAY_GOOD : ICN::BUTTON_SMALLER_OKAY_GOOD );
@zenseii 
There could be more than 4 digits there. Imagine during Human vs Human match when one decides to surrender for one million bucks. :)

2024-01-17 03:09 UTC, Districh-ru commented on src/fheroes2/battle/battle_dialogs.cpp
> +                                            : ( allowToRestart ? ICN::BUTTON_SMALL_OKAY_GOOD : ICN::BUTTON_SMALLER_OKAY_GOOD );
> About this, @Districh-ru, do you know if there's a way to make text try to get as many of the words on the first line before cutting to the next? Right now it seems like the draw function tries to spread the words as evenly between the lines as possible.
> I tried to force a single line for the surrender text by not giving the maxWidth parameter but the height evaluation didn't work properly. Maybe I should have to look at that again.

@zenseii, sadly we don't have such option. In future we may implement it along with text alignment setting (currently it is always center aligned).
You can open an "improvement" issue not to forget to do this.

2024-01-17 16:07 UTC, Districh-ru approved these changes
Well done!

2024-01-20 03:01 UTC, ihhub approved these changes

2024-01-20 03:01 UTC, merged

2024-01-20 03:01 UTC, ihhub commented
@zenseii , many thanks for the changes!