Adding Vertical Gradient for fonts
ihhub/fheroes2 pull request #8262
Opened 2024-01-12 00:17 UTC by MaMadDl

based on Discussion #8078
Adding colors bounds for all the colors in pal.h
Adding 3 point Linear vertical gradient creator
Adding new font color for NORMAL and LARGE fonts

2024-01-13 04:53 UTC, ihhub commented
Hi @MaMadDl , before proceeding with this pull request review please update the original description to include all fonts that you are adding here so every reviewer will have visual interpretation of them.

2024-01-13 15:39 UTC, MaMadDl reviewed
Hello @zenseii 
Requested Reviews have been changed
also for Large Font I've changed the outline pixel width to 2 

Please Take a look

2024-01-13 16:18 UTC, MaMadDl commented
@Mr-Bajs  you're right.
I'm overwriting the letter color by checking for value in its transform layer. 
where at both ends of S it starts get thinner, I suspect I'm overwriting that the transparent part.
will look into it ASAP.

2024-01-13 16:57 UTC, ihhub commented on src/engine/image.h
> +    void ApplyVerticalGradient( fheroes2::Image & image, uint8_t darkColor, uint8_t brightColor, uint8_t offset, uint8_t borderWidth );
clang-tidy is correct here.

2024-01-13 16:57 UTC, ihhub commented on src/engine/image.cpp
> +            fheroes2::Image cnt = CreateContour( image, 0 );
clang-tidy is correct here.

2024-01-15 02:10 UTC, MaMadDl commented
Hello @zenseii 
Thanks for the tip on saving image

here's modified version of Fonts 
Normal
![NormalR](https://github.com/ihhub/fheroes2/assets/18714088/4425f910-ec22-4f30-b239-f069a4c07f39)
Large
![LargeR](https://github.com/ihhub/fheroes2/assets/18714088/4fde3947-92a6-4ea8-92fd-89acf4d1e3e3)

I have changed the function to take in a Color as well 
and wrap all of them with one black contour

fixed Clang-Tidy issues mentioned by @ihhub 

Let me know what you think

2024-01-15 21:09 UTC, MaMadDl commented on src/engine/image.cpp
> +    }
@zenseii 
black contours should come last 
and for brown I think it's best to keep the method customizable so it could be reused.

2024-01-15 22:33 UTC, MaMadDl reviewed
also I have moved the 2 static createContour into `agg_image.cpp` instead of `update_shadow` method

as for the matter of cutter 1 pixel from the middle, after removing 1 pixel from middle a lot of characters got deformed For both Large and Normal fonts so I don't think we should go that route
here's some of the deformations:
Normal `=` 
![=normal](https://github.com/ihhub/fheroes2/assets/18714088/8cdb8095-affb-49c1-91d9-442808d740a4)
`Normal` with middle Cut
![=cut](https://github.com/ihhub/fheroes2/assets/18714088/bfbe77df-ff36-4305-bf63-863674e3571e)
`Large` with middle Cut
![=LargeCut](https://github.com/ihhub/fheroes2/assets/18714088/d115de27-2f3b-46ae-9cce-43d3f553d9d6)



I noticed there's a method called `fheroes2::Stretch`. does that work as linear scaling on `x` and `y` and can we use it to handle the cutting '1 pixel line` is what I asked before.

2024-01-15 22:38 UTC, MaMadDl commented on src/engine/image.cpp
> +    }
@zenseii 
You were right  I mistook it for 2nd layer ( what is drawn before Black)

but overall I think we should go with dark brown for outside layer, in my opinion slightly faded outline looks better

2024-01-17 21:58 UTC, MaMadDl commented
Hello @zenseii

I have added a version of silver gradient however it's slightly thicker than those in campaign 
here's an example for letter H:
Original:
![Screenshot 2024-01-16 043858](https://github.com/ihhub/fheroes2/assets/18714088/5bde9b1a-6136-4a88-9902-e4897d8bcd08)
Recreated:
![Screenshot 2024-01-16 044005](https://github.com/ihhub/fheroes2/assets/18714088/0fbdf2f2-5270-4c4b-8a3b-fb3bcd2ee881)

there's also a problem when I'm trying to separate original white font shade(pixels that's slightly darker) where we are checking by value (Lines `3133` and  `3153` in `image.cpp` ) and i think it's conflicting with Silver color creation and wasn't able to find good solution for it yet.

let me know what you think

2024-01-19 13:38 UTC, ihhub commented
Hi @MaMadDl , please use `Resize()` method for resizing things. `Stretch()` is for different purposes.

2024-04-14 19:10 UTC, MaMadDl commented
Hi @zenseii,

I've managed to fix the issues and made the method a lot simpler and shorter

the final output are:
Silver Gradient (Normal and Large):
![silverNormalH](https://github.com/ihhub/fheroes2/assets/18714088/fcebe610-7f74-4f29-aa43-d88dcf7fc38f)
![silverLargeH](https://github.com/ihhub/fheroes2/assets/18714088/1fa78813-9dfa-4a0c-ae39-12c7467ee059)

Golden Gradient(Normal and Large):
![GoldNormalH](https://github.com/ihhub/fheroes2/assets/18714088/2c70f50c-8ec8-4cea-b930-35126d07d0b9)
![GoldLargeH](https://github.com/ihhub/fheroes2/assets/18714088/c47dc5d0-17ef-49de-a286-3cbb16329ada)

2024-04-19 19:22 UTC, Districh-ru requested changes
Hi, @MaMadDl, thanks for the gradient fonts implementation, I like how it looks.
I left several comments, could you please take a look when you have time.

2024-04-19 19:22 UTC, Districh-ru commented on src/engine/image.cpp
> +            uint8_t val = static_cast<uint8_t>( abs( insideColor + (int)( heightScale * dColor ) ) );
We can slightly simplify this code:
```suggestion
        const uint8_t dColor = outsideColor - insideColor;

        for ( uint8_t row = 0; row < height; row++ ) {
            const uint8_t heightScale = ( dColor * static_cast<uint8_t>( std::abs( centerY - row ) ) ) / centerY;

            const uint8_t val = static_cast<uint8_t>( std::abs( insideColor + heightScale ) );
```

2024-04-19 19:22 UTC, Districh-ru commented on src/engine/image.cpp
> +            uint8_t * inRowStart = inData + static_cast<ptrdiff_t>( row * width );
This pointer can be a pointer to `const`.
It is also better (to avoid overflow) to cast not the result of the multiplication, but the multiplier:
```suggestion
            const uint8_t * inRowStart = inData + static_cast<ptrdiff_t>( row ) * width;
```
The `cast` suggestion is also for the rest lies in this loop. :)

2024-04-19 19:22 UTC, Districh-ru commented on src/engine/image.cpp
> +            uint8_t * inRowEnd = inData + static_cast<ptrdiff_t>( ( row + 1 ) * width );
This pointer can be a pointer to const.

2024-04-19 19:22 UTC, Districh-ru commented on src/engine/image.cpp
> +            uint8_t * inTrans = inTransform + static_cast<ptrdiff_t>( row * width );
This pointer can be a pointer to const.

2024-04-20 11:37 UTC, MaMadDl commented on src/engine/image.cpp
> +        fheroes2::Copy( outImage, image );
Actually we do. In place processing is what I went for in the first implementation and the results had a lot of issues specially on silver gradient.

2024-04-20 12:26 UTC, MaMadDl reviewed
Hi @Districh-ru 
I have made the changes requested , would please take a look?
also on one of the changes requested I had some issues which is commented on.

2024-04-20 13:47 UTC, Districh-ru commented on src/engine/image.cpp
> +        fheroes2::Copy( outImage, image );
@MaMadDl 
As for now the issued in the code are fixed and we can also avoid making a copy of image and do changes directly in the input image.
I removed the `outImage` from the code and got the same result without any issues:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/592e98d8-4257-4bda-a97b-183d44256337)


<details>

```cpp
        assert( !image.singleLayer() );

        const int32_t height = image.height();
        const int32_t width = image.width();

        uint8_t * inData = image.image();
        uint8_t * inTransform = image.transform();

        const uint8_t centerY = static_cast<uint8_t>( std::max( 1, ( height / 2 ) - height % 2 ) );
        const uint8_t dColor = outsideColor - insideColor;

        for ( uint8_t row = 0; row < height; row++ ) {
            const uint8_t heightScale = ( dColor * static_cast<uint8_t>( std::abs( centerY - row ) ) ) / centerY;

            const uint8_t val = static_cast<uint8_t>( std::abs( insideColor + heightScale ) );
            uint8_t * inRowStart = inData + static_cast<ptrdiff_t>( row ) * width;

            const uint8_t * inRowEnd = inData + static_cast<ptrdiff_t>( row + 1 ) * width;
            uint8_t * inTrans = inTransform + static_cast<ptrdiff_t>( row ) * width;

            for ( ; inRowStart != inRowEnd; ++inRowStart, ++inTrans ) {
                if ( *inTrans == 0 ) {
                    // 21 is the pixel limit of shadows in Base white Font
                    if ( *inRowStart < 21 ) {
                        *inRowStart = val;
                    }
                    else {
                        *inTrans = 1;
                    }
                }
            }
        }

        for ( uint8_t i = 0; i < borderWidth; i++ ) {
            fheroes2::Sprite cnt = CreateContour( image, borderColor );
            Blit( cnt, image );
        }
```
</details>

2024-04-20 13:54 UTC, Districh-ru reviewed
@MaMadDl, I left some more comments. Could you please check them?

2024-04-20 13:54 UTC, Districh-ru commented on src/engine/image.h
> +    void ApplyVerticalGradient( Image & image, const uint8_t outsideColor, const uint8_t insideColor, const uint8_t borderWidth, const uint8_t borderColor );
Since this function is applicable only to fonts should we place it in `ui_font.h|cpp` files or name it `applyFontVerticalGradientAndContour` (yes, we apply contour here too).
Also please name new functions according to the [code style suggestions](https://github.com/ihhub/fheroes2/wiki/Code-style). :)

2024-04-20 13:54 UTC, Districh-ru commented on src/engine/image.cpp
> +    void ApplyVerticalGradient( fheroes2::Image & image, const uint8_t outsideColor, const uint8_t insideColor, const uint8_t borderWidth, const uint8_t borderColor )
We are already in `fheroes2` namespace so there is no need to type it for `fheroes2::Image`:
```suggestion
    void ApplyVerticalGradient( Image & image, const uint8_t outsideColor, const uint8_t insideColor, const uint8_t borderWidth, const uint8_t borderColor )
```

2024-04-20 14:50 UTC, MaMadDl commented on src/engine/image.h
> +    void ApplyVerticalGradient( Image & image, const uint8_t outsideColor, const uint8_t insideColor, const uint8_t borderWidth, const uint8_t borderColor );
since most of font manipulator methods are still in `image.h|cpp`  and `ui_font.h` is mostly for multi-language stuff I think `image.h` is more suitable. as for name I tried to follow the conventions already existing in the header

2024-04-20 15:45 UTC, MaMadDl reviewed
hi @Districh-ru 
I've made the changes requested, could you please check them ?

2024-04-20 16:10 UTC, Districh-ru approved these changes
Well done, @MaMadDl !

2024-08-26 21:53 UTC, MaMadDl commented
Hi @zenseii Conflicts resolved and merged with master

2024-09-21 03:51 UTC, ihhub approved these changes

2024-09-21 04:04 UTC, merged

2024-09-21 04:04 UTC, ihhub commented
@MaMadDl , thank you very much for this feature!