Single layer image processing improvements
ihhub/fheroes2 pull request #8276
Opened 2024-01-14 08:17 UTC by Districh-ru

This PR is a part of #8241 but without changes to `transform()` layer memory allocation and `reset()` of transform layer.

2024-01-19 13:53 UTC, ihhub requested changes
Hi @Districh-ru , I put 2 comments here. Would you mind to take a look at them when you have time?

2024-01-19 13:53 UTC, ihhub commented on src/engine/image.cpp
> -        const size_t size = static_cast<size_t>( width_ ) * height_;
Should we revert these change for memory allocation as per description?

2024-01-19 13:53 UTC, ihhub commented on src/engine/screen.cpp
> +        _screenSize = { info.screenWidth, info.screenHeight };
I suggest to revert these changes since we still preserve memory for the transform layer (for now).

2024-01-19 20:20 UTC, Districh-ru commented on src/engine/image.cpp
> -        const size_t size = static_cast<size_t>( width_ ) * height_;
Hi, @ihhub, the amount of allocated memory will be the same as in master build. I've just moved `* 2` from 524 line to 522 line because the `size` of allocated memory (in bytes) is `_width * _height * 2` and also to do all calculations in one line and allocation in another line (without any mathematical operations with the size of memory to allocate).

2024-01-19 20:46 UTC, Districh-ru commented on src/engine/screen.cpp
> +        _screenSize = { info.screenWidth, info.screenHeight };
I master build we just put `1` to the transform layer. I changed it to `reset()` method that will do the same and in addition will put `0` to the just resized screen image data layer.
I thought it would be a little safer this way:
- we will fix possible UI artifacts resulting from an undefined image data layer. This has never happened, but it is possible. And we use `setResolution()` rarely, so filling the image data with `0` won't have much impact on the engine's performance;
- if we remove the transform layer for the screen image, then no more changes will be required here - all the necessary changes will be made in the `reset()` method.

But I could be wrong. If you think so I'll revert the changes. :)

2024-01-20 02:24 UTC, ihhub commented on src/engine/image.cpp
> -        const size_t size = static_cast<size_t>( width_ ) * height_;
Oh, yes. You're right. My bad.

2024-01-20 02:26 UTC, ihhub commented on src/engine/screen.cpp
> +        _screenSize = { info.screenWidth, info.screenHeight };
It seems reasonable. Thanks for the explanation!

2024-01-20 02:26 UTC, ihhub approved these changes

2024-01-20 02:26 UTC, merged

2024-01-20 02:26 UTC, ihhub commented
@Districh-ru , thank you so much for these improvements!