Update pl.po
ihhub/fheroes2 pull request #8288
Opened 2024-01-16 09:49 UTC by krokots

Fixed duplicate polish word for "lots" and "swarm".

2024-01-16 09:55 UTC, Arthusppp commented
I will. Any deadline?

2024-01-22 19:22 UTC, Arthusppp commented
Hello @krokots ! What is the idea behind your changes? 

I have compered it on this map:
[Map_0003.zip](https://github.com/ihhub/fheroes2/files/14014543/Map_0003.zip)

As far as I can see, all translations (except to one) in the fh2 are the same as in the original game (I have GoG version). 
The one exception is "swarm" - currently is "mnóstwo" and the correct translation is "mrowie".


OG/fh2
1-4 few -> mało/mało
5-9 several -> parę/parę
10-19 pack -> grupa/grupa
20-49 lots -> mnóstwo/mnóstwo
50-99 horde -> horda/horda
100-249 throng -> tłum/tłum
250-499 swarm -> mrowie/mnóstwo ?????? -> mrowie!
500-999 zounds -> setki/setki
1000-4000 legion -> legion/legion

2024-01-24 22:31 UTC, krokots commented
There was a bug where both "lots" and "swarm" was translated as "mnóstwo". I changed "lots" to "dużo" and kept "swarm" as "mnóstwo". I don't really care how they're translated, I just needed the duplicate to be fixed.

2024-01-25 21:25 UTC, Arthusppp commented
> There was a bug where both "lots" and "swarm" was translated as "mnóstwo". I changed "lots" to "dużo" and kept "swarm" as "mnóstwo". I don't really care how they're translated, I just needed the duplicate to be fixed.
> 
> Also personal preference : "mrowie" sounds archaic to me.

Given the above, I propose to change wrong transladion of "swarm" from "mnóstwo" to "mrowie". 

I somehow understand your second point: "mrowie" seems to be archaic word. However, the OG translates "swarm" in this way, and "mrowie" tells me more compared to "dużo". It's beacuse "dużo" is new word here, and "dużo" has not been used anywhere in this context.

2024-01-27 19:10 UTC, Arthusppp requested changes

2024-01-27 19:10 UTC, Arthusppp commented on files/lang/pl.po
> +"Kilka\n"
As per my comment, I propose to revert this change.

2024-01-27 19:10 UTC, Arthusppp commented on files/lang/pl.po
> +"Dużo\n"
As per my comment, I propose to revert this change.

2024-01-27 19:10 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Kilka"
As per my comment, I propose to revert this change.

2024-01-27 19:10 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Dużo"
As per my comment, I propose to revert this change.

2024-01-27 19:10 UTC, Arthusppp commented on files/lang/pl.po
> +msgstr "Mnóstwo"
As per my comment, I propose to revert this change.

2024-01-27 19:10 UTC, Arthusppp commented on files/lang/pl.po
Please update line 316:
from 
```
msgid ""
"A swarm of\n"
"%{monster}"
msgstr ""
"Mnóstwo\n"
"%{monster}"
```
to
```
msgid ""
"A swarm of\n"
"%{monster}"
msgstr ""
"Mrowie\n"
"%{monster}"
```

2024-01-29 11:28 UTC, closed without merging