Add infos on the cost of surrender
ihhub/fheroes2 pull request #8299
Opened 2024-01-18 09:22 UTC by zenseii

This discloses how much the diplomacy skill affects the cost of surrender, and adds that the cost of surrender is under normal circumstances half the total cost of troops remaining in the army, in gold only.

<img width="313" alt="image" src="https://github.com/ihhub/fheroes2/assets/12501091/bbb6814c-cce6-4206-98ac-1011241f3d93">

2024-01-18 10:08 UTC, oleg-derevenetz commented on src/fheroes2/heroes/skill.cpp
> +        uint32_t percent = 40;
Hi @zenseii Eh, I'm aware of the fact that these values are currently hardcoded in the `Battle::Force::GetSurrenderCost()`, but since they are now hardcoded also here, it would be better to add at least a free function to the `Skill` namespace to return this percent and use it in both places. What do you think?

2024-01-18 14:19 UTC, ihhub requested changes
Hi @zenseii , I left one suggestion here. Would you mind to take a look?

2024-01-18 14:19 UTC, ihhub commented on src/fheroes2/heroes/skill.cpp
> +    switch ( level ) {
Shouldn't we return 20, 40 and 60 values respectively? At line 526 Expert level will show 20% while Basic will show 40%.

Also to avoid hardcoded values in `battle_army.cpp` we have:
```cpp
const int diplomacyLevel = commander->GetLevelSkill( Skill::Secondary::DIPLOMACY );
if ( diplomacyLevel > Skill::Level::NONE ) {
    mod *= ( Skill::GetDiplomacySurrenderPercent( diplomacyLevel ) * 0.02 );
}
```

but we can do with the proposed changes:
```cpp
mod *= 1 - ( Skill::GetDiplomacySurrenderPercent( commander->GetLevelSkill( Skill::Secondary::DIPLOMACY ) / 100.0 );
```

2024-01-18 20:36 UTC, oleg-derevenetz commented on src/fheroes2/heroes/skill.h
> +    uint32_t GetDiplomacySurrenderPercent( const int level );
Hi @zenseii I'm not insisting, but maybe call this function something like `GetDiplomacySurrenderCostDiscount`/`GetDiplomacySurrenderCostDiscountPercent`?

2024-01-18 22:23 UTC, oleg-derevenetz approved these changes

2024-01-18 22:23 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_dialogs.cpp
> +                _( "Surrendering costs gold. However if you pay the ransom, the hero and all of his or her surviving creatures will be available to recruit again. The cost of surrender is half of the
I should note however that this comment is not 100% accurate. E.g. while non-true-resurrected troops "remain in the army", their cost is not accounted for surrender cost calculation purposes. The same applies to elementals summoned during the battle. But I understand that it is unrealistic to describe all this rather complex mechanics in a couple of sentences.

2024-01-19 06:36 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_dialogs.cpp
> +                _( "Surrendering costs gold. However if you pay the ransom, the hero and all of his or her surviving creatures will be available to recruit again. The cost of surrender is half of the
> "only... against an opposing hero" : in fheroes2 you can surrender if you attack a castle with a captain, probably not if they don't even have that. I haven't checked this up against the original game.

In OG you can surrender to a captain as well:

https://github.com/ihhub/fheroes2/assets/32623900/d7a6f631-79a7-4f48-adda-143e96fea545

> "based on the power of your army." could suggest that paying for summons, mirror images and non-true resurrected creatures is intentional

At the time, this was considered a bug of the original game: #5168.

2024-01-19 14:32 UTC, ihhub approved these changes

2024-01-19 14:32 UTC, merged

2024-01-19 14:32 UTC, ihhub commented
@zenseii , thank you so much for these changes!