Update editor's erasure tool
ihhub/fheroes2 pull request #8395
Opened 2024-02-11 18:58 UTC by Districh-ru

2024-02-13 15:13 UTC, ihhub requested changes
Hi @Districh-ru , I put several comments here. Would you mind to take a look at them?

2024-02-13 15:13 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +    std::set<uint32_t> getObjectUidsInArea( const int32_t startTileId, const int32_t endTileId )
Please add an empty line before to separate 2 functions.

2024-02-13 15:13 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +            return {};
Please add an assertion here as this is not an expected case.

2024-02-13 17:17 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +    bool removeObjects( Maps::Map_Format::MapFormat & mapFormat, fheroes2::Point tileAreaIndices, std::vector<Maps::ObjectGroup> objectGroups )
Hi, @ihhub, thanks for your review and valuable suggestions!
I missed the `const &` here. :(  Done!

2024-02-13 17:18 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +        for ( std::vector<Maps::Map_Format::TileInfo>::iterator mapTile = mapFormat.tiles.begin(); mapTile != mapFormat.tiles.end(); ++mapTile ) {
OK, lets not use iterators here. It will also simplify the streams/roads erase code.

2024-02-13 17:18 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface_panel.cpp
> +    std::vector<Maps::ObjectGroup> EditorPanel::getEraseObjectGroups() const
Sure!

2024-02-13 17:19 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +    std::set<uint32_t> getObjectUidsInArea( const int32_t startTileId, const int32_t endTileId )
👍

2024-02-13 17:19 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +            return {};
Done.

2024-02-15 00:18 UTC, ihhub reviewed
Hi @Districh-ru , I left one comment regarding the logic. Could you please take a look at it?

2024-02-15 00:18 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +                     || std::none_of( objectGroups.begin(), objectGroups.end(), [&object]( const Maps::ObjectGroup group ) { return group == object->group; } ) ) {
Can you please explain when we could have the same object UID but different object group? Is it only for towns? If yes, then what happen if we remove this condition, erase object UID at the end of this loop and treat towns as normal objects?

Moreover, `updateRoadOnTile` and `updateStreamOnTile` calls do not modify mapFormat but these calls keep existing objects on Adventure Map.

2024-02-15 04:55 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +                     || std::none_of( objectGroups.begin(), objectGroups.end(), [&object]( const Maps::ObjectGroup group ) { return group == object->group; } ) ) {
Hi @ihhub. We get object's UIDs from `world` and the main tile of some objects may be outside of the selected area to remove. So we go though all Map_Format tiles. (In future we should optimize it and limit the range of search).
These tow checks are made:
- first - to check if the object in the current `mapTile` is the objects that was selected by user;
- second - if object is in the group of objects that can be erased (user can unselect some groups).
There can be a case when there is more than one object on the `mapTile`. And different objects with one UID is only Town/Castle. And we treat them as normal objects and search only for the main group ( we don't search for flags and basements).

The found UID is removed from `objectsUids`. But if we currently remove any found UID without checking for group then we will not erase the Town: the Town Flag is located prior to the Town. ... We can improve this logic a bit here (erase town by finding its first flag) ... it'll need some tests.

For Roads and Streams we should remove them by `updateRoadOnTile` and `updateStreamOnTile` to properly update Roads and Streams on tiles around in `world`. These objects are updated in Map_Format by `action.commit();` using `writeTile()` function.

2024-02-15 18:37 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +                     || std::none_of( objectGroups.begin(), objectGroups.end(), [&object]( const Maps::ObjectGroup group ) { return group == object->group; } ) ) {
The code is updated: now we remove any found UID except flags and basements because they are the part of town.

2024-02-21 01:00 UTC, ihhub approved these changes

2024-02-21 01:00 UTC, ihhub commented
Hi @Branikolog , please test this PR as the highest priority.

2024-03-02 21:48 UTC, Branikolog commented
Hi, @Districh-ru !
Nice work, as always!

Found only one tiny issue here:

https://github.com/ihhub/fheroes2/assets/55348946/0119a592-28a8-458f-ab97-0232586aa29e

Road under the castle is not erased somehow.

2024-03-05 03:11 UTC, Districh-ru commented
Hi, @Branikolog, the issue is fixed.
In future we will rework roads placing for the new fheroes2 map format. It should fix some road placing issues including this one without a need of placing extra "hacky" checks to the code.

2024-03-05 12:31 UTC, Branikolog commented
Hi, @Districh-ru 
Assertion is occurring, when I release erasure tool (area brush) over the edge of the world map.

2024-03-05 14:38 UTC, Districh-ru commented
> Hi, @Districh-ru Assertion is occurring, when I release erasure tool (area brush) over the edge of the world map.

@Branikolog, thanks for finding this issue!
Fixed.

2024-03-06 22:13 UTC, merged

2024-03-06 22:13 UTC, ihhub commented
@Districh-ru , thanks a lot for these changes!