[TEST, NOT FOR MERGING] Remove the AI unit growth bonuses and income bonuses for all difficulty levels
ihhub/fheroes2 pull request #8402
Opened 2024-02-13 18:18 UTC by oleg-derevenetz

This PR was created within the scope of #8321 for testing purposes and not intended for merging to `master`.

2024-02-15 10:42 UTC, LeHerosInconnu commented
So, I finished my first test with this PR in game difficulty hard.

Here are screenshots of some of the cities I captured, where even without the creature growth bonus and gold income bonus, the AI was unable to recruit most of the creatures.

In fheroes2:

![After yellow 01](https://github.com/ihhub/fheroes2/assets/43583994/1f146b99-f801-41b8-baeb-66fe1be453fc)

![After violet 01](https://github.com/ihhub/fheroes2/assets/43583994/44bc7541-2b09-4d68-ac5a-acfe256c6627)

![After violet 03](https://github.com/ihhub/fheroes2/assets/43583994/fb16c2d2-9b5d-484c-8481-6f4f95a8415a)

Here are the save files:

[Before after hard no ai bonus 01.zip](https://github.com/ihhub/fheroes2/files/14295548/Before.after.hard.no.ai.bonus.01.zip)

Then I watched a [recent let's play of fheroes2](https://www.youtube.com/watch?v=YJejNWNa3UM&t=7435s) with these growth and income bonuses for AI in impossible difficulty mode.
And that's what I've been noticing in my tests too, it's the human player who ultimately benefits from these AI growth bonuses.
That's what makes it so easy for him to win the game, without any further challenge.

In fheroes2 (from the let's play):

![Broken growth 01](https://github.com/ihhub/fheroes2/assets/43583994/5fcb29cf-da85-47b2-971f-8bd56811219f)

2024-02-15 11:34 UTC, oleg-derevenetz commented
> And that's what I've been noticing in my tests too, it's the human player who ultimately benefits from these AI growth bonuses.
That's what makes it so easy for him to win the game, without any further challenge.

So what specific fixes are needed? In theory, we need some kind of formula `M = F(G)` that calculates an increase in money income depending on the increase in unit growth for AI (even if `G` is zero, because not all units are redeemed without bonuses either). By the way, the redemption of units in castles is not carried out every week "automatically", but only if necessary, that is, if the castle is visited by a hero or if the castle is under threat (that is, an enemy hero is seen nearby).

2024-02-15 16:17 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

> > And that's what I've been noticing in my tests too, it's the human player who ultimately benefits from these AI growth bonuses.
> > That's what makes it so easy for him to win the game, without any further challenge.
> 
> So what specific fixes are needed? In theory, we need some kind of formula `M = F(G)` that calculates an increase in money income depending on the increase in unit growth for AI (even if `G` is zero, because not all units are redeemed without bonuses either). By the way, the redemption of units in castles is not carried out every week "automatically", but only if necessary, that is, if the castle is visited by a hero or if the castle is under threat (that is, an enemy hero is seen nearby).

Giving more gold to the AI based on additional creature bonuses is not a solution for me, as it would destabilize the original game's "balance" between the different castles.
Castles with the strongest creatures would receive more gold to buy them and become even more powerful.

In Heroes 2, gold (and other resources) is the main factor to consider.
The game's standard income (the income from a castle compared to the cost of recruiting creatures from the same castle) doesn't allow for the purchase of all creatures, for both human and AI players.
That's why players have to do their best to acquire income from outside the castle.
By increasing the AI's gold income, it will be able to recruit more creatures and more quickly than the human player.
Higher difficulty levels should increase this recruitment capacity, and even more quickly too.

Increasing the AI's income with a simple percentage (without a convoluted formula) is simple for all players to understand and simple to put in place, and there's only one adjustment factor so it's easier to work out what's going wrong.
As I suggested in this post: https://github.com/ihhub/fheroes2/discussions/8321#discussioncomment-8432733.

> No creature growth bonus for AI.
> 
> I would do it this way:
> - Easy: -25% gold income
> - Normal: no bonus/malus
> - Hard: +50% gold income
> - Expert: +100% gold income, +1 of each resource per day
> - Impossible: +200% gold income, +1 of each resource per day
> 
> If impossible mode is not sufficiently different from expert mode, we can adjust to +2 of each resource per day, but I don't think this is necessary.

This would, I think, be a good basis for observing the effectiveness of AI, without giving an advantage that would ultimately be more beneficial to the human player.

In the original game, the AI buys everything it can and never gives gold to the opponent.
Granted, the creatures aren't used to their full potential, but at least the opponent can't recruit them (or at least much less than if the AI didn't recruit them).
Also, if I'm not mistaken, currently the AI is not immune to a long distance attack with the dimension door spell from the human player.

If I remember correctly, in Heroes 2, the bonuses for AI are as follows:
- Hard: +10% gold income, +1 unit of ore, +1 unit of wood per day
- Expert: +50% gold income, +1 of each resource per day
- Impossible: +100% gold income, +2 of each resource per day

And it's not enough, in my experience, to give the AI the ability to recruit all the creatures available in Heroes 2 either.
But there is, thanks to this, a difference between the different difficulty levels.

2024-02-15 16:43 UTC, oleg-derevenetz commented
> I would do it this way:
> 
> * Easy: -25% gold income
> * Normal: no bonus/malus
> * Hard: +50% gold income
> * Expert: +100% gold income, +1 of each resource per day
> * Impossible: +200% gold income, +1 of each resource per day

Well, let's try this way. I adjusted the income bonus in this PR according to this (well, almost - except the +1 of each resource, because this is not available now, it needs some additional code).

> By increasing the AI's gold income, it will be able to recruit more creatures and more quickly than the human player.
Higher difficulty levels should increase this recruitment capacity, and even more quickly too.

This will only work up to a certain limit. Let's say if on the Expert difficulty (+100% income) AI will already be able to buy out all the troops, then additional +100% income on the Impossible difficulty won't matter because there just will be no additional troops to hire.

2024-02-15 17:06 UTC, LeHerosInconnu commented
@oleg-derevenetz,

> > I would do it this way:
> > 
> > * Easy: -25% gold income
> > * Normal: no bonus/malus
> > * Hard: +50% gold income
> > * Expert: +100% gold income, +1 of each resource per day
> > * Impossible: +200% gold income, +1 of each resource per day
> 
> Well, let's try this way. I adjusted the income bonus in this PR according to this (well, almost - except the +1 of each resource, because this is not available now, it needs some additional code).

Okay.

> > By increasing the AI's gold income, it will be able to recruit more creatures and more quickly than the human player.
> > Higher difficulty levels should increase this recruitment capacity, and even more quickly too.
> 
> This will only work up to a certain limit. Let's say if on the Expert difficulty (+100% income) AI will already be able to buy out all the troops, then additional +100% income on the Impossible difficulty won't matter because there just will be no additional troops to hire.

If the AI has more gold, it can be more aggressive (recruit its creatures and build its cities, as well as having more active heroes with strong armies on the adventure map), and it can also recruit creatures from captured castles that the human player was unable to recruit.
Let's see how the AI performs with the latest changes.
I'll start a test tomorrow (certainly in expert difficulty).

Another question I have is whether the AI knows how to use the secondary skill diplomacy.
Because there's also gold to be spent on this, although it requires a very solid economy.

2024-02-17 15:31 UTC, LeHerosInconnu commented
@oleg-derevenetz,

So, I continued my tests.

In a first game, on expert difficulty, I played a bit relaxed, getting surprised by a more aggressive AI with better armies.

In the second game, still on expert difficulty, the AI was just as aggressive, still with better armies, and it took me a little longer to defeat it, and it was more difficult than usual with the standard version of fheroes2.
The cities conquered from the AI offered few or no creatures for recruitment, unlike the standard version of fheroes2.
It's worth noting, however, that the scenario played, Broken Alliance, has plenty of gold mines, which may have given the AI a very generous income.

For me, the current AI income bonus values in this PR are fine.
I'll test the same scenario in impossible difficulty, then another scenario where there are fewer gold resources on the adventure map later.

Here are the save files:
[Expert no ai bonus 01.zip](https://github.com/ihhub/fheroes2/files/14319266/Expert.no.ai.bonus.01.zip)

2024-02-17 18:13 UTC, oleg-derevenetz commented
> In a first game, on expert difficulty, I played a bit relaxed, getting surprised by a more aggressive AI with better armies.

More resources will certainly help AI develop its castles more intensively (even if there is only more gold, because AI is able to buy missing resources using marketplace if it has an excess of gold). The more interesting question is what will happen when it develops all the available castles, and it will be able to spend money only on hiring troops, and the number of troops now does not increase with increasing difficulty. I suspect that this should be more noticeable on L or XL maps. Broken Alliance is a medium map.

2024-02-18 10:54 UTC, LeHerosInconnu commented
@oleg-derevenetz,

First game on impossible difficulty, still Broken Alliance, this time I played a little more seriously.

The AI heroes appear more quickly with armies of level six creatures.
AI cities are well developed, with a few unrecruited creatures left in conquered AI cities.
In this game, I forced the pace and finished the scenario more quickly (I built a level five mage guild in a conquered AI city and obtained the dimension door spell).

In fheroes2:

Some towns where level six creatures are available for a number corresponding to several weeks' growth;
![Broken impossible 001](https://github.com/ihhub/fheroes2/assets/43583994/4ff9e5ef-f9f4-42f3-b5ee-9f6dc5feae73)
![Broken impossible 002](https://github.com/ihhub/fheroes2/assets/43583994/4ad469ac-0f5c-4d38-a2cc-3954306f17e9)

A few unrecruited creatures from the week's growth, nothing too bad;
![Broken impossible 003](https://github.com/ihhub/fheroes2/assets/43583994/2bdd5637-e752-435c-99c9-d7a63dbedd35)

AI's last castle:
![Broken impossible 004](https://github.com/ihhub/fheroes2/assets/43583994/7b4ae6f2-3b48-4f21-8948-66bc5d2e36fb)

Here are the save files:
[Broken impossible 01.zip](https://github.com/ihhub/fheroes2/files/14322132/Broken.impossible.01.zip)

> > In a first game, on expert difficulty, I played a bit relaxed, getting surprised by a more aggressive AI with better armies.
> 
> More resources will certainly help AI develop its castles more intensively (even if there is only more gold, because AI is able to buy missing resources using marketplace if it has an excess of gold). The more interesting question is what will happen when it develops all the available castles, and it will be able to spend money only on hiring troops, and the number of troops now does not increase with increasing difficulty. I suspect that this should be more noticeable on L or XL maps, but with a relatively small number of towns/castles. Broken Alliance is a map of a medium size, AI finds and attacks the human player pretty quickly.

That's what I've observed.
I'm now going to do a test with the scenario Heroes (L size map).

2024-02-18 17:19 UTC, LeHerosInconnu commented
@oleg-derevenetz,

First game on scenario Heroes on impossible difficulty, AI attacks me month 1, week 2, day 6, game over.

In fheroes2:

![Heroes yellow bone end 01](https://github.com/ihhub/fheroes2/assets/43583994/05cc05f8-c192-40cf-b960-6af231f3365a)

Second game on scenario Heroes on impossible difficulty, I win against AI month 3, week 3, day 6.

In fheroes2:

Final combat:
![Heroes win impossible 02](https://github.com/ihhub/fheroes2/assets/43583994/855f5495-f749-4833-b103-9a88e3f5521c)

AI has nice armies, despite the fact that there is only one castle per player and only five gold mines to capture on the adventure map.

In fheroes2:

Month 2, week 1 , day 2;
![AI armies impossible 02 001](https://github.com/ihhub/fheroes2/assets/43583994/12eb3451-fbe6-408d-9d79-cd45d5642d44)
![AI armies impossible 02 002](https://github.com/ihhub/fheroes2/assets/43583994/233c82f6-996b-41b4-ab10-18c203c6e663)
![AI armies impossible 02 003](https://github.com/ihhub/fheroes2/assets/43583994/b440ea54-f7d3-481f-ad0b-fc1c30ed77bd)

Month 2, week 2, day 5;
![AI armies impossible 02 004](https://github.com/ihhub/fheroes2/assets/43583994/b45e3764-5ab8-48a7-ba29-600037ef3e01)
![AI armies impossible 02 005](https://github.com/ihhub/fheroes2/assets/43583994/d3801812-cee4-4fd3-9a69-cabd926e4028)

Month 2, week 4 , day 1;
![AI armies impossible 02 006](https://github.com/ihhub/fheroes2/assets/43583994/8d65c3c6-f006-4ced-aa89-b80c70e75a8b)
![AI armies impossible 02 007](https://github.com/ihhub/fheroes2/assets/43583994/4947e6f8-49aa-4668-8191-bfca5aa497f4)

Here are the save files:
[Heroes lose win impossible 01.zip](https://github.com/ihhub/fheroes2/files/14323530/Heroes.lose.win.impossible.01.zip)

> ...The more interesting question is what will happen when it develops all the available castles, and it will be able to spend money only on hiring troops, and the number of troops now does not increase with increasing difficulty. I suspect that this should be more noticeable on L or XL maps, but with a relatively small number of towns/castles.

The aim is not to make the AI invincible, but to make the AI more harassing more quickly.
If the human player manages to get the better over the AI, I think it's perfectly normal for the AI to get weaker.
If the AI has a large amount of gold (which it might not be able to spend at all times), this is also beneficial for the AL, as the AI will be able to recruit creatures not recruited by the human player (the human player doesn't have the possibility of recruiting all the creatures at his disposal) when capturing or recapturing castles.

2024-02-18 18:15 UTC, oleg-derevenetz commented
> The aim is not to make the AI invincible, but to make the AI more harassing more quickly.

Nevertheless, it would be desirable to make the AI represent some challenge for experienced human players too (at least on Expert and Impossible difficulties). I just tried to increase the creature growth for Expert and Impossible difficulties by 25% and 33% respectively (while maintaining the gold income bonus by 200% and 300% respectively) and propose to try to test this when you have time - what will be your impressions? Will the game become more difficult or not?

2024-02-21 16:35 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

> > The aim is not to make the AI invincible, but to make the AI more harassing more quickly.
> 
> Nevertheless, it would be desirable to make the AI represent some challenge for experienced human players too (at least on Expert and Impossible difficulties). I just tried to increase the creature growth for Expert and Impossible difficulties by 25% and 33% respectively (while maintaining the gold income bonus by 200% and 300% respectively) and propose to try to test this when you have time - what will be your impressions? Will the game become more difficult or not?

So, I continued my tests, this time with the Dominion scenario (PoL), an XL sized map, on impossible difficulty.

In the first game, the orange AI player is superior in power month 3, week 2, day 3, no way to come back for my side.
In the second game, the green AI player made a decisive attack month 1, week 3, day 1, no way to come back for my side.

The AI is much more harassing than the last time I played this scenario.
The green AI player is attacking from the west.
The yellow AI player is attacking by sea from the east.
The orange AI player is attacking by sea from the south.

In the third game, I managed to stand my ground and get the edge over my opponents.
But not necessarily to win the game at that moment.

However, the additional growth of AI creatures benefits the human player.
The fact that it is delayed in time (not at the start of the first day, but only when the AI has the hand) does not detract from this fact.

Over time, it's this extra growth for the AI, which I ultimately benefited from, that ensures I get the upper hand over the other AI players.

<details>
<summary>The human player benefits from the additional creature growth of the AI: (click to expand)</summary>
<br>

First game:
I was able to get the extra AI creatures after recapturing one of my castles:
![Bef recap yellow 01](https://github.com/ihhub/fheroes2/assets/43583994/56137416-94e0-4e9d-aa0f-d99b40d8c1e2)

Third game:
Some cyclops from the previous week are available in excess of standard growth:
![Ai growth bonus human 003](https://github.com/ihhub/fheroes2/assets/43583994/a37e33e2-8a48-477d-8cc7-fe21eedf6b6f)
![Ai growth bonus human 007](https://github.com/ihhub/fheroes2/assets/43583994/8d6d763d-1483-4b9c-93f4-d96d626165f2)

AI has not recruited the extra cyclops (however in numbers less than or equal to standard growth):
![Ai growth bonus human 004](https://github.com/ihhub/fheroes2/assets/43583994/0fd3f02c-e234-48df-bd00-088db8e3a1f5)
![Ai growth bonus human 005](https://github.com/ihhub/fheroes2/assets/43583994/96b4a2c5-b7aa-44c6-ac76-2ad08bc254b6)
![Ai growth bonus human 009](https://github.com/ihhub/fheroes2/assets/43583994/4a4edc24-c0d1-4c7a-913b-4e614a9c2372)

AI has not recruited the extra cyclops (this time in excess of standard growth):
![Ai growth bonus human 006](https://github.com/ihhub/fheroes2/assets/43583994/5db4ea84-619c-4d65-8841-0c7e519e2f62)

A few extra creatures from Knight Castle:
![Ai growth bonus human 008](https://github.com/ihhub/fheroes2/assets/43583994/3865bd16-82e1-4caa-b86d-f81a661db852)

It also works for the Sorceress's castle:
![Ai growth bonus human 010](https://github.com/ihhub/fheroes2/assets/43583994/7cd22d47-ceab-4c2b-ae70-ccde434f4857)

And it's bouquet time in the Wizard's castle:
It's the end of the game for the AI.
From this point on, the game is won for the human player, and the rest is just a matter of completing the scenario.
![Ai growth bonus human 011](https://github.com/ihhub/fheroes2/assets/43583994/0a60c324-7026-4250-925e-9a5df10a6301)

More titans;
![Ai growth bonus human 012](https://github.com/ihhub/fheroes2/assets/43583994/7bd550a5-8f28-4d81-b448-787a174b9686)

A few black dragons, for variety:
![Ai growth bonus human 013](https://github.com/ihhub/fheroes2/assets/43583994/892ec513-049c-4ef7-970e-8b5a29488b37)

And more titans;
![Ai growth bonus human 014](https://github.com/ihhub/fheroes2/assets/43583994/2f3b8353-7715-47fc-a13c-027c81214526)

Even more titans:
![Ai growth bonus human 015](https://github.com/ihhub/fheroes2/assets/43583994/9824c56e-6b28-4595-8e49-c6f6939ff217)

Titans everywhere:
![Ai growth bonus human 016](https://github.com/ihhub/fheroes2/assets/43583994/463f7fea-e6b7-4741-b44f-99ca3bb41acb)

</details>

This just goes to show that additional creature growth for AI is more harmful in the end.
With the gold bonus, the AI comes out ahead, and is more aggressive more quickly.
But the extra creature growth for the AI just allows the human player to get around this.

In short, let's remove the extra growth completely for the AI and see how it performs with the current gold bonus.

Here are the save files:
[Dominion impossible lose 01.zip](https://github.com/ihhub/fheroes2/files/14362082/Dominion.impossible.lose.01.zip)
[Ai growth bonus for human 01.zip](https://github.com/ihhub/fheroes2/files/14362084/Ai.growth.bonus.for.human.01.zip)

2024-02-21 18:07 UTC, oleg-derevenetz commented
> The problem is that as creature growth increases, the most powerful castles, which are also supposed to be trickier to play on smaller maps, will become even more powerful, and on all map sizes.

If necessary, we can easily make different growth bonuses for different castles (and even for different dwellings).

> As I wrote earlier, let's do a test with all creature growth bonuses removed, so with the gold bonus only, and see how it goes.

OK, I removed the dwelling growth bonuses completely once again.

2024-02-21 18:22 UTC, LeHerosInconnu commented
@oleg-derevenetz,

> > The problem is that as creature growth increases, the most powerful castles, which are also supposed to be trickier to play on smaller maps, will become even more powerful, and on all map sizes.
> 
> If necessary, we can easily make different growth bonuses for different castles (and even for different dwellings).

I think it would be very complicated to make something coherent.

> > As I wrote earlier, let's do a test with all creature growth bonuses removed, so with the gold bonus only, and see how it goes.
> 
> OK, I removed the dwelling growth bonuses completely once again.

I'll run a test for that.

2024-02-21 22:09 UTC, oleg-derevenetz commented
As part of this PR, I have now also added resource income bonus for Expert and Impossible difficulties (+2 wood and ore, +1 of each rare resource - i.e. it's like AI on these difficulties always has one mine of each type except gold). But I really don't know how much this will actually complicate the game on these difficulties.

I also additionally banned the level 5 Mage Guild construction on Easy difficulty, but that's another story.

2024-02-25 16:43 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

So, I finished my test with the latest version of this PR.

There are far fewer creatures available for recruitment in castles conquered to AI.
However, it's still too many (especially for the impossible difficulty), and it enabled me to fend off the AI's counter attack to retake its castles thanks to the few titans I was able to recruit.

<details>
<summary>Creatures not recruited by AI: (click to expand)</summary>
<br>

My first attempt to conquer the orange AI player.
Some unrecruited giants:
![After orange 01 01](https://github.com/ihhub/fheroes2/assets/43583994/9a0a7812-597f-4205-8f97-46e5984c2405)
The AI player has giants in his army:
![After orange 01 02](https://github.com/ihhub/fheroes2/assets/43583994/d70ce9f2-b9b1-4a5a-9f96-fe3e23b359e8)

My second attempt to conquer the orange AI player.
One unrecruited titan, nothing fabulous:
![After orange 03 01](https://github.com/ihhub/fheroes2/assets/43583994/0d6177c0-ec83-479c-aee4-a40c4cd38b14)
The AI player has giants in his army:
![After orange 03 02](https://github.com/ihhub/fheroes2/assets/43583994/5f657b23-62fc-4607-af94-84ab309cf781)

Second castle of the orange AI player captured.
This time the titans are numerous:
![After orange 04 01](https://github.com/ihhub/fheroes2/assets/43583994/ba277dee-73aa-4939-9e2e-466b9bde4813)
The AI player has giants in his armies:
![After orange 04 02](https://github.com/ihhub/fheroes2/assets/43583994/ca94c69a-1479-49ba-93f6-115e769135fb)
![After orange 04 03](https://github.com/ihhub/fheroes2/assets/43583994/a2623448-6d67-4c54-95b5-3acc3d9c1cc1)

Third castle of the orange AI player captured.
Titans and other non recruited creatures:
![After orange 05 01](https://github.com/ihhub/fheroes2/assets/43583994/162138d0-b73f-44de-8951-b2c54d06f9e2)

Next castle of the orange AI player captured.
Titans and other non recruited creatures:
![After orange 06 01](https://github.com/ihhub/fheroes2/assets/43583994/a163db66-fac5-42bf-9fe5-bbda5073c210)

Next castle of the orange AI player captured.
Titans and other non recruited creatures:
![After orange 07 01](https://github.com/ihhub/fheroes2/assets/43583994/82db77f9-643c-49f7-b807-f14023225b19)

Castle of the orange AI player recaptured.
Titans and other non recruited creatures (there were 10 titans available for recruitment before the AI captured the castle):
![After orange recap 10 08 01](https://github.com/ihhub/fheroes2/assets/43583994/a9055266-2d6c-41e3-a05a-d42c250fd3d4)

Castle of the red AI player captured.
Creatures available on day two of the week:
![After red 10 01](https://github.com/ihhub/fheroes2/assets/43583994/b02e2fe9-bd95-45c8-9d21-d93d27ca8315)

Castle of the yellow AI player captured.
Many unrecruited black dragons:
![After yellow 01 01](https://github.com/ihhub/fheroes2/assets/43583994/ffe337e0-0629-4f4d-91f4-9a7622cfb0ec)

</details>

I need to know how the AI works.
Does the AI improve the creatures it has already recruited?
In the example, the AI has recruited giants, does it improve them afterwards?
Because if it does, it's a sort of "waste" of important resources (especially with double the difference to upgrade giant, which is then more expensive than the cost of titan), which may mean that it runs out of resources to recruit its available titans.
If so, this could be adjusted by having the AI recruit upgraded creatures first, before upgrading the basic creatures it already has, and if it has enough resources to do so.

Alternatively, the AI may not have enough gold, because it has recruited other, less expensive level six creatures (e.g. phoenixes) from conquered enemy castles that had not been recruited.
Or the AI doesn't have enough resources (in the example, gems for titans and sulfur for black dragons).
Is it possible to check the save file to see how many resources and gold the AI has?

With the current bonuses, only the Wizard's and Warlock's castles have this problem of unrecruited level six creatures.
The problem may be a lack of gold, or lack of resources, or both.

We could increase the AI's gold bonus, which I think would solve all the problems I've mentioned above at once.

This way:

- Easy: -25% gold income
- Normal: no bonus/malus
- Hard: +100% gold income
- Expert: +200% gold income, +2 ore and +2 wood, +1 of each rare resource per day
- Impossible: +300% gold income, +2 ore and +2 wood, +1 of each rare resource per day

I'm ready to do another test with these increased bonuses.

Here are the save files:
[Ai growth impossible dominion 01.zip](https://github.com/ihhub/fheroes2/files/14397058/Ai.growth.impossible.dominion.01.zip)
[Dominion_0127 impossible end.zip](https://github.com/ihhub/fheroes2/files/14397059/Dominion_0127.impossible.end.zip)

2024-02-25 20:27 UTC, oleg-derevenetz commented
> Does the AI improve the creatures it has already recruited?
> In the example, the AI has recruited giants, does it improve them afterwards?

Yes, it does, if possible.

> Because if it does, it's a sort of "waste" of important resources (especially with double the difference to upgrade giant, which is then more expensive than the cost of titan), which may mean that it runs out of resources to recruit its available titans.

I didn't write this logic at the time, but according to what I see AI makes efforts to upgrade units to reinforce the hero by as many powerful units as possible. Otherwise, weaker upgraded units would have to be left in the garrison, and there may even be a situation where their upgraded version will not be able to be hired at all, because AI never dismisses units, even the weakest ones. The most it does is move the weaker units in the garrison, but it never dismisses them.

> Is it possible to check the save file to see how many resources and gold the AI has?

Normally you can't do this, but it is possible to write the appropriate code (which I did). Here are the AI resources at the end of the game (file `Dominion_0127end`). Please note that there is no further resource income after the kingdom has vanquished, so there is sort of "snapshot" of the kingdom's resources on its last day:

```
color: Red, resources: ore: 280, wood: 70, mercury: 65, sulfur: 47, crystal: 5, gems: 49, gold: 186020
color: Green, resources: ore: 89, wood: 32, mercury: 6, sulfur: 16, crystal: 13, gems: 38, gold: 24919
color: Yellow, resources: ore: 98, wood: 32, mercury: 52, sulfur: 2, crystal: 31, gems: 48, gold: 119211
color: Orange, resources: ore: 77, wood: 20, mercury: 22, sulfur: 20, crystal: 22, gems: 21, gold: 6872
color: Purple, resources: ore: 103, wood: 101, mercury: 59, sulfur: 52, crystal: 11, gems: 155, gold: 168348
```

So yes, the Orange player has a kind of shortage of gold (but the rest of the resources seems generally fine). Yellow player has the shortage of sulfur (for dragons), but his gold amount is fine in general. Perhaps using marketplaces for hiring units could help with this, but this is not implemented (at least for now), because although in the case of the castle development, the resource priorities are more or less clear, in the case of simultaneous trading both for the development of castles and the hiring of units, the question of priorities becomes difficult and unreliably calculated due to the large number of poorly predictable options. Right now, marketplace support is mainly intended to let the AI more or less develop castles in conditions of shortage of resources of a certain type (e.g. in case it does not have enough strength to capture a mine of a certain type from its guards or is there simply no such mine nearby - especially when AI doesn't have resource bonuses), but not to hire more units.

> Easy: -25% gold income
Normal: no bonus/malus
Hard: +100% gold income
Expert: +200% gold income, +2 ore and +2 wood, +1 of each rare resource per day
Impossible: +300% gold income, +2 ore and +2 wood, +1 of each rare resource per day

I have just made the appropriate changes to this PR, with one difference: on Impossible AI will get additional resources as if it has 2 extra mines of each type instead of 1.

> I'm ready to do another test with these increased bonuses.

Yes, please, when you have time of course. And how does the game feel in general? Has it really become noticeably harder to play on Expert and Impossible difficulties? Is there a real difference between these two difficulties?

2024-02-26 12:49 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

> > Does the AI improve the creatures it has already recruited?
> > In the example, the AI has recruited giants, does it improve them afterwards?
> 
> Yes, it does, if possible.
> 
> > Because if it does, it's a sort of "waste" of important resources (especially with double the difference to upgrade giant, which is then more expensive than the cost of titan), which may mean that it runs out of resources to recruit its available titans.
> 
> I didn't write this logic at the time, but according to what I see AI makes efforts to upgrade units to reinforce the hero by as many powerful units as possible. Otherwise, weaker upgraded units would have to be left in the garrison, and there may even be a situation where their upgraded version will not be able to be hired at all, because AI never dismisses units, even the weakest ones. The most it does is move the weaker units in the garrison, but it never dismisses them.

Okay, thanks for the precisions.

> > Is it possible to check the save file to see how many resources and gold the AI has?
> 
> Normally you can't do this, but it is possible to write the appropriate code (which I did). Here are the AI resources at the end of the game (file `Dominion_0127end`). Please note that there is no further resource income after the kingdom has vanquished, so there is sort of "snapshot" of the kingdom's resources on its last day:
> 
> ```
> color: Red, resources: ore: 280, wood: 70, mercury: 65, sulfur: 47, crystal: 5, gems: 49, gold: 186020
> color: Green, resources: ore: 89, wood: 32, mercury: 6, sulfur: 16, crystal: 13, gems: 38, gold: 24919
> color: Yellow, resources: ore: 98, wood: 32, mercury: 52, sulfur: 2, crystal: 31, gems: 48, gold: 119211
> color: Orange, resources: ore: 77, wood: 20, mercury: 22, sulfur: 20, crystal: 22, gems: 21, gold: 6872
> color: Purple, resources: ore: 103, wood: 101, mercury: 59, sulfur: 52, crystal: 11, gems: 155, gold: 168348
> ```

Great, it would be nice to have this available as a tool for testing purposes.

> So yes, the Orange player has a kind of shortage of gold (but the rest of the resources seems generally fine). Yellow player has the shortage of sulfur (for dragons), but his gold amount is fine in general. Perhaps using marketplaces for hiring units could help with this, but this is not implemented (at least for now), because although in the case of the castle development, the resource priorities are more or less clear, in the case of simultaneous trading both for the development of castles and the hiring of units, the question of priorities becomes difficult and unreliably calculated due to the large number of poorly predictable options. Right now, marketplace support is mainly intended to help the AI more or less develop castles in conditions of shortage of resources of a certain type (e.g. in case it does not have enough strength to capture a mine of a certain type from its guards or is there simply no such mine nearby - especially when AI doesn't have resource bonuses), but not to hire more units.

Okay, I see.
Let's see the change with the new bonus values for AI before we look at the possibility of exchanging resources to recruit creatures.

> > Easy: -25% gold income
> > Normal: no bonus/malus
> > Hard: +100% gold income
> > Expert: +200% gold income, +2 ore and +2 wood, +1 of each rare resource per day
> > Impossible: +300% gold income, +2 ore and +2 wood, +1 of each rare resource per day
> 
> I have just made the appropriate changes to this PR, with one difference: on Impossible AI will get additional resources as if it has 2 extra mines of each type instead of 1.

Okay, that should do the job.

> > I'm ready to do another test with these increased bonuses.
> 
> Yes, please, when you have time of course. And how does the game feel in general? Has it really become noticeably harder to play on Expert and Impossible difficulties? Is there a real difference between these two difficulties?

In my previous test, the AI did a good job of harassing me and defending its territory.
And it was more difficult to "negotiate" with the AI. :)
I will test this on the same scenario, first on impossible difficulty and then on expert difficulty.

2024-03-01 19:12 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

So, I finished my first test on impossible difficulty.

In the first game, the yellow AI player made a decisive attack month 2, week 1, day 3, no way to come back for my side.
In the first game, the yellow AI player made a decisive attack month 2, week 2, day 2, no way to come back for my side.
I won the third game month 4, week 3, day 2.
This is the first time I've had to concede my starting cities to the AI with this scenario, namely my Knight castles. :)

<details>
<summary>AI yellow player's combined invasion: (click to expand)</summary>
<br>

Start of AI yellow player's combined invasion, month 2, week 4, day 7 (Dominion_0056.sav).
![Dominion_0056](https://github.com/ihhub/fheroes2/assets/43583994/94bfac15-4657-4da4-a67f-11dbe637867a)

Lord Kilburn is in charge of defending the last castle and inflicting maximum casualties on the attackers before surrendering.
![Dominion_0062i 00](https://github.com/ihhub/fheroes2/assets/43583994/2dbc2c8c-9745-43bf-bd50-2f1f19c592d5)
![Dominion_0062i 01](https://github.com/ihhub/fheroes2/assets/43583994/9dda64cd-9107-4ed8-b323-3179cc068da9)
I didn't have enough gold to recruit all the creatures available.
![Dominion_0062i 02](https://github.com/ihhub/fheroes2/assets/43583994/3f83ab48-7979-41ce-ab57-86c3b3c8834d)

Tyro, for his part, will have to repel the invasion of the green player, who the following day will try to retreat by sea, and who will surrender on his boat (Dominion_0062i.sav).
![Dominion_0062i 03](https://github.com/ihhub/fheroes2/assets/43583994/57a7055d-b35c-4774-b71a-c5f14626e826)
The AI pays me gold to keep a few low level creatures.
I'll use that gold to recruit titans later, thanks.
![Dominion_0063 02](https://github.com/ihhub/fheroes2/assets/43583994/ed78b481-6328-4fe6-b0cf-70f9529f2abe)

AI yellow player's conquest completed, month 3, week 1, day 7 (Dominion_0063.sav).
![Dominion_0063](https://github.com/ihhub/fheroes2/assets/43583994/becc2aeb-0114-46f8-9df9-9effbcf923cf)

</details>
<details>
<summary>Creatures not recruited by AI: (click to expand)</summary>
<br>

Some creatures not recruited, day 2 (After green 01.sav).
![After green 01](https://github.com/ihhub/fheroes2/assets/43583994/7d23f98d-41fd-4e72-b93b-ae661439ef11)

Many black dragons not recruited (After yellow 01.sav).
![After yellow 01](https://github.com/ihhub/fheroes2/assets/43583994/13077f24-6081-4cd5-8acb-e30f797576f9)
 
Many black dragons not recruited (After yellow 02.sav).
![After yellow 02](https://github.com/ihhub/fheroes2/assets/43583994/8798929c-2afb-4ef4-9dd2-d1993af43175)

This is not desirable in impossible difficulty, and will have to be remedied.
Can you show (as above) the quantities of resources and gold of all players from the save file "Before yellow 01.sav" to see if the yellow AI player is short on gold and/or sulfur?
Normally, his gold income should enable him to recruit his black dragons, but it's also possible that he spent his gold on recruiting the creatures from the knight castles he conquered and which I hadn't been able to recruit for lack of gold.
After reviewing the remaining resources of the AI players, I will propose the adjustments to be made.

The Anduran hero is available at the tavern.
He has surrendered and has a few creatures in his army.
He is a former hero of the purple AI player.
He is available in a jail on the adventure map at the start of the scenario.
And it's me, the human player, who's going to take advantage of these few creatures funded by the AI (Anduran tavern 01.sav).
![Anduran tavern 01](https://github.com/ihhub/fheroes2/assets/43583994/47815b30-436e-41ce-9598-f2c0dab83f2b)

Some creatures not recruited, day 2.
My hero travelled with the dimension door spell before attacking (After violet 01.sav).
![After violet 01](https://github.com/ihhub/fheroes2/assets/43583994/2c2a15c1-9bc4-4b50-969e-770c0a9535b8)

Some creatures not recruited, day 3.
My hero travelled with the dimension door spell before attacking (After violet 03.sav).
![After violet 03](https://github.com/ihhub/fheroes2/assets/43583994/f15bb044-e980-4c1b-ad18-94b27e7394b7)

Some creatures not recruited, day 4.
My hero travelled with the dimension door spell before attacking (After violet 08.sav).
![After violet 08](https://github.com/ihhub/fheroes2/assets/43583994/6f044f18-b2f6-4c71-85dc-d49542066941)

The AI should take into account the movement capability of opposing heroes with the dimension door spell, and recruit creatures from its cities if it can.

</details>
<details>
<summary>AI is funding the recruitment of my creatures: (click to expand)</summary>
<br>

It's the AI that finances the recruitment of my titans and black dragons, thanks to the ability of its heroes to surrender.

There's a reason why the AI heroes don't surrender in the original game.
The human player is generally out of gold.
The AI never gives the human player any gold to keep him in this "misery".

In fheroes2, all the gold received through surrender allows the human player to get around this gold shortage problem.
In this third game, the AI payed me more than 100 000 gold for the surrender of its heroes.
This corresponds to more than 20 titans or more than 25 black dragons.
This allowed me to recruit titans and black dragons when I needed them.

For my part, I would completely remove the possibility for the AI to allow its heroes to surrender, or else allow it within a very strict context.
As I've already suggested, only to keep level six creatures, and only if they're rare.
And as a special case, for a high level hero and/or one with important artifacts, and this only during a siege.

In fheroes2:
Thank you for funding my conquest, I really appreciate it.
![Gold surrender 10 01](https://github.com/ihhub/fheroes2/assets/43583994/d692f52f-86cf-45ab-bc54-66b73bb3b183)
![Gold surrender 10 02](https://github.com/ihhub/fheroes2/assets/43583994/49d3d09b-806a-4ce5-b0ed-5f2b2399be5e)
![Gold surrender 11](https://github.com/ihhub/fheroes2/assets/43583994/96a02683-9772-4053-a213-3672ea27fbdb)
![Gold surrender 12](https://github.com/ihhub/fheroes2/assets/43583994/762e5523-47f0-4038-9665-f8593f681681)
![Gold surrender 13](https://github.com/ihhub/fheroes2/assets/43583994/9aedc01e-4674-48cc-aa66-173e4a6b0c83)
![Gold surrender 14](https://github.com/ihhub/fheroes2/assets/43583994/e7d8bb6b-1d1c-45ae-bfca-338a96f61a7d)
![Gold surrender 15](https://github.com/ihhub/fheroes2/assets/43583994/adb03230-8666-4460-926e-705c921d1f9c)
![Gold surrender 16](https://github.com/ihhub/fheroes2/assets/43583994/57523800-b4fb-4bcc-9503-e53b9a064994)
![Gold surrender 17](https://github.com/ihhub/fheroes2/assets/43583994/fb9e72e4-fc45-4ec7-81c5-8cbe83298036)
![Gold surrender 18](https://github.com/ihhub/fheroes2/assets/43583994/8e51279f-fe7c-4967-aaa5-b1c648605aa5)
![Gold surrender 101](https://github.com/ihhub/fheroes2/assets/43583994/068adbbc-6ae2-445f-bf35-ce8ac7688c2a)
![Gold surrender 102](https://github.com/ihhub/fheroes2/assets/43583994/e1bf10ab-61c5-43e7-a7e6-e93a9b99c907)
![Gold surrender 103](https://github.com/ihhub/fheroes2/assets/43583994/114838d8-0ff4-400d-a938-247448f114b2)
![Gold surrender 104](https://github.com/ihhub/fheroes2/assets/43583994/3c4e4f04-57ca-40f7-b51c-7b19d690f5db)
![Gold surrender 105](https://github.com/ihhub/fheroes2/assets/43583994/fb1aee52-df5e-48c2-bfb9-045cac23e219)
![Gold surrender 106](https://github.com/ihhub/fheroes2/assets/43583994/0d135026-1574-4bd3-8064-eb41cea37a81)
![Gold surrender 108](https://github.com/ihhub/fheroes2/assets/43583994/a2effbca-2880-4c36-9285-b484d00a4229)
![Gold surrender 109](https://github.com/ihhub/fheroes2/assets/43583994/840fbdb7-b89a-48c5-9a76-e6730269d827)
![Gold surrender 110](https://github.com/ihhub/fheroes2/assets/43583994/268e84fc-8589-4372-98ea-f886993f8553)

</details>

Here are the save files:
[Dominion impossible lose 05 01.zip](https://github.com/ihhub/fheroes2/files/14464798/Dominion.impossible.lose.05.01.zip)
[AI yellow player invasion 01.zip](https://github.com [...]

2024-03-01 20:33 UTC, oleg-derevenetz commented
> Can you show (as above) the quantities of resources and gold of all players from the save file "Before yellow 01.sav" to see if the yellow AI player is short on gold and/or sulfur?
Normally, his gold income should enable him to recruit his black dragons, but it's also possible that he spent his gold on recruiting the creatures from the knight castles he conquered and which I hadn't been able to recruit for lack of gold.

```
Color: Green, funds: ore: 115, wood: 59, mercury: 12, sulfur: 32, crystal: 24, gems: 36, gold: 165194
Color: Red, funds: ore: 118, wood: 44, mercury: 39, sulfur: 53, crystal: 20, gems: 48, gold: 154802
Color: Yellow, funds: ore: 19, wood: 6, mercury: 3, sulfur: 1, crystal: 3, gems: 3, gold: 157459
Color: Orange, funds: ore: 40, wood: 24, mercury: 17, sulfur: 30, crystal: 20, gems: 23, gold: 45235
Color: Purple, funds: ore: 52, wood: 17, mercury: 22, sulfur: 29, crystal: 8, gems: 66, gold: 870105
```

Yellow player has no lack of gold (actually, no AI player has). But he has lack of sulfur, which is understandable, since he owns just one sulfur mine. Apparently, even with two bonus "virtual" mines, this is not enough to redeem all the dragons. I'm not sure if it's worth adding more "virtual" mines for Expert or Impossible difficulty. There is definitely enough gold now,  maybe it should even be reduced a little (say x2.5 bonus for Impossible instead of x3).

> The AI should take into account the movement capability of opposing heroes with the dimension door spell, and recruit creatures from its cities if it can.

Well, that's a separate question :) Now the AI is assessing the danger to its castles (in terms of whether it is necessary to build protective structures and buy out units) based on the so-called "per-region" stats. Maybe it will be improved in some way in the future.

> In fheroes2, all the gold received through surrender allows the human player to get around this gold shortage problem.
In this third game, the AI payed me more than 100 000 gold for the surrender of its heroes.

On the other hand, this means that the AI hero has additional troops left, which would otherwise cost him 200 000 gold (and possibly some additional resources, if we are talking about level 6 creatures). Perhaps on Expert or Impossible difficulties this is not very important, because AI has a bonus income, but on simpler difficulties it does not have this bonus.

2024-03-01 23:03 UTC, LeHerosInconnu commented
@oleg-derevenetz,

> > Can you show (as above) the quantities of resources and gold of all players from the save file "Before yellow 01.sav" to see if the yellow AI player is short on gold and/or sulfur?
> > Normally, his gold income should enable him to recruit his black dragons, but it's also possible that he spent his gold on recruiting the creatures from the knight castles he conquered and which I hadn't been able to recruit for lack of gold.
> 
> ```
> Color: Green, funds: ore: 115, wood: 59, mercury: 12, sulfur: 32, crystal: 24, gems: 36, gold: 165194
> Color: Red, funds: ore: 118, wood: 44, mercury: 39, sulfur: 53, crystal: 20, gems: 48, gold: 154802
> Color: Yellow, funds: ore: 19, wood: 6, mercury: 3, sulfur: 1, crystal: 3, gems: 3, gold: 157459
> Color: Orange, funds: ore: 40, wood: 24, mercury: 17, sulfur: 30, crystal: 20, gems: 23, gold: 45235
> Color: Purple, funds: ore: 52, wood: 17, mercury: 22, sulfur: 29, crystal: 8, gems: 66, gold: 870105
> ```
> 
> Yellow player has no lack of gold (actually, no AI player has). But he has lack of sulfur, which is understandable, since he owns just one sulfur mine. Apparently, even with two bonus "virtual" mines, this is not enough to redeem all the dragons. I'm not sure if it's worth adding more "virtual" mines for Expert or Impossible difficulty. There is definitely enough gold now, maybe it should even be reduced a little (say x2.5 bonus for Impossible instead of x3).

Oh, I think the purple AI player has a fairly substantial gold matelas because he conquered the red player quickly and his basic creatures (Barbarians) are less expensive.
Here is the save file (end the turn):
[AI red lose 01.zip](https://github.com/ihhub/fheroes2/files/14466757/AI.red.lose.01.zip)

It's a good thing that the AI has some gold in reserve so that it can buy creatures not purchased by the human player when it captures his castles.

I'd like to do tests with these values:
- Easy: -25% gold income
- Normal: no bonus/malus
- Hard: +100% gold income, +2 ore and +2 wood, +1 of each rare resource per day
- Expert: +200% gold income, +4 ore and +4 wood, +2 of each rare resource per day
- Impossible: +300% gold income, +6 ore and +6 wood, +3 of each rare resource per day

And we could also put in place something like this:
If the AI has over 100 000 gold, it can buy rare resources to recruit its level 6 creatures, with priority given to green/red/black dragons, then titans/giants, then phoenixes and finally cyclops.

And eventually:
If the AI is short of gold to recruit its creatures (this might eventually happen in certain scenarios), it can sell its resources for gold if they exceed 100 units for ore, 100 units for wood, 50 units for sulfur, 50 units for gems, 50 units for mercury, 50 units for crystal.

> > The AI should take into account the movement capability of opposing heroes with the dimension door spell, and recruit creatures from its cities if it can.
> 
> Well, that's a separate question :) Now the AI is assessing the danger to its castles (in terms of whether it is necessary to build defensive structures and buy out units) based on the so-called "per-region" stats. Maybe it will be improved in some way in the future.

Okay.
While I was at it, I made the point because it concerns creatures to be recruited. :)

> > In fheroes2, all the gold received through surrender allows the human player to get around this gold shortage problem.
> > In this third game, the AI payed me more than 100 000 gold for the surrender of its heroes.
> 
> On the other hand, this means that the AI hero has additional troops left, which would otherwise cost him 200 000 gold (and possibly some additional resources, if we are talking about level 6 creatures). Perhaps on Expert or Impossible difficulties this is not very important, because AI has a bonus income, but on simpler difficulties it does not have this bonus.

Yes, but the AI typically retrieves creatures from lower levels.
As I wrote, this would be okay for level six creatures.
These 100 000 gold enabled me to recruit level six creatures, titans and black dragons (and in addition, available in opposing castles).
Without the 100 000 gold, it would have been harder for me to progress on the map.
It actually made things easier for me, contrary to the AI (opposite effect to the one expected).

2024-03-02 12:05 UTC, oleg-derevenetz commented
Hi @LeHerosInconnu

> I'd like to do tests with these values:
> 
> Easy: -25% gold income
> Normal: no bonus/malus
> Hard: +100% gold income, +2 ore and +2 wood, +1 of each rare resource per day
> Expert: +200% gold income, +4 ore and +4 wood, +2 of each rare resource per day
> Impossible: +300% gold income, +6 ore and +6 wood, +3 of each rare resource per day

OK, I have made the necessary changes.

> And we could also put in place something like this:
> If the AI has over 100 000 gold, it can buy rare resources to recruit its level 6 creatures, with priority given to green/red/black dragons, then titans/giants, then phoenixes and finally cyclops.
>
> And eventually:
> If the AI is short of gold to recruit its creatures (this might eventually happen in certain scenarios), it can sell its resources for gold if they exceed 100 units for ore, 100 units for wood, 50 units for sulfur, 50 units for gems, 50 units for mercury, 50 units for crystal.

As for using the marketplace to buy units, I would suggest not doing it hastily, but coming up with something more versatile. I'm afraid these conditions are only suitable for the Impossible with its huge bonuses, especially "exceed 100 common resources and 50 rare resources", which, judging by the above data on AI resource reserves, is not always possible even for Impossible. They are also hard-coded and do not depend on anything, which in my opinion is also not very good. I propose to postpone this beyond the scope of this PR.

> Yes, but the AI typically retrieves creatures from lower levels.
> As I wrote, this would be okay for level six creatures.

Well, let's try it this way: AI will consider surrender if one of the following conditions is met:

* Hero cannot retreat, but has valuable (non-cursed) artifacts;
* Hero cannot retreat, but is relatively experienced (his level >= 3);
* In the hero's army that will remain after the surrender, there will be at least one level 5/6 unit (I think that level 5 units are also worth saving if possible).

I have made the necessary changes as well.

2024-03-02 15:44 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu
> 
> > I'd like to do tests with these values:
> > Easy: -25% gold income
> > Normal: no bonus/malus
> > Hard: +100% gold income, +2 ore and +2 wood, +1 of each rare resource per day
> > Expert: +200% gold income, +4 ore and +4 wood, +2 of each rare resource per day
> > Impossible: +300% gold income, +6 ore and +6 wood, +3 of each rare resource per day
> 
> OK, I have made the necessary changes.

I'll start testing today.

> > And we could also put in place something like this:
> > If the AI has over 100 000 gold, it can buy rare resources to recruit its level 6 creatures, with priority given to green/red/black dragons, then titans/giants, then phoenixes and finally cyclops.
> > And eventually:
> > If the AI is short of gold to recruit its creatures (this might eventually happen in certain scenarios), it can sell its resources for gold if they exceed 100 units for ore, 100 units for wood, 50 units for sulfur, 50 units for gems, 50 units for mercury, 50 units for crystal.
> 
> As for using the marketplace to buy units, I would suggest not doing it hastily, but coming up with something more versatile. I'm afraid these conditions are only suitable for the Impossible with its huge bonuses, especially "exceed 100 common resources and 50 rare resources", which, judging by the above data on AI resource reserves, is not always possible even on Impossible difficulty. They are also hard-coded and do not depend on anything, which in my opinion is also not very good. I propose to postpone this beyond the scope of this PR.

Okay, let's wait for that.

> > Yes, but the AI typically retrieves creatures from lower levels.
> > As I wrote, this would be okay for level six creatures.
> 
> Well, let's try it this way: AI will consider surrender if one of the following conditions is met:
> 
> * Hero cannot retreat, but has valuable (non-cursed) artifacts;
> * Hero cannot retreat, but is relatively experienced (his level >= 3);
> * In the hero's army that will remain after the surrender, there will be at least one level 5/6 unit (I think that level 5 units are also worth saving if possible).
> 
> I have made the necessary changes as well.

Okay, let's check it with this.

2024-03-05 23:44 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

So, I finished my latest test on impossible difficulty.

In the first game, the green AI player made a decisive attack month 2, week 1, day 6, no way to come back for my side.
I won the second game month 4, week 2, day 7.

</details>
<details>
<summary>Creatures not recruited by AI: (click to expand)</summary>
<br>

Orange AI player's first castle captured, month 2, week 3, day 6 (After orange 01.sav).
Two titans and some halflings not recruited.
![After orange 01](https://github.com/ihhub/fheroes2/assets/43583994/385ca5d9-7bbd-459c-b0a4-a83ac2d7baa0)

Orange AI player's third castle captured, month 2, week 4, day 3 (After orange 03.sav).
One titan and some halflings not recruited.
![After orange 03](https://github.com/ihhub/fheroes2/assets/43583994/6b0627a5-a42a-4819-bf23-e34902cd2c09)

Yellow AI player's first castle recaptured, month 3, week 3, day 2 (After yellow recap 03.sav).
Two black dragons not recruited.
![After yellow recap 03](https://github.com/ihhub/fheroes2/assets/43583994/0aead85f-74d9-44d0-8b0d-663de8b59a4a)

Red AI player's first castle captured, month 3, week 4, day 3 (After red 01.sav).
Gargoyles and centaurs not recruited.
![After red 01](https://github.com/ihhub/fheroes2/assets/43583994/134e90b8-bdfb-408f-ad97-6ee73cfb40f9)
There was no room in the garrison for the creatures (Before red 01.sav).
![Before red 01](https://github.com/ihhub/fheroes2/assets/43583994/4193eb3f-1753-4528-bd72-2bcb8d73c155)

Red AI player's second castle captured, month 4, week 1, day 4 (After red 02.sav).
Gargoyles and centaurs not recruited.
![After red 02](https://github.com/ihhub/fheroes2/assets/43583994/89d8a277-b0b0-45b4-9098-d8ac2f998814)
There was no room in the garrison for the creatures (Before red 02.sav).
![Before red 02](https://github.com/ihhub/fheroes2/assets/43583994/6effa99f-7ab7-493c-be4d-eede6dfde509)

Red AI player's third castle captured, month 4, week 1, day 6 (After red 03.sav).
Only a few unrecruited peasants (no room in the garrison).
![After red 03](https://github.com/ihhub/fheroes2/assets/43583994/fdf7a519-6442-47d6-92db-27e2e76a85f1)

Red AI player's third castle captured, month 4, week 1, day 7 (After red 04.sav).
Only a few unrecruited sprites (no room in the garrison).
![After red 04](https://github.com/ihhub/fheroes2/assets/43583994/5c63a4fc-9547-45aa-9d7f-738dcbab9ed1)

Red AI player's next castle captured, month 4, week 2, day 2 (After red 07.sav).
The hero travelled with the dimension door spell before the attack.
![After red 07](https://github.com/ihhub/fheroes2/assets/43583994/de1ce922-a822-4699-9df4-8bd5b36dcf34)

Red AI player's next castle captured, month 4, week 2, day 2 (After red 08.sav).
The hero travelled with the dimension door spell before the attack.
![After red 08](https://github.com/ihhub/fheroes2/assets/43583994/2ca31eef-79a5-412a-92a0-42a5b82079c2)

Red AI player's next castle captured, month 4, week 2, day 3 (After red 10.sav).
Power liches and vampire lords not recruited.
![After red 10](https://github.com/ihhub/fheroes2/assets/43583994/b6a21026-61f0-4e49-ab28-1530e3046cbf)
There was no room in the garrison for the creatures (Before red 10.sav).
![Before red 10](https://github.com/ihhub/fheroes2/assets/43583994/cc94e143-ea6b-4502-a12f-28ee05413709)

Red AI player's castle recaptured, month 4, week 2, day 5 (After red recap 11.sav)
Only a few unrecruited skeletons (no room in the garrison).
![After red recap 11](https://github.com/ihhub/fheroes2/assets/43583994/771443a4-352c-47a3-9092-c6b0f8786058)

Red AI player's next castle captured, month 4, week 2, day 6 (After red 13.sav).
The hero travelled with the dimension door spell before the attack.
![After red 13](https://github.com/ihhub/fheroes2/assets/43583994/e624e2aa-bd1e-44ce-900b-2819d9916c14)

Red AI player's last castle captured, month 4, week 2, day 7 (After red last castle 15.sav).
No unrecruited creatures.
![After red last castle 15](https://github.com/ihhub/fheroes2/assets/43583994/9fa4bec4-41bb-4ce8-98d9-a972a1172793)

There are only a few level six creatures that have not been recruited by the AI.
This is much better than in the last test done.
Can you show (as above) the quantities of resources and gold of all players from the save files "After orange 01.sav", "After orange 03.sav", "After yellow recap 03.sav" and "Before end game 01.sav" to see what is going on?

</details>
<details>
<summary>AI heroes who surrendered, available at the tavern: (click to expand)</summary>
<br>

Falagar, with a small army, surrendered but not recruited by AI (Falagar available tavern 01.sav).
![Falagar available tavern 01](https://github.com/ihhub/fheroes2/assets/43583994/636ec444-6e87-4820-b9e7-6ec62075c0c9)

Kastore, with a somewhat more substantial army, surrendered but not recruited by AI (Kastore available tavern 01.sav).
![Kastore available tavern 01](https://github.com/ihhub/fheroes2/assets/43583994/26678972-5a9a-4623-bdea-4b822498d63d)
Kastore's army at the start of the combat during which he surrendered (Gold surrender both 05.sav).
![Kastore surrender start army 01](https://github.com/ihhub/fheroes2/assets/43583994/4208f6fa-fefb-4528-b553-6e3fb5b1de77)

Rialdo, with a small army, surrendered but not recruited by AI (Rialdo available tavern 01.sav).
![Rialdo available tavern 01](https://github.com/ihhub/fheroes2/assets/43583994/805762ee-b063-4468-9afa-d92f51f39876)

Ranloo, with a somewhat more substantial army, surrendered but not recruited by AI (Ranloo available tavern 01.sav).
![Ranloo available tavern 01](https://github.com/ihhub/fheroes2/assets/43583994/c253a92d-3360-4f35-8592-eefcd0f7a508)
Ranloo's army at the start of the combat during which he surrendered (Gold surrender both 07.sav).
![Ranloo surrender start army 01](https://github.com/ihhub/fheroes2/assets/43583994/6ac7a1d0-f553-4eb3-8426-83b4376d0a66)

The AI should only make its hero surrender if it is sure of recruiting him.
Otherwise, it makes no sense to pay the opponent and not be able to recruit its hero.
This is a double punishment for the AI, which pays for its hero with its creatures, and it's the human player who benefits from the preserved creatures.
The AI must have a castle and enough gold to be able to recruit the surrendering hero, during the combat in which the hero decides to surrender. And recruit the surrendering hero immediately.

</details>
</details>
<details>
<summary>Gold received for AI heroes who have surrendered: (click to expand)</summary>
<br>

AI hero surrenders in instant combat (Gold surrender 01.sav).
![Gold surrender 01 01](https://github.com/ihhub/fheroes2/assets/43583994/6cca4c9b-5bb1-43f8-82fd-f386db12745c)
At least he could have saved 1 titan (army at the start of the combat).
![Gold surrender 01 02](https://github.com/ihhub/fheroes2/assets/43583994/8941f301-1eb8-40c6-bd00-e76c87dd81d9)
I decide to engage him in combat and prevent him from surrendering.
Accepting the gold, in the end, would have been more interesting.
![Gold surrender 01 03](https://github.com/ihhub/fheroes2/assets/43583994/3d677451-2bd1-4e70-a47a-796c4f0ffc52)

AI hero surrenders in instant combat (Gold surrender both 02.sav).
![Gold surrender instant 02](https://github.com/ihhub/fheroes2/assets/43583994/0ffa0efb-0f7e-47c3-82fd-73a3c2e197d0)
In this case, it saves 1 titan (army at the start of the combat).
![Gold surrender instant check 02](https://github.com/ihhub/fheroes2/assets/43583994/be89b9eb-232f-41e7-887d-1a6033ea6c01)
AI hero surrenders in combat (Gold surrender both 02.sav).
In this case, it saves 2 giants.
Not really a good deal if he upgrades them later.
![Gold surrender combat 02](https://github.com/ihhub/fheroes2/assets/43583994/81944252-fced-4d3b-807a-c25dd5a0dc4e)

Also, it's easy to abuse the system by doing just enough damage to opposing troops, but without decimating low level creatures too much, to encourage the opposing hero to end the combat in order to get more gold when he surrenders.
In the example, without seeking to optimize abu [...]

2024-03-06 10:08 UTC, oleg-derevenetz commented
> Can you show (as above) the quantities of resources and gold of all players from the save files "After orange 01.sav", "After orange 03.sav", "After yellow recap 03.sav" and "Before end game 01.sav" to see what is going on?

After orange 01.sav:

```
06.03.2024 11:37:34: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 89, wood: 140, mercury: 15, sulfur: 94, crystal: 47, gems: 99, gold: 143615
06.03.2024 11:37:34: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 26, wood: 90, mercury: 35, sulfur: 14, crystal: 5, gems: 24, gold: 279899
06.03.2024 11:37:34: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 28, wood: 30, mercury: 31, sulfur: 3, crystal: 15, gems: 18, gold: 149088
06.03.2024 11:37:34: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 33, wood: 0, mercury: 0, sulfur: 0, crystal: 4, gems: 0, gold: 19895
06.03.2024 11:37:34: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 82, wood: 139, mercury: 140, sulfur: 136, crystal: 40, gems: 138, gold: 184468
```

Perhaps the orange player was actively building castles or something like that. He has all the castles built to the maximum at this point (at least in regard to dwellings).

After orange 03.sav:

```
06.03.2024 11:47:40: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 81, wood: 154, mercury: 1, sulfur: 107, crystal: 59, gems: 105, gold: 129815
06.03.2024 11:47:40: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 46, wood: 119, mercury: 13, sulfur: 0, crystal: 0, gems: 13, gold: 353377
06.03.2024 11:47:40: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 32, wood: 47, mercury: 34, sulfur: 1, crystal: 9, gems: 24, gold: 126068
06.03.2024 11:47:40: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 41, wood: 13, mercury: 4, sulfur: 10, crystal: 10, gems: 0, gold: 6581
06.03.2024 11:47:40: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 94, wood: 155, mercury: 150, sulfur: 144, crystal: 48, gems: 148, gold: 189228
```

After yellow recap 03.sav:

```
06.03.2024 11:54:23: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 223, wood: 270, mercury: 22, sulfur: 139, crystal: 91, gems: 157, gold: 215767
06.03.2024 11:54:23: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 269, wood: 271, mercury: 129, sulfur: 97, crystal: 52, gems: 91, gold: 1077503
06.03.2024 11:54:23: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 75, wood: 120, mercury: 102, sulfur: 0, crystal: 46, gems: 71, gold: 297740
06.03.2024 11:54:23: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 140, wood: 85, mercury: 17, sulfur: 55, crystal: 42, gems: 36, gold: 209383
06.03.2024 11:54:23: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 94, wood: 155, mercury: 150, sulfur: 144, crystal: 48, gems: 148, gold: 189228
```

Before end game 01.sav:

```
06.03.2024 11:59:44: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 413, wood: 450, mercury: 73, sulfur: 196, crystal: 138, gems: 223, gold: 343372
06.03.2024 11:59:44: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 406, wood: 207, mercury: 179, sulfur: 158, crystal: 5, gems: 132, gold: 1716931
06.03.2024 11:59:44: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 147, wood: 194, mercury: 152, sulfur: 47, crystal: 89, gems: 115, gold: 372290
06.03.2024 11:59:44: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 260, wood: 241, mercury: 71, sulfur: 115, crystal: 122, gems: 96, gold: 269770
06.03.2024 11:59:44: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 94, wood: 155, mercury: 150, sulfur: 144, crystal: 48, gems: 148, gold: 189228
```

> Would it be possible to make a test with the same bonus values in gold and resources for AI, but disabling the ability for AI heroes to surrender?

I suggest testing the variant where surrender is possible only if the hero cannot retreat (i.e. during siege), and the task of saving the army isn't taken into account in any case (i.e. surrender or retreat are considered only if hero has valuable artifacts or is relatively experienced). I just introduced the corresponding changes in this PR.

2024-03-06 16:06 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

> > Can you show (as above) the quantities of resources and gold of all players from the save files "After orange 01.sav", "After orange 03.sav", "After yellow recap 03.sav" and "Before end game 01.sav" to see what is going on?
> 
> After orange 01.sav:
> 
> ```
> 06.03.2024 11:37:34: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 89, wood: 140, mercury: 15, sulfur: 94, crystal: 47, gems: 99, gold: 143615
> 06.03.2024 11:37:34: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 26, wood: 90, mercury: 35, sulfur: 14, crystal: 5, gems: 24, gold: 279899
> 06.03.2024 11:37:34: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 28, wood: 30, mercury: 31, sulfur: 3, crystal: 15, gems: 18, gold: 149088
> 06.03.2024 11:37:34: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 33, wood: 0, mercury: 0, sulfur: 0, crystal: 4, gems: 0, gold: 19895
> 06.03.2024 11:37:34: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 82, wood: 139, mercury: 140, sulfur: 136, crystal: 40, gems: 138, gold: 184468
> ```
> 
> Perhaps the orange player was actively building castles or something like that. He has all the castles built to the maximum at this point (at least in regard to dwellings).
> 
> After orange 03.sav:
> 
> ```
> 06.03.2024 11:47:40: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 81, wood: 154, mercury: 1, sulfur: 107, crystal: 59, gems: 105, gold: 129815
> 06.03.2024 11:47:40: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 46, wood: 119, mercury: 13, sulfur: 0, crystal: 0, gems: 13, gold: 353377
> 06.03.2024 11:47:40: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 32, wood: 47, mercury: 34, sulfur: 1, crystal: 9, gems: 24, gold: 126068
> 06.03.2024 11:47:40: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 41, wood: 13, mercury: 4, sulfur: 10, crystal: 10, gems: 0, gold: 6581
> 06.03.2024 11:47:40: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 94, wood: 155, mercury: 150, sulfur: 144, crystal: 48, gems: 148, gold: 189228
> ```
> 
> After yellow recap 03.sav:
> 
> ```
> 06.03.2024 11:54:23: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 223, wood: 270, mercury: 22, sulfur: 139, crystal: 91, gems: 157, gold: 215767
> 06.03.2024 11:54:23: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 269, wood: 271, mercury: 129, sulfur: 97, crystal: 52, gems: 91, gold: 1077503
> 06.03.2024 11:54:23: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 75, wood: 120, mercury: 102, sulfur: 0, crystal: 46, gems: 71, gold: 297740
> 06.03.2024 11:54:23: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 140, wood: 85, mercury: 17, sulfur: 55, crystal: 42, gems: 36, gold: 209383
> 06.03.2024 11:54:23: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 94, wood: 155, mercury: 150, sulfur: 144, crystal: 48, gems: 148, gold: 189228
> ```
> 
> Before end game 01.sav:
> 
> ```
> 06.03.2024 11:59:44: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 413, wood: 450, mercury: 73, sulfur: 196, crystal: 138, gems: 223, gold: 343372
> 06.03.2024 11:59:44: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 406, wood: 207, mercury: 179, sulfur: 158, crystal: 5, gems: 132, gold: 1716931
> 06.03.2024 11:59:44: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 147, wood: 194, mercury: 152, sulfur: 47, crystal: 89, gems: 115, gold: 372290
> 06.03.2024 11:59:44: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 260, wood: 241, mercury: 71, sulfur: 115, crystal: 122, gems: 96, gold: 269770
> 06.03.2024 11:59:44: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 94, wood: 155, mercury: 150, sulfur: 144, crystal: 48, gems: 148, gold: 189228
> ```

Okay, thanks.

> > Would it be possible to make a test with the same bonus values in gold and resources for AI, but disabling the ability for AI heroes to surrender?
> 
> I suggest testing the variant where surrender is possible only if the hero cannot retreat (i.e. during siege), and the task of saving the army isn't taken into account in any case (i.e. surrender or retreat are considered only if hero has valuable artifacts or is relatively experienced). I just introduced the corresponding changes in this PR.

Okay, I'll do a test with this on the same scenario.

2024-03-12 21:25 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

So, I finished my testing on the impossible difficulty with the latest change.

In the first game, I can't take back my castle conquered by the green AI player month 1, week 4, day 3, no way to come back for my side.
I won the second game month 4, week 4, day 3.
It was more difficult to recruit titans (without the gold from opposing surrendered heroes) and my progress was slower at the start of my conquest of opposing players.

<details>
<summary>Creatures not recruited by AI: (click to expand)</summary>
<br>

Green AI player's castle captured (my initial castle), month 1, week 4, day 5 (After green 01.sav).
Paladins not recruited. This is acceptable (not upgraded creatures, and "rather weak" for a level six).
![After green 01](https://github.com/ihhub/fheroes2/assets/43583994/6312d1ee-1518-4cd6-8bdc-2e335a49c211)

Orange AI player's castle captured, month 2, week 4, day 4 (After orange 02.sav).
Two Titans not recruited. It's almost acceptable.
![After orange 02](https://github.com/ihhub/fheroes2/assets/43583994/460dc7ce-253f-46b3-bc84-fd2fff957b1d)

Orange AI player's castle captured, month 2, week 4, day 5 (After orange 03.sav).
Three Titans not recruited. It's getting to be a lot.
![After orange 03](https://github.com/ihhub/fheroes2/assets/43583994/68f9243b-1cc8-45e7-b4fc-0753aaf45778)

Orange AI player's castle recaptured, month 3, week 2, day 2 (After orange recap 04.sav).
Three Titans not recruited. It's continuing to be a lot.
![After orange recap 04](https://github.com/ihhub/fheroes2/assets/43583994/ed7645ec-4dec-4dce-9ec9-acf6290e4565)

Orange AI player's castle captured, month 3, week 2, day 5 (After orange 05.sav).
Six Titans not recruited. It's too many.
![After orange 05](https://github.com/ihhub/fheroes2/assets/43583994/8e8c100b-58aa-41c8-b645-3da275bc0296)

The month of the plague arrives, month 4, week 1, day 1 (Before plague 01.sav).
This gives the economy a "breathing space", as no creatures are generated and the number of those available is halved.
![Month of the plague 01](https://github.com/ihhub/fheroes2/assets/43583994/2135e7da-2d05-455a-b70e-b3dcedcf8f5e)

There are still some level six creatures not recruited by the AI, and the month of the plague (no creatures generated) has certainly also had an effect on this for the rest of the scenario.
Can you show the quantities of resources and gold of all players from the save files "After green 01.sav", "After orange 02.sav", "After orange 03.sav", "After orange recap 04.sav", "After orange 05.sav", "Before plague 01.sav" and "Before end game 07.sav"?
I'll look at the values and propose a change based on that.

Certainly like this:
- Easy: -25% gold income
- Normal: no bonus/malus
- Hard: +100% gold income, +2 ore and +2 wood, +1 of each rare resource per day
- Expert: +200% gold income, +4 ore and +4 wood, +2 of each rare resource per day
- Impossible: +400% gold income, +8 ore and +8 wood, +4 of each rare resource per day

It should be noted that the wizard's castle requires large quantities of gems to build (especially when there are several, as in this scenario), and upgrading the giant to titan doesn't help matters.
The same problem can also be noted for the warlock's castle with sulfur (not observed in this test but it is perhaps due to the month of the plague).

</details>
<details>
<summary>Gold received for AI heroes who have surrendered: (click to expand)</summary>
<br>

Gold received for AI heroes.
![Gold surrender both 01](https://github.com/ihhub/fheroes2/assets/43583994/eba02ecf-9310-43f2-ac58-b029fdbd8337)
![Gold surrender both 02](https://github.com/ihhub/fheroes2/assets/43583994/79f2c464-d618-43ec-95c6-a9cf544a8db5)
![Gold surrender 03](https://github.com/ihhub/fheroes2/assets/43583994/2d2bc531-d5a4-4177-9243-affd2ba4b5b5)
![Gold surrender both 04](https://github.com/ihhub/fheroes2/assets/43583994/a55a9298-fcd7-4beb-8ce9-dd8623a2b75e)
![Gold surrender both 05](https://github.com/ihhub/fheroes2/assets/43583994/51d73aa9-86bb-4110-8f70-f4e662bd6467)
![Gold surrender both 07](https://github.com/ihhub/fheroes2/assets/43583994/9b5a7a7e-f8ce-4d23-9012-994b1fb4b354)
![Gold surrender 08](https://github.com/ihhub/fheroes2/assets/43583994/ad9231da-5bf9-4d98-b9d9-0e2d35c1c947)

In this case, the hero does not surrender in instant combat, but surrenders if the combat is played (Gold surrender 06.sav).
Is this normal with the change made, or is it due to a different way of working?
![No surrender instant 06](https://github.com/ihhub/fheroes2/assets/43583994/6b44af69-f266-470f-9450-ac1980f02730)
![Gold surrender 06](https://github.com/ihhub/fheroes2/assets/43583994/4f472920-0009-4a3b-a6e4-1882526610fc)

The amount of gold given by the AI for its surrendered heroes is reduced compared with previous tests, but it's still more than 15,000 gold.

I think the hero should be allowed to surrender only when his primary skill points total is at least 10 (excluding artifacts).
It doesn't have to be according to his level, because a hero can have visited places on the adventure map that give points in his primary skills without the hero necessarily being of a high level.
Also, for this case, the hero should not be allowed to surrender if the amount of gold is equal to or greater than 5000 gold (or maybe even just 4000 gold) (above this amount, too much gold is given to the opponent).
These conditions are met in all the examples presented above.
Of course, this surrendered hero should be recruited immediately by the AI.
For artifacts, each case is specific. This can be evaluated later.

</details>

Here are the save files:
[Dominion impossible lose 07.zip](https://github.com/ihhub/fheroes2/files/14578641/Dominion.impossible.lose.07.zip)
[AI creatures and other 07.zip](https://github.com/ihhub/fheroes2/files/14578642/AI.creatures.and.other.07.zip)
[AI gold surrender 07 01.zip](https://github.com/ihhub/fheroes2/files/14578635/AI.gold.surrender.07.01.zip)

2024-03-13 11:55 UTC, oleg-derevenetz commented
Hi @LeHerosInconnu

> In this case, the hero does not surrender in instant combat, but surrenders if the combat is played (Gold surrender 06.sav).
Is this normal with the change made, or is it due to a different way of working?

If we are talking about the fact that the results of instant and other types of automatic battle differ, then according to the results of my tests this is not the case:

https://github.com/ihhub/fheroes2/assets/32623900/8ee1b95e-cf52-4283-aec1-d111e250bc5d

And if we are talking about the fact that the results of the manually conducted battle (that is, with a different actions / order of action) are different, then this is quite possible. For example, at the time of AI last turn, it has fewer troops left (or you have more troops - in fact, you have, since you have extra Titan), and AI decided to surrender, since currently the decision to surrender is determined by comparing the strength of the remaining troops on each side.

> Can you show the quantities of resources and gold of all players from the save files "After green 01.sav", "After orange 02.sav", "After orange 03.sav", "After orange recap 04.sav", "After orange 05.sav", "Before plague 01.sav" and "Before end game 07.sav"?
I'll look at the values and propose a change based on that.

After green 01.sav:

```
13.03.2024 13:57:00: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 72, wood: 90, mercury: 38, sulfur: 65, crystal: 31, gems: 67, gold: 105526
13.03.2024 13:57:00: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 53, wood: 6, mercury: 38, sulfur: 17, crystal: 29, gems: 55, gold: 52958
13.03.2024 13:57:00: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 8, wood: 16, mercury: 9, sulfur: 10, crystal: 10, gems: 2, gold: 35457
13.03.2024 13:57:00: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 3, wood: 3, mercury: 7, sulfur: 7, crystal: 6, gems: 2, gold: 16
13.03.2024 13:57:00: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 36, wood: 12, mercury: 25, sulfur: 26, crystal: 9, gems: 29, gold: 19916
```

It's not like green AI doesn't have money or resources. Maybe there was no place in the army?

After orange 02.sav:

```
13.03.2024 14:02:28: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 103, wood: 165, mercury: 4, sulfur: 163, crystal: 62, gems: 124, gold: 435636
13.03.2024 14:02:28: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 125, wood: 14, mercury: 43, sulfur: 18, crystal: 0, gems: 48, gold: 258809
13.03.2024 14:02:28: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 18, wood: 15, mercury: 28, sulfur: 1, crystal: 24, gems: 22, gold: 113599
13.03.2024 14:02:28: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 17, wood: 4, mercury: 0, sulfur: 11, crystal: 6, gems: 0, gold: 7972
13.03.2024 14:02:28: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 187, wood: 193, mercury: 120, sulfur: 74, crystal: 23, gems: 108, gold: 203601
```

After orange 03.sav:

```
13.03.2024 14:03:16: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 112, wood: 173, mercury: 1, sulfur: 167, crystal: 65, gems: 128, gold: 447636
13.03.2024 14:03:16: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 134, wood: 22, mercury: 48, sulfur: 22, crystal: 0, gems: 52, gold: 290559
13.03.2024 14:03:16: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 21, wood: 15, mercury: 15, sulfur: 0, crystal: 20, gems: 23, gold: 136130
13.03.2024 14:03:16: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 20, wood: 0, mercury: 0, sulfur: 11, crystal: 5, gems: 0, gold: 36497
13.03.2024 14:03:16: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 193, wood: 201, mercury: 125, sulfur: 78, crystal: 27, gems: 113, gold: 208601
```

After orange recap 04.sav:

```
13.03.2024 14:04:01: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 167, wood: 176, mercury: 18, sulfur: 211, crystal: 68, gems: 172, gold: 472206
13.03.2024 14:04:01: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 288, wood: 127, mercury: 92, sulfur: 40, crystal: 38, gems: 94, gold: 496019
13.03.2024 14:04:01: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 59, wood: 77, mercury: 26, sulfur: 21, crystal: 17, gems: 25, gold: 306310
13.03.2024 14:04:01: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 37, wood: 6, mercury: 0, sulfur: 11, crystal: 8, gems: 0, gold: 27
13.03.2024 14:04:01: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 259, wood: 274, mercury: 180, sulfur: 122, crystal: 63, gems: 168, gold: 232161
```

After orange 05.sav:

```
13.03.2024 14:05:11: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 197, wood: 200, mercury: 27, sulfur: 223, crystal: 77, gems: 186, gold: 499901
13.03.2024 14:05:11: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 332, wood: 163, mercury: 123, sulfur: 57, crystal: 53, gems: 110, gold: 515359
13.03.2024 14:05:11: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 28, wood: 2, mercury: 41, sulfur: 41, crystal: 0, gems: 22, gold: 395288
13.03.2024 14:05:11: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 27, wood: 14, mercury: 0, sulfur: 12, crystal: 6, gems: 0, gold: 8929
13.03.2024 14:05:11: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 277, wood: 295, mercury: 195, sulfur: 134, crystal: 75, gems: 183, gold: 249461
```

Before plague 01.sav:

```
13.03.2024 14:06:08: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 322, wood: 279, mercury: 1, sulfur: 244, crystal: 73, gems: 203, gold: 719991
13.03.2024 14:06:08: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 596, wood: 301, mercury: 203, sulfur: 127, crystal: 117, gems: 181, gold: 763009
13.03.2024 14:06:08: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 5, wood: 25, mercury: 39, sulfur: 5, crystal: 30, gems: 27, gold: 863043
13.03.2024 14:06:08: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 57, wood: 51, mercury: 30, sulfur: 34, crystal: 24, gems: 6, gold: 17308
13.03.2024 14:06:08: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 373, wood: 402, mercury: 275, sulfur: 198, crystal: 131, gems: 263, gold: 287401
```

Before end game 07.sav:

```
13.03.2024 14:07:04: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 494, wood: 408, mercury: 19, sulfur: 311, crystal: 107, gems: 258, gold: 1046711
13.03.2024 14:07:04: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 982, wood: 483, mercury: 330, sulfur: 224, crystal: 231, gems: 310, gold: 1160358
13.03.2024 14:07:04: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 72, wood: 225, mercury: 121, sulfur: 79, crystal: 64, gems: 100, gold: 1351972
13.03.2024 14:07:04: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 57, wood: 51, mercury: 30, sulfur: 34, crystal: 24, gems: 6, gold: 17308
13.03.2024 14:07:04: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 499, wood: 522, mercury: 358, sulfur: 268, crystal: 190, gems: 363, gold: 334582
```

> I think the hero should be allowed to surrender only when his primary skill points total is at least 10 (excluding artifacts).
It doesn't have to be according to his level, because a hero can have visited places on the adventure map that give points in his primary skills without the hero necessarily being of a high level.

Sounds reasonable, I have made the necessary changes to this PR.

> Of course, this surrendered hero should be recruited immediately by the AI.

Currently, if hero has valuable artifacts, it will surrender even if it is the last battle of the corresponding AI player. The point is not to make life easier for the victorious opponent, especially when it comes to maps with alliances. If he does not surrender, the enemy hero will receive all the artifacts immediately, and if he surrenders, it is unknown when the enemy player will be able to hire this hero (and whether he will be able to at all).

> Certainly like this:
> 
> * Easy: -25% gold income
> * Normal: no bonus/malus
> * Hard: +100% gold income, +2 ore and +2 wood, +1 of each rare resource per day
> * Expert: +200% gold income, +4 ore and +4 wood, +2 of each rare resource per day
> * Impossible: +400% gold income, +8 ore and +8 wood, +4 of each rare resource p [...]

2024-03-13 20:55 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu
> 
> > In this case, the hero does not surrender in instant combat, but surrenders if the combat is played (Gold surrender 06.sav).
> > Is this normal with the change made, or is it due to a different way of working?
> 
> If we are talking about the fact that the results of instant and other types of automatic battle differ, then according to the results of my tests this is not the case:
> 
> https://github.com/ihhub/fheroes2/assets/32623900/8ee1b95e-cf52-4283-aec1-d111e250bc5d 
> And if we are talking about the fact that the results of the manually conducted battle (that is, with a different actions / order of action) are different, then this is quite possible. For example, at the time of AI last turn, it has fewer troops left (or you have more troops - in fact, you have, since you have extra Titan), and AI decided to surrender, since currently the decision to surrender is determined by comparing the strength of the remaining troops on each side.

Yes, I see, the AI hero surrenders during the combat in my example because there's a difference in strength between the armies due to the extra titan in one case compared to the other.

> > Can you show the quantities of resources and gold of all players from the save files "After green 01.sav", "After orange 02.sav", "After orange 03.sav", "After orange recap 04.sav", "After orange 05.sav", "Before plague 01.sav" and "Before end game 07.sav"?
> > I'll look at the values and propose a change based on that.
> 
> After green 01.sav:
> 
> ```
> 13.03.2024 13:57:00: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 72, wood: 90, mercury: 38, sulfur: 65, crystal: 31, gems: 67, gold: 105526
> 13.03.2024 13:57:00: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 53, wood: 6, mercury: 38, sulfur: 17, crystal: 29, gems: 55, gold: 52958
> 13.03.2024 13:57:00: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 8, wood: 16, mercury: 9, sulfur: 10, crystal: 10, gems: 2, gold: 35457
> 13.03.2024 13:57:00: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 3, wood: 3, mercury: 7, sulfur: 7, crystal: 6, gems: 2, gold: 16
> 13.03.2024 13:57:00: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 36, wood: 12, mercury: 25, sulfur: 26, crystal: 9, gems: 29, gold: 19916
> ```
> 
> It's not like green AI doesn't have money or resources. Maybe there was no place in the army?

The AI hero defender's army could have included the two paladins if the two peasant troops had been combined (Dominion_0026a.sav).
![Dominion_0026a](https://github.com/ihhub/fheroes2/assets/43583994/3033b948-cfc3-46e4-a4fe-e56514b95260)

Here is the save file:
[Dominion_0026a.zip](https://github.com/ihhub/fheroes2/files/14593793/Dominion_0026a.zip)

> After orange 02.sav:
> 
> ```
> 13.03.2024 14:02:28: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 103, wood: 165, mercury: 4, sulfur: 163, crystal: 62, gems: 124, gold: 435636
> 13.03.2024 14:02:28: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 125, wood: 14, mercury: 43, sulfur: 18, crystal: 0, gems: 48, gold: 258809
> 13.03.2024 14:02:28: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 18, wood: 15, mercury: 28, sulfur: 1, crystal: 24, gems: 22, gold: 113599
> 13.03.2024 14:02:28: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 17, wood: 4, mercury: 0, sulfur: 11, crystal: 6, gems: 0, gold: 7972
> 13.03.2024 14:02:28: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 187, wood: 193, mercury: 120, sulfur: 74, crystal: 23, gems: 108, gold: 203601
> ```
> 
> After orange 03.sav:
> 
> ```
> 13.03.2024 14:03:16: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 112, wood: 173, mercury: 1, sulfur: 167, crystal: 65, gems: 128, gold: 447636
> 13.03.2024 14:03:16: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 134, wood: 22, mercury: 48, sulfur: 22, crystal: 0, gems: 52, gold: 290559
> 13.03.2024 14:03:16: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 21, wood: 15, mercury: 15, sulfur: 0, crystal: 20, gems: 23, gold: 136130
> 13.03.2024 14:03:16: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 20, wood: 0, mercury: 0, sulfur: 11, crystal: 5, gems: 0, gold: 36497
> 13.03.2024 14:03:16: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 193, wood: 201, mercury: 125, sulfur: 78, crystal: 27, gems: 113, gold: 208601
> ```
> 
> After orange recap 04.sav:
> 
> ```
> 13.03.2024 14:04:01: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 167, wood: 176, mercury: 18, sulfur: 211, crystal: 68, gems: 172, gold: 472206
> 13.03.2024 14:04:01: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 288, wood: 127, mercury: 92, sulfur: 40, crystal: 38, gems: 94, gold: 496019
> 13.03.2024 14:04:01: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 59, wood: 77, mercury: 26, sulfur: 21, crystal: 17, gems: 25, gold: 306310
> 13.03.2024 14:04:01: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 37, wood: 6, mercury: 0, sulfur: 11, crystal: 8, gems: 0, gold: 27
> 13.03.2024 14:04:01: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 259, wood: 274, mercury: 180, sulfur: 122, crystal: 63, gems: 168, gold: 232161
> ```
> 
> After orange 05.sav:
> 
> ```
> 13.03.2024 14:05:11: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 197, wood: 200, mercury: 27, sulfur: 223, crystal: 77, gems: 186, gold: 499901
> 13.03.2024 14:05:11: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 332, wood: 163, mercury: 123, sulfur: 57, crystal: 53, gems: 110, gold: 515359
> 13.03.2024 14:05:11: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 28, wood: 2, mercury: 41, sulfur: 41, crystal: 0, gems: 22, gold: 395288
> 13.03.2024 14:05:11: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 27, wood: 14, mercury: 0, sulfur: 12, crystal: 6, gems: 0, gold: 8929
> 13.03.2024 14:05:11: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 277, wood: 295, mercury: 195, sulfur: 134, crystal: 75, gems: 183, gold: 249461
> ```
> 
> Before plague 01.sav:
> 
> ```
> 13.03.2024 14:06:08: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 322, wood: 279, mercury: 1, sulfur: 244, crystal: 73, gems: 203, gold: 719991
> 13.03.2024 14:06:08: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 596, wood: 301, mercury: 203, sulfur: 127, crystal: 117, gems: 181, gold: 763009
> 13.03.2024 14:06:08: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 5, wood: 25, mercury: 39, sulfur: 5, crystal: 30, gems: 27, gold: 863043
> 13.03.2024 14:06:08: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 57, wood: 51, mercury: 30, sulfur: 34, crystal: 24, gems: 6, gold: 17308
> 13.03.2024 14:06:08: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 373, wood: 402, mercury: 275, sulfur: 198, crystal: 131, gems: 263, gold: 287401
> ```
> 
> Before end game 07.sav:
> 
> ```
> 13.03.2024 14:07:04: [DBG_GAME]	Game::Load:  Color: Green, funds: ore: 494, wood: 408, mercury: 19, sulfur: 311, crystal: 107, gems: 258, gold: 1046711
> 13.03.2024 14:07:04: [DBG_GAME]	Game::Load:  Color: Red, funds: ore: 982, wood: 483, mercury: 330, sulfur: 224, crystal: 231, gems: 310, gold: 1160358
> 13.03.2024 14:07:04: [DBG_GAME]	Game::Load:  Color: Yellow, funds: ore: 72, wood: 225, mercury: 121, sulfur: 79, crystal: 64, gems: 100, gold: 1351972
> 13.03.2024 14:07:04: [DBG_GAME]	Game::Load:  Color: Orange, funds: ore: 57, wood: 51, mercury: 30, sulfur: 34, crystal: 24, gems: 6, gold: 17308
> 13.03.2024 14:07:04: [DBG_GAME]	Game::Load:  Color: Purple, funds: ore: 499, wood: 522, mercury: 358, sulfur: 268, crystal: 190, gems: 363, gold: 334582
> ```

Okay, I see, orange is always short in gems and often in gold. Thanks.

> > I think the hero should be allowed to surrender only when his primary skill points total is at least 10 (excluding artifacts).
> > It doesn't have to be according to his level, because a hero can have visited places on the adventure map that give points in his primary skills without the hero necessarily being of a high level.
> 
> Sounds reasonable, I have made the necessary changes to this PR.

Okay.

> > Of course, this surrendered hero sho [...]

2024-03-13 21:15 UTC, oleg-derevenetz commented
> The AI hero defender's army could have included the two paladins if the two peasant troops had been combined

Yeah, it's not very clear why the AI here did not buy out these two crusaders. In your save file, AI sees this hero, but this save file, as far as I understand, was not made at the beginning of the turn (and not at the end of the previous one). It's not clear if the AI saw this hero on the AI turn.

> For each type of castle owned by each AI player:
> 
> * Castle of the knight: +1 unit of crystal per day
> * Castle of the barbarian: +1 unit of crystal per day
> * Castle of the sorceress: +1 unit of mercury per day
> * Castle of the necromancer: +1 unit of sulfur per day
> * Castle of the wizard: +1 unit of gems per day
> * Castle of the warlock: +1 unit of sulfur per day

Yes, it will be possible to do something like this, but also we need to think about what to do with easier difficulties, if we will use "per-castle" resource bonuses.

2024-03-13 21:25 UTC, oleg-derevenetz commented
Hi @ihhub I know there's not much time left before the release, and I don't know if you want to do additional testing for this PR :)

2024-03-13 22:07 UTC, LeHerosInconnu commented
@oleg-derevenetz,

> > The AI hero defender's army could have included the two paladins if the two peasant troops had been combined
> 
> Yeah, it's not very clear why the AI here did not buy out these two crusaders. In your save file, AI sees this hero, but this save file, as far as I understand, was not made at the beginning of the turn (and not at the end of the previous one). It's not entirely clear if the AI saw this hero during the previous AI turn (when it could make a decision about hiring).

The AI has built the cathedral but has not recruited the creatures available as the result of the cathedral's construction (this after the AI had conquered the city just before).
Here are the save files (end of previous turn and start of new turn):
[End previous turn and start new turn 0026 01.zip](https://github.com/ihhub/fheroes2/files/14594355/End.previous.turn.and.start.new.turn.0026.01.zip)

> > For each type of castle owned by each AI player:
> > 
> > * Castle of the knight: +1 unit of crystal per day
> > * Castle of the barbarian: +1 unit of crystal per day
> > * Castle of the sorceress: +1 unit of mercury per day
> > * Castle of the necromancer: +1 unit of sulfur per day
> > * Castle of the wizard: +1 unit of gems per day
> > * Castle of the warlock: +1 unit of sulfur per day
> 
> Yes, it will be possible to do something like this, but also we need to think about what to do with easier difficulties, if we will use "per-castle" resource bonuses.

This could also be applied to the hard and expert difficulties, as in any case the problem of lack of resources for level six creatures would also be present in these difficulties.
Now we'd have to find out what level of difficulty of the game itself is desirable for the player for each difficulty level. :D
This, of course, would require more testing.

2024-03-13 22:42 UTC, oleg-derevenetz commented
> this after the AI had conquered the city just before

Ah, now it's more clear. The problem was that the threat assessment for castles was made at the beginning of the turn, and was not updated at the end of the turn (that is, the AI was not aware of the degree of threat to the newly captured castles). I've made an effort to fix it, and now threat evaluation is made once again at the end of the turn if new castles were captured. By the way, the current logic is that AI will not build new dwellings in castles, which, as it understands, are under threat. It will hire the available troops there instead and build defensive structures (if possible). So now after Dominion_0025c.sav AI will build turret instead of Cathedral.

2024-03-15 15:47 UTC, ihhub commented
Hi @oleg-derevenetz , give me some time to read through the whole conversation and the code here and in the discussion topic as I missed a lot of things being busy with some problems.

2024-03-15 15:48 UTC, oleg-derevenetz commented
> Hi @oleg-derevenetz , give me some time to read through the whole conversation and the code here and in the discussion topic as I missed a lot of things being busy with some problems.

Yes, sure :) Thank you!

2024-03-16 02:04 UTC, ihhub reviewed
Hi @oleg-derevenetz , I left few questions here. Could you please clarify them?

2024-03-16 02:04 UTC, ihhub commented on src/fheroes2/kingdom/kingdom.cpp
> +    if ( isControlAI() ) {
Essentially, we removed all growth bonuses but adjusted Gold income and added resource income for AI. Is it correct?

2024-03-16 02:04 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +                const Force & force = arena.getForce( _myColor );
Can you please briefly explain the rationale behind these changes for hero surrender?

2024-03-16 02:04 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +            castlesInDanger = findCastlesInDanger( kingdom );
Was it a bug not having this code?

2024-03-16 08:59 UTC, oleg-derevenetz commented on src/fheroes2/kingdom/kingdom.cpp
> +    if ( isControlAI() ) {
Hi @ihhub, yes.

2024-03-16 08:59 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +                const Force & force = arena.getForce( _myColor );
@ihhub the rationale was that @LeHerosInconnu believes that AI gave too much money to a human player when surrendering, therefore, the conditions for surrender were tightened. Now surrender occurs only if the hero cannot retreat (i.e. he never surrenders in the "open field"), and the task of saving the army is not set: the hero surrenders only if he is sufficiently "pumped" or has valuable artifacts.

2024-03-16 08:59 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_kingdom.cpp
> +            castlesInDanger = findCastlesInDanger( kingdom );
@ihhub Yes, sort of. Please see https://github.com/ihhub/fheroes2/pull/8402#issuecomment-1995849275, https://github.com/ihhub/fheroes2/pull/8402#issuecomment-1995969009 and https://github.com/ihhub/fheroes2/pull/8402#issuecomment-1996014486 for details.

2024-03-16 13:03 UTC, ihhub commented
Hi @oleg-derevenetz , let's merge it after the release as it is risky to do on the same day. Also, @Branikolog has some concerns about the logic.

2024-03-16 13:54 UTC, oleg-derevenetz commented
Hi @ihhub

> let's merge it after the release as it is risky to do on the same day. Also, @Branikolog has some concerns about the logic.

Well, if that's the case, then in the meantime I'll implement another suggestion from @LeHerosInconnu, namely this:

> For each type of castle owned by each AI player:
> 
> * Castle of the knight: +1 unit of crystal per day
> * Castle of the barbarian: +1 unit of crystal per day
> * Castle of the sorceress: +1 unit of mercury per day
> * Castle of the necromancer: +1 unit of sulfur per day
> * Castle of the wizard: +1 unit of gems per day
> * Castle of the warlock: +1 unit of sulfur per day

Hi @LeHerosInconnu you are free to test this if you want.

2024-03-16 13:56 UTC, ihhub commented
@oleg-derevenetz , my apologies for this delay as I am the one who delayed the review at first place.

2024-03-16 14:02 UTC, oleg-derevenetz commented
Hi @ihhub

> my apologies for this delay as I am the one who delayed the review at first place.

Maybe it's for the best - there will be more complete tuning in the next release :)

2024-03-16 17:55 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

> Hi @ihhub
> 
> > let's merge it after the release as it is risky to do on the same day. Also, @Branikolog has some concerns about the logic.
> 
> Well, if that's the case, then in the meantime I'll implement another suggestion from @LeHerosInconnu, namely this:
> 
> > For each type of castle owned by each AI player:
> > 
> > * Castle of the knight: +1 unit of crystal per day
> > * Castle of the barbarian: +1 unit of crystal per day
> > * Castle of the sorceress: +1 unit of mercury per day
> > * Castle of the necromancer: +1 unit of sulfur per day
> > * Castle of the wizard: +1 unit of gems per day
> > * Castle of the warlock: +1 unit of sulfur per day
> 
> for Expert and Impossible difficulties.
> 
> Hi @LeHerosInconnu you are free to test this if you want.

Okay, I'll test this once I've reported some issues experienced in my previous tests.

2024-03-21 23:40 UTC, ihhub commented
@Branikolog , please provide your feedback.

2024-03-24 14:31 UTC, Branikolog commented
Hi, @ihhub , @oleg-derevenetz  and @LeHerosInconnu !

First of all I really appreciate the work @oleg-derevenetz and @LeHerosInconnu made within this PR but I have certain concerns which I would like to share.

A "few" words about the issue.
Making the game more difficult is great but I'm not sure this should be done in such obvious "cheating" manner, same way the original game had. I hoped we were planning to make the AI tough enough, so he won't need any cheats to win against the human player, but the changes above look to me as a step back.
H2 is a game, where faction development proceeds in a definite resource shortage conditions, but with the proposed changes AI tends to perform much above the economics, buying all creatures and building all castle structures in a shortest period of time.
Cases, when the player captures enemy castles (that could have creatures for hire) - is an essential part of gameplay. To prevent this opponent should defend such "valuable" castles with the increased priority. And a player could just invade the deepest part of the enemy area to capture the castle, which wasn't protected enough. The PR simply excludes such cases. When a player captures an enemy castle full of creatures - it is not a bad thing (from the gameplay perspective) in my opinion. This could happen due to some logic flaws (or poor AI implementation), which made AI skip the defending of such castles. Proposed changes of the PR (concerning additional resources and gold) just allow AI to hire everyone in all castles. Yeah, that makes the game really hard, but is it fair enough? Why doesn't the game add 100K gold and 100 resources to AI in the beginning of the match, so players always play against maximum forced AI? The amount of resources the AI had after some months is ridiculously high.
Why are several Titans available in captured castles considered a failure? They are so expensive, so there's no surprise that AI couldn't hire them all if he has a few castles and no additional gold income. I consider it as an exploration and resource management failure, and I'm not sure it should be fixed with excessive resources granted to AI for free. Looking at human players playing H2 I noticed that they sometimes decide not to build 6 tier at all (or on earlier game stages) (especially titans and dragons) because they feel that they have not enough resources to complete that task and hire those creatures afterwards.
Allowing the AI to hire everything just makes the overall game experience a little bit poor in terms of capturing castles.

I personally believe, to make the game more difficult, we need to improve overall AI logic, rather than providing him with free resources every day. It's just too simple and doesn't allow human players to dominate by capturing resource generators.
Also, giving AI additional resources (without considering his current income) could break some maps, where he wasn't intended to build some structures. Let's say that AI has a village but not enough wood/ore to build the castle. The mapmaker could just create such a map, where he was sure AI won't build or hire any things he was not intended to (up to the moment, he manages to capture resource generators or pick up some treasures from the adventure map). With free resources provided, AI could advance any town and bring the unexpected results into the gameplay of the particular map.
Also, such cheating could become really obvious to a human player, when he captures all enemy mines, but the enemy is still able to build resource-consuming structures in a town.
And the last one... If someone would love to give AI some resources/gold for free, this could be adjusted for a particular map in map editor with a special event feature we are all aware of. There's even a separate "map difficulty marker", that can show a player that this map was created to introduce an extra difficulty to a player.
I'm not against slightly increasing the current AI income as he still does not perform ideally, but adding a fixed number of resources for free even on a map where there could be 0 resources at all... Is it the only solution for now?

Providing additional % of resources income to AI seems to me more valid and predictable (from a player perspective) behaviour, and I believe someday we even succeed in creating such AI, that won't need any cheats to oppose humans.
Increasing the income in such a drastic way (300-400%) looks like hiding not optimal AI behaviour with the additional gold provided every day.

Speaking about the creature growth bonus - I'm not against removing it. After all it just adds a few (1-2) creatures of higher tiers, which couldn't make much difference to gameplay. At the same time, in terms of non optimized resources and gold consuming, it could bring some advantages to a human player, who manages to capture castles with additional creatures that AI couldn't hire at that time. But still, I believe, such cases should be fixed by improving the AI not to leave such castles full of creatures unprotected.

Speaking about surrendering.
I understand the complaint about the fact that AI could provide the player with additional gold. But I believe this is an issue with not fully implemented and not well adjusted conditions for surrendering. I personally really admire the enemy, who decided to surrender while defending the castle. 👍
The code is definitely lacking some logic that helps AI to consider really valuable artifacts (not just non cursed, but bringing valuable benefits for a particular hero) and fleeing/surrendering to keep them. And at the same time reduce the chance of fleeing/surrendering, when a hero has not useful or even cursed artifacts. The logic also does not consider when it is really useful to keep the creatures and surrender, and when they are just useless and there's no need to save them by paying a contribution to the enemy.
Also, I think AI could surrender much earlier in cases, when he couldn't bring much losses to the enemy during the fight AND he has a plan for replenishing at a specific castle or transferring those creatures to a much stronger hero, who could make them perform better.
I love the idea of counting the overall hero's primary skill points, but I believe, 10 in some circumstances could be too high, especially if we consider such skills as Spell Power or Attack. Imagine that an enemy can have a hero with stats like 0-0-7-2 or 6-1-1-1 which still could make such a hero quite beneficial. Could we implement an additional rule to check whether the hero has att/SP attribute higher than a certain value?
Anyway, I love the changes for surrendering logic. I hope in future we can optimize it even further, like increasing the amount of gold AI needs to have in his treasury, so he won't spend too much gold for not necessary surrenderings.

2024-03-26 04:29 UTC, LeHerosInconnu commented
Hello @Branikolog,

> Hi, @ihhub , @oleg-derevenetz and @LeHerosInconnu !
>
> First of all I really appreciate the work @oleg-derevenetz and @LeHerosInconnu made within this PR but I have certain concerns which I would like to share.

Thanks.

I've read your review, thank you for your feedback.
I'm also in favor of a super AI that doesn't need bonuses.
In my opinion, if the AI is competent, a game with just normal and easy (limited AI) levels would be sufficient (eventually with additional "easy" difficulty levels).
But that's not the case, and I doubt it could be done without a monumental amount of work.
Whatever percentage and area the AI gets bonuses in is cheating in favor of the AI for me, and should be a no go for me.

But, in the current state of the game, higher than normal difficulty levels exist, and we have to make sure that there is a difference for the human player when they are selected.
Here's the thing, the AI will never be able, before a certain amount of time and investment, to manage any bonuses in a way that is as relevant as a human player would.
Increasing creature growth per week for the AI, it's cheating for the AI, and in the end it's the human player who benefits.
Increasing resources for the AI, it's cheating for the AI, but it doesn't allow the human player to benefit from it (except with the possibility to surrender for the heroes of the AI players, which is a source of income for the human player, but less so with the latest adjustments).

> And the last one... If someone would love to give AI some resources/gold for free, this could be adjusted for a particular map in map editor with a special event feature we are all aware of. There's even a separate "map difficulty marker", that can show a player that this map was created to introduce an extra difficulty to a player.

In fact, this is currently what difficulty levels higher than normal do directly in the game interface, without having to modify the scenario file in the scenario editor.

> H2 is a game, where faction development proceeds in a definite resource shortage conditions, but with the proposed changes AI tends to perform much above the economics, buying all creatures and building all castle structures in a shortest period of time.
Cases, when the player captures enemy castles (that could have creatures for hire) - is an essential part of gameplay. To prevent this opponent should defend such "valuable" castles with the increased priority. And a player could just invade the deepest part of the enemy area to capture the castle, which wasn't protected enough. The PR simply excludes such cases. When a player captures an enemy castle full of creatures - it is not a bad thing (from the gameplay perspective) in my opinion. This could happen due to some logic flaws (or poor AI implementation), which made AI skip the defending of such castles.

This "is"/should be achieved with normal difficulty.
Now, of course, the AI still needs to be improved. :)

> H2 is a game, where faction development proceeds in a definite resource shortage conditions,

It's worth noting that with the AI heroes' possibility to surrender, the human player receives additional income that he didn't get in the original game, where his poverty was maintained in such a way that not everything was "simple".

At the current state of the game, I can't see any other way of differentiating the game's difficulty levels than to give the AI bonuses in resources that the human player can't benefit from.

For a fair gaming experience, normal difficulty is present.

Now, if the human player realizes that the AI is too weak for him, the first solution is to make a more powerful AI, but this requires time and investment. A quicker solution (which may be temporary) is to give bonuses to the AI, but the player must be warned of this and accept it by choosing higher difficulty levels.

2024-03-26 04:56 UTC, Alucard648 commented
> For a fair gaming experience, normal difficulty is present.

On Normal AI is banned from using end-game map control spells, such as Domension Door and Town Portal.

2024-03-26 05:03 UTC, LeHerosInconnu commented
Hello @Alucard648,

> > For a fair gaming experience, normal difficulty is present.
> 
> On Normal AI is banned from using end-game map control spells, such as Domension Door and Town Portal.

Yes, I'm in favor of removing this limitation, among others.
See here: https://github.com/ihhub/fheroes2/discussions/8321.

2024-03-26 06:53 UTC, oleg-derevenetz commented
Hi @Alucard648

> On Normal AI is banned from using end-game map control spells, such as Domension Door and Town Portal.

This is not the case:

https://github.com/ihhub/fheroes2/assets/32623900/2f95084b-0465-46dd-9dca-567e761d3ecb

Only the number of uses of one specific spell (Dimension Door) by one hero during one turn is limited on Easy, Normal and Hard difficulties (1, 2 and 3 respectively), but AI still can use it on all difficulties.

Hi @LeHerosInconnu @Branikolog regarding AI cheating, AI always cheats one way or another in the original games of HoMM series - in terms of the amount of resources, in terms of exploration (in HoMM2 AI is able to see the entire map according to multiple tests) and it's even capable of doing [weird things](https://www.youtube.com/watch?v=IY9CRBt6OOY). I'd say that providing additional resources is the most harmless kind of cheating (and the most widely practiced).

2024-03-26 08:28 UTC, Branikolog commented
@LeHerosInconnu 

>Increasing creature growth per week for the AI, it's cheating for the AI, and in the end it's the human player who benefits.

True. But this happens only because AI is not optimized well to use and protect that advantage. I don't really like adding extra creatures "from nowhere" to AI opponents too. 

>Increasing resources for the AI, it's cheating for the AI, but it doesn't allow the human player to benefit from it

I believe that game should behave as much predictable as possible. There're certain rules, that players learned after playing a couple of hours, like unit growth numbers in each castle, player gaining crystals/sulfur/... from the mines he had captured, creature growth happens on 1st day of the week and so on. Allowing AI to cheat and ignore that rules makes me not satisfied with the game. Currently (same as in the original game) player should consider like: "I'm playing against 1 human and 1 AI player. Human player gets 3 titans the next week, but AI is going to have 4..." I believe, that if AI is allowed to cheat, this should be done in a manner, a regular player wouldn't notice. Adding additional resources to the current AI income looks much less obvious and more predictable regarding gameplay rules, rather than providing 2-3-4 each day even those, which could be even supposed to be be acquired on a particular map.

>Now, if the human player realizes that the AI is too weak for him, the first solution is to make a more powerful AI, but this requires time and investment. A quicker solution (which may be temporary) is to give bonuses to the AI, but the player must be warned of this and accept it by choosing higher difficulty levels.

After all, resources provide a huge advantage to any player on a map. Starting without any resources on an impossible mode is already a challenge to a player, as he wastes more than a week (comparing to normal difficulty) to progress his kingdom, which is a huge delay. An experienced player can acquire this advantage, but current AI cannot (but I hope he can in some distant future, because we've already advanced so much in this direction).

@oleg-derevenetz 

>I'd say that providing additional resources is the most harmless kind of cheating (and the most widely practiced).

Additional (considering current income) - agreed, all at once - I personally not sure. :)

I'm just sharing my personal opinion here. If the proposed income cheating is a must have - I'm not the one who can prevent such changes in the project.
I suggest making them not so high at least. 3x-4x gold income seems really too much for me. There's no surprise, that AI surrenders with any hero, having so much gold.

I personally believe, that we can increase difficulty level even by small optimizing of the current logic that handles economics, exploration and even battles in more optimal and effective way.

2024-03-26 09:00 UTC, oleg-derevenetz commented
> But this happens only because AI is not optimized well to use and protect that advantage.

This is not the question of AI optimization, but the question of overall game economy. For instance, Wizard castle can bring 1250 gold per day (1000 from the castle itself plus 250 from Statue), it's 8750 gold per week. A single Titan costs 5000 gold, and you will have 3 new Titans per week (with the Well), so you will need 15000 gold per week alone to hire them (and there also will be other units to hire!). The income from castles is such that weekly income from the castle itself is not able to recoup the cost of hiring the weekly unit growth. This is by design. At the beginning of the game there is some help in the form of gold/resource piles, but it can mainly help with the castle development process, not with the weekly hiring of creatures.

2024-03-26 10:37 UTC, Branikolog commented
@oleg-derevenetz 

> > But this happens only because AI is not optimized well to use and protect that advantage.
> 
> This is not the question of AI optimization, but the question of overall game economy. For instance, Wizard's castle can bring 1250 gold per day (1000 from the castle itself plus 250 from Statue), it's 8750 gold per week. A single Titan costs 5000 gold, and you will have 3 new Titans per week (with the Well), so you will need 15000 gold per week to hire them alone (and there also will be other units to hire!). A fully built Wizard's castle will require 23600 gold per week to fully redeem all creatures - in other words, even if you have 2 extra Gold mines (8750 + 1000 * 7 * 2 = 22750 gold per week), you will still not be able to redeem all the creatures! The HoMM2 game economy is such that weekly income from the castle itself is not able to recoup the cost of hiring the weekly unit growth. This is by design, and this is true even for relatively "cheap" castles - for example, a fully built Knight's castle will require 11705 gold per week to fully redeem all creatures (let me remind you that the castle itself will still bring just 8750 gold per week). At the beginning of the game there is some help in the form of gold/resource piles, but it can mainly help with the castle development process, not with the weekly hiring of creatures in the midgame or late game.

Indeed. Because of ridiculously high price Titans are not intended to be bought each week and it is a common situation, when a player can't afford hiring all creature growth in such expensive castles. 
As I mentioned above experienced players sometimes decide even not to build the Cloud Castle, if they feel they have not enough resources or they are threatened by enemies much (around the particular castle or just in some other areas of the adventure map). The AI currently can even capture enemy town and build the Cloud Castle there, while there's no chance for him to defend it and hire them on the next week.
I consider this a mistake of choosing wrong strategy (which human players tend to make too), when instead of rushing enemies with 1-5 tiers or investing into powerful magic player wasted tons of gold and resources into the Cloud Castle and is not capable to hire them. That's the downside of playing as Warlocks or Wizards which are "strong factions, that beat everyone else" ( according to judgement of people, who played the game just a few times 😄 ) I personally failed many times investing into 6 tier and loosing, because was invaded by numerous enemies who easily demolished my only titan hired within a week. 😅 

Current AI is lacking some sort of strategy-selecting algorithms that could help to not waste resources into 6 tier and invest them into something more relevant at the moment. As a result we have many castles full of available troops being captured by human players / other AI players.

By the way, I think we sometimes find such castles just because AI has no precious resources required for hiring. It would be great, If AI could trade 100 useless wood to gems to hire few titans in his castle and beat enemies with those tough tall guys. :)

Sometimes it's more beneficial to hire 1 titan, but sometimes, having 4-5 stacks of weaker troops can bring to enemy more troubles, because he can cover a lonely titan on the opposite side. I'm not sure how and when we can handle such cases. 😅

2024-05-04 23:25 UTC, idshibanov commented
> The AI currently can even capture enemy town and build the Cloud Castle there, while there's no chance for him to defend it and hire them on the next week.

AI should already take account for that. Castles are rated by safety depending on enemy proximity and the ones in the back should be developed first. If it's not the case then we might have a bug.

> Current AI is lacking some sort of strategy-selecting algorithms that could help to not waste resources into 6 tier and invest them into something more relevant at the moment.

Agree on this. We might be able to do a week-ahead planning, for example to save up gold for important purchase. Castle development logic haven't really changed since 2020.

2024-05-06 16:47 UTC, idshibanov commented on src/fheroes2/game/difficulty.cpp
> +        return getIncomeFromSetsOfResourceMines( 3 ) + getBonusForCastles();
```
    case Difficulty::HARD:
        // only ore/wood but a single piece, maybe 1 Castle income
    case Difficulty::EXPERT:
        return getIncomeFromSetsOfResourceMines( 1 ); // maybe a single castle income
    case Difficulty::IMPOSSIBLE:
        return getIncomeFromSetsOfResourceMines( 1 ) + getBonusForCastles();
```

2024-05-06 16:50 UTC, idshibanov requested changes
I appreciate the work you've put into this, but I think you went overboard on resource bonuses to compensate. I ran two debug games on M and L maps and closely watched AI's resource management.

For references these are **exact** OG AI bonuses:
- Hard: 129% gold, a single piece of wood and ore _daily_
- Expert: 145% gold, 1 wood and ore daily plus 1 of everything _weekly_
- Impossible: 160% gold, 1 wood and ore daily plus 2 of everything _weekly_

You essentially doubled the gold income and 26 resources distributed weekly turned into 133. Now let's see the examples:

```
Week 2 Day 1:
06.05.2024 11:57:38: [DBG_AI]   AI::Normal::KingdomTurn:  Red starts the turn: 1 castles, 5 heroes
06.05.2024 11:57:38: [DBG_AI]   AI::Normal::KingdomTurn:  Funds: ore: 46, wood: 99, mercury: 35, sulfur: 28, crystal: 28, gems: 27, gold: 23700
```

Most AI castles had upgraded level 6 creatures by Week 2 Day 3.

```
Week 3:
06.05.2024 12:04:46: [DBG_AI]   AI::Normal::KingdomTurn:  Yellow starts the turn: 2 castles, 5 heroes
06.05.2024 12:04:46: [DBG_AI]   AI::Normal::KingdomTurn:  Funds: ore: 33, wood: 91, mercury: 49, sulfur: 47, crystal: 32, gems: 56, gold: 66050

```
I think it will also help to correct trading behaviour, but I would make that change separate from this PR:
```
06.05.2024 11:53:28: [DBG_AI]   AI::tradeAtMarketplace:  Orange having funds ore: 65, wood: 64, mercury: 34, sulfur: 35, crystal: 35, gems: 14, gold: 9400 
obtains funds ore: 5, wood: 5, mercury: 0, sulfur: 0, crystal: 0, gems: 20, gold: 12500 
through a transaction ore: 43, wood: 42, mercury: 26, sulfur: 27, crystal: 27, gems: -6, gold: -3125
```

2024-05-06 17:03 UTC, oleg-derevenetz commented
Hi @idshibanov

> Most AI castles had upgraded level 6 creatures by Week 2 Day 3.

These changes are not about castle development, they are about hiring all the creatures from the fully built castles (see [this](https://github.com/ihhub/fheroes2/pull/8402#issuecomment-2019867089) comment for details). BTW resource trading currently doesn't work for creature hiring, only for castle development.

2024-05-06 17:54 UTC, idshibanov commented
> Changes in this PR are not about castle development, they are about hiring all the creatures from the fully built castles to maximize the army.

If that's the only goal of your PR why give out any resources at all? This only proves my point.

2024-05-06 18:11 UTC, oleg-derevenetz commented
@idshibanov

> If that's the only goal of your PR why give out any resources at all? This only proves my point.

Technically yes, there is only point to give the resources needed to redeem the creatures (e.g. Gems for Wizard castles). What I want to say is that 130%, 140% or 160% gold bonus income is clearly not enough to hire all the creatures. Some castles need 200% or even more bonus gold for this. As I said here earlier in the discussion, we can do some per-castle-type gold bonus income. The problem is also that AI does not buy out armies in castles located in safe zones (and far from the heroes that can be reinforced in castles) without the need, so we need to have some kind of reserve of gold (and possibly rare resources) in case we need to quickly buy out the entire army accumulated there (for example, if an enemy hero is discovered nearby).

2024-05-06 19:10 UTC, idshibanov commented
Let's be realistic: you can't change unit purchasing and avoid touching castle development unless you do something radical like giving AI units for free.

Goal of this change shouldn't be 0s in all castle dwellings but only avoid giving out level 6 creatures in **fully built castles**. We shouldn't worry how many hydras or steel golems are there. AI buys high tier units first. Even for wizard 210% gold income should be sufficient. Additionally, castles should only give special resource income only if dwelling 6 is built.

I gave out examples to illustrate that current values give AI unlimited resources on standard maps. As a side effect it changes development speed dramatically, which wasn't the intent here.

We can address castle development edge cases separately. For example, a better change would be to avoid building dwellings if there isn't gold income to buy them later.

2024-05-06 20:07 UTC, oleg-derevenetz commented
@idshibanov OK, what do you think about  0b9987f? The rationale is as follows: on Impossible difficulty AI should get a (relatively) good boost to the castle development plus (plus-minus) guaranteed redeem of all creatures, on Hard & Expert difficulties AI should get _some_ boost to the castle development PLUS guaranteed redeem of all creatures on Expert difficulty. What do you think about this approach? Of course, it would be good to additionally check this in real long-term games.

2024-05-07 05:43 UTC, idshibanov approved these changes

2024-05-07 05:43 UTC, idshibanov commented on src/fheroes2/game/difficulty.cpp
> +                result += ProfitConditions::FromMine( Resource::GOLD ) * 2;
Maybe give the second gold mine only if dwelling 6 is present. As of now players starting as Warlock/Wizard develop faster than others.

2024-05-15 08:45 UTC, ihhub commented
Hi @Branikolog , please review this pull request after 1.1 as the top priority. We need to improve our AI and this pull request has been in an open state for so long.

2024-05-25 14:14 UTC, ihhub reviewed
Hi @oleg-derevenetz , I left 2 questions here. Could you please take a look at them?

2024-05-25 14:14 UTC, ihhub commented on src/fheroes2/game/difficulty.cpp
> +                result += ProfitConditions::FromMine( Resource::GOLD );
I am not sure that Warlock needs extra gold income as it has a special building for this.

2024-05-25 14:14 UTC, ihhub commented on src/fheroes2/game/difficulty.cpp
> +    const auto getIncomeFromSetsOfResourceMines = []( const int resourceTypes, const uint32_t numOfSets ) {
**numOfSets** is always 1. Do we need it? Or the intention to keep it for the future changes?

2024-05-25 14:23 UTC, oleg-derevenetz commented on src/fheroes2/game/difficulty.cpp
> +                result += ProfitConditions::FromMine( Resource::GOLD );
@ihhub Total cost of weekly unit income in the Warlock castle (with Well and Waterfall) is 22180 gold. Castle with Statue and Dungeon will bring (1000 + 250 + 500) * 7 = 12250 gold per week, so we still need additional ~10k gold per week, so one extra Gold Mine (7k gold per week) is still not enough.

2024-05-25 14:24 UTC, oleg-derevenetz commented on src/fheroes2/game/difficulty.cpp
> +    const auto getIncomeFromSetsOfResourceMines = []( const int resourceTypes, const uint32_t numOfSets ) {
@ihhub `numOfSets` was used earlier, now it is indeed always 1, so I can remove it, but probably it may be needed once again in future.

2024-05-25 15:09 UTC, ihhub approved these changes

2024-05-27 12:16 UTC, Branikolog commented
Hi, all!

I've made a couple of tests.
AI tends not to surrender outside towns now. If it's a deliberate decision - then OK (I'm still convinced, that sometimes saving troops could be a nice step, especially when AI faces a hero with much stronger army and cannot deal any damage because of drastic stat difference). In some cases, when AI has diplomacy or stateman quill it is definitely worth saving a few troops for a little money... Maybe it could be implemented as a separate PR if you wish...

I'm not against reducing unit growth bonuses.
Speaking about increasing income bonus - I'm not against a reasonable rising of gold income, but absolutely not sure about providing a ton of resources from nowhere. We can always set a resource giveaway for a particular map in the map editor. Maybe a few can be provided, but I still prefer rising the **existing** income, rather than giving all resources for free. What if a mapmaker would like to make a map, where AI cannot afford building a castle creating a map in such manner, that AI does not have any ore mines in his area? It would be hard to explain a player, how AI managed to find so many resources within his closed area...
I'm also unsure about providing resources based on a starting faction. There lots of maps, where a player starts with several multi-faction castles. Sometimes the map is designed in such a way, when a player does not have opportunity to develop his starting castle being forced to capture another. So resource bonus meant for the starting faction could be... Cannot say it is useless, but it looks like an overabundance in my opinion.
Anyway this game is designed in such way, when a player cannot afford to hire all troops on the start of every week. There's nothing wrong, when you capture a castle and find a bunch of troops for hire there. I think the root of the problem lies in AI leaving such castles without sufficient protection. Second thing that allows such issues to happen is AI spending too much money for developing other castles, rather than focusing on hiring new troops.

2024-05-27 15:16 UTC, oleg-derevenetz commented
> We can always set a resource giveaway for a particular map in the map editor.

This giveaway will not depend on AI difficulty then.

> I'm also unsure about providing resources based on a starting faction.

There is no such a thing as providing resources based on starting faction. Resources are provided on per-castle basis for each castle in the kingdom personally. For instance, if a kingdom has Barbarian castle with Cyclopes, Sorceress castle without the Phoenixes and Warlock castle with Dragons, there will be 1 additional Crystal + 1000 Gold per day for Barbarian castle, 1000 Gold per day for Sorceress castle (no Mercury) and 1 additional Sulfur + 2000 Gold per day for Warlock castle.

> I think the root of the problem lies in AI leaving such castles without sufficient protection.

AI will hire troops in the castle if it sees any threat nearby (and will not develop such a castle). But:

1. If AI has already spent money on the development of some other castles, he will not be able to hire enough troops, because the economy in the game is made in such a way that no castle can "feed itself" in terms of hiring troops - even if there is no need to develop other castles;
2. If AI will always hire troops before trying to develop castles, then the overall rate of castle development will be very slow (see point 1);
3. Unlike the original game, AI does not start to see the entire map from a certain point, and cannot see threats hidden by the fog of war (and even more so those that can jump out of the fog of war through half a map using the Dimension Door-like spells).

2024-05-29 18:27 UTC, oleg-derevenetz commented
> having a bunch or resources on the game start gives AI player a huge advantage, comparing to human, starting without any single resource.

On Impossible difficulty, AI starts with 10K gold. This is literally nothing if your single castle wants 15K gold per week just to hire the weekly growth of Titans alone. This may help to speed up the development of the starting castle somewhat, but nothing more. Not such a huge advantage in the long term at all.

> By the way, if we slightly increase the priority for hunting resources for AI, he can do better in terms of castle development and army hiring.

The resources on the map only help to develop the castles (to one degree or another). They don't appear every week and can't help with hiring new troops on weekly basis, especially in the long term.

In general, this PR embodies @LeHerosInconnu's idea, and as far as I understand, according to his tests, game complexity really increases on the Expert and Impossible difficulties, just as planned. If someone has specific ideas on how to achieve a similar result in other ways, they can offer a separate PR.

2024-05-30 10:21 UTC, Branikolog commented
@oleg-derevenetz 
>The resources on the map only help to develop the castles (to a certain extent). They don't re-appear every week and can't help with hiring new troops on weekly basis, especially in the long term.

True! But the faster AI player develops his castle on the first days, the faster he can explore and conquer points of interest. The more resources he gets, the faster he hires new creatures/heroes and picks up more resources. So the less human player can pick up and the slower he develops then. Indeed, the income strictly depends on the number of towns and mines a player captured on the late game. But no one says, that all troops from all castles should be immediately hired. This is not how this game was planned to be played.

>In general, this PR implements the @LeHerosInconnu's idea, and as far as I understand, according to his tests, game complexity really increases on the Expert and Impossible difficulties, just as planned. If someone has specific ideas on how to achieve a similar result in other ways, they can offer a separate PR.

Considering the idea of making the game maximum tough and annoying from the enemy invasion perspective, why can't AI receive 10k gold daily then? Or even 20k gold daily to be sure he hires everything and everywhere? I feel this is not the way we need to make game hard on higher difficulties.

2024-05-30 12:23 UTC, ihhub commented
@Branikolog , please focus on the current improvement proposal. Before the changes AI had gold bonus and monster growth bonus. After the changes AI has gold and resource bonuses. The question is which way is "less" cheating?

2024-05-30 13:49 UTC, ihhub commented
After thinking a bit I think we might consider only giving the AI gold rather than resources. For example, there could be castles where no marketplace exists but then dwellings are being. AI would buy monsters even when they have no mines.

We have logic to convert resources in castles when marketplaces are being built. In most cases this helps the AI to develop the castle and also buy many creatures. This could be a solution to satisfy @Branikolog as well.

@oleg-derevenetz  what do you think?

2024-05-30 13:56 UTC, ihhub commented
@oleg-derevenetz , could you please create a separate PR with the changes for surrender? I can see that this PR takes a lot of discussion and it is good to agree at least on one part rather than delaying both.

2024-05-30 15:54 UTC, oleg-derevenetz commented
Hi @ihhub

> After thinking a bit I think we might consider only giving the AI gold rather than resources. For example, there could be castles where no marketplace exists but then dwellings are being. AI would buy monsters even when they have no mines.
> 
> We have logic to convert resources in castles when marketplaces are being built. In most cases this helps the AI to develop the castle and also buy many creatures.

You see, on Expert and Impossible AI will get starting resources which are more than enough to build the Marketplace in at least one castle even without mines. After that, the construction of new buildings in castles (as well as the upgrade towns into castles) becomes only a matter of time. Therefore, the argument "the mapmaker may want to remove the mines from the map and AI will not be able to build anything" is untenable, at least on those difficulties where it has enough resources to build Marketplaces (AI builds them one of the first, immediately after the Statue). All that additional resources do at higher difficulty levels is accelerate this process, and not "allow" it in principle.

> could you please create a separate PR with the changes for surrender? I can see that this PR takes a lot of discussion and it is good to agree at least on one part rather than delaying both.

IMHO there is still time, 1.1.1 milestone is scheduled for early July only. If the process with this PR drags on, I can do it.

2024-05-31 12:36 UTC, ihhub commented
Hello @oleg-derevenetz , we are planning to allow map makers to disable any buildings in castle. Having this option and AI with extra resources would lead to broken gameplay on some future maps or players would obviously know that AI is cheating.

This isn't implemented yet so I would like to find a solution suitable for everyone.

2024-05-31 13:25 UTC, oleg-derevenetz commented
@ihhub OK, what do you think about 0633eab? Please note that per-castle resource bonuses for level 6 units are still applied (BUT only if the corresponding buildings are built).

2024-06-01 00:37 UTC, ihhub commented
Hi @oleg-derevenetz , the proposed change improves the logic. However, I am still concerned about the resources for creatures from dwellings of level 6. To make sure that for players it won't be obvious that the AI is cheating I am suggesting to add a check whether at least one marketplace is build in any town or the corresponding Mine was captured by the AI. What do you think?

2024-06-01 13:59 UTC, oleg-derevenetz commented
Hi @ihhub

> To make sure that for players it won't be obvious that the AI is cheating I am suggesting to add a check whether at least one marketplace is build in any town or the corresponding Mine was captured by the AI.

OK, so be it. Please take a look at the recent changes.

2024-06-01 14:44 UTC, ihhub approved these changes

2024-06-01 14:45 UTC, ihhub commented
@oleg-derevenetz , now I think this is the best solution we can have at the moment. Thank you very much for this update!

2024-06-01 14:45 UTC, merged

2024-06-08 15:44 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

What about the AI bonuses with the last changes made after my last test to date?
Looking at previous posts and code comments, it seems that the general bonus has been removed and now a bonus is given based on castle type and if the level six dwelling is already built.
If I've understood correctly (values are for understanding purposes):
Castle type A, bonus 10 000 gold and X rare resources.
Castle type B, bonus 5 000 gold no resources.
Etc.
And also the requirement of a resource type mine for the level six dwelling creature, and a marketplace?
I'm thinking of doing a few tests and I'd like to be sure of the AI bonuses for each difficulty level before I start.

2024-06-08 16:01 UTC, oleg-derevenetz commented
Hi @LeHerosInconnu

> Castle type A, bonus 10 000 gold and X rare resources.
> Castle type B, bonus 5 000 gold no resources.

Currently per-castle resource bonuses (on Expert and Impossible difficulties) are as follows:

* +1 Crystal per day for each Barbarian castle;
* +1 Mercury per day for each Sorceress castle;
* +1 Sulfur & +1000 Gold per day for each Warlock castle;
* +1 Gem & +1000 Gold per day for each Warlock castle;

The above bonuses are applied only if all the following conditions are met:

* The corresponding castle has a level 6 dwelling;
* The corresponding kingdom has a Marketplace in at least one of its castles or has at least one captured mine of the appropriate type.

In addition, 1000 gold is always awarded for each castle in the kingdom regardless of its type and dwellings.

2024-06-08 16:44 UTC, LeHerosInconnu commented
Okay, thanks.

2024-06-16 13:18 UTC, LeHerosInconnu commented
Hello @oleg-derevenetz,

I made my report here: https://github.com/ihhub/fheroes2/discussions/8840.