Add info about ranged penalty elimination to archery skill description
ihhub/fheroes2 pull request #8403
Opened 2024-02-13 19:21 UTC by zenseii

Add a description about ranged penalty being when having the archery skill.
Add ranged penalty Get function to `GameStatic` and use in relevant places in the code.

Fix #8398 

<img width="327" alt="image" src="https://github.com/ihhub/fheroes2/assets/12501091/67e78c2e-6eb5-4b3e-b0e4-8426829fc369">

2024-02-13 20:00 UTC, oleg-derevenetz commented on src/fheroes2/game/game_static.h
> +    uint32_t getCastleWallRangedPenalty();
Hi @zenseii I usually add a comment to new functions or a method with a brief (if possible) description of what this function does. For example:

```cpp
// Returns the approximate distance between two tiles with given indexes. This distance is calculated as the number of
// tiles (truncated to the nearest smaller integer value) that would need to be traversed in a straight direction to
// overcome the distance that corresponds to the distance that the hero would have to cover when moving between tiles
// with given indexes using the usual rules and penalties.
//
// For example, in order to navigate to a tile B, which is located seven tiles below and five to the right of tile A,
// the hero should move two tiles down and five tiles right down diagonally (diagonal movement costs 50% more), which
// corresponds to 2 + 5 * 1.5 = 9.5 (9 after truncation) tiles traversed in the straight direction.
//
// This function should be avoided unless high precision is not important.
uint32_t GetApproximateDistance( const int32_t pos1, const int32_t pos2 );
```

The advantage is that many IDEs understand such comments and show tooltips when hovering over this function. For example, this is how it looks in MS Visual Studio:

![tooltip](https://github.com/ihhub/fheroes2/assets/32623900/006237d2-5503-4d22-8259-811adac0b0b6)

The exception is if it is absolutely obvious from the name of the function what it does.

2024-02-13 22:07 UTC, oleg-derevenetz requested changes
Hi @zenseii I just left one question and one reasoning. Could you please take a look when you have time?

2024-02-13 22:07 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_battle.cpp
> +                    _enemyShootersStrength /= 1 + ( GameStatic::getCastleWallRangedPenalty() / 100.0 );
These `/ 1.5` here and below were introduced in #6743 by replacing `/ 2`. Perhaps the value 1.5 is not directly related to this penalty, but, on the other hand, if the penalty is reduced this coefficient should also be reduced (and if the penalty is increased, it should also be increased). OK, let's do it this way.

2024-02-14 09:54 UTC, Branikolog approved these changes

2024-02-14 16:12 UTC, oleg-derevenetz approved these changes

2024-02-15 00:05 UTC, ihhub approved these changes

2024-02-15 00:05 UTC, merged

2024-02-15 00:05 UTC, ihhub commented
@zenseii , huge thanks for this change!