added possibility to "draw" the attack angle between two hexes
ihhub/fheroes2 pull request #8464
Opened 2024-03-07 15:39 UTC by dood-apo

On the smaller touch screens (mobile phones) it is quite difficult to input the correct attack angle. Currently the only option is to click on the appropriate sub-region of a target hex, which is an extremely small area on mobile phones.

This PR addresses this inconvenience, as presented on a video below. An additional input method is introduced, namely "drawing" an attack angle between the source cell and the target cell of attack. Once the attack direction sword is drawn by this method, it gets confirmed by tapping the target cell.

https://github.com/ihhub/fheroes2/assets/84446398/b4ec84f1-b297-43f2-924a-7deb1bb9f97b

Close #7070

2024-03-07 16:26 UTC, oleg-derevenetz reviewed
Hi @dood-apo I just left a few suggestions, please take a look when you have time.

2024-03-07 16:26 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.h
> +            int swipeDstTheme;
I believe, it would be better to initialize the struct fields in-place:

```suggestion
            int32_t swipeSrcCellIndex{ -1 };
            int32_t swipeDstCellIndex{ -1 };
            bool isValid{ false };
            int swipeSrcTheme{ Cursor::NONE };
            int swipeDstTheme{ Cursor::NONE };
```

2024-03-07 16:26 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.h
> +            }
... and this will allow to remove this method and use just:

```cpp
_swipeAttack = {};
```

2024-03-07 16:26 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +    , _swipeAttack( { -1, -1, false, 0, 0 } )
... and to remove this initialization.

2024-03-07 16:26 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.h
> +                _storedIntent = BoardActionIntent{};
You can as well clear the `Battle::Interface::_boardActionIntent` directly instead, because `_storedIntent` is a reference to this field. Since this method is called from the `Battle::Interface` methods, you can replace its call by this:

```cpp
_boardActionIntent = {};
```

2024-03-08 10:30 UTC, oleg-derevenetz reviewed
Hi @dood-apo I just left a couple of minor suggestions, please take a look when you have time.

2024-03-08 10:30 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +            themes = GetSwordCursorDirection( direction );
Since the `direction` it is not used anywhere except for this single line, we can avoid this temporary variable:

```suggestion
            themes = GetSwordCursorDirection( Board::GetDirection( index_pos, _swipeAttack.swipeSrcCellIndex ) );
```

2024-03-08 10:30 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +                bool isConfirmed = boardActionIntentUpdater.isConfirmed();
This variable can be `const`.

```suggestion
                const bool isConfirmed = boardActionIntentUpdater.isConfirmed();
```

2024-03-08 10:49 UTC, oleg-derevenetz approved these changes

2024-03-08 15:19 UTC, ihhub requested changes
Hi @dood-apo , I left several comments here. Could you please take a look at them?

2024-03-08 15:19 UTC, ihhub commented on src/fheroes2/battle/battle_interface.h
> +            bool isValid{ false };
We can remover this member and have the corresponding function:
```cpp
bool isValid() const
{
    return ( swipeSrcCellIndex != -1 ) && ( swipeDstCellIndex != -1 );
}
```

because **isValid** is set only within `storeDst()` call which is risky.

2024-03-08 15:19 UTC, ihhub commented on src/fheroes2/battle/battle_interface.h
> +            }
Should we call them **setSrc()** and **setDst()**? We barely use `store` verb in the code.

2024-03-08 17:48 UTC, dood-apo commented on src/fheroes2/battle/battle_interface.h
> +            bool isValid{ false };
Being valid takes more than that. But you have a point, that it is more robust to inspect the structure and assess if it is valid than rely on a member set externally by client code calls to `setDst`. I've refactored a bit more to be able to reuse `isValidDestination` for `isValid` purposes.

2024-03-08 17:57 UTC, dood-apo commented
By the way, aren't we approaching the moment where `SwipeAttack` is warranted its own compilation unit?

2024-03-09 01:38 UTC, ihhub approved these changes

2024-03-09 12:38 UTC, oleg-derevenetz approved these changes

2024-03-09 20:21 UTC, dood-apo commented
> Hi, @dood-apo. Could you please solve the merge conflict if you have the time?

Done!

2024-03-10 01:57 UTC, merged

2024-03-10 01:58 UTC, ihhub commented
@dood-apo , huge thanks for this improvement!