Add an initial Editor options dialog
ihhub/fheroes2 pull request #8469
Opened 2024-03-10 09:18 UTC by ihhub

This is an initial implementation of the dialog. Animation and passability options logic is going to be added later. We might consider replacing Audio settings by Interface settings as no Audio exist in any of HoMM editors.

2024-03-10 10:38 UTC, ihhub commented
Hi @zenseii , could you please take a look at `editor_options.cpp` file for wordings?

2024-03-10 12:22 UTC, ihhub commented on src/fheroes2/editor/editor_options.cpp
> +                    fheroes2::showStandardTextMessage( "Attention", "Your version of Heroes of Might and Magic II does not support any other languages than English.",
We can keep it as it is if we don't have a proper text replacement.

2024-03-11 13:38 UTC, Branikolog approved these changes

2024-03-11 15:52 UTC, Districh-ru requested changes
Hi, @ihhub, I left some comments. Could you take a look when you have time?

2024-03-11 15:52 UTC, Districh-ru commented on src/fheroes2/system/settings.cpp
>          os << "editor = beta" << std::endl;
To separate this setting from the previous one we can add extra `std::endl` like it is done in all other cases:
```suggestion
        os << std::endl << "editor = beta" << std::endl;
```

2024-03-11 15:52 UTC, Districh-ru commented on src/fheroes2/editor/editor_options.cpp
> +    enum class DialogAction : int
This enumeration will not be big enough so we can use `uint8_t` instead of `int` here. What do you think?

2024-03-17 04:04 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +            int renderFlags = LEVEL_OBJECTS | LEVEL_HEROES | LEVEL_ROUTES;
`Interface::GameArea::Redraw()` method accept **int** as the second argument.

2024-03-17 04:21 UTC, ihhub commented on src/fheroes2/editor/editor_options.cpp
> +                redrawAdventureMap();
Hi @Districh-ru , we do the same way for any other options. I believe you are testing a debug version which is slower and this cases one frame to be rendered in between. We can fix it outside the scope of this pull request as many other places have the same logic.

2024-03-17 04:30 UTC, ihhub commented
Hi @oleg-derevenetz , could you please review this pull request and most importantly the part in `settings.h|cpp` files?

2024-03-17 04:31 UTC, ihhub commented
Hi @zenseii  and @Districh-ru , I changed "Show Passability" states to `Hide` and `Show` as we do with other options in the game. Are you okay with this change?

2024-03-17 04:48 UTC, Districh-ru commented
> Hi @zenseii and @Districh-ru , I changed "Show Passability" states to `Hide` and `Show` as we do with other options in the game. Are you okay with this change?

Hi, @ihhub. I'm okay with these changes but the we should also rename "Show Passability" to "Passability":. Show may be On or Off and Passability may me Show or Hide. :)

2024-03-17 05:01 UTC, Districh-ru commented on src/fheroes2/editor/editor_options.cpp
> +                redrawAdventureMap();
I agree, that we should fix such issues in a separate PR, but in all other cases `redrawAdventureMap()` is called when one dialog is closed (Language, Graphics) and the Options dialog is shown. So one frame between these different dialogs is not so noticeable.
This one frame is noticeable also in the release build:

https://github.com/ihhub/fheroes2/assets/113276641/6539434c-6fe6-4275-b195-b51ff7402f64


... and passability is not shown in the release build. :(

2024-03-17 09:00 UTC, oleg-derevenetz approved these changes
LGTM.

2024-03-17 15:32 UTC, ihhub commented on src/fheroes2/editor/editor_options.cpp
> +                redrawAdventureMap();
Release build missing passability drawing is fixed.

2024-03-17 15:43 UTC, ihhub commented on src/fheroes2/editor/editor_options.cpp
> +                redrawAdventureMap();
I've fixed the flickering as well.

2024-03-17 15:43 UTC, ihhub commented
Hi @Districh-ru , please review it again.

2024-03-17 15:48 UTC, Districh-ru approved these changes
Well done!

2024-03-17 16:00 UTC, merged