add option FHEROES2_WITH_SYSTEM_SMACKER
ihhub/fheroes2 pull request #8527
Opened 2024-03-29 13:36 UTC by undef21

to use system libsmacker instead bundled one.

2024-03-29 14:42 UTC, ihhub commented
Hi @undef21 , can you please explain the reason of using the system library? As far as I remember we ourselves fixed some bugs in this library which comes with the code.

2024-03-29 16:31 UTC, undef21 commented
Hello, @ihhub, @oleg-derevenetz .

Many linux distributions have policies which require to use system libraries as much as possible instead bundled ones. So this PR is mainly for distribution maintainers.

> Yes, I upgraded it to the latest version some time ago, the original libsmacker (without our patches) was nearly unusable, so I removed the option to use the non-bundled one.

Now Debian and Ubuntu have `libsmacker` in their repositories ([Debian](https://packages.debian.org/search?suite=all&section=all&arch=any&searchon=names&keywords=libsmacker-dev) and [Ubuntu](https://packages.ubuntu.com/search?keywords=libsmacker-dev&searchon=names)) with `tree-size-check` patch and `fheroes2` in that distributions already [uses](https://packages.debian.org/sid/fheroes2) system libsmacker. So I suggest restore building with external libraries instead bundled ones.

2024-03-29 18:20 UTC, oleg-derevenetz requested changes
Hi @undef21 looks good, the only recommendation is to slightly rephrase the comment. I suppose this has been tested on systems where there is a `libsmacker` from packages?

2024-03-29 18:20 UTC, oleg-derevenetz commented on Makefile
> +# FHEROES2_WITH_SYSTEM_SMACKER: build with external libsmacker instead bundled one
```suggestion
# FHEROES2_WITH_SYSTEM_SMACKER: build with an external libsmacker instead of the bundled one
```

2024-03-30 08:23 UTC, undef21 commented on Makefile
> +# FHEROES2_WITH_SYSTEM_SMACKER: build with external libsmacker instead bundled one
Thanks. Fixed.

Yes, this has been tested on Debian and Ubuntu, also another Debian derivatives (Kali, Raspbian) use the patched library. Another systems should patch their libsmacker packages to use this options or use the bundled library.

2024-03-30 09:41 UTC, oleg-derevenetz approved these changes

2024-03-31 07:54 UTC, ihhub approved these changes

2024-03-31 07:55 UTC, merged

2024-03-31 07:55 UTC, ihhub commented
@undef21 , huge thanks for this change!