Add a window to change Monster properties
ihhub/fheroes2 pull request #8539
Opened 2024-04-03 07:28 UTC by idshibanov

relates to #6845

Later we can make it's own dialog window to control monster join condition, but it outside of OG scope.

![Screenshot 2024-04-03 032143](https://github.com/ihhub/fheroes2/assets/1373638/5ce963bb-6c5c-4268-9d8d-51cb97e5328d)

2024-04-03 10:44 UTC, Stisen1 commented
The dialog-box works as intended. The minimum number 0 is a wierd one though...

https://github.com/ihhub/fheroes2/assets/118435605/60ef5eaa-5ca7-4949-a041-3b2711540d2b

https://github.com/ihhub/fheroes2/assets/118435605/ce3cc05b-def7-4d4d-8188-3c9a50ea35fd

1. The dialog saves the inserted number of paladins. It's there when you open the dialog box again. 
2. When I save the map and run it, the standard amount of paladins is what you get. 
3. I've tried different values: same result. 

Furthermore: The new code come up with new issues, that I'm sure you've already noticed and get fixed down the line. 
 
![image](https://github.com/ihhub/fheroes2/assets/118435605/d8c9adad-1f15-401f-9128-60f37d6873f8)

2024-04-03 14:49 UTC, Stisen1 commented
@

> @Stisen1.
> 
> > Furthermore: The new code come up with new issues, that I'm sure you've already noticed and get fixed down the line.
> 
> These issues are on your side. As can be seen by the build checks, the changes compile just fine. I've also tested locally myself. Please make sure you are making a clean build and that you are checking out the correct branch locally with GitHub.

@zenseii

I refreshed my local directory with a new one. Now VS has no issue with the changed codes in the editor_interface.cpp file. I get the exact same results as the abovementioned numbered list.

You can delete your comment, because I erased the thing that you commented on.

2024-04-03 15:00 UTC, ihhub requested changes
Hi @idshibanov , I left 2 comments here. Can you please take a look at them?

2024-04-03 15:00 UTC, ihhub commented on src/fheroes2/monster/monster.h
> +        JOIN_CONDITION_UNSET = 3
Let's make it as **-1** to make sure that all negative values represent unset states.

2024-04-03 15:00 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +                    if ( Dialog::SelectCount( _( "Set Monster Count" ), 0, 500000, monsterCount ) ) {
I am suggesting to use monster name here as it is not easy to identify which monster is being modified.

2024-04-03 15:19 UTC, ihhub commented
Hi @Branikolog , please review it as the highest priority.

2024-04-03 15:36 UTC, idshibanov commented on src/fheroes2/monster/monster.h
> +        JOIN_CONDITION_UNSET = 3
We store this value as uint in metadata, might trigger overflow warnings.

2024-04-03 15:51 UTC, idshibanov commented on src/fheroes2/editor/editor_interface.cpp
> +                    if ( Dialog::SelectCount( _( "Set Monster Count" ), 0, 500000, monsterCount ) ) {
![image](https://github.com/ihhub/fheroes2/assets/1373638/a1dbbd82-0942-4e92-b1d5-f678a40b986e)
Would have to check translations if they go over the dialog box limit.

2024-04-03 16:02 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +                    if ( Dialog::SelectCount( _( "Set Monster Count" ), 0, 500000, monsterCount ) ) {
Since it is a temporary solution it is OK.
Later we will make a new monster select dialog. And also we can update this "SelectCount" dialog to allow multiple header lines.

2024-04-04 03:03 UTC, Districh-ru approved these changes

2024-04-05 15:10 UTC, ihhub commented on src/fheroes2/monster/monster.h
> +        JOIN_CONDITION_UNSET = 3
I suggest to still change it to -1 and modify metadata type from `uint32_t` to `int32_`. I don't think that there is a need to even go beyond 2 billion values.

2024-04-05 22:04 UTC, Branikolog commented
Hello!
I've made a couple of tests.
As mentioned by @Stisen1 , when starting a map in single player mode creature numbers don't correspond those I've set in editor.

https://github.com/ihhub/fheroes2/assets/55348946/1d98054b-ce1f-47ee-87f6-f92841bfcc5c

I've also experienced a case, when new monsters I place have non zero value.
This happens after I load the map, delete the existing monster and trying to place other:

https://github.com/ihhub/fheroes2/assets/55348946/f3bfa213-07a5-4f99-9c6f-97d294943006

2024-04-05 22:15 UTC, Branikolog commented
I find it a bit weird too, when I see monster number as 0. If we consider this a default monster number, maybe it's better to use empty field or any non-numeric symbols (like "-" or so).

I can't adjust random monster numbers:
![image](https://github.com/ihhub/fheroes2/assets/55348946/3ca1143f-65eb-40fd-93d9-7d6ef76f13be)

2024-04-05 22:18 UTC, Branikolog commented on src/fheroes2/editor/editor_interface.cpp
> +                    if ( Dialog::SelectCount( _( "Set Monster Count" ), 0, 500000, monsterCount ) ) {
Russian translation has few:
![image](https://github.com/ihhub/fheroes2/assets/55348946/ee0d183b-d99d-482a-82f7-a9366381429f)

2024-04-06 06:40 UTC, idshibanov commented
> I find it a bit weird too, when I see monster number as 0. If we consider this a default monster number, maybe it's better to use empty field or any non-numeric symbols (like "-" or so).

That's the OG behaviour that I kept. To set a random amount you put a 0 there as well. It also represents exactly what's in the data, but I can see how it can confuse users.

> I've also experienced a case, when new monsters I place have non zero value.
> I can't adjust random monster numbers
> Creature numbers don't correspond those I've set in editor

Should be fixed now.

2024-04-06 11:28 UTC, Branikolog commented
Hi, @idshibanov 

>That's the OG behaviour that I kept. To set a random amount you put a 0 there as well. It also represents exactly what's in the data, but I can see how it can confuse users.

Indeed, but in the original game there's a hint explaining what "0" means.

![image](https://github.com/ihhub/fheroes2/assets/55348946/5ae37b4a-89ec-455a-81a6-9e7188ff1c99)

2024-04-06 21:52 UTC, Branikolog approved these changes
If we're going to come back with different dialog later, we can come up with another implementation for that "0" indicator.

2024-04-07 06:13 UTC, Stisen1 commented
How about doing the same thing as how you have 1-4 monsters CountasEnum = "few" in the monster.cpp? Something like: if number value === "0"; return whatever enum that correspond the default enum value for that class of monsters on a map's startup. So if you leave the number untouched, the box says "few | several | etc ". And when you close the dialog box, depending on input or left untouched, the number of monsters displayed will be either default enum or the one corresponding to input size... But uhm... You can't inspect that, if right-click makes you open the box.

2024-04-07 10:54 UTC, Branikolog commented
Hi, @Stisen1 !

> How about doing the same thing as how you have 1-4 monsters CountasEnum = "few" in the monster.cpp? Something like: if number value === "0"; return whatever enum that correspond the default enum value for that class of monsters on a map's startup. So if you leave the number untouched, the box says "few | several | etc ". And when you close the dialog box, depending on input or left untouched, the number of monsters displayed will be either default enum or the one corresponding to input size... But uhm... You can't inspect that, if right-click makes you open the box.

But how "Random Monster" object is going to handled then? 

Showing the number of creatures on right inspecting click seems like a convenient improvement for me, though.

2024-04-07 11:12 UTC, Stisen1 commented
Hi @Branikolog

> Showing the number of creatures on right inspecting click seems like a convenient improvement for me, though

Just make a bigger dialog box for random monsters, that show proportional enum values for each random monster tier.

2024-04-08 12:56 UTC, ihhub commented
@Stisen1 and @Branikolog , we will change this window later. Now we are targeting functionality.

2024-04-08 13:09 UTC, merged

2024-04-08 13:09 UTC, ihhub commented
@idshibanov thank you so much for this change!