Add the jailed hero details dialog in Editor
ihhub/fheroes2 pull request #8540
Opened 2024-04-04 17:11 UTC by Districh-ru

Relates to #6845
This dialog is based on Hero Details dialog and allows to set the jailed hero race.
![hero](https://github.com/ihhub/fheroes2/assets/113276641/c77faeed-5ffa-433e-851c-986b2020d6ee)

2024-04-05 15:56 UTC, ihhub requested changes
Hi @Districh-ru , I put several suggestions here. Would you mind to take a look at them?

2024-04-05 15:56 UTC, ihhub commented on src/fheroes2/maps/map_object_info.h
> +    const Maps::ObjectInfo & getObjectInfo( const Maps::ObjectGroup group, const int32_t objectType );
**objectType** should be **objectIndex**.

2024-04-05 15:56 UTC, ihhub commented on src/fheroes2/maps/map_object_info.h
> +    const Maps::ObjectInfo & getObjectInfo( const Maps::ObjectGroup group, const int32_t objectType );
Please remove `Maps` enumeration usage in this line as this is already under the same enumeration.

2024-04-05 15:56 UTC, ihhub commented on src/fheroes2/maps/map_format_info.h
> +        uint8_t jailedHeroRace{ Race::RAND };
Let's assign this value to 0 and do not use race here. Value 0 corresponds to NONE as a race which is even better to have to detect invalid values.

Also, I suggest to name this member as **race**. Simple as it sounds. Then we won't need an extensive comment for this. Moreover, we can also use this member to check that the hero's race is indeed the same as the sprites for them.

2024-04-05 15:56 UTC, ihhub commented on src/fheroes2/heroes/heroes.cpp
> +    }
As per proposal below we can simply do this:
```cpp
heroMetadata.race = static_cast<uint8_t>( _race );
```

2024-04-05 18:58 UTC, Districh-ru commented on src/fheroes2/maps/map_format_info.h
> +        uint8_t jailedHeroRace{ Race::RAND };
Hi, @ihhub, sure!
I also had thoughts about using this variable to store the normal hero's race but left it unchanged.

2024-04-05 18:59 UTC, Districh-ru commented on src/fheroes2/maps/map_object_info.h
> +    const Maps::ObjectInfo & getObjectInfo( const Maps::ObjectGroup group, const int32_t objectType );
OK)
I just moved this function without reviewing and changing it. :(

2024-04-06 05:52 UTC, ihhub approved these changes

2024-04-07 11:29 UTC, Branikolog approved these changes
Hi, @Districh-ru 
Everything works fine!
Just have a tiny question regarding faction name.
![image](https://github.com/ihhub/fheroes2/assets/55348946/28d90cc6-a235-4fc6-af45-d700a340e685)

Not sure it is going to look better, but have you tried to place faction name a little lower? Currently it is placed just above the bottom line of background crown image. For me personally, it looks like the text underlining, which is not pleasant to eye. Could it look better, of the name is shifted ~5px lower?

2024-04-07 11:46 UTC, Districh-ru commented
Hi, @Branikolog 
> Could it look better, of the name is shifted ~5px lower?

Yes, it looks a little better. We can replace the background image later if we find a suitable one. :)

![изображение](https://github.com/ihhub/fheroes2/assets/113276641/5c88c06f-a5f9-4aa7-ae7c-098b1ac1501f)

2024-04-08 03:09 UTC, merged

2024-04-08 03:09 UTC, ihhub commented
@Districh-ru , many thanks for this update!