Fixing Golden bow sprite glowing pixels
ihhub/fheroes2 pull request #8542
Opened 2024-04-04 21:34 UTC by shprotru

fix #8520

2024-04-04 21:38 UTC, shprotru commented
Please, help me to find the place where the small artifact icons should be processed.

2024-04-05 16:05 UTC, ihhub requested changes
Hi @shprotru , I left one suggestion. You also need to modify `ICN::ARTFX` and `ICN::OBJNARTI` resources.

2024-04-05 16:05 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    if ( _icnVsSprite[id][64].width() == 64 && _icnVsSprite[id][64].height() == 64 ) {
This check is not needed as Copy function will do the same.

2024-04-05 16:25 UTC, shprotru commented on src/fheroes2/agg/agg_image.cpp
> +                    if ( _icnVsSprite[id][64].width() == 64 && _icnVsSprite[id][64].height() == 64 ) {
done

2024-04-05 21:11 UTC, shprotru commented
Hi @ihhub ! I added `ICN::ARTFX`, PR already updated and ready to merge. Where I can see `ICN::OBJNARTI` in the game? At the global map Golden Bow artifact was checked by @Branikolog and there is no any glowing pixels.

2024-07-27 08:28 UTC, Districh-ru reviewed
Hi, @shprotru.
I've checked this fix and all is OK - the glowing pixels are properly replaced with the correct ones:

![изображение](https://github.com/user-attachments/assets/e472c30d-a6af-447b-b2bc-46397b620467) ![изображение](https://github.com/user-attachments/assets/1452dd7a-d338-4a9a-8f45-fc06151cf929)

Could you please, sync this PR with a master branch: we've added extra artifact image for Editor recently and used `case ICN::ARTFX:` in **agg_image.cpp** in the 4121 line.
And then updete this PR: the fix from current lines 3931-3934 should be moved the recently added `case ICN::ARTFX:` to properly merge this PR.

2024-07-28 04:12 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                else if ( _icnVsSprite[id].size() > 63 ) {
This one should be just `if` without `else`: we just check that we are going to fix image that exists and we do want to fix both images.
```suggestion
                if ( _icnVsSprite[id].size() > 63 ) {
```

2024-07-28 17:05 UTC, Districh-ru approved these changes

2024-09-21 04:27 UTC, ihhub commented
Hi @shprotru , please resolve merge conflicts for this branch.

2025-03-10 02:34 UTC, ihhub approved these changes

2025-03-10 02:36 UTC, ihhub commented
Let's move with this change. However, for any other similar issues we need to use a general approach for scanning an image and fixing such glowing pixels.

@shprotru , could you please rebase this branch from `master` branch as we are not able to merge it due to GitHub Actions checks?

2025-03-10 13:58 UTC, merged

2025-03-10 13:58 UTC, ihhub commented
@shprotru , thank you so much for the change!