Fix metadata handling and object loading for new map format
ihhub/fheroes2 pull request #8560
Opened 2024-04-09 12:13 UTC by ihhub

- fix a crash while removing monsters from a map without changing their properties
- fix a crash while loading a map with random castles
- add code to handle all needed metadata for objects
- add extra checks in debug build for map loading
- fix Abandoned Mines update after capturing
- fix inability to select any players except the one placed on a map

Relates to #6845

2024-04-09 18:05 UTC, Districh-ru requested changes
Hi, @ihhub, I left several comments. Could you please check them when you have time?

There is also an issue: the Random Castles are not correctly updated because there is no `BUILD_CASTLE` built. I'll fix it in the Castle Details PR.

2024-04-10 03:01 UTC, Districh-ru commented on src/fheroes2/world/world_loadmap.cpp
> +                    Maps::UpdateCastleSprite( castle->GetCenter(), castle->GetRace(), castle->isCastle(), true );
@ihhub, we can do a fix for Random Castles update by replaceing `castle->isCastle()` with `townObjects[object.index].objectType == MP2::OBJ_RANDOM_CASTLE`:
```suggestion
                    Maps::UpdateCastleSprite( castle->GetCenter(), race, castle->townObjects[object.index].objectType == MP2::OBJ_RANDOM_CASTLE, true );
```

2024-04-10 03:03 UTC, ihhub commented on src/fheroes2/world/world_loadmap.cpp
> +                    Maps::UpdateCastleSprite( castle->GetCenter(), castle->GetRace(), castle->isCastle(), true );
Hi @Districh-ru , I've fixed it another way :)

2024-04-10 03:04 UTC, Districh-ru commented on src/fheroes2/world/world_loadmap.cpp
> +                    race = static_cast<uint8_t>( kingdom.GetRace() );
For the neutral player we should pick a really random race. :)
```suggestion
                    race = ( color == Color::NONE ) ? Race::Rand() : static_cast<uint8_t>( kingdom.GetRace() );
```

2024-04-10 14:20 UTC, Districh-ru approved these changes
👍

2024-04-11 01:39 UTC, merged