Extend button resizing to include height
ihhub/fheroes2 pull request #8562
Opened 2024-04-09 13:52 UTC by zenseii

This PR expands the button resizing function to allow for buttons with varying heights with or without varying widths.

Note: The empty vertical button had to be reduced from 121px in height to 120px for its height to be evenly divided into 5 parts when increasing the height.

This means that vertical buttons can now be taller than originally, allowing for longer words:
![image](https://github.com/user-attachments/assets/b4c7377d-1867-448b-a8b7-7442bc7b0f56)
Note: In the future buttons like these on the same screen should have a shared minimum height to ensure symmetric sizes.

This is an animation showing the steps of generating a new button with increased height and width:
![buttonExpansion](https://github.com/user-attachments/assets/34a6d497-c9f4-4068-9010-89635ce7d846)

2024-09-04 17:56 UTC, Districh-ru requested changes
Hi, @zenseii, I left several comments. Could you please take a look when you have time.

2024-09-04 17:56 UTC, Districh-ru commented on src/fheroes2/heroes/heroes_dialog.cpp
> +                                          fheroes2::AGG::GetICN( ICN::BUTTON_VERTICAL_DISMISS, 0 ), fheroes2::AGG::GetICN( ICN::BUTTON_VERTICAL_DISMISS, 1 ),
We can call `GetICN()` once for `ICN::BUTTON_VERTICAL_DISMISS, 0`:
```suggestion
    const fheroes2::Sprite & dismissPressed = fheroes2::AGG::GetICN( ICN::BUTTON_VERTICAL_DISMISS, 0 );
    fheroes2::ButtonSprite buttonDismiss( dst_pt.x, dst_pt.y - dismissPressed.height() / 2,
                                          dismissPressed, fheroes2::AGG::GetICN( ICN::BUTTON_VERTICAL_DISMISS, 1 ),
```

2024-09-04 17:56 UTC, Districh-ru commented on src/fheroes2/heroes/heroes_dialog.cpp
> +                                     { dst_pt.x, dst_pt.y - fheroes2::AGG::GetICN( ICN::BUTTON_VERTICAL_DISMISS, 0 ).height() / 2 }, { -3, 5 } );
The same comment as the previous one:
```suggestion
        const fheroes2::Sprite & dismissPressed = fheroes2::AGG::GetICN( ICN::BUTTON_VERTICAL_DISMISS, 0 );
        fheroes2::addGradientShadow( dismissPressed, display, { dst_pt.x, dst_pt.y - dismissPressed.height() / 2 }, { -3, 5 } );
```

2024-09-04 17:56 UTC, Districh-ru commented on src/fheroes2/heroes/heroes_dialog.cpp
> +                                     { dialogRoi.x + 9, dst_pt.y - fheroes2::AGG::GetICN( ICN::BUTTON_VERTICAL_PATROL, 0 ).height() / 2 }, { -3, 5 } );
And here too :)
```cpp
    const fheroes2::Sprite & patrolPressed = fheroes2::AGG::GetICN( ICN::BUTTON_VERTICAL_PATROL, 0 );
    const int32_t patrolOffsetY = dst_pt.y - patrolPressed.height() / 2;
    fheroes2::ButtonSprite buttonPatrol( dst_pt.x, patrolOffsetY, patrolPressed, fheroes2::AGG::GetICN( ICN::BUTTON_VERTICAL_PATROL, 1 ) );
    if ( isEditor ) {
        fheroes2::addGradientShadow( patrolPressed, display, { dialogRoi.x + 9, patrolOffsetY }, { -3, 5 } );
```

2024-09-05 16:48 UTC, Districh-ru approved these changes
👍

2024-09-18 14:44 UTC, ihhub approved these changes

2024-09-18 14:44 UTC, merged

2024-09-18 14:44 UTC, ihhub commented
@zenseii , many thanks for these changes!