Update of Ukrainian Translation
ihhub/fheroes2 pull request #8572
Opened 2024-04-13 05:54 UTC by ZaHaDumGoth

Mostly hotkey and some empty rows founded.

2024-04-21 06:04 UTC, ihhub requested changes
Hi @ZaHaDumGoth , I left one comment here. Could you please take a look?

2024-04-21 06:04 UTC, ihhub commented on files/lang/uk.po
>  msgstr ""
{tiles} must not be translated.

2024-04-21 06:55 UTC, ZaHaDumGoth commented on files/lang/uk.po
>  msgstr ""
Fixed it.

2024-04-21 09:16 UTC, ihhub approved these changes

2024-05-05 13:40 UTC, merged

2024-05-05 13:40 UTC, ihhub commented
@ZaHaDumGoth , many thanks for this update!