Implement Castle/Town details dialog in Editor
ihhub/fheroes2 pull request #8574
Opened 2024-04-13 19:51 UTC by Districh-ru

Relates to https://github.com/ihhub/fheroes2/issues/6845

Build restriction is currently not available in the game (except castle build restriction), but will be added soon in new PR.

![img](https://github.com/ihhub/fheroes2/assets/113276641/24f49746-022a-495e-b320-1ea95561db0b)

2024-04-13 21:11 UTC, Districh-ru commented
Hi, @zenseii, could you please check the newly added phrases when you have time?

2024-04-14 11:42 UTC, Branikolog commented
Hello, @Districh-ru !
I made a couple of tests and I admit to say, that selecting town structures is nice and convenient!

I've found a few issues, could you, please, try to fix them, when you have time?

An assertion occurs, when I enter a random town/castle, where I placed 3rd upgraded 6-tier structure.

[1.zip](https://github.com/ihhub/fheroes2/files/14970431/1.zip)

Random town placed on a map always appears to be the same as the pre-selected town type. I.e. it is always sorceress town on the map I attached.

![image](https://github.com/ihhub/fheroes2/assets/55348946/2259ad04-75a2-4ac5-bf37-dce5ac309b7d)
Not sure about the wording "1st level grow", but I cannot suggest any better, though. I hope, @zenseii can help us with this name to be maximum pleasant and accurate.

Random town structures icons look empty in my personal point of view. I believe, we need to place some kind of neutral icon there. Unfortunately, there's nothing suitable in game resources, suppose. Feel free to postpone working on this for later PRs...
![image](https://github.com/ihhub/fheroes2/assets/55348946/90d45730-2c6e-42ae-a8a9-de08f2deb95f)

2024-04-14 12:28 UTC, Branikolog commented
![image](https://github.com/ihhub/fheroes2/assets/55348946/fe41c393-d0ef-4758-b539-f03b2dc4d8ce)

Maybe it's just matter of the personal preference, but showing the text "default building" for each icon looks too overflowed.
Maybe simply making every icon and green header darker (or applying some sort of other image filtering (blurring/saturating)) allows players to understand, that none adjustments were made for the town structure tree yet?

2024-04-14 12:29 UTC, Districh-ru commented
> An assertion occurs, when I enter a random town/castle, where I placed 3rd upgraded 6-tier structure.

Hello, @Branikolog, it should be fixed now. Thanks for testing!

> Random town placed on a map always appears to be the same as the pre-selected town type. I.e. it is always sorceress town on the map I attached.

After we implement map properties dialog we will be able to set what race a player can play. It will be done in the other PR
>Not sure about the wording "1st level grow", but I cannot suggest any better, though. 

It is taken from the original Editor, and I also could not find a better phrase. :(
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/6c1410ad-bf92-4cb3-9d5c-e0167654ca26)


> Random town structures icons look empty in my personal point of view. I believe, we need to place some kind of neutral icon there. Unfortunately, there's nothing suitable in game resources, suppose. Feel free to postpone working on this for later PRs... !

Let's do it later. We can put some images from the game. In example
- use the image from the tavern dialog for the tavern: ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/a175b98e-362d-44c5-ae41-0b19c6077f89)
- place a boat over the background for the shipyard: ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/97b29547-5872-4d8e-bf6e-9943c869304a)
- ...

2024-04-14 12:37 UTC, Districh-ru commented
> Nice catch, @Branikolog!
> 
> The lvl1 creature growth boost building is called the "Horde Building" in the manual, I've heard players call it other things too, but I see no problem in using the official name.
> 
> As for description: "The Horde Building increases the growth rate of the level 1 creatures by 8 per week."

Thanks, @zenseii !!

2024-04-14 12:56 UTC, Districh-ru commented
> Maybe it's just matter of the personal preference, but showing the text "default building" for each icon looks too overflowed. Maybe simply making every icon and green header darker (or applying some sort of other image filtering (blurring/saturating)) allows players to understand, that none adjustments were made for the town structure tree yet?

Sure, we can do so:

![изображение](https://github.com/ihhub/fheroes2/assets/113276641/2f4ac9c9-ad84-4c0b-9f8e-845b8e7a2240)

2024-04-14 13:07 UTC, Branikolog commented
@Districh-ru 
Well, It looks not as well as I expected. 🤔 
Is it possible, to make icons even darker? Blurring feels not realy relevant... The images looks too smooth comparing to the rest of the game.

Btw. with the current troops field implementation it's not impossible to adjust any neutral town to have 0 guardians. I suppose, we need same "default" state as we implement for any other hero/building fields.
![image](https://github.com/ihhub/fheroes2/assets/55348946/a4c84b24-816f-45d7-b4f7-1cdf4c2f7d31)

2024-04-14 13:17 UTC, Districh-ru commented
> @Districh-ru Well, It looks not as well as I expected. 🤔 Is it possible, to make icons even darker? Blurring feels not realy relevant... The images looks too smooth comparing to the rest of the game.

I've reduced the blurring and made the icons darker.
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/c1d3aee3-4925-4ff0-8da8-c8aa24b1d92d)

> Btw. with the current troops field implementation it's not impossible to adjust any neutral town to have 0 guardians. I suppose, we need same "default" state as we implement for any other hero/building fields.

Default army is applicable only to the neutral towns ... I'll try to find a possible solution

2024-04-14 13:36 UTC, Branikolog commented
@Districh-ru 
Well, I like the darker version more.

I also noticed, there are short building descriptions in the town screen. I think, it would be more useful to show the same information window to the castle construction window we have in game, so players could check the whole building requirements (resources + other buildings).
![image](https://github.com/ihhub/fheroes2/assets/55348946/779b8c01-5286-436f-a063-00e3a38dd0cf)

2024-04-14 15:19 UTC, Districh-ru commented
@Branikolog, done:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/8a56ebda-5f15-4694-9b5d-fa531bb0248a)

2024-04-14 18:10 UTC, Districh-ru commented
> I also noticed, there are short building descriptions in the town screen. I think, it would be more useful to show the same information window to the castle construction window we have in game, so players could check the whole building requirements (resources + other buildings).

@Branikolog, I've added the required buildings.
Adding the required resources to the standard info dialog is a bit tricky. What about adding it later? :)

2024-04-17 06:05 UTC, ihhub requested changes
Hi @Districh-ru , I left several comments here. Would you mind to take a look at them when you have time?

2024-04-19 19:04 UTC, Branikolog commented
@Districh-ru 

>Adding the required resources to the standard info dialog is a bit tricky. What about adding it later? :)

The requirements you've added is the most important. Resources could be added later for sure!

Btw, while checking army in castle dialog I experience not instant window fading. Maybe it is related to my weak PC and the development build, but it looks not well though.
I've tried to capture this effect. Not sure it will be noticeable on the video...

https://github.com/ihhub/fheroes2/assets/55348946/1decfb6a-dfe3-4386-96c7-8690a9b930cf

2024-04-20 08:06 UTC, Districh-ru commented on src/fheroes2/maps/map_format_info.h
> +                type = Monster::RANDOM_MONSTER;
Monster::UNKNOWN is 0 and stands for an empty (not random) slot. Castles can have empty army.
I made `-1` to determine that default army should be used.

2024-04-20 08:10 UTC, Districh-ru commented on src/fheroes2/world/world_loadmap.cpp
> +                        == ( townObjects[object.index].metadata[1] == 0 ) );
If a castle has only a castle-building and no other buildings, it is impossible to determine whether all other buildings are not built (forced by the map creator) or if they must be built according to a default (random) pattern. So we need `bool customBuildings` to determine this.

2024-04-20 08:10 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +                    if ( castleMetadata != _mapFormat.castleMetadata.end() ) {
I've converted it to assertion.

2024-04-20 08:21 UTC, Districh-ru commented
> Btw, while checking army in castle dialog I experience not instant window fading.

Hi, @Branikolog, this issue should be fixed now.

2024-04-20 08:50 UTC, Branikolog commented
Hi, @Districh-ru !

>Hi, @Branikolog, this issue should be fixed now.

Thanks! It works good now!

An assertion occurs now when I try to edit random castle. Could you, please, search for the root of this problem?

2024-04-20 09:07 UTC, Districh-ru commented
> An assertion occurs now when I try to edit random castle (belonging to a player). Could you, please, search for the root of this problem?

@Branikolog, thanks for testing. The root was in changed conditions to determine whether the army is default (for Neutral player). Now this issue should be fixed.

2024-04-20 09:29 UTC, Branikolog approved these changes

2024-04-21 04:30 UTC, ihhub requested changes
Hi @Districh-ru , I left just few small remarks here. Could you please check them?

2024-04-21 04:30 UTC, ihhub commented on src/fheroes2/castle/buildinginfo.cpp
> +    std::string description;
For readability purposes could you please add an empty line after this one?

2024-04-21 04:30 UTC, ihhub commented on src/fheroes2/castle/buildinginfo.cpp
> +    return description;
For readability purposes could you please add an empty line before this one?

2024-04-21 04:30 UTC, ihhub commented on src/fheroes2/castle/castle.cpp
> +    if ( dwelling2 && dwelling2 >= Rand::Get( 1, 100 ) ) {
We don't need the first condition which is **dwelling2 > 0** as the second condition covers it.

2024-04-21 04:30 UTC, ihhub commented on src/fheroes2/editor/editor_castle_details_window.cpp
> +                    std::move( requirement.begin(), requirement.end(), std::back_inserter( description ) );
I am not sure that this is more effective than just `description += requirement;` We are essentially moving every byte (8-bit) which is very slow since we are running on 32- or 64-bit machines. Copying a string should be faster.

2024-04-21 04:35 UTC, ihhub approved these changes

2024-04-21 04:54 UTC, merged

2024-04-21 04:54 UTC, ihhub commented
@Districh-ru , awesome job!