AI should determine best skill when leveling up heroes
ihhub/fheroes2 pull request #8591
Opened 2024-04-25 01:53 UTC by idshibanov

Currently AI just rolls randomly when picking a new secondary skills. This decision should be driven by a value estimation, same as everything else.

2024-04-30 12:12 UTC, ihhub commented
Hi @idshibanov , please rebase your branch from master to fix GitHub Actions.

2024-05-05 03:52 UTC, ihhub requested changes
Hi @idshibanov , I put several comments here. Could you please take a look at them when you have time?

2024-05-05 03:52 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            // UNKNOWN skill can be a valid check
Please add an assertion here to make sure that we don't hit it or when we add a new skill.

2024-05-05 03:52 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +}
We can move the implementation of these methods to the header file. A compiler will inline them.

2024-05-05 03:52 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +    return waterPercentage;
If this member is named as **percentage** then its value should be roughly from 0 to 100. Right now it is a normalized value from 0 to 1.

2024-05-05 03:52 UTC, ihhub commented on src/fheroes2/world/world_regions.cpp
> +    mapRoughness = terrainPenalty / ( ( passableTileCount - waterCount ) * Maps::Ground::defaultGroundPenalty );
I would suggest to at least add an assertion that **passableTileCount** is more than 0. It is a very tiny chance of this but just in case.

2024-05-05 03:52 UTC, ihhub commented on src/fheroes2/world/world_regions.cpp
> +    mapRoughness = terrainPenalty / ( ( passableTileCount - waterCount ) * Maps::Ground::defaultGroundPenalty );
**( passableTileCount - waterCount )** can be zero on maps with only water.

2024-05-05 03:52 UTC, ihhub commented on src/fheroes2/world/world_regions.cpp
> +    waterPercentage = waterCount / passableTileCount;
Since we want to have percentage and this value shouldn't be extremely precise we can have this variable as **uint8_t**.

2024-05-05 03:52 UTC, ihhub commented on src/fheroes2/world/world.cpp
> +    return mapRoughness;
The name of method is get**Land**Roughness while the member is called **map**Roughness. I suggest to be consistent.

2024-05-05 13:54 UTC, ihhub requested changes
Hi @idshibanov , I left few more small comments here. Would you mind to take a look once you have spare time?

2024-05-05 13:54 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +    double getSecondarySkillValue( const Heroes & hero, const Skill::Secondary & skill )
Since all values returned by this function positive as well as they are not actually floating values I suggest to return **uint32_t** value which simplifies calculations and comparison of values.

2024-05-05 13:54 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            if ( leftValue < 300.0 ) {
Magic number! :)

A small comment explaining why this  value was chosen would be great to have.

2024-05-05 13:54 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +        const double rightValue = getSecondarySkillValue( hero, right );
I suggest to put these variables before DEBUG_LOG and use them for logging.

2024-05-06 00:55 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +    double getSecondarySkillValue( const Heroes & hero, const Skill::Secondary & skill )
It has to stay double so we can reuse it later in `getObjectValue` calls for the witch hut/etc. Values aren't that arbitrary; they were based on other estimates there.

2024-05-06 12:48 UTC, crypt47 commented
Hello, I've always wanted to ask if Mysticism has any value. It looks like it has pretty much scores in descision making code, but it only gives you something like 4 sp/day at max. This is pretty low, especially for magic heroes who may use 100 sp and more during one battle.

2024-06-02 14:33 UTC, ihhub requested changes
Hi @idshibanov , I left several comments here. Would you mind please to take a look at them?

2024-06-02 14:33 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +        const double leftValue = getSecondarySkillValue( hero, left );
Please add an empty line after if-body for better code readability.

2024-06-02 14:33 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +        const int type = skill.Skill();
Please add an assertion to verify that **skill** is valid.

2024-06-02 14:33 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +        return leftValue > rightValue ? left : right;
Please add an empty line after if-body for better code readability.

2024-06-02 14:33 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            return left.Level() == Skill::Level::BASIC ? left : right;
This logic is not entirely accurate (assuming that we don't know how values are being calculated in **getSecondarySkillValue()**:
```cpp
if ( leftValue < 300.0 ) {
    return left.Level() == Skill::Level::BASIC ? right : left; // <--- here looks okay since right and left can be both of BASIC level
}

return left.Level() == Skill::Level::BASIC ? left : right; // <-- here it NOT okay since right can have higher level than left
```
Also, we should consider randomness of a choice. Right now we are fixed on one of them.

2024-06-02 14:33 UTC, ihhub commented on src/fheroes2/world/world.h
> +    double landRoughness = 1.0;
Let's follow new members naming:
```cpp
uint8_t _waterPercentage{ 0 };
double _landRoughness{ 1.0 };
```

2024-06-02 14:33 UTC, ihhub commented on src/fheroes2/world/world_regions.cpp
> +    const int landTiles = passableTileCount - waterCount;
This value must always be greater than 0. We can add an assertion to check this.

2024-06-02 14:33 UTC, ihhub commented on src/fheroes2/world/world_regions.cpp
> +    double terrainPenalty = 0;
Use **uint32_t** for this variable for faster calculation in the loop. Then at the very end we can convert it to double.

2024-06-02 14:33 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +        if ( hero.GetLevelSkill( skill.first ) >= level ) {
Please use **type** here.

2024-06-02 14:33 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            return ( roughness > 1.25 ) ? 1000.0 : ( roughness > 1.1 ) ? 250.0 : 100.0;
What if the value is lower than 1?

2024-06-02 14:33 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            return 0;
This should not happen, please remove such a case and it should be handled by **default** case.

2024-06-02 14:33 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            const double roughness = world.getLandRoughness();
This skill value should depend on AI role as well.

2024-06-02 14:33 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            return level == Skill::Level::BASIC ? 2500.0 : 1000.0;
This skill value should depend on AI role as well. Couriers don't care about Wisdom so much. The same for many skills below.

2024-06-29 00:57 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            return 0;
No, this is a valid case in case a hero only get a single skill choice.

2024-06-29 00:58 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            const double roughness = world.getLandRoughness();
I don't see how AI role influences this. If map has a lot of swamp and desert ANY hero should have this skill.

2024-06-29 01:00 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            return level == Skill::Level::BASIC ? 2500.0 : 1000.0;
For example, Town Portal/Dimension Door would help out a Courier a lot. Hero development is a long-term investment. Also, a courier might change role later on. Bigger spellbook always helps.

2024-06-29 01:03 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            return ( roughness > 1.25 ) ? 1000.0 : ( roughness > 1.1 ) ? 250.0 : 100.0;
Then this skill has minimal value; a 100. In most cases it's undesirable, don't see an issue with that.

2024-06-29 01:32 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +        const int type = skill.Skill();
Don't think it's needed here. Skill choice might be invalid.

2024-06-29 02:38 UTC, idshibanov commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +            return left.Level() == Skill::Level::BASIC ? left : right;
In the second case it's a valuable skill. Basic level then is more desirable than Advanced or Expert in order to secure the choice. I think the logic is accurate.

2024-07-24 13:38 UTC, oleg-derevenetz commented
Hi @idshibanov I rebased this PR against `master` to resolve conflicts after #8986, could you please take a look, just in case?

2024-07-25 19:09 UTC, oleg-derevenetz approved these changes

2024-07-29 14:17 UTC, ihhub approved these changes

2024-07-29 14:34 UTC, merged

2024-07-29 14:34 UTC, ihhub commented
@idshibanov , thank you so much for this improvement!