Add multi-line text edit feature to edit Sign and Bottle texts and some fixes for text rendering
ihhub/fheroes2 pull request #8604
Opened 2024-05-03 19:19 UTC by Districh-ru

Relates to https://github.com/ihhub/fheroes2/issues/6845
This PR adds ability to input long phases in the multi-line input dialog. It adds ability to input Sign and Bottle text in Editor. It will be also used to input map description in the next PR.

https://github.com/ihhub/fheroes2/assets/113276641/46c71bda-3a35-4ec7-b305-dd1dafd9e8b4

This PR also fixes:
- incorrect cursor position calculation for texts with spaces;
- incorrect multi-line text width calculation for `UniformedVerticalAlignment` texts;
- incorrect cutting of words for multi-font text cases:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/be96c998-cc6a-4015-934b-8d5d4c8a661d) **=>>** ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/343ba1b1-126b-4e98-b6bc-9d9febed458e)

2024-05-04 11:54 UTC, ihhub requested changes
Hi @Districh-ru , I left several comments here. Would you mind to take a look at them when you have spare time?

2024-05-04 11:54 UTC, ihhub commented on src/fheroes2/gui/ui_text.h
> +    // Returns the character position number in the 'text' string.
This function does **not** belong to this file. This file should contain only common classes and structures and not anything specific. So, the original place `ui_tool.h|cpp` was a valid place for this function.

We can expose **CharHandler** class within **ui_text.h** file to avoid having this function here.

2024-05-04 11:54 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +    const int32_t frameBoxHeight = 10 + titleHeight + textbox.height( BOXAREA_WIDTH ) + 10 + inputAreaHeight + keyBoardButtonExtraHeight;
We can cache `textbox.height( BOXAREA_WIDTH )` value.

2024-05-04 11:54 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +        else if ( le.MousePressRight( buttonCancel.area() ) ) {
If we added `else` here then please remove an empty line above.

2024-05-04 11:54 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +            , _charLimit( fheroes2::AGG::getCharacterLimit( _fontType.size ) )
I suggest to use `fontType.size` over `_fontType.size` as using class members already in the initialization list is risky. This code is of course absolutely valid but it's better to be safe.

2024-05-04 11:54 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +                assert( 0 ); // Did you add a new font size? Please add implementation.
Please add **break** here as well.

2024-05-04 11:54 UTC, ihhub commented on src/fheroes2/gui/ui_text.h
> +        size_t getTextInputCursorPosition( const size_t currentTextCursorPosition, const Point & pointerCursorOffset, const Rect & textRoi );
This method should **not** exist for this class. This is a special case which is not related to text class itself. As of now I see no easy way to remove it so let's skip this comment and come back to it once we address other comments.

2024-05-04 11:54 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +        {
Please remove one level of parenthesis.

2024-05-04 11:54 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +        int32_t _spaceCharWidth;
These members can be const.

2024-05-04 11:54 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +            return ( character == spaceChar || _isValid( character ) || character == lineSeparator );
Let's move **isSpaceChar** function declaration above this class and use it here and at line 64.

2024-05-04 11:54 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
>      void getMultiRowInfo( const uint8_t * data, const int32_t size, const int32_t maxWidth, const fheroes2::FontType & fontType, const int32_t rowHeight,
While code duplication is bad I think we should have 2 functions for this case rather than handling 2 different cases in one function. One function should behave exactly as it should be before. The other one should accept only `std::deque<int32_t>` which will contain the number of characters per line. We would have code duplication but it would be much easier to read the code. What do you think?

2024-05-04 13:10 UTC, Districh-ru commented on src/fheroes2/gui/ui_text.h
> +        size_t getTextInputCursorPosition( const size_t currentTextCursorPosition, const Point & pointerCursorOffset, const Rect & textRoi );
I left a TODO to fix it in the future.

2024-05-04 13:36 UTC, Districh-ru commented on src/fheroes2/gui/ui_text.cpp
>      void getMultiRowInfo( const uint8_t * data, const int32_t size, const int32_t maxWidth, const fheroes2::FontType & fontType, const int32_t rowHeight,
I've updated this function to return both vectors.

2024-05-04 13:54 UTC, ihhub requested changes
Hi @Districh-ru , I added few more comments here. Can you please take a look at them?

2024-05-04 13:54 UTC, ihhub commented on src/fheroes2/gui/ui_text.h
> +        }
The implementation for these methods should be in **ui_text.cpp** file as we are exposing too much for the logic for this class.  We are also adding extra dependencies in header files by using logic for these methods here.

Once we move these method's implementation **isLineSeparator**, **isSpaceChar** can be normal functions as before (instead of current `fheroes2::CharHandler::isSpaceChar()`  calls).

2024-05-04 13:54 UTC, ihhub commented on src/fheroes2/gui/ui_text.h
> +        }
Please move the implementation to the cpp file.

2024-05-04 13:54 UTC, ihhub commented on src/fheroes2/gui/ui_text.h
> +    class CharHandler
Please move this class at the bottom of the file just before `bool isFontAvailable()` function since this class is used occasionally outside this file.

2024-05-04 13:54 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +                          std::deque<fheroes2::Point> & offsets, std::vector<int32_t> & charsInLine )
I suggest to create a structure:
```cpp
struct TextLineInfo
{
    fheroes2::Point offset;

    int32_t characterCount{ 0 };
};
```

Then we won't need to handle 2 input containers. Right now these 2 input containers must match by size but we don't verify it and they are different types.

2024-05-04 13:54 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
>              offsets.emplace_back();
If we use proposed structure we can still have only one call to emplace back a new element.

2024-05-04 13:54 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +                    offset->x = lineWidth;
Could you please explain why we modified the logic here?

2024-05-04 13:54 UTC, ihhub commented on src/fheroes2/gui/ui_text.h
> +        size_t getTextInputCursorPosition( const size_t currentTextCursorPosition, const Point & pointerCursorOffset, const Rect & textRoi );
Please make it as a normal function as **isFontAvailable()**. Having this method automatically ponders a question: why other classes don't have it. Making it just a function removes these questions.

2024-05-04 13:54 UTC, ihhub commented on src/fheroes2/gui/ui_text.h
> +        void fitToOneRow( const int32_t maxWidth, const bool ignoreSacesAtEnd = true );
**ignoreSacesAtEnd** is misspelled. Also, it is not clear: at the end of line or text?

2024-05-04 13:54 UTC, ihhub commented on src/fheroes2/gui/ui_text.h
> +    class CharHandler
I suggest to name it as `FontCharHandler` as seeing `fheroes2::CharHandler` in the code outside this file might confuse developers.

2024-05-04 14:42 UTC, Districh-ru commented on src/fheroes2/gui/ui_text.cpp
> +                    offset->x = lineWidth;
Initially for the Multi-Font texts we were counting the the `lineWidth` from **0** and we added it to the `offset->x` that contains the width from the previous font.
Now we count `lineWidth` from this previous `offset->x` value, so now we can use `=` instead `+=`. I thought that it will be a little faster)
For the non-Multi-Font texts we always count from **0** and here we were doing ` = 0 + lineWidth `.

2024-05-04 15:05 UTC, Districh-ru commented on src/fheroes2/gui/ui_text.h
> +        size_t getTextInputCursorPosition( const size_t currentTextCursorPosition, const Point & pointerCursorOffset, const Rect & textRoi );
Other classes also do not have `fitToOneRow()` method. :)
In this method we use `_text`, `_fontType` fields and `.width( maxWidth )` method.
If we want to make it as a separate function we will need one again to make inside it the `fheroes2::Text` object and do not forget to insert the cursor ('_') to the original text (`_text` in the existing object already has '_' inserted).
So first we need to make `Text` class helper functions to get Info from the `Text` object to set cursor position...

2024-05-04 15:33 UTC, Districh-ru commented on src/fheroes2/gui/ui_text.h
> +        size_t getTextInputCursorPosition( const size_t currentTextCursorPosition, const Point & pointerCursorOffset, const Rect & textRoi );
Done!)

2024-05-04 21:44 UTC, Branikolog commented
Hi, @Districh-ru !

I've found a problem with window size for all events, signs all other dialog windows:
![image](https://github.com/ihhub/fheroes2/assets/55348946/0576ec78-e83c-4ff4-8ead-1023a428b4d4)

Can you, please, fix it?

2024-05-05 02:32 UTC, ihhub commented
@Branikolog , the bug should be fixed now.

2024-05-05 02:43 UTC, ihhub commented
Hi @Districh-ru , I made the following changes in this pull request:
- removed extra `fheroes2::` namespace usage (it was in new and old code)
- do not pass **FontType** by reference by rather by value. The size of **FontType** is just 2 bytes while reference has size of 4 or 8 bytes
- fix rendering bug for multi-line text

2024-05-05 02:44 UTC, ihhub approved these changes

2024-05-05 10:26 UTC, Branikolog approved these changes
👍

2024-05-05 10:33 UTC, merged

2024-05-05 10:33 UTC, ihhub commented
@Districh-ru , huge thanks for these changes!