Update of Ukrainian Translation
ihhub/fheroes2 pull request #8625
Opened 2024-05-06 17:51 UTC by ZaHaDumGoth

2024-05-20 13:01 UTC, ihhub requested changes
Hi @ZaHaDumGoth , I left comment here. Could you please take a look at it once you have time?

2024-05-20 13:01 UTC, ihhub commented on files/lang/uk.po
> +msgstr "fheroes2 Resurrection Team представляє"
I think the word **team** must be translated as well.

2024-05-20 13:08 UTC, ZaHaDumGoth commented on files/lang/uk.po
> +msgstr "fheroes2 Resurrection Team представляє"
That is a complete name or only "fheroes2 Resurrection" ?
Or it means team as personnel/people related to project with name "fheroes2 Resurrection" ?

2024-05-20 13:09 UTC, ihhub commented on files/lang/uk.po
> +msgstr "fheroes2 Resurrection Team представляє"
`fheroes2 Resurrection` is a name of a team of people who are making this project. Like "Piano movers" team. Therefore, `fheroes2 Resurrection` is the complete name.

2024-05-20 13:12 UTC, ZaHaDumGoth commented on files/lang/uk.po
> +msgstr "fheroes2 Resurrection Team представляє"
Clear. Thanks. I fixed it minute ago and did Commit.

2024-05-20 13:17 UTC, ihhub commented on files/lang/uk.po
> +msgstr "fheroes2 Resurrection Team представляє"
Emm... I don't see an extra commit. Are you sure that you committed to the same branch as this pull request has?

2024-05-20 13:40 UTC, ZaHaDumGoth commented on files/lang/uk.po
> +msgstr "fheroes2 Resurrection Team представляє"
I presse Save in PoEdit, Pressed Commit in GitHub DSKT and Pull Origin, but some conflik appeared
![Screenshot_1](https://github.com/ihhub/fheroes2/assets/161311240/6356c90d-2972-4822-8876-de40b069c996)

2024-05-20 13:42 UTC, ihhub commented on files/lang/uk.po
> +msgstr "fheroes2 Resurrection Team представляє"
Let's do this way: paste the update translation for this string here. I will replace it.

2024-05-20 13:53 UTC, ZaHaDumGoth commented on files/lang/uk.po
> +msgstr "fheroes2 Resurrection Team представляє"
Ok, here is translated row - Команда fheroes2 Resurrection представляє

2024-05-20 13:59 UTC, ihhub approved these changes

2024-05-21 15:34 UTC, ZaHaDumGoth commented on files/lang/uk.po
>  #, fuzzy
Please clarify where is this text in game.

2024-05-21 15:36 UTC, ZaHaDumGoth commented on files/lang/uk.po
> +msgstr "Місцева платформа донатів|https://www.patreon.com/fheroes2"
Fixed that.

2024-05-21 15:36 UTC, ZaHaDumGoth commented on files/lang/uk.po
> +msgstr "локальна соціальна мережа|https://www.facebook.com/groups/fheroes2"
Fixed.

2024-05-21 15:38 UTC, ZaHaDumGoth commented on files/lang/uk.po
> +msgstr "випадкова раса|істоти 6-го рівня"
Fixed all.

2024-05-22 01:29 UTC, merged

2024-05-22 01:29 UTC, ihhub commented
@ZaHaDumGoth , a bunch of thanks for the update!