Implement Map Specifications dialog for Editor
ihhub/fheroes2 pull request #8636
Opened 2024-05-11 17:22 UTC by Districh-ru

relates to https://github.com/ihhub/fheroes2/issues/6845

![screen](https://github.com/ihhub/fheroes2/assets/113276641/6ee6a057-2968-46d8-9807-fcf3b38b2ceb)

2024-05-12 05:37 UTC, Branikolog commented
Hi, @Districh-ru 

I've started looking into your PR. This dialog looks nice! :)
I'm only concerned about player selection icons. Currently you've implemented 4 icons: no, player, computer player, computer player or human, human only.
What "human only" option is about? Does it means AI will never control this faction if I set more than one human players for a single scenario? :)
Initially, on each single game start we just select between available colours (colours, that are allowed to be both human and AI)
I don't think we need "only human" option at all. Currently, trying to save a map with 2 "humans only" selected crashes the application, crashes load dialog showing this map later, and even crashes save dialog, so I cannot overwrite it. :)

![image](https://github.com/ihhub/fheroes2/assets/55348946/382bd31e-96be-4b45-8110-28f812d3bcbb)


Map Description field could be either empty from the beginning, or showing "No description", and after a click on it you should be introduced to an empty field. Currently, description text field appears with a text, which a player should delete first, before typing a new description.

Description field should have scrollbars:
![image](https://github.com/ihhub/fheroes2/assets/55348946/43065044-296d-44aa-a3a3-d14b4317c313)

Somehow it has an empty first row:
![image](https://github.com/ihhub/fheroes2/assets/55348946/7b3808a3-91ed-4ea7-ab74-90fc76f49180)

2024-05-12 09:35 UTC, Districh-ru commented
Hi, @Branikolog 
 
> I've started looking into your PR. This dialog looks nice! :) I'm only concerned about player selection icons. Currently you've implemented 4 icons: no, player, computer player, computer player or human, human only. What "human only" option is about? Does it means AI will never control this faction if I set more than one human players for a single scenario? :) Initially, on each single game start we just select between available colours (colours, that are allowed to be both human and AI) I don't think we need "only human" option at all. Currently, trying to save a map with 2 "humans only" selected crashes the application, crashes load dialog showing this map later, and even crashes save dialog, so I cannot overwrite it. :)

Thanks!)
Yes, "human only" means than AI can not control this player. There can be forced to be more than human player when we are talking about multiplayer maps ("Hot Seat").
Interesting, I made a map with 2 "humans only" and it worked as intended: It was not available in the Standard Game scenarios, but in Hot Seat for 2 players I was able to find this map and to start it.
Could you please, check it once more. Maybe some other parameter was the case of crashes?

> Map Description field could be either empty from the beginning, or showing "No description", and after a click on it you should be introduced to an empty field. Currently, description text field appears with a text, which a player should delete first, before typing a new description.

Now if now description was given for a new map this filed (and description text) will be empty.

> Description field should have scrollbars: 

This field fully replicates such field in the Load dialog. We can implement scrollbar here only after we do the same in the Load dialog if it is needed.
In future we will limit the text during editing like it is done in original editor. For now I made a check that will cut the text to fit the given 5 rows.

2024-05-12 09:37 UTC, Districh-ru commented
Hi, @zenseii, could you please check out the newly added phrases when you have time?

2024-05-12 13:21 UTC, ihhub requested changes
Hi @Districh-ru , I left few comments here. Could you please take a look at them?

2024-05-12 13:21 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +        std::array<fheroes2::Rect, 6> playerRects;
I suggest not to show all players but only those that are present on the map. Right now it is very confusing to see all 6 players when in reality I have only 2 of them. This will also allow us not to create a set of images for non-existing players on the map.

2024-05-12 13:21 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +                        fheroes2::showStandardTextMessage( _( "Warning" ), _( "This feature is still in development and will be available in the next releases." ),
I suggest to just not to show these options rather than showing this dialog.

2024-05-12 13:34 UTC, Districh-ru commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +    // In original Editor map name is limited to 17 characters. We keep this limit to fit the Select Scenario dialog.
This dialog can, but Select Scenario can not. :(
So we should redo the Select Scenario dialog first.

2024-05-12 13:36 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +    // In original Editor map name is limited to 17 characters. We keep this limit to fit the Select Scenario dialog.
For the Select Scenario and Load Map dialogs we can use `fitToOneRow()` function as we still show information by right clicking.

2024-05-12 13:38 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +    // In original Editor map name is limited to 17 characters. We keep this limit to fit the Select Scenario dialog.
As of now we can keep it is it is but we should improve it in the future.

2024-05-12 13:38 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +    // In original Editor map name is limited to 17 characters. We keep this limit to fit the Select Scenario dialog.
Also, are we having such a check in file save dialog?

2024-05-12 13:49 UTC, Districh-ru commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +    // In original Editor map name is limited to 17 characters. We keep this limit to fit the Select Scenario dialog.
> Also, are we having such a check in file save dialog?

Yes, the same check is there.

2024-05-12 14:51 UTC, Districh-ru commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +        std::array<fheroes2::Rect, 6> playerRects;
Done)

2024-05-12 14:52 UTC, Districh-ru commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +                        fheroes2::showStandardTextMessage( _( "Warning" ), _( "This feature is still in development and will be available in the next releases." ),
Sure.

2024-05-13 13:34 UTC, ihhub commented
> How about setting up alliances?
> 
> For example 2v2 or 3v3 maps.

This is a pull request for "base functions".

2024-05-13 13:37 UTC, ihhub approved these changes

2024-05-13 13:49 UTC, merged