Set the last edited map file as a default for the new Standard game
ihhub/fheroes2 pull request #8680
Opened 2024-05-18 13:50 UTC by Districh-ru

This PR sets the last loaded or saved map in Editor as a default selected map for the new Standard Game. It will be selected only if the map can be played.

2024-05-18 15:09 UTC, ihhub requested changes
Hi @Districh-ru , I left a suggestion in this pull request. Would you mind to take a look when you have spare time?

2024-05-18 15:09 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +        Maps::FileInfo & mapInfo = Settings::Get().getCurrentMapInfo();
This is definitely a hack. We should use `SetCurrentFileInfo()` method for this. Create **FileInfo** object and use **readResurrectionMap()** method for this matter. Going forward: you can create a function in this file which accepts `Maps::Map_Format::BaseMapFormat`, create a new method in **Maps::FileInfo** called for example `loadResurrectionMap()` and move most of the logic there from `Maps::FileInfo::readResurrectionMap()`.

By the way, line 396 in **maps_fileinfo.cpp** should be `Maps::Map_Format::BaseMapFormat map;` as we don't need the full map to be loaded.

2024-05-18 17:59 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +        Maps::FileInfo & mapInfo = Settings::Get().getCurrentMapInfo();
@ihhub, many thanks for the suggestion!

2024-05-19 02:23 UTC, ihhub approved these changes

2024-05-19 12:22 UTC, Branikolog approved these changes

2024-05-19 12:40 UTC, merged

2024-05-19 12:40 UTC, ihhub commented
@Districh-ru , huge thanks for this update!