Properly connect Streams and Deltas
ihhub/fheroes2 pull request #8689
Opened 2024-05-19 04:46 UTC by Districh-ru

This PR fixes Streams and Deltas connections:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/3a5ff5fb-8cb0-4e61-9cdc-9cef352d5441)

2024-05-19 12:54 UTC, Districh-ru commented
In the master branch the connection of river deltas with streams is not properly implemented. All river delta tiles are considered by the engine as streams and streams are automatically placed above deltas during stream interconnection algorithm. 
It causes extra streams above the delta and after erasing deltas.

https://github.com/ihhub/fheroes2/assets/113276641/cd649b96-2f53-4d32-9792-730e2bb1fc9d

2024-05-19 13:02 UTC, Branikolog commented
Hi, @Districh-ru !
Nice work.
I have only one question.
Is it possible to apply stream connection for such case?
![image](https://github.com/ihhub/fheroes2/assets/55348946/a7a35a3c-32af-4283-985e-ad9ac541ec43)

2024-05-19 13:06 UTC, Districh-ru commented
> Is it possible to apply stream connection for such case?

Hi, @Branikolog. 
No, the original assets do not have stream sprites for such connections. :(
Late we can design the new sprites.

2024-05-19 14:25 UTC, Districh-ru commented
> @Districh-ru Okay. Connection with the existing deltas work well for the rest available cases. However, if I place delta near any stream - connection does not occur. Is there a way to apply connection in such case? At least for the cases, when it is possible?

@Branikolog, now the existing streams should update when placing a delta nearby.

2024-05-19 14:37 UTC, Branikolog approved these changes

2024-05-20 03:55 UTC, ihhub requested changes
Hi @Districh-ru , I left one comment here. Could you please check it?

2024-05-20 03:55 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +            action.commit();
The above code might not change anything at all but we are still committing the change which will result in an empty action. We need to make sure that at least one updateStreamsToDeltaConnection() is being called.

2024-05-20 04:29 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +            action.commit();
Hi, @ihhub , `commit()` is called here only when the line 1540 (`_setObjectOnTile()`) returnes true:
If object was set we commit the changes including the possible streams update.

2024-05-20 11:05 UTC, ihhub approved these changes

2024-05-20 11:05 UTC, merged

2024-05-20 11:05 UTC, ihhub commented
@Districh-ru , thank you very much for the fix!