Update Russian translation
ihhub/fheroes2 pull request #8701
Opened 2024-05-20 16:59 UTC by Districh-ru

2024-05-21 01:22 UTC, ihhub requested changes
Hi @Districh-ru , I left several comments here. Could you please take a look once you have time?

2024-05-21 01:22 UTC, ihhub commented on files/lang/ru.po
> +msgstr "Переключит режим запрета постройки зданий."
Missing character **ь**: `Переключить`.

2024-05-21 01:22 UTC, ihhub commented on files/lang/ru.po
> +msgstr "Текс сообщения:"
`Текс` --> `Текст`.

2024-05-21 01:22 UTC, ihhub commented on files/lang/ru.po
> +msgstr "Щёлкните чтобы изменить название замка. Правый клик - сбросить."
I think it should be a comma after the first word.

2024-05-21 01:22 UTC, ihhub commented on files/lang/ru.po
> +"Если этот флажок установлен, это событие произойдёт для игрока-человека если "
A missing comma before the second `если` word.

2024-05-21 01:22 UTC, ihhub commented on files/lang/ru.po
> +"его цвет: %{color}."
I don't think that **:** is needed here.

2024-05-21 01:22 UTC, ihhub commented on files/lang/ru.po
> +msgstr "Нажмите чтобы изменить описание текущей карты."
Missing comma after the first word.

2024-05-21 01:22 UTC, ihhub commented on files/lang/ru.po
> +msgstr "Нажмите чтобы установить героя в режим патруля."
A missing comma after the first word.

2024-05-21 03:03 UTC, ihhub approved these changes

2024-05-22 01:47 UTC, ihhub commented on files/lang/ru.po
> +"Сыграть в игру в режиме \\\"Горячий стул\\\", когда от 2 до 6 игроков играют "
Could you please explain why we have triple \\\ here?

2024-05-22 03:07 UTC, Districh-ru commented on files/lang/ru.po
> +"Сыграть в игру в режиме \\\"Горячий стул\\\", когда от 2 до 6 игроков играют "
Ow, it's a copy from source and paste to Poedit typo. I've fixed it.

2024-05-22 03:34 UTC, merged

2024-05-22 03:34 UTC, ihhub commented
@Districh-ru , thank you very much for the update!