Add missing Sphinx part
ihhub/fheroes2 pull request #8703
Opened 2024-05-21 10:55 UTC by ihhub

Now we can finally add new content with ease.
All credits for **PushPop** from Discord.

![image](https://github.com/ihhub/fheroes2/assets/19829520/6267c401-cc1b-4dac-a7a8-e87e6ecb4be8)

2024-05-21 15:06 UTC, Districh-ru requested changes
Hi, @ihhub.
The fixed Sphinx looks good! Thanks, **PushPop**!
I left one question regarding the need of adding an entry to the ICN enumeration. Could you please check it when you have time?

2024-05-21 15:06 UTC, Districh-ru commented on src/fheroes2/agg/icn.h
> +        OLD_ADVENTURE_OBJECT_PARTS,
Could you please explain what this is for? :)

2024-05-22 01:30 UTC, ihhub commented on src/fheroes2/agg/icn.h
> +        OLD_ADVENTURE_OBJECT_PARTS,
Oops, it's a leftover from my initial implementation.

2024-05-22 03:04 UTC, Districh-ru approved these changes

2024-05-24 07:50 UTC, merged