Update Ukrainian Translation
ihhub/fheroes2 pull request #8725
Opened 2024-05-23 13:40 UTC by ZaHaDumGoth

Rest of empty strings and some corrections of fuzzy.

2024-05-25 03:09 UTC, ihhub requested changes
Hi @ZaHaDumGoth , I left 2 comments here. Can you please check them?

2024-05-25 03:09 UTC, ihhub commented on files/lang/uk.po
>  #, fuzzy
Should we remove this line?

2024-05-25 03:09 UTC, ihhub commented on files/lang/uk.po
> +msgstr "Мапу збережено в:"
Please add a space at the end of line.

2024-05-25 05:37 UTC, ZaHaDumGoth commented on files/lang/uk.po
>  #, fuzzy
Did not get what you mean. I have checked there is no space after sentence.

2024-05-25 05:38 UTC, ZaHaDumGoth commented on files/lang/uk.po
> +msgstr "Мапу збережено в:"
Fixed.

2024-05-25 05:38 UTC, ihhub commented on files/lang/uk.po
>  #, fuzzy
I meant to remove `#, fuzzy`.

2024-05-25 05:41 UTC, ZaHaDumGoth commented on files/lang/uk.po
>  #, fuzzy
Yes, sentence is from map editor, logical and correct translation.

2024-05-25 07:57 UTC, ihhub commented on files/lang/uk.po
>  #, fuzzy
Then why we are keeping **#, fuzzy** since this comment makes to skip the translation?

2024-05-25 09:11 UTC, ZaHaDumGoth commented on files/lang/uk.po
>  #, fuzzy
Sorry, had some troubleshooting, now I got it and corrected. Clicked onto Commit and Push.

2024-05-25 09:25 UTC, ihhub approved these changes

2024-05-30 15:14 UTC, merged

2024-05-30 15:14 UTC, ihhub commented
@ZaHaDumGoth , many thanks for this update!