Code cleanup for the future changes of map loading with more function…
ihhub/fheroes2 pull request #8751
Opened 2024-05-26 08:02 UTC by ihhub

…ality

2024-05-26 18:02 UTC, oleg-derevenetz requested changes
Hi @ihhub, I just left a few notes, please take a look when you have time.

2024-05-28 12:56 UTC, Branikolog commented
Hi, @ihhub !
I'm not sure if it's related to the changes of random artifact logic you've made within this PR...
But random artifacts tend to be distributed in a strange categories in the PR build (I mean Art1/Art2/Art3).
Here I placed a bunch of artifact groups:
![image](https://github.com/ihhub/fheroes2/assets/55348946/ad405685-a27f-438d-af4d-aa2bf0f7e0c3)
And here how they appear in game:
![image](https://github.com/ihhub/fheroes2/assets/55348946/4678072a-cd88-4156-957a-5eab5ac565b8)
Central column is the strongest ones. Right column - the weakest. Left column - intermediate.

2024-05-30 12:04 UTC, Branikolog approved these changes

2024-06-01 03:41 UTC, ihhub commented on src/fheroes2/maps/map_format_info.cpp
> +        if ( fileSize < sizeof( MapFormat ) ) {
Good points. I reverted back to the original approach but increased **minFileSize** value since no maps can be that small.

2024-06-01 03:42 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +    //       then we will have problems.
Hi @oleg-derevenetz , I didn't fully understand your statement. Could you please elaborate?

2024-06-01 16:24 UTC, oleg-derevenetz commented on src/fheroes2/resource/artifact.cpp
> +    //       then we will have problems.
Hi @ihhub what do I mean here - even if some new object is added that gives out a random artifact, this random artifact (or a sequence of such artifacts) should be, in a good way, pre-defined at the map start anyway to prevent players from "gambling" with save/load abuse.

2024-06-01 16:24 UTC, oleg-derevenetz approved these changes

2024-06-01 17:52 UTC, Districh-ru approved these changes

2024-06-02 02:49 UTC, ihhub commented on src/fheroes2/resource/artifact.cpp
> +    //       then we will have problems.
Yes, I agree with this.

2024-06-02 14:53 UTC, merged