Code cleanup for LocalEvent class
ihhub/fheroes2 pull request #8810
Opened 2024-06-05 11:23 UTC by ihhub

- add error handling code for SDL functions
- rename majority of class' methods
- make enum class over just normal enum
- rename all class' members

There is more work to do but this pull request is getting too big so it is better to do this in chunks.

2024-06-05 15:21 UTC, Districh-ru commented on src/engine/localevent.cpp
> +            if ( buttonType == LocalEvent::ControllerButtonType::CONTROLLER_BUTTON_B ) {
Hi, @ihhub to fix Nintendo Switch gamepad buttons remap we should fix this line:
```suggestion
            else if ( buttonType == LocalEvent::ControllerButtonType::CONTROLLER_BUTTON_B ) {
```

2024-06-05 23:38 UTC, ihhub commented on src/engine/localevent.cpp
> +            if ( buttonType == LocalEvent::ControllerButtonType::CONTROLLER_BUTTON_B ) {
Thanks for pointing out!

2024-06-06 17:18 UTC, oleg-derevenetz requested changes

2024-06-06 17:18 UTC, oleg-derevenetz commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                _enemyArmies.erase( tileIndex );
Hi @ihhub please fix the merge conflict by removing this line :)

2024-06-06 23:51 UTC, ihhub commented on src/fheroes2/ai/normal/ai_normal_hero.cpp
> +                _enemyArmies.erase( tileIndex );
Oops

2024-06-07 10:05 UTC, oleg-derevenetz approved these changes

2024-06-07 15:39 UTC, Districh-ru approved these changes

2024-06-08 01:49 UTC, merged