Make default knowledge value for random hero as 1
ihhub/fheroes2 pull request #8813
Opened 2024-06-07 14:56 UTC by ihhub

Also, limit minimum knowledge value to 1 rather than 0.

close #8750

2024-06-08 04:12 UTC, Districh-ru requested changes
Hi, @ihhub.
In this PR we only clamp the "modified" knowledge value, but the base `knowledge` can still be 0.
We should not allow to enter a value lower than 1 for knowledge in hero edit dialog and in battle only dialog.


https://github.com/ihhub/fheroes2/assets/113276641/3b76f6c2-ee2a-4741-8bd2-8d6c11884520

2024-06-08 04:12 UTC, Districh-ru commented on src/fheroes2/heroes/skill.h
> +        int knowledge{ 0 };
Should we also set `1` as the default value for power and knowledge skills then?

2024-09-25 09:36 UTC, Branikolog approved these changes
Fix works as intended. I'm not sure, whether it should be possible to set knowledge to zero... Maybe, mapmakers would like to make a hero without spell points though.
Att and Def are ok to be 0 as default since many magic heroes have zero values from start

2024-09-25 12:55 UTC, Districh-ru approved these changes

2024-09-25 15:41 UTC, merged