Update hero selection dialog in the Editor
ihhub/fheroes2 pull request #8832
Opened 2024-06-13 14:42 UTC by ihhub

As per map makers's request.

2024-06-13 16:12 UTC, Districh-ru requested changes
Hi, @ihhub. I left two suggestions, could you please take a look when you have time?

2024-06-13 16:12 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    fheroes2::StandardWindow background( 520, 280, true, display );
What about making this window a bit lower?

```suggestion
    fheroes2::StandardWindow background( 520, 250, true, display );
```

![изображение](https://github.com/ihhub/fheroes2/assets/113276641/d2b420b4-46f2-479f-8184-d39b001525ab)

2024-06-13 16:12 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    pos.y += 170;
What about moving hero sprite a little lower to avoid possible overlap with two-lined Sorceress translation?
```suggestion
    pos.y += 175;
```
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/78e70aa7-87e9-4b78-8880-7c5ddcea5c1e)

2024-06-13 21:26 UTC, Branikolog commented
Hi, @ihhub 
There're few white pixels left after switching from random hero to any other:
![image](https://github.com/ihhub/fheroes2/assets/55348946/507af037-b56c-4121-a321-8d9c5bbf103a)

2024-06-16 04:44 UTC, ihhub commented
Hi @Branikolog and @Districh-ru , I've addressed your comments. Please take a look.

2024-06-16 10:59 UTC, Districh-ru approved these changes

2024-06-17 02:32 UTC, merged