Update the ui_text code to have less duplications and simplier renderer
ihhub/fheroes2 pull request #8854
Opened 2024-06-21 14:03 UTC by Districh-ru

This PR changes the fheroes2::Text behavior to calculate text parameters only once and then use them for width, height, rows count and rendering.

This PR changes all texts rendering including buttons text.

2024-06-24 14:35 UTC, ihhub commented
Hi @Districh-ru , would you be okay to merge this change after 1.1.1 release? I am worried that since we are getting close to the release we might face some issues with such a big change.

2024-06-24 15:13 UTC, ihhub requested changes
Hi @Districh-ru , I would like to understand the scope of these changes and the intention. Is it correct to say that this pull request does 2 things:
- speed up things by caching some data
- simplifies rendering

I have a question regarding the first part. Could you please explain little bit more for a better understanding of these changes?

2024-06-24 15:43 UTC, Districh-ru commented on src/fheroes2/gui/ui_text.h
> +        }
Ho, @ihhub.
Thanks for highlighting these issues!
Yes we have the performance boost: we do not call `getMultiRowInfo()` many times for each `width()`, `height()`, `row()` and `draw()` methods.
And we don not have to maintain the three copies of the almost the same code, but not the same in all places. - This was the main issue I was trying to solve because it was not always easy to understand how to act in the each "almost the same" code part and to remember to do all the changes in all three duplications. :)
Wу already had some barely noticeable issues: width calculation for the `width()` function and for rendering was different and the results could slightly differ.
Now all text "info" is calculated once and all functions will now use the same data.
We also could not use the results of the TextLineInfo outside this code for the cursor placing and probably some other functions.

I used `const_cast` for the compatibility with the other code and was planning to update this code after we have have checked this drastic changes. I'll do this changes now to get rid of the `const_cast`. Also I'll add the text alignment setting: it would simplify the rendering parts.

2024-06-24 15:49 UTC, Districh-ru commented
> Additionally, I noticed that the text is rendered differently with these changes. Is it intentional?

If you are talking about the MultiFontText: previously the next line offset was considered as the biggest line height of all texts. IMHO it was done to easily calculate text height ( lines_count * line_height ).
Now the next line offset is the height of the current font in which the `\n` is used: like it is used to work in most modern text editors. It can be changed to the previous implementation if it is needed. It can be discussed.

If this differences are in the `fheroes2::Text` then please let me now where it is - I'll fix it.

2024-09-21 15:29 UTC, Districh-ru commented
Closing this PR in favor of #9116

2024-09-21 15:29 UTC, closed without merging