Add support of editing daily events within the Editor
ihhub/fheroes2 pull request #8858
Opened 2024-06-22 13:07 UTC by ihhub

2024-06-23 10:34 UTC, Branikolog commented
Hi, @ihhub 
I'm testing this PR now.
I managed to initiate an application crash when trying to type "space"+"Enter"(new line)+confirm in the event text field.
The crash occurs for all other dialogs of the following type:
![image](https://github.com/ihhub/fheroes2/assets/55348946/a2f403cc-7301-48c9-831f-7fff465a4427)

Should I create a separate issue for it?

2024-06-23 10:37 UTC, Branikolog commented
"-" mark is rendered out of the field range for large numbers:
![image](https://github.com/ihhub/fheroes2/assets/55348946/dcfc27c5-4c41-42e3-bc6c-c059e0ff82bf)

2024-06-23 12:45 UTC, ihhub commented
Hi @Branikolog , please create a separate issue regarding the text editing. This PR is way too big.

2024-06-23 13:20 UTC, Branikolog commented
Hi, @ihhub 
Now it is better, but some digits are still over the field frames:
![image](https://github.com/ihhub/fheroes2/assets/55348946/1192a231-5f05-4a57-bdb5-f7e62cccf9b7)
Maybe we can just place "-" sign to the left of the field, so it never overlaps UI elements? Maybe we can place it into a special checkbox or something like that?

2024-06-23 13:22 UTC, ihhub commented
@Branikolog , we can simply don't allow to enter less than `-99999` and no more than `999999` resources. This is UI issue and should be addressed separately.

2024-06-23 13:24 UTC, Branikolog commented
It would be nice to show the exact day (month, week, day) near this counter. 
![image](https://github.com/ihhub/fheroes2/assets/55348946/4efa2117-e3af-4cc5-a611-0a12af46c92c)
Everything else seem to work properly. 👍

2024-06-23 13:24 UTC, ihhub commented
> It would be nice to show the exact day (month, week, day) near this counter. ![image](https://private-user-images.githubusercontent.com/55348946/342067562-4efa2117-e3af-4cc5-a611-0a12af46c92c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDkzNDYsIm5iZiI6MTcxOTE0OTA0NiwicGF0aCI6Ii81NTM0ODk0Ni8zNDIwNjc1NjItNGVmYTIxMTctZTNhZi00Y2M1LWE2MTEtMGExMmFmNDZjOTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDEzMjQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMTNhNGJhOTQ3Nzc5ZTdmMDUzYTAzNDJkYmUyMTk1NTkxZDU1ZjBlMTVlNjI1NDJjZDgxMzY0MDkxZTY4YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2k3UizDofhIMMaPCZEGTtD7EgtDxn3_H-GyYx9ddxf0) Everything else seem to work properly. 👍

This is an improvement for the future.

2024-06-23 13:24 UTC, Branikolog approved these changes
Great job!

2024-06-24 17:46 UTC, Districh-ru requested changes
Hi, @ihhub.
I left two comments. Could you please take a look when you have time?

2024-06-24 17:46 UTC, Districh-ru commented on src/fheroes2/gui/ui_tool.cpp
> +        if ( minimum < 0 && value != 0 && le.isKeyPressed( fheroes2::Key::KEY_MINUS ) ) {
Should we also process the keypad minus?
```suggestion
        if ( minimum < 0 && value != 0 && ( le.isKeyPressed( fheroes2::Key::KEY_MINUS ) || le.isKeyPressed( fheroes2::Key::KEY_KP_MINUS ) ) ) {
```

2024-06-24 17:46 UTC, Districh-ru commented on src/fheroes2/editor/editor_daily_event_spec_window.cpp
> +                    eventMetadata.message = std::move( temp );
Should we limit the maximum text lines?
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/a6a2a8d0-37d8-41f1-881a-43c243c7ec38)

2024-06-25 08:51 UTC, ihhub commented on src/fheroes2/editor/editor_daily_event_spec_window.cpp
> +                    eventMetadata.message = std::move( temp );
I believe this is not a trivial problem since the window where we actually type has different width leading to different results. And it is also true that an event window which pops up in the game has also different width.

The shown example is an extreme case and I agree that this is a bug. However, this is the problem for many other places and we should fix it in a separate pull request.

2024-06-25 08:53 UTC, ihhub commented on src/fheroes2/gui/ui_tool.cpp
> +        if ( minimum < 0 && value != 0 && le.isKeyPressed( fheroes2::Key::KEY_MINUS ) ) {
It is fixed.

2024-06-25 10:30 UTC, Districh-ru approved these changes

2024-06-25 10:33 UTC, merged