Update DEVELOPMENT.md
ihhub/fheroes2 pull request #8859
Opened 2024-06-22 15:31 UTC by celliott113

Add step in Windows to ensure the user clones the project before proceeding onto next steps.

2024-06-22 16:24 UTC, ihhub requested changes

2024-06-22 16:24 UTC, ihhub commented on docs/DEVELOPMENT.md
> +* You will need to clone the `fheroes2` project.
This is true not only on Windows but on all platforms.

2024-06-22 16:58 UTC, celliott113 commented on docs/DEVELOPMENT.md
> +* You will need to clone the `fheroes2` project.
You are correct, I have adjusted by removing from Windows and adding to the top of the doc to encompass all platforms.

2024-06-22 18:37 UTC, oleg-derevenetz requested changes
Hi @celliott113 I just left one suggestion, please take a look when you have time.

2024-06-22 18:37 UTC, oleg-derevenetz commented on docs/DEVELOPMENT.md
> +<b>Note:</b> You will need to clone the `fheroes2` project before following the below instructions.
There is no need to use HTML tags if there are corresponding Markdown tags:

```suggestion
**Note:** You will need to clone the `fheroes2` project before following the instructions below.
```

2024-06-22 19:14 UTC, celliott113 reviewed
Updated with @oleg-derevenetz recommendations. Necessary to maintain document consistency within the markdown language.

2024-06-22 19:15 UTC, oleg-derevenetz approved these changes

2024-06-23 01:44 UTC, ihhub approved these changes

2024-06-23 11:12 UTC, merged

2024-06-23 11:12 UTC, ihhub commented
@celliott113 , thank you very much for your contribution to the project!