Update logic related to human player selection for maps
ihhub/fheroes2 pull request #8876
Opened 2024-06-25 08:24 UTC by ihhub

2024-06-25 09:39 UTC, oleg-derevenetz requested changes
Hi @ihhub I found just one issue so far, that is related to the variable naming, please take a look when you have time.

2024-06-25 09:40 UTC, ihhub commented on src/fheroes2/game/game_mainmenu.cpp
> +            const uint8_t humanPlayCount = static_cast<uint8_t>( static_cast<int>( result ) - static_cast<int>( fheroes2::GameMode::SELECT_SCENARIO_ONE_HUMAN_PLAYER ) );
You're absolutely right!

2024-06-25 10:15 UTC, oleg-derevenetz approved these changes

2024-06-27 17:29 UTC, Districh-ru approved these changes

2024-06-28 01:10 UTC, merged