Allow normal victory for "Accumulate gold" condition
ihhub/fheroes2 pull request #8883
Opened 2024-06-26 15:07 UTC by ihhub

relates to #8717

2024-06-26 17:31 UTC, Districh-ru requested changes
Hi, @ihhub, I left two questions. Could you please take a look in your spare time?

2024-06-26 17:31 UTC, Districh-ru commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +            _isNormalVictoryAllowed = false;
Why do we force reset `_isNormalVictoryAllowed`?
In original Editor this state is stored if you change the victory condition type.

https://github.com/ihhub/fheroes2/assets/113276641/4feb7275-745a-40e4-9379-4c13aeddcd1e

2024-06-26 17:31 UTC, Districh-ru commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +                mapFormat.isVictoryConditionApplicableForAI = false;
Please correct me if I misunderstand. In the `setCondition()` method we get data from `mapFormat` and set the `VictoryConditionUI` members. Then why we do changes in `mapFormat`?
Should we update `mapFormat` only when the dialog is closed by OKAY button and do no changes otherwise?

2024-06-27 15:24 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +            _isNormalVictoryAllowed = false;
Oh, this is a leftover from development.

2024-06-27 15:29 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +                mapFormat.isVictoryConditionApplicableForAI = false;
The values for other conditions are not set and being reset if you switch to other condition. I believe it is better to keep the same logic for this special variables / checkboxes. Moreover, with the current approach if I select Accumulate gold and click the checkbox, then select None and return back the checkbox is going to be unselected. This is because we don't update the map properties upon this event. Therefore, I put the code to ensure that the values are consistent.

Another reason is to verify that the values are correct for certain conditions as not all of them use these 2 values.

2024-06-27 15:44 UTC, Districh-ru approved these changes

2024-06-27 15:49 UTC, Districh-ru commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +                mapFormat.isVictoryConditionApplicableForAI = false;
OK)
I wanted to say that I needed some time to understand the purpose of `setCondition()` method. From the first place it uses `mapFormat` to set conditions for the UI ... but the next lines tells the this method is used to set conditions in `mapFormat` ... So is the next line ( `_isNormalVictoryAllowed = mapFormat.allowNormalVictory;` ) because we set UI using the `mapFormat` or is should be ( `mapFormat.allowNormalVictory = _isNormalVictoryAllowed ;` ) because we set conditions in `mapFormat`. :)
Maybe it is better to split this method in the future into two - the first will not modify `mapFormat` and the next one will update it.

2024-06-27 15:50 UTC, merged