Add Find Artifact victory condition in Editor
ihhub/fheroes2 pull request #8898
Opened 2024-06-29 16:57 UTC by Districh-ru

relates to https://github.com/ihhub/fheroes2/issues/8717

This PR implements "Find Artifact" Victory condition. The Magic Book and the Spell Scroll artifacts cannot be selected for this case.
It also:
- makes the drop lists to follow the UI style (Good/Evil);
- makes the UI not to reset the values when the condition is changed: when you return back to the previous condition the last value will be restored until the dialog is closed;
- slightly speeds-up rendering сру changes in special victory conditions;
- makes the drop list items be horizontally aligned with the upper (selected) condition icon and text.
The icon for the Ultimate Artifact is temporary and should be updated to a more proper one later.

![goose](https://github.com/ihhub/fheroes2/assets/113276641/09cb0fcd-7ed3-41f3-b3a9-903cde3b55e5) ![list](https://github.com/ihhub/fheroes2/assets/113276641/ed2113f5-5d10-4554-94d7-b92ce55d128e)

![ultArt](https://github.com/ihhub/fheroes2/assets/113276641/f0e0e35e-7a06-4ad4-9251-c975010cc978)

2024-06-30 08:55 UTC, ihhub requested changes
Hi @Districh-ru , I left here multiple comments. Could you please take a look at them when you have spare time?

2024-06-30 08:55 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +        void renderStaticItems( fheroes2::Image & output, const bool isEvilInterface )
It is entirely clear why the separation of render function appeared. Both parts of UI are actually dynamic / changeable. Having 2 different functions is not totally accurate as no UI elements are static. Is the intention to avoid heavy computations? I don't think we gain much by splitting the original function.

2024-06-30 08:55 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +        void setCondition( const uint8_t victoryConditionType )
This function should be then named as `setConditionType()` since we are setting only the type.

2024-06-30 08:55 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +                    _victoryArtifactId = ( mapFormat.victoryConditionMetadata[0] == 0 ) ? ultimateArtifactId : mapFormat.victoryConditionMetadata[0];
I suggest to update the comment like this:
```cpp
// In original game's map format '0' stands for any Ultimate Artifact.
```

2024-06-30 08:55 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +                assert( 0 );
Should we set **_conditionType** to `Maps::FileInfo::VICTORY_DEFEAT_EVERYONE` for this case and then update **mapFormat**?

2024-06-30 08:55 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
>                  // Did you add more conditions? Add the logic for them!
Should we set **_conditionType** to `Maps::FileInfo::LOSS_EVERYTHING` here and then update **mapFormat**?

2024-06-30 08:55 UTC, ihhub commented on src/fheroes2/resource/artifact.h
> +        RANDOM_ULTIMATE_ARTIFACT,
Should we name it as `EDITOR_ANY_ULTIMATE_ARTIFACT`? It would be really obvious what it is for in the code. I am okay to keep this name as well. I am suggesting this to avoid any future misunderstanding from developers while debugging or reading the code.

2024-06-30 08:55 UTC, ihhub commented on src/fheroes2/resource/artifact.h
> +        return id != UNKNOWN && id < ARTIFACT_COUNT && ( id < RANDOM_ULTIMATE_ARTIFACT || id > UNUSED_86 );
I suggest to do this way:
```cpp
return id != UNKNOWN && id != RANDOM_ULTIMATE_ARTIFACT && id < ARTIFACT_COUNT && ( id < UNUSED_84 || id > UNUSED_86 );
```
Yes, it is more complex in terms of computation but it is easier to understand. For example, it is not clear why:
```cpp
( id < RANDOM_ULTIMATE_ARTIFACT || id > UNUSED_86 )
```
condition exists while
```cpp
id != RANDOM_ULTIMATE_ARTIFACT && ( id < UNUSED_84 || id > UNUSED_86 )
```
make the code obvious to read.

What do you think?

2024-06-30 08:55 UTC, ihhub commented on src/fheroes2/resource/artifact_info.cpp
> +            // This artifact is used in Editor for the special victory conditions.
I suggest to rephrase this comment:
```cpp
// This artifact is only used in Editor for the special victory conditions.
```

2024-06-30 08:55 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +                // In original game's map format '0' stands for the Ultimate Artifact. Set it also to '0' for the compatibility.
I suggest to update the comment like this:
```cpp
// In original game's map format '0' stands for any Ultimate Artifact. Set it also to '0' for the compatibility.
```

2024-06-30 08:55 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +        void renderChangableItems( fheroes2::Image & output )
`Changable` should be `Changeable`.

2024-06-30 08:55 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    // Make a sprite for the Random Ultimate Artifact used in Editor for the special victory condition.
If we are going to update the name of the artifact entry we need to change this comment as well.

2024-06-30 08:55 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +             && ( isPriceofLoyaltyArtifactAllowed || !fheroes2::isPriceOfLoyaltyArtifact( id ) ) ) {
What do you think of splitting this long condition into parts? It has become hard to read:
```cpp
if ( id == Artifact::MAGIC_BOOK ) {
    continue;
}

if ( isForVictoryConditions && id == Artifact::SPELL_SCROLL ) {
    continue;
}

if ( !Artifact( id ).isValid() ) {
    continue;
}

if ( !isPriceofLoyaltyArtifactAllowed && !fheroes2::isPriceOfLoyaltyArtifact( id ) ) {
    continue;
}

artifacts.emplace_back( id );
```

2024-06-30 08:55 UTC, ihhub commented
I've added @zenseii to have an opinion about newly added artifact name and description.

2024-06-30 09:14 UTC, Districh-ru commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +        void renderStaticItems( fheroes2::Image & output, const bool isEvilInterface )
If we switch the `allowNormalVictory` initially we restore the background, `Blit()` the artifact frame, render the artifact, render the text and checkbox and then render the check mark.
Now we only render the artifact and check mark.
What if we combine it back into one `render()` method, but add a `const bool doRenderStaticPartForThisCondition` and when it is `false` update only changeable part?

2024-06-30 09:14 UTC, Districh-ru commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +            const fheroes2::Sprite & image = fheroes2::AGG::GetICN( isEvilInterface ? ICN::DROPLISL_EVIL : ICN::DROPLISL, 0 );
Sure!

2024-06-30 09:20 UTC, Districh-ru commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +                assert( 0 );
Yes, lets do this way!
The mapFormat will be updated on dialog close by OKAY button.

2024-06-30 09:40 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +        if ( !isPriceofLoyaltyArtifactAllowed && !fheroes2::isPriceOfLoyaltyArtifact( id ) ) {
Here the condition should be:
```cpp
if ( !isPriceofLoyaltyArtifactAllowed && fheroes2::isPriceOfLoyaltyArtifact( id ) ) {
```

2024-06-30 09:43 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +        if ( !isPriceofLoyaltyArtifactAllowed && !fheroes2::isPriceOfLoyaltyArtifact( id ) ) {
Ow.
Fixed!

2024-06-30 10:44 UTC, Districh-ru commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +                    _allowNormalVictoryRoi = Editor::drawCheckboxWithText( _allowNormalVictory, _( "Also allow normal victory" ), output, roi.x + 5,
Thanks, @zenseii.
Fixed!

2024-06-30 12:59 UTC, ihhub requested changes
Hi @Districh-ru , I added few more comments. Could you please check them?

2024-06-30 12:59 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                    // Make a sprite for the Random Ultimate Artifact used in Editor for the special victory condition.
This comment should be updated like it was done on line 4157.

2024-06-30 12:59 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +        if ( isPriceofLoyaltyArtifactAllowed && !fheroes2::isPriceOfLoyaltyArtifact( id ) ) {
This condition should be:
```cpp
( !isPriceofLoyaltyArtifactAllowed && fheroes2::isPriceOfLoyaltyArtifact( id ) )
```

2024-06-30 12:59 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +                _conditionType = Maps::FileInfo::VICTORY_DEFEAT_EVERYONE;
We should update **mapFormat** as well. Otherwise, `getConditionMetadata()` would trigger another assertion.

2024-06-30 12:59 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +                _conditionType = Maps::FileInfo::LOSS_EVERYTHING;
We should update **mapFormat** as well. Otherwise, `getConditionMetadata()` would trigger another assertion.

2024-06-30 12:59 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +        void render( fheroes2::Image & output, const bool isEvilInterface, const bool redrawStaticItemsForCurrentContion )
`redrawStaticItemsForCurrentContion` is misspelled. I suggest to name the variable as `updateEverything` or `renderEverything`.

2024-06-30 13:36 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +        if ( isPriceofLoyaltyArtifactAllowed && !fheroes2::isPriceOfLoyaltyArtifact( id ) ) {
My mistake(

2024-06-30 13:46 UTC, Districh-ru commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +                _conditionType = Maps::FileInfo::VICTORY_DEFEAT_EVERYONE;
We will already trigger the upper `assert( 0 );`.
I moved this _conditionType fix to the `getConditionMetadata()` default case.

2024-07-01 03:37 UTC, ihhub approved these changes

2024-07-01 13:23 UTC, merged

2024-07-01 13:23 UTC, ihhub commented
@Districh-ru , thank you so much for this change!