Editor victory hero town conditions
ihhub/fheroes2 pull request #8905
Opened 2024-07-01 19:17 UTC by Districh-ru

relates to https://github.com/ihhub/fheroes2/issues/8717

2024-07-06 15:14 UTC, Districh-ru commented
Hi, @zenseii, could you please check the newly added phrases?

2024-07-06 15:28 UTC, ihhub requested changes
Hi @Districh-ru , I left several minor comments here. Would you mind to take a look at them?

2024-07-06 15:28 UTC, ihhub commented on src/fheroes2/maps/map_format_info.h
> +        // The world width in tiles.
Since all maps are square maps this comment is not entirely accurate. It is missing `height`.

2024-07-06 15:28 UTC, ihhub commented on src/fheroes2/maps/map_format_helper.cpp
> +            if ( conditionMetadata.size() == 2 ) {
Let's reduce complexity of this lambda function as it is little hard to read:
```cpp
if ( conditionMetadata.size() != 2 ) {
    return false;
}
// The rest of the code.
...
```

2024-07-06 15:28 UTC, ihhub commented on src/fheroes2/maps/map_format_helper.cpp
> +                const uint32_t tileIndex = conditionMetadata[0];
To be safe let's add an assertion after this line:
```cpp
assert( tileIndex < map.tiles.size() );
```

2024-07-06 15:28 UTC, ihhub commented on src/fheroes2/maps/map_format_helper.cpp
> +            if ( ( map.victoryConditionMetadata.size() != 2 ) || !checkSpecialCondition( map.victoryConditionMetadata, Maps::ObjectGroup::KINGDOM_TOWNS ) ) {
Here (and the code below) is no need to check for `( map.victoryConditionMetadata.size() != 2 )` condition as we do the same inside `checkSpecialCondition()` lambda function.

2024-07-06 15:28 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +                int selectedTownIndex = 0;
This should be **size_t** type as this variable is used only for one purpose: `_mapTownInfos[selectedTownIndex]`.

2024-07-06 15:28 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +                int selectedHeroIndex = 0;
This should be **size_t** type as this variable is used only for one purpose: `_mapHeroInfos[selectedHeroIndex]`.

2024-07-06 15:28 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +                int selectedTownIndex = 0;
This should be **size_t** type as this variable is used only for one purpose: `_mapTownInfos[selectedTownIndex]`.

2024-07-06 15:28 UTC, ihhub commented on src/fheroes2/editor/editor_map_specs_window.cpp
> +                int selectedHeroIndex = 0;
This should be **size_t** type as this variable is used only for one purpose: `_mapHeroInfos[selectedHeroIndex]]`.

2024-07-06 15:35 UTC, ihhub commented on src/fheroes2/maps/map_format_helper.cpp
> +                    objectFound = true;
This is risky as default case actually would hit this line. I suggest to move this line just before lines 619 and 633 to make sure that we mark only the right case.

2024-07-06 17:16 UTC, Districh-ru commented on src/fheroes2/maps/map_format_helper.cpp
> +        // Check and update the special victory and loss conditions that depends on player objects.
Thanks, @zenseii !

2024-07-07 05:25 UTC, ihhub approved these changes

2024-07-08 13:22 UTC, Branikolog commented
Not sure it's related to the current PR, but I somehow cannot select other players:
![image](https://github.com/ihhub/fheroes2/assets/55348946/ba305bf0-e7bc-4506-a775-0013c649e8ca)
![image](https://github.com/ihhub/fheroes2/assets/55348946/3de8bab9-e051-41ac-bc8e-67b5b378476a)

Also there's one more issue:
![image](https://github.com/ihhub/fheroes2/assets/55348946/746fe0b0-1e3a-4d52-ba1f-3ccc87162107)

![image](https://github.com/ihhub/fheroes2/assets/55348946/c74eb699-a3ad-428f-9f99-68499f3298aa)

Blue and green players have similar castle set ups, but I can select starting faction only for green player.

2024-07-08 14:27 UTC, Branikolog commented
Hi, @ihhub 

> Hi @Branikolog , described by you conditions work exactly as in the original Editor. I believe it is a place of improvement for it but definitely not bugs in my opinion.

The original editor in this regard was kind of broken in my opinion. I think we shouldn't allow to create such maps, that are broken and unplayable (in terms of conditions).
I hope you can fix the most apparent issues within future PRs.

2024-07-08 17:53 UTC, Districh-ru commented
Hi, @Branikolog, I've addressed the first issue: now the "Allow this condition also for AI" checkbox is available only for the neutral towns/castles.
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/2196ffe0-6d0a-4f63-9ae9-b18d376a304c)


Let's address the other issues with the special victory/loss conditions in multiplayer in the other PR, because it's more related to the multiplayer logic that most likely needs polishing.

2024-07-08 20:44 UTC, Branikolog commented
Hi, @Districh-ru !

>Let's address the other issues with the special victory/loss conditions in multiplayer in the other PR, because it's more related to the multiplayer logic that most likely needs polishing.

Sure! I find current implementation not really easy to catch, when I start selecting Human-only/Comp-human/Comp-only players and trying to set special conditions.

2024-07-08 20:44 UTC, Branikolog approved these changes

2024-07-09 13:59 UTC, ihhub commented
Hi @zenseii , I've addressed your comments. Could you please check again?

2024-07-09 14:26 UTC, merged

2024-07-09 14:27 UTC, ihhub commented
@Districh-ru , many thanks for implementing such features!