Add Evil theme for ADD, EDIT and DELETE and some other buttons in Editor
ihhub/fheroes2 pull request #8923
Opened 2024-07-06 17:08 UTC by Districh-ru

This PR adds conversion of first 19 images in CELLWIN ICN that corresponsd to some buttons used in Editor and checkbox backgrounds.

![img](https://github.com/ihhub/fheroes2/assets/113276641/aef4659c-ce84-4728-b883-e1aec123954b)

2024-07-07 05:27 UTC, ihhub approved these changes

2024-07-08 14:25 UTC, ihhub requested changes
Hi @Districh-ru , I took a second look and left 2 comments here. Would you mind to check them in your free time?

2024-07-08 14:25 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +                                                PAL::CombinePalettes( PAL::GetPalette( PAL::PaletteType::GOOD_TO_EVIL_INTERFACE ),
We can cache `PAL::CombinePalettes() output outside this loop as this is not an instant operation.

2024-07-08 14:25 UTC, ihhub commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    const fheroes2::Sprite markBackground = fheroes2::AGG::GetICN( isEvilInterface ? ICN::CELLWIN_EVIL : ICN::CELLWIN, 4 );
This variable should be reference.

2024-07-08 16:09 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectitems.cpp
> +    const fheroes2::Sprite markBackground = fheroes2::AGG::GetICN( isEvilInterface ? ICN::CELLWIN_EVIL : ICN::CELLWIN, 4 );
Thanks, @ihhub, for noticing this!

2024-07-08 16:10 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +                                                PAL::CombinePalettes( PAL::GetPalette( PAL::PaletteType::GOOD_TO_EVIL_INTERFACE ),
Done!

2024-07-09 00:57 UTC, ihhub approved these changes

2024-07-09 12:38 UTC, merged