Fix swap of the main tile addon if a top object already exists in that tile
ihhub/fheroes2 pull request #8936
Opened 2024-07-07 18:40 UTC by Districh-ru

The objects order on the same tile is determined by the current main addon object type (checked by `getObjectTypeByIcn()` function) and the layer type of the new tile being placed.

This PR fixes the `getObjectTypeByIcn()` function that was giving object type only for the main tile and giving `OBJ_NONE` for all other tiles. Now the function checks all object tiles.

It also forbids main addon swap if a new tile is the background layer one and the current tile already has an object with ID.

2024-07-08 14:00 UTC, ihhub requested changes
Hi @Districh-ru , I left one comment here. Could you please take a look when you have time?

2024-07-08 14:00 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +            if ( !isMainObject || ( partInfo.layerType == Maps::BACKGROUND_LAYER && currentTile.GetObjectUID() != 0 ) ) {
This is not a valid condition. We need to check whether the object have ground parts below. If it does then this object stands in front of the object we are adding.

2024-07-08 14:03 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +            if ( !isMainObject || ( partInfo.layerType == Maps::BACKGROUND_LAYER && currentTile.GetObjectUID() != 0 ) ) {
How about this:
- check the type of the main tile
- check if any of top layer addons have the same type
- if they do then don't set the new object type since top layer objects are always drawn on top
- an exception applies for true action objects while heroes, castle entrances and etc since we need them to setup properties

What do you think? Will it fix the original problem?

2024-07-08 14:14 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +            if ( !isMainObject || ( partInfo.layerType == Maps::BACKGROUND_LAYER && currentTile.GetObjectUID() != 0 ) ) {
On top of this we need to check the order of layers on the tile. If a tile has an object of BACKGROUND_LAYER and we are setting an object of OBJECT_LAYER then we have to change the tile object type. While in the opposite case we shouldn't.

2024-07-08 19:22 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +            if ( !isMainObject || ( partInfo.layerType == Maps::BACKGROUND_LAYER && currentTile.GetObjectUID() != 0 ) ) {
Hi, @ihhub, thanks for the explained suggestion!
I've done the changes and they work good on a test map.

2024-07-10 03:51 UTC, ihhub approved these changes

2024-07-10 11:07 UTC, Branikolog commented
Hi!
If I place an artifact on a tile behind the castle - it still shown as artifact on right click on it:
![image](https://github.com/ihhub/fheroes2/assets/55348946/c5e7554b-4258-47ef-acbd-fbf09aa9b3a0)
After I pick it up the tile is shown as grass:
![image](https://github.com/ihhub/fheroes2/assets/55348946/fbf30bb2-bae6-4da2-8c15-f8c98ef51ca9)
When the same cell without pre placed artifact belongs to castle area:
![image](https://github.com/ihhub/fheroes2/assets/55348946/43e0b751-83d3-472d-9116-9641c9a8d2cc)

2024-07-10 12:47 UTC, ihhub commented
Hi @Branikolog , this is the same issue as #8505 as it is not related to this PR.

2024-07-10 13:11 UTC, Branikolog approved these changes
Okay. No more issues found then. :)

2024-07-10 13:14 UTC, merged

2024-07-10 13:14 UTC, ihhub commented
@Districh-ru , thank you so much for this fix!