Add monster stats inside editor count dialog
ihhub/fheroes2 pull request #8960
Opened 2024-07-14 11:53 UTC by orzm

This resolves issue https://github.com/ihhub/fheroes2/issues/8780. A new dialog, based on existing SelectCount, has been added. This new function contains handlers for left and right mouse clicks inside monster sprite, which will spawn an ArmyInfo dialog with detailed stats.

2024-07-14 12:12 UTC, ihhub commented
Hi @orzm , please address IWYU complaints and also include a screenshot of the new dialog in the description of this pull request.

2024-07-14 13:19 UTC, orzm commented
> Hi @orzm , please address IWYU complaints and also include a screenshot of the new dialog in the description of this pull request.

Done

2024-07-14 14:07 UTC, ihhub commented
Hi @orzm , while the solution solve the problem my main concern is increase of code duplication. The new function is 90% identical than the old one. I suggest to do this way:
1. **Dialog::SelectCount()** function should accept `const DialogElement * uiElement = nullptr` instead of the current `const fheroes2::Image & backgroundImage`.
2. **uiElement** has needed functionality: **draw()** and **processEvents()** method.
3. Derive a new class from `CustomImageDialogElement` class and override the above methods. Let's assume we call it `MonsterDialogElement`.
4. Pass an instance of the newly created class in 2 places in the code where you call `Dialog::SelectMonsterCount()` at the moment.

Therefore, the updated code will support not only monsters but any other UI elements.

What do you think?

2024-07-14 14:15 UTC, orzm commented
> Hi @orzm , while the solution solve the problem my main concern is increase of code duplication. The new function is 90% identical than the old one. I suggest to do this way:
> 
> 1. **Dialog::SelectCount()** function should accept `const DialogElement * uiElement = nullptr` instead of the current `const fheroes2::Image & backgroundImage`.
> 2. **uiElement** has needed functionality: **draw()** and **processEvents()** method.
> 3. Derive a new class from `CustomImageDialogElement` class and override the above methods. Let's assume we call it `MonsterDialogElement`.
> 4. Pass an instance of the newly created class in 2 places in the code where you call `Dialog::SelectMonsterCount()` at the moment.
> 
> Therefore, the updated code will support not only monsters but any other UI elements.
> 
> What do you think?

This seems reasonable. I'll work on a solution based on Your suggestions.

Thanks.

2024-07-16 15:20 UTC, ihhub commented
Hi @orzm , I've converted this to draft for now. Please mark this pull request as ready to review once it's completed.

2024-07-18 04:46 UTC, ihhub commented
Hi @orzm , I rebased your branch from master branch as we updated dependencies and GitHub Actions were failing for your pull request.

2024-07-18 05:00 UTC, ihhub requested changes
Hi @orzm , I left multiple comments here. Would you mind to take a look at them when you have time?

2024-07-18 05:00 UTC, ihhub commented on src/fheroes2/army/army_bar.cpp
> +                const fheroes2::MonsterDialogElement monsUi{ mons };
This code will caused assertion. Try to set a random monster in the Editor. I think we can use `std::unique_ptr` to handle both cases when monster exists and it doesn't.

2024-07-18 05:00 UTC, ihhub commented on src/fheroes2/gui/ui_dialog.cpp
> +        const fheroes2::Sprite sprite = fheroes2::AGG::GetICN( ICN::STRIP, 12 );
This variable must be const reference to avoid memory copy.

2024-07-18 05:00 UTC, ihhub commented on src/fheroes2/gui/ui_dialog.cpp
> +        if ( le.MouseClickLeft( rect ) ) {
Here we should use `else if` since right and left mouse clicking are mutually exclusive. This will save unnecessary checks in the code.

2024-07-18 05:00 UTC, ihhub commented on src/fheroes2/gui/ui_dialog.cpp
> +        const fheroes2::Sprite sprite = fheroes2::AGG::GetICN( ICN::STRIP, 12 );
Please remove `fheroes2::` from all places in this file since the code is being executed within the same namespace.

2024-07-18 05:00 UTC, ihhub commented on src/fheroes2/gui/ui_dialog.h
> +        Monster _monster;
This member can be `const` as we don't modify it.

2024-07-18 17:26 UTC, orzm commented on src/fheroes2/army/army_bar.cpp
> +                const fheroes2::MonsterDialogElement monsUi{ mons };
I get Your point. However:
1) I think You're pointing to the wrong place in code. I guess situation You've mentioned is handled [here](https://github.com/ihhub/fheroes2/pull/8960/files#diff-33704c51a8784d78313c0f993e7ae4a166b206daa982c990f001b893cac35695R1201-R1206).
2) In code pointed above assertion won't occur due to double-checking of isValid() value right before creation of MonsterDialogElement. That behaviour is wrong as well though, because the dialog a random monster won't show at all. I'll fix that.

Nevertheless, `std::unique_ptr` is a good idea and I'll apply that both in army_bar.cpp and editor_interface.cpp for sake of making the code as error-proof as possible.

2024-07-18 18:59 UTC, orzm commented on src/fheroes2/army/army_bar.cpp
> +                const fheroes2::MonsterDialogElement monsUi{ mons };
Added `std::unique_ptr` instances in mentioned files. Also modified logic, so that count dialog for a random monster is again available. I had to modify `ModifyDialogElement` constructor to throw exception instead of assertion to make current logic work. Don't know if that'll be an acceptable solution.

2024-07-18 18:59 UTC, orzm commented on src/fheroes2/gui/ui_dialog.cpp
> +        const fheroes2::Sprite sprite = fheroes2::AGG::GetICN( ICN::STRIP, 12 );
Done

2024-07-18 18:59 UTC, orzm commented on src/fheroes2/gui/ui_dialog.cpp
> +        if ( le.MouseClickLeft( rect ) ) {
Done

2024-07-18 18:59 UTC, orzm commented on src/fheroes2/gui/ui_dialog.cpp
> +        const fheroes2::Sprite sprite = fheroes2::AGG::GetICN( ICN::STRIP, 12 );
Done

2024-07-18 18:59 UTC, orzm commented on src/fheroes2/gui/ui_dialog.h
> +        Monster _monster;
Done

2024-07-20 08:57 UTC, Districh-ru requested changes
Hi, @orzm, I left two comments. Could you please check them when you have time?

2024-07-20 08:57 UTC, Districh-ru commented on src/fheroes2/gui/ui_dialog.cpp
> +        Blit( sprite, 0, 0, output, offset.x, offset.y, sprite.width(), sprite.height() );
An optional suggestion.
We can use `Copy()` here because all monster images don't have any transparent pixels. We can even make the `sprite` to be single-layer:
```suggestion
        Sprite sprite = AGG::GetICN( ICN::STRIP, 12 );
        sprite._disableTransformLayer();
        renderMonsterFrame( _monster, sprite, { 6, 6 } );
        Copy( sprite, 0, 0, output, offset.x, offset.y, sprite.width(), sprite.height() );
```

2024-07-20 08:57 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +        }
When `uiElement` is not `nullptr` the `display.render()` method is called on every loop. It results in very high render calls:
![изображение](https://github.com/user-attachments/assets/70cfbdff-a0fa-417a-ae23-540556418d22)
We can make `processEvents()` to return `true` if `render()` is needed but to do this we will need to update `DialogElement` class and all its inheritances.

So to solve only this issue we can check for mouse action in the UI element area and only then process the events and do `render()`.
Like this (a code without any optimizations):
```suggestion
        if ( uiElement
             && ( le.isMouseLeftButtonReleasedInArea( { uiOffset, uiElement->area() } ) || le.isMouseRightButtonPressedInArea( { uiOffset, uiElement->area() } ) ) ) {
            uiElement->processEvents( uiOffset );
            display.render();
        }
```

2024-07-20 14:11 UTC, ihhub commented on src/fheroes2/gui/ui_dialog.cpp
> +            throw std::logic_error( "Invalid monster provided" );
We do not use exceptions in the code unless it is absolutely necessary like missing resources. Please use an assertion for this matter.

2024-07-20 16:32 UTC, orzm commented on src/fheroes2/gui/ui_dialog.cpp
> +        Blit( sprite, 0, 0, output, offset.x, offset.y, sprite.width(), sprite.height() );
Done

2024-07-20 16:32 UTC, orzm commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +        }
Done

2024-07-20 16:34 UTC, orzm commented on src/fheroes2/gui/ui_dialog.cpp
> +            throw std::logic_error( "Invalid monster provided" );
Restored assertion and adjusted code in editor_interface.cpp, so that it won't cause failure for random monster

2024-07-20 16:54 UTC, Districh-ru requested changes
Well done, @orzm.
I left just one optimization suggestion.

2024-07-20 16:54 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +            const fheroes2::Rect uiRect{ uiOffset, uiElement->area() };
We can cache `uiRect` outside of the `while` loop. In example, in line 99:
```cpp
const fheroes2::Rect uiRect = uiElement ? fheroes2::Rect( uiOffset, uiElement->area() ) : fheroes2::Rect();
```

2024-07-21 07:27 UTC, orzm commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +            const fheroes2::Rect uiRect{ uiOffset, uiElement->area() };
Done

2024-07-21 08:06 UTC, Districh-ru approved these changes
👍 
@orzm, I left just one more minor code improvement comment.

2024-07-21 08:06 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +            if ( le.isMouseLeftButtonReleasedInArea( uiRect ) || le.isMouseRightButtonPressedInArea( uiRect ) ) {
To make SonarQube happy it is better to fix the maintainability issue and merge these two `if` conditions.
>rule S1066: Nested code - blocks of code inside blocks of code - is eventually necessary, but increases complexity. This is why keeping the code as flat as possible, by avoiding unnecessary nesting, is considered a good practice.
Merging if statements when possible will decrease the nesting of the code and improve its readability.

2024-07-21 08:52 UTC, orzm commented on src/fheroes2/dialog/dialog_selectcount.cpp
> +            if ( le.isMouseLeftButtonReleasedInArea( uiRect ) || le.isMouseRightButtonPressedInArea( uiRect ) ) {
Done

2024-07-21 15:01 UTC, ihhub approved these changes

2024-07-21 15:18 UTC, merged