Update hero spell points indicator after the battle and before performing defeated opponent fade animation
ihhub/fheroes2 pull request #9000
Opened 2024-07-27 13:07 UTC by Districh-ru

Fix #7518

This PR:
- forces the heroes icons update after any battle during player actions;
- forces heroes and castles update during AI actions after the battle with the human player;
- also makes some minor code improvements to heroes action code including AI actions.

Master build (AI actions):

https://github.com/user-attachments/assets/e20f597f-f0d1-4128-bd04-a972e5c3be6d

This PR (AI actions): 

https://github.com/user-attachments/assets/74d0a483-6f66-4e4f-a903-90fa54d75d62

This PR (player actions):

https://github.com/user-attachments/assets/76df81b6-ab0c-4d71-ab55-42d67d1c4308

2024-07-27 14:45 UTC, oleg-derevenetz requested changes
Hi @Districh-ru I just left some suggestions and one question regarding this PR, could you please take a look when you have time?

2024-07-27 14:45 UTC, oleg-derevenetz commented on src/fheroes2/ai/ai_hero_action.cpp
> +                    DEBUG_LOG( DBG_AI, DBG_INFO, defender->GetName() << " the AI hero is protecting the human castle " << castle->GetName() )
If something happens that shouldn't normally happen, it's better to use `DBG_WARN`:

```suggestion
                    DEBUG_LOG( DBG_AI, DBG_WARN, defender->GetName() << " the AI hero is protecting the human castle " << castle->GetName() )
```

2024-07-27 14:45 UTC, oleg-derevenetz commented on src/fheroes2/ai/ai_hero_action.cpp
> +                    DEBUG_LOG( DBG_AI, DBG_INFO, defender->GetName() << " the human hero is protecting the AI castle " << castle->GetName() )
Same as above.

```suggestion
                    DEBUG_LOG( DBG_AI, DBG_WARN, defender->GetName() << " the human hero is protecting the AI castle " << castle->GetName() )
```

2024-07-27 14:45 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_action.cpp
> +        enum class Outcome : uint8_t
Are there any real reasons for this change (and similar changes below)? This `enum` is a local one, it is not stored anywhere to read it later on a different machine (and never will).

If we are talking about pinching pennies, then yes, `uint8_t` is usually smaller than `int`, but this may be compensated by various speed penalties. For instance, IIRC, ARM Cortex CPUs have 32-bit ECC granularity, so they cannot "just update" a single byte in some 32-bit aligned memory location from L1 cache. In this case, the L1 data memory system reads the existing data from the memory to the cache first, "merges" the updated bytes into those from-memory bytes, then calculates ECC from that merged value and only then stores it into memory. A lot of work compared to just storing a 32-bit or 64-bit value at once, right? :) Yes, CPU attempts to apply different tricks trying to "merge" multiple different store operations together, etc. What I'm trying to say is that in this particular case there will be no observable gain from this change, so why do this? :)

2024-07-27 14:56 UTC, Districh-ru commented on src/fheroes2/heroes/heroes_action.cpp
> +        enum class Outcome : uint8_t
Hi, @oleg-derevenetz, thanks for the clarification!
I did not know such details and just followed the clang-tidy suggestion `enum 'Outcome' uses a larger base type ('int', size: 4 bytes) than necessary for its value set, consider using 'std::uint8_t' (1 byte) as the base type to reduce its size [performance-enum-size]`.

But when talking about size of this one instance and CPU performance I choose the performance.

I've reverted the change.

2024-07-27 15:13 UTC, oleg-derevenetz commented on src/fheroes2/heroes/heroes_action.cpp
> +        enum class Outcome : uint8_t
> I did not know such details and just followed the clang-tidy suggestion `enum 'Outcome' uses a larger base type ('int', size: 4 bytes) than necessary for its value set, consider using 'std::uint8_t' (1 byte) as the base type to reduce its size [performance-enum-size]`.

Some new suggestion from clang-tidy > 15.0? I'm also waiting for `ubuntu-24.04` image out of beta (and become `ubuntu-latest`) to start using the Clang tools 18.x. Anyway, this may be a good suggestion if we are hitting memory limits somewhere (for example, if we have some hotspot in our code processing an array of structures with enums that needs to be fitted into CPU cache). In this case, there is nothing like that, there is a single variable of a local `enum` type, so all we have there is extra words in the source file and no real gain.

2024-07-27 15:56 UTC, oleg-derevenetz approved these changes

2024-07-29 14:30 UTC, ihhub approved these changes

2024-07-29 14:30 UTC, merged

2024-07-29 14:30 UTC, ihhub commented
@Districh-ru , many thanks for these updates!