Add monochrome ICN decode code and use original hexagon sprite for the battlefield
ihhub/fheroes2 pull request #9063
Opened 2024-08-24 10:57 UTC by Districh-ru

In HEROES2.AGG there are several monochrome ICNs which are not currently decoded properly. Instead of these sprites we wrote our functions to generate these images.

This PR adds the monochrome ICN decode code and uses one of such images for the hexagon image on the battlefield.

2024-09-04 11:01 UTC, ihhub requested changes
Hi @Districh-ru , I left several comments here. Could you please take a look at them?

2024-09-04 14:54 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +            const bool isMonochromatic = ( header1.animationFrames == 32 );
I've checked the official assets and no ICNs have `animationFrames` more than 32 and is equal to 32 only for the images that were previously incorrectly decoded. And there is also no information telling that there could be more than 31 animation frames.
<details>

```
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle1.icn animationFrames = 11
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle2.icn animationFrames = 26
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtfle3.icn animationFrames = 25
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos1.icn animationFrames = 30
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos2.icn animationFrames = 29
agg\HEROES2\cmbtlos3.icn animationFrames = 22
agg\HEROES2\cmbtlos3.icn animationFrames = 22
agg\HEROES2\cmbtlos3.icn animationFrames = 22
agg\HEROES2\cmbtlos3.icn animationFrames = 22
agg\HEROES2\cmbtlos3.icn animationFrames = 22
agg\HEROES2\cmbtlos3.icn animationFrames = 22
agg\HEROES2\cmbtlos3.icn animationFrames = 22
agg\HEROES2\cmbtlos3.icn animationFrames = 22
agg\HEROES2\cmbtlos3.icn animationFrames = 22
agg\HEROES2\cmbtlos3.icn animationFrames = 22
agg [...]

2024-09-04 15:13 UTC, Districh-ru commented on src/engine/agg_file.h
> +        uint8_t animationFrames{ 0 };
Yes, it can be more than 0 and less than 32 and it is mostly equal to the hardcoded values in `ICN::AnimationFrame()`

But for the `ICN::CMBTFLE1` in `ICN::AnimationFrame()` there is 43 frames that is eaual to the images in the ICN, but `animationFrames` there is equal to **11** (43-32). This part should be investigated later.

2024-09-04 15:16 UTC, Districh-ru commented on src/fheroes2/agg/agg_image.cpp
> +            const bool isMonochromatic = ( header1.animationFrames == 32 );
Funny, but animations with more than 32 frames have `animationFrames` reduced by 32.

2024-09-07 08:39 UTC, ihhub requested changes
Hi @Districh-ru , I left few more suggestions here. Would you mind to take a look at them?

2024-09-07 08:39 UTC, ihhub commented on src/engine/agg_file.h
> +        ICNHeader() = default;
Please remove this line. It is not needed anymore.

2024-09-07 08:39 UTC, ihhub commented on src/engine/agg_file.h
> +        uint8_t animationFrames{ 0 };
I am very cautious about this logic. It seems very odd to me.

2024-09-07 08:39 UTC, ihhub commented on src/tools/icn2img.cpp
> +            const bool isMonochromatic = ( header.animationFrames == 32 );
Can we add an assertion to verify that the parent ICN does indeed have enough frames for normal images?

2024-09-07 08:39 UTC, ihhub commented on src/engine/image_tool.cpp
> +        while ( data < dataEnd ) {
Since we area touching these functions I suggest to pass **ICNHeader** instead of the bunch of variables to simplify the code. What do you think?

2024-09-08 22:13 UTC, oleg-derevenetz commented on src/engine/agg_file.h
> +        uint8_t animationFrames{ 0 };
It's probably a bitfield with bits 1-5 representing the number of frames and bit 6 indicating that this is a monochrome image.

2024-09-09 17:05 UTC, Districh-ru commented on src/tools/icn2img.cpp
> +            const bool isMonochromatic = ( header.animationFrames == 32 );
Sure. I've added the assertion to `agg_image.cpp`

2024-09-09 17:05 UTC, Districh-ru commented on src/engine/image_tool.cpp
> +        while ( data < dataEnd ) {
Done!
I've also moved the monochromatic check here.

2024-09-09 17:14 UTC, Districh-ru commented on src/engine/agg_file.h
> +        uint8_t animationFrames{ 0 };
@oleg-derevenetz, yes, it looks like a bitfield. But currently I see no way to clearly determine when we need to add 32 to the first 5 bits of this value to get the exact frames count.
The only thing I see in original ICN headers that this value is `0` for normal images, is ( `framesCount % 32` ) for animated images and is equal to `32` for monochromatic images.
( Probably it is a leftover from Heroes 1. Maybe the first game never had animations with more than 31 frames. )

2024-09-09 17:18 UTC, oleg-derevenetz commented on src/engine/agg_file.h
> +        uint8_t animationFrames{ 0 };
> But currently I see no way to clearly determine when we need to add 32 to the first 5 bits of this value to get the exact frames count.

Probably an animated image just can't have more than 31 frames?

2024-09-09 17:26 UTC, Districh-ru commented on src/engine/agg_file.h
> +        uint8_t animationFrames{ 0 };
It Heroes 2 it has. In example: the door light animation `SHNGANIM` (on the Main menu) has 39 frames ( `animationFrames` == 7, it is `39 % 32`). And also battle victory animation `CMBTFLE1` has 43 frames, (11 is stored in the header for the frames count).

2024-09-09 18:17 UTC, oleg-derevenetz commented on src/engine/agg_file.h
> +        uint8_t animationFrames{ 0 };
> In example: the door light animation SHNGANIM (on the Main menu) has 39 frames ( animationFrames == 7, it is 39 % 32). And also battle victory animation CMBTFLE1 has 43 frames, (11 is stored in the header for the frames count).

Then probably the actual number of frames is stored at the offset 0 of the ICN file (that is, this is what is called `spritesCount` in the `icn2img.cpp`) and our `ICNHeader::animationFrames` is just a field with flags that just has not been initialized properly (and it so happened that its contents coincided with the number of frames), and a single bit 6 was set (or reset) in it by HoMM2 developers?

2024-09-15 10:10 UTC, Districh-ru commented on src/engine/agg_file.h
> +        uint8_t animationFrames{ 0 };
I've updated the logic to check only this bit to determine if the image is monochromatic.

2024-10-12 06:32 UTC, ihhub approved these changes

2024-10-12 06:32 UTC, merged

2024-10-12 06:32 UTC, ihhub commented
@Districh-ru , thank you very much for this update!