Center sprites and text in adventure map treasure chest dialog
ihhub/fheroes2 pull request #9103
Opened 2024-09-15 22:29 UTC by IvanAtanascev

Fixes #9025 by centering the gold pile and XP sprites horizontally in relation to their respective buttons ("YES" and "NO") in the adventure map treasure chest dialog window.

2024-09-16 15:56 UTC, Districh-ru requested changes
Hi, @IvanAtanascev, the fix looks good to me:
![изображение](https://github.com/user-attachments/assets/66f74a24-3fcc-42b0-9347-94ee8b553093)

I left two suggestions to clean-up the changed code. Could you please check them when you have time.

2024-09-16 15:56 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_chest.cpp
> +
We can get rid of `pt` (line 64) and cache the `fheroes2::AGG::GetICN( buttonYesIcnID, 0 )`:
```cpp
const fheroes2::Sprite & buttonYesSprite = fheroes2::AGG::GetICN( buttonYesIcnID, 0 );

const int32_t buttonsYPosition = box.GetArea().y + box.GetArea().height - buttonYesSprite.height();
const int32_t buttonYesXPosition = box.GetArea().x + box.GetArea().width / 2 - buttonYesSprite.width() - 20;

fheroes2::Button button_yes( buttonYesXPosition , buttonsYPosition, buttonYesIcnID, 0, 1 );

const int32_t buttonNoXPosition = box.GetArea().x + box.GetArea().width / 2 + 20;

fheroes2::Button button_no( buttonNoXPosition , buttonsYPosition, buttonNoIcnID, 0, 1 );
```
Buttons' height is the same so we can use one `buttonsYPosition` for the both buttons.

2024-09-16 15:56 UTC, Districh-ru commented on src/fheroes2/dialog/dialog_chest.cpp
> +    pos.x = buttonYesXPosition + ( ( fheroes2::AGG::GetICN( buttonYesIcnID, 0 ).width() - sprite_gold.width() ) / 2 );
Then we can use `buttonYesSprite` here too:
`pos.x = buttonYesXPosition + ( ( buttonYesSprite.width() - sprite_gold.width() ) / 2 );`
:)

2024-09-16 19:27 UTC, IvanAtanascev commented
Hello, @Districh-ru, thank you for the suggestions. I have applied them in 495bb58. The code looks better this way and works as expected.

2024-09-17 03:06 UTC, Districh-ru approved these changes

2024-09-18 14:16 UTC, ihhub approved these changes

2024-09-18 14:17 UTC, merged

2024-09-18 14:17 UTC, ihhub commented
@IvanAtanascev , thank you so much for your contribution to the project!