Battle log: split long phrases into two lines; clean getHeroAnimation() function code
ihhub/fheroes2 pull request #9118
Opened 2024-09-21 18:14 UTC by Districh-ru

Fix #6357 by splitting long phrases into two lines:
![изображение](https://github.com/user-attachments/assets/9538b7f2-d51a-473a-8a98-475e3b2b7290)

For more tests I temporarily reduced the allowed text width:
![изображение](https://github.com/user-attachments/assets/11d1334d-db44-420f-80b5-1b78821ae88f)

This PR also cleans `getHeroAnimation()` code.

2024-09-25 08:53 UTC, Branikolog approved these changes

2024-09-25 10:04 UTC, ihhub requested changes
Hi @Districh-ru , I left 2 questions here. Could you please take a look at them?

2024-09-25 10:04 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +                assert( pos != std::string::npos );
I am not sure that this is always true. We could simply break from this loop.

2024-09-25 10:04 UTC, ihhub commented on src/fheroes2/battle/battle_interface.cpp
> +                _messages.push_back( std::move( str ) );
How about the case when indeed a word can be longer than area width? Should we use `fitToOneRow()` and `text()` methods here to get the proper string?

2024-09-25 13:47 UTC, Districh-ru commented on src/fheroes2/battle/battle_interface.cpp
> +                assert( pos != std::string::npos );
Hi, @ihhub !
Theoretically there might be a very long word: https://en.wikipedia.org/wiki/Longest_word_in_English
I've added an easy logic for a such case.

In original game there are no such words and when adding new phrases and translating them we should avoid using extra-large words that do not fit even the battle log. :))

2024-09-27 14:58 UTC, ihhub approved these changes

2024-09-27 14:58 UTC, merged

2024-09-27 14:58 UTC, ihhub commented
@Districh-ru , thank you so much for this improvement!