Add dialog to choose between Auto Combat and Quick Combat
ihhub/fheroes2 pull request #9180
Opened 2024-10-10 13:36 UTC by zenseii

This will let more users notice the Quick Combat feature and it will give touch devices access to Quick Combat.

This PR also adds basic shine effect to the generated buttons' edges.

![image](https://github.com/user-attachments/assets/f0dc4d3e-6b71-4071-b43e-264525c8b17f)

Related to #9095 and #9100

Fix https://github.com/ihhub/fheroes2/issues/9094

2025-01-06 22:59 UTC, Branikolog commented
Hi, @zenseii !

Nice work! This dialog definitely makes gameplay more comfortable.
From interaction point this dialog is absolutely fine!
Here are my few notes on the implementation and the design.

- I suppose, large button is considered as a prototype yet? I feel there are some shiny areas missing on them:
![image](https://github.com/user-attachments/assets/c5d3fdfe-f42e-42c6-b3b6-6d1c2dcb6c46)

- I feel two rows of buttons are rarely used in the game UI. In my personal opinion, the placement of three buttons so close to each other in two rows alongside looks a little out of place here. The large buttons increase this feeling even further. :) I can hardly mention any similar dialog with the same kind of design.

What if we take the other window type and make this dialog look like the existing adventure/file options?
![image](https://github.com/user-attachments/assets/9c4529d5-cb9c-4269-a66a-fdafef1f9b0a)

I mean we can use that brown marble window type with the same buttons and texts you've implemented.

I noticed one text issue with descriptions but not sure it is relevant though:
Right click on the "AUTO" button states:
![image](https://github.com/user-attachments/assets/52694f2c-d30c-4693-b817-1f4a655ef093)

And the AUTO COMBAT description states:
![image](https://github.com/user-attachments/assets/19604899-57b7-49a4-8795-d99efdab34af)

Were the first words chosen to be different on purpose?

2025-01-13 10:40 UTC, Branikolog commented
Hi, @zenseii !

I personally love how this dialog is looking now. 👍 

![image](https://github.com/user-attachments/assets/d1b3d772-e945-464e-ad05-2723b2a3f23a)

Auto combat could be stopped by Esc button too. Should we mention it in the description?

![image](https://github.com/user-attachments/assets/b84ab5c1-b3fb-4a06-b701-9008eca9fa22)

Most dialogs have hotkeys. How do you think, if it is neccessary to add a hotkeys here to be able to select both of these features? I know, that both features are able to be triggered outside of this dialog and from my perspective it is just a matter of logic of controls consistency.

2025-01-13 14:36 UTC, Branikolog approved these changes
Wonderful!
Absolutely love this enhancement! Thanks!

2025-01-13 16:46 UTC, Districh-ru approved these changes
Well done, @zenseii!
Also I like that all engine-made buttons have the upper shine lines now.
![изображение](https://github.com/user-attachments/assets/466b186b-f80e-4fad-949e-64a5b2ab05ba)

2025-01-13 18:02 UTC, oleg-derevenetz commented
Hi @zenseii technically everything looks OK, but I have a naming-related question. Everywhere in the code and in the hotkey config file / settings the "auto resolve" action is called like "auto finish" or "finish the battle in auto mode" (in case of hotkey settings). Is there any way to unify this so that there is no confusion, because I have the impression that an end user may not always understand that this is the same thing? At the same time, it would be undesirable to touch the current name in the hotkey settings, because the previous versions of the engine will not understand these changes "right away".

2025-01-13 19:10 UTC, Districh-ru commented
@zenseii 
I vote for `Quick Combat` to be more close to the later HoMM games.

I think that the name of this feature should tell the player that the combat will be instantly finished without any player actions (automatically). And Quick can be understood as automatic. :)
So we will have `Auto Combat` to give control to the AI and watch how it goes (not sow quick), and `Quick Combat` to quickly (almost instantly) do the combat by giving control to the AI without watching the battle.
And ... Quick Resolve sounds for me more like quickly solving equations or other problems. :))

2025-01-13 21:39 UTC, Branikolog commented
@zenseii 

>I personally only care that the name we stick with fits, and all of the above do imo.

100%

I like the version @Districh-ru voted for. I think both phrasings shouldn't look idetical. Players should be able to distinguish both features as easy as possible. So differences in the first word in my opinion catch player attention more effective: Auto Combat / Quick Combat. 👍

2025-01-13 21:45 UTC, Branikolog commented
@Districh-ru 

> Well done, @zenseii! Also I like that all engine-made buttons have the upper shine lines now. ![изображение](https://private-user-images.githubusercontent.com/113276641/402622907-466b186b-f80e-4fad-949e-64a5b2ab05ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4MDM4NzUsIm5iZiI6MTczNjgwMzU3NSwicGF0aCI6Ii8xMTMyNzY2NDEvNDAyNjIyOTA3LTQ2NmIxODZiLWY4MGUtNGZhZC05NDllLTY0YTViMmFiMDViYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExM1QyMTI2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTI4ZWQ3MjhkMjI4OGFiNjViYjc2MGNhN2I2ODdhOWRkYjNjY2NjZDJiMDE2YmRmNmUzZmRmZDQ3ZWQxMDBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cEL1ICEtDKenFQzDq3FoxO90dQOLrhV1Z86OsbmXiGE)


But still not all of them have those shine lines 😢 :

![image](https://github.com/user-attachments/assets/873cd3da-0617-47e6-a7bd-3cc0bd993a33)

![image](https://github.com/user-attachments/assets/ca3756e7-b21f-4e53-bbd1-5bb30c5bee82)

![image](https://github.com/user-attachments/assets/87a3737b-a666-4774-8f54-106e73345f59)

![image](https://github.com/user-attachments/assets/625ab4ee-d901-4260-a944-8e57d877cb27)

2025-01-13 22:40 UTC, oleg-derevenetz commented
As soon as we agree on the name of this thing, I will add a commit to this PR renaming the symbols in the code and in the hotkey config file (in a backward-compatible manner).

2025-01-14 07:55 UTC, LeHerosInconnu commented
Hello @zenseii and everyone,

> @LeHerosInconnu, if you have any feedback regarding pixel-precise™ placement of the buttons and elements then that would be appreciated.

The word "CANCEL" is not centered horizontally in the button, 9 pixels to the right, 12 pixels to the left.

![Cancel button 96 x 25 pixels 01](https://github.com/user-attachments/assets/30df1c70-d190-449e-9cdb-b333eef66b2e)

Also for the "half pixel" that can't be separated when an uneven number is used, e.g. 25 pixels divided by two gives 12.5, i.e. 12 pixels on one side and 13 pixels on the other, we should set up a convention so that the non-separable pixel is always added on the right side for a horizontal dimension, i.e. in the example 12 pixels on the left and 13 pixels on the right, and is always added at the bottom for a vertical dimension, i.e. in the example, 12 pixels at the top and 13 pixels at the bottom.
I can open a specific issue for this if necessary.

The "AUTO COMBAT" button is narrower than the "AUTO RESOLVE" button, 106 pixels for the former and 108 pixels for the latter.

![AUTO COMBAT button 106 x 56 pixels 01](https://github.com/user-attachments/assets/bae94af0-558b-48f1-8c6d-72f4810ab6e4)
![AUTO RESOLVE button 108 x 56 pixels 01](https://github.com/user-attachments/assets/6460fe33-f1e8-4664-af51-8c933cbc7fbe)

About the rest, here's how I see it.

For this one:
![AUTO button info window 01](https://github.com/user-attachments/assets/ecbb9df0-9403-4efc-9aad-5c42c81ae22b)

The window's yellow title should be:

"Auto Combat Modes".

The text should be:

"Choose whether to play the combat in auto combat mode or in instant combat mode."

In the info bar at the bottom of the screen the text should be:

"Auto combat modes"

For this other one:
![Auto combat modes choice window 01](https://github.com/user-attachments/assets/2685d774-e2b5-4aa8-8489-022573c154d3)

The window's yellow title should be:

"Auto Combat Modes".

In the info bar at the bottom of the screen the text should be:

"Auto combat modes"

For this other one:
![AUTO COMBAT button info window 01](https://github.com/user-attachments/assets/f59d06ae-a8a8-4582-9ebf-479c1174aad9)

The window's yellow title should be:

"Auto Combat" (this is already the case).

The text should be:

"The computer plays the combat for you, while you watch the progression of the combat.

This mode can be interrupted at any time by pressing the Auto Combat hotkey or the default Cancel key, or by pressing the right or left mouse button anywhere on the combat screen."

For the last one:
![INSTANT COMBAT button info window 01](https://github.com/user-attachments/assets/951169fb-2a00-4e3c-941a-8932e18b315a)

The window's yellow title should be:

"Instant Combat".

The text should be:

"The combat ends instantly from the current state.

This action cannot be undone once validated."

I continue to think that the expressions “Auto Combat” and “Instant Combat” are more appropriate.
Indeed, both expressions are self-explanatory.
“Auto Combat” represents combat continued automatically, and “Instant Combat” represents combat ended instantly.

I think it's important that the word "combat" is present in both expressions.
It's to combat that the modes refer, and then the user need only remember the two significant words “auto” and “instant”.

2025-01-14 14:42 UTC, oleg-derevenetz commented
> Which means that we're only missing @ihhub and @oleg-derevenetz's choices.

I'm fine with "auto combat" and "instant combat".

2025-01-14 17:31 UTC, oleg-derevenetz commented
> Did we decide on `Instant Combat`? Me, @Districh-ru and @Branikolog voted `Quick Combat`.

These changes are just a preliminary, because there were many symbols like "auto battle" and similar. I want to check everything once again a day later, like I usually do (to ensure that I didn't forgot or miss something), but I don't want to delay it, so I made these preliminary changes. I will replace the "instant" by "quick" if this option turns out to be the final one :)

2025-01-14 17:44 UTC, Districh-ru commented
I prefer the more known **Quick Combat**, but I'm OK with **Instant Combat** - it also has noticeable differences in the first word to catch player attention more effectively and it tells the player that the combat will be performed almost instantly meaning that no combat actions will be shown and no manual interaction with the army can be done until the combat is finished.

2025-01-15 08:10 UTC, oleg-derevenetz commented
So, what is the final wording? :)

2025-01-15 10:40 UTC, ihhub commented
Hi, everyone!

While the later games have similar buttons my concerns that having 2 buttons with at least one identical word would still confuse players. Ideally, we need to have 2 buttons with absolutely different names. Having `Auto Combat` and `Instant/Quick Combat` doesn't differentiate too much.

After thinking for some time we can name the button to give the control to AI as `Auto Control` and another button for finishing the battle as `Quick Combat` (`Instant Combat` is also fine with me).

What do you think about this?

2025-01-15 10:40 UTC, ihhub requested changes
Hi @zenseii , I also left few comments here. Could you please take a look at them?

2025-01-15 10:40 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +            getTextAdaptedButton( _icnVsSprite[id][0], _icnVsSprite[id][1], gettext_noop( "AUTO\nCOMBAT" ),
Would it be better to include prefix for this and the below translations?
```cpp
"battle|AUTO\nCOMBAT"
"battle|AUTO\nRESOLVE"
```

I assume it might be easier to understand these lines for translators. What do you think?

2025-01-15 10:40 UTC, ihhub commented on src/fheroes2/agg/agg_image.cpp
> +        case ICN::BUTTON_AUTO_COMBAT_GOOD:
This is beyond the scope of this pull request: I think we should stop adding new entries for ICN and just provide a function to generate a button for a specific text and interface. This will ease the work of the future button addition in the work. We should address it in a completely separate pull request. As of now we can just create an issue for the change. What do you think?

2025-01-15 10:57 UTC, oleg-derevenetz commented
> After thinking for some time we can name the button to give the control to AI as `Auto Control` and another button for finishing the battle as `Quick Combat` (`Instant Combat` is also fine with me).

> What do you think about this?

Auto Combat is a sort of a well-known/established term in HoMM game series:

![auto-homm2](https://github.com/user-attachments/assets/8f02772d-ca27-4d4f-9948-ff7b509b1cbb)

![auto-homm3](https://github.com/user-attachments/assets/c46bf5e3-482b-4166-baf5-7d2f2bf8f612)

I actually don't think that fheroes2 should be somehow original in this matter :)

2025-01-15 10:59 UTC, ihhub commented
Hi @oleg-derevenetz , in this case let's follow the original game name. With this logic in mind we should use `Quick Combat` for another button.

2025-01-15 11:50 UTC, Branikolog commented
After a few days I came to a conclusion, that "Auto" and "Quick" combat is the best for me. "Auto combat", as @oleg-derevenetz stated, is a well established term. "Quick" is simply shorter than "Instant". Both buttons have the first word different which is much more preferable in regard of visual recognition, than second word on the second line.

2025-01-15 14:50 UTC, LeHerosInconnu commented
Hello everyone,

@zenseii,

> > [...] we should set up a convention so that the non-separable pixel is always added on the right side for a horizontal dimension
> 
> If you can, then please make an issue for this.

I'll do it. :)

> > The "AUTO COMBAT" button is narrower than the "AUTO RESOLVE" button, 106 pixels for the former and 108 pixels for the latter.
> 
> This will be fixed once we change RESOLVE to COMBAT, since the width of the buttons depend on the width of the text on them to accommodate for translations. I've already thought about making a function that forces buttons in the same dialog to have the same size, but I don't want to implement that here.

Okay.

> > The window's yellow title should be:
> > "Auto Combat Modes".
> 
> To avoid confusion with Auto Combat, how about just Automatic Modes.

I think it's important to specify that this refers to combat.
"Automatic Combat Modes".

> > The text should be:
> > "Choose whether to play the combat in auto combat mode or in instant combat mode."
> 
> My impression is that there was a wish to use the word "fight" instead of "play", which is why it says "fight out". I also think fight sounds better than play, which sounds less serious and makes me more aware of this being a game than a battle with high stakes. How about just "Choose between auto combat mode and quick/instant combat mode."

The words "fight" and "combat" are synonyms, that makes it redundant.

The word "play" is used here more in the sense of playback, like playing back a film, rather than in the sense of playing, having fun.
But I'm not a native English speaker, so I don't know if it's seen more one way than the other.

"Choose between auto combat mode and quick/instant combat mode."
This sentence isn't informative enough about what's going to happen.

What about:
"Choose whether to proceed the combat in auto combat mode or in instant combat mode."

> > In the info bar at the bottom of the screen the text should be:
> > "Auto combat modes"
> 
> Same comment as above.

Yeah. :)
"Automatic combat modes".

> > The window's yellow title should be:
> > "Auto Combat" (this is already the case).
> > The text should be:
> > "The computer plays the combat for you, while you watch the progression of the combat.
> 
> Same comment here about "plays". Should we just replace plays with "fight"?

What about:
"The computer continues the combat for you, while you watch the progression of the combat.

> > This mode can be interrupted at any time by pressing the Auto Combat hotkey or the default Cancel key, or by pressing the right or left mouse button anywhere on the combat screen."
> 
> I specifically avoided the use of "mouse" because this is not true for touch devices, even though they have a simulated right-click. Also, you can right or left click anywhere on the game screen, even when you use higher than original resolutions.

What about:
"This mode can be interrupted at any time by pressing the Auto Combat hotkey or the default Cancel key, or by activating the left or right click anywhere on the game screen."

> > The window's yellow title should be:
> > "Instant Combat".
> 
> > The text should be:
> > "The combat ends instantly from the current state.
> > This action cannot be undone once validated."
> 
> These will depend on the wording we go for. We can change the description text.

"The combat ends instantly from the current state."
"The combat ends quickly from the current state."
My choice is made. :D

> > I continue to think that the expressions “Auto Combat” and “Instant Combat” are more appropriate. Indeed, both expressions are self-explanatory. “Auto Combat” represents combat continued automatically, and “Instant Combat” represents combat ended instantly.
> > I think it's important that the word "combat" is present in both expressions. It's to combat that the modes refer, and then the user need only remember the two significant words “auto” and “instant”.
> 
> I agree about not using battle and rather have combat in this case.

Ah. :)

> > The word "CANCEL" is not centered horizontally in the button, 9 pixels to the right, 12 pixels to the left.
> 
> Thanks for checking. I'll fix this.

> @LeHerosInconnu. I looked at the cancel button and the one you're showing is the original cancel button not the one we generate. However, the change you're requesting will affect our generated buttons too, and should be made an issue/discussion for first.

The "CANCEL" button comes directly from this window.
![Auto combat modes choice window 01](https://github.com/user-attachments/assets/2685d774-e2b5-4aa8-8489-022573c154d3)

But I made a mistake by taking into account the whole width of the button instead of what is considered to be the "top" of the button.
The text is well centered with eight pixels on each side. :)

> I also have a comment about this text for the quick combat feature:
> 
> > The combat ends instantly from the current state.
> 
> Using "instantly" is fine, even with quick combat being the word, but the use of "ends" makes it sound like the screen will be exited as if you're quitting, and this can be confusing. How about something like "The combat will be fought out in an instant from the current state."?

What about:
"The combat is instantly resolved from the current state."

@ihhub,

> While the later games have similar buttons my concerns that having 2 buttons with at least one identical word would still confuse players. Ideally, we need to have 2 buttons with absolutely different names. Having `Auto Combat` and `Instant/Quick Combat` doesn't differentiate too much.
> 
> After thinking for some time we can name the button to give the control to AI as `Auto Control` and another button for finishing the battle as `Quick Combat` (`Instant Combat` is also fine with me).
> 
> What do you think about this?

So, here are a few examples of menus with buttons containing the same word:

"STANDARD GAME"
"CAMPAIGN GAME"
"MULTI-PLAYER GAME"
![Same names in menus 001](https://github.com/user-attachments/assets/45f94df4-a871-4c89-b6cb-47048c821607)

"STANDARD GAME"
"CAMPAIGN GAME"
"MULTI-PLAYER GAME"
![Same names in menus 002](https://github.com/user-attachments/assets/8f6edd35-152b-435f-acb1-21f3e645ccc9)

"NEW MAP"
"LOAD MAP"
![Same names in menus 003](https://github.com/user-attachments/assets/12ef9d54-8aeb-406a-984e-c6ff3a0af33c)

"NEW GAME"
"LOAD GAME"
"SAVE GAME"
![Same names in menus 004](https://github.com/user-attachments/assets/7c0a9859-c9a3-4524-8bd3-191bcd2305c8)

On the contrary, I think that having the same word on several buttons referring to the same thing is easier to apprehend and remember, and is also much clearer.

Consider this:

"NEW SCENARIO"
"LOAD PARTY"
"SAVE GAME"

And what do you think about it?

> Hi @oleg-derevenetz , in this case let's follow the original game name. With this logic in mind we should use `Quick Combat` for another button.

The word "quick" is vague.
The word "quick" can be interpreted as "fast" or "rapid", the user may think that he will see the combat in an accelerated way, etc.
With the word "instant", there's no ambiguity: instant is instantaneous, so there's no need to wonder.

2025-01-16 14:38 UTC, LeHerosInconnu commented
Hello @zenseii,

> @LeHerosInconnu,
> 
> > With the word "instant", there's no ambiguity: instant is **instantaneous**, so there's no need to wonder.
> 
> I'm not sure this falls under instantaneous :
> 
>  [fheroes2.engine.version_.1.1.5.2025-01-16.13-57-32.mp4 ](https://github.com/user-attachments/assets/31447534-2f49-4330-8b5b-371984ef18e2)
> 
> However, it is "quicker" than if I'd tried to win the battle. Also don't try this at home, especially not with a maxed stack unless you don't plan to use your PC for a while 😨

It's "quicker" than actually doing the combat, but it's not "quick" either; it just shows that there's still room for improvement in combat resolution in this mode.

You have to look at the meaning of the word itself.

Here's an instant combat:

https://github.com/user-attachments/assets/7b42bbc0-32fe-4fee-8d94-ab738e89b70c

And here's a quick combat:

https://github.com/user-attachments/assets/5a2f728e-f158-4362-b44f-ee2ae174c17d

2025-01-16 18:46 UTC, oleg-derevenetz commented on src/fheroes2/game/game_hotkeys.cpp
> +                        value = config.StrParams( "resolve the battle in quick combat mode" );
Hi @zenseii this change is wrong. The idea is to look for the old hotkey name (currently it is "finish the battle in auto mode") if the new hotkey name ("quick combat") was not found.

2025-01-16 19:07 UTC, oleg-derevenetz commented
> I'm done pushing changes to this branch now. If you have the chance to look over the changes from resolve/instant to quick then that would be greatly appreciated.

Thank you! I'll make an effort to take a look during tomorrow.

2025-01-17 02:15 UTC, ihhub commented on src/fheroes2/game/game_hotkeys.cpp
> +                    // TODO: remove this temporary workaround
How temporary is this workaround? :)

2025-01-17 06:24 UTC, oleg-derevenetz commented on src/fheroes2/game/game_hotkeys.cpp
> +                    // TODO: remove this temporary workaround
@ihhub How temporary it should be? :)

2025-01-17 07:21 UTC, LeHerosInconnu commented
Hello @zenseii,

> @LeHerosInconnu, I've addressed your text suggestions. I shortened this text because `action` was redundant in this context and `undone` already implies that something has been done, and the word `validate` doesn't work in this context. ![image](https://private-user-images.githubusercontent.com/12501091/404039533-6ab9c7da-4842-43c2-802e-41cfb3ac390e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwODk0MTcsIm5iZiI6MTczNzA4OTExNywicGF0aCI6Ii8xMjUwMTA5MS80MDQwMzk1MzMtNmFiOWM3ZGEtNDg0Mi00M2MyLTgwMmUtNDFjZmIzYWMzOTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE3VDA0NDUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MzNhNzA0NjMxZDYwNjZjMjQwNDUxN2U4ZmE3NjhiMmI2Y2M3MDNmMTI2ZGIxNjFiYzY0MzUxN2MxMDJmY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G7DVE4xmhFIidxe4Fgit6usghTIUQeUGf3DtcvHrb3Y)

The words "resolved" and "ended" mean the same thing, and the "and ended" part makes the sentence a bit cumbersome.

What about:
"The combat is resolved from the current state to the end."

> As for this description I changed the part about while you observe because it sounds like the game is forcing you to sit down and watch. `activating` was changed with performing since that is the correct expression, alternatively we could just say `right or left clicking`.
> 
> ![image](https://private-user-images.githubusercontent.com/12501091/404041525-15a174f7-dc78-42ee-b5a0-9cfffa6063c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwODk0MTcsIm5iZiI6MTczNzA4OTExNywicGF0aCI6Ii8xMjUwMTA5MS80MDQwNDE1MjUtMTVhMTc0ZjctZGM3OC00MmVlLWI1YTAtOWNmZmZhNjA2M2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE3VDA0NDUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZTI1NGI4Y2I0ZGE1OGVlMTZiMDkxNTdiZWUwODYzMzRhZmM5M2Q3NmQ2OGU1NzlkZDUzZjE3MzBhZTM3OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TJDbL_sHkDjO25sRwD6gmPpgW7Kzy07kY4io0WbmveU)

The "at the currently set combat speed" part of the sentence will raise a question in the user's mind: "What does that mean?"; whereas the text should be descriptive and clear.

> As for this description I changed the part about while you observe because it sounds like the game is forcing you to sit down and watch.

This indicates that the user will be watching the combat (it's simply a description of what happens in this mode), and that he will be able to observe the AI's actions, which may be beneficial to his understanding of how the AI works.

> alternatively we could just say `right or left clicking`.

Since "by pressing" is used for keys and is not really suitable for clicks (mouse or other, we press a button not a click), there is need to use a more appropriate term for clicks and in the same style as "by pressing", "by performing" is fine.

Why replace the word "time" with "moment"?

What about:
"The computer continues the combat for you, while you watch the progression of the combat.

This can be interrupted at any time by pressing the Auto Combat hotkey or the default Cancel key, or by performing a left or right click anywhere on the game screen."

2025-01-17 08:59 UTC, Branikolog commented
>"The combat is resolved from the current state to the end."

Looks nice.
However "The combat ends instantly from the current state." looked good for me too.

>The "at the currently set combat speed" part of the sentence will raise a question in the user's mind: "What does that mean?"; whereas the text should be descriptive and clear.

I agreed. Mentioning speed is useless in the description. 
Mentioning "the progression of the combat" also feels redundant, since we're mentioning in the following description, that the battle could be interrupted at any moment...

What about more short and simple? "The computer continues the combat for you in auto mode/automatically"? 
I'm even OK with "The computer continues the combat for you."

2025-01-17 10:22 UTC, LeHerosInconnu commented
@Branikolog and @zenseii,

So, I am fine to go with:

"The combat is resolved from the current state.

This cannot be undone."

and:

"The computer continues the combat for you.

This can be interrupted at any moment by pressing the Auto Combat hotkey or the default Cancel key, or by performing a left or right click anywhere on the game screen."

2025-01-17 11:25 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +            return;
I changed the logic to immediately `return` here and in the similar case above instead of checking for `!actions.empty()`, because in theory technically `actions` can already be non-empty when calling this method.

2025-01-17 11:29 UTC, oleg-derevenetz commented on src/fheroes2/dialog/dialog_system_options.cpp
> +            std::string value = spellcast ? _( "Quick Combat" ) : _( "Quick, No Spells" );
I wonder if it's worth leaving the old wording here specifically, because technically "Auto Resolve" is better suited here, IMHO - the computer here really tries to conduct a quick combat at first, but this is not the only thing it does - it also offers to conduct the manual battle if you don't like the results.

2025-01-17 11:38 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +            return;
OK, I changed the logic a bit by changing the return type of `EventStartAutoCombat()` and `EventQuickCombat()` methods, now it should work in a more convenient way.

2025-01-17 12:00 UTC, oleg-derevenetz commented on src/fheroes2/dialog/dialog_system_options.cpp
> +            std::string value = spellcast ? _( "Quick Combat" ) : _( "Quick, No Spells" );
OK, I reverted this place to the previous wording.

2025-01-17 12:01 UTC, oleg-derevenetz approved these changes

2025-01-17 12:02 UTC, oleg-derevenetz commented on src/fheroes2/battle/battle_interface.cpp
> +            return;
> I also just realized that we need to setup a cursor restorer for this dialog because the cursor in this dialog currently lacks the yellow outline which it has in the confirmation dialogs and the combat settings dialog.

Do as you see fit :)

2025-01-18 04:41 UTC, ihhub commented on src/fheroes2/game/game_hotkeys.cpp
> +                    // TODO: remove this temporary workaround
Hi @oleg-derevenetz , as you mentioned yourself we should be reluctant to changing the hotkeys file. However, such cases might happen and it could be an improvement or literally a bug fix. We could actually introduce versioning through a separate parameter in this file. If users mess this parameters it would be on their shoulders.

We could do this in a separate pull request as @zenseii did a lot of work here and we would like to proceed with the changes.

2025-01-18 04:41 UTC, ihhub approved these changes

2025-01-18 04:42 UTC, merged

2025-01-18 04:42 UTC, ihhub commented
@zenseii , many thanks for this useful feature!