Update the Czech translation
ihhub/fheroes2 pull request #9189
Opened 2024-10-12 20:54 UTC by GeorgeK1ng

1) 100% Czech translation
Fixed previous translation text - castle building names and all troops. Fixed typos, improved and corrected text on existing 52% translation - touched almost all strings.
Finished remaining 48% of non-translated text. Tested with v1.1.2 public version and original Heroes of Might and Magic II Gold Czech files by CDPROJEKT.

Also tested few maps and game play looks fine. Will see what will be fixed or improved in future. Now is game perfectly playable for Czech users!

2024-10-13 09:22 UTC, GeorgeK1ng commented
Hi, no one from developers speak Czech. Virtual Keyboard could be saparated, but it's like 10 lines of code only. 
But it makes no sence with whole translation, I used POEdit, everything was using gived rules. I already told this on discord. They should discuss it in internal team. I have spend time to make game play for Czech community. Revised whole text in current translation which was unusable and really broken.
I will polish this 100% in future when needed, then of course in small chunks. I'm not going to make 10 PRs if we cound with 400 lines in each just for review rule. As nobody from developers speak Czech it's up to me. I made whole translation review and fullfilled it to make it 100% and usable to gaming. I have also played various maps and tested it. It works like a charm. File diff looks fine and it's just addition of 100% translation. I hope they can do exception to accept whole translation at once. Otherwise it was waste of time to make this translation.

2024-10-13 11:24 UTC, ihhub commented
Hi @GeorgeK1ng ,

each pull request should be dedicated to solve one particular thing. This is true for almost every software development project and it is being done to focus only one thing during pull request review and also to keep track of changes in the future. Therefore, please create a separate pull request regarding the virtual keyboard changes.

Regarding the translation part and the size of this pull request. Even despite of a fact that possibly none of developers from the core team speak native Czech, we still review the code as we do for every single translation. This means that the amount of work for checking 2000 lines is gigantic and more code / lines to review, the higher chance of missing any mistakes in the code. Having multiple pull requests is not a problem at all as it is simply a copy-pasted text approach. Knowing line numbers from the file gives precise answer what to copy.

We do not blindly accept any changes in the code without reviewing them. This means that 2 people must manually review the pull request by reading every single line of the changes. You can calculate the amount of time it takes by multiplying (the amount of time to read every single line changed) by (the number of people reviewing it) and (by a factor of 2-4 since it is not native language for us). I think it would give you a rough estimation how much time we would need to review this big text.

Moreover, we can also ask @agiat86 and @joyinko to review the changes but I highly doubt that anyone is willing to read 4000+ lines of text.

2024-10-13 13:27 UTC, GeorgeK1ng commented
@ihhub I have removed Czech Virtual Keyboard from that branch.

@joyinko @agiat86 Can you please review my whole translation at once? I have touched that file only using POEdit. I also compared it with "empty" translation file when I removed every translation and then compare with Beyond Compare. I don't see any issue in full translation formatting as on POEdit was used to touch it. I hope for positive answer.

2024-10-13 16:05 UTC, joyinko commented on files/lang/cs.po
> +msgstr "UKONČIT"
Zde bude text moc dlouhy. Proto jsem texty v prekladu zkracoval, koukal si jak tohle vypada ve hre?

2024-10-13 16:06 UTC, joyinko commented on files/lang/cs.po
> +msgstr "PŘIJMOUT"
Zde bude text moc dlouhy. Proto jsem texty v prekladu zkracoval, koukal si jak tohle vypada ve hre?

2024-10-13 16:06 UTC, joyinko commented on files/lang/cs.po
> +msgstr "NAUČIT"
Zde bude text moc dlouhy. Proto jsem texty v prekladu zkracoval, koukal si jak tohle vypada ve hre?

2024-10-13 16:06 UTC, joyinko commented on files/lang/cs.po
> +msgstr "SMĚNIT"
Zde bude text moc dlouhy. Proto jsem texty v prekladu zkracoval, koukal si jak tohle vypada ve hre?

2024-10-13 16:07 UTC, joyinko commented on files/lang/cs.po
> +msgstr "ODEJÍT"
Zde bude text moc dlouhy. Proto jsem texty v prekladu zkracoval, koukal si jak tohle vypada ve hre?

2024-10-13 16:07 UTC, joyinko commented on files/lang/cs.po
> +msgstr "PROPUSTIT"
Zde bude text moc dlouhy. Proto jsem texty v prekladu zkracoval, koukal si jak tohle vypada ve hre?

2024-10-13 16:07 UTC, joyinko commented on files/lang/cs.po
> +msgstr "NASTAVENÍ"
Zde bude text moc dlouhy. Proto jsem texty v prekladu zkracoval, koukal si jak tohle vypada ve hre?

2024-10-13 16:08 UTC, joyinko commented on files/lang/cs.po
> +"KAMPAŇ\n"
Zde bude text moc dlouhy. Proto jsem texty v prekladu zkracoval, koukal si jak tohle vypada ve hre?

2024-10-13 16:09 UTC, joyinko commented on files/lang/cs.po
> +msgstr "POVĚSTI"
ZVESTI nebo KLEPY by se hodilo taky?

2024-10-13 16:16 UTC, joyinko commented on files/lang/cs.po
> -msgstr "Pryč"
Zde bude text moc dlouhy. Proto jsem texty v prekladu zkracoval, koukal si jak tohle vypada ve hre?

2024-10-13 16:17 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Odejít"
Zde bude text moc dlouhy. Proto jsem texty v prekladu zkracoval, koukal si jak tohle vypada ve hre?

2024-10-13 16:20 UTC, joyinko commented on files/lang/cs.po
> +msgstr "„Trpasličí zhoubaaaa!!! Utíkejte o život!“"
zhoubaaaa je takhle napsano zamerne?

2024-10-13 16:23 UTC, joyinko commented on files/lang/cs.po
> +msgstr "%{name} nelze postavit, protože hrad je moc daleko od more."
moře - bylo spravne

2024-10-13 16:30 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Klávesová zkratka "
Klávesová zkratka:

2024-10-13 16:43 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Statistiky hrdiny:"
Tohle by meli byt statistiky nejepsiho hrdiny. **Best** Hero.

2024-10-13 18:33 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Statistiky hrdiny:"
Na té obrazovce se zobrazují jen statistiky nejlepšíh hrdinů, pokud se nepletu.

2024-10-13 18:33 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "„Trpasličí zhoubaaaa!!! Utíkejte o život!“"
Jo, můžeme klidně přepsat.

2024-10-13 18:34 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "POVĚSTI"
Použil jsem pověsti všude, pasuje mi to více do hry.

2024-10-13 18:35 UTC, GeorgeK1ng commented on files/lang/cs.po
> +"KAMPAŇ\n"
V originálu je to přesně takto a vešlo se to tam.

2024-10-13 18:42 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Klávesová zkratka "
Opraveno

2024-10-13 18:42 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "%{name} nelze postavit, protože hrad je moc daleko od more."
Opraveno

2024-10-13 18:42 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "„Trpasličí zhoubaaaa!!! Utíkejte o život!“"
Opraveno

2024-10-13 18:42 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Odejít"
Opraveno

2024-10-13 18:42 UTC, GeorgeK1ng commented on files/lang/cs.po
> +"KAMPAŇ\n"
Opraveno

2024-10-13 18:43 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "NASTAVENÍ"
Opraveno

2024-10-13 18:43 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "PROPUSTIT"
Opraveno

2024-10-13 18:43 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "ODEJÍT"
Opraveno

2024-10-13 18:43 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "SMĚNIT"
Opraveno

2024-10-13 18:43 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "NAUČIT"
Opraveno

2024-10-13 18:43 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "PŘIJMOUT"
Opraveno

2024-10-13 18:44 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "UKONČIT"
Opraveno

2024-10-13 18:48 UTC, GeorgeK1ng commented
Updated mentioned things. Mostly things to polish during longer gameplays.

2024-10-14 07:05 UTC, joyinko commented
Hi guys, I commented some rows already yesterday. 
I will need more time to finish it unfortunately.
Anyways, the translation quality and fixes are so far good, very good.

Thank you @GeorgeK1ng

Joyinko


 ** Sun, 13 Oct 2024 04:24:48 -0700 - "ihhub/fheroes2" ***@***.***>, "ihhub/fheroes2" ***@***.***> **

 Hi @GeorgeK1ng ,
 
 each pull request should be dedicated to solve one particular thing. This is true for almost every software development project and it is being done to focus only one thing during pull request review and also to keep track of changes in the future. Therefore, please create a separate pull request regarding the virtual keyboard changes.
 
 Regarding the translation part and the size of this pull request. Even despite of a fact that possibly none of developers from the core team speak native Czech, we still review the code as we do for every single translation. This means that the amount of work for checking 2000 lines is gigantic and more code / lines to review, the higher chance of missing any mistakes in the code. Having multiple pull requests is not a problem at all as it is simply a copy-pasted text approach. Knowing line numbers from the file gives precise answer what to copy.
 
 We do not blindly accept any changes in the code without reviewing them. This means that 2 people must manually review the pull request by reading every single line of the changes. You can calculate the amount of time it takes by multiplying (the amount of time to read every single line changed) by (the number of people reviewing it) and (by a factor of 2-4 since it is not native language for us). I think it would give you a rough estimation how much time we would need to review this big text.
 
 Moreover, we can also ask @agiat86 and @joyinko to review the changes but I highly doubt that anyone is willing to read 4000+ lines of text.
 
 -- 
 Reply to this email directly or view it on GitHub:
 https://github.com/ihhub/fheroes2/pull/9189#issuecomment-2408939205
 You are receiving this because you were mentioned.
 
 Message ID: ***@***.***>

2024-10-14 07:17 UTC, GeorgeK1ng commented
@joyinko Thanks, I'm sure there will be of course needed a touch. But it will be like quality fixes, to impove game play. I played about 30 hours and fixed what I found. I had no time to test Campaings now. This I can do later on my tablet when 100% translation will be included in Android APK to make it "portable" fo travelling instead of gaming on PC :)

2024-10-15 13:40 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Upg. Obydlí 6"
"2x Upg. Obydlí 6"

2024-10-15 13:48 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Kliknutím se rozliśení změní na vybrané."
"Kliknutím se rozlišení změní na vybrané."

2024-10-15 13:51 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Vyberte oceánský object:"
"Vyberte oceánský objekt:"

2024-10-15 14:03 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Mapy je poškozena."
"Mapa je poškozena."

2024-10-15 14:10 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Podmínky pro výhru"
Nejsou tohle speciální podmínky?

2024-10-15 14:10 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Podmínky pro prohru"
Nejsou tohle speciální podmínky?

2024-10-15 14:11 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Nastevení aliancí:"
"Nastavení aliancí:"

2024-10-15 14:13 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Tyh hráče"
"Typ hráče"

2024-10-15 14:15 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Mřížka"
"Průchodnost"

2024-10-15 14:21 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Zobrazir nejlepší výsledky kampaně."
"Zobrazit nejlepší výsledky kampaně."

2024-10-15 14:23 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Vybra extra velkou mapu"
"Vybrat extra velkou mapu"

2024-10-15 14:27 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Přístap"
"Přístav"

2024-10-15 14:28 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Sloučit jednotku"
"Sloučit jednotky"

2024-10-15 14:31 UTC, joyinko commented on files/lang/cs.po
> +"Vítej ve hře Heroes of Might and Magic II běžící na enginu fheroes2!\n"
všude je teď vykání, takže **Vítejte**

2024-10-15 14:38 UTC, joyinko commented on files/lang/cs.po
> +"Jeden nebo více hrdinů se ještě může pohybovat, určitě chceš ukončit svůj "
"Jeden nebo více hrdinů se ještě může pohybovat, určitě chcete ukončit svůj "

2024-10-15 14:39 UTC, joyinko commented on files/lang/cs.po
> +"Zobrazuje informaci o stavu tvého království nebo hrdinech, dále zobrazuje "
vašeho, nebo nic

2024-10-15 14:39 UTC, joyinko commented on files/lang/cs.po
> +"Toto okénko poskytuje informaci o stavu tvého království, zobrazuje datum. "
vašeho, nebo nic

2024-10-15 14:41 UTC, joyinko commented on files/lang/cs.po
> +"S každým dalším obsazeným majákem budou tvé lodě moci doplout každý den o "
vaše

2024-10-15 14:43 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Bohužel to vypadá, že ti momentálně schází zlato."
vám

2024-10-15 14:44 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Vodní vír pohltil tvou loď. Část posádky spadla přes palubu."
vaší loď

2024-10-15 14:57 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Upg. Obydlí 6"
Opraveno

2024-10-15 14:58 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Kliknutím se rozliśení změní na vybrané."
Opraveno

2024-10-15 14:58 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Vyberte oceánský object:"
Opraveno

2024-10-15 15:00 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Toto kouzlo nebude na nikoho učinkovat."
Překlad je Kouzlo nenalezeno, nevím v jakém kontextu toto vyskakuje?

2024-10-15 15:00 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Nastevení aliancí:"
Opraveno

2024-10-15 15:01 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Tyh hráče"
Opraveno

2024-10-15 15:02 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Mřížka"
Opraveno, ale stejně mi přijde, že ta mřížka tam pasuje lépe.

2024-10-15 15:02 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Vedoucí programáto"
Opraveno

2024-10-15 15:03 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Vybra extra velkou mapu"
Opraveno

2024-10-15 15:03 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Přístap"
Opraveno

2024-10-15 15:04 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Sloučit jednotku"
Opraveno

2024-10-15 15:05 UTC, GeorgeK1ng commented on files/lang/cs.po
> +"Jeden nebo více hrdinů se ještě může pohybovat, určitě chceš ukončit svůj "
Opraveno

2024-10-15 15:06 UTC, GeorgeK1ng commented on files/lang/cs.po
> +"Zobrazuje informaci o stavu tvého království nebo hrdinech, dále zobrazuje "
Opraveno

2024-10-15 15:08 UTC, GeorgeK1ng commented on files/lang/cs.po
> +"S každým dalším obsazeným majákem budou tvé lodě moci doplout každý den o "
Opraveno

2024-10-15 15:08 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Vodní vír pohltil tvou loď. Část posádky spadla přes palubu."
Opraveno

2024-10-15 15:09 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Bohužel to vypadá, že ti momentálně schází zlato."
Opraveno

2024-10-15 15:11 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Toto kouzlo nebude na nikoho učinkovat."
Taky zatím netuším, opraveno.

2024-10-15 15:11 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Zobraz přehled království."
Opraveno

2024-10-15 15:12 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Mapy je poškozena."
Opraveno

2024-10-15 15:15 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Podmínky pro výhru"
Opraveno

2024-10-15 15:15 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Podmínky pro prohru"
Opraveno

2024-10-15 15:17 UTC, GeorgeK1ng commented
Uploaded cs.po with all mentioned fixes.

2024-10-15 15:20 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Nekonečná brašna zlata"
bezedná?

2024-10-15 15:23 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Nekonečná brašna síry"
bezedná?

2024-10-15 15:23 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Nekonečná ampule rtuti"
bezedná?

2024-10-15 15:24 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Nekonečná otep dřeva"
bezedná?

2024-10-15 15:24 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Nekonečný vozík s kamením"
bezedný?

2024-10-15 15:24 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Nekonečný sáček krystalů"
bezedný?

2024-10-15 15:29 UTC, joyinko commented on files/lang/cs.po
> +msgstr "Lopata nekromancie"
Rýč, lopata je shovel. Pokud to nebyl záměr...

2024-10-15 15:32 UTC, joyinko commented on files/lang/cs.po
> +"zasáhne nejbližší stvůru s polovičním poškozením a poté zasáhne DALŠÍ "
jednotku/y místo stvůry používej všude, pokud to chceš zaměnit

2024-10-15 15:39 UTC, GeorgeK1ng commented on files/lang/cs.po
> +"zasáhne nejbližší stvůru s polovičním poškozením a poté zasáhne DALŠÍ "
Opraveno

2024-10-15 15:45 UTC, joyinko reviewed
@GeorgeK1ng , já jsem hotov. Prosím mrkni na poznámky, případně uprav pokud uznáš za vhodné. Ďekuji
@ihhub, I am done here, left some comments for GeorgeK1ng. Just minor stuff. I am not playing fheroes at the moment so not sure about text fitting on the tiles. That is for our contirbutor, I guess. I was only focused on translation itself. Please let me know if you need me to approve this pull request? thanks

2024-10-15 15:57 UTC, GeorgeK1ng commented
@joyinko I'm creating righ now map in original Heroes 2 with all artefacts to make them 1:1 to make it like original translator (Gremlin) did it. Sad is I have no documentation available for artefacts. I will rewrite it in few hours and upload modded file. Every other note was closed and fixed. Great polishment start.

2024-10-15 16:09 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Nekonečná brašna zlata"
Bezedná tobolka zlata, opraveno.

2024-10-15 16:11 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Nekonečná brašna zlata"
Bezedná taška zlata, opraveno

2024-10-15 16:16 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Nekonečná ampule rtuti"
Bezedná ampule truti, opraveno.

2024-10-15 16:21 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Nekonečný sáček krystalů"
Bezedná mošna krystalů, opraveno

2024-10-15 16:22 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Nekonečný vozík s kamením"
Bezedný vozík kamení, opraveno

2024-10-15 16:23 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Nekonečný sáček drahokamů"
Bezedná mošna drahokamů, opraveno

2024-10-15 16:26 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Nekonečná brašna síry"
Bezedná mošna síry, opraveno

2024-10-15 16:27 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Nekonečná otep dřeva"
Bezedný sáh dřeva, opraveno

2024-10-15 16:39 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Lopata nekromancie"
Rýč nekromancie, opraveno

2024-10-16 07:40 UTC, joyinko approved these changes
Approved, for future please follow the rules and keep ammount of changes at reasonable size.
thx

2024-10-16 19:53 UTC, GeorgeK1ng commented
@ihhub I hope we can get this translation alive in v1.1.3 if possible.

2024-10-19 08:06 UTC, GeorgeK1ng commented
@ihhub I have added 2 new lines translated which you merged into my branch tonight. Now it's 100% Czech again.

2024-10-21 14:27 UTC, ihhub requested changes
Hi @GeorgeK1ng , I left several comments here. I didn't check the whole translation as it is beyond time to be completed in 1 shot. Most of comments fall into 2 categories:
- remove parts of the translation. which very added recently
- usage of `„` and `“` symbols which I think don't exist in the game

Please take a look at the comments.

2024-10-21 14:27 UTC, ihhub commented on files/lang/cs.po
> -msgid "You cannot cast spells without a commanding hero."
Revert this change back.

2024-10-21 14:27 UTC, ihhub commented on files/lang/cs.po
> +msgstr "Pokročilá Lukostřelba"
Can you check how it looks in the Hero's dialog? Does it fit within the skill area?

2024-10-21 14:27 UTC, ihhub commented on files/lang/cs.po
> +msgstr "Odejít"
Should it be a longer text than just Exit?

2024-10-21 14:27 UTC, ihhub commented on files/lang/cs.po
> -msgid "Select Language:"
Please revert this change back.

2024-10-21 14:27 UTC, ihhub commented on files/lang/cs.po
>  msgstr "Vybrat jazyk:"
We differentiate game's language and just language which could be a language of a map.

2024-10-21 14:27 UTC, ihhub commented on files/lang/cs.po
> -#, fuzzy
Revert this change back.

2024-10-21 14:27 UTC, ihhub commented on files/lang/cs.po
> -msgid ""
Revert this change back and the one below.

2024-10-21 14:27 UTC, ihhub commented on files/lang/cs.po
> -msgid "Click to change the language of the map."
Revert this change back.

2024-10-21 14:27 UTC, ihhub commented on files/lang/cs.po
> +msgstr "Z věži slyšíte hlas: „Jdi pryč! Nemohu ti pomoci!"
I don't think symbol `„` exists in the game resources. Also, there is no closing symbol for the phrase.

2024-10-21 14:27 UTC, ihhub commented on files/lang/cs.po
> +"Zpoza zamčených dveří slyšíte hlas: „Nemáte dost zlata na zaplacení mých "
I don't think symbol `„` exists in the game resources. Also, there is no closing symbol for the phrase.

2024-10-21 14:27 UTC, ihhub commented on files/lang/cs.po
> +"hrdle. „Tvůj život je můj,“ říká. „Prodám ti ho zpět za %{count} zlata."
I don't think symbol `„` and `“` exist in the game resources.

2024-10-21 14:27 UTC, ihhub commented on files/lang/cs.po
> +"V jeskyni narazíte na mocného a groteskního Démona. „Dnes,“ huhlá, „budete "
I don't think symbol `„` and `“` exist in the game resources.

2024-10-21 14:27 UTC, ihhub commented on files/lang/cs.po
> +"Hlavní ošetřovatel vám říká: „To je pěkný kůň, kterého máte. Obávám se, že "
I don't think symbol `„` exists in the game resources. Also, there is no closing symbol for the phrase.

2024-10-21 14:27 UTC, ihhub commented on files/lang/cs.po
> +"válečného koně. „Tento kůň vám pomůže urychlit vaše cesty. Ach, za týden se "
I don't think symbol `„` exists in the game resources. Also, there is no closing symbol for the phrase.

2024-10-21 15:13 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Pokročilá Lukostřelba"
I have already fixed campaign skills here, just waited for merge, then PR update with small changes.

2024-10-21 15:14 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Odejít"
I just copied that logic from original game.

2024-10-21 15:18 UTC, GeorgeK1ng commented on files/lang/cs.po
> +"Zpoza zamčených dveří slyšíte hlas: „Nemáte dost zlata na zaplacení mých "
Already fixed them here, just waited for merge to PR small update.

2024-10-21 15:18 UTC, GeorgeK1ng commented on files/lang/cs.po
> +"hrdle. „Tvůj život je můj,“ říká. „Prodám ti ho zpět za %{count} zlata."
Already fixed them here, just waited for merge to PR small update.

2024-10-21 15:18 UTC, GeorgeK1ng commented on files/lang/cs.po
> +"Hlavní ošetřovatel vám říká: „To je pěkný kůň, kterého máte. Obávám se, že "
Already fixed them here, just waited for merge to PR small update.

2024-10-21 15:18 UTC, GeorgeK1ng commented on files/lang/cs.po
> +"válečného koně. „Tento kůň vám pomůže urychlit vaše cesty. Ach, za týden se "
Already fixed them here, just waited for merge to PR small update.

2024-10-21 15:18 UTC, GeorgeK1ng commented on files/lang/cs.po
> +"V jeskyni narazíte na mocného a groteskního Démona. „Dnes,“ huhlá, „budete "
Already fixed them here, just waited for merge to PR small update.

2024-10-21 15:21 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Z věži slyšíte hlas: „Jdi pryč! Nemohu ti pomoci!"
Already fixed them here, just waited for merge to PR small update.

2024-10-21 15:30 UTC, GeorgeK1ng commented on files/lang/cs.po
> -#, fuzzy
Reverted, even it's perfectly translatable.

2024-10-21 15:32 UTC, GeorgeK1ng commented on files/lang/cs.po
> -msgid "You cannot cast spells without a commanding hero."
Fixed

2024-10-21 17:24 UTC, GeorgeK1ng commented on files/lang/cs.po
> +msgstr "Odejít"
Fixed as requested

2024-10-21 17:25 UTC, GeorgeK1ng commented on files/lang/cs.po
>  msgstr "Vybrat jazyk:"
Fixed

2024-10-21 17:26 UTC, GeorgeK1ng commented on files/lang/cs.po
> -msgid ""
Fixed

2024-10-21 17:26 UTC, GeorgeK1ng commented on files/lang/cs.po
> -msgid "Click to change the language of the map."
Fixed

2024-10-21 17:37 UTC, GeorgeK1ng commented
@ihhub I understand, that comparing files on GitHub is real pain. Thats why I never use GitHub files compare. To easily check that my latest cs.po is fine, do it localy please. Download cs.po from your repo as cs_old.po, cs.po from my repo as cs_100%.po. Download Beyond Compare if don't have it. It's trial without any limitations. Drag both files into Beyond Compare and scroll. In few minutes you will see what was changed according to original file. It's easy and fast using this way.

Reason why I have not uploaded my updated cs.po with for example Campaing bonuses was simple, I was waiting for merge, to upload small fixes PR instead of huge one.

What you mean with parts that was added recently? You mean your two lines that were pushed to my translated branch?

2024-10-21 19:19 UTC, GeorgeK1ng reviewed
Fixed needed things

2024-11-09 14:45 UTC, GeorgeK1ng commented on files/lang/cs.po
> +"pohyb."
Hi, this translation is fine, it makes sense in Czech and it means what you are talking about. It's still the same Czech sentence as before my touch, just better written.

2024-11-09 14:49 UTC, GeorgeK1ng reviewed
Nothing to change

2024-11-17 02:51 UTC, ihhub approved these changes

2024-11-19 22:47 UTC, GeorgeK1ng commented
Can we see this in 1.1.4 please?

2024-11-21 10:02 UTC, merged

2024-11-21 15:29 UTC, GeorgeK1ng commented
Thanks! Lets see what we need to improve it future! I think there will be just minor changes :)