Added Czech Virtual Keyboard
ihhub/fheroes2 pull request #9203
Opened 2024-10-15 16:54 UTC by GeorgeK1ng

Added Czech Virtual Keyboard

![image](https://github.com/user-attachments/assets/1df1c0a6-b0ef-46b9-9a55-782ce23a43db)

P.S. Special letters Ť, Ó, Ň, Ď that are not available on physical keyboard are not included.

2024-10-17 23:55 UTC, ihhub requested changes
Hi @GeorgeK1ng , I added one comment here. Can you please take a look at it?

2024-10-17 23:55 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
> +        case fheroes2::SupportedLanguage::Czech:
Please sort languages in an alphabetic order in all places we changed.

2024-10-18 06:03 UTC, GeorgeK1ng commented on src/fheroes2/gui/ui_keyboard.cpp
> +        case fheroes2::SupportedLanguage::Czech:
Done

2024-10-18 06:24 UTC, GeorgeK1ng commented
@ihhub Fixed as requested

2024-10-18 10:41 UTC, GeorgeK1ng commented
> @GeorgeK1ng
> 
> > P.S. Special letters Ť, Ó, Ň, Ď that are not available on physical keyboard are not included.
> 
> Could you please elaborate. To me it seems strange that if these letters are needed to write Czech but we don't make them available. This keyboard is the only way to insert special letters and so this would not be good for map makers or players who want to write Czech. Is this correct?

They are really rare to use. I have no idea where they are used normally. For example I don't rememeber when I used them, in job I write a lot o mails and tickets. 

Of course it's easy to add them, but they are not listed on physical keyboard. You need to use some kind of key kombinations.

I don't think someone will reguest them, they are realy rarely used.

2024-10-18 15:26 UTC, ihhub approved these changes

2024-10-18 15:27 UTC, merged

2024-10-18 15:27 UTC, ihhub commented
@GeorgeK1ng , many thanks for this update!

2024-10-18 16:06 UTC, GeorgeK1ng commented
@ihhub I hope the Czech community will appreciate it :)