ui_button.cpp/.h code clean
ihhub/fheroes2 pull request #9206
Opened 2024-10-16 17:51 UTC by Districh-ru

This PR updates the `ui_button.cpp` and `ui_button.h` code:
- use `unique_prt` instead of `new`/`delete`;
- remove the never set `Display & output = Display::instance()` argument and call `Display::instance()` only when it is needed for render;
- make some methods inline (move from cpp to h);
- ...

2024-10-20 07:59 UTC, ihhub requested changes
Hi @Districh-ru , I left one comment here. Can you please check it?

2024-10-20 07:59 UTC, ihhub commented on src/fheroes2/gui/ui_button.h
> -        bool drawOnPress( Display & output = Display::instance() );
Having `Display & output` an input argument was deliberate decision. The only problem I see here is that it should be `Image` instead of `Display`. It was done to support rendering buttons on an image rather than on screen for the future image scaling support for Virtual Keyboard, battle and castle dialogs and etc. I suggest not to simplify things here and in other similar places.

2024-10-20 13:32 UTC, Districh-ru commented on src/fheroes2/gui/ui_button.h
> -        bool drawOnPress( Display & output = Display::instance() );
Hi, @ihhub,
I've reverted this change.

We can not use `Image` instead of `Display` because we do `output.render();'.
But it looks really odd: we have the only instance oа `Display` and if I'm not wrong there will never be other argument than `Display::instance()`. That's why I removed `Display & output = Display::instance()`.

And as we can see this forced render is not needed (and is harmful) in some places.
Probably we need functions like "drawOnPressWithoutRender( Image & output )" :)

2024-10-20 14:02 UTC, ihhub commented on src/fheroes2/gui/ui_button.h
> -        bool drawOnPress( Display & output = Display::instance() );
We can do a trick to create another class which can accept in constructor either `Image` or `Display`. Based on given input it could behave one way or another. But, we need to think about a proper solution for this.

2024-10-20 14:05 UTC, ihhub commented on src/fheroes2/gui/ui_button.h
> -        bool drawOnPress( Display & output = Display::instance() );
However, I suggest to replace (in another pull request) many instances of
```cpp
button.isEnabled() && le.isMouseLeftButtonPressedInArea( button.area() ) ? button.drawOnPress() : button.drawOnRelease();
```
by
```cpp
button.drawOnState( le.isMouseLeftButtonPressedInArea( button.area() ) );
```
This will be a step forward for maintaining and improving the code. What do you think?

2024-10-20 14:21 UTC, Districh-ru commented on src/fheroes2/gui/ui_button.h
> -        bool drawOnPress( Display & output = Display::instance() );
I fully agree that the next (in a new PR) we should use `drawOnState()` in any place we can to have the same logic in all places.
And the next we should think about "forced render" issue and using `Image` instead of `Display`.
Maybe by using new method `drawAndRenderToScreen()` that will always use `Display` and render to it and another function with `Image` as input argument that will only `draw()` without `render()`.

2024-10-21 14:57 UTC, ihhub requested changes
Hi @Districh-ru , I left 2 more comments here. Can you please take a look at them?

2024-10-21 14:57 UTC, ihhub commented on src/fheroes2/gui/ui_button.cpp
> +                le.isMouseLeftButtonPressedInArea( button->area() ) ? button->drawOnPress() : button->drawOnRelease();
Since we are touching this code should we use `drawOnState()` call here?

2024-10-21 14:57 UTC, ihhub commented on src/fheroes2/gui/ui_button.h
> +        ButtonSprite( const int32_t offsetX, const int32_t offsetY, Sprite released, Sprite pressed, Sprite disabled = Sprite() )
We can use `Sprite disabled = {}` to have more flexibility but this is optional.

2024-10-21 15:23 UTC, Districh-ru commented on src/fheroes2/gui/ui_button.cpp
> +                le.isMouseLeftButtonPressedInArea( button->area() ) ? button->drawOnPress() : button->drawOnRelease();
Hi, @ihhub, sure!
I've started to do such changes in the code and will open a PR soon.

2024-10-21 15:23 UTC, Districh-ru commented on src/fheroes2/gui/ui_button.h
> +        ButtonSprite( const int32_t offsetX, const int32_t offsetY, Sprite released, Sprite pressed, Sprite disabled = Sprite() )
Done!

2024-10-21 15:31 UTC, ihhub approved these changes

2024-10-23 23:27 UTC, merged

2024-10-23 23:27 UTC, ihhub commented
@Districh-ru , thank you very much for this cleanup!