Use drawOnState() for buttons precessing and cache buttons' position for event handler loop
ihhub/fheroes2 pull request #9223
Opened 2024-10-21 23:08 UTC by Districh-ru

This PR affects most of the dialogs in the engine including the main menu.

It replaces `le.isMouseLeftButtonPressedInArea( button.area() ) ? button.drawOnPress() : button.drawOnRelease();` with `button.drawOnState( le.isMouseLeftButtonPressedInArea( buttonArea ) );` and do `buttonArea` cache not to call `.area()` with all its calculations on every loop.

It also modifies some dialogs that can be also called by the mouse right click to have its own event handler loop to reduce some checks. And in some dialogs it skips the possibly unused buttons initialization making them `unique_ptr`, in example in Hero dialog: DISMISS and PATROL buttons.

2024-10-26 10:42 UTC, ihhub requested changes

2024-10-26 14:11 UTC, Districh-ru commented on src/fheroes2/battle/battle_dialogs.cpp
> +            else if ( le.MouseClickLeft( optionAreas[7] ) ) {
Hi, @ihhub, thanks for pointing this out!
I've fixed this and other places.

2024-11-17 08:03 UTC, Districh-ru commented on src/fheroes2/battle/battle_dialogs.cpp
> +    std::unique_ptr<fheroes2::Rect> buttonRestartArea;
When the button is made its `area()` is often used.
Then should we just add `fheroes2::Rect _areaPressed;` and `fheroes2::Rect _areaReleased;` to the `ButtonBase` class?
Then we can make an inline method like:
```cpp
Rect & area()
{
    return _isPressed ? _areaPressed : _areaReleased;
}
```
And then remove all caches in of `area()` in the code.
What do you think, @ihhub?

2024-11-17 11:37 UTC, Districh-ru commented on src/fheroes2/battle/battle_dialogs.cpp
> +    std::unique_ptr<fheroes2::Rect> buttonRestartArea;
@ihhub, 
I've made the proposed change to cache area in `ButtonBase` class and the just return a const reference to it by `area()` call.

2024-12-03 12:06 UTC, ihhub reviewed
Hi @Districh-ru , I left just one small comment here. Would you mind please to take a look at it?

2024-12-03 12:06 UTC, ihhub commented on src/fheroes2/gui/ui_button.h
> +    private:
I suggest to keep the same section for these virtual functions for easier code reading. Having the section for base and child classes reduces confusion with understanding of sections.

The class is already marked as `final` so no other code can access protected section.

2024-12-03 14:27 UTC, Districh-ru commented on src/fheroes2/gui/ui_button.h
> +    private:
Sure!

2024-12-04 03:22 UTC, ihhub approved these changes

2024-12-05 14:19 UTC, merged

2024-12-05 14:19 UTC, ihhub commented
@Districh-ru , a bunch of thanks for these corrections!