Move Streams handling in Editor from "world" tiles to "Map_Format"
ihhub/fheroes2 pull request #9264
Opened 2024-11-09 14:48 UTC by Districh-ru

Relates to #8589

This PR updates Streams placing, removing and connecting with river deltas in Editor.

2024-11-14 10:56 UTC, Branikolog approved these changes

2024-11-17 03:23 UTC, ihhub requested changes
Hi @Districh-ru , I added several comments and suggestions here. Could you please take a look at them once you have time?

2024-11-17 03:23 UTC, ihhub commented on src/fheroes2/maps/map_format_helper.h
> +    int getRiverDeltaDirectionByIndex( const int32_t objectIndex );
This function's real return value is used only in 2 places while in other places we just verify that the value is valid. I suggest to create a separate function that will return a boolean variable to simply check if an object is a river delta. For example,
```cpp
bool isRiverDeltaObject( const ObjectGroup group, const uint32_t objectIndex );

...

bool isRiverDeltaObject( const ObjectGroup group, const uint32_t objectIndex )
{
    return getRiverDeltaDirectionByIndex( group, objectIndex ) != Direction::UNKNOWN;
}
```

2024-11-17 03:23 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +        for ( size_t mapTileIndex = 0; mapTileIndex < mapFormat.tiles.size() && !objectsUids.empty(); ++mapTileIndex ) {
Having several conditions in a foor loop might be problematic for some developers to read. Since we already have this code below:
```cpp
                if ( objectsUids.empty() ) {
                    break;
                }
```

I suggest to do the same for this loop as well.

2024-11-17 03:23 UTC, ihhub commented on src/fheroes2/maps/map_format_helper.cpp
> +    bool isNeedStreamToDeltaConnection( Maps::Map_Format::MapFormat & map, const int32_t tileId, const int direction )
Let's call this function as `isStreamToDeltaConnectionNeeded`.

2024-11-17 03:23 UTC, ihhub commented on src/fheroes2/maps/map_format_helper.cpp
> +        for ( const int direction : { Direction::LEFT, Direction::TOP, Direction::RIGHT, Direction::BOTTOM } ) {
Is there a need to run this loop when **streamDirection** is 0?

2024-11-17 03:23 UTC, ihhub commented on src/fheroes2/maps/map_format_helper.cpp
> +        const uint8_t objectIndex = getStreamIndex( forceStreamOnTile ? ( direction | Direction::CENTER ) : direction );
I am thinking should we avoid magic numbers in the code like here and just return a boolean variable for the function while the real value can be assigned into a second input argument. What do you think?

2024-11-17 03:23 UTC, ihhub commented on src/fheroes2/maps/map_format_helper.cpp
> +            if ( !Maps::setObjectOnTile( world.getTile( tileId ), objectInfo, true ) ) {
Do we need to do this on a tile of Adventure Map since we refresh the whole map after?

2024-11-17 03:23 UTC, ihhub commented on src/fheroes2/maps/map_format_helper.cpp
> +    bool addStreamToMap( Map_Format::MapFormat & map, const int32_t tileId )
We can skip `toMap` as we are in map format helper code.

2024-11-17 03:23 UTC, ihhub commented on src/fheroes2/maps/map_format_helper.cpp
> +        if ( isStreamOnMapTile( thisTile ) || world.getTile( tileId ).isWater() ) {
I am wondering should we check group type using `thisTile` instead since we want to eliminate usage of **world** here?

2024-11-17 07:29 UTC, Districh-ru commented on src/fheroes2/maps/map_format_helper.cpp
> +        for ( const int direction : { Direction::LEFT, Direction::TOP, Direction::RIGHT, Direction::BOTTOM } ) {
Hi, @ihhub, previously it was needed because only after the call of this function we checked the `forceStreamOnTile`  and the directions around were needed for the further logic.
Now this function is changed to accept `forceStreamOnTile` and if it is **false** and `streamDirection` is **0** the function returns this **0**.

2024-11-17 07:30 UTC, Districh-ru commented on src/fheroes2/maps/map_format_helper.cpp
> +        const uint8_t objectIndex = getStreamIndex( forceStreamOnTile ? ( direction | Direction::CENTER ) : direction );
Now `forceStreamOnTile` is used in the other place and this place looks much better.

2024-11-17 07:33 UTC, Districh-ru commented on src/fheroes2/maps/map_format_helper.cpp
> +            if ( !Maps::setObjectOnTile( world.getTile( tileId ), objectInfo, true ) ) {
Yes, because when placing a stream there is no whole map refresh.
The whole map refresh is currently done for Erase and Undo/Redo operations.
In future we should avoid the whole map refresh and erase/place only one object.

2024-11-17 07:34 UTC, Districh-ru commented on src/fheroes2/maps/map_format_helper.cpp
> +        if ( isStreamOnMapTile( thisTile ) || world.getTile( tileId ).isWater() ) {
Now we use `Ground::getGroundByImageIndex( thisTile.terrainIndex )`.
Thanks!)

2024-11-17 09:14 UTC, ihhub reviewed
Hi @Districh-ru , I left 2 minor comments here. Would you mind to check them?

2024-11-17 09:14 UTC, ihhub commented on src/fheroes2/editor/editor_interface.cpp
> +                    const int riverDeltaDirection = Maps::getRiverDeltaDirectionByIndex( objectIter->group, static_cast<int32_t>( objectIter->index ) );
Here we should use `isRiverDeltaObject` function call as we don't use **riverDeltaDirection** anywhere else.

2024-11-17 09:14 UTC, ihhub commented on src/fheroes2/maps/map_format_helper.cpp
> +    bool isStreamOnMapTile( const Maps::Map_Format::TileInfo & mapTile )
Since we are passing `mapTile` as argument we could name this function as **isStreamPresent**. What do you think?

2024-11-17 09:28 UTC, Districh-ru commented on src/fheroes2/editor/editor_interface.cpp
> +                    const int riverDeltaDirection = Maps::getRiverDeltaDirectionByIndex( objectIter->group, static_cast<int32_t>( objectIter->index ) );
We use **riverDeltaDirection** at line 394:
`Maps::updateStreamsToDeltaConnection( mapFormat, static_cast<int32_t>( mapTileIndex ), riverDeltaDirection );`

2024-11-17 09:32 UTC, Districh-ru commented on src/fheroes2/maps/map_format_helper.cpp
> +    bool isStreamOnMapTile( const Maps::Map_Format::TileInfo & mapTile )
Sure.

2024-11-17 09:32 UTC, ihhub approved these changes

2024-11-17 10:46 UTC, merged

2024-11-17 10:47 UTC, ihhub commented
@Districh-ru , thank you so much for this change!