Add Virtual Numpad support
ihhub/fheroes2 pull request #9287
Opened 2024-11-20 13:02 UTC by ihhub

close #8719

2024-11-21 08:02 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
> +    const int32_t numbericWindowWidth{ 320 };
This is spelled incorrectly.

2024-11-22 13:49 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
> +            lastButtonRow.back().button.hide();
To center the rest of button.

2024-11-22 13:49 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
> +                output = std::stoi( outputString );
It is a good point. We should limit the number of digits.

2024-11-22 13:56 UTC, oleg-derevenetz commented on src/fheroes2/gui/ui_keyboard.cpp
> +                output = std::stoi( outputString );
Or, as a variant, we can catch this exception (just this one, there is also `std::invalid_argument`, but it should never be normally raised if the logic is fine) and handle it by showing some error dialog maybe (and not change the number in the corresponding input).

2024-11-22 20:37 UTC, oleg-derevenetz reviewed
Hi @ihhub I just made a few changes regarding the sanity checking improvements that should fix [this](https://github.com/ihhub/fheroes2/pull/9287#discussion_r1852681411) my comment. Also I renamed the `numbericWindowWidth` constant, which should fix also [this](https://github.com/ihhub/fheroes2/pull/9287#discussion_r1851537797) comment.

2024-11-22 20:37 UTC, oleg-derevenetz commented on src/fheroes2/gui/ui_keyboard.cpp
> -        const std::vector<SupportedLanguage> supportedLanguages = getSupportedLanguages();
What was the purpose of this line? The `supportedLanguages` variable was unused from the very beginning.

2024-11-23 04:10 UTC, ihhub commented on src/fheroes2/gui/ui_keyboard.cpp
> -        const std::vector<SupportedLanguage> supportedLanguages = getSupportedLanguages();
I think it's a leftover from the old code.

2024-11-24 05:57 UTC, Districh-ru commented on src/fheroes2/gui/ui_keyboard.cpp
> +                        handleError();
Should we show the limits values in the error message?
Currently it is not shown and players will spend some annoying time to find this limit.

2024-11-24 06:08 UTC, Districh-ru requested changes
Hi, @ihhub,
After the `handleError` dialog is shown th **OK** button stays displayed as pressed:
![изображение](https://github.com/user-attachments/assets/87c86a46-5275-4944-94d6-1da8ef16cd4b)

Also I left one suggestion. Could you take a look when you have time.

2024-11-24 06:28 UTC, Districh-ru commented
Hi, @ihhub, I've fixed the found issue and implemented a suggestion to show value limits when the entered value is out of bounds.

2024-11-24 06:35 UTC, Districh-ru approved these changes

2024-11-24 10:01 UTC, oleg-derevenetz approved these changes

2024-11-24 10:05 UTC, merged