Fix text input cursor setting for multi-line text input with many spaces at the line end
ihhub/fheroes2 pull request #9319
Opened 2024-12-05 16:22 UTC by Districh-ru

This PR fixes the issue with setting input cursor position when there are many spaces in multi-line text input: https://github.com/ihhub/fheroes2/pull/9281#issuecomment-2503107119

This PR also:
- moves `getTextInputCursorPosition()` to `ui_tool`;
- fixes horizontal position of the multi-font text line separated by `-`
master build:
![bug](https://github.com/user-attachments/assets/424dcb77-d1bd-44e5-a4c0-b4e08deea031)
this PR:
![nobug](https://github.com/user-attachments/assets/742434c6-f655-4612-bcc1-cf88c67ef90d)

2024-12-05 16:37 UTC, Districh-ru commented
Hi, @ihhub!
I've faced a strange code style check behavior: https://github.com/ihhub/fheroes2/actions/runs/12183834934/job/33986233552?pr=9319
The code was formatted using our `.clang-format` file.
And also the suggested change (https://github.com/ihhub/fheroes2/pull/9319/commits/ed153492cd40cdb63f275bdc3bb8c3689fc36fda) looks not good to me.

2024-12-06 15:58 UTC, oleg-derevenetz commented
> I've faced a strange code style check behavior: https://github.com/ihhub/fheroes2/actions/runs/12183834934/job/33986233552?pr=9319 The code was formatted using our `.clang-format` file. And also the suggested change ([ed15349](https://github.com/ihhub/fheroes2/commit/ed153492cd40cdb63f275bdc3bb8c3689fc36fda)) looks not good to me.

This formatting is because `clang-format` treats this as an assignment operation, and there is no knob yet to format assignment operations and pure virtual function declarations in a different way. Please see https://github.com/llvm/llvm-project/issues/57569 for details.

2024-12-06 20:10 UTC, oleg-derevenetz commented
Hi @Districh-ru

> I've updated this clang-format to the latest version (making a symlink to LLVM folder, VS does not look in the PATH environment variable folders) and now formatting goes like Code Style Check wants.

There is no need to create symlinks, MSVC can use a custom `clang-format` executable:

![clang-format](https://github.com/user-attachments/assets/a494b0b8-bacc-4570-b75a-56b49c3678ea)

2024-12-07 02:11 UTC, ihhub requested changes
Hi @Districh-ru , I left 2 comments here. Can you please take a look at them?

2024-12-07 02:11 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +            // To properly join multi-font text we must not ignore spaces at the text end if there is next text.
A cosmetic suggestion:
```cpp
// To properly render a multi-font text we must not ignore spaces at the end of a text entry which is not the last one.
const bool isLastTextEntry = ( i == textsCount - 1 );

_texts[i].getTextLineInfos( textLineInfos, maxWidth, rowHeight, isLastTextEntry && ignoreSpacesAtTextEnd );
```

But your version is fine as well.

2024-12-07 10:36 UTC, Districh-ru commented on src/fheroes2/gui/ui_text.h
> +                                       const bool ignoreSpacesAtTextEnd = true ) const
Hi, @ihhub, I've updated the logic a bit and now `_ignoreSpacesAtTextEnd` is a member of Text class along with `_ignoreSpacesAtLineEnd`

2024-12-08 13:53 UTC, ihhub commented on src/fheroes2/gui/ui_text.h
> +                                       const bool ignoreSpacesAtTextEnd = true ) const
Hi @Districh-ru , my comment was to still keep the **ignoreSpacesAtTextEnd** input argument but not to make it to have the default value. **ignoreSpacesAtTextEnd** is used only within `getTextLineInfos()` functions so making it as an input argument is the best solution.

2024-12-08 15:53 UTC, Districh-ru commented on src/fheroes2/gui/ui_text.h
> +                                       const bool ignoreSpacesAtTextEnd = true ) const
Hi, @ihhub, sure, lets keep is as input argument. :)
I just thought to store all "text configuration" data in the Text class.

2024-12-11 11:51 UTC, ihhub commented on src/fheroes2/gui/ui_text.h
> +                                       const bool ignoreSpacesAtTextEnd = true ) const
We can store an argument as a member of class if it's being used internally. This variable is being used only within this function 🙂

2024-12-11 11:54 UTC, ihhub approved these changes

2024-12-11 15:14 UTC, ihhub requested changes
Hi @Districh-ru , I took another round of review of this pull request as @Branikolog hasn't reviewed yet. I left few suggestions for improvements. Could you please take a look at them?

2024-12-11 15:14 UTC, ihhub commented on src/fheroes2/gui/ui_text.h
> +        void setIgnoreSpacesAtLineEnd( const bool ignoreSpacesAtLineEnd )
How about we change this method's name and the corresponding variable into:
```cpp
void keepTrailingSpaces()
{
    _keepTrailingSpaces = true;
}
```

We never use this method with an input argument as `true` in the original form.

2024-12-11 15:14 UTC, ihhub commented on src/fheroes2/gui/ui_text.h
> +                               const bool ignoreSpacesAtTextEnd ) const override;
Instead of **ignoreSpacesAtTextEnd** I am suggesting to use **ignoreTrailingSpaces** or **keepTrailingSpaces**.

2024-12-11 15:14 UTC, ihhub commented on src/fheroes2/gui/ui_text.h
>          // By default it ignores spaces at the end of the text phrase.
Please update this comment.

2024-12-11 15:14 UTC, ihhub commented on src/fheroes2/gui/ui_text.h
> +        virtual void getTextLineInfos( std::vector<TextLineInfo> & textLineInfos, const int32_t maxWidth, const int32_t rowHeight,
I don't think that we need to make this function virtual: the only place where this virtual function is being used in **getTextInputCursorPosition()** function which uses `Text` class. Therefore, this method can be a public method of `Text` class only while `MultiFontText` class should have a different private method.

Unless, we are going to use **getTextLineInfos()** method from `MultiFontText` class somewhere else in the future.

2024-12-11 17:17 UTC, Districh-ru commented on src/fheroes2/gui/ui_text.h
> +        void setIgnoreSpacesAtLineEnd( const bool ignoreSpacesAtLineEnd )
Hi, @ihhub,  sure, but I've separated `_keepLineTrailingSpaces` and `keepTextTrailingSpaces`.
The first one tells the code to keep all spaces at every line end including the end of the whole text.
The second one tells to keep spaces only at the end of the whole text, but ignore spaces at the line end if it is not the last line.

2024-12-11 17:18 UTC, Districh-ru commented on src/fheroes2/gui/ui_text.h
> +                               const bool ignoreSpacesAtTextEnd ) const override;
Ok

2024-12-11 17:19 UTC, Districh-ru commented on src/fheroes2/gui/ui_text.h
>          // By default it ignores spaces at the end of the text phrase.
Ow, i missed this.
Done!

2024-12-11 17:20 UTC, Districh-ru commented on src/fheroes2/gui/ui_text.h
> +        virtual void getTextLineInfos( std::vector<TextLineInfo> & textLineInfos, const int32_t maxWidth, const int32_t rowHeight,
Yes, currently we do not plan to do some extra operations with the multi-font texts.

2024-12-11 23:51 UTC, ihhub approved these changes

2024-12-12 15:36 UTC, merged

2024-12-12 15:37 UTC, ihhub commented
@Districh-ru , I made the tests myself. Everything works perfect. Thank you!