Fixed a bug when picking up an object whose type does not match its sprite on the map
ihhub/fheroes2 pull request #9326
Opened 2024-12-07 13:56 UTC by Districh-ru

Fix  #9322

This PR fixes such chest objects during map load and take into account a possible case when object type does not match the ICN while performing the fade-out animation.

It also has some lines updated by the new clang-format. :)

2024-12-07 14:56 UTC, Districh-ru commented
Hi, @oleg-derevenetz, for your information:
I've (automatically) formatted the code with the new clang-format (v.19.1.5) but its formatting is not good for our Code style check: https://github.com/ihhub/fheroes2/actions/runs/12213646529/job/34073492599?pr=9326  :(

So I've additionally installed LLVM v.17 to match out Code style checker clang-format version.
(For the original clang-format v.12 it is needed to revert the latest changes in the `.clang-format` file.)

2024-12-07 15:00 UTC, oleg-derevenetz commented
Well, yes, different versions of `clang-format` may have a bit different formatting logic, so it's better to use the same version of `clang-format` on both sides.

2024-12-08 13:46 UTC, ihhub requested changes
Hi @Districh-ru , I left several comments in this pull request. Would you mind please to take a look once you have spare time?

2024-12-08 13:46 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +             mainObjectType == objectType || MP2::isInGameActionObject( mainObjectType ) ) {
Is there a need to have `MP2::isInGameActionObject( mainObjectType )` check?

The original idea is to expand the functionality of this class to support removal of any object, not only an action type.

2024-12-08 13:46 UTC, ihhub commented on src/fheroes2/heroes/heroes_action.cpp
> +            removeObjectFromTileByType( tile, actualObjectType );
Wouldn't we have an assertion while passing `actualObjectType` as **MP2::OBJ_NONE** is no actual object is found at the tile?

2024-12-08 13:46 UTC, ihhub commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +                    const auto & objectInfo = Maps::getObjectInfo( Maps::ObjectGroup::ADVENTURE_WATER, seaChestObjectId );
To avoid this we can add the following code:
```cpp
static int32_t seaChestObjectId = -1;
if ( seaChestObjectId < 0 ) {
    const auto & objects = Maps::getObjectsByGroup( Maps::ObjectGroup::ADVENTURE_WATER );
    for ( size_t i = 0; i < objects.size(); ++i ) {
        if ( objects[i].objectType == MP2::OBJ_SEA_CHEST ) {
            seaChestObjectId = static_cast<int32_t>( i );
            break;
        }
    }

    assert( seaChestObjectId >= 0 );
}
```

What do you think?

2024-12-08 16:31 UTC, Districh-ru commented on src/fheroes2/heroes/heroes_action.cpp
> +             mainObjectType == objectType || MP2::isInGameActionObject( mainObjectType ) ) {
Hi, @ihhub, yes, because if the map is hacked we check if the object is active. Currently the function is called `runActionObjectFadeOutAnimation` so it is meant that the object should be an action one. :)
And this change is described in the upper comment. Currently it is a way to fix such map hacks.

I've updated the code to support also non-action objects by adding `const bool isActionObject = MP2::isInGameActionObject( objectType );` and then checking `... || ( isActionObject && MP2::isInGameActionObject( mainObjectType ) )`.

2024-12-08 16:31 UTC, Districh-ru commented on src/fheroes2/heroes/heroes_action.cpp
> +            removeObjectFromTileByType( tile, actualObjectType );
If it is so then we will break the previous assertion `assert( objectUID != 0 );`. :)
But lets be more safe - I've added `&& actualObjectType != MP2::OBJ_NONE`.

2024-12-08 16:31 UTC, Districh-ru commented on src/fheroes2/maps/maps_tiles_helper.cpp
> +                    const auto & objectInfo = Maps::getObjectInfo( Maps::ObjectGroup::ADVENTURE_WATER, seaChestObjectId );
Sure!
I just wanted to make a faster code, but lets be more safe)
I've slightly modified your suggestion to place a Sea Chest object only if it is found and to do nothing otherwise.

2024-12-09 01:05 UTC, oleg-derevenetz commented
I suppose this PR should close #9184 as well.

2024-12-09 03:03 UTC, Districh-ru commented
@oleg-derevenetz, yes, you are absolutely right!

2024-12-11 11:46 UTC, ihhub approved these changes

2024-12-11 11:46 UTC, merged

2024-12-11 11:47 UTC, ihhub commented
@Districh-ru , huge thanks for this fix!