Add 3 new variants of Observation Tower object
ihhub/fheroes2 pull request #9379
Opened 2024-12-25 05:46 UTC by ihhub

2024-12-25 08:26 UTC, oleg-derevenetz approved these changes

2024-12-25 17:35 UTC, Districh-ru requested changes
Hi, @ihhub,
I like how the new objects look! Many thanks, **PushPop**!

I left a comment regarding the passability of the Desert and Snow towers. Could you please take a look?

2024-12-25 17:35 UTC, Districh-ru commented on src/fheroes2/maps/map_object_info.cpp
> +                                                  Maps::BACKGROUND_LAYER );
Yes, there is a small pile of snow, but it does not block vertical movement on the right side of the tower.
![изображение](https://github.com/user-attachments/assets/7399f7ab-1e68-488a-9b0d-efe9a42f0c39)
Should we move the right part of this object to the `TERRAIN_LAYER`?
```suggestion
            object.groundLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNMUL2, 239U, fheroes2::Point{ 1, 0 }, MP2::OBJ_NONE, Maps::TERRAIN_LAYER );
```

2024-12-25 17:35 UTC, Districh-ru commented on src/fheroes2/maps/map_object_info.cpp
> +                                                  Maps::BACKGROUND_LAYER );
The same comment:
```suggestion
            object.groundLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNMUL2, 237U, fheroes2::Point{ 1, 0 }, MP2::OBJ_NONE, Maps::TERRAIN_LAYER );
```

2024-12-27 11:46 UTC, ihhub commented on src/fheroes2/maps/map_object_info.cpp
> +                                                  Maps::BACKGROUND_LAYER );
Hi @Districh-ru , it is intentional and also an action object cannot have terrain layer parts. An assertion at line 4955 (`assert( info.objectType == MP2::OBJ_NONE );`) will blow up because of this.

2024-12-27 17:30 UTC, Districh-ru commented on src/fheroes2/maps/map_object_info.cpp
> +                                                  Maps::BACKGROUND_LAYER );
Hi, @ihhub this assertion blows up if the `TERRAIN_LAYER` object part is not `MP2::OBJ_NONE`. So this change will not break the assertion:
![изображение](https://github.com/user-attachments/assets/1354aa2e-4f3c-4f7a-bae9-971c4abde6db)

IMHO the current passablilty is strange - the pile does not block the vertical movement, it can block the horizontal movement from the center to the right tile. But it is mine POV. :)

@Branikolog, @oleg-derevenetz and @zenseii, what do you think about these towers passability?
Should it be like for all other towers? Or the vertical movement at the right part of the tower should be blocked if there is a snow/sand pile part in the lower tile?

2024-12-27 17:34 UTC, oleg-derevenetz commented on src/fheroes2/maps/map_object_info.cpp
> +                                                  Maps::BACKGROUND_LAYER );
I really don't think that the same object should have different passability on different terrains.

2024-12-28 02:50 UTC, ihhub commented on src/fheroes2/maps/map_object_info.cpp
> +                                                  Maps::BACKGROUND_LAYER );
Hi @Districh-ru and @oleg-derevenetz , I've changed the logic to match the original tower passability.

2024-12-28 03:02 UTC, Districh-ru approved these changes

2024-12-28 03:22 UTC, merged