Show Monster and Artifact names in the popup dialog of the Editor
ihhub/fheroes2 pull request #9380
Opened 2024-12-25 10:25 UTC by ihhub

2024-12-25 12:20 UTC, oleg-derevenetz approved these changes

2024-12-25 17:47 UTC, Districh-ru requested changes
Hi, @ihhub, I left two similar comments regarding the information of the object info text. Could you please check them when you have time?

2024-12-25 17:47 UTC, Districh-ru commented on src/fheroes2/editor/editor_object_popup_window.cpp
> +                    return MP2::StringObject( MP2::OBJ_ARTIFACT ) + std::string( " - " ) + Artifact( static_cast<int32_t>( info.metadata[0] ) ).GetName();
How about printing the name of the Artifact on the next line?
![изображение](https://github.com/user-attachments/assets/db9b4001-ec7d-4221-83de-e52ab6cbedb9)
For the long-named artifacts it looks not good when the part of it's name is moved to the next line:
![изображение](https://github.com/user-attachments/assets/7e80aa29-760b-4aab-992b-151738693d70)

```suggestion
                    return MP2::StringObject( MP2::OBJ_ARTIFACT ) + std::string( "\n" ) + Artifact( static_cast<int32_t>( info.metadata[0] ) ).GetName();
```

2024-12-25 17:47 UTC, Districh-ru commented on src/fheroes2/editor/editor_object_popup_window.cpp
> +                    return MP2::StringObject( MP2::OBJ_MONSTER ) + std::string( " - " ) + Monster( static_cast<int32_t>( info.metadata[0] ) ).GetMultiName();
The same comment - a suggestion to print this way: 
![изображение](https://github.com/user-attachments/assets/793919a2-9c5a-4a63-a019-cd6ab00a4066)

```suggestion
                    return MP2::StringObject( MP2::OBJ_MONSTER ) + std::string( "\n" ) + Monster( static_cast<int32_t>( info.metadata[0] ) ).GetMultiName();
```

Currently it is:
![изображение](https://github.com/user-attachments/assets/9c68382b-99de-4273-91a0-83ac411a7afa)

2024-12-26 01:02 UTC, ihhub commented on src/fheroes2/editor/editor_object_popup_window.cpp
> +                    return MP2::StringObject( MP2::OBJ_ARTIFACT ) + std::string( " - " ) + Artifact( static_cast<int32_t>( info.metadata[0] ) ).GetName();
Hi @Districh-ru , I followed random artifacts and monsters naming. For example, Random Monster - weak. I also need to check whether the window has enough space for this idea.

2024-12-27 17:13 UTC, Districh-ru approved these changes

2024-12-28 02:44 UTC, merged