Modified Button Layout to be similar to OG
ihhub/fheroes2 pull request #9385
Opened 2024-12-25 23:33 UTC by felix642

Relates to: #1355 

The button layout has been changed for the button groups (YES/NO, OKAY/CANCEL)
The buttons are now closer to the center and some padding was added on each side. 

![Screenshot from 2024-12-25 17-50-37](https://github.com/user-attachments/assets/d5afbb0c-be0a-4c3e-9829-c1e048bde3d8)
![Screenshot from 2024-12-25 17-54-00](https://github.com/user-attachments/assets/f4854c6a-b8ef-4689-ad77-75dd2d42f72b)
![Screenshot from 2024-12-25 17-54-14](https://github.com/user-attachments/assets/d3057b7e-5932-4f09-9c65-c09de2bb3fc5)
![Screenshot from 2024-12-25 17-56-47](https://github.com/user-attachments/assets/b1bbbdf6-13c7-44b1-87ee-c0d4ffd16b25)
![Screenshot from 2024-12-25 17-59-52](https://github.com/user-attachments/assets/123bb5f2-b9ed-4edd-b7c8-e5faf4af125a)
![Screenshot from 2024-12-25 18-00-24](https://github.com/user-attachments/assets/8c5345b3-4c18-419a-9047-c5d5f692d55e)
![Screenshot from 2024-12-25 17-57-33](https://github.com/user-attachments/assets/50d3315d-d322-42e1-b104-f193e8e13b29)

Some layouts were not changed since they are already similar to the original game:

![Screenshot from 2024-12-25 17-56-02](https://github.com/user-attachments/assets/f88dfc6d-aedd-4005-a276-bff1f0fb228a)
 ![Screenshot from 2024-12-25 17-50-25](https://github.com/user-attachments/assets/ca6de3a2-f84e-4f56-8368-7a6b17807e5d)

This one I'm not sure if we should update the position or not. It is already similar to the recruitment dialog so we might want to keep it as it.
![Screenshot from 2024-12-25 18-00-08](https://github.com/user-attachments/assets/3b04a437-e4d2-478a-ae63-f09c2eb520ad)

2024-12-26 08:34 UTC, Districh-ru requested changes
Hi, @felix642, I left two code style related comments.
Could you please take a look when you have time.

2024-12-26 08:34 UTC, Districh-ru commented on src/fheroes2/gui/ui_button.cpp
> +        } break;
Could you please move `break;` to the next line:
```suggestion
        }
        break;
```

2024-12-26 08:34 UTC, Districh-ru commented on src/fheroes2/gui/ui_button.cpp
> +        } break;
Could you please move `break;` to the next line:
```suggestion
        }
        break;
```

2024-12-26 13:58 UTC, felix642 commented on src/fheroes2/gui/ui_button.cpp
> +        } break;
Hello @Districh-ru, thank you for the review.
This is what I had done initially but this was flagged by clang-format so I had to change it. 
https://github.com/ihhub/fheroes2/actions/runs/12497443035/job/34870080287
https://github.com/ihhub/fheroes2/pull/9385/commits/fb583c0aeea7dd9e1ec1c4405dab5125a56aeaa7

2024-12-26 14:18 UTC, felix642 commented
> @felix642. Thanks for improving the UI. I'm wondering, have you checked these changes with other languages, especially Spanish and German?

No, I did not realize the size of the buttons would change depending on the selected language. I just had a quick look and everything looks good IMO.
 
![image](https://github.com/user-attachments/assets/296b2f8a-8b52-4363-bb9f-d08935c63bc2)
![image](https://github.com/user-attachments/assets/e9c594cd-fc6b-42ee-85a6-6856c4a00c3d)
![image](https://github.com/user-attachments/assets/3fecb969-2a43-444e-aae1-b7ff20164385)
![image](https://github.com/user-attachments/assets/90530644-5083-4c17-a046-5a0919be8d00)

2024-12-26 15:50 UTC, Districh-ru commented on src/fheroes2/gui/ui_button.cpp
> +        } break;
Oh, you're right, @felix642!
But how about doing it another way? :)
```suggestion
            break;
        }
```

2024-12-26 17:04 UTC, Districh-ru approved these changes
👍

2024-12-27 11:48 UTC, ihhub commented
This pull request will not be merged till 1.1.5 release as it touches many in-game dialogs which we need to test.

2024-12-31 06:27 UTC, ihhub requested changes
Hi @felix642 , I left several comments here. Could you please take a look at them?

2024-12-31 06:27 UTC, ihhub commented on src/fheroes2/gui/ui_button.cpp
> +            const int32_t horizontalFreeSpace = area.width - AGG::GetICN( buttonYesIcnID, 0 ).width() - AGG::GetICN( buttonNoIcnID, 0 ).width();
Please cache `AGG::GetICN( buttonYesIcnID, 0 )` and `AGG::GetICN( buttonNoIcnID, 0 )` calls as we have the same calls in the code below.

2024-12-31 06:27 UTC, ihhub commented on src/fheroes2/gui/ui_button.cpp
> +            const int32_t horizontalFreeSpace = area.width - AGG::GetICN( buttonYesIcnID, 0 ).width() - AGG::GetICN( buttonNoIcnID, 0 ).width();
Should we add an assertion that **horizontalFreeSpace** must be always be more than 0?

2024-12-31 06:27 UTC, ihhub commented on src/fheroes2/gui/ui_button.cpp
> +            const int32_t padding = horizontalFreeSpace / 4;
The same comments as for line 429.

2025-01-04 02:56 UTC, ihhub approved these changes

2025-01-04 02:56 UTC, merged

2025-01-04 02:57 UTC, ihhub commented
@felix642 , huge thanks for these changes!