Scrollable text input
ihhub/fheroes2 pull request #9393
Opened 2024-12-30 20:24 UTC by felix642

Improved the editable text field in the save menu. When overflowing, the textbox would previously display the beginning of the text and complete with '...' for the overflowing text. The user could continue typing but would not get any feedback. With those changes the input box now scrolls when the text overflows.

[save.webm](https://github.com/user-attachments/assets/c6406c76-eb0d-48b9-b147-06156ff77a5d)

The changes were also applied to the virtual keyboard, but since this keyboard does not have any arrow key the user is not able to scroll left or right. This is still an improvement from the current implementation since the user it at least able to see what he is typing, but ideally we should also add some arrow keys or similar feature to be able to move the cursor left and right.

2024-12-31 06:44 UTC, ihhub requested changes
Hi @felix642 , I put few comments here. Would you mind to check them?

2024-12-31 06:44 UTC, ihhub commented on src/fheroes2/gui/ui_text.h
> +        TextInput( std::string text, const FontType fontType )
Try to use `using Text::Text;` instead of redeclaring the constructor.

2024-12-31 06:44 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +        const fheroes2::FontCharHandler charHandler( _fontType );
We can reduce code duplication by:
```cpp
const fheroes2::FontCharHandler charHandler( _fontType );

computeTextOffset( maxWidth );
```
and remove line 402 as it won't be needed.

2024-12-31 06:44 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +        computeTextOffset( maxWidth );
Language switcher is missing here. The code won't work for non-English characters.

2024-12-31 06:44 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +                                                          static_cast<int32_t>( _text.size() - _textOffset ), charHandler, maxWidth );
These lines are exact lines as 387-389. We could remove **computeTextOffset()** completely as just move the while loop below into the **fitToOneRow()** method.

2024-12-31 06:44 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +        }
Is it correct to say that the complexity of this loop is O(N * (N / 2)) where N is the number of characters present in the string? Is there a way to avoid recalculating all the character lengths?

2025-01-25 17:54 UTC, Districh-ru commented on src/fheroes2/gui/ui_text.cpp
> +        constexpr size_t DISTANCE_TO_SIDE = 4;
Hi, @felix642, let's name the variables according to https://github.com/ihhub/fheroes2/wiki/Code-style
And let's give it a more clear name, in example: `cursorToBorderDistance` or simply `cursorOffset`.

2025-01-28 10:25 UTC, ihhub requested changes
Hi @felix642 , I left several comments here. Could you please take a look at them?

2025-01-28 10:25 UTC, ihhub commented on src/fheroes2/gui/ui_text.h
> +        using Text::Text;
Please put this statement within `public` section.

2025-01-28 10:25 UTC, ihhub commented on src/fheroes2/gui/ui_text.h
> +        TextInput() = default;
Do we need to have this constructor if we use `using Text::Text`?

2025-01-28 10:25 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +        constexpr size_t curosorToBorderDistance = 4;
**curosor** is misspelled. Also, please declare this variable just before using it so it would be easier to identify where it is being used.

2025-01-28 10:25 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +        // If the cursor is to the left of the textBox
Let's be consistent: some comments have a full stop at the end while others don't.

2025-01-28 10:25 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +        // If the cursor is to the right of the Textbox
`TextBox` is written here while at line 391 it is `textBox`.

2025-01-28 10:25 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +        while ( _textOffset + maxCharacterCount <= _cursorPosition + curosorToBorderDistance && _textOffset + maxCharacterCount < _text.size() ) {
Could you please add parenthesis for these 2 conditions to separate them visually?

2025-01-28 10:25 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +            const int32_t nbCharactersToReplace
We do not use `nb` as abbreviation for `number` if it was the intention. If you would like to shorten the variable name you can name it as `charCountToReplace`.

2025-01-28 10:25 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +            int nbChars = 0;
We do not use `nb` as abbreviation for `number` if it was the intention. If you would like to shorten the variable name you can name it as `charCount` or `charNumber`.

2025-01-28 10:25 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +            = getLineWidth( reinterpret_cast<const uint8_t *>( _text.data() ), static_cast<int32_t>( _text.size() ), charHandler, _keepLineTrailingSpaces );
Is there a situation when we want not to keep trailing spaces? I believe for editing a string it is a must to show everything. If it is true then the code below to calculate the maximum number of characters can be reduce to just deduct a character width from the current one and do it again till we satisfy the requirements.

2025-02-08 17:27 UTC, felix642 commented on src/fheroes2/gui/ui_text.cpp
> +            = getLineWidth( reinterpret_cast<const uint8_t *>( _text.data() ), static_cast<int32_t>( _text.size() ), charHandler, _keepLineTrailingSpaces );
Hi @ihhub I'm not sure I understand properly what you're saying here. Are you referring to the fact that the current "view" is moved using the `getLineWidth()` method instead of using something like `FontCharHandler::getWidth()`?
If you could elaborate a bit more on your explanation I would greatly appreciate it.

2025-02-09 05:38 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +            = getLineWidth( reinterpret_cast<const uint8_t *>( _text.data() ), static_cast<int32_t>( _text.size() ), charHandler, _keepLineTrailingSpaces );
Answering your question in 2 parts:
- at this line we are calling `getLineWidth()` function with **_keepLineTrailingSpaces** parameter. Since `TextInput` class is designed to handle text input for users it is important to maintain whitespaces as we want to show a blinking cursor after them.
- in the code below this line we are trying to calculate a width of string iteratively excluding the last character from a string. If this is true then would it be more optimal to calculate the current width of a string and then deduct a single character's width from it?

2025-02-17 15:43 UTC, ihhub requested changes
Hi @felix642 , I put few more comments here. Can you please check them?

2025-02-17 15:43 UTC, ihhub commented on src/fheroes2/gui/ui_text.cpp
> +        ;
Please remove this line.

2025-02-22 17:14 UTC, felix642 commented on src/fheroes2/gui/ui_tool.cpp
> +    size_t getTextInputCursorPosition( const TextInput & textInput, const std::string & fullText, const size_t currentTextCursorPosition,
Not exactly, the textInput might have some ellipsis (...) at the beginning which would return an invalid offset. So we have to use the original text to get the real location of the cursor.

2025-02-22 17:16 UTC, felix642 commented on src/fheroes2/gui/ui_text.h
> +        size_t getOffset() const
This is the offset from the beginning of the text, so technically, an index offset in 1D array, do you want me to change it for something else ?

2025-02-23 13:05 UTC, ihhub commented
Hi @felix642 , can you please rebase this brach from master branch?

2025-03-21 15:04 UTC, ihhub commented
Hi @Districh-ru , could you please review this pull request again?

2025-03-21 15:05 UTC, ihhub approved these changes

2025-03-21 15:09 UTC, Districh-ru commented
> Hi @Districh-ru , could you please review this pull request again?

Hi @ihhub, sure, I'll do it a little later today.

2025-03-21 16:21 UTC, Districh-ru commented
This PR has an issue with fitting the text input field to one row:
![изображение](https://github.com/user-attachments/assets/5faf8c0a-98f1-4bea-a38d-697961d5ed8e)
![изображение](https://github.com/user-attachments/assets/45189a12-675c-491b-8c9b-87aa1421ae45)

I'm converting it to draft and will try to fix this.

2025-03-22 15:53 UTC, Districh-ru commented
Hi @felix642, thanks for fixing the width calculation!
Now it works good.

2025-03-22 15:54 UTC, Districh-ru approved these changes

2025-03-25 12:18 UTC, oleg-derevenetz approved these changes
Hi @Districh-ru I just made a few minor changes:

1. While the iterator comparison using `<` is valid in general and there are clear rules about this comparison, it may be slower than the `==` or `!=` because it implies the calculation of distance between two iterators, and this calculation may be fast or slow depending on the container. Usually it is fast for the random access containers, but I still replaced the comparison in a couple of places with `!=`;
2. We can break the iteration early in couple of places.

Please look at my changes, if everything is fine with them, then you are free to merge this PR.

P.S. Clang-Tidy suggests to replace the forward iteration by the range-based for, but I'll leave it as it is so that forward and reverse iteration match in style.

2025-03-25 15:39 UTC, Districh-ru approved these changes

2025-03-25 15:41 UTC, merged